### ISSUE TITLE
Countrywide App Installation

### ISSUE THREAD

**Issue by BYMIntegrations** [reapit/foundations#10003]
Please take a look at our FAQ's before submitting an issue, as your question may already be covered in the documentation https://foundations-documentation.reapit.cloud/faqs

**Summary**
Hello Support,

I hope you are well.

We have been asked to setup Countrywide on the Foundations API. I have been trying to get the customer to install the "BriefYourMarket Integration" app from the app marketplace but they have been unresponsive.

We need app installations for systems CWX and ABB. I have attempted to progress this through their account manager but he has been unresponsive to my emails and phone call attempts.

This is the only other option we have to progress this.

If you have any questions, then please let me know 😊

Thanks,

Toby Hunter 
Integrations and Support Analyst

0344 800 84 24 (Ext 222) | [TobyH@briefyourmarket.co.uk](mailto:TobyH@briefyourmarket.co.uk)
[www.briefyourmarket.com](http://www.briefyourmarket.com/)

**Detail and or supporting links and screenshots**

**Comment by AshDeeming** [comment]
CSM dealing directly with Client & @BYMIntegrations (Toby)
