### ISSUE TITLE
sortBy and createdFrom / modifiedFrom inconsistent

### ISSUE THREAD

**Issue by chestertons** [reapit/foundations#10009]
We're pulling down our data from the API into a local database. To run the synch, we first check our local database for the newest record, and then issue a request to the API for "records newer than"

For 20 of the 24 APIs we're using this works as expected, and 0 records are returned if none modified. However for 

- journalEntries
- tenancies
- transactions
- worksOrders

the API appears to be using a "greater than or equal" operator

example of table **working as expected**
https://platform.reapit.cloud/applicants/?sortBy=modified&modifiedFrom=2023-10-19T14:27:39Z
returns 0 records (you can find the latest modified date by running https://platform.reapit.cloud/applicants/?pageSize=1&sortBy=-modified&embed=)

example of table **not working as expected**
https://platform.reapit.cloud/journalEntries/?sortBy=created&embed=&createdFrom=2023-10-20T14:02:42Z
returns 1 record (find the latest record at https://platform.reapit.cloud/journalEntries/?pageSize=1&sortBy=-created&embed=)

Can you pls advise if this is expected behaviour?

**Specification** 
- Investigate the various services to verify the same behaviour is consistent

**Comment by chestertons** [comment]
Can I bump this please?

**Comment by HollyJoyPhillips** [comment]
@chestertons This has been reviewed and will likely be associated to an upcoming sprint

**Comment by chestertons** [comment]
Thanks Holly - does that indicate this is a bug / changes will be made? ie, "my understanding is correct and functionality will be changed at your end", or "my understanding is incorrect and functionality must be changed at my end"

**Comment by HollyJoyPhillips** [comment]
Hi @chestertons we will need to first review the various services to verify the same behaviour is consistent so, until that has been done, I can't confirm if it's a bug or not. If it is, we will of course update our services. 

This has been assigned to our next sprint which starts 30/10/23. Thanks.

**Comment by chestertons** [comment]
OK thank you


David Colvin
 Chief Data Officer

[https://cdn.chestertons.net/rps12-email-assets/logos/chestertons-flicker-hires.gif]<https://www.chestertons.co.uk/en-gb/?utm_campaign=web-and-data-uk-a&utm_content=logo&utm_medium=email&utm_source=email+signatures>

***@***.******@***.***>
Direct: +44 (0)20 3040 8710
chestertons.co.uk<https://www.chestertons.co.uk/en-gb/?utm_campaign=web-and-data-uk-a&utm_campaign=footer-text&utm_content=www.chestertons.co.uk&utm_medium=email&utm_source=email+signatures>
  196 Shaftesbury Avenue, Covent Garden, London,  WC2H 8JF


[https://cdn.chestertons.net/signatures/web-and-data-uk-a/currentCampaign.png]<https://www.chestertons.co.uk/en-gb/currentCampaign/web-and-data-uk-a/?utm_campaign=web-and-data-uk-a&utm_content=banner&utm_medium=email&utm_source=email+signatures>
[https://cdn.chestertons.net/signatures/cyber-security/currentCampaign.png]<https://www.chestertons.co.uk/en-gb/currentCampaign/cyber-security/?utm_campaign=web-and-data-uk-a&utm_content=cyber-banner&utm_medium=email&utm_source=email+signatures>

Registered office Chesterton Global Ltd, 40 Connaught Street, Hyde Park, London, W2 2AB
Registered in England Company Number 05334580

Chesterton Global Ltd - This e-mail is confidential and may contain legally privileged information; it is intended for the use of the addressee only. If you are not the addressee you must not read, use, distribute copy or rely on this e-mail. If you have received this communication in error please notify us immediately by e-mail or by telephone (+44 (0)20 3040 8240)

The contents of this e-mail do not constitute a commitment by Chesterton Global Ltd, unless separately endorsed by an authorized representative of Chesterton Global Ltd. Chesterton Global Ltd believes that this e-mail and any attachments are free of viruses. However, it is the responsibility of the recipient to ensure it is virus free and Chesterton Global Ltd does not accept any responsibility for any loss or damage that may arise from the use of this e-mail or its contents.

________________________________

**Comment by RWilcox-Reapit** [comment]
Hi David @chestertons 

Thanks for flagging the inconsistency between the API's. This was not done intentionally and I've since updated the services you've mentioned above to align with our other 'greater than' rather than 'greater than or equal to' which should solve the polling issue.

Thanks,
Ryan
