### ISSUE TITLE
Expose the Additional Services field in the marketing descriptions 

### ISSUE THREAD

**Issue by tarasparrow** [reapit/foundations#10019]
This request is for Connells/CW.

Please can we expose the "additional services" field within the marketing section on the property record. 
This will be for use for their API and also for Data Warehouse. 

I have provided a screenshot below and also attached the document which lists all of the databases.

[Countrywide Databases.xlsx](https://github.com/reapit/foundations/files/13113015/Countrywide.Databases.xlsx)

Any questions, please let me know. 

Thanks
Tara 
![CW](https://github.com/reapit/foundations/assets/58702449/43d8fff2-6af4-4c57-b2a4-e1a443fab9d7)

[Countrywide Databases.xlsx](https://github.com/reapit/foundations/files/13113018/Countrywide.Databases.xlsx)

**Comment by AshDeeming** [comment]
https://reapit.atlassian.net/browse/RSD-257773

**Comment by plittlewood-rpt** [comment]
Hi @tarasparrow based on what the service team have done to provide this functionality, there's no way this can go into the data warehouse or indeed the API. We seem to have 'repurposed' an existing field using a UI Translation to change the label of a field which has a completely different purpose

**Comment by plittlewood-rpt** [comment]
@AshDeeming  please park this - we can't proceed due to how it's being implemented.

**Comment by plittlewood-rpt** [comment]
For information, support for the standard available services mechanism is available now in the property API as part of #9722 so the customer may wish to implement this (though the data won't make sense due to my previous comments)
