### ISSUE TITLE
Issue with an appointment not showing on Agency Cloud but on API

### ISSUE THREAD

**Issue by danielalmeidaconnellsgroup** [reapit/foundations#10022]
DB: NWE
OFFICE:GOS
PROPERTY REF: GOS230009

When we made the booking, we got a 500 error but the appointment is coming back from the API but it's not showing on Agency Cloud

**Comment by danielalmeidaconnellsgroup** [comment]
@plittlewood-rpt  - As per email

**Comment by HollyJoyPhillips** [comment]
Resolved via email
