### ISSUE TITLE
Deep dive into Occupant data 

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#10034]
As specified in ticket: #9744

**Comment by RLAV1** [comment]
Hey @HollyJoyPhillips  @plittlewood-rpt  
Just a reminder if this one can be reviewed in this weeks refinement as this and the linked https://github.com/reapit/foundations/issues/9744 are causing issues for Savills 

Thank you

**Comment by HollyJoyPhillips** [comment]
Hi @RLAV1, This has already been through refinement and added to our 'Near Term' backlog.

**Comment by plittlewood-rpt** [comment]
Internal ticket logged to look at data structures and possible refactor to make this more appropriate for exposing publicly: PBI-5303
