### ISSUE TITLE
Property lettingStatus/sellingStatus filters not working reliably

### ISSUE THREAD

**Issue by pocketarc** [reapit/foundations#10031]
**Describe the bug**
We grab a list of properties filtered by lettingStatus/sellingStatus, and then look at their embedded tenancies/offers, but it seems that sometimes, data that our partners expect us to pull in, isn't being pulled in - it usually takes a few days for it to actually pull in correctly. I'm not sure if it's something wrong with the filters or perhaps the embedded tenancies/offers not coming through for some properties, for some reason, but it's been frustrating our partner, and hard for us to debug because by the time an issue is reported and we go to investigate it, the data has already come through, and we're not able to reproduce.

**To Reproduce**

1. Call /properties with embed = tenancies,offers and lettingStatus =arrangingTenancyUnavailable,arrangingTenancy

**Expected behaviour**
All properties returned will list their tenancies.

**Actual behaviour**
Some properties are missing the relevant tenancies.

**Additional context**
We've been asked to have a dev submit a GitHub issue, so doing that here. We are still trying to reproduce the issue on our side, but the fact that it starts working after a few days of not working is making it quite difficult timing-wise.

**Specification**
- Project: Reapit.Services.Properties
- Review comments below. Latest comment suggests that the sellingAndLetting filter is not working as it should. Validate this behaviour and resolve as appropriate. It's possible that the flags in the database are the wrong way round on this property (LS instead of SL or vice versa). The CRM should always store them in the same order, but we may have to work around bad data here (or just fix it)

**Comment by AshDeeming** [comment]
Hi @pocketarc 
Please could you confirm the affected app along with any further details and examples - including the request & references please

**Comment by hivetom** [comment]
Hi @AshDeeming ,

We have encountered a similar issue with live client data and have managed to replicate using the SBOX account data:

Using GET @ /properties with lettingStatus =arrangingTenancyUnavailable,arrangingTenancy for a specific office ID (for SBOX, I used MKT)
This returns properties for the office ID MKT but only properties that have an "arranging" tenancy AND a "current" tenancy. Properties that only have an "arranging" tenancy do not get returned in the response regardless of params/filters applied.

Examples: MKT210179 has an arrangingTenancy status, it does not get returned in the /properties response
MKT210175 has tenancyCurrent status, gets returned in the /properties response

We expect properties with "arrangingTenancy" status to be returned in the /properties response when we pass 'lettingStatus' param with value 'arrangingTenancy'.

Hope this helps.

**Comment by plittlewood-rpt** [comment]
Hi @hivetom we've had a look at this today based on your comment. The filters do appear to be working however I'm wondering if you're also using the marketingMode parameter in your request. The property you mention isn't being returned in your request is a dual marketed property so has a marketingMode of sellingAndLetting. The property that is being returned in your request is letting only, so has a marketingMode of letting. Could I ask you to look at this again with this in mind as we are unable to recreate the problem you have reported. The following request does indeed return both properties:

`GET https://platform.reapit.cloud/properties/?lettingStatus=arrangingTenancy&lettingStatus=tenancyCurrent`

You can limit the results if required by using the createdFrom parameters:

`GET https://platform.reapit.cloud/properties/lettingStatus=arrangingTenancy&lettingStatus=tenancyCurrent&createdFrom=2021-01-01&createdTo=2021-12-31'

Please also note that when passing multiple values in the same parameter, you need to explicit list the parameter multiple times, rather than using a comma delimited list. The Swagger pages in the Developer Portal should help you with formatting.

**Comment by plittlewood-rpt** [comment]
Hi @pocketarc we've been unable to replicate this behaviour - if there's any additional information you can give us I'd be grateful. It's worth noting that the tenancy status does not necessarily match the property status. I don't know if that's causing any confusion here. It's completely normal to have a property whose status is tenancyCurrent that also has an arranging tenancy (ie the next tenant moving in after the current one moves out)

**Comment by hivetom** [comment]
> Hi @hivetom we've had a look at this today based on your comment. The filters do appear to be working however I'm wondering if you're also using the marketingMode parameter in your request. The property you mention isn't being returned in your request is a dual marketed property so has a marketingMode of sellingAndLetting. The property that is being returned in your request is letting only, so has a marketingMode of letting. Could I ask you to look at this again with this in mind as we are unable to recreate the problem you have reported. The following request does indeed return both properties:
> 
> `GET https://platform.reapit.cloud/properties/?lettingStatus=arrangingTenancy&lettingStatus=tenancyCurrent`
> 
> You can limit the results if required by using the createdFrom parameters:
> 
> `GET https://platform.reapit.cloud/properties/lettingStatus=arrangingTenancy&lettingStatus=tenancyCurrent&createdFrom=2021-01-01&createdTo=2021-12-31`
> 
> Please also note that when passing multiple values in the same parameter, you need to explicit list the parameter multiple times, rather than using a comma delimited list. The Swagger pages in the Developer Portal should help you with formatting.

Hi @plittlewood-rpt , thanks for investigating this issue.

I have executed the following GET request using the SBOX account and cannot see the property with ID MKT210179 in the results: `https://platform.reapit.cloud/properties?pageNumber=1&pageSize=100&officeId=MKT&marketingMode=letting&marketingMode=sellingAndLetting&lettingStatus=arrangingTenancy&lettingStatus=tenancyCurrent`

MKT210175 is present in the results, however. 

If I remove the params for 'marketingMode', then yes, MKT210179 is returned in the results. But why does it not show when I specify marketingMode "sellingAndLetting" - the value that is set on that property?

**Comment by hivetom** [comment]
Hi @plittlewood-rpt @AshDeeming @cduggan-reapit ,

Further to this issue, we have been advised by clients of additional properties not being imported where an arrangingTenancy tenancy is set. We have investigated this and replicated with SBOX data as follows:

Property: MKT210309
Tenancy: MKT210158 (status: Arranging Tenancy)

Using this query, we are unable to retrieve the aforementioned property:

`properties?pageNumber=1&pageSize=100&officeId=MKT&embed=tenancies&marketingMode=letting&marketingMode=sellingAndLetting&lettingStatus=arrangingTenancy&lettingStatus=arrangingTenancyUnavailable&lettingStatus=tenancyCurrent
`

Fetching the property directly via its ID reveals:

> "marketingMode" => "letting",
> "letting" => [
>     ...
>     "status" => "arrangingTenancyUnavailable",
> ],
> ...
> "_embedded" => [
>         "tenancies" => [
>           [
>             "id" => "MKT210158",
>             "status" => "arranging",
>             ...
>             ]
>           ]
> ]

Any info you could share on this would be greatly appreciated. 

Kind regards
