### ISSUE TITLE
How to get customer details using reapit api?

### ISSUE THREAD

**Issue by au63** [reapit/foundations#10048]
I have the application.install webhook enabled and this is a snapshot of data received from the webhook:
![image](https://github.com/reapit/foundations/assets/139497587/4e098559-4d82-4882-a2ea-d9ab564d57d3)
How can I get those details like organizationId, customerId, customerEmail using reapit api?

**Comment by AshDeeming** [comment]
Hi @au63 
I believe the below may assist, but please revert if this and the subsequent pages don't help you progress;
https://foundations-documentation.reapit.cloud/troubleshooting/accessing-customer-data
