### ISSUE TITLE
Status Page

### ISSUE THREAD

**Issue by seanhinton** [reapit/foundations#10049]
There are times when I see elevated errors when using the Reapit Foundations API. I would like a Reapit Foundations API "current status" page to identify if an issue is the API being down for a short time or if there is an error in our code.

**Comment by AshDeeming** [comment]
Hi @seanhinton 
Please see & subscribe to the below;
http://status.reapit.com/

**Comment by seanhinton** [comment]
@AshDeeming Thank you very much!

I feel as though this page could have some better links to it, if you'd like to feed that back to the team who would consider that, that would be great, just to let you know my journey to putting in a question for this, I looked / tried the following things to find the Reapit status page:

- Looked for links on https://developers.reapit.cloud/apps/ and did not find link to status page
- Looked on https://www.reapit.com/foundations/ and did not find link to status page 
- Looked on https://foundations-documentation.reapit.cloud/ and did not find link to status page 
- Looked on https://github.com/reapit/foundations/ and did not find link to status page  
- Googled "Reapit Status" and "Reapit Foudations Status" and did not find link to status page

Thanks again for your help! This is super helpful cheers.

**Comment by AshDeeming** [comment]
Hi @seanhinton 
Thank you for this feedback, we will update our documentation accordingly.
