### ISSUE TITLE
Warehouse 'Standard_WH' cannot be resumed because resource monitor '(1) has exceeded its quota

### ISSUE THREAD

**Issue by tclempson** [reapit/foundations#10050]
AWS data warehouse is blocking access 

**Additional context**
![Picture221](https://github.com/reapit/foundations/assets/134079259/f05202f8-8162-4674-9f47-f57db1944184)

**Comment by plittlewood-rpt** [comment]
Hi @tclempson - this error is occurring as all the credits for the current billing period have been used. I'm discussing this internally and will come back to you ASAP

**Comment by plittlewood-rpt** [comment]
Warehouse has reset quota for the new month. Conversation continuing internally and we have also added new monitoring for an early warning for customers who are at risk of running their quota down before the end of each month.
