### ISSUE TITLE
Stuck in Sandbox mode

### ISSUE THREAD

**Issue by EN-DD** [reapit/foundations#10054]
Hi

Our developer account is in sandbox mode. Our website integration is setp and working -
We now need to connect to the live data feed for Stride & Son but we are not able to access the live data via our developer account.'

Please advise.

**Comment by AshDeeming** [comment]
Hi @EN-DD 
I can the app has been installed by the client. Please confirm the below has been reviewed:
https://foundations-documentation.reapit.cloud/app-development/website-development

**Comment by EN-DD** [comment]
Hi. The app was reviewed and accepted on Friday. I have changed the private toggle so it says it is now under revision. 

https://marketplace.reapit.cloud/apps/3ad83781-0c5a-435b-a8dc-627f23a54a95

App Status

Your app is live and private to selected customers with a pending revision under review

**Comment by EN-DD** [comment]
Under Installations I can see the live data and sandbox data. But I cant anyway to change form Sandbox to Live. 

<img width="1729" alt="Screenshot 2023-10-30 at 16 37 36" src="https://github.com/reapit/foundations/assets/8480801/a4a4e581-7b1b-4038-9211-53c17b57424c">
 Installations

**Comment by AshDeeming** [comment]
Hi @EN-DD 
The app is correctly privately listed & installed by the client.

You should now be able to pull data from that database

**Comment by EN-DD** [comment]
ok. How do I connect to the live database?

<img width="1713" alt="Screenshot 2023-10-30 at 16 56 17" src="https://github.com/reapit/foundations/assets/8480801/b3ac63e5-c8bb-48e8-acb3-a75b564d04cb">
<img width="1731" alt="Screenshot 2023-10-30 at 16 55 38" src="https://github.com/reapit/foundations/assets/8480801/fdc2a595-e255-4294-97dd-c809d377ae64">

**Comment by EN-DD** [comment]
I using the client id and secret key as above. But these connect to the sandbox data as you can see here - https://staging.strideandson.co.uk/estate-agents/sales

**Comment by AshDeeming** [comment]
please ensure you have updated the header on your request

**Comment by AshDeeming** [comment]
Hi @EN-DD 
Please can you confirm this is now resolved.

**Comment by EN-DD** [comment]
yes it has been resolved. Thanks
