### ISSUE TITLE
Lomond reporting no Michael Jones data in Data Warehouse since they migrated to Lomond environment

### ISSUE THREAD

**Issue by Steve-Clark-Reapit** [reapit/foundations#10058]
The data from the Michael Jones environment (MJO) was migrated to the Lomond environment (LOC) over the period of 19-22 October.

Since then, the FiveTran synchronisation has been switched off due to conversion team running several scripts to fix data issues. However, the FiveTran synchronisation was reactivated on the evening of 30th October, so it should have caught up.

However the client is saying their data warehouse contains no Michael Jones data

**Expected behaviour**
Client's data warehouse should contain Michael Jones data along with all other brands.

**Comment by Steve-Clark-Reapit** [comment]
Further info from Elizabeth Hamlin at Lomond pasted below

No data is coming through for MJ into the Lomond data warehouse and it should automatically.

Here are some of my reports and as you can see, Michael Jones is not there - 

![DW1](https://github.com/reapit/foundations/assets/129882073/0ed024f1-a163-4f27-a710-db7a21c723b4)

With regards to the exchanges, completions and fall throughs, below you can see all of the data that is missing and not just for MJ –
![DW2](https://github.com/reapit/foundations/assets/129882073/41ae4fd7-04fa-4b10-abe0-4696ddc9f851)

**Comment by plittlewood-rpt** [comment]
Hi @Steve-Clark-Reapit I've emailed the customer and copied you in. The data is all there from what I can tell, so looks like a report filter.

**Comment by plittlewood-rpt** [comment]
Resolved as per email threead
