### ISSUE TITLE
Product Features

### ISSUE THREAD

**Issue by LegendarySpork9** [reapit/foundations#10068]
Please take a look at our FAQ's before submitting an issue, as your question may already be covered in the documentation https://foundations-documentation.reapit.cloud/faqs

**Summary**
Is it possible to make a product's features available in the API so that we can pull the information?

**Detail and or supporting links and screenshots**

**Comment by AshDeeming** [comment]
Hi @LegendarySpork9 
Please could you provide more details around this request, i.e. what product features are you referring to?

**Comment by BYMIntegrations** [comment]
Hello Ash,

Apologies, I raised this through my personal account.

Currently, a properties features are not available in the API. We are wondering if it is possible to alter the API to expose this data.

Thanks,

Toby

**Comment by plittlewood-rpt** [comment]
HI @BYMIntegrations please can you elaborate on what you mean by "Product Features" - are you referring to a specific area in AgencyCloud? Thanks

**Comment by BYMIntegrations** [comment]
Hello Pete,

I mean the features of a property.

![image](https://github.com/reapit/foundations/assets/102583061/ced5c14b-6d2f-456a-bb0d-bba29924a4a9)

Like the attached image.

Thanks,

Toby

**Comment by plittlewood-rpt** [comment]
Hi @BYMIntegrations - if this is the field I think it is, you'll find it under `PropertyModel.summary` - if you can give me an example property and customer, I can confirm that's the field you want, but I'm 99% sure that's what you're referring to. Thanks

**Comment by BYMIntegrations** [comment]
Hello Pete,

Thanks for all the information.

This request can be closed as we have resolved this.

Thanks,

Toby
