### ISSUE TITLE
Requesting access to Featured property flag from API (Dacha - DCH)

### ISSUE THREAD

**Issue by asif-startberry** [reapit/foundations#10062]
Request
Our client wants to show the featured property in the website. The featured property flag is currently not available in the default API response. So we request you to enable the extras field for this and share the field name.

Customer Code: Dacha - DCH
Field: Featured

**Comment by AshDeeming** [comment]
Hi @asif-startberry 
Please could you confirm where/what screen the Agent flags properties as 'Featured' in AgencyCloud for this client?

**Comment by plittlewood-rpt** [comment]
Hi @asif-startberry please confirm if you still need assistance with this issue? Thanks

**Comment by plittlewood-rpt** [comment]
Thanks for coming back to us. Just reach out when you need us again.
