### ISSUE TITLE
Client MAI webhooks not firing

### ISSUE THREAD

**Issue by Speedway1** [reapit/foundations#10075]
We have enabled all but the webhooks are not firing. Please can you check.

**Comment by plittlewood-rpt** [comment]
Hi @Speedway1 - events are being captured for this customer, so please can you check your webhook configuration and that the customer concerned has your app installed?

**Comment by Speedway1** [comment]
Hi, apps are installed. We are about to test with the client again. Will revert asap.

**Comment by Speedway1** [comment]
Hi All, we have tested a few times with the client. We have templates that are triggered when the appointment is saved with All confirmed however the webhooks are not firing. The reaction on their side is that the email confirmation pop-up is correctly popping up. Would appreciate if you could have a look at an appointment created at 11:19 today under office code CHW.

**Comment by Speedway1** [comment]
Just to summarise:
1) Webhooks registered
2) Can see on Reapit portal registered
3) Customer created appt (see above)
4) No corresponding webhooks fired at us.

Probably best if we all got on a call together with the customer and diagnosed this in real time.

**Comment by MatthewGoddard** [comment]
@Speedway1  Can we get the corresponding payload via the API?

**Comment by plittlewood-rpt** [comment]
Hi @Speedway1 I have got to the bottom of this and the issue should be resolved. I can see events being fired to you now. There was configuration error in one of our data capture pipelines that prevented events from a small number of customers being processed correctly. We'll do some further investigation to see how this happened in due course to ensure it doesn't crop up again in the future. Thanks

**Comment by Speedway1** [comment]
Many thanks! I will ask the client to test.

**Comment by plittlewood-rpt** [comment]
@Speedway1 this should all be fine now but please reach out again if not. Thanks
