### ISSUE TITLE
Can't access Reapit System

### ISSUE THREAD

**Issue by anpar199** [reapit/foundations#10084]
After trying to log into with my credentials, seeing the error attached.
<img width="481" alt="Screenshot 2023-11-06 at 11 39 58" src="https://github.com/reapit/foundations/assets/150029245/1c9d9a51-ce1c-4239-a763-b3941e11fa79">

**Comment by AshDeeming** [comment]
Please could you confirm your email address @anpar199 

Feel free to send to the below inbox with the ticket ref in the subject line: sinfo@reapitfoundations.zendesk.com
