### ISSUE TITLE
Job Title is not coming in the Negotiators table - Snowflake Analytics Schema 

### ISSUE THREAD

**Issue by SairamKDXFT** [reapit/foundations#10081]
Hi Team, 

Job title is not available in the Negotiator's table in the Snowflake analytics schema 

This information assist us in generating the reports based on roles of our negotiators.
could you make this available please. 

<img width="731" alt="image" src="https://github.com/reapit/foundations/assets/145762206/420aa6a7-63ad-4f6c-8e20-e7cc15668b33">

**Comment by plittlewood-rpt** [comment]
Hi @SairamKDXFT thanks - this should be fixed shortly.

**Comment by plittlewood-rpt** [comment]
Hi @SairamKDXFT this is now resolved. Thanks

**Comment by SairamKDXFT** [comment]
@plittlewood-rpt we have refreshed the data share ; still we are unable to see the title's in the database  
<img width="308" alt="image" src="https://github.com/reapit/foundations/assets/145762206/a0016c83-82b1-4fa2-9151-4e34e21d52ea">

**Comment by plittlewood-rpt** [comment]
Hi - there is only one negotiator with this information set in AgencyCloud (as shown in your screenshot). Negotiators need to have this data attached to their profile to be able to see it in the warehouse

**Comment by SairamKDXFT** [comment]
are you referring to this column in Agency Cloud ?

<img width="270" alt="image" src="https://github.com/reapit/foundations/assets/145762206/c23f5593-3e17-4d42-964e-aa3b8aa90d63">

**Comment by plittlewood-rpt** [comment]
Hmm yes - can you let me know which negotiator that is? Just the id is fine - it could be version related possibly

**Comment by SairamKDXFT** [comment]
we have more than 70 + contacts setup with Job title and only 1 pulling the data ;   ex: ZGU
<img width="265" alt="image" src="https://github.com/reapit/foundations/assets/145762206/49713c0c-3af2-4a79-8a21-9e1d3bdfd658">

**Comment by plittlewood-rpt** [comment]
I see the issue - thanks - leave this with me

**Comment by plittlewood-rpt** [comment]
This is sorted now. Thanks
