### ISSUE TITLE
Maintain styling of a full-width table

### ISSUE THREAD

**Issue by alexsmith02** [reapit/foundations#10082]
While reviewing the element's documentation, I noticed that in the "Table" section, is there an option to adjust the width? 
Currently, when the width reaches a specific size, the table collapses, but we'd like to maintain the styling of a full-width table.

![image](https://github.com/reapit/foundations/assets/150021938/90c49630-8719-4542-97b2-4008c51a93b2)

![image](https://github.com/reapit/foundations/assets/150021938/a5d37972-a434-4ab4-b474-c6c1adac2bab)

Thank you,
Alex Smith (Perfect Portal)

**Comment by plittlewood-rpt** [comment]
@willmcvay Please can you provide some feedback on this? It's quite specific when it comes to responsive UI so I guess it depends on the use case here, but your view would be appreciated

**Comment by willmcvay** [comment]
@alexsmith02 Below a tablet size, the data becomes un-readable for a user in the vast majority of cases, hence collapsing and stacking the cells. Can you explain your use case and we might consider a force flag as a feature for the upcoming v4 release.

**Comment by HollyJoyPhillips** [comment]
Hi @alexsmith02, is this still an issue/requirement?

**Comment by alexsmith02** [comment]
Hi @HollyJoyPhillips, this is no longer an issue. Thank you.

**Comment by HollyJoyPhillips** [comment]
Thank you for the quick reply, I'll close the ticket.
