### ISSUE TITLE
Instructed date wrong

### ISSUE THREAD

**Issue by matt-austin-andrews** [reapit/foundations#10086]
Hi there,

I run the below query and get instructed date:
SELECT P.CODE, S.*
FROM "REAPIT"."ANALYTICS_ANE"."PROPERTY_SALES_WON_INSTRUCTIONS" AS S 
LEFT JOIN "REAPIT"."ANALYTICS_ANE"."PROPERTIES" AS P ON S.PROPERTY_ID = P.ID
WHERE P.CODE IN ('APX231029','CHS200191')
ORDER By P.CODE

![image](https://github.com/reapit/foundations/assets/88837586/e2004b04-9b95-4eda-99b2-7936231d46d1)

However, CHS200191 shouldn't appear 18/10/2023 as instructed date:
![image](https://github.com/reapit/foundations/assets/88837586/fa94b4e3-85f3-4c10-879e-99c83d891a17)

same as APX231029:
![image](https://github.com/reapit/foundations/assets/88837586/da67427a-4710-4575-8271-86df97e9d479)

From what i know, when the status changes from market appraisal to for sale - available, it will record the date as instructed date. Is there a bug for instructed date of these properties? 

many thanks,
Jessie

**Comment by plittlewood-rpt** [comment]
Hi @matt-austin-andrews please can you let me know what you think the bug is here? 

APX231029 had a status change from MA -> For Sale on both 3/3/23 and 3/10/23
CHS200191 had a status change from MA -> For Sale on both 4/8/23 and 18/1023

All these dates are reflected in your data warehouse screenshot. Thanks :)

**Comment by matt-austin-andrews** [comment]
Hi Pete,

APX231029 shows from Pre Appraisal to For Sale - Available on 03/10/2023
CHS200191 shows from Pre Appraisal to For Sale - Available on 18/10/2023

Or both market appraisals and pre appraisal reflect to MA?

**Comment by plittlewood-rpt** [comment]
Ah apologies thanks for clarifying. An instruction is any status _prior_ to For Sale, so yes, Pre Appraisal and Marketplace Appraisal would both be included here. Some agents occasionally skip the MA stage, so the analytics schema needs to account for both

**Comment by matt-austin-andrews** [comment]
Do you mean: when it's any status to For Sale - Available, it will record the date as instructed date?

**Comment by plittlewood-rpt** [comment]
Not from any status no - any status prior to For Sale in the property lifecycle (ie Sold STC to For Sale wouldn't count as an instruction, as that's a fall through. It will be Pre APpraisal -> For Sale or Market Appraisal -> For Sale in your system)

**Comment by matt-austin-andrews** [comment]
Ok, Thank you Pete. all clear.
