### ISSUE TITLE
Data Discrepancy in Offers and Sales Pipeline Fees

### ISSUE THREAD

**Issue by SairamKDXFT** [reapit/foundations#10098]
Hi Team, 

In our Snowflake database, we've noticed a discrepancy related to a specific property with the following details:
•	Property ID: 502219545217bf5d1a0358af52273ccd

The problem lies in the "property_sales_pipeline_fees" table, where the fee for this property appears to be null, while in the "Offers" table, the potential fee is reflecting. The status of the offer associated with this property is "Accepted."

can you check or guide us for the correct contact

**Specification**
- This is likely data related. Review the way this data model is built against the data in AgencyCloud for this property. If it's an isolated issue, correct the data else fix any bugs with the data model

**Comment by plittlewood-rpt** [comment]
Hi @SairamKDXFT - apologies for the time it's taken to get to this. It looks like the example provided is no longer in the pipeline as I suspect it's completed. Do you have any current examples I can look at?

**Comment by SairamKDXFT** [comment]
hi @plittlewood-rpt ,   please find the highlighted example from screen copy

<img width="871" alt="image" src="https://github.com/reapit/foundations/assets/145762206/733dbe2c-16c3-4a7d-bdd8-1ae1d4b52f59">

**Comment by plittlewood-rpt** [comment]
Thanks. I think this is to do with fee splits being configured before a final commission has been entered. In this scenario we should fall back to the calculated commission based on the offer price and selling commission (percentage) or the fixed fee amount which doesn't seem to be happening. We'll get this looked at. Thanks

**Comment by plittlewood-rpt** [comment]
Hi @SairamKDXFT I've been having another look at this and its definitely to do with fee splits being configured before the final commission has actually been entered. There's a couple of things I need to do here. The examples given are actually external fee splits from a joint agency sale. I'm planning on removing the portion of the calculated fee for external parties as those fees aren't in your own pipeline - does that sound feasible to you?

**Comment by SairamKDXFT** [comment]
@plittlewood-rpt , understood.  When we extract Sales Pipeline Deals information from _Reapit power reports_, we can see the fees associated with joint properties. However, in the Data Warehouse, the fee is coming up as null. Which revenue numbers should we consider

![image](https://github.com/reapit/foundations/assets/145762206/b4b646b4-ea02-4efc-b1c9-89b1e7e21631)

**Comment by plittlewood-rpt** [comment]
The power report is correct, the analytics schema is not calculating the fee for fee splits in a specific scenario that's all

**Comment by SairamKDXFT** [comment]
@plittlewood-rpt , we have the same Fee info in the DWH table please ?

**Comment by SairamKDXFT** [comment]
thanks @plittlewood-rpt .. will wait for the update
