### ISSUE TITLE
As a "developer", I should be directed to information if I try to access the marketplace without a client Id

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#101]
Given that I am a ‘Developer’, when I want to either login as a ‘Client’, I need to be sponsored by a client with a valid RPS desktop license. Currently, we throw a 'developer id does not exist in state error' and show a 404 message.

**Task**: 

- Do not throw or log the error in Sentry anymore. Instead, show a modal on the current page saying "You do not currently have an Agency Cloud User License so you can't visit the Reapit Marketplace, if you would like more information on Agency Cloud please visit [our public site](https://www.reapit.com/agency-cloud/). Alternatively, if you are a developer on the Reapit Platfom, one of your clients may be willing to sponsor with a paid user license."
- The footer should contain three buttons, "Home Page, Developers, and Logout" redirecting to the respective routes.

**Comment by nphivu414** [comment]
Hi @HollyJoyPhillips ,
The Home Page button will be removed from the modal as what we've discussed because it doesn't make sense here.
