### ISSUE TITLE
Possibility of pending tenancy creation behaving the same as current?

### ISSUE THREAD

**Issue by hivetom** [reapit/foundations#10102]
Please take a look at our FAQ's before submitting an issue, as your question may already be covered in the documentation https://foundations-documentation.reapit.cloud/faqs

**Summary**
Is it possible to have a pending tenancy creation behave the same way a current tenancy creation does?
E.g. when a pending tenancy is created, could it update the related property's "modifiedFrom" value?

**Detail and or supporting links and screenshots**

**Comment by AshDeeming** [comment]
Hi @hivetom 

Each Tenancy will be under its own entity/record - therefore the modified from date would be applicable to the relevant record i.e. 1 relating to current & 1 relating to pending.

**Comment by hivetom** [comment]
Hi @AshDeeming, thanks for the info. Is it possible when a user creates a pending tenancy it triggers an update on the related property's "modifiedFrom" field? 

By pending tenancy, I mean "arranging" tenancy.

Thank you.

**Comment by hivetom** [comment]
Hi @AshDeeming , sorry to chase but could we get an answer to the question please? Thank you.

**Comment by AshDeeming** [comment]
Hi @hivetom 
Apologies for missing your response

The modified from date will only be updated when that direct object is amended & saved, changes to the Tenancy will only update the Tenancy modified date & same with the property record.
