### ISSUE TITLE
Higher Concurrency Limit

### ISSUE THREAD

**Issue by byt3sage** [reapit/foundations#10104]
**Is your feature request related to a problem? Please describe.**
Hi guys! We're running into fairly large issues around your concurrent connections limits and wanted to explore the possibility of getting this upped to 10 from 5? I appreciate you're going to want some context as to understand the 'why' of this request but being honest, it's not something I can openly discuss on such a public platform, instead I think it might be good to have a call with Holly to go into this and our plans and why this is such an issue for us.

**Describe alternatives you've considered**
We could just generate more app credentials and have a few clients but that might result in potential slow downs and other unintended consequences and feels way too hacky for what we're trying to do.

**Comment by HollyJoyPhillips** [comment]
Hi @byt3sage, I've replied via email. Thanks.
