### ISSUE TITLE
Offer Accepted date incorrect in Data Warehouse

### ISSUE THREAD

**Issue by ktanalyst** [reapit/foundations#10107]
**Describe the bug**
We've found an issue where the ACCEPTED_DATE from the OFFERS view in Data Warehouse is pulling through based on the applicant rather than the specific offer. In the example (see screenshot) the applicant has submitted four separate offers; three have been rejected and one accepted, however the ACCEPTED_DATE is the same across all four offers despite three being rejected.

My theory is that the ACCEPTED_DATE for the accepted offer has replicated across the other offers submitted by that applicant. This isn't an isolated case, it is happening across the entire database.

**To Reproduce**
Steps to reproduce the behaviour eg:

`SELECT id OFFER_ID
,applicant_id
,created_date
,accepted_date
,status
FROM OFFERS
WHERE applicant_id = '1a7d446c70e2d679357cb3d828164bb3'`

**Expected behaviour**
The ACCEPTED_DATE in the OFFERS view should only report a date if that specific offer has been accepted, rather than replicating dates across other offers made by the applicant.

**Screenshots**
![image](https://github.com/reapit/foundations/assets/143076147/08271812-d8ba-4744-b8e3-ee2922a116f8)

**Device (please complete the following information for web issues):**
 - Device: PC

**Additional context**

**Specificiation**
- Project: Analytics SChema
- Check example above. It could just be here that we need to ensure the accepted date isn't populate for non accepted offers as this doesn't make sense. We should validate however that the date on the accepted offer is correct. This happens because there is no direct link between a journal entry (where the dates come from) and an offer, you have to go via the applicant/property looking at the offer dates and amounts to try and marry everything up. There may be situations where this is not working correctly.

**Comment by plittlewood-rpt** [comment]
Hi @ktanalyst this has now been resolved.

**Comment by ktanalyst** [comment]
Great news, thanks for sorting.

**Comment by ktanalyst** [comment]
Hi @plittlewood-rpt , there seems to be an issue since the ticket was completed. Any offer with a status of 'Fallthrough' no longer has an accepted date against the record. This is still valuable information as it allows us to calculate the time between an offer being accepted and subsequently falling through - we also have code which relies on there being an accepted date which has now been lost.

Please can data in this field be restored? Thanks

**Comment by ktanalyst** [comment]
Hi @plittlewood-rpt , please can I get your thoughts on this? I go on annual leave tomorrow and need to update the directors as our figures aren't pulling through correctly.
Thanks

**Comment by plittlewood-rpt** [comment]
Hi @ktanalyst apologies this was on my to do list for today. The easiest thing to do right now is revert the change that was made. Your point is valid and an accepted offer that subsequently fell through should retain the original accepted date. I think this was the original intention but I need to just look at the history of that table.

**Comment by plittlewood-rpt** [comment]
Hi @ktanalyst this should be resolved in the next schema refresh. The offer accepted date will be retained for accepted offers and also offers that fell through.

**Comment by ktanalyst** [comment]
Thanks @plittlewood-rpt, that looks much better now

**Comment by plittlewood-rpt** [comment]
Great stuff thanks for confirming.
