### ISSUE TITLE
App revision/submission - decline notes to be included in email body

### ISSUE THREAD

**Issue by AshDeeming** [reapit/foundations#10126]
**Background context or User story:**

When an app/integration is declined via the Admin portal, an email goes out to advise such. 
Currently the reason for the decline does not appear to be included in the email however this would be add value to the email being issued. 

**Specification or Acceptance Criteria:**
Include the decline reason within the main section of the decline email to 3rd party. 

- Project: Marketplace
- Add `bool includeReasonInEmail` property to `RejectRevisionModel` (default false)
- Update email template Marketplace_AppRevisionRejection to take an optional property for the rejection reason which is provided if includeReasonInEmail is set to true. See [this documentation](https://docs.aws.amazon.com/ses/latest/dg/send-personalized-email-advanced.html#send-personalized-email-advanced-conditionals) for information on conditional SES template content
- @HollyJoyPhillips to log F/E ticket that can be done after this item

**Comment by plittlewood-rpt** [comment]
HP to discuss with AD
