### ISSUE TITLE
Foundations feed to DNG.ie and Myhome.,ie

### ISSUE THREAD

**Issue by ultanwhelan** [reapit/foundations#10125]
**Describe the bug**
No foundations feed working to DNG.ie or Myhome.ie- I there and issue at the moment?

**To Reproduce**
Steps to reproduce the behaviour eg:

**Expected behaviour**

**Screenshots**
If applicable, add screenshots to help explain your problem. Please ensure that screenshots do not include sensitive data such as personally identifiable information. If you do have private or sensitive information you need to share that will help with aiding resolution of this issue, please email sinfo@reapitfoundations.zendesk.com adding the issue number as the subject line. Please only use this mailbox to share information you cannot add to this issue.

**Device (please complete the following information for web issues):**
 - Device: [e.g. iPhone6, PC, Mac]
 - Browser [e.g. Chrome, Safari]

**Additional context**

**Comment by AshDeeming** [comment]
Hi @ultanwhelan 
Please could you provide more information.

Are the two app's for these 3rd parties installed/enabled for the client?

**Comment by AshDeeming** [comment]
Thanks @ultanwhelan 

Do you have an example property ref i can check please?
