### ISSUE TITLE
Expose selected Nominal Code in GET Company 

### ISSUE THREAD

**Issue by CHINTHAKAJRC** [reapit/foundations#10133]
We need to identify the Nominal Code assigned to a Company. Currently this is not available in the API.

![image001](https://github.com/reapit/foundations/assets/125424669/0a3705df-4a06-431a-8233-459a8f46cab5)

Can you expose this field in the following Endpoints.

GET /Companies/
GET /Companies/{id}

Note : This is required for Savills

**Specification**
- Project: Reapit.Services.Companies
- Add new `CompanyPaymentsModel` to `CompanyModel`  as `payments` that looks as follows:

```
{
   "accountId": ""
}
```

- Using an object leaves this open to extension later
- accountId to expose `cnt.cntExtra.cmpNominalCode` value
- Add `account` to `_links`  collection that navigates to `/transactions/nominalAccounts/{accountId}` when accountId is populated with a value

**Comment by HollyJoyPhillips** [comment]
Internal: Requested information from the Foundations team

**Comment by HollyJoyPhillips** [comment]
Foundations approved for 'read only' - need to discuss field or object requirement
