### ISSUE TITLE
Add Sales Progressor / Sales Administrator to Analytics Schema

### ISSUE THREAD

**Issue by ktanalyst** [reapit/foundations#10136]
A new field, "Sales Progressor", has been added to the property relationships section of Agency Cloud in the latest release. Please can the Sales Progressor ID be added to the PROPERTIES view in the Analytics schema so we can report on this field in Data Warehouse?

**Specification**
- Project; Analytics Schema
- Add new SALES_PROGRESSOR_NEGOTIATOR_ID column to PROPERTIES model that surfaces the composite negotiator id key when there is a lookup of the relevant type in the AC database. Ensure field is null when there is no lookup in `prpneg` table (prpneg.type = 'psp')
- Add new SALES_ADMINISTRATOR_NEGOTIATOR_ID column to PROPERTIES model that surfaces the composite negotiator id key when there is a lookup of the relevant type in the AC database. Ensure field is null when there is no lookup in `prpneg` table (prpneg.type = 'spa')
- PL to update documentation once new fields are added

**Comment by AshDeeming** [comment]
![image](https://github.com/reapit/foundations/assets/61687775/8b709ab3-fca9-4cce-9347-16c0d7990003)

**Comment by ktanalyst** [comment]
Hi @plittlewood-rpt , is this something which could make it into the next sprint? It would be very helpful if this field was available for the start of 2024. 

There is also a new field - additional negotiator - being added in the 12.175 Reapit release. Is there a plan for this to also be added into data warehouse?

Thanks

**Comment by plittlewood-rpt** [comment]
Hi @ktanalyst there is some prerequisite work that needs to happen before we can action this in the analytics schema in that all customers need to have been upgraded to the new database schema first. Once that's been done this work can be scheduled

**Comment by ktanalyst** [comment]
> Hi @ktanalyst there is some prerequisite work that needs to happen before we can action this in the analytics schema in that all customers need to have been upgraded to the new database schema first. Once that's been done this work can be scheduled

Hi Pete, is this in reference to the Sales Progressor field, or the new additional negotiator field? Or both? 

Just so I can report back on progress. Cheers

**Comment by plittlewood-rpt** [comment]
Hi @ktanalyst they are both dependant on the same piece of work. Thanks

**Comment by ktanalyst** [comment]
@plittlewood-rpt can the tenancy manager field also be scheduled in here? 

This would belong to the TENANCIES view:

![image](https://github.com/reapit/foundations/assets/143076147/d669ac0d-10e6-4e18-84e5-ca1924a5d4e0)

**Comment by plittlewood-rpt** [comment]
Hi @ktanalyst  please can I ask you to log a separate item for the tenancy manager as the work on this ticket has actually been completed we're just waiting for some database schema changes ot be rolled out to some of our customers so it can be merged. Many thanks

**Comment by plittlewood-rpt** [comment]
HI @ktanalyst this work has now been merged. Documentation should update shortly and you'll need to use the Refresh Share option in the Data Marketplace app to update your schema. The two new fields are in the PROPERTIES view. Thanks!
