### ISSUE TITLE
enquiries API

### ISSUE THREAD

**Issue by chestertons** [reapit/foundations#10130]
Our enquiries API is not loading; 

https://platform.reapit.cloud/enquiries/?PageNumber=1&PageSize=100&sortBy=modified&modifiedFrom=2023-11-12T12%3A26%3A32Z

Even if I set the curl timeout to 30 seconds, request times out with no response

**Specification**
- Project: Reapit.Services.Enquiries
- Update repository methods to force database to ignore synchdel index as it's causing a table scan in large databases and rows are rarely soft deleted in this table
- We can also force the use of the amend index by adding an upper range to the query. Speak to PL for details

**Comment by plittlewood-rpt** [comment]
Hi @chestertons this is likely due an index that had not been applied to your database due to not being part of the standard index group. This has now been applied. Please can you rerun your query and let me know if this resolves the problem. You will likely also find you get better performance if you don't order your results by modified (given you're querying based on the modified date you can likely live without sorting by the same field). Hope this helps

**Comment by plittlewood-rpt** [comment]
We have run some more tests on this API and identified some areas where we may be able to improve the performance further. The spec on the ticket has been updated and will be implemented in due course

**Comment by chestertons** [comment]
Please may I have an update on this ticket?

**Comment by plittlewood-rpt** [comment]
Hi @chestertons sorry for the delay coming back to you on this. I've had a look at the parameters your are using to make your request and it looks like you're trying to read every single enquiry, and likely wanting to fetch all your enquiry data from the earliest resource in your database. You're subsequently running into a similar problem to some of our other partners who are working with our enterprise customers with very large databases.

For reference, there are around 1.36 million enquiries in your system in total dating back to September 2013. I'd question whether you really need all that data at all, and would recommend fine tuning your query. As with any database backed system, the bigger they get the more you need to be careful how you query the data. You will likely find you have more success pulling a month at a time for your initial data fetch, if you do really need all that data.

For example:
GET /enquiries/?pageNumber=1&pageSize=100&sortBy=created&createdFrom=2013-09-01&createdTo=2013-10-01
Page through results then
GET /enquiries/?pageNumber=1&pageSize=100&sortBy=created&createdFrom=2013-10-01&createdTo=2013-11-01
Page through results then
GET /enquiries/?pageNumber=1&pageSize=100&sortBy=created&createdFrom=2013-11-01&createdTo=2013-12-01

and so on. Querying the data in this manner allows the database to pick the best indexes for querying such a large dataset.

I've run some tests and the API performs as I'd expect following the example above.

I'd be grateful if you could review and come back to me. Thanks

**Comment by chestertons** [comment]
Thanks - got it.
