### ISSUE TITLE
Buying Reason

### ISSUE THREAD

**Issue by ChazBYM** [reapit/foundations#10155]
Please take a look at our FAQ's before submitting an issue, as your question may already be covered in the documentation https://foundations-documentation.reapit.cloud/faqs

**Summary**
Hi, are you able to tell me the standard fields (standard across all customers) seen in the BuyerReason endpoint? 

**Detail and or supporting links and screenshots**

**Comment by AshDeeming** [comment]
Hi @ChazBYM 
Please note that Buying Reasons can be custom per client & you will need to call the Configuration endpoint;

![image](https://github.com/reapit/foundations/assets/61687775/7318ee80-f1af-45ba-9ef5-d78ad426f9a2)
