### ISSUE TITLE
VendorLogin - Aberdein Considine

### ISSUE THREAD

**Issue by amacdougall11** [reapit/foundations#10153]
Hello,

**Context**
As part of Equator investigating the solution for Aberdein Considine (acandco.com) - we are hoping for support with the issue below.
Kenny from Reapit advised contacting yourselves regarding this.

**Ask**
Equator developer Kieran Brawley ([Kieran.Brawley@eqtr.com](mailto:Kieran.Brawley@eqtr.com)) is requiring access tokens to help with investigative work for work on acando.com

**Details below:**
VendorLogin

{{https://platform.reapit.cloud/}}token

https://foundations-documentation.reapit.cloud/api/api-documentation#client-credentials-flow

Obtain access tokens for your application to interact with these protected endpoints.

This approach is known as the Client Credentials Flow

**Comment by AshDeeming** [comment]
Hi @amacdougall11 
The user mentioned above is already an admin user on the Developer portal & has the required access. 

Please can you clarify what you require?

**Comment by amacdougall11** [comment]
Thanks for the prompt response Ash.

Kieran has been able to obtain ac access token via the 'Authorization: Bearer <access token>' when reviewing other SOAP calls and documenting their REST endpoint (equivalent).

However, for the below, its been flagged that an access token is required:

![image](https://github.com/reapit/foundations/assets/150816359/53524692-6b1a-4b01-8fbf-dc8055e72e42)

https://foundations-documentation.reapit.cloud/api/api-documentation#client-credentials-flow

Conscious this may become a blocker in our investigations/work if we cannot interact with these protected endpoints.

Thanks,
Andy

**Comment by AshDeeming** [comment]
Hi @amacdougall11 

If I've understood correctly, you will need to create a (Client side) app:
![image](https://github.com/reapit/foundations/assets/61687775/46ddd2f2-05c9-41c9-98b0-28b5b1b34c38)
Once this app is available & installed by the relevant client, access to their data for the above will be possible.

**Comment by amacdougall11** [comment]
HI @AshDeeming 
Our senior developer at EQTR has attempted to create a new server-side app integration (name was auto generated).
It looks like we need admin permissions to obtain the client secret, something that's necessary for authenticating and making those api calls.

Image attached.
![Vendor login](https://github.com/reapit/foundations/assets/150816359/d15fbbbc-ab70-4dcc-9206-c94edef0d08b)


Thanks,
Andy

**Comment by AshDeeming** [comment]
Hi Andy, any admin user can amend the other users access via: https://developers.reapit.cloud/settings/members
