### ISSUE TITLE
Requesting access to RERA Permit data from API (Dacha - DCH)

### ISSUE THREAD

**Issue by asif-startberry** [reapit/foundations#10159]
Request
Our client wants to show the RERA Permit Number in the website. The RERA permit number data is currently not available in the default API response. So we request you to enable the extras field for this and share the field name. And I have attached a image link of a property having RERA Permit Number.

https://github.com/reapit/foundations/assets/114076270/71120dd6-d589-4bad-a452-fc66616e8480

Customer Code: Dacha - DCH
Field: RERA Permit

**Comment by AshDeeming** [comment]
HI @asif-startberry access for the field mentioned above has been set up and should become active within the next 15 minutes.

As per any other semi structured data you access it using the extrasField query string parameter eg;

DCH
Field names:
Featured -> pFeatured
GET /properties?extrasField=properties.pFeatured

**Comment by asif-startberry** [comment]
Hi @AshDeeming 

Thank you for your prompt response.

I have verified the points you mentioned:

    I am able to access the "pFeatured" field from the property API using the following endpoint:
    https://platform.reapit.cloud/properties/?id=DCH232451&extrasField=pFeatured.

    However, I encountered an issue accessing the "RERA Permit Number" from the property API using the endpoint:
    https://platform.reapit.cloud/properties/?id=DCH232747&extrasField=pRERA.

Take a look into the image and provide guidance on resolving this issue.

https://github.com/reapit/foundations/assets/114076270/15a0023b-c19a-4abf-ab23-b5a71f2e838f

**Comment by AshDeeming** [comment]
Hi @asif-startberry 
Apologies that the pRERA field was missed - this has now been added too & should be accessible shortly

**Comment by asif-startberry** [comment]
HI @AshDeeming,

                    It is working now. Thank you for your support
