### ISSUE TITLE
Urgent: Need Assistance with Property Status Updates on Website

### ISSUE THREAD

**Issue by sanjayisg** [reapit/foundations#10151]
Hello,

I have a concern regarding the property status. It seems that when a property is marked as completed and subsequent changes are made in RPS, these modifications are not being reflected on our website. My assumption is that hooks are not generated for completed or archived properties.

We display sold properties as well on our website, so it's crucial that every change is accurately reflected. I would appreciate your suggestions or assistance in resolving this matter.

Thank you,

Sanjay Gupta

**Comment by AshDeeming** [comment]
Hi @sanjayisg 
Are you using standard webhooks or json event filtering?

**Comment by sanjayisg** [comment]
Hi Ash,

I am not getting your comment but this is what I have set, please check screenshot:

![Screenshot 2023-11-14 163950](https://github.com/reapit/foundations/assets/89017410/97ca18ef-7fae-41c9-a511-94537b2cea54)

Thanks,

Sanjay Gupta

**Comment by AshDeeming** [comment]
Thank you @sanjayisg 

Using the standard webhooks, these will omit properties that are not longer active/available 

Please see the doc below which relates to building webhook event filters which will allow you to control what triggers theses in more granular detail;
**https://foundations-documentation.reapit.cloud/api/webhooks#building-event-filters**

**Comment by plittlewood-rpt** [comment]
Likely related to #10110

**Comment by plittlewood-rpt** [comment]
Closing as this is the same issue as #10110 - please follow this tickets for updates

**Comment by plittlewood-rpt** [comment]
Hi @sanjayisg this should now be resolved. If you can keep an eye on things your end and report back if there are any outstanding problems I'd be grateful
