### ISSUE TITLE
Release custom mailer update

### ISSUE THREAD

**Issue by plittlewood-rpt** [reapit/foundations#10154]
**Background context**
To support brand launch in ANZ we need to release the custom mailer to this environment, but NOT to the UK

**Comment by plittlewood-rpt** [comment]
Waiting for feedback. This might be going out to both regions next week

**Comment by joshbalfour** [comment]
Been okayed to release new brand to UK so unblocked

**Comment by plittlewood-rpt** [comment]
Pencilled for Monday 11th Dec
