### ISSUE TITLE
Viewing/MP is booked to completed

### ISSUE THREAD

**Issue by SairamKDXFT** [reapit/foundations#10165]
Hi Team,

I am in the process of generating a report on the number of Valuations and Viewings booked and completed. I was wondering if there is any entry in the Agency Cloud application or Analytics schema that tracks information after the journal is created for viewing/valuation, indicating that the event has been completed.

**Specification**
- Project: Analytics Schema
- Add new string property `attendance` to APPOINTMENTS model that surfaces the `diary.attended` column as follows. It should be possible to do this with a new lookup list in project.yml

| diary.attended value  | Analytics Schema value |
| ------------- | ------------- |
| null  | Not set  |
| True  | Attended |
| False | No Show |

- Update documentation to include new field in APPOINTMENTS model with the following commentary. `Value indicating whether or not the appointment attendee was present at the appointment (Not set/Attended/No Show)`

**Comment by plittlewood-rpt** [comment]
Hi @SairamKDXFT 

Journal entries do not get created when a diary appointment is completed, however we have recently introduced an attendance flag on the diary appointment in AgencyCloud v12.171 which possibly fits the bill here. This isn't yet in the analytics schema. Can you let me know if this would suit your use case, and if so I will spec the ticket accordingly.

**Comment by SairamKDXFT** [comment]
Thank you, @plittlewood-rpt  for the information. I suggest adding attendance details to the Analytics Schema. I'll advise the team to update this field after every meeting.

Could we target having this information in the analytics schema by this week? Your support is much appreciated!

**Comment by plittlewood-rpt** [comment]
HI @SairamKDXFT this will be scheduled in line with our development processes, however I will flag the importance of the ticket with our product owner. Thaks

**Comment by SairamKDXFT** [comment]
thanks @plittlewood-rpt

**Comment by plittlewood-rpt** [comment]
Have dropped out of the current sprint as the field isn't available in all systems yet. Will be prioritised again once customer builds have caught up

**Comment by plittlewood-rpt** [comment]
Hi @SairamKDXFT this information is now available in the analytics schema as shown in the spec at the top of this item. You will need to refresh your data share through the [data warehouse app](https://data-warehouse-app.reapit.cloud/) to be able to see the field in your copy of the data.
