### ISSUE TITLE
Data Warehouse - Dashboard/Alerts 

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#10166]
**To discuss:** 
- Create dashboard in Snowflake 
- Create automated internal alerts when limit is near (90%)

**Comment by plittlewood-rpt** [comment]
@HollyJoyPhillips  I've reached out to Snowflake about this. It doesn't look it's possibly to fully automate the alerting process as email addresses have to be verified before you can setup notifications. I've got an account level notification set up which I'm hoping should breach today and we'll see the email come through, but a better solution would be to have notifications running from our customer accounts.
