### ISSUE TITLE
malformed base64 value at `FileInput` component on iOS Safari 

### ISSUE THREAD

**Issue by ss-dimasm** [reapit/foundations#10164]
**Describe the bug**
Hi we found an odd behavior of `FileInput` component (Elements 4 beta 9) on Safari browser, the encoded value got cropped/trimmed after we upload the file and follow the encoder process that has been set inside of `FileInput`. Unfortunately the received value is the malformed one.

We're trying to replicate this issue since it's a little bit of weird if the `FileReader` web API has a limit based on uploaded file image size to encode the binary image file to base64. At the end, there are two assumption from our end and it could discover the possibilities where is the bug come from.

1. the setter value (`handleSetNativeInput`)
2. the storage of encoded base64 (`ElFileInputHidden`)

We also provide a video to compare between the `FileInput` (Elements), and the `AdvancedFileInput` (our prototype to replicate this), There are two things that make it different, (1) the setter native input value and (2) the base64 value storage (we change it to be `textarea` instead `input`). [Example of code about the prototype](https://codesandbox.io/s/unruffled-leftpad-nl4xpn?file=/src/App.tsx). Thanks

**To Reproduce**
Steps to reproduce the behaviour eg:
1. Open iOS - Safari web browser
3. Go to https://nl4xpn.csb.app
4. Upload an image with more than 2.5MB size on both components
5. See the different

**Expected behaviour**
Seems we could retrieve a proper encoded base64 from the uploaded image on iOS - Safari

**Video**
https://github.com/reapit/foundations/assets/96416644/75b0f6e6-d9ca-4c18-902c-9d5d29577212

**Device (please complete the following information for web issues):**
 - OS: iOS
 - Browser Safari

**Additional context**
Previously we already raise the relevant issue, but look like it's not fixed yet (https://github.com/reapit/foundations/issues/10004)

**Comment by plittlewood-rpt** [comment]
@willmcvay would you mind just casting your eye over this one as you've done most of the work on elements v4. If you can give any pointers, we may be able to handle it this side.

**Comment by willmcvay** [comment]
It's not an issue with the file upload, rather it's a file size limit on safari rendering base64 file urls. The solution was to render a local file url blob in the preview rather than the base64. This is fixed on beta.10 and have just validated it on a real iphone mobile Safari
