### ISSUE TITLE
Licence Document Upload and Licensing Section Sync

### ISSUE THREAD

**Issue by jamesgoyuno** [reapit/foundations#10167]
**Is your feature request related to a problem? Please describe.**
When I upload a licence document, I would like this to sync to the licensing section of the app so that I do not have to enter the dates of the licence and input the licence type twice

**Describe the solution you'd like**
I would like you to sync the data fields between the licensing section and the licence document upload section so that I don't have to always deal with licence uploads twice per upload. 

This will also ensure users do not have mismatched data for the same licence

"Licensing Section"
![image](https://github.com/reapit/foundations/assets/102355892/4e90ad7b-ec72-4464-a3ce-68cf04c06c09)

"Licence Upload Section" - Licence is usually an option here
![image](https://github.com/reapit/foundations/assets/102355892/fd23c10d-4eb3-439a-b30a-355dccda5c77)

**Comment by plittlewood-rpt** [comment]
Hi @jamesgoyuno 

You can already upload documents to the Documents panel on the licensing tab by calling `POST /documents` with an `associatedType` of property, `associatedId` of the property id, and `type` of _LIC_ (this should be coming back already from `GET /configuration/documentTypes`). 

Regarding your second point, License won't be a type on the Certificates panel in all builds. To understand what certificate types are available in a build, call `GET /configuration/certificateTypes`. You can also upload your documents here too, by using the `POST /documents` endpoint, with associatedType of certificate, associatedId of the certificate id (created/retrieved through `GET/POST properties/{id}/certificates`) and the relevant document type as detailed in GET `/configuration/documentTypes`. 

Please note that the Licensing panel and Certificates panel are not connected in AgencyCloud. 

Please let me know if the above doesn't answer your question.

Thanks
