### ISSUE TITLE
ExtrasFields for a sandbox

### ISSUE THREAD

**Issue by MarcinuB** [reapit/foundations#10168]
Would you be able to enable below field for the sandbox account? 
Location

Those are a standard fields in your interface and it would be really good to have them enabled for the demos with our customers to show them the full potential of the integration

**Comment by AshDeeming** [comment]
Hi @MarcinuB access for the field mentioned above has been set up 

SBOX
Field names:
Location-> pLocation

As per any other semi structured data you access it using the extrasField query string parameter eg;
GET /properties?extrasField=properties.pLocation
