### ISSUE TITLE
How is Correspondence Address identified in the API Contact data?

### ISSUE THREAD

**Issue by nbdesignstudio** [reapit/foundations#10174]
In the Agency Cloud the users have the option of selecting a 'Different correspondence address' either via the Checkbox or dropdown options of current or after completion. But where is the value identified within the API? either at just Contact level or through Applicant or Vendor API data.

We also note that in the primaryAddress array for a Contact there is sometimes a 'type' value. Is this connected to the above? or something else?

Our question comes about, as we would like to have some logic that grabs either the Contact address or Property address based on IF this 'correspondence address' checkbox is checked or not.

![Screenshot 2023-11-17 at 15 00 copy](https://github.com/reapit/foundations/assets/24694998/94660ebd-bbee-4557-9fb5-b349d440f641)

<img width="262" alt="Screenshot 2023-11-17 at 15 32 35" src="https://github.com/reapit/foundations/assets/24694998/1a90b12e-a844-44a3-8aac-d07011f12b2a">

**Comment by plittlewood-rpt** [comment]
Hi @nbdesignstudio as per my email just for visibility for other developers, there is partial support for this feature in the vendors API. See VendorModel.correspondenceAddressType

When set to `property` it means the vendor’s address is the same as the property address, and equates to the “Current correspondence address” flag being unchecked. When set to `contact` it means the vendor’s address is different to that of the property being sold, and equates to the “Current correspondence address” flag being checked. There is currently no support for the “After completion” address, but we can look at the possibility of adding support for this if required as part of the aforementioned ticket

**Comment by nbdesignstudio** [comment]
Thank you for your response @plittlewood-rpt really appreciate it. We will discuss the options with our client, and if they wish to further develop this will get back in touch.

**Comment by nbdesignstudio** [comment]
HI @plittlewood-rpt I presume no such .correspondenceAddressType needs to exist within the Applicant API?

Due to the Client / Contact address always in theory existing, within the 'related / /primaryAddress' array for the Applicant?

**Comment by plittlewood-rpt** [comment]
Hi @nbdesignstudio that's correct. The applicant address comes explicitly from the contact address.

**Comment by nbdesignstudio** [comment]
Ok thank you for confirming.
