### ISSUE TITLE
 PDF upload to a website is not always working

### ISSUE THREAD

**Issue by MarcinuB** [reapit/foundations#10175]
We're uploading pdf brochures for our customer - Savills and those are expected to show on their website soon after publish. This is not always the case. We often get a reports from agents that the pdf brochure doesn't update at all. 

Steps: 
1. Upload pdf to Reapit through API
2. Set selling.brochureId to the uploaded documentId
3. check on a website.

Example from Today (at around 12:11):
PropertyCode: EHS230043
DocumentId: RPT23872445.
All was updated but the website (https://search.savills.com/property-detail/gbesrsehs230043) still shows previous version of the pdf.

**Comment by HollyJoyPhillips** [comment]
Hi @MarcinuB, if the correct document is being returned in the API then it's more than likely a time issue/delay with their website provider. Might be worth exploring how often their website feed occurs etc.

**Comment by MarcinuB** [comment]
ok thank you @HollyJoyPhillips. We will query that with the customer then. 

Cheers
