### ISSUE TITLE
Recent list retrieval and updating 

### ISSUE THREAD

**Issue by craigforrest** [reapit/foundations#10210]
**Is your feature request related to a problem? Please describe.**
We want to leverage Reapit's recent lists in our mobile centric apps, allowing a user to see their recently accessed records (properties, applicants, contacts and companies) and update the list when a record is opened.

**Describe the solution you'd like**
We would like the list to work similarly as it does in Reapit desktop so the recent lists match between products. So the list should be read from the user's 'neg' table entry and updated when a record is accessed, either changing the list by adding the new record's reference and removing the oldest entry (if the recent list exceeds the maximum) or reordering the list of a record further down the recent list is accessed to bring that record to the top of the recent list.

The total number of recent list entries is a configurable value in Reapit, but I believe the typical default is 10 if we need a set value.

**Describe alternatives you've considered**
This has been looked at previously but was determined that the work would be better placed with Desktop, as the app in question would be launched from within Reapit. These apps are intended to be used outside of Reapit since they are aimed at mobile/ tablet users.

**Additional context**
We want to utilise recent lists in a mobile apps where search fields are present. being able to quickly select a recently accessed record would be valuable functionality and is something that can be done in RPS Mobile, as the new mobile apps intend to replace mobile it's key that we cover as much useful RPS Mobile functionality as possible.

If writing to the recent list proves to be complex, a read only option may be sufficient at least in the short term

**Comment by plittlewood-rpt** [comment]
@PaulHaynes we need to talk about this one - can we schedule something next week?

**Comment by plittlewood-rpt** [comment]
Following previous conversations we won't pursue this. Recent lists should really be kept separate to the product consuming them otherwise it introduces a huge amount of complexity to keep them in sync during active sessions.
