### ISSUE TITLE
Remove potential code examples not currently available  

### ISSUE THREAD

**Issue by AshDeeming** [reapit/foundations#10218]
**Background context**
Expected code examples that are not available are being waited for, with no current expected delivery date. 

**Specification**

Remove the links/text relating to the examples not currently available from: https://github.com/reapit/foundations-code-examples

**Comment by plittlewood-rpt** [comment]
@HollyJoyPhillips this is done and can go to production once you're ready

**Comment by HollyJoyPhillips** [comment]
Thanks @plittlewood-rpt dev portal has been released :)
