### ISSUE TITLE
Adding 'Featured' field to data received for Grant & Co (GAC)

### ISSUE THREAD

**Issue by quigger** [reapit/foundations#10221]
**Summary**
Adding 'Featured' field to data received for Grant & Co (GAC)

**Detail and or supporting links and screenshots**
Please can we request the same for Grant & Co as per this related question: https://github.com/reapit/foundations/issues/10127

We would like access to the featured flag in pExtraFields

**Comment by AshDeeming** [comment]
Hi @quigger the access for the fields mentioned above has been set up and should become active within the next 15 minutes.

As per any other semi structured data you access it using the extrasField query string parameter eg;

GAC
Field names: Featured -> pFeatured

GET /properties?extrasField=properties.pFeatured

**Comment by quigger** [comment]
Thanks @AshDeeming 
Speedy! Ta.
