### ISSUE TITLE
Issue accessing Contact data with specific Reapit Customer code

### ISSUE THREAD

**Issue by nbdesignstudio** [reapit/foundations#10225]
Can you please help.

For the following Applicant case: RPT190742, under the ROM-GPRT code, we note there are 2 Contacts:

- RPT19001719
- LEY17004618

Can you please confirm which Leaders / Romans Reapit code, these 2 Contacts come under please. 

As there are a group of EA users is trying to refer the above Applicant case within our Smart Compliance application with these Contacts, but NONE of the Leaders / Romans ROM-XXX Codes appear to work when accessing these contacts, so our existing App setup cannot find the Contact data.

**Comment by HollyJoyPhillips** [comment]
Hi @nbdesignstudio, 

RPT19001719 is associated to office Reapit (RPT) & LEY17004618 is associated to Leyton Outlook (LEY) neither offices are part of the office group ROM-GPRT. 

Thanks
Holly

**Comment by nbdesignstudio** [comment]
Hi @HollyJoyPhillips thank you for your response on this.

As the Contacts are not linked to the client code ROM-GPRT how have these clients been created under the other codes and linked to the case. We are especially puzzled by the RPT one. But as both as not linked to the overall ROM group, how are the Agents even seeing these Contacts in the first place?

**Comment by HollyJoyPhillips** [comment]
Hi @nbdesignstudio AC security (what they can access in the CRM) can differ to the Platform Office Group security (depending on how the organisation has been setup). 
They can change the associated office or add a secondary office within that office group to resolve.

**Comment by nbdesignstudio** [comment]
Ok thank you Holly. So basically this is a configuration issue at the EA organisation about who can access / see which cases and contacts? I would have thought though as the RPT cases should only be available on the Developer accounts and not use for Live real cases? It is normal for some EA agents to assign RPT references to their cases or contacts?

**Comment by HollyJoyPhillips** [comment]
Hi @nbdesignstudio, 

"I would have thought though as the RPT cases should only be available on the Developer accounts and not use for Live real cases? It is normal for some EA agents to assign RPT references to their cases or contacts?"

Yes, it is possible for some agents to have RPT references in their live database. 

"Also, can you please confirm if either of the contacts are listed within the overall ROM group?" 

RPT and LEY are not part of an office group so access to those contact records would only be accessible via the Platform API by a user not part of an office group. Hope that helps but let me know if you need any further clarification. 
Thanks
Holly
