### ISSUE TITLE
Area API costs

### ISSUE THREAD

**Issue by Sandy-Galbraith** [reapit/foundations#10229]
I know this may sound a little odd but we've been getting huge numbers of API calls to the Areas API (As many as to our properties) though I am not sure how our previous developer implemented the API on our site.

Is there a way I can check where the Areas are being called? Or a log as part of Reapit that might shine a light on it?

**Comment by AshDeeming** [comment]
Hi @Sandy-Galbraith 
The web developer for the site will be best placed to advise what calls are being made &/or why re Areas

**Comment by AshDeeming** [comment]
Apologies for the confusion @Sandy-Galbraith 
Please see the analytics page; 

https://developers.reapit.cloud/analytics/calls 
https://developers.reapit.cloud/analytics/costs
