### ISSUE TITLE
Property checks endpoint returning blank description

### ISSUE THREAD

**Issue by david-silverink** [reapit/foundations#10236]
Any property we check using this endpoint returns a blank description, however the status, dates and type are all OK.
The name/description is visible in AC but doesn't seem to translate to the API, example below. Many thanks in advance.

```
{
                                "id": "HEO23000193",
                                "created": "2023-07-26T13:43:47Z",
                                "modified": "2023-07-26T13:43:47Z",
                                "description": "",
                                "status": "completed",
                                "type": "preInstruction",
                                "propertyId": "SUT220220",  
                                "_eTag": "\"9D80093E61A7676E3794141DB010047F\"",
                                "_links": {
                                                "self": {
                                                                "href": "/properties/SUT220220/checks/HEO23000193"
                                                },
                                                "property": {
                                                                "href": "/properties/SUT220220"
                                                }
                                },
                                "_embedded": null,
                                "metadata": {}
}
```

**Specification**
- Project: Reapit.Services.Properties
- When a check uses the default name that's configured in the src table (relationship here is tenChk.srcCode -> src.Code) we need to ensure this gets surfaced properly when tenchk.extra.Name is not set (this is only set when a user adds a custom check or explicitly overrides the default description)
- We may need to add the Source entity to this project so that we can setup the EF relationship between TenChk and Source so that we can easily access the default check description
- Outcome of this ticket should be:
  - When a check has a custom description (stored in tenChk.extra.Name) this should be surfaced in the `description` property of the model
  - When a check has a does not have a customer description, the value stored in the associated source recordshould be surfaced in the `description` property of the model

**Comment by AshDeeming** [comment]
Zendesk related ticket; 957

**Comment by awogan06** [comment]
Many thanks for update - this is a priority item for SF

**Comment by plittlewood-rpt** [comment]
Hi @david-silverink this is now resolved. Thanks
