### ISSUE TITLE
Importing properties with no status

### ISSUE THREAD

**Issue by quigger** [reapit/foundations#10238]
**Summary**
Importing properties with no status
We imported two properties that the client said we should not have done.

**Detail and or supporting links and screenshots**
We had two properties that imported even though they didn't have any selling or letting statuses.

e.g.

```
      "selling": null,
      "letting": null,
      "commercial": null,
      "regional": null,
      "type": ["house"],
      "style": ["terraced"],
      "situation": [],
      "parking": [],
      "age": [],
      "locality": [],
      "specialFeatures": [],
```

Initially the 
internetAdvertising was set to true 

we asked the client for a screenshot

![image](https://github.com/reapit/foundations/assets/644502/b9b8310f-9d4e-4490-b907-6f931dcb1ea9)

and now we find:
internetAdvertising set to false

The property is NOT importing now.

So, is it possible (and is it expected behaviour) that a listing sometimes doesn’t have a status set.

e.g.
for a data call like:

https://platform.reapit.cloud/properties?embed=images&embed=documents&embed=negotiator&fromArchive=false&internetAdvertising=true&officeId=XXX&pageNumber=2&pageSize=100&sellingStatus=forSale&sellingStatus=underOffer&sellingStatus=reserved&sellingStatus=exchanged

**Comment by plittlewood-rpt** [comment]
Hi @quigger  I've taken a look at the customer's data and it looks like this is badly converted data. There were two properties with no type set at all (it should always be sales, lettings, or both). I've corrected the data so this property should import correctly if No Internet Advertising is turned off (assuming it's ready to be marketed). Thanks
