### ISSUE TITLE
Include Journal Entries of Type = BC in GET /journalEntries/ 

### ISSUE THREAD

**Issue by MatthewGoddard** [reapit/foundations#10231]
We have been asked by clients to trigger landlord communications when a Journal Entry of type BC (Bank Detail Change) occurs.

Use the 'Type' parameter against GET /journalEntries/ to return those that equal BC

**Specification**
- Project: Reapit.Services.JournalEntries
- New endpoint GET /journalEntries/landlords
- Scoped to `journalentries.read`
- Query string parameters:
  - pageSize/pageNumber
  - landlordId[]
  - propertyId[]
  - negotiatorId[]
  - type (mandatory)
  - createdFrom/createdTo
- New enum for mapping journal entry database types to something more friendly (we'll need to have the full enum here, not just bank detail changes). Watch out for type of DC which is used for multiple purposes. Type should also offer map back to the respective table in the database (bank detail changes for landlords in jnlmisc, and so on)
- New `LandlordJournalEntryModel`

```
{
      "created": "2019-01-25T15:44:28Z",
      "propertyId": "OXF190022",
      "landlordId": "LLD240001",
      "type": "bankDetailChange",
      "negotiatorId": "JAS",
      "description": "Mr John Smith contacted us via live chat regarding 62 Test Road",
      "_links": {
        "negotiator": {
          "href": "/negotiators/JAS"
        },
        "property": {
          "href": "/properties/OXF190022"
        },
        "landlord": {
          "href": "/landlords/LLD240001"
        }
      }
    }
```

**Comment by HollyJoyPhillips** [comment]
Product meeting arranged for 22/12

**Comment by plittlewood-rpt** [comment]
There is no plan to do anything with the bank detail journal entries. As a result we should probably look at a breaking change here to force use of certain query string parameters that will allow us to more performantly (hopefully) aggregate data across tables

**Comment by plittlewood-rpt** [comment]
We need to wait on this until we've fleshed out our versioning strategy as this will be a breaking change

**Comment by plittlewood-rpt** [comment]
We may be able to address this by hitting jnlmisc AND jnl only when associatedType is landlord. It looks like there is a very limited number of landlord journal entries in the main jnl table which might mean performance is acceptable (though not ideal)

**Comment by MatthewGoddard** [comment]
Sounds positive, @plittlewood-rpt

**Comment by RWilcox-Reapit** [comment]
Hi @MatthewGoddard 

Happy to confirm this work is done now, you should have access to a new journal entries endpoint: GET /journalEntries/landlords

Any issues let me know,

Thanks

**Comment by MatthewGoddard** [comment]
Amazing - thanks Ryan!
