### ISSUE TITLE
Web feed failure

### ISSUE THREAD

**Issue by laurasomervilleadt** [reapit/foundations#10242]
Property Hive (propertyhive) - Version 2.0.2 
Property Hive Property Import Add On (propertyhive-property-import) - Version 1.3.32 
PHP 7.4

**Summary**
Having installed the Property Hive plugin, I’ve selected ‘Reapit Foundations API’ and ‘CIT’ as the ID. On attempting import, the error reads as below and ends. I have increased max_execution_time on the server from the default 30 secs to 240 secs but receive the same error. 

**Detail and or supporting links and screenshots**
The documentation you referred to appears to be written for API development only and doesn’t address Property Hive plugin (unless I’ve missed it – please advise!). 
  
11:16:53 27th November 2023 - Executed manually by bitcsam 
11:16:53 27th November 2023 - Obtaining token 
11:16:53 27th November 2023 - Parsing properties 
11:16:54 27th November 2023 - Request failed. Response: Array 
( 
    [headers] => WpOrg\Requests\Utility\CaseInsensitiveDictionary Object 
        ( 
            [data:protected] => Array 
                ( 
                    [date] => Mon, 27 Nov 2023 11:16:54 GMT 
                    [c 
  
Can you shed any light on this? Property Hive suggest that the app isn't installed in the marketplace. The screenshots suggest otherwise. 
![Screenshot(8)](https://github.com/reapit/foundations/assets/130456192/28cd4ec0-3451-4833-b442-94d93ac92bf1)
![Screenshot(7)](https://github.com/reapit/foundations/assets/130456192/b49661ca-b653-46b8-a85d-b9a9de752654)
I'm an Administrator, but don't seem to have any permissions to 'submit' anything more. Thank you.

**Comment by AshDeeming** [comment]
Hi @laurasomervilleadt 
I can see the app is listed to CIT however this has not yet been installed by them (it's currently only installed to SBOX) 
An admin user from AgencyCloud will need to install this via the AppMarket - any issues please let me know

**Comment by AshDeeming** [comment]
Thanks for the update @laurasomervilleadt 
I can see the app showing as installed by CIT today on our side. 

With regards to your account, apologies for not advising, if you are an AgencyCloud Admin user & a Developer Portal user, in order to install apps you may need to check your profile is set to Customer & not Sandbox; https://developers.reapit.cloud/settings/profile
