### ISSUE TITLE
Applicants API endpoint bug.

### ISSUE THREAD

**Issue by adamcollison85** [reapit/foundations#10252]
When querying the applicants/ endpoint, the Min/Max bedrooms is not working.

To test this request:

https://platform.reapit.cloud/applicants/?bedroomsFrom=1

and you will see the first results has 
"bedroomsMin": 4,
"bedroomsMax": 5,

Same results with 
https://platform.reapit.cloud/applicants/?bedroomsFrom=1&bedroomsTo=2

This is causing the wrong applicants to be returned. 

**Specification**
- Project: Reapit.Services.Applicants
- Review how the bedroom filtering is done in `ApplicantRepository` class. The problem could be obvious but could also be related to the fact that the room labels are customisable and AgencyCloud can be configured to store bedrooms in a different field

**Comment by adamcollison85** [comment]
Just to flag we are also having issues with the endpoint overall, looks like its timing out, just working our our dev team to provide more details.

Anything your end? have you had any errors flagged?

**Comment by cduggan-reapit** [comment]
Hi @adamcollison85 - I've been looking into this, but haven't been able to replicate the issue so far.  Were you seeing this behaviour for a particular customer?

**Comment by plittlewood-rpt** [comment]
Hi @adamcollison85 please can you let us know which customer this relates to.

**Comment by adamcollison85** [comment]
Very odd, the results are now working, not sure if it was a cache issue? Will monitor this end thanks for reviewing.
