### ISSUE TITLE
Negotiator diary colour retrieval 

### ISSUE THREAD

**Issue by craigforrest** [reapit/foundations#10258]
**Is your feature request related to a problem? Please describe.**
As part of a tsk to support multiple negotiator diaries in the Diary App we want to be able to display each negotiators AgencyCloud diary colour, we do not need to consider functionality for changing the colour at this stage.

The colour is stored in negs.settings as 'nColour'
![image](https://github.com/reapit/foundations/assets/26924168/de7f7d5c-78bb-4b4f-8b49-e93ec63f8b7a)

**Describe the solution you'd like**
The ability to retrieve the nColour associated with a neg code

**Describe alternatives you've considered**

**Additional context**

**Comment by plittlewood-rpt** [comment]
Meeting to be arranged to discuss as per note on linked ticket

**Comment by plittlewood-rpt** [comment]
HI @craigforrest did we agree that we're not going to do this?

**Comment by craigforrest** [comment]
No longer required
