### ISSUE TITLE
Wrong data returned while getting properties data with `keys` embedded

### ISSUE THREAD

**Issue by ss-dimasm** [reapit/foundations#10254]
**Describe the bug**
Found an inconsistent data between `/properties` and `/properties/{propertyId}` endpoints on embedded `keys` data. Returned data from `/properties` service could have same embedded `keys` for each properties data.

**To Reproduce**
Steps to reproduce the behaviour eg:
1. Hit the paginated version along with the query params (https://platform.reapit.cloud/properties/?embed=keys&id=MKT235084&id=MKT234872)
2. Both would have same embedded `keys` data
3. Now hit the single endpoint version with get method(https://platform.reapit.cloud/properties/MKT234872?embed=keys) 
4. At step 3, the embedded "keys" data is not available (which is the correct one)

**Expected behaviour**
The paginated version endpoint should return the proper same embedded `keys` data like the single endpoint version

**Additional context**
Sandbox data

**Project**
- Project: Reapit.Services.Properties
- Keys embedding is handled in `GetPropertiesQueryHandler` and `GetPropertyByIdQuery` - check first that the two properties above don't just have the same key data before digging too deep

**Comment by HollyJoyPhillips** [comment]
Testing notes: 

**https://platform.reapit.cloud/properties/?embed=keys&id=MKT235084&id=MKT234872**

 "keys": [
          {
            "id": "MKT23000011",
            "created": "2023-11-23T04:49:18Z",
            "modified": "2023-11-23T04:49:18Z",
            "number": "123333",
            "typeId": "MA",
            "officeId": "MKT",
            "propertyId": "MKT235084",
            "status": "checkedIn",
            "keysInSet": [
              {
                "name": "Front Door Key"
  "keys": [
          {
            "id": "MKT23000011",
            "created": "2023-11-23T04:49:18Z",
            "modified": "2023-11-23T04:49:18Z",
            "number": "123333",
            "typeId": "MA",
            "officeId": "MKT",
            "propertyId": "MKT235084",
            "status": "checkedIn",
            "keysInSet": [
              {
                "name": "Front Door Key"
              }

**https://platform.reapit.cloud/properties/?embed=keys&id=MKT235084**

  "_embedded": {
        "keys": [
          {
            "id": "MKT23000011",
            "created": "2023-11-23T04:49:18Z",
            "modified": "2023-11-23T04:49:18Z",
            "number": "123333",
            "typeId": "MA",
            "officeId": "MKT",
            "propertyId": "MKT235084",
            "status": "checkedIn",
            "keysInSet": [
              {
                "name": "Front Door Key"

**https://platform.reapit.cloud/properties/?embed=keys&id=MKT234872**

  "_embedded": {
        "keys": []


**https://platform.reapit.cloud/properties/MKT234872/keys**

{
  "_embedded": [],
  "pageNumber": 1,
  "pageSize": 25,
  "pageCount": 0,
  "totalPageCount": 0,
  "totalCount": 0,
  "_links": {
