### ISSUE TITLE
patch `internalArea.type: squareMetres` not saved properly to property endpoint

### ISSUE THREAD

**Issue by nurm717123** [reapit/foundations#10266]
**Describe the bug**
I'm wanted to update the property with `internalArea.type` included with value `squareMetres`, but the value stored become `squareFeet`.

**To Reproduce**
Steps to reproduce the behaviour eg:
1. hit https://platform.reapit.cloud/properties/FND237304 using `PATCH` method
2. include payload `internalArea: {max: 21, min: 3, type: "squareMetres"}`
3. `GET` https://platform.reapit.cloud/properties/FND237304
4. see the returned internalArea's type become `squareFeet`

**Expected behaviour**
`internalArea.type` should be updated to `squareMetres`

**Screenshots**
![image](https://github.com/reapit/foundations/assets/106480336/5b014637-f76c-4512-86dc-16932f5b9e3e)
![image](https://github.com/reapit/foundations/assets/106480336/4df21725-c05d-4a8e-8e30-2b386511ba1f)

**Specification**
- Project: Reapit.Services.Properties
- This is likely something to do with the way the default option is being handled in the build this report relates to. Review code to try track down what's going on here.

**Comment by plittlewood-rpt** [comment]
@nurm717123 Please can you let us know which customer this report is on behalf of? It's likely due to the configuration of that specific system

**Comment by nurm717123** [comment]
Hi @plittlewood-rpt , this issue just occur while development, and it's on Sandbox data/SBOX

**Comment by plittlewood-rpt** [comment]
Thanks for the info - we'll take a look as soon as we can.

**Comment by ss-dimasm** [comment]
hi @plittlewood-rpt , this is also happening when we're try to change the `externalArea.type` and seems still relate with this issue
