### ISSUE TITLE
Any progress on better reporting for multiple clients in one report?

### ISSUE THREAD

**Issue by quigger** [reapit/foundations#10279]
**Summary**
Any progress on better reporting for multiple clients in one report?

**Detail and or supporting links and screenshots**
I submitted a few tickets around reporting about one year ago.
Has any progress been made, as I don't see it in admin?

This is my main request:
https://github.com/reapit/foundations/issues/8041

and then a similar one:
https://github.com/reapit/foundations/issues/8208

I also had this error (and still do):
https://github.com/reapit/foundations/issues/8042
which I think is waiting on:
https://github.com/reapit/foundations/issues/8379

Can I have an update on all reporting please?

**Comment by AshDeeming** [comment]
Hi @quigger 
Apologies for the delay, please see the below;

#8041 - This is in our Long term -  see; https://foundations-documentation.reapit.cloud/dev-requests#columns-definitions
#8208 - Closed - relating to on-boarding clients post install. The OfficeGroups will need to be mapped & renamed if required on your side. 
#8042 > #8379 - Mid Term, please see the above link for time frames relating to this.
