### ISSUE TITLE
Document download forbidden

### ISSUE THREAD

**Issue by SirPaulO** [reapit/foundations#10318]
I uploaded two documents (PDF files) through REST API as both base64, and binary to a presigned URL.
In both cases I can get the document information through `GET /documents/:id` but get the following error message when trying to download the file through `GET /documents/:id/download`:

```json
{
    "statusCode": 403,
    "dateTime": "2023-12-04T15:32:03.7405076Z",
    "description": "The identity attached to this request does not have the required permission to access the requested data. If you think you should be able to access this data, please use the Reapit Foundations Developer Portal to contact us to discuss the problem"
}
```

_Response headers_
`Date: Mon, 04 Dec 2023 15:32:03 GMT`
`x-amzn-RequestId: b9843533-c78d-4c89-b155-d53e3a94b504`
`x-amz-apigw-id: PbKWHHHorPEEL-Q=`

**To Reproduce**
1. Upload a file through `POST /documents/` using `fileData` (base64) or `fileUrl` (presigned URL) attribute.
2. Search for the file ID using `GET /documents/` [cof* because the previous request didn't provide any ID cof*]
3. Try to download the file using `GET /documents/:id/download`

**Expected behaviour**
I expected to be able to download the file.

**Specification**
- Project:Reapit.Services.Documents
- This is unlikely to be a bug but more likely due to office group security which is explicitly applied to the download endpoint. We will need to understand which customer this relates to, and which user(s) are trying to download the asset. From memory, and this should be confirmed, we remove the download link from the links collection in the DocumentModel if the caller doesn't have access to the physical file

**Comment by HollyJoyPhillips** [comment]
Hi @SirPaulO, please could you provide the customer ID/Name?

**Comment by plittlewood-rpt** [comment]
Hi @SirPaulO can you confirm if this is still causing you a problem? It's highly likely that it was related to the office group configuration for the customer concerned. The documents API will block access to the physical file if your app does not have access to the owning resource (ie a letter attached to a property requires you to have access to the property resource for you to be allowed to download the file.

**Comment by HollyJoyPhillips** [comment]
Closing this issue as no response, please comment if it's still an issue or you have any questions. Thanks.
