### ISSUE TITLE
Elements V4: Logo click to return to 'Home' page

### ISSUE THREAD

**Issue by craigforrest** [reapit/foundations#10314]
**Is your feature request related to a problem? Please describe.**
A common feature on many websites is the ability to click the website's logo to go back to the home page.
Internal and external feedback shows that people expect this functionality to occur from the 'Reapit' logo when using a Foundations app, particularly when using a mobile device.
![image](https://github.com/reapit/foundations/assets/26924168/40209d50-82cd-4343-a119-2e9cc4c6bcdd)
On desktop the icon appears to be 'clickable' when hovered over, although this may be due to how it was implemented by the developers.

**Describe the solution you'd like**
When the 'Reapit' logo is clicked, return the user to the 'Home' page of an app

**Comment by HollyJoyPhillips** [comment]
Messaged @craigforrest
