### ISSUE TITLE
Reapit Connect - VPN

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#10320]
**Background:** We've noticed some strange behaviour with Reapit Connect which seems associated/related to the VPN. Although, unable to replicate. 

Loading: 
![image](https://github.com/reapit/foundations/assets/52408607/9fcfcc45-83a2-4c27-bc69-926f82055181)

Missing Logo: 
![image](https://github.com/reapit/foundations/assets/52408607/8a4e3c88-0a45-438b-a531-52ed56be7094)

**Comment by joshbalfour** [comment]
This might be related to @plittlewood-rpt's reports of not being able to load config.js.

![image (6)](https://github.com/reapit/foundations/assets/1060378/f764ea60-caad-4fb3-ae67-b2619b69325c)


That one should be rectified by changing the cache behaviour to remove the cookie header from the cache key.
