### ISSUE TITLE
As a Client, I should be able to configure my web component installations in the Marketplace

### ISSUE THREAD

**Issue by willmcvay** [reapit/foundations#1033]
Given that I am a ‘Negotiator’, when I install the ‘Book a Valuation/Viewings’ app/tool on my website, I should then have the option to configure how the appointments are displayed to the public 

**Summary:** As the Book a Valuation/Viewing widgets needs to be configurable for each website, we need to present the configuration options to the 'Negotiator/Office'. 

**For options see schema:** #1031

**Task:** Add a ‘Settings' header’ and 'Configuration' button on Web component apps and create a configuration modal when clicked
-	If an app has been installed and the ‘isWebComponent’ is set to ‘true’ (/apps/{id}), we should display a ‘Settings/Configuration’ button on the App when accessed through the ‘Manage’ page (https://dev.marketplace.reapit.cloud/client/manage). See mockup: 
![Config](https://user-images.githubusercontent.com/52408607/81782653-0ed41d00-94f2-11ea-9f15-326b758ab355.jpg)

- When clicked, should present the following configuration options: 
- Heading: Book a Viewing Configuration 
- Subtext for Viewing Widget: Please use the following form to configure your diary settings for your ‘Book a Viewing’ widget on your website
- Subtext for Valuation Widget: Please use the following form to configure your diary settings for your ‘Book a Valuation’ widget on your website
- Time between appointments:  15 mins, 30min, 1hr or 1hr 30mins 
Default 30 mins
- Length of Appointments: 15 mins, 30 mins, 1hr or 1hr 30mins 
Default 30 mins
- Negotiators: List all negotiators with the option to select or deselect 'Negotiators' (use https://elements.reapit.cloud/?path=/story/dropdownselect--primary)
Default all selected
- Days of the Week 
Monday, Tuesday, Wednesday, Thursday, Friday, Saturday and Sunday 
(Default all expect Sunday) 
Buttons: Close and Save Changes

See mockup: 
![ViewingConfig](https://user-images.githubusercontent.com/52408607/81782944-82762a00-94f2-11ea-908b-1f91e86b5036.jpg)

**Comment by vuhuucuong** [comment]
hi @willmcvay, I have a question, just to make sure. So we have one `web-components-config-server` and we get config by `customerId`, which mean all web components will be using the same config.
For example `search-widget`, `book-valuation`, of the same customer will have the same config, based on `customerId`.
Is that right? Correct me if I'm missing something. Thanks

**Comment by ant066** [comment]
Hi @willmcvay @HollyJoyPhillips , currently at app details, it only shows the app is a webComponent or not. I don't know the type of that app 'book viewing, book valuation, or search widget' to show the correct title, subtitle for config modal. 

```js
authFlow: "clientCredentials"
category: {id: "6", name: "Communication", description: "Messaging and communication"}
created: "2020-03-04T17:57:22"
description: "DO NOT DELETE,  DO NOT DELETE,  DO NOT DELETE,  DO NOT DELETE,  DO NOT DELETE,  DO NOT DELETE,  DO NOT DELETE,  DO NOT DELETE,  DO NOT DELETE,  DO NOT DELETE,  DO NOT DELETE,  DO NOT DELETE,  DO NOT DELETE,  DO NOT DELETE,  DO NOT DELETE,  DO NOT DELETE,  DO NOT DELETE,  DO NOT DELETE,  DO NOT DELETE,  DO NOT DELETE,  DO NOT DELETE,  DO NOT DELETE,  DO NOT DELETE,  DO NOT DELETE,  DO NOT DELETE,  DO NOT DELETE,  DO NOT DELETE,  DO NOT DELETE,  DO NOT DELETE,  DO NOT DELETE,  DO NOT DELETE,  DO NOT DELETE,  DO NOT DELETE,  DO NOT DELETE,  DO NOT DELETE,  DO NOT DELETE,  DO NOT DELETE,"
desktopIntegrationTypeIds: []
developer: "Reapit Ltd"
developerId: "47a37635-5044-4f20-b981-4f25970ac9cf"
externalId: "2pluiclhl922r6p8s5lvo893jv"
homePage: "https://reapit.com"
id: "4fbbb1e8-bad0-43a2-98f9-bfb9bba366e7"
installationId: "9c116b08-ee80-4ddf-bd5c-337f2ccac361"
installedOn: "2020-05-22T07:41:57"
isDirectApi: true
isFeatured: false
isListed: true
isSandbox: false
isWebComponent: true
launchUri: "https://reapit.com"
limitToClientIds: []
links: [{rel: "self",…}, {rel: "developer",…}, {rel: "revisions",…}, {rel: "installations",…},…]
media: [{id: "23970732-a7fe-41c7-8b15-4b8c0bd65964",…}, {id: "299ea689-2940-4335-8a13-e393319dae36",…}]
name: "Search Widget DO NOT DELETE"
pendingRevisions: false
redirectUris: []
scopes: [{name: "agencyCloud/images.read", description: "Read property images"},…]
signoutUris: []
summary: "DO NOT DELETE,  DO NOT DELETE,  DO NOT DELETE,  DO NOT DELETE,  DO NOT DELETE,  DO NOT DELETE,  DO NOT DELETE,  DO NOT DELETE,"
supportEmail: "cbryan@reapit.com"
telephone: "0777777777"
```

**Comment by ant066** [comment]
We can test with this application: https://dev.marketplace.reapit.cloud/client/apps/4fbbb1e8-bad0-43a2-98f9-bfb9bba366e7
