### ISSUE TITLE
Geo Diary should be refactored to use Apollo Client instead of Redux

### ISSUE THREAD

**Issue by willmcvay** [reapit/foundations#1037]
**Background context or User story:**

_Subject to tickets in progress at time of writing, we support the endpoints necessary to Refactor Geo Diary using Apollo Server rather than Redux. Aim is to showcase GraphQL in prod and to demonstrate reduction in codebase plus better offline support_

**Specification or Acceptance Criteria:**

- Strip out redux store and replace with Apollo Client
- Bind queries to components, remove Redux pattern
- Test as appropriate
- Should work exactly as per current dev

Note to dev: this is deliberately a large ticket. Part of the aim of the task is to demonstrate the simplification and overall code reduction afforded by using Apollo over Redux. Would be great to use the PR as a diff we can show as a showcase refactor.

**Comment by tanphamhaiduong** [comment]
https://d2hls69nl7onvi.cloudfront.net
The link for testing
