### ISSUE TITLE
Closing date for a property

### ISSUE THREAD

**Issue by TaylorMadeDigital** [reapit/foundations#10387]
**Request**

Hi, here at Savills we require the closing date field to be returned when fetching a property - I was unable to find it in the api docs. For our Scottish properties we require this to be shown to indicate when offers will be accepted until. I've attached a screenshot of where we enter the closing date within Reapit. 

![b2cbf6a3-0af4-4789-8a46-84da49c9e400](https://github.com/reapit/foundations/assets/2045175/c6455e09-c38d-4665-829b-1e72b14e2ca9)

Thanks

**Comment by AshDeeming** [comment]
Hi @TaylorMadeDigital 
Could you confirm this is for read only access only?

**Comment by TaylorMadeDigital** [comment]
Yep we just need it for read only

**Comment by TaylorMadeDigital** [comment]
Hi, we actually have a requirement us to be able to update a property with a closing date via the API for our e2e tests. Is it possible to make the closing date read/write?

**Comment by rochellelevy** [comment]
@HollyJoyPhillips can we have an eta on when this can be put into a sprint?

**Comment by AshDeeming** [comment]
Hi @TaylorMadeDigital  & @rochellelevy 

Apologies for the delay -access for the field requested above has been set up and should become active within the next 15 minutes.
SAV
pClosingDate

As per any other semi structured data you access it using the extrasField query string parameter eg;
GET /properties?extrasField=properties.pClosingDate

**Comment by rochellelevy** [comment]
thanks @AshDeeming

**Comment by AshDeeming** [comment]
> Hi, we actually have a requirement us to be able to update a property with a closing date via the API for our e2e tests. Is it possible to make the closing date read/write?

Hi @TaylorMadeDigital unfortunately this data is currently read only.

**Comment by TaylorMadeDigital** [comment]
Hi Ash, is this available on our sandbox env as well `SAU`

Currently getting a 400

**Comment by AshDeeming** [comment]
Hi @TaylorMadeDigital 
This field was added to SAV originally but added to SAU now too

**Comment by TaylorMadeDigital** [comment]
Thanks can confirm that is working
