### ISSUE TITLE
Accessing the date of withdrawal for properties

### ISSUE THREAD

**Issue by msc0000001** [reapit/foundations#10397]
I am fetching withdrawn properties via the REST API and need to see the date in which a property was withdrawn.
Could I please be advised if this data is available, and which endpoint/field this is located in?

Many thanks

**Comment by AshDeeming** [comment]
Hi @msc0000001 
Withdrawn properties are shown using the property status;
![image](https://github.com/reapit/foundations/assets/61687775/e24fbf8d-22aa-4b5c-bd2c-53ff61a22b23)

**Comment by msc0000001** [comment]
Hi Ash, thanks for your response. 
I am aware of the status field; however, I am asking if it is possible to view the date in which the property was assigned the 'withdrawn' status?

**Comment by plittlewood-rpt** [comment]
Hi @msc0000001 you would want to look in the journalEntries endpoint for this information. This endpoint will give you a chronological history of events relating to the property. In your case `GET /journalEntries?propertyId=PRP230001` will give you what you need. You may also wish to use the `typeId` parameter to further filter your results. For this scenario I think the typeId you'll need is `SX` (status to Exchanged) however you can obtain the full list from `GET /configuration/journalEntryTypes`

Thanks

**Comment by msc0000001** [comment]
Brill that's a big help thank you
