### ISSUE TITLE
Incorrect Exchange date in Data Warehouse

### ISSUE THREAD

**Issue by ktanalyst** [reapit/foundations#10398]
**Describe the bug**
We have a property which exchanged on Friday 8th December 2023 which has an EXCHANGED_DATE of 8th January 2024 in the PROPERTY_SALES_EXCHANGES view. This is a critical error for our reporting given proximity to year end - please can it be rectified ASAP?

I've attached a screenshot showing the status change dates for the property in question - I have no idea where the January 2024 date is being pulled from?

**To Reproduce**
Steps to reproduce the behaviour eg:
```
SELECT *
FROM REAPIT.ANALYTICS_KLR.PROPERTY_SALES_EXCHANGES
WHERE DATEDIFF(YEAR,EXCHANGED_DATE,CURRENT_DATE) <0
ORDER BY EXCHANGED_DATE DESC

```
**Expected behaviour**
The EXCHANGED_DATE for the property should be 8th December 2023 as per the status change.

**Screenshots**
![image](https://github.com/reapit/foundations/assets/143076147/24459c7f-2939-4e6f-89ed-f8bc308a56b5)

**Device (please complete the following information for web issues):**
 - Device: PC

**Comment by plittlewood-rpt** [comment]
HI @ktanalyst please can you confirm the property id?

**Comment by plittlewood-rpt** [comment]
@ktanalyst  I've found it don't worry. It's because that's what the date has been set to on the exchange window. The data should be corrected after which the warehouse will refresh on the next run

![image](https://github.com/reapit/foundations/assets/30798627/dde557d0-b24e-4107-8ccb-00e1f2677451)

**Comment by ktanalyst** [comment]
Thanks Pete, I assumed the date for this table would have been linked to the status change. Does this mean all exchange records are looking at the exchange date field rather than the date of the status change?

**Comment by plittlewood-rpt** [comment]
That's correct yes - it gets around uses making accidental status changes, which would further skew your figures.

**Comment by ktanalyst** [comment]
Apologies for more questions on this, but I just want to make sure I fully understand:

1. What is the trigger for a new record in the PROPERTY_SALES_EXCHANGES table, if it isn't based on a status change?
2. If the exchange price comes from the accepted offer, why is the OFFER_ID field NULL?

**Comment by plittlewood-rpt** [comment]
Hi @ktanalyst 

Both the exchanged date and exchanged price come from the Buyer & Sales details tab on the Property Offers screen. This should always match the amount of the Accepted Offer, however they are stored separately. 

There is a separate item #9893 to look into why offer ids are not being populated correctly which we'll get to as soon as we can.

Hope this helps

Thanks

**Comment by plittlewood-rpt** [comment]
Sorry I answered that query in my head and it didn't make it to my fingers! A property will appear in that view if there is an exchange date set on the Buyer & Details tab on the property Offers screen AND the property status is either Exchanged or Completed.
