### ISSUE TITLE
Update RC 1.5 UI with new brand assets

### ISSUE THREAD

**Issue by plittlewood-rpt** [reapit/foundations#10394]
**Background context**
Please update the RC 1.5 UI to match new UK production brand. Assets attached

**Specification**
[rc-rebrand-cognito.css.txt](https://github.com/reapit/foundations/files/13629072/rc-rebrand-cognito.css.txt)
![25087268-4b32-445b-8355-feb07e4b33aa](https://github.com/reapit/foundations/assets/30798627/5166ee28-cf92-401f-9dac-e51ca7a7368e)

**Comment by HollyJoyPhillips** [comment]
Marketing have approved rebrand for Reapit Connect
