### ISSUE TITLE
Demo Site Search Widget and Filtering Updates

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#1039]
**Summary:** Please see below a few issues resulting in initial testing of the Demo Site Search Widget and filtering feature 

- The Search field should have ‘e.g. London or EC1N’ as the placeholder text (this should be added to the theming file)
- The page is blue and the fields have a blue border. For this theme, it should just be vanilla grey and black by default. 
- It should be ‘Sale’ not ‘Sell’ on the toggle option and ‘Result’ line 
- The filters do not need be added to the ‘Results’ line unless something has been selected. For example, if no min or max bed, price or property type it should just display: 
63 results for london, For Sale 
- Change the results line to: 
63 Properties for Sale in London: 1-2 Bed, £300,000 - £400,000 
- Do not include ‘Order Results’ or ‘Added In’ in the results line 
- We should be able to select the same option for min and max beds. For example, searching for just one bed properties I should be able to search 1 min and 1 max. 
- The ‘Price From’ starts at £50,000 but only goes up to £300,000, should go to £2,000,000
- The ‘Price To’ starts at £300,000, should start at £50,000 (same as ‘Price From’
See below: 
Price From and To: Start at £50,000 and increment by £10,000
So £50,000, £60,000, £70,000 etc
Go up to £300,000 and from there increment by £25,000
So £300,000, £325,000, £350,000
Stop at £2,000,000
- Should prevent searching in the search field  unless something is entered in the search field. If a user tries to search without entering, we should display validation text: Please enter a town or postcode 
- Should be able to press enter after searching to activate the ‘Search Properties’ function

**Comment by HollyJoyPhillips** [comment]
Hi @trankhacvy, thanks for the update, a few things to have a look at please? 

- The Search field should have ‘e.g. London or EC1N’ as the placeholder text (this should be added to the theming file)
- The page is blue and the fields have a blue border. For this theme, it should just be vanilla grey and black by default.
- The results line should only show if a selection has been made in the ‘Advanced Search’, see example below (should not be showing no min – no max for price as it wasn’t included in the filtering
"1 Property For Sell in MK18 4PH: 4 - 4 bed, No min – No max"
- Change ‘Sell’ for ‘Sale’ in the results line 
- Price from should have a ‘No Min’ currently showing ‘No Max’ 
 
![image](https://user-images.githubusercontent.com/52408607/80962139-5d9ff980-8e04-11ea-9226-b15de6793b40.png)

**Comment by trankhacvy** [comment]
@HollyJoyPhillips for this point
> Hi @trankhacvy, thanks for the update, a few things to have a look at please?
> 
> * The page is blue and the fields have a blue border. For this theme, it should just be vanilla grey and black by default.

For now, the color of input border is different by each theme so please give me color code for each theme. We have 4 theme variants (default, variantA, variantB, variantC)
