### ISSUE TITLE
Enquiry not visible within Reapit

### ISSUE THREAD

**Issue by manishautomatic** [reapit/foundations#10407]
Using the https://platform.reapit.cloud/enquiries/ API we created an Enquiry with the email  -- shobhit.patil@commversion.com, of type - salesApplicant on 6th December 2023. 
The API returned 201 Created response.
However, the client says that are not able to view this enquiry on their end.
Could you please assist with the needful towards resolution of this problem.
Kindly let me know in case additional information is required to diagnose this.

**Comment by AshDeeming** [comment]
Hi @manishautomatic 
Please could you provide more information such as which database & the enquiry reference for review.

If sensitive, please send to: sinfo@reapitfoundations.zendesk.com

**Comment by plittlewood-rpt** [comment]
Hi @manishautomatic I think I've found this one. If it's for customer KYC, the enquiry was sent to us by your system at 12:02pm and added as a new applicant with id HBL231425 by user Aida Chekdouf  at 17:11 on the same day. After this point the enquiry won't be listed in the internet registrations panel in AgencyCloud any longer as the enquiry has been handled. The user can use the Portal Enquiries report to see which enquiries came through the system eg

![image](https://github.com/reapit/foundations/assets/30798627/3124f532-f1d9-49b6-a808-7692b13d7540)

Please let me know if you need any further help

**Comment by AshDeeming** [comment]
Additional enquiry not showing in AC however 3rd party received a successful 201 Created response

**14th December 2023--

  "enquiryType": "salesApplicant",
    "marketingConsent": "grant",
    "sourceName": "CommVersion",

"officeId": "BKS",

    "email": "shobhit.patil@commversion.com",
    "surname": "Shobhit",
    "forename": "Patil"

reapit-customer : FRC**

**Comment by plittlewood-rpt** [comment]
The enquiry above is in the FRC system, and hasn't been dealt with yet:

![image](https://github.com/reapit/foundations/assets/30798627/829157a9-d217-4820-9bff-0b9567ae927f)

**Comment by HollyJoyPhillips** [comment]
Closing as information has been provided. If any further issues please re-open.
