### ISSUE TITLE
Reapit Connect Sign in colour

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#10404]
When clicking 'sign in' the button colour _sometimes_ is incorrect (prod): 

![image](https://github.com/reapit/foundations/assets/52408607/527ee189-9676-473c-88f0-c1eae642e28f)

- Ensure button:active css is configured correctly

**Comment by plittlewood-rpt** [comment]
Hi @HollyJoyPhillips does this seem app specific? Be interested to know if you've found any pattern to this behaviour. It _might_ just be that you're getting a stale copy of the CSS

**Comment by HollyJoyPhillips** [comment]
HI @plittlewood-rpt, tested with: 

Admin Portal

https://github.com/reapit/foundations/assets/52408607/177a4264-e8e9-4871-a2fe-3da0fbb92682

DevPortal: 

https://github.com/reapit/foundations/assets/52408607/9a8d5431-2a4e-46a4-b60f-2981e1c2950c

**Comment by plittlewood-rpt** [comment]
Cannot customise active state, will need to wait for next version
