### ISSUE TITLE
Inconsistent ContactSubscriptions 

### ISSUE THREAD

**Issue by robchett** [reapit/foundations#10408]
**Describe the bug**

The `/contacts/{id}/subscriptions` and `/contacts/DUN22000778/subscriptions/{subscriptionId}` APIs are giving us different results compared to the Reapit interface

**To Reproduce**
Steps to reproduce the behaviour eg:
1. Using the customerID YOM 
2. Get API response for https://platform.reapit.cloud/contacts/DUN22000770/subscriptions/EPM
3. Compare with Mailing Subscriptions for DUN22000770
4. See that the API says "unsubscribed" to "Email Product Marketing" and that the interface has it ticked

**Expected behaviour**
`"status"` to match the tick boxes shown in the interface

**Screenshots**
![image](https://github.com/reapit/foundations/assets/5231691/5013c2a7-99a8-4a1e-a570-18e088f0d2da)

**Additional context**
We've identified the same issue across multiple accounts. It appears to be present when no `subscribedOn` is provided via the API, but that could be a coincidence. 
* DUN22000770
* DUN22000779
* DUN23000770
* DUN22000771

Toggling the subscription appears to fix the issue.

As we use these statuses to show signup status on our unsubscribe page, this is leading users to believe they have already unsubscribed from marketing and has raised the threat of ICO complaints. 

@roscoe2001

**Specification**
- Project: Reapit.Services.Contacts
- The behaviour described above is happening because the customer has the "Consent will subscribe to mailings by default" option enabled in System Configuration. This causes AgencyCloud to assume that the contact is subscribed to all mailings unless there's an explicit unsubscribe event. The API does not currently handle this setting (there is only a very small handful of companies using this setting)
- Update service to use the ConfigurationClient package to fetch that setting and update `Contact.GetSubscriptions` to take this setting into account when determining the subscriptions list. Note that this setting only auto subscribes to mailings if the contact's marketing consent is set to granted

**Comment by alxbland** [comment]
Hi,
I can see that this is now in the 'QA column' of 'Platform sprint 110', but I am unsure what this actually means. Will this move to 'done' when the sprint completes on the 12th? Is there anything we should be doing our side? 
Thanks,
Alex
