### ISSUE TITLE
Image update previews missing in Pending Revisions modal

### ISSUE THREAD

**Issue by SteveRad** [reapit/foundations#1040]
**Describe the bug**
As a Developer(?) I'm unable to see the first sequence of image previews after adding a new logo and multiple screenshots

**To Reproduce**
On the Marketplace listing page
- make some textual updates
- add a logo and 2 screenshots
- tick some permissions required 
- Submit 

**Expected behavior**
Revisions modal displays all uploaded images to validate upload succeeded

**Screenshots**
![image](https://user-images.githubusercontent.com/1046960/79915245-8a283e80-841e-11ea-9053-846dc7b11644.png)

**Device (please complete the following information for web issues):**
 - OSX/Chrome latest

**Comment by willmcvay** [comment]
Thanks for the report @SteveRad - will get someone to take a look at it
