### ISSUE TITLE
RE MIGRATION FROM RESOURCE TECHNIQUES TO HOMEFLOW

### ISSUE THREAD

**Issue by JulieEngall** [reapit/foundations#10417]
Reapit service desk have asked me to contact you regarding above.  

In order for Homeflow to process feed from Reapit Foundations they need the following;-

1.  Reapit administrator to install Homeflow property feeds app on the foundations Marketplace.
2. Customer code for our organisation - usually found in the settings section of foundations marketplace.
Look forward to hearing from you.

Julie Engall
Mills Knight

**Comment by AshDeeming** [comment]
Hi @JulieEngall 
An admin user within AgencyCloud will be best placed to install/enable a 3rd party app/integration

The code should not be required by a 3rd party as they will receive details once the app/integration is enabled.

**Comment by JulieEngall** [comment]
Hi Ash

How do I ask an admin user within AgencyCloud to install this for me?

Regards

Julie

**Comment by AshDeeming** [comment]
Hi @JulieEngall 
Please let me know your email address & i'll email you directly to advise the clients CSM or admin users.

**Comment by JulieEngall** [comment]
Hi Ash

My email is ***@***.******@***.***>.

Regards

Julie

**Comment by AshDeeming** [comment]
Thanks @JulieEngall 
Unfortunately the email is hidden - could you confirm the company name & i'll find via that instead. 
TIA

**Comment by JulieEngall** [comment]
Mills Knight

**Comment by AshDeeming** [comment]
Thanks @JulieEngall 
I've send an email to the Organisation admin (for TEAM association) to advise regarding this issue.

**Comment by JulieEngall** [comment]
Hi Ash

We are not a Team member – could you please sort this out for me today as time is running out.

Regards

Julie

**Comment by AshDeeming** [comment]
Thanks & apologies @JulieEngall 
Can I ask how/what you use to input properties etc to feed to your website?

**Comment by JulieEngall** [comment]
Via Resource Techniques.

**Comment by AshDeeming** [comment]
Thank you @JulieEngall & apologies for the confusion 

A colleague will reach out to you directly.

**Comment by JulieEngall** [comment]
Hi Ash

I have just spoken to Lianne at Resource Techniques – who said to make you aware that we upload manually direct to site.  She can help you with any queries that you have regarding migration of our site – contact ***@***.******@***.***>.

Kind Regards

Mills Knight

**Comment by JulieEngall** [comment]
Hi Ash

Have you managed to sort things out with Lianne at RT?

Regards

Julie

**Comment by AshDeeming** [comment]
Hi @JulieEngall 
I've caught up with Lianne & understand you will need to ask what she has advised to Homeflow & copy her in, not here via the Reapit Platform. 
Best regards
