### ISSUE TITLE
We are unable to fetch Name of a Company Landlord 

### ISSUE THREAD

**Issue by raymond2323** [reapit/foundations#10418]
We are being shown by clients through screenshots that they have Company landlords where they can also see the Director details in the UI, however when we fetch the landlord using the API - GET Landlord we don't get those details in the response for example see below: (tried to redact some of the sensitive info)

`{"id"=>"LEY150001", "created"=>"2015-12-15", "modified"=>"2021-03-21T18:32:29Z", "active"=>true, "solicitorId"=>nil, "officeId"=>"LEY", "source"=>nil, "related"=>[{"id"=>"LHO15001352", "name"=>"XXXXXXXXX", "title"=>nil, "forename"=>nil, "surname"=>nil, "dateOfBirth"=>nil, "type"=>"company", "homePhone"=>nil, "workPhone"=>nil, "mobilePhone"=>"XXXXXXXX", "email"=>"[XXXXXXXXXX](mailto:XXXXXXXXX)", "primaryAddress"=>{"buildingName"=>"XXXXX", "buildingNumber"=>"", "line1"=>"Park Road", "line2"=>"Adlington", "line3"=>"Chorley", "line4"=>"Lancashire", "postcode"=>"XXXXXX", "countryId"=>""}, "additionalContactDetails"=>[{"type"=>"Business", "value"=>"XXXXXX"}]}], "extrasField"=>{}, "_eTag"=>"\"85FAB562C518C3BD0DE3043680A59B55\"", "_links"=>{"self"=>{"href"=>"/landlords/LEY150001"}, "documents"=>{"href"=>"/documents/?associatedType=landlord&associatedId=LEY150001"}, "appointments"=>{"href"=>"/appointments/?attendeeType=landlord&attendeeId=LEY150001"}, "office"=>{"href"=>"/offices/LEY"}, "properties"=>{"href"=>"/properties/?landlordId=LEY150001"}, "relationships"=>{"href"=>"/landlords/LEY150001/relationships"}}, "_embedded"=>nil, "metadata"=>{}}`

In the screenshot we have been shared, the name of the Director is under a section called `Attention`

Can you advise how we would be able to get this information.

**Comment by AshDeeming** [comment]
Hi @raymond2323 

I can't locate that example on SBOX, is this a production example?

**Comment by raymond2323** [comment]
@AshDeeming It's production - Agent Customer ID is RER-GFAL

**Comment by raymond2323** [comment]
@AshDeeming ? is this a bug or we are doing something wrong?

**Comment by AshDeeming** [comment]
Hi @raymond2323 
Apologies, the labels were added to the wrong ticket. 

For contacts or Staff/Attention added to a company record, please use the /companies/{ID}/staffMembers

**Comment by raymond2323** [comment]
Thanks @AshDeeming will try this.
