### ISSUE TITLE
Online checklist validation for completion

### ISSUE THREAD

**Issue by AshDeeming** [reapit/foundations#10428]
**Describe the bug**
When using the Online Checklist app, since the UI change, once updating all 5 sections, the validation appears to not complete for the Primary & secondary ID sections, therefore max you can complete is 3 of 5 - meaning that the update status, does not allow for a 'complete' state

**To Reproduce**
Steps to reproduce the behaviour eg:
1. Go to a contact record
2. Click on identity checks
3. Populate all required fields in 5 sections (with uploads)
4. 5 of 5 should be shown & the status option opened for completed

![image](https://github.com/reapit/foundations/assets/61687775/a8217fce-fe97-4f4e-aeda-adcecdadc701)

**Comment by LauraRogers1** [comment]
Hi there, 

Please could I get an update on this ASAP? This property needs to be marketed as under offer online but I cannot do that until the identity check is completed.

Many thanks

**Comment by HollyJoyPhillips** [comment]
Hi @AshDeeming has this been resolved?

**Comment by AshDeeming** [comment]
Issue resolved & clients updated via Zendesk
