### ISSUE TITLE
Add OrgAgencyCloudID (organisation ID)  filter on /users 

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#10420]
**Summary**: To enhance the RC service app and based on feedback from other departments, it would be useful to be able to filter by organisation ID e.g. RES on the users endpoint 

**Task**: 
On the /users endpoint, add the ability to filter by organisation ID (we already have ID e.g. XXXXXXXXXXXX) but would like to search based on 3 chars. 

**Specification**
- To review frontend before making backend changes (might be better to allow loading of users from the Orgs tab which is already aware of the organisationId)
- Project: Internal user service
- Add new `orgAgencyCloudId` string property to `GetUsersQuery`
- When provided, lookup the organisation with the id specified and then return users associated to that organisation in the query

**Comment by plittlewood-rpt** [comment]
Hi @HollyJoyPhillips you can already do this (GET /users?agencyCloudId=XXX) :)

**Comment by HollyJoyPhillips** [comment]
Hi @plittlewood-rpt. So you can, thanks for the quick turnaround!
