### ISSUE TITLE
Add Referral Configuration

### ISSUE THREAD

**Issue by techleadcht** [reapit/foundations#10426]
Hello, all the developers in our team (as registered in the Reapit Developer Portal) will need access to the Configuration panel for the Leads/Referrals (for the AgencyCloud Developer edition in the Sandbox environment) as we are working on API calls for referrals.

![image](https://github.com/reapit/foundations/assets/153836949/aabdec74-71e2-40d1-96ba-eebc2e06850d)

**Comment by HollyJoyPhillips** [comment]
Hi @techleadcht, the configuration options are not available by default for Developers through the Developer Edition. 

If you can let us know the name, roles and app name of the referral, we can setup the referral on your behalf.

**Comment by HollyJoyPhillips** [comment]
Confirmed referrals have been setup. Please reach out if you have any questions/issues.
