### ISSUE TITLE
Postman request to access renewal negotiations for a Berkshire Hathaway tenancy results in"401 Unauthorized" error

### ISSUE THREAD

**Issue by steves99** [reapit/foundations#10451]
Please refer to attached screenshots
![image001](https://github.com/reapit/foundations/assets/136316379/bd6ff0e3-2778-4c67-b912-43f276b5f2eb)
![image002](https://github.com/reapit/foundations/assets/136316379/80dd6e71-c005-4d85-b3c6-445194c0d008)

**Comment by plittlewood-rpt** [comment]
Hi @steves99 please can you review what's happening in the Postman console when you issue this request (Ctrl + Alt + C or go to Menu -> View -> Show Postman Console)? I've checked the logs at this end and the path coming through our gateway is platform.reapit.cloud/KCL230034/renewalNegotiations which is odd looking at your screenshot above:

![image](https://github.com/reapit/foundations/assets/30798627/10a0909e-b322-4aa6-b454-52fe0c88010e)

**Comment by steves99** [comment]
Hi Pete,
Please see screenshot below.
Thanks,
Steve.
[image: image.png]

**Comment by plittlewood-rpt** [comment]
Hi Steve

Please can you forward the screenshot to sinfo@reapitfoundations.zendesk.com as Github has stripped it out 🤦 

Thanks

**Comment by plittlewood-rpt** [comment]
Hi Steve - I've responded via Github, but for reference for anyone who might come across this ticket in the future, the Authorization header is missing from your request. Many thanks
