### ISSUE TITLE
Can't obtain tokens for my application

### ISSUE THREAD

**Issue by anpar199** [reapit/foundations#10453]
Can't obtain tokens for my application

I am trying to access sandbox data for my application in Reapit but receiving '405 Method not allowed' response. I am following the this documentation https://foundations-documentation.reapit.cloud/api/api-documentation#authentication

**Comment by AshDeeming** [comment]
Hi @anpar199 
Please could you confirm the app name?

**Comment by anpar199** [comment]
Hi Ash,

It is hayman-joyce-sticky-pizzas
*Thanks,*
*Anton Parfeniuk*
Founder and CEO
The New Normal Analytics

*m*: +44 7876 705934
*e*: ***@***.***
*w*: thenewnormalanalytics.com
<https://www.thenewnormalanalytics.com/?utm_source=direct&utm_medium=personalemail&utm_campaign=emails>

**Comment by plittlewood-rpt** [comment]
@anpar199 please provide information about the request you are making so we can best support you. Thanks

**Comment by anpar199** [comment]
Hi Pete,

Please find below the request I am making in Postman:
[image: image.png]

I was following this part
<https://foundations-documentation.reapit.cloud/api/api-documentation#client-credentials-flow>
of the documentation.

Many thanks,
*Anton Parfeniuk*
Founder and CEO
The New Normal Analytics

*m*: +44 7876 705934
*e*: ***@***.***
*w*: thenewnormalanalytics.com
<https://www.thenewnormalanalytics.com/?utm_source=direct&utm_medium=personalemail&utm_campaign=emails>

**Comment by plittlewood-rpt** [comment]
Hi @anpar199 thanks for sending the information over. You are providing your information to the token endpoint as query string parameters and inside the x-www-form-urlencoded Body. From your screenshot you just need to move the items in the Params tab over to the Body tab

**Comment by plittlewood-rpt** [comment]
Hi @anpar199 I'll close this item down but please reach out if you still need any assistance. Thanks
