### ISSUE TITLE
Problem obtaining access token from a client-side app

### ISSUE THREAD

**Issue by Filip5991** [reapit/foundations#10462]
Hi,
We (Acaboom) have 2 apps on the foundations platform, one is an integration, and the other is a client-side app. 
So far, I've always used the integration app for any access tokens required, and that works great.
For a specific client, I needed to do it through the client-side app.

I followed the process explained at: 
https://foundations-documentation.reapit.cloud/api/reapit-connect#direct-user-to-reapit-connect

Used
![image](https://github.com/reapit/foundations/assets/23519137/6a5885ad-0bad-4934-80c9-749fe32683a1)
To get a code, and succesfully obtained one.
When I tried using the code however, to ping
https://connect.reapit.cloud/token, I keep getting an 'invalid_grant' message. (Grant type is set to 'authorization_code' and code is the one obtained from the redirect URL.

Am I doing something wrong in the procedure, or maybe our app needs to be granted some access to be able to obtain a token?

**Comment by HollyJoyPhillips** [comment]
HI @Filip5991, the following documentation might be useful: https://foundations-documentation.reapit.cloud/troubleshooting/authentication-issues#client-credentials-flow-authentication-issues

**Comment by Filip5991** [comment]
Hi @HollyJoyPhillips ,
I already saw the documentation link, but I discarded it as it is for 'Client credentials flow'?
What I was trying to use was 'Authorization Code Grant Flow', where a code is used instead of credentials. This is not an integration app, so it does not have a client secret for authorization

**Comment by plittlewood-rpt** [comment]
Hi @Filip5991 please can you send an example of the request you're making to the token endpoint. If you need to share sensitive information please email sinfo@reapitfoundations.zendesk.com with the details

**Comment by Filip5991** [comment]
Hi @plittlewood-rpt ,
I sent an example request at sinfo@reapitfoundations.zendesk.com :-)

**Comment by plittlewood-rpt** [comment]
Thanks - I've just replied

**Comment by Filip5991** [comment]
Thanks a lot @plittlewood-rpt , it was the trailing slash indeed...

**Comment by Filip5991** [comment]
@plittlewood-rpt actually ond more small question, apologies.

The access_token generated allows me access only to resources available to the user I logged in (which is my user, and the sandbox environemnt).
Is there a way to bypass this, and see data from clients that have installed our app, without having a user from a specific client generate the code/token for us?

I tried using a 'reapit-customer' header like I would do in a server-side app, but I think it is ignored.

**Comment by plittlewood-rpt** [comment]
Hi @Filip5991 your access token is explicitly scoped to the user you are logged in as when using the authorization_code oauth flow. There is no way to bypass this and you'd never want to be doing this either as you'd end up showing data to a user that they shouldn't have access to. If you need to use the same access token for multiple systems, using the client_credentials flow (server side) is the thing you'd need to be doing
