### ISSUE TITLE
Build POST /referrals endpoint

### ISSUE THREAD

**Issue by plittlewood-rpt** [reapit/foundations#10471]
**Background context**
To support some private enterprise integrations we need to create a POST endpoint in the referrals API

When customers install apps with the referrals.write scope, they are asked if they want to restrict which referrals the developer will have access to. This is because we don't want referral data being shared between third parties in some cases. The write endpoint is to support the setup of a specific referral type for one of our enterprise customers and the same mechanism will be used. When a customer configures referral filters at install, their selections are stored in the AppMarket database installation entry under a field called metadata. As a request comes into the Platform, the authorizer checks for this metadata and injects it into the downstream request so it is then available to backend services that need it. You can see how this is currently used by referencing `UpdateReferralCommandHandler`. The idea here is that the metadata will be inspected as part of the request handler (or indeed, this could be done in the validation layer) to ensure that the caller has permission to create referrals of a given type

**Specification**
- Project: Reapit.Services.Referrals
- Add new endpoint and associate handlers to create referrals (POST) protected by `referrals.write` scope
- Model: `CreateReferralModel`

```
{
      "referralTypeId": "JTS",
      "negotiatorId": "RPT",
      "propertyId": "RPT200420",
      "applicantId": "RPT210001",
      "contactId": "RPT22000001",     
      "amount": 0
}
```

**Validation**
 - To perform the id validations below, it may help to use the latest PlatformDatabase package which has all base entities and configurations in it. 
   - propertyId should be a valid LIVE property when set
   - applicantId should be a valid LIVE applicant when set
   - contactId should be a valid LIVE contact when set
   - negotiatorId should be a valid negotiator when set
   - referralTypeId should be a valid source when set AND access must be permitted to the caller
 - It should only be possible to set propertyId, applicantId or contactId NOT a combination
 - As above, it should not be possible to create referrals for archived records
 
**Behaviour**
 - Status should be set to "Sent" in all uses of the new POST endpoint
 - Amount must be non-negative when set
 - [ ] Confirm with AgencyCloud if it's possible to have two referrals of the same type against an entity at once. It's likely this isn't possible, but we should double check this
 - [ ] Confirm with product whether we should FORCE customers to setup referral filters at install, or if it should be optional. The former would prevent 'accidental' access to all referral data being opened up

**Comment by HollyJoyPhillips** [comment]
Requires input from the Foundations team.
