### ISSUE TITLE
Add Next Call Date field to PROPERTIES view in Analytics Schema

### ISSUE THREAD

**Issue by ktanalyst** [reapit/foundations#10477]
**Is your feature request related to a problem? Please describe.**
It is common practice for estate agents to use the Next Call Date field on the property card to manage communication with vendors. It would be great if this field was available within Data Warehouse so it can be linked to other data within the Analytics Schema.

**Describe the solution you'd like**
A new DATE field NEXT_CALL to sit within the PROPERTIES view in the analytics schema.

**Comment by plittlewood-rpt** [comment]
Hi @ktanalyst you will find these fields in the VENDORS view as the dates pertain to the last/next call to the contact, not the premise (which would be the PROPERTY). Please let me know if this isn't suitable for your use case. Thanks

**Comment by ktanalyst** [comment]
Hi @plittlewood-rpt, thanks for explaining. Yes that makes sense - we operate using the NCD on the property card but we can just join to vendor table to retrieve this field.

Thanks
