### ISSUE TITLE
Adding Consent Information To Contacts On Related

### ISSUE THREAD

**Issue by byt3sage** [reapit/foundations#10478]
**Is your feature request related to a problem? Please describe.**
It's really annoying that when querying applicants (for example) you get the nice handy related array given back to you but, it doesn't contain consent information which I think is one of the main pieces of information around a contact.

**Describe the solution you'd like**
It would be good to expose this field on related too.

**Describe alternatives you've considered**
Having to do another query to fetch consent information

**Specification**
- Projects
  - [x] Reapit.Services.Applicants
  - [x] Reapit.Services.Vendors
  - [x] Reapit.Services.Tenancies
  - [x] Reapit.Services.Landlords
  - [x] Reapit.Services.Offers

- Add new `string marketingConsent` property to the related contact model that exposes the marketing consent of the contact. Use the business logic from the contacts API to calculate this as there are some nuances from when the GDPR regulations were introduced. This should be read only like the rest of the model as updates are managed via the contacts API

**Comment by plittlewood-rpt** [comment]
@neilpellowe  just to flag this has been requested by multiple people now. Thanks

**Comment by neilpellowe** [comment]
Hi @plittlewood-rpt  - Happy to proceed into refinement with this one and add to the related info.

**Comment by jaetoole** [comment]
@plittlewood-rpt @HollyJoyPhillips does that mean we can maybe get it moved into near term then? ;)

**Comment by HollyJoyPhillips** [comment]
Hi @jaetoole, sorry for the delay, this is now in near term (as you'll have probably seen). I'll flag with the Foundations team so we can understand when it can be allocated to a sprint.

**Comment by adamcollison85** [comment]
Any update on this, its an urgent one for us an a number of large agencies we work with.

**Comment by HollyJoyPhillips** [comment]
Hi @adamcollison85 it's in our current sprint which runs from today (12th) until 23rd. Thanks.
