### ISSUE TITLE
Lomond - Brand Vaughan & Michael Jones Reapit Configuration - Fixflo Integration

### ISSUE THREAD

**Issue by jwkelsall** [reapit/foundations#10473]
Please take a look at our FAQ's before submitting an issue, as your question may already be covered in the documentation https://foundations-documentation.reapit.cloud/faqs

We need to speak to a Reapit technical/product individual about how we can combine both Michael Jones & Brand Vaughan's reapit data so that it syncs into one Fixflo system. 

Is there an individual who could jump on a zoom Friday 22nd December at either 11am or 3:30pm?  I will be joined by Fixflo Head of Product, Kate to discuss options

Thanks

**Comment by AshDeeming** [comment]
Hi @jwkelsall 
This will be best discussed via the Clients CSM(s) 

If the two databases remain separate, you will need to review how you store the datasets on your side as the app installation process will remain in place.

**Comment by HollyJoyPhillips** [comment]
Discussed with developer.
