### ISSUE TITLE
Expose Tenancy Manager (tTenMan) for SAV and SAU

### ISSUE THREAD

**Issue by MatthewGoddard** [reapit/foundations#10481]
Please expose Tenancy Manager (tTenMan) from the Tenancy table for SAV and SAU

- SAU and SAV
- Tenancy Manager - Ten.tTenMan (translated to Tenancy Progressor in the UI) 
- We are sending AC Tasks to the Tenancy Progressor to notify them of work they need to undertake

![image](https://github.com/reapit/foundations/assets/10115484/f0c51c8b-3a84-4842-bf75-9ae6b2cd3eec)

**Comment by AshDeeming** [comment]
Hi @MatthewGoddard 
The access for the field mentioned above has been set up as requested and should be active within the next 15 minutes.

As per any other semi structured data you access it using the extrasField query string parameter eg;

GET/tenancies?extrasField=tenancies.tTenMan

**Comment by MatthewGoddard** [comment]
Thanks @AshDeeming - that's brilliant.

Happy New Year to you and the team 😁

**Comment by plittlewood-rpt** [comment]
Hi @MatthewGoddard reviewing this we are going to add the manager as a structured field (read onyl for now) as I can see people might want to write to this field at some point. #10546 should hopefully go out today.
