### ISSUE TITLE
Inconsistencies In Buying/Sales Marketing Modes On Applicants API & Webhooks

### ISSUE THREAD

**Issue by jaetoole** [reapit/foundations#10480]
**Describe the bug**
The docs say for the API, that marketingMode should be sales for a sales applicant, but actually it is buying, but on the webhook examples, it is sales.

What is the live webhook field? Is marketingMode sales or is it buying...

**Comment by AshDeeming** [comment]
As discussed via Live Chat - Sales properties have the marketing mode as selling or sellingAndLetting

**Comment by jaetoole** [comment]
Hi @AshDeeming ,
Sory I said sales applicant

**Comment by AshDeeming** [comment]
Thanks @jaetoole 

Requirement to update the payload shown for Applicant

Buying/Renting > Sales/Letting

**Comment by jaetoole** [comment]
@AshDeeming  thanks!

Will you pick this up in the docs and the webhook pings?

**Comment by plittlewood-rpt** [comment]
Hi @jaetoole  I've updated the example payload sent when pinging your endpoint using the Applicant Created/Applicant Modified event. This is the only incorrect reference I can find. Have I missed anything that you've spotted? I can't see anything in the Swagger docs so possibly looking in the wrong place. Cheers
