### ISSUE TITLE
Don't know where I can download the developer edition install file.

### ISSUE THREAD

**Issue by MarcinuB** [reapit/foundations#10484]
Hello Team.

Happy Christmas!

I love the Developer portal revamp. It's nice and clean. However I can't find the place where I can download the Reapit developer edition. I have an existying licence but I can't find that option on the new Subscriptions  page. Would you be able to point me to a place where I can click Download or provide me with link please? 

Also I've noticed that pdf links are broken on your FAQ pages: https://foundations-documentation.reapit.cloud/faqs#developer-edition-of-agencycloud

Thanks

**Comment by AshDeeming** [comment]
Hi @MarcinuB 
Thank you  & hope you have a great festive break too

Regarding developer edition, please see: https://developers.reapit.cloud/desktop

I'll flag the broken links internally, thanks again

**Comment by MarcinuB** [comment]
How I didn't noticed that 🤦 

Thank you!
