### ISSUE TITLE
Application Scope - One or Multiple Apps?

### ISSUE THREAD

**Issue by morgan-young** [reapit/foundations#10499]
**Summary**

I am creating an app on Reapit that can do multiple things with work orders, transactions, etc.

**Detail and or supporting links and screenshots**

I'm wondering if it is best practice to create an app for each process, for example "Creating Works Orders" and another for "Adding Transactions to Tenancies"? Or, should I create one app and just allow users to opt in/out of the different processes as required?

I'm asking because the first option would mean multiple apps with tighter scope in terms of the endpoints we can access, and the second option would mean one app that requests multiple different scopes.

Which is best? Thanks

**Comment by AshDeeming** [comment]
Hi @morgan-young 
The approach of separate apps will work best if you plan to have the app public & may need to amend permission scope in the future. 

If however the app is in house & the scope set initially, you can use a single app to pull the required data

**Comment by morgan-young** [comment]
Thanks Ash!
