### ISSUE TITLE
Investigate the Sentry logs to address errors being reported for GEO Diary

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#1050]
**Summary**: When loading GEO Diary in Desktop (RPS) sentry is reporting background errors. Whilst in the front end it seems to be loading and behaving correctly. 

**Common Errors:** 
- unknown
- Cannot read property 'zoom' of null

The 'Zoom' error "Looks like a race condition because we are calling zoom on the map when the map hasn’t loaded" 

This most likely when there a 0 appointments so the map takes longer to load

**Task:** To invesitgate/fix the background errors in GEO Diary

**GEO Diary Sentry Errors:** https://sentry.io/organizations/reapit-ltd/issues/?project=1885608&referrer=slack

**Comment by tanphamhaiduong** [comment]
Blocked by this PR: https://github.com/reapit/foundations/pull/1136 for upload source map to sentry.io for easy to debug

**Comment by tanphamhaiduong** [comment]
@willmcvay @HollyJoyPhillips could we close this issue because I still cannot replicate it
