### ISSUE TITLE
Customer ID variations because of Marketplace Management App

### ISSUE THREAD

**Issue by Filip5991** [reapit/foundations#10520]
We have a client-side application developed inside Foundations called 'Acaboom push'.
When a client initiates the application, we pull the customer ID for that client, for further operations.
It was observed that users across different customers faced challenges while attempting to access our application. Following an investigation, the issue was identified: variations in customer IDs occur when clients access our app. 
One example would be the customer RBJ (Robinson Jackson).
Instead of the anticipated 'RBJ' customer ID, we occasionally receive slight variations like 'RBJ-GNRH'. Following our contact with support, we received the following information:

"It appears that the Marketplace Management App which Robinson Jackson are using might be the cause of the issues due to office security settings. Currently, any security settings set at config level within Reapit against users or offices are not reflected within Marketplace Management yet – work is underway to have this corrected."

I'm initiating this ticket as we were advised to open a bug-ticket for improved tracking of this issue.

**Comment by HollyJoyPhillips** [comment]
Hi @Filip5991, this section in the documentation may be useful: https://foundations-documentation.reapit.cloud/faqs#what-are-office-groups

**Comment by Filip5991** [comment]
Hi @HollyJoyPhillips , I understand the concept of office groups, but I'm not sure how to assist our client. When a customer opens our client-side app, we are sending a 'customer id' back to our system. The app was installed by 'RBJ' (their global customer), so when they open the app, we expect to see RBJ as the id, but instead we get some of the sub IDs, like 'RBJ-GNHR'. Is there a way to find the global, main ID from a sub-id like RBJ-GNHR, or would they need to re-install the app for each office group seaprately?

**Comment by HollyJoyPhillips** [comment]
Hi @Filip5991 Whilst the app was installed at organisation level, if the user belongs to an office group their ID will be that of the office group ID. 
Within the token we provide a 'agencyCloudId' field which will present the ID of the organisation. 

For reference the office group ids will always start with the organisation ID (not sure if that helps). 

You can use that field if you are mapping back to your system to assign users to an organisation but you should be aware that if an app is installed at office group level, it will still show the organisation ID so shouldn't be used for installation mapping.

**Comment by Filip5991** [comment]
Hi @HollyJoyPhillips thanks for this, just to confirm I understood you well:
If the app was installed at organisation level (RBJ), the agencyCloudId will be RBJ, but if the app was installed at office group level (RBJ-GNHR) then the agencyCloudId will be RBJ-GNHR? If yes, then I think it's better we use this field, because I think using the office group ids (or at least their first part) will cause issues when the app was installed by an office group, we would have no way to know if we need to check for the organization or just the office group

**Comment by HollyJoyPhillips** [comment]
Hi @Filip5991 sorry if I wasn't clear, the agencyCloudId will always be the main organisation ID e.g. regardless of the install it will always be RBJ which is why it shouldn't be used to match installations.

The clientcode will change based on if the user is part of an office group or not. 

What is it you are trying to achieve?

**Comment by Filip5991** [comment]
@HollyJoyPhillips  In our system each user Reapit ID is mapped to a unique user id from our system, but also to the Reapit organization ID it belongs to.
RBJ as an organization can have Reapit users ABC and XYZ under it. If we are trying to find out who user ABC is in our system, we need both the Reapit user id (ABC) and the Reapit organization id (RBJ). This is mostly because Reapit user IDs can be repetitve with different organizations (another organization can also have Reapit user id ABC).

RBJ installed our app as an organization. So, to identify who Reapit user id ABC is, we are expecting ABC + RBJ (Reapit user id + Reapit organization that installed the app). But, when office groups exist, we are getting back ABC + RBJ-GNHR (because we are using the loginIdentity.clientId) and because of that we cannot identify the user. 

The question is - how to pull the organization ID that installed the app (RBJ) and not the office group id (RBJ-GNHR). This also needs to work for cases when the app was installed by an office group (If instead of RBJ, RBJ-GNHR installed the app, user ABC would be linked with RBJ-GNHR, so we need this ID)

Hope this makes sense

**Comment by plittlewood-rpt** [comment]
Hi @Filip5991 I think the documentation you've found is slightly out of date. The loginIdentity object includes an `agencyCloudId` property which will _always_ be the id of the parent client, regardless of what gets assigned to the user. The reason the client code gets exposed with the office group suffix is to ensure that any requests back to the APIs include the necessary security/filtering requirements. Can you have a look at this property and let me know if it resolves your problem? 

When a customer (lets say ABC) using office groups installs an app globally, you'll see offGrouping set to true in the identity object and a clientCode of something like ABC-GXYZ, but the agencyCloudId will still be set to ABC.

When a customer using office groups installs an app for a specific office group, you'll get exactly the same content in the identity object as described above.

The identity object is about the person using your app, and doesn't have anything to do with the installation of the app being used. As you'll know if an app has been installed at an office group level or not (by the presence or omission of the suffix when the app gets installed), you can make an intelligent decision in code which property to use from the identity object to map back to your own system.

**Comment by plittlewood-rpt** [comment]
@joshbalfour would you mind checking the docs out [here](https://foundations-documentation.reapit.cloud/app-development/connect-session#basic-browser-usage) please. It looks like it's slightly out of date when compared to the [loginIdentity object in connect-session](https://github.com/reapit/foundations/blob/7bf4c180771e746473aee8b71b1ccaf9950c8936/packages/connect-session/src/types.ts#L57)

**Comment by Filip5991** [comment]
@plittlewood-rpt the `agencyCloudId `might just be what we need, thanks for that!

One last question: ..."As you'll know if an app has been installed at an office group level or not (by the presence or omission of the suffix when the app gets installed)" - I can find this out if I check the list of app installations, but is there a way to know this when a person (client) first starts our app, so that we automatically know which property to use from the identity object? If not we can probably exapnd the customer table on our end, and include the organization id as a field even for those customers who installed the app as an office group

**Comment by plittlewood-rpt** [comment]
Hi @Filip5991 there isn't really a way you can determine this from the identity object unfortunately. I think what you suggest above sounds like the best solution.

**Comment by Filip5991** [comment]
Thank you for your assistance @HollyJoyPhillips  and @plittlewood-rpt  :-)
