### ISSUE TITLE
another approach to close the MobileControls background

### ISSUE THREAD

**Issue by ss-dimasm** [reapit/foundations#10536]
**Is your feature request related to a problem? Please describe.**
Can we have an additional approach to close the MobileControls background when it's on active state? perhaps by pressing the highlighted area would be nice if it closing the background

![image](https://github.com/reapit/foundations/assets/96416644/90c17e90-6d7c-4a86-af27-39f9e2c0a715)

**Additional context**
Elements 4.0.1

**Comment by plittlewood-rpt** [comment]
@willmcvay can you feedback on this item? Presume it needs to go to the design team?

**Comment by willmcvay** [comment]
I can add this
