### ISSUE TITLE
Get tenancies checks data is slow

### ISSUE THREAD

**Issue by abrahamseni** [reapit/foundations#10538]
Get requests to /tenancies/checks getting slow in SAV.
I try query checks with pageSize of 2 resulting in 8.87s ( in avg, about 8s) for only 2.22 kb of data.
Could you please investigate why it gets so slow?
Thanks.

![Screenshot 2024-01-03 103452](https://github.com/reapit/foundations/assets/94949137/ca26f273-4785-4dc0-8357-160dc266f7c0)

**Specification**
- Run the query above directly against the tenancies API to see if it's the database being slow. The likelihood is this is being caused by metadata as the partition for Savills is running incredibly hot.
- If query against tenancies API is quick, move to the metadata API and make the call that the broker is making directly to the service to observe performance. If this is slow we need to look at our metadata structure. Additional indexing may solve this problem (new index with the sort key in the partition key)
- If it's possible to refactor the repository layer to make the query more performant we should do so
- Consider that there is no metadata housekeeping at all so we need a strategy for that (separate ticket fine here, but consider this whilst looking at the above)

**Comment by MatthewGoddard** [comment]
@abrahamseni Please can you do a similar set of checks against the applicant endpoint.

**Comment by abrahamseni** [comment]
@MatthewGoddard , this is some test that I did today:
This is all initial GET request, not the subsequent req that I assume will throw a cache.

Tenancy Checks (pageSize:2):
Note: subsequent req will result in the same time, oddly when the pageSize is 1 I can get less than 1 sec (around 300ms-400ms), if I change the pageSize to 20 up to 100, the amount of time load is about the same which is around 9-12 sec
![2024-01-04-tenancy-checks](https://github.com/reapit/foundations/assets/94949137/6c916b94-0f43-4d5e-b95c-1b305cea88e4)

Metadata (pageSize:100):
![2024-01-04-metadata](https://github.com/reapit/foundations/assets/94949137/ed61642b-fdce-4149-a7a3-6fb2cd214443)

Properties (pageSize: 100):
![2024-01-04-properties](https://github.com/reapit/foundations/assets/94949137/665fd533-73a4-4c35-b23d-476704873454)

Applicants (pageSize:100):
![2024-01-04-applicants](https://github.com/reapit/foundations/assets/94949137/cf0de1dc-a252-48ca-9ca0-e1fe72f05711)

Tenancies (pageSize:100):
![2024-01-04-tenancies](https://github.com/reapit/foundations/assets/94949137/0aa406ea-fa9b-44f8-b386-cc6bc5eb1735)

**Comment by abrahamseni** [comment]
Note: I think something is happening with metadata services for tenancy checks.
When querying via swagger it is fast.
