### ISSUE TITLE
possibility to close the AppSwitcher menu by pressing anywhere another on NavResponsive component

### ISSUE THREAD

**Issue by ss-dimasm** [reapit/foundations#10537]
**Is your feature request related to a problem? Please describe.**
can we have a feature to close the shown AppSwitcher menu by clicking the anywhere without click the AppSwitcher button again?

![image](https://github.com/reapit/foundations/assets/96416644/6c493a7a-5a43-4b42-ba21-7808fd7d5455)

**Additional Context**
Elements 4.01

**Comment by plittlewood-rpt** [comment]
@willmcvay can you feedback on this item? Presume it needs to go to the design team?

**Comment by willmcvay** [comment]
I can add this, it's a trivial fix
