### ISSUE TITLE
Including 'user1' and 'Extra Descriptions - Locations' in requests to /properties

### ISSUE THREAD

**Issue by propertyhive** [reapit/foundations#10541]
Client Name: House Partnership
Customer ID: THP

Client is reporting they've completed fields in the Reapit UI called 'User 1' and 'Extra Descriptions - Locations' but these aren't coming through in the data when making requests to `/properties`. Can you confirm how we obtain these, or if they need to be requested as extraFields?

Thanks,
Steve

**Comment by HollyJoyPhillips** [comment]
Hi Steve @propertyhive, 

Location is an extra field which I've now enabled for THP (pLocation). 

I can't seem to see where User 1 is completed in the CRM, can you ask the customer for a screen grab of where the field is located please?

**Comment by propertyhive** [comment]
Hi Holly, 

Thanks. Will do. As soon as I hear back I'll update this thread.

**Comment by plittlewood-rpt** [comment]
Hi @propertyhive we'll close this item down for now but please get back in touch if you ever find out the info for the User 1 field. Many thanks
