### ISSUE TITLE
We need access to the extras field to support a site integration procedure

### ISSUE THREAD

**Issue by rformato** [reapit/foundations#10550]
Hello,
I'm writing for Strutt & Parker,
we are in the middle of rewriting the property import procedure from the legacy DB sync to the Reapit API.
The aim of the import procedure is to import and show property data to the Strutt & Parker and John Clegg sites.

There are several extras fields used by Strutt & Parker, I am not sure about the name of those fields, because the names I can read in the Database Sync are different to those exposed by the API. I've noticed some of the data previously in the extras are now plain fields, but some of them are still not, such as the virtual tour links, some additional content, the brochure URL and other ones.

Would it be possible to get access to those fields through the API?

Thanks a lot!

**Comment by HollyJoyPhillips** [comment]
Hi @rformato, 

The brochure URL can be located under 'publicBrochureUrl' under the ‘Selling’ or ‘Letting’ object:
![image](https://github.com/reapit/foundations/assets/52408607/f07928a4-f4fb-48be-924c-402aaf722eb8)

Virtual Tours are captured under videoUrl and video2Url: 
![image](https://github.com/reapit/foundations/assets/52408607/5fad1b48-4054-4dfb-9fe6-cdc7ce3126a4)

If you can provide screen shots of the additional fields we can obtain the field names and see if it's possible to add a extra fields specific for this customer. For more information on extra fields please see: https://foundations-documentation.reapit.cloud/faqs#certain-fields-are-not-exposed-by-default-in-the-platform

**Comment by rformato** [comment]
Thanks Holly,
here is some fields I cannot find (situation, outside, direction), property MRP230085.
NB: there's a situation field in the API but that's not what I'm referring to

![immagine](https://github.com/reapit/foundations/assets/969336/8eb8bd3e-4e51-4e26-a25b-446aab2d30da)

Other fields I cannot find are:

- "open house day" boolean
- we used to have pPrice, pMinPrice, pMaxPrice but I can just see a price and a priceTo

**Comment by HollyJoyPhillips** [comment]
Hi @rformato 

Outside, Situation and Directions have been enabled. You can request pDirections and/or pSituation and/or pOutside via the extrasField query string parameter in calls to GET /properties eg

GET https://platform.reapit.cloud/properties?extrasField=pDirections&extrasFIeld=pSituation&extrasFIeld=pOutside

or

GET https://platform.reapit.cloud/properties/ABC1234567?extrasField=pDirections&extrasFIeld=pSituation

Are you able to ask the customer to provide a screen grab of where 'open house day' is set in the software (CRM) please? 

I'll come back to you on the price question shortly.

**Comment by rformato** [comment]
Here is the screen grab about open house day

![openhouseday](https://github.com/reapit/foundations/assets/969336/531699b2-9725-4199-a79e-0db56ea7dd08)

**Comment by HollyJoyPhillips** [comment]
Hi @rformato, pOpnHsDy (Open House Day) as also been enabled under the extra field request as above. Thanks.

**Comment by HollyJoyPhillips** [comment]
Hi @rformato Min Price and Max Price for non development properties, relates to matching criteria which isn't currently exposed via the Properties API. If you're happy with the other answers above, I'll close this ticket and if you require min/max price can you raise a separate feature request please?

**Comment by rformato** [comment]
that's fine, I opened a new issue https://github.com/reapit/foundations/issues/10556

**Comment by HollyJoyPhillips** [comment]
Great, thank you. I've added the request to our refinement column.
