### ISSUE TITLE
Client WNK-GMMU does not appear to have our second app available

### ISSUE THREAD

**Issue by Speedway1** [reapit/foundations#10557]
The client has installed our Core Features app but does not have access to the Nurture Add on app. They have contacted Reapit Support who have referred them back to us as apparently have access to their apps. 

They have also confirmed that the client has the correct permissions to install/enable. 

Thanks!

**Comment by HollyJoyPhillips** [comment]
Hi @Speedway1, the app was installed by that office group on 15-11-2023 by l******@winkworth.co.uk. When they open the app in the AppMarket, they should see 'App Installed'

![image](https://github.com/reapit/foundations/assets/52408607/6a45748b-c8e0-4864-81b5-c7dde5140024)

Are they having issues accessing it from the launch points perhaps? Is it for all users or a specific user?

**Comment by Speedway1** [comment]
Hi yes we have this app installed however it is the second app that they say they cannot access. Permissions is not an issue as that has also been checked. When they search for Nurture Add on, NIL is returned. This is the one we need installed.

**Comment by HollyJoyPhillips** [comment]
HI @Speedway1, I understand, sorry I misread the ticket. The app 'SMS Speedway Nurture Pack add-on' is set by the Organisation Admin at WNK to 'hidden' which hides it from the AppMarket. The organisation admin can either keep it hidden and install on behalf of that office group or make the app visible. Only the organisation admin has access via the Marketplace Management app to control visibility.
