### ISSUE TITLE
URGENT: E500 (internal data error) on Properties data - Customer LIR

### ISSUE THREAD

**Issue by Speedway1** [reapit/foundations#10558]
**Customer ID: LIR**

We have an internal data corruption issue on the properties table.

This endpoint - 
`https://platform.reapit.cloud/properties/?PageNumber=6&PageSize=100&modifiedFrom=2024-01-04T18:20:47Z&sortBy=created
`
keeps failing for a specific client with this response since last week:

{"statusCode":500,"dateTime":"2023-09-22T11:03:33.3499389Z","description":"An unexpected error has been encountered when fulfilling this request. This incident has been logged and will be investigated. Please try again."}

**Comment by plittlewood-rpt** [comment]
Hi @Speedway1 this is now resolved and was caused by some bad data. I've logged an item with our service team to investigate how it got to be in that state to try and prevent a reoccurrence. Many thanks

**Comment by Speedway1** [comment]
Thanks Pete! Have a great weekend.

Best,.
Brad
