### ISSUE TITLE
Missing Regional BER information for property BRY200224

### ISSUE THREAD

**Issue by declanlawlor** [reapit/foundations#10553]
**Describe the bug**
For property BRY200224, the BER information is not being passed in the webhook payload and is not available in the API. From Agency Cloud, we can see that the BER information is being set - see screenshot. However, in the JSON payload the `regional` property is set to `null`.

**Expected behaviour**
I would expect the `regional` property to be set containing `irl` and the associated BER data within `buildingEnergyRating`. This is a sample of what we see for other properties. 

```
"regional": {
        "ggy": null,
        "irl": {
            "buildingEnergyRating": {
                "exempt": false,
                "rating": "D1",
                "refNumber": "107216731",
                "epi": "238.11 kWh/m²/yr"
            }
        }
    },
```

**To Reproduce**
1. Hit the endpoint https://platform.reapit.cloud/properties/BRY20022
2. Inspect the response. 
3. Note the `regional` property is `null`

**Screenshots**
Screenshot of BER configured for BRY200224.

![image001](https://github.com/reapit/foundations/assets/2196083/53f5850d-9246-48be-b606-433c1a439a2f)

**Additional context**
This appears to be specific to this property only, as we are receiving the BER information for all other properties for this Customer/Office.

**Comment by HollyJoyPhillips** [comment]
Hi @declanlawlor, please can you provide the customer ID/Name?

**Comment by HollyJoyPhillips** [comment]
Hi @declanlawlor we were able to identify which customer this property record belongs to and the issue seems to be that the 'country' field has not been set in the CRM, Please can you check with the customer if after setting the country if the data is then accessible?

**Comment by declanlawlor** [comment]
Hi @HollyJoyPhillips, yes updating the Country field fixed the issue. We are now seeing the BER Data. Thanks!

**Comment by HollyJoyPhillips** [comment]
Great, thanks for letting us know.
