### ISSUE TITLE
Reapit <> Fixflo Basic

### ISSUE THREAD

**Issue by katedeedman** [reapit/foundations#10564]
Hi team,

Our developers at Fixflo are trying to understand exactly how the Fixflo <> Reapit Basic integration works. 

A key question from our developers is how you resolve the codes/ids from the issue report data? If you could send over any information, that would be a big help for us to decide what we do next with the Basic integration conversations.

Many thanks in advance!

-Kate

**Comment by AshDeeming** [comment]
Hi @katedeedman 
Apologies as I don't understand the question - The integration is owned by yourselves as far as I understand? 
Could you provide more information around the issue report data mentioned?
