### ISSUE TITLE
Combining Michael Jones & Brand Vaughan Reapit to sync into one Fixflo instance

### ISSUE THREAD

**Issue by jwkelsall** [reapit/foundations#10562]
Please take a look at our FAQ's before submitting an issue, as your question may already be covered in the documentation https://foundations-documentation.reapit.cloud/faqs

Hi Platform Team, 

Lomond have requested that both Michael Jones & Brand Vaughan data is synced over to one Fixflo instance. I'm informed by your colleague Michael Woods that the _Marketplace Management App does not allow an office to exist in more than one office group, so the only solution here would be to install FixFlo at Organisation level._The Product team is keen to delve into specific details to gain a comprehensive understanding to determine the most appropriate next action and avoid any unknown problems. 

To facilitate a more in-depth discussion, would any of the following times work 

- Monday 15th @ 4pm 
- Tuesday 16th @ 4pm
- Wednesday 17th @ 2pm

Thanks, 

James

- 

**Detail and or supporting links and screenshots**

**Comment by AshDeeming** [comment]
Hi @jwkelsall 
The installation option for OfficeGroup level or Organisation level is down to the client

**Comment by jwkelsall** [comment]
Hi @AshDeeming, I understand that the downloading of the app is down to the client. We're like to understand the impact that this might have on other brands if they are to change the app installation, also the developer will need to ask questions about the impact the changes might have on our middleware which is likely to throw up additional questions. In the interest of time, a call would be beneficial with a member of Reapit's developer team.  do any of the following times work? 

Monday 15th @ 4:30pm
Tuesday 16th @ 4pm
Wednesday 17th @ 2pm

**Comment by jwkelsall** [comment]
Hi @AshDeeming just chasing up on this to see when would be the preferred time? These times are still available but unfortunately will be booked up so a timely response would greatly be appreciated.

**Comment by AshDeeming** [comment]
Hi @jwkelsall 
Apologies for the delay - please could you provide your email address or contact via the below to discuss further;
support@reapitfoundations.zendesk.com

**Comment by HollyJoyPhillips** [comment]
Discussed with developer.
