### ISSUE TITLE
504 response for GET request to journal endpoint

### ISSUE THREAD

**Issue by garrym** [reapit/foundations#10575]
**Describe the bug**
Our application makes a GET request to `https://platform.reapit.cloud/journalEntries?propertyId=MYS230021&typeId=PC&typeId=PD&typeId=SF` to obtain journal entries but is receiving a 504 HTTP response code. This appears to be also happening for a different property and in our UAT environment too.

Reapit customer ID is `SAV`

Discussing with Reapit support chat the following was mentioned by the agent:
> from a quick review, the team are seeing around 1 request a minute being blocked, they will need to debug to find the cause. 

**To Reproduce**
1. Make a GET request to `https://platform.reapit.cloud/journalEntries?propertyId=MYS230021&typeId=PC&typeId=PD&typeId=SF`
2. Response is 504 after around 30 seconds

**Expected behaviour**
Journal entries should be returned for the property ID MYS230021

**Screenshots**
None

**Device (please complete the following information for web issues):**
- AWS Lambda running Node runtime.

**Additional context**
None

**Comment by plittlewood-rpt** [comment]
Hi @garrym thanks for raising this item, it was something that was already on my radar as I'd spotted the errors when they started occurring. This ultimately is boiling down to the way the database is choosing to run the query. For some bizarre reason it's choosing to use an index which isn't really suitable for the query generated for the parameters you're passing. I've brought our architecture team into the discussion internally to see if we can establish why we are seeing this behaviour. Can you confirm what process are your end is actually making those requests? The problem definitely seems to almost go away on a weekend when the database isn't running as hot which is something I'd expect based on the error I can see at this end. I'll endeavour to keep you updated as I continue to look at this.

**Comment by plittlewood-rpt** [comment]
Hi @garrym just to let you know this is now with our architecture team who will be looking at running some optimisation on the journal table in the Savills and Savills UAT databases which should address the strange behaviour we are seeing. This will need to be planned in and cannot really be run during working hours without impacting your users, so we'll be in touch with our key contacts as required.

**Comment by plittlewood-rpt** [comment]
Internal ticket: SI-22951

**Comment by garrym** [comment]
Thanks for the detailed update @plittlewood-rpt .

The process making this request is a synthetic browser test we have running every 5 minutes that logs in to our application and updates the viewing arrangements for this test property. Any failure in this test alerts us to issues with the application. We noticed the failures started occurring from about 10am on the 10th of Jan.

I can see that there are quite a few journal entries for this property in Reapit, which may have exacerbated the index problem you are seeing.

As I understand it the reason for this API call is to obtain price change information for the property for all time. If there are any further optimisations you'd recommend to obtain this information then we'd be happy to implement.

Thanks,
Garry

**Comment by plittlewood-rpt** [comment]
Hi @garrym 

I did note the excessive number of journal entries and decided it was some kind of smoke testing mechanism you had running. We could clear down the journal entries if that would be acceptable, however it won't deal with the underlying problem. That said, it might 'unblock' things so it probably depends on the perceived urgency here.

The way you're doing it is ultimately correct, as you want all price change journals for a specific property, there's no leaner way to do it really.

Pete

**Comment by garrym** [comment]
Thanks @plittlewood-rpt , a manual clear-down would be great and help get our synthetic tests working again, if possible.

**Comment by plittlewood-rpt** [comment]
Hi @garrym I've cleared all the miscellaneous entries for this property in SAV and SAU and the API is behaving itself again as the database is using the correct index. If you can confirm all OK at your end on Monday I'd be grateful and we'll keep the conversation going at this end about the underlying problem

**Comment by garrym** [comment]
I can confirm we're not seeing any issues on this end now, thanks for that.

**Comment by plittlewood-rpt** [comment]
Thanks for confirming. I'll close the Github item down and we'll continue to discuss internally.
