### ISSUE TITLE
Allow pAltNeg from extras

### ISSUE THREAD

**Issue by rformato** [reapit/foundations#10577]
Hello,
I'm writing for Strutt & Parker,
can we please add pAltNeg?

Would it also embed the alternative negotiator if negotiator is selected as to be embedable?

Thanks!

**Comment by AshDeeming** [comment]
Hi @rformato access for the fields mentioned above has been set up and should become active within the next 15 minutes.
**pAltNeg**

As per any other semi structured data you access it using the extrasField query string parameter eg;
GET /properties?extrasField=properties.pAltNeg
