### ISSUE TITLE
Extra Descriptions - Directions - not passed in Webhook Event Payload

### ISSUE THREAD

**Issue by declanlawlor** [reapit/foundations#10576]
**Describe the bug**

For Customer SFG, property BRY200224, we are not receiving the Directions text as part of the payload.

**To Reproduce**
1. Go to the Directions panel as part of the "Extra Descriptions" on the marketing screen
2. Add some Directions text and Save
3. Retrieve the Property via the Foundations 'Get Property' API
4. The Directions text is not found in the response 

**Expected behaviour**
The Directions text should be available in the API/Webhook.

**Screenshots**
![ReapitDirections](https://github.com/reapit/foundations/assets/2196083/40b6be44-a6f5-46df-bedf-fd6952aeec6f)

**Comment by AshDeeming** [comment]
Hi @declanlawlor 
As these are semi structured, they will need to be made available - I can action this for Directions, however i wanted to check if the other extra descriptions will be needed too?

**Comment by plittlewood-rpt** [comment]
To discuss whether or not we should look at including the extra descriptions by default somehow

**Comment by plittlewood-rpt** [comment]
We are discussing whether or not it is sensible to just expose all custom descriptions as part of the standard API response. This is likely going to take some time. As a result we should use the existing extrasField mechanism with a caveat that the mechanism may change in the future.

**Comment by declanlawlor** [comment]
hey guys, to my knowledge, we only require Directions. I don't see any issue with it changing in the future.

**Comment by AshDeeming** [comment]
Thanks @declanlawlor 

Access for the field **pDirections** has been set up and should become active within the next 15 minutes.

As per any other semi structured data you access it using the extrasField query string parameter eg;
GET /properties?extrasField=properties.pDirections

**Comment by declanlawlor** [comment]
@AshDeeming thanks, but i'm not seeing that when i test it on SBOX just now. i assuming here i'll see this in the webhook event?

**Comment by HollyJoyPhillips** [comment]
For this to be available via webhooks, you'll need to configure this via the DeveloperPortal. More information can be found here: https://foundations-documentation.reapit.cloud/api/webhooks#including-semi-structured-data-in-webhook-events
