### ISSUE TITLE
Urgent: Issue with Text Description in Properties API Extraction

### ISSUE THREAD

**Issue by SairamKDXFT** [reapit/foundations#10573]
Description
Hi Team ,

We have identified a critical issue with the Properties API data extraction.

whenever any update happens on a Property in Reapit ; Over the callback API the property description for 'newly' keyword is showing as 'embeddedly'.

Ex : Property code : BGO110142

The description is ''A newly, fully refurbished second floor flat (35.21 sq m/379 sq ft approx.) converted from a Victorian terraced house".

post the Callback API we are receiving as

"A embeddedly, fully refurbished second floor flat (35.21 sq m/379 sq ft approx.) converted from a Victorian terraced house".

This impacts data accuracy.

Few other sample Reapit Property codes : NHO230192, COF230101, NHO230212

Please investigate and fix this urgently. Let me know if you need more details

<img width="861" alt="image" src="https://github.com/reapit/foundations/assets/145762206/719c6b9a-dc59-4471-8726-e88ef5b82cd5">

<img width="494" alt="image" src="https://github.com/reapit/foundations/assets/145762206/7b165206-3d02-401d-bc37-1d06b571c11f">

**Comment by HollyJoyPhillips** [comment]
Hi @SairamKDXFT, can you provide the customer name or ID please?

**Comment by SairamKDXFT** [comment]
Hi @HollyJoyPhillips 

customer Id :  Druce & Co (International) Limited (URA)

**Comment by plittlewood-rpt** [comment]
Hi @SairamKDXFT we've had a look at the transaction logs at our end and it does appear that we send the correct text. You should be able to see this yourself if you look at the Webhooks Transaction Log in the Developer Portal under API -> Webhooks -> Transaction Log.

Can you let me know which tool you're using in the second screenshot above? We've tested this just now on a sandbox property and get the correct data through, so this seems very odd!

**Comment by plittlewood-rpt** [comment]
Hi @SairamKDXFT do you have any feedback on the above? Thanks

**Comment by SairamKDXFT** [comment]
Hi @plittlewood-rpt  we are using Salesforce to get the data.  

can we have a call today to discuss further ?

**Comment by plittlewood-rpt** [comment]
Hi @SairamKDXFT we do not support external tools. I would recommend setting up a test webhook using an endpoint that can just log out the raw data (there are several tools that do this, such as Pipedream and Ngrok). If you can test that from your end and advise if you still see the same thing I'd be grateful.

**Comment by SairamKDXFT** [comment]
Hi @plittlewood-rpt  thanks for the details. we have identified the issue and we applied fix at our end.

**Comment by plittlewood-rpt** [comment]
That's great - thanks for confirming
