### ISSUE TITLE
Salutation missing for Staff Members for Companies 

### ISSUE THREAD

**Issue by raymond2323** [reapit/foundations#10582]
I am able to add a Salutation for a Staff Member of a Company, however I am not able to fetch it via the API 

<img width="1070" alt="image" src="https://github.com/reapit/foundations/assets/17427875/b64af0da-b7ec-4b44-8a85-1fa19a5b6ebc">

Can we add this to the API ?

**Specification**
- Project: Reapit.Services.Companies
- Update `StaffModel` to include new `string Salutation` property that exposes `cnt.cntExtra.cSaltnX` for named staff members OR the preferred salutation for linked contact staff members (use cntPrefSaltn to pick correct semi structured value)

**Comment by plittlewood-rpt** [comment]
Hi @neilpellowe - can you give this your review please? It will tick a box for one of our enterprise customers and is pretty simple to implement.

**Comment by neilpellowe** [comment]
Hey @plittlewood-rpt. Happy to go ahead and add this info to the API.
