### ISSUE TITLE
Increase level of access for developer - referred to you by support

### ISSUE THREAD

**Issue by DannyMLT** [reapit/foundations#10585]
Hi,

We require a higher level of access on a client account in order to access app secrets. Our client is Andersonbain LLP - and our developer email is support@mltdigital.co.uk

I realise this is likely not for Github but we were directed here by your support team (Gemma Taylor)

We were instructed to raise this issue here in Github as ReapIT support cannot grant a higher level of access, and the administrator of the account does not have the ability to do so either. As a result this is blocking any attempts by us to progress with the integration of your service to the client's website.

If you are unable to do this, can you please liase with gtaylor@reapit.com urgently to get it sorted? Please if needed contact Andersonbain LLP to approve if needed. But we're a bit stuck and cannot progress further without access.

Thank you,

Daniel at MLT Digital.

**Comment by AshDeeming** [comment]
Hi @DannyMLT 
Please note that the admin user for the Clients developer organisation (Paul Flecher-Herd) will need to do this via the below url:
https://developers.reapit.cloud/settings/members
