### ISSUE TITLE
Testing Agency Cloud Integration App 

### ISSUE THREAD

**Issue by Ivana90GS** [reapit/foundations#10584]
We have launched application on Reapit Market Place – “Acaboom Push”. This app was developed using Reapit Connect and also we have downloaded the Desktop Agency Cloud Developer Edition, which was used for testing before the app was submitted for revision and made public. While developing the app the Redirect Uri listed under the 'Authentication' section was localhost:8080, but that was changed when the app got published with live Uri. Now we need to make some changes in the React front end part of the application and my question is how should we test this. Starting and building the app in the VS Code is not working since the redirect Uri is not connected to the localhost anymore. And if we change the redirection Uri of the app the app will stop working. How should we proceed?

**Comment by AshDeeming** [comment]
Hi @Ivana90GS 
If the testing is being done with sandbox data, please create a new app with the revised permissions.
