### ISSUE TITLE
Property Status change table

### ISSUE THREAD

**Issue by elizabethhamlin** [reapit/foundations#10586]
Hi

The property status change table does not seem to function as it should.

For example, I want to be able to report on any properties that are classed as a relet so where there has been a tenancy on the property before. Therefore this would be any property status where it has changed from either provisional or tenancy current - unavailable to To Let - available or Tenancy Current - available.
However the when using these filters it does not pull through the data. I have check some of the properties that should have appeared and they do not despite this entry being present -
<img width="331" alt="image" src="https://github.com/reapit/foundations/assets/104636752/3109000f-1a11-4014-83b2-ab0888e698ba">

Please can you let me know your thoughts?

**Comment by plittlewood-rpt** [comment]
Hi @elizabethhamlin the entry you mention above is showing in the PROPERTY_STATUS_CHANGES view. If you run the following query directly against Snowflake you'll see the row

`SELECT * FROM PROPERTY_STATUS_CHANGES WHERE OLD_STATUS LIKE '%Tenancy Current - Unavailable%' AND NEW_STATUS LIKE '%Tenancy Current - Available' AND CHANGED_AT_DATE = '2024-01-05' AND _CUSTOMER_ID = 'LOC' ORDER BY CHANGED_AT_TIME`

![image](https://github.com/reapit/foundations/assets/30798627/3963f417-6241-4196-a2c6-3ee3d772f4ef)

Are you able to give me a bit more information about the problem you're seeing?

**Comment by plittlewood-rpt** [comment]
Hi @elizabethhamlin all the image content has been stripped out. Please can you email this to sinfo@reapitfoundations.zendesk.com so I can take a look?

**Comment by elizabethhamlin** [comment]
Hi Pete 
Any update on this one?
Thanks 
Lill

**Comment by plittlewood-rpt** [comment]
Hi @elizabethhamlin did you ever send the detail over to Zendesk? Thanks

**Comment by elizabethhamlin** [comment]
Yes

Elizabeth Hamlin MARLA
Reporting and Systems Manager
07443 188920
***@***.******@***.***>

[Text  Description automatically generated]

Lomond is a group of leading Lettings and Sales Agents across the UK. Lomond is the trading name of Chianti Holdings Ltd. Registered office address 70 St. Mary Axe, London, EC3A 8BE. Registered in England and Wales. Registered Company No. 13075482.

This email is confidential and intended solely for the use of the individual to whom it is addressed. Any views or opinions presented are solely those of the author and do not necessarily represent those of Lomond. If you are not the intended recipient, be advised that you have received this email in error and that any use, dissemination, forwarding, printing, or copying of this email is strictly prohibited. If you have received this email in error please contact the sender. Finally, the recipient should check this email and any attachments for the presence of viruses. The company accepts no liability for any damage caused by any virus transmitted by this email.

**Comment by plittlewood-rpt** [comment]
Closing as per zendesk ticket. Glad you got this sorted. Thanks
