### ISSUE TITLE
Strange Retry Behaviour

### ISSUE THREAD

**Issue by declanlawlor** [reapit/foundations#10591]
**Describe the bug**
Noting strange retry behaviour for event `b71f29e8-25a9-48e0-85fd-ee28cc69043c`. It is not confined to that event only, I've seen other examples. Here is the retry sequence:-

At 16-01-2024 11:24:04, SendAttempts = 1 
At 16-01-2024 11:26:14, SendAttempts = 4 
At 16-01-2024 11:31:14,  SendAttempts = 4
At 16-01-2024 11:41:15,  SendAttempts = 4 

**Expected behaviour**

As per the [Documentation](https://foundations-documentation.reapit.cloud/api/webhooks#failure-handling-and-exponential-backoff) it should be something like this:-

At 16-01-2024 11:24:04, SendAttempts = 1 
At 16-01-2024 11:25:04, SendAttempts = 2 (missing from above)
At 16-01-2024 11:27:04, SendAttempts = 3 
At 16-01-2024 11:32:14,  SendAttempts = 4
At 16-01-2024 11:42:04,  SendAttempts = 5 (missing from above)
At 16-01-2024 11:57:15,  SendAttempts = 6 

**Additional context**
For each of the retry attempts we don't receive the `X-Signature` header, but this is already tracked in another issue. 

**Specification**
- Project: Reapit.Services.Webhooks
- Review transaction log (DynamoDb table) for the event mentioned to confirm the behaviour reported above. Ensure that this isn't just a case of us failing to send the second and third attempts for that event. 
- Review webhook error logs from the time specified above to see if there is any odd behaviour occurring
- Review code in `EmitWebhookCommandHandler` which houses the code responsible for the retry mechanism to see if there are any obvious places this could be misbehaving. There is a chance that a batch of events is taking too long to process and so when we try to delete the event it fails because the token we use to delete the event has expired. It is possible to deal with this problem by telling SQS to extend the lifetime of the visibility timeout if processing is taking longer than the initial timeout.

**Comment by RWilcox-Reapit** [comment]
Hi @declanlawlor 

I've looked into this issue and the retry mechanism has worked as expected.
(noting the exponential backoff time between each retry shown above 2, 5, 10 minutes etc)

I can't look back to see the exact payload which includes 'sendAttempts' sent on each retry but I can see the delay mechanism has worked.
I have made an enhancement to the retry mechanism to give our processors a longer time to handle the retry. This should protect us from the same retry being picked up multiple times.
 
We will monitor this moving forward.

Thanks,
Ryan
