### ISSUE TITLE
Corrupt Renewal Checks in SAV

### ISSUE THREAD

**Issue by MatthewGoddard** [reapit/foundations#10593]
The renewal checks for renewal negotiation REL240103 on tenancy FAL230317 are corrupt (no Description or checkTypeId).

Looking via the Command Processor (thanks to Ross L) the checks are there, as per the attached file named REL240103.xlxs.
[REL240103.xlsx](https://github.com/reapit/foundations/files/13953327/REL240103.xlsx)

There is a previous renewal negotiation REL735969 for this tenancy where the checks are working. Export also attached.
[REL735969.xlsx](https://github.com/reapit/foundations/files/13953341/REL735969.xlsx)

It appears that all of the checks where created on the 10th January when the renewal negotiation was created.

We have another example with renewal negotiation code REL240033 on tenancy WIL230222 with the same issue in the API (no Description or checkTypeId).

**Specification**
- Review Gateway access logs to confirm that these negotiations were created via the API. It's likely that the default checks are persisted in the database when the initial call to GET /tenancies/{id}/renewalNegotiations/checks is made
- If the API did create the entries, get to a point where this can be replicated and resolved. Issue is more than in likely in the repository layer

**Comment by plittlewood-rpt** [comment]
Hi @MatthewGoddard this should now be resolved. I've checked the examples given in the live system and they are now displaying correctly. If you can get some feedback from the customer before I close this I'd be grateful
