### ISSUE TITLE
Issue accessing staff information in API

### ISSUE THREAD

**Issue by darraghmcgrath3** [reapit/foundations#10597]
Hi all, 

A company we're working with is trying to use the API through our app "Mortgage Referral Companion" to pull staff data, but they are only receiving information for one office when querying the negotiators endpoint (https://platform.reapit.cloud/negotiators), despite the app being installed for several office groups through Marketplace Management. The install is for specific referral types, but should this affect the negotiator endpoint? They are receiving other office referrals in the API, but not staff updates. 

Company: SFG

Thanks,
Darragh

**Comment by HollyJoyPhillips** [comment]
Hi @darraghmcgrath3, the app has been installed for 2 office groups. One office group has only one office 'HEO' attached to it so if it's that group, it would make sense it's only returning data for that one office.

Can you confirm which office/office group please?

**Comment by darraghmcgrath3** [comment]
Thanks, Holly.

That is the group that we are getting information for, but we are receiving no information for the second group SFG-GNEH containing four offices (CNH, DNH, GNH, & LNH).

We are receiving through referrals created under those offices.

Many thanks,
Darragh


Darragh McGrath
Web Operations Executive
Sherry FitzGerald
Silverstone House, Ballymoss Road, Sandyford, Dublin 18, D18 A7K7

Direct: +353 1 237 6338
Mobile: +353 87 709 3553
Email: ***@***.***
Web: www.sherryfitz.ie

I have sent this email at a time that is convenient for me. I do not expect you to respond to it outside of your usual working hours.
​
Sign up to mySherryFitz now to book viewings, make offers, see existing bids, arrange property notifications and chat to us online – we’re here to help!
Click here to view the Sherry FitzGerald Privacy Policy
Please consider the environment before printing this email 
 
Sherry FitzGerald Group Ireland Holdings Limited. Registered in Ireland, CRO no 623927. 
Registered office: Silverstone House, Ballymoss Road, Sandyford, Dublin 18. D18 A7K7.
 
The contents of this e-mail are Subject to Contract /Contract denied. 
​
​This e-mail and any files transmitted with it are confidential and are intended solely for the use of the intended recipient. Any unauthorised direct or indirect dissemination, distribution or copying of this message and any attachments is strictly prohibited. If you have received this e-mail or any file attachment transmitted with it in error, please notify Sherry FitzGerald at ***@***.*** 
​
​This email has been scanned for computer viruses.
 
A part of the Sherry FitzGerald Group
Residential | New Homes | Lettings |  Mortgages

**Comment by HollyJoyPhillips** [comment]
Hi @darraghmcgrath3 thank you. You mention they are only getting one office back, which office from that group?

**Comment by darraghmcgrath3** [comment]
Thanks Holly—we’re getting the HEO info, just no info from any offices under the other office group.


Darragh McGrath
Web Operations Executive
Sherry FitzGerald
Silverstone House, Ballymoss Road, Sandyford, Dublin 18, D18 A7K7

Direct: +353 1 237 6338
Mobile: +353 87 709 3553
Email: ***@***.***
Web: www.sherryfitz.ie

I have sent this email at a time that is convenient for me. I do not expect you to respond to it outside of your usual working hours.
​
Sign up to mySherryFitz now to book viewings, make offers, see existing bids, arrange property notifications and chat to us online – we’re here to help!
Click here to view the Sherry FitzGerald Privacy Policy
Please consider the environment before printing this email 
 
Sherry FitzGerald Group Ireland Holdings Limited. Registered in Ireland, CRO no 623927. 
Registered office: Silverstone House, Ballymoss Road, Sandyford, Dublin 18. D18 A7K7.
 
The contents of this e-mail are Subject to Contract /Contract denied. 
​
​This e-mail and any files transmitted with it are confidential and are intended solely for the use of the intended recipient. Any unauthorised direct or indirect dissemination, distribution or copying of this message and any attachments is strictly prohibited. If you have received this e-mail or any file attachment transmitted with it in error, please notify Sherry FitzGerald at ***@***.*** 
​
​This email has been scanned for computer viruses.
 
A part of the Sherry FitzGerald Group
Residential | New Homes | Lettings |  Mortgages

**Comment by HollyJoyPhillips** [comment]
Hi @darraghmcgrath3 I suspect it will most likely be the authentication and the developer is not using the correct client ID. Can you ask the developer to send the full request (CURL) to us and we can validate. They can send to sinfosinfo@reapitfoundations.zendesk.com. Thanks.

**Comment by darraghmcgrath3** [comment]
Thanks Holly, have requested that now.


Darragh McGrath
Web Operations Executive
Sherry FitzGerald
Silverstone House, Ballymoss Road, Sandyford, Dublin 18, D18 A7K7

Direct: +353 1 237 6338
Mobile: +353 87 709 3553
Email: ***@***.***
Web: www.sherryfitz.ie

I have sent this email at a time that is convenient for me. I do not expect you to respond to it outside of your usual working hours.
​
Sign up to mySherryFitz now to book viewings, make offers, see existing bids, arrange property notifications and chat to us online – we’re here to help!
Click here to view the Sherry FitzGerald Privacy Policy
Please consider the environment before printing this email 
 
Sherry FitzGerald Group Ireland Holdings Limited. Registered in Ireland, CRO no 623927. 
Registered office: Silverstone House, Ballymoss Road, Sandyford, Dublin 18. D18 A7K7.
 
The contents of this e-mail are Subject to Contract /Contract denied. 
​
​This e-mail and any files transmitted with it are confidential and are intended solely for the use of the intended recipient. Any unauthorised direct or indirect dissemination, distribution or copying of this message and any attachments is strictly prohibited. If you have received this e-mail or any file attachment transmitted with it in error, please notify Sherry FitzGerald at ***@***.*** 
​
​This email has been scanned for computer viruses.
 
A part of the Sherry FitzGerald Group
Residential | New Homes | Lettings |  Mortgages

**Comment by HollyJoyPhillips** [comment]
Hi @darraghmcgrath3, you can only provide a single customer ID in a request. The referral types are set against the installation. 

For SFG-GNEH, the approved referral types are  "RPT08", "RPT07" and for SFG-GHEO, it is "RPT02", "RPT6". 

Using the client ID of SFG-GHEO should only return referrals of "RPT02", "RPT6". If they have an example request where they are using the SFG-GHEO and it's returning referrals outside of what has been set, please forward to us and we can investigate.

**Comment by darraghmcgrath3** [comment]
Hi Holly,

Please see example below, it also seems like referrals of type RPT02 & RPT6 are going through also for New Homes despite the app not being installed for them.

[image.png]

Thanks,
Darragh


Darragh McGrath
Web Operations Executive
Sherry FitzGerald
Silverstone House, Ballymoss Road, Sandyford, Dublin 18, D18 A7K7

Direct: +353 1 237 6338
Mobile: +353 87 709 3553
Email: ***@***.***
Web: www.sherryfitz.ie

I have sent this email at a time that is convenient for me. I do not expect you to respond to it outside of your usual working hours.
​
Sign up to mySherryFitz now to book viewings, make offers, see existing bids, arrange property notifications and chat to us online – we’re here to help!
Click here to view the Sherry FitzGerald Privacy Policy
Please consider the environment before printing this email 
 
Sherry FitzGerald Group Ireland Holdings Limited. Registered in Ireland, CRO no 623927. 
Registered office: Silverstone House, Ballymoss Road, Sandyford, Dublin 18. D18 A7K7.
 
The contents of this e-mail are Subject to Contract /Contract denied. 
​
​This e-mail and any files transmitted with it are confidential and are intended solely for the use of the intended recipient. Any unauthorised direct or indirect dissemination, distribution or copying of this message and any attachments is strictly prohibited. If you have received this e-mail or any file attachment transmitted with it in error, please notify Sherry FitzGerald at ***@***.*** 
​
​This email has been scanned for computer viruses.
 
A part of the Sherry FitzGerald Group
Residential | New Homes | Lettings |  Mortgages

**Comment by darraghmcgrath3** [comment]
Hi Holly, would it be possible for you to join a call with us and our developer from OnlineApplication just to discuss the above please? If so, would tomorrow or Wednesday morning suit? Thanks, Darragh

**Comment by plittlewood-rpt** [comment]
hi @darraghmcgrath3 unfortunately Github has stripped your screenshot out from the above. Can you possibly email it so sinfo@reapitfoundations.zendesk.com and I'll have a look. Holly is away until Wednesday so depending on what I find from your screenshot I'll come back to you as necessary

**Comment by darraghmcgrath3** [comment]
Hi Pete, I’ve sent that by email now. Thanks, Darragh


Darragh McGrath
Web Operations Executive
Sherry FitzGerald
Silverstone House, Ballymoss Road, Sandyford, Dublin 18, D18 A7K7

Direct: +353 1 237 6338
Mobile: +353 87 709 3553
Email: ***@***.***
Web: www.sherryfitz.ie

I have sent this email at a time that is convenient for me. I do not expect you to respond to it outside of your usual working hours.
​
Sign up to mySherryFitz now to book viewings, make offers, see existing bids, arrange property notifications and chat to us online – we’re here to help!
Click here to view the Sherry FitzGerald Privacy Policy
Please consider the environment before printing this email 
 
Sherry FitzGerald Group Ireland Holdings Limited. Registered in Ireland, CRO no 623927. 
Registered office: Silverstone House, Ballymoss Road, Sandyford, Dublin 18. D18 A7K7.
 
The contents of this e-mail are Subject to Contract /Contract denied. 
​
​This e-mail and any files transmitted with it are confidential and are intended solely for the use of the intended recipient. Any unauthorised direct or indirect dissemination, distribution or copying of this message and any attachments is strictly prohibited. If you have received this e-mail or any file attachment transmitted with it in error, please notify Sherry FitzGerald at ***@***.*** 
​
​This email has been scanned for computer viruses.
 
A part of the Sherry FitzGerald Group
Residential | New Homes | Lettings |  Mortgages

**Comment by darraghmcgrath3** [comment]
Hi Pete,

I just wanted to check if you had a chance to review the below?

Thanks,
Darragh

From: Darragh McGrath ***@***.***>
Sent: Monday, January 22, 2024 4:43 PM
To: reapit/foundations ***@***.***>; reapit/foundations ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [reapit/foundations] Issue accessing staff information in API (Issue #10597)

Hi Pete, I’ve sent that by email now. Thanks, Darragh

[https://signatures.sherryfitz.ie/logo/SF%20Group%20logo_2018.jpg]
Darragh McGrath​
Web Operations Executive
Sherry FitzGerald
Silverstone House, Ballymoss Road, Sandyford, Dublin 18, D18 A7K7
[https://signatures.sherryfitz.ie/logo/Proud_June23.png]<https://www.100kin30days.ie/>
Direct:
+353 1 237 6338<tel:+353%201%20237%206338>
Mobile:
+353 87 709 3553<tel:+353%2087%20709%203553>
Email:
***@***.******@***.***>
Web:
www.sherryfitz.ie<http://www.sherryfitz.ie/>
I have sent this email at a time that is convenient for me. I do not expect you to respond to it outside of your usual working hours.
​
Sign up to mySherryFitz<https://www.mysherryfitz.ie/buyers/sign_in?utm_source=GMB&utm_medium=email&utm_campaign=email_sig#sign-up> now to book viewings, make offers, see existing bids, arrange property notifications and chat to us online – we’re here to help!
Click here to view the Sherry FitzGerald Privacy Policy<http://www.sherryfitz.ie/privacy>
Please consider the environment before printing this email

Sherry FitzGerald Group Ireland Holdings Limited. Registered in Ireland, CRO no 623927.
Registered office: Silverstone House, Ballymoss Road, Sandyford, Dublin 18. D18 A7K7.

The contents of this e-mail are Subject to Contract /Contract denied.
​
​This e-mail and any files transmitted with it are confidential and are intended solely for the use of the intended recipient. Any unauthorised direct or indirect dissemination, distribution or copying of this message and any attachments is strictly prohibited. If you have received this e-mail or any file attachment transmitted with it in error, please notify Sherry FitzGerald at ***@***.******@***.***>.
​
​This email has been scanned for computer viruses.

A part of the Sherry FitzGerald Group
Residential<https://www.sherryfitz.ie/sell/why-us> | New Homes<https://www.sherryfitz.ie/advice/first-time-buyers> | Lettings<https://www.sherryfitz.ie/advice/landlords-why-us> |  Mortgages<https://www.sherryfitz.ie/mortgages>

**Comment by darraghmcgrath3** [comment]
Hi Pete, just to ask also on the point above about having to call the office group IDs separately, is it possible to tell from a webhook which office group ID has triggered the webhook? Thanks, Darragh

**Comment by HollyJoyPhillips** [comment]
Hi @darraghmcgrath3 the customer ID in the payload will indicate which office group the request has been emitted from: 
![image](https://github.com/reapit/foundations/assets/52408607/45ca116f-a85c-46af-8b28-d04d0e930c06)

**Comment by HollyJoyPhillips** [comment]
"Hi Pete, I just wanted to check if you had a chance to review the below? Thanks, Darragh "

Hi @darraghmcgrath3, we've had a chance to review the issue and have logged the following ticket which will be picked up in refinement this afternoon: https://github.com/reapit/foundations/issues/10627

After refinement, we'll be able to confirm where it can be allocated to a sprint. 
Thanks
Holly

**Comment by darraghmcgrath3** [comment]
Thanks, Holly

**Comment by darraghmcgrath3** [comment]
Hi Holly, just a quick query on the API calls - is a single call to the same endpoint for multiple different office groups generating a single API call/charge for each branch group, so multiple charges/calls for each endpoint, or a single API call/charge overall for each endpoint?

**Comment by HollyJoyPhillips** [comment]
Hi @darraghmcgrath3 apologies for the delayed reply. It will be a charge for each group. We have moved the related tickets into our next sprint which starts on 11th. Thanks,
