### ISSUE TITLE
Properties API Office filter parameter

### ISSUE THREAD

**Issue by rajeshwl** [reapit/foundations#10596]
We have a client who has two different brands and website separately and planned to use single reapit instance, but we need to filter the  properties in the website import. In properties API call we have option to pass office id's in the request and filter the data. Can you please confirm whether using more office ids in the URL's will work, like 20 office ids in the URL parameter. I have added the client code and the properties sample URL.

Client Code: ROM
Sample Request: https://platform.reapit.cloud/properties/?officeId=ROM&officeId=TER&officeId=BRA&officeId=LON&officeId=LES

Kindly check and let us know.

**Comment by plittlewood-rpt** [comment]
Hi @rajeshwl - yes this should work, you can pass multiple officeIds as you note above, so you are only really limited by the maximum length of the URL which from memory is 8192 characters. Bear in mind that this will end up getting converted into quite a large database query so what you may choose to do instead is to store the officeId map at your end, and call the API individually for each office, to limit the risk of any performance problems. This better future proofs your application as the customer organisation grows over time and doesn't really affect the way you'll be billed as you'd end up making around the same number of calls as the overall number of properties won't change. There'll be the odd difference when you don't get full pages back but that's likely acceptable in favour of a more performant application. Hope this helps
