### ISSUE TITLE
fromArchive incorrect on Vendor embedded contacts

### ISSUE THREAD

**Issue by robchett** [reapit/foundations#10616]
**Describe the bug**
fromArchive data is inconsistent on the related Contacts for an Vendor, one shows true, the other false.

**To Reproduce**
Using CustomerID YOM
See that /contacts/RAD18000024 is not archived
See that /vendor/RAD180020 shows RAD18000024 as archived.

**Expected behaviour**
The contact in the embedded objects to not be archived

**Additional context**
Looks to be related to https://github.com/reapit/foundations/issues/7728, but with Vendor not Applicant

**Specification**
- Project: Reapit.Services.Vendors
- Update `ContactLookupConverter` to set the fromArchive flag based on the location of the contact, NOT the relationship (lookuip). The PR from the linked item can be used as a reference

**Comment by robchett** [comment]
Would you mind confirming this for Landlord too when you get to it?

**Comment by cduggan-reapit** [comment]
Hi @robchett - I've had a quick check while working on this, and we don't surface any archive information in the Landlords API.
