### ISSUE TITLE
BER Information not coming through API

### ISSUE THREAD

**Issue by darraghmcgrath3** [reapit/foundations#10610]
Please take a look at our FAQ's before submitting an issue, as your question may already be covered in the documentation https://foundations-documentation.reapit.cloud/faqs

Hi there, a developer of ours is trying to pull BER information through the API using our (SFG) app Mood DS Service, but it isn't coming through. The request put through is ("/properties/?pageSize=25&pageNumber=1&sortBy=-modified&embed=images&embed=negotiator&officeId=" + officeId + "&sellingStatus=forSale&internetAdvertising=true&extrasField=pBERRating&extrasField=pBERNumber&extrasField=pEPI&extrasField=pBERExempt");. but the only thing visible under EPC is the below: 

![image](https://github.com/reapit/foundations/assets/118818916/c4e2932e-516d-4654-a736-a3e9a9765353)

Could you please advise why that isn't coming through? Thanks, Darragh

**Comment by AshDeeming** [comment]
Hi @darraghmcgrath3 
Please could you confirm the property ID the error is from?

**Comment by darraghmcgrath3** [comment]
Hi Ash,

There is no particular property, the developer is looking to pull BER information for all properties that the app is installed for, but does not receive BER information for any.

For example, the screenshot below is from the data received for BLA230076.

Many thanks,
Darragh


Darragh McGrath
Web Operations Executive
Sherry FitzGerald
Silverstone House, Ballymoss Road, Sandyford, Dublin 18, D18 A7K7

Direct: +353 1 237 6338
Mobile: +353 87 709 3553
Email: ***@***.***
Web: www.sherryfitz.ie

I have sent this email at a time that is convenient for me. I do not expect you to respond to it outside of your usual working hours.
​
Sign up to mySherryFitz now to book viewings, make offers, see existing bids, arrange property notifications and chat to us online – we’re here to help!
Click here to view the Sherry FitzGerald Privacy Policy
Please consider the environment before printing this email 
 
Sherry FitzGerald Group Ireland Holdings Limited. Registered in Ireland, CRO no 623927. 
Registered office: Silverstone House, Ballymoss Road, Sandyford, Dublin 18. D18 A7K7.
 
The contents of this e-mail are Subject to Contract /Contract denied. 
​
​This e-mail and any files transmitted with it are confidential and are intended solely for the use of the intended recipient. Any unauthorised direct or indirect dissemination, distribution or copying of this message and any attachments is strictly prohibited. If you have received this e-mail or any file attachment transmitted with it in error, please notify Sherry FitzGerald at ***@***.*** 
​
​This email has been scanned for computer viruses.
 
A part of the Sherry FitzGerald Group
Residential | New Homes | Lettings |  Mortgages

**Comment by AshDeeming** [comment]
Hi @darraghmcgrath3 
That particular property is exempt: 
![image](https://github.com/reapit/foundations/assets/61687775/0a5cec13-2145-48ca-91e6-1d5f2645c1b5)

**Comment by darraghmcgrath3** [comment]
Hi Ash,

That is correct, but you should still see the fields as blank, and a field called BERExempt marked as True. In this case, nothing is coming across. It is similar for DNL230208, which is not BER Exempt.

Thanks,
Darragh


Darragh McGrath
Web Operations Executive
Sherry FitzGerald
Silverstone House, Ballymoss Road, Sandyford, Dublin 18, D18 A7K7

Direct: +353 1 237 6338
Mobile: +353 87 709 3553
Email: ***@***.***
Web: www.sherryfitz.ie

I have sent this email at a time that is convenient for me. I do not expect you to respond to it outside of your usual working hours.
​
Sign up to mySherryFitz now to book viewings, make offers, see existing bids, arrange property notifications and chat to us online – we’re here to help!
Click here to view the Sherry FitzGerald Privacy Policy
Please consider the environment before printing this email 
 
Sherry FitzGerald Group Ireland Holdings Limited. Registered in Ireland, CRO no 623927. 
Registered office: Silverstone House, Ballymoss Road, Sandyford, Dublin 18. D18 A7K7.
 
The contents of this e-mail are Subject to Contract /Contract denied. 
​
​This e-mail and any files transmitted with it are confidential and are intended solely for the use of the intended recipient. Any unauthorised direct or indirect dissemination, distribution or copying of this message and any attachments is strictly prohibited. If you have received this e-mail or any file attachment transmitted with it in error, please notify Sherry FitzGerald at ***@***.*** 
​
​This email has been scanned for computer viruses.
 
A part of the Sherry FitzGerald Group
Residential | New Homes | Lettings |  Mortgages

**Comment by AshDeeming** [comment]
Thanks @darraghmcgrath3 
I'll tag our back end team to review in more detail

**Comment by plittlewood-rpt** [comment]
Hi @darraghmcgrath3, BER information can be found at `[root].regional.irl` in the PropertyModel. EPC information is for stock in England. Note that the property's country must be set correctly (Ireland) for this model to get populated. Please let me know if this doesn't answer your query.

**Comment by plittlewood-rpt** [comment]
Looking at the query above they are requesting the BER information as extrasFields, in which case they'll find them in the `extrasfield` collection on the property model. It's likely this was set up prior to the regional models being added, but they should see the same data in both places. It's preferable to use the regional models over the extrasField mechanism as it keeps the query strings a little lighter.

**Comment by plittlewood-rpt** [comment]
Hi @darraghmcgrath3 can you let me know if the above sorted your problem? Thanks

**Comment by darraghmcgrath3** [comment]
Hi @plittlewood-rpt , apologies, that solved the issue - many thanks for your help. Darragh
