### ISSUE TITLE
Additional Contact Details API issue related to MyAgency

### ISSUE THREAD

**Issue by Endlay** [reapit/foundations#10629]
It has been requested by AgentPoint to have a look if we could investigate why 'additionalContactDetails' does not exist for one specific client as they are unable to verify from their end. 

Following various attempts, it looks like the api sees no data to retrieve when the data is available. "the complete information both business phone and work phone in the Agency Cloud, from AP investigation in the API reveals only the presence of the work phone. This divergence in data is confusing, and unfortunately, we are unable to address it as it originates from the source."

We need your help to understand the root cause to this. 

Related ticket - https://reapit.atlassian.net/browse/PCQ-691

![image](https://github.com/reapit/foundations/assets/128380605/ebb93574-7cde-4c58-9748-51b74a6a0291)

**Comment by plittlewood-rpt** [comment]
HI @Endlay this is working as intended. The business number is exactly the same as the work number so the API considers it a duplicate and omits it from the response. It makes no sense to have the same number stored twice. Cheers

**Comment by Endlay** [comment]
thanks @plittlewood-rpt.
