### ISSUE TITLE
Adding Featured field to our data

### ISSUE THREAD

**Issue by will-yellowpeach** [reapit/foundations#10624]
**Summary**
Adding 'Featured' field to data received for Charters Estate Agents (CHR)

**Detail and or supporting links and screenshots**
Please can we request the same for Charters Estate Agents as per this related question: https://github.com/reapit/foundations/issues/10127

**Comment by will-yellowpeach** [comment]
Hi there,

They have this 'Featured property' tickbox in their property software (screenshot below) which they used to use when using the Reapit web service for their website (propertyhive). However since we've switched to Foundations, we can no longer see that Featured flag anywhere and it doesn't update the 'Featured' field in PH.

![Screenshot 2024-01-25 at 08 41 58](https://github.com/reapit/foundations/assets/64958924/20685521-6048-4e29-8401-1b0045ce14de)

**Comment by AshDeeming** [comment]
Thanks @will-yellowpeach 
The featured property tick box is not currently setup for CHR - This will need to be requested via the clients CRM or the Reapit Support Desk before we can action the Platform API side.

**Comment by AshDeeming** [comment]
Thanks @will-yellowpeach 
Access for this field has been set up via the API and should become active within the next 15 minutes.
Featured -> properties.pFeatured
