### ISSUE TITLE
Identification of a Sub Plot in a New Homes Development via Webhook

### ISSUE THREAD

**Issue by declanlawlor** [reapit/foundations#10622]
**Summary**
I'm currently trying to understand how we identify sub plots of a New Homes Development, when we receive the Webhook. 

**Detail and or supporting links and screenshots**
Taking Sub Plot `DNH220469` which is part of a New Development [DNH191667](https://platform.reapit.cloud/properties/?masterId=DNH191667)  for customer `SFG` as an example, when I inspect the payload received for `DNH220469`, I can't see anything that identifies it as part of this Development. 

Additionally, if I look at the payload for the parent `DNH191667`, I cannot see any way to identify it either. 

Apologies in advance, if I have missed something obvious. 

**Specification**
- Project: Reapit.Services.Properties
- Add new `string developmentSiteType`  property to PropertyModel with the following mapping

| prp.Site  | developmentSiteType |
| ------------- | ------------- |
| C  | subPlot  |
| M  | siteMaster  |
| blank/null | none |

We should ensure there are no other values that can be added to this field.
- New property should be readonly as there's no way to manage relationships through the API at present
- The solution above will allow webhooks to be configured to ignore any properties that are part of a development/site

**Comment by AshDeeming** [comment]
Hi @declanlawlor 
Please see the DepartmentID 
You may need to initially use the below config endpoint to check which departments are setup per client;
![image](https://github.com/reapit/foundations/assets/61687775/3cdd780d-18cc-4ec4-b943-650ca6d6b405)

https://foundations-documentation.reapit.cloud/platform-glossary#department

**Comment by declanlawlor** [comment]
Hi @AshDeeming, 

I don't quite follow. According to your link `The following table shows the values exposed in the type collection returned by the Applicant, Property, Department. So specifically wrt the Property API, the `type` field is not set to `developmentPlot` or `developmentOpportunity` (which I presume relate to New Homes). 

So to summarise neither the `Get Property API` or the Webhook that I receive when a property is created or modified, is indicating that the above is a new homes development. What am i missing here?

**Comment by AshDeeming** [comment]
Hi @declanlawlor 
Within the properties payload there will be a Department ID i.e;
![image](https://github.com/reapit/foundations/assets/61687775/b5cccc43-5463-441d-b090-bb74eab6b03d)
For the above example off SBOX - This is G - for General/Residential  (via Departments endpoint)

You will need to GET departments to check which of these are setup to New Homes - This will then provide you with a departmentID to differentiate between properties that have this departmentID verse those with G.

**Comment by declanlawlor** [comment]
Hi @AshDeeming 

Not quite there yet. 

Taking property `DNH230349` it is returning a `departmentId` of `S`. And querying the Department Data, I receive the following typeOptions 

```
 "typeOptions": [
                "house",
                "bungalow",
                "cottage",
                "flatApartment"
            ],

```
So this does not help in me identifying this is a unit of a New Homes development. 

Similarly, if I take the parent property that this unit is part of `DNH221102`, the `departmentId` is also `S`.

**Comment by AshDeeming** [comment]
Hi @declanlawlor 
I'll convert this ticket into a feature request for deeper review by the back end team

**Comment by declanlawlor** [comment]
Thanks @AshDeeming, we are in the middle of a rollout, and we do not want to process New Developments (parent or child) so would appreciate if one of the backend team can give me some clues. Appreciate your help!

**Comment by declanlawlor** [comment]
Hi @AshDeeming how long would it typically take for this ticket to be reviewed by the team. I'm just trying to plan a rollout and set time expectations, as I need to delay agents that have new developments to the end of our rollout.

**Comment by plittlewood-rpt** [comment]
Hi @declanlawlor. Sorry for the delay in getting a response back to you. At the moment there's no concrete way to do this via a webhook. The way the relationship is currently described is through the use of links which are added to the `_links` collection on the model returned from the properties. Links get deliberately stripped out from webhook events to keep the payload size down. We'll discuss this item in our refinement session today as it's a reasonable use case to add a `developmentUnitType` property to the model (or something similar) that describes master/subPlot more explicitly which can then be backed up by an appropriate query string parameter that allows you to filter subplots and master records out in your query

**Comment by declanlawlor** [comment]
Thanks @plittlewood-rpt - for now the most important thing for our rollout is to be able to determine if a property is either a) master b) subplot, so your suggestion around a `developmentUnitType` sounds good. The second part - to understand the relationship, ie. is subplot X is part of master Y is not as critical for us right now, but will be required in a few months.

**Comment by declanlawlor** [comment]
@plittlewood-rpt would it be safe to assume that new developments can currently be identified by `numberOfUnits` > 1?

**Comment by plittlewood-rpt** [comment]
Unfortunately not as that can be open to problems as agents might forget to fill it in. You are welcome to use that in the interim however it might not give reliable results across data sets. We've specd out this item so I'll see if we can get it in the next sprint which starts on Monday

**Comment by plittlewood-rpt** [comment]
@HollyJoyPhillips can we consider for Sprint 113 please?
