### ISSUE TITLE
Matching statuses (activity) between applications

### ISSUE THREAD

**Issue by Filip5991** [reapit/foundations#10620]
We were asked by mutual clients to try and match the statuses (activity) between our application (Acaboom) and the app we have built in the Foundations system. As we weren't exactly sure what belongs under statuses in Reapit, a client suggested opening a ticket may help identify those (and if the API caters for marrying these).
Exploring the API docs, I saw that each property has a "status" field (one example value for this is 'underOffer').
In the RPS - Developer app, I also saw a few properties called statuses:
![image](https://github.com/reapit/foundations/assets/23519137/158c031b-6649-4203-88fc-53d7f8e3f4c0)
Are those statuses 'standard' and if so what are the possible options, or can they be amended by the client?

One client asking for this seems to be focused on an offer (i.e. an amount to buy or rent the property) being made rather than pre-marketing. 

Can you please shed some light on what we are after, or maybe something we can ask the client to help clarify this?

**Comment by AshDeeming** [comment]
Hi @Filip5991 
The statues referred to above i.e. under offer, are against the property however the screen shot is from the offers information & can be found under the offers endpoint;
![image](https://github.com/reapit/foundations/assets/61687775/0ef3f62f-bbdb-41d3-8cdd-a4fe7e6b0e5f)

Does that help clarify?

**Comment by Filip5991** [comment]
Hi @AshDeeming ,
It was mentioned to us that Foundations has a completely different range of status names and most seem to be relating to whether a property is available or under-offer etc. rather than pre-marketing. 

So I think the question is what status names does Foundations have relating to an appointment booked, pending, lost, won, etc. and where can these be found?

**Comment by AshDeeming** [comment]
Hi @Filip5991 
Property statues do have two differing options wtihin the CRM, which mean the same thing within the Industry -  Under Offer  aka SSTC

All other statues should be universal & can be found via the swagger model under each relevant endpoint

Properties: 
(Lettings) 
![image](https://github.com/reapit/foundations/assets/61687775/e740c01d-c059-4b2a-8716-8077afd83030)
(sales)
![image](https://github.com/reapit/foundations/assets/61687775/8f4898f1-ddd9-4750-bc69-381f25fb7f56)

Offers: 
![image](https://github.com/reapit/foundations/assets/61687775/47296d91-5b72-456b-92a6-66cf82dc63e4)

Appointments can relate to a multitude of reasons, if you wish to segment these based on their type, please note that the configuration endpoint to call the below will be required re appointment typeID
![image](https://github.com/reapit/foundations/assets/61687775/f52ee7bb-8fde-47a2-986e-6a043b70e8ea)

**Comment by Filip5991** [comment]
Hi Ash,
I don't think appointment types, nor offers statuses are what we are after. The 'offers' values don't sound right, as by that time the property has been marketed and thus 'won' in our world.
Are there any other statuses that relate to a market appraisal point in time only - e.g. won, lost, pending, withdrawn etc.?
We are really after the property status i.e... are there any statuses that relate to the property for a market appraisal?

**Comment by AshDeeming** [comment]
Hi @Filip5991 
For property statues, the below can be used to segment - the highlighted are values would represent a property is that is yet to be marketed. 

![image](https://github.com/reapit/foundations/assets/61687775/e30914b1-0321-4011-a046-c22da035c3ee)

**Comment by Filip5991** [comment]
Hi @AshDeeming 
Apologies for the delayed response, it's been a crazy period :-)

If the selling/lettingStatus is what we need, what would be the best way to track all status updates of a property? I can see there are multiple webhooks available, like 'properties.selling.withdrawn' or 'properties.selling.instructed', but I don't think these fully match the statuses from your image? Plus I don't see any 'properties.lettings' webhooks? We are interested to capture every status change and pass it to our system, but I'm not sure if the status changes can be tracked with a webhook at all. Maybe the 'properties.modified' webhook also includes selling/letting status updates?

**Comment by AshDeeming** [comment]
Hi @Filip5991 
No problem, hope things calm asap for you

The webhooks mentioned above relate to the standard subject available - it may be useful to build event filters, which allow you to filter which elements of the payload you're interested in; 
https://foundations-documentation.reapit.cloud/api/webhooks#building-event-filters

**Comment by Filip5991** [comment]
Hi @AshDeeming , 
I was planning to include an event filter anyway, but I wasn't sure with which webhook to start. Do we need to use the 'properties.modified' webhook, and then somehow build JSON schemas and filter the hook to only retrieve selling/letting status updates?
Also, are there any instructions out there on how to build the event filter outside of https://json-schema.org/?

Thank you in advance :)

**Comment by AshDeeming** [comment]
Hi @Filip5991 
Apologies for the delay - the modified webhook could be used 
The previously provided docs link is the relevant section - please let us know if more assistance required?
