### ISSUE TITLE
Update v1 & v1.5 Reapit Connect logo

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#10628]
**Task**: 
- Update Reapit Connect logo on dev (v1.5) and prod (v1). AC (beta) and RC email templates are already using the new logo 
![Reapit Connect RGB](https://github.com/reapit/foundations/assets/52408607/ecaf49c3-c712-40f0-a2d6-88ffea8a9d64)

**Comment by plittlewood-rpt** [comment]
v1 completed
