### ISSUE TITLE
Access request for pClosingDate

### ISSUE THREAD

**Issue by AdamHall12** [reapit/foundations#10637]
**Request**

In order for us to grant access to Semi-structured 'extras' field data, please provide the following information in this request:

- The name of the customer you represent: Rettie & Co. RET
- The name of every field you need surfaced (if known) pClosingDate
- A screenshot of of the field(s) you require in the agency cloud user interface
- A short use case as to why you require this data. For use in an internal App.

**Comment by soilleir** [comment]
@plittlewood-rpt  its Graham from Rettie.  We need this exposed to be able to move an internal app across in time for the AWS move on Monday 5th.  Whilst it  isnt critical to have this live by then we will need pClosingDate available in the endpoint shortly afterwards

**Comment by plittlewood-rpt** [comment]
@AshDeeming please can you pick this up.

**Comment by AshDeeming** [comment]
Hi @soilleir & @AdamHall12 
Access for the field mentioned above has been set up and should become active within the next 15 minutes.

properties.pClosingDate
