### ISSUE TITLE
Fields request for Michael Graham

### ISSUE THREAD

**Issue by MarcinuB** [reapit/foundations#10632]
Hi Team.
Just a quick Semi-structured 'extras' field request: 

 - Customer: Michael Graham
 - Field: Marketing - Situation
-  Field: Marketing - Advert Bullets

- Use Case: To use with FluxPro interactive brochures.

Thank you kindly

**Comment by AshDeeming** [comment]
Hi @MarcinuB 
Access for the fields mentioned above has been set up and should become active within the next 15 minutes.
Situation - properties.pSituation
Advert Bullets - properties.pAdvbp

As per any other semi structured data you access it using the extrasField query string parameter eg;
GET /properties?extrasField=properties.pAdvbp

**Comment by MarcinuB** [comment]
Hi @AshDeeming 
Thank you for a quick turnaround.

Have a good weekend
Marcin
