### ISSUE TITLE
Multi-Lingual User Interface

### ISSUE THREAD

**Issue by SMollins** [reapit/foundations#10644]
**Is your feature request related to a problem? Please describe.**
We would like to expand our usage of Agency Cloud to multiple countries, but are limited because the UI can only display in English. 

**Describe the solution you'd like**
We'd like to be able to use the API to re-label the UI in Agency Cloud to use other languages, primarily Spanish, Italian, French and German.

**Describe alternatives you've considered**
We have tried using the 'translation' tool with Spanish in Spain, but this isn't as comprehensive as we would require (and results in some very  'Span-glish' wording in drop-down menus!). No other options are available to us.

**Additional context**
I will be in Rome later this week, so would be grateful for a heads up ASAP. If there is a solution to be found using the API, then there is a strong possibility we will look to roll out Reapit as our primary Resi CRM globally, so this does represent a huge opportunity for Reapit, if we can make it work!

**Comment by plittlewood-rpt** [comment]
Hi @SMollins there is no capability in the API at present, however I'll get this in front of the product team for you.

**Comment by HollyJoyPhillips** [comment]
@neilpellowe FYI

**Comment by neilpellowe** [comment]
Discussed with client. This isn't something we will look to do in the short term, but we have added discovery item for Later against our digital product roadmap. 

This request can be closed
