### ISSUE TITLE
Add pDirections access to Chapplins

### ISSUE THREAD

**Issue by Simon-Homeflow** [reapit/foundations#10646]
**Request**

- Chapplins: all three instances (TEA-GCHF, TEA-GCJL, TEA-GCHH)
- pDirections to be surfaced
- Screenshot attached
- Required to migrate client from legacy feed to RFPF
![image](https://github.com/reapit/foundations/assets/119927358/dd008ded-2602-4845-86cd-60b4c0faabe9)

**Comment by plittlewood-rpt** [comment]
Hi @Simon-Homeflow this field has now been added and should be available in the next 15 minutes. Include the field in your responses by including the `extrasField` query string parameter in your request with the value `pDirections` eg

`GET platform.reapit.cloud/properties?extrasField=pDirections` 

and/or

`GET platform.reapit.cloud/properties/ABC123456?extrasField=pDirections`
