### ISSUE TITLE
Investigate 'Loop Limit Exceeded' error reported by Sentry 

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#1064]
**Describe the bug**
Sentry is reporting an error for the 'Dropdown' select component on the 'Submit' app form in the Developers Portal. 

**Task:** To investigate why the 'Agency Cloud Intergeration' downdown select component is logging these errors in Sentry. 

**Sentry Log:** https://sentry.io/organizations/reapit-ltd/issues/1614369493/?project=1885603&referrer=slack
 
**Error:** ResizeObserver loop limit exceeded

![image](https://user-images.githubusercontent.com/52408607/80079720-8f81a800-8548-11ea-83c8-dce72dfb2841.png)

![image](https://user-images.githubusercontent.com/52408607/80079668-7f69c880-8548-11ea-988c-458250bab3f5.png)

**Comment by tanphamhaiduong** [comment]
I cannot replicate it on marketplace dev

**Comment by tanphamhaiduong** [comment]
Moving back to Ready to Dev for keep track, Since I cannot replicate the bug

**Comment by tanphamhaiduong** [comment]
@willmcvay @HollyJoyPhillips could we close this issue because I still cannot replicate it
