### ISSUE TITLE
Possible Duplicate Tenant data

### ISSUE THREAD

**Issue by raymond2323** [reapit/foundations#10643]
Production Client Customer ID: JOR

We are fetch Tenancy with ID NEL240106

the Related response is the following (redacted some of the sensitive info)

`[{"id"=>"NEL24000257", "name"=>"Mr "XXXXX", "title"=>"Mr", "forename"=>"XXX", "surname"=>"XXX", "dateOfBirth"=>nil, "type"=>"contact", "homePhone"=>nil, "workPhone"=>nil, "mobilePhone"=>"07949068572", "email"=>"[XXXXX](XXXXXX)", "paymentReference"=>nil, "fromArchive"=>false, "primaryAddress"=>{"buildingName"=>"", "buildingNumber"=>"XX", "line1"=>"Masefield Crescent", "line2"=>"Abingdon", "line3"=>"Oxfordshire", "line4"=>"", "postcode"=>"XXXX", "countryId"=>"GB"}, "additionalContactDetails"=>nil}, {"id"=>"NEL24000257", "name"=>"XXXX", "title"=>"Mr", "forename"=>"XXXX", "surname"=>"XXXXX", "dateOfBirth"=>nil, "type"=>"contact", "homePhone"=>nil, "workPhone"=>nil, "mobilePhone"=>"07949068572", "email"=>"[XXXXXX](mailto:XXXXX)", "paymentReference"=>nil, "fromArchive"=>false, "primaryAddress"=>{"buildingName"=>"", "buildingNumber"=>"XX", "line1"=>"XXXX", "line2"=>"Abingdon", "line3"=>"Oxfordshire", "line4"=>"", "postcode"=>"XXXX", "countryId"=>"GB"}, "additionalContactDetails"=>nil}, {"id"=>"NEL24000258", "name"=>"XXXXX", "title"=>"Miss", "forename"=>"Julia", "surname"=>"Kobet", "dateOfBirth"=>nil, "type"=>"contact", "homePhone"=>nil, "workPhone"=>nil, "mobilePhone"=>"XXX", "email"=>"[XXXXXXX](mailto:XXXXXX)", "paymentReference"=>nil, "fromArchive"=>false, "primaryAddress"=>{"buildingName"=>"", "buildingNumber"=>"", "line1"=>"", "line2"=>"", "line3"=>"", "line4"=>"", "postcode"=>"", "countryId"=>"GB"}, "additionalContactDetails"=>nil}]`

Why is the tenant with ID NEL24000257 duplicated in the response?

**Comment by plittlewood-rpt** [comment]
Hi @raymond2323 thanks for raising this. I've resolved the issue which was being caused by a duplicate role record for that contact. I've flagged it with the CRM team to try and establish how it got there in the first place, but you should only see that contact listed once on this tenancy now.
