### ISSUE TITLE
LSLi Selling Reason

### ISSUE THREAD

**Issue by BYMIntegrations** [reapit/foundations#10642]
Hello Support,

I am looking into an issue with getting selling reasons from the API for LSLi.

We are getting the following error:

{"statusCode":500,"dateTime":"2024-01-29T00:07:02.8506084Z","description":"An unexpected error has been encountered when fulfilling this request. This incident has been logged and will be investigated. Please try again."}

If you have any questions, then please let me know 🙂

Thanks,

Toby Hunter
Integrations and Support Analyst

+44 1332 423356 | [TobyH@briefyourmarket.co.uk](mailto:TobyH@briefyourmarket.co.uk)
[www.briefyourmarket.com](http://www.briefyourmarket.com/)

**Comment by AshDeeming** [comment]
Hi @BYMIntegrations 
Please could you confirm what request is being made to return this error?

**Comment by plittlewood-rpt** [comment]
Hi @BYMIntegrations this should be resolved. It was caused by some misconfiguration in the client system. Thanks

**Comment by plittlewood-rpt** [comment]
Logged internal ticket ACT-856 to look at preventing the bad configuration in the CRM itself
