### ISSUE TITLE
AgencyCloud displays hosted UI instead of our UI at application startup

### ISSUE THREAD

**Issue by plittlewood-rpt** [reapit/foundations#10657]
**Background context**
When AgencyCloud is loaded, it calls the logout endpoint with a redirect_uri instead of a logout_uri which is a [documented approach](https://docs.aws.amazon.com/cognito/latest/developerguide/logout-endpoint.html) in the AWS docs. This is currently resulting in a redirect by Cognito back to the hosted UI. We need to intercept this in the logout Lambda handler and ensure the user gets directed back to the custom UI instead.

![image](https://github.com/reapit/foundations/assets/30798627/2c36d044-aa04-42be-be2f-ab325fdd9e95)
AgencyCloud loaded against connect.dev.paas.reapit.cloud

**Specification**
- Package: /packages/federation-endpoints/src/endpoints/logout/
- Pass cognito URL down to this lambda and strip it off the front of the redirect URL prior to redirecting the user. This should ensure that users are redirected based on the custom domain (connect.dev.paas.reapit.cloud in the case of the dev environment)

**Comment by joshbalfour** [comment]
@plittlewood-rpt is this still an issue?

**Comment by plittlewood-rpt** [comment]
I have retested this and aren't seeing the same behaviour so will close this item down
