### ISSUE TITLE
Countrywide - John D Wood

### ISSUE THREAD

**Issue by BYMIntegrations** [reapit/foundations#10658]
Hello Support,

I hope you are well.

We have been asked to set up the John D Wood data for countrywide. However, we haven't been able to locate it in either code we have:

CWO-GBTG
ABB-GBTG

Please can you confirm where the data exists? If it needs a new installation can we get that organised?

If you have any questions, then please let me know 😊 
 
Thanks, 
 
Toby Hunter 
Integrations and Support Analyst 
 
+44 1332 423356 | [TobyH@briefyourmarket.co.uk](mailto:TobyH@briefyourmarket.co.uk)
[www.briefyourmarket.com](http://www.briefyourmarket.com/)

**Comment by AshDeeming** [comment]
Hi @BYMIntegrations 
Please could you confirm that a contact to John Wood has installed the required app - I'm unable to see a current install for JDW

**Comment by BYMIntegrations** [comment]
Hello Ash,

From what we have been told, Countrywide have no admin users so they wouldn't be able to install it.

If this is not the case then can you send me the name or email of an admin user for JDW?

Thanks,

Toby

**Comment by AshDeeming** [comment]
Thanks @BYMIntegrations 

Jamie Roberts is the admin - I believe CWD will liaise directly with yourselves to progress.
