### ISSUE TITLE
Create CRON to purge S3 buckets based on commit hash

### ISSUE THREAD

**Issue by willmcvay** [reapit/foundations#1065]
**Background context or User story:**

_We get occasional chunk missing errors in dev when we deploy because currently we replace the content of a bucket with the new deployment. If a user has a session, the script will be missing when they navigate. eg of this behaviour https://sentry.io/organizations/reapit-ltd/issues/1623235951/?project=1885603&referrer=slack_

**Specification or Acceptance Criteria:**

- We should support at least 2 recent versions of each app in an S3 bucket. 
- We should update our webpack scripts so the master HEAD commit hash is prepended to the output script file names. This means we can identify the scripts by release
- We should have a CRON job that runs weekly to purge all S3 buckets of all but the last two releases by most recent commit hash.

**Comment by phmngocnghia** [comment]
We have dicussed about using service-worker, offline-plugin API to check if the assets have been changed to do a refetched-navigation and agreed to try this method: https://zach.codes/handling-client-side-app-updates-with-service-workers/

The service worker implemented by the lib “offline-plugin” (we are currently using it) allows us to detect when the new code is out by checking the status of the manifest file automatically every X time, or checking it manually, then we can use that info to do a re-fetched navigation when the user changes their route

**Comment by willmcvay** [comment]
- Had to remove S3 Cron file, this needs re-instating. 

Also;

- When a new release is available and I click on the button, throws this error: https://sentry.io/organizations/reapit-ltd/issues/1636945628/?referrer=slack
- When I have clicked on the new release button, the toast should submit. Doesn't currently in dev which could be linked to the error
