### ISSUE TITLE
Access to Tenant Tracker

### ISSUE THREAD

**Issue by katedeedman** [reapit/foundations#10655]
Hi Reapit,

We have a demo with a potential new client next week. They've requested to see the Fixflo <> Reapit integration via the Tenant Tracker. We don't have access to one so I wondered if you had a test one that I could use? They just want to see the issue being raised from within the Tracker. We can then demonstrate the issue being progressed through Fixflo & into our Reapit sandbox. 

Thanks in advance!

-Kate

**Comment by AshDeeming** [comment]
Hi @katedeedman 
Please could you provide more information regarding the 'tenant tracker' 
If you're looking to test your app via SBOX the 'Fixflo - Advanced Integration' is currently showing as installed

**Comment by Endlay** [comment]
@plittlewood-rpt

**Comment by plittlewood-rpt** [comment]
Hi @neilpellowe. After speaking with  @Endlay it sounds like you might already be in a separate conversation about this. Are you OK to pick this up with Kate please?

**Comment by neilpellowe** [comment]
Hi Kate,

I’m going to book a call with you and End’Lay who is the Product Owner for My Agency. I’ll send the invite over shortly.

From: katedeedman ***@***.***>
Sent: Thursday, February 1, 2024 9:24 AM
To: reapit/foundations ***@***.***>
Cc: Neil Pellowe ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [reapit/foundations] Access to Tenant Tracker (Issue #10655)

External Message - Please be cautious when opening links or attachments in email
________________________________
Thanks all!

Apologies, I meant the MyAgency app... I'm stuck in the past with Tenancy
Tracker.

I've got some help articles for now but a demo account would be great.

Let me know if you need anything else from me or have any other questions.

-Kate
