### ISSUE TITLE
Your Move Scotland are missing the cloud icon to access applications

### ISSUE THREAD

**Issue by NathanTLH** [reapit/foundations#10651]
We have had reported to us that our customer is no longer able to access the cloud icon to access The Lettings Hub application through the tenancy screen. They have reported that they used to have this but are now unable to see the cloud.

can this please be investigated so that they can use the applications that they have attached to their account.

**Comment by AshDeeming** [comment]
Hi @NathanTLH 
Could you confirm which user(s) this has impacted - any sensitive info can be sent to: support@reapitfoundations.zendesk.com
Thanks in advance

**Comment by NathanTLH** [comment]
Thanks @AshDeeming  - i have provided details to the email address. 
thanks

**Comment by AshDeeming** [comment]
https://reapitfoundations.zendesk.com/agent/tickets/1015
