### ISSUE TITLE
Request for "Featured property" field

### ISSUE THREAD

**Issue by reech-dev** [reapit/foundations#10659]
**Request**

Hi, we require access to the "Featured property" field that is accessed through the "extrasField" parameter.

- Balfours
- "featured property"
- <img width="1039" alt="Screenshot 2024-02-01 at 13 33 48" src="https://github.com/reapit/foundations/assets/119589001/968f2a3e-5580-4676-b05b-61afb0c36878">  <img width="315" alt="Screenshot 2024-02-01 at 17 05 26" src="https://github.com/reapit/foundations/assets/119589001/1735d043-137f-4e20-8200-fe88846635f4">

- Currently, the client is manually setting this value every month in their website and through Reapit as it is not available in the API. As a solution we would like to be able to automate this process so that it's pulled directly from the Reapit API and updates the website accordingly.

**Comment by AshDeeming** [comment]
Hi @reech-dev access for the field mentioned above has been set up and should become active within the next 15 minutes.
pFeaturedPrp

As per any other semi structured data you access it using the extrasField query string parameter eg;
GET /properties?extrasField=properties.pFeaturedPrp

**Comment by reech-dev** [comment]
> ?extrasField=properties.pFeaturedPrp

@AshDeeming We've just tested this in Postman and we're getting the following error:

> GET https://.../properties/?extrasField=properties.pFeaturedPrp
```json
{
    "statusCode": 400,
    "dateTime": "2024-02-02T16:55:26.761198Z",
    "description": "Access to one or more of the specified fields is not permitted. You must be granted access to this data beforehand"
}
```

Could you take a look and see if it's available for us to query?

**Comment by AshDeeming** [comment]
Hi @reech-dev 
The additional flag (pFeaturedPrp) is in place, it may have related to the session - Could you confirm if this is now obtainable?

**Comment by reech-dev** [comment]
Hi @AshDeeming - We've just cleared the session and generated a new token and we're still getting the 400 error.

```json
"description": "Access to one or more of the specified fields is not permitted. You must be granted access to this data beforehand"
```

**Comment by plittlewood-rpt** [comment]
Hi @reech-dev your extrasField query string parameter should just be "pFeaturedPrp"  (without the properties. prefix) - sorry for the confusion

**Comment by HollyJoyPhillips** [comment]
As the comment above has provided the required information we will now close this ticket. Please reach out if you have any further questions/issues.
