### ISSUE TITLE
Provide an endpoint which returns weather data for a given location

### ISSUE THREAD

**Issue by adrian-reapit** [reapit/foundations#10666]
We would like to get weather data from an API such as https://www.weatherapi.com/

It would be helpful to have a proxy endpoint to weatherapi which keeps the API key hidden so that non Reapit users can't use it

The endpoint should accept weather api format payloads and forward it on. Short term caching of weather api data can be considered  but the weather api cost is relatively low so caching may not be worthwhile

**Comment by plittlewood-rpt** [comment]
HI @adrian-reapit can you let me know what the use case for this is please? Seems a bit odd

**Comment by HollyJoyPhillips** [comment]
@neilpellowe to speak with @adrian-reapit as this isn't a Platform feature request.
