### ISSUE TITLE
Additional Flag not visible in API

### ISSUE THREAD

**Issue by darraghmcgrath3** [reapit/foundations#10664]
Hi there, we have added an Additional Flag to our Head Office group/properties, but cannot see the field under the extras in the API. Does the call need to be amended to pull this? Thanks, Darragh

![image](https://github.com/reapit/foundations/assets/118818916/18d462d7-3fbd-494d-afa7-4459e697748b)

![image](https://github.com/reapit/foundations/assets/118818916/53e6880d-27e4-4d19-ae54-b45711c18690)

**Comment by AshDeeming** [comment]
Hi @darraghmcgrath3 
Once the field has been added in the Reapit CRM - we need to enable via the API semi structured data too. Could you confirm the client name or ID for this request/database please?

**Comment by darraghmcgrath3** [comment]
Thanks, Ash. The app is Mood DS Service. The customer ID is SFG, we have only added it for the office HEO in the Marketplace Management group SFG-GHEO, but will be adding it to several office groups once tested. Does that need to be enabled for each office group separately?

**Comment by AshDeeming** [comment]
Thanks @darraghmcgrath3 
The below extra field has been enabled for SFG - These are set at organisation level, so should be available for both org and/or OfficeGroup levels. 

properties.pDisplay

**Comment by darraghmcgrath3** [comment]
Thanks @AshDeeming! Will that come through on the regular properties call or does that need to be amended?

**Comment by AshDeeming** [comment]
Apologies @darraghmcgrath3 I should have said previously, as with any other semi structured data you access it using the extrasField query string parameter eg; GET /properties?extrasField=properties.pDisplay

**Comment by darraghmcgrath3** [comment]
Thanks a mill, @AshDeeming
