### ISSUE TITLE
DataWarehouse Tenancies Table - Finished Reason only Available when Tenancy Finished'

### ISSUE THREAD

**Issue by kmacgregorPR** [reapit/foundations#10670]
Within the Tenancies Table, the 'Finished Reason' only pulls through the information upon the tenancy status being 'finished'. We need to see the finished reason when the tenancy has had its 'end confirmed' but is still 'current' - i.e. using this to track upcoming tenancy end dates were a notice has been served as the reason for the tenancy ending for example. Attached screenshot showing blank area. 

Also attached a record which has the finished reason in reapit as 'Landlord served S21 Notice' but is still current (with end confirmed as yes) but is not pulling the reason through. Please could this be adjusted so we can see this reason for a tenancy if it has one no matter the tenancy status?
<img width="1082" alt="DataWarehouse 2" src="https://github.com/reapit/foundations/assets/128388971/69df9315-9e4e-4498-b9f9-a9c6f89f1f4b">
<img width="1117" alt="DataWarehouse" src="https://github.com/reapit/foundations/assets/128388971/b868010c-2a54-441a-a0f5-db7ec7d6b46e">

**Specification**
- Project: Analytics Schema
- Update the TENANCIES view model to always populate the existing FINISHED_REASON column whenever it is present. This allows it to cater for situations where the reason is entered prior to the tenancy moving to a finished/cancelled state
- Update the commentary on this field accordingly

**Comment by AshDeeming** [comment]
@neilpellowe
