### ISSUE TITLE
API field location for "Exchange Due" in offer section?

### ISSUE THREAD

**Issue by ss-dimasm** [reapit/foundations#10674]
**Summary**
Hi, where can I get the value of "Exchange Due" field in Offer section (AgencyCloud)? I could see the field at AgencyCloud but after looking forward in Offer and Conveyancing services I can't find it, thanks

**Detail and or supporting links and screenshots**
![image](https://github.com/reapit/foundations/assets/96416644/d64e7274-2990-4060-989d-6e19bbdb16ee)

**Specification**
Project: Reapit.Services.Offers
- Add support for semi-structured data 
- Add offers.fExchange to customer config (customer org ID tbc - see comments)

**Comment by AshDeeming** [comment]
Hi @ss-dimasm 
This is stored within the properties payload:
![image](https://github.com/reapit/foundations/assets/61687775/b6488807-fa1b-4ff8-ab42-87d3ce97ed6a)

**Comment by ss-dimasm** [comment]
Hi @AshDeeming , I have try to check this and unfortunately it's not showing the value that I've set on Property -> Offers ->  Offer -> Exchange Due

**Comment by ss-dimasm** [comment]
yes it's read only @HollyJoyPhillips

**Comment by HollyJoyPhillips** [comment]
Hi @ss-dimasm thank you for confirming. This will need to be added as a semistructured field (extra field) but we don't currently support extra field data in the offers endpoints. 
We'll move this to refinement for a specification to be added. Thanks.

**Comment by HollyJoyPhillips** [comment]
@ss-dimasm Please can you confirm the customer ID this is for?

**Comment by ss-dimasm** [comment]
I believe it's for SBOX and ROD at this moment, @craigforrest is there any cus ids that we could have more?

**Comment by craigforrest** [comment]
Not at the moment @ss-dimasm.

@HollyJoyPhillips Just for context this is for the app being built as part of the Reapit Digital 'Plus' mobile project. It's not a must have as we just want to give a brief detail of an offer as part of an 'activity' pane and if there is a bigger technical concern than just adding an API call for a field we can revisit the requirement and see if there is an alternative.

**Comment by HollyJoyPhillips** [comment]
Hey @craigforrest thank you for the context. We can expose this field using semi structured data but it would need to be requested per customer going forward, as it's added to the customers config once we add support on the offers API. 

We'll review on refinement to estimate how much work is involved and I'll reach out after to see if you want to proceed.

**Comment by HollyJoyPhillips** [comment]
Agreed with @craigforrest to close for now due the structure of the data and the need to request this information per customer until addressed. Can re review if the requirements comes up again.
