### ISSUE TITLE
Auto responder email from Reapit for appointments made via API

### ISSUE THREAD

**Issue by wtienzo** [reapit/foundations#10680]
**Describe the bug**
We are moving our website from  RDA [https://tracker.reapit.net/demo/_demo/rda/] for viewing appointments to using the foundations API.

However the auto responder email we are getting from Reapit when we made the appointment from foundations API is not the same as what are getting from RDA. 

See below the email on the left was received when the viewing appointment was made via RDA and the email on the right  was recieved when the viewing was made via foundations API.

![Foundations (1)](https://github.com/reapit/foundations/assets/28800868/c993dd0b-3010-475e-822d-1f9054d75e70)

How can we get Reapit to send out the same auto-responder email as the one from RDA.

**Comment by plittlewood-rpt** [comment]
Hi @wtienzo are you sending that email from your own system? There is nothing in Foundations itself that will send automatic emails out like the above so we may need to go on the hunt here. If you are sending the email yourself, do you just need the template that RDA sends?

**Comment by plittlewood-rpt** [comment]
Would you be able to forward the two emails in your screenshot over to our zendesk address so I can track down what generated them? I'm a bit confused at the moment by the second one as to it's origin. sinfo@reapitfoundations.zendesk.com

**Comment by plittlewood-rpt** [comment]
Hi @wtienzo I've just responded on Zendesk. Sorry for the delay picking this one up

**Comment by plittlewood-rpt** [comment]
Hi @wtienzo I'll close this item down now we've got a thread running on Zendesk. Thanks
