### ISSUE TITLE
Not able to verify the Webhook signature

### ISSUE THREAD

**Issue by CarlosEspinoTimon** [reapit/foundations#10695]
**Describe the bug**
Hi.

We are about to integrate with Reapit.

We are trying to create a Webhook so Reapit can notify us about certain events, however, we are not able to verify the signature.

We have tried to verify it with Python and after failing, we tried with the NodeJS example in the Cryptographic Signing in the [Securing your endpoint section](https://foundations-documentation.reapit.cloud/api/webhooks#securing-your-endpoint), however, we are still not able to verify the signature and we are wondering what are we doing wrong.

**To Reproduce**
Steps to reproduce the behaviour eg:
1. Create the local Node JS server and put this code
```javascript
const express = require('express');
const crypto = require('node-forge');
const bodyParser = require('body-parser');

// Configure Express
const app = express();
const port = 5000;

// Be sure to read the raw request body, rather than
// using a JSON pre-processor/JSON.stringify()
app.use(bodyParser.raw({ inflate: true, type: 'application/json' }));

// Setup POST handler
app.post('/', function (req, res) {
    const ED25519 = crypto.pki.ed25519;

    // Read the X-Signature header
    const sigHeader = req.header("x-signature");
    const sigParts = sigHeader.split(":");
    
    // Read the signature segments
    const keyId = sigParts[1];
    const timestamp = sigParts[2];
    const signature = sigParts[3];

    // The message to verify is a concatenation of the timestamp (from the X-Signature header)
    // and the raw request body, with no delimiting characters
    const msgToVerify = `${timestamp}${req.body.toString()}`;

    // Retrieve the public key from the respective endpoint
    // or store OUTSIDE your code. This is an example only
    const publicKeyBase64 = "TO_BE_FILLED_ONCE_WE_CREATE_THE_WEBHOOK _IN_REAPIT";

    // Verify the signature
    const verified = ED25519.verify({
        message: msgToVerify,
        encoding: "utf8",
        signature: Buffer.from(signature, "base64"),
        publicKey: Buffer.from(publicKeyBase64, "base64")
    });

    if (verified) {
        console.log("Signature is valid");

        // Continue to process webhook
    }
    else {
        console.log("Signature is invalid");
    }

    res.send("Webhook processing complete");
});

// Start the server
app.listen(port, () => {
    console.log(`Now listening on port ${port}`);
}); 
```
2. Create the Webhook in the Developer Portal, point it to your local server
This is how is configured
![image](https://github.com/reapit/foundations/assets/9631836/7cf9c175-a67a-473b-82e6-19657a4768de)

3. Click on `Copy Public Key`
![image](https://github.com/reapit/foundations/assets/9631836/3a415089-bbdd-48fa-9680-00bdb3df2553)

The copied key is this:
```
{ "kid": "08dc2709-c52b-4a3a-8c2d-895d6d928d3e", "crv": "Ed25519", "x": "VCuHwZpt8LBv2JNdF8ZD0C_OAbejv8-J4BKDqPEuLg8" }
```

4. Take the `x`  from the Public Key and put it as the `publicKeyBase64` in the NodeJS server
5. `Ping` the webhook
6. The `Signature is invalid`
![image](https://github.com/reapit/foundations/assets/9631836/c67c871f-2d6f-4b66-b3d4-ef4b1f9aa795)

We see how Reapit is able to reach out to our webhook but the `Signature is invalid`

**Expected behaviour**
To be able to verify the signature and see the `Signature is valid` message

**Device (please complete the following information for web issues):**
- NodeJS server in v21.6.1 (I also tried initially with v16.13.1)

Thank you very much for your time! :smile:

**Comment by plittlewood-rpt** [comment]
Hi @CarlosEspinoTimon please can you confirm the name or id of the app your webhook is associated with?

**Comment by CarlosEspinoTimon** [comment]
Hi @plittlewood-rpt , the app_id is `b0365e96-4c7a-4635-8891-5d522ddfc77c`

**Comment by plittlewood-rpt** [comment]
Hi @CarlosEspinoTimon thanks for confirming - I've set up a webhook to a test endpoint to validate the behaviour on your account - this will be removed shortly. From my tests it looks like this is just a bug with the ping functionality. Can you confirm if you are encountering the same issue if you process a 'real' Sandbox event?

**Comment by CarlosEspinoTimon** [comment]
Hi @plittlewood-rpt 

Yes, I have tried with a "real" Sandbox event and it works :partying_face: 

Thank you very much for your help 

Have a great day!

**Comment by plittlewood-rpt** [comment]
No problem. I'm going to reopen this as we should fix the bug with the ping endpoint. @HollyJoyPhillips FYI
