### ISSUE TITLE
Match Price From and Match Price To for Michael Graham

### ISSUE THREAD

**Issue by MarcinuB** [reapit/foundations#10693]
Hello Team.

Can you enable Match Price From and Match Price To fields from Financial and Agency Information for Michael Graham?

![image](https://github.com/reapit/foundations/assets/8589350/2d63bb5a-e857-44d7-b1c5-e79f4220aec5)

Thank you.

**Comment by MarcinuB** [comment]
Hi @AshDeeming - what is the ETA for this request?

**Comment by HollyJoyPhillips** [comment]
Hi @MarcinuB we have another ticket requesting the same information which you can follow here https://github.com/reapit/foundations/issues/10556

In brief, we are waiting for details from the desktop team if the location of the data is likely to change. Once we have confirmation we will be able to expose this information via the API. I'll close this ticket as it's a duplicate so please feel free to subscribe to 10556. Thanks.
