### ISSUE TITLE
Cannot find contact when searching via email

### ISSUE THREAD

**Issue by rlockett1121** [reapit/foundations#10706]
**Describe the bug**
We have a contact, ADE17000552, who cannot be found when we search for them via their email address using the foundations API. We can search for them if we use their ID as the search parameter, however, and they should show up in the returned payload according to our search query.

**To Reproduce**
Steps to reproduce the behaviour eg:
1. Search for contact 'ADE17000552' by their email, in non-archived contacts

**Expected behaviour**
The contact should be returned in the payload.

**Additional context**
This search is being performed via the "/contacts" endpoint using a GET request

Our query parameters are as follows:
- marketingConsent: grant (though it will be changed by the time this ticket is reviewed)
- marketingConsentFilterType: assumedOrExplicit
- email: Their email

**Comment by HollyJoyPhillips** [comment]
Hi @rlockett1121, please could you let me know which customer this is for? Thanks.

**Comment by rlockett1121** [comment]
Hi, this is for MNS.

**Comment by HollyJoyPhillips** [comment]
Hi @rlockett1121, Thank you. If you removed the marketing consent filters, are you able to retrieve the contact using just their email address?

**Comment by rlockett1121** [comment]
Hi,

No, searching the contact using their email did not work. The only
way I could find them directly was using their ID as the query parameter.

When I used the ID, the marketing consent filters acted as they were meant to.

Thanks



Rory Lockett  
| Web Developer
T: 0113 258 2657 
.
This E-Mail and the information contained in it and in any attachments are confidential and may be privileged. If you have received this E-Mail in error please notify us immediately. You are not authorised to, and must not disclose, copy, distribute or retain this E-Mail or any part of it. Northern Estate Agencies Group does not enter into any form of contract via this medium, nor is our staff authorised to do so on our behalf. Any opinions expressed in the E-Mail are those of the sender, and will not reflect the opinions of Northern Estate Agencies Group unless specifically stated.
Northern Estate Agencies Limited, Registered Office: Leigh House, 28-32 St Pauls Street, Leeds, LS1 2JT. Registered in England No: 2546381

**Comment by HollyJoyPhillips** [comment]
HI @rlockett1121, we've had a look into the specific record and it seems to be related to the data and how the email address was stored against the database. It's possible it was an old issue (2017) that has since been resolved by the desktop team. To resolve the searching,  the email address needs to be edited in AgencyCloud (CRM). 

This was confirmed using another unrelated record. It wasn't possible to verify on this record due to the marketing consent policy in place. 

Once the email address has been edited and saved, you'll find searching to work as expected. Thanks.

**Comment by HollyJoyPhillips** [comment]
That's great, thank you for confirming.
