### ISSUE TITLE
Instruction details are coming incorrectly in DWH

### ISSUE THREAD

**Issue by SairamKDXFT** [reapit/foundations#10701]
Instruction details are coming incorrectly. 

Hi team the instructed details in the Reapit or not matching with the details in the DWH. 

In this example we can see from DWH it's Instructed by Chris; but in the Reapit system for the same date we can see Oliver done this activity (status change). 
and the property is not under Chris zone. 
can you check and fix these errors. this is effecting the reporting ayer build on top of DWH. 

DWH
select ins.property_code,off.name as office_Name,nego.name as Negotiator_Name,ins.* from property_sales_won_instructions ins
join offices off on off.id=ins.office_id
join negotiators nego on ins.negotiator_id =nego.id
where ins.id= '54cc155bafec1e670a2c234e56e483a6'

<img width="953" alt="image" src="https://github.com/reapit/foundations/assets/145762206/6e1477a9-e5b7-443a-9ca7-8f35fda83770">

Reapit 

<img width="836" alt="image" src="https://github.com/reapit/foundations/assets/145762206/7c673a54-6567-49ab-9d05-0c04b2621d5a">

**Comment by SairamKDXFT** [comment]
Hi Team, any update on this ?

**Comment by HollyJoyPhillips** [comment]
Hi @SairamKDXFT this has been assigned to our next sprint starting on 26/02. Thanks.
