### ISSUE TITLE
Disaster Recovery - A way to get missed events?

### ISSUE THREAD

**Issue by Max-Shannon** [reapit/foundations#10704]
**Summary**
We are talking about our integration with Reapit and we were looking at potential failures on our side.

**Detail and or supporting links and screenshots**
In the event of a failure or outage on our side, is there anyway we can see can see what events we missed coming from Reapit? I checked the FAQs and couldn't see anything.

**Comment by HollyJoyPhillips** [comment]
Hi @Max-Shannon, the webhook transaction logs will record every transaction and can be filtered by date range. More information can be found here: https://foundations-documentation.reapit.cloud/whats-new#webhooks-transaction-logs

Does that answer your question?

**Comment by HollyJoyPhillips** [comment]
Hi @Max-Shannon, yes, there are various filters available here https://developers.reapit.cloud/webhooks/logs: 

![image](https://github.com/reapit/foundations/assets/52408607/3cc21472-abbb-434c-8f83-f7e722b6b8ba)

**Comment by Max-Shannon** [comment]
> Hi @Max-Shannon, yes, there are various filters available here https://developers.reapit.cloud/webhooks/logs:
> 
> ![image](https://private-user-images.githubusercontent.com/52408607/304365503-3cc21472-abbb-434c-8f83-f7e722b6b8ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4MjY4NzYsIm5iZiI6MTcwNzgyNjU3NiwicGF0aCI6Ii81MjQwODYwNy8zMDQzNjU1MDMtM2NjMjE0NzItYWJiYi00MzRjLThmODMtZjdlNzIyYjZiOGJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEzVDEyMTYxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3NDk1NTAwZGM5M2I4N2Q1NjllMmU1YzIzZWVmN2E2NWY2YTBjNDRkZmIxZThhYTdlYTQ1N2U2ZjUwMGI0NGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Sb2EgJOvNHTARbUc4CJ0PKDdodgkZsi46021zvX9ETw)

Sorry I mightn't have been clear. 

We would have to manually download each payload this way wouldn't we? I was looking for an API.

**Comment by HollyJoyPhillips** [comment]
Hi @Max-Shannon, apologies for the delay. Yes you would need to manually download as we don't have a dedicated API for retrieving emitted webhooks.
 
However, the topic, event ID & date is visible in the transaction logs so you could poll the specific data based on that information if required.

**Comment by Max-Shannon** [comment]
Perfect. Thank you @HollyJoyPhillips
