### ISSUE TITLE
403 on request images

### ISSUE THREAD

**Issue by abelyankov** [reapit/foundations#10717]
**Describe the bug**
When you try to open image url it return 403 error.

**To Reproduce**
Open url: 
https://assets.reapit.net/sau/live/pictures/LAI/23/LAI230352_20.jpg

**Comment by AshDeeming** [comment]
Hi @abelyankov 
Please could you provide more details, including; is this occurring in Sandbox or particular client on production?

**Comment by abelyankov** [comment]
@AshDeeming Hello! Yes, it's real client on production

**Comment by AshDeeming** [comment]
Hi @abelyankov 
Could you confirm who is seeing this error & at what stage in the process?
