### ISSUE TITLE
Letting Status params not being respected in get Properties

### ISSUE THREAD

**Issue by hivetom** [reapit/foundations#10710]
Hi @plittlewood-rpt @AshDeeming @cduggan-reapit ,

Further to this issue, we have been advised by clients of additional properties not being imported where an arrangingTenancy tenancy is set. We have investigated this and replicated with SBOX data as follows:

Property: MKT210309
Tenancy: MKT210158 (status: Arranging Tenancy)

Using this query, we are unable to retrieve the aforementioned property:

`properties?pageNumber=1&pageSize=100&officeId=MKT&embed=tenancies&marketingMode=letting&marketingMode=sellingAndLetting&lettingStatus=arrangingTenancy&lettingStatus=arrangingTenancyUnavailable&lettingStatus=tenancyCurrent
`

Fetching the property directly via its ID reveals:

> "marketingMode" => "letting",
> "letting" => [
>     ...
>     "status" => "arrangingTenancyUnavailable",
> ],
> ...
> "_embedded" => [
>         "tenancies" => [
>           [
>             "id" => "MKT210158",
>             "status" => "arranging",
>             ...
>             ]
>           ]
> ]

Any info you could share on this would be greatly appreciated. 

Kind regards

_Originally posted by @hivetom in https://github.com/reapit/foundations/issues/10031#issuecomment-1936015989_

**Comment by HollyJoyPhillips** [comment]
Hi @hivetom, one of our engineers ran the same query via the swagger in the DeveloperPortal and that property was returned: 

https://platform.reapit.cloud/properties/?pageSize=100&pageNumber=1&embed=tenancies&lettingStatus=arrangingTenancyUnavailable&lettingStatus=arrangingTenancy&lettingStatus=tenancyCurrent&marketingMode=letting&marketingMode=sellingAndLetting&officeId=MKT

![image](https://github.com/reapit/foundations/assets/52408607/38ad0151-44b4-4938-8444-de92c0cc89e6)

**Comment by hivetom** [comment]
Hi @HollyJoyPhillips ,

Thanks for this. Is there a private/secure area where we can disclose real-world examples that are not SBOX data please?

Kind regards

**Comment by HollyJoyPhillips** [comment]
Hi @hivetom, of course, you can send examples to sinfo@reapitfoundations.zendesk.com. Thanks.

**Comment by HollyJoyPhillips** [comment]
Hi @hivetom, do you have any other examples or are happy for us to close this ticket?

**Comment by hivetom** [comment]
Hi @HollyJoyPhillips I have sent a live example via email just now for you to review. Kind regards

**Comment by HollyJoyPhillips** [comment]
Internal Issue #10710

**Comment by HollyJoyPhillips** [comment]
Hi @hivetom, I've replied to the ticket. Please confirm if that answers your query. Thanks.

**Comment by hivetom** [comment]
Thank you @HollyJoyPhillips , that does indeed answer our query. Kind regards.
