### ISSUE TITLE
Correct the API Version on GEO Diary

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#1071]
**Summary:** The API Version being used on GEO Diary is incorrect and needs to be updated

**Task:** Update the API Version in GEO Diary 
- The current version is 2020-01-31 (GEO is using 'api-version: 2020-02-06')

Also, please ensure all of our apps are using the correct version as detailed in the documentation (https://foundations-documentation.reapit.cloud/api/api-documentation#versioning)

**Comment by tanphamhaiduong** [comment]
I check current GEO-Diary using API 2020-02-06
