### ISSUE TITLE
DataWareHouse Properties Table Request - Period End Date From Rent/Fees Screen

### ISSUE THREAD

**Issue by kmacgregorPR** [reapit/foundations#10714]
Request for the Management start/end dates to be brought into the Properties table as shown in the screenshot. 
<img width="325" alt="DataWarehouse Date Field" src="https://github.com/reapit/foundations/assets/128388971/2a06c65d-e5f6-44d5-b59a-fbae0e642ddd">

**Specification**
- Project: Analytics Schema
- Add five new fields to PROPERTIES view that expose the following

| Schema Field | Map From |
|--------|--------|
| VACANT_MANAGEMENT | Yes when vacant management fee is populated, otherwise No |
| VACANT_MANAGEMENT_FEE_AMOUNT | prp.extra.pVacManAmt |
| VACANT_MANAGEMENT_FEE_PEIOD | prp.extra.pVacManFreq (convert to friendly text) |
| VACANT_MANAGEMENT_START_DATE | prp.extra.pVacManFr | 
| VACANT_MANAGEMENT_END_DATE | prp.extra.pVacManTo | 

- Ensure schema documentation in properties.yml is updated
- Ensure schema documentation in separate project is updated

**Comment by plittlewood-rpt** [comment]
Hi @kmacgregorPR can I just check how you are using these fields. Those fields have actually been relabelled in your system and should be being used a vacant management fee date periods so I need to be a bit careful if you're using them for a different purpose to what they were originally intended for.

**Comment by kmacgregorPR** [comment]
Hi Pete, 
Thank you for your message. Yes, I understand we have 'relabelled' these, and don't use them for vacant management as such, but rather to record the actual management end dates for our properties which are leaving our management. It is a really important date field for us, and the only area in Reapit we could use to record this, so were advised to do so by RPS when onboarding, and they suggested re-labelling accordingly.

**Comment by plittlewood-rpt** [comment]
HI @kmacgregorPR this data is now available in the fields shown in the spec at the top of this Github issue. You will need to use the Refresh Share mechanism in the data warehouse app to update your dataset. Many thanks

**Comment by kmacgregorPR** [comment]
Thank you so much!
