### ISSUE TITLE
Credentials to connect to Stirling Ackroyd data warehouse

### ISSUE THREAD

**Issue by tclempson** [reapit/foundations#10719]
Hi all,

My developers are looking to connect to/acess the Stirling Ackroyd data warehouse - can you advise how they would do this?

Thanks

**Comment by HollyJoyPhillips** [comment]
Hi @tclempson, access to the data warehouse is setup through the data warehouse app. Looking at the account it is setup and controlled by your IT Department. You'll need to speak with them about setting up additional users/access.
