### ISSUE TITLE
Request: Enable Array Support for typeId on Appointment Endpoint

### ISSUE THREAD

**Issue by olorunfemiprospectorpro** [reapit/foundations#10716]
I've identified an inconsistency in the API documentation regarding the typeId query parameter on Appointment endpoint. Currently, the documentation states that typeId accepts an array, but the API only takes a string value.

Kindly enable 'typeId' support for array as our use case will require this to filter appointments using multiple typeIds.

Thank you for consideration.

**Comment by AshDeeming** [comment]
Hi @olorunfemiprospectorpro 

Please separate the typeId as per the below example for this to work as expected; 

https://platform.dev.paas.reapit.cloud/appointments/?typeId=VW&typeId=VL
