### ISSUE TITLE
Query Offices by Region

### ISSUE THREAD

**Issue by abrahamseni** [reapit/foundations#10712]
Our client needs to query Offices by Region

Context: `/offices?region='east'`
or can we use `extrasField` for this?

Expected return values: offices within the region.

**Specification**
- Project: Reapit.Services.Offices
- Add new `string Region` property to OfficeModel that exposes the semi structured field offices.extra.oRegion
- Add new `string Region` property to GetOfficesQuery that allows filtering on this value. Typically we wouldn't do this with it being a semi structured field, however that is a fairly finite number of rows in this table which is relatively small even on larger databases so we shouldn't see any overly noticeable issues with performance. The largest table across the estate only has 860 rows.
- When GetOfficesQuery.Region is present, filter as appropriate. It's likely acceptable to just do this in memory (after fetching only offices with a region using LIKE), but if not, each database has a GetExtra function that can be used for this purpose)

**Comment by rochellelevy** [comment]
@HollyJoyPhillips would it be possible to get this into your next sprint? This is our last couple of weeks with them and we would like to get the work completed.

**Comment by HollyJoyPhillips** [comment]
Hi @rochellelevy, it needs to go through refinement first to understand if it's possible/how much development work is involved. Once we have that we will be able to look at allocation. We have refinement tomorrow. Thanks.

**Comment by rochellelevy** [comment]
@HollyJoyPhillips thank you!

**Comment by AshDeeming** [comment]
Hi @abrahamseni 
Access for the fields mentioned above has been set up and should become active within the next 15 minutes.
Region-> oRegion

**Comment by abrahamseni** [comment]
Thanks @AshDeeming ,

We can access the `oRegion` but we also need to query the offices by region, i.e:
`/offices?region='lettings country'`

**Comment by abrahamseni** [comment]
Also, can you help me with the region list?
Where can we access it?

**Comment by rochellelevy** [comment]
@AshDeeming @HollyJoyPhillips can you help Abraham please?
