### ISSUE TITLE
DataWarehouse - Tenancies Table - Inspection Information Required

### ISSUE THREAD

**Issue by kmacgregorPR** [reapit/foundations#10715]
Request for Inspection 'Last' date, 'Next' date and whether booked or not fields to be brought into the tenancies table (or separate table) within DataWarehouse from RPS. Screenshot attached. 
<img width="463" alt="DataWarehouse Inspections" src="https://github.com/reapit/foundations/assets/128388971/1bd9d858-13b4-4456-bf8e-e8fb687d4035">

*Specification**
- Project: Analytics Schema
- View model: TENANCIES
- Add new fields LAST_INSPECTION (datetime), NEXT_INSPECTION_DUE (datetime), NEXT_INSPECTION (datetime) and NEXT_INSPECTION_STATUS (string - Booked/Not Booked) that surface the following information respectively:
  - the last Property Inspection appointment datetime, 
  - the CALCULATED next inspection date based on the last inspection date (or the tenancy start date if there hasn't been an inspection yet), 
  - the next Property Inspection appointment datetime 
  - Status of next property inspection (Booked/Not Booked) based on the presence of a value in the preceding field
- Include foreign key relationship back to the DATES table
- Update analytics schema documentation.

**Comment by kmacgregorPR** [comment]
Hello, just wondered if there was an update on this at all? Many thanks, Katherine

**Comment by HollyJoyPhillips** [comment]
Hi @kmacgregorPR, this has been assigned to our next sprint (starting 17th). For more information on our processes, please visit: https://foundations-documentation.reapit.cloud/dev-requests Thanks

**Comment by kmacgregorPR** [comment]
Thanks Holly!
