### ISSUE TITLE
Integrate into our website

### ISSUE THREAD

**Issue by eqxDev** [reapit/foundations#10723]
We are looking to integrate this to display land & commercial properties on our website, When we asked for API information & credentials we were told to create a ticket here.

**Comment by AshDeeming** [comment]
Hi @eqxDev 
You will need to go through the below page, selecting the relivant option in order to access the developer portal:

**Comment by eqxDev** [comment]
> Hi @eqxDev You will need to go through the below page, selecting the relevant option, in order to access the developer portal: https://developers.reapit.cloud/select-role

Thanks, we made an application last week and still haven't heard back, is it possible for you to chase us for this as its really holding us up.

Thank you.
