### ISSUE TITLE
How to Access (Commissions,Rental value, Gross yield)

### ISSUE THREAD

**Issue by thashendran-perinparasa-property-logic** [reapit/foundations#10728]
Hi Team, 

How can I access the information circulated in red in the screenshot below using the Reapit Api 

Property_id: GST230036

![image](https://github.com/reapit/foundations/assets/53749234/85f94b46-d8f0-4404-b0e7-e6792aea34c7)

Thanks 
Thashendran

**Comment by AshDeeming** [comment]
Hi @thashendran-perinparasa-property-logic 
The Price & its qualifier, along with commission/fee can be found via the Properties endpoint (within selling) 
![image](https://github.com/reapit/foundations/assets/61687775/be35c553-cee8-4aaa-ad0f-095e74ae3b56)

Please note that Rental Value is semi structured data & i'll look to add this if you can confirm the Client/ClientID this is required for? 

With regards to Gross Yield, i'll revert further once I have an update.

**Comment by thashendran-perinparasa-property-logic** [comment]
Hi @AshDeeming 
Client name: Maguire Jackson
Client id: MAJ

Thanks 
Thashendran

**Comment by HollyJoyPhillips** [comment]
Hi @thashendran-perinparasa-property-logic, just to confirm 'pEstMonthlyRentalValue' is now available as an extra field for MAJ. 

Please see below an example to include the additional field when making a query to the properties endpoint: 

https://platform.reapit.cloud/properties/ABC00000?extrasfield=pEstMonthlyRentalValue

For more information on semi structured data (extra fields) please see https://foundations-documentation.reapit.cloud/faqs#certain-fields-are-not-exposed-by-default-in-the-platform 

The Gross Yield data is calculated in the CRM and not as a set field. You would most likely need to do the calculation on your side.
