### ISSUE TITLE
Add lifecycle policies to manage our OS logs

### ISSUE THREAD

**Issue by RWilcox-Reapit** [reapit/foundations#10724]
**Background context**
Currently, it's a manual process to clear down older logs from our OpenSearch cluster.
this can be automated with an 'Index State Management' policy. 

**Specification**
Add a policy to both DEV and PROD to clear down logs automatically after X amount of time (90 days?)
Discuss which indices should be cleared down (gwl*, fnd*, sums*)
Look into if this can be added via the template

**Comment by plittlewood-rpt** [comment]
Duplicate of #5461
