### ISSUE TITLE
Extras Fields for Bell Ingram

### ISSUE THREAD

**Issue by MarcinuB** [reapit/foundations#10735]
Hi Team.

Could you enable below extras fields for Bell Ingram please:
 - Location
 - Services
 - Directions
Also a query: if we would need the Outside and Fixtures and Fittings - is it a simple request for extras or do you need to do a code change? We don't need them for now, asking just in case :).

Thank you

![unnamed](https://github.com/reapit/foundations/assets/8589350/338b5586-8b5b-4187-9cd0-dd558dc98624)

**Comment by AshDeeming** [comment]
Hi @MarcinuB 

I've enabled access for all the current fields shown in the screenshot, these should become available within the next 15 minutes.

BEL:
Long description; pLongDesc
Outside: pOutside
Location: pLocation
Directions: pDirections
Services: pServices
Fixtures and Fittings: pFixandFit

As per any other semi structured data you access it using the extrasField query string parameter eg;
GET /properties?extrasField=pDirections

**Comment by MarcinuB** [comment]
Hi @AshDeeming .

Thank you kindly. Have a good weekend!
