### ISSUE TITLE
Add Appointment Attendance field into Analytics Schema

### ISSUE THREAD

**Issue by ktanalyst** [reapit/foundations#10731]
**Background context**

There is a field called Attendance ('Attended','No Show','Not Set') which can be set against an appointment record in Reapit. Please can this field be added to the APPOINTMENTS view in the Analytics Schema?

![image](https://github.com/reapit/foundations/assets/143076147/dc0f4769-c443-4304-b3c9-5be9a812da58)

**Specification**

**Comment by plittlewood-rpt** [comment]
Hi @ktanalyst this was recently added in #10165 - you just need to refresh your data share to see the new 'attendance' field in the appointments table. Please refer to the analytics schema documentation for the possible values

**Comment by ktanalyst** [comment]
Hi @plittlewood-rpt, where can I find the documentation?

I've tried accessing from the support page within Reapit but none of these links go anywhere:

![image](https://github.com/reapit/foundations/assets/143076147/adf94f47-31ab-4dc2-97c3-c2d990f07b9f)

**Comment by plittlewood-rpt** [comment]
Hi @ktanalyst you can access them via the [Developer Portal ](https://developers.reapit.cloud/analytics-schema-docs)(Docs -> Warehouse) however a direct link which you may choose to bookmark is https://reapit-analytics-schema.prod.paas.reapit.cloud/
