### ISSUE TITLE
Reapit float & Fixflo

### ISSUE THREAD

**Issue by katedeedman** [reapit/foundations#10732]
Hi Reapit! 

We've been developing the landlord float function into Fixflo. 

Callum (our developer) and I have a few questions - some are technical and some are more around the use case. Would anyone be able to jump on a call with us over the next few weeks? Not super urgent so no big rush! 

Let me know. 

Thanks in advance!

-Kate

**Comment by AshDeeming** [comment]
Hi @katedeedman 
I've referred this to our partnership team who will reach out directly.
