### ISSUE TITLE
Method Of Fetching Sales Progress Via The REST API

### ISSUE THREAD

**Issue by rlockett1121** [reapit/foundations#10737]
**Is your feature request related to a problem? Please describe.**
There is no obvious way of fetching the sales progression of a property via the REST API, either through the properties or the offers endpoints,

**Describe the solution you'd like**
The current sales progress of an offer included in the payload for when we fetch the data for an individual record.

**Additional context**
This is currently possible on your old API, here: https://webservice.reapit.net/demo/rest/_doc/

**Comment by plittlewood-rpt** [comment]
Hi @rlockett1121 have you had a look at the conveyancing API? I think this is probably what you are looking for.

**Comment by rlockett1121** [comment]
Hi,

Yes this looks like what I need, sorry I didn't see it earlier.

Thanks for your help.
