### ISSUE TITLE
Propertyhive - pull specific branches and status.

### ISSUE THREAD

**Issue by Richjaw** [reapit/foundations#10748]
Hi, I was wondering how I would specify Propertyhive only pull specific branches and status' from Reapit.

For example, only manchester branches, not liverpool ones and only for sale, to let and under offer properties, not pulling under instruction etc.

we operate many offices across 2 brands and I need to separate them across 2 sites.

thanks in advance.

**Comment by AshDeeming** [comment]
Hi @Richjaw 
This would need to be discussed with the 3rd party directly.

N.B

Areas endpoint may be applicable regarding geographical coverage and the Properties endpoint details the property statues used.

**Comment by HollyJoyPhillips** [comment]
Closing as comment above has answered the question. If you still require assistance, please reopen/comment.
