### ISSUE TITLE
Expose 'Offices to view' in API

### ISSUE THREAD

**Issue by craigforrest** [reapit/foundations#10741]
**Is your feature request related to a problem? Please describe.**
As part as a Reapit mobile app we need to support being able to view multiple users diaries.

Following multiple discussions, we think the only initial requirement we need to support this is being able to determine the offices that a user can select other negotiators from.
![image](https://github.com/reapit/foundations/assets/26924168/ec4f0356-1e7b-47cb-8e1f-63bd72121bee)

This is currently stored in the neg table as "nDryOffices"

**Describe the solution you'd like**
This can be read only with a user needing to make any changes to the selected offices through Reapit first

**Specification**
- Project: Reapit.Services.Negotiators
- Add new properties to `NegotiatorModel` as below

| Property | Type | Mapping |
| ------------- | ------------- | ------------- |
| diaryOfficeIds  | string[] | negs.extra.nDryOffices | 
| diaryNegotiatorIds  | string[] | negs.extra.nDefaultUsers |

- Support should be for read and write

**Validations**
- No duplicates in either field
- Provided negotiator ids must be between 2 and 4 alphanumeric characters
- Provided office ids must be between 2 and 3 alphanumeric characters

**Comment by plittlewood-rpt** [comment]
@HollyJoyPhillips I have agreed we can look at adding the extras field mechanism to the negotiators API for now, with the capability of allowing extras field lists at an app level instead of at a company level. It means we don't have to add seemingly random values to the core schema but gives the digital team what they need
