### ISSUE TITLE
Many fields not updating in OFFERS view (Analytics Schema)

### ISSUE THREAD

**Issue by ktanalyst** [reapit/foundations#10744]
**Describe the bug**
Within the 'Sales Progress' section of an offer window in Agency Cloud (see first screenshot), there are a number of tick box fields (see second screenshot). When running a query on the OFFERS view to retrieve this data, everything is set to 'No' by default, despite multiple boxes being ticked (with accompanying dates) on the platform. This is affecting all fields related to the Sales Progress tick box section, such as:

IS_ENQUIRIES_SENT = 'No'
ENQUIRIES_SENT_DATE = NULL
DAYS_TO_ENQUIRIES_SENT = NULL  
(and repeat for all other fields)

**To Reproduce**
I have found an example of a completed property where most of the boxes within the Sales Progress window have been ticked (see second screenshot). Here is the query to access this offer record:

Steps to reproduce the behaviour eg:
`SELECT * FROM REAPIT.ANALYTICS_KLR.OFFERS 
WHERE id = '81f52c8c6be68d5e3d2834c6b23d1f15'`

**Expected behaviour**
When a box is ticked for a Sales Progress field, data within the Analytics Schema should change to 'Yes' and any relevant date fields should also display a date.

**Screenshots**
![image](https://github.com/reapit/foundations/assets/143076147/4b3787df-c7fb-4f43-8118-b33a51ca8ccf)

![image](https://github.com/reapit/foundations/assets/143076147/38d1875b-549b-4b40-a17d-f620b3e103af)

**Device (please complete the following information for web issues):**
PC

**Additional context**
We reported a similar problem where the 'Include in pipeline' field didn't update when the box was ticked in Reapit. It is likely the same resolution will need to be applied for all remaining fields within this view:

https://github.com/reapit/foundations/issues/9967#issuecomment-1796515876

**Specification**
- Project: Analytics Schema
- This data is based on the Sales Progression configuration in the CRM. This can be completely customised from client to client. The analytics schema currently only supports the standard set which could be the issue here. If it is, we need to consider support for the customisation of this screen and how we would do that. It would have to be a separate view entirely with the data pivoted in a different way

**Comment by plittlewood-rpt** [comment]
Hi @ktanalyst - two new view models are now available to you which will give you the capability of tracking all 16 configurable sales progression items. These are OFFERS_SALES_PROGRESSION and OFFERS_SALES_PROGRESSION_CONFIGURATION (the latter helps you understand and evaluate the 16 configurable 'steps'). The update documentation is just going out to production. You will need to use the Refresh Share option in the Data Warehouse App to provision the new models to your warehouse instance. Many thanks

**Comment by ktanalyst** [comment]
Thanks Pete, that's a really useful addition to the schema.

**Comment by plittlewood-rpt** [comment]
For reference as well, our [next sprint](https://github.com/reapit/foundations/projects/130) (starting Monday) has a lot of analytics schema bits and pieces in which is worth you being aware of.
