### ISSUE TITLE
Grant access to a custom field via API

### ISSUE THREAD

**Issue by anpar199** [reapit/foundations#10740]
**Request**

In order for us to grant access to Semi-structured 'extras' field data, please provide the following information in this request:

- The name of the customer you represent: Hayman-Joyce
- The name of every field you need surfaced (if known): chatbot in the marketing tab of a property description
- A screenshot of of the field(s) you require in the agency cloud user interface: attached
![image](https://github.com/reapit/foundations/assets/150029245/50920da5-fbd3-4d55-854f-4963b4e088f9)
- A short use case as to why you require this data: it will be used by AI chatbot on Hayman-Joyce's website

**Comment by AshDeeming** [comment]
Hi @anpar199 
Access for the fields mentioned above has been set up and should become active within the next 15 minutes.
ClientId: HMJ

Field = pChatBot

As per any other semi structured data you access it using the extrasField query string parameter eg;
GET /properties?extrasField=pChatBot

**Comment by anpar199** [comment]
Thank  you
*Anton Parfeniuk*
Founder and CEO
The New Normal Analytics

*m*: +44 7876 705934
*e*: ***@***.***
*w*: thenewnormalanalytics.com
<https://www.thenewnormalanalytics.com/?utm_source=direct&utm_medium=personalemail&utm_campaign=emails>
