### ISSUE TITLE
Fixflo <> Reapit // Block sync

### ISSUE THREAD

**Issue by katedeedman** [reapit/foundations#10746]
Hi Reapit, 

One of our mutual clients has flagged to us that Reapit now includes 'Block' feature. I can't see any API calls for blocks in your docs - is that right? Is there anything we need to amend in the app to include this?

Thanks!

Kate

**Comment by AshDeeming** [comment]
Hi @katedeedman 
Block Management isn't currently include in the Platform API 
If there are specific fields required, a feature request detailing these can be submitted & will be reviewed by the relevant team.

**Comment by katedeedman** [comment]
Thanks for confirming, Ash!
