### ISSUE TITLE
Performance Degraded - 19/02/2024

### ISSUE THREAD

**Issue by Max-Shannon** [reapit/foundations#10747]
**Describe the bug**
Hi,

We have noticed that we are receiving events some time after the event-time.

Example:
f15b18e6-47b4-48a9-a044-85da846ebc99
"eventTime": "2024-02-19T12:03:35.0977457Z"

We only received this event at: 19-02-2024 14:49:13

**Expected behaviour**
We would expect that events are coming in, in near real-time.

**Additional context**
We have noticed that the version of the property returned via the getProperty API is different than the last event. 

It would seem that the events are coming in 2-3 hours after the update in some cases.

**Comment by Max-Shannon** [comment]
Hi - I have seen the System status page now and see that you are aware of the problem.

**Comment by plittlewood-rpt** [comment]
HI @Max-Shannon this issue should now be resolved
