### ISSUE TITLE
Where to find additional property image details in the API feed/app we have created and approved for ReapIT

### ISSUE THREAD

**Issue by LightBulbWebDesign** [reapit/foundations#10754]
We have an approved app on the ReapIT marketplace which we are using to pull down property data to display on a new website, currently in development.

We can only find reference in the feed data to the main property image, and cannot find anything that indicates the details for additional property images. Everything else is OK and we can find the details and use on the website.

Can anyone advise how we get the list of additonal images for each property so we can use them on the website?

We were advised by ReapIT support to post our question here.

Thanks for any reply.

Chris

**Comment by AshDeeming** [comment]
Hi @LightBulbWebDesign 
Please see the swagger documentation - specifically the 'PropertyImages' endpoint (https://developers.reapit.cloud/swagger)

**Comment by HollyJoyPhillips** [comment]
Hi @LightBulbWebDesign, please can you confirm the above comment has answered your question with regards to property images?
