### ISSUE TITLE
Add Client ID in my app Reapit Dev portal

### ISSUE THREAD

**Issue by amandaclark9** [reapit/foundations#10766]
My name is Amanda Clark and currently we are using reapit dev portal for our integration. My company app is Private however we want to add another Client ID. After I added my new Client ID after the comma, I clicked "Create Revision" but the client ID that i just added it's gone. Am I doing it right?

Thank you
![Screenshot 2024-02-22 at 13 26 25](https://github.com/reapit/foundations/assets/129269791/8b4f7eb1-09c6-4cbe-bfd5-b0fc73285268)
![Screenshot 2024-02-22 at 14 11 46](https://github.com/reapit/foundations/assets/129269791/ea81a7f0-f35f-41d5-9359-769906621d85)

**Comment by AshDeeming** [comment]
Hi @amandaclark9 
The revision to add HTN to the advised app has now been approved
