### ISSUE TITLE
Unable to see RM stats for LSLi brands

### ISSUE THREAD

**Issue by HelenWill** [reapit/foundations#10761]
We make a Reapit API call (Webservice) though to LSLi properties to pull the RM stats. For all tested properties we seem to be returning 0, A change was made for YM/RR to move the RM stats data into Reapit a few years ago. Was this change also made for LSLi? If so where can we see the data?

Alternatively there may be a fault with the webservice api or the integration from Rightmove to Reapit. If we can know the first part of is it in LSLi reapit then we can narrow down the search

![image](https://github.com/reapit/foundations/assets/160746935/04129513-7bec-4fbd-9359-30286d0c4016)

**Comment by plittlewood-rpt** [comment]
Hi @HelenWill you will need to liaise with our servicedesk directly regarding this issue as the Github project is only for Foundations related items. It looks like you are using the legacy soap or REST services
