### ISSUE TITLE
Alternate code

### ISSUE THREAD

**Issue by elizabethhamlin** [reapit/foundations#10765]
Please can we pull the alternate code/old code that stored under marketing on the property

**Specification**
- Project: Analytics Schema
- Add new fields OLD_SYSTEM_CODE and ALTERNATE_SYSTEM_CODE to PROPERTIES model that expose prp.extra.pOldCode and prp.extra.pAltCode respectively. 
- Add documentation for new fields (PL will need to do this due to licensing on the tool we generate our documentation from)

**Comment by plittlewood-rpt** [comment]
Hi @elizabethhamlin I can sort of see why alternate code would be useful, but can you let me know your use case for needing the old code surfacing?

**Comment by elizabethhamlin** [comment]
Hi Pete
This code helps us to determine if the business is acquired or not based on the alternate code
Thanks
Lill

**Comment by plittlewood-rpt** [comment]
hi @elizabethhamlin this has now been added as per the spec above. You will need to use the Refresh Share facility in the data warehouse app to update the schema in your warehouse account. The analytics schema documentation will update shortly.

**Comment by elizabethhamlin** [comment]
Amazing, thanks Pete

Lill

Elizabeth Hamlin MARLA
Reporting and Systems Manager
07443 188920
***@***.******@***.***>

[Text  Description automatically generated]

Lomond is a group of leading Lettings and Sales Agents across the UK. Lomond is the trading name of Chianti Holdings Ltd. Registered office address 70 St. Mary Axe, London, EC3A 8BE. Registered in England and Wales. Registered Company No. 13075482.

This email is confidential and intended solely for the use of the individual to whom it is addressed. Any views or opinions presented are solely those of the author and do not necessarily represent those of Lomond. If you are not the intended recipient, be advised that you have received this email in error and that any use, dissemination, forwarding, printing, or copying of this email is strictly prohibited. If you have received this email in error please contact the sender. Finally, the recipient should check this email and any attachments for the presence of viruses. The company accepts no liability for any damage caused by any virus transmitted by this email.
