### ISSUE TITLE
Enquiry not showing in CRM

### ISSUE THREAD

**Issue by shaheen-svz** [reapit/foundations#10788]
I have created an APP in the developer portal and connected the API's and below are the steps which we are following:

**Steps**

1. Create access token 
2. Get 'negotiatorId' from property details  
    API: https://platform.reapit.cloud/properties/{id}
4. Get Agent details (officeId) using the negotiatorId  
    API: https://platform.reapit.cloud/negotiators/{id}
6. Push the Enquiry 
   API: https://platform.reapit.cloud/enquiries/
   Body:
  {
  "surname": "Tahir Test",
  "enquiryType": "salesApplicant",
  "message": "testing api",
  "officeId": "PLM",
  "marketingConsent": "grant",
  "sourceName": "Property Finder",
  "mobilePhone": "971561139245",
  "propertyIds": ["DCH240354"]
   }
   
We got the response as 201 Created, but the client cannot see this inquiry in their CRM.

When I searched the enquires, I could find all the test we created in the API response.

What could be the reason for not showing these enquiries in the CRM?

**Comment by plittlewood-rpt** [comment]
Hi @shaheen-svz please can you confirm which customer this item relates to?

**Comment by shaheen-svz** [comment]
Hi @plittlewood-rpt 
Customer name: Dacha Real Estate, Dubai
Company Code: DCH

**Comment by HollyJoyPhillips** [comment]
Thanks @shaheen-svz. 

@plittlewood-rpt logged into their build and regardless of changing various filters, no enquires are present. Needs further investigation

**Comment by plittlewood-rpt** [comment]
Hi @shaheen-svz the enquiries are indeed in the database and showing up correctly as you will see below. By default however, users will only see enquiries for their own office (so in the case of your own example, only users in the Palm Jumeriah office would be able to see the lead). I can see as well from the configuration for this customers that by default enquiries will be filtered by property manager. As a result, it might also be necessary for the users to change the filter highlighted in red below to "Show All"

Please can you review the above and let me know how you get on. The users are able to reach out to our service team for assistance with configuration as required.

![image](https://github.com/reapit/foundations/assets/30798627/d41ab532-7d5c-402b-890d-7c322c026361)

**Comment by shaheen-svz** [comment]
@plittlewood-rpt thanks, let me check this with the client and get back to you.

**Comment by HollyJoyPhillips** [comment]
Hi @shaheen-svz are you able to confirm you can view the enquiry?

**Comment by shaheen-svz** [comment]
@HollyJoyPhillips yes, we can view it

**Comment by HollyJoyPhillips** [comment]
Hi @shaheen-svz Great, thanks for letting us know. Please let us know if you have any further issues.
