### ISSUE TITLE
Customer/Client Journey using our app

### ISSUE THREAD

**Issue by amandaclark9** [reapit/foundations#10781]
Good morning

I have already added new client ID in our app, do you have any documentation regarding the client journey for example after I added the new client ID, what should client do for example in terms of installing our app ?How do they do that ?

At the moment, my app is in private mode and only visible for 2 clients.

Thank you
Amanda

**Comment by HollyJoyPhillips** [comment]
Hi @amandaclark9, once the app has been approved, it will be visible for the customer(s) to install. Most customers are familiar with the process but this section in our documentation may help: https://marketplace-documentation.reapit.cloud/#installing-enabling-an-app. 

In brief, the customer needs to access the AppMarket and enable or install the app or integration. If you want to provide your app name or ID I will be able to confirm it's available in the AppMarket for said customers to install?

**Comment by amandaclark9** [comment]
Hi @HollyJoyPhillips thank you for your swift response. This is our App ID f77dce4a-a82e-4905-b46f-2a2863ffa341 (Homebox). In this app, the status is private and I added my client id KYC and HTN. I am expecting that HTN should be able to see our app and install our app using the guide you mentioned above?

**Comment by HollyJoyPhillips** [comment]
Hi @amandaclark9 that's correct. The app will be visible to HTN. They have enabled other third-party applications so should be familiar with the AppMarket. Please reach out if you have any issues.

**Comment by amandaclark9** [comment]
Thank you @HollyJoyPhillips , I have received this from the partner and they said they already installed our app, does it mean the Reapit team need to activate this in order they use our app?
![image](https://github.com/reapit/foundations/assets/129269791/023605ac-3f16-4b35-8499-6b1dc5bb064c)

**Comment by HollyJoyPhillips** [comment]
Hi @amandaclark9, the user in the screenshot doesn't have the correct permissions to enable the integration which is why they won't see the option, please see https://foundations-documentation.reapit.cloud/faqs#why-can-i-not-see-the-option-to-install-app-or-enable-integration. There are only 2 users within their organisation that can install or enable apps.

**Comment by HollyJoyPhillips** [comment]
Hi @amandaclark9, I see the integration still hasn't been enabled, do you need further support?

**Comment by amandaclark9** [comment]
Hi @HollyJoyPhillips thank you for checking out and investigated it for me. I have mentioned this to them but the user who is working on this currently working part time so hopefully we will hear from her once she is back.

**Comment by HollyJoyPhillips** [comment]
I'll close this ticket but please re open or comment if you're still having issues. Thanks.
