### ISSUE TITLE
Integration of SBOX AgencyCloud with MAP is not working properly.

### ISSUE THREAD

**Issue by Endlay** [reapit/foundations#10783]
User story: 
The user update data on SBOX AgencyCloud. Then when user check the update on dashboard or App MAP, they will notice the data is not updated.

Issue: Integration of SBOX AgencyCloud with MAP is not working properly.

Last update 26/02/2024 10am

Full detail and screenshots on -https://reapit.atlassian.net/browse/PCQ-767
Only occurs on SBOX account with all environment

Acceptance criteria:

Webhook should subscribe and active

There’s no pending on webhook

Webhook should be working on all environment

**Comment by plittlewood-rpt** [comment]
@Endlay  as per discussions today this should be resolved. Please confirm back to me tomorrow if you can. Thanks

**Comment by plittlewood-rpt** [comment]
Confirmed with Endlay this is resolved.
