### ISSUE TITLE
domvs access denied to images

### ISSUE THREAD

**Issue by BYMIntegrations** [reapit/foundations#10785]
**Background context**

Hello,

Hope all is well,

We are doing a full pull of the data for the customer DOMvS for the integration for their BYM system.

For alot of the property images we appear to not have access, for example:

https://assets.reapit.net/dom/live/pictures/DOR/06/DOR060207_01.jpg

![image](https://github.com/reapit/foundations/assets/102583061/8c8361db-c8a9-4230-bdbb-e1b85a25a828)

Could this please be looked into why.

**Specification**

**Comment by plittlewood-rpt** [comment]
Hi @BYMIntegrations you will get this error when the physical media asset does not exist. That looks like a very old property which is in the archive so it's highly likely that those images were deleted a long time ago. Looking at their system they've got around 2500 images in this state which can be cleaned by our service team, if required.
