### ISSUE TITLE
Add 'Website Integration' category by default 

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#10782]
**Summary:** When a developer creates an app they have the option of selecting 'Website Integration' as a type. We should automatically add 'Website Integration' as a category type on creation, if possible. 

**Task**: 
- Auto add 'Website Integration' category type on selected app creation. 
- It might be sensible here to have a map of app type options (on the What do you want do today? column [here](https://developers.reapit.cloud/apps/new)) to default categories so that it's a reusable mechanism in the event the list ever changes. This would give the ability to easily change the list whilst retaining the default category behaviour.
- Result of the work is that CreateAppModel.categoryIds is populated in the POST request to the marketplace/apps endpoint

**Comment by bashleigh** [comment]
On app creation form. When "website feed" step selected, and initial permissions of "read offices", "read negotiators", "read properties" are selected then add category "website integration" as a default category (category with id of 14)
