### ISSUE TITLE
How to archive a record?

### ISSUE THREAD

**Issue by chestertons** [reapit/foundations#10797]
Can't see this documented - tried setting "fromArchive" to true, but that's not it! Any ideas?

[headersSent] => Array
        (
            [0] => accept: application/json
            [1] => api-version: 2020-01-31
            [2] => reapit-customer: xxx
            [3] => Authorization: Bearer xxx
            [4] => if-match: "xxxx"
            [5] => id: PUL233018
        )
[post] => {"id":"PUL233018","fromArchive":true}

[responseinfo] => Array
        (
            [url] => https://platform.reapit.cloud/applicants/PUL233018
            [http_code] => 204
        )

**Comment by plittlewood-rpt** [comment]
Hi @chestertons archiving of applicant data is not currently supported and should be managed using the housekeeping tools in the CRM itself. Our service desk can assist with this. We will review the request as a feature enhancement at our next refinement session

**Comment by chestertons** [comment]
Thanks - can a record on _any_ table be archived ?

**Comment by HollyJoyPhillips** [comment]
Hi @chestertons, no, it's not possible to archive any record via the Platform.
