### ISSUE TITLE
API connection broken

### ISSUE THREAD

**Issue by AdamHall12** [reapit/foundations#10791]
**Background context**
This has only stopped working about 30 minutes ago and has brought down a vital integration of ours. 

The error message on the API call that is failing is: "This application has not been granted the required scope to interact with this endpoint. If your application requires access to this resource, please use the Reapit Foundations Developer portal to request permission to access this resource"

However it was working earlier today and no changes have been made. I have also checked and the app does have the correct permissions.

I am from Rettie & Co - Graham has asked me to tag you @plittlewood-rpt

Is there an expiry on the authentication or something I might have missed?

Thanks

**Comment by jaetoole** [comment]
@AdamHall12 it should work again now

**Comment by olliebennett** [comment]
This also affected us (Goodlord); can confirm it's working again now.

**Comment by AdamHall12** [comment]
Working again, thanks @jaetoole

**Comment by HollyJoyPhillips** [comment]
Hi All, I know you are aware this has been resolved but just in case this is our status page http://status.reapit.com/
