### ISSUE TITLE
Foundations Code & Infra Housekeeping

### ISSUE THREAD

**Issue by willmcvay** [reapit/foundations#10806]
**Background context or User story:**

_There are a number of packages and services that are either not being maintained, or can be deprecated and tidied up from the Foundations codebase. In some cases, they are not included in the "workspaces" glob so would need to be added and removed to perform any infra tear down. My feeling is we can be quite brutal - we always have them in Git history if the code is needed in the future_

**Specification or Acceptance Criteria:**

- [x] Change this line https://github.com/reapit/foundations/blob/master/package.json#L6 to "packages/**/*" so we know all current code is in active maintenance and do a yarn install
- [x] Look at each of the unused packages 
* if they have infra associated, run either `serverless remove` or `cdk destroy` to tear down.
* Delete any config in parameter store with config manager
* Delete the package, and run yarn install to remove any unused dependencies and commit. 

 Repeat for each of:

* [cloud-alert](https://github.com/reapit/foundations/tree/master/packages/cloud-alert)
* [config-service](https://github.com/reapit/foundations/tree/master/packages/config-service)
* [cra-template-foundations](https://github.com/reapit/foundations/tree/master/packages/cra-template-foundations)
* [create-node-app-generator](https://github.com/reapit/foundations/tree/master/packages/create-node-app-generator)
* [elements](https://github.com/reapit/foundations/tree/master/packages/elements)
* [events-service](https://github.com/reapit/foundations/tree/master/packages/events-service)
* [geo-diary-marketing](https://github.com/reapit/foundations/tree/master/packages/geo-diary-marketing)
* [insights](https://github.com/reapit/foundations/tree/master/packages/insights)
* [login-with-reapit](https://github.com/reapit/foundations/tree/master/packages/login-with-reapit)
* [react-app-scaffolder](https://github.com/reapit/foundations/tree/master/packages/react-app-scaffolder)
- [x] Agree between @HollyJoyPhillips @joshbalfour  and @bashleigh that you agree with the list of things to nuke in advance. Should leave us with only code that is in active use and maintenence.
- [x] Run yarn upgrade-all and do any minor version bumps as required
- [x] Remove any packages that are obviously unused now (webpack & serverless plugins for example, we hardly use these now)
- [x] Run yarn dedupe to clean up the cache
- [x] Check build, test, lint are all working

**Comment by bashleigh** [comment]
@willmcvay  What would you like to do with https://www.npmjs.com/package/@reapit/cra-template-foundations ?

**Comment by bashleigh** [comment]
Also can't see which account reapit/elements is being deployed to? Guessing it's still dev-paas? So will not delete resources

**Comment by joshbalfour** [comment]
list looks fine to me 👍

**Comment by bashleigh** [comment]
branch: chore/#10806-housekeeping-remove-unused-packages having to move back to exit-data
