### ISSUE TITLE
 Reapit integration with NEC & iPC - Nottinghill Genesis

### ISSUE THREAD

**Issue by Rawlo007** [reapit/foundations#10802]
Hello,

I am solution architect from NHG working on Reapit < = > NEC integration. We want to know the integration technology Reapit support for this integration.

We are using Microsoft stake for our integrations mainly APIM, Service Bus and Login App etc.  

1.	Do you have Rest API we can consume to created, update and delete records
2.	What technology use are using to consume our API to create and update tenancy
3.	What authentication you are supporting
4.	Do you have any API limit on your platform
5.	Are you supporting real time API integration 
6.	Are you supporting bulk upload    
7.	Can you please share your API contract

Kind Regards

Rakesh Upadhyaya 
Solution Architect  | Digital Technology

We Make Technology Work For You

Phone: 020 3815 1229 | Mobile: 077 3617 1889 | Email: [Rakesh.Upadhyaya@nhg.org.uk](mailto:Rakesh.Upadhyaya@nhg.org.uk)

**Comment by plittlewood-rpt** [comment]
HI @Rawlo007  - please go to https://developers.reapit.cloud/select-role to register your interested with our developer portal and our partnerships team will be in touch. In the meantime, you can access the Platform documentation at https://foundations-documentation.reapit.cloud/ - many thanks

**Comment by RakeshUpadhyaya** [comment]
Hello I cant able to open webhook page to see the fields and map to our system. I also want to know API endpoints for tenancy.

Thanks

**Comment by plittlewood-rpt** [comment]
Hi @RakeshUpadhyaya please see my note above. You will need to register with us at the link specified. One of our partnerships team will then reach out to you to get you set up in our Developer Portal at which point you'll have full sandbox access and access to the Swagger documentation.

**Comment by RakeshUpadhyaya** [comment]
Thanks, I have registered with above link and waiting for your partnership team to setup in your Development Portal and give access sandbox and Swagger documentations.
