### ISSUE TITLE
Shared Contact Entities between Reapit Systems or Brands

### ISSUE THREAD

**Issue by BYM-Henry** [reapit/foundations#10810]
**Summary**
Hi Reapit,

Hope you are all doing well.

We have a question regarding permissions within a Reapit System, is it possible in some Reapit systems to have a Contact object who is shared between brands within a Reapit system (or shared between Reapit systems), but that contact owns role objects (applicant, landlord, etc) which can only be accessed by a certain brand (or Reapit system).

We have a mutual customer who is concerned about us writing back journal entries onto the contact object as it may reveal unwanted data to different brands (or Reapit systems), does this sound like a valid concern, or would this situation not be possible?

Please let me know if this isn't clear as I appreciate its quite an odd question.

Many Thanks,

Henry Fitch
Integrations Developer

**Comment by plittlewood-rpt** [comment]
Hi @BYM-Henry sorry for the delay in responding to this. Ultimately it's up to our customers how they set up the security in their own systems. It's becoming more commonplace to have multiple brands in the same database. Typically data is not shared between these brands and as such any journal entries you write back to us would only be visible to contacts that the branch staff actually had visibility of. I'm not completely sure I understand what they're asking though. If it's roles attached to the contact they are more worried about, then you just need to make sure you attach the journal entry to the role and not the contact, but that's dependent on your own system and the content of the entry. Do you have anything else you could share to help understand the context?

**Comment by BYM-Henry** [comment]
Hi @plittlewood-rpt, cheers for coming back.

We recently went through this requirements in more detail with the customer and have come to the conclusion we will need to writeback to the role instead of the contact.

So I think we can close this ticket for now.

Thanks again for the help.
