### ISSUE TITLE
Update recurrence model commentary in appointments API

### ISSUE THREAD

**Issue by chris-percival-unrvld** [reapit/foundations#10819]
Can the documentation show how I interpret the Appointment Recurrence Until field.  Does the last repeated appointment start date include or exclude the until date?

For example:

Appointment start: 2024-01-01
Recurrence type: daily
Recurrence interval: 1
Recurrence until: 2024-01-04

Would the last occurrence occur on the 3rd or 4th?

**Comment by plittlewood-rpt** [comment]
Hi @chris-percival-unrvld 
`reccurence.until` is an inclusive date, so in your example above, the last occurrence would occur on 4th January. I'll tweak the Swagger documentation to reflect that for anyone with a similar query in the future.

**Comment by chris-percival-unrvld** [comment]
Just to follow up on this, the documentation now says "The date and time of the last occurrence of the appointment". However the until field doesn't contain a time.  As the recurrences are always essentially multiples of days, should I only use the date to determine the last occurrence?

![image](https://github.com/reapit/foundations/assets/108338125/5a109f37-2e00-4aed-b06d-b40b35f81542)
