### ISSUE TITLE
Reapit connect infinite loop

### ISSUE THREAD

**Issue by au63** [reapit/foundations#10839]
We are using the reapit connect session library for a front end app and it works fine for us.
But while demoing for certain clients, it goes into an infinite loop with the state value increasing endlessly like this:

Parameters: {"code"=>"e87fbd38-8429-4c91-a03e-2591dbc57c06", "state"=>"/?state=%2F%3Fstate%3D%252F%253Fstate%253D%25252F%25253Fstate%25253D%2525252F%2525253Fstate%2525253D%252525252F%252525253Fstate%252525253D%25252525252F%25252525253Fstate%25252525253D%2525252525252F%2525252525253Fstate%2525252525253D%252525252525252F%252525252525253Fstate%252525252525253D%252525

And the clients think it is some fault on our side.
I was reading up on openid connect infinite redirect and there were quite a lot of posts stating this problem.
Is there any known solution from reapit staff?

**Specification**
- Some staff have also seen this problem so we should invest some time trying to understand what is going on and if there's anything we can do about it. Clearing the cache generally solves this problem but there's a lack of understanding still as to the root cause
- Ideally we need to be able to break the loop, with the connect-session package if possible. HP thinks she might be able to replicate this so step 1 is to try and replicate on demand
- If we can replicate log separate ticket with full details so we can look at resolving it

**Comment by Speedway1** [comment]
There is a known issue with openid when it's using cookies please see the link below:
https://openid.net/specs/openid-connect-session-1_0.html#ThirdPartyContent

Paragraph 5.1 applies.

We believe that in the CW case, because they use Citrix, this may also have an impact. We are using the Reapit Connect library.

**Comment by AshDeeming** [comment]
Hi @au63 

Please could we ask you advise the app name, example of clients you are seeing this occur along with any other details to: sinfo@reapitfoundations.zendesk.com

**Comment by au63** [comment]
@AshDeeming can you please acknowledge whether you got the email or not?

**Comment by AshDeeming** [comment]
Thanks @au63 
We'll be in touch for me info if required

**Comment by au63** [comment]
we solved by removing the reapit connect library and instead doing the token decoding entirely on the backend and then using server side sessions
