### ISSUE TITLE
Patch statusId with empty value

### ISSUE THREAD

**Issue by chestertons** [reapit/foundations#10846]
using sbox applicant MKT240119
PATCH sending
Array(
    [statusId] => 
    [id] => MKT240119
)
204 status returned, applicant's modified date is updated, but the statusId is not updated

**Comment by plittlewood-rpt** [comment]
Hi @chestertons this might just be that the behaviour needs explaining. I've just tested and it does appear to be working as intended.

If the statusId is empty, the API is designed to return GE (General) which is how the CRM behaves
To clear a field in the API, you need to pass an empty string and not a null value where strings are concerned. When patching, there is a distinction between an empty string and null (the latter just gets ignored as no value as been provided)

Please can I ask you to re-review with the above in mind, and provide more detail if you believe there to still be a problem?

Many thanks

**Comment by chestertons** [comment]
Understood thank you Pete,
