### ISSUE TITLE
Inconsistent statusID mapping

### ISSUE THREAD

**Issue by chestertons** [reapit/foundations#10849]
Following up on https://github.com/reapit/foundations/issues/10846

In our config (CHT), our statusID mapping for a "General" applicant  is set to "GN"; 
However in the default Foundations settings, the API status for statusId when empty is "GE"

Therefore our application is unable to map applicants with a status "GE" to our own config, and unable to set "GN" as a statusId as it doesn't exist on our config

![image](https://github.com/reapit/foundations/assets/146189484/0fe5196f-25c7-41e4-93ca-818944d328ce)

Can you update all our applicants which are set to "GN" to "GE", and change our config to set the "GN" value to "GE"?

**Comment by plittlewood-rpt** [comment]
Hi @chestertons - to rework your existing applicants would be a job for our service team and should be logged through our main helpdesk. This Github project is just for Foundations related features and issues. That said there are two ways we can look to tackle this:

1) As you mention above, refactor GN -> GE in your build. There might be reasons GN was chosen though and so altering it could have downstream implications or
2) We look at the applicants API to determine whether or not we can pick up your own default. 

Option 1 should definitely be explored then we aren't adding additional latency to the APIs, however we'd need our service team to do a deep dive to understand why it's currently setup the way it is before making any decisions.

**Comment by chestertons** [comment]
Thanks, logged
