### ISSUE TITLE
legacy sellingPosition and statudID on API mismatch

### ISSUE THREAD

**Issue by chestertons** [reapit/foundations#10840]
we have applicants whose "sellingPosition" is "renting" eg applicant CHK210770; however when updating, the API will not allow us to use "renting" as a sellingPosition and fails with an error

at the same time we have a legacy "statusID" of "GE" which is also not allowed by the API, and is not listed when querying the applicantStatuses config

Whose config needs to be changed to make these work pls?

**Comment by AshDeeming** [comment]
Hi @chestertons 
Please ensure you are using the configuration endpoint, see below, to understand which positions &/or reasons are inplace, per client;
![image](https://github.com/reapit/foundations/assets/61687775/bea0e726-ddfe-4436-88a1-ec181ef771b9)

**Comment by chestertons** [comment]
Ash?

**Comment by AshDeeming** [comment]
Hi @chestertons 
Could you confirm what database you are referring to please? 

To amend SellingPosition (& any other config setting) would be via the Reapit Service Desk/Reapit CRM Config
