### ISSUE TITLE
sources API does not return all sources

### ISSUE THREAD

**Issue by chestertons** [reapit/foundations#10847]
API seems to only return rows where type is "advertisement" or "source"

Data can be seen in the raw SRC table, so must be a bug?

Thx

**Comment by chestertons** [comment]
We want to make more use of "contact categories" (we have a specific project in mind, but also more generally)

If contact categories data is not exposed in the API this makes it inaccessible?

**Comment by plittlewood-rpt** [comment]
Great thanks for confirming. You can get to the configuration of contact categories at GET platform.reapit.cloud/configuration/contactCategories. Categories can be managed against a contact in the contacts API (POST and PATCH /contacts)

**Comment by chestertons** [comment]
Thanks - How is the "parent" category to be found - eg I can see I can explode "Current Location - Grenada" on the ' - ' string to get parent / child values, but is there a better way?

**Comment by plittlewood-rpt** [comment]
HI @chestertons that's not possible at the current time. We'll refine this in our refinement session tomorrow. It might be that we can add the parentId in this kind of scenario

**Comment by plittlewood-rpt** [comment]
I have logged an issue specific to the requirement to expose the relationship between categories and will close this one. Thanks
