### ISSUE TITLE
Access to the oRegion extras field on the Office record

### ISSUE THREAD

**Issue by whanno-lsl** [reapit/foundations#10856]
**Request**

- The name of the customer you represent
LSL group of customers (YOM, RER, LSI)

- The name of every field you need surfaced (if known)
oRegion on the Office record

- A screenshot of of the field(s) you require in the agency cloud user interface
I don't have access to the AC configuration screen unfort

- A short use case as to why you require this data
We need this to try and identify all offices for a specific franchise. After looking at some reporting queries we think this should give us 
what we need. 

Also with regards to testing this in the AC Developer Edition for the SBOX customer,  we don't have access to set these values so could someone please set oRegion to "SBOX Franchise" for our two main test offices: MKT (Camberwell) & YON (York North), thanks.

**Comment by plittlewood-rpt** [comment]
hi @whanno-lsl the offices API was updated fairly recently to expose the region field. please see `OfficeModel.region` in the swagger documentation. This maps to the oRegion field you mention

**Comment by plittlewood-rpt** [comment]
Hi @whanno-lsl that's now been done. Thanks
