### ISSUE TITLE
Ability to view if a Landlord accepts deposit schemes on a property 

### ISSUE THREAD

**Issue by neilpellowe** [reapit/foundations#10854]
related to PBI-5400

Can we look update the relevant endpoint to include information around the acceptance of deposit schemes. Raised as part of ongoing discussions with an existing Partner. 

**Specification**
- Project: Reapit.Services.Properties
- Add new field `depositSchemeAccepted` to PropertyLettingModel that exposes semi structured field prp.extra.pDepSchemeAccptd (default false)

**Comment by plittlewood-rpt** [comment]
Hi @neilpellowe we'll ultimately need to know where this is stored in AgencyCloud. If it's in there, we can expose it. If it's not, it's either an AgencyCloud enhancement first or the partner can use metadata to store that information themselves. Cheers

**Comment by HollyJoyPhillips** [comment]
Dependent on development from AC (PBI-5400)

**Comment by HollyJoyPhillips** [comment]
AC work has been completed.

**Comment by neilpellowe** [comment]
[like]  Neil Pellowe reacted to your message:
________________________________
From: HollyJoyPhillips ***@***.***>
Sent: Wednesday, April 3, 2024 6:01:10 PM
To: reapit/foundations ***@***.***>
Cc: Neil Pellowe ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [reapit/foundations] Ability to view if a Landlord accepts deposit schemes on a property (Issue #10854)


External Message - Please be cautious when opening links or attachments in email
________________________________
AC work has been completed.

**Comment by plittlewood-rpt** [comment]
Cannot action this until 12.182 starts rolling out

**Comment by HollyJoyPhillips** [comment]
Confirmed filtering on checkbox isn't required and just visibility in the payload is needed.
