### ISSUE TITLE
Landlords API fails with 500 error

### ISSUE THREAD

**Issue by chestertons** [reapit/foundations#10851]
Our request to pull from this API fails; works on sbox instance

https://platform.reapit.cloud/landlords/?PageNumber=1&PageSize=100&sortBy=modified&modifiedFrom=2018-04-03T09%3A03%3A59Z

Server response is immediate 500

Array
(
    [statusCode] => 500
    [dateTime] => 2024-03-06T13:14:59.0965652Z
    [description] => An unexpected error has been encountered when fulfilling this request. This incident has been logged and will be investigated. Please try again.
)

**Comment by plittlewood-rpt** [comment]
@chestertons this is now be resolved and was caused by some bad data in the landlords database which I have now cleaned. Many thanks
