### ISSUE TITLE
API call in Python

### ISSUE THREAD

**Issue by BYMIntegrations** [reapit/foundations#10865]
Hey team,

I hope you are well.

I am trying to make a few calls to the foundations API, one to the Token endpoint and another to the offices endpoint. However, when I make the call the only response I get is 405.

This appears to be a method not supported error. Is there a restriction on the API to prevent python from calling it?

Thanks,

Toby

**Comment by plittlewood-rpt** [comment]
Hi @BYMIntegrations we'd need to see the call you're making to be able to assist with this :) Thanks

**Comment by BYMIntegrations** [comment]
Hello Pete,

Here is the code to make the call:

```
import requests

api_url = "https://connect.reapit.cloud/token"
cus_code = ""
todo = {"client_id": "", "grant_type": "client_credentials", "reapit-customer": cus_code}
headers = {"User-Agent": "PostmanRuntime/7.37.0", "Content-Type": "application/json;charset=UTF-8", "api-version": "2020-01-31", "reapit-customer": cus_code, "Authorization": "Basic "}
response = requests.post(api_url, headers=headers, allow_redirects=True)
print(response)
```

I have removed the sensitive information like client keys and codes?

**Comment by plittlewood-rpt** [comment]
Hi @BYMIntegrations  thanks. From your code snippet above you're not actually passing the data parameter to the endpoint. Here is a minimal example which should work fine:

```
import requests

url = "https://connect.reapit.cloud/token"

payload = 'grant_type=client_credentials&client_id=*********'
headers = {
  'Content-Type': 'application/x-www-form-urlencoded',
  'Authorization': 'Basic ******'
}

response = requests.post(url, headers=headers, data=payload)

print(response.text)
```
