### ISSUE TITLE
Missing transaction category

### ISSUE THREAD

**Issue by robchett** [reapit/foundations#10867]
**Describe the bug**
Transactions of type Rent Insurance/rentins are being displayed in the API as "unknown"

**To Reproduce**
Steps to reproduce the behaviour eg:
1. Look at [transaction](https://platform.reapit.cloud/transactions/TAA24103590) on YOM
2. See "category": "unknown",

**Expected behaviour**
See "category": "rentInsurance" or similar,

**Screenshots**
N/A

**Device (please complete the following information for web issues):**
N/A

**Additional context**
If it's possible to see if any other types have not been mapped that would be great.

**Specification**
- Project: Reapit.Services.Transactions
- Add `TransactionCategory` enum mapping for nomtran.category = "RI" -> rentInsurance. Have checked the other transactions in their system and this is the only one not mapped, likely because rent insurance was added after the API was initially built

**Comment by HollyJoyPhillips** [comment]
Hi @robchett, we are unable to access the transaction link, please can you provide a property or transaction reference?
