### ISSUE TITLE
Access to the 

### ISSUE THREAD

**Issue by samlinesgroup** [reapit/foundations#10878]
Our client wants us to filter by the following statuses:

- 'For Sale - Available'
- 'Sold STC - Unavailable'

They set them here in Reapit:
![unnamed](https://github.com/reapit/foundations/assets/86668891/c19b7e38-880e-49ef-be27-7468d8518293)

However, in the API documentation and indeed the data we receive we can only use statuses like these:

- 'forSale'
- 'forSaleUnavailable'
- 'underOffer'
- 'underOfferUnavailable'

In the old JET feed we were able to request an additional data field called internalSaleStatus which gave us the statuses they want to use, however, I can't see in the Foundations documentation how we get this data - can you please advise?

Many thanks
Sam

**Comment by AshDeeming** [comment]
Hi @samlinesgroup 
Under Offer & SSTC are interchangeable - this is a configuration setting in the CRM

**Comment by samlinesgroup** [comment]
Thanks, but the statuses in the file I attached, what field are they in and
is it available in an api response?

Kind regards
Sam

**Comment by plittlewood-rpt** [comment]
Hi @samlinesgroup as my colleague states, the Under Offer and Sold STC terms are used interchangeable but actually map to the same thing in the database. The API uses the underOffer terminology. Therefore in your example above, Sold STC - Available maps to underOffer in the API, and Sold STC - Unavailable maps to underOfferAvailable

Please refer to the Swagger documentation, specifically `PropertySellingModel` which is returned as part of `PropertyModel`

![image](https://github.com/reapit/foundations/assets/30798627/7dfa5373-8d24-4bba-9325-ac1c57882286)

Many thanks

**Comment by samlinesgroup** [comment]
Thank you, are you able to provide a list of the statuses in the screenshot
that I first provided and the API statuses that each one maps to please?

This will allow us to accurately translate our client's statuses to API
statuses.

Kind regards
Sam
