### ISSUE TITLE
Price filter not working properly

### ISSUE THREAD

**Issue by abelyankov** [reapit/foundations#10876]
Summary: When you have listing in the ZAR currency and trying to filter with the selling.price (priceFrom attribute for filter) it return zero results.

Steps to reproduce: select property with different currency. try to filter on it. then covert to gbp and filter that out, you will see results.

Expected Results: show listings

Actual Results: zero listing in the response.

https://github.com/reapit/foundations/assets/25284754/c45aa396-298d-492e-9912-b69d3fd68426

**Specification**
- Project: Reapit.Services.Properties
- Run through the steps in the video to try and understand where this is falling down. Some options:
  - The conversion back to the system base currency isn't happening correctly or
  - The lack of currency query string parameter means that developers need to (currently) understand the system currency and provide the price values in that currency
- This might not be something we can immediately solve, but understand what's going on is a good first step. Additional tickets to be logged if there isn't a simple fix for this.
- Once we know what's going on, discuss further

**Comment by RWilcox-Reapit** [comment]
Hi @abelyankov 

I've updated this endpoint to support filtering by different currencies using the query parameter 'priceFiltersCurrency'.
This is to give the query context of what currency 'priceFrom' and 'priceTo' are in.

In your example above you'd pass:
properties/?priceFrom=35000000&priceFiltersCurrency=ZAR

This will also still return properties stored in other currencies as long as their price exceeds 35 million ZAR when converted. 

Thanks
Ryan
