### ISSUE TITLE
Where can I see who installed my app, and where can I find their customer ID? Also, how can I use the customer ID in an API call?

### ISSUE THREAD

**Issue by wolffe** [reapit/foundations#10873]
![image](https://github.com/reapit/foundations/assets/910240/bf9111a0-b033-4ab9-922c-8cadc1135a9e)

**Comment by HollyJoyPhillips** [comment]
Hi @wolffe, this section in the documentation should help: https://foundations-documentation.reapit.cloud/faqs#installation
