### ISSUE TITLE
ROM_GCRN - webhook not firing

### ISSUE THREAD

**Issue by Speedway1** [reapit/foundations#10888]
Please see previous ticket: 
#10871

Thank you

**Comment by HollyJoyPhillips** [comment]
Hi @Speedway1, I've picked this up and will come back to you as soon as possible.

**Comment by HollyJoyPhillips** [comment]
Webhooks have been enabled again, we're investigating why it was disabled. I'll leave this ticket open until we have found the route cause and confirm it will remain enabled. Thanks.

**Comment by Speedway1** [comment]
Many thanks for the fast response! Much appreciated.
