### ISSUE TITLE
Webhooks tooling docs link

### ISSUE THREAD

**Issue by plittlewood-rpt** [reapit/foundations#10893]
**Background context**
The Docs link in the Webhooks tooling dashboard currently doesn't do anything. We should make sure there is a comprehensive guide to using the tooling that can be linked to from this button in the app.

**Specification**

**Comment by plittlewood-rpt** [comment]
@HollyJoyPhillips  do we have any documentation written up for this tooling yet (think the answer is no)

**Comment by HollyJoyPhillips** [comment]
Hi @plittlewood-rpt. it's just been merged :)
