### ISSUE TITLE
Tenancy Exchange Date required in Snowflake schema

### ISSUE THREAD

**Issue by SairamKDXFT** [reapit/foundations#10895]
Hi Team,

We need to track "Exchanged Deals," which refers to finalized tenancy agreements. However, the existing schema doesn't have this date. (highlighted in the Screen copy). 

Please Include "Exchange Date" in either the TENANCY_CHECKS or TENANCIES schema. This would allow us to efficiently track this details over a specific period.

Let me me know if any additional details required. 

**Specification**
- Project: Analytics Schema
- Add new REQUIRED_BY_DATE column to TENANCY_CHECKS view model that exposes tenchk.duedate
- Update documentation (new yml spec might be needed for this view, if it does, use the existing commentary from [the documentation ](https://reapit-analytics-schema.prod.paas.reapit.cloud/#/doc/v3893/reapit-analytics/views/tenancy-checks)as a starting point)
- Update Dataedo project (PL will need to do this)

<img width="551" alt="image" src="https://github.com/reapit/foundations/assets/145762206/592cf58a-371f-4964-a279-5fb4d0190936">

**Comment by plittlewood-rpt** [comment]
Hi @SairamKDXFT a new "REQUIRED_BY_DATE" field is now available in the TENANCY_CHECKS view model. Please use the Refresh Share mechanism in the Data Warehouse app to update your dataset. Thanks
