### ISSUE TITLE
Foundations API - Property Domain Model

### ISSUE THREAD

**Issue by mab-rdremza** [reapit/foundations#10905]
Hi,

I'm currently working on a feature to pull customer information associated with a property from Reapit into MABs platform. The assumption we made was there is a one-to-one relationship between property and vendor i.e. a property must have only one vendor, and a vendor must have only one property. We could then rely on the vendor ID associated with a property to fetch the related contact/customer information and store that in our system.

After some investigation in a sandbox environment it looks like this assumption is wrong. Some properties have a vendor, others don't. E.g. in the sandbox environment:

Property MKT240216 is associated with one vendor.
Property MKT240452 is not associated with a vendor.

Is the relationship between property and vendor in fact one to zero-or-one? Is there a visual domain model available from which it is clear how to find customer information associated with a property?

Many thanks

**Comment by mab-rdremza** [comment]
@plittlewood-rpt thank you for the quick response. That has helped clear things up in my mind.

Is there an endpoint within the Foundations API which returns the property type based on a unique identifier? E.g. MKT240452 has property type `Lettings` therefore I know not to expect a relationship with a vendor. Or should this be inferred based on the `_links` collection?

For context, we would like to extend our Reapit Marketplace app so that it is also accessible when viewing a property (currently only accessible from applicants), but only for properties with a vendor.

Thanks

**Comment by plittlewood-rpt** [comment]
Hi @mab-rdremza you should use the `marketingMode` property that is part of `PropertyModel` - this will be `selling`, `letting` or `sellingAndLetting`

**Comment by mab-rdremza** [comment]
Perfect, thank you.

When querying selling properties in the sandbox environment, the property ID and vendor ID are always the same. Is this just a quirk of the sandbox environment or an accurate reflection of production data? E.g.

https://platform.reapit.cloud/properties/AAN240001

Response:
`
{
  "id": "AAN240001",
  ...,
  "selling": {
    "vendorId": "AAN240001",
    ...,
  }
}
`

**Comment by plittlewood-rpt** [comment]
This is correct and expected behaviour. Under the hood, the property and vendor are actually the same database entity, they are just separate concerns in the API.

**Comment by mab-rdremza** [comment]
Makes sense.

Going to close the issue now - thank you for very much for the help.
