### ISSUE TITLE
Property image dimensions

### ISSUE THREAD

**Issue by Jhudell** [reapit/foundations#10917]
Is it possible to access property image dimensions through the API? Specifically in the embedded field of the property API?

Thanks!

**Comment by AshDeeming** [comment]
Hi @Jhudell 
Image dimensions are not currently surfaced via the API

**Comment by Jhudell** [comment]
Hi Ash, 

Is this something that will be added in the future?

**Comment by plittlewood-rpt** [comment]
Hi @Jhudell this isn't something that's likely going to be added without a change going into the core CRM first. Can I enquire as to your use case for this information? You can calculate the dimensions once you've downloaded the file anyway so I'm struggling to see where this information would be useful from a data perspective

**Comment by Jhudell** [comment]
Hi Pete, We are looking to standardise imagery on our website which is powered by the RPS API's so we are hoping to pull out properties that have different image dimensions from these calls.
