### ISSUE TITLE
POST to documents endpoint returns 500 error

### ISSUE THREAD

**Issue by hivetom** [reapit/foundations#10922]
**Describe the bug**
When sending a document to the `documents` endpoint via a POST request, we are receiving a 500 error response:

> [
>   "success" => false
>   "body" => array:4 [
>     "message" => """
>       Server error: `POST https://platform.reapit.cloud/documents` resulted in a `500 Internal Server Error` response:\n
>       {"statusCode":500,"dateTime":"2024-03-19T15:25:36.532863Z","description":"An unexpected error has been encountered when  (truncated...)\n
>       """
>     "code" => 500
>     "errors" => "An unexpected error has been encountered when fulfilling this request. This incident has been logged and will be investigated. Please try again."
>     "attempts" => 1
>   ]
> ]

**To Reproduce**
Steps to reproduce the behaviour eg:
Attempt to send a document to the `documents` endpoint via a POST request for a specific customer ID. (Customer ID I will share in a secure email).

**Expected behaviour**
Document upload success and document ID returned.

**Screenshots**
N/A

**Device (please complete the following information for web issues):**
 - Device: Mac/Server
 - OS: Ubuntu/MacOS
 - Browser N/A (terminal/bash)
 - Version N/A

**Additional context**
N/A

**Comment by plittlewood-rpt** [comment]
Hi @hivetom I can see this in our logs and it's caused by some bad configuration. I'll ask the relevant team to rectify this and confirm back to you once it's resolved. Thanks

**Comment by plittlewood-rpt** [comment]
@hivetom  this should now be resolved. I'd be grateful if you could confirm your app is now able to post documents for this customer. I'll keep an eye on logs this end. Thanks

**Comment by hivetom** [comment]
Thanks @plittlewood-rpt , I have retried the request this morning and can confirm we now get the expected response back.
