### ISSUE TITLE
SOAP Connection

### ISSUE THREAD

**Issue by monolithagency** [reapit/foundations#10926]
Hi,

I have been directed here by a Reapit support team member (https://reapitsupport.refined.site/). I am unsure if this is the correct place to  post this question;

A single, specific, property is not in the feed from Reapit. The issue my client has is with regard to the SOAP client or possibly simply settings within the property in question. For reference;

https://tracker.reapit.net/demo/_doc/web-service/#client

I am of the understanding the property is set to be disabled on all portals but is still set to "show on web".

Please can you let me know if I should be directing this enquiry elsewhere.

Regards,

Michael McBride

**Comment by plittlewood-rpt** [comment]
HI @monolithagency this Github board relates only to the Foundations REST APIs so I'm sorry that you've been pointed here in error. Do you have the ticket reference so I can get you to the right person? Thanks

**Comment by monolithagency** [comment]
Hi, @plittlewood-rpt 

Thanks for the response, I was expecting that this was the case. The ticket reference I have is RSD-274094. I believe I know what the issue is now but I just need to inform the correct person.

Regards,

Michael McBride

**Comment by plittlewood-rpt** [comment]
Hi @monolithagency thanks - I've just read through the history of this case and sorry it's going round the houses. Are you definitely using the SOAP feed for this customer's website? I can see that it looks like you've registered for our Developer Portal which is specifically for our new modern suite of REST APIs. I just want to make sure we're all looking in the same (and correct place!) Thanks

**Comment by monolithagency** [comment]
Hi @plittlewood-rpt,

Yes, I can confirm the website is using the SOAP API as per the link I provided above.

The website has been running for several years now and I have been maintaining it periodically. I signed up for the developer portal just in case we ever needed to implement a different solution.

Regards,

Michael McBride

**Comment by plittlewood-rpt** [comment]
Understood thanks for confirming. The web service is returning that property when using GetGeneralProperty so it's likely something to do with the filters you're applying. I'm assuming you're using GetGeneralProperties and passing a number of parameters. Can you confirm the call you are making to the SOAP endpoint so I can replicate it at this end?
