### ISSUE TITLE
Adding Offices - Documentation 

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#10930]
It specifies in the documentation the office array should be: 

"officeCode": ["MLK", "RPS"],

However, when adding additional offices the following occurs: 

"Payload": {
   "status": "FAILED",
   "reason": "Validation was not met. [officeCode] failed on [officeCode must be a string]"
}

Please confirm the correct payload and update the documentation accordingly. 

Suggested format that my work: 

"officeCode": ["MLK, RPS"],

**Comment by plittlewood-rpt** [comment]
Resolved by https://github.com/reapit/exit-data.reapit.cloud/pull/19
