### ISSUE TITLE
Question on building event filters

### ISSUE THREAD

**Issue by au63** [reapit/foundations#10937]
It says here 'Once your event schema has been built, post it to the appropriate resthooks endpoint'.
![image](https://github.com/reapit/foundations/assets/139497587/33d4e7aa-c5bf-4076-b2fa-5883df548e77)
Can anyone share an example regarding how to post that event schema?
I have looked into the resthooks model but I cannot find anything labelled event schema here
![image](https://github.com/reapit/foundations/assets/139497587/97819297-d7ee-483d-9ddc-b4ff255a2615)

**Comment by AshDeeming** [comment]
Hi @au63 
Please could you provide your email address via support@reapitfoundations.zendesk.com

**Comment by au63** [comment]
> Hi @au63 Please could you provide your email address via [support@reapitfoundations.zendesk.com](mailto:support@reapitfoundations.zendesk.com)

Email sent.
