### ISSUE TITLE
Modifications of Archived records via API PATCH methods

### ISSUE THREAD

**Issue by robchett** [reapit/foundations#10939]
**Is your feature request related to a problem? Please describe.**
The business needs to be able to archive Applicants & Contacts to do housekeeping and speed up data retrieval on the CRM. However, as these Applicants and Contacts are used for other purposes they need to remain modifiable via the APIs so that these users can still be enrolled in Email Marketing with the option for them to unsubscribe themselves without requiring a member of staff to do so via the CRM.

**Describe the solution you'd like**
Modification of Applicants that are archived, at a minimum the ability to change `active`, ideally it would be all fields. For Contacts it is already possible to change `MarketingConsent`. 

**Describe alternatives you've considered**
This is the only way that has been identified that would allow the business to maintain a sizable dataset while also keeping the CRM system performant. 

**Additional context**
```{"statusCode":400,"dateTime":"...","description":"It is not possible to update an archived applicant"}```

**Specification**
- Project: Reapit.Services.Applicants
- Permit updates to Applicants, but _only_ for the active flag. We do something similar with contact marketing consent

**Comment by plittlewood-rpt** [comment]
HI @robchett I'm not sure if this is something we would look to change at this time. From your commentary above, it feels like you might be using the active flag for something it's not intended for. The active flag is really designed to govern whether or not live applicants match to properties and vice versa. It's almost redundant/irrelevant once an applicant gets archived. We made a decision to allow marketing consent information to be updated for archived contacts as that is who you are marketing to and it's a realistic requirement that older contacts might want to opt out of marketing. Is there a reason the marketing consent flag on the contact isn't appropriate for your use case? Thanks

**Comment by plittlewood-rpt** [comment]
PL to speak to customer CSM

**Comment by plittlewood-rpt** [comment]
Hi @robchett followng a call with some of your team yesterday this has now been implemented. Updates to the active flag only are permitted on archived applicants and this change has now been released. Thanks
