### ISSUE TITLE
Video Imagery - New App 

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#10942]
**Issue**: Placeholder image/video link is not rendering correctly: 
**Location**: https://developers.reapit.cloud/apps/new

Examples: 
https://developers.reapit.cloud/apps/new

![image](https://github.com/reapit/foundations/assets/52408607/a3fc43e5-c11c-4c8c-85bf-6e0db759e626)
Website Feed:
![image](https://github.com/reapit/foundations/assets/52408607/1a56a5d5-5cab-48c9-87c5-3da205266e3c)
Server-side: 
![image](https://github.com/reapit/foundations/assets/52408607/c85ac7d1-8520-4705-8ef0-4156463135da)

Location: https://developers.reapit.cloud/desktop

![image](https://github.com/reapit/foundations/assets/52408607/5a5b1ecd-e33f-4da7-94a3-9a4df2e73de4)

**Comment by plittlewood-rpt** [comment]
@HollyJoyPhillips  this still needs releasing just FYI
