### ISSUE TITLE
New office group to support MFA app visibility 

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#10945]
**Summary**: When logging into the MFA app we surface users based on their office group. We have a use case for 'Admin' users to see all users within their organisation. 

To control the security we should: 

- Add new user group - OrgansationUserAdmin. Description 'Users who can administer users within the organisation' 
- This will allow any user part of that group to see all users within their organisation regardless is they are part of an office group already. 

**FE ticket**: https://github.com/reapit/foundations/issues/10946

**Comment by darraghmcgrath3** [comment]
Hi Pete, Thanks for the update on this, should I be able to see all users in the MFA app now? Thanks, Darragh

**Comment by plittlewood-rpt** [comment]
Hi @darraghmcgrath3 not yet, this is the backend ticket. The linked ticket (in the description) needs doing next to update the frontend. Hope this helps! Thanks

**Comment by darraghmcgrath3** [comment]
Great, thanks @plittlewood-rpt.

**Comment by HollyJoyPhillips** [comment]
Hi @darraghmcgrath3, small adjustment needed before we can release this to production, please see https://github.com/reapit/foundations/issues/11028. Once completed, we can release the Marketplace Management app to allow you to set Organisation User Admins which will have full visibility in the MFA app regardless of office groups.

**Comment by darraghmcgrath3** [comment]
Thanks, @HollyJoyPhillips
