### ISSUE TITLE
Slow IAAS deployment

### ISSUE THREAD

**Issue by abrahamseni** [reapit/foundations#10943]
The IAAS deployment stops at the `deploy` task, and this could happens days without the ability to cancel it or do manual deploy.

**To Reproduce**
- Push the new code to a repo
- or do manual deployment via dev portal
- go to Apps > pipeline in dev portal

**Expected behaviour**
- deploy successfully (average time is about 3-4 mins)
- able to cancel in-progress deployment

**Screenshots**
![Screenshot 2024-03-22 011706](https://github.com/reapit/foundations/assets/94949137/08c13822-bca6-4a7e-a2a8-f48cbe930d6c)

This one failed after 1 day
![Screenshot 2024-03-22 011741](https://github.com/reapit/foundations/assets/94949137/d30bacb8-7124-47c6-8411-7e350f926ed0)

**Comment by bashleigh** [comment]
Duplicate #10941

**Comment by abrahamseni** [comment]
closing this issue.
fix with #10956 .
Thanks @bashleigh !
