### ISSUE TITLE
500 returned when requesting journal entries via API

### ISSUE THREAD

**Issue by garrym** [reapit/foundations#10952]
**Describe the bug**
An authorised request to obtain journal entries for a property from the API yields a 500 internal server error.

The request is:

`https://platform.reapit.cloud/journalEntries?propertyId=MYS230021&typeId=PC&typeId=PD&typeId=SF`

I've noticed that this only happens when `SF` is included as an extra parameter for `typeId`. If `typeId=SF` is omitted then the request works fine.

**To Reproduce**
1. Make an authenticated `GET` request to `https://platform.reapit.cloud/journalEntries?propertyId=MYS230021&typeId=PC&typeId=PD`
2. Request works and returns a HTTP status code 200
3. Make an authenticated `GET` request to `https://platform.reapit.cloud/journalEntries?propertyId=MYS230021&typeId=PC&typeId=PD&typeId=SF`
4. Request fails with a HTTP status code 500.

**Expected behaviour**
Expect a 200 response with journal entries of type `PC`, `PD` and `SF`.

**Screenshots**
N/A

**Device (please complete the following information for web issues):**
N/A

**Comment by garrym** [comment]
Actually, on further testing the `SF` doesn't seem to affect it that much. The request seems to generally fail with different `typeId` parameters.

**Comment by plittlewood-rpt** [comment]
Hi @garrym this is something we're aware of as we can see the errors in our logs, and there's a ticket outstanding with our service team to run some housekeeeping and analysis on the journal (Internal ref SI-23163). I'll try and get some information on where this is at. Ultimately the amount of data in the journal is causing some issues with the query optimizer by the look of it which is resulting in the wrong indexes being used when queries execute which subsequently result in slow queries that time out.

**Comment by plittlewood-rpt** [comment]
HI @garrym to try and deal with this at the API layer I've got a PR up that adds a secondary sort (by property id) when the caller passes one or more property ids. It resolves the issue on your own database and helps the optimizer pick the more sensible index to use. I need to run some tests on other datasets before I can get this out to you.

**Comment by plittlewood-rpt** [comment]
HI @garrym this update is just going to production. I can see the timeouts in our logs so I'll keep an eye on them as I'm expecting them to disappear with this update. Cheers

**Comment by plittlewood-rpt** [comment]
HI @garrym logs are looking good at this end and I can't see any further timeouts to the journal API for your production or UAT workloads. I'll wait to hear back from you before I close the item down. Thanks

**Comment by garrym** [comment]
Morning @plittlewood-rpt , I can confirm that the number of errors that we're seeing for this have dropped to zero, so the fix looks good to us.

Thanks very much for looking into this and explaining the fix too. Happy to close the issue.
