### ISSUE TITLE
Reapit App - AgencyCloud Integration Configuration Update

### ISSUE THREAD

**Issue by mab-rdremza** [reapit/foundations#10951]
Hi,

I would like to make an update to the AgencyCloud Integration configuration of a Reapit app that is live and public. The app is currently enabled for "Applicants" and I would like to extend it to "Properties":

![image](https://github.com/reapit/foundations/assets/132556599/f52065c5-8bfa-4613-82f4-23c0f158cf74)

Does this create a revision of the app that requires consent from each customer that has installed the app before it is accepted and deployed, similar to permissions updates?

Many thanks

**Comment by AshDeeming** [comment]
Hi @mab-rdremza 
Only changes to app permission scope requires installed client approval. 

The above mentioned change can be submitted & approved.

**Comment by mab-rdremza** [comment]
@AshDeeming perfect, thank you :)
