### ISSUE TITLE
500 returned when requesting property entries via API

### ISSUE THREAD

**Issue by vb3117** [reapit/foundations#10961]
Description
APP/Client ID : redacted - AD
Reapit Customer Code: LOC-GBRM

**Describe the bug**
An authorized request to obtain properties from the API yields a 500 internal server error.

**The request is:**

https://platform.reapit.cloud/properties?marketingMode=letting&fromArchive=false&isExternal=false&pageSize=25&internetAdvertising=true&lettingStatus=toLet&lettingStatus=tenancyCurrent&lettingStatus=arrangingTenancy&PageNumber=6

I've noticed that this only happens when PageNumber=6 and pageSize=25. Other page request are works fine.

**To Reproduce**

Make an authenticated GET request to **https://platform.reapit.cloud/properties?marketingMode=letting&fromArchive=false&isExternal=false&pageSize=25&internetAdvertising=true&lettingStatus=toLet&lettingStatus=tenancyCurrent&lettingStatus=arrangingTenancy&PageNumber=5**

Request works and returns a HTTP status code 200

Make an authenticated GET request to **https://platform.reapit.cloud/properties?marketingMode=letting&fromArchive=false&isExternal=false&pageSize=25&internetAdvertising=true&lettingStatus=toLet&lettingStatus=tenancyCurrent&lettingStatus=arrangingTenancy&PageNumber=6**

Request fails with a HTTP status code 500 with following message.
{
    "statusCode": 500,
    "dateTime": "2024-03-27T05:30:23.7230501Z",
    "description": "An unexpected error has been encountered when fulfilling this request. This incident has been logged and will be investigated. Please try again."
}

Expected behavior
Expect a 200 response with property entries.

![DJA - Reapit issue](https://github.com/reapit/foundations/assets/114083729/61593c00-bccf-42c5-b0dd-75a983293929)

**Comment by AshDeeming** [comment]
Hi @vb3117 

Please could you confirm the app name -  the ID provided doesn't appear to relate to the app.

**Comment by vb3117** [comment]
Hi @AshDeeming 
App name : Starberry DataXchange AWS

**Comment by plittlewood-rpt** [comment]
Hi @vb3117 this should now be resolved and was caused by some bad data on one of the property records. Many thanks
