### ISSUE TITLE
 Incomplete Applicant Details  in Tenancies table

### ISSUE THREAD

**Issue by SairamKDXFT** [reapit/foundations#10971]
Hi Team, 

We are trying to extract the applicants details for the _Tenancies_ and we could see 56% of them are blanks (since 2021). 

Tried to extract the same using the _Tenancy_Contacts_ table and this table is also not giving the complete details.

Example : Tenancy code:  MAL240008. 
this have applicant information in Tenancies table but no details in _Tenancy_Contacts_ details. 

Could you please check and fix either of the two tables to get the complete information. 

Let me know if any details required.

**Comment by plittlewood-rpt** [comment]
Hi @SairamKDXFT the fix for this has just been merged in so once the job next runs this should be corrected. Thanks

**Comment by plittlewood-rpt** [comment]
Hi @SairamKDXFT the data will be in the tenancy_contacts table, as it's contact relationships for the tenancy. Thanks

**Comment by SairamKDXFT** [comment]
@plittlewood-rpt   Thank you for your prompt clarification. We'll proceed with referencing the Tenancy_Contacts table for applicant information

**Comment by plittlewood-rpt** [comment]
HI @SairamKDXFT this should now be resolved. Thanks
