### ISSUE TITLE
Can Customer create a new tenancytype?

### ISSUE THREAD

**Issue by GoYuno** [reapit/foundations#10975]
Our client wants to create a new Tenancy Type

I cant see it via API so is this something they can 
1. Do themselves?
2. Reapit Account Management can do for them?
3. Its not possible at all in Reapit?

thanks!

**Comment by AshDeeming** [comment]
Hi @GoYuno 
Tenancy Types can be customised per client, for customers to amend/add to these, they will need to log a request via the Reapit Service Desk.
