### ISSUE TITLE
Get customer details from Enquiry

### ISSUE THREAD

**Issue by shaheen-svz** [reapit/foundations#10981]
I have created an APP in the developer portal and connected the API's and below are the steps which we are following:

**Steps**

1. Create access token
2. Get 'negotiatorId' from property details
API: https://platform.reapit.cloud/properties/{id}
3. Get Agent details (officeId) using the negotiatorId
API: https://platform.reapit.cloud/negotiators/{id}
4. Push the Enquiry
API: https://platform.reapit.cloud/enquiries/
Body:
{
"surname": "Tahir Test",
"enquiryType": "salesApplicant",
"message": "testing api",
"officeId": "PLM",
"marketingConsent": "grant",
"sourceName": "Property Finder",
"mobilePhone": "971561139245",
"propertyIds": ["DCH240354"]
}
We got the response as 201 Created.

Now I want to get the details of this customer 'Tahir Test' using his mobilePhone and update other details.

Which API should I use to get above details? I tried 'Read Applicant' API but does not return any results.

**Comment by shaheen-svz** [comment]
Customer name: Dacha Real Estate, Dubai
Company Code: DCH

**Comment by plittlewood-rpt** [comment]
Hi @shaheen-svz an enquiry doesn't become a customer until the enquiry is handled by the agent, at which point they may get added as a contact and/or applicant. If this happens, the enquiry will be updated with an applicantId, which can be used to fetch the details from GET /applicants/{id}. I hope this helps.

**Comment by shaheen-svz** [comment]
@plittlewood-rpt thanks, let me re-check with client and get back to you.
