### ISSUE TITLE
Use production userpool in RC production environment

### ISSUE THREAD

**Issue by joshbalfour** [reapit/foundations#10989]
Previously whenever a new app was registered in the developer portal it would be automatically attached to every identity provider in Cognito. When adding the additional reapit connect provider, this would have caused the dual login screen (with enterprise login options) to be displayed which was undesirable. This was addressed in #11006 and #11007 and these changes are now in production. We also need to update the configuration for the production workload so that when deploying the new Reapit Connect stack to the production account, it skips adding the new provider to every app to prevent the dual login screen.

**Specification**
- Update the .github/workflows/production-merge.yml workflow in the reapit connect project to use the production account number (DM_0_ACCOUNT) and the production user pool id (DM_0_USER_POOL_ID). There is no need to store the account number in a secret.
- Going through the PR process and merging to the production branch will force the stack to update
- When merging, monitor closely as this will be the first time we've tried to push resources to the PaaS production account instead of the dev account. If there are issues with deployment it will be up to Platform to fix as it's our AWS account

**Comment by plittlewood-rpt** [comment]
Meeting scheduled 9/4/24 to discuss this in detail and add spec

**Comment by joshbalfour** [comment]
blocked by #11006 and #11007
