### ISSUE TITLE
Reapit Error message Portal Update request

### ISSUE THREAD

**Issue by Simon-Homeflow** [reapit/foundations#10998]
Chapplins Fareham (TEA-GCHF) reported that some properties were not being uploaded to their Homeflow website. There was a bug in the RFPF processing at our end that has been fixed. They are getting an error message in Reapit which they assumed was linked to the failure for the property to be uploaded to Homeflow. I believe this is coincidental and a Reapit error. Please could you confirm and pass over to the appropriate Reapit helpdesk if that is the case or provide me with log info if it is Homeflow that is causing the error message?

![image](https://github.com/reapit/foundations/assets/119927358/b4181e68-f217-465c-bfd9-643648faa794)

Steps to reproduce the behaviour eg:
1. Go to "marketing details"
2. Click on 'Send to portals'
3. See error

**Expected behaviour**
Property is sent to portals without errormesage

Contact at Chapplins is Darren Johnstone, 01329 283330, darrenjohnstone@chapplins.co.uk

**Comment by AshDeeming** [comment]
Hi @Simon-Homeflow 
Having confirmed with the relevant team, this error relates to RT feed being closed however the data access for yourselves should still be in place
