### ISSUE TITLE
Error when exporting for specific offices  

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#10991]
Error: 
```
"Payload": {
    "status": "FAILED",
    "reason": "Validation Failed, offices or dirs do not exist"
  }
```

Payload example: 

```
{
  "payload": {
    "customerCode": "AWP",
    "ticketRef": "SI-2032024-TEST-01",
    "email": "jdean@reapit.com",
    "officeCode": ["BCK"],
    "ipSource": "193.117.134.197/32",
    "overrides": {
      "databaseCluster": "rpt-test-db-clients-01",
      "databaseName": "rps_awp_test"
    }
  }
}
```

**Current code:** 
`innerDirs.map((dir) => offices.map((office) => `${customerCode}/${office}/${dir}`))`

**Exact file format:** 
Pictures: `${customerCode}/rps/live/pictures/{$office}`
Thumbnails: `${customerCode}/rps/live/thumbs/{$office}`

For Prplet/correspondence (fileman table content) files, as seen in the screenshots below: 
`${customerCode}/rps/live/prplet/{$office}*`

![image](https://github.com/reapit/foundations/assets/52408607/0371c0a3-e3fa-4e0f-b05f-80e2fd271bb0)
![image](https://github.com/reapit/foundations/assets/52408607/f56f862a-e1b4-44d6-932e-a0b456a63f83)

**Comment by bashleigh** [comment]
Have resolved this but the examples photos show the incorrect dir. I've not added the ability to use the test dir within the bucket. The code I've written will not use the test dir
