### ISSUE TITLE
Metadata limited to 500 items

### ISSUE THREAD

**Issue by Ian-T-Price** [reapit/foundations#10990]
**Describe the bug**
It is only possible to return 500 items from a Metadata Schema.

If a 501st item is added to the metadataSchema a seemingly random(?) item is displaced by the new item.

If an unrelated item is deleted then the displaced item reappears.

Thus, all items are being stored but only the last 500 items are available to be used.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a Metadata schema or use BeresfordsReferrals20240329 in the SandBox account
2. Create 500 items in the metadataSchema - The above schema has 500 items
3. Add a new item
4. The item will be added but another item will be displaced.  The displaced item cannot be listed or searched for even in a subset of data.
5. Delete an unrelated item
6. The displaced item will reappear

**Expected behaviour**
All items should be available.  We are looking to store upwards of 20,000 items.

**Screenshots**
N/A

**Device (please complete the following information for web issues):**
 - Device:HP Laptop
 - OS: Ubuntu VERSION="20.04.6 LTS (Focal Fossa)" Linux 5.15.0-94-generic x86_64
 - Browser: Brave [Version 1.64.116 Chromium: 123.0.6312.105 (Official Build) (64-bit)](https://brave.com/latest/)

**Additional context**

**Specification**
Service: Reapit.Services.Metadata, Reapit.Lambdas.MetadataProxy
- Update the Get /metadata endpoint to support the paging filters that are already present
- Allow a maximum of 500 records to be retrieved (Current limit, reducing may cause issues for others)
- This query uses token based paging but don't want to change the response structure here to avoid a breaking change.
-  Instead we will add the token to the `pagedResult` object so users can pass this to retrieve more records

**Comment by RWilcox-Reapit** [comment]
Hi @Ian-T-Price 

Could I ask what the use case for adding 20,000 schemas is? Do you have 20,000 `entityTypes`?
Currently, you only need one schema per `entityType` as they can contain X amount of validation checks.

The endpoint does not currently support paging as we never foresaw a use case for someone having over 500 schemas.
We can go ahead and add support for that if required but just trying to see if we can resolve this another way.

Thanks,
Ryan

**Comment by Ian-T-Price** [comment]
It is not 20,000 entityTypes - heavens, and probably ReapIT, forbid. There is only one production schema.

It is 20,000 items/records in an entityType.  We currently have 10,000 items but I'm working hard to cut down both the items and the fields within the item; this will possibly get as low as 5,000 items. We'll be adding approx. 1,000 - 1,500 items per year after that.

**Comment by RWilcox-Reapit** [comment]
Hi @Ian-T-Price 

Thanks for confirming that makes sense now. So you are hitting the metadata endpoint to retrieve entities for your custom type 'BeresfordsReferrals20240329'

I've updated the spec on the ticket as we'll need to add paging support to the endpoint.

Thanks

**Comment by Ian-T-Price** [comment]
Hello @RWilcox-Reapit 

That is correct.  So my next question is, when will this be scheduled?  A rough timeline of days, weeks, months would be great.  I am, inevitably of course, ready to go live with our app.  so I need to manage expectations with Beresford.

Our metadata item is no more than 2k each so we are well within the 1Mb fetch limit for DynamoDB given that we can get a max. of 100 items on a page.  I therefore assumed that the 500 item limit was an artificial limit for the SandBox account only.     Is this not the case?

Many Thanks, Ian

**Comment by Ian-T-Price** [comment]
Many thanks for this.  I can confirm that the returned results are now as expected ;-)

However, it is a somewhat non-standard approach compared to the rest of the API and it breaks the page and totals  counts.  It is not possible to get the total number of items without stepping though the entire dataset and counting them. If you don't use the TokenBasedPaging then the max totalCount is still reported as 500.

This is not an issue for my app however.

I presume there was a good reason for this solution; I see performance mentioned in #11244
