### ISSUE TITLE
TypeID for certificates 

### ISSUE THREAD

**Issue by amyfixflo** [reapit/foundations#11003]
Hello,

We're [Fixflo] calling the "/properties/{propertyId}/certificates") endpoint to get the certificates for a property and the result contains a TypeId which is a two letter code identifying what certificate it is. When logging into their agent application is there anywhere (we assume this might be in the admin section) we can find these 2 letter TypeId codes. We need them to be able to successfully map their certificates to certain FF entities.

Thanks,

Amy

**Comment by plittlewood-rpt** [comment]
Hi @amyfixflo this is found on the Certificates window in AgencyCloud. Open a Lettings property, then navigate to Attributes -> Applicances, Insurance & Safety, then select a certificate or click the + button on the Safety Checks, Certificates, Insurances & Warranties panel:

![image](https://github.com/reapit/foundations/assets/30798627/01a163c1-9fe8-4349-a2e3-0d133824b74e)


Hope this helps! Worth noting there is a configuration endpoint in the Platform for understanding what types are available which might be more useful for you. GET /configuration/certificateTypes
