### ISSUE TITLE
Getting webhook signing keys

### ISSUE THREAD

**Issue by jmsfwk** [reapit/foundations#11009]
**Summary**

I'm following the instructions in https://foundations-documentation.reapit.cloud/api/webhooks#securing-your-endpoint.

I've generated a token via the client credentials flow but when I try to access https://platform.reapit.cloud/webhooks/signing/08dc3f8c-1bba-412d-8f8c-9a9da6e67b15 I get a 404.

**Comment by plittlewood-rpt** [comment]
Hi @jmsfwk could you possibly send a full curl over to sinfo@reapitfoundations.zendesk.com so I have can have a look at this? I can access the key with that id with no issues so at the very least I'd have expected a 403 instead of a 404 so may need to dig into this a bit. Thanks

**Comment by gareth-evans** [comment]
@plittlewood-rpt I have the same issue too. Have sent curl to the above email address

**Comment by gareth-evans** [comment]
@plittlewood-rpt  is there a reason for requiring auth for getting the public signing keys? There is no risk in making public keys accessible without auth.

The reason I ask is that we'd like to have a single api gateway authorisation lambda for all our webhooks. Requiring auth means that we need to deploy the same lambda multiple times, configured with the client credentials for each app, then ensure that each api gateway stag is configured to use the correct authorisation lambda.

**Comment by plittlewood-rpt** [comment]
The issue with the signing keys endpoint returning a 404 is now resolved. I've logged a separate item to look at the authentication of this endpoint which will be picked up in line with our development processes. Thanks

**Comment by gareth-evans** [comment]
Awesome thanks @plittlewood-rpt
