### ISSUE TITLE
Follow on from 11003.

### ISSUE THREAD

**Issue by amyfixflo** [reapit/foundations#11005]
Following up https://github.com/reapit/foundations/issues/11003. We want to understand where and how we configure/setup new certificates?

**Comment by plittlewood-rpt** [comment]
Thanks @amyfixflo sorry if I misunderstood your message. The customer would need to request that with our service team as it's part of the configuration of the system. We have mechanisms to alter what is in the certificate list and the ids associated with each. It's unlikely that we'd ever change the id of an existing certificate type but the list is indeed configurable.
