### ISSUE TITLE
Reapit API's 500 error code

### ISSUE THREAD

**Issue by KeithLowe** [reapit/foundations#11010]
Issue with Reapit API, checked the logs and looks like we're getting 500s back from Reapit for QA + Live.
Test/uat appear to be OK. 
Mostly looks like GetAppointment requests but there's a GetContacts one in there too - so could be all requests.

Status: 500
Response: 
{"statusCode":500,"dateTime":"2024-04-10T14:49:30.1788935Z","description":"An unexpected error has been encountered when fulfilling this request. This incident has been logged and will be investigated. Please try again."})

**To Reproduce**
Some example calls from our tests earlier today:
___________________________________________________________________ (13:29:46.5677)
GET
https://platform.reapit.cloud/appointments/?pageNumber=1&pageSize=100&embed=property&negotiatorId=VVAI&negotiatorId=FRT8&negotiatorId=HWS9&negotiatorId=OP32&negotiatorId=FT72&negotiatorId=JCD4&negotiatorId=KRW4&negotiatorId=RTY7&negotiatorId=MNTD&negotiatorId=MWL&negotiatorId=LPP1&negotiatorId=ROU5&negotiatorId=K973&negotiatorId=SHP6&includeCancelled=false&includeUnconfirmed=true&fromArchive=false&officeId=MLB&start=2024-04-03T00%3A00%3A00.0000000Z&end=2024-05-22T00%3A00%3A00.0000000Z 
Reapit Request Id: fd46bd66-e215-45db-a959-0374d95a42c7 
Reapit Request Time: 00:00:25.2321882 
Response: 500 
____________________________________________________________________ (13:43:38.5594)
GET 
https://platform.reapit.cloud/appointments/?pageNumber=1&pageSize=100&embed=property&negotiatorId=VVAI&negotiatorId=FRT8&negotiatorId=HWS9&negotiatorId=OP32&negotiatorId=FT72&negotiatorId=JCD4&negotiatorId=KRW4&negotiatorId=RTY7&negotiatorId=MNTD&negotiatorId=MWL&negotiatorId=LPP1&negotiatorId=ROU5&negotiatorId=K973&negotiatorId=SHP6&includeCancelled=false&includeUnconfirmed=true&fromArchive=false&officeId=MLB&start=2024-04-03T00%3A00%3A00.0000000Z&end=2024-05-22T00%3A00%3A00.0000000Z 
Reapit Request Id: 294878bb-2297-4db8-a2a6-5f77595fc1aa 
Reapit Request Time: 00:00:25.3080642 
Response: 500 

Using the live credentials - both had the same response as above in the debug logs

**Expected behaviour**
API transaction to be successfully processed!  

**Screenshots**
n/a

**Comment by RWilcox-Reapit** [comment]
Hi @KeithLowe 
I have been looking into this issue today to understand what's causing this for a small number of clients. 
In the instances and others pulled from logs I can see it's related to some negotiators being associated to large number of appointments. 

One suggestion to prevent this for the immediate future would be to narrow down the start and end date params. The examples given above have a 7 week range which will result in a larger DB hit. 

Can I ask the use case for pulling back 7 weeks worth of appointments in one hit, are you performing a data sync or is this for a screen?

I'm currently looking at ways to improve this query to prevent it timing out, this may end up being broken up into another ticket, I'll keep you updated on here.

Thanks

**Comment by KeithLowe** [comment]
Morning!

Thanks for the update, happy to assist with testing any changes you may need to make.  Looping in Louis for info and more background to the request reasons.

Keith


Keith Lowe | Development Manager | IT Solutions & Development
[Connells Group Logo]<http://www.connellsgroup.co.uk/>
6 Caldecotte Lake Business Park, Milton Keynes
Buckinghamshire, MK7 8JT
Tel:
01908 722865<tel:01908%20722865>
Email:
***@***.******@***.***>
Web:
www.connellsgroup.co.uk<http://www.connellsgroup.co.uk>

**Comment by RWilcox-Reapit** [comment]
Hi @KeithLowe 

I've recently put out some performance improvements to the appointments service. After some testing for your use cases above you should notice significant reductions in response time.

Thanks,
Ryan

**Comment by KeithLowe** [comment]
Hi Ryan,

Thanks, much appreciated.  If we find any further issue we’ll let you know.

Keith


Keith Lowe | Development Manager | IT Solutions & Development
[Connells Group Logo]<http://www.connellsgroup.co.uk/>
6 Caldecotte Lake Business Park, Milton Keynes
Buckinghamshire, MK7 8JT
Tel:
01908 722865<tel:01908%20722865>
Email:
***@***.******@***.***>
Web:
www.connellsgroup.co.uk<http://www.connellsgroup.co.uk>
