### ISSUE TITLE
Error 403 Forbidden using webhooks with API Gateway

### ISSUE THREAD

**Issue by Ian-T-Price** [reapit/foundations#11020]
**Summary**

I am getting Error 403 Forbidden using webhooks with AWS API Gateway

**Details of the issue**

1) I have set up  webhooks using both webhooks.site and pipedream.com These work without issue
2) I have set up an API POST method on AWS API Gateway.  This works without issue from the likes of PostMan.
3) I try to send the webhook to API Gateway and I get 403 Forbidden errors.

**Debugging efforts**

I have tried the following:

a) Setting Authorisation to None
b) Setting no API Key
c) Setting and NOT setting CORS
d) Compared the headers on PipeDream.com with those on API Gateway (from PostMan) - I can not discern any  material differences
e) Enabling full logging on API Gateway; There are no logs generated for the ReapIT webhook, as if it never gets to the Gateway.
f) Exhausted all the suggestions of both ChatGPT & Gemini 
f) I finally set up a workflow on PipeDream.com to receive the webhook from ReapIT and forward it to API Gateway.  This works without issue. 

What is the magic sauce that I'm missing to get the ReapIT webhook to successfully connect to AWS API Gateway?
Any pointers or guide gratefully received.

**Attached**

[i) api-gateway-logs.csv](https://github.com/reapit/foundations/files/14960748/api-gateway-logs.csv) - Sucessful webhook data sent via PipeDream
[ii) api-headers.md](https://github.com/reapit/foundations/files/14960752/api-headers.md) - Headers from both API Gateway & PipeDream

**Comment by plittlewood-rpt** [comment]
Hi @Ian-T-Price you should be able to get around this by using a custom domain on your API Gateway. We have an internal endpoint that currently intercepts all traffic to the AWS api gateway namespace which prevents external consumers using gateways without a custom domain. There are a couple of workarounds:
- Use a custom domain on the gateway
- If you are using a serverless lambda function as the webhook handler, you can use the Function URL to negate the need for a gateway altogether which uses a different dns format

There is currently no timescale for resolving the underlying issue with the routing, but this should hopefully allow you to workaround the problem. Many thanks

**Comment by Ian-T-Price** [comment]
@plittlewood-rpt 

Many, many thanks for the magic sauce, especially considering the promptness & lateness of the hour of the reply.
Gratefully received.

I suspected from Debugging efforts (e) that there was some sort of outbound block.  Not something I would have found innately, although I was about to instigate a custom domain  so I may have stumbled on the solution by accident...

The custom domain is working fine but the functional URL gives a 404 error, again despite the fact it works via PostMan.  It might be a DNS delay issue of course.

Hopefully this issue will provide guidance for others treading the same path, but might I suggest an update to the documentation?  It would have saved a couple of days of my life at least.

Many thanks once again, Ian
