### ISSUE TITLE
Upgrade RDS cluster to use MySQL 8 (Aurora v3) for Cloud Deployment Service stacks

### ISSUE THREAD

**Issue by plittlewood-rpt** [reapit/foundations#11026]
**Background context**
MySQL 5.7 will soon be out of support at AWS and as such we need to test and upgrade the RDS cluster attached to the cloud deployment service stack

**Comment by plittlewood-rpt** [comment]
@bashleigh this one will be for you I think. Can you confirm that this cluster is indeed for IaaS?

**Comment by bashleigh** [comment]
Believe it should be using the `VER_3_03_1` engine. Which is 8.0 aurora mysql? Can you confirm which account it's for? If it's production then we should just need a release @plittlewood-rpt

**Comment by plittlewood-rpt** [comment]
Ah thanks - it looks like this has already been dealt with which means we can close this and #10739 as I'd logged dupliates. We do however need to do this for #10738
