### ISSUE TITLE
Reapit Connect Config - MFA

### ISSUE THREAD

**Issue by darraghmcgrath3** [reapit/foundations#11039]
Hi all, two of our staff members have reported issues with configuring the MFA app on Microsoft Authenticator, getting the below error even when the code is correct and far from expired. Has this been reported by anyone else? 

![image](https://github.com/reapit/foundations/assets/118818916/bbddd401-05da-4918-a41e-f0af3830f176)

Thanks, Darragh

**Comment by plittlewood-rpt** [comment]
Hi @darraghmcgrath3 can you confirm if the time on the MFA device is correct? The identity provider accounts for some clock skew but not a huge amount so if the time on the device is out by more than a minute you'll run into this problem. Our service desk can assist with troubleshooting if required. Thank you

**Comment by HollyJoyPhillips** [comment]
Hi @darraghmcgrath3, it looks to be related to the time on the device, please see the following link for more information: https://reapit-mfa-documentation.reapit.cloud/troubleshooting

**Comment by darraghmcgrath3** [comment]
Thanks @plittlewood-rpt & @HollyJoyPhillips - will try that now and let you know if the issue persists.

**Comment by HollyJoyPhillips** [comment]
Hi @darraghmcgrath3, did you manage to resolve this for those users?

**Comment by HollyJoyPhillips** [comment]
Thank you.
