### ISSUE TITLE
Sutton Kersh (SUT) Website Feed

### ISSUE THREAD

**Issue by AdamBakerCG** [reapit/foundations#11035]
I have been asked by Reapit Support to raise a GitHub for a question related to whether Ina4 (Sutton Kersh) are using the most up to date API for their property portal? They currently aren't pulling across any of the NTS type A details but not sure if this is due to them using an incorrect API or they havent been given the latest Schema to setup the pull?
 
These are the details they use:
Reapit URL:   https://webservice.reapit.net/sut/?wsdl
ClientID: INA4

This links to https://reapitsupport.refined.site/portal/1/RSD-282088

Response from Support

"The Foundations team are saying they should be able to implement these fields for SUT, I was trying to avoid asking you to raise a ticket on Github, but they need one as they will have to decide if it’s possible to keep the webservice feed or switch to Foundations.

So can you please raise this request on Github, they asked that you mention the fields, Part A includes, Price, council tax and tenure please see the name of the fields below.

the property price/rental price
Table: PRP
Field: PRICE
Field: MAXPRICE
Field: MINPRICE
the council tax band (or property rates information in Northern Ireland)
Table: PRP
pCouncilTaxBand=''
tenure information (for sales).
Table: PRP
Field: TENURE
Field: ENDLEASE
Kindest Regards,"

Thanks in advance

**Comment by AshDeeming** [comment]
Hi @AdamBakerCG 
All these fields are available in the Platform API - see the interactive swagger docs; https://developers.reapit.cloud/swagger

**Comment by plittlewood-rpt** [comment]
Hi @AdamBakerCG sorry you are being passed round a bit on this. The old webservices are in care and maintenance now and as such no further development is planned. When the type A legislation came out a couple of years ago, all the necessary changes were made to the Foundations Platform APIs (hosted at the entrypoint platform.reapit.cloud) and customers were encourage at the time to start making the switch to the new Platform. I'm surprised this has come up now so long after type A rules were introduced. Ultimately, the feed mentioned is no longer being updated and hasn't been for around 2 years now so InA4 will need to move over to using the Foundations APIs to power the website.

**Comment by plittlewood-rpt** [comment]
Hi @AdamBakerCG sure - they can just navigate over to https://developers.reapit.cloud/select-role and click through the relevant options. Our partnerships team will then get in touch to get them up and running.
