### ISSUE TITLE
Can't create new tenancy check with specific checkTypeId

### ISSUE THREAD

**Issue by abrahamseni** [reapit/foundations#11049]
SAV:
when creating new tenancy check with this payload, it return an error:
```json
{
  "checkTypeId" : "LHO110"
  "status" : "needed"
  "type" : "preTenancy"
}
```

Error return:
```json
{
    "statusCode": 404,
    "dateTime": "2024-04-19T06:11:12.2643186Z",
    "description": "Entity \"Source\" (LHO110) was not found."
}
```

Expected result: creating tenancy check without error.

**Comment by MatthewGoddard** [comment]
Hi All,

This has now been resolved. It was in issue created by support deleting the check on RSD-282983 🤦🏻‍♂️.

Matt

**Comment by plittlewood-rpt** [comment]
Thanks Matt - that was going to be my first check!
