### ISSUE TITLE
Archived Property Webhook

### ISSUE THREAD

**Issue by adamcollison85** [reapit/foundations#11044]
We have been getting reports that we are not reflecting the archived property status on our end.

We leverage the property.modified webhook to handle this.

We have just checked a recent one and it looks like the "fromArchive":false notes is false... Is there a bug at your end regarding this?  

When a property is changed to archived we would expect this to be set to true in the subsequent webhook.

Can you please clarify if this is a bug or if there is another way for us to detect this.

Happy to supply webhook contents and further details, please email support@prospectorpro.co.uk and we can provide details on request.

**Comment by plittlewood-rpt** [comment]
Hi @adamcollison85 we do not send webhooks for any archived records. When a record is archived, it will come through to you as a properties.modified event and appear as a deletion (where you have a null "new" object, and a populated "old" object). Hope this helps :)
