### ISSUE TITLE
Including 'Additional Information' in feed

### ISSUE THREAD

**Issue by will-yellowpeach** [reapit/foundations#11045]
Please can we request that the 'Additional Information' field is included as part of the Charters Estate Agents (CHR) feed.

![Screenshot 2024-04-18 at 14 09 26](https://github.com/reapit/foundations/assets/64958924/2639dfea-7f99-4558-a6a3-d2bd93a80f23)

**Comment by HollyJoyPhillips** [comment]
Hi @will-yellowpeach we've now enabled 'pAdditionalInformation' for CHR, which can requested as an additional query param. 

For example: 
https://platform.reapit.cloud/properties/ABC00000?extrasfield=pAdditionalInformation

For more information, please visit: https://foundations-documentation.reapit.cloud/faqs#certain-fields-are-not-exposed-by-default-in-the-platform
