### ISSUE TITLE
Savills - Expose Pre-Ten Check Status within API 

### ISSUE THREAD

**Issue by RLAV1** [reapit/foundations#11046]
**Request**

In order for us to grant access to Semi-structured 'extras' field data, please provide the following information in this request:

- The name of the customer you represent - Savills 
- The name of every field you need surfaced (if known) 
- A screenshot of of the field(s) you require in the agency cloud user interface
- A short use case as to why you require this data

Within Agency Cloud Version 12.178.00 a new field has been development for Savills called "Pre-Tenancy Checklist status"
![image](https://github.com/reapit/foundations/assets/125357332/e49ee94a-267e-4813-9230-f42b0fbc4d10)

Custom values can be added via config - custom lists 
![image](https://github.com/reapit/foundations/assets/125357332/034c5e63-bf4e-432a-88d7-c504990def2e)

Savills have a long list of Pre-Tenancy Checks which are broken into 4 status', these status require to be reported on which has now been completed via development - however for the system to report on changes made to this field via the App- the data will need to be exposed in the API so that Savills software Seni team can ensure changes made in the App are reflected in the system UI 

Any further info needed or Queries do let me know 

**Specification**
- Project: Reapit.Services.Configuration
- Add new endpoints GET /preTenancyCheckStatuses and GET /preTenancyCheckStatuses/{id} that expose the values stored in system configuration (uPreTenChkStatus) as a collection in the same way the other endpoints work

- Project: Reapit.Services.Tenancies
- Familiarise yourself with this functionality in AgencyCloud before proceeding. Requires statuses to be setup as per the screenshot above in System Configuration, which then enable the Pre Tenancy Check status on the tenancy screen
- Add new `string preTenancyCheckStatusId` field to `TenancyModel` (the status is stored against the tenancy, not each individual check) which exposes ten.extra.tCSCurKey
- Add new item to `_links` where preTenancyCheckStatusId is not empty/null that links off to the respective configuration service endpoint
- Add new `string preTenancyCheckStatusId` field to `UpdateTenancyModel` to allow the same field to be updated. For write operations:
  - Validate that the supplied value is valid. Use the ConfigurationClient package to do this. This also takes care of third parties trying to use this field when there is no configuration, as the same validation will fail
  - When updating the field, a journal entry should be written into jnlmisc against the tenancy with the content `Pre-Tenancy check status changed from {x} to {y}` - this should be associated to the user making the change (taken from PlatformIdentity) if available, or assigned to the negotiator associated with the tenancy for machine to machine applications. . You will want to update the Reapit.Packages.Journalisation package to support this entry type
  - When updating the field, change dates should be stored in ten.extra as follows:
    - ten.extra.tCSCurDate -> DateTime of the latest change
    - ten.extra.tChkStatXX -> DateTime of the latest change to status XX

**Comment by HollyJoyPhillips** [comment]
Reached out to Ross for more information

**Comment by AshDeeming** [comment]
![image](https://github.com/reapit/foundations/assets/61687775/d0008829-3ff6-4908-abf1-ed58fb04b5ce)

tChkStatNE - Negotiaton
tChkStatAD - Admininstration 
tChkStatAP - Approval
tChkStatCO - Complete

**Comment by AshDeeming** [comment]
Hi @RLAV1 
Please could you confirm this issue/request can now be closed?

**Comment by RLAV1** [comment]
Hey @AshDeeming has the work now been completed? if so then yes this can be closed, if not this will need to remain open until completed.. 
i can see Holly was requesting additional information in which was provided on the same day.. so i assume this needs to have the label "Not Ready" removed and the label "to review" re added

**Comment by HollyJoyPhillips** [comment]
Thanks both, I've moved this back into refinement.

**Comment by plittlewood-rpt** [comment]
Hi @RLAV1 - the title of this ticket is to expose ten check status, but your comments seem to elude that the app they're building will _update_ these values. Can you confirm this please?

**Comment by RLAV1** [comment]
Hey @plittlewood-rpt  
The app that has been built by Savills replaces our Pre-Tenancy check screen 
the Pre-Ten check status' are updated via the app but are not then reflect in Agency Cloud based on the new data fields developed to store this data (the list has been provided above where these fields are now available in Agency Cloud) which are not updated based on the status changes within the APP 
This request is to expose the data within the API so that this can take place. 
Therefore the request still stands that this data is required to be exposed in the API

**Comment by MatthewGoddard** [comment]
@plittlewood-rpt and @cduggan-reapit For clarity, the request here is for READ, POST and PATCH please.
