### ISSUE TITLE
Tenencies - meter reading question

### ISSUE THREAD

**Issue by GraemeHTM** [reapit/foundations#11067]
This is just an general tenancy (get tenencies/{id}) question please. Can you confirm meter readings are only a date and reading, it's "never" two two dates and two readings?

      "meterReadingGas": "012111",
      "meterReadingGasLastRead": "2022-02-18",
      "meterReadingElectricity": "1000123",
      "meterReadingElectricityLastRead": "2022-02-26",
      "meterReadingWater": "111022",
      "meterReadingWaterLastRead": "2022-02-21",

**Comment by AshDeeming** [comment]
Hi @GraemeHTM 
THat's correct per tenancy
