### ISSUE TITLE
Property status through the API

### ISSUE THREAD

**Issue by BYMIntegrations** [reapit/foundations#11079]
Please take a look at our FAQ's before submitting an issue, as your question may already be covered in the documentation https://foundations-documentation.reapit.cloud/faqs

**Summary**
When querying properties through the API, what status are we expecting to see on properties marked as Sold STC - Available?
**Detail and or supporting links and screenshots**
A customer has provided the status history change of a property as shown below:
![image](https://github.com/reapit/foundations/assets/102583061/6d8e9da7-e05e-4013-ab02-21ada86d080b)
When we have been calling the API on this property, we have been receiving 'Under Offer' as the status, is this working as intended?
Is this status a base reapit status or is it somehow custom?

**Comment by plittlewood-rpt** [comment]
Hi @BYMIntegrations under offer and Sold STC are interchangeable in AgencyCloud., You can use the GET /configuration/terminology endpoint to understand which is in use in a particular build govern what you display in the UI.

**Comment by BYMIntegrations** [comment]
Hi @plittlewood-rpt ,

I have done a GET to /configuration/terminology and it has returned 
`{
    "properties": {
        "useSoldStc": true,
        "useMarketAppraisal": true
    }
}`

Does this mean that we should be receiving both under off and sold stc? I am only ever getting Under offer for properties.
Do you mean that you will return the same status regardless of whether a property is marked Sold STC or Under offer?
What do you mean by them being interchangeable, because they are objectively not the same thing?

**Comment by plittlewood-rpt** [comment]
Hi @BYMIntegrations sorry if I'm not clear. The propeties API uses the underOffer terminology _always_ - the purpose of the terminology endpoint is to allow you to understand which terminology a particular customer is using. In this case, they've opted to display this status as Sold STC instead of Under Offer.
