### ISSUE TITLE
Fixflo <> Reapit advanced integration // Company API 

### ISSUE THREAD

**Issue by katedeedman** [reapit/foundations#11074]
Hi all,

One of our mutual clients (will share the name via email) is having trouble with some archived companies syncing into Fixflo as Active. This isn't intended behaviour. One example is PMG22000094 but when we call your APIs to get a list of all the companies in this agency, it's not there. 

Would someone be able to help us understand why it's not being returned?

Many thanks!

Kate

**Comment by AshDeeming** [comment]
Zendesk 1124 updated
