### ISSUE TITLE
Web Components should be deployed to NPM

### ISSUE THREAD

**Issue by willmcvay** [reapit/foundations#1107]
**Specification or Acceptance Criteria:**

- I should be able to NPM install the web components package and import each of the modules as a ES or Common JS module
- Should deploy to NPM via normal prod release process
- Each web component should be a single module from a single package so will require multiple files from the same dist. We can add an index.js if this helps distribution.

**Comment by phmngocnghia** [comment]
Update more scopes of this ticket:
- Web-component start:dev script is live-reloadable when editing theme files
- Demo-site start:dev script should now be live-reload (edit ejs file, assets of svelete depedencies packages, themes will rebuild, and the browser reloading it self)
- Fix bug: Property detail page not render view-booking component

**Comment by willmcvay** [comment]
Created a release for v0.0.6 and NPM deploy task failed am afraid. NPM says we are still on v0.0.4. Can you investigate please @phmngocnghia
