### ISSUE TITLE
couldn't have 'hectares' external areas type value in property model (patch)

### ISSUE THREAD

**Issue by ss-dimasm** [reapit/foundations#11083]
**Describe the bug**
can't have hectares value when did an update operation to single property

**To Reproduce**
Steps to reproduce the behaviour eg:
1. Hit patch to properties endpoint with the following payload
2. See the latest get result with get

**Expected behaviour**
the 'hectares' type should be saved

**Payload**
```json
{
  "externalArea": {
    "type": "hectares",
    "min": 100
  }
}
```
**Additional context**
SBOX
api version = 2020-01-31

**Comment by RWilcox-Reapit** [comment]
Hi @ss-dimasm 

This issue has now been resolved. 
We now handle the conversion of hectares to acres on POST/PATCH but always return it as acres due to the functionality in AC.

Thanks
