### ISSUE TITLE
HAH - 'Completion Status', 'Payment Method' and 'No. of cheques' semi-structure fields

### ISSUE THREAD

**Issue by MatthewGoddard** [reapit/foundations#11081]
In order for us to grant access to Semi-structured 'extras' field data, please provide the following information in this request:

- HAH
- Three fields
1. pComStat
2. pPayType
3. pNoOfCheq
- ![image](https://github.com/reapit/foundations/assets/10115484/88fac7b1-24a7-4884-91b1-845b424839d1)
- These fields have been added to the Attributes screen for us and we now want to present them on our website

**Comment by AshDeeming** [comment]
Hi @MatthewGoddard 

This appears to match the request - #11070 which will be updated with the values asap
