### ISSUE TITLE
Fixflo - Reapit advanced integration

### ISSUE THREAD

**Issue by Valentinamorofixflo** [reapit/foundations#11091]
Please take a look at our FAQ's before submitting an issue, as your question may already be covered in the documentation https://foundations-documentation.reapit.cloud/faqs

**Summary**
I am Valentina, Senior Onboarding Executive at Fixflo. I am onboarding a new Lomond branch - Beals Estate Agents.
We went live yesterday and have 2 questions
- Work order not syncing - IS14526922- RPT24048517. The webhook is successful and here is a screenshot of it but the client is not seeing this on reapit. Our senior devs asked to raise this with you
![Screenshot 2024-04-30 135932](https://github.com/reapit/foundations/assets/158284995/bbaa552e-0acc-4f67-ba94-c5f3c3f06422)

-Some properties are not syncing ie BAY230003, BSE180088 - the error given is ''Property will be archived if previously imported - property has no letting on Reapit, property letting Agent Role not set not is import list, property marked as archived 02/23/2024 22:51:29''. Our devs asked to clarify this since we are unaware if something is missing at these properties hence preventing the sync

Please let me know if you have any questions and thanks in advance!

Vale

**Comment by plittlewood-rpt** [comment]
HI @Valentinamorofixflo sorry for the delay getting back to you on this. I've just checked the Lomond build and can see that works order but it's got a status of Cancelled now. Do you still require support on this? Thanks

**Comment by Valentinamorofixflo** [comment]
Hi @plittlewood-rpt - thanks for getting back to me!

To confirm - the Works order is in Reapit and it has been cancelled so the Agency has visibility of this - correct?

Thanks in advance

**Comment by plittlewood-rpt** [comment]
Hi @Valentinamorofixflo yep it is indeed:

![image](https://github.com/reapit/foundations/assets/30798627/39cbfddf-d855-402e-9ffa-6fa5eafce3af)

**Comment by Valentinamorofixflo** [comment]
@plittlewood-rpt fantastic thank you! We were not able to see the works order at the property profile but thanks for confirming! Will flag this to the client! - best, Vale
