### ISSUE TITLE
Access to Properties oInetSV extras field

### ISSUE THREAD

**Issue by garrym** [reapit/foundations#11102]
**Request**

In order for us to grant access to Semi-structured 'extras' field data, please provide the following information in this request:

- The name of the customer you represent
Savills
- The name of every field you need surfaced (if known)
oInetSV for Properties

- A screenshot of of the field(s) you require in the agency cloud user interface
I've not seen the field in the agency cloud user interface

- A short use case as to why you require this data
This contains the office code of properties stored in Reapit. We need this to construct public URLs for our properties.

Please enable retrieval of this field on both our UAT and production environments.

**Comment by plittlewood-rpt** [comment]
Hi @garrym this has already been enabled for both UAT and Production systems. This field is available from the offices API and not the properties API as you are requesting, as it is an office level configuration. Hope this helps.
