### ISSUE TITLE
Add No Internet Advertising field to PROPERTIES view

### ISSUE THREAD

**Issue by ktanalyst** [reapit/foundations#11105]
**Background context**

Within the property card marketing section, there is a tick box to denote whether a property should not be marketed on the internet. This would be a really useful field to report on - primarily to track the levels of interest these properties get when compared with similar properties that are marketed online.

Please can this field be added to the PROPERTIES view?

![image](https://github.com/reapit/foundations/assets/143076147/36366a9d-3e4e-4e34-b66a-a1178e15a6a0)

**Specification**
- Project: Analytics Schema
- Add new field to PROPERTIES view model as below

| Analytics Schema Field | AgencyCloud Mapping | Notes |
| --- | --- | --- |
| INTERNET_ADVERTISING | prp/prp_a.nointadv | Watch out: This field exposes the INVERSE of the AgencyCloud field |

- Ensure schema yaml is updated
- Ensure documentation is updated

**Comment by plittlewood-rpt** [comment]
@ktanalyst this is now available as per the spec above. Please use the Refresh Share mechanism in the Data Warehouse app to update your schema. Thanks!

**Comment by ktanalyst** [comment]
Thanks @plittlewood-rpt - appreciate it being sorted so quickly!
