### ISSUE TITLE
Developer Edition fails installation due to Webview2 already being installed

### ISSUE THREAD

**Issue by garrym** [reapit/foundations#11100]
**Describe the bug**
I'm trying to install developer edition `12.182.1`, downloaded from https://updates.reapit.com/awsdev/publish.htm with Microsoft Edge but unable to because Microsoft Edge Webview2 is already installed.

I uninstalled the previous version of Reapit before attempting installation. I've also tried to uninstall Microsoft Edge Webview2 from my add/remove programs menu in Windows 11, but there is no option to remove that.

When installing I get the following screen: 
![image](https://github.com/reapit/foundations/assets/1433438/10ea97d5-b465-40c4-9f69-41f0d03c55c3)

After continuing I get an Edge installation failed screen:
![image](https://github.com/reapit/foundations/assets/1433438/ebffa0a6-427e-482a-9297-ae399fb70472)

Which then results in the Reapit installation failing with the following:
![image](https://github.com/reapit/foundations/assets/1433438/0adf022c-484d-498f-9881-77ad0d0dbc4c)

I'm now stuck as I don't have the previous version of Reapit to use and the upgrade fails.

**To Reproduce**
See above

**Expected behaviour**
Reapit Developer Edition should install, and update Edge Webview2  

**Screenshots**
See above

**Device (please complete the following information for web issues):**
- PC
- Windows 11 Pro 64-bit 23H2 22631.3447
- Edge 124.0.2478.67 (Official build) (64-bit)

**Additional context**
None

**Comment by AshDeeming** [comment]
Hi @garrym 

Please could you delete the current & previous versions in the registry

- Press Windows Key + R: This key combination opens the Run dialog box.
- Type “regedit”: In the Run dialog box, type “regedit” (without quotes) into the text field.
- Press Enter or click OK: Hit Enter on your keyboard or click OK to launch the Registry Editor.

 
Find CurrentVersion & PreviousVersion - right click both & delete. 
 
Then relaunch RPS Developer Edition & you should see the Reapit Connect screen.

**Comment by garrym** [comment]
Thanks Ash, that worked. I'm now able to open it.
