### ISSUE TITLE
Failed to install new Agency Cloud

### ISSUE THREAD

**Issue by abrahamseni** [reapit/foundations#11106]
Installing the newest Agency Cloud failed.

screen recording:
https://github.com/reapit/foundations/assets/94949137/6055578f-447d-4e24-911c-4243199f6091

**Comment by AshDeeming** [comment]
Hi @abrahamseni 
Please could you delete the current & previous versions in the registry:

- Press Windows Key + R: This key combination opens the Run dialog box.
- Type “regedit”: In the Run dialog box, type “regedit” (without quotes) into the text field.
- Press Enter or click OK: Hit Enter on your keyboard or click OK to launch the Registry Editor.
- Find CurrentVersion & PreviousVersion - right click both & delete.

Then relaunch RPS Developer Edition & you should see the Reapit Connect screen.

**Comment by DataMC-BenFung** [comment]
> Hi @abrahamseni Please could you delete the current & previous versions in the registry:
> 
> * Press Windows Key + R: This key combination opens the Run dialog box.
> * Type “regedit”: In the Run dialog box, type “regedit” (without quotes) into the text field.
> * Press Enter or click OK: Hit Enter on your keyboard or click OK to launch the Registry Editor.
> * Find CurrentVersion & PreviousVersion - right click both & delete.
> 
> Then relaunch RPS Developer Edition & you should see the Reapit Connect screen.

Hi @AshDeeming , I have the exactly the same issue as @abrahamseni. I followed your above steps but it didn't work for me.

1. Delete the current Version in regedit
https://github.com/reapit/foundations/assets/168748770/ddd86a5e-dbc4-46f4-a3be-bcb279a5a2ad

2. Back to Reapit Connect screen, and run a new version
https://github.com/reapit/foundations/assets/168748770/d839b69f-9f4a-4e1f-b683-14fb78870a44

3. Same issue again
https://github.com/reapit/foundations/assets/168748770/26b0f43a-3c31-42e9-9c77-b19682581ac9

**Comment by AshDeeming** [comment]
Hi @DataMC-BenFung 
Please could you unistall & then reattempt the install using Edge?

**Comment by DataMC-BenFung** [comment]
> Hi @DataMC-BenFung Please could you unistall & then reattempt the install using Edge?

@AshDeeming May I know what exactly should I uninstall?

**Comment by AshDeeming** [comment]
Hi @DataMC-BenFung 
Any instances of RPS /AgencyCloud please

**Comment by DataMC-BenFung** [comment]
> Hi @DataMC-BenFung Any instances of RPS /AgencyCloud please

Hi @AshDeeming, I tried that already and showing the same screen as before.

May I know if it is correct to use the following setupdev to install RPS?
<img width="573" alt="image" src="https://github.com/reapit/foundations/assets/168748770/2bf78597-f3b2-4635-84b5-d99e56d730b3">

I also tried to download the RPS from https://updates.reapit.com/awsdev/publish.htm
but it failed to run on my machine.

<img width="301" alt="image" src="https://github.com/reapit/foundations/assets/168748770/78b133a6-c74e-4ec7-b619-3845bd870896">

Here is the log in the Details:
[RDS_Log.txt](https://github.com/reapit/foundations/files/15190545/RDS_Log.txt)

**Comment by abrahamseni** [comment]
> Hi @abrahamseni Please could you delete the current & previous versions in the registry:
> 
> * Press Windows Key + R: This key combination opens the Run dialog box.
> * Type “regedit”: In the Run dialog box, type “regedit” (without quotes) into the text field.
> * Press Enter or click OK: Hit Enter on your keyboard or click OK to launch the Registry Editor.
> * Find CurrentVersion & PreviousVersion - right click both & delete.
> 
> Then relaunch RPS Developer Edition & you should see the Reapit Connect screen.

Thanks @AshDeeming , this works.
@DataMC-BenFung my steps:
- uninstall all RPS instances in the control panel, 
- remove the CurrentVersion and PreviousVersion in the registry,
- restart
- install the app again using the link: https://updates.reapit.com/awsdev/publish.htm

Hope it works.

**Comment by DataMC-BenFung** [comment]
> > Hi @abrahamseni Please could you delete the current & previous versions in the registry:
> > 
> > * Press Windows Key + R: This key combination opens the Run dialog box.
> > * Type “regedit”: In the Run dialog box, type “regedit” (without quotes) into the text field.
> > * Press Enter or click OK: Hit Enter on your keyboard or click OK to launch the Registry Editor.
> > * Find CurrentVersion & PreviousVersion - right click both & delete.
> > 
> > Then relaunch RPS Developer Edition & you should see the Reapit Connect screen.
> 
> Thanks @AshDeeming , this works.
> 
> @DataMC-BenFung my steps:
> 
> * uninstall all RPS instances in the control panel,
> * remove the CurrentVersion and PreviousVersion in the registry,
> * restart
> * install the app again using the link: https://updates.reapit.com/awsdev/publish.htm
> 
> Hope it works. Note: change your timezone and region to UK if you are not in UK.

Thanks for the advice. 
I just discovered that the link https://updates.reapit.com/awsdev/publish.htm only works on Edge.
However, after completing your steps, it still didn't work for me.

I even tried to install it into a new device using the above link through Edge.
And I get the same error in the new device as well.

**Comment by DataMC-BenFung** [comment]
Hi @AshDeeming, is there any workaround?

**Comment by AshDeeming** [comment]
Hi @DataMC-BenFung 

Once any instances of RPS have been uninstalled, versions removed from key reg & the email hyperlink opened via Edge - this should allow the Reapit Connect screen to load. 

Could you confirm if you are on a virtual machine?
