### ISSUE TITLE
how to get advertising data?

### ISSUE THREAD

**Issue by nurm717123** [reapit/foundations#11115]
**Summary**
we need to make a property and applicant journal page (similar like the AC), but there is a advertisement section in property's journal which I didn't know where is it come from, the question is 
- where should we get the advertising list with swagger?
- is it possible to get all structured property/applicant journal data (only providing the propertyId or appplicantId) ?, because currently we have to fetch it one by one (eg: fetch journal entry, task, referral for property) and combine it

**Detail and or supporting links and screenshots**
- **Property's journal**
![image](https://github.com/reapit/foundations/assets/106480336/fa64e9af-9d04-4643-b2fd-1caee91906c6)

- **Property's advertising**
![image](https://github.com/reapit/foundations/assets/106480336/e5272631-7e65-43c4-a9ef-818493a1c8db)

**Comment by HollyJoyPhillips** [comment]
Hi @nurm717123, Advertising information, whilst it may appear in the activity feed (if set) is not a Journal Entry. However, you may find you can obtain advertising information from the GET invoices/charges endpoint. 

See example on sandbox for property MKT220297

![image](https://github.com/reapit/foundations/assets/52408607/11fe8955-0dcc-47d2-bb5d-d2375557183b)

![image](https://github.com/reapit/foundations/assets/52408607/39cc8bb3-088a-485a-982b-132ec8744451)

**Comment by nurm717123** [comment]
Hi @HollyJoyPhillips , thanks for the reply. I've tried the endpoint but there are some record that doesn't returned, is that because bad data or something else?

propertyId: NGL150191 (only the first 2 record returned from swagger)

![image](https://github.com/reapit/foundations/assets/106480336/52d0534b-b159-4b44-936e-f63ef085204d)

**Comment by HollyJoyPhillips** [comment]
Hi @nurm717123, I would initially say it's probably bad data but we'd need to verify. I'll move this ticket into refinement as it will need to be picked up and the backend data reviewed by one of our devs.

**Comment by nurm717123** [comment]
thanks for that @RWilcox-Reapit 👍
