### ISSUE TITLE
New RPS Developer edition won't install

### ISSUE THREAD

**Issue by roscoe2001** [reapit/foundations#11122]
I've uninstalled RPS Developer edition (as per the email on 1/5/2024) and gone to install the new version but get an error (see attached).
-------------------------------------------------------------------------------------------------------------------------------------------
ERROR DETAILS
	Following errors were detected during this operation.
	* [07/05/2024 09:08:57] System.Deployment.Application.InvalidDeploymentException (Zone)
		- Deployment and application do not have matching security zones.

**Comment by roscoe2001** [comment]
[97RYY9CT.log](https://github.com/reapit/foundations/files/15232565/97RYY9CT.log)

**Comment by AshDeeming** [comment]
Hi @roscoe2001 
Please could you look to delete the current & previous versions in the registry

Press Windows Key + R: This key combination opens the Run dialog box.
Type “regedit”: In the Run dialog box, type “regedit” (without quotes) into the text field.
Press Enter or click OK: Hit Enter on your keyboard or click OK to launch the Registry Editor.
Find CurrentVersion & PreviousVersion - right click both & delete.

Then relaunch RPS Developer Edition & you should see the Reapit Connect screen.

**Comment by roscoe2001** [comment]
Hi Ash,

Are the instructions missing a line ? i.e. 
Before this line 'Find CurrentVersion & PreviousVersion - right click both & delete.'
should there be something saying "look for rps dev edition" or whatever (otherwise there's loads of Current/Previous versions of various things)

**Comment by AshDeeming** [comment]
Hi @roscoe2001 
Apologies, you will need to uninstall any instances first.

Then complete the above to clear any RPS versions being set/defaulted
 >HKEY_CURRENT_USER 
> SOFTWARE
>Reapit
 

Then open the link again - running via Edge (we've found with Chrome users, it downloads & encounters issues)

**Comment by roscoe2001** [comment]
Thanks, it all works now (the key thing was to use Edge not Chrome (once we did that it worked ok).
