### ISSUE TITLE
500 Error on transactions API

### ISSUE THREAD

**Issue by chestertons** [reapit/foundations#11120]
Using CHT , consistent errors retrieving data from this API since around 23:00 last night

https://platform.reapit.cloud/transactions/?PageNumber=1&PageSize=100&sortBy=modified&modifiedFrom=2024-05-02T12:31:36Z&modifiedTo=2024-05-03T08:06:13Z
status was 500
data returned follows

{
    "statusCode": 500,
    "dateTime": "2024-05-03T07:06:16.9539797Z",
    "description": "An unexpected error has been encountered when fulfilling this request. This incident has been logged and will be investigated. Please try again."
}
curl 500 at https://platform.reapit.cloud/transactions/?PageNumber=1&PageSize=100&sortBy=modified&modifiedFrom=2024-05-02T12%3A31%3A36Z&modifiedTo=2024-05-03T08%3A06%3A13Z !

**Comment by plittlewood-rpt** [comment]
Hi @chestertons I've tracked down the problem record. A supplier invoice was posted yesterday without a date on the transaction. I've asked our client accounts team to try and unpick how the system permitted that action and am just waiting back to hear from them about what to do about the problem record

**Comment by plittlewood-rpt** [comment]
HI @chestertons it looks like someone has (in branch) updated the problem record so these calls should no longer fail if you can plese confirm?

**Comment by plittlewood-rpt** [comment]
Hi @chestertons I can see from our logs that calls to this endpoint started to return successfully following the update last week, and have consistently been OK since. I'll therefore close this item down. Thanks
