### ISSUE TITLE
BLM feed issue

### ISSUE THREAD

**Issue by desine-net** [reapit/foundations#11124]
Good morning, our client currently receives their website property listings from a BLM feed via FTP, but this suddenly stopped working on 25th Apr. They're in the process of switching over to the API, however the new API-driven website won't be ready to go live for a couple of weeks. 

Kenny in your team has requested that I raise a ticket with you, but has also mentioned that all support for BLM feeds has now ended (the ticket ref is RSD-285353). We'd be extremely grateful if you look into, or clarify, why the BLM feed has stopped working, as the information on their website is becoming increasingly more out of date with each day that passes. Please let me know if you need more information about the specific case, and thank you in advance for your assistance with this.

**Comment by plittlewood-rpt** [comment]
Hi @desine-net sorry that you've been passed around the houses a bit here. I've picked this up with our support team as I can see the errors you are mentioning on our feed monitor. Someone should get in touch soon as I've asked for it to be prioritised

**Comment by plittlewood-rpt** [comment]
Hi @desine-net I can see that the latest upload to you was successful so I'll close this down. Please liaise with our main service desk if there's anything outstanding. Many thanks
