### ISSUE TITLE
The Reapit properties data returning from API is with strange property ID of other Office

### ISSUE THREAD

**Issue by hoangnguyentci** [reapit/foundations#11133]
**Describe the bug**
Upon reviewing the response data, we've noticed several discrepancies that require urgent attention:

Properties listed by other estate agents have been included in the response. For example, COL240099 and TOT240025 were erroneously sent under TOL and TOT office, respectively, but are actually listed by Fenn Wright and Barstow Eves. Our client has confirmed that these properties do not belong to them.

The consistency of API response data is compromised. In the latest call, COL240099 no longer appears, while TOT240025 persists along with a new property listed by another agent (ID: LEY200028).
There have been instances where properties are missing from the data pull.
 
While we've only seen this issue with one client so far, we're concerned that it may happen to others. Therefore, I kindly request that this matter be treated as a high priority and please inform us of the estimated timeline for the resolution.

**To Reproduce**
The Reapit properties data returning from API is with strange ID
Office id TOL Tottenham Lettings in region Ellis & Co has all properties with ID "TOT-----"
Few days ago we have property result IDs COL240099, COL240163, COL240207, COL240308. Today those IDs are disappeared, and another strange property ID LEY200028 is in the property result of Office TOL

- API endpoint: https://platform.reapit.cloud/properties/

- User logs in under Client code: MAC-GTTT

- run API endpoint https://platform.reapit.cloud/properties/?officeId=TOT

or API endpoint https://platform.reapit.cloud/properties/LEY200028

- Result return has:

```
{
    "id": "LEY200028",
    "created": "2020-06-13T15:46:24Z",
    "modified": "2020-11-14T12:20:11Z",
    "marketingMode": "selling",
    "currency": "GBP",
    "officeIds": [
        "TOT"
    ],
...
}
```

**Expected behaviour**
Properties API endpoint for Office TOL should return all property IDs "TOT-----", not "COL-----" or "LEY-----" 

**Screenshots**
<img width="757" alt="Screenshot 2024-05-10 at 15 50 04" src="https://github.com/reapit/foundations/assets/102959174/1e86cdef-a29e-41c9-a493-d20966392e89">
<img width="923" alt="Screenshot 2024-05-10 at 15 49 49" src="https://github.com/reapit/foundations/assets/102959174/88df994f-f350-4d46-a1a6-d672faaf1e69">

**Device (please complete the following information for web issues):**
 - Device: API Call on any device
 - Browser [e.g. Chrome, Safari]

**Additional context**

**Comment by plittlewood-rpt** [comment]
Hi @hoangnguyentci 

I think you may have assumed incorrectly that the property id prefix corresponds to the owning office however this is not the case. Office ownership is dictated by the officeIds collection, and this is what the officeId filter acts on. Properties can move between offices once created so the behaviour you are seeing is correct. It's normal to see properties with a different id prefix to the officeId

Thanks
Pete

**Comment by plittlewood-rpt** [comment]
Closing as per separate email thread.
