### ISSUE TITLE
DELETE applicants/{id}/relationships/{id} endpoint not working

### ISSUE THREAD

**Issue by AdamHall12** [reapit/foundations#11130]
**Describe the bug**
The DELETE applicants/{id}/relationships/{id} endpoint not working for certain applicants

**To Reproduce**
Steps to reproduce the behaviour eg:
1. This is one example of where the endpoint is not working https://platform.reapit.cloud/applicants/SHA242545/relationships/SHA24004362

**Expected behaviour**
The applicant relationship should be removed but is not

**Comment by AshDeeming** [comment]
Hi @AdamHall12 
Please could you confirm the app & the customer names?

**Comment by AdamHall12** [comment]
Rettie Connect is the app and RET is the customer name. However it is not working on the Foundations API tool either

**Comment by AdamHall12** [comment]
Hi @AshDeeming, is this being looked into? Thanks
