### ISSUE TITLE
Access to the Analytics schema

### ISSUE THREAD

**Issue by LukeWallis87** [reapit/foundations#11132]
Good Morning,

Please can I request access to this schema. 

**Background context**

**Specification**

**Comment by AshDeeming** [comment]
Hi @LukeWallis87 
Please could you confirm which customer you are working with/on behalf of?

**Comment by LukeWallis87** [comment]
Hi @AshDeeming 
Marsh and Parsons

**Comment by HollyJoyPhillips** [comment]
Hi @LukeWallis87 Marsh and Parsons have already been provisioned access to the Analytics Schema, they may just need to create a share in the Data Warehouse app.  https://datawarehouse-foundations.reapit.cloud/creating-a-data-share. The app can only be accessed by an Organisation Admin which is currently Giles.

**Comment by LukeWallis87** [comment]
Thanks I have checked and we are getting the following error message.

![image](https://github.com/reapit/foundations/assets/99893513/527dd6ff-9fae-40d7-8484-a1331f33a580)

**Comment by plittlewood-rpt** [comment]
Hi @LukeWallis87 there was an old pending request which I've just cleaned up. Are you able to give it another try please?

**Comment by LukeWallis87** [comment]
sorted thank you.
