### ISSUE TITLE
 TDS FSS Property issue

### ISSUE THREAD

**Issue by ChrisSandersTDS** [reapit/foundations#11140]
Message from The Tenancy Deposit Scheme 

The latest release added some security policies to the infrastructure. I can see that there have been requests to this url that have hit a policy called “NoUserAgent_HEADER”.  This rule blocks requests to the sever that have no user agent set, a basic indication of a bot or attack vector

Can you confirm if it is possible to add a user agent to their web requests

Register deposits via Reapit for FSS

**Comment by AshDeeming** [comment]
Hi @ChrisSandersTDS 
Please could you confirm what app this relates to along with what request is being made?

**Comment by ChrisSandersTDS** [comment]
Hi Ash 

Thanks for your response.

This is for the Reapit integration with the tenancy deposit scheme website. This relates how Reapit creates SFTP files and sends them across to the TDS SFTP server. Our developer has put in place a security feature that is preventing the upload of SFTP files to our server. They have explained: 

The latest release added some security policies to the infrastructure. I can see that there have been requests to this url that have hit a policy called “NoUserAgent_HEADER”. This rule blocks requests to the sever that have no user agent set, a basic indication of a bot or attack vector

Can you confirm if it is possible to add a user agent to their web requests

I was advised by the Reapit Service desk to raise this issue here. Can you confirm if this is enough information. The agent will not be able to register deposit protections until this has been resolved. 

Thanks
Chris Sanders

**Comment by AshDeeming** [comment]
Dealt with via https://reapit.atlassian.net/browse/rsd-286613

**Comment by ChrisSandersTDS** [comment]
Oh yes sorry - please complete/close the issue
