### ISSUE TITLE
Reapit/InventoryBase Integration 

### ISSUE THREAD

**Issue by RebeccaPalmerCurchods** [reapit/foundations#11147]
Our Property Management department have been liaising with InventoryBase for some time about the app keeping disconnecting and they have to keep re-syncing it. InventoryBase have advised it is an issue at the Reapit end and not theirs. Are you able to have a look at what the issue is please?

**Comment by RebeccaPalmerCurchods** [comment]
Hi @AshDeeming,

I raised it with them and they said I needed to come to you. I spoke to InventoryBase and they said it was an issue at Reapits end...

**Comment by SteveRad** [comment]
Hey Rebecca, It sounds like the legacy app that requires refreshing the connection every 30 days and we have a new app available that remains connected permanently. I've emailed you directly to get this resolved.
