### ISSUE TITLE
Extra Field Required in Property endpoint - TLC London

### ISSUE THREAD

**Issue by vb3117** [reapit/foundations#11145]
Client: TLC London(TLC)
Endpoint: /properties/

Fields Required:
All Open House Date and Time

Screenshot:
![image002 (2)](https://github.com/reapit/foundations/assets/114083729/ef3ddb27-ad07-4157-b96f-656c49ad011b)

The client wants this information to be displayed on the website. So can you please enable these fields in extrasField in the property endpoint and share the field names.

**Comment by AshDeeming** [comment]
Hi @vb3117 
Please see the appointments endpoint - you may also need to use the configuration endpoint to get the appointmentType

**Comment by vb3117** [comment]
Okay got it, thanks @AshDeeming
