### ISSUE TITLE
When embedding extensions in GET `/tenancies`, can `rent` ever be `null`?

### ISSUE THREAD

**Issue by ethangates** [reapit/foundations#11146]
**Summary**
Hello! I'm currently working on embedding extensions on our call to GET `/tenancies` and I've noticed that when I add a non-renewal type extension (i.e. an alteration/fee/etc), the `rent` always has a value populated anyway. Is this expected behaviour? Are there any scenarios where there may be an extension on a tenancy, but the rent on that extension is null?

**Detail and or supporting links and screenshots**
e.g. 

```json
{
  "_embedded": [
    {
      "id": "ABC1234",
      "created": "2024-02-29T13:36:56Z",
      "modified": "2024-05-15T08:00:55Z",
      "startDate": "2024-07-12",
      "endDate": "2031-07-13",
      "status": "current",
      "agentRole": "managed",
      "rent": 1516.67,
      "rentFrequency": "monthly",
      "endDateConfirmed": false,
      "isPeriodic": true,
      "rentInstalmentsFrequency": "every28Days",
      "rentInstalmentsAmount": 1400,
      "rentInstalmentsStart": null,
      "meterReadingGas": null,
      "meterReadingGasLastRead": null,
      "meterReadingElectricity": null,
      "meterReadingElectricityLastRead": null,
      "meterReadingWater": null,
      "meterReadingWaterLastRead": null,
      "typeId": "AS",
      "negotiatorId": "ABC",
      "propertyId": "ABC32121",
      "applicantId": "",
      "managerId": null,
      "groupPaymentReference": null,
      "lettingFee": {
        "type": "percentage",
        "amount": 0,
        "frequency": "28days"
      },
      "related": [//blah blah],
      "fromArchive": false,
      "feeNotes": null,
      "legalStatusId": null,
      "renewalOptions": null,
      "arrears": {
        "chaseArrears": true,
        "paymentPlan": "no"
      },
      "_eTag": "\"9E39DED15C930C46A4DD60385C05FACD\"",
      "_links": {// etc},
      "_embedded": {
        "extensions": [
          {
            "id": "ABC999999",
            "created": "2024-05-15T15:16:25Z",
            "modified": "2024-05-15T15:16:25Z",
            "startDate": "2033-04-08",
            "endDate": null,
            "type": "alteration",
            "negotiatorId": "ABC",
            "rent": 1516.67,
            "rentFrequency": "monthly",
            "tenancyId": "MKT240151",
            "fee": {
              "amount": 100,
              "summary": "2323",
              "type": "landlordToTenantFee"
            },
            "_eTag": null,
            "_links": {
              "self": {
                "href": "/tenancies/ABC1234/extensions/ABC999999"
              },
              "tenancy": {
                "href": "/tenancies/ABC1234"
              },
              "negotiator": {
                "href": "/negotiators/ABC"
              }
            },
            "_embedded": null
          }
        ],
        "applicant": null
      },
      "metadata": {}
    }
  ],
  "pageNumber": 1,
  "pageSize": 25,
  "pageCount": 1,
  "totalPageCount": 1,
  "totalCount": 1,
  "_links": {// etc}
}
```

In the above example, the initial rent is `1516.67`. There's an extension added with an alteration to add a `landlordToTenantFee` of `100`. The `rent` is returned in that extension as the same figure for the initial rent: `1516.67`. Does this always happen? And if yes, how is this field populated? If there were a renewal extension added to the tenancy prior to another type of extension, will the `rent` be from the extension prior rather than from the initial rent?

Thanks very much in advance!

**Comment by AshDeeming** [comment]
Hi @ethangates 
The rent amount will be associated to the Property/tenancy therefore if populated in the CRM it will return in the payload. 
Does that answer your question?

**Comment by ethangates** [comment]
Thanks @AshDeeming - so just to be clear, if the initial rent is set, OR if there's an extension with an overriding rent amount set, then `rent` will never be null in an extension added afterwards? Rent would only be `null` in an extension in this scenario?

A tenancy exists which does not have an initial rent amount set
An extension which does not modify the rent total is added

**Comment by ethangates** [comment]
Hey @RWilcox-Reapit - thank you so much!!
