### ISSUE TITLE
Power BI connection blocked by IP restriction 

### ISSUE THREAD

**Issue by LukeWallis87** [reapit/foundations#11152]
We are trying to access the Snowflake from Power BI but the IP whitelisting restricts us. Is there option to allow Power BI IPs ?

**Comment by AshDeeming** [comment]
Hi @LukeWallis87 
Please could you confirm which customer this relates to? 
any Data warehouse requests can go to: dwh@reapitfoundations.zendesk.com

**Comment by LukeWallis87** [comment]
Thanks Ash, I will log a ticket there.
