### ISSUE TITLE
Error Querying Tenancies Allowance

### ISSUE THREAD

**Issue by abrahamseni** [reapit/foundations#11164]
env: SAV
querying GET `tenancies/{id}/allowances` result in `500` error.
But we can see the data in AC.
id: RDL230130

screenshot:
![Screenshot 2024-05-23 051223](https://github.com/reapit/foundations/assets/94949137/22eda676-4fce-4c77-8446-22883576a0fb)

**Comment by AshDeeming** [comment]
Hi @abrahamseni 
Could i just confirm that this issue continues after logging out & back into the portal?

**Comment by abrahamseni** [comment]
Hi @AshDeeming 
Yes, it is. This was first reported by Savills, and I can confirm it.
Try it a couple of times, it keeps returning 500 error.

**Comment by abrahamseni** [comment]
This also happens to this tenancy Id: HKR230350 (env. SAV)
