### ISSUE TITLE
Request for Access to staging Client Reapit Portal for Integration Testing

### ISSUE THREAD

**Issue by amandaclark9** [reapit/foundations#11162]
Dear Reapit Customer Support,

I hope this email finds you well.

My name is Amanda Clark, and I am reaching out on behalf of Homebox. We have potential mutual clients who are interested in utilising our product in conjunction with Reapit. To ensure a seamless integration and provide the best possible service to our shared clients, we are requesting access to the staging Client Reapit portal.

Access to the portal will allow us to thoroughly test our integration and validate the data, ensuring that everything functions correctly before we go live. This proactive step is crucial for minimising any potential issues and providing a smooth user experience for our clients.

Could you please provide us with the necessary access to the staging Client Reapit portal for testing purposes? If there are any specific requirements or steps we need to follow to obtain this access, kindly let us know, and we will comply promptly.

Thank you for your attention to this matter. We look forward to your positive response and are excited about the opportunity to work together to serve our mutual clients effectively.

Best regards,

Amanda Clark

**Comment by AshDeeming** [comment]
Hi @amandaclark9 
Please refer to Mike, who will be able to invite you to the relevant developer account via https://developers.reapit.cloud/settings/members

**Comment by amandaclark9** [comment]
Good morning @AshDeeming , I have an account to access the reapit developer already but I was wondering if there's a way that I can use the client portal to create an example property test in order to be able to validate the data when sync the data to our system before we go fully live with the integration.

Thank you

**Comment by AshDeeming** [comment]
Hi @amandaclark9 
Thanks for confirming you have access to the developer portal 
In order to access the CRM you can download the desktop app (on a windows machine) via ; https://developers.reapit.cloud/desktop
Any issues, please let us know

**Comment by amandaclark9** [comment]
Thank you @AshDeeming  . Another questions, is there any endpoints that we can use if we want to exclude certain properties from sync/integrate to our system?

**Comment by AshDeeming** [comment]
Hi @amandaclark9 
No problem - yes, you can use the available parameters to filter which fields within the endpoint
see: https://developers.reapit.cloud/swagger
