### ISSUE TITLE
Expose the thumbnail urls within property images

### ISSUE THREAD

**Issue by RWilcox-Reapit** [reapit/foundations#11172]
**Background context**
Currently for each image created a second thumbnail image is created. This path for the asset is very similar with the distinction of one folder. As part of the work Adrian is doing he's requested we expose this path.

**Specification**
- Project: Reapit.Services.PropertyImages
- When an image is added to either AgencyCloud or via the PropertyImages API, a thumbnail is generated and stored along with the main asset. This is useful for search result style pages and reduces the bandwidth needed to serve this content. Thumbnails are stored in exactly the same structure as the /pictures folder, just in the /thumbs folder instead. The URLs are also identical with the only difference being /thumbs/ instead of /pictures/ in the path ie:

https://assets.reapit.net/sbox/live/thumbs/MKT/22/MKT220014_11.png
https://assets.reapit.net/sbox/live/pictures/MKT/22/MKT220014_11.png

- Add `thumbnailUrl` to the GET endpoints. (This is already generated by  our GetFolderPath extension)

**Comment by madebyparent** [comment]
How do we use this now?
