### ISSUE TITLE
Action Required: Reapit Connect Tokens

### ISSUE THREAD

**Issue by andortamas** [reapit/foundations#11174]
Hi,

As your last email said, I have tried upgrading the reapit connect session from 2.0.9 to 2.3.2 to use new endpoints. However it raises a Bad Request error. I have debugged the network communication and found the following:

**The current process which works with 2.0.9:**

- Requests a token from here: https://connect.reapit.cloud/token?grant_type=authorization_code&client_id=foo&code=bar&redirect_uri=baz
- Then it calls the https://cognito-idp.eu-west-2.amazonaws.com/eu-west-2_foo/.well-known/jwks.json and gets a valid response including keys object.

**The process which causes infinite loop with 2.3.2:**

- Requests a token from here: https://connect.reapit.cloud/token?grant_type=authorization_code&client_id=foo&code=bar&redirect_uri=baz
- Then it calls the https://cognito-idp.eu-west-2.amazonaws.com/eu-west-2_foo which comes back a _400 Bad Request error_ then it requests a new token, then calls this cognito link again and again with 400 Bad Request response.

**Some other info which may help:**

- Our app is based on your old RactJS sample
- I've cleared the npm cache and reinstalled all of the packages correctly

Have you got any idea what happens here?

Many thanks,
Andor

**Comment by andortamas** [comment]
Hi @joshbalfour,

Many thanks for your advice. It works perfectly, however I see that the token is still requesting from the cognito-idp.eu-west-2.amazonaws.com

Is this ok?

Regards,
Andor

**Comment by plittlewood-rpt** [comment]
Hi @andortamas  yes this is correct for the time being. This update is in preparation for us to start to rollout changes which will alter the issuer to connect.reapit.cloud. Thanks

**Comment by andortamas** [comment]
I make sense. Thank you very much for your help.
