### ISSUE TITLE
Sales Progression API

### ISSUE THREAD

**Issue by rshiels** [reapit/foundations#1117]
We’d like to request that this is brought forward in the roadmap as per Gary Barker's discussion with the TwentyCI CEO Ian Lancaster

**Comment by plittlewood-rpt** [comment]
Hi @rshiels thanks for reaching out. We are in the the early stages of laying out the foundations for this API and while I can't give you any timescales at the moment, we should have a milestone you can track within the next couple of weeks.

**Comment by cbryanreapit** [comment]
This was delivered end of May, closing this ticket.
