### ISSUE TITLE
Appointment attendee should have name split into title, forename and surname

### ISSUE THREAD

**Issue by au63** [reapit/foundations#11176]
This is how the response for appointment attendee looks like in reapit
![image](https://github.com/reapit/foundations/assets/139497587/b9593ef2-0a60-46cf-8da1-3cbd2c294fea)
But the contact record looks like this
![image](https://github.com/reapit/foundations/assets/139497587/5e919acd-d1e3-4248-b58f-3efe14ced6a3)

We have a requirement to get the first name for an appointment attendee and this requires a trip to contact record to get the first name because appointment only gives us the entire name without knowing what is the title or firstname

Will it be possible for you to expose the title, forename and surname in appointment attendee?

## Specification
- Project: Reapit.Services.Appointments
- Retain existing `name` and add support for `title`, `forename` and `surname` on GET endpoints
- Check all attendee types have name segments stored separately

**Comment by plittlewood-rpt** [comment]
@RWilcox-Reapit just reviewing this, it's likely it was implement this way because a company attendee doesn't fit into the structure being requested here. No real issue with this though, we'll just need to make it clear in the documentation
