### ISSUE TITLE
Image sizes

### ISSUE THREAD

**Issue by madebyparent** [reapit/foundations#11183]
Does Reapit create and retain various image sizes? 

We're using direct linked images on https://www.beresfords.co.uk/find-a-property/for-sale/?location= but finding it particularly slow to load. Are there smaller / thumbnail versions of every images we could access?

**Comment by AshDeeming** [comment]
Hi @madebyparent 
The below ticket may be of use - please feel free to subscribe to it for updates:
https://github.com/reapit/foundations/issues/11172

**Comment by plittlewood-rpt** [comment]
Hi @madebyparent the thumbnail URL is now available in the payload from GET /propertyImages as per the linked ticket above. This has been implemented specifically for use cases such as yours where you are displaying search results which only require a smaller version. Please note that the thumbnail size is dictated by AgencyCloud configuration and any changes would need to be made by the customer to our servicedesk. Many thanks

**Comment by madebyparent** [comment]
How do i see the solution though?ThanksChris HarmanParent®On 13 Jun 2024, at 07:55, github-actions[bot] ***@***.***> wrote:﻿
It looks like you have commented on a closed issue. If your comment relates to a bug or feature request, please open a new issue, and include this issue number/url for reference.
For more information on our processes,  please click here
