### ISSUE TITLE
Right Now Residential unable to install Fixflo Advanced

### ISSUE THREAD

**Issue by MarceFF22** [reapit/foundations#11182]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour eg:
1. Go to Reapit Marketplace
2. Click on Fixflo Advanced with Funds 
3. There's no option to install the app.

**Expected behaviour**
There should be an option to download the app, so Fixflo can setup the advanced integration with funds but the client is unable to do so. 

**Screenshots**
If applicable, add screenshots to help explain your problem. Please ensure that screenshots do not include sensitive data such as personally identifiable information. If you do have private or sensitive information you need to share that will help with aiding resolution of this issue, please email sinfo@reapitfoundations.zendesk.com adding the issue number as the subject line. Please only use this mailbox to share information you cannot add to this issue.

**Comment by AshDeeming** [comment]
Hi @MarceFF22 
Only users with the correct access can install apps/integrations for a Customers organisation - For this customer, there are 3 users with the access.

**Comment by MarceFF22** [comment]
Thank you, what are the three users please? The person who was trying to install it is Zac Gill.

**Comment by AshDeeming** [comment]
Hi @MarceFF22 
The client should be able to confirm this - alternatively, please confirm your email using this ticket ref as the subject via : [sinfo@reapitfoundations.zendesk.com]

**Comment by MarceFF22** [comment]
But they are not able to confirm, I'm afraid. Zac went to Reapit support to ask for help and they told them that Fixflo has to open a ticket here, which I have done. Now you are telling me you can't help me either, so it's a bit frustrating... 

How can this be resolved?

**Comment by AshDeeming** [comment]
Zendesk ticket: 1153
