### ISSUE TITLE
Fields on Custom Marketing Screen

### ISSUE THREAD

**Issue by byt3sage** [reapit/foundations#11185]
**Request**

In order for us to grant access to Semi-structured 'extras' field data, please provide the following information in this request:

- The name of the customer you represent
MNS
- The name of every field you need surfaced (if known)
- A screenshot of of the field(s) you require in the agency cloud user interface
![image](https://github.com/reapit/foundations/assets/61322528/55d60a59-4d2a-4e5d-b216-335552c8d7ff)

- A short use case as to why you require this data

Internal Reporting

**Comment by AshDeeming** [comment]
Hi @byt3sage 

Access for the fields mentioned above has been set up and should become active within the next 15 minutes.
ClientId: MNS

Fields = pPartex & pSalesAssist 

As per any other semi structured data you access it using the extrasField query string parameter eg;
GET /properties?extrasField=pPartex
