### ISSUE TITLE
App Revision - Consents For Clients Who No Longer Use The App

### ISSUE THREAD

**Issue by mab-rdremza** [reapit/foundations#11181]
Hi,

I am a software engineer at Mortgage Advice Bureau (MAB) working on MAB's Reapit marketplace app. We submitted a request to update permissions for our app a couple of months ago, and since then I believe a couple of our clients have uninstalled the app. However, they are still appearing as pending app consent in Reapit's developer portal.

Please could you let us know if this is the case and if the pending app consents can be removed? I am concerned it will block the app revision being approved.

App name: MAB Send to Midas
App ID: 9d09b279-557f-4f60-af5b-9d654050a9ec

Also, is GitHub issues the best place to raise non-technical issues and problems? I emailed sales@reapit.com a week or so ago but have not received a reply.

Thanks.

**Comment by AshDeeming** [comment]
Thanks @mab-rdremza 

I can see the consents agreed now for all installed clients & both app revisions approved
