### ISSUE TITLE
Document 6mb file size limit, possibly not accurate?

### ISSUE THREAD

**Issue by nbdesignstudio** [reapit/foundations#11187]
We are experiencing a few 413 errors when trying to upload Identity Check documents to a Contacts Identity Check endpoint.

We have logging in place to identify IF the encoded file is 'near' to the standard 6mb limit and if it is, we then use your pre-signed URL end point which then works.

However we have noticed that we are receiving the 413 error response when the encoded files are say less than 6mb, say 5.7mb for example. Can you please clarify if the limit is indeed set to 6mb, or are there other issues at play?

Some logging from our side is below to show what we record and the file sizes that the documents are, and then the response we receive from you after attempting the upload:

[2024-05-21 12:16:29] prod.INFO: Set status and identity document for contact HYW20000365; Status: pass  
[2024-05-21 12:16:29] prod.INFO: Compliance pack file size: 4.29 MB  
[2024-05-21 12:16:29] prod.INFO: Compliance pack encoded file size: 5.72 MB  
[2024-05-21 12:16:29] prod.INFO: Post to identityChecks: response status: 413;  

[2024-05-22 14:03:15] prod.INFO: Set status and identity document for contact EAO24000334; Status: pass  
[2024-05-22 14:03:15] prod.INFO: Compliance pack file size: 4.28 MB  
[2024-05-22 14:03:15] prod.INFO: Compliance pack encoded file size: 5.71 MB  
[2024-05-22 14:03:15] prod.INFO: Post to identityChecks: response status: 413;  

[2024-05-22 18:49:47] prod.INFO: Set status and identity document for contact ISA24000388; Status: pass  
[2024-05-22 18:49:47] prod.INFO: Compliance pack file size: 4.24 MB  
[2024-05-22 18:49:47] prod.INFO: Compliance pack encoded file size: 5.65 MB  
[2024-05-22 18:49:47] prod.INFO: Post to identityChecks: response status: 413;

**Comment by plittlewood-rpt** [comment]
Hi @nbdesignstudio the 6Mb limit is the encoded file content PLUS the rest of the request (headers, body etc - once you've taken things like the Bearer token into account it's likely you're just tipping over the edge of that limit). We use AWS Lambda in the backend for our main API endpoints which is where the limitation comes from. Using pre signed URLs negates this problem because the size of your request overall is much smaller and we move the physical asset in the backend to where it needs to be.

I'll look at making some documentation updates to make this clearer.

**Comment by nbdesignstudio** [comment]
> the 6Mb limit is the encoded file content PLUS the rest of the request (headers, body etc - once you've taken things like the Bearer token into account it's likely you're just tipping over the edge of that limit)

Thanks for this Pete. We obviously didn't know this extra data was taken in to account. We have therefore reduced our own thresholds accordingly and this appears to have helped resolve some of the upload issues that were being experienced before.

**Comment by plittlewood-rpt** [comment]
Thanks for confirming. I’ve updated the documentation and swagger commentary accordingly. Sorry this wasn’t clear first time round.
________________________________
From: nbdesignstudio ***@***.***>
Sent: Wednesday, June 12, 2024 7:25:28 PM
To: reapit/foundations ***@***.***>
Cc: Pete Littlewood ***@***.***>; State change ***@***.***>
Subject: [EXTERNAL] Re: [reapit/foundations] Document 6mb file size limit, possibly not accurate? (Issue #11187)


External Message - Please be cautious when opening links or attachments in email
________________________________
the 6Mb limit is the encoded file content PLUS the rest of the request (headers, body etc - once you've taken things like the Bearer token into account it's likely you're just tipping over the edge of that limit)

Thanks for this Pete. We obviously didn't know this extra data was taken in to account. We have therefore reduced our own thresholds accordingly and this appears to have helped resolve some of the upload issues that were being experienced before.
