### ISSUE TITLE
Paton & Co

### ISSUE THREAD

**Issue by MarcinuB** [reapit/foundations#11191]
Hi Team.

Could I get access to the below fields for Paton & Co:

![image](https://github.com/reapit/foundations/assets/8589350/406953ee-9759-4d1d-8cc0-267108c85f40)

This is required for their integration with FluxPro.

Thank you

**Comment by AshDeeming** [comment]
Hi @MarcinuB 

Access for the fields mentioned above has been set up and should become active within the next 15 minutes.
ClientId: PTN

Long description; pLongDesc
Situation: pSituation
Directions: pDirections
Advert Text: pAdvert
What3Words: pWhat3words
Online Brochure: pOnlineBrochure

As per any other semi structured data you access it using the extrasField query string parameter eg;
GET /properties?extrasField= pLongDesc
