### ISSUE TITLE
500 Internal Server Error when pulling data for Aspire Estate Agents. 

### ISSUE THREAD

**Issue by ynwaJon** [reapit/foundations#11192]
Our client has been in contact to say that their lettings properties are not displaying on the site. 

We've carried out some digging and it looks like there are some issues when trying to pull data via our Foundations App (Property Feeder). 

Message from our Tech who did the digging. 

"I made some experimental calls using the details there, ie Customer ID "AEA" & Office ID "BSE".

With "Reapit-Customer: AEA" & a suitable "Authorization: Bearer ..." in the headers, the call
https://platform.reapit.cloud/properties?officeId=BSE&internetAdvertising=true&isExternal=false&pageSize=100
works fine, but the call
https://platform.reapit.cloud/properties?officeId=BSE&internetAdvertising=true&isExternal=false&pageSize=100&pageNumber=2
comes back with a 500 Internal Server Error, with this in the response body:
{
  "statusCode": 500,
  "dateTime": "2024-06-03T13:12:50.6063215Z",
  "description": "An unexpected error has been encountered when fulfilling this request. This incident has been logged and will be investigated. Please try again."
}

If I remove the pageSize parameter, it works for pageNumber values of 1-5 and 8, but fails as above for pages 6 & 7.

Please can this be looked into.

**Comment by plittlewood-rpt** [comment]
Hi @ynwaJon this should now be resolved. There was some odd data in their system upsetting some of the mapping logic in the API which I've now cleaned up. I've logged a separate issue (linked above) for improving the APIs handling of the bad data.

**Comment by ynwaJon** [comment]
Champion. 

Thanks for sorting that so quickly.

**Comment by ynwaJon** [comment]
@plittlewood-rpt - Just thinking... is it worth me going back to client and letting them know what the errors were?  If you can let me know that would be great.

**Comment by plittlewood-rpt** [comment]
Hi @ynwaJon it isn't something the customer would have been able to resolve unfortunately. I think it's possibly left over from when they originally joined us but I could be wrong. The attached ticket will look into it a bit deeper :)
