### ISSUE TITLE
Writeback payloads and the activity feed

### ISSUE THREAD

**Issue by BYMIntegrations** [reapit/foundations#11197]
**Summary**
Hi all,

When we configure our payloads to writeback data into reapit, is there configuration on our end that allows us to determine if this written back data appears within a contacts activity feed? Our customer would like us to write back certain types of interactions and data, but for that written back data to not "spam" their activity feed for a customer

**Detail and or supporting links and screenshots**
![image](https://github.com/reapit/foundations/assets/102583061/5fc64638-f746-405a-ba92-1be557908d67)

**Comment by AshDeeming** [comment]
Hi @BYMIntegrations 
Yes, this would depend on the JounralEntry 'associatedType' being posted
![image](https://github.com/reapit/foundations/assets/61687775/9cf9ecbb-218e-4a71-b22d-6a23fee25fbd)

**Comment by BYMIntegrations** [comment]
Perfect thank you!
