### ISSUE TITLE
Property not pulling through for Domvs

### ISSUE THREAD

**Issue by ynwaJon** [reapit/foundations#11194]
Hi, 

Client has reported that a property is not showing on their website. 

Client name - Domvs. 
Property ID - WDO230065 

Please can you check to see why this might be.

**Comment by HollyJoyPhillips** [comment]
Hi @ynwaJon, please could you provide some additional information, for example, what is the request you are making in which the property doesn't appear in the results? Are you expecting the data via a webhook? 

What is the name of the app/integration and the customer organisation ID it's been installed for? 

Thanks.

**Comment by ynwaJon** [comment]
Hi, 

Domvs are using our Foundations App called Property Feeder. 

Their Customer ID is DOM

Webhooks are enabled as far as i'm aware.

**Comment by HollyJoyPhillips** [comment]
Hi @ynwaJon, were you expecting to see the property in a webhook or did you make a request and the property is not there? If it's the second point, please can you provide the query so we can investigate?

**Comment by ynwaJon** [comment]
Hi, 

Please can you confirm the Branch ID that is applied to this property.

**Comment by HollyJoyPhillips** [comment]
Hi @ynwaJon that property is associated to Beaminster (BEA). Thanks.

**Comment by HollyJoyPhillips** [comment]
Please can you confirm you have the information you need so we can close the ticket?
