### ISSUE TITLE
Quealy & Co - invoice sync issue 

### ISSUE THREAD

**Issue by MarceFF22** [reapit/foundations#11200]
**To Reproduce**
Steps to reproduce the behaviour eg:
1. An invoice is added to a job in Fixflo. The job is closed, which triggers a webhook that should sync the invoice to Reapit. 
2. Webhook fails with the following response:
![image](https://github.com/reapit/foundations/assets/119598247/8ca1d26f-1540-470a-8f3e-6103f4a42c27)
![image](https://github.com/reapit/foundations/assets/119598247/5aaec250-6343-429a-baf5-c78f1b8a2d2a)

**Expected behaviour**
The invoice should sync across to Reapit. 

**Screenshots**
![image](https://github.com/reapit/foundations/assets/119598247/c65ebbb3-8103-4607-8853-916d8bacb1eb)

**Comment by plittlewood-rpt** [comment]
HI @MarceFF22 as the error suggests the agent needs to assign a client account to the property's landlord. This is a requirement otherwise the system does not know how to allocate funds correctly

**Comment by MarceFF22** [comment]
Thank you, I understand this but they claim they've done it. It seems that there's some knowledge gap here and ideally, someone from your support team should show them how to do this correctly. How can we progress this please?

**Comment by plittlewood-rpt** [comment]
Thanks - let me look in their system and come back to you shortly

**Comment by MarceFF22** [comment]
Thank you SO much!

**Comment by plittlewood-rpt** [comment]
Ok I see the problem. The transactions API attempts to set a client account if one is not provided in the body to POST /supplierInvoices . To do this it first looks at the landlord associated with the property to see if there is one explicitly set, before falling back to checking the system for a single primary account. This customer has two primary accounts (one of which is closed) however the lookup isn't ignoring closed accounts so it thinks there's two. As a result it knows not to just pick one so fails with the error. As there's only one active primary account the agent can't actually explicitly set it. We need to fix this in the API which I'll get onto now

**Comment by MarceFF22** [comment]
Incredible, thank you for the prompt update, much appreciated.

**Comment by plittlewood-rpt** [comment]
Hi @MarceFF22 I've got a fix going through QA for this now. I'd prefer to hang on until Monday to deploy it if that's feasible. I can manually attach a client account to the landlord so you can submit this in the meantime if that would help. Can you let me know? Thanks

**Comment by MarceFF22** [comment]
No worries, let's wait till Monday and sort out then I think. :)

**Comment by plittlewood-rpt** [comment]
Hi @MarceFF22 sorry for the delay getting this out it slipped my mind. The update has now gone to production so you should be able to submit this invoice. Thanks
