### ISSUE TITLE
Selling status: Sold STC - Unavailable

### ISSUE THREAD

**Issue by BYMIntegrations** [reapit/foundations#11229]
Please take a look at our FAQ's before submitting an issue, as your question may already be covered in the documentation https://foundations-documentation.reapit.cloud/faqs

**Summary**
Hi reapit,

Is there any chance you could detail what the difference between the two status's "Sold STC - Available" and "Sold STC - Unavailable" is when we make a GET request through the API? 

We are unable to find a customer with an example but would like to ensure our testing is accurate for some related development work

Thanks!

**Detail and or supporting links and screenshots**
![image](https://github.com/reapit/foundations/assets/102583061/5f5a2f95-0c02-4ddb-b484-76ffa7774875)

**Comment by AshDeeming** [comment]
Hi @BYMIntegrations 

The difference in these status relate to where the property is marketable (available) or not (unavailable)

**Comment by BYMIntegrations** [comment]
Hi @AshDeeming 

Is that only relating to "marketingMode" or "internetAdvertising"? What do these status' show for Unavailable?

**Comment by AshDeeming** [comment]
Hi @BYMIntegrations 
The statues mentioned relate to the Property status directly, as per swagger docs;:

**Selling**: preAppraisal/valuation/paidValuation/forSale/forSaleUnavailable/underOffer/underOfferUnavailable/reserved/exchanged/completed/soldExternally/withdrawn

**Letting**: valuation/toLet/toLetUnavailable/underOffer/underOfferUnavailable/arrangingTenancyUnavailable/arrangingTenancy/tenancyCurrentUnavailable/tenancyCurrent/tenancyFinished/tenancyCancelled/sold/letByOtherAgent/letPrivately/provisional/withdrawn


**MarketingMode** relates to the property being for sales or lettings, or both (selling/letting/sellingAndLetting)) 

**internetAdvertsing** can be used by users to mark a property as marketable or not - i.e. boolean

**Comment by BYMIntegrations** [comment]
Hi @AshDeeming,

The problem we have is we don't have frontend access to our sandbox, so therefore we can't accurately recreate a Sold STC - Unavailable lead to see how its GET differs from Sold STC - Available. That is specifically what information we are looking for

**Comment by AshDeeming** [comment]
Hi @BYMIntegration
you can download the developer edition of the desktop crm via https://developers.reapit.cloud/desktop

The get properties payload shouldn't differ as this relates to the status field only

**Comment by BYMIntegrations** [comment]
Hi @AshDeeming ,

Fantastic thanks, I queried this internally and I don't think we were aware of the developer client. Appreciate the help!
