### ISSUE TITLE
Property_id duplications in Analytics Schema

### ISSUE THREAD

**Issue by ktanalyst** [reapit/foundations#11221]
**Describe the bug**
We currently have 8 duplicate IDs in the properties view. 

This is having a knock on effect in the PROPERTY_SALES_EXCHANGES view as the id for this table shares the property_id for each record. When any of these 8 properties exchange, they are duplicating IDs in the exchanges view too. 

My understanding based on the schema notes below is that the exchange id should be unique to the exchange action, not just a copy of the property id?

![image](https://github.com/reapit/foundations/assets/143076147/df349f65-4f47-4b89-b3e2-14503b0a9fe1)

**To Reproduce**
The 8 records can be retrieved using this query:

`SELECT id
,code
,created_date
,COUNT(*) AS id_count
FROM REAPIT.ANALYTICS_KLR.PROPERTIES 
GROUP BY id
,code
,created_date
HAVING id_count >1`

**Expected behaviour**
Each property id should be unique in the table - any duplication needs removing. Also, what has caused this for the above properties?

The ID in the exchanges view should also be unique to the action and not linked to the property id - this seems to be causing issues.

**Device (please complete the following information for web issues):**
PC

**Additional context**
This issue is causing some of our exchange fee records to double in value, which is incorrect. I've tried using a QUALIFY statement in our code to limit one record per ID, but this isn't filtering some of the dupes. I'll keep working on another way around it internally, but we would appreciate this being resolved relatively swiftly if possible.

**CustomerID: KLR**

**Comment by cduggan-reapit** [comment]
Hi @ktanalyst - the property duplication should now be resolved.  Please let us know if you have any questions!
