### ISSUE TITLE
DWH - Duplicate row in PROPERTIES view preventing data refresh

### ISSUE THREAD

**Issue by MatthewGoddard** [reapit/foundations#11232]
I am getting an issue when doing a data refresh as there is a duplicate Property ID – see details below.

This affects the relationships in the reports so will be preventing updates.

![image](https://github.com/reapit/foundations/assets/10115484/0719617d-ed2d-4bdb-bb0b-8b1a144df91e)

Please can you help?

FYI - I logged a ticket similar to this previously, but the type appears to be set on this occasion
https://github.com/reapit/foundations/issues/11114

**Comment by cduggan-reapit** [comment]
Hi @MatthewGoddard - the property duplication should now be resolved.  Please let us know if you have any questions!
