### ISSUE TITLE
Simpson & Marwick (SIM) Field Request

### ISSUE THREAD

**Issue by darren1910** [reapit/foundations#11235]
**Request**

In order for us to grant access to Semi-structured 'extras' field data, please provide the following information in this request:

- The name of the customer you represent - Simpson & Marwick (SIM)
- The name of every field you need surfaced (if known) - pBURL
- A screenshot of of the field(s) you require in the agency cloud user interface
![image](https://github.com/reapit/foundations/assets/95343602/389f5160-2691-4d93-8f0f-eace0973f36f)
- A short use case as to why you require this data - need this to feed via the app developed for the website integration so that they can show this on the website

**Comment by AshDeeming** [comment]
THanks @darren1910 

Access for the field mentioned above (along with the other extra descriptions, has been set up and should become active within the next 15 minutes.
ClientId: SIM

Field = pBURL
(pLongDesc + pAdvert too) 

As per any other semi structured data you access it using the extrasField query string parameter eg;
GET /properties?extrasField=pBURL
