### ISSUE TITLE
Image reindexing unexpected validation error

### ISSUE THREAD

**Issue by nurm717123** [reapit/foundations#11246]
**Describe the bug**
I want to build a feature to reorder an image, therefore I am using `/propertyImages/reindex` endpoint, I have put the correct payload but I got validation error. 

**To Reproduce**
Steps to reproduce the behaviour eg:
1. Go to swagger
2. hit `/propertyImages/reindex` endpoint with `POST` method (using payload attached below)
3. See unexpected validation error

**Expected behaviour**
should be success, or a more clear validation error.

**Screenshots**
![image](https://github.com/reapit/foundations/assets/106480336/fbd20dfe-de58-4997-b45e-aed78e645d62)

![image](https://github.com/reapit/foundations/assets/106480336/e3bdfff7-192d-47bf-95c2-9637526d9566)

**payload**
{
    "propertyId": "FND236766",
    "imageOrder": [
        "FND236766_13.jpg",
        "FND236766_14.jpg",
        "FND236766_15.jpg",
        "FND236766_16.jpg",
        "FND236766_17.jpg"
    ]
}

**Comment by AshDeeming** [comment]
Hi @nurm717123 

Please could you confirm the app name & the customer the above examples relate to?

**Comment by nurm717123** [comment]
I just test it with "ACO240003" propertyId today, and its work now, thanks.
