### ISSUE TITLE
Savills Pre Tenancy (TP) APP - users unable to save/make any changes

### ISSUE THREAD

**Issue by NicolePerezSavills** [reapit/foundations#11244]
**Describe the bug**
When a user updates a check, it does not save. It unticks itself and/or changes other checks statueses

**To Reproduce**
See attached video. 

**Expected behaviour**
When a user updates a check, it retains the selection. 

**Additional context**
This happens in all arranging tenancies, not any particular tenancy. 
Software Seni have been investigating, they have disabled the refetch data feature on SAV (prod) and this did not solve the issue.

There is also an ongoing Outlook/Reapit diary sync issue (Reapit timeouts) that could potentially be linked to this issue that occurred at roughly the same time. 

This is over 48 hours now of users not being able to progress deals. 

Uploading App unticks check when going back on app.mp4…

**Comment by plittlewood-rpt** [comment]
Hi @NicolePerezSavills I can see a large number of PATCH requests to the tenancy checks endpoints returning a 412 Precondition Failed response. This suggests that the app is using the incorrect eTag value when issuing the PATCH. We'll need Software Seni involved to be able to accurately investigate this problem

**Comment by abrahamseni** [comment]
@plittlewood-rpt 
Could you please check the `metadata` entity? I think it was corrupted.
Meaning that it randomly return empty metadata even we do have it exist.

Screenshot:
left (saved response) right (newest response)
![Screenshot 2024-06-20 at 08 31 47](https://github.com/reapit/foundations/assets/94949137/1a6d2d0c-38a6-4260-b330-d28f6a314ab6)

@NicolePerezSavills 
We log the change status history in the metadata, so when the response give us an empty metadata, the app think that this check has been updated by another user, so it patching back the status.

**Comment by abrahamseni** [comment]
Another screenshot:

![Screenshot 2024-06-20 at 08 44 41](https://github.com/reapit/foundations/assets/94949137/dd2a7f0e-921b-4da0-9f00-19d3c65d3c1d)

**Comment by plittlewood-rpt** [comment]
Hi @abrahamseni I've had a look in our logs and I can see two PATCH requests for that tenancy check in the last 2 days:

The first is at 2024-06-20T00:13:41.434Z and the second at 2024-06-20T01:30:20.729Z. The metadata object in the latest request looked like this:

```
"metadata": {
		"lettings": {
			"modifiedByUser_email": "",
			"modifiedByUser_name": "",
			"hasChangedByUser": false,
			"reasonForRejection": "",
			"changeHistory": []
		}
	}
```

This is what has been stored (empty strings don't get stored). I'm just having a look to see if I can discover why it isn't being returned.

**Comment by abrahamseni** [comment]
> Hi @abrahamseni I've had a look in our logs and I can see two PATCH requests for that tenancy check in the last 2 days:
> 
> The first is at 2024-06-20T00:13:41.434Z and the second at 2024-06-20T01:30:20.729Z. The metadata object in the latest request looked like this:
> 
> ```
> "metadata": {
> 		"lettings": {
> 			"modifiedByUser_email": "",
> 			"modifiedByUser_name": "",
> 			"hasChangedByUser": false,
> 			"reasonForRejection": "",
> 			"changeHistory": []
> 		}
> 	}
> ```
> 
> This is what has been stored (empty strings don't get stored). I'm just having a look to see if I can discover why it isn't being returned.

@plittlewood-rpt the second patch is because the API returned an empty metadata, so the app thinks that the check status has been changed by another user so it patching it again with mostly empty data.

I am aware that ""/ null /undefined don't get stored.

**Comment by NicolePerezSavills** [comment]
@plittlewood-rpt Any update on this please?

**Comment by plittlewood-rpt** [comment]
HI @NicolePerezSavills we are investigating this at the moment

**Comment by RWilcox-Reapit** [comment]
Hi @NicolePerezSavills 

A fix is currently being tested and will be going out soon. I'll keep you updated.

Thanks,
Ryan

**Comment by RWilcox-Reapit** [comment]
Hi @NicolePerezSavills 

This should be fixed now, 
I'll leave this ticket open until you confirm your end.

Thanks

**Comment by NicolePerezSavills** [comment]
@RWilcox-Reapit Looks like it's fixed now based on initial testing. Let's keep this ticket open until tomorrow for monitoring when majority of the business has had the chance to fully use the TP App. 

Also, what caused this issue?

**Comment by RWilcox-Reapit** [comment]
Hi @NicolePerezSavills 

We introduced a new feature to allow users to have token based paging #10990 
That has some substantial performance benefits for users paging through data. 

A bug was inadvertently introduced which incorrectly paged data in memory meaning some records were trimmed from the response.

Hope this helps, 
Ryan
