### ISSUE TITLE
Update property API so that sub agent terms explicitly sets call for fees without exposing a value when set in the CRM

### ISSUE THREAD

**Issue by metaljoe** [reapit/foundations#11255]
This issue follows on from #10615 and #10940 to do with fetching the commissions used by the LonRes subscriber website. 

#10940 adds the subAgentTerms to the property endpoint, however the values being returned do not always match the values currently being sent in the BLM file to LonRes.

For example, we are beta-testing with Russell Simpson and on 12th June the BLM file had the following instructions with a LONRES_FEE set as follows:

1 lettings instruction with commission:

- 1000003977_RUS200366_L → 2%

5 sales instructions with commission:

- 1000003977_KEN210087 → 0.5%
- 1000003977_KEN220237 → 0.5%
- 1000003977_KEN240238 → 1%
- 1000003977_RUS200682 → 0.5%
- 1000003977_RUS230061 → Call For Fees

On Foundations, the letting instructions do not have the field available (it appears #10940 only implemented the field for sales properties), which is another issue. The following sales properties are available from Foundations and have subAgentTerms available:

- 1000003977_KEN240238 → 1%
- 1000003977_RUS230061 → 0.5% (doesn’t match BLM)
- 1000003977_KEN210087 → 0.5%

So 1000003977_RUS230061 is set to Call For Fees in the BLM, but Foundations returns 0.5%.

Can someone confirm whether the LONRES_FEE commission data sent to LonRes in the BLM file from iupload is supposed to be the same as that supplied in subAgentTerms? If not, what needs to be done to make the LonRes fee/commission data available?

**Specification**
- Project: Reapit.Services.Properties
- When call for fees is set, the API should not return an `amount` (instead return null) in the `subAgentTerms` object in `PropertySellingModel` (even if amount is set in the CRM)

**Comment by plittlewood-rpt** [comment]
Hi @metaljoe we have split this ticket up as you will see above. We will address the issue of not exposing callForFees correctly first, and deal with adding support for sub agent terms in for properties with a lettings marketing mode in the linked issue

**Comment by metaljoe** [comment]
Thanks for the update @plittlewood-rpt - all makes sense.
