### ISSUE TITLE
Getting a page of works orders is now taking around 16 seconds since 18th June

### ISSUE THREAD

**Issue by whanno-lsl** [reapit/foundations#11253]
**Describe the bug**
We have an integration that reads a page of the most recent 100 works orders created so do some checks, and since 18th June it now takes around 16 seconds to return the page instead of around a couple of seconds previously.

This is causing our containers to run a lot longer than expected.

Firing the query through Postman shows the same issue.

Note this is for the customer "YOM", when I hit "SBOX" as a test it was fine.

**To Reproduce**
Running the following in Postman for customer "YOM" shows the timing issue:
https://platform.reapit.cloud/worksOrders/?pageSize=100&pageNumber=1&createdFrom=2024-06-25

**Expected behaviour**
The API should return the results in a performant time period as before.

**Additional context**
From checking our logs for "YOM", up to and including the 17th June all was fine, so guessing something may have changed that night as from 18th it went slow.

**Comment by plittlewood-rpt** [comment]
Hi @whanno-lsl - we think we know what's caused this. To support larger pages of custom metadata entity types, we've introduced token based paging as a performance optimisation. This appears to have had an undesired effect on the response augmentation process specifically for the works order data metadata you have stored. I've just made a configuration change which should address this which should become active in the next 15 mins. I'm monitoring the latency metrics to check it does what we are expecting. We have a more permanent solution that will be developed and rolled out in due course.

**Comment by plittlewood-rpt** [comment]
Hi @whanno-lsl can I just check in that everything is still OK with this? Thanks

**Comment by whanno-lsl** [comment]
Yep all seems fine now, thanks.

**Comment by plittlewood-rpt** [comment]
Thanks for confirming.
