### ISSUE TITLE
RPS not creating webhook events for property created + modified

### ISSUE THREAD

**Issue by richclicksmith** [reapit/foundations#11269]
Our client "SWF" created a new property and updated another in RPS this morning but I can't see these actions in the webhook transaction log.

The entity IDs are as follows:

LMA230347
LMA240263
LMA240326

Thanks.

**Comment by plittlewood-rpt** [comment]
Hi @richclicksmith this should now be resolved - please accept my apologies for the delay in responding. Some maintenance on the webhook queue had some undesired effects this morning which caused quite a backlog to form. This is now clear and I can see events for all the properties mentioned above.
