### ISSUE TITLE
Request for Extra Fields for Paton & Co

### ISSUE THREAD

**Issue by propertyhive** [reapit/foundations#11262]
Please can you enable access to the following extra fields for Paton & Co:

pLongDesc
pAccomComp
pDirections
pSituation

**Comment by HollyJoyPhillips** [comment]
Hi @propertyhive, the following fields are already available as extra field requests: 

pLongDesc
pDirections
pSituation

I have added 'pAccomComp' which will be populated in about 15 minutes. 

Thanks
Holly

**Comment by propertyhive** [comment]
Thanks Holly! All working now.
