### ISSUE TITLE
As a customer or developer, I should route to the new standalone apps page

### ISSUE THREAD

**Issue by willmcvay** [reapit/foundations#1126]
**Background context or User story:**

_See #1125 for launch, we should route app modals to the new standalone pages. 
** Do not attempt this ticket until the UI Tickets #1206 #1225 are completed and passed QA**._

**Specification or Acceptance Criteria:**

- As per the above ticket, where we currently load an app modal, we should now route to the appropriate standalone app page.
- Delete all the old modal code
- There should be a 'back to apps' link at the bottom of the page like the apps edit page

**Comment by nphivu414** [comment]
![image](https://user-images.githubusercontent.com/22409039/82989529-09fc8680-a025-11ea-92a0-f8670464b72d.png)
Hi @willmcvay ,
Could you please provide screenshots for the "Back To Apps" button on standalone apps page (for both desktop and mobile screen)?
