### ISSUE TITLE
As a developer, I should be able to see a preview of my app listing 

### ISSUE THREAD

**Issue by willmcvay** [reapit/foundations#1127]
**Background context or User story:**

_See #1126 - using the standalone apps page, I should be able to see a preview of my app listing from the submit app and edit app pages. **Depends on #1126 - do not start this until ticket has passed QA**_

**Specification or Acceptance Criteria:**

- Should be a button at the bottom of the submit app form called "preview"
- Should be a link on the developer standalone page that routes to this preview
- Should load `client/apps/:id` page in a new tab, at the route `developer/apps/:id/preview`

**Comment by tanphamhaiduong** [comment]
@willmcvay So I have a question. For the submitting app, the preview will proceed before or after submit the app?

**Comment by HollyJoyPhillips** [comment]
@ant066 Couple of things: 

Please can you hide the 'Back to App' button and line above it when in preview mode
![image](https://user-images.githubusercontent.com/52408607/83732705-5a3aa080-a644-11ea-960c-943115d072dc.png)


Can you also link this icon to the preview page (accessed from the standalone page from developer/apps: 
![image](https://user-images.githubusercontent.com/52408607/83732674-4f800b80-a644-11ea-9e59-161c053924db.png)
