### ISSUE TITLE
API Response changed/error

### ISSUE THREAD

**Issue by danielalmeidaconnellsgroup** [reapit/foundations#11271]
**Describe the bug**
We are now getting object null exceptions on our integration to Reapit API.

We've seen this on negotiator endpoint and contact endpoint so believe it's wide spread.

We're passing the params:

OfficeId=MCK&PageSize=100&PageNumber=1&ReapitCustomer=CWC&ReapitApiVersion=2020-1-31
on both end points

This was working fine previously but looks something has changed. My dev teams are trying to identify exactly what is returning null for us and what the response we're getting looks like

**Comment by plittlewood-rpt** [comment]
Hi @danielalmeidaconnellsgroup can you send me the full request please? I can't see any errors at all coming from the negotiators API today. Thanks

**Comment by plittlewood-rpt** [comment]
No action needed as per internal thread. Will leave ticket open until we know it's resolved
