### ISSUE TITLE
Client credentials flow

### ISSUE THREAD

**Issue by kevinmackenzielablateral** [reapit/foundations#11273]
We are integrating using the Reapit API - as below.
![image](https://github.com/reapit/foundations/assets/5858805/5d85833e-659d-44bc-a9de-aac267621edb)

I believe that we need to do nothing as a result of the **Action Required: Reapit Connect Tokens** email?

Is this something that you could confirm for me?

**Comment by AshDeeming** [comment]
Thanks @kevinmackenzielablateral 
Please could you confirm this relates to the below app: Carter Jonas - Dotdigital Data Integration?

If so, this app is using client credentials flow, which this is not applicable to this update.

**Comment by kevinmackenzielablateral** [comment]
@AshDeeming It relates to the **Carter Jonas Website Integration** .... can I presume that this update is also not applicable?

**Comment by AshDeeming** [comment]
Thanks @kevinmackenzielablateral 
That is also a Server-side integration so yes, the update is not applicable.

**Comment by kevinmackenzielablateral** [comment]
@AshDeeming Many Thanks
