### ISSUE TITLE
Client Accounts Assistant property

### ISSUE THREAD

**Issue by abrahamseni** [reapit/foundations#11270]
Please expose the `Client Accounts Assistant` value against the Property

screenshot:
![image-20240626-150253](https://github.com/reapit/foundations/assets/94949137/8abd1663-d0a4-4dc4-bb14-c698a1a93fbb)

Thanks.

### Specification
- Service: Reapit.Services.Properties
- As a user I want to be able to retrieve the `Client Accounts Assistant` value against the Property
- Update both GET endpoints to display the the negotiator id associated to the value above. This is stored in properties extras under `pClAcAssist`
- Add a links to the `PropertyModel` to support the retrieval of this when populated `clientAccountsAssistant` which will reference `/negotiators/{ClientAccountsAssistantId}`. See the read model's `PopulateLinks` for reference.
- Add tests where relevant

**Comment by AshDeeming** [comment]
Hi @abrahamseni 
Please could you confirm which client this is required for?

**Comment by abrahamseni** [comment]
> Hi @abrahamseni Please could you confirm which client this is required for?

This is for SAV and SAU

**Comment by RWilcox-Reapit** [comment]
Hi @abrahamseni 

This is now available via the GET endpoints on properties as `clientAccountsAssistantId`

Thanks,
Ryan
