### ISSUE TITLE
Expose the attribute: Property -> Marketing -> Internet -> What3Words in api.

### ISSUE THREAD

**Issue by au63** [reapit/foundations#11281]
I tried looking for this value from Foundations API but couldn't find it:
![image](https://github.com/reapit/foundations/assets/139497587/89bc2fe7-0b37-4e14-8427-081ab91e164e)

So need that value exposed in the Foundations API.

### Specification
- Service: Reapit.Services.Properties
- As a user I want to be able to retrieve the What3Words field against a properties
- Update both GET endpoints to display the What3Words. This is stored in properties extras under `pWhat3Words` 
- This should be added to the core model under `urlCaption` to resemble the view in AC
- This is a read-only for now as requested (Write side is complex due to the lat-long lookup validation we perform in AC)

**Comment by RWilcox-Reapit** [comment]
Hi @au63 
This is now available via the properties GET endpoints as `what3Words`

Thanks,
Ryan
