### ISSUE TITLE
How reliable is the modified time stamp in property Schema

### ISSUE THREAD

**Issue by thashendran-perinparasa-property-logic** [reapit/foundations#11299]
Hi Team, 

I have a question regarding the modified date on the property schema, does the time stamp get updated only if certain fields are updated or will it update anything that is related to that property is updated e.g. images, documents, extra fields and ect?  

Thanks
Thashendran

**Comment by plittlewood-rpt** [comment]
Hi @thashendran-perinparasa-property-logic thanks for reaching out. The modified datetime will only be updated typically when root level fields change. This is something that does cause problems from time to time (ie when property images are updated, we did ask the CRM engineering team to ensure the parent property modified timestamp was updated). Its unrealistic for us to update the property modified date each time ANY child resource is updated, particularly where things like documents are concerned. The best thing I can suggest is if you've got a specific use case that relates to this query, to provide some more detail and we may be able to tell you yes or not as to whether that timestamp will be updated when certain actions are carried out. Hope this helps
