### ISSUE TITLE
Data Warehouse not syncing

### ISSUE THREAD

**Issue by ktanalyst** [reapit/foundations#11306]
**Describe the bug**
Logged on this morning and the last sync date for some views is 14:01 yesterday afternoon. I haven't checked all views but this is consistent for appointments and property status changes. As a result there is alot of missing data from yesterday afternoon. Please can you let us know at the earliest opportunity whether this is a known issue or something specific to our platform? When will we see this data populate?

**To Reproduce**
This will show the most recent sync date in the appointments view
`SELECT TOP 1 *
FROM REAPIT.ANALYTICS_KLR.APPOINTMENTS
ORDER BY _last_synch_at DESC`

**Expected behaviour**
All data from yesterday afternoon should be accessible within the views.

**Comment by ktanalyst** [comment]
Morning guys, please can I get an urgent update on this? @plittlewood-rpt

**Comment by plittlewood-rpt** [comment]
Hi @ktanalyst everything should be up to date. The sync was offline overnight due to the AgencyCloud upgrade last night.

**Comment by ktanalyst** [comment]
Thanks @plittlewood-rpt - given that our data isn't up to date does that mean we have an issue? I need to report back into the directors as our reports aren't accurate for yesterday. Cheers

**Comment by plittlewood-rpt** [comment]
Hi @ktanalyst can you provide some insight into what isn't up to date? Everything is showing as synchronised at this end

**Comment by ktanalyst** [comment]
See last sync times for a few of our most used views:

![image](https://github.com/user-attachments/assets/a64606d9-db48-4266-893f-e66097f5c8a4)

We've had reports this morning around missing data and I assume this will be why.

**Comment by plittlewood-rpt** [comment]
Just spotted it's the analytics schema you're reporting issues with. Let me just double check that as it's a separate job

**Comment by plittlewood-rpt** [comment]
Thanks - so this is related to the upgrade last night. As it was an upgrade that required data migrations, the warehouse sync was disabled mid-afternoon which meant it wasn't running when the last analytics schema refresh ran at 8pm. The first sync of the day runs at 10am and takes about an hour so I'd expect your reports to be up to date at around 10.45am - I'll keep an eye on it here

**Comment by plittlewood-rpt** [comment]
Hi @ktanalyst you should be starting to see updates coming through. The refresh job is about halfway through but I can see the appointments view model data has updated now.

**Comment by ktanalyst** [comment]
Thanks @plittlewood-rpt, we can see some of the views have updated, and still waiting for some others. 

Is this something that happens when every new version of agency cloud is released? We haven't noticed an issue like this before but it would be helpful to know when our feed is likely to be affected in the future. As a business we rely heavily on the data so it's important that we factor in any planned downtime.

**Comment by plittlewood-rpt** [comment]
Hi @ktanalyst please can you confirm everything caught up? Some communication was sent out specifically about this update as it involved quite a big migration of data to other areas of the database which is why the sync had to be turned off. Most agency cloud updates do not involve this kind of work so it's quite a niche situation. I'll work with our client account managers around messaging to see if anything was missed etc.

**Comment by ktanalyst** [comment]
Morning @plittlewood-rpt, all seems to be working as expected now. 

Just as a point of general interest - will a view only sync if there is new data (or amended data) to update? I've noticed that some views haven't synced since yesterday afternoon, while some have synced this morning. The ones that haven't synced may not have changed since yesterday though.

Cheers

**Comment by plittlewood-rpt** [comment]
Hi @ktanalyst the refresh job refreshes all view model data so it's based on the state of the data in your system when the job runs if that answers the question?

**Comment by ktanalyst** [comment]
Sorry, that doesn't really make much sense to me but don't worry!
