### ISSUE TITLE
Error While Integrating with Reapit API -|| Reapit Cloud ||- 2024-07-16

### ISSUE THREAD

**Issue by jcncnn** [reapit/foundations#11301]
Hello Team,

We are developers working on building new solutions using Reapit Cloud. During this process, we are integrating with the Reapit API.
We authenticate our integration using an Auth token, and subsequently, we use the API to fetch leads.

However, we are encountering an issue while fetching leads. Specifically, we receive the error: **"Error fetching leads: 403 {"message":"Missing Authentication Token"}"**. This error occurs even though we are providing the token as well as necessary parameters like Content-Type and reapit-customer when making the API call to fetch leads. 

We have also attempted this manually using Postman, but we encounter the same issue.

We kindly request your assistance in resolving this issue.

Below are API we we are using for integration

API to get token:-'https://connect.reapit.cloud/token'
API to get leads:-'https://platform.reapit.cloud/leads'

**Comment by plittlewood-rpt** [comment]
Hi @jcncnn - please refer to the [swagger documentation here](https://developers.reapit.cloud/swagger). There is no endpoint https://platform.reapit.cloud/leads - it's likely the one you are looking for is https://platform.reapit.cloud/enquiries. Many thanks

**Comment by jcncnn** [comment]
Its works!

Thanks for the help
