### ISSUE TITLE
Issue assigning Journal Entry to Enquiry using API

### ISSUE THREAD

**Issue by adamianblack** [reapit/foundations#11300]
I am sending enquiries into Reapit which hit the "internet registrations" area.
After creating the enquiry i would like to add journal entries to record any previous phone calls/messages that have been actioned against the enquiry.

When attempting to create these journal entries i get a regular error telling me that the associated ID must be 9 characters but the enquiry id is only 4 characters long.

I have included a screenshot of the structure of the payload i'm using with $create being the id returned from the enquiry post request.

Can you please advise how i should change my request to be able to successfully add Journal Entries to Enquiries

**Detail and or supporting links and screenshots**
<img width="307" alt="Screenshot 2024-07-15 at 16 04 52" src="https://github.com/user-attachments/assets/3b02116f-a500-40f0-a1ae-d7415324638d">

**Comment by plittlewood-rpt** [comment]
HI @adamianblack thanks for reaching out - it is not possible to create journal entries against enquiries. It looks like you are trying to create a journal entry here against an applicant, whose ids are 9 alphanumeric characters. Hope this helps!

**Comment by adamianblack** [comment]
Thanks for the reply, it makes sense now why there is not an "enquiry" type in the options.
Is it possible for this functionality to be added? I am working with a client who is very keen for us to be able to send this data into their system

**Comment by plittlewood-rpt** [comment]
Hi @adamianblack the customer would need to reach out to our service team to log this as a feature request. Until the CRM itself supports this functionality, we can't expose the capability in the API

**Comment by adamianblack** [comment]
The CRM appears to have an "activity log" attached to enquiries within "internet registrations" so i assumed it should just be a case of adding this to the API. Is my assumption incorrect? 
I would like to be 100% sure so I can pass this information on to our client

**Comment by plittlewood-rpt** [comment]
Hi @adamianblack yes this will need adding to the API. Apologies I didn't know this feature had gone into the CRM so had to go and check. We'll get this refined as a feature request for the API soon.

Internal ref:  PBI-5732

**Comment by adamianblack** [comment]
Thanks for sorting this, is there an estimated timeline when this might be available? 
It is for our (and i presume your) biggest client who are keen to progress with the integration.

**Comment by plittlewood-rpt** [comment]
HI @adamianblack this functionality is now available. Please refer to the swagger documentation for POST /journalEntries for changes.
