### ISSUE TITLE
Issue with Allocating Negotiator IDs to Enquiries in Reapit Cloud

### ISSUE THREAD

**Issue by jcncnn** [reapit/foundations#11314]
Hello Team,

We are developers working on creating an application for a real estate client using Reapit Cloud. During sandbox testing in developer mode, our objective is to fetch enquiries along with negotiators and allocate the enquiries to the negotiators. However, we are encountering an error when attempting to assign negotiator IDs to enquiries.

Attached below are the screenshot for error and code snippet demonstrating the issue. Kindly let us know if our approach is correct or if we are missing something and is it possible to assign negotiators to enquiries.

![image](https://github.com/user-attachments/assets/4a177898-2a2d-435f-87f3-24a75950c9b2)

[code.txt](https://github.com/user-attachments/files/16310913/code.txt)

**Comment by plittlewood-rpt** [comment]
Hi @jcncnn as you will note from the Swagger documentation this isn't currently supported in the API however it has been requested in #11243 which you are welcome to track. I'll close this item as a duplicate. Thanks
