### ISSUE TITLE
Post API for Property Licencing

### ISSUE THREAD

**Issue by DataMC-BenFung** [reapit/foundations#11321]
Summary
The licencing is available in the properties GET and PATCH API endpoint.
However, it cannot be found in the POST API endpoint.

Detail and or supporting links and screenshots
May I know if it is possible to set it through the POST API?
Are there any prerequisites for setting it?

**Comment by plittlewood-rpt** [comment]
Hi @DataMC-BenFung please see PATCH /properties/{id} - the chances of having this information available when creating a new property is quite slim, as a result it's not supported on POST /properties. hope this helps
