### ISSUE TITLE
RENEWAL NOT SHOWING IN DATA REFRESH

### ISSUE THREAD

**Issue by ijones-kooky** [reapit/foundations#11343]
We have a tenancy that currently has renewal actively assigned see screen shot below with arrow.
This was appearing in our query on the renewals table - today on refresh this has disappeared? Can someone investigate why this?
![image](https://github.com/user-attachments/assets/4b5afdae-1b57-4aa3-b74f-8bf0fe9794f1)

On the renewals table its now just showing the newer renewal not the older one?
![image](https://github.com/user-attachments/assets/8279d182-1afe-4326-9843-fb1b429ee1a3)

Please can someone help on this

**Specification**
- Project: Analytics Schema
- Update stg_tenancy_renewals view model data to use a better join when building the extensions_no_renewal table. The reason for this particular report (and the one that has been emailed) is that it is attached to a tenancy that also has a renewal that went through the negotiation process. The join is causing the renewals without a negotiation to get stripped out

**Comment by AshDeeming** [comment]
Hi @ijones-kooky 
Please could you confirm how the Renewal table has been produced? I.e. is this from the CRM reports or an App using the API?

**Comment by ijones-kooky** [comment]
Hi Ash - any luck working this out?

**Comment by plittlewood-rpt** [comment]
Hi @ijones-kooky there's a fix for this deploying now. Your data should updated in the next hour or so. Can I ask you to review it in the morning and let me know if it's resolved the problems you were reporting? Thanks

**Comment by ijones-kooky** [comment]
Hi Pete – thank you SO much.

Will look through now.

Kind regards,

Ian Jones
Head of Finance

T
 +44 (0) 20 7100 5694
1 Vere Street
4th Floor
London
W1G 0DF
[signature_1194851264]<https://www.linkedin.com/company/delph-property-group>

[signature_934278327]<https://delphgroup.com/>
[A picture containing shape  Description automatically generated]<https://forty8developments.co.uk/>
[Shape  Description automatically generated]<https://mykookyhome.com/>
[A picture containing icon  Description automatically generated]<https://delphliving.com/>

DISCLAIMER: This email and any files transmitted with it are confidential and are intended solely for the use of the individual or entity to whom they are addressed. If you are not the intended recipient or the person responsible for delivering the email to the intended recipient, be advised that you have received this email in error and that any use, dissemination, forwarding, printing, or copying of this email is strictly prohibited. If you have received this email in error, please immediately notify the sender via email or telephone and delete it from your system. We take all reasonable steps to ensure that all emails leaving our offices are tested for software viruses but we do not accept responsibility for any loss or damage which may occur from using this email or any attachment. Whilst this email has been scanned for all viruses by Panda Security Cloud Email Protection, Delph Property Group cannot be held responsible for any failure by the recipient or entity to check for viruses prior to opening the email or any files transmitted. Delph Property Group Limited - Registered Office: 6th Floor 9 Appold Street, London, EC2A 2AP. Registered No: 11121890. Registered in England.

**Comment by ijones-kooky** [comment]
Brilliant work @plittlewood-rpt  - thank you so much! could you confirm that this will fix any other instances where a renewal didnt go the negotiation process before?

Thanks :)

**Comment by plittlewood-rpt** [comment]
Thanks @ijones-kooky yes it will resolve all the other instances (there were only a few based on your data yesterday).

**Comment by ijones-kooky** [comment]
Thank you very much Pete – have a great day

Ian Jones
Head of Finance

T
 +44 (0) 20 7100 5694
1 Vere Street
4th Floor
London
W1G 0DF
[signature_1194851264]<https://www.linkedin.com/company/delph-property-group>

[signature_934278327]<https://delphgroup.com/>
[A picture containing shape  Description automatically generated]<https://forty8developments.co.uk/>
[Shape  Description automatically generated]<https://mykookyhome.com/>
[A picture containing icon  Description automatically generated]<https://delphliving.com/>

DISCLAIMER: This email and any files transmitted with it are confidential and are intended solely for the use of the individual or entity to whom they are addressed. If you are not the intended recipient or the person responsible for delivering the email to the intended recipient, be advised that you have received this email in error and that any use, dissemination, forwarding, printing, or copying of this email is strictly prohibited. If you have received this email in error, please immediately notify the sender via email or telephone and delete it from your system. We take all reasonable steps to ensure that all emails leaving our offices are tested for software viruses but we do not accept responsibility for any loss or damage which may occur from using this email or any attachment. Whilst this email has been scanned for all viruses by Panda Security Cloud Email Protection, Delph Property Group cannot be held responsible for any failure by the recipient or entity to check for viruses prior to opening the email or any files transmitted. Delph Property Group Limited - Registered Office: 6th Floor 9 Appold Street, London, EC2A 2AP. Registered No: 11121890. Registered in England.
