### ISSUE TITLE
Snowflake/Fivetran sync times

### ISSUE THREAD

**Issue by thomastruman** [reapit/foundations#11351]
Hi, I've been informed the sync frequency of data to Snowflake is set to 15 minutes, however from testing with SQL queries today and yesterday it seems to be anywhere up to around 30 minutes.

I'm currently creating tools and reports that automatically refresh queries and need to be able to provide an estimate of sync frequency to the users.

Could you confirm the set sync frequency, and whether up to 30 minutes is normal/to be expected? Is it slower at different times of day or impacted by higher traffic?

Thanks

**Comment by plittlewood-rpt** [comment]
Hi @thomastruman the sync job will start to execute every 15 minutes but depending on load at the time it may take longer. This is also for the operational schema only. The analytics schema refreshes less frequently

**Comment by thomastruman** [comment]
That's good to know - thank you
