### ISSUE TITLE
Properties APIs are not returning the same result

### ISSUE THREAD

**Issue by hoangnguyentci** [reapit/foundations#11379]
**Describe the bug**
Property FAR240051 (client ROM) is missing from get properties API but appearing in the property detail API

**To Reproduce**

- Call API: https://platform.reapit.cloud/properties/?id=FAR240051

There is no property returns in the response

- Call API: https://platform.reapit.cloud/properties/FAR240051

Property ID FAR240051 returns in the response

**Expected behaviour**
Both API https://platform.reapit.cloud/properties/?id=FAR240051 and https://platform.reapit.cloud/properties/FAR240051 should return the Property ID FAR240051

**Screenshots**
<img width="494" alt="Screenshot 2024-08-14 at 17 47 13" src="https://github.com/user-attachments/assets/ec1d6144-7d53-447e-a00a-4ef312429374">
<img width="638" alt="Screenshot 2024-08-14 at 17 47 05" src="https://github.com/user-attachments/assets/307714be-349a-4109-8778-2c5768e3f400">

**Device (please complete the following information for web issues):**
 - Device: [e.g. iPhone6, PC, Mac]
 - Browser [e.g. Chrome, Safari]

**Additional context**

**Comment by AshDeeming** [comment]
Migrated to: PBI-5853

**Comment by AshDeeming** [comment]
Please note - This is expected behaviour.  FAR240051 is archived, therefore is only returned by the wider GET route if the user specifically requests archived items.

**Comment by plittlewood-rpt** [comment]
Closed as discussed with third party
