### ISSUE TITLE
Relation between Manager and Negotiator 

### ISSUE THREAD

**Issue by adisingh789** [reapit/foundations#11375]
Want to know, how to get the relation between Manager and Negotiator from snowflake datawarehouse.

**Comment by plittlewood-rpt** [comment]
Hi @adisingh789 please can you elaborate a little on what you are trying to determine? Is it the office manager you are talking about? Or the contact manager or property manager etc

**Comment by adisingh789** [comment]
Hi @plittlewood-rpt I want to know which table can be used to view the relationship between office manager and its office negotiators.

**Comment by plittlewood-rpt** [comment]
Hi @adisingh789 thanks - you should be able to do this fairly simply.

OFFICES has a field called MANAGER_NEGOTIATOR_ID which joins to NEGOTIATORS.ID however this is probably irrelevant here if you're already looking at the OFFICES table. You should just be able to run something like:

`SELECT * FROM NEGOTIATORS WHERE OFFICE_ID = '[OFFICE.ID]'` where OFFICE.ID is the id from the same row you're looking at in the offices table for a particular manager. 

Does that answer your question?

**Comment by adisingh789** [comment]
Thanks!
