### ISSUE TITLE
Adding photos field in the appointment table and price change,price change date in property_sales_won_instruction

### ISSUE THREAD

**Issue by adisingh789** [reapit/foundations#11377]
Hi Team,

Please add photos field in the appointment table and price change, price change date in property_sales_won_instructions table.

**Comment by plittlewood-rpt** [comment]
Hi @adisingh789 this information wouldn't go into either of those tables as they are completely different entities and/or pieces of information. You are responsible for joining data in whatever system you are using (Power BI etc) to model the data as you wish.

Property image data is found in the PROPERTY_IMAGES view model
Price change data can be found in the PROPERTY_SALES_PRICE_CHANGES (for Sales) and PROPERTY_LETTINGS_RENT_CHANGES (for Lettings) view models. What you are suggesting isn't something we'd be able to implement in the models requested for the reasons above.
