### ISSUE TITLE
Add new checkbox option in AgencyCloud?

### ISSUE THREAD

**Issue by richclicksmith** [reapit/foundations#11388]
Is it possible to add a new checkbox option to the Descriptions section in AgencyCloud that would then be accessible via the /properties/ endpoint?

See screenshot below.

<img width="963" alt="Screenshot 2024-08-15 at 12 51 12" src="https://github.com/user-attachments/assets/5c8cff05-95ce-4b13-ac3e-b2594d48b8e0">

Thanks.

**Comment by AshDeeming** [comment]
Hi @richclicksmith 
Addtional fields to the CRM will need to go through the Reapit Support desk - the client can request this & our support team can implement. Once in place, this will be surfaced via the attributes in the Properties endpoint
