### ISSUE TITLE
Need to get measurement section such as floor size key information

### ISSUE THREAD

**Issue by sanjayisg** [reapit/foundations#11389]
Hi There,

I need to get **measurement section such as floor size key information** from API. Right now it's coming in summary section but that can not parsed exactly. We need to put this information on page schema code which is very useful for SEO and page ranking.

Please help me to get this information.

![floorsize](https://github.com/user-attachments/assets/b0d32be9-5f83-4a84-9078-153b87a76265)

Thanks,

Sanjay Gupta

**Comment by plittlewood-rpt** [comment]
HI @sanjayisg please see GET /properties and refer to the `internalArea` property

**Comment by sanjayisg** [comment]
Thanks Plittlewood..
