### ISSUE TITLE
Set the title of an appointment created through the API

### ISSUE THREAD

**Issue by unrvldtomward** [reapit/foundations#11406]
Hi,

Is there a way to set the title on appointments (and other entities) created through the API?

Through an old integration, the title for an appointment was being created with a "Made by: Reapit" suffix, but I can't see any field that would allow the title to be set in this way in the foundations API.
![image](https://github.com/user-attachments/assets/cbf124fd-2952-4b96-8ac0-98f2ab9c3b84)

Thanks.

**Comment by plittlewood-rpt** [comment]
Hi @unrvldtomward this is achieved by setting the "organiserId" to the relevant negotiator id when calling `POST /appointments`

Hope this helps! Thanks
