### ISSUE TITLE
Bar Chart Update (Billing/Analytics)

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#1145]
**Summary:** We now have the billing endpoint to populate the ‘Services’ bar chart on the Billing 
tab in the Developers Portal Analytics

**Endpoint:** https://dev.platformmarketplace.reapit.net/trafficevents/swagger/index.html
/billing

**Location:** https://dev.marketplace.reapit.cloud/developer/analytics/billing

The chart is based on the ‘grossAmount’ for each month.
 
- The first month should be the month the developer was created (/developers/{id} ‘created’)
- Query the /billing endpoint, supply the ApplicationIds (will need to supply all apps for that developer - to get the ID's you will need to query 'Apps by DeveloperId')
- 'DateFrom' should be the month the developer was created
- 'DateTo' should be the current month 
- The endpoint will return a ‘requestsByPeriod’ which will include those months.
- Use the ‘periodName’ to label each bar (should include the year)
- Display the ‘grossAmount’ for each bar

**Comment by HollyJoyPhillips** [comment]
Hi @tanphamhaiduong Just a small tweak please, can you add a pound sign (£) for the hover over, so it will be £.6.88 

![image](https://user-images.githubusercontent.com/52408607/81562820-6016cc00-938d-11ea-8ace-df1767df4e92.png)

**Comment by tanphamhaiduong** [comment]
As discussion with @HollyJoyPhillips  we'll add like the image below.
![image](https://user-images.githubusercontent.com/22660833/81667776-e73b7100-946d-11ea-8696-7e8798b39f66.png)
