### ISSUE TITLE
Add clientIDs without raising Reapit app revision

### ISSUE THREAD

**Issue by Reapit-TanMatthews** [reapit/foundations#11463]
Hi, 
Third-party request ability to add client/ customer IDs without the Reapit raising revision dependency. 
Reason: Could save time for both parties.

Advised current process requires clients approving/ acknowledging app once revision/ request information received, so additional client IDs still required post app go live.

**Comment by plittlewood-rpt** [comment]
@Reapit-TanMatthews Github is no longer being used to manage work. Please reach out on JIRA. Thanks
