### ISSUE TITLE
Updates required to the Webhooks page in the Developers Portal 

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#1159]
**Summary:** As we now have the Webhook page with the Add and Edit functionality, there are a few features and UI tweaks that need looking at.

**Location:** https://dev.marketplace.reapit.cloud/developer/webhooks

- Remove the option to Add a New Webhook' and the table headers until an app has been selected: 
![image](https://user-images.githubusercontent.com/52408607/81165078-4b9b9380-8f89-11ea-826a-ca4d72d83e35.png)

- Remove the requirement to add a customer as if no customers are added it should apply ‘All Customers’ by default:  
![image](https://user-images.githubusercontent.com/52408607/81165087-50604780-8f89-11ea-8f10-2eb48fb30b54.png)

- When editing 'GEO Diary' web hooks 'DXX' is displaying multiple times: 
![image](https://user-images.githubusercontent.com/52408607/81165118-63731780-8f89-11ea-84df-c954d23af5d9.png)

- If I select ‘DXX’ as a customer, it displays as ‘All Customers’ rather than DXX on the table: 
![image](https://user-images.githubusercontent.com/52408607/81165132-6a018f00-8f89-11ea-993b-a59fcf76cb8e.png)

- Can we use the Topic ‘Name’ rather than the ‘ID’ for the Topic column please?
- ![image](https://user-images.githubusercontent.com/52408607/81165145-6ff77000-8f89-11ea-9984-1a2c26d6b451.png)
![image](https://user-images.githubusercontent.com/52408607/81165174-784fab00-8f89-11ea-8b08-01a221698956.png)

- Can you stack the Topics rather than side by side in the Topic column:   
![image](https://user-images.githubusercontent.com/52408607/81165192-800f4f80-8f89-11ea-8120-4bbdd4733245.png)

**Comment by ant066** [comment]
Hi @HollyJoyPhillips.
When editing 'GEO Diary' webhooks 'DXX' is displaying multiple times:
when I call API to get app's installation, it returns many multiple times DXX client.
<img width="688" alt="Screen Shot 2020-05-07 at 10 21 17 AM" src="https://user-images.githubusercontent.com/30467048/81251274-0fca0200-904d-11ea-9c16-4eb1e4f7cee4.png">
So I think this issue about API data.

> curl 'https://dev.platformmarketplace.reapit.cloud/installations?AppId=42c60301-c2c5-49bb-b4ec-d5cb27eaf2a4' \
  -H 'authority: dev.platformmarketplace.reapit.cloud' \
  -H 'dnt: 1' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36' \
  -H 'x-api-key: QGUz1hI2ye9VMohQdssOu6N2klb7OetWx5rRAIfh' \
  -H 'content-type: application/json' \
  -H 'accept: */*' \
  -H 'origin: http://localhost:8080' \
  -H 'sec-fetch-site: cross-site' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-dest: empty' \
  -H 'referer: http://localhost:8080/developer/webhooks' \
  -H 'accept-language: vi-VN,vi;q=0.9,fr-FR;q=0.8,fr;q=0.7,en-US;q=0.6,en;q=0.5' \
  --compressed

**Comment by HollyJoyPhillips** [comment]
@ant066 So it looks like we are calling the Installations endpoint for all installations not just the current installation. DXX has installed and uninstalled GEO Diary on several occasions which is why it is appearing multiple times. It should only show current installations. 

If you look on the Analytics page you will see we display GEO Diary as having 2 current installations: 
![image](https://user-images.githubusercontent.com/52408607/81283118-0d1edb00-9054-11ea-88eb-35724352a60e.png)

You can use the same query to display the customer ID's. 

We should only display current installations (where an installation does not have a 'terminated' date). Does that make sense?

**Comment by HollyJoyPhillips** [comment]
Hi @ant066, can we please add validation to the URL field. If I enter an incorrect URL the backend reports the following 'The value must be a valid and secure URI' can we display that in the frontend please? 

![image](https://user-images.githubusercontent.com/52408607/81662605-bb03fe00-9435-11ea-9661-cc90dcff3450.png)

Please also update the placeholder text from 'Enter a URL' to 'Enter a secure URL (https://)'
