### ISSUE TITLE
HTML Description field

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#1160]
**Summary:** As we have introduced the ability to edit the Description with HTML, we need to address the following issues 

**Relates to ticket:** https://github.com/reapit/foundations/issues/1123

- Can we make the box the same size as the Summary: 
![image](https://user-images.githubusercontent.com/52408607/81165856-a386ca00-8f8a-11ea-9632-159785385acf.png)

- Adding an external link seems to include the code ‘&nbsp:’	
- The bullet point seems to be out of the green area and not aligned in the revisions modal 
![image](https://user-images.githubusercontent.com/52408607/81165885-ae415f00-8f8a-11ea-99bc-199df0bf464d.png)

 
- Or after saving: 

 
![image](https://user-images.githubusercontent.com/52408607/81165893-b4374000-8f8a-11ea-8441-2bd6c878951c.png)

- The external link does not work on the modal, when you click it nothing happens: 
![image](https://user-images.githubusercontent.com/52408607/81165912-ba2d2100-8f8a-11ea-9524-a4bc42542e3c.png)

 
- The link should also be the Reapit blue (#0061a8) 
- We need to be able to view the link in the Admin Portal when a revision is made, might need to be a separate ticket? 
- I can’t edit the external link when editing the app, I would have thought highlighting the wording and clicking on the ‘link’ icon would give me the option to edit the existing link 
 
![image](https://user-images.githubusercontent.com/52408607/81165922-bef1d500-8f8a-11ea-95d4-45ad21d18d12.png)

- The line break/paragraph tag doesn’t seem to work at all. 
 
![image](https://user-images.githubusercontent.com/52408607/81165941-c44f1f80-8f8a-11ea-9c03-930d56a97dc9.png)

**Comment by vuhuucuong** [comment]
hi @HollyJoyPhillips , about this

> We need to be able to view the link in the Admin Portal when a revision is made, might need to be a separate ticket?

Now we can just click into the link in the revision modal to check where it's linked to. But if you want to somehow view the link without click into it. I think a popup like this pic
<img width="261" alt="Screen Shot 2020-05-11 at 15 33 48" src="https://user-images.githubusercontent.com/26746668/81541136-dc64db80-939c-11ea-8d4b-cc6821dd5bba.png">
when hovering on the link should be suitable for this.
Please create a new ticket if you want that thing. Thanks :)

**Comment by HollyJoyPhillips** [comment]
Hey @vuhuucuong That's a great idea. I'll get a ticket added for it, thank you.

**Comment by HollyJoyPhillips** [comment]
Hey @vuhuucuong, thanks for looking at this, just a couple of points: 

The placeholder text on the Description is very light, makes it hard to read, can we match the colour with the summary placeholder text 
![image](https://user-images.githubusercontent.com/52408607/81560459-58edbf00-9389-11ea-855e-4c3adcf7ad37.png)

I still cannot edit an existing link, can only create a new one?

**Comment by vuhuucuong** [comment]
Thank @HollyJoyPhillips, It's weird if you cant edit existing link, I'm able to do it

https://streamable.com/fkgij5

About the color, I'll fix it

**Comment by HollyJoyPhillips** [comment]
Hi @vuhuucuong, thanks for updating the font and adding the H5, much better. 

Just one small thing, the validation is no longer appearing underneath box if the char limit has not been met or exceed. It is still appearing at the bottom of the page but we should still show it under the field (as we do with the summary) 

![image](https://user-images.githubusercontent.com/52408607/81661893-b723ac00-9434-11ea-9798-84ec3ed9a918.png)

![image](https://user-images.githubusercontent.com/52408607/81661925-c1de4100-9434-11ea-84d8-34492c550e0a.png)

**Comment by HollyJoyPhillips** [comment]
Hi @vuhuucuong, it looks like there maybe an issue with the char limit. I've entered 678 chars in the example below, all plain text and it's showing the validation error: 

![image](https://user-images.githubusercontent.com/52408607/81786959-434ad780-94f8-11ea-9373-4ba735b0df6f.png)
