### ISSUE TITLE
Investigate error response for webhooks topics retrieval issue

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#1163]
Holly saw a webhooks service error when retrieving available topics for a specific application:

The trace showed that hitting the following:

`/webhooks/topics?applicationId=5c0ce6b1-0573-4594-9606-adb55671d8b8`

Resulted in a 400 error: 

`description: "Value cannot be null.↵Parameter name: source"`

Request looked legit so we need to look at why this fell over. 

May be a perfectly legitimate error but we should be returning a better message here at least.

**Comment by plittlewood-rpt** [comment]
This is happening because there are no scopes attached to the app you've run this test with. I'll update the handling for this situation, though it shouldn't happen really

**Comment by plittlewood-rpt** [comment]
PR 1894 opened to fix this
