### ISSUE TITLE
Sentry issues with service worker

### ISSUE THREAD

**Issue by willmcvay** [reapit/foundations#1183]
**Issue details:**

_See screenshot, there is a service worker error that posts at 2am each morning. Given the exact time, this is likely to be a problem with the CRON job that purges S3 or similar_

<img width="990" alt="Screenshot 2020-05-11 at 07 48 41" src="https://user-images.githubusercontent.com/4630495/81533069-72791180-935d-11ea-808f-21f5c40826d7.png">

**Comment by tanphamhaiduong** [comment]
This error relates to cronjob clean up S3 bucket. So it's no longer appear on sentry.
