### ISSUE TITLE
Unable to load GEO Diary (PROD) 

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#1188]
**Describe the bug**
Unable to load GEO Diary (prod). Navigating to https://geo-diary-app.reapit.cloud/ in incognito the page should either load page or navigate to login

**To Reproduce**
Load https://geo-diary-app.reapit.cloud/
**Expected behavior**

**Comment by tanphamhaiduong** [comment]
I think this ticket has been resolve by me.
