### ISSUE TITLE
UI for the Developer Side standalone app 

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#1210]
**Summary:** As the apps in the developer portal are now standalone and accessible via another page rather than a modal, we need to update the UI with the following.

**Relates to ticket:** https://github.com/reapit/foundations/issues/1125
**Client side**: https://github.com/reapit/foundations/issues/1206

### General
- Headers: H5, Museo Sans 700
- Colour: #12263f
- Text: Roboto, 14px 
- Colour: 556986
- Guttering: 1rem (as with submit app and other pages in the developer portal)

### Lefthand navigation
- Heading: Category - if one has been selected, use Lozenge/tag component - if no category has been selected show 'None' 
- Should display ‘Desktop Integration Types’ (as above)
- Heading: Private App - should display 'Yes' or 'No' 
- Heading: Direct API - should display 'Yes' or 'No' 
- Heading: Status - Should display 'Is Listed' status - if yes 'Listed' with green tick. If 'not listed' display 'Not Listed' with red X (as we do currently on the modal) 
- Heading: Manage App
- Buttons: Edit Detail & Delete App 

### Main Apps Page
- Icon image to the left of App Name
- App Name: H2, Museo Sans 300
- Directly underneath, add ‘Verified by Reapit’ and a green tick (the same green tick when an app is listed) 
- Summary: App ‘Summary’
- Heading: See listing preview 
- Icon: FaExternalLinkAlt (Reapit blue #0061a8)
- Link: Dependent on ticket: https://github.com/reapit/foundations/issues/1127
- Helper text: The listing preview will display your app as it would appear in the Marketplace 
- Heading: Authentication 
Should display the client ID and Secret (depending on Authorisation flow) 
- Heading: Installations 
- Display client installations (as we do currently on the modal). If an installation exists, change the 'Uninstall' button for a link (reapit blue #0061a8) 
If no installations, display helper text, 'Currently, there are no installations for your app'

See mockup:
![AppPage---Dev](https://user-images.githubusercontent.com/52408607/81607954-6a58ba80-93cd-11ea-9b86-a67218698d38.jpg)

**Comment by HollyJoyPhillips** [comment]
@phmngocnghia, Couple of things: 

- Confirm uninstall modal has additional white padding: 
![image](https://user-images.githubusercontent.com/52408607/82944208-b2153f80-9f92-11ea-97e9-d862e1cc1e4f.png)

See normal padding on the modal: 
![image](https://user-images.githubusercontent.com/52408607/82944219-b80b2080-9f92-11ea-8e2d-15c2533bf65a.png)

The same white spacing around the ‘Success’ when confirming a uninstall 
 
![image](https://user-images.githubusercontent.com/52408607/82944239-bccfd480-9f92-11ea-8a00-646f8a56f7bf.png)

- I have removed the ‘Desktop Integration’ types from GEO Diary: 
 
![image](https://user-images.githubusercontent.com/52408607/82944250-c0fbf200-9f92-11ea-869b-f6a7296b9024.png)


But they are still showing on the standalone page:
![image](https://user-images.githubusercontent.com/52408607/82944264-c8bb9680-9f92-11ea-81c3-e4d25e74a5a2.png)


- Similar, Holly Loop Test has 3 desktop types & and Private is set to ‘No’
![image](https://user-images.githubusercontent.com/52408607/82944285-d244fe80-9f92-11ea-9fc6-97287f84bc71.png)

 
![image](https://user-images.githubusercontent.com/52408607/82944300-d6711c00-9f92-11ea-93ce-37c22e92def8.png)

However, if you look at the standalone page, there are additional desktop types and private app is showing as ‘Yes’: 
![image](https://user-images.githubusercontent.com/52408607/82944307-dc66fd00-9f92-11ea-8ffe-e84ae4500b11.png)

**Comment by phmngocnghia** [comment]
@HollyJoyPhillips About Issue Can't edit app detail in the standalone developer app. I was working for me.

Have you approved the pending revision after edit the app?

**Comment by phmngocnghia** [comment]
About the issue: "modal has additional white padding". I have tested the issue today, unable to reproduce the issue. Seems like cloudfront cache issue (server-side stuff)
