### ISSUE TITLE
Config CloudFront cache to avoid cannot load chunk file when deploy

### ISSUE THREAD

**Issue by tanphamhaiduong** [reapit/foundations#1217]
**Background context or User story:**
- Now when we do deployment on development environment the CLI clean up the old version one and after that push the new version one. So that will cause the current user-facing with the Error cannot load chunk files because it has been deleted by dev deployment pipeline

**Specification or Acceptance Criteria:**
- There's no alert for error cannot load chunk files for development environment anymore
- User can use the old version as normal when we deploy the new version to S3
- Modify the serverless.yml for the cache of CloudFront

**Suggested solution:**
- We need an increasing cache of CloudFront service for js file only.
- Revert the deployment for S3 bucket on the pipeline to delete old assert before copy the new one to development bucket
- Monitoring for a week to make sure it works correctly

**Comment by tanphamhaiduong** [comment]
I'll config for the marketplace dev only and let it in review 1 week for testing purposes.

**Comment by tanphamhaiduong** [comment]
@willmcvay Finish on the config for development env. Pls wait and check, If everything is ok it'll proceed to the production environment

**Comment by willmcvay** [comment]
Upgrading this issue to bug status, need to resolve in the stability milestone
