### ISSUE TITLE
Address confusing structure in web components

### ISSUE THREAD

**Issue by willmcvay** [reapit/foundations#1218]
**Background context or User story:**

_The current structure of web components does not make sense regarding the widgets it should output

The web components should output 5 named packages, plus common folder:

* Search Widget
* Book Valuation Widget
* Book Viewing Widget
* Property Detail Widget
* Appointment Planner Component

Each of the four widgets should have it's own script on the CDN and be an exportable module from NPM.

The Appointment Planner should be a sub component of both book a valuation and book a viewing and live in it's own folder as it is shared. The appointment planner should not need to be rendered separately or deployed as a separate script, rather it should be included in the booking components at compile time.

Each of the 4 widgets plus the appointment planner will have their own server folder, lambda and API like search widget. 

Task is to ensure this structure works, change naming conventions where required, deploy and update the demo site_

**Comment by willmcvay** [comment]
<img width="586" alt="Screenshot 2020-05-26 at 14 20 55" src="https://user-images.githubusercontent.com/4630495/82905782-326c7e00-9f5c-11ea-846b-7e89eeb2f4a5.png">

The folder structure still doesn't quite map right, as per the spec, the widgets are;

Search Widget
Book Valuation Widget
Book Viewing Widget
Property Detail Widget
Appointment Planner Component

So I guess a clear folder structure would be:

`search-widget`
`book-valuation-widget`
`book-viewing-widget`
`property-detail-widget`
`appointment-planner-component`

**Comment by vuhuucuong** [comment]
hi @willmcvay, do we need to put `common` folder in `./src`, or move it outside, and about the `login` folder, should it be in here ?

**Comment by willmcvay** [comment]
Login, yes, but should be called `login-reapit-component` common is fine where it is I think

**Comment by vuhuucuong** [comment]
@willmcvay Thank you, I will fix it 👍
