### ISSUE TITLE
Business logic for Appointment Planner API

### ISSUE THREAD

**Issue by willmcvay** [reapit/foundations#1224]
**Background context or User story:**

_Depends on #1222. The Appointment Planner API should return a list of available slots as a GET from the route `/appointment-slots`_ 

**Specification or Acceptance Criteria:**

- As a query string, API will accept parms "postcode", "dateFrom" and "dateTo"
- reapit-customer will be available as a header in the API request
- See platform API Swagger, first query Offices by address, passing in Postcode as address param and fetching negotiators as an _embedded resource.
- Then fetch config for reapit-customer as per above from Web Components Config API - this will return a list of negotiator ids
- Filter the list of negotiators from each office by the list of config negotiator ids
- Request appointments for each negotiator by id and by "dateFrom" and "dateTo"
- Look at the appointment planner client code for expected object structure - the response should be convenient for populating the planner table.
- Assuming an 8am to 8pm working day (we can make this a config variable later), set up slots for all working days (omitting non-working days from the config). 
- Iterate through each slot, checking if *all* negotiators are unavailable. If so, mark the slot unavailable, if not, mark it available.
- Of the available slots, check that the negotiator is still available at the end based on the duration of the slots set in the config and that they do not have another appointment starting within the duration between appointments set in the config.
- If they are available, assign the negotiator to this slot and move on, if not check the other available negotiators, if none are available by this criteria, mark the slot unavailable and move on.
- On completion of this filtering, you will have a list of available slots with negotiators assigned to them and unavailable slots with no negotiator assigned, grouped by day and in time order.
- Return this list via the initial GET res object.

**Comment by trankhacvy** [comment]
Hi @willmcvay , as I understanding, the flow will be:
- Query Offices by address => receive list of offices
- For each office => query negotiators by officeId => receive list of negotiators
- Then fetch config for reapit-customer as per above from Web Components Config API - this will return a list of negotiator ids (Not so sure about this, what endpoint of this config ?)
- Filter the list of negotiators from each office by the list of config negotiator ids
- Request appointments for each negotiator by id and by "dateFrom" and "dateTo"

Is it correct flow ? Could you please explain for me more about point 3 ?

**Comment by trankhacvy** [comment]
Hi @willmcvay , I have some questions about this ticket.
- When we fetch negotiators of each office we receive  PagedResultNegotiatorModel_ result and when we fetch the config for  reapit-customer we receive some thing like this 
<img width="243" alt="Screen Shot 2020-05-27 at 14 49 41" src="https://user-images.githubusercontent.com/8068926/82993036-31098700-a02a-11ea-8ca9-a02ba08db6fa.png">

=> So how we `Filter the list of negotiators from each office by the list of config negotiator ids`

- How can we set up slots ? ex: an 8am to 8pm working day, appointmentLength = 60 and appointmentTimeGap = 60 (get from config api) so the slots will be `8am - 9am`, `10am-11am` ... is it right ?

- After we have list appointments and list of slots, Iterate through each slot, for example slot `10am-11am`, we check it with list of appointments, if all appointments **haven't** occur from 10am to 11am so this slot is available. If at least one appointment occurs in this time, this slot is unavailable. Is it correct ?

**Comment by willmcvay** [comment]
- So on your first point, the address will return you 1 or possibly more offices and you will request the negotiators for these offices as an _embedded resource.
- You have a list of negotiator ids from the config endpoint.
- Filter each office's negotiators by the list of negotiators from the config. We are only interested in this sub set.

**Comment by willmcvay** [comment]
- On your point 2, not quite. Because if the negotiator is free from 8 until 9, they can have an appointment at 9 as long as there is still a 60min gap after before their next appointment.
- On your point 3, again not quite. What you are describing is a scenario where _all_ negotiators are free - what we are looking for is a slot where _at least one_ negotiator is free.

**Comment by willmcvay** [comment]
A better way to look at is this; forget about slots for a minute. 

- For each working day 8-8, just iterate through each negotiator appointments list and find blocks where they are free. The blocks are defined as `gap between + length of appointment + gap between` If the block is either before 9am or after 7pm (the beginning and end of the day), disregard the before or end times respectively.
- In this case you have your available slot - the `length of appointment` value in the middle of your block.
- Take this slot and push into your available slots array.
- When you have completed day one, move on to day 2 etc. Return when you have an array of each day's slots.

**Comment by phmngocnghia** [comment]
@willmcvay Currently, the web-component config requires input appId and reapit customer for /GET /PUT/ PATCH. What appId value should I use for appointment planner to access web-component config?

**Comment by phmngocnghia** [comment]
Hi @Will McVay Currently, on web-component local server, we are using `DXX` as default `reapit-customer` header value. I have tried to query offices using this value, and got error: “The request could not be fulfilled as the reapit customer specified by the provided credentials does not have the application installed.“. When I change the value to `SBOX` which is used by the development marketplace account (wmcvay), It works as expected. Should I change the value to `SBOX` (It defined in a constant file located at /packages/web-components/src/common/utils/constants.ts, or is there something wrong with `DXX` reapit-customer?

**Comment by will** [comment]
not sure, but i cant really go into the office because of covid so that
might by why the request can't be filled?
