### ISSUE TITLE
Edit apps without approval in sandbox mode

### ISSUE THREAD

**Issue by iWader** [reapit/foundations#1242]
**Is your feature request related to a problem? Please describe.**

Currently when you need to edit your app (e.g add a new scope) you have to wait for approval before this actually works. This is a bit frustrating when you're developing apps and just want to try new endpoints, etc.

**Describe the solution you'd like**

It would be great if we could have sandbox versions of our apps which don't require approval when permissions are edited, but also don't affect production versions.

**Comment by cbryanreapit** [comment]
Revisions that are submitted for unlisted applications no longer require approval from the Foundations team (unless the revision changes the 'is listed' state of the application). 

This change is live now.
