### ISSUE TITLE
I should be able to render a "Log in with Reapit" button on my site

### ISSUE THREAD

**Issue by willmcvay** [reapit/foundations#1256]
**Background context or User story:**

_As a developer working with Reapit, I want to be able to use Reapit Connect to log in to my own site. This should be with the addition of a single script tag to the page that will render a "Log in with Reapit" button_

**Specification or Acceptance Criteria:**

- The component should take 3 params in the component constructor; clientId (the Reapit Connect ClientId), redirectUri (the OAuth return Url), and containerId (the target for the button, a valid id for an HTML element).
- Button should under the hood be an anchor tag with href in the format: `https://dev.connect.reapit.cloud/login?response_type=code&client_id=<<clientId>>&redirect_uri=<<redirectUri>>`
- Should render on the demo site and be distributed via our CDN as per all web components
- Should NOT have a CSS file, CSS should be inlined
- Button should be an SVG - switching out one SVG for another on hover - see assets below
- Darker blue is the default, lighter blue is the hover state
- Button should be the same height as a standard Reapit Button see: https://elements.reapit.cloud/?path=/story/button--info
- Width auto to scale the SVG with the height

**Suggested solution:**

- Suggest very strongly we use Svelte and Web Components for this as all the scripts to build, minify, distribute to the CDN, NPM and render on the demo site exist already

[reapit-login-buttons.zip](https://github.com/reapit/foundations/files/4628077/reapit-login-buttons.zip)

**Comment by willmcvay** [comment]
When I tried to verify this on a regular index.html page, the script threw a 403 error.

To replicate;

- Create an index.html and load in your browser eg

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <div id="login-reapit-component"></div>
    <script src="https://web-components.reapit.cloud/login-with-reapit.js"></script>
    <script>
      LoginReapitComponent &&
        new LoginReapitComponent({
          clientId: 'clientId',
          redirectUri: 'redirectUri',
          containerId: '#login-with-reapit-widget',
        })
    </script>
  </body>
</html>
```

- Refresh the index.html - you will see this error

<img width="614" alt="Screenshot 2020-05-29 at 11 56 57" src="https://user-images.githubusercontent.com/4630495/83253131-5f12d680-a1a4-11ea-98c3-98c175296170.png">

**Comment by willmcvay** [comment]
@trankhacvy @HollyJoyPhillips So the good news is the button works correctly, redirects to the app, tested etc. There is one small issue, looks like the text and image are not vertically centered. This could be an issue with the SVG itself - might be needs cropping so the content is vertically aligned, or could be a couple of CSS lines need tweaking.

<img width="657" alt="Screenshot 2020-06-01 at 11 50 42" src="https://user-images.githubusercontent.com/4630495/83402354-81a02c00-a3fe-11ea-87ae-089f513ffe64.png">

**Comment by ktre2017** [comment]
Hi,

I am trying to use "Log in with Reapit" button and when I run it, I could see Login button as expected but when I click I am getting error as "https://connect.reapit.cloud/error?error=redirect_mismatch&client_id=1gunpvl3ftfccn62vj9tnrsai8". I think I have configured redirect url correctly. 

My test Index.html code is as follows. Can you please advise why I am getting this error and how to fix it?

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Reapit Login test</title>
  </head>
  <body>
<div id="reapit-connect-component"></div>
<script src="https://web-components.prod.paas.reapit.cloud/reapit-connect-component.js"></script>
<script>

  const connectHasSessionCallback = (reapitConnectBrowserSession) => {
    reapitConnectBrowserSession.connectSession().then(session => {
      console.log('Session is', session)
      fetch('https://platform.reapit.cloud/appointments', {
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${session.accessToken}`,
          'api-version': '2020-01-31'
        }
      })
      .then(res => res.json())
      .then(appointments => console.log('Appointmemts are', appointments))
    })
  }

  ReapitConnectComponent && new ReapitConnectComponent({
    connectClientId: '1gunpvl3ftfccn62vj9tnrsai8',
    connectUserPoolId: 'eu-west-2_eQ7dreNzJ',
    connectOAuthUrl: 'https://connect.reapit.cloud',
    connectLoginRedirectPath: 'http://localhost:8080',
    connectLogoutRedirectPath: 'http://localhost:8080/login',
    connectContainerId: '#reapit-connect-component',
    connectHasSessionCallback
  })
</script>
  </body>
</html>
