### ISSUE TITLE
Improve visibility of the OpenAPI specification document

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#1294]
The interactive API explorer provides a link for developers to be able to obtain the OpenAPI/Swagger specification document. 

Presently, it is badged as "https://dev.platform.reapit.cloud/docs" but we've received feedback that it isn't particularly clear what that link provides.

![image](https://user-images.githubusercontent.com/34191069/82321971-a7c0d780-99cd-11ea-9b93-2b15bc586c66.png)

Ideally, this link would read "OpenAPI Specification".

**Comment by willmcvay** [comment]
We don't control the markup of this link so we will need to alter the text content dynamically.

**Comment by vuhuucuong** [comment]
Verified on dev
![image](https://user-images.githubusercontent.com/26746668/86099054-25a1f380-bae1-11ea-8c60-89f483dab52e.png)
