### ISSUE TITLE
Architect automatic retry mechanism with exponential backoff for webhook transmission failures

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#1299]
If our service attempted to POST a payload to a developer configured endpoint and for whatever reason that request failed, we should provide the ability to automatically retry that transmission.

**Specification**
- Review existing infrastructure and other platform webhook implementations
- Create architectural plan to provide this functionality
- Present to team
- Outcome is to create implementation ticket(s)

**Comment by kitoban** [comment]
Any news on progress with this issue?

**Comment by RWilcox-Reapit** [comment]
Moving to In-Review. Document created around the best approach, awaiting discussion to present this to the team and tickets will follow once approved.
