### ISSUE TITLE
Update to Demo Site Search Widget

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#1316]
Summary: UI updates required to the styling of the search & advanced search 

- Reduce the font size of the For Sale/To Rent and Advance Search so they all fit on the same line. Currently ‘Advanced Search’ is misaligned 
 
![image](https://user-images.githubusercontent.com/52408607/82639314-63694d80-9c00-11ea-913d-aa1ad6a689ce.png)

See example from variant B 
 
![image](https://user-images.githubusercontent.com/52408607/82639323-66fcd480-9c00-11ea-9695-dfaee635e9e9.png)

- Advanced Search (and icon) should be the same colour as the For Sale/To Rent
- The font colour for the advanced search options should also the be the same colour and font size 16px: 
![image](https://user-images.githubusercontent.com/52408607/82639336-6bc18880-9c00-11ea-9dcd-ead79c63e0ec.png)

- Book a valuation button should be the same colour according to each theme, so should have the same styling as the 'Search Properties' and when you hover over should reflect the colour of the theme. See examples below: 
For variant A 
 
![image](https://user-images.githubusercontent.com/52408607/82639347-6feda600-9c00-11ea-86fb-a860c85bcd8a.png)

For variant B
![image](https://user-images.githubusercontent.com/52408607/82639353-7419c380-9c00-11ea-8ac9-80fca1bda6a0.png)

**Comment by HollyJoyPhillips** [comment]
Hi @phmngocnghia Thanks for the updates. Just a couple of things:

The bullet point colour has turned blue on variant A? 

![image](https://user-images.githubusercontent.com/52408607/84068466-e4766200-a9c0-11ea-99d5-1d4b883e812c.png)

Can you please reduce the size of 'For Sale', 'To Rent' & 'Advanced Search'. To Rent & Advanced Search are too close together, probably 14px: 

![image](https://user-images.githubusercontent.com/52408607/84068619-28696700-a9c1-11ea-984a-addffeebf677.png)

**Comment by phmngocnghia** [comment]
@HollyJoyPhillips It's browser native style for radio button, we haven't styled it in the past... Would you like me to update it's color to match the screenshot?

**Comment by HollyJoyPhillips** [comment]
@phmngocnghia Yes please, it was grey previously: 
![image](https://user-images.githubusercontent.com/52408607/84124305-f42e8e80-aa32-11ea-9ddf-06d9028b801a.png)
