### ISSUE TITLE
As an Admin Developer, I want to be able to disable/enable developers in my organisation

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#1346]
**Summary:** A developer who is an ‘Admin’ should have the ability to disable/enable members within their organisation 

**Dependent on ticket**: https://github.com/reapit/foundations/issues/1342

**Task:** To add a disable/enable link on the ‘Organisation’ page for ‘Users’ of an organisation 
- Should only apply to the users (not the admin) 
- Location – last column (see mockup) 

![image](https://user-images.githubusercontent.com/52408607/82892716-def03500-9f47-11ea-8c91-18039cf907c2.png)

- When clicked should populate modal
- Modal Header: Disable Member? 
- Sub text: Are you sure you want to disable the account for member ‘Name of Developer’? 
Change text if developer is already disabled to ‘Are you sure you want to enable….’ 
- Buttons: Cancel and Continue. 
- Continue should set isInactive Boolean /developers/{id} (same as we do in the Admin Portal https://dev.marketplace.reapit.cloud/admin/dev-management) 

![image](https://user-images.githubusercontent.com/52408607/82892733-e9123380-9f47-11ea-98bb-b0d262cb2244.png)

**Comment by trankhacvy** [comment]
Hi @HollyJoyPhillips, on admin portal, I see a success popup like this below image. Do we also need to add that pop to this ticket ?

<img width="940" alt="Screen Shot 2020-06-24 at 14 03 17" src="https://user-images.githubusercontent.com/8068926/85513400-2cce8a80-b625-11ea-9f23-5296576952a9.png">

**Comment by HollyJoyPhillips** [comment]
@trankhacvy, yes please :)

**Comment by trankhacvy** [comment]
Verifed on dev

<img width="1439" alt="Screen Shot 2020-06-24 at 16 14 28" src="https://user-images.githubusercontent.com/8068926/85528257-dddd2100-b635-11ea-843e-1ecdf5d29b6a.png">

<img width="1440" alt="Screen Shot 2020-06-24 at 16 14 38" src="https://user-images.githubusercontent.com/8068926/85528270-e170a800-b635-11ea-9571-8978b61ace32.png">
