### ISSUE TITLE
As an Admin Developer, I want to be able to access and amend our billing information 

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#1349]
**Summary:** An Admin Developer should have access to the ‘Billing’ tab in ‘Settings’ with the ability to provide account information and complete and sign (by adobe sign) a direct debit which we should record. This ticket is to create the UI for the ‘Billing’ tab

**Relates to ticket:** https://github.com/reapit/foundations/issues/1340
**Important:** If env is prod - tab should be hidden 

**Task:** To create the UI for the ‘Billing’ tab under ‘Settings’ 
- Heading: Accounts Information 
- Fields:
Accounts Email – Subtext: This email will be used by our Accounts Department to send any account related correspondence
Accounts Telephone – Subtext: If you have a specific telephone number for your accounts department, please enter here
Accounts Contact – Subtext: If you have a key contact in your Accounts Department, please enter here
- Reapit Reference – Subtext: If you have an existing account with Reapit you will be able to find your Reapit reference on previous correspondence
- Radio select – Yes or No 
If yes – Provide additional text box with placeholder text ‘Please enter reference’ 
If no – disable the box 
- Do you have a Direct Debit setup already? - Sub text: If you have an existing Direct Debit setup, please select Yes below. If not, please select No and complete a Direct Debit form below: 
Radio Select - Yes, No & Other (cheque/bacs/credit)

If Yes - do not display the 'Direct Debit' section below
If No - display the 'Direct Debit' section below'
If 'Other' do not display the 'Direct Debit' section below 
- Button : Save (action TBC)

Additional: 
If 'No' is selected from the Reapit Reference section and 'Yes' is selected from the 'Do you have a Direct Debit Setup Already section, should populate modal: 

Email address should be: creditcontrol@reapit.com 
![image](https://user-images.githubusercontent.com/52408607/83390060-18fa8480-a3e9-11ea-9efd-36368dd97c06.png)

- **Second Section Heading** – Direct Debit
- Subtext: Before you can make any of your applications available in the Marketplace, you will first need to complete and sign a Direct Debit.
- Button ‘Setup Direct Debit’ – Action TBC 

See mockup: 
![YesRefYesDD](https://user-images.githubusercontent.com/52408607/83390127-37f91680-a3e9-11ea-971a-91da2dfddfeb.png)

**Comment by nphivu414** [comment]
Hi @HollyJoyPhillips ,
There are 2 points that I'm not clear about this ticket.
1. It seems like the 'Direct Debit' section is missing from the mockup. I got the information of the heading, subtext, button of this section but I still need to know how it's UI looks like
2.  If 'No' is selected from the Reapit Reference section and 'Yes' is selected from the 'Do you have a Direct Debit Setup Already section, the additional modal will be populated. But what if after that users select 'Yes' from the Reapit Reference section and then select 'No', should the modal be populated again?

**Comment by nphivu414** [comment]
I put this ticket to backlog because @HollyJoyPhillips needs to finalize the Direct Debit section

**Comment by nphivu414** [comment]
Hi @HollyJoyPhillips ,
I know the Direct Debit section still hasn't been finalized yet but you can test the UI of other sections in this form. Please let me know when you have any update on the Direct Debit section.
Thank you
