### ISSUE TITLE
Update the 'Confirm Uninstall' modal 

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#1354]
**Summary:** The 'Confirm Uninstall' modal needs to be updated to keep with the same type/font as our other modals: 

**Location:** Developer Portal > App > Installations > click on uninstall

Current modal: 
![image](https://user-images.githubusercontent.com/52408607/82944579-6020e980-9f93-11ea-9430-44c288b63667.png)

Update: 
![image](https://user-images.githubusercontent.com/52408607/82944679-8a72a700-9f93-11ea-8300-3ec1259f5b5d.png)

**Comment by trankhacvy** [comment]
Verified on dev env

<img width="1434" alt="Screen Shot 2020-06-01 at 20 47 07" src="https://user-images.githubusercontent.com/8068926/83415369-2c3d3c80-a449-11ea-947b-72d34c6196f0.png">

**Comment by trankhacvy** [comment]
Verified on dev environment.

<img width="648" alt="Screen Shot 2020-06-02 at 16 09 48" src="https://user-images.githubusercontent.com/8068926/83502303-8e4e7e00-a4eb-11ea-865b-3063e2dc0b9d.png">
