### ISSUE TITLE
As an Admin Developer, I want to be able to access and amend our billing information 

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#1355]
**Summary:** An Admin Developer should have access to the ‘Billing’ tab in ‘Settings’ with the ability to provide account information and complete and sign (by adobe sign) a direct debit which we should record. This ticket is to create the UI for the ‘Billing’ tab

**Relates to ticket:** https://github.com/reapit/foundations/issues/1340

**Task:** To create the UI for the ‘Billing’ tab under ‘Settings’ 

- **First Heading**: Accounts Information 

- **Fields**
**Accounts Email** – Subtext: This email will be used by our Accounts Department to send any account related correspondence
Placeholder text: Please enter email address 
**Accounts Telephone** – Subtext: If you have a specific telephone number for your accounts department, please enter here
Placeholder text: Please enter telephone number
**Accounts Contact** – Subtext: If you have a key contact in your Accounts Department, please enter here
Placeholder text: Please enter contact 
- **Reapit Reference** – Subtext: If you have an existing account with Reapit you will be able to find your Reapit reference on previous correspondence
- Radio select – Yes or No 
If yes – Provide additional text box with placeholder text ‘Please enter reference’ 
- If no – TBC 
- Button: Save (endpoint TBC)

- **Second Section Heading** – Direct Debit
Subtext: Before you can make any of your applications available in the Marketplace, you will first need to complete and sign a Direct Debit.
- Button ‘Setup Direct Debit’ – Action TBC 

See mockup: 
![Accounts New1](https://user-images.githubusercontent.com/52408607/82945478-e7229180-9f94-11ea-8e40-b01a5ef42535.png)

**Comment by tanphamhaiduong** [comment]
Moving this one to QA. Because it duplicated with issue #1349
