### ISSUE TITLE
The Web Components Config API should store config by appId

### ISSUE THREAD

**Issue by willmcvay** [reapit/foundations#1369]
**Background context or User story:**

See: #1033 and #1289 

_Currently the web components config API stores config by customerId as it's primary key. This works fine however, it should be expanded so that it can have a secondary key that fetches by an appId - this will allow a customer to have multiple components and a config per app_

**Specification or Acceptance Criteria:**

- Should allow GET, POST, PUT, DELETE endpoints to access config for only the app they need to perform a CRUD operation on.
- Should preserve the existing config, just adding an additional `appId` layer to the document eg

```
{
  someCustomerId: {
    someAppId: {
      config: {}
    },
    anotherAppId: {
      config: {}
    }
  }
}
```

**Comment by phmngocnghia** [comment]
@willmcvay: you may want to add additonal secondary index key to dynamodb if performance is considered in the future
