### ISSUE TITLE
Create an itemised monthly spreadsheet for the Admin portal 

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#1382]
**Summary:** 
We will need to send the Reapit Accounts Department an itemised spreadsheet every month for each developer, to raise associated invoices. Going forward this will be automated, but this ticket is to log the required fields. 

This is dependent on the additional fields the ‘Organisation’ page will handle. The fields that are required for the spreadsheet: 

- Company Name
- Building Name
- Building No
- Line 1
- Line 2
- Line 3
- Line 4
- Postcode
- Country
- Accounts Contact	
- Account Email	
- Account Telephone	
- VAT	
- Reg	
- NI
- Reapit Reference	
- Charging Period
- Line Item Description (include all high level items e.g. API Calls, Application Listing
- Charge (Before VAT)

See example spreadsheet: 
[Example Spreadsheet.xlsx](https://github.com/reapit/foundations/files/4812519/Example.Spreadsheet.xlsx)

*** Implementation ***
- Add `GET /developers/costs/{month}`
- `month` from route should be in format: `yyyy-MM`
- API responsible for returning all the costs for all developers (hence the slightly ususual URL format, this is still Restful)
- Upon receiving request, identity all developers with a status that may have charges against them (>approved)
- Communicate with billing API to get breakdown of charges per developer
- Amalgamate developer information and the associated billing details into a result object and repeat
- Use the list of result objects to populate a CSV in the format attached
- The results listing is important step - this isn't likely to remain a CSV for long, we should prepare for that by building in a re-usable way

**Comment by cbryanreapit** [comment]
We don't yet capture all of this information, blocked until we have completed relevant developer organisation tickers.
