### ISSUE TITLE
Large number of React Invalid Warnings in development Marketplace

### ISSUE THREAD

**Issue by willmcvay** [reapit/foundations#1391]
**Background context or User story:**

_When loading the marketplace / dev portal in development, clicking around throws a large number of invalid React warnings of various types. This should be cleaned up see screenshot_

<img width="1133" alt="Screenshot 2020-05-28 at 07 34 31" src="https://user-images.githubusercontent.com/4630495/83107176-b128fe80-a0b5-11ea-98c8-ff3b394d38fc.png">

**Specification or Acceptance Criteria:**

- There should not be invalid React warnings in the console

**Comment by trankhacvy** [comment]
Verified on dev.
