### ISSUE TITLE
Ensure apps have correct configs

### ISSUE THREAD

**Issue by willmcvay** [reapit/foundations#1409]
**Background context or User story:**

_See #1395 there is some confusion with how apps should be submitted to marketplace. They should not share clientIds_

**Specification or Acceptance Criteria:**

- Dev and local should have one client id, the app should be submitted as "Dev <<app name>>"
- Prod should have it's own client id the app should be submitted as "<<App name>>"
- When submitting, redirect uris and logout uris should point to correct dev, prod and localhost routes for default and login routes respectively.
- Client ids should be added to the correct dev, prod and local configs in parameter store
- Apps should be re-deployed to dev and prod so we are sure correct config is deployed.

**Comment by vuhuucuong** [comment]
Hi @willmcvay , I have a few questions to confirm a few things:
- So now we will clone each app (Geo-diary, all, lifetime-legal), and each app will have two variants, prod is `listed`, dev is `Not listed`(as in the doc). For example:
  - `Dev <Geo-diary>` (listed) and `<Geo-diary>` (Not listed)
- How about `web-components` apps (such as `Search-widget`)? Do we also need to clone them too?
- And now the differences between DEV and PROD app are just `clientId`, `redirectURIs`, `logoutURIs`. Is there anything else?

**Comment by willmcvay** [comment]
@vuhuucuong Not quite, the prod ones are listed, not the dev ones. To be honest, the isListed value is the least important thing because when we have a prod infra, the prod apps will move to a different AWS account.

Web components (and other apps, eg SMB, Site Builder), that only have a dev infra, obviously only have a dev app and dev client id. 

Yes, the only practical difference at this stage is they have different clientIds and redirect / logout uris but, this will change when we have the prod infra as they will have different APIs, keys and other config. They will also be hosted in a different AWS account.
