### ISSUE TITLE
Developer Portal Browser Testing

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#1421]
**Summary:** Please see below the results of testing the Developers Portal in IE11, Edge & Chrome

**Edge**
‘Back to Apps’ button is stacked above the ‘Submit App’ button when editing an app 
 
![image](https://user-images.githubusercontent.com/52408607/83182237-f84ada00-a11d-11ea-99c2-7de0dd71a4af.png)

**IE**
The call to actions on are on the left when on the Submit and Edit app forms
Submitting and App  
![image](https://user-images.githubusercontent.com/52408607/83182258-00a31500-a11e-11ea-90b0-cb5859d253e1.png)

Editing an App: 
![image](https://user-images.githubusercontent.com/52408607/83182739-b706fa00-a11e-11ea-843c-6469f14b482d.png)

**Edge/IE/Chrome**
Cost Explorer page is failing to load: 
 
![image](https://user-images.githubusercontent.com/52408607/83182367-2a5c3c00-a11e-11ea-96e2-43966f71baf3.png)

**Edge/IE/Chrome**
Background and style issues on API (Swagger) 
![image](https://user-images.githubusercontent.com/52408607/83182389-30eab380-a11e-11ea-8bb1-0b0ea609a218.png)

**Edge/IE**
The page is not fixed and shows white space when I scroll down :
 
![image](https://user-images.githubusercontent.com/52408607/83182426-3c3ddf00-a11e-11ea-9193-77fc92a8fa5e.png)

**IE**
Modal is not fixed when scrolling up: 
 
![image](https://user-images.githubusercontent.com/52408607/83182442-44961a00-a11e-11ea-863d-ca00c6b197de.png)

**Edge/IE** 
Page is not fixed when scrolling up: 
 
![image](https://user-images.githubusercontent.com/52408607/83182459-4bbd2800-a11e-11ea-96af-a3ece01d3c22.png)

**Edge** 
Drop down menu visually looks incorrect when selecting a webhook: 
 
![image](https://user-images.githubusercontent.com/52408607/83182554-76a77c00-a11e-11ea-913d-2d9ef6a3944c.png)

**IE**
Same as above: 
![image](https://user-images.githubusercontent.com/52408607/83182564-7b6c3000-a11e-11ea-957c-afa77b2c7994.png)

**IE**
The ‘Docs’ fail to load to correctly: 
 
![image](https://user-images.githubusercontent.com/52408607/83182580-8030e400-a11e-11ea-8688-1553ae122127.png)

**Edge**
The ‘Docs’ fail to load at all: 
 
![image](https://user-images.githubusercontent.com/52408607/83182609-858e2e80-a11e-11ea-957e-7609006077dc.png)

**Comment by trankhacvy** [comment]
@HollyJoyPhillips @willmcvay 

- Which Edge version do you use to test ? I use Edge 83 run on Window 10 but I can't replicate your bugs.
- About select box in Edge and IE, for now we use native select box (select, option tag) so it is default style of select box in Edge and IE, the style isn't same with chome. If we want the same style in all browers we need rewrite the select box component .

<img width="1437" alt="edge_latest" src="https://user-images.githubusercontent.com/8068926/83603077-fc537d80-a59d-11ea-9394-5dffdaa49f54.png">
<img width="1438" alt="Screen Shot 2020-06-03 at 11 20 44" src="https://user-images.githubusercontent.com/8068926/83603090-01183180-a59e-11ea-8468-04b0668bc033.png">
<img width="1440" alt="Screen Shot 2020-06-03 at 11 21 27" src="https://user-images.githubusercontent.com/8068926/83603107-04132200-a59e-11ea-8223-5f0d172d42e0.png">

**Comment by HollyJoyPhillips** [comment]
Hi @trankhacvy, thanks for the updates. Couple of points. 

The 'Cost Explorer' is still not loading when using Edge (Version 83.0.478.45): 
![image](https://user-images.githubusercontent.com/52408607/84066955-952f3200-a9be-11ea-81f3-3edc4dae9de7.png)

Also, can you change the wording for the message in IE when accessing the docs from: 

Unsupported Brower
marketplace probably won't work great in Internet Explorer 11. we generally only support the recent versions ofmajor browers like Chrome, Firefox, Safari and Edge

To 

Unsupported Browser - Unfortunately as Internet Explorer 11 is no longer supported, we are unable to display the documentation, please login to the Developer Portal using either Chrome, Firefox, Safari or Edge

Also use the info toast that remains on the screen 'https://elements.reapit.cloud/?path=/story/toastmessage--default' 

![image](https://user-images.githubusercontent.com/52408607/84067685-af1d4480-a9bf-11ea-957f-81435d125a5b.png)

**Comment by trankhacvy** [comment]
Hi @HollyJoyPhillips, I have tried to open 'Cost Explorer'  page on Microsoft Edge (Version 83.0.478.45, window10) and it work fine, no error display. It's weird. Could you please help me to delete cache and re-test it again ? If you still get this error,  could you please right click on screen and click on Inspect menu (or press Ctrl + Shirt + I ) to open developer tool. On developer tool, please click on Console tab and send me the screenshot of console tab. 
It's very helpful if you can give me the record video when you test it.

**Comment by HollyJoyPhillips** [comment]
@trankhacvy Cleared cache again and it's now displaying, thank you.

**Comment by HollyJoyPhillips** [comment]
Hi @trankhacvy Thanks for adding the toast. Can we stack the message on 2 lines as on my screen I can't see the full message: 
![image](https://user-images.githubusercontent.com/52408607/84242077-3cfc4b00-aaf8-11ea-8eb5-0a16d80deee5.png)

**Comment by HollyJoyPhillips** [comment]
Also @trankhacvy just noticed that the 'Logout' button is missing on the settings button on IE: 
![image](https://user-images.githubusercontent.com/52408607/84242367-ab410d80-aaf8-11ea-8a94-5d5468bf56ea.png)
