### ISSUE TITLE
Client Portal Browser Testing

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#1422]
**Summary:** Please see below the results of testing the Client Portal in IE11, Edge & Chrome

**IE**
Browse Apps – Pagination is at the top of the page
![image](https://user-images.githubusercontent.com/52408607/83183040-24b32600-a11f-11ea-86b2-2399d073be47.png)

**Edge/IE/Chrome**
Browse Apps Filtering style incorrect - Already raised as a ticket: https://github.com/reapit/foundations/issues/1371

**Edge/IE/Chrome**
Installed Apps – tile spacing is inconsistent   
![image](https://user-images.githubusercontent.com/52408607/83183076-3268ab80-a11f-11ea-8a6b-043ed0074557.png)

**Edge/IE/Chrome**
Browse Apps – tile height for the LeadPro is incorrect: 
 
![image](https://user-images.githubusercontent.com/52408607/83183097-37c5f600-a11f-11ea-9843-622bde2110eb.png)

**Comment by vuhuucuong** [comment]
hi @HollyJoyPhillips, I was able to replicate all of them but not this one 
<img width="647" alt="Screen Shot 2020-06-01 at 14 27 02" src="https://user-images.githubusercontent.com/26746668/83385762-ffbafd80-a413-11ea-91fd-f87f08d2fa24.png">
It was fine from my side, IE 11. Could you help me to check it again? And could you check the exact IE 11 version you're currently using?
Thanks
<img width="1435" alt="Screen Shot 2020-06-01 at 14 30 21" src="https://user-images.githubusercontent.com/26746668/83386098-a1dae580-a414-11ea-8b96-178c6e683e14.png">
My IE 11 version
<img width="362" alt="Screen Shot 2020-06-01 at 14 32 42" src="https://user-images.githubusercontent.com/26746668/83386201-ccc53980-a414-11ea-9e95-774b953848e5.png">

**Comment by HollyJoyPhillips** [comment]
Hi @vuhuucuong, looks like i'm using an older version but I am unable to update (laptop restrictions). Let me test on another PC with the latest version to confirm :)

**Comment by HollyJoyPhillips** [comment]
@vuhuucuong Really odd but I can't access the client portal on IE at all now. I've tested on my laptop (cleared cache) and also on another PC with the latest version also used InPrivate browsing

![image](https://user-images.githubusercontent.com/52408607/83540160-d5d70900-a4ef-11ea-8692-ce64c4469909.png)

**Comment by vuhuucuong** [comment]
Hi @HollyJoyPhillips , I've been debugging and the error came from other PR since my PR is just editing some small CSS, I'm working with the team to fix it
