### ISSUE TITLE
AML Browser Testing (including mobile) 

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#1425]
**Summary:** Please see below the results of testing the AML app on mobile and using IE11, Edge and Chrome: 

**Edge/IE**
The page (search/results/profile) is not fixed so when I scroll down, a white space appears the bottom & top: 
![image](https://user-images.githubusercontent.com/52408607/83184399-51683d00-a121-11ea-9ca0-fa8f7c2c2fe4.png)

**Edge**
No spacing under the ‘Print Report’ button on the ‘Report’ modal: 
 
![image](https://user-images.githubusercontent.com/52408607/83184411-575e1e00-a121-11ea-8642-bb8d2245d362.png)

**Chrome**
View ‘Report’ - the 'Status' is not on one line: 
 
![image](https://user-images.githubusercontent.com/52408607/83184433-5e852c00-a121-11ea-86ab-38e486b4c540.png)

### AML Mobile: 

**Edge/Chrome** 
The table is splitting names/address/status onto another line. It should not split a word up to fit as the table is scrollable. For example, Phillips is one word but it is moving the ‘ps’ onto another line. Similarly, ‘Pending’ is split into ‘Pendi’ and ‘ng’. Should only move to another line if it is a full word. 
 
![image](https://user-images.githubusercontent.com/52408607/83184539-807eae80-a121-11ea-953a-5c0d601c8b1c.png)

Similarly, the 'View' report modal is displaying the status over 2 lines: 
 
![image](https://user-images.githubusercontent.com/52408607/83184552-85dbf900-a121-11ea-86b3-cf0db36f091c.png)

Update Status – the CTA’s are stacked but not aligned : 
 
![image](https://user-images.githubusercontent.com/52408607/83184572-8d9b9d80-a121-11ea-9c5d-a87ec2c37ae6.png)

**Comment by vuhuucuong** [comment]
Hi @HollyJoyPhillips , all bugs have been fixed but not this:
<img width="638" alt="Screen Shot 2020-06-03 at 16 25 03" src="https://user-images.githubusercontent.com/26746668/83619956-d38bb200-a5b6-11ea-93af-087dede871b2.png">
Because it only happens in old Edge, but not new Edge (chromium Edge) so I think it'll be fine. We can fix that but it will potentially break other browsers, so I think we can leave it like that

**Comment by HollyJoyPhillips** [comment]
@vuhuucuong That's fine, i've just testing on the latest browser and it looks good.

**Comment by HollyJoyPhillips** [comment]
Hi @vuhuucuong Just a small tweak: 

The 'Update Status' modal buttons require scrolling, can we stack them instead? 
![UpdateStatusMobile](https://user-images.githubusercontent.com/52408607/83749690-fcb24e00-a65b-11ea-8b9f-828ed0ef1884.jpg)

![UpdateStatus](https://user-images.githubusercontent.com/52408607/83749654-edcb9b80-a65b-11ea-9cb1-1f6e5ce3834a.jpg)

**Comment by vuhuucuong** [comment]
Hi @HollyJoyPhillips , It's been fixed now :)

**Comment by HollyJoyPhillips** [comment]
@vuhuucuong Looks much better, thank you!
