### ISSUE TITLE
Delete operations trigger unexpected behaviour in the conveyancing broker

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#1452]
![image](https://user-images.githubusercontent.com/34191069/83283508-3d7d1380-a1d3-11ea-9c0b-3bf7d2e488ea.png)

Delete upward/download using id 'RPT200023' triggers above log entry and an error response.

**Comment by plittlewood-rpt** [comment]
PR 2003 opened for update to metadata client package. Assuming this is OK, we just need to run a package update in the broker project which should resolve this issue

**Comment by plittlewood-rpt** [comment]
PR 2007 opened to update package in broker project.

**Comment by plittlewood-rpt** [comment]
Retested and confirmed up/down chain id's can be deleted using the appropriate methods/routes
