### ISSUE TITLE
Create modal to display App contact details

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#1463]
**Summary:** A modal should populate the app contact details when a client clicks on ‘Need Help?’ when browsing/managing app (standalone) 

**Task:** To create a modal that shows the app contact details  when a client clicks on ‘Need Help?’ from the ‘Contact Developer’ section. 

- Modal Title: Contact Details
Company: ‘developer’
Telephone Number: ‘telephone’
Support Email: ‘supportEmail
Website:  ‘homePage’

See mock up: 
![ContactDetails](https://user-images.githubusercontent.com/52408607/83385800-c5d10380-a3e1-11ea-8df8-7f12159e555e.png)

![image](https://user-images.githubusercontent.com/52408607/83385811-ca95b780-a3e1-11ea-8d69-35af821e8198.png)

**Comment by trankhacvy** [comment]
Verified on dev.

<img width="1379" alt="Screen Shot 2020-06-04 at 14 08 44" src="https://user-images.githubusercontent.com/8068926/83725932-f7113400-a66c-11ea-9220-db4034c07446.png">
