### ISSUE TITLE
[Submit App] Should not allow to upload file is not image (.doc, .txt, .xslx)

### ISSUE THREAD

**Issue by tanphamhaiduong** [reapit/foundations#1497]
**Describe the bug**
Should not allow to upload file is not image (.doc, .txt, .xslx)

**To Reproduce**
1. Login with role developer
2. Go to "Submit App"
3. Upload file which is not image (.doc, .txt, .xslx)

**Expected behavior**
Should not allow upload file with types: .doc, .txt, .xslx
**Screenshots**
![image](https://user-images.githubusercontent.com/22660833/83515036-e2169280-a4fe-11ea-81f7-5799cf0858c9.png)

**Comment by ant066** [comment]
After discussing with @HollyJoyPhillips, We will raise a separate ticket to handle notifying the user if the incorrect format has been used. Move this ticket to DONE.
