### ISSUE TITLE
[Login][Developer role] Login layout breaking

### ISSUE THREAD

**Issue by tanphamhaiduong** [reapit/foundations#1507]
**Describe the bug**
Login layout breaking

**To Reproduce**
1. Go to https://dev.marketplace.reapit.cloud/developer/login

**Expected behavior**
Login layout not broken

**Screenshots**
![image](https://user-images.githubusercontent.com/22660833/83592859-80e5d200-a585-11ea-91b2-41562b055b1f.png)

**Comment by nphivu414** [comment]
Hi @tanphamhaiduong ,
This issue was caused by caching issues. I've just invalidated cloudfront cache for marketplace dev and it's gone.
Please check my screenshot:
![image](https://user-images.githubusercontent.com/22409039/83609284-42adda00-a5a8-11ea-8e3e-31055a2d8543.png)
