### ISSUE TITLE
Remove params on pagination

### ISSUE THREAD

**Issue by tanphamhaiduong** [reapit/foundations#1509]
**Background context or User story:**
- Now we're using pagination by queryString instead of url Params
![image](https://user-images.githubusercontent.com/22660833/83595883-6879b580-a58d-11ea-97d4-6436fc9ae747.png)

**Specification or Acceptance Criteria:**
- Remove 
```
    case Routes.MY_APPS_PAGINATE:
      store.dispatch(myAppsRequestData(page))
      break
```

```
    case Routes.INSTALLED_APPS_PAGINATE:
      store.dispatch(installedAppsRequestData(page))
      break
```

**Suggested solution:**
- Change to use queryString

**Comment by willmcvay** [comment]
@ant066 Looked at this on dev and pagination not working on the developer apps page. Loads the correct page on refresh but using the pagination controls renders the same page each time

**Comment by ant066** [comment]
> @ant066 Looked at this on dev and pagination not working on the developer apps page. Loads the correct page on refresh but using the pagination controls renders the same page each time

Hi @willmcvay, This ticket just ask refactor on 2 routes in client portal. So I haven’t check on developer portal. But sure, I will check then updtae it tomorrow.
