### ISSUE TITLE
[Submit App] Description field is stretched when filling 78 characters

### ISSUE THREAD

**Issue by tanphamhaiduong** [reapit/foundations#1516]
**Describe the bug**
Description field of Submit App page is stretched when filling characters.
Description field of Edit App, Confirm Revision and Pending Revisions have the same issue. 

**To Reproduce**
1. Login with Developer role
2. Go to "Submit App" page
3. Input more than 77 characters into "Description" field

**Expected behavior**
Description field is not stretched and text down the line when input more than 77 characters

**Screenshots**
![image](https://user-images.githubusercontent.com/22660833/83604694-ce236d00-a5a0-11ea-91a1-56704f4c7849.png)
![image](https://user-images.githubusercontent.com/22660833/83604766-e5faf100-a5a0-11ea-9bfc-ee1b856c0621.png)

**Comment by phmngocnghia** [comment]
fixed in #1518
