### ISSUE TITLE
[Marketplace][Approvals] Data of each field must be display in the field area

### ISSUE THREAD

**Issue by tanphamhaiduong** [reapit/foundations#1520]
**Describe the bug**
Data of each field should be displayed in the field area.

**Precondition**
- Log in with an Administrator account
- Apps are pending have long data in any field

**To Reproduce**
1. Go to 'Marketplace' with Admin role
2. Click on 'Approvals'
3. Click 'View Details' of Apps is pending
4. Horizontal scroll at 'Confirm Test App For Migration Configd revision' popup

**Expected behavior**
Data displays correctly in the field area

**Screenshots**
https://recordit.co/t4v7Kyk7wA

**Device (please complete the following information for web issues):**
 - Device: Labtop 15.6 inch
 - OS: Windows 10 - ver 1903
 - Browser: Chrome

**Comment by phmngocnghia** [comment]
Fixed in https://github.com/reapit/foundations/issues/1516

**Comment by HollyJoyPhillips** [comment]
@phmngocnghia, added a long string of text to the summary and it's still requiring scrolling

![image](https://user-images.githubusercontent.com/52408607/84065768-cb6bb200-a9bc-11ea-9056-fd10cab27957.png)
