### ISSUE TITLE
[MarketPlace][Apps] Should be limiting the size of the input value in fields

### ISSUE THREAD

**Issue by tanphamhaiduong** [reapit/foundations#1526]
**Describe the bug**
Should be limiting the size of the input value in fields.

**To Reproduce**
1. Go to 'Marketplace' with Admin role
2. Click on 'Apps' on the menu
3. Enter the long value in 'App Name', 'Developer Name' and 'Company Name' fields

**Expected behavior**
Should be limiting size value of 'Name' and 'Company' fields

**Screenshots**
https://recordit.co/EHOyA5Cd5k

**Comment by ant066** [comment]
Hi @tanphamhaiduong @willmcvay, What max length should we apply to?

**Comment by tanphamhaiduong** [comment]
@ant066 I think we'll limit like database column define on backend side

**Comment by willmcvay** [comment]
@tanphamhaiduong is correct, you will have to find out the max char length for those fields. Just add a very large number of chars and save the form - the error object will tell you the max length

**Comment by ant066** [comment]
@willmcvay I tried but the API response nothing. I think we should set the limit at 256. 
<img width="548" alt="Screen Shot 2020-06-08 at 1 52 28 PM" src="https://user-images.githubusercontent.com/30467048/84000865-b593c800-a98f-11ea-9e2b-25b00d5e08b7.png">
