### ISSUE TITLE
Unable to submit private application without CustomerId

### ISSUE THREAD

**Issue by mab-dev-farnie** [reapit/foundations#1528]
**Unable to submit private application without CustomerId**

Reading the documentation for submitting an application [https://foundations-documentation.reapit.cloud/developer-portal](https://foundations-documentation.reapit.cloud/developer-portal) the text under private app reads "For the public beta we don't support surfacing the client ids you wish to restrict to since the marketplace is not live however, *if you want your app to be private, you can select "yes" and ignore the customer code list*"

When we select the "Yes" option under Private Apps, validation is informing us we need to provide a Customer Id.

**To Reproduce**
Steps to reproduce the behavior eg:
1. Go to 'https://marketplace.reapit.cloud/developer/submit-app'
2. Click on 'Yes for Private Apps'
3. Fill out the rest of the form
4. Scroll down to 'Submit App'
5. Click on 'Submit App'
6. Error reads as followed: "The following validation errors have occurred:
Private Apps: At least one Customer ID is required"

**Expected behavior**
Submitting a Private Application does not require Customer Id and validation does not kick in.

**Screenshots**
Documentation - [https://foundations-documentation.reapit.cloud/developer-portal](https://foundations-documentation.reapit.cloud/developer-portal)
![image](https://user-images.githubusercontent.com/57000662/83627295-96abc500-a58e-11ea-8ac0-84ee6699ef1e.png)

Validation Message - [https://marketplace.reapit.cloud/developer/submit-app](https://marketplace.reapit.cloud/developer/submit-app)

![image](https://user-images.githubusercontent.com/57000662/83627169-6f54f800-a58e-11ea-98b6-01a0693c4559.png)

![image](https://user-images.githubusercontent.com/57000662/83627479-e4283200-a58e-11ea-8599-43e952a09364.png)

**Device**
Windows 10 Desktop - Chrome version: 83.0.4103.61

**Comment by willmcvay** [comment]
Agree with this. Correct behaviour for the beta is that "No" should be selected by default and the field be disabled. 

Text should have the addition after `(TBC)`. "This field is disabled during the beta period. Your app will be private by default as the marketplace is not yet live. You will have the opportunity to make your app private via an edit before setting it to be "Listed" in the marketplace when we move from beta to production".

@mab-dev-farnie Thanks for flagging this, as per above your app will be private by default as there is no marketplace for it to be public within at present. You are fine to submit an app with this value set to "No" for now and will have chance to change this to "Yes" before you go live.

**Comment by mab-dev-farnie** [comment]
That's great! Thank you for picking this up so quickly!

We are now of the understanding that the marketplace is not aware of our application until we flag it as listed and await the Reapit Foundation verification process. What we have done for now is, set the private app flag to yes and put a "dummy" CustomerId in place "000".

Thank you for getting back so quickly!

**Comment by tanphamhaiduong** [comment]
verified on dev
![image](https://user-images.githubusercontent.com/22660833/84358325-2f76bc00-abf1-11ea-9f75-7c8aeec7a781.png)

**Comment by HollyJoyPhillips** [comment]
@tanphamhaiduong Could you please add the following to the text: 

This field is disabled during the beta period. Your app will be private by default as the Marketplace is not yet live. You will have the opportunity to make your app private via an edit before setting it to be "Listed" in the marketplace when we move from beta to production.

**Comment by tanphamhaiduong** [comment]
hi @HollyJoyPhillips I'll add it as below image
![image](https://user-images.githubusercontent.com/22660833/84379305-c81c3480-ac0f-11ea-8d5d-10348b4ed51c.png)

**Comment by tanphamhaiduong** [comment]
verified on dev
