### ISSUE TITLE
App Name is missing on the Delete confirmation modals

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#1554]
**Summary:** The app name is missing on the modal when you click 'Delete App'. 

**To replicate:** Open app > click 'Delete App' > observe missing app name on first modal > click 'Delete' > observe missing app name on confirmation modal

See first modal should include the App name: 
![image](https://user-images.githubusercontent.com/52408607/83723853-39b81980-a637-11ea-916a-5fff2447ec96.png)

Also missing on the confirmation modal: 
![image](https://user-images.githubusercontent.com/52408607/83723896-48063580-a637-11ea-9e9f-71a1ebad8c21.png)

**Comment by tanphamhaiduong** [comment]
Hi @HollyJoyPhillips  I cannot replicate this bug as image below
http://g.recordit.co/C1LYyGBpeE.gif

**Comment by tanphamhaiduong** [comment]
verified on dev
![image](https://user-images.githubusercontent.com/22660833/84009660-cd724880-a99d-11ea-9299-1361414a1831.png)

**Comment by tanphamhaiduong** [comment]
@willmcvay @HollyJoyPhillips seems the commit for this ticket has been overwrite by https://github.com/reapit/foundations/issues/1565. So I need to fix it again
