### ISSUE TITLE
[My Apps][Chrome] Should be adjust the notice size on the "My Apps" page

### ISSUE THREAD

**Issue by tanphamhaiduong** [reapit/foundations#1557]
**Describe the bug**
The notice overlap "Settings" function on the "My Apps" page

**To Reproduce**
1. Login with Developer role
2. Go to "My Apps" page

**Expected behavior**
The notice not overlap "Settings" function 

**Screenshots**
![image](https://user-images.githubusercontent.com/22660833/83730680-9df8ce80-a673-11ea-917a-1cfc13bf3c13.png)

**Device (please complete the following information for web issues):**
 - Device: Laptop
 - Browser: Chrome
 - Version: 83.0.4103.61

**Comment by nphivu414** [comment]
Hi @tanphamhaiduong ,
This issue has already been fixed
![image](https://user-images.githubusercontent.com/22409039/84102645-38be2800-aa3b-11ea-8b53-e33f7fcb1834.png)
