### ISSUE TITLE
Desktop testing bugs

### ISSUE THREAD

**Issue by willmcvay** [reapit/foundations#1579]
**Describe the bug**

_Bugs came out of testing on desktop app. Should be tested in desktopMode as we as web_

- The client side welcome wizard shows in desktop, this should only be rendered in web mode.
- Uninstalling an app does not show a notification as before. The action of confirming the uninstall should trigger a refresh of the page in desktop mode as before using an ACButton component
- The same is true installing an app, it does not show a dialogue or trigger a refresh in desktop
- Uninstalling an app does not trigger a page refresh so you can repeatedly try to uninstall an app that is already uninstalled.
- The back to apps button on the apps pages should re-direct back to where you came from. So if I arrived on the app page from manage apps I should return to manage apps. Currently it will return you always to the browse apps page.

**Comment by nphivu414** [comment]
Hi @willmcvay ,
I cannot reproduce the issue that doesn't trigger a page refresh after installing/uninstalling an app in desktop.
Please check my screen record:
![Untitled_ Jun 5, 2020 4_30 PM](https://user-images.githubusercontent.com/22409039/83861860-59d8fd00-a74b-11ea-8102-8ff8d0112dde.gif)

Thanks
