### ISSUE TITLE
[Submit App] Should have "*" mark for required fields

### ISSUE THREAD

**Issue by tanphamhaiduong** [reapit/foundations#1580]
**Describe the bug**
Required fields are currently missing "*" mark

**To Reproduce**
1. Login with Developer role
2. Go to "Submit App" page

**Expected behavior**
Should have "*" mark for required fields

**Screenshots**
![image](https://user-images.githubusercontent.com/22660833/83853131-06f94880-a73f-11ea-88ad-0800cea510a6.png)

**Comment by tanphamhaiduong** [comment]
verifed on dev
http://g.recordit.co/vGzvj0Rh2l.gif

**Comment by HollyJoyPhillips** [comment]
Hi @tanphamhaiduong I see you have added 'Category' (categoryId) as a required field, it hasn't been a required field previously, any reason it's now been added?

**Comment by tanphamhaiduong** [comment]
@HollyJoyPhillips ok so let me remove required for category fields

**Comment by HollyJoyPhillips** [comment]
@tanphamhaiduong Thanks. Also, the telephone number field should support spaces (it does on the edit form not just submit): 
![image](https://user-images.githubusercontent.com/52408607/84370725-95068080-abd0-11ea-89cd-15e0b8fd4ea3.png)

**Comment by tanphamhaiduong** [comment]
hi @HollyJoyPhillips I removed it could you help me to check again 
![image](https://user-images.githubusercontent.com/22660833/84378894-14b34000-ac0f-11ea-9086-69c19c05c416.png)
