### ISSUE TITLE
[Submit App] Should be fixed list of "Integration Types" field

### ISSUE THREAD

**Issue by tanphamhaiduong** [reapit/foundations#1585]
**Describe the bug**
List of "Integration Types" is not fixed. It is overlap to other fields when scrolling page

**To Reproduce**
1. Login with Developer role
2. Go to "Submit App" page

**Expected behavior**
List of "Integration Types" is  fixed.

**Screenshots**
![image](https://user-images.githubusercontent.com/22660833/83856492-d8ca3780-a743-11ea-921d-596c6bd1ce2e.png)

**Comment by vuhuucuong** [comment]
Hi @HollyJoyPhillips , you can see the old and the new behavior images I attached as GIFs in here https://github.com/reapit/foundations/pull/1638
