### ISSUE TITLE
[Aml Checklist][Edit] Should only accept ".jpg", ".png" files

### ISSUE THREAD

**Issue by tanphamhaiduong** [reapit/foundations#1621]
**Describe the bug**
User can upload all file type at current 

**To Reproduce**
1. Go to 'Alm Checklist' as client role
2. Filling at 'Search by name' field (my case is 'Philip')
3. Click on 'Search' button
4. At 'Result' tab, click any 'Edit' button (my case is first Edit button)
5. Continue click 'Edit' button (my case is 2nd button)
6. Click 'Upload file'
7. Choose mp3 file

**Expected behavior**
Should only accept ".png", ".jpg" files and a warning message appears as "wrong file type" when choose invalid file type at 'Primary ID', 'Secondary ID', 'Address information' and 'Declaration Risk Management' form.

**Screenshots**
https://recordit.co/c9XAT1VF5p

**Comment by trankhacvy** [comment]
Verified on dev.

<img width="658" alt="Screen Shot 2020-06-15 at 14 41 29" src="https://user-images.githubusercontent.com/8068926/84630650-7678f000-af16-11ea-9a64-baa2d3bd4019.png">

**Comment by HollyJoyPhillips** [comment]
@trankhacvy I've tried uploading a word document but the message about the 'Wrong file type' does't appear. It allows me to save but doesn't save the file. Having said that, we should actually support word docs/pdf's etc so will close the ticket for now and create additional ticket to support additional file types.
