### ISSUE TITLE
[Aml Checklist][Edit] Should not allow to fill text into telephone number fields

### ISSUE THREAD

**Issue by tanphamhaiduong** [reapit/foundations#1624]
**Describe the bug**
Telephone number fields: Mobile, Work, Home allow to fill text at Edit form

**Precondition**
Search Client with data input is 'Philip'

**To Reproduce**
1. Click on 'Edit' button
2. Delete current data in Mobile, Work and Home fields
3. Entering text into Mobile, Work, Home fields

**Expected behavior**
Should have validation text when containing text in "Mobile", "Work", "Home" fields

**Screenshots**
![image](https://user-images.githubusercontent.com/22660833/84025154-4335de80-a9b5-11ea-8e5c-1a8622394183.png)

**Comment by HollyJoyPhillips** [comment]
@nphivu414 The validation seems to now apply to all telephone fields as each field is showing as 'required' but only one telephone number is required to save. 

Also, each telephone number should allow spaces: 
![image](https://user-images.githubusercontent.com/52408607/84600620-9bb42280-ae72-11ea-9f8f-79e8b12bfb55.png)

**Comment by nphivu414** [comment]
Hi @HollyJoyPhillips ,
The issue that makes all telephone numbers required was fixed but there is one problem.
Our telephone number validation still accepts spaces, the problem with your example is "7946" has 4 characters, it should have only 3 characters instead. This validation rule is also being applied in our Marketplace Submit App form:
![image](https://user-images.githubusercontent.com/22409039/84613631-de671080-aeed-11ea-851e-223aed62e7fc.png)

Please help me check. Thank you

**Comment by HollyJoyPhillips** [comment]
@nphivu414 As agreed we will leave the validation as is and look at refining it later. The issue with the requirement for more than one number has been fixed, thank you.
