### ISSUE TITLE
[Geo Diary] Should not auto zoom the current location

### ISSUE THREAD

**Issue by tanphamhaiduong** [reapit/foundations#1629]
**Describe the bug**
The current location is zoomed when starting app or after clicking on 'Today', 'Tomorrow', Week view', 'Car', Walk' buttons

**To Reproduce**
1. Go to 'Geo Diary' app as Client role
2. Accept location access request
3. See current location on map side (on the right of screen)
4. Click on 'Today' button and see current location on map side
5. Click on 'Tomorrow' button and see current location on map side
6.  Click on 'Week view' button and see current location on map side
7. Click on 'Car' button and see current location on map side
8. Click on Walk' button and see current location on map side

**Expected behavior**
The current location is not zoomed when starting app and after clicking on 'Today', 'Tomorrow', Weekview', 'Car', Walk' buttons 

**Screenshots**
- Starting app
![image](https://user-images.githubusercontent.com/22660833/84104590-2f838a00-aa40-11ea-95ac-b393f79aff8f.png)
- Click on 'Today' button 
![image](https://user-images.githubusercontent.com/22660833/84106159-9acf5b00-aa44-11ea-8ac9-be16512d6933.png)

- Click on 'Tomorrow' button
![image](https://user-images.githubusercontent.com/22660833/84106389-2b0da000-aa45-11ea-954f-a560e2ab90c5.png)

- Click on 'Week view' button
![image](https://user-images.githubusercontent.com/22660833/84106405-3a8ce900-aa45-11ea-89c0-16544b38d4b3.png)

- Click on 'Car' button
![image](https://user-images.githubusercontent.com/22660833/84106423-4aa4c880-aa45-11ea-84ae-7d49d1bf70c3.png)

- Click on 'Walk' button
![image](https://user-images.githubusercontent.com/22660833/84106447-58f2e480-aa45-11ea-8048-4cec9c1732e4.png)

**Comment by phmngocnghia** [comment]
@HollyJoyPhillips 
Could you help me to confirm the spec of the geo diary's map:
- When the new coordinate/marker list input the the map, should it snap it view to the bound (the view that contain all the markers)?

Also Could you help me to create a few appointments (2) for the geo-diary match the filter sections: today, tomorrow, please.

**Comment by tanphamhaiduong** [comment]
verified on dev
![image](https://user-images.githubusercontent.com/22660833/84483334-69b08e00-acc3-11ea-9d67-104b576d4f8c.png)
