### ISSUE TITLE
[Marketplace] App preview should have default placeholder for App Icon

### ISSUE THREAD

**Issue by tanphamhaiduong** [reapit/foundations#1649]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior eg:
1. Go to  Developer Submit App
2. Scroll down to end
3. Click on preview app

**Expected behavior**
- App Icon should have default placeholder images
![image](https://user-images.githubusercontent.com/22660833/84226637-835ba500-ab0c-11ea-8bdf-c07b377f9f7a.png)

- Layout should be normal

**Screenshots**
http://g.recordit.co/XN3WPwgI7o.gif

**Comment by ant066** [comment]
Hi @tanphamhaiduong @willmcvay @HollyJoyPhillips, after apply placeholder Image in preview app page, the layout like below image.
<img width="1280" alt="Screen Shot 2020-06-10 at 2 21 44 PM" src="https://user-images.githubusercontent.com/30467048/84239121-3d133f80-ab26-11ea-805a-8b687683bfd3.png">

Without data, the preview page does not render the correct layout. I think we should disable the preview button if the user does not fill all the required fields.
<img width="815" alt="Screen Shot 2020-06-10 at 2 29 26 PM" src="https://user-images.githubusercontent.com/30467048/84239521-cfb3de80-ab26-11ea-8872-0047225c3b93.png">
