### ISSUE TITLE
Change validation to Yup schema

### ISSUE THREAD

**Issue by tanphamhaiduong** [reapit/foundations#1670]
**Background context or User story:**
This is validate from marketplace
![image](https://user-images.githubusercontent.com/22660833/84345546-e1a18a00-abd7-11ea-83cc-bf9e8ceb8c17.png)

**Specification or Acceptance Criteria:**
![image](https://user-images.githubusercontent.com/22660833/84373369-abc7ca00-ac06-11ea-9783-7649eef76802.png)

**Suggested solution:**
- Change to use YUP validation

**Comment by vuhuucuong** [comment]
FYI, here is a list of affected pages:
- Register
- Admin revision approve/reject
- Cost calculator
- Developer invite member
- Webhook edit modal
If anything weird happens, please let me know. Thanks :)
