### ISSUE TITLE
Search widget does not work locally - 403 error

### ISSUE THREAD

**Issue by willmcvay** [reapit/foundations#1676]
**Background context or User story:**

_Loading localhost search widget with latest reapit config on latest master throws an unauthorized 403 error. Blocks local development_

**To replicate:**

- Check out web components, run yarn start:dev search-widget - perform a search, throws the error

**Comment by phmngocnghia** [comment]
@willmcvay 

![image](https://user-images.githubusercontent.com/36730355/84357524-00ac1600-abf0-11ea-8c00-296b3b9e62fc.png)


Have you put the debug token on the generated html file: `public/index.html`, `public/detail.html`

**Comment by willmcvay** [comment]
@phmngocnghia No I didn't - I was not aware this was necessary. Is it documented?

**Comment by phmngocnghia** [comment]
@willmcvay No, It's not documented at the moment

**Comment by willmcvay** [comment]
Cool, I checked and it's working. Can you update the docs here please: https://github.com/reapit/foundations/blob/master/packages/web-components/scripts/README.md
