### ISSUE TITLE
[Geo Diary] Cannot load app with Client role

### ISSUE THREAD

**Issue by tanphamhaiduong** [reapit/foundations#1680]
**Describe the bug**
Client only open app, cannot use the app

**To Reproduce**
1. Go to 'Geo Diary' app as Client role (username: plittlewood)
2. Observe current page

**Expected behavior**
Client can use the app

**Screenshots**
![image](https://user-images.githubusercontent.com/22660833/84362932-31904900-abf8-11ea-9ddf-0f1aa3e64a8e.png)

**Comment by HollyJoyPhillips** [comment]
Issue with installation, now working correctly.

**Comment by tanphamhaiduong** [comment]
This bug is backend bug and it's working to resolve it
