### ISSUE TITLE
[Marketplace] The length of the 'Search' field should be limited 

### ISSUE THREAD

**Issue by tanphamhaiduong** [reapit/foundations#1683]
**Describe the bug**
The length of the 'Search' field at 'Browse Apps' modal is unlimited as client role

**To Reproduce**
1. Go to 'Marketplace' as Client role
2. Inputting long text at 'Search' field

**Expected behavior**
The maximum length of the 'Search' field is 256 characters

**Screenshots**
https://recordit.co/kS8Vs7SODi

**Comment by vuhuucuong** [comment]
Please see the new behavior description in here https://github.com/reapit/foundations/issues/1686#issuecomment-643265476
