### ISSUE TITLE
[Marketplace] A validation text should be appeared when Search field is invalid

### ISSUE THREAD

**Issue by tanphamhaiduong** [reapit/foundations#1686]
**Describe the bug**
No validation text is appeared when Search field is empty or entering only 'space' at 'Browse apps' modal

**To Reproduce**
1. Go to 'Marketplace' as Client role
2. Click on 'Browse' tab on the menu
3. Don't input the value or Inputting space only at the 'Search' field on 'Browse Apps' modal
4. Click on 'Search' icon on the 'Search' field

**Expected behavior**
A validation text "The value is invalid" is appeared

**Screenshots**
- Empty: https://recordit.co/MR1HAqTltT
- Space only: https://recordit.co/XCrcqO7Den

**Comment by vuhuucuong** [comment]
Tested on dev
1. Input only spaces or invalid character
![Screenshot (19)](https://user-images.githubusercontent.com/26746668/84506397-81027200-ace9-11ea-8247-d264c277a0df.png)
![Screenshot (21)](https://user-images.githubusercontent.com/26746668/84506495-a8593f00-ace9-11ea-8b5b-dc414585af74.png)

2. Long input exceeds 256 chars
![Screenshot (20)](https://user-images.githubusercontent.com/26746668/84506437-95466f00-ace9-11ea-92c0-d91340bc6f52.png)
