### ISSUE TITLE
Update the Developer Registration T&C's

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#1714]
**Summary**: We have recently included new information in the Terms and Conditions so will need to update the the T&C's modal on the developer registration page

**Location:** https://dev.marketplace.reapit.cloud/register

**Task:** Update the T&C's on the developer registration page 

- Specifically the 'DEFINITIONS AND INTERPRETATION'  starting from 1.1.11 & the Schedule Fees table. 

See changes in blue/purple here 
[Reapit-Foundations Developer Agreement (Final v4 29.05.20)_DEVED addition.docx](https://github.com/reapit/foundations/files/4777021/Reapit-Foundations.Developer.Agreement.Final.v4.29.05.20._DEVED.addition.docx)

**Comment by tanphamhaiduong** [comment]
Verified on dev
