### ISSUE TITLE
Create ‘Confirm Subscription’ modal for ‘Developer Edition’ 

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#1717]
**Summary**: This ticket is to create the modal for when a developer clicks on ‘Confirm Subscription’ when on the ‘Desktop’ page 

**Dependent on ticket:** https://github.com/reapit/foundations/issues/1716

**Task:** Create modal for confirming subscription 
- Modal tile ‘Success’ 
- Subtext: 
You have successfully subscribed 1 Agency Cloud user licences and an email has been sent to the following members of your organisation with instructions on how to get started.  
John Smith - johnsmith@proptech.com
 We have added your subscription to your monthly billing. To manage your subscriptions please visit the 'Billing' tab. 
 Reminder: There is no charge for the Developer Edition Licence during the Beta Phase.
- Subtext should include ‘developer email’ 
- Should post to \subscriptions as ‘developerEdition’ 
- ApplicationId TBC

![image](https://user-images.githubusercontent.com/52408607/84602007-4c72ef80-ae7c-11ea-81a5-8eaf62882f3f.png)

**Comment by trankhacvy** [comment]
@HollyJoyPhillips **Should post to \subscriptions as ‘developerEdition’** => what api endpoint should we call ?

**Comment by HollyJoyPhillips** [comment]
Hi @trankhacvy Just a small change, can you remove the 's' from licences please as we are only issuing one licence at the moment. We will need to come back to it to show 'licences' when more than one user has been selected.  

"You have successfully subscribed 1 Agency Cloud user licences"
