### ISSUE TITLE
Add a ‘Subscriptions’ table on the ‘Billing’ tab in developers portal 

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#1718]
**Summary:** Developers will be able to subscribe to certain products and licences within the portal so we need to display the subscriptions to the developer 
**Task:** Add a ‘Subscriptions’ section and table on the ‘Billing’ tab 
- Columns: Type, Summary, Start Date, Renewal Date, Status
- Display subscription by developerId from \subscriptions 
Type = type
Summary = summary
Start Date = created
Renewal Date = renews
Frequency = frequency
Cost = cost
Cancel = DELETE \subscription\{ID}

![image](https://user-images.githubusercontent.com/52408607/84602039-7f1ce800-ae7c-11ea-81c4-3472cbffd38d.png)

**Comment by ant066** [comment]
Hi @HollyJoyPhillips, when clicking on the Cancel button, do we need a confirm modal to call delete API?

**Comment by HollyJoyPhillips** [comment]
@ant066 Good point, yes please: 

Header: Confirm Cancellation
Subtext: Are you sure you want to cancel this subscription? 
Buttons: Cancel - Confirm

Thanks
