### ISSUE TITLE
[AML Checklist] "Expiry Date" field still shows error message although having data in it

### ISSUE THREAD

**Issue by tanphamhaiduong** [reapit/foundations#1727]
**Describe the bug**
"Expiry Date" field still shows error message although having data in it

**To Reproduce**
Steps to reproduce the behavior eg:
1. Go to 'AML CheckList app'
2. Search for the client (my case: Phillip)
3. Click on "Edit" button on the specific results
4. Click on "Edit" button on the Primary ID part
5. Click on "Save" button
6. Observe Result at "Expiry Date" field

**Expected behavior**
Should not showed error message when having data in the "Expiry Date" field

**Video**
https://recordit.co/PCwqzHVcNR

**Workaround**
Click on the "Expiry Date" and choose data again, save new update successfully

**Comment by HollyJoyPhillips** [comment]
@trankhacvy The 'Required' message is no longer showing, thanks. 

The DOB issue still seems to be there though. We should be able to save the record without having to enter a DOB. It's not required to 'Save' the record but is required to make the 'Personal Details' complete. 

![image](https://user-images.githubusercontent.com/52408607/84669897-4bde6580-af1d-11ea-9b15-f77e5d9460d5.png)
