### ISSUE TITLE
Elements file upload should have an image crop component

### ISSUE THREAD

**Issue by willmcvay** [reapit/foundations#1740]
**Background context or User story:**

_When uploading an image to the site, there should be a component that supports cropping of images prior to upload_

**Specification or Acceptance Criteria:**

- Should be an Elements button file upload
- Should validate image types
- Should support fixed sizing so that a user can adjust the focus but not dimensions of the image
- Choice of library to do this should be well supported and as lightweight as possible

**Comment by vuhuucuong** [comment]
FYI: The base64 string of the image after cropping will be outputted in the `Action` tab here
<img width="1230" alt="Screen Shot 2020-06-22 at 14 11 27" src="https://user-images.githubusercontent.com/26746668/85266775-8e182180-b49e-11ea-9513-705ca22744b1.png">
