### ISSUE TITLE
The helper wizard containers are broken in both Safari and Chrome

### ISSUE THREAD

**Issue by willmcvay** [reapit/foundations#1743]
**Background context or User story:**

_See screenshots. The wizard component should be mobile responsive in all browsers. Please take the opportunity to refactor the CSS properly, not just quick fixes._

<img width="641" alt="Screenshot 2020-06-16 at 08 11 14" src="https://user-images.githubusercontent.com/4630495/84743007-3878dc00-afa9-11ea-815b-1b06497ea8bf.png">
<img width="749" alt="Screenshot 2020-06-16 at 08 10 56" src="https://user-images.githubusercontent.com/4630495/84743012-3ca4f980-afa9-11ea-8a87-b5f61387ef8a.png">
<img width="663" alt="Screenshot 2020-06-16 at 08 10 44" src="https://user-images.githubusercontent.com/4630495/84743015-3d3d9000-afa9-11ea-8bcf-8140f93c5b54.png">
<img width="925" alt="Screenshot 2020-06-15 at 20 02 05" src="https://user-images.githubusercontent.com/4630495/84743025-40388080-afa9-11ea-97c7-5ed66c600694.png">
<img width="915" alt="Screenshot 2020-06-15 at 20 01 58" src="https://user-images.githubusercontent.com/4630495/84743026-40388080-afa9-11ea-8019-a5455f05db7f.png">

**Comment by tanphamhaiduong** [comment]
Verified on dev env

**Comment by HollyJoyPhillips** [comment]
Hi @tanphamhaiduong I'm seeing following issue with text showing outside the container when viewing on a mobile: 
Iphone X simulator on a browser in Chrome
![image](https://user-images.githubusercontent.com/52408607/85417783-ebc47080-b567-11ea-8597-c27f8aa9fa65.png)

On Samsung S7 
![S7](https://user-images.githubusercontent.com/52408607/85418159-59709c80-b568-11ea-8eb2-966608d994ed.jpg)

In Chrome: 
![image](https://user-images.githubusercontent.com/52408607/85418220-6b523f80-b568-11ea-880a-3703771a88b7.png)

**Comment by HollyJoyPhillips** [comment]
Hi @tanphamhaiduong The wizard looks much better on a web browser but still having an issue with the container on a mobile (Samsung S7 Chrome) 
![Helper](https://user-images.githubusercontent.com/52408607/85985094-18eaa600-b9e2-11ea-93be-d86112a85840.jpg)

**Comment by tanphamhaiduong** [comment]
Waiting for issue #1805  finish and I will continue to fix it
