### ISSUE TITLE
[Submit App][Edit App]Should be not allow to upload file is not image files (.doc, .txt, .xslx) 

### ISSUE THREAD

**Issue by tanphamhaiduong** [reapit/foundations#1768]
**Describe the bug**
Should be not allow to upload file is not image files (.doc, .txt, .xslx)

**To Reproduce**
1. Login with role developer
2. Go to Submit App page and Edit App page
3. Click on "Upload image" button
4. Select option "All files" on popup folder
5. Upload file which is not image (.doc, .txt, .xslx)
6. Click on "Submit App" button

**Expected behavior**
Should not allow upload file with types: .doc, .txt, .xslx
Show message error when upload file is not image(.doc, .txt, .xslx)

**Screenshots**
https://recordit.co/p9TsKBAQ4v

**Comment by HollyJoyPhillips** [comment]
Hi @ant066 I can see that the open image window is defaulting on 'Images' but if i change to 'All Files' I can upload a .doc file and save without an error: 

![image](https://user-images.githubusercontent.com/52408607/85702604-7cb95a00-b6d6-11ea-8dfe-341a162ff6dc.png)

**Comment by HollyJoyPhillips** [comment]
Hi @ant066 Please can you change the validation/error to 'Invalid file type, please upload an image' 
![image](https://user-images.githubusercontent.com/52408607/85704766-8348d100-b6d8-11ea-8e00-8a87d36ac223.png)

**Comment by ant066** [comment]
Hi @HollyJoyPhillips. I changed the validation text on dev
