### ISSUE TITLE
[Submit App][Edit App]"Name" field should not allow special characters and numbers

### ISSUE THREAD

**Issue by tanphamhaiduong** [reapit/foundations#1769]
**Describe the bug**
"Name" field accpects numbers and special characters

**To Reproduce**
1. Login with developer role
2. Go to "Submit app" page and "Edit app" page
3. Input values number, special characters into "Name"
4. Observe at "Name" field

**Expected behavior**
"Name" field should not allow special characters and numbers

**Screenshots**
![image](https://user-images.githubusercontent.com/22660833/84980586-ac0f1a80-b15c-11ea-82d7-2683fb0a86d1.png)
![image](https://user-images.githubusercontent.com/22660833/84980620-c5b06200-b15c-11ea-83ad-a5576133ba90.png)

**Comment by tanphamhaiduong** [comment]
verified on dev
![image](https://user-images.githubusercontent.com/22660833/85394703-2682d480-b579-11ea-9c28-98159ae05c2e.png)

**Comment by HollyJoyPhillips** [comment]
@tanphamhaiduong Just one small change please, can you change the validation message to read 'Name can only contain letters and numbers'  
![image](https://user-images.githubusercontent.com/52408607/85512936-5e7a2e00-b5f2-11ea-8291-aad11b8e9afa.png)
![image](https://user-images.githubusercontent.com/52408607/85512956-676aff80-b5f2-11ea-9c12-fdb9f624b521.png)
