### ISSUE TITLE
[Submit App][Edit App] Should be limit the number of character entered into the fields

### ISSUE THREAD

**Issue by tanphamhaiduong** [reapit/foundations#1770]
**Describe the bug**
- "Name" field allows enter 2000 characters
- "Telephone" field allows enter 2000 number characters

**To Reproduce**
1. Login with developer role
2. Entering 2000 characters into 'Name' field
3. Entering 2000 number characters into "Telephone"field
3. Click on 'Submit App' button

**Expected behavior**
Should be limit the number of character entered into the fields
-"Name" field: 256 characters
-"Telephone": 16 number characters

**Screenshots**
https://recordit.co/utW46NXLlJ

**Comment by phmngocnghia** [comment]
@reapit/platform is checking this issue

**Comment by tanphamhaiduong** [comment]
as @phmngocnghia checked. The name support only 100 char right now. So I think field name is only 100 chars. Does it ok with you @HollyJoyPhillips @willmcvay.

**Comment by willmcvay** [comment]
Yep that sounds good to me @tanphamhaiduong 👍

**Comment by tanphamhaiduong** [comment]
@willmcvay for telephone should I validate length 32 ?

**Comment by tanphamhaiduong** [comment]
verified on dev
![image](https://user-images.githubusercontent.com/22660833/85394570-f804f980-b578-11ea-99a4-83f6b6bf2a85.png)
