### ISSUE TITLE
Add crop component to Submit and Edit App forms

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#1801]
**Summary:** We have recently created a image crop component in Elements which we should add to the relevant pages in the Developers Portal

**Dependent to ticket:** https://github.com/reapit/foundations/issues/1740 

**Component:** https://dev.elements.reapit.cloud/?path=/story/imagecropper--pre-integrated-imageinput

**Task:** To add the crop image component to the submit and edit app forms in the Developers Portal

**Comment by vuhuucuong** [comment]
Tested on dev
<img width="1422" alt="Screen Shot 2020-06-23 at 16 21 40" src="https://user-images.githubusercontent.com/26746668/85386344-b28eff00-b56d-11ea-8d3b-1483d8718788.png">
