### ISSUE TITLE
Migrate existing metadata into new metadata system

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#1811]
We don't want to lose existing metadata used by developer applications at the point of migration to our new system, so we should identity and migrate these to avoid confusion and support requests.

**Comment by plittlewood-rpt** [comment]
2 x app metadata rows migrated to new system to coincide with updates to the service/broker. These have all now been deployed.

**Comment by cbryanreapit** [comment]
I think this can be closed, governed by the other ticket, the tool is ready to go.
