### ISSUE TITLE
Remove standalone submit app code, rename developer-submit-app page to submit-revision

### ISSUE THREAD

**Issue by phmngocnghia** [reapit/foundations#1824]
- Remove standalone submit app page code
- Rename submit-app page into submit-revision. We are using the same page for submit revision / app at the moment. Submit app is now a wizzard on developer my apps page
- Remove `// @ts-nocheck` and fixlinter errors
- Remove all submit-app-specific stuffs

**Comment by vuhuucuong** [comment]
Hi @HollyJoyPhillips, the PR changed lots of things in Edit App page (validation & submit). We may need to test it again to make sure there's no regression. Thank you :)

**Comment by vuhuucuong** [comment]
Hi @HollyJoyPhillips, the PR changed lots of things in Edit App page (validation & submit). We may need to test it again to make sure there's no regression. Thank you :)
