### ISSUE TITLE
Ability to retrieve all Buyers for a Property

### ISSUE THREAD

**Issue by johnphipa-bnppre** [reapit/foundations#1833]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
_I'd like Api access to the Buyers of a property (Not just the Primary Buyer)._ 

**Describe alternatives you've considered**

**Additional context**

**Comment by cbryanreapit** [comment]
Thanks for reaching out. We'll need a little more information from you on this so I've updated your original ticket with the template we use for feature requests. If you'd be so kind as to fill in the blanks, we'll be able to get to grips with what you're asking for.

Many thanks

Craig

**Comment by cbryanreapit** [comment]
Closed due to inactivity - please let us know if this is still a requirement for you and you're able to expand on it.
