### ISSUE TITLE
Present message to Developer when a subscription already exists 

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#1836]
**Summary:** If a developer has already subscribed to the ‘Developer Edition’ on the ‘Desktop’ page and attempts to subscribe again, the endpoint will return an error. 

**Relates to ticket:** https://github.com/reapit/foundations/issues/1837 

**Location:** https://dev.marketplace.reapit.cloud/developer/desktop

**Task**: To surface this error in the front end

"It looks as though you already have a subscription in place for the Developer Edition of Agency Cloud. If you have not received your email with instructions on how to download, please let us know using the live chat feature on the ‘Help’ page."

Link 'Help' to https://marketplace.reapit.cloud/developer/help

**Comment by trankhacvy** [comment]
Verified on dev

<img width="1440" alt="Screen Shot 2020-06-25 at 21 59 14" src="https://user-images.githubusercontent.com/8068926/85744545-2f1d0b80-b72f-11ea-91b9-31d775b2cec1.png">

**Comment by HollyJoyPhillips** [comment]
@trankhacvy Thanks for adding the message but it really needs to be separated from the success message as we won't be sending another email. 

Please can you create a separate modal 'Existing Subscription'
Make the message Roboto, not bold.

![image](https://user-images.githubusercontent.com/52408607/85837753-6243b700-b790-11ea-99fe-ed0fc7986e04.png)

In addition and outside the scope of this ticket, the other modals for the developer edition should be Roboto and non bold too. Are you able to make that change as part of this ticket or shall i raise a separate ticket? 

Current view when clicking on 'Developer Edition' 
![image](https://user-images.githubusercontent.com/52408607/85837946-b189e780-b790-11ea-94eb-a748073cd755.png)

Roboto and no bold text
![image](https://user-images.githubusercontent.com/52408607/85838187-21986d80-b791-11ea-83a1-56d3bac4b925.png)


Current View on success message
![image](https://user-images.githubusercontent.com/52408607/85838336-57d5ed00-b791-11ea-95bf-98c26cc8e57e.png)

Roboto and no bold text
![image](https://user-images.githubusercontent.com/52408607/85838139-07f72600-b791-11ea-8725-9196c71a9a00.png)

**Comment by HollyJoyPhillips** [comment]
Hi @trankhacvy, thanks for creating the modal. It seems to be working in the front end but I'm getting a sentry error when I close the 'Existing Subscription' modal. 

**Error:** https://sentry.io/organizations/reapit-ltd/issues/1756285474/?project=1885603&referrer=slack 

**To replicate**: I'm using account hollyjoyphillips+1234@gmail.com > Desktop > Developer Edition > Confirm Subscription > Click 'Close' on Existing Subscription' modal > sentry error

**Comment by trankhacvy** [comment]
@HollyJoyPhillips the sentry error is an error which receive from back-end side. When user already subscribed to developer edition and try to  subscribe again, the back-end side will send an error look like
```
{
  "statusCode": 400,
  "dateTime": "2020-07-01T09:48:21.0047223Z",
  "description": "Unable to create subscription. An identical subscription is already active."
}
```
