### ISSUE TITLE
As a developer I should only see my apps when using the marketplace in Developer Edition

### ISSUE THREAD

**Issue by willmcvay** [reapit/foundations#1848]
**Background context or User story:**

_When developers subscribe to the developer edition of Desktop, they will be added to a Congito Group `AgencyCloudDeveloperEdition`, this means they can log into the Desktop software and for the first time, can load the client side of Marketplace. When they do this, they should not see "all apps", rather they should only see the apps that belong to their company_

**Specification or Acceptance Criteria:**

- Update the client fetch calls to the apps endpoints on the client side to add a developerId filter to each one (Browse Apps, Installed Apps, Manange Apps), if the user is part of the `AgencyCloudDeveloperEdition` group.
- You will get the `AgencyCloudDeveloperEdition` group in the Id Token from Cognito
- Developers that have this group will also be allocated a clientId ie `SBX`, so they have client side access to the app.
- To test this, you should create a new developer (or use your own), and add a subscription to Developer Edition then inspect the Id JWT to look at the values you get back.

**Suggested solution:**

- Should extend the LoginIdentity object in Cognito Auth if it is not already available (this is where we parse the Identity JWT), to include the groups the developer belongs to. If we are lucky we may have this for free when we get the MarketplaceAdmins group.

**Comment by HollyJoyPhillips** [comment]
Hi @trankhacvy I've logged into the client portal as hollyjoyphillips+1234@gmail.com (Holly's Company) and whilst the main browse app page is only showing my apps, i can still see other developers apps on the featured apps section?
 
![image](https://user-images.githubusercontent.com/52408607/86102027-f1174300-bab2-11ea-9d2a-43abd4a18f23.png)
