### ISSUE TITLE
Prod requirements for ‘Billing’ tab

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#1871]
**Relates to ticket**: https://github.com/reapit/foundations/issues/1870

**Summary**: Update the 'Billing' tab when in prod to display only the subscriptions table

**Location**: https://dev.marketplace.reapit.cloud/developer/settings/billing

**Task:** In prod: 
- On Billing tab:
Hide the Accounts section but show the subscriptions table
- Add helper text above ‘Subscriptions’ table: 
Text:  The subscriptions table below is just for reference whilst we are in Beta. When we move out of the Beta Phase you can use the table below to view and manage your Developer Portal Subscriptions. 

Subscriptions Only on 'Billing' tab
![image](https://user-images.githubusercontent.com/52408607/86043991-60544f00-ba41-11ea-8568-f9156c63c06b.png)

**Comment by vuhuucuong** [comment]
Hi @HollyJoyPhillips , So the Billing Tab is currently hidden in prod marketplace. Does it mean we will enable it in the next release. And how about the organization tab?
