### ISSUE TITLE
Login button on register success page is on the left

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#1874]
**Summary**: After registering as a new developer, the 'Login' button should be positioned to the right, currently on the left

![image](https://user-images.githubusercontent.com/52408607/86047320-9fd16a00-ba46-11ea-83ba-d31c03b8d046.png)

**Steps to reproduce:** Navigate to https://dev.marketplace.reapit.cloud/register, fill in form and accept T&C's > observe location of the 'Login' button

**Comment by tanphamhaiduong** [comment]
Result like below
![image](https://user-images.githubusercontent.com/22660833/86086321-a7872200-bacb-11ea-9dcf-23c594ce53f7.png)

**Comment by tanphamhaiduong** [comment]
verified on dev
![image](https://user-images.githubusercontent.com/22660833/86104080-c72c4380-bae7-11ea-95e5-f9d61f545acf.png)
