### ISSUE TITLE
Apply new styles and containers to Geo Diary App

### ISSUE THREAD

**Issue by willmcvay** [reapit/foundations#1891]
**Background context or User story:**

_See #1805 & #1869 New styles applied to Marketplace should be applied to other apps - this task is to apply to Geo Diary_

**Specification or Acceptance Criteria:**

- Flex containers replaced with sections. Main app container 
- Ensure 16px rem base is applied and does not break layouts
- Apply helper to change rem base to 14px when in desktop
- Ensure Menu is showing and is in grey styles when in desktop
- Remove as much custom CSS as possible in favour of Elements
- Ensure styles not broken by removal of !important helpers
- Replace vertical styling containers with helpers
- Ensure main headings are H3s and inner headings H5
- Add Content tags for body text
- Ensure Roboto is only font and delete Museo Sans

**Comment by HollyJoyPhillips** [comment]
Hi @nphivu414 just a couple of small things: 

Can you change the background colour to # F5F7F9 (still showing as the old # EEF3F9)
Is it possible to increase the size of the container as the buttons need spacing and when the 'ETA' is present it moves it onto another line: 
![image](https://user-images.githubusercontent.com/52408607/86971578-5204e200-c169-11ea-8bbf-79ac2f92c83d.png)
![image](https://user-images.githubusercontent.com/52408607/86971589-54ffd280-c169-11ea-9c2d-01774e06632d.png)
