### ISSUE TITLE
Apply new styles and containers to App Scaffolder

### ISSUE THREAD

**Issue by willmcvay** [reapit/foundations#1893]
**Background context or User story:**

_See #1805 & #1869 New styles applied to Marketplace should be applied to other apps - this task is to apply to App Scaffolder_

**Specification or Acceptance Criteria:**

- Flex containers replaced with sections. Main app container 
- Ensure 16px rem base is applied and does not break layouts
- Apply helper to change rem base to 14px when in desktop
- Ensure Menu is showing and is in grey styles when in desktop
- Remove as much custom CSS as possible in favour of Elements
- Ensure styles not broken by removal of !important helpers
- Replace vertical styling containers with helpers
- Ensure main headings are H3s and inner headings H5
- Add Content tags for body text
- Ensure Roboto is only font and delete Museo Sans, plus all references to it

**Additional**

- Ensure tested with all combinations of the scaffolder
- Remove styled components version in favour of Linaria as we want to support this lib only, make sure the CLI reflects this
- Tidy up any legacy scripts we are not using anymore

**Comment by phmngocnghia** [comment]
@willmcvay Can we remove the styling option for the scaffolder, and make it use the same styling webpack config from our foundation app

we have centralized our app webpack configs for the mono repo. I think we can do the same thing for non-foundation app. It will lead to less maintenance effort, and keep them in sync with our webpack config

**Comment by phmngocnghia** [comment]
**Additional scopes are:**

-  Reflect the latest build script
- Make sure scripts run smooth: dev, lint, build, test
