### ISSUE TITLE
Validation bug on edit app detail

### ISSUE THREAD

**Issue by tanphamhaiduong** [reapit/foundations#1900]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior eg:
1. Go to Edit App Detail
2. Click on Submit App
3. Scroll down to See validation

**Expected behavior**
Button should red and show required below

**Screenshots**
![image](https://user-images.githubusercontent.com/22660833/86208296-788bb180-bb9a-11ea-965d-1d71935ee10f.png)
![image](https://user-images.githubusercontent.com/22660833/86208303-7d506580-bb9a-11ea-9c07-c587e9833278.png)
![image](https://user-images.githubusercontent.com/22660833/86208341-91946280-bb9a-11ea-8769-1742e5e02356.png)

**Additional context**

**Comment by HollyJoyPhillips** [comment]
@tanphamhaiduong The icon image is showing as required (in red) but not the feature image

![image](https://user-images.githubusercontent.com/52408607/86291503-f07fc900-bbe6-11ea-8d20-64401edeea1b.png)

**Comment by tanphamhaiduong** [comment]
@HollyJoyPhillips  I have just tested on dev
![image](https://user-images.githubusercontent.com/22660833/86331342-2a96ac80-bc73-11ea-8821-e5c3eca5d826.png)

**Comment by tanphamhaiduong** [comment]
I have just check the input will red after click to submit app the first time. I think i need to investigate it
