### ISSUE TITLE
The cloud uptime reporter is not reporting prod outages

### ISSUE THREAD

**Issue by willmcvay** [reapit/foundations#1919]
**Background context or User story:**

_Today there was a prod outage caused by a 500 error (Platform), the tests failed and caught the error but did not post to the Sentry channel_

**Specification or Acceptance Criteria:**

- See test fail: https://github.com/reapit/foundations/actions/runs/154132230
- Should have alerted to the channel
- Would be helpful if this could report with an `@here` mention to alert online users

**Comment by tanphamhaiduong** [comment]
hi @willmcvay there is an report on cloud-sentry channel on 20:37

![image](https://user-images.githubusercontent.com/22660833/86321325-fa471200-bc62-11ea-97b8-483ff0dd5bba.png)

**Comment by willmcvay** [comment]
@tanphamhaiduong They are not Marketplace - they are search widget related. It was dev and prod marketplace that was down
