### ISSUE TITLE
Create build scripts and project setup for Elements v2

### ISSUE THREAD

**Issue by willmcvay** [reapit/foundations#1920]
**Background context or User story:**

_Currently we have an Elements v2 folder that contains a couple of components but nothing significant. Direction of travel for us should be a complete re-write of our components for v2. Aim firstly to do a v1 release of Elements for full production, maintain and patch as required but do not add to it. For v2 start a new project, fresh build scripts, best possible practices. Fully component based architecture, no compromises._

_Internally we will start to use the new components as they are ready to test and iterate on. We can import them into our projects using an alias `@reapit/elements-next` so we can use alongside the v1 code. When we are ready, we will start to release versions to alpha and beta channels, then deprecate v1 package_

**Specification or Acceptance Criteria:**

- Remove v2 folder from Elements v1 - integrate the few components we have back into main project. Do any required tidying, remove styled components.
- Create new v2 project, set up build scripts CSS to be linaria based, no Bulma
- Set base, fonts, colors, media queries, reset CSS etc on new project
- Migrate some basic layout components we can start to use, basic typography, containers etc
- Set up new storybook and deploy to a temporary Cloudfront instance for testing

**Comment by tanphamhaiduong** [comment]
should we use roll up as bundler only instead of use tsdx and customize by roll up ?
