### ISSUE TITLE
UI updates to the Submit App wizard 

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#1921]
**Summary**: This ticket is to address a few UI small tweaks to the new Submit App wizard flows 

**On all steps:** Subheadings should be H5 and the back button should be positioned left and clear. 

**Step 1** 
- Subheading should be a h5 
- ‘View Docs’ should open a new tab
 
![image](https://user-images.githubusercontent.com/52408607/86290705-d2659900-bbe5-11ea-90a2-a4c775935937.png)

**Step 2**
- Back button should be on the left and clear
 
![image](https://user-images.githubusercontent.com/52408607/86290721-d7c2e380-bbe5-11ea-91d1-218195609876.png)
![image](https://user-images.githubusercontent.com/52408607/86290750-de515b00-bbe5-11ea-99ea-2a4f5575cfea.png)

 
**Step 3**
- Subheading should be a H5
- Move 'Yes' & 'No' to the right and ‘Back’ to the left and clear (as above) 
 
![image](https://user-images.githubusercontent.com/52408607/86290762-e3160f00-bbe5-11ea-8e69-0d7f96e2a767.png)

**Authentication** 
- ‘Back’ to the left and clear (as above)
- Wrap helper text in ‘content’ tag 
- Capitalise ‘uri’ on validation 
![image](https://user-images.githubusercontent.com/52408607/86290791-ee693a80-bbe5-11ea-97f5-5c547394a451.png)

- Change URL to URI in the first paragraph “Please now register one or more Redirect URIs and a Sign Out URI…”
 
![image](https://user-images.githubusercontent.com/52408607/86290805-f3c68500-bbe5-11ea-9d22-011019e300be.png)

- Subheading should be H5
- Back should be on the left (as step 2) 
- Remove ‘Please select’ 
- Client side and Server side should be on the same line 
- Helper text should be justified and fill the container 
![image](https://user-images.githubusercontent.com/52408607/86290817-fa54fc80-bbe5-11ea-8152-2fce40a4ab2d.png)

![image](https://user-images.githubusercontent.com/52408607/86290836-ff19b080-bbe5-11ea-83a2-769c75d7ab8e.png)

 **Permissions**
- Subheading should be H5
- Drop down select list should display below the field not above
- Back should be left and clear (as step 2 above) 
 
![image](https://user-images.githubusercontent.com/52408607/86290855-06d95500-bbe6-11ea-8ec7-40cf00419a70.png)

 

**Success**
- Subheading should be H5 
- Authentication should be same font size as Client ID 
- The client id should not be bold but the heading should eg. **Client ID**: kjrwkehjkrhwkejrh
- Please remove the full stop after Marketplace "Marketplace. to potential clients" 
- Please remove ‘For more information on the App submission process, please click here.’ 
 
![image](https://user-images.githubusercontent.com/52408607/86290869-0e006300-bbe6-11ea-8ac0-0250e4d6abf8.png)
![image](https://user-images.githubusercontent.com/52408607/86291015-4ef87780-bbe6-11ea-9c76-396761c07d55.png)

**Comment by trankhacvy** [comment]
Hi @HollyJoyPhillips on Authentication modal, you want to Wrap helper text in ‘content’ tag but for now the helper text is a part of Input component so if we change it will effect other components which use Input. Do you really one to do it ?
