### ISSUE TITLE
[Admin] Search button should align center

### ISSUE THREAD

**Issue by tanphamhaiduong** [reapit/foundations#1926]
Steps to reproduce:
1. Login to Reapit as Admin
2. Click on the 'Apps' from the navigation menu
3. Observe at "Search" and "Refresh" button

Actual Result: "Search" and "Refresh" button are not aligned with text fields at "Admin Apps Filter Form"
![image](https://user-images.githubusercontent.com/22660833/86319952-e352f080-bc5f-11ea-9671-0a06fedf8a02.png)

Expected Result: "Search" and "Refresh" button are aligned with text fields at "Admin Apps Filter Form"

**Comment by vuhuucuong** [comment]
Old
![86323663-73e0ff00-bc67-11ea-88b8-c0ccdd528a26](https://user-images.githubusercontent.com/26746668/86351124-f54b8800-bc8d-11ea-87a5-0c726a865078.png)
New
![86323611-590e8a80-bc67-11ea-9494-1dcb9df6d4cf](https://user-images.githubusercontent.com/26746668/86351135-faa8d280-bc8d-11ea-83fa-415d91e7c5f2.png)
