### ISSUE TITLE
[Admin] Developer List search form cannot select registered date because validation

### ISSUE THREAD

**Issue by tanphamhaiduong** [reapit/foundations#1927]
Pre-condition: Have existed developer had created on July 1st, 2020

Steps to reproduce:
1. Login to Reapit as Admin
2. Click on the 'Developers' tab from the navigation menu
3. Choose "July 1st, 2020" at "Registered From" field
4. Observe at "Registered To" field

Actual Result: 
![image](https://user-images.githubusercontent.com/22660833/86320526-42653500-bc61-11ea-8258-2c954fc6a4c8.png)

Cannot choose a current date in the "Registered To" field
Options are disable

**Comment by vuhuucuong** [comment]
Hi @HollyJoyPhillips , please see the old and the new behaviors in my PR's description here
https://github.com/reapit/foundations/pull/1937#issue-443394041
