### ISSUE TITLE
[Elements] Datepicker can delete to empty by delete button

### ISSUE THREAD

**Issue by tanphamhaiduong** [reapit/foundations#1928]
Steps to reproduce:
1. Login to Reapit as Admin
2. Click on the 'Developers' tab from the navigation menu
3. Choose specific day in the "Registered From" field
4. Click on "Registered From" field again, press "Delete" on the computer and observe

Actual Result: Cannot delete data input in "Registered From" field by pressing "Delete" button on the computer
https://recordit.co/Z4204OiB3l

Expected Result: Can delete data input in "Registered From" field by pressing "Delete" button on the computer

**Comment by phmngocnghia** [comment]
@tanphamhaiduong  This one is correct behavior of date time picker. If you blur the date picker while the invalid value is already filled, it will be reseted to its original value

**Comment by phmngocnghia** [comment]
Will be patch in element V2
