### ISSUE TITLE
Update the filtering options on the ‘Detailed’ tab in ‘Analytics’

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#1961]
@phmngocnghia's comment: Please take a look at my latest comment

**Summary**: We need to change the 3 ‘Filter by’ options on the ‘Detailed’ tab on the 'Analytics' page in the Developers Portal. In addition, we should now support the current date as an option when using the date range calendar

**Location:** https://marketplace.reapit.cloud/developer/analytics

**Current filter by options:** 
Yesterday, Last Week & Last Month 
![image](https://user-images.githubusercontent.com/52408607/86475337-5d58a780-bd3c-11ea-905b-d2ad6fb74ea8.png)

**New filter by options:** 
Today, Last 7 Days & Last 30 days
 
![image](https://user-images.githubusercontent.com/52408607/86475347-6184c500-bd3c-11ea-812e-cee757a51369.png)

- Today – should return data from current day
- Last 7 days – should return data from current day – 6 days
- Last 30 days – should return data from current day – 29 days 
- Should default on ‘Last 7 Days’ 

**Date select:**
Currently, we do not allow ‘Today’ as an option on the date picker. With the new filter options above we should allow the current date to be selected: 
 
![image](https://user-images.githubusercontent.com/52408607/86475360-68133c80-bd3c-11ea-8a49-a8f0d3d2c396.png)

**Comment by phmngocnghia** [comment]
> Currently, we do not allow ‘Today’ as an option on the date picker. With the new filter options above we should allow the current date to be selected:

Hi, @HollyJoyPhillips I don't understand this part of requirement? Could you help me to clarify it

**Comment by phmngocnghia** [comment]
@phmngocnghia We lost this code after the migration (copy from marketplace to developer portal, seems like we didn't have a chance to rebase the marketplace before migration)

- Get the changes from https://github.com/reapit/foundations/pull/1980
- Move it to developer-portal

**Comment by phmngocnghia** [comment]
d
