### ISSUE TITLE
Only display endpoints (itemCount) for ‘API Requests’ 

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#1971]
**Summary**: The column ‘Endpoints’ on the Cost Explorer only applies to ‘API Requests’. Therefore we should only show the Endpoints (itemCount) number for ‘API Requests’ 

**Task:** Only show the ‘itemCount’ (Endpoints) for API Requests 

See current table display:
![image](https://user-images.githubusercontent.com/52408607/86512218-0912fd80-bdf8-11ea-9819-14523ea6d536.png)

Example showing only the API Requests 
![image](https://user-images.githubusercontent.com/52408607/86512221-0ca68480-bdf8-11ea-9f4c-31bcaefb070d.png)

**Comment by ant066** [comment]
Hi @HollyJoyPhillips, Should we show `Endpoints` at sub row of `API Requests` or not
![image](https://user-images.githubusercontent.com/30467048/86554176-1276a400-bf77-11ea-8b40-5ed2bcca7bb9.png)

**Comment by HollyJoyPhillips** [comment]
@ant066 Yes please, we should still show endpoints for the sub rows of API Requests. Thanks for checking.
