### ISSUE TITLE
UI Updates to ‘Organisations’

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#1985]
**Summary**: Updates required to the ‘Organisations’ page in Developer Portal 

**Location:** https://dev.developers.reapit.cloud/settings/organisation

**Tasks**: 
- Rename ‘No VAT Number’ to ‘Not VAT Registered’
- When ‘Not VAT Registered is ticked – **do not** display the ‘National Insurance Number’ field. Only when ‘No Company Registration’ is ticked, should the ‘National Insurance Number’ field be displayed. 

See example below: 
![image](https://user-images.githubusercontent.com/52408607/86757648-34395f00-c03b-11ea-9462-eabdd470ca38.png)

- Add fields: Building Name (above Address line 1) & Building Name (above Address line 2)
- Swap ‘Country’ and ‘Postcode’ 
See mockup 
![image](https://user-images.githubusercontent.com/52408607/86757754-47e4c580-c03b-11ea-9f29-7dc6286d601f.png)

- Create dropdown list for Country using ISO 3166 codes – Alpha 2. You may already have a list but I have provided the attached:
[CountryIDs.txt](https://github.com/reapit/foundations/files/4883885/CountryIDs.txt)
 
- Duplicate ‘United Kingdom’ at the top of the list (as it will be the most commonly selected)

**Comment by vuhuucuong** [comment]
hi @HollyJoyPhillips about `Duplicate ‘United Kingdom’ at the top of the list (as it will be the most commonly selected)`
I moved the UK option to the top, but we can't duplicate it because the `select option` key must be unique
