### ISSUE TITLE
Update ‘Billing’ page 

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#1987]
**Summary**: As we now have the available endpoint we should link the ‘Billing’ page to the /developers endpoint

**Location:**https://dev.developers.reapit.cloud/settings/billing

**Task**: Connect the ‘Billing’ page to the /developers endpoint 

Accounts Email: billingEmail
Accounts Telephone: billingTelephone
Accounts Contact: billingKeyContact
Reapit Reference: reapitReference
Validation: Should consist of 6 chars (3 letters and 3 numbers) 

**To save:** Accounts Email, Accounts Telephone, Accounts Contact & if 'Reapit Reference' is ticked > A Reapit reference should be provided in the correct format. 
**When saved:** Should set status to 'Pending' 
Add 'Account Status:' field to display status
See mockup :
![image](https://user-images.githubusercontent.com/52408607/86766740-e0327880-c042-11ea-8c28-d4f8b8a5e3f4.png)

If 'No' is selected for 'Reapit Reference' ticket TBC

**Comment by phmngocnghia** [comment]
The Developer settings page on the mock doesn’t look like the same as the screenshot
![image](https://user-images.githubusercontent.com/36730355/87613958-fb833f00-c738-11ea-830b-9db824b18f3d.png)

Validation rule of reapitReference. should it be 6 chars max, with 3 characters, 3 numbers or the same validation as option 1 with number, character should be consecutive. E.g. A1B2C3 or ABC123 or 123ABC? (edited)

**Comment by HollyJoyPhillips** [comment]
@phmngocnghia The mock up was created before the new style update. Lets leave it as it is now and come back to it. The columns are not properly aligned on Dev but we can come back to it. 

The Reapit Reference will always be 3 letters and then 3 numbers.

**Comment by HollyJoyPhillips** [comment]
@phmngocnghia Thanks for updating the endpoints. Just a couple of points: 

- We should disable the ‘Reapit Reference’ field and checkbox once a reference has been saved

- When loading the page for the first time (no account information is present), Reapit Reference is defaulting on ‘No’. Neither option should be selected (Direct Debit and Setup Direct Debit shouldn’t be shown until ‘No’ is selected: 
 
![image](https://user-images.githubusercontent.com/52408607/87680470-63577b00-c775-11ea-94ef-d57f09959f3c.png)

- Consist is spelt incorrectly: 
 
![image](https://user-images.githubusercontent.com/52408607/87680540-766a4b00-c775-11ea-858b-71c9cd44bcb0.png)

- ‘Account Status:’ field and data should be same colour as the other headings. 
![image](https://user-images.githubusercontent.com/52408607/87680561-7b2eff00-c775-11ea-9769-5c4aabc6456f.png)


- If the Account Status is ‘Pending’ and a Reapit reference is present (saved), we should display the following helper text in place of the ‘Direct Debit’ section: 

We are currently verifying your information with our Accounts Department 
Account Status: Pending

**Comment by HollyJoyPhillips** [comment]
@phmngocnghia Thanks for updating the billing section. Apologies if it wasn't clear but when the account status is 'pending' we should only display the helper text 'We are currently verifying your information with our Accounts Department' not the direct debit helper text as well. Also, the helper text should be in italics

Current view: 
![image](https://user-images.githubusercontent.com/52408607/88588881-27af9180-d050-11ea-95d8-1311dbac83ac.png)

See mock up: 
![image](https://user-images.githubusercontent.com/52408607/88589106-8b39bf00-d050-11ea-9542-621116676663.png)

**Comment by HollyJoyPhillips** [comment]
Hi @phmngocnghia just a couple of tweaks please: 

- Can we capitalise the ‘status’ field please e.g. confirmed to Confirmed, pending to Pending and underReview to Under Review
- If the status is ‘Confirmed’, ‘Under Review’ or ‘Remove’ we shouldn’t display any direct debit/helper text 
Current: 
![image](https://user-images.githubusercontent.com/52408607/88665915-41e08280-d0d7-11ea-918d-df09bddd1d15.png)

No helper text: 
![image](https://user-images.githubusercontent.com/52408607/88665934-47d66380-d0d7-11ea-9054-bff0e1787f72.png)

**Comment by HollyJoyPhillips** [comment]
Hi @phmngocnghia, 

The direct debit header and helper text is still showing even though a reapit reference is present and the account status is 'Pending'. It should just show the helper text 'We are currently verifying your information with our Accounts Department'. Also it should be in italics:

![image](https://user-images.githubusercontent.com/52408607/89784117-0484e780-db10-11ea-8a74-3ce48d878352.png)
