### ISSUE TITLE
Addition of 'Disposal' to the /properties/ API endpoint

### ISSUE THREAD

**Issue by rosscooneyISG** [reapit/foundations#1998]
**Background context**
Agency Cloud provides the 'disposal' concept: a sales specific field that  responsible for detailing the mechanism to be used to sell the property in question. We should present this data for read and write in our properties API.

**Specification**
- Add 'selling.disposal' attribute to the payloads for `GET /properties`, `GET /properties/{id}`, `POST /properties` and `PATCH /properties`
- This is a sales specific attribute and will be nested in the `selling` structure
- Not a required field for `POST` (**not a breaking change**). 
- Default to `privateTreaty` when not specified in `POST` payload
- When provided in POST or PATCH payloads, validate the value is one of the 5 acceptable options (auction/confidential/tender/offersInvited/privateTreaty)
- Reindex ElasticSearch on release of new version of service

**Original message**

We would like an extension to the /properties/ endpoint of the API to include details of the status of the properties 'disposal'.

We would like to be able to GET and POST this data so that we are able to read and update this status.

**Comment by cbryanreapit** [comment]
Thanks for the feedback @rosscooneyISG  - we'll get this added.
