### ISSUE TITLE
Populate and create the action for setting up a Direct Debit 

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#2011]
**Summary**: We now have the mechanism to load an interactive direct debit from that will be signed electronically by developers to setup their account

**Location**: https://dev.developers.reapit.cloud/settings/billing

**Tasks:** 
### Create an iframe and insert code from Adobe Sign when a Developer clicks on ‘Setup Direct Debit’ 
**Code**: 
"<iframe src="https://reapit.na1.echosign.com/public/esignWidget?wid=**APIKEY***&hosted=false" width="100%" height="100%" frameborder="0" style="border: 0; overflow: hidden; min-height: 500px; min-width: 600px;"></iframe>"

**Note:** Please contact me direct for the API Key. 
**Important:** Do not commit the API Key should store in the config file.

- Add content & button on the footer of the iframe
“Once you have completed this form, please click here to continue” 
![image](https://user-images.githubusercontent.com/52408607/86923200-a38b7d80-c125-11ea-8723-9022674167b9.png)

### Button ‘Finish’ 
- Button action: Closes modal/iframe
- Replaces ‘Direct Debit’ heading & subtext with ‘Thank you for setting up a Direct Debit, to continue please click ‘Save’ below
- Remove ‘Setup Direct Debit’ button
- Enable ‘Save’ 
![image](https://user-images.githubusercontent.com/52408607/86923228-ab4b2200-c125-11ea-960c-d1d4014437e8.png)

### When ‘Saved’
- Should save account information and set ‘status’ to ‘Pending’ 
- Replace helper text with: 
“Thank you for submitting your Account Information and setting up a Direct Debit, we just need to validate your information with our Accounts Department. One this has been completed your account will be set to ‘Active’ and you can procced with any subscriptions.  
- ‘Add ‘Account Status: Pending’ (status) 
![image](https://user-images.githubusercontent.com/52408607/86923248-b1d99980-c125-11ea-943e-bf9e4ef92cf7.png)

**Steps**: Load ‘Billing’ page > enter Account Email, Telephone & Contact > selects ‘No’ to ‘Reapit Reference’ > click on ‘Setup Direct Debit’ > fills out form > clicks on ‘Finish’ > click ‘Save’ > sets account to ‘Pending’

**Comment by vuhuucuong** [comment]
Hi @HollyJoyPhillips and @willmcvay , a few things I'm concerning about this:
- So we will have an `iframe` in a modal -> and in that `iframe` we have a form which users can fill info in?
- If that's the case, how can we detect if users are finished filling data in the form, I don't think we have a proper way to interact with `iframe` from our web apps, due to security reason.

Am I missing something? 🤔

**Comment by willmcvay** [comment]
@vuhuucuong No, we don't have a way of interacting with it. We know it's not ideal - we'll just have to work around that.

**Comment by HollyJoyPhillips** [comment]
@vuhuucuong After loading the modal - it's asking me to sign into Adobe, it should just load the form. If run the same iframe code from a basic browser I don't need to log in first? 
![image](https://user-images.githubusercontent.com/52408607/87672730-46b64580-c76b-11ea-9779-65a4d3d57420.png)

After you click 'Finish' this is the message that should display: 
![image](https://user-images.githubusercontent.com/52408607/87672837-7bc29800-c76b-11ea-82c2-efe98878c6bf.png)

Then when the user clicks save, this message should appear with the account status: 
![image](https://user-images.githubusercontent.com/52408607/87672940-a3196500-c76b-11ea-9814-98823d29c63e.png)

When the user then re loads the page and the account status is 'Pending' this is the message that should display: 
![image](https://user-images.githubusercontent.com/52408607/87672940-a3196500-c76b-11ea-9814-98823d29c63e.png)
