### ISSUE TITLE
CRA template tweaks and tidy up for full production

### ISSUE THREAD

**Issue by willmcvay** [reapit/foundations#2023]
**Background context or User story:**

_For the app scaffolder, we are migrating to CRA for external users. As such, we will need to tidy up the code and deprecate the old scaffolder._

**Specification or Acceptance Criteria:**

- CRA template should have minimum number of NPM dependencies as possible
- Should be tested in all browsers to IE11
- Should have simple, slimmed down configs with minimal opinionated additions eg Jest, ESLint, TSConfig
- Scaffolder should have a final stable version of current build deployed to NPM, v1.0.0. 
- When we are ready to switch off the old scaffolder, add a deprecation notice to README.md before deploying another minor release - should redirect users to the CRA template.
- Scaffolder should be simplified when deprecation notice is live to only output internal scaffolds, external code to be deprecated and removed
- Internal scaffold to use new Auth Module

**Comment by phmngocnghia** [comment]
@willmcvay Could you help me to clarify this part of requirement:
```
Scaffolder should be simplified when deprecation notice is live to only output internal scaffolds, external code to be deprecated and removed
```

**Comment by willmcvay** [comment]
No, for internals we can use what we have - it's all set up to use our scripts. It just won't be an external NPM package

**Comment by willmcvay** [comment]
Issues that came out of testing;

- Add connect session to package.json
- Remove context for connect session as no longer exported
- Add react router to package.json
- Rename client id and oauth url in window.config - should match the connect session conventions to be clearer
- Should have an example service that shows the fetching from the api via a hook and the platform API - am thinking just to hit the swagger endpoint as an example
- Do the error messages do anything? I think this constants don't pass
- Tests don’t pass - window config error - we should include a config.json in the scaffold - people can manually add their client id but we should provide this. For this package only will rename it reapit.config.json so it is not gitignored
