### ISSUE TITLE
Update Billing page in Admin Portal

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#2025]
**Summary**: We already have a page in the Developers Portal for ‘Billing’ and we now have the endpoint available.

**Relates to ticket:** https://github.com/reapit/foundations/issues/1382

**Location:** https://dev.developer-admin.reapit.cloud/admin/billing

**Task:** Update the ‘Billing’ page in the developers /GET /developers/costs/{month}
- Billing Period: Display Month and Year (month from route should be in format: yyyy-MM) 
- File: Link to download the file

**Comment by phmngocnghia** [comment]
Hi @HollyJoyPhillips What period would you like display, what month would you like me to input to `developer/costs` API?

**Comment by ant066** [comment]
Hi @HollyJoyPhillips, We should display the current month only, or all period from the month that account was created?

**Comment by HollyJoyPhillips** [comment]
So on page load, we should show the current month and year

Then have a 2 drop down menus (month & year) (default on current month and year) to filter the results accordingly
