### ISSUE TITLE
GEO Diary V2 UI Issues 

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#2072]
**Summary**: Following the release of GEO Diary V2, this ticket is to address a few UI Issues

**GEO Chrome**
- On the previous version, the appointments are numbered on the map in order of time/date. 
See previous: 
 
![image](https://user-images.githubusercontent.com/52408607/87597661-17abbf80-c6ea-11ea-84e5-9209a425f0f1.png)

V2
![image](https://user-images.githubusercontent.com/52408607/87597676-1bd7dd00-c6ea-11ea-9871-1eb940611766.png)

- As above and on V2, it’s not showing my current location 

- If no property address is present, we should not display the ‘Start Journey’ nav: 
Previous: 
 
![image](https://user-images.githubusercontent.com/52408607/87597691-21352780-c6ea-11ea-851c-aa378afc9bb7.png)

V2:
![image](https://user-images.githubusercontent.com/52408607/87597703-25f9db80-c6ea-11ea-96ce-400366ad1fcb.png)

- If no property address is present, we shouldn’t display the ‘Property’ heading when clicking on ‘Details’ 
Previous: 
 
![image](https://user-images.githubusercontent.com/52408607/87597711-2abe8f80-c6ea-11ea-9b1b-130f74348f45.png)

V2:
 
![image](https://user-images.githubusercontent.com/52408607/87597723-2f834380-c6ea-11ea-88b6-f25d8c26c212.png)

GEO Mobile
- When the ‘ETA’ CTA is present the buttons are placed outside the container
 
![image](https://user-images.githubusercontent.com/52408607/87597730-33af6100-c6ea-11ea-8033-c7e7b3af1927.png)

**Comment by HollyJoyPhillips** [comment]
Hi @tanphamhaiduong, a couple of UI issues detected: 

- The spacing is inconsistent on the left- and right-hand side of the buttons: 
![image](https://user-images.githubusercontent.com/52408607/87985952-5e2b6080-cad4-11ea-81bf-5fd672973492.png)


- When you select an appointment (by clicking ‘Details’ or ‘Directions’) it is no longer highlighting the tile with a blue border
See previous: 
![image](https://user-images.githubusercontent.com/52408607/87985965-64214180-cad4-11ea-93d1-6f48bd3c046e.png) 

V2
![image](https://user-images.githubusercontent.com/52408607/87985986-6a172280-cad4-11ea-9c77-f460d6a3aea1.png)

When you click on ‘Directions’, the ‘Start Journey’ bar is no longer appearing (same for mobile):  
![image](https://user-images.githubusercontent.com/52408607/87986028-7d29f280-cad4-11ea-8ad9-4c57525047c4.png)


**Mobile:** 
- The background/spacing between appointments is no longer present, it’s all white:  
![image](https://user-images.githubusercontent.com/52408607/87986044-82873d00-cad4-11ea-8393-f240f8859dc3.png)

- When clicking on ‘Details’, the email address is unreadable:  
![image](https://user-images.githubusercontent.com/52408607/87986054-85822d80-cad4-11ea-89d8-8dbd00fc87ff.png)

**Comment by tanphamhaiduong** [comment]
verified on dev
