### ISSUE TITLE
Update ‘Invite New Member’ modal with endpoints

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#2095]
**Summary**: We now have the required endpoints for the ‘Invite New Member’ section of ‘Organisations’. Some functionality is not yet completed in the backend but the fields are available. 

**Location**: https://dev.developers.reapit.cloud/settings/organisation

**Task**: Update the Invite New Member Modal with the correct endpoints 

**Endpoint:** POST /developers/{id}/members

Name: name
Add field Job Title: jobTitle
Email: email
Message: message

We should include the name of the logged in developer as the ‘sender’ as it is required in the POST but not a field on the modal 

![image](https://user-images.githubusercontent.com/52408607/87883112-05d55f80-c9fd-11ea-9b21-637e6723278b.png)

**Comment by HollyJoyPhillips** [comment]
Hi @tanphamhaiduong Thanks for updating the modal, please can you also add 'Job Title' as a field on the invite?

- Add field Job Title: jobTitle'

**Comment by tanphamhaiduong** [comment]
ok @HollyJoyPhillips
