### ISSUE TITLE
Create a direct route to the Developers Portal to action an Invite

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#2096]
**Summary:** When an invitation as been sent, a developer will click on a button ‘View Invitation’ within the email which should direct them to a standalone route with a modal to either ‘Confirm’ or ‘Decline’ the invitation. 

**NOTE:** The URL will include the developerId & memberId

Example of the email (for information only): 

![image](https://user-images.githubusercontent.com/52408607/87883155-6cf31400-c9fd-11ea-8560-66e041ef0027.png)
 
**Task:** Create a non public accessible route which will populate a modal to confirm or decline member invitation 
- Do not display nav bar
- Plain background
- Route: https://dev.developers.reapit.cloud/invite 
- Modal title: Reapit Foundations Invite
- Text: You have been invited to join the 'COMPANY NAME' organisation on Reapit Foundations. 
Before confirming your account, please ensure your details are correct below. 
Name*: 
Job Title*: 
**Important:** If you already have an account and confirm this invitation, any data on your existing account will no longer be available.

- ‘Company Name’ GET /developers/{id}
- Fields: Name*: prepopulated with ‘name’ & Job Title*: prepopulated with ‘jobTitle’ 
GET /developers/{developerId}/members/{memberId}
- Buttons: 
Confirm: POST /developers/{id}/members/{memberId}/accept
Decline: POST /developers/{id}/members/{memberId}/reject

![image](https://user-images.githubusercontent.com/52408607/87883162-767c7c00-c9fd-11ea-9713-4d716cbb2702.png)

**Task:** Create ‘Success’ modal on ‘Confirm’
- If a developer clicks on ‘Confirm’- return a ‘Success’ message: 
- **Modal Title:** Success
- **Text:** Thank you for confirming your invite to Reapit Foundations.

If you already had a Developer account, you can use your existing credentials to login to the Developers Portal. If not, you will shortly receive an email with instructions on setting up your login credentials. 
 
![image](https://user-images.githubusercontent.com/52408607/87883167-7d0af380-c9fd-11ea-8de4-4ce24a4354fa.png)

**Task:** Create ‘Confirmation’ modal on ‘Decline’
- If a developer clicks on ‘Decline’  - return the following: 
- **Modal Title:** Invitation Declined
- **Text:** You have successfully declined the invitation to Reapit Foundations. 
 
![image](https://user-images.githubusercontent.com/52408607/87883171-81cfa780-c9fd-11ea-9a49-d425c1190403.png)

**Comment by ant066** [comment]
Hi @HollyJoyPhillips, After a member accepted or rejected an invite, they still access the URL we provide, what should we show for them? Currently, I can get the current status of the member, which is `(active/inactive/pending/rejected)` and show `Decline` or `Success` modal. Should I do that, or just show the ` Reapit Foundations Invitation` again?

**Comment by HollyJoyPhillips** [comment]
@ant066 That's a very good point. Let me check with Platform as we may need to think about users that click 'Decline' and their status is set to 'Rejected' but they later wish to join the organisation. I would guess when an invite goes out it would be changed to pending again but will need to check to be sure. Can you leave this with me please.

**Comment by HollyJoyPhillips** [comment]
Hi @ant066 Thanks for creating the route, it works well. I have been able to accept and decline users. 

Just a small thing, please can you make the modal headers the same size & colour as our other modals please?  

I believe it's font size 24px (1.5 rem) 
See example of our other modal headers 

![image](https://user-images.githubusercontent.com/52408607/88333634-798ea980-cd28-11ea-9c81-ed879bcb630b.png)

On the Invitation, decline and success it's smaller
![image](https://user-images.githubusercontent.com/52408607/88333654-84493e80-cd28-11ea-9ebd-fdd138508acc.png)
![image](https://user-images.githubusercontent.com/52408607/88333669-890df280-cd28-11ea-9550-fab0ce7dd539.png)
![image](https://user-images.githubusercontent.com/52408607/88333680-8dd2a680-cd28-11ea-9146-cad226877173.png)
