### ISSUE TITLE
Pagination of Browse Apps list on Marketplace should be an infinite scroll

### ISSUE THREAD

**Issue by willmcvay** [reapit/foundations#2120]
**Background context or User story:**

_We will soon be adding a "coming soon" apps banner that will sit on the Browse Apps page where the pagination bar currently sits. To accommodate this, we will paginate the page with an infinite scroll_

**Specification or Acceptance Criteria:**

- Remove the pagination bar
- Should update the current pagination to initially load 9 apps, not the current 12
- When the user scrolls and the bottom of the list is visible, load another 3 apps
- Add a fade in effect for the new apps similar to the fade in on the welcome wizard
- Preserve the scroll position of the user on the page so the page doesn't jump

**Comment by HollyJoyPhillips** [comment]
Hi @trankhacvy, there seems to be an issue when you open an app then navigate back the apps are duplicated: 

See video of loading the browse apps page > opening 'Starberry Tool Kit' > navigating back > observe duplication of the app 
https://www.dropbox.com/s/g715fj3ky6gzacp/DuplicateApps.mp4?dl=0
