### ISSUE TITLE
Internal users should be able to filter browse apps by query string

### ISSUE THREAD

**Issue by willmcvay** [reapit/foundations#2123]
**Background context or User story:**

_Internal users want to be able to filter the browse apps page to get a preview of the marketplace. To do this we will apply a query string to the browse apps page and filter by a list of client ids_

**Specification or Acceptance Criteria:**

- Query string should be `?preview=true` if present, don't perform the normal fetch and instead fetch apps from a client id whitelist.
- List of clientIds to be supplied by @HollyJoyPhillips 
- List of featured apps also to be filtered, again to be supplied by @HollyJoyPhillips 
- Client id lists should be hardcoded or supplied via Reapit Config
- API supports a list of clientIds as a filter https://dev.platformmarketplace.reapit.net/swagger/index.html called `ExternalAppId[]`
- Should render the returned featured and apps list as normal
- All other filters (isListed for example), to be removed so all expected results are returned

**Comment by vuhuucuong** [comment]
hi @willmcvay, I have a few questions on this:

> List of featured apps also to be filtered

so how do we filter featured apps, is it also by `clientIds` too, or by some other fields like `developerName`?


> All other filters (isListed for example), to be removed so all expected results are returned

Does it mean when `?preview=true`, we only send API with some basic fields like `pageSize, pageNumber` and `ExternalAppId` and remove all other fields, do we need to pass in `ClientId` field in here?
![image](https://user-images.githubusercontent.com/26746668/88255001-4ecd3280-cce1-11ea-976a-fd16a16bf340.png)

**Comment by willmcvay** [comment]
@vuhuucuong Yes the featured apps will be filtered by client id too in this instance. 

Page size, just set to be the length of the list of clientIds. Page number 1 obviously.

On clientId - I think it's a required field but not sure, will have to just experiment. I think it will work either way but will just have to see. Let me know if you hit a problem

**Comment by HollyJoyPhillips** [comment]
Hi @vuhuucuong Thanks for putting this together, looks good. Just one small thing, the main apps are duplicating: 
![image](https://user-images.githubusercontent.com/52408607/88514274-b0dbaf80-cfe1-11ea-8030-705c4190621b.png)
