### ISSUE TITLE
Marketplace should be refactored to use new Connect Session Auth module

### ISSUE THREAD

**Issue by willmcvay** [reapit/foundations#2125]
**Background context or User story:**

_The Connect  Session browser module and hook simplifies our auth flow. Each app that currently uses Cognito Auth should be refactored to reduce complexity. Ultimate aim is to deprecate Cognito Auth altogether_

**Specification or Acceptance Criteria:**

- Remove Cognito Auth from project and replace with Connect Session
- Remove "loginType" conditionals, this behaviour is deprecated
- Remove auth reducers, session, auth actions, sagas and any code tied to old auth flow like cookie getters

**Suggested solution:**

- Use the AML Checklist refactoring as a template https://github.com/reapit/foundations/pull/2092/files

**Comment by phmngocnghia** [comment]
@willmcvay 

`Marketplace also uses change password behaviours from Cognito auth. As this behaviour is only in Marketplace, incorporate this into the marketplace project so we can fully deprecate Cognito Auth.`

^ Do you mean move the change password logic to the marketplace?

**Comment by willmcvay** [comment]
Yes

**Comment by phmngocnghia** [comment]
@willmcvay I saw there's no change password feature on marketplace. I think this feature belong to developer portal

**Comment by willmcvay** [comment]
Sorry, my bad, it should be developer portal, will update
