### ISSUE TITLE
Able to access AML-Checklist login page after login

### ISSUE THREAD

**Issue by phmngocnghia** [reapit/foundations#2161]
- Login AML-Checklist: https://dev.aml-app.reapit.cloud/login
- After login try to access the login page: https://dev.aml-app.reapit.cloud/login
- Expected result: Should be redirected to the app if user has logged in

**Comment by willmcvay** [comment]
This is intentional, login is an unprotected route, am fine with people landing here if they like, they can always log in again. The idea is that protected routes are wrapped in the session provider, login is outside so it is unprotected.
