### ISSUE TITLE
Alert message box is not disappeared automatically when switching to another tab

### ISSUE THREAD

**Issue by tanphamhaiduong** [reapit/foundations#2173]
Steps to reproduce:
1. Click on 'Create New App' button and click on 'Create New App' button at "Before you start" box
2. Enter new app with the same name from pre-condition
3. Click on 'Yes' button
4. Enter two URL at "Redirect" and "Sign Out" field
5. Choose the type of area
6. Click on 'Next' button and observe at "Alert Message" box at the right corner of the browser
7. Click on another tab on the Menu
8. Observe alert message box

Actual Result: Alert message box is not disappeared automatically when  switching to another tab
- Video:  https://recordit.co/xWvM7EuM2r

Expected Result: Alert message box is disappeared automatically when  switching to another tab

**Comment by vuhuucuong** [comment]
This has already been fixed in other PR
