### ISSUE TITLE
Supporting embedding tenancy information in GET /properties/ API call

### ISSUE THREAD

**Issue by jk-trs** [reapit/foundations#2175]
I can see that currently, the GET /properties/ API call allows for landlord data to be embedded in the response, it would also be great to also have the option to embed all associated tenancies.

- Add embed option for 'tenancies' to GET /properties and GET /properties/{id}

**Comment by cbryanreapit** [comment]
Thanks for the feedback @jk-trs

We can certainly enhance to allow tenancies to embedded within the property response and we agree that's a good addition. I'll update this ticket accordingly to be specific to that requirement.

Right now, we don't support the ability to embed for entities that aren't directly related to the resource. For example, being able to use the properties endpoint and embed 'tenancies' is fine, but using 'tenancies.applicants' is not presently supported.

**Comment by plittlewood-rpt** [comment]
Work in PR

**Comment by plittlewood-rpt** [comment]
This has now gone out. Changelog updated

**Comment by plittlewood-rpt** [comment]
Hi @jk-trs - just to let you know that this has now been completed for you. Please refer to the changelog/docs for more details

https://dev.developers.reapit.cloud/api-docs
