### ISSUE TITLE
Filter GET /Properties/ API call by OfficeID

### ISSUE THREAD

**Issue by jk-trs** [reapit/foundations#2178]
We would like the option to filter properties included in the GET /Properties/ API call by the office that the property is assigned to.

- Add 'officeId' query string parameter to GET /properties
- String parameter 
- Allow this querystring to be provided more than once to provide searching for multiple officeIds
- To search any officeId associated to a property, not just the primary

**Comment by cbryanreapit** [comment]
Thank you for the request @jk-trs - we agree that this should be part of our API.

I'll amend original ticket now and we'll look to add this in.
