### ISSUE TITLE
Add field validation to Organisation and Billing tabs

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#2191]
**Summary**: This ticket is to add the backend validation requirements to the front end fields for the 'Organisation' and 'Billing' tab in the Developers Portal 

**Locations**: https://dev.developers.reapit.cloud/settings/organisation & https://dev.developers.reapit.cloud/settings/billing

### Organisations Tab 
Company Name: Max 250 chars
Telephone TBC
Website: max 100 chars & should be valid URI
VAT Number: max 50 chars 
Company Registration Number: max 50 chars 
About: max 250 chars 
National Insurance Number: max 20 characters
Building Name: max 35 chars
Building Number: max 8 chars
Address Line 1: max 35 chars 
Address Line 2: max 30 chars
Address Line 3: max 30 chars
Address line 4 max 30 chars 
Postcode: max 9 chars 

### Billing Tab
Billing Email: max 320 chars must be valid email address 
Billing Telephone: max 30 chars 
Billing Key Contact: max 150 chars

**Comment by vuhuucuong** [comment]
Hi @HollyJoyPhillips 
About those fields
- `Company Registration Number`
- `National Insurance Number`
- `Building Number`
should they be number only, or they can include letters?

**Comment by willmcvay** [comment]
@vuhuucuong They can (and usually do), contain letters so no need to validate this
