### ISSUE TITLE
Add content to the Reapit Connect Welcome page

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#2202]
**Summary:** As we now have the standalone Welcome page for Reapit Connect, this ticket is to the add the content: 

**Relates to ticket:** https://github.com/reapit/foundations/issues/2091

**Location:** https://dev.connect.reapit.cloud/welcome

**Task:** Add the content to the Reapit Connect Welcome page 

**Note:** 
Depending on the type of account the user has we should display certain information. For example:
- If account has a ‘developerId’ only, we should only display the ‘Developers Portals’ section.
- If account has a ‘clientId’ only, we should only display the ‘Marketplace’ section.
- If an account has both a ‘developerId’ and ‘clientId’, we should display both the Developer Portal & Marketplace sections (Developer Portal first).
- The format of the page should be text the left – graphic to the right for the Welcome to Reapit Connect section always. Any section that follows should be graphic to the left – text to the right. 
- Any other sections should follow the pattern of alternating the graphic and text left and right

### Main Heading 
Reapit Connect Logo: https://www.dropbox.com/s/qw5plx9z09a042b/ReapitConnectLogo.jpg?dl=0
Heading: Welcome to Reapit Connect
Subheading: Your account has been successfully created 
Text: Reapit Connect is our single sign on solution which allows you to seamlessly access products and services provided by Reapit Ltd.
Image: https://www.dropbox.com/s/us36sq8z7y1azij/MainHeadingGraphic.jpg?dl=0
See mockup: 
![image](https://user-images.githubusercontent.com/52408607/88644650-249dbb00-d0bb-11ea-9d33-c1177b6b04b2.png)

### Developer Portal 
Background colour: #209bd4
Button colour: #1e2454
Button Label: DEVELOPERS PORTAL
Link: https://developers.reapit.cloud 
Image: https://www.dropbox.com/s/c46lva14l6jvwxl/DeveloperPortalGraphic.jpg?dl=0
Heading: Developers Portal 
Subheading: A self-service platform  
Text: The Foundations Developer Portal provides a fully scalable, high-performance platform that developers can quickly onboard in minutes to build powerful new apps that can be published directly to the Reapit App Marketplace to extend Agency Cloud and Property Cloud functionality.
![image](https://user-images.githubusercontent.com/52408607/88644687-31baaa00-d0bb-11ea-8af3-accd58f41685.png)

### Marketplace
Background colour: # 1e2554
Button colour: #209bd4
Button Label: Marketplace
Link: https://marketplace.reapit.cloud 
Image: https://www.dropbox.com/s/kbblmi9z6yrydri/MarketplaceGraphic.jpg?dl=0
Heading: Marketplace 
Subheading: Enhancing the power of Agency Cloud
Text: The Foundations App Marketplace provides agencies with a variety of app and software integrations that have been tested and approved for immediate integration, allowing agencies to customise their Reapit CRM software to suit their business needs.
![image](https://user-images.githubusercontent.com/52408607/88644725-3b441200-d0bb-11ea-87cd-7951c2b546ad.png)

See mock up of ‘developerId’ only
![image](https://user-images.githubusercontent.com/52408607/88644794-4eef7880-d0bb-11ea-9fd5-f0c1a2da51f1.png)
See mockup of clientId’ only:  
![image](https://user-images.githubusercontent.com/52408607/88644813-53b42c80-d0bb-11ea-9717-be29959a467d.png)
See mockup of both ‘developerId’ & ‘clientId’:
![image](https://user-images.githubusercontent.com/52408607/88644836-5a42a400-d0bb-11ea-942a-b5ae721b67f1.png)

**Comment by willmcvay** [comment]
@trankhacvy Needs a bit of work on the UI to match the design please. Specifically, should be inside a responsive container so it has max widths at the standard breakpoints. See screenshots, looks crazy large on a bigger monitor.

Also, each of the sections should be equal height. You may need to set a fixed height on these, align the text vertically to find the sweet spot for the fixed height when responsive so the text is always inside the container. Should be trivial as the text is hardcoded.

Finally, the padding around the content is only 1 rem, on the design it was much larger - as this is a marketing page, we don't need to follow the usual Elements rules - just use custom CSS to make it look like the design. Thx

**Comment by HollyJoyPhillips** [comment]
Hi @trankhacvy, just a couple of points 

- Can you reduce the size of the Reapit Connect logo slightly please and align it with the 'Welcome to Reapit Connect' 
![image](https://user-images.githubusercontent.com/52408607/90011269-35445880-dc99-11ea-8650-3da4cb5b9a50.png)

- The sizes of the Developer Portal and the Marketplace sections are not the same:
See Developer Portal: 
![image](https://user-images.githubusercontent.com/52408607/90011136-f7473480-dc98-11ea-9a74-fcbe168e3edd.png)

See Marketplace: 
![image](https://user-images.githubusercontent.com/52408607/90011154-ff9f6f80-dc98-11ea-8e27-73cc879a41d1.png)

- Can you make the 'Marketplace' button the same size as the 'Developer Portal' so it looks consistent please
![image](https://user-images.githubusercontent.com/52408607/90011222-1f369800-dc99-11ea-9902-b8d8a35fd17d.png)

**Comment by HollyJoyPhillips** [comment]
Hi @trankhacvy Thanks for updating. Just a small thing but the image on the Developer Portal now looks stretched.

Can you revert the image size to what it was previously please and just reduce the size of the Marketplace image so it's the same height as the Developers Portal. 

Previous: 
![image](https://user-images.githubusercontent.com/52408607/90123780-45bb0880-dd57-11ea-8247-648df0365bab.png)

Current: 
![image](https://user-images.githubusercontent.com/52408607/90123822-54a1bb00-dd57-11ea-935a-4ae6b70861cd.png)
