### ISSUE TITLE
Update developer organisation migration routine to take account of developer edition subscription

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#2226]
The test migrations that have taken place did not take account of the requirement for developer edition for existing developers. Upon passing through the migration routine, developers should be:

- Added to the relevant group provisioning them dev edition access
- Have the agency cloud id against their organisation set to SBOX
- End to end testing

**Comment by plittlewood-rpt** [comment]
PR 2328 opened with this work
