### ISSUE TITLE
Developers should redirect to developer portal when landing on the Reapit Connect splash page

### ISSUE THREAD

**Issue by willmcvay** [reapit/foundations#2252]
**Background context or User story:**

_When landing on the Reapit Connect splash page, if I am a developer only, I should be redirected to developers.reapit.cloud_

**Specification or Acceptance Criteria:**

- Developer is defined as a user with ONLY a developerId in their access token ie not an admin, not a client
- Admins and clients with a developer id also, should still see the page
- Redirect should be to the production site in all cases, not to dev 
- Should land on the default apps route

**Comment by willmcvay** [comment]
There is a case we haven't considered. If I have a clientId and the clientId === 'SBOX' I also need to be redirected to developer portal - because in this case we know the user is a developer only

**Comment by phmngocnghia** [comment]
@willmcvay Is that count for 'cbryan@reapit.com' account: Admin account which has `clientId` = 'SBOX'
![image](https://user-images.githubusercontent.com/36730355/89763719-47998780-db1d-11ea-997a-ab7cc9918662.png)
