### ISSUE TITLE
Provide read/write access to certificates, warranty and policy information using Platform APIs

### ISSUE THREAD

**Issue by jonoldroyd** [reapit/foundations#2268]
I believe a third party API link to allow certificates (eg. Gas safety certificates) from third party suppliers to allow the certificate to be lifted from one software to an appropriate location on reapit. 

Currently this can work but the certificate would land in the ‘letters’ section of reapit. It would be more beneficial for your clients if this could locate in the ‘Lettings’ section.

**Comment by cbryanreapit** [comment]
@jonoldroyd thank you for your feedback. We agree that this would be a useful feature. I'll leave this issue open for now but we'll create a milestone once this has been prioritised and scheduled.

**Comment by cbryanreapit** [comment]
For internal: we will perform a deep dive on this functionality, outcome will be new tickets with API specifications

**Comment by plittlewood-rpt** [comment]
Hi @jonoldroyd - this ticket should have been updated a while ago apologies. This functionality is available already at the `/properties/{id}/certificates` endpoint.

#4687
