### ISSUE TITLE
Improve documentation for enquiries API

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#2276]
We should better explain that propertyIds are only a required part of an enquiry if the enquiry is from a sales/lettings applicant. At present, that relationship is not made clear.

![image](https://user-images.githubusercontent.com/34191069/89288832-30a2f300-d64e-11ea-948e-9c15728bf7a7.png)

- Append '. Used to indicate the properties that a sales or lettings applicant has an expressed an interest in.'

**Comment by plittlewood-rpt** [comment]
PR 2362 opened
