### ISSUE TITLE
Add GQL version to App Scaffolder

### ISSUE THREAD

**Issue by phmngocnghia** [reapit/foundations#228]
Create an internal react scaffold version that uses Apollo client to interact with GraphQL Service.
- Should be an option from CLI
- Should be based on Non Redux version of internal scaffolder
- Should also ensure other scaffolds are still working and updated to latest lib versions.

**Comment by vuhuucuong** [comment]
hi @willmcvay  & @HollyJoyPhillips . Here're the steps to test this:
- `cd` to `packages/react-app-scaffolder`
- `yarn scaffold`
- Select `Apollo GraphQL` option and generate an app
- Fill in the required data in `config.json`
- Add the generated's package name in the root `package.json` like this
![Screen Shot 2020-09-04 at 14 29 03](https://user-images.githubusercontent.com/26746668/92211955-735d2280-eebb-11ea-9e08-948ba3fdd753.png)
- `yarn workspace [app-name] start:dev`
- Login and open `console` to see the data from graphql server

**Comment by tanphamhaiduong** [comment]
Verified, Moving to DONE
