### ISSUE TITLE
Update ‘Coming Soon’ section

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#2345]
**Summary:** As we are approaching the release of the Marketplace we will need to make a few adjustments to the ‘Coming Soon’ section. This ticket is to remove/add images and to wrap images in mailto email links.

**Location:** https://dev.marketplace.reapit.cloud/apps

**Note**: Do not commit to codebase, store in config.json

### Email content 
**Text Version**
Email: Provided for each below
Subject: Reapit Foundations Marketplace – Coming Soon
Dear Reapit App Developer, 
I would like more information about your app featured in the ‘Coming Soon’ section of the Reapit Marketplace 
Regards

**Link Version:** 
href=mailto:INSERTEMAILHERE?subject=Reapit%20Foundations%20Marketplace%20-%20Coming%20Soon&body=Dear%20Reapit%20App%20Developer%2C%20%0A%0AI%20would%20like%20more%20information%20about%20your%20app%20featured%20in%20the%20%E2%80%98Coming%20Soon%E2%80%99%20section%20of%20the%20Reapit%20Marketplace%20%0A%0ARegards

**Task:** 
- **Replace** ‘Area’ with ‘YourKeys’ 
Image: https://www.dropbox.com/s/vviht86ugktm6uc/11Yourkeys.jpg?dl=0
Email: sales@yourkeys.com
**Add Link:** mailto:sales@yourkeys.com?subject=Reapit%20Foundations%20Marketplace%20-%20Coming%20Soon&body=Dear%20Reapit%20App%20Developer%2C%20%0A%0AI%20would%20like%20more%20information%20about%20your%20app%20featured%20in%20the%20%E2%80%98Coming%20Soon%E2%80%99%20section%20of%20the%20Reapit%20Marketplace%20%0A%0ARegards

- **Replace** ‘Starberry’ image
Image: https://www.dropbox.com/s/wcyqo0pt3gl56ti/2aStarberry.jpg?dl=0
Email: hello@starberry.tv
**Add link:** mailto:hello@starberry.tv?subject=Reapit%20Foundations%20Marketplace%20-%20Coming%20Soon&body=Dear%20Reapit%20App%20Developer%2C%20%0A%0AI%20would%20like%20more%20information%20about%20your%20app%20featured%20in%20the%20%E2%80%98Coming%20Soon%E2%80%99%20section%20of%20the%20Reapit%20Marketplace%20%0A%0ARegards

- **Add link** for ‘Vyomm’
Email: hello@vyomm.com
Link: mailto:hello@vyomm.com?subject=Reapit%20Foundations%20Marketplace%20-%20Coming%20Soon&body=Dear%20Reapit%20App%20Developer%2C%20%0A%0AI%20would%20like%20more%20information%20about%20your%20app%20featured%20in%20the%20%E2%80%98Coming%20Soon%E2%80%99%20section%20of%20the%20Reapit%20Marketplace%20%0A%0ARegards 

- **Add link** for ‘Yomdel’ 
Email: sales@yomdel.com
Link: mailto:sales@yomdel.com?subject=Reapit%20Foundations%20Marketplace%20-%20Coming%20Soon&body=Dear%20Reapit%20App%20Developer%2C%20%0A%0AI%20would%20like%20more%20information%20about%20your%20app%20featured%20in%20the%20%E2%80%98Coming%20Soon%E2%80%99%20section%20of%20the%20Reapit%20Marketplace%20%0A%0ARegards

- Replace 'iamproperty' with 'Integrated Interest' 
Image: https://www.dropbox.com/s/lxeq4tveo8n1rfn/12Integrated.jpg?dl=0
Email: info@integratedinterest.com
Link: mailto:info@integratedinterest.com?subject=Reapit%20Foundations%20Marketplace%20-%20Coming%20Soon&body=Dear%20Reapit%20App%20Developer%2C%20%0A%0AI%20would%20like%20more%20information%20about%20your%20app%20featured%20in%20the%20%E2%80%98Coming%20Soon%E2%80%99%20section%20of%20the%20Reapit%20Marketplace%20%0A%0ARegards

- **Add Link** for 'Zero Deposit'
Email: enquiries@zerodeposit.com
Link: mailto:enquiries@zerodeposit.com?subject=Reapit%20Foundations%20Marketplace%20-%20Coming%20Soon&body=Dear%20Reapit%20App%20Developer%2C%20%0A%0AI%20would%20like%20more%20information%20about%20your%20app%20featured%20in%20the%20%E2%80%98Coming%20Soon%E2%80%99%20section%20of%20the%20Reapit%20Marketplace%20%0A%0ARegards

- **Add Link** for 'TwentyCi'
Email: enquiries@twentyci.co.uk
Link: mailto:enquiries@twentyci.co.uk?subject=Reapit%20Foundations%20Marketplace%20-%20Coming%20Soon&body=Dear%20Reapit%20App%20Developer%2C%20%0A%0AI%20would%20like%20more%20information%20about%20your%20app%20featured%20in%20the%20%E2%80%98Coming%20Soon%E2%80%99%20section%20of%20the%20Reapit%20Marketplace%20%0A%0ARegards

**Comment by tanphamhaiduong** [comment]
pls refer the branch `feat/2345-comming-soon-app`

**Comment by HollyJoyPhillips** [comment]
Please update SMS Speedway image with this: 
![SMS2](https://user-images.githubusercontent.com/52408607/90814935-ccf11900-e321-11ea-9607-c503d7cfcdff.jpg)


Email: support@sms-speedway.com
Link: mailto:support@sms-speedway.com?subject=Reapit%20Foundations%20Marketplace%20-%20Coming%20Soon&body=Dear%20Reapit%20App%20Developer%2C%20%0A%0AI%20would%20like%20more%20information%20about%20your%20app%20featured%20in%20the%20%E2%80%98Coming%20Soon%E2%80%99%20section%20of%20the%20Reapit%20Marketplace%20%0A%0ARegards

**Comment by HollyJoyPhillips** [comment]
Hi @phmngocnghia Thanks for updating the coming soon section. Just a small point on the images, there seems to be a white border on the image now, the banner should be edge to edge: 

![image](https://user-images.githubusercontent.com/52408607/91169592-89a2fb80-e6cf-11ea-952f-d4e0fd2ffb5d.png)

If you copy the actual image onto a black background you can see there is no white border: 

![image](https://user-images.githubusercontent.com/52408607/91169655-9f182580-e6cf-11ea-8154-d3f4218c0a72.png)


We would also like to update one of the images and add 4 more, see below: 

**Update** ‘Twenty CI’ image for this: 
**Image:** https://www.dropbox.com/s/suabzl41uv8j7vs/TwentyCiProspect.jpg?dl=0
**Email**: enquiries@twentyea.co.uk
**Add link**: mailto:enquiries@twentyea.co.uk?subject=Reapit%20Foundations%20Marketplace%20-%20Coming%20Soon&body=Dear%20Reapit%20App%20Developer%2C%20%0A%0AI%20would%20like%20more%20information%20about%20your%20app%20featured%20in%20the%20%E2%80%98Coming%20Soon%E2%80%99%20section%20of%20the%20Reapit%20Marketplace%20%0A%0ARegards


**Add** image for another 'TwentyCi' 
**Image:** https://www.dropbox.com/s/g8ocqd87o7tb1oe/TwentyCiVMC.jpg?dl=0
**Email**: enquiries@viewmychain.com
**Add link**: mailto:enquiries@viewmychain.com?subject=Reapit%20Foundations%20Marketplace%20-%20Coming%20Soon&body=Dear%20Reapit%20App%20Developer%2C%20%0A%0AI%20would%20like%20more%20information%20about%20your%20app%20featured%20in%20the%20%E2%80%98Coming%20Soon%E2%80%99%20section%20of%20the%20Reapit%20Marketplace%20%0A%0ARegards


**Add** image for another 'SMS Speedway'
**Image:** https://www.dropbox.com/s/1dqf1fnnyg576q9/SMSMobile.jpg?dl=0
**Email:** support@sms-speedway.com
**Add link**: mailto:support@sms-speedway.com?subject=Reapit%20Foundations%20Marketplace%20-%20Coming%20Soon&body=Dear%20Reapit%20App%20Developer%2C%20%0A%0AI%20would%20like%20more%20information%20about%20your%20app%20featured%20in%20the%20%E2%80%98Coming%20Soon%E2%80%99%20section%20of%20the%20Reapit%20Marketplace%20%0A%0ARegards

**Add** image for 'I am Property' (previously removed) 
**Image:** https://www.dropbox.com/s/o7wmc9xyyc6nbx7/3IAMProperty.jpg?dl=0
**Email:** app-support@iamproperty.com 
**Add link:** mailto:app-support@iamproperty.com?subject=Reapit%20Foundations%20Marketplace%20-%20Coming%20Soon&body=Dear%20Reapit%20App%20Developer%2C%20%0A%0AI%20would%20like%20more%20information%20about%20your%20app%20featured%20in%20the%20%E2%80%98Coming%20Soon%E2%80%99%20section%20of%20the%20Reapit%20Marketplace%20%0A%0ARegards

**Add** image ‘Reapit Payments'
**Image:**https://www.dropbox.com/s/cf7fg4y5g1r5afp/ReapitPayments.jpg?dl=0
**Email:** hphillips@reapit.com 
**Add link**: mailto:hphillips@reapit.com?subject=Reapit%20Foundations%20Marketplace%20-%20Coming%20Soon&body=Dear%20Reapit%20App%20Developer%2C%20%0A%0AI%20would%20like%20more%20information%20about%20your%20app%20featured%20in%20the%20%E2%80%98Coming%20Soon%E2%80%99%20section%20of%20the%20Reapit%20Marketplace%20%0A%0ARegards

**Comment by HollyJoyPhillips** [comment]
@phmngocnghia Unable to see the changes? 
![image](https://user-images.githubusercontent.com/52408607/91340528-1503b600-e7d0-11ea-8efe-42fd6724151c.png)
