### ISSUE TITLE
Transaction history showing month before created date

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#2346]
**Summary**: Currently logged in as a developer that was created 03/08/20. When viewing the 'Transaction History' on the 'Cost Explorer' it is showing transaction history for the month of July. Should only show the months from the created date. 

**Location:** https://dev.developers.reapit.cloud/analytics/costexplorer

**To replicate:**
Log in as hollyjoyphillips+test@gmail.com (message me for PW) 
Go to: https://dev.developers.reapit.cloud/analytics/costexplorer
See 'Transaction History' display month of July 

![image](https://user-images.githubusercontent.com/52408607/89920109-f0b2b180-dbf3-11ea-95f2-6fbd08623af5.png)

**Comment by tanphamhaiduong** [comment]
Verified on dev

**Comment by tanphamhaiduong** [comment]
Moving to In progress because @HollyJoyPhillips  want  to hide previous section if there is no previous section
