### ISSUE TITLE
Investigate and potentially implement Storybook 6 for Elements

### ISSUE THREAD

**Issue by willmcvay** [reapit/foundations#2354]
**Background context or User story:**

_See https://medium.com/storybookjs/storybook-6-0-1e14a2071000, we should be able to get the benefits of Storybook Controls see https://medium.com/storybookjs/storybook-controls-ce82af93e430_ 

**Specification or Acceptance Criteria:**

- See if it is possible to upgrade without code changes from v5 to v6.
- If it looks trivial, implement and add controls for our components - docs say this should be auto codegenerated from our TS definitions
- Ensure the HTML codegen plugin is not broken - we need to be able to support our HTML only users as well as React
- If it's possible but not trivial, advise on how best to break the task down

**Comment by tanphamhaiduong** [comment]
As discuss with @willmcvay after change to ver 6.0 we need to change the syntax from storiesOf to new syntax. This is a big deal, so this ticket will leave and we'll get back after have time
