### ISSUE TITLE
Add 'main image' flag to '/propertyImages/' endpoints

### ISSUE THREAD

**Issue by dalereapit** [reapit/foundations#2355]
**Background context or User story:**
As a developer I would like to be able to determine if the image returned is the main image of the property. This is important for us as we're rewriting the property projector which uses the main image to show the outside of the property.

**How the option appears in RPS:**
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/43369700/90033946-f07bea00-dcb7-11ea-82bd-7a3ef6e5c138.png)

**Specification or Acceptance Criteria:**
1.  Have the ability to determine the main image of a given property.

**Suggested solution:**
My suggestion would be to have a boolean flag which is set to `true` if the image is the main image, however, I'm happy for any other implementation.

**Comment by plittlewood-rpt** [comment]
Hi @dalereapit  thanks for this. Seems sensible. I'll discuss with the team when we plan next week's work and we'll get back to you

**Comment by cbryanreapit** [comment]
No longer a requirement
