### ISSUE TITLE
Browse apps infinite scroll does not load if viewed on a large screen

### ISSUE THREAD

**Issue by willmcvay** [reapit/foundations#2371]
**Background context or User story:**

_Navigate to the browse apps page on a large monitor, or zoom out in your browser, so all the initially loaded apps are visible eg on https://dev.marketplace.reapit.cloud/apps?preview=true. Twelve apps are visible in the main section however, there should be 14. The lazy loaded apps never load on scroll_

**Specification or Acceptance Criteria:**

- The lazy loaded apps should load following the initial load because that section of the page is already visible

**Comment by tanphamhaiduong** [comment]
@willmcvay could you give me the screen solution to replicate it ?

**Comment by willmcvay** [comment]
@tanphamhaiduong The resolution is irrelevant, just visit https://dev.marketplace.reapit.cloud/apps?preview=true then zoom out until you can see 12 apps in the main view. Refresh then scroll. There should be 14, the last 2 never load
