### ISSUE TITLE
Sentry 'TypeError' being reported when accepting a member invite

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#2372]
**Summary:** Sentry is reporting a 'TypeError' after clicking 'Accept' on a member invitation

**Error:** 
TypeError
Cannot set property onunhandledrejection of [object Object] which has only a getter

**Link**: https://sentry.io/organizations/reapit-ltd/issues/1840384553/?project=1885603&referrer=slack

**To replicate:** Log into Developer Portal > Invite New Member > click on 'Respond to Invitation' link in email > accept. 
Notice the error occur

**Comment by tanphamhaiduong** [comment]
This bug relate to redirect URL, Moving to in review, and I'll test again after @willmcvay fix it
