### ISSUE TITLE
Generate an email to ‘Administrators’ for installs/uninstalls 

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#2383]
**Summary**: Users (non admins) are presented with a message to contact their Administrators when they click on ‘Install’ or ‘Uninstall’ on apps in the client-side Marketplace. We should include an option to send an email to their administrators

**Task**: ‘Send Request’ should auto generate an email to all administrators of that organisation with the following: 

### Install Content 
Subject: App Installation Request – APP NAME
Dear NAME OF ADMINISTRATOR, 
USER has requested an installation of APP NAME for your organisation from the Reapit Foundations Marketplace.

Message: 
OPTIONAL

For more information and to install, please log into Agency Cloud > click ‘Apps’ > Browse and open ‘APP NAME’ > click ‘Install’ 

Alternatively, please click here to log into the Marketplace to install

Regards
Reapit Foundations

**Note**: Click here should include the APP ID on the URL e.g. https://dev.marketplace.reapit.cloud/apps/2030367e-1dd3-47a8-ae59-a57605a1f460

### Uninstall Content
Subject: Uninstall App Request – APP NAME
Dear NAME OF ADMINISTRATOR, 

USER has requested to uninstall APP NAME from all users of your organisation. 

Message: 
OPTIONAL

To uninstall, please log into Agency Cloud > click ‘Apps’ > Browse and open ‘APP NAME’ > click ‘Uninstall’ 

Alternatively, please click here to log into the Marketplace to uninstall

Regards
Reapit Foundations

**Note**: Click here should include the APP ID on the URL e.g. https://dev.marketplace.reapit.cloud/apps/2030367e-1dd3-47a8-ae59-a57605a1f460

**Comment by cbryanreapit** [comment]
No longer a known requirement
