### ISSUE TITLE
Expand GraphQL Service service for Documents entity

### ISSUE THREAD

**Issue by vuhuucuong** [reapit/foundations#2445]
**Background context or User story:**

_As we move to a public Alpha release of the GraphQL service, we should aim to be service complete for the Platform API. This means for each platform entity https://developers.reapit.cloud/swagger we should have GQL schema definitions and resolvers for each of the endpoints. For each ticket in this milestone, we need to do the following:_

**Specification or Acceptance Criteria:**

- Create a Query resolver for each GET endpoint
- Queries should map query string params for the platform to GQL variables as closely as possible
- Queries and mutations should be strongly typed
- Where appropriate, create a Mutations for POST, PATCH, PUT and DELETE endpoints
- Mutations should map correctly to platform body requests where relevant

**Comment by ant066** [comment]
Hi @willmcvay, in Documents entity, we have download document endpoint at `/documents/{id}/download`, it returns a blob file like below. Do we need to expand it in graphql service?
<img width="516" alt="Screen Shot 2020-08-25 at 1 32 05 PM" src="https://user-images.githubusercontent.com/30467048/91132570-6c722b00-e6d7-11ea-86bd-d206cfcaba49.png">
