### ISSUE TITLE
[Developers] Should let developer invite one user only 1 time

### ISSUE THREAD

**Issue by tanphamhaiduong** [reapit/foundations#2475]
Pre-condition: the user had accepted the invitation from a developer
Steps to reproduce:
1. Go to the developer's site as a developer
2. Go to the "Organisation" page from "Settings" tab in navigation's menu
3. Scroll to "Members" part and click on "Invite new member" button, invite the user from pre-condition
4. Observe Results:
![image](https://user-images.githubusercontent.com/22660833/91254123-aa308b80-e78b-11ea-8b45-aa0d5ce9e2fd.png)

Actual Result: Developer can send the invitation to the user had accepted one invitation
Expected Result: Should let developer invite one user only 1 time

**Comment by nphivu414** [comment]
Hi @tanphamhaiduong ,
I've already discussed with @willmcvay  and @HollyJoyPhillips about this issue. The current behaviour is correct for now, no need to fix anything so I'll close it.

Thanks
