### ISSUE TITLE
[Developers] Should open "How can we help?" chat-box in one time only

### ISSUE THREAD

**Issue by tanphamhaiduong** [reapit/foundations#2476]
Steps to reproduce:
1. Go to the "Help" page and click on the "Start Chat" button from 'Need Help' part
2. Click on "How can we help you?" button or "Start Chat" button multiple times and observe

Actual Result: Multiple chat-box is opened and overrode in each other
https://recordit.co/A2M5CzZWzh

Expected Result: Should open chat-box in one time only

**Comment by HollyJoyPhillips** [comment]
Hi @trankhacvy I'm still seeing the same behaviour where i can create multiple windows?
