### ISSUE TITLE
Coming soon apps are missing in prod

### ISSUE THREAD

**Issue by willmcvay** [reapit/foundations#2484]
**Background context or User story:**

_they should not be - see sceenshot_

<img width="1028" alt="Screenshot 2020-08-26 at 07 03 43" src="https://user-images.githubusercontent.com/4630495/91267071-75600c80-e76a-11ea-9c96-b396e48854d2.png">

**Comment by tanphamhaiduong** [comment]
hi @willmcvay for coming soon apps, now we load apps with the Ids in the config.json, when we move to production, in the production we don't have any coming soon app created and provide the id for the config.json, so it's blank now
