### ISSUE TITLE
Health Check API endpoints

### ISSUE THREAD

**Issue by adam-brewer-mab** [reapit/foundations#2488]
Summary of Request:

Could the Reapit Foundation Marketplace API include a health check endpoint that can be called to check if foundations APIs are up.

This would be useful so that consumers of foundations APIs can setup alerting to be automatically notified if Reapt’s APIs are down.

Expected Behaviour

The health check endpoint will return a 200 response if the Reapit APIs are up.

**Comment by plittlewood-rpt** [comment]
Hi @adam-brewer-mab - we have recently added Platform to our Global status page at [status.reapit.com](https://status.reapit.com). Details of any incidents will be posted here, and this is something you can also subscribe to
