### ISSUE TITLE
The GraphQL service is throwing a type error

### ISSUE THREAD

**Issue by willmcvay** [reapit/foundations#2500]
**Background context or User story:**

_See screenshot from Geo Diary, appears to be in relation to embedded behaviour_
<img width="1268" alt="Screenshot 2020-08-26 at 16 41 45" src="https://user-images.githubusercontent.com/4630495/91325407-0f4fa580-e7bb-11ea-9562-b17795912acb.png">

**Comment by vuhuucuong** [comment]
This's already been fix in another PR
![image](https://user-images.githubusercontent.com/26746668/91385242-aa4b8c80-e85a-11ea-854a-f3ecea07c502.png)
