### ISSUE TITLE
AML App should display friendly errors to users

### ISSUE THREAD

**Issue by willmcvay** [reapit/foundations#2512]
**Background context or User story:**

_Currently when the AML App gets a server error, we do not display to users that something has failed. We should show errors in a pop up notification_

**Comment by HollyJoyPhillips** [comment]
@tanphamhaiduong See bug: https://github.com/reapit/foundations/issues/2548 getting a 403 failed to upload file but not seeing a user facing notification?

**Comment by tanphamhaiduong** [comment]
hi @HollyJoyPhillips the bug #2548 I can't replicate it, so I think let the ticket in review and will fix when #2548 can replicate the bug
