### ISSUE TITLE
List of 'ID Types' not populating on AML

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#2518]
**Summary**: On the primary and secondary ID we pre-populate the ID Types dropdown menu. However. this is currently not working;

**Steps**: Open any unchecked record in AML and view primary ID - observe the 'ID Type' drop down menu is not populated 

![image](https://user-images.githubusercontent.com/52408607/91487758-2e773180-e8a6-11ea-8097-b395561f85a6.png)

**Comment by trankhacvy** [comment]
@HollyJoyPhillips  @willmcvay It's a back-end issue and they've already fixed.
