### ISSUE TITLE
Update dev pipeline to deploy to new dev infra

### ISSUE THREAD

**Issue by willmcvay** [reapit/foundations#2519]
**Background context or User story:**

_Currently we have to deploy our production apps to the new dev infra manually. This should now be automated and the old dev infra scripts should be deprecated_

**Specification or Acceptance Criteria:**

- For the 8 apps we already have on the new dev infra, deploy automatically using the new dev scripts
- Add to this web components and the web components config server

**Comment by phmngocnghia** [comment]
I don’t understand this part of the task description. Could you help me to clarify it?

> Add to this web components and the web components config server

**Comment by phmngocnghia** [comment]
I'm also not really clear about the description of the task: only 8 apps that already have on the new dev infra will be deployed automatically, other apps will be ignored, and deploy manually? The old infra dev script (release:dev) will deprecated, and we are using `serverless deploy` command for now to deploy the app?

**Comment by tanphamhaiduong** [comment]
Verified, moving to QA
