### ISSUE TITLE
SMB App should redirect to Users route from root path

### ISSUE THREAD

**Issue by willmcvay** [reapit/foundations#2524]
**Background context or User story:**

_After login, currently you land on root path. If you land on this path you should be redirected to the default path, the users path. I should not be able to direct to the root path. Also update the redirect URIs in dev and prod so Reapit Connect uses the users route as the default path_

**Comment by ant066** [comment]
Hi @willmcvay, Can you help me add following uris to redirect URIs, the smb login have `redirect_mismatch` problem when use `/users` path as redirect URL:

```
http://localhost:8080/users
https://smb-app.dev.paas.reapit.cloud/users
https://smb-app.reapit.cloud/users
```

And help me add redirect URI to SMB production config. I updated it on development & local config but production I cannot.
```json
"connectLoginRedirectPath": "/users"
```

**Comment by willmcvay** [comment]
@ant066 Just add this as a constant - it's not a variable so doesn't make sense in config

**Comment by AshDeeming** [comment]
Tested & working as Expected with redirect to /Users
