### ISSUE TITLE
[Developers] Should let developer invite one user only 1 time

### ISSUE THREAD

**Issue by tanphamhaiduong** [reapit/foundations#2535]
Pre-condition: the user had accepted the invitation from a developer
Steps to reproduce:
1. Go to the developer's site as a developer
2. Go to the "Organisation" page from "Settings" tab in navigation's menu
3. Scroll to "Members" part and click on "Invite new member" button, invite the user from pre-condition
4. Observe Results:

Actual Result: Developer can send the invitation to the user had accepted one invitation

![Uploading image.png…]()

Expected Result: Should let developer invite one user only 1 time

**Comment by willmcvay** [comment]
The solution is to filter in the front end so that each invite is only shown once. 
- If the user is active, or pending, don't show any previous invites
- Only filter out  multiple instances of pending and deactivated invites

**Comment by HollyJoyPhillips** [comment]
This is good to go

**Comment by HollyJoyPhillips** [comment]
FYI waiting for platform update (https://github.com/reapit/foundations/issues/2656) before completing test
