### ISSUE TITLE
Files uploaded to 'Address Information' section not saving

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#2548]
**Summary**: On the 'Address Information' section on the AML app, it's not saving any uploaded files. 

**Location**: https://aml-app.reapit.cloud/checklist-detail/MLK13000122

**Steps to replicate:** 
Open any record
Open 'Address History' section 
Upload file & Save
Notice the file has failed to save 

**Sentry error:** https://sentry.io/organizations/reapit-ltd/issues/1492059699/?project=1885615&referrer=slack

**Comment by tanphamhaiduong** [comment]
@HollyJoyPhillips Could you give me more information to replicate it, or could you test again. I can't replicate it
