### ISSUE TITLE
An error was encountered with the requested page.

### ISSUE THREAD

**Issue by buonzz** [reapit/foundations#2552]
**Describe the bug**
after hitting ```yarn start``` and visiting http://localhost:8080/
* it redirects here first https://dev.connect.reapit.cloud/authorize?response_type=code&client_id=34anjh9l7ikamurnu77i453ba2&redirect_uri=http://localhost:8080&state=%2F%3F
* it then redirects to this page https://dev.connect.reapit.cloud/error?error=server_error&client_id=34anjh9l7ikamurnu77i453ba2
saying **An error was encountered with the requested page.**

**To Reproduce**

1. Create a new app in developer portal as instructed in https://developers.reapit.cloud/api-docs/developer-portal
2. Create a new React app locally using https://foundations-documentation.reapit.cloud/app-development/create-react-app-template
3. configure src/reapit.config.json file
4. ```yarn install``` then ```yarn start```
5. visit  http://localhost:8080

here is the contents of my src/reapit.config.json file

```
{
  "appEnv": "local",
  "connectClientId": "34anjh9l7ikamurnu77i453ba2",
  "connectOAuthUrl": "https://dev.connect.reapit.cloud",
  "platformApiUrl": "https://dev.platform.reapit.cloud",
  "connectUserPoolId": "eu-west-2_hbt0B7yys"
}
```

**Expected behaviour**
it should display the "Welcome to Reapit Foundations" welcome page as shown in https://foundations-documentation.reapit.cloud/app-development/create-react-app-template

**Screenshots**
https://drive.google.com/file/d/1Yt-R5oh55BVmPvjSeMNiLXOW4YG-WUt7/view?usp=sharing

**Device (please complete the following information for web issues):**
 - Device: Mac
 - OS: MacOS Catalina 10.15.6
 - Browser: Chrome
 - Version: 84.0.4147.135 (Official Build) (64-bit)

**Comment by plittlewood-rpt** [comment]
Hi @buonzz 

You should now be using the production URLs as per the email the registered developers were sent last week. Can you confirm if you received it? If not please jump on live chat and I'll get you a copy of the new information

**Comment by plittlewood-rpt** [comment]
Hi @buonzz 

You should now be using the production URLs as per the email the registered developers were sent last week. Can you confirm if you received it? If not please jump on live chat and I'll get you a copy of the new information

**Comment by buonzz** [comment]
hi, @plittlewood-rpt  thanks for the response. I havent received anything in my work email ( darwin at utilihub dot io)
most likely its sent to  my CTO's inbox as he owns the registered email account. will ask him.

**Comment by plittlewood-rpt** [comment]
Information provided on live chat - closing

**Comment by buonzz** [comment]
hi @plittlewood-rpt 

unfortunately, still did not work.

i've used the  production urls in src/reapit.config.json

```
{
  "appEnv": "local",
  "connectClientId": "34anjh9l7ikamurnu77i453ba2",
  "connectOAuthUrl": "https://connect.reapit.cloud",
  "platformApiUrl": "https://platform.reapit.cloud",
  "connectUserPoolId": "eu-west-2_eQ7dreNzJ"
}
```

but what happens now is, im getting this series of redirects:

* https://connect.reapit.cloud/authorize?response_type=code&client_id=34anjh9l7ikamurnu77i453ba2&redirect_uri=http://localhost:8080&state=%2F%3F
* https://connect.reapit.cloud/error?error=redirect_mismatch&client_id=34anjh9l7ikamurnu77i453ba2

Screenshot: https://drive.google.com/file/d/1er0Oxp0BCXVwfP1r16cq6aEAM-jXr8dC/view?usp=sharing

thank you

**Comment by buonzz** [comment]
alright, figured it out. Its due to the fact that in my App settings, the "REDIRECT URI(S) *" is set to 

```
http://localhost:8080/
```

but yarn is starting it as this url (without the forward slash)
```
http://localhost:8080
```

**Comment by willmcvay** [comment]
@buonzz This is not related to Yarn. You can set your redirect_uri to whatever you like in your app however, it has to match exactly what we hold in Reapit Connect as the redirect_uri, as per the OAuth spec. You can specify a different redirect path by passing a different relative path to where our connect session module is instantiated in the `connect-session.ts` file in your CRA - the key you need to set is `connectLoginRedirectPath` - by default the value is `""` but in your case it will work if you set it to `"/"`. See https://foundations-documentation.reapit.cloud/app-development/connect-session#basic-browser-usage for more details. Hope this explains.
