### ISSUE TITLE
Developer portal Invite - email instructions on setting up login credentials not received

### ISSUE THREAD

**Issue by buonzz** [reapit/foundations#2566]
**Describe the bug**
When you go to https://developers.reapit.cloud/settings/organisation
and invite a new member, the invited developer only receives the initial email with subject 
"You've been invited to join Movinghub!"
after opening the email and clicking the "Respond to invitation" link
it doesn't send any other email after that

**To Reproduce**
Steps to reproduce the behaviour eg:
1. Go to https://developers.reapit.cloud/settings/organisation while logged-in as admin account
2. Click on  "INVITE NEW MEMBER" button
3. Input the email of developer and other info
4. Have the developer check for the email with subject "You've been invited to join Movinghub!"
5. Have the developer click the "Respond to invitation" link
6. Have the developer click the "CONFIRM" button in the invitation
7. Should see a page confirming the invite confirmation

```
Thank you for confirming your invite to Reapit Foundations.

If you already had a Developer account, you can use your existing credentials to login to the Developers Portal. If not, you will shortly receive an email with instructions on setting up your login credentials.
```
8. No email was sent to the developer, even checking spam, cant find any email.

**Expected behaviour**
It should send a second email, with instructions on setting up the login credentials

**Screenshots**
https://drive.google.com/file/d/1gKOjZ0XlaNWdbFBjQv_EFDv8j19KTyq1/view?usp=sharing

**Device (please complete the following information for web issues):**
 * Device: Mac
 * OS: MacOS Catalina 10.15.6
 * Browser: Chrome
 * Version: 84.0.4147.135 (Official Build) (64-bit)

**Additional context**
- Already checked the Spam folder
- Im sure the email is correct
- If i try to forgot password using the email invited, it just simply says 
"Could not reset password for the account, please contact support or try again"

**Comment by plittlewood-rpt** [comment]
Hi @buonzz  - sorry I hadn't seen this issue pop up. Can you confirm if you've been able to login now? I know my colleague Holly has dealt with a few of these, which seem to have been caused as we migrated over to production. Let me know if you've still got issues and we'll get on this.

**Comment by buonzz** [comment]
im not able to actually login still, as i havent had the chance to setup the login credentials, being i did not received the second email. by any chance that could be resent, I checked in admin https://developers.reapit.cloud/settings/organisation and the only option there is to "disable", but nothing to reset password or something. I could not delete and re-add myself either

**Comment by plittlewood-rpt** [comment]
Hi @buonzz - we did have an issue with invitations last week so perhaps it got caught up in this. Can you send me an email noting the email address your account should have been created under so I can track it down. My email address is plittlewood [at] reapit [dot] com

**Comment by buonzz** [comment]
@plittlewood-rpt  email sent. thank you 👍

**Comment by plittlewood-rpt** [comment]
Thanks @buonzz  - I've got it. I'll check it out and get back to you

**Comment by plittlewood-rpt** [comment]
@buonzz  I've just replied via email

**Comment by plittlewood-rpt** [comment]
Confirmed with @buonzz  that issue is now resolved. Closing
