### ISSUE TITLE
As a User I want to download a sample file for uploading offices and user

### ISSUE THREAD

**Issue by tanphamhaiduong** [reapit/foundations#2590]
**Background context or User story:**
- As a user I want to download a sample file for uploading offices and user in SMB

**Specification or Acceptance Criteria:**
- Have a `Download Sample` button next to `Upload File` to get sample CSV file before upload

**Suggested solution:**
- Add button to download Sample file csv for filling up the data before upload

**Comment by AshDeeming** [comment]
Hi @trankhacvy 
I can see 'Download Sample' on the Office page but not showing on the User page:
![image](https://user-images.githubusercontent.com/61687775/92580827-c998df80-f286-11ea-82b4-c9bca55aa035.png)
![image](https://user-images.githubusercontent.com/61687775/92580858-d289b100-f286-11ea-8ff2-e96cc1603d75.png)

It was also noticed that the spacing between the 'upload file' and 'Download Sample' buttons differ, please could these be aligned correctly to match.
