### ISSUE TITLE
As a User, I want to upload SMB users By CSV

### ISSUE THREAD

**Issue by tanphamhaiduong** [reapit/foundations#2594]
As a User, I want to upload SMB users By CSV

**Screenshots**
http://recordit.co/1D1unEm2Fp.gif

**Comment by AshDeeming** [comment]
Hi @ant066 - 

If i Download the file, add a single user, i get an error based on the original download - not my additional user:
![image](https://user-images.githubusercontent.com/61687775/92921139-714f1280-f42b-11ea-9457-619b2a18276c.png)

Further to this, the new user included on the upload file doesn't appear on the list. 
![image](https://user-images.githubusercontent.com/61687775/92921338-c9861480-f42b-11ea-8f65-f3a57af5fb70.png)

**Comment by ant066** [comment]
`Further to this, the new user included on the upload file doesn't appear on the list.`
Hi @AshDeeming, I found the limit rows records are 30 when uploading csv file at https://github.com/reapit/foundations/issues/652.
and the new user record is 275 that why it doesn't appear.

**Comment by ant066** [comment]
@AshDeeming I tried to upload new user via this csv file, it still work.
[UPLOAD_USER.zip](https://github.com/reapit/foundations/files/5216496/UPLOAD_USER.zip)

FYI: Office column must be Office ID, not office name. 
<img width="566" alt="Screen Shot 2020-09-14 at 13 35 37" src="https://user-images.githubusercontent.com/30467048/93051841-4c5ad980-f68f-11ea-9a9c-f68dc8ff75b8.png">
