### ISSUE TITLE
Create Messages API so that developers can post app notifications to Desktop CRM

### ISSUE THREAD

**Issue by willmcvay** [reapit/foundations#2602]
**Background context or User story:**

_One of our developer partners (Area), has been attempting to use Chrome notifications to display info to users of their integrated desktop app. This is being blocked by our integrated Chromium solution and is probably not the best UX we can offer to users._

**Specification or Acceptance Criteria:**

- This has been discussed internally before but having spoken to @PaulHaynes, suggestion to create a platform API over the Messages table in RPS DB, so developers can post notifications from their apps to be picked up in the native messages inbox in RPS.
- @plittlewood-rpt @cbryanreapit @HollyJoyPhillips @RWilcox-Reapit happy to discuss internally

**Comment by cbryanreapit** [comment]
The Tasks API includes the messaging functionality
