### ISSUE TITLE
[Foundations REST API ] How to store credentials (api keys) of an external 3rd party API?

### ISSUE THREAD

**Issue by buonzz** [reapit/foundations#2606]
**Summary**
If lets say I wanted to develop an app and integrate a 3rd party API to reapit. The end-user (in this case, the agent) need to provide the credentials (e.g api key, user/pass etc). 

**Question** 
what API endpoint to persist these information? so that the next time the agent logged in to Connect Session, we could pull that info and make authenticated requests to a 3rd party api?

**Comment by plittlewood-rpt** [comment]
Hi @buonzz  - I'm not sure storing this information in our system would be the best approach here. Would each user really need to have their own credentials or would it be a set of credentials for the company as a whole? Can you provide more of a summary of the app you have in mind?

**Comment by buonzz** [comment]
hi @plittlewood-rpt  in movinghub, we have a feature called "Agent Portal"  that  allows agents to have the  ability to track his referrals, applications and so on.  If an agent have also an Agency Cloud CRM. we would like to give him the ability to view his MovingHub stuffs right from within that CRM.

In order for us to authenticate the agent though, he need to provide us with an API key and credentials,
that the app needs to provide when making requests to our API (https://au-api.utilihub.io/docs/v2/#/)

yep - we could issue a single credentials for the entire company as a whole (easier route), but that would mean every agent for that company will be given the same privileges (as our authorization is based on api key). We would like to have the "least privilege" principle, wherein we only allow agents with minimum access needed, and be able to revoke permissions without affecting the other agents in the same company.

**Comment by cbryanreapit** [comment]
Hi @buonzz - we do not support storing API key / credential information in our APIs. I would recommend an interim external service geared to securely manage sensitive credential information (eg. AWS Secrets Manager) as a place to lookup whatever credentials are assigned to each user via email address.
