### ISSUE TITLE
The documentation pages should be styled to look like elements. 

### ISSUE THREAD

**Issue by willmcvay** [reapit/foundations#2612]
**Background**

_Elements UI library is being refactored to ensure better DX, UX and a more lightweight, flexible library with a more consistent API_

**Task**

- See specification here: https://github.com/reapit/foundations/blob/master/packages/elements-next/src/index.mdx
- The docs app should use the same fonts, sizing, spacing and have the same general look and feel as the rest of Elements
- Borders should be the same, links should be correct Reapit blue, background containers the same white on pale grey effect as our apps. 
- Padding, line breaks and overflow should be fixed for the rendered component output section - see below
<img width="1171" alt="Screenshot 2020-09-08 at 12 43 27" src="https://user-images.githubusercontent.com/4630495/92472146-ff7b8c80-f1d0-11ea-81fe-f6342658865d.png">

**Comment by phmngocnghia** [comment]
Hi @willmcvay 

> The docs app should use the same fonts, sizing, spacing and have the same general look and feel as the rest of Elements
Would you like the text of the documentation page to look like elements storybook config, header?

Could you explain the ticket in a more detail way please?

**Comment by willmcvay** [comment]
@phmngocnghia Elements is a Styleguide. I want to use this styleguide to style the documentation page.

**Comment by nphivu414** [comment]
Hi @willmcvay , @tanphamhaiduong 
As we decided to use StoryBook V6 for Elements V2, I need to re-work on this issue.

**Comment by willmcvay** [comment]
Who decided this @nphivu414 @tanphamhaiduong and why?

**Comment by tanphamhaiduong** [comment]
@willmcvay  actually I see the issue here https://github.com/doczjs/docz/issues/1442. So that is the reason why I move to the storybook. The docz library I think there's no maintainer for it
