### ISSUE TITLE
Update Reapit Connect landing page to include 'Agency Cloud' section

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#2618]
**Summary:** We should display an additional section ‘Agency Cloud’ to users that are part of the group ReapitUsers or ReapitUsersAdmin 

**Location:** https://reapit-connect.reapit.cloud/

**Task:** Display an additional section on the Reapit Connect Landing page to users that are part of the groups ReapitUsers or ReapitUsersAdmin 
- Heading: Agency Cloud
- Subheading: Account Successfully Created
- Text: If you have Agency Cloud already installed on your machine, you can now login via Reapit Connect with your new credentials. If not, please contact your IT Department or Administrator to arrange installation. 
- Image: https://www.dropbox.com/s/pzcm0jcqka9adia/ACImage.jpg?dl=0
- Background Colour: #015b73
- Place above the ‘Marketplace’ section 
- No CTA needed 
- Additional
The splash page should be in a container, currently does not display well on larger screens

Section mockup:  
![image](https://user-images.githubusercontent.com/52408607/92479901-11aef800-f1dc-11ea-8d71-bcfdd7451488.png)

Mockup:
![ClientExample](https://user-images.githubusercontent.com/52408607/92479937-1b386000-f1dc-11ea-827a-78f8b0448dce.jpg)

**Comment by phmngocnghia** [comment]
Hi @willmcvay  @HollyJoyPhillips. I figured out that we have a group named "ReapitUser", but the description mentions about group "ReapitUsers". Not sure if there's a typos on the desc. How do I create / access user belonging to the group named "ReapitUsers"

**Comment by phmngocnghia** [comment]
![image](https://user-images.githubusercontent.com/36730355/92550697-568f6900-f286-11ea-9c4a-ef1ee0598d1c.png)

**Comment by willmcvay** [comment]
@phmngocnghia Yes, it's ReapitUser

**Comment by HollyJoyPhillips** [comment]
Hi @phmngocnghia, thanks for working on this. A couple of points: 

The sections should follow the pattern of alternating the graphic and text left and right  - see mock up: 
![image](https://user-images.githubusercontent.com/52408607/92721773-8611a480-f35e-11ea-83dd-ee7406b8cf0f.png)

Currently the images on both sections are on the left: 
![image](https://user-images.githubusercontent.com/52408607/92721845-9e81bf00-f35e-11ea-873b-e88dc36ba8db.png)

Also, the page should be in a container, see how it displays on larger screens: 
![image](https://user-images.githubusercontent.com/52408607/92721752-7c883c80-f35e-11ea-8902-3ab2a192ad03.png)
