### ISSUE TITLE
[Agency Cloud Developer] Reapit Desktop app stucked in "checking time..."

### ISSUE THREAD

**Issue by buonzz** [reapit/foundations#2639]
**Describe the bug**
When you login to RPS - Developer windows app, after logging in, it displays "Checking time..." and it is stuck there (its been like an hour already and it doesn't respond anymore)

**To Reproduce**
Steps to reproduce the behaviour eg:
1. Go to https://developers.reapit.cloud/desktop
2. Click on 'SUBSCRIBE NOW'
3. Check email for the download link of the desktop app.
4. run the "setupdev.exe" and complete the installation process
5. start the application and provide your credentials
6. it will display the error

**Expected behaviour**
after logging in, it should launch the main screen and allow me to use the application, and test my app.

**Screenshots**
https://drive.google.com/file/d/19FlG1WRZ1rxiaO-x035-0984eF3gMfCM/view?usp=sharing

**Device (please complete the following information for web issues):**
 - Device: Desktop
 - OS: Windows 10 Pro
-  OS Version: 1809
-  OS Build Number: 17763.1457
- RAM : 4GB
- System Type: 64-bit
- RPS - Developer: 12.120.1.0
 - RPS - PDF (novaPDF 7.5 printer)
- Microsoft Visual C++ 2015-2019 Redistributable (x86) - 14.22.27821
- MySQL Connector /ODBC 8.0

**Comment by buonzz** [comment]
hi @plittlewood-rpt  im on GMT+8

**Comment by cbryanreapit** [comment]
Thanks for the feedback. FYI @PaulHaynes

**Comment by buonzz** [comment]
Hi,

I've attempted to create a remote windows machine in two different regions in AWS

* eu-west-1
* ap-southeast-1

also, tried installing it in a fresh windows 10 installation in  physical laptop. same issue.
We are getting the same result as in the screenshot..
https://drive.google.com/file/d/1is1TNeDWGX-aOUItkQrqXh8H3_hCb-n3/view?usp=sharing

**Comment by plittlewood-rpt** [comment]
Hi @PaulHaynes 

I have been able to replicate this on my own machine by setting my clock to UTC +6. Please can you take a look and debug this one?

Thanks
Pete

**Comment by plittlewood-rpt** [comment]
Hi @buonzz we think we know what is causing this and are looking at the best way to resolve. We wil be in touch

**Comment by buonzz** [comment]
hi,

Holly reached out to me via email, and I've shared the credentials to the remote machine where can this be replicated.
I confirm this issue is resolved now.

Thanks everyone!  💯
