### ISSUE TITLE
Email Link/URL on Developer invite email pointing to dev.developer

### ISSUE THREAD

**Issue by AshDeeming** [reapit/foundations#2642]
Developer email invite - the url points to old url: dev.developers

Update should point to: 
Developers.dev.paas. 

Should point to: 
Developers.dev.paas.

**Comment by cbryanreapit** [comment]
@AshDeeming could you expand on this? Both of those URLs are the same. Is this for dev or prod?

**Comment by AshDeeming** [comment]
@cbryanreapit - Please ignore, I spoke with Holly & this is invalid. Thanks
