### ISSUE TITLE
Populate DynamoDb using real time data streaming pipeline

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#2664]
Our data warehouse (and broader architecture) will be simplified and enriched by building a multi tenancy NoSQL datastore of all of our customers data. DynamoDB is the obvious candidate for this, since we will not be using it for broad querying, rather a secondary data storage technology to power other AWS interactions.

- Attach new lambda to listen to SQS events from real time data pipeline
- Lambdas responsibility is to build and index a series of multi tenant DynamoDB tables
- Data is for internal use only
- Customer id / primary key as partition/sort keys for each tabkle
- Update in real time, as per ElasticSearch at present

We need to index our dynamoDb table so that it can be periodically scanned for changed records.

More information TBC

**Comment by plittlewood-rpt** [comment]
PR 2715 opened

**Comment by plittlewood-rpt** [comment]
Working fine on dev. Needs CF template update before we can release this to production. Logged separately
