### ISSUE TITLE
Update Desktop API to handle URL to start a native windows process

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#2694]
**Summary**: External URL's are currently opening using the internal Chromium browser. We should look to handle as below:

agencycloud://process?argument

Where we take argument and then start a Process object with that as the argument, and let windows decide what application to launch. 

For example:
agencycloud://process?dave@email.com (would start default mail client)
agencycloud://process?https://www.google.co.uk (would start default browser at that page)

**Comment by cbryanreapit** [comment]
FYI @PaulHaynes

**Comment by HollyJoyPhillips** [comment]
Desktop API now supports opening using external default browser, full documentation here https://foundations-documentation.reapit.cloud/api/desktop-api#process
