### ISSUE TITLE
Introduce local data caching for UPRN address lookup

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#2700]
**Background context**
Ordnance Survey have released a new geospatial data platform that promise to unlock additional value to third parties for no/low usage cost. We should examine this platform and understand what value we can obtain from it by augmenting our own data / offering additional services to our partners.

**Specification**
We should use the third party API as sparingly as possible and as such, we should keep our own database of previous UPRN/address lookups. Care should be taken to ensure data does not get stale and we may not always have the right to cache. Additionally, we should keep a catalog of previous property UPRN lookup successes when a property id in is in scope (eg. via our real time data pipeline) so that we can gain future insight (eg. linked transactions)

More information TBC.

**Comment by HollyJoyPhillips** [comment]
This will be driven by desktop development
