### ISSUE TITLE
TBC - Create New App issue when user clicks outside of wizard

### ISSUE THREAD

**Issue by AshDeeming** [reapit/foundations#2703]
**Background context or User story:**

When on http://developers.dev.paas.reapit.cloud/apps - Select 'Create New App' 

Whilst completing the new app wizard, if the user clicks off the wizard, any information entered is lost & they have to start again.

Screen recording below shows how this can happen:
https://www.dropbox.com/s/jdpwyk1phof7ocr/Create%20app%20clicked%20off.mp4?dl=0

**Specification or Acceptance Criteria:**
TBC

**Suggested solution:**
'Are you sure you want to exit' message?
New Tab?

**Comment by plittlewood-rpt** [comment]
I logged this with Holly a while ago so might be a duplicate possibly
