### ISSUE TITLE
metadata not returned on property when using generated token

### ISSUE THREAD

**Issue by Nialld** [reapit/foundations#2719]
**Describe the bug**
request a property by using /properties/{id} via a standard access_token does not return metadata attributes, this is happening in the test environment

**To Reproduce**
Steps to reproduce the behaviour eg:
1. request a token via https://connect.reapit.cloud/token
2. use this token in a request to https://platform.reapit.cloud/properties/RPT200081 via postman OR openapi client library
3. no meta data is returned

"metadata": {}

4. perform exactly the same request via the interactive portal at https://developers.reapit.cloud/swagger
5. metadata is returned as expected

"metadata": {
        "CustomField1": "CustomValue1",
        "CustomField2": true,
        "CustomField3": 123
    }

**Expected behaviour**
i would expect metadata to be returned to be identical, it appear that metadata is not retrievable via the generated token.

**Device (please complete the following information for web issues):**
 - Device: PC
 - OS: Linux
 - Browser Chrome
 - Version 85

**Additional context**
Replacing the Bearer auth token provided with https://connect.reapit.cloud/token with the bearer auth token used by the interactive portal, all other data returned is identical except for metadata which is missing

**Comment by cbryanreapit** [comment]
Hi @Nialld 

Any metadata added into our APIs is associated to the developer of the application that inserted it. This means that when you add metadata, it will only be returned to the application that inserted it, and any other application created on the same developer portal account. It's your own private store designed not to clash with the operations of other applications.

Any test data that gets added to our sandbox using the Swagger tool gets associated to the Reapit developer account and therefore is therefore not shared to your own applications. You should find that if you insert metadata using your own application, it'll be returned to you as you expect.

Let us know if this solves your problem and thanks for reaching out

Craig

**Comment by cbryanreapit** [comment]
I have closed this issue - please let us know if your issue remains unsolved and we'll reopen.

**Comment by Nialld** [comment]
yes thanks, i re read the docs, missed this point,

**Comment by cbryanreapit** [comment]
Thanks for the confirmation @Nialld !
