### ISSUE TITLE
not all webhook topics are available for subscription @ https://developers.reapit.cloud/webhooks

### ISSUE THREAD

**Issue by Nialld** [reapit/foundations#2722]
**Describe the bug**
im trying to subscribe to properties events but these are not available as an option from the modal dropdown

**To Reproduce**
1.  Go to https://developers.reapit.cloud/webhooks
2. add or edit a webhook, 
3. SUBSCRIPTION TOPICS is missing some topics, the ones i have noticed are properties create and update

**Expected behaviour**
i would expect that all available endpoints are available in the test environment for subscription

**Device (please complete the following information for web issues):**
 - Device: PC
 - OS: Linus
 - Browser chrome
 - Version 85

**Comment by cbryanreapit** [comment]
Hi @Nialld 

The webhook topics that we present are filtered based on the scopes that your application has been assigned. For example, if your application has not been assigned to properties.read scope, we won't offer to emit property based webhook topics to your application. You should find that you can just add the additional scopes to your application and the associated webhook topics will become available. 

Let us know if this solves your issue and we'll look to enhance the documentation to make this clearer (https://d3n4a9i5oscc99.cloudfront.net/api/webhooks#registering-your-app)

Craig

**Comment by cbryanreapit** [comment]
I have closed this issue - please let us know if your issue remains unsolved and we'll reopen.

**Comment by Nialld** [comment]
the property create / update events appears by themselves, i didn't change anything on my side so i can only assume it was fixed on your side, thanks

**Comment by Nialld** [comment]
i can confirm that "Offers Creates" is still not showing on this list, ive recreated this webhook from scratch and even tried with a separate app, it does not show for either
