### ISSUE TITLE
Add additional field 'Role' to Settings page

### ISSUE THREAD

**Issue by AshDeeming** [reapit/foundations#2727]
**Background context:**
We currently display Name, Email, Company & customer ID on the settings page of Marketplace. i.e.
![image](https://user-images.githubusercontent.com/61687775/93497521-68b57b00-f908-11ea-9cbf-a57d7b62b760.png)
https://marketplace.reapit.cloud/settings

**Specification**

Investigate adding a field to display the users role. 

i.e.
If **ReapitUser** - display **User**
If **ReapitUserAdmin** - display **Admin**
If **AgencyCloudDeveloperEdition** - display **App Developer**

**Comment by willmcvay** [comment]
@AshDeeming So there are a few cases we haven't thought of here, also, we don't account for multiple roles. Have added these in - hopefully works for you
```
const roles = {
  FoundationsDeveloper: 'App Developer',
  AgencyCloudDeveloperEdition: 'Developer Edition Subscriber',
  FoundationsDeveloperAdmin: 'Developer Admin',
  ReapitEmployee: 'Reapit Employee',
  ReapitUser: 'User',
  ReapitUserAdmin: 'User Admin',
}
```
Mappings above ^^
