### ISSUE TITLE
Update ‘Need Help’ modal when in desktop mode to use agencycloud scheme for Email and Home Page

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#2730]
**Summary**: Currently, the email address and home page url we display on the ‘Need Help’ modal, when in desktop mode, open a chromium browser inside of agency cloud, it should open the default system mail client or browser 

**Location:** https://marketplace.reapit.cloud/apps/

**Task:** When in desktop mode, update the email address on the ‘Need Help’ modal to: 

agencycloud://process/email?address=email@email.com

**Task:** Update the home page url to: 

agencycloud://process/webpage?url=http://www.bbc.co.uk 

![image](https://user-images.githubusercontent.com/52408607/93576261-98a96080-f992-11ea-9ff1-0937ddec0b88.png)

**Comment by willmcvay** [comment]
@HollyJoyPhillips Have added this to the coming soon links too
