### ISSUE TITLE
Improvements for app submission validation

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#274]
**Summary of Request:**

A few quick wins to improve user experience when submitting an app:

- Provide visual feedback that validation has failed at the bottom of the submit form (near the submit button). When you submit an app and it fails validation, each invalid field will provide validation failure reason. The problem is that these are scrolled off the screen when you're submitting, the submit button is at bottom of the form so you cannot see these indicators. It makes the submit button feel like its unresponsive/not working.
- For the two descriptive textual fields, it would be good to provide a current character count / maximum character count as the developer is typing. Presently, you don't know how long your text is at the point of entry and upon submit, you often have to scroll back up to enter/remove text.
- The UI doesn't tell the developer that URLs need to include http / https components for all URLs required by the form. You only find that out after you hit submit.

**Comment by HollyJoyPhillips** [comment]
This ticket has been split into separate tickets and added to the board.
