### ISSUE TITLE
Investigate the possibility of augmenting developer/sandbox identity tokens with sandbox negotiator id

### ISSUE THREAD

**Issue by plittlewood-rpt** [reapit/foundations#2742]
When logging into Reapit Connect through Sandbox or as a Developer, the identity tokens do not have the userCode property populated because the developer accounts are not associated with Agency Cloud accounts. Investigate whether or not we can populate this token property for this type of login

In addition, when a developer is subscribed to Developer Edition, it would be useful to include the ReapitUser and/or ReapitUserAdmin groups in the groups list so developers can simulate a true user

Similar query raised in #2743 - we may need to look at enhancing the `loginIdentity` property in the `ReapitConnectSession` object to expose organisational information but this will need discussion with UI team

We may need to review terminology used in some places - we are referring to both customers and organisations in places which is causing some confusion

**Comment by cbryanreapit** [comment]
Default is ADV.

**Comment by plittlewood-rpt** [comment]
Developer token will now be augmented with user code that can be used to query negotiators/{id} endpoint when a developer logs into Agency Cloud Developer Edition. Requires active subscription.
