### ISSUE TITLE
Beta ClientId being sent in Webhook Header

### ISSUE THREAD

**Issue by adam-brewer-mab** [reapit/foundations#2759]
**Describe the bug**

This is a follow up from https://github.com/reapit/foundations/issues/2755 . Tested this again on our system and it now appears to be working.

The issue I am now finding is that the client id being sent up is the previous one from before Reapit went into full production.

**To Reproduce**
Steps to reproduce the behaviour eg:
1. Migrate an app created in beta stage generating a new client id and secret
2. Trigger a webhook
3. The old client id is sent in the header

**Expected behaviour**
The production client id will be sent in the header of the webhook request

**Screenshots**

![image](https://user-images.githubusercontent.com/70258275/94430519-f6585c80-018b-11eb-9e90-495bcc59a881.png)

**Additional context**

```shell
Error Time="2020-09-28 08:37:36.813" Service="Midas.Api.Reapit" Instance="2" Operation="WebhookAuthorisation.ClientIdsMatch" Event="Reapit-Webhook-Signature does not match ReapitClientId" ConfigClientId="ln0mjjlrnlsu7t803ha8391ot" ApiClientId="bG4wbWpqbHJubHN1N3Q4MDNoYTgzOTFvdA==" RequestClientId="MWY5OTF1NW12cW5oMTd2NGRkNDI4bXRpaG0=" MessageId="f8b6456b-ed92-48b3-a2a3-6efe2016d519"

adambrewer@mab ~> echo MWY5OTF1NW12cW5oMTd2NGRkNDI4bXRpaG0= | base64 --decode
1f991u5mvqnh17v4dd428mtihm⏎
```

__Reapit Endpoint Config__

  "ReapitConnectString": "https://connect.reapit.cloud/token",
  "ReapitPlatformString": "https://platform.reapit.cloud",

**Comment by plittlewood-rpt** [comment]
Hi @adam-brewer-mab  thanks for flagging this - there were some webhooks still active in our dev environment (previously the beta environment you were using) which might have been generating some hooks to go out still. I've just disabled them all as they should be turned off now. Can you rerun your test and let me know if you still get the incorrect id?

**Comment by adam-brewer-mab** [comment]
Now there seems to be no events coming through from the Desktop app even though they are setup on the portal 

![image](https://user-images.githubusercontent.com/70258275/94450646-6b845b80-01a5-11eb-8fa7-f7310d2af49f.png)

However I am able to ping to this address

We're running version: 12.120 of the desktop app

![image](https://user-images.githubusercontent.com/70258275/94451069-e3528600-01a5-11eb-8aad-30456b126253.png)

**Comment by plittlewood-rpt** [comment]
Hi @adam-brewer-mab  thanks I'm looking into this now

**Comment by plittlewood-rpt** [comment]
Hi @adam-brewer-mab it might be easier if you jump on live chat when it opens at 9am. It looks like you might possibly still be using the old version of Agency Cloud Developer Edition. Did you reinstall it when we moved to production? You should have received an email with instructions. I can see some activity from a machine called MAB1341 yesterday in the old version so not sure if that's your machine?

**Comment by plittlewood-rpt** [comment]
HI @adam-brewer-mab , my colleague Holly was in touch with Callum earlier as he reported an issue which confirmed the wrong version of Developer Edition was being used. Now that that's all sorted can you let me know and/or close this ticket down if the issue with webhooks has also been resolved. I suspect it probably has been but would be good to confirm. Thanks

**Comment by adam-brewer-mab** [comment]
Seems  to be resolved now thanks for all your help :+1:
