### ISSUE TITLE
Add an additional email to the auto generated email that is sent to accounts

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#2761]
**Related ticket:** https://github.com/reapit/foundations/issues/2367

**Summary**: Currently we send an email to accounts (creditcontrol@) when an developer organisation account is set to 'pending'. We would like to include an additional email address for extra coverage

**Requirement:** Include foundationssupport@reapit.com as an additional email address in the email that gets auto generated to accounts

**Comment by plittlewood-rpt** [comment]
PR 2723 opened

**Comment by plittlewood-rpt** [comment]
Confirmed by Holly on dev. Released to production
