### ISSUE TITLE
Unable to login - User flagged as inactive

### ISSUE THREAD

**Issue by CallumRoss97** [reapit/foundations#2763]
Hi, 

I have tried to login to RPS this morning as callum.ross@mab.org.uk however it keeps failing, 'User is flagged as inactive' I had uninstalled and tried to reinstall for a new version of RPS however on doing that I now cant login. Any help would be appreicated

Thanks, 
Callum

![image](https://user-images.githubusercontent.com/53347161/94545957-231c7a80-0245-11eb-982c-c0cd231c8348.png)
![image](https://user-images.githubusercontent.com/53347161/94546012-36c7e100-0245-11eb-9fc1-6fbe05c02468.png)

**Comment by HollyJoyPhillips** [comment]
Emailed instructions to Callum, confirmed working.
