### ISSUE TITLE
[ Developer Portal ] How to enable Client credentials flow?

### ISSUE THREAD

**Issue by buonzz** [reapit/foundations#2767]
**Summary**
My app is listening to **tenancies.created** topic via webhook, which contains the **new.applicantId** and **new.propertyId** fields.
now, using those data, I wanted to pull the applicant and property detail in my backend codes. 
In order to do this, I needed to enable the **CLIENT CREDENTIALS** in my app, but the checkbox is disabled when I edit my app in developers portal.
I tried creating a new app, and there is no option presented to me where I could enable it, was there anything I missed to do to enable the **CLIENT CREDENTIALS** ?

thank you!

**Comment by willmcvay** [comment]
@buonzz Unfortunately you can only support one Auth flow for a single client id (app) and this flow cannot be changed after creation. This is a restriction of the OpenId Connect spec, not a product decision by us. You can create a new Client Credentials app by selecting "no" when asked if you want the app to launch within agency cloud and "server side" authentication at the next step as per the screenshots below.
<img width="654" alt="Screenshot 2020-09-30 at 09 50 13" src="https://user-images.githubusercontent.com/4630495/94664255-9801ba00-0302-11eb-9bcc-e47d21bdb227.png">
<img width="676" alt="Screenshot 2020-09-30 at 09 50 01" src="https://user-images.githubusercontent.com/4630495/94664259-989a5080-0302-11eb-8b5e-e1d0b8e9e370.png">



You will either need to have two applications (one Client Credentials, one Auth Code), or potentially you could store the tenancy information from the webhook and fetch the property and applicant information on the fly, when the user requests details about a tenancy, passing you an accessToken. Obviously I am not sure about your exact use case so difficult to advise futher.

**Comment by buonzz** [comment]
thank you!

**Comment by buonzz** [comment]
hi @willmcvay  manage to implement this option:

have two applications (one Client Credentials, one Auth Code)
https://drive.google.com/file/d/1jGYR2CpZpavrTRBXfEkmbZznUOXV1DPE/view?usp=sharing

* Movinghub - for customer-facing side of the app, contains my react app
* Movinghub Direct API -  for direct integration and server-side interaction

I'm able to make server-side calls, the only problem is, now the user have to install two separate apps, which is not a great user experience. 

### regarding my use-case
 Basically what we are trying to do is when a `tenancies.created` topic is fired in webhook, we wanted to create a movinghub application in our end by making a call to our internal api. This requires supplying contact details and property details, it needs to happen without a user-interaction, thus making the second option (using an accessToken from Connect) not possible.

###  Questions

- Im the only one who happened to have this use-case? (e.g. needing both Authentication Flow in the same app), I'm curious how others had approached this issue.
- is there a way to define a dependency among apps (e.g. automatically install and grant permission to another app, when the primary app is installed) 
- is there a way for me to check if the other app is installed and vice versa at runtime? (So i could display a warning in my UI)




thank you :)

**Comment by willmcvay** [comment]
@buonzz To answer your questions;

- Yes other people have the same use case and yes, the approach I have outlined is how it was solved.
- No there isn't and there is no planned mechanism to do this at present.
- Yes, you can receive a webhook for installations for both apps to a single endpoint and therefore check that both apps are installed.
- As I have said previously, my advice would be to cache the response of the webhook and make the calls you need on the fly when the user interacts with your app. You will doubtless need to think about the most efficient way to do this but unless I am missing something crucial here, I can't see a scenario in what you are doing that could not be achieved with a single app installation.
