### ISSUE TITLE
create webhook events for properties are being reported twice

### ISSUE THREAD

**Issue by Nialld** [reapit/foundations#2768]
**Describe the bug**
i create a property, the webhook that notifies of a creation is being triggered twice

**To Reproduce**
Steps to reproduce the behaviour eg:
1. create a property via the API, making sure that webhooks are setup for property create
2. 2 events are received per property create

**Expected behaviour**
i would expect only 1 event to be triggered

**Additional context**

the head of the logs im receiving

{
  "eventId": "8a5274b8-6c0e-4d17-874f-1f71197a4885",
  "entityId": "RPT200090",
  "customerId": "SBOX",
  "eventTime": "2020-09-30T08:50:50.91613Z",
  "topicId": "properties.created",

AND

{
  "eventId": "305edaf5-b72e-4cf9-890a-543e98b09c09",
  "entityId": "RPT200090",
  "customerId": "SBOX",
  "eventTime": "2020-09-30T08:50:49.8675539Z",
  "topicId": "properties.created",

**Comment by plittlewood-rpt** [comment]
Hi @Nialld 

Thanks for getting in touch. I've been able to replicate this problem so will look at getting this resolved in due course.

**Comment by plittlewood-rpt** [comment]
PR 2732 opened which should resolve this problem

**Comment by plittlewood-rpt** [comment]
Hi @Nialld this should now be resolved.
