### ISSUE TITLE
[ REST API ] format of Contact.mobilePhone?

### ISSUE THREAD

**Issue by buonzz** [reapit/foundations#2770]
Hello guys :)

just would like to confirm the format of `Contact.mobilePhone`
based on what Im noticing in sandbox, its 12-digit field.

## Question
 
is it safe to assume that the first 2 digits is the country code?

for example, given: 

```
{
      "id": "MKT20000055",
      "name": "Miss Helga Braithwaite",
      "title": "Miss",
      "forename": "Helga",
      "surname": "Braithwaite",
      "type": "contact",
      "homePhone": null,
      "workPhone": null,
      "mobilePhone": "071234587653",
      "email": "helga.braithwaite@glfiction.com",
      "primaryAddress": {
        "buildingName": "",
        "buildingNumber": "54",
        "line1": "Broome Road",
        "line2": "Durham",
        "line3": "County Durham",
        "line4": "",
        "postcode": "DH1 1NE",
        "countryId": "GB"
      }
```

the `071234587653` part in here, `07` is the country code, while the `1234587653` is the actual phone number (minus the country code)? 

thanks!

**Comment by cbryanreapit** [comment]
Hi @buonzz. Our REST API surfaces the data as the user has entered it into their system so 07 is not the country code here. Our CRM software products do not force users to enter country code, rather they'll generally enter the telephone number details in the convention of their location country (usually UK) and in the case where a contact is overseas and a dialling code is required, it will be inputted as an exception.

**Comment by buonzz** [comment]
got it, thank you
