### ISSUE TITLE
Developer Marketplace - Is listed Check box required

### ISSUE THREAD

**Issue by AshDeeming** [reapit/foundations#2775]
**Background context**

Currently the 'Is Listed' check box is available within the App Edit Details section. 

**Suggested solution:**

'Is listed' to be an option on the App front page - as per below;
(This will need to include the logic regarding billing)
![image](https://user-images.githubusercontent.com/61687775/95084149-63806a80-0715-11eb-85da-500a8db38aa6.png)

**Comment by willmcvay** [comment]
Agreed with Holly, will keep the is listed on the Edit app page but move it into prominence and hide the auth flow code
