### ISSUE TITLE
[Marketplace] After a user had installed an app, is it possible to automatically launch the app and visit a specific route?

### ISSUE THREAD

**Issue by buonzz** [reapit/foundations#2795]
Hello Guys :) 

When a user clicked the install button and he had successfully installed the app in agency cloud crm, is it possible to launch the app and have him visit a specific route in my app?

the reason is, I wanted for a user to configure the app for first-time use. Like a /setup-app route which just asks a few questions regarding the customer and their account, so we could configure their account in our side properly.

Thank you

**Comment by willmcvay** [comment]
@buonzz You just specify the launch URI you want your application to load at in the app edit form. Suggest (although not essential), that you match this to a re-direct uri in the auth flow so that Reapit Connect re-directs to your desired route after authentication. Hopefully this makes sense.

**Comment by willmcvay** [comment]
Can I close this @buonzz ?

**Comment by buonzz** [comment]
yep, sorry thanks @willmcvay
