### ISSUE TITLE
Update tenancies through Reapit API

### ISSUE THREAD

**Issue by FrankieMalpass** [reapit/foundations#2825]
**Is your feature request related to a problem? Please describe.**
As an agent who uses Goodlord and Reapit, I want to create my Pending Offers in Reapit but process the tenancy on Goodlord (i.e. collect holding deposit, security deposit, references, and sign contracts on Goodlord). When I create the tenancy on Goodlord, I do this on Goodlord by using their integration with Reapit to select the Pending offer / tenancy on Reapit and Goodlord importing the details. However, during the course of the tenancy, certain details sometimes change. For example, the start date of the tenancy may be moved back if the references take a long time to be assessed. **I want Goodlord to be able to update Reapit automatically when things like this change so that I don't have to do it manually myself in two systems.** 

**Describe the solution you'd like**
Via the API, I want to update the following tenancy details in Reapit:
- Start date
- End date
- Rent
- Security deposit

I also want to be able to accept, reject, or withdraw an offer via the API (e.g. collecting the holding deposit through Goodlord will automatically update the tenancy from Pending Offer to Offer Accepted)

**Describe alternatives you've considered**

**Additional context**

**Comment by cbryanreapit** [comment]
To be reviewed and where approrpriate broken down into smaller tickets

**Comment by cbryanreapit** [comment]
Ticker superceded by https://github.com/reapit/foundations/issues/3602
