### ISSUE TITLE
Build estimates of the number of rows that are added/edited in a month for a spread of customers

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#2826]
We need to understand the number of rows that are added or edited per month in a spread of different databases. The goal of this ticket is to produce some figures on a selection of different customer databses (suggest small, medium and large customers included) to understand the percentage of records that are updated in a given month.

**Comment by plittlewood-rpt** [comment]
I have run figures off this morning for 8 customers and it's coming out at 1.1% of records with activity since 8th September. I've got approval to run the stats for all hosted customers overnight tonight to get an accurate figure.

**Comment by plittlewood-rpt** [comment]
Have run across 95% of the hosted customer base and it's slightly higher at 2.1% of unique records added/edited in a month. Will share full set of data internally.
