### ISSUE TITLE
The ability to update multiple entities with a single request

### ISSUE THREAD

**Issue by RWilcox-Reapit** [reapit/foundations#2827]
Raised from a live issue:
A customer has request the ability to update multiple entities with a single request:

Example discussed: 
Events are streamed to the customer from third party suppliers, they would want the ability to apply these updates in a single request. For example the updating of a properties metadata and the properties images in a single transaction.

**Comment by cbryanreapit** [comment]
Some platforms do provide the ability to bulk write operations. These usually work by accepting a payload of an array of a single entity type - often they're asynchronous. We may look to introduce this functionality for some of our entity types given a good use case requirement. We wouldn't look to support multiple types of entity in a single request, however. I will set this issue into the backlog for now.

**Comment by cbryanreapit** [comment]
No immediate plans to deliver bulk update mechanisms
