### ISSUE TITLE
[Agency Cloud Developer] Is it possible to add my own data in sandbox?

### ISSUE THREAD

**Issue by buonzz** [reapit/foundations#2838]
Hi,

I wanted to test my app thoroughly before submission. Im currently using Developer Edition of Agency Cloud primarily to test my app, but I have few issues with the sandbox environment:

- I cant' add agents (I need to be able to test it in agent's point of view and have a hierarchy of agents and offices)
- I cant add new contacts or applicants
- cant delete tenancy, applicants or contacts
- the `loginIdentity`  doesn’t have the ReapitUser and ReapitUserAdmin in its “groups” attribute (used to determine who has administrative privilege to manage the account) - https://github.com/reapit/foundations/issues/2742

is there a way for me to perform end-to-end tests with all those features available? 

thank you in advance.

**Comment by cbryanreapit** [comment]
Hi @buonzz 

You can add data into the sandbox by either using agency cloud developer edition or by using our REST APIs as below:

/POST negotiators
/POST contacts
/POST applicants

Are you experiencing a problem with these endpoints?

Regards

Craig

**Comment by buonzz** [comment]
hi @cbryanreapit  thank you for the reply.  I don't intend to make data changes via REST API, but would like to use the agency cloud developer edition, as if how a real end-user would use it.

I'm having hard time figuring out how to add negotiator, contacts and applicants in the RPS' user-interface... this is what it looks like in my end
https://drive.google.com/file/d/1NlFDFAFJrrYRxzxLZlUCyedi8vv4j00q/view

when i click the Applicant and Contact menu item in the left sidebar,  i only see two buttons (see more/less details and a close button), but I'm failing to see the button where I could add new entry..

any help will be appreciated :)

Thank you!

**Comment by cbryanreapit** [comment]
Hi @buonzz 

We have documentation on Agency Cloud developer edition [here](https://developers.reapit.cloud/assets/developer-edition-guide.pdf). The last page includes a link to a training site containing videos on how to use the product in a little more depth. I hope that should answer your specific questions.

Regards

Craig
