### ISSUE TITLE
Developer Portal down?

### ISSUE THREAD

**Issue by buonzz** [reapit/foundations#2867]
**Summary**
around 12:30 AM GMT+1 today (Oct 16, 2020), I signed in to https://developers.reapit.cloud/ but all the functionality is not working.
 
- there are notifications with message "SOMETHING WENT WRONG FETCHING DATA"
- there are no apps displaying ( I have two apps)

then when i checked the chrome console, there are CORS issues like

```
Access to fetch at 'https://platform.reapit.cloud/marketplace/apps?developerId=10a028c3-ba11-45ad-bdac-1d4445a8cf5a&pageNumber=1&pageSize=12' from origin 'https://developers.reapit.cloud' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```
**What I have already tried**
* Signing out and Signing in again
* Refresh browser cache
* open the developer portal in Incognito window mode

**Detail and or supporting links and screenshots**
here is the screen recording of the session 
https://drive.google.com/file/d/102WEioaVtT5wM54ay1mZaTN2VfJCroqG/view?usp=sharing

**Comment by plittlewood-rpt** [comment]
Hi @buonzz  this should be back online. The backend service suffered an outage which I'm currently looking into
