### ISSUE TITLE
Create a subscriptions section on the Admin Portal 

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#2877]
**Summary**: Should include an additional section in the Admin portal ‘Subscriptions’ to surface any developer subscriptions

**Tasks**: 
**Nav**
Add nav icon BiPurchaseTag
Route:  /subscriptions 

**Search Options:** 
By Subscription Type (SubscriptionType)
Developer Name & or Company (User DeveloperId on /members) 

**Table of Results:** 
Subscription Type (type) 
Summary (Summary)
Application ID (applicationId) 
Member Name (name /members)
Member Email (user)
Start Date (created)
Renewal Date (renews) 
Frequency (frequency) 
Cost (cost)
Status (Active unless date populated in cancelled) 
Cancel (/DELETE)

**Comment by willmcvay** [comment]
https://platform.reapit.cloud/marketplace/swagger/index.html

**Comment by willmcvay** [comment]
https://developers.reapit.cloud/settings/billing

**Comment by HollyJoyPhillips** [comment]
Hi @Bdragon93, could you please swap the box behaviours so that:

The 'Type' is a drop down menu that displays the available subscriptions '(applicationListing/developerRegistration/developerEdition)'. If new subscriptions are added to the endpoint, will it automatically be visible on the dropdown?

Rename 'Dropdown Select' to 'Developer Name' and have it as free text field: 
![image](https://user-images.githubusercontent.com/52408607/99943664-8d472c80-2d69-11eb-9e09-1380b810601d.png)

Much like the 'Name' search field on Developer Management: https://developer-admin.dev.paas.reapit.cloud/dev-management
