### ISSUE TITLE
Provide ability administrator portal to surface the last login time of a developer / member

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#2878]
To make developer portal usage easier to understand, we should surface the last login date of a developer/member in a format that can be consumed by the administrator portal. 

More information TBC

**Comment by HollyJoyPhillips** [comment]
Thanks for adding Craig but have spoken to Will to confirm the requirements and it is no longer required.

**Comment by MatthewGoddard** [comment]
@HollyJoyPhillips This can now be closed.
