### ISSUE TITLE
[ Plaform API ] How to attach metadata to a tenancy?

### ISSUE THREAD

**Issue by buonzz** [reapit/foundations#2883]
**Summary**
Hello :)
I need to store some tenancy level metadata to a tenancy, so I could reference them later (use it as a filter parameter).
but issuing PATCH request to `/tenancies/{id}` doesnt work
Im getting : 
```
An unexpected error has been encountered when fulfilling this request. This incident has been logged and will be investigated. Please try again
```

**Detail and or supporting links and screenshots**
this is an example cURL request to simulate the patch request

```
curl -X PATCH "https://platform.reapit.cloud/tenancies/RPT200129" -H  "accept: application/json" -H  "If-Match: 759AFE65AF7FDA33CF8DD1C64E1786FF" -H  "Content-Type: application/json-patch+json" -H  "api-version: 2020-01-31" -H  "Authorization: Bearer <PUT VALID TOKEN HERE>" -d "{\"metadata\": {\"MyCustomField1\": \"MyCustomValue1\"}"
```

thanks!

**Comment by cbryanreapit** [comment]
Hi @buonzz 

We don't presently provide a PATCH /tenancies/{id} endpoint therefore tenancy metadata is not supported. Please feel free to create a feature request ticket and we'll assess / prioritise from here.

Thanks

Craig
