### ISSUE TITLE
[Platform API]  Tenancy status definitions?

### ISSUE THREAD

**Issue by buonzz** [reapit/foundations#2906]
**Summary**
Hello Guys :)

in `https://platform.reapit.cloud/tenancies/{tenancy id}` response body,  im seeing there is a field called `status`
when i look at the Model tab, i saw these possible values
`offerPending/offerWithdrawn/offerRejected/arranging/current/finished/cancelled`

### Questions

- do you happen to have any formal definitions of what each status means? (I have some idea what each means, but I wanted to make sure and confirm my assumptions)
- is there any sort of flowchart, that shows how a tenancy change its status over time?
- let's say an applicant wanted to rent a property, then a new tenancy is created, which status will be assigned so that we know that both tenant and landlord agreed for that tenancy?
- is it correct to assume, that there would be multiple `tenancies.created` topic fired for the same property, and only one of those will be actually accepted by the landlord? At which point the landlord could stop accepting applicants for that property?

thank you

**Comment by cbryanreapit** [comment]
Hi @buonzz 

- If a tenant makes an offer to rent a property not at the advertised terms (eg. less rent), the 'offerPending' status would be initially set. 
- The landlord can reject the offer (offerRejected) or the tenant can decide to later withdraw that offer (offerWithdrawn). 
- If the offer is accepted, the tenancy moves to 'arranging' status. This it when the checks and processes required to let a property take place. 
- If something goes wrong at this stage, 'cancelled' is set. 
- Once complete and the tenancy has started, we use the 'current' status. 
- When the tenancy has ended, 'finished' is set

Your webhooks assumption is correct - there can be multiple tenancy.created webhooks emitted related to a single property.

Hope this helps

Craig
