### ISSUE TITLE
Ensure usage of new metadata endpoints surfaces itself in developer analytics

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#2916]
**Background context**
We should ensure that all requests that are sent to the upcoming metadata endpoints record the request in the billing service as expected in the usual format

**Specification**
- All metadata requests (including schema management) should be surfaced to billing service in the usual manner
- This should happen at the proxy level, not the downstream service

**Comment by RWilcox-Reapit** [comment]
Tested in prod, closing
