### ISSUE TITLE
Documents service swagger payloads do not include metadata information

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#2918]
**Describe the bug**
Our documents endpoints support metadata being attached but presently, they do not advertise that fact in the swagger documentation. 

**Expected behaviour**

- POST and PATCH payloads should include information on creating/updating metadata
- GET payloads should include metadata in response
- Examples should be updated in-line with other services

**Comment by plittlewood-rpt** [comment]
PR 3166 opened
