### ISSUE TITLE
Update RPS Remote debugger to Chrome v86.0.4240.183 or later?

### ISSUE THREAD

**Issue by buonzz** [reapit/foundations#2935]
**Is your feature request related to a problem? Please describe.**
when using Elements to design our app's UI, I'm mostly using Chrome 86 or higher, but when loading the app inside the RPS, there is a bit differences in the UI due to the RPS using an old version (e.g Chrome 69) , as indicated by the user-agent it is sending

```
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.12 Safari/537.36
```

**Describe the solution you'd like**
Is it possible for RPS to use the latest version of chrome when loading the apps?

**Describe alternatives you've considered**
- Tried downgrading the Chrome version I have, but its way too tedious and not optimal. Also, most developers assume they need to test in the latest version (unless told otherwise)
- We could debug right in the sandbox remote debugger, but its much faster to use the host chrome browser, specially when doing HMR

**Comment by PaulHaynes** [comment]
This feature is currently on the Agency Cloud roadmap for future investigation

**Comment by cbryanreapit** [comment]
Closing ticket since this is handled by AC roadmap.
