### ISSUE TITLE
Reapit Payments - Update Nav bar 

### ISSUE THREAD

**Issue by AshDeeming** [reapit/foundations#2936]
**Task**

Current Nav bar has Apps followed by:

Payments, Rentals & Deposits, Help & Logout

This is to be updated with: 

**Account**: Icon used in example: AiOutlineDashboard

& 

**Search**: Icon used in example : GoSearch

**Help** & **Logout** to remain. 

![image](https://user-images.githubusercontent.com/61687775/98798157-71f12e80-2405-11eb-93c9-85a3f65f7e04.png)

**Comment by willmcvay** [comment]
This is now done
