### ISSUE TITLE
How to test listed app in sandbox?

### ISSUE THREAD

**Issue by buonzz** [reapit/foundations#2951]
**Summary**
When my app is marked as "listed" in developer portal and set it to private apps,  I'm not able to find it anymore to install it and test when i click browse apps in Agency Cloud Developer Edition.
I tried adding the customer Id "SBOX", but it says the following error
```
Invalid Customer ID(s). Each Customer ID should consist of 3 characters. 
```

**Detail and or supporting links and screenshots**
https://drive.google.com/file/d/1eHMh9AyC6s8_jgE24Vmk-5p4FiPajTNk/view?usp=sharing

**Comment by HollyJoyPhillips** [comment]
@buonzz Thanks for the info, will investigate and come back to you

**Comment by HollyJoyPhillips** [comment]
Linked to ticket: https://github.com/reapit/foundations/issues/2963
