### ISSUE TITLE
Desktop Page - Download link non responsive 

### ISSUE THREAD

**Issue by AshDeeming** [reapit/foundations#2955]
**Describe the bug**
When on the Developer portal, Desktop page - as a Developer Edition Subscriber, clicking on the Subscribe Now, then Confirm Subscription, there is a modal advising that there is already an Existing Subscription. Within this is a Download Now button, which appears to be non responsive.

On production, the same steps produce a downloadable exe:
![image](https://user-images.githubusercontent.com/61687775/98376907-10634580-203c-11eb-9ae2-80904367160a.png)

**To Reproduce**
Steps to reproduce the behaviour eg:
1. Go to 'https://developers.dev.paas.reapit.cloud/desktop'
2. Click on 'Subscribe Now, then Confirm Subscription' followed by Download Now
3. See no responce

**Expected behaviour**
As per production, setupdev.exe should be provided for download.

**Comment by willmcvay** [comment]
Have tested this one @AshDeeming and seems fine - can you check again please?

**Comment by AshDeeming** [comment]
Thanks @will - I've tested again as willmcvay@me.com but still no download commencing. Will ask Holly to test too & see if we get the same outcome.

**Comment by AshDeeming** [comment]
URL needs to be updated for updates.reapit.net from http to https to allow download please

![image](https://user-images.githubusercontent.com/61687775/98672461-c5a04100-234d-11eb-9af9-ca06863b3278.png)
