### ISSUE TITLE
Split second error on Marketplace Manage Apps

### ISSUE THREAD

**Issue by AshDeeming** [reapit/foundations#2957]
**Describe the bug**
When logged into Marketplace as (App Developer, Developer Admin, Developer Edition Subscriber - willmcvay@me.com) or/and ( User Admin, User - Sales@reapit.com)  if i click on Manage followed by one of the apps & then back to Manage there is occasionally a very quick red error back is shown at the top of the page

**To Reproduce**
Steps to reproduce the behaviour eg:
1. Go to 'https://marketplace.dev.paas.reapit.cloud/manage'
2. Click on 'Manage followed by an App, then back to Manage '
3. See error as page loads

**Expected behaviour**
No red error box shown

**Comment by willmcvay** [comment]
This is confirmed as an issue. Also, with the same login it is possible for you to be able to load the apps that are not just installed on the manage page, and instead load all apps for the developer. See screengrab. Expected is that only installed apps should appear here. My guess is there is a race condition when fetching apps as can only get into this state by clicking around really quickly.

<img width="1546" alt="Screenshot 2020-11-09 at 12 05 50" src="https://user-images.githubusercontent.com/4630495/98539658-a12c6200-2284-11eb-8c4f-db4f2bc403b5.png">
