### ISSUE TITLE
Increase char limit validation for ‘Private Apps’

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#2962]
**Summary**: We currently apply a validation on ‘Private Apps’ that a customer ID should be no more than 3 characters. However, for developers to continue to test under ‘SBOX’ and to allow for franchises, the endpoint now supports up to 15. We should increase the validation to allow for up to 15 chars and allow for special characters such as '-' 
 
**Dependent on platform:** https://github.com/reapit/foundations/issues/2963

![image](https://user-images.githubusercontent.com/52408607/98597118-63edc180-22d0-11eb-8e90-cb0a68587dc0.png)
 
![image](https://user-images.githubusercontent.com/52408607/98597142-67814880-22d0-11eb-937f-1e16b9ac993d.png) 

**Task**: Update Customer ID validation to increase max char to 15 and allow special characters such as '-' 
Field: 'limitToClientIds'

**Comment by AshDeeming** [comment]
Pending Platform release
