### ISSUE TITLE
Reprovisioning the legacy views schema throws an error in the data warehouse

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#2979]
**Background context**
Views data schema can be provisioned and deprovisioned successfully however when attempted to provision for a second time, a 500 is thrown and the request fails.

**Recreate**
- Provision legacy views schema for SBOX
- Deprovision legacy views once ready
- Reprovision legacy views schema for SBOX

**Comment by plittlewood-rpt** [comment]
PR 3341 opened

**Comment by plittlewood-rpt** [comment]
Confirmed resolved in dev. Deployed to production
