### ISSUE TITLE
When sending an applicant modified webhook test applicant created webhook is sent

### ISSUE THREAD

**Issue by patryk-k** [reapit/foundations#3002]
**Describe the bug**
Both applicant created and applicant modified test webhooks are sending the same applicant created payload

**To Reproduce**
Steps to reproduce the behaviour eg:
1. Send an applicant created and applicant modified test webhooks
2. Check that the payload is identical, wrong for the modified one

**Expected behaviour**
Applicant modified webhook test should have topicId of 'applicants.modified' and the old and diff shouldn't be empty

**Screenshots**
![Screenshot 2020-11-18 at 09 54 20](https://user-images.githubusercontent.com/48892012/99515669-28648e80-2985-11eb-9429-b455449976fc.png)
![Screenshot 2020-11-18 at 09 54 45](https://user-images.githubusercontent.com/48892012/99515681-2dc1d900-2985-11eb-882a-0ae63a98554f.png)
![Screenshot 2020-11-18 at 09 55 00](https://user-images.githubusercontent.com/48892012/99515690-2f8b9c80-2985-11eb-8c33-f77ede13a4dd.png)

**Device (please complete the following information for web issues):**
 - Device: Mac
 - OS: iOS10.5
 - Browser Chrome
 - Version 86

**Additional context**
Have checked the select's HTML and the option value is correct so it looks like it's something to do with processing the submission

**Comment by plittlewood-rpt** [comment]
Hi @patryk-k  thanks for raising this, we'll get this resolved

**Comment by plittlewood-rpt** [comment]
Hi @patryk-k  this should now be resolved
