### ISSUE TITLE
Desktop type now showing in the Marketplace

### ISSUE THREAD

**Issue by AshDeeming** [reapit/foundations#3003]
**Describe the bug**
Desktop Intergration type showing as None for Apps which have this selected
**To Reproduce**
Steps to reproduce the behaviour eg:
1. Go to 'Marketplace'
2. Select an app
3. Scroll down to 'Desktop Integration'
4. See None - However if you check the requested permissions in Developer Portal, there are Integration Types selected

**Expected behaviour**
Desktop Integration & Integration types to match

**Screenshots**

![image](https://user-images.githubusercontent.com/61687775/99521135-eab73400-298b-11eb-8eef-0c5c5033e053.png)

**Comment by willmcvay** [comment]
@AshDeeming This was an issue in the Dev Portal Preview too. Have fixed this also
