### ISSUE TITLE
Reapit connect non-developer landing page

### ISSUE THREAD

**Issue by AshDeeming** [reapit/foundations#3010]
**Describe the bug**
When logging into Developer portal as a User/User Admin (@me.com) the modal advising to navigate to Marketplace/Logout/Register does not show. Instead an error box is thrown as per below; 

**To Reproduce**
Steps to reproduce the behaviour eg:
1. Go to 'https://developers.dev.paas.reapit.cloud' logged in as a User
2. See error

**Expected behaviour**
Modal to pop up advising the user they do not have developer access & provide alternative options

**Screenshots**
![image](https://user-images.githubusercontent.com/61687775/99687753-eb7bc300-2a7c-11eb-88c3-6638e022d87e.png)

**Comment by willmcvay** [comment]
<img width="1867" alt="Screenshot 2021-02-23 at 13 25 00" src="https://user-images.githubusercontent.com/4630495/108849858-8cc56880-75da-11eb-897c-58e139d55b07.png">

Can't replicate this, seems to be working fine @AshDeeming  will close unless you can give me any more info
