### ISSUE TITLE
Unable to uninstall app in agency cloud developer edition

### ISSUE THREAD

**Issue by buonzz** [reapit/foundations#3011]
**Summary**
Hi,

im trying to uninstall my app in agency cloud developer edition, but im getting the following error:

```
Error: the identity attached to this request does not have the required group membership..
```
Im logged in as the admin account of the organization, so Im not sure why i'm not able to perform the operation

Thanks

**Detail and or supporting links and screenshots**
https://drive.google.com/file/d/1Fb9Mt4bAvkdrp2Er1Oc7lsZGJgykxyup/view?usp=sharing

**Comment by RWilcox-Reapit** [comment]
Hi @buonzz  , 

Thanks for bringing this to our attention. This issue has now been resolved so you should be able to uninstall now.
Please do get back in touch if you are still having issues. 

Thanks,
Ryan
