### ISSUE TITLE
Correct self link for tenancy relationship model 

### ISSUE THREAD

**Issue by patryk-k** [reapit/foundations#3018]
**Describe the bug**
When querying the self-link provided by tenancy relationships result is 404 (Sandbox data)

**To Reproduce**
Steps to reproduce the behaviour:
1. Query `tenancies/MKT200007/relationships`
2. The result will look something like this:

```
        "_embedded" => [
         [
           "id" => "MKT20000147",
           "created" => "2020-09-25T13:40:30Z",
           "modified" => null,
           "tenancyId" => "MKT200007",
           "associatedType" => "contact",
           "associatedId" => "MKT20000002",
           "isMain" => true,
           "_links" => [
             "self" => [
               "href" => "/tenancies/MKT200007/tenants/MKT20000147",
             ],
             "contact" => [
               "href" => "/contacts/MKT20000002",
             ],
           ],
           "_embedded" => null,
           "metadata" => [],
         ],
       ],
       "pageNumber" => 1,
       "pageSize" => 25,
       "pageCount" => 1,
       "totalPageCount" => 1,
       "totalCount" => 1,
       "_links" => [
         "self" => [
           "href" => "/tenancies/?PageNumber=1&PageSize=25",
         ],
         "first" => [
           "href" => "/tenancies/?PageNumber=1&PageSize=25",
         ],
       ],
```

3. Note the `['_embedded'][0]['_links']['self']['href']` - `"/tenancies/MKT200007/tenants/MKT20000147"`
4. Try to query that uri
5. The result of that is a 404 Not Found

**Expected behaviour**
I expected to receive what is above in `['_embedded'][0]` as a result of the query in step 4

**Comment by plittlewood-rpt** [comment]
Hi @patryk-k  thanks for reporting. We will check this out

**Comment by cbryanreapit** [comment]
We're presenting an invalid self link here - we will correct this

**Comment by plittlewood-rpt** [comment]
PR 3169 opened

**Comment by plittlewood-rpt** [comment]
Hi @patryk-k  this has now been corrected. There is a new endpoint for retrieval of a specific relationship and the self link on the model has been corrected. Thanks for bringing this to our attention
