### ISSUE TITLE
Cannot cancel a pending revision

### ISSUE THREAD

**Issue by eazynow** [reapit/foundations#3030]
**Describe the bug**
Cannot seem to cancel a pending revision to an app. (Typo in a URL)

**To Reproduce**
Steps to reproduce the behaviour eg:
1. Make a revision to an app
2. Whilst pending, click "PENDING REVISION"
3. Click "CANCEL PENDING REVISION"
5. Click "YES, PROCEED"
4. It says I don't have the group membership required

**Expected behaviour**
Pending revision should be cancelled. 

**Screenshots**
![Screenshot 2020-11-23 at 17 32 01](https://user-images.githubusercontent.com/612686/99995290-0f5b4380-2db2-11eb-95be-ddcaec3a7017.png)

![Screenshot 2020-11-23 at 17 27 26](https://user-images.githubusercontent.com/612686/99994993-b4c1e780-2db1-11eb-9c5c-e0e763394068.png)

**Comment by AshDeeming** [comment]
Thanks for flagging this @eazynow 
We will get this investigated & keep you updated

**Comment by plittlewood-rpt** [comment]
This has now been resolved
