### ISSUE TITLE
Metadata Schema endpoints are at the bottom of the SwaggerMerger output

### ISSUE THREAD

**Issue by RWilcox-Reapit** [reapit/foundations#3045]
A series of new endpoint have been added into the DEV environment to support the MetadataSchemas. 
As it stand the swagger merge tool is mapping over the additional controller but adding it to the bottom of the list.

These endpoint are in alphabetical order and ideally we want Metadata next to MetadataSchema: 

![image](https://user-images.githubusercontent.com/61189374/100261203-511af400-2f42-11eb-8575-dd49400efaf7.png)

**Comment by plittlewood-rpt** [comment]
PR 3062 resolves this

**Comment by RWilcox-Reapit** [comment]
Closing as I've merged to Prod and its works
