### ISSUE TITLE
Provide API to allow a payments details to be partially updated

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#3061]
## Overview
This endpoint will be responsible for partially updating the details of a single payment

### Location
`PATCH /payments/{id}` (protected: **yes**)

## Request
```
{
    "status" : "pending",
    "externalReference" : "myApayaRef",
}
```

### Parameters

`id` - string - from path

### Success
**204**

### Failure
**400 Bad Request
401 Authorised
403 Forbidden
404 Not found **

### Notes
- Add links to property and contact
- For mapping notes, speak to CB

**Comment by plittlewood-rpt** [comment]
PR opened: https://dev.azure.com/reapit/Reapit.Services.Payments/_git/Reapit.Services.Payments/pullrequest/3086
