### ISSUE TITLE
Create new platform scope for payments interaction

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#3062]
**Background context**
Resources in the platform are restricted based on the application that making the request and the scopes it has been granted. We should apply this mechanism to payments.

**Specification**
- Add payments.read and govern read endpoints with this scope
- Add payments.write and govern write endpoints with this scope
- Update marketplace seed routine to provide this scope for future environments

**Comment by plittlewood-rpt** [comment]
PR open to update marketplace: https://dev.azure.com/reapit/Marketplace/_git/Marketplace/pullrequest/3087

**Comment by plittlewood-rpt** [comment]
New scopes have been added to dev environment
