### ISSUE TITLE
Update installation success modal for directApi false apps 

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#3066]
**Summary**: Currently, after installing an app we present the following modal: 

![image](https://user-images.githubusercontent.com/52408607/100464957-6587f980-30c6-11eb-9d0b-ba73845a7d21.png)

In order to refine the onboarding process for apps, we should include a button to 'Launch App' and when clicked, should open the app: 

![image](https://user-images.githubusercontent.com/52408607/100468155-c1a14c80-30cb-11eb-97ca-cc0cda873783.png)

**Function:** https://github.com/reapit/foundations/blob/master/packages/marketplace/src/utils/launch-app.ts

**Task**: Update the success modal after installing an app that is directAPI = false 
- Button label: Launch App
- Should launch app launchURI 

**In desktop mode**
- Button URL should be agencycloud://app?id=APPID&launchUri=LAUNCHURI

Example 
agencycloud://app?id=1bbe034c-859f-49f9-92f6-114a61d530bf&launchUri=https://aml-app.prod.paas.reapit.cloud

**Comment by AshDeeming** [comment]
Once link clicked, the app should open in new tab - target blank rather than load on the same page

**Comment by willmcvay** [comment]
@AshDeeming I can do this now
