### ISSUE TITLE
Journal service to respond to events emitted from other services when journalisation of an event required

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#308]
Some field level changes are recorded in the journal system for agents to view historically. Rather than requiring third party integrators to record these field changes themselves, we should consider whether this it would be better to add functionality into the platform to automatically generate these

**Specification**
- Identity key events that should be given this treatment
- Queue events from those services that should emit events
- Update journal service to respond to events and create journal entries
- Ticket to be broken down into smaller parts before scheduling

**Comment by awogan06** [comment]
Offer information is being pushed to the Offer screen but is not being recorded in the journal,  is this correct or related to above?

**Comment by cbryanreapit** [comment]
We've broken out that requirement into it's own ticket here: https://github.com/reapit/foundations/issues/4070. It will be groomed next week

**Comment by HollyJoyPhillips** [comment]
This issue has been reviewed and is too large to be handled in a single issue and requires the need to be broken down by our development team. We will add the associated/dependent issues to this ticket when available. 

The induvial tickets will then be reviewed in our weekly refinement sessions. 

For more information on our processes, please see https://foundations-documentation.reapit.cloud/dev-requests

**Comment by HollyJoyPhillips** [comment]
HP - to obtain status updates from Desktop

**Comment by plittlewood-rpt** [comment]
Logged PBI-3955 to start looking at journal entries created by server-side apps which will come into this

**Comment by plittlewood-rpt** [comment]
Chased PBI-3955

**Comment by plittlewood-rpt** [comment]
A route to allow server-side apps to create journal entries with an identity is being discussed as part of ongoing engineering strategy meetings. This is a long term goal however so it's unlikely we can reliably do this in the near term

**Comment by HollyJoyPhillips** [comment]
Relates to: https://github.com/reapit/foundations/issues/7435

**Comment by HollyJoyPhillips** [comment]
Closing as related ticket, please follow 7435
