### ISSUE TITLE
Request failure when only passing part populated applicant.renting JSON when creating new applicant entity

### ISSUE THREAD

**Issue by plittlewood-rpt** [reapit/foundations#3085]
Logged on behalf of third party developer

An internal server error is thrown by the `POST /applicants` endpoint if the `renting` properties are only part populated ie

```
"renting": {
   "rentFrom": 100
}
```

When one bound is sent (rentFrom in the example above) the service currently expects the other bound to also be present. It is throwing an internal server error rather than a validation error. We should consider whether only passing a single price bound should actually be accepted

Specification
- Ensure that validation for` POST /applicant` enforces capture of `rentFrom`, `rentTo `and `rentFrequency` fields and that the values fall within acceptable bounds
- Only to apply where the applicant is renting (not for sales)

**Comment by cbryanreapit** [comment]
To review: application rent price validation rules.

**Comment by RWilcox-Reapit** [comment]
After testing on DEV vs PROD for any possible breaking changes we've found an issue with PATCH.

BEFORE:
When passing 'marktingMode' of 'renting' to PATCH it requires the renting object to be populated with priceFrom, priceTo and rentingFrequency

AFTER:
When passing 'marktingMode' of 'renting' to PATCH with no renting info it 500's

Solution:
Update the PATCH endpoint to return validation errors like it did before when 'marketingMode' is given without renting info
