### ISSUE TITLE
Identify relationships that should function as a embeddable resource

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#311]
Examine the APIs we present and identify useful opportunities to embed relationship data.

Most relationships surfaced in `_links` is likely to be useful for our consumers.

**Comment by plittlewood-rpt** [comment]
I have started to list out resources that could be supported as part of embed operations and come up with a few thoughts that we should discuss

- It may be useful to able to configure the embed mechanism to follow a particular link in the links collection. This makes it easier to embed objects that come from a sub resource (like applicant relationships) or that are quite dynamic and take into account an entity type (like appointment attendee)
- We can't currently directly embed contacts in a lot of cases without doing it from the relationships endpoint (ie applicants). Is this a problem?

@cbryanreapit  what do you think?

**Comment by plittlewood-rpt** [comment]
Discussed list internally and agreed on general approach. Will log separate items for each service broker to be built.
