### ISSUE TITLE
Create broker services for any resource that should present an embeddable resource

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#312]
- Build broker services where request composition functionality is desirable
- Use template presented in https://github.com/reapit/foundations/issues/310 
- Create codebase, pipelines, infrastracture
- Provide required composition functionality in each service
- Ensure swagger.json updated to present functionality

**Comment by plittlewood-rpt** [comment]
Separate issues have been logged for each service requiring a broker fronting them:

Applicants: https://github.com/reapit/foundations/issues/496
Appointments: https://github.com/reapit/foundations/issues/497
Companies: https://github.com/reapit/foundations/issues/498
Contacts: https://github.com/reapit/foundations/issues/499
Documents: https://github.com/reapit/foundations/issues/500
Identity Checks: https://github.com/reapit/foundations/issues/501
Landlords: https://github.com/reapit/foundations/issues/502
Negotiators: https://github.com/reapit/foundations/issues/483
Offices: https://github.com/reapit/foundations/issues/495
Offers: https://github.com/reapit/foundations/issues/507
Properties: https://github.com/reapit/foundations/issues/503
Property Images: https://github.com/reapit/foundations/issues/504
Tasks: https://github.com/reapit/foundations/issues/505
Vendors: https://github.com/reapit/foundations/issues/506
