### ISSUE TITLE
Situation where appointment attendee contacts can be duplicated in the appointments API

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#3138]
We have identified a situation where if a contact appears as an attendee in a single page of appointments, the attendee contact will appear duplicated against each appointment it is associated to (one duplicate per appointment)

To reproduce this issue using sandbox data, issue the following request:

https://platform.dev.paas.reapit.cloud/appointments?negotiatorId=adv&end=2020-12-14T23:59:59.999Z&start=2020-12-08T00:00:00.000Z&includeCancelled=true&includeConfirm=true

**Comment by plittlewood-rpt** [comment]
PR opened: https://dev.azure.com/reapit/Reapit.Services.Appointments/_git/Reapit.Services.Appointments/pullrequest/3164

**Comment by plittlewood-rpt** [comment]
Retested on dev, example URL returns correct data
