### ISSUE TITLE
Identify platform services that should respect office group data boundaries

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#3152]
**Background context**

We should review all platform services and assess which of those should respect the data boundaries that our office group mechanism enforces.

**Acceptance Criteria:**
- Identify which services contain data scoped by office
- Design how this data can be restricted appropriately
- Create tickets for each service requiring an update

**Comment by plittlewood-rpt** [comment]
WIP:

Applicants -> app.OffCode, app.Shared
Contacts -> cnt.OffCode, cnt.Shared
Companies -> cnt.OffCode, cnt.Shared
Properties -> prp.OffCode, prp.OffCode2, prp.OffCode3
Vendors -> prp.OffCode, prp.OffCode2, prp.OffCode3
Appointments -> diary.OffCode, lookup.CodeTo
Landlords -> lld.OffCode

IdentityChecks -> based on the contact entity (cnt.OffCode, cnt.Shared)
Offers -> based on the property entity (prp.OffCode, prp.OffCode2, prp.OffCode3)

Negotiators -> neg.OffCode
Tenancies -> cnt.OffCode, cnt.Shared - but only when tenancy is current
Payments -> cnt.OffCode, cnt.Shared

**Comment by plittlewood-rpt** [comment]
Services identified and spreadsheet circulated to team for discussion. Will hold off creating tickets for now until we've agreed a concrete list
