### ISSUE TITLE
Investigate and architect auction support

### ISSUE THREAD

**Issue by Nialld** [reapit/foundations#3169]
The RPS desktop system supports auction fields such as Lot number / reserve price / guide price / buyer deposit etc... i would like these fields to be accessible via the new API

The current API only supports general private treaty sales... yes there is an option to set the disposal as auction but the fields mentioned above are nowhere to be seen in the current docs

**Specification**
- Outcome of this ticket is to architect and approach, discuss with the team, write technical implementation tickets
- This work should be for read only endpoints only at this stage

**Comment by cbryanreapit** [comment]
For internal: we need to perform a deep dive required on auctions functionality before we can progress

**Comment by awogan06** [comment]
This is something urgently required for SF also
