### ISSUE TITLE
Add 'modifiedFrom' parameter to more collection endpoints.

### ISSUE THREAD

**Issue by BYM-Henry** [reapit/foundations#3189]
**Is your feature request related to a problem? Please describe.**
We need to be able to pull daily changes of objects through the foundations API, we can do this by using the 'modifiedFrom' parameter, however this is only available on a handful on endpoints currently.

**Describe the solution you'd like**
We would need the 'modifiedFrom' parameter added to more endpoints. We would need this to work in a similar way to the parameter in the properties collection endpoint with the following description:

"Only return properties which have been modified/created since the given ISO8601 date and time provided."

This would then allow us to get all objects in a collection with the least amount of API calls. Ideally this would be on all collection endpoints, but we currently require this on the following endpoints:

- [x] GET /applicants/
- [x] GET /areas/
- [x] **GET /appointments/**
- [x] GET /companies/
- [x] GET /contacts/
- [x] GET /landlords/ - RW
- [x] GET /negotiators/
- [x] GET /offers/
- [x] GET /offices
- [x] GET /tenancies/ - This contains the parameter but it does not seem to include the created field
- [x] GET /vendors/

/appointments/ is the most important endpoint as we do not have a workaround for this currently as explained below.

**Describe alternatives you've considered**
A current workaround we have is making use of the 'sortBy' parameter that is available on most collection endpoints, we can use this on the modified field in descending order and then stop the paging once we can see a value below our required modified date.

However as modified seems to be nullable, this also requires us to do a separate pull with the 'sortBy' parameter on the created field in descending order. Only then are we guaranteed to have all objects that have been created or modified after our required date.

This workaround is inefficient and inaccurate for us as it requires us to reduce the pageSize parameter (to increase accuracy) and make two sets of calls per collection. Furthermore this workaround does not work for all collection endpoints (particularly GET /appointments/) as it lacks the ability to sortBy the modified date.

Please let me know if you need anymore information on this feature request.

Many Thanks,

Henry Fitch
Integrations Developer

BriefYourMarket

**Comment by plittlewood-rpt** [comment]
Hi @BYM-Henry  thanks for getting in touch. It may be the New Year before we get to this. In the meantime have you considered using web hooks so you can receive updates in real time as that would eliminate the need for a 'polling' type app at all?

**Comment by plittlewood-rpt** [comment]
PR 3214 opened to update offices API. Implementation is as follows:

- Modified field is now always populated rather than being null. For new records that have not yet been amended since first save, modified == created.
- In the offices API it is now possible to filter based on created or modified date (the latter with the above being taken into account) and also sort by these two fields.

**Comment by plittlewood-rpt** [comment]
Hi @BYM-Henry - the update outlined above has been released to production on the offices API if you want to have a look. Other endpoints will follow soon but it may take a short while before we get through them all. Any feedback on the changes welcome

**Comment by plittlewood-rpt** [comment]
PR 3249 opened to update areas API

**Comment by plittlewood-rpt** [comment]
PR 3250 opened to update companies API

**Comment by plittlewood-rpt** [comment]
PR 3251 opened to update contacts API

**Comment by plittlewood-rpt** [comment]
Hi @BYM-Henry - this has now been implemented. Please let me know if you have any problems
