### ISSUE TITLE
Build pipeline/env for SMB App

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#32]
- Create env for the SMB Project: dev.smb-app.reapit.com & smb-app.reapit.com
- Should use Github Actions
- Should run unit and e2e tests before deploying
- Should deploy to development when merging to master
- Should deploy to prod when pushing a tag as per other apps

**Comment by tanphamhaiduong** [comment]
@willmcvay, @HollyJoyPhillips could we remove run e2e in the scope of the ticket, as now BE use the same for PROD and DEV so we cannot run it right?

**Comment by tanphamhaiduong** [comment]
@willmcvay and @HollyJoyPhillips one more things just want to clarify with you 
`Create env for the SMB Project: dev.smb-app.reapit.com & smb-app.reapit.com`
It should be .com or .cloud
