### ISSUE TITLE
Update to the ‘Billing’ spreadsheet 

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#3203]
**Summary**: To make the distinction between apps on an invoice, we should include the ‘App Name’ & split the API Requests as an additional row per App Listing 

This will make it clear what API requests are being associated to which app, when a developer has multiple apps. 

Currently, all subscriptions and consumption charges are presented on one line: 
 
![image](https://user-images.githubusercontent.com/52408607/102626878-4fa6ab00-413f-11eb-8672-003f40e2d0a1.png)

For each app and associated API requests, we should create a separate row, for example: 
 
![image](https://user-images.githubusercontent.com/52408607/102626882-52a19b80-413f-11eb-876e-19f6d58398b4.png)

**Comment by cbryanreapit** [comment]
No longer required
