### ISSUE TITLE
GET by last modified date 

### ISSUE THREAD

**Issue by TomFixflo** [reapit/foundations#3204]
**Is your feature request related to a problem? Please describe.**

As Fixflo, I am currently using the following Reapit endpoints: 

- GET Landlords 
- GET Vendors 
- GET Negotiators 
- Get Contacts 

The problem = currently, the call is returning all of the above records, regardless of whether or not the record has changed since the last call was made. 

**Describe the solution you'd like**

It would be great, if like Get Properties, I could filter records retrieved by last modified date. 

**Describe alternatives you've considered**

I know that I can use the webhooks BUT in the medium term but in the short term this would be useful.

**Comment by cbryanreapit** [comment]
Hi @TomFixflo - this issue has already been logged at https://github.com/reapit/foundations/issues/3189 which includes all of your request - we'll be working on it from this ticket so please feel free to follow it.

Thanks for the feedback.
