### ISSUE TITLE
Get journalEntries from a propertyId

### ISSUE THREAD

**Issue by hectorperez** [reapit/foundations#3211]
**Is your feature request related to a problem? Please describe.**
I'm trying to get the journal entries from a property.

The POST journalEntries endpoint has a `propertyId`. However, GET journalEntries has no `propertyId` parameter - and `associatedType` doesn't include "property".

**Describe the solution you'd like**
In the GET journalEntries endpoint, I'd like a new propertyId parameter.

**Describe alternatives you've considered**
Another option would be to include an `associatedType` "property" so I can use `associatedId` to filter.

**Additional context**
We'd like to use this in our Barbuck integration.

Thank you!

**Comment by plittlewood-rpt** [comment]
Changelog entry created

**Comment by plittlewood-rpt** [comment]
Hi @hectorperez  this has now been implemented. Any issues let us know!

**Comment by hectorperez** [comment]
@plittlewood-rpt That's brilliant, thank you! I had a quick look and it looks great. I'll test it more on Thursday.
