### ISSUE TITLE
Webhook containing officeIds array empty/not populating

### ISSUE THREAD

**Issue by RachelLightfoot** [reapit/foundations#3216]
**Describe the bug**
When processing a webhook call, we are comparing the list of office (branch) Ids received in a webhook containing the ‘officeIds’ array with the list of branch codes stored against the account and it will not proceed unless it finds a match. However, in the below webhook you will see that the ‘officeIds’ array is empty (compare to the ‘negotiatorIds’ array above it) and so we have nothing to compare, the comparison fails and the processing of the webhook halts.

**Error example**
At 16:42:49 on Friday 18th we received the following webhook call from Reapit:

(

    [eventId] => 9baf2bd8-e095-4f27-907e-15986eae45bc

    [entityId] => MIM2005017

    [customerId] => HMJ

    [eventTime] => 2020-12-18T16:42:49.2673081Z

    [topicId] => appointments.created

    [new] => Array

        (

            [id] => MIM2005017

            [created] => 2020-12-18T16:42:42Z

            [modified] =>

            [start] => 2020-12-21T17:00:00Z

            [end] => 2020-12-21T17:15:00Z

            [typeId] => PI

            [description] =>

            [recurring] =>

            [recurrence] =>

            [cancelled] =>

            [followUp] => Array

                (

                    [due] =>

                    [responseId] =>

                    [notes] =>

                )

 

            [propertyId] => MIM120132

            [organiserId] => SEM

            [negotiatorIds] => Array

                (

                    [0] => SEM

                )

 

            [officeIds] => Array

                (

                )

 

            [attendee] =>

            [accompanied] => 1

            [negotiatorConfirmed] =>

            [attendeeConfirmed] =>

            [propertyConfirmed] =>

            [_eTag] => "AB2F2BCBFA240D9EB5FA4DAB6FF233EE"

        )

 

    [old] =>

    [diff] => Array

        (

        )

 

)

**Expected behaviour**
Whilst we do not know the logic that Reapit uses to determine the contents of this array, we would expect based on our understanding of the system and the API documentation to find it populated with one or more branch codes (specifically MIM in this instance).

**Comment by Bryazon** [comment]
Hey Rachel - thanks for the report - some questions if I may:

- Is this happening for all of the customers who use your app or just some?
- It it happening for both appointment created and modified topics?
- Do you see this data condition for every webhook you receive or is it sporadic? 
- Did you different behaviour when testing webhooks via the developer edition of agency cloud?

**Comment by cbryanreapit** [comment]
Hey Rachel - thanks for the report - some questions if I may:

Is this happening for all of the customers who use your app or just some?
It it happening for both appointment created and modified topics?
Do you see this data condition for every webhook you receive or is it sporadic?
Did you different behaviour when testing webhooks via the developer edition of agency cloud?

**Comment by RachelLightfoot** [comment]
Hi. Apologies I've only just seen this comment.  I've answered the questions below, I will need to run some tests to see whether different behaviour is happening in the developer edition of agency cloud.

- Yes it's happening for all customers who use the app.
- It is only being tested for appointments created as this is being used by customers for the first time.
- I believe this is happening for every webhook where the ‘officeIds’ array is being pulled.

**Comment by RachelLightfoot** [comment]
Further to this, I have run some tests in the developer edition of agency cloud and appointments/properties are not coming across via webhooks.  Our support team are checking the logs for further details but I can only assume the same issue is present. Can you check the ‘officeIds’ array to see if there are any errors?  We have customers chasing us on this now so a quick resolution would be appreciated.

**Comment by Bryazon** [comment]
Thanks for the information @RachelLightfoot - I will make sure this gets looked at tomorrow.

**Comment by cbryanreapit** [comment]
Thanks for the information @RachelLightfoot - I will make sure this gets looked at tomorrow.

**Comment by plittlewood-rpt** [comment]
PR 3212 opened

**Comment by RachelLightfoot** [comment]
Hi Pete.  I have some more information for you on this - see below.  Essentially we think we are seeing the expected officeIds from your sandbox but not from the production environment, which would perhaps indicate a problem with said environment or even just a difference in configuration between the accounts in each environment. 

2) We’re seeing the same behaviour on appointments.modified topics

3) This seems to be every appointments.created and appointments.modified topic, but not any other topics (that we have seen) e.g. I can see an applicants.modified topic which does have a populated officeIds array.

Now, moving on to point 4, we’ve checked the logs (had to look on staging as the Reapit Sandbox environment is set up to fire webhooks here, rather than live) and can see the webhooks coming through for these appointments with populated officeIds. First one:

(

    [eventId] => e43a0584-637e-4b1d-a3b8-1eeb5d4409e2

    [entityId] => MKT2100002

    [customerId] => SBOX

    [eventTime] => 2021-01-04T13:40:32.6727503Z

    [topicId] => appointments.created

    [new] => Array

        (

            [id] => MKT2100002

            [created] => 2021-01-04T13:40:29Z

            [modified] => 2021-01-04T13:40:29Z

            [start] => 2021-01-04T14:00:00Z

            [end] => 2021-01-04T14:30:00Z

            [typeId] => CI

            [description] =>

            [recurring] =>

            [recurrence] =>

            [cancelled] =>

            [followUp] => Array

                (

                    [due] =>

                    [responseId] =>

                    [notes] =>

                )

 

            [propertyId] => MKT200020

            [organiserId] => ADV

            [negotiatorIds] => Array

                (

                    [0] => ADV

                )

 

            [officeIds] => Array

                (

                    [0] => MKT

                )

 

            [attendee] =>

            [accompanied] => 1

            [negotiatorConfirmed] =>

            [attendeeConfirmed] =>

            [propertyConfirmed] =>

            [_eTag] => "9F4EBB8E6349B8B114E5F0754CF0ED57"

        )

 

    [old] =>

    [diff] => Array

        (

        )

)

And second one:

(

    [eventId] => 664360a0-37e2-47f6-8eef-84821104e694

    [entityId] => MKT2100003

    [customerId] => SBOX

    [eventTime] => 2021-01-04T13:43:09.7005693Z

    [topicId] => appointments.created

    [new] => Array

        (

            [id] => MKT2100003

            [created] => 2021-01-04T13:43:03Z

            [modified] => 2021-01-04T13:43:03Z

            [start] => 2021-01-04T15:00:00Z

            [end] => 2021-01-04T15:30:00Z

            [typeId] => PI

            [description] =>

            [recurring] =>

            [recurrence] =>

            [cancelled] =>

            [followUp] => Array

                (

                    [due] =>

                    [responseId] =>

                    [notes] =>

                )

 

            [propertyId] => MKT200057

            [organiserId] => ADV

            [negotiatorIds] => Array

                (

                    [0] => ADV

                )

 

            [officeIds] => Array

                (

                    [0] => MKT

                    [1] => MRK

                )

 

            [attendee] =>

            [accompanied] => 1

            [negotiatorConfirmed] =>

            [attendeeConfirmed] =>

            [propertyConfirmed] =>

            [_eTag] => "D3ED344E858722880137AD3108D113BC"

        )

 

    [old] =>

    [diff] => Array

        (

        )

)

**Comment by plittlewood-rpt** [comment]
Hi @RachelLightfoot  thanks for your commentary - it's not a difference between sandbox and production, more to do with the original intended use of this field. I'm not sure if you have access to Agency Cloud Developer Edition but the `officeIds` array currently only lists out offices who are explicitly added as accompanying 'attendees' on a particular appointment. In the case of the first example above this is the 'Marketplace' (MKT) office:

![image](https://user-images.githubusercontent.com/30798627/103654252-895c1c00-4f5d-11eb-83dd-d87b6732efb5.png)

I am currently in the process of ensuring that the officeId associated with the primary negotiator whose diary an appointment is booked in is included in the officeId array which will give you what you want. This isn't something that a user can actually set themselves in Agency Cloud so it's a slight difference in usability between Agency Cloud and the appointments API. I think what I'm working on will solve your problem and it should be ready soon. 

If you create an appointment in Agency Cloud and choose not to set any additional offices then access that appointment via the API, you'll notice that `officeIds` remains empty. In the next release of the API `officeIds` will always contain the officeId of the office that the primary negotiator on the appointment belongs to, even though this isn't actually visible inside Agency Cloud

Hope this helps

**Comment by RachelLightfoot** [comment]
Ok that should solve the issue. When I was testing yesterday I was including the 'Marketplace' office ID but it still wasn't pulling through.  Your solution of including the officeIDs that is associated with the primary negotiator whose diary the appointment is being scheduled in should resolve this.

**Comment by plittlewood-rpt** [comment]
Hi @RachelLightfoot 

That's now been implemented and released - can you let me know if you have any issues with it? Thanks

**Comment by plittlewood-rpt** [comment]
Changelog updated
