### ISSUE TITLE
Ability to set an uploaded PDF as the 'Predefined Details' for Marketing

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#3233]
**Background context or User story:**
As a company providing PDF brochures for agents to use for marketing, they can upload via the Documents API but cannot specify if that PDF should be the one to use for portals/websites as the default PDF. 

**Specification or Acceptance Criteria:**
In Agency Cloud you can upload a PDF in the 'Predefined Details' as either sales details or lettings. Additionally, you can upload a PDF via letters and select 'Set as sales particulars' or 'Set as lettings particulars' which determines that the brochure can be used for marketing. 

**Suggested solution:**
Provide the ability to set a PDF document upload as the Predefined details (either sales or lettings) 

![image](https://user-images.githubusercontent.com/52408607/103674970-4c048800-4f77-11eb-8591-40715052ed5c.png)

![image](https://user-images.githubusercontent.com/52408607/103675046-63437580-4f77-11eb-9c4e-a3431199801a.png)

**Specification**
- Provide ability to set sales / lettings documents as the primary/predefined details for property marketing
- Update PATCH /properties to allow this information to be set
- Update GET /properties and GET /properties/{id} to allow this information to be surfaced

**Comment by Mike-PygottandCrone** [comment]
Just want to reiterate how useful we at Pygott & Crone would find this feature, it would be great if this feature could be added soon!

**Comment by W00dy-PygottandCrone** [comment]
Hi Paul from Pygott and Crone here, please can this issue be moved to a higher priority. We have developed online brochure creation which has saved a huge amount of admin time, and we want the ability to push our automatic PDF brochure into RPS and set as the property particulars. Thanks Woody

**Comment by plittlewood-rpt** [comment]
PR 3233 opened
