### ISSUE TITLE
Property modifications involving the 'special' property attributes do not appear with API

### ISSUE THREAD

**Issue by kitoban** [reapit/foundations#3242]
**Is your feature request related to a problem? Please describe.**
When updating a property with a 'special' property attributes change this triggers an update webhook but there is no change denoted against the property.

**Describe the solution you'd like**
Extension of the property model to include these attributes, in the same way as situation, parking etc.

**Comment by kitoban** [comment]
Any news on progress with this issue?

**Comment by cbryanreapit** [comment]
Please see recent functionality introduced: https://foundations-documentation.reapit.cloud/whats-new#configurable-webhook-behaviour - you can now specify whether your application needs to be made aware of eTag/modified only changes using the new webhook setting.

**Comment by kitoban** [comment]
eTag/modified behaviour is unrelated to this issue, there are values against the property that do not appear within the schema.
