### ISSUE TITLE
Documentation update to show the default options for our configuration types

### ISSUE THREAD

**Issue by RWilcox-Reapit** [reapit/foundations#3263]
A number of live chats have come through requesting the default values for various configuration types. 
Currently these have been handled on an ADHOC basis but it may be worth adding a section to the documentation to show the default types we seed (along with the information that custom ones can be added)

**Comment by plittlewood-rpt** [comment]
@RWilcox-Reapit  do you mean department types or something else? You can't customise departments as far as the API is concerned

**Comment by RWilcox-Reapit** [comment]
Updated to configuration types @plittlewood-rpt
