### ISSUE TITLE
Displaying standalone metadata in agency cloud app.

### ISSUE THREAD

**Issue by JamesIreland-Savills** [reapit/foundations#3269]
When creating standalone metadata I would like to be able to display that data against the relevant reapit entity.

E.G. if i create an metadata entity called "CustomEntity", which has a propertyId attribute in it (which stores the reapit property id), I would like to be able to display this information against the specific property on the screen somewhere.

**Comment by cbryanreapit** [comment]
Hi James. Agency Cloud does not provide an inbuilt user interface for you to be able to present metadata inside of the application. Instead, you should build your own user interface for that that can then be launched from within Agency Cloud. You're able to build a fully functional application that can be seamlessly hosted inside of Agency Cloud to capture and present any information you wish. 

Our [developer portal](https://developers.reapit.cloud/api-docs/api/developer-portal) and [desktop API](https://developers.reapit.cloud/api-docs/api/desktop-api) documentation should provide you with the information you need to start building. Additionally, be sure to check out the the [various open source resources](https://developers.reapit.cloud/api-docs/app-development) we provide to assist in your development.
