### ISSUE TITLE
Provide additional flexibility for how webhook notifications are emitted

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#3271]
**Background context**
Presently, our data driven webhooks will emit the entities current eTag state as part of the payload. This is to support the case where future updates are required to that object without requiring an API hit to fetch the latest state of the eTag. This is not always a fitting case for our partners however and in some cases, it may mean that our partners receive notifications that they may not require. 

**Specification**
- Provide configuration ability on webhook topic subscriptions to control conditions of when they are emitted
- Existing webhooks need to work as they do now, new webhooks should adopt the new mechanism (configured by developer) 
- Where new mechanism in place, we should no longer emit webhooks where the eTag/modified date has changed without other significant payload change
- Default value in CREATE payload to be false, but the UI should populate true by default. 
- Documentation update required
- This will require a user interface update (ticket to come)

**Comment by plittlewood-rpt** [comment]
PR 3462 opened

**Comment by plittlewood-rpt** [comment]
@HollyJoyPhillips the backend work to support this change has now been released. Can I leave it with you to pick up the UI ticket please? The UI should populate true by default for the new flag.

@cbryanreapit let's discuss the documentation change as that probably doesn't want to happen until the UI goes out

**Comment by cbryanreapit** [comment]
Sounds good @plittlewood-rpt 

@HollyJoyPhillips nudge me when it comes to putting together the textual option for the UI

**Comment by plittlewood-rpt** [comment]
Documentation draft is saved ready to go once UI is ready so this can now be closed
