### ISSUE TITLE
Add 'Virtual' tick box to to the Appointments API 

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#3287]
**Summary**: Agency Cloud have implemented a 'Virtual' tick box on 'Appointments'. Please can we look to make this available in the Appointments API: 

![image](https://user-images.githubusercontent.com/52408607/104585145-88ad3f00-565b-11eb-8919-046582edb0f0.png)

**Comment by cbryanreapit** [comment]
To add a 'virtual' flag to the appointment model (read/write)
