### ISSUE TITLE
propertyImage.modified generates a lot of messages on sort operations.

### ISSUE THREAD

**Issue by kitoban** [reapit/foundations#3289]
**Is your feature request related to a problem? Please describe.**
When a user moves an image or sets a new main image (single click operation) we are seeing a large number of propertyImage.modified webhook events being triggered as the SortOrder is stored as an int on the property image itself, and every image has received an update.

**Describe the solution you'd like**
If the storage of the sort is changed to a linked list of next item in list then the order change would only effect the images surrounding the change which could vastly reduce the number of update events going through the system

**Describe alternatives you've considered**
Alternatively a mechanism to batch the updates on the webhook for this sort of single click operation would reduce the noise.

**Additional context**
Scenarios: 
- user adds a new image to a pre-existing property that has 10 images already, then sets the new image as the master image. (i.e. property have asked for a new main image to update their advert)
- user is in the process of uploading a batch of images to a property and adds them in any order, then proceeds to work through then and order them to best highlight the property by dragging and dropping the order until they are satisfied. (each drag drop operation can trigger up to the image count number of webhook triggers)

**Comment by cbryanreapit** [comment]
@kitoban thanks for the feedback. Agree that in some cases a batch webhook mechanism would be a more appropriate delivery format, so have created https://github.com/reapit/foundations/issues/3315 to supercede this ticket
