### ISSUE TITLE
Rate Limit Per Client

### ISSUE THREAD

**Issue by BYM-Henry** [reapit/foundations#3295]
**Is your feature request related to a problem? Please describe.**
By imposing a rate limit per application the speed of our integration will decrease as we acquire more clients. It also means on our side we need to make infrastructure changes so each instance of the integrations (for each client) are aware of each other so we can throttle accordingly.

This makes it difficult for us to give the customer a reliable timeframe when their integration will complete as it is completely dependant on how many other customers are running an integration.

**Describe the solution you'd like**
To have the rate limits (20 calls per second, 250,000 calls per day) based on the 'client_id' used and not just the application.

**Describe alternatives you've considered**
Alternative solutions would be infrastructure changes on our side (proxy that all requests go through) so we can throttle all requests made to the foundations API. However this has some drawbacks as explained above. 

**Additional context**
No but please let me know if you have any questions.

Many Thanks,

Henry Fitch
BriefYourMarket
Integration Developer

**Comment by cbryanreapit** [comment]
As discussed, we'll look at this in the longer term with shorter term solution available to us

**Comment by HollyJoyPhillips** [comment]
@BYM-Henry We are currently reviewing our Long Term column and would like to know if this is still a requirement? Thanks.

**Comment by BYM-Henry** [comment]
Hi @HollyJoyPhillips,

I can confirm this is no longer a requirement for us.

Thanks.

**Comment by HollyJoyPhillips** [comment]
@BYM-Henry Thank you for coming back to us.
