### ISSUE TITLE
Present archived data for some platform entity types

### ISSUE THREAD

**Issue by BYM-Henry** [reapit/foundations#3296]
**Is your feature request related to a problem? Please describe.**
We have customers who want to be able to filter out and market to archived contacts or exclude archived data from their marketing emails. To do this ideally we would be able to pull archived data from the API, we could then flag this on our side as archived. It also helps if we can have as much data parity with Reapit as possible as the data requirements each customer can be different.

**Describe the solution you'd like**
The ability, perhaps with a parameter, to receive archived data for contacts, companies, 'vendors'? (not sure if this can be archived in Reapit), applicants and landlords. We would also need a value similar to the active flag on these entities to show if the entity is archived.

**Describe alternatives you've considered**
Webhook's give us the ability to find out when a entity becomes archived, but doesn't let us pull archived data. We currently don't use web hooks for the integration so would require changes our side to get this working.

**Additional context**
No, but please let me know if you have any questions.

Many thanks,

Henry Fitch
Integration Developer
BriefYourMarket

**Comment by cbryanreapit** [comment]
Hi Henry - as you noted, webhooks are our mechanism to broadcast when an entity has been archived, rather than returning every historical archived record from our APIs. I have however backlogged this item for future consideration.

**Comment by BYM-Ricky** [comment]
Hi @cbryanreapit, really appreciate your response. 

It's definitely possible for us to implement webhooks as it might be useful for various things in the future, i.e. live updates.

However, in an attempt to bump what we really need up in your feature backlog, webhooks don't really fulfil our mutual customers requirement or what they are asking for in an integration. As I understand and as Henry expressed, a webhook will tell us in real time when a change happens, meaning we get archived data moving forward, but not backward. 

You might be confused why we are asking for this so let me give you a bit of context, apologies if I'm stating the obvious but I'm well aware you have many requirements coming your way. We have learned that more than 70% of our customers valuable data lives in their archive, and so all their business they are likely to generate through marketing lives in that data. We aren't that bothered with utilising current changes as this is more transactional, and most CRMs already update clients when those changes happen and so, even though we do those sort of communications it's not really our core objective, our our customers that use our product in conjunction with Reapit.

Therefore, without all of the archived data products like ours can't be in the market place and we will have to continue utilising your older APIs. I was just wondering what Reapits take on that is, and try and gauge how that affects your roadmap for this feature request?

Other than that though, really enjoying the experience developing against foundations!

Thanks,
RB

**Comment by cbryanreapit** [comment]
@BYM-Henry thank you for the detailed explanation - that definitely gives us a better understanding of your use case. I will be in touch with a response ASAP.

**Comment by BYM-Ricky** [comment]
@cbryanreapit Thanks, we really appreciate your help on this!

**Comment by cbryanreapit** [comment]
Prioritised list of entities to review at grooming:

1.	Contacts
2.	Vendors
3.	Properties
4.	Applicants
5.	Appointments
6.	Landlords
7.	Tenancies
8.	Companies

**Comment by cbryanreapit** [comment]
The work comprised to deliver this ticket is substantial, so will be broken into multiple tickets. Have updated the state of this issue while new tickets are written and scoped, at which point we'll close it. Links to be added here so that they may be tracked.

**Comment by cbryanreapit** [comment]
Contacts: https://github.com/reapit/foundations/issues/3466

**Comment by cbryanreapit** [comment]
Companies: https://github.com/reapit/foundations/issues/3467

**Comment by cbryanreapit** [comment]
Vendors: https://github.com/reapit/foundations/issues/3468

**Comment by cbryanreapit** [comment]
Applicants: https://github.com/reapit/foundations/issues/3469

**Comment by cbryanreapit** [comment]
Landlord: https://github.com/reapit/foundations/issues/3470

**Comment by cbryanreapit** [comment]
Property: https://github.com/reapit/foundations/issues/3472

**Comment by cbryanreapit** [comment]
Appointments: https://github.com/reapit/foundations/issues/3473

**Comment by cbryanreapit** [comment]
Tenancies: https://github.com/reapit/foundations/issues/3474

**Comment by cbryanreapit** [comment]
Issue superceded by afforementioned issues - closed.
