### ISSUE TITLE
Provide API for tenant guarantors and references

### ISSUE THREAD

**Issue by amandapun** [reapit/foundations#3312]
**Problem:**

Currently, data about guarantors for tenants cannot be called via the API. We require information about guarantors including information about:
- if a tenant has a guarantor
- the guarantor's contact details

We require guarantor information so that we can initiate a guarantor referencing check to assess the guarantor's eligibility to be the tenant's guarantor 

**Specification**
Before commencing work on the below ensure you are comfortable with the AC behaviour and data store

We will provide read only APIs to allow the guarantor and reference information to be surfaced for each individual tenant associated with a tenancy

Guarantor/reference information is stored in the extra table with type LG and LR respectively. The relationship is between the applicant/tenant and a contact or company

`GET /tenancies/{id}/relationships/{relationshipId}/references`
`GET /tenancies/{id}/relationships/{relationshipId}/guarantors`

```
{
  "_embedded": [
    {
      "id": "OXF18000001",
      "created": "2018-02-12T09:45:01.0000000Z",
      "modified": "2019-06-23T12:30:12.0000000Z",
      "title": "Mr",
      "forename": "John",
      "surname": "Smith",
      "homePhone": "01234 567890",
      "workPhone": null,
      "mobilePhone": "07890 123456",
      "email": "example@email.com",
      "primaryAddress": {
        "type": "primary",
        "buildingName": null,
        "buildingNumber": "15",
        "line1": "Example street",
        "line2": "Solihull",
        "line3": "West Midlands",
        "line4": null,
        "postcode": "B91 2XX",
        "countryId": "GB"
      }
      "_links": {
        "self": {
          "href": "/tenancies/{id}/relationships/{relationshipId}/guarantors/OXF18000001"
        },
        "tenancy": {
          "href": "/tenancies/{id}"
        },
      },
      "_embedded": null
    }
  ],
  "pageNumber": 1,
  "pageSize": 1,
  "pageCount": 1,
  "totalPageCount": 1,
  "totalCount": 50,
  "_links": {
    "self": {
      "href": " /tenancies/{id}/relationships/{relationshipId}/guarantors/?PageNumber=1&PageSize=1"
    },
    "first": {
      "href": " /tenancies/{id}/relationships/{relationshipId}/guarantors/?PageNumber=1&PageSize=1"
    },
    "next": {
      "href": " /tenancies/{id}/relationships/{relationshipId}/guarantors/?PageNumber=2&PageSize=1"
    },
    "last": {
      "href": " /tenancies/{id}/relationships/{relationshipId}/guarantors/?PageNumber=50&PageSize=1"
    }
  }
}

```

**Comment by cbryanreapit** [comment]
We'll provide APIs to surface information about tenant guarantors. However, this body of work is unlikely to include the third point in your request, since this is information we do not currently capture. 

Implementation information to follow.

**Comment by amandapun** [comment]
@cbryanreapit Thanks for getting back to me. What's the timeline to implementation?

**Comment by cbryanreapit** [comment]
For internal: deep dive required on this functionality - outcome of this will be new set of tickets with API contracts designed

**Comment by plittlewood-rpt** [comment]
Internal discussions ongoing with product

**Comment by fargp** [comment]
This would be needed for our integration as well. (@Openbrix)
The following fields will be generated on our side : 
gaurantor.name
gaurantor.first_name
gaurantor.last_name
gaurantor.title
gaurantor.number
gaurantor.email
gaurantor.correspondece_address
gaurantor.post_code
gaurantor.full_reference_data

**Comment by HollyJoyPhillips** [comment]
After a discussion with the Foundations team, we are now in a position to re review this request.

**Comment by HollyJoyPhillips** [comment]
This is now in production as part of ticket: https://github.com/reapit/foundations/issues/9537

More information can be found here: https://foundations-documentation.reapit.cloud/whats-new#id-31-12-23
