### ISSUE TITLE
Applicant advanced rent payment information provided in API response

### ISSUE THREAD

**Issue by amandapun** [reapit/foundations#3313]
**Requirement:**

- To help us to assess the applicant's affordability for a tenancy referencing check, we are required to have data to understand if the applicant is paying for rent in advance
- If the applicant is paying rent in advance, we are required to know how much rent is being paid in advance (e.g. 6 months of rent or full rent is paid upfront)

**Specification**

- Add three new fields to the tenancies API for GET, PATCH and POST
- `rentInstalmentsFrequency` captures the frequency of rental instalment payments
- Validate that when `rentInstalmentsFrequency` provided, this value falls within acceptable enumeration values
- `rentInstalmentsAmount` captures the size of the instalment in monetary value
- Validate that when `rentInstalmentsAmount`  provided, this value is greater than zero.
- `rentInstalmentsStart` captures the date that the first instalment is due
- Ensure this is a date only field (and document)

** Technical **
- `rentInstalmentsFrequency` maps to structured field 'rentFreq'
- Available options as below (please use a smart enumeration)
        /// 7 - Weekly
        /// 14 - Fortnightly
        /// MO - Monthly
        /// QU - Quarterly
        /// HY - Half Yearly
        /// YR - Yearly
        /// 28 - 28 Days
        /// OT - Other
- `rentInstalmentsAmount` maps to structured field `inst`
- `rentInstalmentsStart` maps to structuered field `firstinst`
- Test particularly that when creating new records, the lack of these fields being provided is not be a breaking change

**Comment by cbryanreapit** [comment]
We'll surface the rent payment frequency as part of the tenancies API - implementation details to follow.

**Comment by cbryanreapit** [comment]
Need to confirm behaviour with AC
