### ISSUE TITLE
Surface Lost MA information from Properties APIs

### ISSUE THREAD

**Issue by hectorperez** [reapit/foundations#3314]
**Describe the solution you'd like**
We would like the `sellingStatus` `lostMA` to be exposed in the `GET /properties` endpoint as well as in `GET /vendors` when `"embed" = "property"`.

**Additional context**
We at Barbuck are interested in `Pre Appraisal`, `Market Appraisal` (`valuation`), `Withdrawn` and `Lost MA`. This last one is the only one we can't access at the moment.

Thank you!

**Comment by cbryanreapit** [comment]
Reapit allow for agents to continue tracking the status of a potential instruction after they have lost the market appraisal. As such, we do not have a sales status of 'Lost MA'. We do record the date an instruction was lost and the reason for that, which we'll surface as an enhancement to the properties API.

**Comment by hectorperez** [comment]
Thank you
