### ISSUE TITLE
Enquires API - Surname character error

### ISSUE THREAD

**Issue by AshDeeming** [reapit/foundations#3318]
**Describe the bug**

Simon from Yomdel has flagged that he is getting an error on the enquires API for length of surname. Holly confirmed last year and it was 45 chars but this is the payload with error using 'TestTownsend2' as the surname: :

 "requres body = {'title': 'N/A', 'forename': 'TestTownsend2', 'surname': 'TestTownsend2', 'position': 'renting', 'enquiryType': 'salesProperty', 'message': "This is a test please ignore. Further information is contained in the chat transcript below.\n\nTranscript\nAli: Hi, how can I help you?\nVisitor: Hi Ali- quick technical test - please could you close the chat and tag as 'Lead' 'buyer/seller' \nVisitor: and then retag as 'non-lead (test)'\nAli: Thanks for coming on chat. Let me see what I can do for you.\nAli: Thank you very much for using our live chat service. You can email this transcript to yourself via the button at the top of the chat window.\nAli: Please also feel free to leave a comment on your live chat experience after closing the chat window. Thanks again and goodbye.\n", 'officeId': 'MKS', 'marketingConsent': 'grant', 'sourceName': 'Yomdel', 'homePhone': '01433 345678', 'workPhone': '01433 345678', 'mobilePhone': '01433 345678', 'email': 'simonte@summat.com', 'address': {'buildingName': None, 'buildingNumber': '4', 'line1': ' Elfort Road', 'line2': '', 'line3': '', 'line4': None, 'postcode': 'N5 1AZ', 'countryId': 'GB'}}
resonse = <Response [422]>
'{"errors":[{"field":"surname","message":"The value provided exceeds the maximum length of 12 characters"}],"statusCode":422,"dateTime":"2021-01-18T11:25:47.8253296Z","description":"One or more validation failures have occurred. Please refer to Errors list for details"}'" (edited)

**Comment by plittlewood-rpt** [comment]
PR 3309 opened

**Comment by plittlewood-rpt** [comment]
Validated on dev and pushed out to production. Changelog entry created
