### ISSUE TITLE
Cannot see icons properly if scrollbar appears on navigation panel in developer portal

### ISSUE THREAD

**Issue by plittlewood-rpt** [reapit/foundations#3326]
**Describe the bug**
I have been using a different laptop to normal which has a screen resolution of 1366x768. When loading up the developer portal I get a scrollbar on the left hand navigation bar and cannot see the icons fully. Should the icons resize when this happens?

![image](https://user-images.githubusercontent.com/30798627/105182144-9ca5e480-5b24-11eb-8115-47103541e7c7.png)

**To Reproduce**
Steps to reproduce the behaviour eg:
1. Login to the developer portal and either change your screen resolution or make your browser window smaller to force a scrollbar to appear on the navigation panel. Observe the UI

**Comment by willmcvay** [comment]
It's a system setting @plittlewood-rpt somewhere in windows settings you have scrollbars set to always be visible. We did used to hide them but a customer complained that if you don't have a scroll wheel or trackpad, you have no means of scrolling. Awful but a feature not a bug 😁
