### ISSUE TITLE
Foundation Platform - Hosting as a Service Offering?

### ISSUE THREAD

**Issue by johnphipa-bnppre** [reapit/foundations#3329]
Due to our internal IT governance we are prevented from having an external web hosting platform, this prevents us from utilising the Foundations Platform.

I would like Reapit to facilitate Hosting-as-a-Service on their foundations platform.

**Comment by HollyJoyPhillips** [comment]
Hi @johnphipa-bnppre, hope all is well. We have been exploring hosting as service and wondered if this was something you would still be interested in?

**Comment by willmcvay** [comment]
Hi @johnphipa-bnppre, I am closing this issue as I am happy to report we have opened our public beta of Infra as a Service (IaaS). If this is still of interest, please drop us a line at iaasbeta@reapitfoundations.zendesk.com Thanks.
