### ISSUE TITLE
Modifiedfrom on the Companies endpoint is not returning the right results 

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#3332]
**Summary**: Selecting a date on GET Companies endpoint: modifiedFrom=2021-01-08 is not returning the correct results. Also tried modifiedFrom=2021-01-08T20%3A53%3A39Z

Please see the top 3 results: 

{
  "_embedded": [
    {
      "id": "MKT21000008",
      "created": "2021-01-08T20:53:39Z",
      "modified": "2021-01-08T20:53:39Z",
      "name": "Awesome Asif",
      "branch": "Uranus",
      "notes": null,
      "active": true,
      "vatRegistered": true,
      "typeIds": [
        "AC",
        "DV"
      ],
      "supplierTypeId": null,
      "workPhone": null,
      "mobilePhone": null,
      "email": null,
      "address": {
        "buildingName": "05",
        "buildingNumber": "06",
        "line1": "Uranus",
        "line2": "Saturn",
        "line3": "",
        "line4": "",
        "postcode": "",
        "country": "GB"
      },
      "_eTag": "\"74FC052B5C21922C44A5571A917C6B81\"",
      "_links": {
        "self": {
          "href": "/companies/MKT21000008"
        },
        "companyTypes": {
          "href": "/configuration/companyTypes/?id=AC&id=DV"
        },
        "relationships": {
          "href": "/companies/MKT21000008/relationships"
        }
      },
      "_embedded": null,
      "metadata": {}
    },
    {
      "id": "RPT21000030",
      "created": "2021-01-05T17:23:17Z",
      "modified": "2021-01-05T17:23:17Z",
      "name": "Reapit",
      "branch": "Oxford",
      "notes": "Founded in 1997, The Reapit Group is a property software provider of CRM and property management solutions specialising in the residential real estate sector",
      "active": true,
      "vatRegistered": true,
      "typeIds": [
        "SP"
      ],
      "supplierTypeId": "MG",
      "workPhone": "01234 567890",
      "mobilePhone": "07890 123456",
      "email": "example@email.com",
      "address": {
        "buildingName": "",
        "buildingNumber": "15",
        "line1": "Example street",
        "line2": "Solihull",
        "line3": "West Midlands",
        "line4": "",
        "postcode": "B91 2XX",
        "country": "GB"
      },
      "_eTag": "\"D9C7F50B2D3CC73E50EEB2E796110FF9\"",
      "_links": {
        "self": {
          "href": "/companies/RPT21000030"
        },
        "companyTypes": {
          "href": "/configuration/companyTypes/?id=SP"
        },
        "relationships": {
          "href": "/companies/RPT21000030/relationships"
        },
        "supplierType": {
          "href": "/configuration/supplierTypes/MG"
        }
      },
      "_embedded": null,
      "metadata": {
        "CustomField1": "CustomValue1",
        "CustomField2": true
      }
    },
    {
      "id": "RPT20000172",
      "created": "2020-10-19T13:41:36Z",
      "modified": "2020-10-19T13:41:36Z",
      "name": "Reapit",
      "branch": "Oxford",
      "notes": "Founded in 1997, The Reapit Group is a property software provider of CRM and property management solutions specialising in the residential real estate sector",
      "active": true,
      "vatRegistered": true,
      "typeIds": [
        "SP"
      ],
      "supplierTypeId": "MG",
      "workPhone": "01234 567890",
      "mobilePhone": "07890 123456",
      "email": "example@email.com",
      "address": {
        "buildingName": "",
        "buildingNumber": "15",
        "line1": "Example street",
        "line2": "Solihull",
        "line3": "West Midlands",
        "line4": "",
        "postcode": "B91 2XX",
        "country": "GB"
      },
      "_eTag": "\"BAAB5CC5F602FE1FE0BD7CBA04C22376\"",
      "_links": {
        "self": {
          "href": "/companies/RPT20000172"
        },
        "companyTypes": {
          "href": "/configuration/companyTypes/?id=SP"
        },
        "relationships": {
          "href": "/companies/RPT20000172/relationships"
        },
        "supplierType": {
          "href": "/configuration/supplierTypes/MG"
        }
      },
      "_embedded": null,
      "metadata": {
        "CustomField1": "CustomValue1",
        "CustomField2": true
      }
    },

**Comment by plittlewood-rpt** [comment]
PR 3323 opened to fix this

**Comment by plittlewood-rpt** [comment]
Now released to production and I've emailed the third party to advise
