### ISSUE TITLE
Register and surface a flag to be used for agency cloud customers who require SSO

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#3347]
To ensure that the user experience of logging into Agency Cloud remains as streamlined as possible when using Reapit Connect, we should add a client id into the user pool that is for those customers who want to authenticate using SSO.

This app client will be able to authenticate using all third party sources of identity, but not Reapit Connects own user pool. Conversely, the existing agency cloud id will only be able to authenticate using Reapit Connects user pool. 

- Update the authorization components to accept an additional client id for agency cloud
- Present the client id that AC should use as part of the proxy response (similar to how customer id works)
- By default, this should be the non-SSO app client id

**Comment by plittlewood-rpt** [comment]
PR 3388 opened
