### ISSUE TITLE
Ensure user management operations are blocked for users originating from third party sources

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#3349]
We provide certain user management operations for our users who are members of the Reapit Connect users such as password reset. For users who originate from third party identity providers, this is not required and should not be supported. We should instead ensure that the APIs responsible check the users tenant and reject the request with informative message if an attempt like this is made on a user whose credentials are managed externally

**Specification**
- Update user needs to be blocked
- As does password management
- Group membership endpoints
- We can determine if a user belongs to an organisation based on the SSO configuration assigned to it

**Comment by plittlewood-rpt** [comment]
PR 3480 opened
