### ISSUE TITLE
Provide ability to associate tenant to a third party users identity during token generation

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#3350]
When a user logs in using a third party identity provider, they are issued an identity token in the usual way which allows us to capture that situation programmatically using the pre-token generation routines.

Upon a external user being presented for the first time, we should attempt to look up their tenant using the information we'll store as part of https://github.com/reapit/foundations/issues/3348. Once we have their tenant, we can load our organisation information with this user and make smart decisions about their product usage (eg. populate their AC user information).

Many customers using SSO will not do this from a standing start, so this mechanism also needs to be able to pick up existing user information for users that previously used AC but used a the Reapit Connect user pool as the source of authentication. 

More information TBC

**Comment by plittlewood-rpt** [comment]
Various PRs open for this
