### ISSUE TITLE
New and existing marketplace applications should be updated to make use of customers third party authentication providers

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#3351]
App tenants in our user pool need to be associated to a source of authentication in order to be able to originate/extend sessions for users belonging to that source. 

- Ensure that on registration, new applications will accept authentication for all registered authentication sources
- Provide ability to update all existing applications when a new federated identity source is added to the user pool

More information TBC

**Comment by plittlewood-rpt** [comment]
PR 3428 opened
