### ISSUE TITLE
Provide additional fields on the GET /properties/{id} endpoint

### ISSUE THREAD

**Issue by Mike-PygottandCrone** [reapit/foundations#3355]
As an estate agent we would expect the following fields to also be returned when running a GET on a single property.

- Second virtual tour (presently only the first virtual tour field comes through; as "videoUrl")
- Agency
- Commission
- Notes (although they should never be exposed publically, it would be useful to see the notes)
- Key reference (the ID assigned when a key is logged; or simply whether or not a key is logged against the property)
- Brochure (url)

**Comment by cbryanreapit** [comment]
To be reviewed and broken into smaller tickets

**Comment by cbryanreapit** [comment]
Ticket for video tours: https://github.com/reapit/foundations/issues/3612

**Comment by cbryanreapit** [comment]
Ticket for notes: https://github.com/reapit/foundations/issues/3400 (this has already been completed)

**Comment by cbryanreapit** [comment]
Ticket for agency: https://github.com/reapit/foundations/issues/3613

**Comment by cbryanreapit** [comment]
Key management to be covered as a milestone: https://github.com/reapit/foundations/milestone/39

**Comment by cbryanreapit** [comment]
All items now broken into separate tickets (3 of them are already done). These tickets now supercede this one, so closing.
