### ISSUE TITLE
Ensure deletions are correctly handled for the operational schema for data warehouse

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#3371]
When sharing the operational raw schema to our customers, we need to confirm and ensure that the views we generate are correctly filtering out deleted records.

**Comment by plittlewood-rpt** [comment]
May not need to do anything here - awaiting confirmation on filtering of legacy views from infrastructure. Its likely that soft deleted records do actually need to be surfaced so consumers can more accurately deal with deletions

**Comment by plittlewood-rpt** [comment]
SI have confirmed that the views do not filter based on synchDel as the idea was to replicate the synchronised copy of data so the synchronisation required could be removed. A couple of views added later on do filter this information out as we were more sensible about the volume of data being surfaced. To discuss approach for legacy db schema.

**Comment by plittlewood-rpt** [comment]
This can be closed - no action required
