### ISSUE TITLE
Referrals API

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#3389]
Epic for the govenance of a system to refer an inviduals details to a third party service and track/update the referrals progress

**Comment by mbevanGoTo** [comment]
Hi All,

Currently we have clients set up (Lawrence Rand) utilising the referral panel to send us emails when they want us to action something. The app has been built but at the moment doesnt record back to the referral panel and actually takes a bit more time to refer when were trying to make it slicker.

Just putting our hands up that we would love to be able to record back to the referral panel from our app to enable clients to see what has been referred and include it in the referral report however, appreciate this could be tough as we offer 9 services but clients can pick and choose what they want to use (they may use only 1 service).

Also, what if the referral panel isnt switched on, how does that get activated?

Also, could it link from the referral panel to our app to fill in the data? or do they need to go through the app to order all the time

Mark @ GoToGroup
07467 569 33

**Comment by awogan06** [comment]
Sherry FitzGerald are also looking for this item to be included in API to be able read and record back referral to see what had been referred and include it in referral report

**Comment by mbevanGoTo** [comment]
Hi Guys, is it likely that the referral panel API will be opened up in June just because we need to schedule in a developer our end to do the work.

Thanks,

Mark
