### ISSUE TITLE
Ability to refresh an entity screen via an agencycloud endpoint

### ISSUE THREAD

**Issue by nroper** [reapit/foundations#3397]
**Is your feature request related to a problem? Please describe.**
During testing of our app the user has been frustrated that jounal entries posted from the app are not reflected in the Activity feed of the associated entity unless other actions are carried out in the desktop.
  
For example, the app adds a journal entry for a Contact, but on returning to the Contact screen from the app, the entry doesn't appear in the feed and it's necessary to go to another Contact and back again to force a refresh

If, after returning to the Contact screen from the app, a change is applied in the edit screen itself - for example to change the Marketing consent type - then the asssociated entry in the Activity appears as soon as the changes are saved - but the journal entry added by the app still doesn't appea and it's necessary to navigate away and back in ordrer to refresh the activity feed.

**Describe the solution you'd like**
The ability to force a refresh/save of an entity screen and associated Activity feed from an action in the app.

**Describe alternatives you've considered**
We tried using an agencycloud endpoint to simulate the edit screen being opened in the hope that this would perhaps force a refesh, but it didn't work.

`agencycloud://contacts/{id}`

**Additional context**

**Initail screen before launching the app**
Shows a Lifetime Legal journal entry dated 27/01/2021

![Screen Shot 2021-01-29 at 08 40 43](https://user-images.githubusercontent.com/479971/106252464-38fb7580-620e-11eb-89c5-e46237b6d2c7.png)

**App is loaded and an action carried out that adds a journal entry**
![Screen Shot 2021-01-29 at 08 41 13](https://user-images.githubusercontent.com/479971/106252508-43b60a80-620e-11eb-8e8a-f3c360e450a3.png)

**Return to Contact screen**
New journal entry is not displayed in Activity feed

![Screen Shot 2021-01-29 at 08 41 31](https://user-images.githubusercontent.com/479971/106255071-6e559280-6211-11eb-9c0c-3aff0a9e1e1b.png)

**Change Marketing Consent and Save**
New entry in activity feed for Marketing Consent change, but still no new Lifetime Legal item

![Screen Shot 2021-01-29 at 08 42 20](https://user-images.githubusercontent.com/479971/106253200-187feb00-620f-11eb-895c-1b25749c94d3.png)

**Navigate away and back**
Journal entry added by app is now displayed

![Screen Shot 2021-01-29 at 08 42 44](https://user-images.githubusercontent.com/479971/106253404-5a109600-620f-11eb-84eb-3fed178620a1.png)

**Comment by AshDeeming** [comment]
Hi @nroper , This ticket relates to AgencyCloud functionality & would therefore need to be requested via a Client's CSM & logged via our Service Desk.
