### ISSUE TITLE
Add support for the notes field in Property model

### ISSUE THREAD

**Issue by eazynow** [reapit/foundations#3400]
At present there is a "Notes" field on the property page in Reapit that is not exposed via the Property model in the API.

Please add it in to the API so we can set/get/update it.

![Screenshot 2021-01-29 at 11 55 06](https://user-images.githubusercontent.com/612686/106272392-e67b8280-6228-11eb-851a-6b2913118332.png)

**Comment by plittlewood-rpt** [comment]
PR 3430 opened
