### ISSUE TITLE
Operational data schema should be using views rather than direct snowflake share

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#3407]
We should ensure that the operational database schema is shared via secure views rather than the tables themselves.

**Comment by plittlewood-rpt** [comment]
PR 3354 opened

**Comment by plittlewood-rpt** [comment]
Agreed to abandon this idea for now as it may cause operational issues for customers already using reports against this schema type

**Comment by plittlewood-rpt** [comment]
Reopening as we need to do this to add another layer of data access control

**Comment by plittlewood-rpt** [comment]
PR 3402 opened
