### ISSUE TITLE
Include negotiator ID of the user who triggers app.install in webhook body.

### ISSUE THREAD

**Issue by dalefknight** [reapit/foundations#3422]
**Is your feature request related to a problem? Please describe.**
Our product requires details about an Organisation (Equivalent to a Reapit Customer) and at least one Person (Equivalent to a Reapit Negotiator). When a Reapit agent installs our app, we have no visibility on the negotiator that triggered the install. Due to this, we can't have a seamless onboarding into our product from an app install.

**Describe the solution you'd like**
Return the negotiator ID of the person who installed the app in the `app.install` webhook body.

**Describe alternatives you've considered**
We could ask additional questions to the user in our Reapit marketplace app, which will be asked after app install. This is not ideal as it requires us to persist a "partial signup" in our system for an unknown period of time, which is not something that we currently support and would require unwanted and extensive changes.

**Comment by cbryanreapit** [comment]
Hey @dalefknight - we don't include that since it isn't necessary for a user to have a corresponding negotiator id when making an app install. As an alternative, would the ability identity a negotiator by email address work just as well?

**Comment by cbryanreapit** [comment]
Closing due to lack of response - please let us know if you need a hand
