### ISSUE TITLE
Geo-diary - Landlord contact details to be surfaced

### ISSUE THREAD

**Issue by AshDeeming** [reapit/foundations#3423]
**Describe the bug**
Following on from #3186  - Vendor contact details are now surfaced within Geo Diary appointment details. However if a property is a Lettings property, users would expect to see Landlord contact details however none are shown. 

Sales prop: 
![image](https://user-images.githubusercontent.com/61687775/106885628-c9d4c400-66da-11eb-92c3-bbb1af44fe3f.png)

Letting prop:
![image](https://user-images.githubusercontent.com/61687775/106885686-e244de80-66da-11eb-9630-b9239dec6753.png)

**Task**

Allow Landlord contact details to be surfaced in same way as Vendors.

**Comment by willmcvay** [comment]
Have looked at this and the landlord is surfaced if they are an attendee. If we want the landlord to be fetched as a matter of course, this is a new feature and will require a permission change to the app

**Comment by HollyJoyPhillips** [comment]
Read landlord now added as a permission
