### ISSUE TITLE
Webhooks when adding/editing more record types

### ISSUE THREAD

**Issue by jon64digital** [reapit/foundations#3426]
**Is your feature request related to a problem? Please describe.**
We have a statically generated website and we need to regenerate it when any data changes which is shown on the website. So if the user is looking at a property page and it shows the branch details then we need to re-generate that page when the Reapit Office that it corresponds to is updated. Same for areas for example.

**Describe the solution you'd like**
More webhook topics. The more the better but for our current needs the following list....

- Areas
- Documents
- Offices

**Describe alternatives you've considered**
Running a script overnight which looks for newly created records and pulls them in, but that would mean a massive lag.

**Comment by cbryanreapit** [comment]
To be broken down into smaller tickets and reviewed

**Comment by cbryanreapit** [comment]
Thanks for the feedback @jon64digital. We've scheduled a milestone which includes new webhooks functionality [here](https://github.com/reapit/foundations/milestone/87). This covers of your request for documents webhooks.

Areas and offices are entities that don't frequently change so provide less utility as webhooks, so will be prioritised a little further into the future.
