### ISSUE TITLE
Enhance Property API to include extra Property fields

### ISSUE THREAD

**Issue by otrace** [reapit/foundations#3428]
**Is your feature request related to a problem? Please describe.**
Based on previous experience with the webservice there are a number of fields we need to add in to the existing webservice from the PExtra fields to populate websites etc. These fields are not included in the current version of the API but will be required by third parties building private applications.

**Describe the solution you'd like**
Within the properties API, I would like the following to be included from the PExtra Table:

pLongDescription - this contains additional marketing materials/descriptions of the property
pAltCode - this is where the code from the previous system is stored (as part of a migration). it is particularly useful to third parties who are trying to link records together as part of a migration of systems.
pMADate

**Describe alternatives you've considered**
There does not appear to be an alternative method for the above scenarios as the fields where this data resides seems to be the only logical place to add them,

**Comment by cbryanreapit** [comment]
@otrace can you provide more information on where this request originated from please?

**Comment by otrace** [comment]
@cbryanreapit sure. The request is predominantly based on experience with the current webservice that clients use to populate their websites. Obviously Foundations allows them to do a lot more beyond that with Beresfords being a good example of that. However, for a bit more context see below;

pLongDescription -
A lot of third party applications we migrate from have a number fields which can be used for Property Descriptions. We (PS) make use of pLongDescription field, when migrating the data, into RPS. Therefore, I believe it likely that the client/thrid party will want to be able to extract that data via the Foundations API (I think this field is supplied to Rightmove as part of the current RTDF)

pAltCode
As part of the migration we (PS) insert the source reference for a property. This allows a client to find and compare the record between source and Agency Cloud as well as allowing third parties to join up records at their end. It may also be used temporarily assist with URL redirects (e.g. Match Emails)

pMADate
Having looked into the pExtras table I thought this might be a useful field to include

Hope this helps

**Comment by cbryanreapit** [comment]
@otrace Appreciate feedback and I don't disagree with your points, but I believe we'd be better to respond to the requests of our customers/developer partners than speculatively add fields because the web services used them - particularly for things like 'alt code'. We risk presenting data and exerting dev effort on fields that may never get used otherwise. Closing, but let us know if you hear a request for these and we'll act accordingly.

**Comment by otrace** [comment]
@cbryanreapit for the avoidance of doubt the request for the pAltCode has come via Beresfords - as per the commentary above they need the code, stored in this field, to link records together at their end.

I agree the other two, pLongDescription and pMADate, are more speculative but that is based on experience of how frequently these fields are used when we move data across from another system.

**Comment by cbryanreapit** [comment]
Thanks for clarification @otrace - in which case, could you or the developer fire up a new issue for the specific pAltCode request? We'll assess and prioritise from there. Cheers.
