### ISSUE TITLE
Update various endpoint to handle 2 character negotiatorIds

### ISSUE THREAD

**Issue by RWilcox-Reapit** [reapit/foundations#3433]
Due to legacy data some negotiators have a 2 character identifier.
This has become an issue when attempting to associate other entities with the given negotiator as validation demands 3-4 characters (contacts in the live chat example).

Discussion to find out which endpoints need updating to support a negotiatorId of 2 characters and update the validation to allow it.

**Comment by plittlewood-rpt** [comment]
The following APIs are affected by this bug

Contacts
IdentityChecks
Offers
Properties
