### ISSUE TITLE
Provide API ability to search for negotiators by email address

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#3435]
**Background context**
Upon installation, we emit the email address of the user made the installation so that they can be the point of contact for that apps relationship. For some onboarding journeys triggered by webhook, it would be useful for them to be able to associate an email address to a negotiator in the customers data, where one exists.

**Specification**
- Add 'email' parameter to GET /negotiators endpoint
- Singular value only
- Do not support partial email address matches, complete matches only

**Comment by plittlewood-rpt** [comment]
PR 3384 opened
