### ISSUE TITLE
Provide read and write access to lettings property letting and management fee information

### ISSUE THREAD

**Issue by TomFixflo** [reapit/foundations#3465]
**Is your feature request related to a problem? Please describe.**

As Fixflo
I am interested in getting managed properties from Reapit 
Ideally, I would rely on a combination of AgentRole = ManagedLet + LettingStatus 
However, it seems that some clients do not use the AgentRole + LettingStatus reliably to indicate whether or not a property is currently under management. 

A mutual client (TLC Real Estate Services) rely on whether or not the ManagementFee <> 0 

**Describe the solution you'd like**

As Fixflo 
I would like to have visibility of the management fee for a property
I am particularly interested in understanding whether that value is > 0 

**Describe alternatives you've considered**

Continue relying on AgentRole and LettingStatus and request that the client 'tidy' their Reapit data

**Additional context**

![image](https://user-images.githubusercontent.com/75664952/107494425-af8d6100-6b86-11eb-8086-a6fbd9314c30.png)

**Specification**

- Add new `letting.managementFee` and `letting.lettingFee` sub models in all payloads

```
{
   "letting" : 
   {
      "managementFee" : 
      {
         "type" : "percentage",
         "amount" : "3.5"
      },
      "lettingFee" : 
      {
         "type" : "fixed",
         "amount" : "500"
      }
   }
}

```

- Behaviour described below applies to both fee types
- Validate `type` on two possible values: `fixed` and `percentage`
- `amount` to present a decimal field - this could be the percentage amount of commission or the fixed amount of commission, depending on what the type is
- When `type` is `fixed`, validate that `amount` is greater than -1
- When `type` is `percentage`, validate that corresponding `amount` is greater than -1 and less than 100.
- **Ensure this is not a breaking change** with controller tests - these fields not being provided should continue to work for POST and PATCH
- For updates specifically - clear out  `amount` when `type` is provided in isolation
- Where fields are updated singularly, validate the entity state in the Update method
- Consider building 'Fee' value object here

**Comment by cbryanreapit** [comment]
Implementation to be reviewed
