### ISSUE TITLE
Add support to surface archived landlord information

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#3470]
**Background context**
Our APIs do not at present read/write access to archived data. We have taken this approach since the vast majority of our partners do not require access to it and to surface that information would add complexity, noise and expense to their consumption. 
However, we do have app partners that require access to an agents archive in order to fulfill their purpose and landlord is a key entity that forms a part of this requirement.

**Specification**
- `GET /landlords/` to provide new `fromArchive` query string (boolean) to switch the endpoint to fetch data from a customers archive. This allow the endpoint to present either live or archived data, but never both in a single request
- `GET /landlords/{id}` will present the landlord that occupies that id, regardless of archive status
- `GET /landlords/` and  `GET /landlords/{id}` response to include a new `fromArchive` flag in the root level landlord model
- `GET /landlords/` and  `GET /landlords/{id}`  response to include a new `archiveDate` attribute in the root level landlord model where available
- `GET /landlords/{id}/relationships` and `GET /landlords/{id}/relationships/{relationshipId}` will present the specific role for the landlord in question, regardless of archive status of the associated contact/company
- `GET /landlords/{id}/relationships` and and `GET /landlords/{id}/relationships/{relationshipId}` response to include a new `fromArchive` flag in the root level relationship model (relating to the contact/company state)
- `PATCH /landlords` - should not allow `fromArchive` to be updated - do not include it in the model
- `PATCH /landlords` - should not allow archived landlordsto be updated - fail with appropriate error response 
- `POST /landlords/` should not allow archived landlords to be updated - fail with appropriate error response 
- `POST /landlords/{id}/relationships` should not allow archived landlords to be updated - fail with appropriate error response

**Comment by plittlewood-rpt** [comment]
This may not be required as landlords are never archived. To discuss

**Comment by plittlewood-rpt** [comment]
Agreed nothing required here as no landlord archive

**Comment by BYM-Henry** [comment]
Hi All,

Just a question if landlords cannot be archived, does this mean a contact/company who is related to a landlord cannot be archived? We were under the impression that a contact/company can only be set as archived if all the roles it's related to are an archived status. Just want to double check how this relationship works with landlords.

Many Thanks,

Henry Fitch
BriefYourMarket

**Comment by plittlewood-rpt** [comment]
Hi @BYM-Henry - Agency Cloud won't let you archive a contact that has a landlord role associated with it (even if the landlord has no properties assigned to it).

Hope that helps

Pete

**Comment by BYM-Henry** [comment]
Hi @plittlewood-rpt 

Yeah brilliant, that answers my question.

Thanks for the quick response.

Henry Fitch
BriefYourMarket
