### ISSUE TITLE
Add support to surface archived property information

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#3472]
**Background context**
Our APIs do not at present read/write access to archived data. We have taken this approach since the vast majority of our partners do not require access to it and to surface that information would add complexity, noise and expense to their consumption. 
However, we do have app partners that require access to an agents archive in order to fulfill their purpose and property is a key entity that forms a part of this requirement.

**Specification**
- `GET /properties/` to provide new `fromArchive` query string (boolean) to switch the endpoint to fetch data from a customers archive. This allow the endpoint to present either live or archived data, but never both in a single request
- `GET /properties/{id}` will present the property that occupies that id, regardless of archive status
- `GET /properties/` and  `GET /properties/{id}` response to include a new `fromArchive` flag in the root level property model
- `GET /properties/` and  `GET /properties/{id}`  response to include a new `archivedOn` attribute in the root level property model where available
- `PATCH /properties` - should not allow `fromArchive` to be updated - do not include it in the model
- `PATCH /properties` - should not allow archived property to be updated - fail with appropriate error response 
- `POST /properties/` should not allow archived properties to be updated - fail with appropriate error response

**Comment by plittlewood-rpt** [comment]
PR 3476 opened
