### ISSUE TITLE
Incorrect status code returned when trying to download a file for a document entity whose associated physical file does not exist

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#3492]
It is likely that our /documents API will encounter orphaned records where the associated physical file does not exist. Right now, we are returning a 500 from `GET /documents/{id}/download`

Specification
- Where a physical file does not exist, we should be returning a 404 status code. 
- Log appropriately as to the failure

**Comment by plittlewood-rpt** [comment]
PR 3429 opened
