### ISSUE TITLE
Add support for SABA to continue functioning for customers who use Reapit Connect

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#3494]
The legacy authentication system provided some level of integration with SABA to grant access to that resource. We no longer provide this for Reapit Connect customers

First, we need to understand
- Is there still a requirement for this functionality?
- How did this previously work?
- What is the fallout from us not adding in SABA functionality?

If this does equate to work we want to do, we'll need to review SABA to understand how we can make this fit together, bearing in mind the existing users in that platform.

**Comment by cbryanreapit** [comment]
FYI @aalim405

**Comment by aalim405** [comment]
@cbryanreapit 

**Is there still a requirement for this functionality?**
Yes, this is still a requirement. 

**How did this previously work?** 
Previously, users added to sums were added automatically to Saba within 24 hours

_MyJet_

- Users created via myjet automatically get an IQ account created using the following logic: JET underscore company code dash neg code EG: JET_CLM-ANT 

- Currently if I log into myjet I can go directly into Reapit IQ without a Saba log in - this may not be required going forward - we will simply change/remove the MyJet link for ReapitIQ to from auto-login to manual login similar to how our enterprise clients login.  

**What is the fallout from us not adding in SABA functionality?**

Manual effort to add all users to SABA will be required (for new client onboarding) i.e mass uploading - Only one person (Massi) can do this. 
Any new starters for existing clients will require a manual 
- if the user does not get added automatically either a Support Ticket is raised or the client fills out a form here: https://www.reapit.com/reapit-iq-signup/ which then requires someone from the training dept to manually add the user. - again only Massi can do this.
