### ISSUE TITLE
Include pAltCode data in the API

### ISSUE THREAD

**Issue by otrace** [reapit/foundations#3496]
**Is your feature request related to a problem? Please describe.**

- Beresfords have a third party, Cognio Digital, who provide Beresfords with a number of Digital Products (such as Landlord Portals etc.). 
- Cognio will be migrating these digital products across to Reapit (from Beresfords current CRM), and will use the Foundations API to retrieve the relevant data they need
- In order to allow for the migration of Cognio's products, they need to be able to link the records, from Reapit, back to the records from the current source system. The only way of doing this is by mapping the Reapit Property Code back to the Source System ID/Code
- As part of the Reapit Data Conversion, we use the field **pAltCode** (stored in pEXTRAS) to house that Source System ID/Code
- However, pAltCode is not currently exposed via the Foundations API. Therefore, Cognio are currently unable to merge records between Agency Cloud and the source system

**Describe the solution you'd like**

- pAltCode to be included in the Foundations API so that it can be retrieved when calling property data

**Describe alternatives you've considered**

- Having reviewed the fields that are available via the API, I don't believe there is an alternate/sensible place to store the source system ID

**Additional context**

**Comment by cbryanreapit** [comment]
Thanks @otrace

**Comment by cbryanreapit** [comment]
We will add an 'alternateId' attribute to the properties model for read/write operations
