### ISSUE TITLE
Posting files larger than 10MB results in failure 

### ISSUE THREAD

**Issue by SteveRad** [reapit/foundations#3504]
**Is your feature request related to a problem? Please describe.**
Our Reapit  Foundations app (InventoryBase) posts inventory/inspection reports to the Letters section of a Tenancy. In the event that document is over 10MB ([or is it 6MB?](#3495)), it fails, and we receive back the following error: 

```
Client error: `POST https://platform.reapit.cloud/documents` resulted in a `413 Request Entity Too Large` response:

{"message":"The request could not be completed"}
```

**Describe the solution you'd like**
Increasing the limitation to 20MB would reduce more than 90% of failures, if this is possible, 50MB wouldn't have any failures, if it isn't ... 

**Describe alternatives you've considered**
We circumvented lamda's limits via Direct-to-CDN uploads, without something like this I'd suggest we have the ability to post logical documents as well as physical, where by we can add a link to a PDF and store that in letters as a link? 

**Additional context**
Customer provided 3 areas they felt a 'Link' could be placed... 

> Ideally we’d want it to go into the associated Tenancy Letters page (screenshot below), but failing that, the property Letters section (screenshot 2). If you’re not able to add it as a document with a link, then a “note” within the property record would be fine and is screenshot 3.

Cannot post the screenshots as they contain tenant info.

**Comment by cbryanreapit** [comment]
Thanks for the report - we already have this issue flagged. I've linked your report to the one at https://github.com/reapit/foundations/issues/3495 - please track this issue.
