### ISSUE TITLE
Investigate issue where id query string parameter was not being respected in properties API

### ISSUE THREAD

**Issue by plittlewood-rpt** [reapit/foundations#3514]
In #3471 a situation arose whereby the id query string parameter was being completely ignored in `GET /properties` and no matter what parameters were passed, the same results were returned from the service. Restarting the service resolved the problem so it seems like some kind of memory related issue.

**Comment by plittlewood-rpt** [comment]
This has come up again this week with the propertyImages service (see ticket #4210 )

**Comment by RWilcox-Reapit** [comment]
After further investigation on this ticket I believe it's an intermittent caching issue with LINQ to SQL as there are many sources to support this theory on SO. 
I'm not able to replicate this locally at all so no fix has gone out. Ticket is to be used a reference should a customer experience this again
