### ISSUE TITLE
Provide 'Contact Preferences' in the Contacts API

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#3518]
**Summary**: Agency Cloud supports contact preferences for 'Contacts'. Currently this information is not available in the Contacts endpoint. We should allow this information to be read and written back into the API so that our developer partners can make of use it. 

**Requirement**: Surface the contact preferences for a contact in the Contacts endpoint for GET, POST and PATCH.

**Technical notes**: 
- It's a configuration option set at 'Contact/Companies' in AC 'Turn on communication preferences functionality' 
- Held in semi structured fields as follows, all values defaulting to true.
    - cntCommPrefLetter
    -   cntCommPrefEmal
    -   cntCommPrefPhone
    -   cntCommPrefSMS 
- We need to finalise the contract before proceeding work 
![image](https://user-images.githubusercontent.com/52408607/108090878-07d6ce00-7073-11eb-974b-9ef1be1489a6.png)

**Comment by cbryanreapit** [comment]
@PaulHaynes is this likely to become a feature that all agents have turned on in time?

**Comment by PaulHaynes** [comment]
@cbryanreapit - as it's on a config option then yes I would expect more agents will turn it on in time.

**Comment by cbryanreapit** [comment]
@HollyJoyPhillips do you happen to know if this can be read only or is write back also required?

**Comment by HollyJoyPhillips** [comment]
It would be write back also as the preferences are controlled via the portal. The example given was the contact could control mailing list subscription by opting out when logged in to the portal
