### ISSUE TITLE
Automation of assigning a property to a building

### ISSUE THREAD

**Issue by jedarlington** [reapit/foundations#3535]
Here is the live chat I had with reapit:

I cant see into the clients reapit accounts but they want me to auto assign properties to buildings in my application, however, I cant find a way of knowing what building_number relates to what building

Sure fire away

is there a way?

Our properties endpoint should give you the information you need within the address object or am I misunderstanding?

Yeah the properties object has a building number, but how does that relate to a building? A building is not an entity within reapit and my application has buildings - so I think that what im asking is impossible - but without access to my clients reapit account I cant even see how properties are assigned to buildings or what they are assigned too.

I have tried to explain this to the client but its a vital part of this application
as far as i can see a building number is just an integer with no relation to an entity in reapit

I am integrating your API and an essential part of our application is that we auto assign properties to buildings by matching the building number: I have no access to the clients reapit account so cannot see/do not know how a building number is generated or how properties relate to buildings in reapit. My understanding is that a building is not an entity otherwise id be able to call them via the api.

I can manually form a relationship between the two but the building number integer on a property response means nothing as it does not relate to a building in any way as buildings are not entities.

Thanks, Jim.

**Comment by cbryanreapit** [comment]
@jedarlington as you correctly assumed , we do not have the concept of a standalone 'building' entity inside of our platform or products. Therefore what you are asking for is just a fundamental mismatch between the way your system and our platform handles buildings. Recommend that you explore our swagger documentation to understand the functionality that we do offer. We also provide metadata support to allow you to store additional and custom entities inside of the platform which may help you here too - please see our API documentation for more information.
