### ISSUE TITLE
Ensure that data warehouse provisioning service works with office groups

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#3542]
**Background context**
We should update the data warehouse provisioning service to ensure it works as expected when an organisation has office groups in place. 

**Specification**
- Data boundaries should be put into the views that the service generates
- Ensure that office group is accounted for when creating new accounts for naming/provision - do not clash with another office group.

**Comment by HollyJoyPhillips** [comment]
DWH should be org level only.
