### ISSUE TITLE
Update example payload for application webhook event for ping demonstration functionality

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#3552]
**Background context**
Our 'ping' functionality allows developers to view an example payload for our webhooks service. This payload seems out of date for the application.install event (and possibly application.uninstall too)

**Specification**
* Ensure that the payload example is an accurate reflection of the notification that gets emitted
* Also check uninstall event.

**Comment by plittlewood-rpt** [comment]
PR 3463 opened to resolve issue with the two example payloads. They have been updated already on dev/production environments
