### ISSUE TITLE
Provide API ability to attach a landlord to a lettings property

### ISSUE THREAD

**Issue by raymond2323** [reapit/foundations#3553]
**Overview**
Presently, it is possible to retrieve the landlord id associated to a lettings property, but it isn't possible to set this value, either via the `POST /properties` or `PATCH /properties/{id}` endpoints. 

**Specification**
- Allow `landlordId` to provided in both PUT and PATCH payloads
- Validate that the `landlordId` is in the correct id format
- For POST: validate that a `landlordId` cannot be provided where the property has `marketingMode` of "selling"

**Comment by cbryanreapit** [comment]
@raymond2323 thanks for the report - we'll review and update the ticket from here.

**Comment by raymond2323** [comment]
is this now live, as I don't see this currently in the docs.

**Comment by cbryanreapit** [comment]
@raymond2323 yes - `lettings.landlordId` is available in `POST` and `PATCH`, as per `GET`. You should see it in the swagger docs (model section). Let us know if not.
