### ISSUE TITLE
Marketing mode filter on properties endpoint behaves inconsistently when more than one option provided

### ISSUE THREAD

**Issue by patryk-k** [reapit/foundations#3564]
**Describe the bug**
When fetching properties that are either `letting` or `sellingAndLetting`, the results returned aren't consistent with expectation

**To Reproduce**
Steps to reproduce the behaviour:
1. Use 'RES' demonstration data 
2. Issue request `GET /properties?pageNumber=1&pageSize=100&marketingMode=letting`]
3. Note that RPT210004 is included and is `letting`
4. Issue request `GET /properties?pageNumber=1&pageSize=100&marketingMode=sellingAndLetting&marketingMode=letting`
3.  Note that RPT210004 is NOT included

**Expected behaviour**
RPT210004 should be included in both requests.

**Attachments**
The zip folder contains two JSON files with request and response data.
[Archive.zip](https://github.com/reapit/foundations/files/6035626/Archive.zip)

**Comment by cbryanreapit** [comment]
Hi @patryk-k - the response you pasted for `GET /properties` fetches over 100 properties (am assuming this is using our sandbox data but correct me if it isn't). This is a paged response, could it be that RPT210004 is on a subsequent page? 

You'll see that if you add the query string `id=RPT210004` to the GET /properties request, it will get returned, so this does not look like an issue in returning that specific property from the endpoint. Let us know - thanks.

**Comment by patryk-k** [comment]
Thanks for the reply, I added the pageSize=100 to eliminate any possibility of it being on another page or anything of the sort, there are 8 props returned there so there are no more pages. 

At the point of that happening in the code of my integration the ids aren't known yet so I can't check that. 

However, I don't see how that relates to the reported issue, if you run that get request when that prop is set to be arrangingTenancyUnavailable it will not be returned, if you change it to arrangingTenancyAvailable that same call will return it, and I'm not filtering statuses. 

I don't think it is a problem with that particular prop was meant to be just an example, my guess is that unavailable props are not returned unless specifically queried.

**Comment by cbryanreapit** [comment]
@patryk-k  Understood - thanks for response. Just for the avoidance of doubt, this is sandbox data, right? 

I ask because your example payload is very different the response I get for sandbox for the query that you ran (far more than 8 properties). If you can confirm the environment and perhaps confirm the query you're running here on the ticket, at least we'll be on the same page :) 

Also just to confirm that your assertion is correct: property status should not impact the visibility of a property (unless specifically filtered) - so we'll dig into that when you confirm above details. Thanks.

**Comment by patryk-k** [comment]
Ok, thanks.

No, it's the data under the 'RES' customer id, I'm running a `GET` request to `properties?pageNumber=1&pageSize=100&marketingMode=letting&marketingMode=sellingAndLetting`.

Cheers

**Comment by cbryanreapit** [comment]
Thanks @patryk-k - I can reproduce the issue. Will update ticket as appropriate and get this attended to.
