### ISSUE TITLE
Enhance performance of function that serves OpenAPI specification

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#3571]
We should look to enhance the performance of the function that serves our OpenAPI specification. Right now, it merges documents from disparate serves on demand but we should look to enhance this process as it's become quite slow as our service offering as grown.

- Research the best way to improve performance of this function (caching? static file?)
- Present ideas to the team to discuss
- Caching probably preferable as keeping the merged document up to speed less straightforward

**Comment by cbryanreapit** [comment]
Caching to be preferred option to explore first - 30 mins cache invalidation time

**Comment by plittlewood-rpt** [comment]
Comments circulated to team for discussion on stand up

**Comment by plittlewood-rpt** [comment]
PR 3482 opened
