### ISSUE TITLE
Provide a denominator for currency in the payments API

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#3575]
**Summary**: Currently the 'amount' field on the payments API has no denomination of currency specified. Some customers will request payments in other currency via the payments app as AC supports this. 

**See example:** "amount": 50.0,

**Enhancement**: Provide currency type on the payments API

**Specification**
- Project: Reapit.Services.Payments
- Add `currency` property to `PaymentModel` that surfaces the currency associated with each entity.
- Confirm that the currency on a payment item is always in the system base currency with the AC dev team (this looks to be the case but we should double check)

**Comment by plittlewood-rpt** [comment]
Not a product requirement at this time
