### ISSUE TITLE
Retire unused platform codebases from Azure DevOps

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#3577]
The following codebases are no longer used and can likely be retired:

- [x] - Reapit.Packages.AWS.CognitoClient
- [x] - Reapit.Packages.MarketplaceClient (double check)
- [x] - App Store (confirm with Will)
- [x] - API Template
- [x] - ServerlessTestProj
- [x] - Reapit.Packages.BrokerLogging

**Comment by plittlewood-rpt** [comment]
Projects backed up on local network
