### ISSUE TITLE
Automate the email notification that occurs when meaningful app changes occur

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#3579]
**Summary**: When an app is listed and installed, an agent agrees to a certain set of permissions. If those permissions are modified, it is a manual process for the Foundations team to let the agents know.

**Possible solution:** Look to send an email to all agents that have installed the app to make them aware of a modification to the original permissions set they had agreed to. This should happen when the listed app's new revision has been approved. 

**Email subject:** APP NAME – Requested Permissions  

Dear 'AGENT', 

This email is to notify you that the app ‘APP NAME’, which you have installed via the Reapit Marketplace, has requested or modified permissions to your data.  

Requested/Modified Permissions: Read Properties

To review the permissions or to uninstall this app, please click here. (LINK TO EXTERNAL MARKETPLACE/APPID) 

As this app is currently installed through the Reapit Marketplace, you do not need to do anything if you are happy with the additional request.

Kind regards 
Reapit Ltd

**Specification** 
- We already capture the email address of the individual that installed the app
- At the point that a meaningful revision is approved,, generate email with above content to ALL customers who installed the app
- Can we make a single email work or can we BCC customers in and have it feel like an acceptable experience? @HollyJoyPhillips to confirm

**Comment by RWilcox-Reapit** [comment]
After discussion with Holly we are removing the 'Dear 'AGENT'' entirely.
We are also only sending updates out when new scopes are requested.
