### ISSUE TITLE
Investigate 'No space left on device' issue with for some containerised services

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#3586]
We have seen a couple of instances where high traffic services (webhooks and marketplace) have reported issues because the ECS docker container running out of local storage space. The error reported in cloudwatch is `No space left on device`

The only thing that could realistically be causing this is some sort of local logging to file. The docker containers are setup with a 10Gb local file store and this cannot be increased, according to the ECS documentation. The way to increase it is to attach additional EBS volumes or similar. 

We need to identify the underlying cause here and preferably just stop it filling up. This problem goes away when we move to serverless, though these two services don't fit the serverless bill without some fundamental changes.

In the meantime it might be worth setting up some cloudwatch events to periodically restart these services, as the problem only seems to crop up when the container has been running for a long period of time, which was the case in both instances with marketplace/webhooks

**Comment by plittlewood-rpt** [comment]
This has come up again this morning with the negotiators service. We need to prioritise this ticket

**Comment by plittlewood-rpt** [comment]
This has come up again today (see ticket above). I may know what's causing it and it will be resolved by an update to the logging package so I'll try and prioritise it. Busy services (like this one) are likely to hit this problem.

**Comment by cbryanreapit** [comment]
@plittlewood-rpt I'm going to close this until we see it again, based on working theory that we will solve based on logging alterations
