### ISSUE TITLE
Add email address to application install/uninstall notifications webhooks

### ISSUE THREAD

**Issue by plittlewood-rpt** [reapit/foundations#3588]
Currently when an app is installed/uninstalled from the marketplace, any consumers listening to application setup webhook events receive a payload containing information about the customer installing the app, but it does not contain any contact details. We should enhance the payload to include the email address of the user installing or uninstalling the app as this can then be used by third parties as a means of contact.

**Specification**
- Update the existing application.install webhook event payload emitted by the marketplace to include a new `customerEmail` property. This should be populated with the email address of the user who installed the app. Property name to stay consistent with existing properties
- Update the existing application.uninstall webhook event payload emitted by the marketplace to include a new `customerEmail` property. This should be populated with the email address of the user who uninstalled the app. Property name to stay consistent with existing properties
- Update example payloads sent via the developer portal
- Update example provided in any Foundations documentation.

**Comment by cbryanreapit** [comment]
@plittlewood-rpt could you add a specification to this issue please? Thanks!

**Comment by plittlewood-rpt** [comment]
PR 3496 opened. Example payloads/documentation will be updated once PR is approved

**Comment by gpn273** [comment]
@plittlewood-rpt Would you be able to confirm that the `customerEmail` will always populated inside of the payload or can it be `null` or an empty string?

**Comment by plittlewood-rpt** [comment]
@gpn273 This field will always be populated and is based on the user that is logged in and performing the install/uninstall action

**Comment by plittlewood-rpt** [comment]
PR 3501 opened to update example payloads

**Comment by plittlewood-rpt** [comment]
Changelog updated
