### ISSUE TITLE
Passing an invalid etag format causes a 500 error

### ISSUE THREAD

**Issue by plittlewood-rpt** [reapit/foundations#3608]
**Describe the bug**
Raised off the back of a report from a developer. If an eTag in an invalid format is issued as part of a PATCH request, a 500 error will be thrown. This error should be more helpful

**To Reproduce**
Steps to reproduce the behaviour eg:
1. Issue a patch against an entity (report was for `PATCH /appointments/{id}`) with the If-Match header set as follows:

```
'If-Match: /"7510CB31179EC09BA0FCB64D4E051358/"'
```

2. Observe the error. Note that the request doesn't get as far as the backend service and fails at the layer above.

PR 2809 (Landlords Broker) can be used as a reference

**Comment by cbryanreapit** [comment]
Linked to https://github.com/reapit/foundations/issues/2784

**Comment by plittlewood-rpt** [comment]
Various PRs opened
