### ISSUE TITLE
Images for Sales/App Review team build are not saving correctly

### ISSUE THREAD

**Issue by plittlewood-rpt** [reapit/foundations#3614]
The RES sales build is not saving images correctly through the API. When images are added via `POST /propertyImages` they are not visible in Agency Cloud yet the API returns a 201

@HollyJoyPhillips  FYI

**Comment by plittlewood-rpt** [comment]
Liaising with desktop team and infrastructure team as we just need to switch this build over to use S3. The problem mentioned in the description only affects this build and not customer databases

**Comment by cbryanreapit** [comment]
Not a platform issue - handed over as appropriate
