### ISSUE TITLE
Performance modifications for marketplace application activity

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#3625]
**Background context**
We've identified a means to improve performance for marketplace `GET /apps/{id}`. 

**Specification**
- Soft delete old revisions
- Write script to tidy up old revisions

**Comment by plittlewood-rpt** [comment]
Script has been run on production to clean up old revisions. PR for self cleaning to follow

**Comment by plittlewood-rpt** [comment]
PR 3495 opened
