### ISSUE TITLE
Update the traffic events handler to ignore requests from our internal services

### ISSUE THREAD

**Issue by RWilcox-Reapit** [reapit/foundations#3634]
Update the message handler to ignore messages received from our internal services such as the BulkIndexer. 

These message are not billed for so there is no reason to process and store these. 

This information can be obtained from the traffic events 'applicationId'.

** Specification **
- Add parameter store for CSV list of services to be excluded from traffic events handler
- Update billing service to account for that
- When a request is encountered with the applicationId inside of the white, just delete the message

**Comment by plittlewood-rpt** [comment]
PR 3570 opened
