### ISSUE TITLE
Add webhook topic in Transaction History spreadsheet

### ISSUE THREAD

**Issue by RachelLightfoot** [reapit/foundations#3643]
**Is your feature request related to a problem? Please describe.**
When a transaction history report is downloaded it gives detailed information about the specific API end points that have been called.  However for webhooks there is no detail provided for the topic of the webhook that has been called.  

**Describe the solution you'd like**
As we are being charged for each webhook call made it would be extremely useful to see which topic is being called for each one to help with decision making so that we can see where the majority of webhook calls are being made.  If an extra column of data for the webhook topic could be added to the spreadsheet that would be very useful.

**Comment by HollyJoyPhillips** [comment]
Agreed we would evaluate the data for a period of time and review if this is still required.

**Comment by RachelLightfoot** [comment]
We've been trying to analyse the billing data and we are still seeing an unusually high number of webhooks being called.  However as we're unable to drill into the detail of those webhook calls to see what 'event type' they are, it's difficult to identify the cause of the high numbers.  Are you able to consider adding the 'event type' to the transaction history download?

**Comment by HollyJoyPhillips** [comment]
Closing ticket as webhook specific transaction logs is addressed in a sperate ticket (https://github.com/reapit/foundations/issues/3797). @RachelLightfoot FYI I've emailed you direct to confirm specifics. UI ticket TBC.
