### ISSUE TITLE
Provide ability to locate contacts by mobile telephone number

### ISSUE THREAD

**Issue by thomasbing4589** [reapit/foundations#3656]
**Is your feature request related to a problem? Please describe.**
Trying to query the Contacts API and filter by mobile number. I need to get the Reapit Contact ID of a user based on the mobile number of the contact. There exists no other unique identifier other than ID (which is what I'm trying to get).

**Describe the solution you'd like**
Being able to filter a Contacts API query by mobile number.

**Describe alternatives you've considered**
Querying all contacts and looping through to find the contact with the mobile number.

**Specification**
- Add new 'phone' query string to `GET /contacts`
- Should match implementation of email address filter
- We should normalize the number at our end before we use it as a search term (we have method already)

**Comment by cbryanreapit** [comment]
@thomasbing4589 have you considered using email address? This is generally a better means of identifying a unique contact than email address and it's already available in the API.

**Comment by thomasbing4589** [comment]
@cbryanreapit Thanks for the quick reply. Using email address is a good alternative but our platform integrating with reapit relies on a mobile number - the users on our platform are required to have a mobile number but not required to have an email. I think we could get away with using just email if we could query for an applicant with an email address. I see on the swagger docs that querying for an applicant by email isn't possible. Thanks for the help so far.

**Comment by cbryanreapit** [comment]
@thomasbing4589 we have an open ticket to deliver searching by applicant email: https://github.com/reapit/foundations/issues/3515 - this is scheduled to be delivered next week.

I think your request is valid and we will prioritise accordingly, but wanted to flag this as a potential workaround for you

**Comment by thomasbing4589** [comment]
That's awesome. I'll definitely be following the progress of that ticket. Thanks a ton

**Comment by cbryanreapit** [comment]
Re-opening as we plan to deliver this

**Comment by cbryanreapit** [comment]
From another development: "please could you add the ability to search by phone number. It makes sense to add just one phone query parameter that searches all the phone number fields (homePhone, workPhone, mobilePhone)"

**Comment by sgregory6767** [comment]
Hi, is there any news on when this might be delivered ?

I don't think getting all contacts (in pages, so multiple calls) then attempting to locate the contact with the correct number is going to be feasible for us.

**Comment by plittlewood-rpt** [comment]
This is now available using the `contactDetail` query string parameter on the `GET /contacts` endpoint. Please refer to the Swagger documentation for more details.
