### ISSUE TITLE
Confusion over getting properties using "modifiedFrom" filter

### ISSUE THREAD

**Issue by jon64digital** [reapit/foundations#3658]
**Describe the bug**
I am trying to return all properties modified after a certain date. After trying a few different dates the results i am getting are inconsistent.

**To Reproduce**

Request properties from the /properties endpoint using Beresfords' staging data. Set the pageCount to "5", sortBy to "modified" and the "modifiedFrom" to "2021-01-01T00:00:00z"

When I do this I get 5 properties with the following ID/created date/modified date

ID: BIS100482 :: Created: 2010-09-21 :: Modified: 2021-01-12T12:28:20Z
ID: BIS080003 :: Created: 2008-05-08 :: Modified: 2021-01-12T12:28:21Z
ID: BIS140145 :: Created: 2014-10-23 :: Modified: 2021-01-12T12:28:21Z
ID: BIS070066 :: Created: 2007-09-07 :: Modified: 2021-01-12T12:28:22Z
ID: BIS080098 :: Created: 2008-01-30 :: Modified: 2021-01-12T12:28:22Z

So, when requesting all properties modified after 1st Jan this year I get 5 properties, all modified on the 12th Jan and all created before last year.

Run this again but with a modifiedFrom of "2020-11-01T00:00:00z", so 1st November last year. I get the following results...

ID: BES200579 :: Created: 2020-11-02 :: Modified: 2021-01-10T20:29:59Z
ID: GPS200570 :: Created: 2020-11-02 :: Modified: 2021-01-10T20:29:40Z
ID: LNH200005 :: Created: 2020-11-02 :: Modified: 2021-01-10T20:29:32Z
ID: LNH200006 :: Created: 2020-11-02 :: Modified: 2021-01-10T20:29:39Z
ID: LNH200007 :: Created: 2020-11-02 :: Modified: 2021-01-10T20:29:32Z

This is confusing because (a) if it was returning all results modified after the requested date then why wouldn't the results from the second batch be showing in the first batch as they were modified after the 1st Jan and should appear before the results I got which we're modified until 2 days later, and (B) If it's returning all results created after my requested date then why would my first batch of results have results which were created before my requested date?

Possibilities I've considered....

1) That my dates are in the wrong format, but I checked they are ISO8601 date compliant.

2) That the results are being returned if they were modified OR created after the requested date, but again the properties modified on 10th Jan should have shown up in my request.

3) That when the results were created or modified after the requessted date they are returned but not in the order I asked for them, which I can't easily check.

I'm sure there's a logical explanation for this and I apologise if I'm wasting your time but I've wracked my brain for over an hour on this one.

Jon

**Comment by cbryanreapit** [comment]
Thanks for the report @jon64digital - we'll take a look and progress the ticket.
