### ISSUE TITLE
Fee information 

### ISSUE THREAD

**Issue by jpmorganuk** [reapit/foundations#3660]
Please can you expose the Marketing Price Suggested and Fee Quoted in the MA via the API?

**Comment by cbryanreapit** [comment]
We have written a ticket to encompass the work to expose selling property c omission information here: https://github.com/reapit/foundations/issues/3766

We'll provide another ticket for the other requirement

**Comment by cbryanreapit** [comment]
https://github.com/reapit/foundations/issues/3768 for recommended asking price functionality. This ticker has been superceded by the others - closing.
