### ISSUE TITLE
Inconsistent error response under certain payload conditions

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#3678]
If a badly formatted JSON payload is provided to some of our services, it is possible to generate an error response that does not conform with our standards.

Contacts POST: 
```
{
  "errors": {
    "": [
      "<error>"
    ]
  },
  "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
  "title": "One or more validation errors occurred.",
  "status": 400,
  "traceId": "|ad5a2c0b-4fc18b4d093665d0."
}
```
 
See PR 2912 for background information (metadataproxy)

**Specification**
- Project: Reapit.Lambdas.MultiBroker
- Ensure this is handled in multi broker project correctly. Other services will automatically get this update when we choke the individual brokers out

**Comment by HollyJoyPhillips** [comment]
PL, RW & HP: Reviewed

**Comment by HollyJoyPhillips** [comment]
PL, RW & HP: Agreed to review again in conjunction with the migration to serverless.
