### ISSUE TITLE
Update the data warehouse usage cap to kick at scaling percentages

### ISSUE THREAD

**Issue by RWilcox-Reapit** [reapit/foundations#3686]
Update the percentage at which the resource monitor kicks in based on the usage cap requested. 
This is to prevent users being overcharged by exceeding the caps which they have set.

Problem:
The higher the requested cap the more leeway we have on assigning the user close to 100%.
For the lower requested caps (example 2 hours), giving a user 99% means we have 72seconds to shutdown the warehouse which is not always possible.

Solution:
Update the usage monitor to allow a scaling percentage cap before locking down the warehouse.
95-99% increasing as the number of hours allowed do.

**Comment by cbryanreapit** [comment]
No longer required
