### ISSUE TITLE
Perform marketplace routines for specific customer

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#3708]
**Background context**
We should perform prep routines for customer: CNS. Speak to PN before kicking it off.

**Comment by plittlewood-rpt** [comment]
Got some figures and sent volume info over to SI team for approval

**Comment by plittlewood-rpt** [comment]
Job approved for this morning - running now

**Comment by plittlewood-rpt** [comment]
Completed and automation enabled
