### ISSUE TITLE
Deep dive on tenancy renewals and extensions functionality

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#3709]
**Background context**
Perform deep dive on this tenancy renewals and extensions functionality in AgencyCloud with a view to extending the functionality available in the Platform tenancies API

Outcome of this ticket is a thorough understanding of the different data states, particular where client accounts data is concerned. Lean on other departments as necessary

**Comment by cbryanreapit** [comment]
https://github.com/reapit/foundations/issues/5219 came from a developer.

**Comment by plittlewood-rpt** [comment]
Liaising with desktop team to arrange a time to do this deep dive

**Comment by plittlewood-rpt** [comment]
PBI-3830 logged as initial link with desktop team
