### ISSUE TITLE
Complete surface area data source testing 

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#3725]
**Background context**
On completion of https://github.com/reapit/foundations/issues/3688, we should run through our postman test suite using the two datasets we have targeted for testing for AWS and RAX

**Specification**
- Run test suite for each dataset
- Note results and share with team
- Write tickets for investigation of any anomalies 
- Those new tickets should be where effort is estimated/attributed on a case by case

**Comment by plittlewood-rpt** [comment]
Have run test suite against both Rackspace and AWS hosted customer with large dataset. Results have been circulated.
