### ISSUE TITLE
Different property currency being given between desktop and api

### ISSUE THREAD

**Issue by Nialld** [reapit/foundations#3735]
We have a customer whose properties are listed in EUR... an example is RED210146 

the property in the RPS desktop system is listed as EUR 
the API is returning GBP as the currency

i can provide screenshots privately if required

**Specification**
- Investigate example provided
- Update service(s) (TBC) to ensure that the currency reflected in the customers identity package is surfaced in the API where no currency has been set in the data itself
- Review other services that may have the same problem and write up new tickets where appropriate

**Comment by cbryanreapit** [comment]
@Nialld could you let us know which customer your example relates to please?

**Comment by Nialld** [comment]
Company Id is EDD, does that help?
