### ISSUE TITLE
Open house support

### ISSUE THREAD

**Issue by Nialld** [reapit/foundations#3743]
please provide API support for open house, i appreciate it might not be an immediate concern but integration clients are refusing to move forward without support for this.

For reference this has been requested by an agent will 100+ branches

**Comment by awogan06** [comment]
Sherry FitzGerald  also require this in the API  for advertising viewing time  & dates on their website

**Comment by plittlewood-rpt** [comment]
This feature was added last week as part of the following tickets:

#5581 
#5568 
#5582 
#5569

**Comment by HollyJoyPhillips** [comment]
Closing this ticket as developement work was covered in the issues listed in the above comment
