### ISSUE TITLE
Refresh token rejected

### ISSUE THREAD

**Issue by RachelLightfoot** [reapit/foundations#3747]
**Describe the bug**
A customer has reported that the connection with Reapit is not working.  When the customer last connected to Reapit (Approximately 2021-02-12 12:01:30) we were given a refresh token which has been successfully used many times to get a new access token, with the final successful refresh occurring at 2021-03-13 14:09:25. At 2021-03-15 09:29:28, the system attempted to use said refresh token once more and the call to https://connect.reapit.cloud/token was rejected with a status code of 400 and a response of “{"error":"invalid_grant"}”. Every subsequent request to use the refresh has failed in the same manner.

One thing that may be of interest is that when the refresh token has been used, we’ve received a new access token but not a new refresh token. E.g. the response is in the form:

{"id_token":"{{ID TOKEN}}","access_token":"{{ACCESS TOKEN}}","expires_in":3600,"token_type":"Bearer"}

Where as we would (at least some of the time) expect it to be as follows:

{"id_token":"{{ID TOKEN}}","access_token":"{{ACCESS TOKEN}}","refresh_token":"{{REFRESH TOKEN}}","expires_in":3600,"token_type":"Bearer"}

We can provide the refresh token (in JWT format) upon request but this is a private field which we don’t wish to publish in a public forum.

If you could please respond ASAP that would be much appreciated.

**Comment by willmcvay** [comment]
@RachelLightfoot The refresh tokens have a 1 month expiry so the behaviour sounds to be correct and working as expected. Your user will need to log in again and you will receive a new refresh token.

**Comment by RachelLightfoot** [comment]
I've just checked the API documentation and can see the following re refresh tokens.  There is no mention of a one month expiry:

"Refresh tokens provide your application with a means of retrieving a new set of tokens without requiring an interaction from the user. They are long lived and will continue to function until they are revoked."

It's not a great customer experience if you have to ask your customers to set up a new token each month. Especially as these will often be the managers/business owners who don't use the system day-to-day and will expect these things to just be in place and working.

**Comment by willmcvay** [comment]
@RachelLightfoot We expect your users to log in using their username and password and for the refreshing of sessions to be handled programatically by your software. To be honest, your statement;

```
It's not a great customer experience if you have to ask your customers to set up a new token each month. Especially as these will often be the managers/business owners who don't use the system day-to-day and will expect these things to just be in place and working.
```
Sounds very worrying from a security perspective. This is certainly not our intention for authentication to be managed and if you are doing this, I would look very closely at your development procedures.

I will review internally but I suspect this may be a breach of our terms of service.
