### ISSUE TITLE
Provide API to surface a paged list of transactions

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#3751]
## Overview
This endpoint will be responsible for presenting details of transactions in a page listing.

### Location
`GET /transactions/` (protected: **yes**)

### Parameters

`id` - string[] - from query
`type` - string[] - from query
`status` - string[] - from query 
`created` - datetime - from query
`ledger` - string[] - from query
`category` - string[] - from query
`propertyId` - string[] - from query
`landlordId` - string[] - from query
`tenantId` - string[] - from query

### Success
**200 OK**
```
{
  "data": [
{
  "id": "PAY20000001",
  "created": "2018-12-12T12:30:23.0000000Z",
  "modified": "2019-01-08T12:30:34.0000000Z",
  "category": "categoryType",
  "type": "paymentRequest",
  "description": "Tenancy Check Fee",
  "status": "awaitingPosting",
  "ledger": "tenant",
  "netAmount": 100,
  "taxAmount": 20,
  "grossAmount": 120,
  "outstanding": 0,
  "companyId": null,
  "landlordId": null,
  "propertyId": "PRP200001",
  "tenancyId": null,
  "_eTag": null,
  "_links": {
    "self": {
      "href": "/transactions/PAY20000001"
    },
    "customer": {
      "href": "/contacts/OXF12300101"
    },
    "property": {
      "href": "/properties/PRP200001"
    }
  }
}
  ],
  "pageNumber": 1,
  "pageSize": 1,
  "pageCount": 1,
  "totalCount": 25
  }
}

```
### Failure
**400 Bad Request
401 Authorised
403 Forbidden **

### Notes
- Add links to response where appropriate
- Internal payments service should be the starting point for this service
- Only landlord and tenant ledger items for now
- Brand new service, should be a lambda

**Comment by plittlewood-rpt** [comment]
@cbryanreapit Do we want to expose the code or textual version of the category? I've gone for the latter but it's a pretty long list so the Swagger documentation might look at bit messy. The former would mean adding a new endpoint to the configuration service to expose the information. For what it's worth, I think the latter is better as it makes the API easier to use, but just wanted to check

**Comment by plittlewood-rpt** [comment]
PR 3630 opened
