### ISSUE TITLE
Provide API to surface details about a specific transaction

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#3752]
This endpoint will be responsible for presenting details of a specific payment

**Location**
GET /transactions/{id} (protected: yes)

**Request**
Parameters
`id `- string - from path

**Response**
Success
200 OK

```

{
  "id": "PAY20000001",
  "created": "2018-12-12T12:30:23.0000000Z",
  "modified": "2019-01-08T12:30:34.0000000Z",
  "category": "categoryType",
  "type": "paymentRequest",
  "description": "Tenancy Check Fee",
  "status": "awaitingPosting",
  "ledger": "tenant",
  "netAmount": 100,
  "taxAmount": 20,
  "grossAmount": 120,
  "outstanding": 0,
  "companyId": null,
  "landlordId": null,
  "propertyId": "PRP200001",
  "tenancyId": null,
  "_eTag": null,
  "_links": {
    "self": {
      "href": "/payments/PAY20000001"
    },
  }
}

```
**Failure**
**400 Bad Request
401 Authorised
403 Forbidden
404 Not found **

**Notes**
- Add links as appropriate 
- Internal payments service should be the starting point for this service
- Only landlord and tenant ledger items for now

**Comment by plittlewood-rpt** [comment]
PR 3630 opened
