### ISSUE TITLE
Acorn Estate Agents - Vendor Invoices API

### ISSUE THREAD

**Issue by C4ADev** [reapit/foundations#3757]
**Is your feature request related to a problem? Please describe.**
There is not currently an API for querying/updating vendor invoices/credit notes.

**Describe the solution you'd like**
The REST API to be updated to include vendor invoice/credit notes for create/read/update/delete.

**Describe alternatives you've considered**
N/A

**Additional context**
Steve Gould advised us to raise a ticket for Acorn Estate Agents.  I believe that this was something discussed during their implementation stage of Reapit.

**Comment by dawson** [comment]
I’m closing this following our conversation with SG. Happy for it to be resubmitted and considered with correct fields and read-only scopes.
