### ISSUE TITLE
Show validation errors on the bottom of the Submit/Edit app pages

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#377]
**Summary:** A developer will be notified a validation has occurred but will not know which field it refers to unless they scroll up and view that particular section. This doesn’t provide a very good user experience. We should show all validation errors in the white space currently occupied by the ‘Submit App’ button. 

**Task:** To display the validation errors to the developer at the bottom of the ‘Submit’ and ‘Edit’ pages in the developer portal. 

**For example:** 
This is the following error that occurs when the characters in the summary box exceeds the limit 

![image](https://user-images.githubusercontent.com/52408607/74836502-6ca00100-5317-11ea-9f6c-87dcbc881244.png)

We should display this (in addition the message that appears around the field) to the developer at the bottom of the page.
- **Heading:** The following validation errors have occurred:
- Should include the field label and the description of the error

See example: 
The following validation errors have occurred:
Summary: The value provided exceeds the maximum length of 150 characters

See mockup: 
![image](https://user-images.githubusercontent.com/52408607/74836547-83deee80-5317-11ea-9886-31b66d1a1828.png)

See mockup of multiple validation errors: 
![image](https://user-images.githubusercontent.com/52408607/74836571-8ccfc000-5317-11ea-981f-f27f791d524f.png)

**Comment by tanphamhaiduong** [comment]
Propose migrate to https://github.com/jquense/yup for validation form with formik

**Comment by phmngocnghia** [comment]
@HollyJoyPhillips 
I have some questions about this task:
- Should I render the field 'description' from the error response? (some error responses only have field 'description' and don't have field 'errors'. E.g.: User have reached maximum apps)
- If yes, then how would you like it to be placed?

**Comment by phmngocnghia** [comment]
@HollyJoyPhillips 
In case of a field has more than one error, how should it be displayed? (E.g. two errors: an error of client-side, another is an error of server-side)

I think there is a lot of spacing, so think they could be separated by a comma.

**Comment by HollyJoyPhillips** [comment]
@phmngocnghia I agree, including the description is a good thing, it might be too much text but i think the more information to help the end user is a good idea. We can always alter it after we get some initial feedback. 

Please use the description text as the header: "One or more validation failures have occurred..." and as you said, if it is not present, use 'The following validation errors have occurred"

If 2 errors occur, BE and FE display both separated by a comma. It believe it will be a rare case to see so many errors listed so lets see how it looks first. Thank you.

**Comment by HollyJoyPhillips** [comment]
@phmngocnghia Thanks for changing the names, looks much better. Just one thing, 'Name' is appearing twice:

![image](https://user-images.githubusercontent.com/52408607/75462947-f46fb600-597c-11ea-97d2-71cc8fd29bf8.png)

It looks as though it should be 'Icon': 
See remaining validation:
![image](https://user-images.githubusercontent.com/52408607/75462999-0fdac100-597d-11ea-8bb9-697604e75fb5.png)

See the code: 
![image](https://user-images.githubusercontent.com/52408607/75463106-37318e00-597d-11ea-9b8b-222cff4e9974.png)
