### ISSUE TITLE
31st March - Update Developer Edition subs and pricing

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#3781]
-On 31st March 2021 we should update the subscription cost for the Developer Edition of Agency Cloud from 0 to 300 
- Cancel all existing subscriptions for dev edition
- Preferably do cancellations via API so that group memberships are revoked.
- Check for anyone who has a developer edition group membership after this occurs to ensure nobody gets through the cracks

**Comment by cbryanreapit** [comment]
@HollyJoyPhillips we decided to shift this to next week while you're around to oversee
