### ISSUE TITLE
Include Commission Info in API

### ISSUE THREAD

**Issue by tsadlerbrs** [reapit/foundations#3786]
**Is your feature request related to a problem? Please describe.**

We currently use the SQL views for our application and have to migrate across to the API as the SQL views are now depreciated. We have access to the documentation and the commission info is not available.

We need to use the GET  -- /tenancies/?embed=property endpoint to obtain commission info but this is not currently available.

**Describe the solution you'd like**

Include the Comm and Commman fields in the endpoint detailed above

Include the Comm and Commman fields in the endpoint detailed above

**Describe alternatives you've considered**

Make legacy SQL views available to us

**Additional context**

**Comment by cbryanreapit** [comment]
Thanks for reaching out @tsadlerbrs 

I believe we already have a ticket for this request: https://github.com/reapit/foundations/issues/3465

I'll close this one as a duplicate. You can track our progress on the other ticket, we'll look to prioritise in the next 1/2 weeks.
