### ISSUE TITLE
Send email notification on success/failure for bulk data indexing service

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#3791]
**Background**
The bulk indexer should be a tool run by SI rather than engineering, as such, we should introduce feedback on it's success or failure.

**Specification**
- Send SES/SNS email on completion or failure of bulk index
- Email addresses to be confirmed by the team

**Comment by RWilcox-Reapit** [comment]
Tested and closing, 
Notification triggered from dev environment are fired to our slack notification channel, prod environment is fired to the email address provided by infra
