### ISSUE TITLE
The description and summary fields are not being validated in the front end

### ISSUE THREAD

**Issue by willmcvay** [reapit/foundations#380]
Issue:

On the submit app form, it is possible to submit an app in error where the description and summary fields are not being validated correctly. Currently we only validate that these fields are required however there is an upper and lower char limit.

Fix:

Summary should be validated between 50 and 150 chars.
Description should be validated between 150 and 1000 chars.

Validations should read: 
Must be between 50 and 150 characters” for Summary and “Must be between 150 and 1000 characters” for Description

**Comment by tanphamhaiduong** [comment]
@willmcvay So what will we show for the error message when user input wrong?
