### ISSUE TITLE
The Sentry logger should display more helpful information on BE errors

### ISSUE THREAD

**Issue by willmcvay** [reapit/foundations#381]
See this issue on Sentry:  https://sentry.io/organizations/reapit-ltd/issues/1523624392/?project=1885615&referrer=slack

2 issues here;

- Firstly, the error was generated by a type error caused by Sentry itself not the 422 from the server. This is a low priority bug, needs fixing but not a huge problem.
- Secondly, and more importantly, we were not able to diagnose the cause of the 422 error because the server errors list was not available.

Steps to replicate: See #380 - submitting an app without a complete field will throw a 422 and cause this problem. 

Fix: Ensure type error is not thrown by Sentry
Enhancement: Capture platform errors and pass to Sentry so we can see the back end problems our users are generating.

**Comment by vuhuucuong** [comment]
Hi @willmcvay , I have a question
This means we'll include **all** the API calls from `marketplace`, not just the submit app API, right?
And for now, do we need to update in other APPs or just `marketplace` ?

**Comment by vuhuucuong** [comment]
Hi @willmcvay @HollyJoyPhillips , another problem with this.
I tried to submit an app with invalid data in https://marketplace.reapit.cloud/developer/submit-app
I see `Sentry` send a POST request with the exception, but it's not shown in `https://sentry.io/` dashboard. 

![image](https://user-images.githubusercontent.com/26746668/75007489-e49d3100-54a7-11ea-85ea-769da89533ae.png)
It seems to work fine from localhost when I `start:dev` and change the logic to something like this
![image](https://user-images.githubusercontent.com/26746668/75007710-8755af80-54a8-11ea-9a2e-8cf2f1261aa3.png)

Not sure what's happening here 🤔

**Comment by willmcvay** [comment]
See: https://sentry.io/organizations/reapit-ltd/issues/1525740914/?project=1885603&referrer=slack
Looks like the stack trace capture is still not working in prod am afraid. @vuhuucuong can you investigate please?

**Comment by vuhuucuong** [comment]
@willmcvay that's weird, let me check again, cannot reproduce it in local 🤔

**Comment by vuhuucuong** [comment]
@willmcvay  look like the problem is happening when using safari or firefox, work fine in chrome. Let me try to find a solution

**Comment by HollyJoyPhillips** [comment]
@vuhuucuong The errors are reporting nicely, I've tested on Chrome & Firefox. Will test on IE when we can. Thanks
