### ISSUE TITLE
Sending images to property images endpoint gives a 500 error repeatedly throughout the day

### ISSUE THREAD

**Issue by mark-orme** [reapit/foundations#3814]
2 requests attached which get a 500 error response from the server.

[Basecamp Download.zip](https://github.com/reapit/foundations/files/6183082/Basecamp.Download.zip)

**Comment by mark-orme** [comment]
on the attached examples they did eventually go through as part of our auto retry but we need to establish why some are getting a 500 error as customers are complaining that some are not being received from us if it errors more than our auto retry then the image(s) are not received etc.

I did add a feature request to be able to send more than 1 image at a time as at least then they are all received or all fail etc.

**Comment by cbryanreapit** [comment]
Thanks for the info @mark-orme - in order for us to investigate further, are you able to provide the request id from a failed requests response header please? You can find details on how to locate that here : https://api-docs.dev.paas.reapit.cloud/api/api-documentation#errors

**Comment by mark-orme** [comment]
did you see the 2 requests attached ?

**Comment by cbryanreapit** [comment]
I did - but since you've described this is an intermittent problem,  we're looking for information provided to you with the failed response, rather than just the request (the `x-amzn-RequestId` response header). This will allow us to see exactly what went wrong, what customer it was for, etc. Many thanks.

**Comment by mark-orme** [comment]
I will get the request Id but this is the reply we are getting etc.

''Failed to upload deliverable #12619820. Exception: Server error: `POST https://platform.reapit.cloud/propertyImages` resulted in a `500 Internal Server Error` response:''

**Comment by mark-orme** [comment]
Hi there, we are also getting failed issues to the /documents endpoint:

we had a 504 Gateway Timeout` response from the below request ID

ID for that request is 25053353-f8b7-44f1-b93f-26002a8b6d91 and gateway ID csrOUEiCrPEFdXw=

**Comment by mark-orme** [comment]
Morning,

we have 5 more examples today please can you let me know why they keep failing ? @cbryanreapit 


| Date                         | x-amzn-requestid                     | x-amz-apigw-id   | x-amzn-trace-id                                    |
|------------------------------|--------------------------------------|------------------|----------------------------------------------------|
| 2021-03-25T10:54:50.4607774Z | 46020427-5030-46cb-bf11-6136f3217404 | cvXPDF6KLPEFhdw= | Root=1-605c6bf9-5264d3b57e6a629e2bd75fea;Sampled=0 |
| 2021-03-25T10:54:53.2315093Z | da3ad604-bb0f-44c1-aa47-2f86fa234c12 | cvXPiE85LPEFvcw= | Root=1-605c6bfc-4bc51eaa1014fab92ea6bb12;Sampled=0 |
| 2021-03-25T10:54:55.6802947Z | 523b455e-caae-4c30-bacd-c946d3651b6d | cvXP1EUVrPEFWlA= | Root=1-605c6bfe-212c6052585ee9b55d5c1576;Sampled=0 |
| 2021-03-25T10:55:00.8612054Z | df703987-ca75-4ec9-89d0-ed09e5e8e55b | cvXQsEmbrPEFqOg= | Root=1-605c6c04-69b3413a4e1c7f4f10d337c0;Sampled=0 |
| 2021-03-25T10:55:07.5465334Z | 1000e304-90ff-4c09-a17e-a17e987a9d64 | cvXRvG0ALPEFl2w= | Root=1-605c6c0b-2d834a6b12fb0bdf40e867ab;Sampled=0 |
| 2021-03-25T10:55:14.9618376Z | c35adf66-2644-4cf8-9e1a-8f91cd5fcfec | cvXS6H7lLPEFg3g= | Root=1-605c6c12-6d7d06546f2838e837b2480d;Sampled=0 |

**Comment by cbryanreapit** [comment]
Thanks @mark-orme - are those examples images or documents?

**Comment by mark-orme** [comment]
they are property images on these 6, as per the below

Failed to upload deliverable #12658513. Exception: Server error: `POST https://platform.reapit.cloud/propertyImages` resulted in a `500 Internal Server Error` response:

**Comment by cbryanreapit** [comment]
Thanks for providing those ids, we'll check out the specific failures

**Comment by plittlewood-rpt** [comment]
Hi @mark-orme 

Thanks for the info so far. Can you confirm how you are interacting with the API when you send images. Do you send one and wait for a response before sending the next one, or are you sending multiple requests at a time (so we've effectively got multiple requests running concurrently)?. This might help track down the problem.

Thanks
Pete

**Comment by mark-orme** [comment]
We send them concurrently

**Comment by plittlewood-rpt** [comment]
Ok thanks - I can see why this could happen intermittently. I've got an update ready to QA that extends the retry behaviour in the service which should hopefully mitigate these problems

**Comment by plittlewood-rpt** [comment]
PR 3641 opened

**Comment by mark-orme** [comment]
Thanks Pete

We have added a new feature  request to allow for a payload with more than
one image as our average is 25 per property which when sending 1:1 is open
to more fails etc



On Mar 25, 2021, at 13:44, Pete Littlewood ***@***.***> wrote:

﻿

PR 3641 opened

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/reapit/foundations/issues/3814#issuecomment-806768318>,
or unsubscribe

**Comment by cbryanreapit** [comment]
@mark-orme 

Uploading 25 images concurrently will be problematic as you'll hit the [rate limits applied to your app](https://api-docs.dev.paas.reapit.cloud/api/api-documentation#rate-limits). This will be playing a part in your issues.

The work we're doing at our end should help matters, but you should see more reliable mass uploads by introducing a short delay between each image. 

Your request for batch upload is in our backlog and will be prioritised

**Comment by mark-orme** [comment]
Thanks for this.

looking at the logs we have not seen one 429 error at all its all been the 500 error detailed above but we will take note of the limit etc.

thanks

**Comment by plittlewood-rpt** [comment]
@mark-orme  I've pushed out the updates to our production environment just now and will continue to monitor performance on this service

**Comment by mark-orme** [comment]
Hi there thanks for this, since your deploy we have a new error on same endpoint.

Failed to upload deliverable #12681451. Exception: Client error: `POST https://platform.reapit.cloud/propertyImages` resulted in a `400 Bad Request` response:

I will get the request Id's so you can have a look

thanks.

**Comment by plittlewood-rpt** [comment]
Thanks Mark - I can see those so don't worry about looking through your logs. It looks like this approach wasn't enough. I'll see what else we can do. How difficult would it be to send these images sequentially instead of all at once?

**Comment by mark-orme** [comment]
Hi Pete

 

While we upload concurrently we should only ever have 2-3 uploads going at the same time. The concurrency comes from the floorplans possibly being sent at the same time as photos conversion as when they come in we trigger a separate job to upload those and the photos task may already be in progress, otherwise uploads are done synchronously per-task

**Comment by plittlewood-rpt** [comment]
Thanks - I've increased the pause between retries slightly (100ms so won't cause you any issues) to see if helps to alleviate things

**Comment by mark-orme** [comment]
Hi Pete,

we are back to 500 errors now it seems:

[REAPIT]: Failed to upload deliverable #12684242. Exception: Server error: `POST https://platform.reapit.cloud/propertyImages` resulted in a `500 Internal Server Error` response:

**Comment by plittlewood-rpt** [comment]
Hi Mark 

I've pushed some further adjustments out to this handling. I'm hopeful the latest change will resolve this but let me know if you see any more failures. I'll monitor at this end also

**Comment by mark-orme** [comment]
hi Pete,

I can add a new ticket but not sure if linked to this but we are also getting errors from the /documents endpoint as well.

[REAPIT]: Failed to upload deliverable #12699302. Exception: Server error: `POST https://platform.reapit.cloud/documents` resulted in a `504 Gateway Timeout` response:

**Comment by plittlewood-rpt** [comment]
Hi Mark

Yes if you can log a new ticket that would be great thanks. It's likely a separate issue. Thanks

Pete

**Comment by mark-orme** [comment]
[REAPIT]: Failed to upload deliverable #12713156. Exception: Server error: `POST https://platform.reapit.cloud/propertyImages` resulted in a `504 Gateway Timeout` response:

we have had a different error today on this ?

**Comment by mark-orme** [comment]
Hi Pete,

We are getting lots of 504 gateway timeout errors today and clients complaining of no images received:

Apr 09 10:32:38 ip-172-31-17-56 laravel-cli-2021-04-09.log [2021-04-09 09:32:38] production.ERROR: [REAPIT]: Failed to upload deliverable #12822628. Exception: Server error: `POST https://platform.reapit.cloud/propertyImages` resulted in a `504 Gateway Timeout` response:

we are getting these throughout the morning on uploads

**Comment by mark-orme** [comment]
Hi Pete,

We are getting lots of 504 gateway timeout errors today and clients complaining of no images received:

Apr 09 10:32:38 ip-172-31-17-56 laravel-cli-2021-04-09.log [2021-04-09 09:32:38] production.ERROR: [REAPIT]: Failed to upload deliverable #12822628. Exception: Server error: POST https://platform.reapit.cloud/propertyImages resulted in a 504 Gateway Timeout response:

we are getting these throughout the morning on uploads

**Comment by plittlewood-rpt** [comment]
Hi Mark

We have identified the cause of the problem and it should now be resolved

Thanks
Pete
