### ISSUE TITLE
Please can you expose the Exchange Fee and Fee Banked the Listing via the API?

### ISSUE THREAD

**Issue by jpmorganuk** [reapit/foundations#3817]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by cbryanreapit** [comment]
@jpmorganuk can you fill in the template with the details of your request please? Thanks.

**Comment by cbryanreapit** [comment]
Closing ticket due to lack of response, please provide information required if this is still needed. Thanks.

**Comment by jpmorganuk** [comment]
Is your feature request related to a problem? Please describe.
The problem is creating an ROI statement for the software. If we knew the banking, we could identify the properties that had used Acaboom vs those that did not, and therefore work out if the fees are higher with or without our software.

Describe the solution you'd like
We would like to know the fees at exchange or banking.

Describe alternatives you've considered
We have looked at using the fee at listing, but there is slippage.

Additional context
None

**Comment by jpmorganuk** [comment]
Apologies for the slow response.
