### ISSUE TITLE
https://developers.reapit.cloud/webhooks page requests are failed

### ISSUE THREAD

**Issue by HenadziMiasnikou** [reapit/foundations#3819]
When click on any button/link on the webhooks page requests are failed

Steps to reproduce the behaviour eg:
1. Go to https://developers.reapit.cloud/webhooks
2. Click on "Edit"/"Add New Webhook" buttons or "Ping" link
3. See error "An unexpected error has been encountered when fulfilling this request. This incident has been logged and will be investigated. Please try again."

![image](https://user-images.githubusercontent.com/81237289/112148988-8fbe7380-8bef-11eb-89da-6804ec342d1e.png)
**Device (please complete the following information for web issues):**
 - Device: PC
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 89.0.4389.90

**Comment by cbryanreapit** [comment]
If you could also let us know your organisations name and the name of the app you're building (as described in the developer portal), that will help us investigate. If you'd prefer to provide this privately, please use our live chat feature.

**Comment by plittlewood-rpt** [comment]
Hi @HenadziMiasnikou please can you try this again when you get a moment and let us know the results. I believe this may be related to #3586

**Comment by HenadziMiasnikou** [comment]
Hi,

Now it works well.

Thanks.

**Comment by plittlewood-rpt** [comment]
Thanks for confirming. Please feel free to follow the ticket mentioned above for updates.
