### ISSUE TITLE
Foundations API 401 Unathorized returns Malformed JSON

### ISSUE THREAD

**Issue by eazynow** [reapit/foundations#383]
Summary:
If you attempt to call the foundations API without having provided relevant credentials, you get a 401 response, however the JSON is malformed as it's missing a comma after the datetime.

Steps to reproduce:
A simple curl suffices:

```
 curl https://dev.platform.reapit.cloud/applicants/
```

Expected Results:
```
{
    "statusCode": 401,
    "dateTime": "",
    "description": "Unauthorized"
}
```

Actual Results
```
{
    "statusCode": 401,
    "dateTime": ""
    "description": "Unauthorized"
}
```

**Comment by HollyJoyPhillips** [comment]
The Platform team have resolved this issue and the fix has now been applied. I have contacted Erol directly to let him know.
