### ISSUE TITLE
Provide additional user context to downstream services

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#3832]
**Background context**
We should provide additional user context to our downstream services

**Specification**
- Add email address
- Add userId
- Any other information that might be useful

**Comment by plittlewood-rpt** [comment]
PR 3765 opened to include email address in authorizer context. UserId is already being returned (but may not be being mapped downstream, will check this as second part of this work)

**Comment by plittlewood-rpt** [comment]
PR 3766 opened to update downstream identity mapping mechanism
