### ISSUE TITLE
BER information (Legal requirement to display on all ads in Ireland) - similar to EPC UK 

### ISSUE THREAD

**Issue by awogan06** [reapit/foundations#3851]
In Ireland we are legally required to provide BER (similar to your EPC) information on each property we have for sale, or to Rent.
 
We store this information on the a custom version of the EPC screen see sample below,  all three fields must be advertised on our websites and any advertising.   This information is not available in the API and is required urgently for us to publish information to our website.

![BER Screen RPS (Irish clients)](https://user-images.githubusercontent.com/80464318/112832058-b3b90380-908c-11eb-81f1-852a348c4074.JPG)

**Comment by cbryanreapit** [comment]
Investigating how this functionality works and how best to provide it for next grooming session

**Comment by cbryanreapit** [comment]
Superseded by https://github.com/reapit/foundations/issues/4025 - I will therefore close this issue and use the other the progress.
