### ISSUE TITLE
Expose functionality of the geolocation app to the desktop API so we can add functionality using our own app

### ISSUE THREAD

**Issue by andycurriew3w** [reapit/foundations#3855]
**Is your feature request related to a problem? Please describe.**

In order to create an app with a good user journey we would like to be able to add to the functionality of the geolocation app used when locating a property.

<img width="698" alt="Screenshot 2021-03-29 at 16 25 48" src="https://user-images.githubusercontent.com/35260231/112860175-8039a180-90ab-11eb-8b4b-cbffab1d64d3.png">

**Describe the solution you'd like**

We would like to be able to access the geolocation app for the desktop application using the API [https://developers.reapit.cloud/api-docs](url). We would like to be able to modify the screen above to include extra information and an input field etc. 

**Describe alternatives you've considered**

The alternative is to add duplicated functionality but outside of the main user journey (under Menu -> App -> our app) which we think the user may forget to use.

**Comment by cbryanreapit** [comment]
@PaulHaynes this ticket would align to Agency Cloud

**Comment by AshDeeming** [comment]
Hi @andycurriew3w, please note that as this request relates to AgencyCloud & has been logged with the correct team via the below link.
https://reapit.atlassian.net/browse/PBI-2457
