### ISSUE TITLE
The app scaffolder is broken in Windows shell

### ISSUE THREAD

**Issue by willmcvay** [reapit/foundations#386]
Scaffolding an app is not possible in Windows shell.

I believe that this is because internally the scaffolder leverages unix kernal specific commands to move files, resulting in a failure at the lint stage in the scaffold because the moved files are not in the directory as expected.

Fix: will need to find a way of outputting files to target directory without bash specific commands

Test: Needs verifying on a Windows Shell. User was using shell for Visual Studio 2017. 

![image](https://user-images.githubusercontent.com/4630495/74955011-e9a4a680-53fb-11ea-9e22-21abb608ff73.png)

**Comment by tanphamhaiduong** [comment]
Assign to @nphivu414 because you use window laptop

**Comment by vuhuucuong** [comment]
https://github.com/prettier/prettier/issues/4804
I think it's just a quote issue , try change to double-quote to see if this works @nphivu414 :)
