### ISSUE TITLE
Update first-load routine to prepare user for interaction with snowflake via metabase

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#3881]
When a new organisation encounters metabase for the first time, we should prepare a snowflake user for their organisation to interact with.

- A new role to be created per organisation
- Role to be granted permission to interact with required schemas
- A new user to be added with that role employed and defaulted (no storage requirement)
- New user to be assigned to auto scaling warehouse (shared) and defaulted

**Comment by RWilcox-Reapit** [comment]
Closing ticket as I have ran this end to end on dev pointing towards the production snowflake. 
(See collection '75' in metabase which is hooked up to sales data)
Raising a subsequent ticket to bring the snowflake dev account inline with prod.
