### ISSUE TITLE
Bank details desktop type

### ISSUE THREAD

**Issue by MarkMpn** [reapit/foundations#3899]
**Is your feature request related to a problem? Please describe.**
Partners could provide additional value around bank details

**Describe the solution you'd like**
A desktop type of "Bank" to replace the standard bank account details control

**Comment by cbryanreapit** [comment]
Could you provide more information about your use case please?

FYI @PaulHaynes

**Comment by MarkMpn** [comment]
We would like to be able to replace the standard bank details screen (sort code, account number etc) with our own in order to provide validation and show additional information about the bank/account

**Comment by AshDeeming** [comment]
Hi @MarkMpn 
Please note that this request is now under the relivant team for AgencyCloud; https://reapit.atlassian.net/browse/PBI-2455
