### ISSUE TITLE
Documents broker has intermittent JsonReader errors

### ISSUE THREAD

**Issue by plittlewood-rpt** [reapit/foundations#3900]
Spotted in application logs. There have been a small handful of errors in the following format from the documentsBroker (latest error 7/4/2021)

`Error reading JObject from   JsonReader. Current JsonReader item is not an object: StartArray. Path '',   line 1, position 1.`

We need to understand what is causing this and resolve the problem

**Comment by cbryanreapit** [comment]
Not a prevalent issue, closing until such a time that it is
