### ISSUE TITLE
Review CloudWatch log verbosity and identify opportunities to reduce

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#3926]
**Specification**
- Review cloudwatch logs
- Identity areas / services / packages that are being overly verbose
- Outcome of this ticket is new tickets to resolve

**Comment by plittlewood-rpt** [comment]
LInk to discussion summary circulated to interested parties. To discuss in more detail before logging new tickets as approach needs to be agreed which will determine which path we take on this one

**Comment by plittlewood-rpt** [comment]
#3955 logged off the back of this ticket to look at implementing new mechanism
