### ISSUE TITLE
Generate GraphQL types from Foundations TS Definitions

### ISSUE THREAD

**Issue by willmcvay** [reapit/foundations#3940]
**Background context or User story:**

_Currently GraphQL definitions were written from TS types manually - this is a maintenance pain. We should be able to automate this_

**Specification or Acceptance Criteria:**

- For each entity, find a codegen tool that can generate GraphQL types from the Foundations TS Definitions, keeping the schema in sync with the platform API each time the definitions are published.
- Update all entities using this system and re-generate schema then deploy

**Comment by bashleigh** [comment]
@willmcvay Shall I closed this issue? As #4142 continues from this?

**Comment by willmcvay** [comment]
@bashleigh yep, please feel free
