### ISSUE TITLE
Add file size validation on AML

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#3942]
**Summary**: Currently, AML allows files to be upload that exceed the file limit (on or around 3.2mb) although do not allow the user to proceed (next/save disabled). 

**Task:** Investigate the option to validate the file size after uploading or provide a textual indication of the file size limit (will need to validate it's at 3.2mb. 

![image](https://user-images.githubusercontent.com/52408607/114421630-6751e580-9bad-11eb-8adf-9c7d5cb05fd4.png)

**To replicate:** 
Upload a file larger that 3.2 mb.

**Comment by HollyJoyPhillips** [comment]
@willmcvay The next/save buttons are now enabled but it's not patching the fileData or the name if the file is too large: 

See 3.2mb
![image](https://user-images.githubusercontent.com/52408607/114573695-82395e00-9c70-11eb-8e5d-d16ef403a1a8.png)


See 3.9mb
![image](https://user-images.githubusercontent.com/52408607/114573676-7a79b980-9c70-11eb-9706-d6db43550bf8.png)

**Comment by willmcvay** [comment]
Have added a validation in the end - seems there is a file size limit on the gateway
