### ISSUE TITLE
Creating journal entries does not allow for British Summer Time

### ISSUE THREAD

**Issue by Mike-PygottandCrone** [reapit/foundations#3946]
**Describe the bug**
When creating a journal Entry using the POST /journalEntries endpoint, the datetime is being set in GMT. Hence, in RPS the journal entry is showing "1 hour ago".

**To Reproduce**
Steps to reproduce the behaviour eg:
1. Make a journal entry POST call
2. Open corresponding file and examine journal

**Expected behaviour**
Journal entry datetime to be in the current timezone i.e. BST

I've attached a dump of the args and response when making a request, also note current timestamp on first line (highlighted yellow), and a screenshot of the journal in RPS

![journalrps](https://user-images.githubusercontent.com/77488245/114544138-21029200-9c52-11eb-9b8f-b40b24ff42e5.jpg)
![journaldebug](https://user-images.githubusercontent.com/77488245/114544141-219b2880-9c52-11eb-827a-decffb773e9f.jpg)

**Specification**
- Replicate the issue and present a solution to the team

**Comment by plittlewood-rpt** [comment]
Hi @Mike-PygottandCrone this should now be resolved. Please let me know if you continue to see any issues
