### ISSUE TITLE
Update the insights page to handle incomplete account provision status

### ISSUE THREAD

**Issue by RWilcox-Reapit** [reapit/foundations#3956]
Recent changes have meant that the metabase setup routing is now asynchronously.

This means return a payload containing a status and the content duplication and warehouse is done in the background. The user is then later emailed to notify them that the setup has complete.

Now when calling the POST Authenticate endpoint the response body contains one of three statuses , these are: 'complete', 'incomplete' and 'failed'. 

The insights app is built to wait for the long process to finish as it did before but as it no longer does this the holding screen needs to be updated.

On a response of 'complete' the user is navigated to metabase which can continue as normal.
We need to handle the situations where the setup is 'incomplete' and 'failed' and inform the user respectively

**Comment by cbryanreapit** [comment]
I think @willmcvay completed this - closing - re-open if not :)
