### ISSUE TITLE
500 error returned in property update request

### ISSUE THREAD

**Issue by ConnorFC** [reapit/foundations#3957]
**Describe the bug**
When attempting to update a property within the sandbox a 500 error is returned, this also occours when using the same data used to create the property and also using the example data on the Swagger page.

**To Reproduce**
Steps to reproduce the behaviour eg:
1. Make a PATCH request to https://platform.reapit.cloud/properties/PROPERTY_ID with example information

**Expected behaviour**
A success message indicating an update was successful or a 4xx to show an issue on my end

**Screenshots**
<img width="504" alt="image" src="https://user-images.githubusercontent.com/81359005/114690561-ba8f7980-9d0e-11eb-8eb3-86fdbaf699c6.png">

**Additional context**
This is using the sandbox and I can confirm I populated:
* Property ID in URL
* etag in If-Match header
* api-version in header
* reapit-customer in header
* Bearer token

**Comment by cbryanreapit** [comment]
Hi @ConnorFC - could you provide us with request id please? It is provided to you in the header of the response (x-amzn-RequestId). Additionally, it would be helpful if could you just confirm the exact payload that you are providing with your PATCH

**Comment by ConnorFC** [comment]
@cbryanreapit Hello, I am using the payload listed on the Swagger docs here 
`{
  "strapline": null,
  "description": "We are delighted to offer for sale this EXTENDED THREE BEDROOMED SEMI DETACHED PROPERTY situated in a much sought after residential location of Greasby, having the benefits of two separate entertaining rooms, morning room, extended kitchen. To the first floor there are three bedrooms, spacious family bathroom, gas central heating gardens front and rear and off road parking.",
  "summary": null,
  "alternateId": "10002",
  "address": {
    "buildingName": null,
    "buildingNumber": "15",
    "line1": "Example street",
    "line2": "Solihull",
    "line3": "West Midlands",
    "line4": "",
    "postcode": "B91 2XX",
    "countryId": "GB",
    "geolocation": {
      "latitude": 52.4158586,
      "longitude": 1.7773383
    }
  },
  "bedrooms": 4,
  "receptions": 1,
  "bathrooms": 2,
  "councilTax": "A",
  "internetAdvertising": true,
  "viewingArrangements": "Accompanied viewings after 3PM only",
  "videoUrl": "https://www.example.com/property/123/videoTour",
  "videoCaption": "Virtual property tour",
  "video2Url": "https://www.example.com/property/123/3dVideoTour",
  "video2Caption": "3d virtual property tour",
  "notes": "Property was on the market previously with another agent but struggled to get much interest",
  "epc": {
    "exempt": false,
    "eer": 45,
    "eerPotential": 71,
    "eir": 53,
    "eirPotential": 81
  },
  "externalArea": {
    "type": "acres",
    "min": 1,
    "max": 2
  },
  "internalArea": {
    "type": "squareFeet",
    "min": 1500,
    "max": 2000
  },
  "selling": {
    "instructed": "2018-11-18",
    "price": 250000,
    "qualifier": "askingPrice",
    "status": "underOffer",
    "disposal": "privateTreaty",
    "completed": "2019-08-27",
    "exchanged": "2019-08-15",
    "tenure": {
      "type": "leasehold",
      "expiry": "2019-05-01"
    },
    "sellingAgency": "ownToSell",
    "fee": {
      "type": "fixed",
      "amount": 1900
    },
    "recommendedPrice": 450000
  },
  "letting": {
    "instructed": "2018-11-18",
    "availableFrom": "2018-12-26",
    "availableTo": "2019-03-23",
    "rent": 750,
    "rentFrequency": "monthly",
    "furnishing": [
      "furnished",
      "partFurnished"
    ],
    "term": "long",
    "status": "toLet",
    "agentRole": "managed",
    "landlordId": "LLD210001",
    "managementFee": {
      "type": "percentage",
      "amount": 11.8
    },
    "lettingFee": {
      "type": "fixed",
      "amount": 190
    }
  },
  "type": [
    "house"
  ],
  "style": [
    "detached"
  ],
  "situation": [
    "garden",
    "land",
    "patio"
  ],
  "parking": [
    "secure",
    "doubleGarage"
  ],
  "age": [
    "period"
  ],
  "locality": [
    "rural",
    "village"
  ],
  "negotiatorId": "JAS",
  "officeIds": [
    "OXF",
    "SOL"
  ],
  "areaId": "BRM",
  "metadata": {
    "CustomField1": "CustomValue1",
    "CustomField2": true
  }
}`

The request ID is `bb4d3283-e31a-4b22-bd3a-c1bfefca5634`

**Comment by garymiller1966** [comment]
@cbryanreapit can you please provide an estimate when this bug will be picked up? The ability to update property data is a core feature required for a property software platform....

**Comment by cbryanreapit** [comment]
@garymiller1966 there appears to be something not right about your request - PATCH works fine in the swagger documents and for other integrators. I'll allocate more time for the team to dig in further and report back.

**Comment by cbryanreapit** [comment]
@garymiller1966 from what we're seeing in our logs, believe this is because you're likely passing through an invalid eTag format (probably missing quotation marks) 

The optimistic concurrency section of our [platform documentation](https://developers.reapit.cloud/api-docs) demonstrates the required format. Alternatively, you can find that information here: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag

We have a ticket in our backlog to handle this situation better: https://github.com/reapit/foundations/issues/3608

Let us know if this doesn't solve the issue and we'll re-open the ticket.
