### ISSUE TITLE
Pass Applicant or Property ID to App when launching an Identity Check integration

### ISSUE THREAD

**Issue by nroper** [reapit/foundations#3971]
**Is your feature request related to a problem? Please describe.**
It is frustrating that the Identity Check integration doesn't make the associated Applicant or Property ID to the App when an Identity Check link is clicked on an Applicant or Property page.  Our client currently uses a custom extension that replaces the default 'Identity Check' behaviopus and is aware of the underlying case ID.  Our Foundations App will be replacing this extension in due course, but we are currently unable to access case ids via this integration point. 

**Describe the solution you'd like**
On launching an Identity Check integration, make the associated Applicant or Property id available to the App along with the `cntCode' value.

**Describe alternatives you've considered**
The only alternative that we seem to have at the moment is for the user to launch the App via the Applicant or Property 'Apps' menus, but this isn't consistent with the journey that they are used to with the current extension.

**Additional context**

**Comment by AshDeeming** [comment]
Hi @nroper 
Please note that this request is logged under the relevant team; https://reapit.atlassian.net/browse/PBI-2471

**Comment by nroper** [comment]
@AshDeeming thanks for the update - I don't have access to the JIRA item
