### ISSUE TITLE
Provide additional image processing for upload of new property images

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#398]
### Overview
At present, `POST /propertyImages` will accept file data and subsequently upload into the relevant client file store location. We don't perform any processing on that image which could result in unnecessarily large images being stored and high storage costs for our customers. 

### Expected behaviour

- Images should be capped to a maximum dimension - image size TBC - discuss with team before proceeding

**Comment by HollyJoyPhillips** [comment]
Duplicate ticket logged #7233
