### ISSUE TITLE
403 error when accessing property images endpoint on sandbox

### ISSUE THREAD

**Issue by ConnorFC** [reapit/foundations#3992]
**Describe the bug**
On the sandbox, despite the application supporting the read property images and write property images permission the API returns a 403 for all endpoints related to property images.

**To Reproduce**
Steps to reproduce the behaviour eg:
1. Create an app with read property images and write property images permission
2. Call endpoint to add image to property

**Expected behaviour**
A property image to be added or a different error explaining why

**Screenshots**
<img width="889" alt="image" src="https://user-images.githubusercontent.com/81359005/115355975-18aad980-a1b3-11eb-9542-a6d8585bf152.png">
<img width="1002" alt="image" src="https://user-images.githubusercontent.com/81359005/115356383-82c37e80-a1b3-11eb-9a0b-73f14bc992c8.png">
<img width="994" alt="image" src="https://user-images.githubusercontent.com/81359005/115356437-91119a80-a1b3-11eb-8a41-5b773dda7cd7.png">
<img width="995" alt="image" src="https://user-images.githubusercontent.com/81359005/115356484-9c64c600-a1b3-11eb-8858-f1949ffec04f.png">

**Additional context**
Headers present: 
* Bearer token
* api-version
* reapit-customer
Amazon Request ID for creation endpoint: 2e463c0d-04ce-4e6c-b682-cf5f47e08a66

**Comment by cbryanreapit** [comment]
@ConnorFC does the same access token grant you access to the other endpoints you've got scope for? Did you add any additional scopes to your application shortly before testing this?

**Comment by ConnorFC** [comment]
@cbryanreapit Hello, right now we've only been using the create and update properties endpoints which have been working. I did add the permissions for property documents shortly after running into this issue for the first time as a bit of a sanity check

**Comment by cbryanreapit** [comment]
Thanks for the info - could you give this another go after obtaining a fresh access token and let us know the outcome? If the outcome remains the same, a timestamp of your failed requests would also be useful to us. Many thanks.

**Comment by ConnorFC** [comment]
@cbryanreapit I used a fresh access token and got back the same response.

Timestamp as returned by HTTP header "Thu, 22 Apr 2021 11:19:22 GMT"
Amazon request ID "58ed664f-b1d0-4b6c-af3f-ff811be65f44"

**Comment by garymiller1966** [comment]
@cbryanreapit hi, could we please have an update on this ticket as we are still blocked sending property images to Reapit..thanks

**Comment by cbryanreapit** [comment]
No known issues with this functionality - this is almost certainly going to be an issue with the way the request has been built. Recommend you use live chat in our developer portal from here and we can assist there.

**Comment by willmcvay** [comment]
Resolved over live chat - endpoint needed to be camelCase ie `/propertyImages`
