### ISSUE TITLE
End to end testing of Reapit Insights in production

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#3999]
**Background context**
We should run the entire end to end experience of Reapit Insights for a new customer using the app for the first time using the now built library

**Specification**
- Outcome is a demonstration to the team

**Comment by RWilcox-Reapit** [comment]
End to end testing complete and working for RES (See collection 4 on the metabase production environment.)
Leaving ticket open whilst we wait for the production insights app so I can record a full demo end to end rather than calling swagger
