### ISSUE TITLE
Update lambda migration routine to work with third party API agnostic of product API

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#4011]
**Background context**
At the point that a Reapit customer is migrated to RC, we perform a lazy migration routine to ensure that the user can retain their existing password and credentials. In this step, we provide username and password to a third party API (now SUMS) to validate creds/user identity before populating them into RC.

**Specification**
- Understand if we can identity the application id that a user has attempted to log in via
- Update RC to call out to an endpoint agnostic of source
- Will require a new architectural layer in the migration service (not new infrastructure)
- Layer will sit between third party IDP APIs and the migration lambda to abstract away implementation
- To be responsible for directing traffic to the right API based on applicationId

**Comment by plittlewood-rpt** [comment]
PR 3943 opened
