### ISSUE TITLE
Provide Typescript definitions for Webhook payload

### ISSUE THREAD

**Issue by shaneosullivan** [reapit/foundations#4013]
**Is your feature request related to a problem? Please describe.**
When consuming webhooks in Node, it is currently required to use the "ping" feature and record the resulting payload as examples to build off of. 

**Describe the solution you'd like**
It would be better to have well defined Typescript definitions for each of the payload types, so we do not have to write them ourselves.

**Describe alternatives you've considered**
I've looked at each of the example webhook payloads from the "ping" tool and written my own Typescript types. These may or may not be accurate, as they are each based off a single example payload, which as far as I know could have multiple different shapes.  However there is no way to tell currently as the docs are not comprehensive, so I'll find out when a partner causes a bug live in my production.

**Additional context**
None

**Comment by willmcvay** [comment]
Hi @shaneosullivan see: https://foundations-documentation.reapit.cloud/api/webhooks#example-payload our webhooks post the same object interface as per the existing definitions i.e. for the contacts.modified webhook, the old and new keys will be a ContactModel, in the ts-definitions package. This would apply to all entities i.e. property.created would be PropertyModel and so on.

For the webhook payload itself and for the couple of webhooks not part of the platform eg application.install, happy to add this to the backlog and we'll look at providing definitions in the future. For now, hopefully you should be able to construct your own interface from the docs.

**Comment by shaneosullivan** [comment]
Thanks - I'm using this for now:

```

export type ReapitTopic =
  | "contacts.modified"
  | "contacts.created"
  | "contacts.modified"
  | "landlords.created"
  | "landlords.modified"
  | "propertyimages.created"
  | "propertyimages.modified"
  | "properties.created"
  | "companies.created"
  | "companies.modified"
  | "application.install"
  | "application.uninstall";

export interface ReapitPayload {
  eventId: string;
  entityId: string;
  customerId: string;
  eventTime: string; // ISO8601
  topicId: ReapitTopic;
}

// This is not included in Reapit's Typescript definitions for some reason.
interface ReapitApplicationModel {
  customerId: string;
  customerName: string;
  applicationId: string;
  applicationName: string;
  customerAddress: AddressModel;
  customerEmail: string;
  organisationId: string;
}

export interface ReapitCompanyCreatedPayload extends ReapitPayload {
  new?: CompanyModel;
}

export interface ReapitCompanyModifiedPayload
  extends ReapitCompanyCreatedPayload {
  old?: CompanyModel;
}

export interface ReapitContactCreatedPayload extends ReapitPayload {
  new?: ContactModel;
}

export interface ReapitContactModifiedPayload
  extends ReapitContactCreatedPayload {
  old?: ContactModel;
}

export interface ReapitLandlordCreatedPayload extends ReapitPayload {
  new?: LandlordModel;
}

export interface ReapitLandlordModifiedPayload
  extends ReapitLandlordCreatedPayload {
  old?: LandlordModel;
}

export interface ReapitPropertyImageCreatedPayload extends ReapitPayload {
  new?: PropertyImageModel;
}

export interface ReapitPropertyImageModifiedPayload
  extends ReapitPropertyImageCreatedPayload {
  old?: PropertyImageModel;
}

export interface ReapitPropertyCreatedPayload extends ReapitPayload {
  new?: PropertyModel;
}

export interface ReapitPropertyModifiedPayload
  extends ReapitPropertyCreatedPayload {
  old?: PropertyModel;
}

export interface ReapitApplicationInstalledPayload extends ReapitPayload {
  new?: ReapitApplicationModel;
}

export interface ReapitApplicationUninstalledPayload
  extends ReapitApplicationInstalledPayload {
  // The uninstalled payloard also uses "new", unlike the Modified interfaces
}

```
