### ISSUE TITLE
Microservice template tweaks required

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#4015]
**Background context**
Upon recent usage of the serverless microservice template, it was noted that we experienced a couple of problems.

**Specification**
- gitignore file not being copied into correct location
- PR template isn't included (include to use the one CB wrote  W/C 15/04)
- Included Test project spun up as a regular web API project
- Moq reference in test project is missing
- ~Invalid json in launch settings (missing curly brace at end of file)~

**Comment by plittlewood-rpt** [comment]
PR 3854 opened
