### ISSUE TITLE
Configuration endpoint failure for specific customer

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#4020]
**Background context**

For customer RUS, an error occurs when attempting to fetch appointmentTypes. This looks to be data related, we but we should look to handle this situation more gracefully. 

![image](https://user-images.githubusercontent.com/34191069/115685282-fe5a3280-a34f-11eb-8598-9d16d5614b24.png)

**Specification** 
- When encountering a duplicate key, do not throw an error in this way
- Instead, take the default entry rather than configured additional entry
- Tests to assert this behaviour
- Should be across the board for all config types that are additive 
- Ensure same logic applies for the Get By ID endpoint equivalent

**Comment by plittlewood-rpt** [comment]
PR 3866 opened to update package where the problem lies.

**Comment by plittlewood-rpt** [comment]
PR 3870 opened
