### ISSUE TITLE
POST Works order without a NegotiatorId 

### ISSUE THREAD

**Issue by TomFixflo** [reapit/foundations#4023]
**Is your feature request related to a problem? Please describe.**

Fixflo allows tenants/occupiers to report maintenance issues themselves, without a negotiator/agent acting as an intermediary.
 
We want Reapit users to have visibility of that Fixflo issue as a works order as soon as it is raised. 
We use the POSTWorksOrders endpoint 
BUT this falls over because at this stage in the process there is no negotiator associated with the works order and 'NegotiatorId' is a required field. 

**Describe the solution you'd like**

Allow works orders to be posted without a NegotiatorId 
OR provide a 'System default' Id we can use for all clients to post works orders before they are assigned a negotiator. 

**Describe alternatives you've considered**

Create works orders later --> this means the negotiator will not have visibility of the maintenance issue raised in Fixflo until it is manually assigned --> suboptimal.

**Comment by cbryanreapit** [comment]
Need to understand the downstream impact of doing this in terms of AC

**Comment by TomFixflo** [comment]
Hi,

I was wondering if there was any update on this? 

Thanks, 

Tom
