### ISSUE TITLE
Request for PSRA semi structured office field

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#4027]
**Request**
- Sherry Fitzgerald for PSRA license number in office semi structured
![image](https://user-images.githubusercontent.com/34191069/115764914-08a31d80-a39e-11eb-939c-312a0879e619.png)

**Comment by cbryanreapit** [comment]
Blocked by https://github.com/reapit/foundations/issues/4041 for now

**Comment by plittlewood-rpt** [comment]
Have let the original requestor know what query string parameters to pass via email
