### ISSUE TITLE
End to end testing of bulk data indexing modifications

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#4036]
**Background context**
We should test this process end to end with DXX in our development environment.

**Specification**
- Check that emails are fired off as appropriate
- Check that the data moves in expected fashion
- Check that pipeline is created and turned on at appropriate time

**Comment by plittlewood-rpt** [comment]
Had to set up another customer account as the cluster naming convention for the DXX/Sandbox databases in Dev does not sit correctly with the CF template
