### ISSUE TITLE
Retrieve Staff associated to a Company

### ISSUE THREAD

**Issue by nbdesignstudio** [reapit/foundations#4056]
**Is your feature request related to a problem? Please describe.**
When a Company is selling a property rather than Contact, we can see the Staff linked to the Company within the Reapit Desktop App. But we are unable to retrieve them via the API. 

**Describe the solution you'd like**
Either using the existing /Company/ID/Relationships, or the preferred options of a new /Company/ID/Staff method be able to retrieve the Staff associated with a Company that own/is selling a property

**Describe alternatives you've considered**
There do not appear to be suitable alternatives. As the only alternative is some manual entry text fields, for the RPS user to input the data, but this manual entry would NOT be then connected to either a 'Company' or a 'Contact' within RPS.

**Additional context**
![Company_Staff](https://user-images.githubusercontent.com/24694998/116265324-f1d04280-a772-11eb-9ee4-a89af369035e.png)

We would like to access Fiona Brick and Simon from the Staff list for example...

**Specification**
- Provide `GET /companies/{id}/staffMembers` endpoint 
- First iteration of this functionality will be read only, no write back
- Contract as below
```
[
   {
     "name" : "Mr John Smith"
     "active" : true,
     "jobTitle" : "Managing Director",
     "workPhone": "0121 331123",
     "mobilePhone": "07890 123456",
     "email": "example@email.com",
   },
   {
      ...
   }
]
```
- Some staff members correspond to a full contact record, some do not. For the cases where a full contact record is available, include a `contact` link in the `_links` collection
- Populate same contract regardless of whether staff member is semi structured or a fully fledged contact
- `staffMembers` is not a required field in AgencyCloud so may not always be populated

**Comment by plittlewood-rpt** [comment]
This has been raised by another party now - we should discuss in a bit more detail and re-review

**Comment by nbdesignstudio** [comment]
That is good news. If there is anything we can help with in our request, please advise @plittlewood-rpt
