### ISSUE TITLE
Provide managed process to migrate Reapit internal users to Reapit Connect

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#4062]
**Background context**
We should turn on RC migration for internal Reapit staff members. This is a potential impactful operation so due care and process must be laid out.

**Specification**
- Build a internal email address whitelist that the migration code respects when encountering a Reapit user (@reapit.com?)
- Ensure whitelist is respected when lambda migration runs to allow us to granularly control a subset of users who get RC internally
- Once proven, we'll want to turn this on across the board for all Reapit users, the whitelist/behaviour will need to respect that
- The migration code itself will need to be able to identity Reapit users and assign them to the correct org/user groups on migration

**Comment by plittlewood-rpt** [comment]
PR 3934 opened to update migration routine

**Comment by plittlewood-rpt** [comment]
Have tested this in the dev environment and it seems to work as intended. Need to highlight a subset of staff to migrate over. Will do this under a new ticket
