### ISSUE TITLE
Add the LongDescription field to the property feed in Reapit PaaS for Acorn Group

### ISSUE THREAD

**Issue by msumanthraj** [reapit/foundations#4063]
- The long description field needs to be added to the Reapit PaaS for the Acorn Group in the data feed in Reapit PaaS 
- Client ID is 'ACR'

**Comment by msumanthraj** [comment]
[
[reapit id - WEL211191.txt](https://github.com/reapit/foundations/files/6390699/reapit.id.-.WEL211191.txt)
](url)

**Comment by cbryanreapit** [comment]
This is a duplicate, please track: https://github.com/reapit/foundations/issues/4044
