### ISSUE TITLE
Remove group management functionality from organisation user update

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#4064]
**Background context**
Presently, user group membership can be managed using the PUT endpoint as well as a dedicated group management endpoint. We should remove the group management component from this endpoint and rely on the dedicated endpoint

**Specification**
- Remove from PUT payload
- Update calling parties to use the group management endpoint instead (eg. SUMS proxy)
- Keep POST users, fine for this to remain
- Ensure marketplace management app is updated prior to this change (may not be required)

**Comment by plittlewood-rpt** [comment]
PR 3935 opened to remove functionality from internal user management service

**Comment by plittlewood-rpt** [comment]
PR 3936 opened to update NuGet package required by internal proxy

**Comment by plittlewood-rpt** [comment]
PR 3937 opened to update internal proxy which is the only other service using the deprecated mechanism

**Comment by plittlewood-rpt** [comment]
This is now blocked by #4094  - I have tested the internal proxy which works fine in terms of group membership changes but normal user updates fail due to the requirement in the current iteration of the user management service that all users must be associated with at least one group
