### ISSUE TITLE
Allow generic user and organisation claims to be captured in Reapit Connect

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#4066]
**Background context**
We should allow claims to be captured in Reapit Connect to allow integrating Reapit products to surface / capture any information they choose to about their customers. 

**Specification**
- Add user and organisation claims endpoints required to manage this feature
- Capture/surface created, modified, id, claim, value, includeInToken
- Ensure that we can update a claim without looking up it's ID first (composite/natural key?)
- Claim names to be acceptable to Cognito (length etc)
- Need to ensure we don't allow for more claims than cognito can handle

**Comment by plittlewood-rpt** [comment]
PR 3938 opened
