### ISSUE TITLE
Augment identity tokens with information held in new organisation claims mechanism

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#4068]
**Background context**
We are building a generic way of capturing information about users and organisations - some of which can optionally be surfaced into identity tokens. 

**Specification**
- Where a user claim has been set up for X user, include it in the id token if the 'includeInToken' flag is true
- Where a organisation claim has been added to a users company, also include it in the id token if the 'includeInToken' flag is true

**Comment by plittlewood-rpt** [comment]
Cannot be actioned until #4066  is signed off (currently in PR) as the updated models need to go into one of the packages that the token generation routine uses

**Comment by plittlewood-rpt** [comment]
PR 4043 opened
