### ISSUE TITLE
Migrate Agency Cloud Reapit Connect users/organisations to use new generic claims mechanism

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#4069]
**Background context**
To ensure RC is agnostic of product for other Reapit companies, we should use the claims mechanism as the means of surfacing AC specifics

**Specification**
- Build migration routine to copy AC specifics into user/org claims
- Update token generation routines to check new location for these fields (and no longer check the old location)
- Update any service interacting with RC to work with claims mechanism to update user/org claims (SUMS migration etc, SUMS Proxy).
- The 'override' customer ID functionality needs special care

**Comment by plittlewood-rpt** [comment]
PR 4048 opened
