### ISSUE TITLE
Return exchanged information in properties endpoint

### ISSUE THREAD

**Issue by frankdillon85** [reapit/foundations#4076]
**Is your feature request related to a problem? Please describe.**
We are currently in the process of updating an existing project to use the API. The project is reliant on using the exchprice and exchoffcode fields which is not returned by the API.

**Describe the solution you'd like**
Return the exchanged price and exchanged office code in the selling object of the GET /Properties endpoint?

**Specification**
- Add `selling.exchangedPrice` and `selling.exchangedOfficeId` fields to `GET /properties` and `GET /properties/{id}` payload
- Read only at this stage
- Data location is `ExchPrice` and `ExchOffCode`

**Comment by plittlewood-rpt** [comment]
PR 4014 opened
