### ISSUE TITLE
Address search on both vendor and associated property record

### ISSUE THREAD

**Issue by nroper** [reapit/foundations#4079]
**Is your feature request related to a problem? Please describe.**
We are trying to implement a form that will allow a user to carry out an address search that covers both vendors and the associated property.  This is not currently possible in a single request.

**Describe the solution you'd like**
An endpoint, or option on existing endpoint, to include both the vendor's address and associated property address when carrying out an address search.

**Describe alternatives you've considered**
As suggested by support, we have tried using 2 requests - one against the `/vendors/?address={text}` endpoint and one against the `/properties/?address={text}` endpoint and then 'joining' these together.  

In order to ensure that we capture all related information we also need to embed vendor data into the properties results and vice-versa, so `/vendors/?address={text}&embed=property` and `/properties/?address={text}&embed=vendor`.

We then need to related the data sets together and de-dupe any common results.

This is making what would be a simple operation with an SQL join into a fairly complex operation that requires multiple requests.

**Additional context**

**Comment by cbryanreapit** [comment]
We consider properties and vendors as two different concepts and as such, they're handled separately. As such we have no plans to implement this feature at present time - recommend you continue to search for each independent entity as you've described.
