### ISSUE TITLE
Table component requires additional work

### ISSUE THREAD

**Issue by willmcvay** [reapit/foundations#4089]
**Background context or User story:**

_See https://github.com/reapit/foundations/pull/4081 there are a couple of outstanding issue on this PR to resolve_

**Specification or Acceptance Criteria:**

Specifically from the comments:

```
Things not covered by this PR that might be useful or needed to use the table in prod

The expandable row doesn't currently animate
There aren any tests for the molecule components and not very thorough tests for the Table as a whole
In the design one of the cells has a little status circle
A prop or setting to allow a different order of cells on the narrow table view
Modifiers for the TableHeader to allow it show show as ASC or DESC arrow
Adding more breakpoints in, and allowing a configurable breakpoint (currently it's hard-set at <750px for narrow view)
And a possible refactor

Perhaps TableCell shouldn't be supporting the special darkText prop and instead just make that the responsibility of the children it renders. E.g. it could just render something like <p className="dark-text">... which would reduce the complexity on TableCell (same thing could be done for the little status circles)
```

- The refactor suggestion looks to be the best way of dealing with the dark text and status circles
- Sorting and breakpoints we can leave as out of scope fow now
- Tests and animations are the most important tasks

**Comment by bashleigh** [comment]
[ ] The expandable row doesn't currently animate
[ ] There aren any tests for the molecule components and not very thorough tests for the Table as a whole
[ ] In the design one of the cells has a little status circle
[ ] A prop or setting to allow a different order of cells on the narrow table view
[ ] Modifiers for the TableHeader to allow it show show as ASC or DESC arrow
[ ] Adding more breakpoints in, and allowing a configurable breakpoint (currently it's hard-set at <750px for narrow view)
And a possible refactor

[ ] Perhaps TableCell shouldn't be supporting the special darkText prop and instead just make that the responsibility of the children it renders. E.g. it could just render something like <p className="dark-text">... which would reduce the complexity on TableCell (same thing could be done for the little status circles)
