### ISSUE TITLE
Add missing SMS buttons onto the search screens where it's missing

### ISSUE THREAD

**Issue by bradkieser** [reapit/foundations#4103]
The Reapit search results have the SMS button implemented on only 2 searches, whereas the email button is on all of them. Many clients are requesting that the SMS button is put in where it is currently missing.

The pop-up is the same across all the results, just that the SMS option is missing.

Here is the list:

- Applicant: Present
- Property: Present
- Tenants: Missing
- Landlord: Missing
- Contact: Missing

Further details can be seen here with a full write-up and screenshots: https://drive.google.com/file/d/1ahRPRzvD4MNahombzJP6x2cfP4UhqSQq/view

**Comment by HollyJoyPhillips** [comment]
@bradkieser I believe this has now been resolved and no longer needed, therefore will close the ticket. If it is, please feel free to comment.
