### ISSUE TITLE
Investigate an image corruption issue

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#4108]
Issue with image conversion. Details TBC

**Comment by plittlewood-rpt** [comment]
Related to PHP bug mentioned here: https://bugs.php.net/bug.php?id=75910

In summary, using a base64-encode stream filter when reading a file can result in the EOF marker being stripped from the output. When PHP tries to read a file that has been saved from an affected base64 string, it cannot do so:

```
stream_filter_append($stream, "convert.base64-encode");
```

Workaround for now is to use `base64_encode()` instead.
