### ISSUE TITLE
Allow access to Archived Contacts

### ISSUE THREAD

**Issue by stebrough** [reapit/foundations#4121]
**Is your feature request related to a problem? Please describe.**
Yes, our client wants to be able to market to Archived Contacts through our system. They have circa 90k archived contacts so a substantial set of potential repeat business.

**Describe the solution you'd like**
A way to access Archived Contacts via the Contacts endpoint of the API.

**Describe alternatives you've considered**
There doesn't seem to be any available.

**Additional context**
The client has a large number of contacts archived, it is important to them to be able to market to this contact base, rather than just leave this number of contacts to languish and not be able to access and utilise the data.

**Comment by cbryanreapit** [comment]
For internal discussion

**Comment by cbryanreapit** [comment]
Superceded by https://github.com/reapit/foundations/issues/4176 - please track this issue instead
