### ISSUE TITLE
BER fields required for our Client - EDD

### ISSUE THREAD

**Issue by markdarcyleacam** [reapit/foundations#4122]
**Request**

In order for us to grant access to Semi-structured 'extras' field data, please provide the following information in this request:

- Customer - Ed Dempsey & Associates (EDD)
- Fields - ALL BER related fields (BER Exempt, BER Rating, BER Number, Energy Performance Indicator) 
- ![image](https://user-images.githubusercontent.com/73422378/117662068-0f4fd400-b197-11eb-8ac1-aa6c94337306.png)
- Use case - we are building a new website for our Client. It is against regulations to advertise a property for sale in Ireland without BER information included.

**Comment by plittlewood-rpt** [comment]
Hi @markdarcyleacam 

Please see below the `extrasField` query string parameter values you can now include with your request to retrieve the BER information for Ed Dempsey & Associates:

BER Exempt -> pBERExempt
BER Rating -> pBERRating
BER Number -> pBERNumber
Energy Performance Indicator -> pEPI

As an example, to return all the above fields (where present), you would append the following to your GET request URI:
?extrasField=pBERRating&extrasField=pBERNumber&extrasField=pEPI&extrasField=pBERExempt

Any problems please let me know.

Thanks
