### ISSUE TITLE
GraphQL generation from swagger doc download

### ISSUE THREAD

**Issue by bashleigh** [reapit/foundations#4142]
**Is your feature request related to a problem? Please describe.**

#3940 After researching different possible methods the only method that seems viable to produce an exact schema to the TS definitions would be to build our own TS compiler to convert the AST to a graphQL schema.

**Describe the solution you'd like**
Use the TSC to generate the available graphQL schema

**Describe alternatives you've considered**
We've tried both `swagger-to-graphql` and `type-graphql` packages to generate types from both swagger and ts-definitions. `type-graphql` meant writing each interface as a class and applying decorators to both classes and properties which was time consuming and also would mean having to manually maintain these classes and decorator values. `swagger-to-graphql` resulted in error due to none typed swagger documentation or impossible types such as `_embedded` and `_links` which should be scalars

**Comment by willmcvay** [comment]
This looks very promising with a wrapper around it https://github.com/grantila/typeconv had some issues installing in the mono repo so didn't have the time to pursue but on an external repo, gives us 90% of what we need.

**Comment by bashleigh** [comment]
Does appear that typeconv will be an easy fix. After doing some digging I've come up with the following possible solutions to the problem.

The problem: _embedded values are not supplied by swagger resulting in the types not being provided. 

1. Ask the swagger dev to add these values for all missing types
2. Manually add the types to the JSON returned from the swagger response
3. Force the foundations ts package to merge existing types and generated types (meaning we can add _embedded manually to TS)
4. Add to missing types to graphql after it has been generated

**Comment by willmcvay** [comment]
As discussed, think we can use the WarnFunction here https://github.com/grantila/core-types-ts#typescript-to-core-types so whenever typeconv hits an "any" type or similar, we can re-name it using a regex pattern, as opposed to using the generic type generated by the lib. Also, we will likely have to define the embedded types ourselves and look to merge them in at parse time. Lots to do here but I think it's achievable
