### ISSUE TITLE
Bulk indexer service production enhancements

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#4153]
**Background context**
We should ensure this service is ready to be handed over to SI

- [x] Ensure service added to gateway 
- [x] Standard access token requirement enforced
- [x] Replicate the mechanisms in place for other services that aren't customer centric
- [x] cdcCloudformationRole IAM role needs ModifyReplicationTask permissions (CF template)
- [x] ~~We need to check whether or not we are retrying throttled requests. I noticed on smaller databases where the APIs respond very very quickly that write requests were being throttled which means there'll be gaps in the data being indexed. Larger databases where API response times are slightly longer don't have this problem. To recreate this, kick off an indexing task on a couple of small databases and monitor the table write metrics - it looks like the SDK handles this scenario for us as we aren't getting exceptions back to the application (see https://github.com/aws/aws-sdk-net/issues/623)~~

**Comment by plittlewood-rpt** [comment]
PR 4060 opened to allow more generalised handling of apps that do not use the main domain service (typically internal apps, agencycloud, marketplace etc) in the gateway authorizer which is a requirement to be able to put the bulk indexer on the gateway

**Comment by plittlewood-rpt** [comment]
This ticket is just waiting on the PR above now the final point has been looked into
