### ISSUE TITLE
Deep dive of working of Certificates in Agency Cloud

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#4158]
**Background context**
We should deep dive this functionality so that we can best know how to apply the proposed new API/fields into the platform.

**Specification**
- Understand data source(s) and propose solution(s) to how certificates are presented (speak to CB)
- Create tickets to implement this functionality

**Comment by StuartLaw99** [comment]
Would be good to have a web hook that only fired on update and create of these as well as an API call to get a delta list of created and amended since x.

**Comment by plittlewood-rpt** [comment]
Dive completed - circulated document outlining suggested implementation. Further tickets to follow

**Comment by plittlewood-rpt** [comment]
Closing ticket - have put something in calendar to confirm implementation for next week
