### ISSUE TITLE
Negotiator Appointment and Availability Calendar

### ISSUE THREAD

**Issue by Shabaristarberry** [reapit/foundations#4195]
Hi

We would want to access the negotiator availability and appointment data to display it on the web application that is in development for 10 of our mutual clients. We did have access to this data in the SOAP and REST calls and we cant find the correct API in PAAS to import the data we need.

Give below the API calls that we used

**GetNegotiatorAvailability**
Returns a list of available diary appointments for the negotiator identified by the ID parameter between the times specified in the From and To parameters, over a maximum 14 day period. 
The duration (in minutes) of the required appointment can be specified using the Duration argument and the required time between appointments using the Interlude parameter.

**GetValuationAppointments**
Returns a list of available diary appointments for the supplied postcode between the times specified in the From and To parameters. 
The duration (in minutes) of the required appointment can be specified using the Duration argument and the required time between appointments using the Interlude parameter. 
'Sales' or 'Lettings' can be specified in the ValuationType argument.

**GetViewingAppointments**
Returns a list of available diary appointments for the supplied PropertyID between the times specified in the From and To parameters. 
The duration (in minutes) of the required appointment can be specified using the Duration argument and the required time between appointments using the Interlude parameter.

Could you please have a look and let us know how we can get access to these data in PAAS

Thanks
Shabari

**Comment by plittlewood-rpt** [comment]
Hi @Shabaristarberry 

We will look at doing an investigation into how feasible this will be to include in the platform. I have logged a separate ticket #4235 to complete an initial investigation, after which we will be able to comment further

Thanks
Pete

**Comment by HollyJoyPhillips** [comment]
Hi @Shabaristarberry, 

Whilst this is a valid feature request, it's not a feature we will be able to implement in with our current Roadmap capacity. 

We will move the ticket to our Long Term backlog as we cannot commit to when or if this would be something implemented into the Platform. 

Thanks
Holly
