### ISSUE TITLE
Add 'Buying Position', 'Buying Reason', 'Selling Position' and 'Selling Status' fields to Applicant endpoints

### ISSUE THREAD

**Issue by stebrough** [reapit/foundations#4199]
**Is your feature request related to a problem? Please describe.**
Our clients want to market to applicants in specific positions etc. We have a number of large clients wanting these fields.

**Describe the solution you'd like**
Add 'Buying Position', 'Buying Reason', 'Selling Position' and 'Selling Status' fields to Applicant endpoints

**Describe alternatives you've considered**
None available

**Additional context**
None available

**Specification**
- Fields work as follows: 
- `buying.reason` (configurable)
- `buying.position` (configurable)
- `renting.position` (configurable)
- `sellingStatus` (standard options)
- `sellingPosition` (standard options)
- Configurable values will require an accompanying configuration endpoint to express meaning of data
- Update applicant broker to call out to the relevant configuration service endpoints. It should pass a sensible header through to the applicants service which will then have a view of what the configuration looks like, and can use that to split the app.position field up into the various model components
- Update applicants service to check for and use the new header (or headers) to determine which parts of the app.position field should be exposed in each new model property

**Comment by cbryanreapit** [comment]
To re-review in next planning

**Comment by cbryanreapit** [comment]
Original specification doesn't include all required work - configuration endpoints need to be included. Further specification to be added.

**Comment by cbryanreapit** [comment]
To be broken down into smaller tickets

**Comment by plittlewood-rpt** [comment]
See analysis in #5064 for summary of configuration across the estate. This needs to come into how we architect this mechanism

**Comment by plittlewood-rpt** [comment]
This is a complex ticket that was added late to sprint 38 and is so carrying over to sprint 39, next week

**Comment by plittlewood-rpt** [comment]
Carrying over to next sprint - we cannot merge this work in until some other pre requisites are completed

**Comment by plittlewood-rpt** [comment]
Hi @stebrough - the work to expose this information in the applicants API has been completed, however there is some other prerequisite work that needs to be completed before we can release the change so it will be a little longer before this goes out. I'm going to close this particular ticket, and would ask you to track the two tickets above. Once they are done we'll be able to release the updated applicant endpoints.
