### ISSUE TITLE
AML (Online Check List) and Companies

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#4201]
**Summary**

_The AML app should allow identity checking of companies as well as contacts_

**Spec**

- When landing on the `/checklist-detail/:id` route, the app should initially attempt to retrieve a contact record using the `/contacts/:id` endpoint
- If the record is not found (404), we should check if the id is a company record instead by calling `/companies/:id`
- If a company record is returned, the id check should progress as normal however, rather than updating the contact endpoint, we should update the company record instead
- All other behaviours as per a contact id check

**Comment by willmcvay** [comment]
As discussed @HollyJoyPhillips needs some more scoping as definitely a non-trivial task
