### ISSUE TITLE
dateOfBirth value missing from related or embedded Contacts within a Vendor or Property API Call

### ISSUE THREAD

**Issue by nbdesignstudio** [reapit/foundations#4207]
**Is your feature request related to a problem? Please describe.**
The dateOfBirth value for related Contacts or embedded Contacts in a Vendor or Property API call is missing.

**Describe the solution you'd like**
As all other Contact values are available within the related Contact or embedded Contacts options, other than the dateOfBirth we presume this is an accidental oversight

**Describe alternatives you've considered**
The only other option seems to be to make an additional API call to the get the full Contact data, but as this dateOfBirth value appears to be the only value missing from the related or _embedded Contacts calls, it seems unnecessary to have to make a direct call to the Contact API method to get this one value.

**Additional context**
Maybe it is just us, but using your 'embed' endpoint functionality appeared to mean that we could make metaphorical 'joins' like in a normal database query but between endpoints, so that it would negate the need to make as many API calls to each individual endpoint to retrieve data. 

Also the amount of extra data that would be pulled especially for supplying a full set of Contact data when linked via Vendor or Property endpoints seems negligible and would mean less API calls needing to be made by your users

**Specification**
- Update GET endpoints for following services `related` response: Vendors, Applicants, Landlords, Tenancies, Offers
- Include `dateOfBirth` field in related contacts payload
- Do not populate when `type` is company (irrelevant field in this case)

**Comment by plittlewood-rpt** [comment]
Hi @nbdesignstudio 

Thanks for logging the feature request – we’ll see if we can support that when we review it.

When you mention the ‘embed’ functionality, can you just confirm for me what you’ve tried or what you’ve referring to as you can’t opt to embed contact data in the properties/vendors API responses (you just get the related collection back in the vendor endpoint)

Also can you let me know your use case for the dateOfBirth field? That might just help us evaluate better whether or not it's appropriate to include it in our summary models returned from those endpoints.

**Comment by nbdesignstudio** [comment]
We have tried pulling using the Property endpoint and embedding the Vendor so that it pulls the Vendor details, and this is missing the DOB.

We have tried pulled via the Vendor endpoint, and this already pulls in the related Contact data, but again is missing the DOB.

The Applicant endpoint has the same issue as the Vendor one, as this already pulls in the related Contact data, but again is missing the DOB.

I guess the alternatives are:

• Add DOB to the above 'related' data?
• Allow the Contact endpoint to be _embedded to either the Property or Vendor endpoints? I would guess the Vendor endpoint would be most appropriate?

Is there another option we have missed @plittlewood-rpt? without having to make a separate call to the Contact endpoint?

**Comment by plittlewood-rpt** [comment]
@nbdesignstudio There's no alternative at the moment unfortunately. When you use the embed option it embeds the content returned from the respective service (so if you choose to embed the vendor in the property response, it embeds the data returned from /vendors/{id} for the respective property which is why you don't see the dateOfBirth field when using that approach either.

Depending on the volume of data and how your app is going to receive it's data, you can get up to 100 (limited by max page size) specific contacts in one go from `GET /contacts` by using the `id` query string parameter, which would reduce the number of calls you were making. For example if you've got 3 vendors each with a single related contact to process you can hit `GET /contacts?id=XXX21000001&id=XXX21000002&id=XXX21000003` to return those three specific contacts in a single request.

**Comment by plittlewood-rpt** [comment]
@nbdesignstudio We need to review this one further. It will probably be next week when we can advise.

**Comment by nbdesignstudio** [comment]
Ok thank you. We look forward to a response.

**Comment by nbdesignstudio** [comment]
@plittlewood-rpt Is there any news on this request at all?

**Comment by plittlewood-rpt** [comment]
Hi @nbdesignstudio  we have a refinement session tomorrow where this will be discussed so we should be able to come back to you with an update then.

**Comment by nbdesignstudio** [comment]
Great news. Thank you.
