### ISSUE TITLE
Reapit Connect Incompatible with iOS Applications

### ISSUE THREAD

**Issue by CAppleton-Reapit** [reapit/foundations#423]
When trying to use Reapit Connect the currently supported URI types (https or http://localhost) are not compatible with how iOS applications expect applications to be launched.

The iOS apps have a registered scheme value that allows the app to be launched from a browser, this cannot start with either of the accepted URI types (along with a few others: see the link at the bottom of this issue).

The app registration would need to allow for free text URI values, or another agreed upon prefix for iOS applications. 

https://developer.apple.com/documentation/uikit/inter-process_communication/allowing_apps_and_websites_to_link_to_your_content/defining_a_custom_url_scheme_for_your_app

**Comment by cbryanreapit** [comment]
Broken into 2 tickets:

https://github.com/reapit/foundations/issues/431
https://github.com/reapit/foundations/issues/429
