### ISSUE TITLE
Create a pending approval supplier invoice

### ISSUE THREAD

**Issue by MatthewGoddard** [reapit/foundations#4248]
**Is your feature request related to a problem? Please describe.**
I would like to be able to add a supplier invoice that a property manager can then review.

**Describe the solution you'd like**
A single API end point that I can POST a new supplier invoice to with the status of awaiting approval.

**Describe alternatives you've considered**
Property Managers carry on doing this manually via the New Supplier Invoice screen in Reapit's AgencyCloud product.

**Additional context**
![image](https://user-images.githubusercontent.com/10115484/119784676-5b548580-bec6-11eb-81bf-1309703a6c5e.png)

**Comment by TomFixflo** [comment]
@HollyJoyPhillips @cbryanreapit Perhaps this can be merged with me issue #3826 ? Thanks

**Comment by ray-niptech** [comment]
I agree this ticket could be merged with 3826 as long as all types of invoices are handled not just work orders

**Comment by Julianstirlingackroyd** [comment]
Update please?

**Comment by HollyJoyPhillips** [comment]
@Julianstirlingackroyd As the auto reply indicates, we are unable to commit to the work required to implement this request at the moment. Therefore, we have moved your request to our Long Term column. The work requires development associated to account and transactional data which is not currently exposed via Platform. As we have similar tickets raised, we have now created an epic that you can follow here https://github.com/reapit/foundations/issues/6322. As an when are in a position to re review this, you will be automatically updated.
