### ISSUE TITLE
Issues with the Marketplace in Firefox 

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#425]
**Summary:** Please see below various issues and errors that are occurring in the Developer Portal  using Firefox 

**Browser Version:** V 70.0.1 

**Location:** https://dev.marketplace.reapit.cloud/developer/apps
**Issue:** No icon image appearing on App tiles
**Steps to replicate:** Navigate to 'Apps' in the developer portal 
![image](https://user-images.githubusercontent.com/52408607/75148135-d133d500-56f6-11ea-9a03-989e58affdec.png)

**Issue:** No screenshot or icon images appearing on app modal
**Steps to replicate:** Open any app from 'Apps'
![image](https://user-images.githubusercontent.com/52408607/75148158-ddb82d80-56f6-11ea-8bbb-d5612019be29.png)

**Location:** https://dev.marketplace.reapit.cloud/developer/swagger
**Issue:** Error in the console when loading the page
**Steps to replicate:** Navigate to 'API' in the developers portal 
![image](https://user-images.githubusercontent.com/52408607/75148295-37b8f300-56f7-11ea-9d33-683074520411.png)

**Issue:** Further errors when trying to execute a query
**Steps to replicate:** Collapse endpoint 'Appointments' > click 'Try it out' > click on 'Execute' 
![image](https://user-images.githubusercontent.com/52408607/75148311-42738800-56f7-11ea-90cf-75a3faa2d1e5.png)

**Location:** https://dev.marketplace.reapit.cloud/developer/help 
**Issue:** Live Chat 'Start Chat' widget fails to load 
**Steps to replicate:** Navigate to the 'Help' page, click on 'Start Chat' in the 'Need Help?' section 
![image](https://user-images.githubusercontent.com/52408607/75148380-5fa85680-56f7-11ea-9ccd-5a8a04c859e3.png)

**Location:** https://dev.marketplace.reapit.cloud/developer/submit-app 
**Issue:** Unable to submit an app
**Steps to replicate:** Navigate to 'Submit App' page, fill in the form and try to 'Submit' 
![image](https://user-images.githubusercontent.com/52408607/75148464-9d0ce400-56f7-11ea-8060-8639e8f5ba1c.png)

**Comment by phmngocnghia** [comment]
@HollyJoyPhillips I have tested the bugs against same Firefox version above. Except the warnings which don't interrupt the request, I couldn't reproduce the bugs. Maybe there's a deployment issue while testing causing the behaviour as above.

**Comment by HollyJoyPhillips** [comment]
@phmngocnghia You are right, I've uninstalled and reinstalled and it's working perfectly fine. Thanks for looking, will close the ticket.
