### ISSUE TITLE
Customer Billing - Developer Portal 

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#4256]
**Summary**: Customer organisations should not be charged for the Developer Edition of Agency Cloud. 

We should remove the subscription charge for the Developer Edition of AC. 

- Applies to any users that is a member of a customer organisation
- Set subscription to 0 

**Specification**
- When creating a subscription to Developer Edition, detect if user belongs to a customer organisation 
- If so, alter the cost in the notification we emit to the billing service to send a zero cost
- We will also need to adjust any existing subscriptions in the appropriate table (there are only a few) once this change goes out as it will not retrospectively update existing active subscriptions

**Comment by cbryanreapit** [comment]
Review

**Comment by HollyJoyPhillips** [comment]
Reopened as now required
