### ISSUE TITLE
Metadata like field available between developers

### ISSUE THREAD

**Issue by Daramithes** [reapit/foundations#4267]
**Is your feature request related to a problem? Please describe.**
Our company uses a mix of external, and internal developers to develop apps for PaaS. At the moment, there doesn't seem to be a way to allow one developer to create a custom field, and have this accessible through Reapit by the other developer.

**Describe the solution you'd like**
I would like a solution that acts pretty much the way Metadata does at the current moment, but instead of being specific to the developer, have it accessable by any developer. 

**Describe alternatives you've considered**
At present, we are having to allow our third party developer to register the application in order for them to access our metadata, however this really isn't ideal as it complicates how we will be using the data in the future along with several other issues.

We have considered creating API's ourselves which will allow us and the third party developer to communicate the data back and forth, however this creates much more work for each of us and seems a bit pointless when two developers could simply share a common metadata field.

**Additional context**
Our estate agency director spoke with Matthew Goddard about this and he suggested posting it to this forum to get onto roadmap. 

A simple example would of what we would like to be able to do is below:

1. On property "21 Sycamore Place" AC application creates shared "Metadata like" field called "Photography_Date" and saves "02/06/2021" as the value. 
2. External developer app performs get request on "21 Sycamore place" and included in property entity is "Photography_Date" with "02/06/2021" value.

**Comment by RWilcox-Reapit** [comment]
Hi @Daramithes ,
I'm bringing this ticket into sprint as we are currently looking at ways to architect this. 
The outcome of this ticket will be further tickets for implementation

Thanks

**Comment by Daramithes** [comment]
Thats amazing! Thanks for the update :)

**Comment by HollyJoyPhillips** [comment]
Whilst the nature of this request has been accepted, we are unable to commit to a specified sprint and therefore have assigned your issue to the ‘Long Term’ column. 

We will regularly review any issues and where development capacity is available, or work is aligned with our Roadmap, the issue will be updated.

For more information on our processes, please see https://foundations-documentation.reapit.cloud/dev-requests
