### ISSUE TITLE
Prop Centre Ref Field

### ISSUE THREAD

**Issue by Daramithes** [reapit/foundations#4268]
**Request**

In order for us to grant access to Semi-structured 'extras' field data, please provide the following information in this request:
![RPS](https://user-images.githubusercontent.com/33520316/120482643-391ca500-c3a9-11eb-8d0a-b3cd70db29b9.jpg)

- The name of the customer you represent
Aberdein Considine (AAC)
- The name of every field you need surfaced (if known)
Prop Centre Ref on Marketing Details Screen (See screenshot)
- A screenshot of of the field(s) you require in the agency cloud user interface
- A short use case as to why you require this data
Building application to update ASPC data, we require the ASPC ID reference which will be stored in the prop centre ref field.

**Comment by plittlewood-rpt** [comment]
Hi @Daramithes 

Please see below the extrasField value you need to include with your request to retrieve the Prop Centre Ref information for this customer:
 
Prop Centre Ref -> pAltCode
 
As an example, to return this field (where present), you would append the following to your GET request URI:
?extrasField=pAltCode
 
Thanks
Pete
