### ISSUE TITLE
Update REST hooks surface area to include filter management endpoints

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#4291]
**Background context**
#4289 will update the downstream webhooks service to be able to work with json filters to serve as a filter for webhook messages. We should update the REST Hooks contract to surface these endpoints.

**Specification**
- Surface all new endpoints in the REST hooks API
- Ensure properly documented, including example values

**Comment by plittlewood-rpt** [comment]
Superseded by #8373  which is in current sprint
