### ISSUE TITLE
Ensure user identity is accounted for specific service internal interactions

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#4329]
We should implement the research we did on applying group restrictions.

**Spec**
- Consider the authorizer
- Domain validation
- Refer to spreadsheet 
- Consider pre tokengen
- Check for services using OMS client package

**Comment by HollyJoyPhillips** [comment]
@plittlewood-rpt has the documentation

**Comment by plittlewood-rpt** [comment]
Next batch in PR
