### ISSUE TITLE
Allow 3rd parties to import compliance certificates via Reapit API

### ISSUE THREAD

**Issue by FrankieMalpass** [reapit/foundations#4337]
**Is your feature request related to a problem? Please describe.**
Lettings agents must provide tenants with the EPC (energy performance certificate), Gas safety certificate, EICR (electrical installation condition report), and other compliance documents prior to move in. When they import a property from Reapit onto our system, they want the compliance documents automatically imported along with the expiry dates so they 
a) don't forget to add the certificates (as our system will send them automatically to tenants if they are attached to the property), 
b) so they reduce the potential for manual error due to having to manually upload documents and enter the expiry dates again, 
c) to save them time as they have to download the docs from Reapit or other shared folder and upload into our platform. 

This is the single most requested feature from customers currently using our integration with Reapit. 

**Describe the solution you'd like**
Ability to call the API for EPC, Gas safety, EICR and other compliance documents, retrieve the document and its expiry date. 

**Describe alternatives you've considered**

**Additional context**

**Comment by cbryanreapit** [comment]
Duplicated at https://github.com/reapit/foundations/issues/2268 - closing in preference of the other ticket
