### ISSUE TITLE
Add new mobile menu and toggles to Geo Diary

### ISSUE THREAD

**Issue by willmcvay** [reapit/foundations#4342]
**Background context or User story:**

_Ahead of release, the new Geo Diary app should have it's tabs replaced with Toggles and the new Mobile nav_

**Comment by HollyJoyPhillips** [comment]
@willmcvay Driving and walking toggles remove the property pin placements 


https://www.dropbox.com/s/zgwwxvm7go2a7x3/Toggles.mp4?dl=0

**Comment by willmcvay** [comment]
@HollyJoyPhillips This bug has been around for a bit I think - have done a fix now
