### ISSUE TITLE
POST vendors/{id}/relationships returns 404 not found

### ISSUE THREAD

**Issue by lidiawisniewska** [reapit/foundations#4352]
**Describe the bug**
POST request to https://platform.reapit.cloud/vendors/{id}/relationships returns 404 'Entity "Contact" ({contactId}) was not found.' when request is made right after the contact is created.

**To Reproduce**
1. Create contact (POST /contacts/)
2. Create property (POST /properties/)
3. Create vendor contact relationship using contactId and vendorId returned from the previous two requests (POST /vendors/{id}/relationships)

**Expected behaviour**
Vendor-contact relationship should be created (201).

**Specification**
- Replication is the likely cause here based on the quick succession of actions
- We should look to pull contact from write rather than read
- Likely to affect other services so we should apply the same fix 
- Applies to applicants, vendors, landlords

**Comment by plittlewood-rpt** [comment]
Hi @lidiawisniewska - the vendor APIs have now been updated to hopefully resolve this problem. Please let me know if the issue you reported persists. Please note that the applicants/landlords relationship endpoints have not had the fix applied yet, that should follow shortly later today

**Comment by lidiawisniewska** [comment]
@plittlewood-rpt great to hear, will keep an eye on it. Thank you 👍
