### ISSUE TITLE
Add ability to search contacts by phone number

### ISSUE THREAD

**Issue by eazynow** [reapit/foundations#4353]
We are being asked increasingly by clients to add the ability to search for their contacts by phone number as well as/instead of email. 

At present, there is no way to search for a contact by phone number.

Please could you add the ability to search by phone number. It makes sense to add just one `phone` query parameter that searches all the phone number fields (`homePhone`, `workPhone`, `mobilePhone`)

**Comment by cbryanreapit** [comment]
Duplicated here: https://github.com/reapit/foundations/issues/3656 - the specifics of this request have been added to ticket
