### ISSUE TITLE
Add ability to search applicants by phone number

### ISSUE THREAD

**Issue by eazynow** [reapit/foundations#4354]
This follows on from #4353

We are being asked increasingly by clients to add the ability to search for their applicants by phone number as well as/instead of email.

At present, there is no way to search for an applicant by phone number.

Please could you add the ability to search by phone number. It makes sense to add just one phone query parameter that searches all the phone number fields (homePhone, workPhone, mobilePhone) related to the applicant's contact.

**Specification**
- Project: Reapit.Services.Applicants
- Implement new `contactDetail` query string parameter in the same way we have implemented this search mechanism in the contacts API

**Comment by sgregory6767** [comment]
Hi, is there any news on when this might be delivered ?

I don't think getting all contacts (in pages, so multiple calls) then attempting to locate the contact with the correct number is going to be feasible for us.
