### ISSUE TITLE
The developer registered stats seem inconsistent in the Admin Portal 

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#437]
**Summary:** According to the developer stats in the Admin Portal, there were only 4 developers registered on 19th. However, having checked with the DB, it should show 57. 

**Location:** https://dev.marketplace.reapit.cloud/admin/stats

See screen shot from Admin Portal:
![image](https://user-images.githubusercontent.com/52408607/75243772-694ac080-57c2-11ea-8426-96a2e687edf3.png)

See query:
https://dev.platformmarketplace.reapit.cloud/developers?pageSize=12&RegisteredFrom=2020-02-18T11:03:30.200Z&RegisteredTo=2020-02-25T11:03:30.200Z

See DB results :
![image](https://user-images.githubusercontent.com/52408607/75243739-5a640e00-57c2-11ea-932d-a6ec83f651d9.png)

**Expected Results:** The graph in the Admin portal should reflect the DB 

**To replicate:** Login to the Admin Portal > navigate to 'Stats' > select 'Developers' & 'Last Week'

**Comment by plittlewood-rpt** [comment]
@HollyJoyPhillips  there's a chance this is a UI issue. By default we only return a page size of 12 from this endpoint. It looks like the UI isn't paging through the results. Can we get someone from the UI team involved to just confirm if that's the case as that'll confirm who needs to do the work here to rectify the problem

**Comment by plittlewood-rpt** [comment]
@HollyJoyPhillips can you close this if #142 has resolved it?
