### ISSUE TITLE
Interactive API requests don't work

### ISSUE THREAD

**Issue by kraft001** [reapit/foundations#438]
**Summary:**
The API console doesn't display request details properly

**Steps to reproduce:**
Submit any API request through the interactive API console. Let's take, for example, the applicant view.

**Expected Results:**
A curl command for the API request and applicant details.

**Actual Results:**
`curl -X "undefined"` and `TypeError: Failed to fetch`
![Screenshot from 2020-02-25 17-58-13](https://user-images.githubusercontent.com/983140/75259175-a9c53100-57f8-11ea-99b9-a9832f3f93b6.png)

**Comment by willmcvay** [comment]
@kraft001 I can see from your request that you have entered an invalid id in the id field. To use the explorer, you first need to fetch a list of items, then get a valid id to fetch the resource. 

In your example, first fetch a list of applicants, get an applicant id and enter it into the id field on the GET applicant by id endpoint. The CURL we are aware will return undefined and we are looking to fix this however, the actual fetch return a 200.

See screenshot:

<img width="1437" alt="Screenshot 2020-02-25 at 15 24 44" src="https://user-images.githubusercontent.com/4630495/75262187-0f5af280-57e4-11ea-9151-079ce003868e.png">

**Comment by kraft001** [comment]
> I can see from your request that you have entered an invalid id in the id field

If the applicant ID wasn't found, then I expect to receive a correct 404 response
Yesterday there was an error in the response too, but now it seems to be fixed
Thank you!

> The CURL we are aware will return undefined and we are looking to fix this

Okay, if you're aware of the problem, could you point to the task please?
I didn't find it in the list of issues here, but I'd like to subscribe to it

**Comment by willmcvay** [comment]
@kraft001 See screenshot from prod 2 mins ago, this does return a 404 as expected. It is possible you experienced a network failure or there is a browser plugin causing your issue.

Can you try again to replicate in an incognito window and give us any other information that could be useful eg browser & version. 
<img width="1428" alt="Screenshot 2020-02-26 at 09 25 41" src="https://user-images.githubusercontent.com/4630495/75331393-817e1680-587a-11ea-8ceb-b4e63ea33d9f.png">

On the CURL, we are using the official Swagger UI React plugin and it does seem to be an issue with this (we are on the latest version), as the Swagger doucment itself is valid and works in a standalone version. Will keep this issue open and continue to monitor.

**Comment by willmcvay** [comment]
@kraft001 The issue is due to this bug. https://github.com/swagger-api/swagger-ui/issues/4778

The suggested fix does not work but have established another workaround and will be pushing a patch today.
