### ISSUE TITLE
"Start Chat" on Help page does not work

### ISSUE THREAD

**Issue by shaneosullivan** [reapit/foundations#4390]
**Describe the bug**
Clicking the Start Chat button on the Help page does not initiate a chat session. There is no visual feedback at all, not even an error message. Reproduced on Firefox & Chrome

**To Reproduce**
Steps to reproduce the behaviour eg:
1. Go to https://developers.reapit.cloud/help
2. Click on Start Chat
3. See that nothing happens

**Expected behaviour**
A chat widget should appear.

**Screenshots**

**Device (please complete the following information for web issues):**
 - Device: Macbook Pro
 - OS: Mac OSX 10.15.7
 - Browser Chrome & Firefox
 - Version: Chrome 90.0.4430.212, Firefox 88.0.1

**Additional context**
Please see the attached screenshot of the browser network logs after clicking on the button.  It appears to be initiating the widget but not succeeding. No errors are visible in the browser console
![Reapit_Chat_Network_Logs](https://user-images.githubusercontent.com/49378/122438314-7d579a00-cf92-11eb-836b-f8f1d8e9e66c.png)

**Comment by shaneosullivan** [comment]
Digging in to this more, I see that there is a caught exception when clicking the **Start Chat** button, stating 

```SyntaxError: Unexpected end of JSON input```

and in the screenshot you can see that **e.triggerJSON** is an empty string, while it is supposed to be valid JSON.

![Screenshot 2021-06-17 at 18 19 27](https://user-images.githubusercontent.com/49378/122444591-9bc09400-cf98-11eb-95f5-12dd14061e7a.png)

**Comment by willmcvay** [comment]
Closing as can't replicate - it's possible that this was fixed at a prior bug fix. Feel free to re-open if you are able to give more details
