### ISSUE TITLE
Add Sale Board details from Property Marketing to the API

### ISSUE THREAD

**Issue by azura-mg** [reapit/foundations#4415]
**Is your feature request related to a problem? Please describe.**
We were planning on creating an integration against an inbuilt field, but this field is not exposed to the API.

**Describe the solution you'd like**
In the AgencyCloud platform, under Properties there is a Marketing feature. Within that there is the ability to select a Sales Board to be put up outside a property. Currently this field is unavailable over the API so we are unable to retrieve the values that we would need for our integration.

**Describe alternatives you've considered**
Since the field isn't exposed by the API there doesn't appear to be any other method to pull this data via the API.

**Comment by cbryanreapit** [comment]
We need understand the sale board status options available in AC and how often this list is customised. This will lead us on the best approach for any sale board status field

**Comment by plittlewood-rpt** [comment]
There are 9 different Sale Board Types in circulation, though this field seems seldom used (only set on about 740 properties across the estate). Flag, V-Board and None are the items on the standard marketing screen

| Value  | Name | Usage |
| ------------- | ------------- | ----------|
|F|Flag|420|
|V|V-Board|277|
|N|None|89|
|W|Custom|3|
|T|Custom|2|
|G|Custom|1|
|RPT|Custom|1|
|S|Custom|1|
|P|Custom|1|

There are 68 sale board status options in circulation. This field is widely used and is set on 340,000 properties across the estate. The default list is as follows, and accounts for 225,000 properties (approx 66%):

For Sale, To Let, Sold, Sold STC, Under Offer, Let, None

The list of sale board statuses is additive and can be customised, so can be exposed via the configuration API, with just the code being returned from the properties API

There is a text field for "sale board note" (optionally enabled on a customer per customer basis) and a date field, both of which are generally used with the sale board ordering mechanism. This is a feature of Agency Cloud which fires when the sale board status is changed (an email goes to the board contractor) to send the status change information, note and requested date of change via email.

Suggestion would be to probably do away with the sale board type as it seems almost redundant now, and just support the type, note and date fields, paying consideration to how the note field is setup given it won't be enabled for all customers

**Comment by cbryanreapit** [comment]
**Specification**
- Add `GET /configuration/boardStatuses` and `GET /configuration/boardStatuses/{id}` endpoints to surface the sale board types that have been set up for a particular customer
- For GET, POST and patch property endpoints, make the following model revisions:
- Add `boardStatus` field to property model (string): Validate that when provided, it's an acceptable format (2 letter string code?)
- Add `boardStatus` link to `/configuration/boardStatuses/{id}` to document fields meaning
- Add `boardUpdated` field (date): Validate that when provided, it's an acceptable date only value
- Add 'boardNotes` fields (string): Validate that when provided, it's an acceptable length (TBC)
