### ISSUE TITLE
Unable to make Reapit employees inactive in Reapit Connect through internal service desk system

### ISSUE THREAD

**Issue by plittlewood-rpt** [reapit/foundations#4446]
When trying to deactivate a user in our internal service desk system that exists on Reapit Connect, an error is thrown and the user does not get deactivated.

**Specification**
- Isolate reason that the user does not get deactivated as intended and resolve

**Comment by plittlewood-rpt** [comment]
Have had a look into this this morning - to discuss further internally

**Comment by cbryanreapit** [comment]
Limitation documented, no further action required as this time
