### ISSUE TITLE
Additional financial analytics in properties model

### ISSUE THREAD

**Issue by plittlewood-rpt** [reapit/foundations#4478]
In the analytics schema we do not currently expose any information regarding fees. We should add this information

**Specification**
- Add SALES_COMMISSION_FIXED and SALES_COMMISSION_PERCENTAGE fields to properties model to expose both values on all records, calculating the opposite value where required

**Comment by cbryanreapit** [comment]
To be reviewed later, I'm not sure if this is a property model thing
