### ISSUE TITLE
Update data warehouse provisioning service to publish variation of compatibility view

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#4485]
**Background context**
As part of https://github.com/reapit/foundations/issues/4484, we'll have a variation of the compatibility views for a specific customer. We should ensure that a subset of our customer base can access and provision these views using the standard data warehouse application

**Specification**
- Add the new snowflake compatibility views to the warehouse provisioning service
- To be in addition to the existing compatibility views, rather than a replacement of
- Ensure provisioning and deprovisioning works in the same way
- Add functionality to hide the existing compatibility views and show the modified compatibility from the API, based on the customers organisation
- Default should always show current compatibility views, unless customer is present on a whitelisted value, in which case, swap out which is displayed

**Comment by plittlewood-rpt** [comment]
Blocked by #4484
