### ISSUE TITLE
Installations endpoint

### ISSUE THREAD

**Issue by kraft001** [reapit/foundations#449]
**Related to** #447

**Summary:**
When a new customer installs or uninstalls an app, the developer isn't notified about that.
For "client credentials" (machine-to-machine) applications it's important to have an up-to-date list of installations. It would be great to have an API endpoint with all app installations, so that we can scan it regularly and update the list of customers in our internal database.

**Comment by cbryanreapit** [comment]
We will be building a webhook to provide a real time notification for this purpose. Installation notifications will happen in real time and remove the need for polling : https://github.com/reapit/foundations/issues/1124

Additionally, an email will be sent to the primary developer email address: https://github.com/reapit/foundations/issues/953

Install information is also be available in the developer portal.

**Comment by cbryanreapit** [comment]
Ticket supercded by https://github.com/reapit/foundations/issues/1124
