### ISSUE TITLE
Marketplace issues on Internet Explorer (Dev Portal)

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#453]
**Summary:** The following UI issues and bugs have been detected when accessing the Developer Portal through IE

**Browser/Version:** Internet Explorer 11

- The Welcome Guide steps line is misaligned
**Location:** https://dev.marketplace.reapit.cloud/developer/welcome
**Steps to replicate:** Click on the above link in IE
![image](https://user-images.githubusercontent.com/52408607/75433019-3aaa2280-5947-11ea-830a-52bd53590845.png)

 

- The navigation bar 
The icons names do not match to the correct icons
For example: ‘Submit’ is assigned to the ‘Analytics’ tab, ‘Elements’ is assigned to ‘Help’, ‘Help’ has no icon and the cog is not sitting above ‘Settings’
If you click on the ‘Analytics’ icon it incorrectly opens the API (https://dev.marketplace.reapit.cloud/developer/swagger) docs 
![image](https://user-images.githubusercontent.com/52408607/75433042-43025d80-5947-11ea-83dd-f1c51efa724d.png) 

- Elements (Storybook) is not loading correctly
**Location:** https://dev.marketplace.reapit.cloud/developer/elements
**Steps to replicate:** Click on the above link
 
![image](https://user-images.githubusercontent.com/52408607/75433070-4c8bc580-5947-11ea-9d60-ebd501f4c9be.png)

- Unable to load the ‘Help’ page: 
**Location:** https://dev.marketplace.reapit.cloud/developer/help
**Steps to replicate:** Click on the link above in IE and the page does not load (completely blank), the following error occurs in the console
 
![image](https://user-images.githubusercontent.com/52408607/75433098-54e40080-5947-11ea-8351-e37862a7613a.png)

- On the ‘Submit’ and ‘Edit’ app pages the buttons are positioned out of the container
**Location:** https://dev.marketplace.reapit.cloud/developer/submit-app
**Steps to replicate:** Click on the above link or click on ‘Edit Detail’ on any app to view the ‘Edit’ app page
 
 
![image](https://user-images.githubusercontent.com/52408607/75433133-65947680-5947-11ea-8c2a-ada9a79d6020.png)
![image](https://user-images.githubusercontent.com/52408607/75433147-6b8a5780-5947-11ea-800d-e3d3eebab9cf.png)

- The buttons are out of the container on the success message after submitting and app: 
**Steps to replicate:** Submit an app to view the success message
![image](https://user-images.githubusercontent.com/52408607/75433178-78a74680-5947-11ea-9c14-1e47dd594021.png)
 

- No ‘Back to list’ button when deleting an App
**Steps to replicate:** Confirm deletion of an app. There should be a ‘Back to list’ button to close the message. 
 
![image](https://user-images.githubusercontent.com/52408607/75433199-7f35be00-5947-11ea-9f44-277afc531045.png)

- ‘Logout’ button is missing from ‘Settings’
**Location:** https://dev.marketplace.reapit.cloud/developer/settings
**Steps to replicate:** Click on the above link
 
![image](https://user-images.githubusercontent.com/52408607/75433258-9674ab80-5947-11ea-9883-e73ec42a9950.png)

**Comment by tanphamhaiduong** [comment]
Assign to @vuhuucuong because we need to debug on IE

**Comment by HollyJoyPhillips** [comment]
@nphivu414 Hey Vu, IE is now looking much better, thanks. I've noted your point with regards the elements page so will complete this ticket and test at a later date.
