### ISSUE TITLE
Status code 400 when retrieving appointmentTypes for specific customer

### ISSUE THREAD

**Issue by mattwoodleymerisis** [reapit/foundations#4532]
**Describe the bug**
When sending a GET request to `/configuration/appointmentTypes` for a specific customer, the response is always
`{"statusCode":400,"dateTime":"{{DATE}}","description":"An item with the same key has already been added. Key: VL"}`.

I wouldn't expect a GET request to be trying to add a new appointment type.

This is only happening for one customer using the application. Reapit Live Chat support suggested that this may be a problem with how that customer has their agency cloud set up so a Reapit service desk ticket was created, but they were unable to help and suggested raising an issue here instead.

**To Reproduce**
As this is only happening for a specific customer, I don't think it is possible to reproduce.

**Expected behaviour**
We would expect a response with status 200 and of form
`[
  {
    "id": "string",
    "value": "string"
  }
]`

**Screenshots**
N/A

**Device (please complete the following information for web issues):**
N/A, requests sent using PHP 7.x curl.

**Additional context**

**Comment by plittlewood-rpt** [comment]
Hi @mattwoodleymerisis - please can you confirm the id of the customer concerned?

**Comment by plittlewood-rpt** [comment]
Don't worry about this - I've found the ticket.

**Comment by cbryanreapit** [comment]
Data issue is now fixed, but we should ensure that this situation is handled better by the service

** Specification **
- Review previous fix for this issue here: https://github.com/reapit/foundations/issues/4020
- Ensure additive options to inbuilt lists will gracefully handle duplication (prefer standard value rather than the custom value)
