### ISSUE TITLE
Add lettings tenancy arranging model to analytics schema

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#4552]
**Background context**
 - Add reporting capability for lettings property tenancy arranging 
 - Consider whether under offer events are included here, or whether that requires a different model

**Comment by plittlewood-rpt** [comment]
I've opened a PR for dealing with arranging tenancy - I'd suggest offers are handled separately as they are a different bit of the process (precedes the arranging state). Let me know if you disagree
