### ISSUE TITLE
"marketingMode" filter on properties is broken

### ISSUE THREAD

**Issue by lidiawisniewska** [reapit/foundations#4569]
**Describe the bug**
"marketingMode" filter on properties is not working as expected.

Request to 'https://platform.reapit.cloud/properties/?marketingMode=letting' returns both 'letting' and 'sellingAndLetting' properties.
Request to 'https://platform.reapit.cloud/properties/?marketingMode=selling' returns both 'selling' and 'sellingAndLetting' properties.

**To Reproduce**
1. Go to Sandbox environment
2. Click on 'Properties'
3. Test the request with 'marketingMode' selected to 'letting' or 'selling'
4. The response includes 'sellingAndLetting' properties

**Expected behaviour**
The response should only include 'letting' or 'selling'

**Screenshots**
<img width="673" alt="Screen Shot 2021-07-12 at 4 34 31 PM" src="https://user-images.githubusercontent.com/19517181/125315461-732d7f00-e337-11eb-87f4-290380c40430.png">

**Comment by cbryanreapit** [comment]
This is working as intended - all lettings properties should be returned when 'letting' is specified, regardless if they're also being marketed as a sales property (and vice versa)

**Comment by lidiawisniewska** [comment]
@cbryanreapit thanks for quick response 👍

**Comment by cbryanreapit** [comment]
Very welcome - we appreciate your feedback. We'll ensure the docs better reflect what the expected behaviour should be here.
