### ISSUE TITLE
Location header not visible when creating new resources in Interactive API Explorer

### ISSUE THREAD

**Issue by plittlewood-rpt** [reapit/foundations#457]
When using the Interactive API Explorer to create a new resource using POST, the Location response header is not displayed in the UI, even though it does get returned from the service

UI
![image](https://user-images.githubusercontent.com/30798627/75495557-b7c0b080-59b6-11ea-81e7-75b448512c94.png)

Response from server
![image](https://user-images.githubusercontent.com/30798627/75495618-d9ba3300-59b6-11ea-858e-301a01b234f2.png)

**Comment by willmcvay** [comment]
Investigated this and there is a browser restriction with the Fetch API that limits the headers that can be forwarded to the Swagger UI. See this answer for an explanation: https://stackoverflow.com/questions/43344819/reading-response-headers-with-fetch-api#44816592
