### ISSUE TITLE
Certificates access via API or Webhook

### ISSUE THREAD

**Issue by StuartLaw99** [reapit/foundations#4574]
**Summary**
We don't seem able to get start and end dates of things like EPC certificates. 

**Detail and or supporting links and screenshots**
Is there an api method that we can use to pull all updates on Additions to certificates including the start and end date? eg. gas etc

**Comment by cbryanreapit** [comment]
This has already been requested by another developer, please follow https://github.com/reapit/foundations/issues/4158 for status updates
