### ISSUE TITLE
Review feasibility of entity relationship diagram for analytics schema

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#4579]
**Background context**
An ERD can explain relationships between entities visually, which coupled with the relationships embedded into the models, provides an excellent way understanding the schema.

**Specification**
- Review off the shelf ERD products to identity a suitable product
- Something that looks good - simplicity is key - we just need to demo relationships at this point
- Go to should be a single, diagram. This may not fit on a single screen legibly, but that may be acceptable
- We may discover that a single diagram isn't going to work and may need to break down by major concept (eg. separate ERD for contacts). This should be the fallback.
- Understand how we publish the ERD in terms of distribution - eg. a single large image, a link to external site, an embedded form?
- If this feels like something that would work reasonably well, output is write ticket to build it

**Comment by cbryanreapit** [comment]
As an example:
![image](https://user-images.githubusercontent.com/34191069/125625483-7162811a-9382-4cdb-b0ce-a5ddba0ee90c.png)

**Comment by cbryanreapit** [comment]
For example:
![image](https://user-images.githubusercontent.com/34191069/125625644-5884c0bd-eca4-4017-a3f6-7fe34d554d12.png)

**Comment by RWilcox-Reapit** [comment]
After comparing a few options the lucid chart gives us a tonne of functionality totally free: 
Pricing: https://lucid.app/pricing/lucidchart#/pricing

The editor give us many relationship and shape options:
![image](https://user-images.githubusercontent.com/61189374/127142274-8ce3f829-a7b0-4e11-a697-5e0645b65b29.png)

In terms of displaying to an end user we have the ability to share the diagram as a read-only link, an edit-able link or as an image:
Read only: https://lucid.app/lucidchart/29cf7bf9-6f4e-4537-9e12-1e25ebf8d4f3/view?page=0_0#
Editable: https://lucid.app/lucidchart/invitations/accept/inv_dd0d3a00-2e2a-4ab4-bd6f-3c8d36a40919?viewport_loc=-77%2C-33%2C2207%2C1475%2C0_0

Personally based on the views we currently have I think that Properties may need its own in-depth ERD as there are currently 15 views linked to a property.

**Comment by RWilcox-Reapit** [comment]
Further research to look for a tool which will auto generate the ER diagram based on a live connection to our warehouse. 

I've looked into a few tools and got the live connection working for both **Dataedo** and **DBeaver** which are the top suggestions by a snowflake engineer. 

Unfortunately Dataedo attempt to make a relationship between all joins which it is not possible to disable when auto generating the diagram. You can go back and remove the links but the layout is a mess and the number of joins is in the 100's making it unmanageable. 

**Dataedo Example**:
![image](https://user-images.githubusercontent.com/61189374/127355731-97d2aaf7-a199-4908-b429-f28656377328.png)

The second tool is **DBeaver** unfortunately this tool is not picking up any keys between the view in the analytics schema. Perhaps further research into setting a field as a key when creating the views is required. 

**DBeaver Example**:
![image](https://user-images.githubusercontent.com/61189374/127356043-e6ba05b7-14a4-4a32-b8e8-1f621e2f6c75.png)

The best option I've come across so far is either using the lucid app builder in the comment above which is simple to use and has a nice UI (But this means building it ourself).
OR using another tool called **QuickDBD** which relies on JSON to generate the diagram allowing us to source control it. This does require us to build and modify the diagram ourselves and unfrontuanely Key'd fields are required on the table

**QuickDBD Example:**
![image](https://user-images.githubusercontent.com/61189374/127357283-0c9e592a-c4a4-406d-bf25-48e95e35e9f0.png)
