### ISSUE TITLE
Webhook not firing on updating appointment's Negotiators

### ISSUE THREAD

**Issue by bisoh** [reapit/foundations#4631]
**Describe the bug**
Hi,
Updatin the 'Negotiators' field only does not fire the webhook.
We have a webhook that is subscribed to "_Appointment cancelled, Appointment created, Appointment modified_" events. When we create an appointment, save it, edit it and change only the 'Negotiators' field, the webhook does not get fired. We have to edit something else like (description, dates, accompanied, etc) and then it will be fired

**To Reproduce**
Steps to reproduce the behaviour:
1. Click on _Property_ on the left hand side menu
2. Select a property
3. Click on '_Viewings and Key_'
4. Create an appointment for that property
5. Fill in the details and make sure the "Accompanied user" and "Negotiator/Office" is populated with data
6. Save it
7. Edit the appointment above
8. Change the 'Negotiators' **ONLY**
9. The webhook won't be fired. Checking the "Transaction Logs" on https://developers.reapit.cloud/ should confirm that

**Expected behaviour**:
If the negotiator(s) are updated or removed, the webhook should be called

**Screenshots**

**Device (please complete the following information for web issues):**
 - Device: PC
 - OS: Win10, version: 21H1, OS build: 19043.1110
 - ReapIt desktop version: 12.132.2

**Specification**
- Recreate bug using steps above
- Determine where in the data pipeline this is not being processed correctly
- Apply relevant fix

**Comment by plittlewood-rpt** [comment]
Hi @bisoh - thanks for reporting this. It should now be resolved

Thanks
Pete
