### ISSUE TITLE
Update spacing for the secondary nav in the Dev Portal

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#4635]
**Summary**: For the secondary navigation, the spacing between the image and heading should be 12px

**Task**: 
- Update spacing on all secondary nav between the image and heading in the Developer Portal to 12px
![image](https://user-images.githubusercontent.com/52408607/126479080-d7e8c5b6-5d63-4921-8dcc-a98eada7c2c8.png)

**Comment by willmcvay** [comment]
@HollyJoyPhillips Already done this - should be on dev now
