### ISSUE TITLE
Access Extra Description Fields in Marketing Details of Property

### ISSUE THREAD

**Issue by StuartLaw99** [reapit/foundations#4638]
**Summary**
Unsure how to get to the Contract Ref ID field show here on the screenshot in Marketing details of a property.

![Capture](https://user-images.githubusercontent.com/48994486/126600207-7be0eb6f-9554-496d-8443-7ed5b8c8019d.JPG)

**Detail and or supporting links and screenshots**
Assuming its a custom field, the documentation states - 

extrasField
array[string]
(query)
Include extras fields matching one or more field names specified. You must be granted access to this data beforehand

It is not clear on how you grant access to this data beforehand as the api key has permissions to read all entities.

**Comment by cbryanreapit** [comment]
Hi @StuartLaw99

I've pasted a screenshot from the relevant part of our API documentation:
![image](https://user-images.githubusercontent.com/34191069/126950015-ffd53904-0905-4435-896e-e0edaee51dc5.png)

If you would be so kind as to log a new ticket using the template provided 

Many thanks
