### ISSUE TITLE
Icon / Content reveal functionality

### ISSUE THREAD

**Issue by nbdesignstudio** [reapit/foundations#4642]
**Is your feature request related to a problem? Please describe.**
As there is no Help / Live chat any more I was unsure where to submit this. 

We were chatting with Live chat a few weeks ago, and were advised that as part of the new Elements release there would be functionality available in the Elements toolkit, that would enable a User to click an icon / button to show some other inline content, such as in a div below.

**Describe the solution you'd like**
We are displaying a List of items, and some of the items have additional information that we would like to display, below that specific list item but above the next list item, in the list, when either the list item or an icon on that list item is clicked.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by HollyJoyPhillips** [comment]
Provided information via email
