### ISSUE TITLE
Query based on Extrafields

### ISSUE THREAD

**Issue by Daramithes** [reapit/foundations#4643]
**Is your feature request related to a problem? Please describe.**
Our company is currently using one of its extrafields as a store for an identifier for an external API. We would like to include a facility in our application to be able to look up all properties where this field is populated, either for use when communicating with the external API, or for reporting.

**Describe the solution you'd like**
To be able to perform a simple get a request on properties where any extrafield is populated.

**Describe alternatives you've considered**
We have considered using Metadata to store the data, as I believe you can query this. With over 1000 properties we run into the issue of having to manually identify which ones have the extra fields populated to begin with. 

**Additional context**

**Comment by cbryanreapit** [comment]
The metadata mechanism has been designed for this purpose and can be queried, we would not look to built out similar functionality in two places. If we are able to assist in usage of metadata to achieve your endgoals here, please raise another issue.
