### ISSUE TITLE
Docs rendering differently from certain links

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#4646]
**Summary**: The docs are rendering slightly differently if you are accessing them from the 'Help' page (could be others areas but can replicate easily from 'Help' 

**Accessing from 'Docs'**
![image](https://user-images.githubusercontent.com/52408607/126772045-98735406-c670-41f1-b41b-62ead6abc512.png)

**Accessing them from 'Help' > 'What's New'** 
![image](https://user-images.githubusercontent.com/52408607/126772102-5549fda9-c714-47a0-8518-710808bd2948.png)

**Comment by HollyJoyPhillips** [comment]
@willmcvay Still the same for me? 
![image](https://user-images.githubusercontent.com/52408607/127123824-20e465ce-9ab5-48ec-8f4f-c473f79427e2.png)

**Comment by willmcvay** [comment]
@HollyJoyPhillips try now

**Comment by HollyJoyPhillips** [comment]
@willmcvay Perfect, thank you!
