### ISSUE TITLE
App won't open and then quits.

### ISSUE THREAD

**Issue by nbdesignstudio** [reapit/foundations#4650]
**Describe the bug**
Opening the RPS Desktop app, doesn't open past the Login screen and the 'Loading Organiser setting's...' loading window, and then it quits. This does it for both myself and my colleague on 2 different desktop environments. Please see the screenshot.

**To Reproduce**
Steps to reproduce the behaviour eg:
Open the app, and you see the issue.

**Expected behaviour**
To be able to open the app.

**Screenshots**
Screenshot attached.

**Device (please complete the following information for web issues):**
Mac,
Virtual Machine running Windows 10

![Screenshot 2021-07-26 at 09 32 50](https://user-images.githubusercontent.com/24694998/126958926-2836d2b5-0482-45c7-8ccd-26f1f4467a53.png)

**Comment by HollyJoyPhillips** [comment]
@nbdesignstudio Hi Nathan, 

Can you confirm the last time you successfully logged in please?

**Comment by nbdesignstudio** [comment]
@HollyJoyPhillips  I believe I last logged in successfully on Friday. But my colleague Nick logged in yesterday. and was seeing the same issue as me early this morning.

**Comment by HollyJoyPhillips** [comment]
@nbdesignstudio Thank you for the information. Please could you follow the steps below: 

1.	Close & Uninstall AgencyCloud
For help and guidance on uninstalling programs from Windows, please click [here](https://support.microsoft.com/en-us/windows/uninstall-or-remove-apps-and-programs-in-windows-10-4b55f974-2cc6-2d2b-d092-5905080eaf98#:~:text=Uninstall%20from%20the%20Control%20Panel,select%20Uninstall%20or%20Uninstall%2FChange.)
2.	Once uninstalled, please see email with link to download the setup file
3.	Run the setup.exe file and install the latest version
4.	The Developer Edition of AgencyCloud should automatically start

I will email you the link direct on point 2.

**Comment by HollyJoyPhillips** [comment]
Confirmed uninstalling and reinstalling worked
