### ISSUE TITLE
Applying metadata filter against /properties/ endpoint.

### ISSUE THREAD

**Issue by dbContext** [reapit/foundations#4661]
**Summary**
Attempting to query /properties/ endpoint and filter down upon the *metadata* query param, with no luck.

**Detail and or supporting links and screenshots**

We’re identifying properties that we have on our system (sync’d up to the relevant Reapit property) via your metadata object on the individual properties.
 
I’ve just attempted to query properties with the specific metadata field we’ve created, as specified in the API documentation.
 
![image](https://user-images.githubusercontent.com/55065793/127128504-ad2fb219-3838-406a-9cdb-70703b04e4f8.png)

However nothing I’ve attempted thus far, has filtered down the search results at all. Please advice.
 
Attempted query parameters (end of URI):
 
https://platform.reapit.cloud/properties?pageNumber=1&pageSize=15&marketingMode=selling,sellingAndLetting&sellingStatus=forSale&metadata[0]=pipVaultId
 
https://platform.reapit.cloud/properties?pageNumber=1&pageSize=15&marketingMode=selling,sellingAndLetting&sellingStatus=forSale&metadata[]=pipVaultId
 
https://platform.reapit.cloud/properties?pageNumber=1&pageSize=15&marketingMode=selling,sellingAndLetting&sellingStatus=forSale&metadata=pipVaultId

**Comment by cbryanreapit** [comment]
Hi @dbContext - please read the documentation for details of how to use metadata search operations

https://foundations-documentation.reapit.cloud/api/api-documentation#searching-for-metadata
