### ISSUE TITLE
How to programmatically determine if a app install is from a AWS client or a non-AWS client

### ISSUE THREAD

**Issue by kitoban** [reapit/foundations#4663]
**Summary**
As webhooks are only available for AWS clients how can we programmatically determine if a app install is from a AWS client or a non-AWS client? 
Is this a field that has been added to the install webhook?

**Detail and or supporting links and screenshots**

**Comment by cbryanreapit** [comment]
@AshDeeming I believe projects have discussed something similar with you of late, can you catch up with me on that one please

**Comment by eazynow** [comment]
@cbryanreapit @AshDeeming is there any news on this as it's something we need to consider also

**Comment by HollyJoyPhillips** [comment]
@eazynow Is this still a requirement we will be migrating all our customers to AWS?

**Comment by eazynow** [comment]
@HollyJoyPhillips depends how long before this is complete 🙂

**Comment by plittlewood-rpt** [comment]
Hi @eazynow - a very rough timeframe for completion of this migration work is the middle of the year, however this is always subject to change so we will move this to the long term column so we can review it in line with how that project is moving along to decide whether or not we should do anything in the Platform

**Comment by HollyJoyPhillips** [comment]
We will not be in a position to build anything in the Platform ahead of all customers being migrated to AWS. Therefore will close this ticket. Thanks.
