### ISSUE TITLE
Processing of identityChecks for a contact

### ISSUE THREAD

**Issue by nroper** [reapit/foundations#4674]
**Summary**
Request for clarification on the concepts/lifecycle for processing identity checks for a contact.

**Detail and or supporting links and screenshots**
We would be grateful for some clarification on how identityChecks records for a contact are intended to be processed.

Our assumption was that there would be a single identityChecks record created for a contact and that this would be PATCHed with updates submitted via an Identity checks form (to edit document details etc) or received via an API call to a third party.

However, it appears that there can be an array of identityChecks records associated with a contact - see URL below for example:

https://platform.reapit.cloud/identityChecks/?contactId=MKT21000230

Note: These were created as a result of testing POST submissions during development.

Is the intended lifecycle of an identity check that a new record is created for a contact every time an update is made, or would you expect there to be a single identityChecks that is PATCHed per our undertsanding above?

This is pretty fundamental to how we process data in our App, so some guidance would be appreciated.

Many thanks.

**Comment by cbryanreapit** [comment]
@nroper can you please add an example payload to this ticket that exhibits the problem?

**Comment by HollyJoyPhillips** [comment]
@nroper Is this still an issue?
