### ISSUE TITLE
Surface Energy Supplier field in API

### ISSUE THREAD

**Issue by rhenesy** [reapit/foundations#4689]
**Is your feature request related to a problem? Please describe.**
We need to be able to pull the "energy supplier" data for a tenancy from Reapit via the API integration where a client has entered this information at tenant check out stage. This will enable us to ensure where the client provides such information to Reapit we are using it to enhance the notifications service we can offer to that client. This request has been driven by feedback from our mutual client Rettie & co.

**Describe the solution you'd like**
Ability to access via the API the "energy supplier" data for a tenancy where a client has entered this information onto Reapit at the tenant check out stage.

**Describe alternatives you've considered**
The client sending us this information manually outside of the API has been considered, but it's not currently an option and even it if was, it wouldn't be viable as a long term solution and somewhat defeats the object of using the API integration.

**Additional context**

**Comment by cbryanreapit** [comment]
Superceded by https://github.com/reapit/foundations/issues/4739 - please track this ticket instead
