### ISSUE TITLE
Retrieving joint landlords for a property 

### ISSUE THREAD

**Issue by TomFixflo** [reapit/foundations#4702]
As Fixflo 
We deal in maintenance issues 
Both primary and joint landlords would like to be kept informed of updates on maintenance at their property 

I am not a developer so I may be missing something obvious (apologies) 
I cannot see how to GET joint landlord records for a property from the Reapit API 

I tried GETProperty but this only seems to return the primary landlord 
I tried GETLandlordRelationship but again, I could not see the secondary landlord on this 

Am I missing something obvious? 

Thanks

**Comment by cbryanreapit** [comment]
@TomFixflo a property can only be assigned a single landlord, however that landlord may have multiple contacts associated to it (joint landlords)

**Comment by TomFixflo** [comment]
@cbryanreapit Is there a way of retrieving those joint landlord contacts through the API? 

Thanks

**Comment by cbryanreapit** [comment]
![image](https://user-images.githubusercontent.com/34191069/128512266-9d840924-b692-4373-ab66-ddc759ebdeac.png)
This is the endpoint you need for this
