### ISSUE TITLE
Identity Document POST function, incorrectly enforcing 2 Identity Documents?

### ISSUE THREAD

**Issue by nbdesignstudio** [reapit/foundations#4707]
**Summary**
We are trying to insert 1 Identity Document set of details using your patch API function: /identityChecks/{id} we are trying to input new Identity Documents to a Contact. 
However it appears that we get the following error if only trying to upload 1 document:

"errors": [
    {
      "field": "document2",
      "message": "The value cannot be empty; The document must contain details or file data/file url and name"
    }
  ]

Is the validation indeed trying to enforce a User inputs 2 sets of Identity Documents? 

What happens if the Contact can only provide 1, which must surely happen quite often.

**Specification**
- Replicate issue from payload attached in later comment
- If replicable, update the payload validation rules to no longer make document2 required

**Comment by cbryanreapit** [comment]
@nbdesignstudio can you please add an example payload that demonstrates the issue you describe? Thanks.

**Comment by nbdesignstudio** [comment]
Hi there @cbryanreapit 

I need to also point out that I should have said an initial POST request rather than PATCH request. As the issue is actually with the initial POST request when submitting Identity Document details for a Contact who doesn't currently have any associated identityChecks data.

Please find an example payload below as request:

Request:
{
    "contactId":"MKT21000562",
    "status":"unchecked",
    "modified":"1628496567391",
    "negotiatorId":"ADV",
    "identityDocument1":{
        "typeId":"DL",
        "expiry":"",
        "details":"COSTE508264EC9SZ"
    },
    "identityDocument2":{
        "typeId":"",
        "expiry":"",
        "details":""
    },
    "checkDate":"2021-08-09"
}

Response:
{
    "errors":[
        {
            "field":"document2",
            "message":"The value cannot be empty; The document must contain details or file data/file url and name"
        }
    ],
    "statusCode":422,
    "dateTime":"2021-08-09T08:09:27.4634802Z",
    "description":"One or more validation failures have occurred. Please refer to Errors list for details"
}

**Comment by cbryanreapit** [comment]
Thanks @nbdesignstudio - I have updated ticket to reflect this is a question about POST rather than PATCH, we will review and comment here.

**Comment by nroper** [comment]
@cbryanreapit just to note that we have tried various approaches for submitting a POST that only has details for identityDocument1, including setting identityDocument2 to null, but haven't been able to get anything to work.

However, the URL below returns an identityCheck record with identityDocument2 set to null, so it appears that it should be possible.

https://platform.reapit.cloud/identityChecks/MKT21000030

**Comment by nbdesignstudio** [comment]
Hi @cbryanreapit is there any news on this at all? have you been able to replicate the issue that we found?

**Comment by cbryanreapit** [comment]
@nbdesignstudio now that this ticket is in a proceedable state, it will be groomed as per our [outlined development processes](https://foundations-documentation.reapit.cloud/dev-requests). This is likely to happen this week.

**Comment by nbdesignstudio** [comment]
Ok. Thank you for the update.

**Comment by RWilcox-Reapit** [comment]
Hi @nbdesignstudio and @nroper, 

I've just had a look into this issue and you are currently able to create an identity check with a single document.
It is done by not constructing the 'identityDocument2' at all and setting it to null. This can also be achieved by removing 'identityDocument2' from the payload entirely:

**Example of null setting**: 
```
{
    "contactId":"MKT21000562",
    "status":"unchecked",
    "modified":"1628496567391",
    "negotiatorId":"ADV",
    "identityDocument1":
    {
        "typeId":"DL",
        "expiry":"",
        "details":"COSTE508264EC9SZ"
    },
    "identityDocument2": null,
    "checkDate":"2021-08-09"
}
```

I'll update the documentation to make this clearer. If you have any further issues just respond on here and I'll get back to you ASAP

**Comment by nroper** [comment]
@RWilcox-Reapit are you sure that setting  identityDocument2 to null works?  We had already tried that and it threw an error [(see not above)](https://github.com/reapit/foundations/issues/4707#issuecomment-895124686)

**Comment by RWilcox-Reapit** [comment]
@nroper Hi Nick, yes setting it to null does work. 
You can give it a try via our swagger page within marketplace if you wanted to confirm it.

**Comment by nroper** [comment]
@RWilcox-Reapit 

Hi, I just tried the swagger page with the example payload that you gave above, as well as with the one below.  In both cases the request wouldn't submit.  Maybe I'm doing something wrong, but I can't spot anything.

```
{
  "contactId": "OXF19000001",
  "checkDate": "2020-01-22",
  "status": "pending",
  "negotiatorId": "JAS",
  "identityDocument1": {
    "typeId": "DL",
    "expiry": "2050-03-22",
    "details": "Driving License",
    "fileData": null,
    "fileUrl": null,
    "name": null
  },
  "identityDocument2": null,
  "metadata": {
    "CustomField1": "CustomValue1",
    "CustomField2": true
  }
}
```

**Comment by RWilcox-Reapit** [comment]
Hi @nroper, It looks like that's an issue with the hosted swagger page specifically on production as that payload works on our test environments. I'll have to raise that with the front end team. 

The payload is valid though, I've just posted that via Postman and created entity: RPT21000021:

```
{
    "id": "RPT21000021",
    "contactId": "RPT21000067",
    "created": "2021-08-16T12:15:08Z",
    "modified": "2021-08-16T12:15:08Z",
    "checkDate": "2020-01-22",
    "status": "pending",
    "negotiatorId": "JAS",
    "identityDocument1": {
        "documentId": null,
        "typeId": "DL",
        "expiry": "2050-03-22",
        "details": "Driving License"
    },
    "identityDocument2": null,
    "_eTag": "\"8891E396FE5A5F9A9AA289E886778420\"",
    "_links": {
        "self": {
            "href": "/identityChecks/RPT21000021"
        },
        "contact": {
            "href": "/contacts/RPT21000067"
        },
        "documentType1": {
            "href": "/configuration/identityDocumentTypes/DL"
        }
    },
    "_embedded": null,
    "metadata": {
        "CustomField1": "CustomValue1",
        "CustomField2": true
    }
}
```

**Comment by nroper** [comment]
@RWilcox-Reapit thanks for checking.  We definitely tried that from within the App and got an error though - we'll try again and post results here.

**Comment by nbdesignstudio** [comment]
Hi @RWilcox-Reapit this is still to be tested later on today. Please keep this ticket open until we have successfull tested as per @nroper comment.

**Comment by nroper** [comment]
@RWilcox-Reapit I see this has been closed, but we haven't re-tested inside our App yet

**Comment by RWilcox-Reapit** [comment]
Sure I'll re-open. We're you not able to test this using Postman as suggested above?

**Comment by nroper** [comment]
@RWilcox-Reapit  We can test in Postman, but that doesn't necessarily replicate posting to the endpoint from within the context of the Foundations framework

**Comment by cbryanreapit** [comment]
Glad to hear you have this working - we haven't actually changed any behaviour here, other than firming up our documentation to make the null requirement clearer for future developers. Feedback is much appreciated.

**Comment by nroper** [comment]
@cbryanreapit @RWilcox-Reapit actually I think I spoke too soon.  If there's an existing identityDocument2 and we patch it with null then it leaves the original document intact. We're doing some more testing at the moment

**Comment by nroper** [comment]
@cbryanreapit do you have a link to the associated documentation?
Thanks

**Comment by RWilcox-Reapit** [comment]
Hi @nroper, good to hear you have it working. This is actually by design for a PATCH endpoint. 
Passing null would mean you do not want to make any changes to the document.

It was just some additional documentation added to the Swagger endpoint within Marketplace's API screen: 
See POST /identityChecks
![image](https://user-images.githubusercontent.com/61189374/129731151-4757086b-02bf-40af-be89-4e660eb4b039.png)

**Comment by nroper** [comment]
@RWilcox-Reapit I'd have thought that passing null would imply that it should be set to null, but that leaving identityDocument2 out of the payload would leave any existing document intact.

**Comment by nroper** [comment]
The only way that we've managed to patch an existing document to nuk is by passing  `{ typeId: '', expiry: '', details: ''}` - which seems like a hack. We tried `{}` as well but that doesn't work either.

**Comment by nroper** [comment]
@cbryanreapit @RWilcox-Reapit 

Could someone please advise how we can actually reset an identityDocument to null?

**Comment by cbryanreapit** [comment]
@nroper since the original misunderstanding related to POST is solved and your most recent commentary relates to PATCH we have closed this issue. If you're experiencing other issues with this endpoint, could you create a new issue please? We'll need the usual replication steps, example payloads and a use case to help us understand the requirement. Thanks.

**Comment by nroper** [comment]
@cbryanreapit sure, will do
