### ISSUE TITLE
Documentation typo deprecation vs depreciation

### ISSUE THREAD

**Issue by diabolo** [reapit/foundations#4721]
First of all apologies for being pedantic.

Your api docs use the word depreciation when they should be using deprecation (see below)

<img width="701" alt="Screenshot 2021-08-04 at 14 38 18" src="https://user-images.githubusercontent.com/11524/128190744-25a9778d-6170-49fb-bbb0-6f473f0114ae.png">

See screenshot below for definition of deprecation if you need confirmation

<img width="678" alt="Screenshot 2021-08-04 at 14 39 02" src="https://user-images.githubusercontent.com/11524/128190945-80a2e2c8-9d5d-48f7-9cc4-cdf30c3c80dd.png">

**Comment by willmcvay** [comment]
This is now fixed, thanks
