### ISSUE TITLE
Update warehouse provisioning service to support latest schema

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#4732]
- See PR 4291, we can filter this schema to a specific customer
- Update the table listing to account for latest changes

**Comment by plittlewood-rpt** [comment]
@cbryanreapit list of models to be shared:

APPLICANT_CONTACTS,APPLICANT_ENQUIRIES,APPLICANT_REQUIREMENTS,APPLICANTS,APPOINTMENTS,CONTACT_CATEGORIES,CONTACT_SUBSCRIPTIONS,CONTACTS,DATES,IDENTITY_CHECKS,LANDLORD_CONTACTS,LANDLORDS,NEGOTIATORS,OFFER_CONTACTS,OFFERS,OFFICES,PROPERTIES,PROPERTY_ATTRIBUTES,PROPERTY_IMAGES,PROPERTY_LETTINGS_CERTIFICATES,PROPERTY_LETTINGS_LOST_INSTRUCTIONS,PROPERTY_LETTINGS_RENT_CHANGES,PROPERTY_LETTINGS_VALUATIONS,PROPERTY_LETTINGS_WITHDRAWALS,PROPERTY_LETTINGS_WON_INSTRUCTIONS,PROPERTY_MATCHES,PROPERTY_SALES_COMPLETIONS,PROPERTY_SALES_EXCHANGES,PROPERTY_SALES_FALLTHROUGHS,PROPERTY_SALES_LOST_INSTRUCTIONS,PROPERTY_SALES_PRICE_CHANGES,PROPERTY_SALES_VALUATIONS,PROPERTY_SALES_WITHDRAWALS,PROPERTY_SALES_WON_INSTRUCTIONS,TASKS,TENANCIES,TENANCY_CHECKS,TENANCY_CONTACTS,TENANCY_RENEWALS,VALUATION_ENQUIRIES,VENDOR_CONTACTS,VENDORS,WORKS_ORDERS,WORKS_ORDERS_ITEMS
