### ISSUE TITLE
Architect approach for surfacing utility information in properties API

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#4739]
**Specification**
- Review lettings utility storage and design contracts to capture/present
- Present to the team and write ticket(s) off the back off that meeting

**Comment by RWilcox-Reapit** [comment]
Subsequent ticket raised to implement this and further discussion required regarding contracts:

Please see:
https://github.com/reapit/foundations/issues/4949
https://github.com/reapit/foundations/issues/4948
