### ISSUE TITLE
Metadata not persisted when creating appointments

### ISSUE THREAD

**Issue by bisoh** [reapit/foundations#4751]
We are performing a `POST/appointments` with an appointment that has values in it's metadata, and when later doing a `GET Appointments (filtering on start and end)`, the appointment created previously has no metadata populated. I have tested this using Postman and a console app that makes a call similar to our code.

**To Reproduce**

1. Post the following `ReapItApi/appointments`
```
{
  "Start": "2021-08-13T12:30:02.00Z",
  "End": "2021-08-13T13:30:02.00Z",
  "TypeId": "MI",
  "Description": "Get burger",
  "OrganiserId": "MRAD",
  "NegotiatorIds": [
    "MRAD"
  ],
  "OfficeIds": [
    "OXF"
  ],
  "Attendee": null,
  "Accompanied": false,
  "NegotiatorConfirmed": true,
  "Virtual": false,
  "Recurrence": {
    "Interval": 0,
    "Yype": null,
    "Until": null
  },
  "metadata": {
    "ExternalSystemId" : "123----123"
  }
}
```
2. Perform a `GET ReapItApi/appointments/?includeCancelled=false&start=2021-08-13&end=2021-08-14`
3. Metadata will be empty

**Expected behaviour**
The appointment created above should have metadata populated with property ExternalSystemId = "123----123"

**Device (please complete the following information for web issues):**
 - Windows 10  20H2
 - Postman v8.10.0
 - ReapIt API version 2020-01-31

**Specification**
- Attempt to replicate issue
- Diagnosis and surface with team before acting on a fix

**Comment by plittlewood-rpt** [comment]
Hi @bisoh  I've just run through the steps to replicate provided above in the Sandbox environment using the Swagger API page in the developer portal and I'm getting the metadata returned without an issue. Please can I ask you to retest? When you post a new a appointment can you also look at it on the `GET /appointments/{id}` endpoint as well as that's probably easier to look at. Remember that the metadata will be embedded within each resource when using the `GET /appointments` endpoint.

**Comment by bisoh** [comment]
Hi Pete,
Thanks for looking into this. I have just posted the following through Postman (on sandbox)

```
{
  "Start": "2021-09-13T12:30:02.00Z",
  "End": "2021-09-13T13:30:02.00Z",
  "TypeId": "MI",
  "Description": "Test this",
  "OrganiserId": "MRAD",
  "NegotiatorIds": [
    "MRAD"
  ],
  "OfficeIds": [
    "OXF"
  ],
  "Attendee": null,
  "Accompanied": false,
  "NegotiatorConfirmed": true,
  "Virtual": false,
  "Recurrence": {
    "Interval": 0,
    "Yype": null,
    "Until": null
  },
  "metadata": {
    "ExternalSystemId" : "123----123"
  }
}
```
this has created appointment RPT2101671.
Doing a `GET /appointments/RPT2101671` or  `GET /appointments/?includeCancelled=false&start=2021-09-13&end=2021-09-14`  is returning `"metadata": {}`
I also tested on Swagger and metadata is empty

**Comment by plittlewood-rpt** [comment]
Would you be able to reissue the request for me and send me the response headers that you get? You should get a couple back prefixed with x-amz-* which will help me find the request in some of the logs.

**Comment by bisoh** [comment]
Sure.
Request :

```
{
  "Start": "2021-09-13T12:30:02.00Z",
  "End": "2021-09-13T13:30:02.00Z",
  "TypeId": "MI",
  "Description": "Test with response headers",
  "OrganiserId": "MRAD",
  "NegotiatorIds": [
    "MRAD"
  ],
  "OfficeIds": [
    "OXF"
  ],
  "Attendee": null,
  "Accompanied": false,
  "NegotiatorConfirmed": true,
  "Virtual": false,
  "Recurrence": {
    "Interval": 0,
    "Type": null,
    "Until": null
  },
  "metadata": {
    "ExternalSystemId" : "123----123"
  }
}
```

Response Headers:

x-amzn-RequestId
7ade2227-a30c-4403-ab08-0118c387ea97

x-amz-apigw-id
EQqBlHAULPEFXQw=

x-amzn-Remapped-Server
Kestrel

Location
https://platform.reapit.cloud/appointments/RPT2101673

X-Amzn-Trace-Id
Root=1-611cf070-34cd24c06b6fb6fa18aa9ef0;Sampled=0

x-amzn-Remapped-Date
Wed, 18 Aug 2021 11:35:12 GMT

Thanks

**Comment by plittlewood-rpt** [comment]
Thanks - this is a little strange. There is some metadata associated with that entity and your developer account but not what you've submitted in your payload. The metadata looks like this (actual values omitted for security)

```
"metadata": {
    "correlationid": null,
    "graphapietag": "omitted",
    "graphapiresourceid": "omitted",
    "graphapisensitivity": null,
    "graphapishowas": null,
    "isoutlookorigin": false,
    "migratedtooutlook": null
  },
```

Is this something that's familiar to you?

**Comment by bisoh** [comment]
Yes. That is normally what our systems would add to a an appointment. However, when I do a `GET/appointments/RPT2101673` I don't see it on postman.
Our problem is that when our code does the get above and does not find the metadata, it behaves incorrectly because its expected to be there.

**Comment by bisoh** [comment]
here is the response I just got from making the call to that appointment
![image](https://user-images.githubusercontent.com/3708220/129909511-b2e27729-9d35-4a06-a0a6-fc9b1ad5f1ed.png)

**Comment by plittlewood-rpt** [comment]
Thanks - how are you getting / setting your reapitToken parameter?

**Comment by bisoh** [comment]
Making a Post /token, saving result in a variable and reusing it. We do that for all our postman calls 
![image](https://user-images.githubusercontent.com/3708220/129911928-184acddc-f9a0-4a60-a017-5ec8a988eb75.png)
![image](https://user-images.githubusercontent.com/3708220/129911998-30e7e26b-d9bc-4710-aea6-d72a861429f4.png)
![image](https://user-images.githubusercontent.com/3708220/129912101-71d4c5de-20fa-43de-9efd-f775b0aa17ae.png)

**Comment by plittlewood-rpt** [comment]
Thanks - can you just confirm the last 3 digits of your client id?

**Comment by bisoh** [comment]
1pm

**Comment by RWilcox-Reapit** [comment]
Hi @bisoh, 
I'm just joining Pete on looking in to this and can't seem to replicate it either via both postman and the marketplace swagger.

Can I ask that you send us over the bearer token for both requests (The POST and GET). 
If you can send it to my email to keep it off this public board that'd be great: rwilcox@reapit.com

It will help us rule out a potential issue and if they align we'll have to dig deeper. 

Thanks,
Ryan
