### ISSUE TITLE
Updating appointments issue in Reapit

### ISSUE THREAD

**Issue by RachelLightfoot** [reapit/foundations#4762]
**Describe the bug**
We’re having some problems regarding the IDs of some appointments changing when their start and end dates are updated in Reapit, which is causing issues for our customers who are using the API integration with TouchRight.

When a customer needs to edit an appointment in Reapit to change the date/time, we would expect the appointment ID to remain the same so that when we sync with Reapit in TouchRight, we can find that same appointment in TR and update it with the new information. However, because the ID seems to be changing, a new TouchRight appointment is being created instead which is causing confusion for our customers and for ourselves as they are getting lots of duplicate appointments in their account which they don't need.

We have spoken to one of our customers who showed us how they were updating the start/end date of appointments in Reapit. They definitely updated it and did not create a new one, as we could see the appointment changing to a different date/time in their Reapit diary when edited.

Our logs are showing that the original Reapit appointment is being marked as cancelled at this point, however work may have been done in Reapit on that appointment and deleting it would lose that work. Additionally, creating a new appointment with the new Reapit ID means that our customers need to do that work again.

Examples of this happening are appointments with IDs WND2102921 and WND2103048 for the property WND150645.

We have tried testing this ourselves by creating an appointment then updating the start and end dates, but the ID remained the same. This was done via the API so perhaps this is only happening via the UI?

We’d just like some clarification on what the process is regarding updating appointments and whether the Reapit ID is meant to be updating. Additionally if the ID is meant to be updating, is there any way we can link the new ID to the old one so that we can prevent duplicates from being created?

**Comment by cbryanreapit** [comment]
@RachelLightfoot We would not expect appointments to be rekeyed. Could you provide the customer name and the steps to replicate when using Agency Cloud please? Could you also expand on the appointment ids you provided to include which appear to be the original and newly created appointment please

**Comment by RachelLightfoot** [comment]
@cbryanreapit The customer is Hamilton Chess. 

- They had already created an appointment in their Reapit account and synced it to TouchRight (with ID WND2102921 for property WND150645).
- They then edited that appointment in Reapit to change the date and time - they did this by opening the property and going to the Management tab, then in the Inspections area, they clicked either the 'last' or 'next' date field to edit the inspection appointment and changed the date/time.

![Screenshot (23)](https://user-images.githubusercontent.com/76471776/129225578-3e535e44-5940-41f6-af89-3552ce8663e5.png)

- The customer then carried out a resync in TouchRight to update the existing appointment, however rather than updating the existing appointment record in TouchRight a separate new appointment is being created with a different ID WND2103048. 
- As the ID is new, we're unable to match it to the appointment ID we already have.

We have tried testing this ourselves by creating an appointment then updating the start and end dates, but the ID remained the same, which suggests that it is working correctly via the API, and this issue is only happening via the UI for the customer. Perhaps there's a bug somewhere to cause these different behaviours?

Let me know if you need any more information.

**Comment by RachelLightfoot** [comment]
@cbryanreapit is there any update on this ticket, what stage is it at?

**Comment by cbryanreapit** [comment]
@RachelLightfoot we aren't able to reproduce a brand new appointment being created when hitting 'last' or 'next' links where the link is previewing an existing appointment. If the customer is certain that hitting 'last' or 'next' is creating brand new appointments rather than updating an existing one, they should flag this using the usual Agency Cloud support channels. 

However, I suspect what may be happening here is that the customer is hitting the 'book inspection' button, screenshotted below. This will have the effect of booking a brand new, additional inspection appointment. The 'next' link UI may update at the point that this happens, if it's the next inspection to occur.

![image](https://user-images.githubusercontent.com/34191069/129557163-0bb5b0ae-98bb-460a-a304-c9d7facebd6b.png)

This is the expected behaviour and tenancies can have multiple inspections scheduled at any given time, as per the inspection schedule. Is your application expected only a single inspection appointment to be scheduled at any given time?

![image](https://user-images.githubusercontent.com/34191069/129557320-750be96d-a0c3-469b-9e28-642022429084.png)

**Comment by RachelLightfoot** [comment]
@cbryanreapit I'm afraid your suggestion for what might be happening isn't correct, as I've been on a screenshare with the customer and they showed me exactly what they were doing.

Just to be clear, the customer is not saying that a brand new appointment is being created in Reapit when they use the last or next links.  They are simply using those links to open the appointment and then edit it to change the date and time in Reapit and then seeing that appointment move in their Reapit diary from one date to another.

Our application is NOT expecting only a single inspection appointment to be scheduled at any given time as multiple appointments can be scheduled in TouchRight.  We are expecting that when an existing appointment is edited in Reapit, that appointment will keep the SAME ID as when it was originally synced to TouchRight, so the existing record can be updated accordingly.  At the moment we are seeing that amended appointment is being sent to TouchRight with a new ID, so the existing record can't be updated, and a duplicate record is being created.

**Comment by cbryanreapit** [comment]
Thanks for the clarification @RachelLightfoot - since the issue being reported here is based on user interaction within the Agency Cloud application and does not appear to be API related, the best course of action is for the customer to raise an issue using the usual Agency Cloud support channels.

**Comment by RachelLightfoot** [comment]
Ok @cbryanreapit a ticket was raised with them initially which they subsequently closed and redirected us through this route. It's a shame this can't be redirected internally.  I assume they can see the correspondence on this ticket so we don't have to start again?

**Comment by cbryanreapit** [comment]
Apologies for that - this ticket is public so they'll be able to see correspondence, yes
