### ISSUE TITLE
Offers analytics error when retrieving records

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#4765]
**Specification**
```
SQL compilation error: View definition for 'REAPIT.ANALYTICS_XXX.OFFERS' declared 91 column(s), but view query produces 92 column(s).
```

**Comment by matt-austin-andrews** [comment]
@cbryanreapit - same issue present on OFFICES table:
`SQL compilation error: View definition for 'REAPIT.ANALYTICS_XXX.OFFICES' declared 17 column(s), but view query produces 20 column(s).`

**Comment by plittlewood-rpt** [comment]
Hi @matt-austin-andrews  please can you confirm if this is still an issue? I reprovisioned the latest set of views for you on Friday afternoon which should have resolved the problem

**Comment by matt-austin-andrews** [comment]
All good now @plittlewood-rpt - thank you very much!

**Comment by plittlewood-rpt** [comment]
Thanks for confirming @matt-austin-andrews  - FYI we've a separate ticket to work out the best way of governing updates to the schema going forwards if you want to follow it. #4760
