### ISSUE TITLE
Issue on Signup

### ISSUE THREAD

**Issue by patrikwork1** [reapit/foundations#4771]
**Describe the bug**
Someone has installed and signed up for our app. We have received an email about the signup but it seems like there was an issue during the process. On signup RentProfile’s API did not receive enough information from Reapit about the company’s details so our API did not link the agency up correctly to our system. Also the company address is missing from the developer dashboard.

The scenario happened as follows:
Someone installed RentProfile’s app through the Reapit Marketplace at Kay and Co
Since the individual never used the app RentProfile never received the details that the system would require to setup a new agent
Later someone else tried using RentProfile’s app under a different email with no success (Since our system have not received the agencies details earlier)
On the developer dashboard the details I am seeing is that the user used name 'Kay and Co' and client 'KYC' for signing up.

**To Reproduce**
Steps to reproduce the behaviour eg:
1. User installed the app (Company Address is missing)
2. User did not use the app after installation
3. Someone from the same company tried logging into the app without success

**Expected behaviour**
Renter signs up with the correct details, RentProfile receives the necessary information for the user (email, name, reapit_ref etc..) from Reapit so the system can link up the account correctly.

**Device (please complete the following information for web issues):**
 - Device: [PC, Mac]
 - Browser [Chrome, Safari]

My suggestion is the addition of a different testing account for RentProfile for testing. Rather than using the one provided by default as using our own account for testing is not as reliable as we are also the supplier.

**Comment by HollyJoyPhillips** [comment]
@patrikwork1 I replied direct to your email on 13/08/21. If that did not answer your question, please feel free to reopen the ticket.
