### ISSUE TITLE
Update data warehouse provisioning service to create analytics views powered by field listing

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#4813]
**Background context**
Presently, our views are performing a `SELECT *` - we should call the fields out by name to ensure that downstream field additions do not break views already deployed at customer warehouses. 

**Specification**
- Verify that adding a field to back end, centrally held analytics schema will break views generated for customers based on `SELECT * FROM table`

**Comment by plittlewood-rpt** [comment]
For info you can generate the SQL programatically by running something along the lines of the below:

```
SELECT 
    CONCAT('SELECT ', LISTAGG(column_name, ', ') WITHIN GROUP (order by ordinal_position), ' FROM ', table_name, ' WHERE _CUSTOMER_ID = ''XXX''') as cmd
FROM
    (SELECT column_name,  TABLE_NAME, ordinal_position FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'DBT_PLITTLEWOOD' AND TABLE_NAME = 'APPLICANTS' ) as t1
GROUP BY table_name
```

Replace the table name (based on your loop) and the schema name as appropriate
