### ISSUE TITLE
Removing an existing identy document from an identityCheck record

### ISSUE THREAD

**Issue by nroper** [reapit/foundations#4815]
**Summary**
Request for guidance on how to delete, or nullify, an existing `identityDocument2` in an identity check record

**Detail and or supporting links and screenshots**
Would be grateful if someone could advise as to how we should go about setting an existing `identityDocument2` to `null`.

For example, if a POST request is sent to created a new `identityCheck` record then it is possible to set `identityDocument2` to `null`.

```
{
      "id": "RPT21000076",
      "contactId": "MKT21000587",
      "created": "2021-08-19T06:13:57Z",
      "modified": "2021-08-19T06:13:57Z",
      "checkDate": "2021-08-18",
      "status": "pending",
      "negotiatorId": "ADV",
      "identityDocument1": {
        "documentId": "RPT21000745",
        "typeId": "BB",
        "expiry": "2021-08-27",
        "details": "Test"
      },
      "identityDocument2": null,
      "_eTag": "\"BDFBBBBC1AF4AD2DC67BF6A542989B4F\"",
      etc...
 }
```

It is then possible to PATCH the record so that `identityDocument2` is assigned an object.

We need to be able to revert the record back to its original state by setting `identityDocument2` back to `null`. However, as advised by yourselves [in this ticket](https://github.com/reapit/foundations/issues/4707#issuecomment-900283689), passing a `null` value is assumed to imply that it should be left intact.

I'd have expected that explicitly passing `null` would imply that it should actually be set to `null`,  but that leaving `identityDocument2` out of the payload would leave it intact.

How should we go about resetting `identityDocument2` to it's original `null` value?

Thanks

**Specification**
- Project: Reapit.Services.IdentityChecks
- Update the UpdateIdentityCheckCommandValidation rules to allow the documentId for either document to be set to an empty string. This is the mechanism by which child objects can be cleared (we have done something similar in the appointments service for clearing an attendee, so we should follow the same precedent)
- This may have downstream effects on the associated command handler which may expect documents to be present
- The documents can ONLY be cleared, where the status of the identity check is `unchecked` or `pending`. At the point the identity check is completed/succeeded/failed, the information should remain available in the CRM
- Do not remove the physical file assets for the time being
- Ensure appropriate tests are added

**Comment by cbryanreapit** [comment]
Hi @nroper - to help us understand and prioritise, could you provide us with a use case as to why you'd want to clear out a previously added identity document?

**Comment by nroper** [comment]
Hi @cbryanreapit, the scenarios that I can think of are:

A document was added by mistake initially
A document that was added originally is no longer valid - for example a passport or driving licence has expired and isn't being renewed or replaced by another document type

There may other reasons which @nbdesignstudio is aware of.

**Comment by nbdesignstudio** [comment]
@nroper Yes those reasons sounds like quite possible scenarios. 

The last thing you want is to have data stored that you can't remove, yet it is completely useless. So would naturally be better to get rid of it.
