### ISSUE TITLE
Automated SSRS-Style Reports

### ISSUE THREAD

**Issue by matt-austin-andrews** [reapit/foundations#4840]
**Describe the solution you'd like**
As an analyst, I want to be able to schedule queries from the Snowflake interface to (a) run at specific times and (b) for the results to be emailed to designated addresses. This would allow us to send specific data to clients and third parties in an automated fashion.

**Specific use-case (Andrews)**
In an ideal world, we would be able to run queries and email/share the results via a proper BI tool, but we do not yet have access to such a program and have to rely on Excel for now due to budget constraints. As such, we either have to:

- login to snowflakecomputing.com, run the query and manually send the results, _or_
- run the query via the ODBC connector in Excel and share the spreadsheet

The latter is not too arduous, but the only way to automate this is by setting up a data gateway (which kind of defeats the point of a cloud database) and writing a VBA script for the onward email send (life is too short for VBA).

**Comment by cbryanreapit** [comment]
Hi @matt-austin-andrews - Snowflake doesn't possess that capability out of the box and a report scheduler isn't something we'd look to build in-house I'm afraid.

As an alternative, suggest you might want to look at am iPaaS solution to do something like this (eg. https://www.shipyardapp.com/solutions/send-snowflake-data-as-a-report-via-email). An iPaaS approach like this can be very cost effective.

**Comment by matt-austin-andrews** [comment]
Thanks @cbryanreapit - that tool looks perfect for our current requirements!
