### ISSUE TITLE
question: what's the delay between desktop app updates and updated data available on reapit api?

### ISSUE THREAD

**Issue by DonGiulio** [reapit/foundations#4843]
We have a number of complaints that agents update properties on the desktop app, then click on our 'reapit update' button, which does a series of get applicant, get tenancies, get properties requests using the `modifiedFrom` parameter. 

The complaint is that the updates are then not reflected on our app. 

I clicked on the same button a few hours later and the update worked with no problems. 

so my question is: is there a delay between the moment the user updates/creates an item on the desktop app and the moment the new data is available on the api? 

Thanks.

**Comment by cbryanreapit** [comment]
@DonGiulio to answer your question: updates made to data via Agency Cloud is reflected immediately in our APIs. Things to examine:
- Users should hit 'save' before they hit your 'Reapit Update' button
- Ensure the timestamps you are passing through as `modifiedFrom` are using UTC
- You can test this behaviour using Agency Cloud Developer Edition
