### ISSUE TITLE
Extrafields for Appointments, specifically "Followed Up" field.

### ISSUE THREAD

**Issue by Daramithes** [reapit/foundations#4844]
**Request**

In order for us to grant access to Semi-structured 'extras' field data, please provide the following information in this request:

- Aberdein Considine (AAC)
- The "Follow up" toggle on a property viewing page within RPS.
- Building customer portal where they can view feedback from a customer once passed by agent. Want to only display the followed up note once the feedback has been followed up. 

![2021-08-23 18_52_50-AC Citrix Desktop - Desktop Viewer](https://user-images.githubusercontent.com/33520316/130493864-a5ec015a-e0ee-4602-be02-c95b23b44d6c.png)

**Comment by Daramithes** [comment]
Already spoke to Holly to confirm extra-fields isn't available for Applicant API. Can this also be considered a feature request for that component in the API?

**Comment by cbryanreapit** [comment]
@Daramithes the 'followed up' checkbox pictured just clears out the appointment follow up due date, it doesn't actually store anything in the back end. 

You should consider an appointment as 'followed up' when a user has inputted the `followUp.responseId` or `followUp.notes` fields. These fields are already returned by the API - swagger screenshotted below.

![image](https://user-images.githubusercontent.com/34191069/130514308-6b6d8030-6161-4ee8-8485-86ed287a1d13.png)

For applicants, please log a new issue using the template provided - thanks.
