### ISSUE TITLE
Extrafield "Unaccompanied viewing"

### ISSUE THREAD

**Issue by Daramithes** [reapit/foundations#4859]
**Request**

In order for us to grant access to Semi-structured 'extras' field data, please provide the following information in this request:

- AAC (Aberdein Considine)
- Currently our site filters requests using the SOAP api by determining if a client is handling their viewings themselves. We are building a new mobile application using the PaaS platform and would like to do the same.
![Capture](https://user-images.githubusercontent.com/33520316/130948085-e983433a-e80e-45aa-b3a6-230f264ba762.PNG)

We are working with a third party developer on this, and both of us will require access to this data, would they need to also submit a request in order to gain access?

**Comment by RWilcox-Reapit** [comment]
Hi again @Daramithes 

This has now been added and it's accessible by passing 'pUnacView' to the query parameter 'extrasField' on either GET endpoint for properties.

Thanks
