### ISSUE TITLE
Architect approach for negotiator centric webhooks

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#4862]
**Background context**
We should provide the ability for negotiator events to be emitted from our webhooks service

**Specification**
- negotiators.created
- negotiators.modified
- The source table may stream many events through our pipeline here, we should we wary of load and handle accordingly
- Output of ticket is a plan to present to team

**Comment by RWilcox-Reapit** [comment]
Unfortunately there is no way of preventing the event from being emitted from kinesis so the handling/ignoring of specific negotiator updates will have to take place in the DB event handler. 
This leaves us with three approaches here to be discussed.

1. Update to create a stream for each table or for a group of tables (This way new tables with high volume such as negotiators can be assigned it's own stream)
2. Update to create a stream per customer (When millions events are fired for a specific customer there is no knock on effect to other) 
3. Increase the number of shards. A stream can have up to 500 shards each capable of processing 1,000 records per second allowing us to process 500k per second. (https://docs.aws.amazon.com/streams/latest/dev/service-sizes-and-limits.html)

Further discussion to be had

**Comment by plittlewood-rpt** [comment]
FYI I've confirmed with the desktop team and the negotiator records get updated every 30 seconds so the volume of changes going through the pipeline is going to be vast
