### ISSUE TITLE
Vendor modified date not getting updated

### ISSUE THREAD

**Issue by Filip5991** [reapit/foundations#4873]
A Reapit customer I was testing with had a vendor created with the id RPT130001 some time ago.

On 26.08.2021 we decided to change the surname of the first relation of this vendor, and see if this vendor appears in the vendors that were modified on that day(modifiedFrom=2021-08-26T00:00:01Z ; modifiedTo=2021-08-26T23:59:59Z) by using the url:

https://platform.reapit.cloud/vendors/?PageNumber=1&PageSize=100&modifiedFrom=2021-08-26T00:00:01Z &modifiedTo=2021-08-26T23:59:59Z

We did not see this particular vendor in the vendors modified list (even though the modification occurred on that day).

If I ping the vendor as a single object, by using:

https://platform.reapit.cloud/vendors/RPT130001

I can see the change we made in the surname is there, but the “modified” date is the 18th of August (instead of today): https://prnt.sc/1qlu98d

I was wondering why changing some of the relations info does not update the vendor modified date (or trigger a vendors modified webhook)?

**Specification**
- Check to see if webhook is emitted using outlined steps

**Comment by RWilcox-Reapit** [comment]
Hi @Filip5991

I can confirm after testing that a webhook event would be emitted for _vendors.modified_.
The vendors modified date however would not be updated as the change was applied to the contact rather than the relationship.

Subscribing to _vendors.modified_ would be the best route to track these updates rather than polling vendors by modified.

Thanks,
Ryan

**Comment by Filip5991** [comment]
Hi @RWilcox-Reapit,
The biggest issue here is that this is a Rackspace using app, so webhooks cannot be used.
If I understood you correctly, checking for any possible vendor (relation) changes would require getting all the vendors for that customers through the /vendors/ endpoint, and then checking them manually?
