### ISSUE TITLE
Better documentation around Master Plots

### ISSUE THREAD

**Issue by shaneosullivan** [reapit/foundations#4887]
**Is your feature request related to a problem? Please describe.**
The purpose of Master Plots is unclear, as mentioned briefly in the `property/masterId` and `property/isMaster` API fields.

**Describe the solution you'd like**
Please add better documentation for the usage of master plots. 
- Are they intended for multi-property developments, such as apartment blocks, or for something else?  
- Are there any consequences of using them, e.g. if a master property is deleted, are all related non-master properties deleted?  
- Are there any extra restrictions in place when a property has a `masterId`, e.g. the master cannot be deleted if it has related properties?  If not, what happens if the master is deleted and the sub-properties have a now invalid `masterId`?

**Describe alternatives you've considered**
I tried searching the docs (there aren't any) and Googling it, but nothing showed up.

**Comment by shaneosullivan** [comment]
@plittlewood-rpt thanks so much for working on this!  I'm looking at the current documentation on the site but can't find the change that was made.  If it has been deployed, would you mind adding a url here to it? I'd love to take a read.

**Comment by plittlewood-rpt** [comment]
Hi @shaneosullivan - the commentary is inline in the swagger documentation. If you look at the Swagger documentation `PropertyModel` there is some additional content at the header and also some new content on the `Property.Model._links` object. Let me know if you still can't find it. Thanks!

**Comment by plittlewood-rpt** [comment]
Hi @shaneosullivan the properties in the model shouldn't actually be being surfaced in the example as they don't get returned (they are used internally for building the links collection). To navigate around developments you need to solely use the links collection to do what you are wanting to do. I will get the issue with the example model being incorrect shortly.

**Comment by shaneosullivan** [comment]
@plittlewood-rpt pinging this again - will these fields be publicly shared, or should they not be used?
