### ISSUE TITLE
Extrafield Request "Pack URL"

### ISSUE THREAD

**Issue by Daramithes** [reapit/foundations#4905]
**Request**

In order for us to grant access to Semi-structured 'extras' field data, please provide the following information in this request:

- AAC
- Pack URL, located on the HR tab of a property. 
- In order to display home-report in our mobile application that uses PAAS backend.

![2021-09-01 14_18_01-AC Citrix Desktop - Desktop Viewer](https://user-images.githubusercontent.com/33520316/131678568-1ef6e0d1-59d3-41ce-b033-fce0c94d0000.png)

Also, as with previous request of ours, our third party developer Starberry will also need access to this extra field, unsure if they are to submit a seperate request or not so if you could advise that would be great.

Thanks!

**Comment by RWilcox-Reapit** [comment]
Hi again @Daramithes 

This has now been added and it's accessible by passing 'pHipUrl' to the query parameter 'extrasField' on either GET endpoint for properties.

Thanks
