### ISSUE TITLE
Extrafield - "Factor" 

### ISSUE THREAD

**Issue by Daramithes** [reapit/foundations#4909]
**Request**

In order for us to grant access to Semi-structured 'extras' field data, please provide the following information in this request:

- AAC
- "Factor" on Marketing Details screen for Lettings Properties.
- For our new mobile application, we require this to help provide a contact for our lettings management experience.

![image](https://user-images.githubusercontent.com/33520316/131700527-5c60bed5-fb20-41b8-aca5-44776f53c479.png)

**Comment by RWilcox-Reapit** [comment]
Hi @Daramithes 

This has now been added and it's accessible by passing 'pFactor' to the query parameter 'extrasField' on either GET endpoint for properties.

Thanks
