### ISSUE TITLE
Skipped fields when using POST applicants can cause some entities to not work as expected in AC

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#4914]
**Background context**
Where some fields in POST applicant payload are not entered, the resulting downstream data can be set to null which has downstream problems in agency cloud because of matching.

**Specification**
- Update DB package to rename existing `PatchValue` method to become `SetValueIfNotNull` 
- Ensure applicants entity constructer uses `SetValueIfNotNull` for incoming command values
- QA by ensuring matching works for applicants created with barebones payload and database record looks correct 
- Liaise with Sam C to correct data for AC

**Comment by eazynow** [comment]
@cbryanreapit I'm assuming this is in response to our (Areas) conversations with your support team?

**Comment by cbryanreapit** [comment]
@eazynow yes

**Comment by eazynow** [comment]
@cbryanreapit thanks. We are looking at putting a patch in to default as much as we can, but we cannot be sure it will be enough as the relationship between Foundations and the database, plus the logic in the desktop app queries is something Reapit maintains

**Comment by cbryanreapit** [comment]
@eazynow good to hear - we'll have a release that tightens up the behaviour at the platform end available soon, the work is already underway. It won't be a breaking API change.

**Comment by eazynow** [comment]
Thanks @cbryanreapit. Any idea roughly how long before you can get that fix live? It's just we need to keep our clients updated.

**Comment by eazynow** [comment]
I see @RWilcox-Reapit is on it, so I'd expect like 5 minutes tops 😉

**Comment by cbryanreapit** [comment]
Too early to say, best to track the issue as you'll see it go through review/QA/release.

**Comment by eazynow** [comment]
@cbryanreapit sure. I'll provide all the entities we generate:
#### POST contacts
```
{
    "title": null,
    "forename": "Jeff",
    "surname": "Linton",
    "active": true,
    "marketingConsent": "notAsked",
    "officeIds":
    [
        "ABC"
    ],
    "negotiatorIds":
    [
        "ABC"
    ],
    "metadata":
    {
        "areaCustomerId": "ffffffff-fff-ffff-ffff-ffffffffffff"
    },
    "primaryAddress":
    {
        "type": "primary",
        "line1": "Big Road",
        "line2": "Somewhere",
        "line3": "",
        "line4": "",
        "postcode": "EC2Y 5DN",
        "buildingNumber": "100"
    },
    "email": "notsure@email.com",
    "mobilePhone": "07761234567"
}
```

#### POST applicants
```
{
    "marketingMode": "renting",
    "active": true,
    "notes": "Area Lead 2021-09-02 15:39:17\nI am a random message\nlooking for three to four bedroom. looking for bigger property. \r\ntwo children 13 + 15year old.\nProperty RPT000001_L: 1 New Road, Somewhere, Surrey, TW28 8TA",
    "bedroomsMin": 1,
    "receptionsMin": 0,
    "bathroomsMin": 0,
    "departmentId": "G",
    "officeIds":
    [
        "ABC"
    ],
    "negotiatorIds":
    [
        "ABC"
    ],
    "related":
    [
        {
            "associatedId": "RPT21000001",
            "associatedType": "contact"
        }
    ],
    "metadata":
    {
        "areaLeadId": "ffffffff-fff-ffff-ffff-ffffffffffff",
        "areaPropertyId": "ffffffff-fff-ffff-ffff-ffffffffffff"
    },
    "renting":
    {
        "rentFrom": 1,
        "rentTo": 2250,
        "rentFrequency": "monthly"
    },
    "source":
    {
        "id": "ADV002",
        "type": "source"
    }
}
```

#### POST properties
```
{
    "marketingMode": "selling",
    "departmentId": "G",
    "internetAdvertising": false,
    "address":
    {
        "line1": "Some Road",
        "line2": "London",
        "line3": "",
        "line4": "",
        "postcode": "EC2Y 5DN",
        "buildingNumber": "5"
    },
    "negotiatorId": "ABC",
    "officeIds":
    [
        "ABC"
    ],
    "notes": "Area Lead 2021-09-02 13:32:16\n",
    "metadata":
    {
        "areaLeadId": "ffffffff-fff-ffff-ffff-ffffffffffff"
    },
    "selling":
    {
        "status": "preAppraisal"
    }
}
```

**Comment by plittlewood-rpt** [comment]
Hi @eazynow - if you have a replicable scenario in Agency Cloud Developer Edition please can you issue your payloads above and confirm if the issue is now resolved.
