### ISSUE TITLE
create-react-app using template issues 

### ISSUE THREAD

**Issue by ktre2017** [reapit/foundations#4921]
Hi,

I am new to Reapit and we need to build a marketplace app. I registered with developer portal and following the documentation.

I created a App in the portal ann configured urls to http://localhost:8080 

I following the following link to test it.

https://foundations-documentation.reapit.cloud/app-development/create-react-app-template

I downloaded the template using npx create-react-app etest --template @reapit/cra-template-foundations

Edited src/reapit.config.json with the following

{
  "appEnv": "local",
  "connectClientId": "4h1m6t3d9m8e3d8gedrf3ln4ts",
  "connectOAuthUrl": "https://connect.reapit.cloud",
  "platformApiUrl": "https://platform.reapit.cloud",
  "connectUserPoolId": "eu-west-2_eQ7dreNzJ",
  "marketplaceUrl": "https://marketplace.reapit.cloud/installed"
}

then run yarn start

I can see the Login dialog and after login I see the following error

TypeScript error in /etest/src/platform-api/configuration-api.ts(24,69):
Object is of type 'unknown'.  TS2571

    22 |     throw new Error('No response returned by API')
    23 |   } catch (err) {
  > 24 |     console.error('Error fetching Configuration Appointment Types', err.message)
       |                                                                     ^
    25 |   }
    26 | }
    27 |

Do we need any CRM license to execute it?

Please advise how to fix this and see the "welcome to reapit foundation" screen.

Thanks

**Comment by willmcvay** [comment]
@ktre2017 There are 2 problems here;

1. You can get rid of the  typescript error by removing `.message` from the console logged `err` in `src/platform-api/configuration-api.ts`. This is just because Typescript has updated and now treats all caught errors as `unknown` We will fix this as a bug our end.
2. Your app is misconfigured - when you set your app up, the re-direct uris do not include `http://localhost:8080` and http://localhost:8080/login` for the logout uri. You can set these values at `https://developers.reapit.cloud/apps/:appId` by hitting the edit app button and saving the changes.

**Comment by ktre2017** [comment]
Great. Thanks @willmcvay. It is working now.

Our solution is in PHP and we would like to use the same for building the Marketplace App to speed up our implementation. Do you have any library / code that can help us to integration this authentication process for the frontend?

Also we wanted to integrate with Reapit CRM desktop. Do we need to get Developer license for this?

Please advise.

Thanks

**Comment by willmcvay** [comment]
Great @ktre2017 glad you got sorted.

We don't support any PHP tooling I am afraid however, this development partner has open sourced some code that may be useful to you https://github.com/Northern-Estate-Agencies/reapit-foundations-php-client

Regarding the desktop CRM, yes, you will need a developer license if you want to test it yourself however, integrations are just rendered in a Chromium browser so there is no practical requirement to do this. If it works in a browser, it will work in the CRM.

**Comment by ktre2017** [comment]
Thank you @willmcvay for the inputs on desktop CRM and PHP. 

Please guide me how we can implement the following scenario. 

My requirement is we need to integrate with Reapit CRM where in CRM property details we wanted to place a button to open our app (if possible) or when our app is opened from CRM menu, we need to get the current property id to our App so that we can use Reapit REST APIs to fetch the property details and required information within our App and offer our services to the user.

Please advise how we can get the property id from the CRM and can this be achieved without CRM developer version installed. 

Thank you
Reddy

**Comment by willmcvay** [comment]
@ktre2017 Please refer to the Desktop API documentation on this https://foundations-documentation.reapit.cloud/api/desktop-api
