### ISSUE TITLE
Properties API is not reflecting updated letting and selling values

### ISSUE THREAD

**Issue by OdooHaus** [reapit/foundations#4929]
**Describe the bug**
We have witnessed a bug in the API that it's not reflecting the latest changes in the nested **Letting** and **Selling** JSON in the properties API, so whenever we update its value after some time of the property creation it does reflect these changes in client application but not an API response.

**To Reproduce**
Steps to reproduce the behaviour eg:

1. Create a property
2. Set some letting fee values
3. Save it and see the reflection in the API response
4. Update the letting fee value for the same property.
5. Save it and see the reflection in the API response, it won't appear.

**Expected behaviour**
The changes should reflect in the API response

**Comment by plittlewood-rpt** [comment]
Hi @OdooHaus  - please can you provide some JSON payloads you are sending to the various endpoints we can use to try and replicate the issue?

**Comment by OdooHaus** [comment]
Hi Pete,

Thank you for your email.

Please see the below as requested.

Request:
https://platform.reapit.cloud/properties/?id=DBI710192


Response:
{
    "_embedded": [
        {
            "id": "DBI710192",
            "created": "2021-06-28T06:45:44Z",
            "modified": "2021-08-15T12:20:15Z",
            "marketingMode": "letting",
            "currency": "AED",
            "alternateId": null,
            "address": {
                "buildingName": "Villa E127, Sawgrass (NOT LIVE)",
                "buildingNumber": "",
                "line1": "Whispering Pines",
                "line2": "Jumeirah Golf Estates",
                "line3": "Dubai",
                "line4": "",
                "postcode": "",
                "countryId": "AE",
                "geolocation": {
                    "latitude": 25.023262,
                    "longitude": 55.197094
                }
            },
            "areaId": "ear",
            "strapline": "Independent Sawgrass | Large Rectangle Pool",
            "description": "haus & haus is proud to present to the market this stunning 4 bedroom Sawgrass villa in the sought after village of Whispering Pines. The property offers a fully integrated kitchen, large rectangle swimming pool and sits on a extended plot. Currently vacant and available to move in.",
            "longDescription": "haus & haus is proud to present to the market this stunning four bedroom independent Sawgrass type villa in the sought after village of Whispering Pines.\r\rThe property sits on a large extended plot and offers a rectangle swimming pool to the rear.\r\rInternally are four double en-suite bedrooms with the master located on the ground floor. The kitchen is fully integrated with Miele appliances.\r\rMaids room is located externally. This unit is also offered with a golf buggy.\r\rBroker fee - 5% + VAT\rSecurity deposit - 5%\r\rCall Peter (BRN: 37900) on +971 (0)50 300 6205 for more information, to arrange a viewing or to make an offer.\r\rFor further details or to arrange viewings, please contact our Head Office on +971 (0)4 302 5800, alternatively visit our website www.hausandhaus.com<http://www.hausandhaus.com> where you will find our full selection of properties available both for sale and rent.",
            "summary": "Sawgrass Type\r4 bedrooms\r5 bathrooms\rRectangle Swimming pool\rVacant\rLarge Extended Plot\rVery private allocation\rCall Peter on +971 (0)50 300 6205",
            "departmentId": "G",
            "negotiatorId": "CMS",
            "bedrooms": 4,
            "receptions": 2,
            "bathrooms": 5,
            "councilTax": null,
            "internetAdvertising": false,
            "viewingArrangements": null,
            "videoUrl": null,
            "videoCaption": null,
            "video2Url": null,
            "video2Caption": null,
            "notes": "Property copied from reference: DUB181522Access (open/tenant/call owner etc)\r\rDate available\r\rPrice (firm/negotiable)\r\rNo of Cheques\r\rWork that's been agreed to be done (painted/cleaned/landscaping etc)\r\rLocation (close to pool/shop etc)\r\rView (back2back/lake/golf course etc)\r\rDocuments\r\rPOA?\r\rNationality\r\rMaintenance Contract\r\rOwner in Dubai to sign?",
            "boardStatus": null,
            "boardNotes": null,
            "boardUpdated": null,
            "archivedOn": null,
            "fromArchive": false,
            "externalArea": null,
            "internalArea": {
                "type": "squareFeet",
                "min": 3985.0,
                "max": 0.0
            },
            "epc": {
                "exempt": false,
                "eer": 0,
                "eerPotential": 0,
                "eir": 0,
                "eirPotential": 0
            },
            "selling": null,
            "letting": {
                "instructed": "2018-04-10",
                "availableFrom": "2022-09-05",
                "availableTo": null,
                "rent": 325000.0,
                "rentFrequency": "annually",
                "furnishing": [],
                "term": "long",
                "status": "tenancyCurrentUnavailable",
                "agentRole": "",
                "landlordId": "DUB150866",
                "brochureId": null,
                "managementFee": null,
                "lettingFee": null,
                "qualifier": "askingRent"
            },
            "type": [],
            "style": [],
            "situation": [
                "garden",
                "balcony"
            ],
            "parking": [
                "garage"
            ],
            "age": [
                "modern"
            ],
            "locality": [],
            "rooms": [],
            "officeIds": [
                "DBI"
            ],
            "lostInstructionDate": null,
            "lostInstructionNote": null,
            "extrasField": {},
            "_eTag": "\"436317DEF290D1B9A529324F10197E26\"",
            "_links": {
                "self": {
                    "href": "/properties/DBI710192"
                },
                "images": {
                    "href": "/propertyImages/?propertyId=DBI710192"
                },
                "documents": {
                    "href": "/documents/?associatedType=property&associatedId=DBI710192"
                },
               "offers": {
                    "href": "/offers/?propertyId=DBI710192"
                },
                "appointments": {
                    "href": "/appointments/?propertyId=DBI710192"
                },
                "negotiator": {
                    "href": "/negotiators/CMS"
                },
                "offices": {
                    "href": "/offices/?id=DBI"
                },
                "department": {
                    "href": "/departments/G"
                },
                "landlord": {
                    "href": "/landlords/DUB150866"
                },
                "area": {
                    "href": "/areas/ear"
                }
            },
            "_embedded": null,
            "metadata": {}
        }
    ],
    "pageNumber": 1,
    "pageSize": 25,
    "pageCount": 1,
    "totalPageCount": 1,
    "totalCount": 1,
    "_links": {
        "self": {
            "href": "/properties/?PageNumber=1&PageSize=25&id=DBI710192"
        },
        "first": {
            "href": "/properties/?PageNumber=1&PageSize=25&id=DBI710192"
        }
    }
}





Please let me know at your earliest on resolving this issue.

Thanks,

***@***.***
Farhan Aqil
UAECA, FCCA, CIA, M.Com, Bsc (Hons)
Accounts Director
m: +971 54 763 3758<tel:+971+54+763+3758>  |
***@***.******@***.***>  |
***@***.***
Chat via WhatsApp<https://api.whatsapp.com/send?l=en&phone=971547633758&text>
***@***.***<https://www.hausandhaus.com/>
***@***.*** <https://www.hausandhaus.com/#newsletter-form>     ***@***.*** <https://www.feefo.com/en-US/reviews/haus-haus?displayFeed-backType=SERVICE&timeFrame=ALL&timeFrame=ALL>
haus & haus Real Estate Broker
www.hausandhaus.com<https://www.hausandhaus.com/>
[Facebook icon]<https://www.facebook.com/hausandhaus>
[LinkedIn icon]<https://twitter.com/hausandhaus>
[Twitter icon]<https://www.instagram.com/hausandhaus/>
[Google Plus icon]<https://www.linkedin.com/company/haus-&-haus>
[Youtbue icon]<https://www.youtube.com/hausandhaus-videos?sub_confirmation=1>
[Pinterest icon]<https://www.pinterest.com/hausnhaus>
***@***.***<https://www.hausandhaus.com/latest-news/blog/814-the-haus-haus-pledge-during-the-covid-19-period>
Our Covid-19 guidelines here<https://www.hausandhaus.com/latest-news/blog/814-the-haus-haus-pledge-during-the-covid-19-period>
***@***.***<https://www.hausandhaus.com/about-us/awards>

**Comment by plittlewood-rpt** [comment]
Hi @OdooHaus - please can you advise how much time you left between making the update in Agency Cloud and checking for the update on the API? Database changes have to propagate across our network and at times of heavy network traffic this doesn't happen instantly. I've just tested this myself and it seems to be working without a problem so it's likely you may just not have waited long enough for the change to get round to all our databases. Our database clusters have several servers which in a master-slave replication setup so I suspect the update just hadn't reached the server we read data back from on your subsequent GET request. One way you should be able to tell if the record has actually updated or not is to check whether or not the modified timestamp changes.

**Comment by OdooHaus** [comment]
Hi Pete,

We have re-run the API load for the property ID DBI710192, we are still unable to get the updated “Initial Rent” and “Letting Fee” amounts (Attached Pic). We have also attached the Reapit screenshot showing the “Initial Rent” and “Letting Fee” amounts in the system for same property ID. Please be noted that the “Initial Rent” and “Letting Fee” amounts are added into the Reapit at “Financial and Extensions” page and this information has been updated in the system on 15/08/2021. Kindly let us know the process to extract this financial information from the “Financial and Extensions” page using API.

Thanks,

***@***.***
Farhan Aqil
UAECA, FCCA, CIA, M.Com, Bsc (Hons)
Accounts Director
m: +971 54 763 3758<tel:+971+54+763+3758>  |
***@***.******@***.***>  |
***@***.***
Chat via WhatsApp<https://api.whatsapp.com/send?l=en&phone=971547633758&text>
***@***.***<https://www.hausandhaus.com/>
***@***.*** <https://www.hausandhaus.com/#newsletter-form>     ***@***.*** <https://www.feefo.com/en-US/reviews/haus-haus?displayFeed-backType=SERVICE&timeFrame=ALL&timeFrame=ALL>
haus & haus Real Estate Broker
www.hausandhaus.com<https://www.hausandhaus.com/>
[Facebook icon]<https://www.facebook.com/hausandhaus>
[LinkedIn icon]<https://twitter.com/hausandhaus>
[Twitter icon]<https://www.instagram.com/hausandhaus/>
[Google Plus icon]<https://www.linkedin.com/company/haus-&-haus>
[Youtbue icon]<https://www.youtube.com/hausandhaus-videos?sub_confirmation=1>
[Pinterest icon]<https://www.pinterest.com/hausnhaus>
***@***.***<https://www.hausandhaus.com/latest-news/blog/814-the-haus-haus-pledge-during-the-covid-19-period>
Our Covid-19 guidelines here<https://www.hausandhaus.com/latest-news/blog/814-the-haus-haus-pledge-during-the-covid-19-period>
***@***.***<https://www.hausandhaus.com/about-us/awards>

**Comment by OdooHaus** [comment]
Hi Pete,

I will appreciate if you can check the below email and reply on it as we have to finalize our ERP implementation.

Thanks,

From: Farhan Aqil
Sent: Sunday, September 12, 2021 2:40 PM
To: reapit/foundations ***@***.***>; reapit/foundations ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [reapit/foundations] Properties API is not reflecting updated letting and selling values (#4929)

Hi Pete,

We have re-run the API load for the property ID DBI710192, we are still unable to get the updated “Initial Rent” and “Letting Fee” amounts (Attached Pic). We have also attached the Reapit screenshot showing the “Initial Rent” and “Letting Fee” amounts in the system for same property ID. Please be noted that the “Initial Rent” and “Letting Fee” amounts are added into the Reapit at “Financial and Extensions” page and this information has been updated in the system on 15/08/2021. Kindly let us know the process to extract this financial information from the “Financial and Extensions” page using API.

Thanks,

***@***.***
Farhan Aqil
UAECA, FCCA, CIA, M.Com, Bsc (Hons)
Accounts Director
m: +971 54 763 3758<tel:+971+54+763+3758>  |
***@***.******@***.***>  |
***@***.***
Chat via WhatsApp<https://api.whatsapp.com/send?l=en&phone=971547633758&text>
***@***.***<https://www.hausandhaus.com/>
***@***.*** <https://www.hausandhaus.com/#newsletter-form>     ***@***.*** <https://www.feefo.com/en-US/reviews/haus-haus?displayFeed-backType=SERVICE&timeFrame=ALL&timeFrame=ALL>
haus & haus Real Estate Broker
www.hausandhaus.com<https://www.hausandhaus.com/>
[Facebook icon]<https://www.facebook.com/hausandhaus>
[LinkedIn icon]<https://twitter.com/hausandhaus>
[Twitter icon]<https://www.instagram.com/hausandhaus/>
[Google Plus icon]<https://www.linkedin.com/company/haus-&-haus>
[Youtbue icon]<https://www.youtube.com/hausandhaus-videos?sub_confirmation=1>
[Pinterest icon]<https://www.pinterest.com/hausnhaus>
***@***.***<https://www.hausandhaus.com/latest-news/blog/814-the-haus-haus-pledge-during-the-covid-19-period>
Our Covid-19 guidelines here<https://www.hausandhaus.com/latest-news/blog/814-the-haus-haus-pledge-during-the-covid-19-period>
***@***.***<https://www.hausandhaus.com/about-us/awards>

**Comment by plittlewood-rpt** [comment]
Hi @OdooHaus  - we do not work on a Saturday and Sunday. I will check the above shortly. Thanks

**Comment by plittlewood-rpt** [comment]
Hi @OdooHaus - there is no letting fee or management fee currently set on this property so the response you are receiving is correct

![image](https://user-images.githubusercontent.com/30798627/133037555-6883440f-4969-4ca2-85ab-f294adb2d9f7.png)

If you set one then I'd expect it to come through in the API

Thanks
Pete

**Comment by OdooHaus** [comment]
Hi Pete,

Thank you for your reply on this.

I’ll check with my team and revert back to you.

Best regards,

**Comment by OdooHaus** [comment]
Hi Pete,

Please see the below email shared by the Development team of Odoo ERP.

We are not getting the required information from Reapit’s team. Yes, what they have shared is same as we are getting as well but in our request, we clearly required from them the information updated under the “Financial and Extensions” page, which is updated by the Admin team of haus & haus. Please see attached screenshots of email sent by Admin team for the information available in Reapit and the data from Reapit which is integrated into Odoo for your reference.


***@***.***


Thanks,

From: Farhan Aqil
Sent: Monday, September 13, 2021 11:01 AM
To: reapit/foundations ***@***.***>; reapit/foundations ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [reapit/foundations] Properties API is not reflecting updated letting and selling values (#4929)

Hi Pete,

Thank you for your reply on this.

I’ll check with my team and revert back to you.

Best regards,

**Comment by plittlewood-rpt** [comment]
Hi @OdooHaus  I cannot see the attachments. Please can you paste them into the issue rather than replying to the email.

Thanks

**Comment by OdooHaus** [comment]
Hi Pete,

Sure, please see the pasted images below.

***@***.***


***@***.***

Thanks,

**Comment by plittlewood-rpt** [comment]
Hi @OdooHaus I still cannot see them as it looks like you replied to the email. You'll need to physically open the issue on Github and paste them into a new comment. Thanks

**Comment by OdooHaus** [comment]
Hi Pete,

Sure, we will paste the images in Github now.

Many thanks,

**Comment by OdooHaus** [comment]
<img width="1293" alt="DBI710192 API INFO" src="https://user-images.githubusercontent.com/86656047/133065446-76514033-99a5-4bad-ac30-970ec29e4524.png">
![DBI710192](https://user-images.githubusercontent.com/86656047/133065463-d9e5d8fb-2298-49b1-9a3b-974fc3d17e2d.JPG)
Hi as highlighted in the attached images, we are unable to get the Initial Rent and Letting Fee under the "Financial & Extensions" tab. Kindly let us know how to extract such information using API.

**Comment by plittlewood-rpt** [comment]
Hi @OdooHaus I'm very confused by this. As mentioned previously, there is no information stored in these fields on the property in question.

Can you provide a screenshot showing the populated data in Agency Cloud vs the API as I think we've got crossed wires somewhere here. As you can see below, when I populate the fields you mention with data and access the property in the API, the data is returned as I'd expect. Please note that I have removed the 5% again after providing this example

![image](https://user-images.githubusercontent.com/30798627/133067515-890aa120-02ab-493e-98ab-fd0a066a9992.png)


Thanks
Pete

**Comment by plittlewood-rpt** [comment]
If you are talking about data on the tenancy (rather than the property), that data would normally be accessed via the tenancies API (in your case `GET /tenancies/DUB210717`) however we do not currently expose the letting fee information in this API but you will be able to get to the initial rent using this method. To expose the fee information you could need to log a feature request on the Github project.

**Comment by plittlewood-rpt** [comment]
Hi @OdooHaus  I can see you have now opened ticket #4977 so I will now close this ticket down.

**Comment by OdooHaus** [comment]
Hi Pete,

Thanks and noted.

I’ll really appreciate if we can have this ticket resolved at the earliest.

Best regards,

**Comment by OdooHaus** [comment]
Hi Pete,

Please let us have an update on this issue as we are waiting to finalize our ERP implementation.

Thanks,

From: Farhan Aqil
Sent: Tuesday, September 14, 2021 12:15 PM
To: reapit/foundations ***@***.***>; reapit/foundations ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [reapit/foundations] Properties API is not reflecting updated letting and selling values (#4929)

Hi Pete,

Thanks and noted.

I’ll really appreciate if we can have this ticket resolved at the earliest.

Best regards,

**Comment by plittlewood-rpt** [comment]
Hi @OdooHaus  please track the relevant ticket, #4977 for updates. You will see it has been moved to our near term list so the work has been committed to for a future upcoming sprint. Many thanks

**Comment by OdooHaus** [comment]
Hi Pete,

Thanks for your reply. Please let me know when the future upcoming sprint will happen, like today or tomorrow. I just need to update everyone involved in the ERP implementation for the status of this.

Best regards,
