### ISSUE TITLE
Ability to Update Meter Readings for a Current Tenancy via the Foundations API

### ISSUE THREAD

**Issue by otrace** [reapit/foundations#4931]
**Background context**

It's been reported that it is nor, currently, possible to update meter readings via the Foundations API when a Tenancy has a status of Tenancy Current. 

Can the Foundations API be updated so this is possible? During the lifetime of a Tenancy, multiple property visits may be carried out where an update to meter readings are required. It is not restricted to before a Tenancy Starts or after it ends

**Specification**
- Adjust the tenancy `Update` method to allow updates to occur to tenancy current status tenancies when only those fields are provided
- Where other fields are included, continue to return commandResult.fail, but provide a helpful message indicating why

**Comment by plittlewood-rpt** [comment]
Original ticket where this was implemented: #3590

**Comment by plittlewood-rpt** [comment]
Hi @otrace 

Can you let us know who has reported this please? I'd also ask if you can encourage whatever developer you're working with to log their own issues so they can track them. 

Cheers
Pete
