### ISSUE TITLE
Adding/removing the same negotiator in "Negotiator/Office" fires incorrect payload in webhook

### ISSUE THREAD

**Issue by bisoh** [reapit/foundations#4939]
**Description**

We have a webhook that is subscribed to Appointments (create/update/delete). 
When creating an appointment and then adding and removing a negotiator a few times, I get a webhook call for a 'Appointment created' instead of a 'Appointment modified'. Both payloads have the same entityId.

**Steps to reproduce the behaviour:**
1. Create an appointment with negotiator A in the "Accompanied" field.
2. Save
3. Edit the appointment and select negotiator B in the "Negotiator/Offices" and Save
4. Edit the appointment and remove negotiator B and save.
5. Check the webhook transaction log. You will find an "Appointment created" event fired on the webhook instead of an "Appointment modified". [**_you may need to repeat steps 3-6 for it to happen. Check logs after every save. Sometimes it happens after the second addition, sometimes on removal_**]

_If you download the payload (from the transaction log) for the last 2 events (modified , created), they will have the same entityId._

**Expected behaviour**
To get a webhook call for "Appointment modified" (including the new and old data) instead of a "Appointment created".

**Screenshots**
If applicable, add screenshots to help explain your problem. Please ensure that screenshots do not include sensitive data such as personally identifiable information.

**Device (please complete the following information for web issues):**
 - Device: PC 
 - OS: Win10 20H2
 - RPS: Developer Edition v12.132.2

**Additional context**
An example from sandbox for appointments with this issue MKT2101164 & MKT2101165

**Comment by plittlewood-rpt** [comment]
This issue is also apparent when adding/removing/re-adding an additional applicant, the same .modified -> .created behaviour occurs. PR out to fix this

**Comment by plittlewood-rpt** [comment]
Hi @bisoh this issue has now been resolved. Thanks for bringing it to our attention

**Comment by bisoh** [comment]
Thanks Pete. Has this been released ? If not when would it be?

**Comment by plittlewood-rpt** [comment]
Hi @bisoh yes it's been released. Thanks
