### ISSUE TITLE
Main tenant not populated after creating tenancy using applicantId

### ISSUE THREAD

**Issue by DonGiulio** [reapit/foundations#4940]
**Describe the bug**
When I do a post /applicants/ the main tenant is not populated, all the tenants involved are marked as 'additional'.

**To Reproduce**
* create a property post /property/...
* create a few contacts post /contact/...
* create an applicant with the contacts from above
* create a tenancy using one of the new applicants (see discussion comments for example payload)
* Open the new tenancy in agency cloud and observe that the main tenant information is not set

request similar to:

```
{:renting=>{:rentFrom=>10, :rentTo=>9999900, :rentFrequency=>"weekly"},
 :marketingMode=>"renting",
 :active=>true,
 :departmentId=>"G",
 :related=>[{:associatedId=>"LBR21007973", :associatedType=>"contact"}],
 "negotiatorIds"=>["SAL"],
 "officeIds"=>["LBR"]}
```

**Expected behaviour**
the first contact in the related of the applicant is marked as main tenant in the property
 
** actual behaviour ** 
all the tenants are in the 'additional tenants' field.

**Screenshots**
![image](https://user-images.githubusercontent.com/4629740/132346908-d2fcda64-93ef-4874-ad2b-b87c05b7663f.png)

**Specification**
- Update tenancies API to lookup and set the mainTenCode property when creating new tenancies

**Comment by plittlewood-rpt** [comment]
Hi @DonGiulio  please can you submit the payload you are sending to POST /tenancies?

**Comment by plittlewood-rpt** [comment]
Thanks - we'll look into this as part of our next refinement session. Please continue to follow the ticket to track it's progress

**Comment by RWilcox-Reapit** [comment]
Hi @DonGiulio ,
Thanks for bringing this to our attention. 
This has now been resolved.
