### ISSUE TITLE
"Log in with Reapit" button usage issue

### ISSUE THREAD

**Issue by ktre2017** [reapit/foundations#4954]
Hi,

I am trying to use "Log in with Reapit" button and when I run it, I could see Login button as expected but when I click I am getting error as "https://connect.reapit.cloud/error?error=redirect_mismatch&client_id=1gunpvl3ftfccn62vj9tnrsai8". I think I have configured redirect url correctly. 

My test Index.html code is as follows. Can you please advise why I am getting this error and how to fix it?

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Reapit Login test</title>
  </head>
  <body>
<div id="reapit-connect-component"></div>
<script src="https://web-components.prod.paas.reapit.cloud/reapit-connect-component.js"></script>
<script>

  const connectHasSessionCallback = (reapitConnectBrowserSession) => {
    reapitConnectBrowserSession.connectSession().then(session => {
      console.log('Session is', session)
      fetch('https://platform.reapit.cloud/appointments', {
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${session.accessToken}`,
          'api-version': '2020-01-31'
        }
      })
      .then(res => res.json())
      .then(appointments => console.log('Appointmemts are', appointments))
    })
  }

  ReapitConnectComponent && new ReapitConnectComponent({
    connectClientId: '1gunpvl3ftfccn62vj9tnrsai8',
    connectUserPoolId: 'eu-west-2_eQ7dreNzJ',
    connectOAuthUrl: 'https://connect.reapit.cloud',
    connectLoginRedirectPath: 'http://localhost:8080',
    connectLogoutRedirectPath: 'http://localhost:8080/login',
    connectContainerId: '#reapit-connect-component',
    connectHasSessionCallback
  })
</script>
  </body>
</html>

_Originally posted by @ktre2017 in https://github.com/reapit/foundations/issues/1256#issuecomment-915916142_

**Comment by willmcvay** [comment]
@ktre2017 Please refer to the docs https://foundations-documentation.reapit.cloud/app-development/web#sign-in-with-reapit your `connectLoginRedirectPath` and `connectLogoutRedirectPath` values are incorrectly configured - they should be relative paths not absolute urls

**Comment by ktre2017** [comment]
Hi @willmcvay, Thank you for your reply and info on Redirect Paths. I have changed the paths as per the docs and it seems to be working now.

**Comment by willmcvay** [comment]
Great, closing this issue
