### ISSUE TITLE
Reporting Server Error

### ISSUE THREAD

**Issue by LyndsayCremin** [reapit/foundations#4965]
Hi There, 

We are encountering an error when attempting to refresh the diary table in Power BI - please see image included. 

I have tried using both, the Snowflake and ODBC connectors in Power BI but am receiving the same error message for the 'diary' table on both. 
 
I can connect to the data warehouse and refresh all of the other tables I have loaded into Power BI but, not the ‘diary’ table. 

Unfortunately, the error refreshing the diary table results in the whole dataset refresh failing. The reports combine data from a number of tables so, we need them all to be refreshed at the same time. 

The last successful refresh was on the evening of Monday 6th September. 

If you need anything further from me, don't hesitate to let me know. 

Many thanks, 

Lyndsay 
![Diary table error](https://user-images.githubusercontent.com/90459251/132858209-02f5ee28-d144-4f8b-b447-fedc67a3c34f.PNG)

**Comment by plittlewood-rpt** [comment]
Hi @LyndsayCremin  thanks for bringing this to our attention. In the data warehouse app please can you delete the share and reprovision it. I think this problem will then resolve itself if you could confirm. I'll keep this ticket open so we can investigate the underlying cause

**Comment by plittlewood-rpt** [comment]
Hi @LyndsayCremin  - whilst we sort the access issue out I've just reprovisioned the schema for you. Please can you let me know if you are still seeing the error in Power BI

**Comment by LyndsayCremin** [comment]
Thanks @plittlewood-rpt , I am no longer seeing the error but, the refreshes are hit and miss. I was able to refresh one dataset manually but, unfortunately it failed twice on the scheduled refresh - I have included a screenshot of the error.

In addition, it took 3 attempts for me to manually refresh another dataset via Power BI desktop, as it said I couldn't connect to the server - to make sure the server was on and the credentials are correct. 

The credentials are correct and the dataset did eventually refresh on the third attempt so, I am not sure why we are encountering this issue?

![image](https://user-images.githubusercontent.com/90459251/133058163-1fb56c5a-ca46-48e7-9a6d-cdccb1b618b1.png)

Do you know what caused the previous error? Was there an issue with the view on the diary table?

Many thanks, 

Lyndsay

**Comment by plittlewood-rpt** [comment]
Hi @LyndsayCremin 

I still need to look at the underlying cause. It's likely relate to an Agency Cloud upgrade which altered the data structure which is an action that requires the schema to be reprovisioned in the data warehouse - it's something we are aware of and looking into separately already.

The time of that error was about when I reprovisioned the dataset for you which may well be what caused it. Can you let me know if it occurs again?

Thanks
Pete

**Comment by plittlewood-rpt** [comment]
@LyndsayCremin once we are happy the immediate problem is resolved, please track ticket https://github.com/reapit/foundations/issues/4973 where we will make a small change to the warehouse routines to prevent a similar occurrence in the future.

**Comment by plittlewood-rpt** [comment]
Closing this ticket as update to provisioning service to safeguard against underlying schema changes to be implemented in #4973
