### ISSUE TITLE
Data Warehouse App

### ISSUE THREAD

**Issue by LyndsayCremin** [reapit/foundations#4966]
Hi There, 

We are encountering an issue with the data warehouse app in the RPS desktop application. It appears as though we haven't provisioned any user accounts, but we have set up one account which is currently being used for our Power BI integration with the reporting server. 

I have included some screenshots - one of the error message and another of the user screen. 
![DataWarehouse Error](https://user-images.githubusercontent.com/90459251/132859242-5b9561f3-9d2e-4bd8-9500-7cfb21854aab.png)
![UserScreen](https://user-images.githubusercontent.com/90459251/132859245-88d31a52-e4cf-421e-b364-8f19e2a7324c.png)

Any help would be greatly appreciated. 

Many thanks, 

Lyndsay

**Comment by plittlewood-rpt** [comment]
Hi @LyndsayCremin please can you confirm the email addres you are logging into the app with?

**Comment by LyndsayCremin** [comment]
Hi @plittlewood-rpt, the email address is darragh.mcgrath@sherryfitz.ie

**Comment by plittlewood-rpt** [comment]
Thanks - interesting, i can see the subscription at this end. Let me do some digging

**Comment by plittlewood-rpt** [comment]
@LyndsayCremin  I think this is because Darragh's account is currently in Sandbox Mode. If he logs into the developer portal and changes the toggle switch on the Organisation tab to "Use Sherry Fitzgerald data" and logs out/back in to the data warehouse app I _think_ that'll solve it. Can you let me know either way. If it does fix it we probably need to address this at some point so I can raise another ticket to cover that off

**Comment by LyndsayCremin** [comment]
Thanks @plittlewood-rpt , that change has been made but unfortunately I am getting a pop up to say it is still in the sandbox mode - is there something else we need to do?

I have logged in and out of the system twice and tested it. 

![DataChange](https://user-images.githubusercontent.com/90459251/132875554-747202a0-5b54-42ec-beac-6d6eb8fcc6c9.png)
![Sandbox](https://user-images.githubusercontent.com/90459251/132875558-bfb0c199-2d58-48d9-a41f-b6aef2a30d18.PNG)

**Comment by plittlewood-rpt** [comment]
Hi @LyndsayCremin  that popup will always be there in the developer portal (a little confusing so I'll mention it to our product owner to pick up). Can you see if the warehouse app will list your subscriptions now?

**Comment by LyndsayCremin** [comment]
Ah ok, no unfortunately it is still the same. Additionally, I actually can't see the data warehouse app in the browser version developer portal, only under the 'Apps' in the Reapit desktop application. I used to be able to access it in the browser as, that is where the user account was provisioned, not in the desktop application.

**Comment by plittlewood-rpt** [comment]
It should be accessible in both which is odd. The direct link to the app is https://data-warehouse-app.reapit.cloud/ if you want to give that a try

**Comment by LyndsayCremin** [comment]
Sorry @plittlewood-rpt , I can see that now. Unfortunately, it is still saying there is no user account provisioned?

**Comment by plittlewood-rpt** [comment]
Hi @LyndsayCremin - please can I ask you to login again as Darragh and let me know when you've done it. I just want to try and intercept the request at this end to see what attributes are being sent with the request.

**Comment by LyndsayCremin** [comment]
Hi @plittlewood-rpt , no problem I have logged in as Darragh now.

**Comment by plittlewood-rpt** [comment]
Thanks! Will check it out this end

**Comment by plittlewood-rpt** [comment]
@LyndsayCremin I think this is due to to Darragh's Agency Cloud account being assigned to an office group which isn't being handled correctly as I've been able to replicate the problem with a test user when I move it into an office group. I'm not sure who manages your office groups (via the Marketplace Management App).

**Comment by LyndsayCremin** [comment]
Thanks @plittlewood-rpt , should his account not be assigned to an office group or do we need to change a setting? I can ask my colleagues who manage the office groups to make the required change.

**Comment by plittlewood-rpt** [comment]
@LyndsayCremin it's a bug that we need to resolve however in the interim if the Head Office group is not actually being used it can just be disabled which should give you access back to the Data Warehouse app using that account. I'm just investigating in a bit more detail at this end. It might be that I can push a fix out today for it in which case you may be able to get by for now

**Comment by LyndsayCremin** [comment]
Hi @plittlewood-rpt , I just wanted to check in to see if your further investigations uncovered anything? Do you think you will be able to push out a fix for it?

**Comment by plittlewood-rpt** [comment]
Hi @LyndsayCremin this should be resolved shortly. There is a fix building now which should be out within the hour all being well.

**Comment by plittlewood-rpt** [comment]
HI @LyndsayCremin this fix has just gone out, please can I ask you to log back in as Darragh and confirm that the subscription is now showing correctly?

**Comment by LyndsayCremin** [comment]
Thanks @plittlewood-rpt , yes that is showing now. Many thanks for all your help in resolving the issue.

**Comment by plittlewood-rpt** [comment]
No problem. Thanks for bringing it to our attention. I'll close out this ticket now.
