### ISSUE TITLE
Add the ability to launch apps directly from the Match window

### ISSUE THREAD

**Issue by designreact** [reapit/foundations#4968]
**Is your feature request related to a problem? Please describe.**
We want to add user specific tracking parameters to match email links, in time also sending match notifications via other channels such as SMS and WhatsApp.

**Describe the solution you'd like**
We want to add/configure a button on the match window (see screenshot), this button would send match data into a foundations app. Our app would orchestrate sending match emails adding the relevant user specific parameters to property links.

**Describe alternatives you've considered**
- Intercept the email in MS exchange, prevent sending of the original email, create and send a new email for each bcc addressee.
- Create a foundations app which recreates existing match functionality, write the results back into journal (journal API would need an update to allow non-Misc. entries to be written).
- Create a watch folder on negotiators computers, export match data into xml, save to watch folder. Watch tasks sends export to API for processing, write results back into journal.
- Request a new saved match API from the Reapit team so neg's saved matches can be read by our foundations app.

**Additional context**
Ability to track individual user interactions with marketing emails is a standard feature of various CRM systems. Enabling support via “Match apps” would be great for my client as well as many others. Adding "Match Apps" could open the door to integrate match email tracking with SalesForce and Adobe marketing platforms.

![image](https://user-images.githubusercontent.com/6464260/132879465-25c42966-1e7d-4ad3-90b4-01865f960922.png)

**Comment by plittlewood-rpt** [comment]
@HollyJoyPhillips this will need to go through desktop team via Sab. Can we discuss on refinement

**Comment by plittlewood-rpt** [comment]
Hi @designreact - this is in AgencyCloud v12.142.0 and later - I'll close out this ticket now as you'll get the updates through the AC channels as it's ready to be deployed to you.
