### ISSUE TITLE
Update data warehouse provisioning routine to apply field selection logic

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#4973]
**Specification**
- As per https://github.com/reapit/foundations/issues/4813
- For the operational table views, call out each column name

**Comment by LyndsayCremin** [comment]
Hi @plittlewood-rpt , apologies I wasn't sure whether to comment on this ticket or #4965  . Unfortunately, two of the dashboards have failed to refresh this morning on their scheduled refresh. I am getting the same error as yesterday of being unable to connect to the data source. Is there anything I need to do from my end? It appears to be an irregular occurrence as they were refreshing ok yesterday afternoon.

**Comment by plittlewood-rpt** [comment]
No problem. What error did you get this morning? Was it the error about the number of columns changing or a connectivity error?

**Comment by LyndsayCremin** [comment]
It was the connectivity error - unable to connect to data source.

**Comment by LyndsayCremin** [comment]
Hi @plittlewood-rpt , I just wanted to check in to see if you managed to find out why I am encountering the connectivity issue.

I had it again this morning - please see screenshot below.

![image](https://user-images.githubusercontent.com/90459251/133576168-30132b27-bd67-46c1-9522-1176cc0cb6a5.png)

**Comment by plittlewood-rpt** [comment]
Hi @LyndsayCremin  not yet - I need to speak to our infrastructure team about it as it looks to be something to do with PowerBI itself rather than the data warehouse. I'll revert back once I've spoken to them

**Comment by LyndsayCremin** [comment]
Thanks @plittlewood-rpt, much appreciated.

**Comment by plittlewood-rpt** [comment]
Hi @LyndsayCremin this looks like an issue between the Azure platform that PowerBI uses in the background and the data warehouse. There are a few people who seem to have had the same issue who have suggested altering Privacy settings on your dashboard (and Azure account for your organisation if you have one) may resolve the problem. Here is the link if you want to have a read: https://community.powerbi.com/t5/Service/Unable-to-connect-to-data-source-undefined/td-p/607443

**Comment by LyndsayCremin** [comment]
Thanks @plittlewood-rpt

**Comment by plittlewood-rpt** [comment]
Hi @LyndsayCremin did you manage to get this sorted?
