### ISSUE TITLE
Missing fields on applicant endpoint for matched properties and viewed properties

### ISSUE THREAD

**Issue by jaetooledev** [reapit/foundations#4979]
**Is your feature request related to a problem? Please describe.**
The legacy RDA API used to give back fields to see what properties have been matched to an applicant and also their viewed properties. This is now missing on the foundations API.

**Describe the solution you'd like**
We are in desperate need of these fields adding back in to progress with our refactors away from the legacy API.

**Describe alternatives you've considered**
I'm unaware of any alternative ways to get this data from Reapit but would be open to any alternatives.

**Comment by plittlewood-rpt** [comment]
Hi @jaetooledev - I think you should be able to get what you are wanting from 

`GET /journalEntries/?typeId=MA&typeId=BS&typeId=DS&associatedId=APP210001&associatedType=applicant`

Where MA, and BS, and DS are the journal codes for Match, Brochure Sent and Details Sent respectively, and APP210001 is the code of the applicant you're interested in. 

To get viewings for an applicant use

`GET /appointments?attendeeId=APP210001&attendeeType=applicant[&typeId=VW]`

Where APP210001 is the applicant you're interested and, optionally, VW is the appointment code for a Viewing

Does this give you what you're after?

**Comment by jaetooledev** [comment]
Hi Pete,
Thanks for this, I'll close this for now while we do some more internal testing however this annoyingly doesn't feel as efficiant as what it was before!
