### ISSUE TITLE
Reapit offers linking to Tenancy

### ISSUE THREAD

**Issue by raymond2323** [reapit/foundations#4982]
I have been informed by an Agent that when they submit an offer it creates an entry in tenancy details. See below

![image](https://user-images.githubusercontent.com/17427875/133238418-122fea4f-7486-4171-b572-4a25b9ff4b79.png)

When we push an offer through the API it appears to only show on the activity feed: 

![image](https://user-images.githubusercontent.com/17427875/133238531-304dcc2c-9ff5-4c18-becd-258c5e422b21.png)

Do you know why it's not creating an entry on tenancy details? 

Secondly, in order for the Agent to achieve the reporting they require, they would want the offer to be linked to Tenancy once we push this from our system to Reapit. How can ensure that the Tenancy is linked to the underlying offer?

**Comment by plittlewood-rpt** [comment]
Hi @raymond2323 - you can use the `POST tenancies` endpoint to achieve what you are wanting, submitting a tenancy with a status of `offerPending` (or whatever is more appropriate). Please see the API documentation for more information about the required payload. Let me know if this does not answer your question.

**Comment by plittlewood-rpt** [comment]
Hi @raymond2323 - apologies for the lack of response on this ticket, unfortunately it was missing some labels so wasn't visible to us. We already have a `PATCH tenancies` endpoint which allows a limited subset of tenancy fields to be updated. It does not provide a full surface area for operational reasons. You can post documents to a tenancy using the `POST documents` endpoint already. Can you have a look at the documentation on the tenancies PATCH endpoint and advise further on the specific information you are wanting to update, so we can discuss this further?

**Comment by HollyJoyPhillips** [comment]
Closing ticket as no reply. Please open a new issue if this is still required.
