### ISSUE TITLE
Images are not importing with properties

### ISSUE THREAD

**Issue by sahilchahal** [reapit/foundations#5023]
Hello,

I am trying to import properties with images but I am not able to import images. In my app I have selected "Read property images" but not able to import.

Please check the screenshots and let me know.

Thanks

![image](https://user-images.githubusercontent.com/86303421/133556181-4456f2c2-0059-4425-970b-a76f2b634592.png)

![image](https://user-images.githubusercontent.com/86303421/133556137-067b44ab-3f1c-4d2b-970a-5f401cd453bb.png)

**Comment by plittlewood-rpt** [comment]
Hi @sahilchahal can you confirm what calls you are making to the propertyImages API?

**Comment by sahilchahal** [comment]
I am using wp plugin property Hive import addon:-
![image](https://user-images.githubusercontent.com/86303421/133599106-d3f74946-cfaf-45bd-bbba-9b787cea6cb7.png)

**Comment by plittlewood-rpt** [comment]
I cannot see that you are a customer of Reapit's. Can you confirm if that is the case? If it is you don't want to be using the Foundations API anyway. In any case, you need to speak to Property Hive who are the ones who support the Property Hive Wordpress Plugin. Many thanks

**Comment by sahilchahal** [comment]
We are customer of Reapit and this is my website link:- https://letstalkproperty.uk/
