### ISSUE TITLE
Extrafield request - "Fee Earner"

### ISSUE THREAD

**Issue by Daramithes** [reapit/foundations#5027]
**Request**

In order for us to grant access to Semi-structured 'extras' field data, please provide the following information in this request:

- AAC
![image](https://user-images.githubusercontent.com/33520316/133632450-c2f2f3b8-4362-48ba-8962-e15919751906.png)
- for mobile app we are developing, fee earner needs to be made available in extra fields for us to provide end user with information in the property management section of our app

**Comment by msumanthraj** [comment]
Hi, We have requested this field through the properties API. We get a 400 bad request error in the response.

**Comment by plittlewood-rpt** [comment]
Hi @msumanthraj - apologies it looks like that configuration didn't sync round properly. I've just forced an update so it should work now. If you can let me know either way I'd be grateful. Thanks
