### ISSUE TITLE
Cannot access API documentation

### ISSUE THREAD

**Issue by stebrough** [reapit/foundations#5054]
**Describe the bug**
When accessing https://developers.reapit.cloud/swagger the documentation doesn't load. Can see the following errors in the web dev console:

**swagger:1 Access to fetch at 'https://reapit-swagger-prod.s3.eu-west-2.amazonaws.com/foundations_swagger.json' from origin 'https://developers.reapit.cloud' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
instrument.js:136 GET https://reapit-swagger-prod.s3.eu-west-2.amazonaws.com/foundations_swagger.json net::ERR_FAILED**

**To Reproduce**
Access https://developers.reapit.cloud/swagger

**Expected behaviour**
Documentation loads

**Comment by HollyJoyPhillips** [comment]
@stebrough I can confirm the issue with the swagger documentation has now been resolved. Thanks for letting us know.
