### ISSUE TITLE
Analyse the configurable setup

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#5064]
This ticket is to research and analyse the configurable setup for the following: 

buying.reason (configurable)
buying.position (configurable)
renting.position (configurable)
sellingStatus (standard options)
sellingPosition (standard options)

**Comment by plittlewood-rpt** [comment]
![image](https://user-images.githubusercontent.com/30798627/134320023-fcbe1dd9-b8b1-43ed-9373-e1691f1f54e0.png)
