### ISSUE TITLE
Adding in a Reapit Connect Logout 

### ISSUE THREAD

**Issue by jaetooledev** [reapit/foundations#5079]
**Is your feature request related to a problem?**
We're using Laravel Socialite to login with Reapit Connect using a custom provider. Now when we come to log a user out, Reapit Connect is staying logged in. While the app logs the user out, logging in again means Reapit Connect logs the user in straight away with no option to logout.

**Describe the solution you'd like**
We would like a page like https://login.microsoftonline.com/common/oauth2/v2.0/logout which we can send a user to upon logging out of the application to log them out of Reapit Connect.

**Describe alternatives you've considered**
The only solution is moving our SSR app to client side and using Reapit Connect there which isn't ideal.

**Comment by jaetooledev** [comment]
Again, is this something we can have an update on? It's affecting our group quite heavily for dual company users.

**Comment by plittlewood-rpt** [comment]
Hi @jaetooledev - can you let me know if you've had chance to review the above? We will close the ticket in our next review if what we have suggested met your requirements

**Comment by jaetooledev** [comment]
@plittlewood-rpt I'll close this for now - not had chance to test this however we have a ticket coming up soon to get this implemented.

Thanks @HollyJoyPhillips
