### ISSUE TITLE
Review performance of insights 'spin up' time when first loading

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#5090]
**Background context**
Presently, the first load of insights can take upwards of 10 seconds. We should review what is happening during this time (when the progress indicator is on screen)

**Comment by plittlewood-rpt** [comment]
Observations
- Multiple calls to same endpoint from frontend (see ticket #5111)
- DB migration routine running at every cold start
- Keep warm timer only running every 15 mins (have changed to 5 min interval)

**Comment by plittlewood-rpt** [comment]
Increasing memory allocation and keep warm timer frequency has made a big difference to execution time. Once #5111 has been done I think this will be acceptable therefore closing this ticket
