### ISSUE TITLE
Research / architect the ability to surface 'load' statistics for a customers data warehouse instance

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#5108]
**Background context**
Aside from warehouse uptime, we should look to provide the ability to surface when a customers data warehouse instance is underscaled. Outcome of this ticket is a proposal for surfacing a metric that can be included into our existing usage API.

**Ideas**
- Slow queries
- Many concurrent queries being run
- Virtual warehouse CPU stats (if available best measure)
- Review and research to understand best metric
- Outcome is a ticket (if a good metric available) to surface this statistic into our warehouse billing endpoint

**Comment by RWilcox-Reapit** [comment]
**Findings**
After research I've a view containing what was spotted last week and more also showing blocked requests etc.
This can all be retrieved using the 'warehouse_load_history' we have access to:

-  average number of queries queued
- average number of queries being provisioned
- average number of number of queries blocked
- average number of queries running
This can all be retrieve for a given time frame (hour or day)

Slow queries are not a factor for snowflake as the query is blocked/queued until resource is available.

**Suggested Approach**
Background worker running once per day (for the previous day) to run the query shown below. 
This will need to be ran against every customer using the master login. 
The data can be stored within the DataMarketplace DB as it's not being billed for. 
Emails could then be fired to sales for customer who have queries blocked/queued.
Alternatively an endpoint could be built to allow this data to be queried although this would required someone to constantly check the usage metrics.

**Example of call**
![image](https://user-images.githubusercontent.com/61189374/135829951-0ef91ef8-93c5-4197-a019-03c97b42dd1a.png)
