### ISSUE TITLE
Devise mechanism to synch RC internal staff status

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#5117]
**Background context**
Internal user management is managed using a legacy tool that interacts with Reapit Connect. To ensure data is in sync with our AD service, we should provide a means for our infrastructure team to be able to understand which users are inactive/active with ReapitEmployee type group memberships

**Comment by plittlewood-rpt** [comment]
PL in discussion with WA about this - not ready yet

**Comment by plittlewood-rpt** [comment]
@HollyJoyPhillips I think this is a good candidate for the RC management app. We already have endpoints to allow querying a list of users based on their group membership which could be added to this app. The details about the user can then be displayed and any anomalies corrected. Let me know what you think and if this is appropriate what the next steps are
