### ISSUE TITLE
Webhooks unavailable

### ISSUE THREAD

**Issue by markdarcyleacam** [reapit/foundations#5155]
When I log into the developer portal, no "Webhooks" section is available, but was previously available.

We have 4 webhooks registered.

When I navigate to https://developers.reapit.cloud/webhooks, I get a "Page Not Found"

**Comment by willmcvay** [comment]
@markdarcyleacam The correct url is https://developers.reapit.cloud/webhooks/about for webhooks

**Comment by willmcvay** [comment]
Am assuming this is resolved, feel free to re-open if not
