### ISSUE TITLE
Naming conventions for applicant ID codes 

### ISSUE THREAD

**Issue by awogan06** [reapit/foundations#5164]
Sherry FitzGerald group require the naming conventions used for ID’s when creating applicant records to match the logic of Agency Cloud (and how it worked in the previous API).   When creating a new applicant with an office ID and negotiator ID for a property,  the applicant ID created has the prefix RTP not the office prefix.   
 
Example
 
Offers made on a property associated with the Sherry FitzGerald office in Tullamore via our mySF platform using new API.   System checked to see if contact or applicant pre-exists for this office and if it doesn’t it created a new contact / applicant record to add offer to property.
  
New applicant created for this office was prefix RTP not TUL 
 
Applicant code created was RPT210025 (contact code RPT21000079)
Applicant code created was RPT210016 (contact code RPT21000074)
 
 
We have 65 Franchise offices and 28 owned offices.   Year to date for the entire company we have registered 51,113 applicants.   I appreciate all of these won’t be created via the API but a large volume of them are,  and this is due to increase.   The API will only allow for the generation of 9999 RPT codes.  Applicant codes are 6 digits with the first two digits associated to the year so it is critical for our business that this works in a similar fashion to Agency Cloud and entities created via the API will be generated with a the prefix associated with the office.
 
This is high priority for SFG

Rgds
Audrey 
 
**Specification**
- Update applicant service to account for differing office id
- Prefer officeId associated to identity of user  (machine to machine auth)
- Failing that, prefer officeId associated as primary office for applicant
- Failing that, fall back to RPT
- Build single method in platform identity package to accept a fallback officeId (in this case, from the applicant) and respect order of precident above

**Comment by cbryanreapit** [comment]
Thanks Audrey, we'll review accordingly based on the scale you provide.

We have a similar issue logged: https://github.com/reapit/foundations/issues/3573

**Comment by dawson** [comment]
@awogan06 This ticket has not yet been scheduled. [Please see our documentation](https://foundations-documentation.reapit.cloud/dev-requests) for how our development requests processes work:

> When we're ready to schedule the issue, it will be assigned to a dated GitHub project board for that particular sprint where you can continue to track its progress to completion

You can subscribe for notifications to this ticket by clicking the "Subscribe" button on the right and you will be emailed when there is an update or change in status.

**Comment by plittlewood-rpt** [comment]
Hi @awogan06 - this has now been implemented on the applicant APIs and released out to production, with the behaviour as follows:

- If a user centric app is creating an applicant, the code of the office the user is assigned to in Agency Cloud will be used as the prefix for the reference number of the new applicant
- If a machine to machine (integration) app is creating an applicant, there is no user in scope and so the primary office id passed with the new applicant data will be used as the prefix for the reference number of the new applicant. If this cannot be obtained from the payload sent to the API, we fall back to RPT, before finally falling back to FND if there are no RPT reference numbers available.

It's likely that this mechanism will be rolled out across the other APIs in due course, but there is no timescale for this at present.

Thanks
