### ISSUE TITLE
Archived Applicants in API Data

### ISSUE THREAD

**Issue by Prospect-Louis** [reapit/foundations#5168]
Hi guys, 

When we run an Applicant's Call, we're only pulling back approx 4,000 records. 

This seems like it doesn't include archived applicants. 

We need to be able to access archived data. 

Can someone look into this for us? 

thanks, 
Louis

**Comment by cbryanreapit** [comment]
Hi @Prospect-Louis - please see the swagger documentation, you'll see there's a `fromArchive` query string that allows you to interact with archived data

**Comment by Prospect-Louis** [comment]
Thank you @cbryanreapit, 
We didn't realise you had to specify that and assumed that if you didn't put in a filter either way then it would just pull back all data. 
Is there a way to get ALL applicant records in a single call? e.g. would it work if we did **&fromArchive=true&fromArchive=false**

Are there any other API calls that we'll need to do a separate call to pull back archived data?

thanks, 
Louis
