### ISSUE TITLE
Make departmentId an optional parameter when filtering properties and applicants by their attributes

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#517]
Presently, when you filter `GET /properties` or `GET /applicants` by using a property attribute / applicant requirement query string, you're also required to specify the department id that your attribute/requirement based filter applies to.

Most of our clients do not have more than one department, so this is an unnecessary hurdle for developers to have to jump. 

Outside the scope of this ticket, we will be making amendments to other systems to allow this value to be defaulted to the clients configured preferred default department.

For now, we should update our property and applicant services to default to the 'General' department for property and applicant endpoint interactions while we make the further change behind the scenes.

- Update property GET query to default to departmentId for 'General'
- Update applicant GET query to default to departmentId for 'General'

**Comment by plittlewood-rpt** [comment]
PR 1670 opened to update properties service

**Comment by plittlewood-rpt** [comment]
PR 1684 opened to update behaviour in GET /applicants endpoint
PR 1670 opened to update behaviour on GET /properties endpoint
