### ISSUE TITLE
Some Contacts believed to be 'Inactive' in RPS, show in Foundations as Active: true.

### ISSUE THREAD

**Issue by stebrough** [reapit/foundations#5179]
**Describe the bug**
Within RPS a contact's Status is changed to 'Mark as inactive'. When the contact is pulled from the Contacts endpoint, we see Active: true.

**To Reproduce**
1. Locate a test contact within RPS
2. Change the status to 'Mark as inactive' and choose a reason.
3. Request the contact from the Contacts endpoint of foundations.
4. Observe the Active property.

**Expected behaviour**
The active property should be false.

**Additional context**
We have a specific customer reporting this issue.

![Screenshot 2021-10-06 214309](https://user-images.githubusercontent.com/40298446/136280433-48e9801b-69c3-4dd7-b554-0c129fad7c1b.png)

![Screenshot 2021-10-06 214528](https://user-images.githubusercontent.com/40298446/136280550-3a98dbc4-6704-47be-a514-34d32f9f1501.png)

**Comment by plittlewood-rpt** [comment]
Hi @stebrough - please can you provide the id of the customer who has reported this to you?

**Comment by stebrough** [comment]
Hi @plittlewood-rpt, thanks for that mate, you're spot on I'd missed that fact!
