### ISSUE TITLE
Access to Directions field

### ISSUE THREAD

**Issue by gfyans** [reapit/foundations#5187]
**Request**

In order for us to grant access to Semi-structured 'extras' field data, please provide the following information in this request:

- The name of the customer you represent - Bell Ingram
- The name of every field you need surfaced (if known) - Directions
- A screenshot of of the field(s) you require in the agency cloud user interface
![image](https://user-images.githubusercontent.com/1040786/136423016-1f86173d-a47f-4599-a73a-be267e5c87dd.png)

- A short use case as to why you require this data - We need to be able to see directions on the website that consumes the data.

**Comment by madebyparent** [comment]
Hi — We're trying this, but getting the error;

Access to one or more of the specified fields is not permitted. You must be granted access to this data beforehand

I can't see any potential permissions it could be that we don't have
![Screenshot 2022-04-05 at 09 39 26](https://user-images.githubusercontent.com/45567266/161716655-20eb2534-9a9d-40bd-9ddd-6898c933bf65.png)
.

**Comment by plittlewood-rpt** [comment]
Hi @madebyparent - are you working with @gfyans  who logged the original ticket? This is customer specific so if you are trying to do this for a different company you will get an error as described.

**Comment by madebyparent** [comment]
> Hi @madebyparent - are you working with @gfyans who logged the original ticket? This is customer specific so if you are trying to do this for a different company you will get an error as described.

Have started a different ticket as noticed that is closed.
And no, different client
