### ISSUE TITLE
API to fetch clients properties

### ISSUE THREAD

**Issue by sahilchahal** [reapit/foundations#5197]
I want to fetch live properties of my client i.e 
https://letstalkproperty.uk/

I have already integrated the dummy properties i guess :- https://letstalkproperty.uk/properties/

Using this API:- https://platform.reapit.cloud/properties

**Comment by willmcvay** [comment]
Suggest you watch this video as a starting point https://www.youtube.com/watch?v=uXswMdscoqg

Anything not covered in the video or the docs, you can raise as a question
