### ISSUE TITLE
Investigate automating fivetran as part of data warehouse customer onboarding routine

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#5220]
**Background context**
As part of when a customer onboards with the warehouse, we should consider automating the fivetran pipeline using their API.

**Comment by HollyJoyPhillips** [comment]
@HollyJoyPhillips requested direction from Parm.

**Comment by HollyJoyPhillips** [comment]
Parm to update the ticket when Platform are required to implement automation work

**Comment by plittlewood-rpt** [comment]
I have spoken to @rpt-pneale about this today as part of something else. He can supply a list of API calls to make to fivetran that will set up the Fivetran connector and kick off the initial sync, so this is likely something that can be scoped now
