### ISSUE TITLE
Robinson Jackson Migration - SQL Views to PAAS

### ISSUE THREAD

**Issue by Shabaristarberry** [reapit/foundations#5231]
Hi Support,

We have migrated the property data for our mutual client Robinson Jackson via the Starberry DataXchange APP in PAAS Marketplace. Post import we have discrepancies in data available in PAAS database and its not in line with the SQL views, there are additional data available in PAAS for the statuses For Sale, SSTC and Exchanged.

Please refer to the attached google spreadsheet, 

https://docs.google.com/spreadsheets/d/17R4YmdVhalH6Xv90USHyyWECYth7I4BxUAZFoxC52Gg/edit?usp=sharing

Can you please let us know why the difference in count and is this something to be updated at your end

Thanks
Shabari
Contact on feeds@starberry.tv / shabari@starberry.tv

**Comment by rajeshwl** [comment]
Hi Support,
Any updates regarding this?

**Comment by plittlewood-rpt** [comment]
Hi @Shabaristarberry - the external flag is now exposed and was done this week as part of #5228 
Thanks

**Comment by Shabaristarberry** [comment]
Hi @plittlewood-rpt thats great, we will check at our end and come back

Thanks
Shabari
cc @rajeshwl

**Comment by HollyJoyPhillips** [comment]
Closing this issue as it seems to have accommodated what you need with the external flag. P
