### ISSUE TITLE
Webhooks generates an "Invalid URL" error when using a Microsoft Power Automate generated URL

### ISSUE THREAD

**Issue by boydduk** [reapit/foundations#5234]
When using an auto-generated URL from Microsoft Power Automate I get an error (it works fine with url from webhook.site).  Just wondering if there is something in the URL which is being deemed invalid?
 
https://prod-26.uksouth.logic.azure.com:443/workflows/852a3c17b3924d7c80324ee0420039d3/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=6V3RlN2XfbiX3o_c6uMMrJ5Jkz_Tjwjlq0ZGsjKiZp8
 
tried the following also:
 
https://prod-26.uksouth.logic.azure.com/workflows/852a3c17b3924d7c80324ee0420039d3/triggers/manual/paths/invoke?api-version=2016-06-01&sp=/triggers/manual/run&sv=1.0&sig=6V3RlN2XfbiX3o_c6uMMrJ5Jkz_Tjwjlq0ZGsjKiZp8

**Specification**
- Attempt to replicate using the webhooks user interface and track down the issue, fix

**Comment by plittlewood-rpt** [comment]
Hi @boydduk 

Can I just confirm you were running into this problem when using the Developer Portal (rather than trying to set the webhook up via our resthooks API). We have released an update to the Webhooks management interface in the developer portal and it looks like this was being caught by UI previously as I've been able to create a webhook using the URL you specified above without a problem. If you could let us know if you still have trouble, we can investigate further.

Thanks

**Comment by plittlewood-rpt** [comment]
Hi @boydduk thanks for confirming. From the original issue I thought the issue was with creating the webhook in the first place. Is it just the ping functionality that is not working as you expect?

**Comment by boydduk** [comment]
I have recreated this in Power Automate with a new URL, I have tested using Postman and all works.  Below is the new URL and the Postman Curl output.  It might be because the Parameters are not being passed by the Developer Portal (e.g. API Version etc, these need to be passed)?

https://prod-26.uksouth.logic.azure.com:443/workflows/852a3c17b3924d7c80324ee0420039d3/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=6V3RlN2XfbiX3o_c6uMMrJ5Jkz_Tjwjlq0ZGsjKiZp8

curl --location --request POST 'https://prod-26.uksouth.logic.azure.com:443/workflows/852a3c17b3924d7c80324ee0420039d3/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=6V3RlN2XfbiX3o_c6uMMrJ5Jkz_Tjwjlq0ZGsjKiZp8'

**Comment by plittlewood-rpt** [comment]
Hi @boydduk sorry for the delay in responding to this I was away last week and your latest response didn't get circulated to the team. I can see the issue I think. The limit on the URL is currently 200 characters. I have logged an enhancement ticket #5337 to look at increasing the limit. In the meantime the only thing I can suggest is to try and see if there is a URL format you can use that comes in under the 200 character limit. Perhaps set up a short URL somewhere?

**Comment by plittlewood-rpt** [comment]
@boydduk the character limit for webhook URLs has now been increased so the URL will no longer get truncated. If you update your webhook configuration to use the new URL this should start to function correctly.

**Comment by plittlewood-rpt** [comment]
@boydduk For info I've just tried with your original URL and got the following error back from Azure so you'll want to look into this I think.

```
{"error":{"code":"TriggerInputSchemaMismatch","message":"The input body for trigger 'manual' of type 'Request' did not match its schema definition. Error details: 'Invalid type. Expected String but got Integer.'."}}
```

**Comment by boydduk** [comment]
Thanks, this is now working correctly.
