### ISSUE TITLE
Some Property Attributes aren't being sent through the API

### ISSUE THREAD

**Issue by jennyCognio** [reapit/foundations#5235]
Not all the property attributes are being sent to us through the API; we've tested with a property where all property attributes available in Reapit have been ticked and the results are in the attached sheet
see Column A for the names on the Reapit UI, Column B is what comes through the API

As you can see, some of the sections have some of the mappings, only one has all of them (Locality) and the ones in red have none at all.

We're currently building the new website search that will require all of these to be available through the API and without the correct data we're missing out on properties being shown in search results. 

We did speak to the tech support desk at Reapit but were told that as Beresfords are using custom names for the attributes, they weren't included in the API.  This wasn't explained to Beresfords when they were told the attribute names could be changed and I'm not sure it explains the sections where only one attribute isn't being received.

We've been told to report this as a feature request but it feels much more like a bug to me.

[Attribute Mappings (1).xlsx](https://github.com/reapit/foundations/files/7336795/Attribute.Mappings.1.xlsx)

**Specification**
- Add new PropertyParking attribute `carport` with options `Carport` and `Car Port`
- Add new PropertyAge attribute `old` with options `Old`
- Add new PropertyStyle attribute `duplex` with options `Duplex`
- Add new option `Communal Gardens` to existing PropertySituation CommunalGarden attribute
- Add new PropertySituation attribute `outsideSpace` with options `Outside Space`
- Ensure documentation is updated where required on each of the models to encompass the new options
- Update both property and applicant services

**Comment by jennyCognio** [comment]
Hi
To update you, we've added use cases to both those tickets, however neither
of those cover the issue that certain attributes in some standard
categories are also not being sent through.
such as Duplex under Style or Carport under Parking
Is this a bug which is being treated differently to tickets 5316 & 5315 or
has it been missed?

Thanks
Best wishes
Jenny

Jenny Forster



Cognio Digital Ltd      12 Melcombe place, Marylebone, London, NW1 6JJ   Tel:
0800 433 7045
 www.cogniodigital.com
<https://mailtrack.io/trace/link/3fade48459ed1757ad9155271a25b0c5a88e1ea1?url=http%3A%2F%2Fwww.cogniodigital.com&userId=2673365&signature=2cdd7ef74566cc6b>
   Company Reg: 11227933   VAT No: 290277882

**Comment by plittlewood-rpt** [comment]
@jennyCognio I have added a specification to this ticket and it will be actioned this week. The other two tickets you mention have been completed over the last two weeks also. Thanks

**Comment by plittlewood-rpt** [comment]
@RWilcox-Reapit subject to feedback from customer on #5282 please can we also add "Residential Site/Land" as a variation of the existing Land mapping as part of this ticket
