### ISSUE TITLE
Access to the Media For Boomin training environment

### ISSUE THREAD

**Issue by kitoban** [reapit/foundations#5249]
**Background context or User story:**
Boomin foundation app is currently under testing within the Boomin training environment, 
Currently appears that the training environment is not whitelisted to access reapit foundations media.

**Specification**
- Review the way public URLs are being build in the property images API. Ensure that any office group suffix is stripped off the customer id,
- Ensure unit tests written to cover this scenario
- Once updates are completed, make sure that links output from this service are accessible

**Comment by plittlewood-rpt** [comment]
Hi @kitoban 

The underlying issue that was causing the incorrect link to be generated has now been resolved. I've added a new image to one of the properties in our Sales build (code RES) and confirm that the URL generated is accessible (image id NPG090251_11.jpg)

As it is a demo system there will be a number of dead links due to the age of the data, but this won't be the case when querying real data (or indeed sandbox data, where you can set up your own tests)

Hope this helps. Please let me know if you continue to experience issues

Pete

**Comment by kitoban** [comment]
@plittlewood-rpt Now that we are no longer seeing Forbidden, we seem to be getting back not found instead on all the media within the testing system.

**Comment by plittlewood-rpt** [comment]
Hi @kitoban thanks, Ash flagged this with me yesterday. I did test adding a new image and pulling it back via the API/image URL and it did work OK. It's on my radar to look into this further.

**Comment by plittlewood-rpt** [comment]
Hi @kitoban - I've spoken with our infrastructure team who are going to issue a fix for this environment tonight. The URLs should start functioning by morning but I'll make a note to check them myself before confirming back to you

**Comment by kitoban** [comment]
@plittlewood-rpt thanks, should hopefully enable Ash to continue testing.

**Comment by plittlewood-rpt** [comment]
Hi @kitoban - I've just run a test and 8,303 out of 8,307 URLs returned from the RES system are returning with a 200 OK which means there's only 4 orphaned image records (with no matching file asset) in that system. It's worth noting that you should have handling in your application for 404s as we can't guarantee that there won't be missing physical file assets in a customer system (though the chances of this happening are quite low). It is too expensive in performance terms to do a file existence check every time we build URLs out of the PropertyImages API. Can you rerun your import on this system and let me know what issues you run into? Thanks

**Comment by kitoban** [comment]
@plittlewood-rpt the system does handle 404's however if the advert's primary images is a 404 it is not accepted within the system, For non primary images then these will be skipped if cannot be found and the other images will be used for the advert.
I have just triggered a resync from our side as requested and the live properties are now loading correctly, including MKS210001 which was one of the ones that had issues loading the images previously. So does now look like this issue is resolved.

**Comment by plittlewood-rpt** [comment]
Great - thanks for confirming Paul
