### ISSUE TITLE
Custom Marketing Screen Info Not Pulling Through On Foundations

### ISSUE THREAD

**Issue by jaetooledev** [reapit/foundations#5284]
**Request**

In order for us to grant access to Semi-structured 'extras' field data, please provide the following information in this request:

- The name of the customer you represent
Manning Stainton
- The name of every field you need surfaced (if known)
-Standard Description
- A screenshot of of the field(s) you require in the agency cloud user interface
![Capture](https://user-images.githubusercontent.com/61322528/138110227-1e55600c-91f4-4135-9ff9-5c379f9accfc.PNG)

- A short use case as to why you require this data
We have a custom marketing screen with descriptions. On the RDA API this was mapped into a StdDesc field for Standard Description.

**Comment by plittlewood-rpt** [comment]
Hi @jaetooledev. I have enabled access to the Standard Description field and it should be available for use within the next 15 minutes or so once the new configuration has chance to propagate across the platform. To access this field, use the `extrasField` query string parameter in your GET requests, passing `pStdDesc` as the value eg

`GET /properties?extrasField=pStdDesc`
`GET /properties/XXX123456?extrasField=pStdDesc`

The API will respond with a 400 Bad Request error if you attempt to access any semi structured data that hasn't been enabled for access, or the configuration hasn't propagated yet.

Any issues please let me know

**Comment by jaetooledev** [comment]
@plittlewood-rpt this did work but now it doesn't.

![image](https://user-images.githubusercontent.com/61322528/144270680-53104b44-2da3-4c1a-818d-69767dedbc11.png)
https://platform.reapit.cloud/properties/MLY210526?embed=images&extrasField=pStdDesc

**Comment by plittlewood-rpt** [comment]
Hi @jaetooledev  - it looks like some configuration may  have been overwritten when you moved over to AWS. I'll get someone to sort this out now

**Comment by jaetooledev** [comment]
Cheers @plittlewood-rpt - you have no idea how long I spent trying to work out what I'd broke ha

**Comment by RWilcox-Reapit** [comment]
Hi @jaetooledev this has now been resolved. 
Apologies for the inconvenience.
