### ISSUE TITLE
Additional fields in Schema No Gas and Work Orders

### ISSUE THREAD

**Issue by StuartLaw99** [reapit/foundations#5290]
Can you add 'no gas' to the property entity so that we can do detailed reporting on certificate compliance correctly.

Please also add Description & Type to Work orders and Notes to Work Order Items.

Without these, Work Order reporting is virtually impossible.

Similar request in #5517 

**Specification**
- Review best place to add works order description/notes/types.
- Consider field name to add to lettings property entries to denote whether or not there is a gas supply to the property. Bear in mind that other utilities might get added to the schema. This might be via the use of another table specifically designed for utilities that can evolve over time.

_Utilities_
PROPERTY_LETTINGS_UTILITIES (1-1 with properties table)
Only lettings properties

Fields
property_id
has_gas (Yes/No) - inverse of no gas
gas_supplier_company_id (blank if not set - ensure this uses surrogate key)
electricity_supplier_company_id (blank if not set - ensure this uses surrogate key)
water_supplier_company_id (blank if not set - ensure this uses surrogate key)
_customer_id
_last_synch_at

**Comment by plittlewood-rpt** [comment]
Hi @StuartLaw99 - part of this ticket is now complete. We have added new fields to works_orders called `DESCRIPTION` and `TYPE` and a new field to works_orders_items called `DESCRIPTION` - the documentation you can see in the Developer Portal has also been updated to reflect these changes. As these are new fields it is necessary to reprovision the share to see them, although we are looking at an easier way to refresh your version of the dataset. Let me know if you have any problems with this. We are still discussing the best approach for surfacing whether or not a property has gas

**Comment by plittlewood-rpt** [comment]
This ticket did not quite get completed in sprint 38 so has moved over to sprint 39 to be finished next week

**Comment by plittlewood-rpt** [comment]
Hi @StuartLaw99 - if you reprovision your dataset you should now be able to see a new table called PROPERTY_LETTINGS_UTILITIES which gives you the ability to see which properties do/do not have gas. We have done it this way so it gives us a way to expand utility related information independently of the main properties model. The new table is available now, and the updated documentation to go out to the developer portal early tomorrow morning

**Comment by StuartLaw99** [comment]
> Hi @StuartLaw99 - if you reprovision your dataset you should now be able to see a new view called PROPERTY_LETTINGS_UTILITIES which gives you the ability to see which properties do/do not have gas. We have done it this way so it gives us a way to expand utility related information independently of the main properties model. The new table is available now, and the updated documentation to go out to the developer portal early tomorrow morning

@plittlewood-rpt Thanks for this. I will test this Monday but sure it will be all ok.
