### ISSUE TITLE
Provide ability to read special attribute data from property/applicant APIs

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#5315]
**Background context**
Special attributes are a heavily customised feature of AgencyCloud where property attributes/applicant requirements can be specified using a largely bespoke list of options. As such, building a uniform API structure around this attribute type in the same way as other attribute lists is not feasible, and we should review how best to expose this data. Typically, data held in this field is not important to third party integrators, though has now been requested. 

**Specification**
- Add `specialFeatures` string array to contracts
- Expose the labels as they are configured in the source system as there is no real uniformity in what these options are
- Two services in scope here, applicants and properties
- Read only from GET endpoints only

**Comment by jon64digital** [comment]
Hi there.

Just wanted to add some info here as we requested this change.

Our new website allows customers to search for properties using attribute filters and there are some attributes in this custom list that would make useful search filters. For example, being able to filter out retirement homes, or specifically filter for only homes with a swimming pool or equestrian homes.

In addition to search filters we also like to show a list of features with icons on the property listing itself, so it would be nice to show retirement homes and swimming pool or tennis courts etc. with a corresponding icon.

I guess it's also worth saying that the list is quite small at the moment but having access to it through the API would allow us to add a lot of new features in the future.

Many thanks.
