### ISSUE TITLE
Provide ability to read decoration information from property/applicant APIs

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#5316]
**Background context**
Presently, we do not surface information about standards of property decoration in our API, since this is not a field that integrators typically care about. We should add the ability to read it from property and applicant APIs.

**Specification**
- Use mechanism for furnishing as a guide here as the implementation will be very similar
- Add `decoration` string array to the contracts in the applicant and property APIs
- Surface selected values. Use camel case as per other attribute fields
- Support for both read and write

**Comment by jon64digital** [comment]
Just a note to say that our reason for requesting this is the same as the other attributes covered in ticket 5315

https://github.com/reapit/foundations/issues/5315

Basically, it would be great if our customers could search for properties which are in need of modernisation and plenty of people are specifically looking for a "project" home. This isn't as important to us as the other ticket but would be nice to have.

Thanks.
