### ISSUE TITLE
CORS 401 issue

### ISSUE THREAD

**Issue by WeCOMPLETE** [reapit/foundations#5328]
Morning,

Can someone please help with the dreaded 401 response?

We are trying to build a small app over the framework.

We tried the 'no-cor' option as suggested in the console, while that stopped the error we are still getting the 401 exception.

Here is an example of the call:

https://platform.reapit.cloud/applicants/?pageSize=2&pageNumber=1&embed=&age=new&furnishing=furnished&locality=townCity&parking=residents&situation=garden&style=terraced&type=bungalow&marketingMode=buying&rentFrequency=annually&bedroomsFrom=3&bedroomsTo=10&active=true

Below are the images attached for your reference.

![image](https://user-images.githubusercontent.com/92932141/139411880-06a99983-fa5c-46aa-9bf5-a3864ecbe2b5.png)

![image](https://user-images.githubusercontent.com/92932141/139411958-c972fbef-fd87-4fdc-8076-f1a0657d9399.png)

![image](https://user-images.githubusercontent.com/92932141/139411992-1e0ee7d8-c863-41d2-ac9e-137499200566.png)

Kind regards
Suraj

**Comment by willmcvay** [comment]
Closing as no response. Feel free to re-open if you have any further questions.
