### ISSUE TITLE
filter out Lost MA on get properties endpoint

### ISSUE THREAD

**Issue by Daniel-GabrielN** [reapit/foundations#5331]
**Background context**
Is there a way to filter out Lost MA on get properties endpoint?

**Specification**
These properties have following fields set:
"agency": "comparable"
"lostInstructionDate": "2021-10-27"

**Comment by plittlewood-rpt** [comment]
Hi @Daniel-GabrielN 

A new property `isExternal` has been added to the `GET /properties` and `GET /properties/{id}` endpoints. This will typically be set to true whenever a property is set as Lost MA and you can also filter by this new field. Calling `GET /properties?isExternal=false` should give you the result you are wanting here. Can you test this out and confirm?

**Comment by Daniel-GabrielN** [comment]
Good morning Pete, I have tried the new query parameter and it works as described. Thanks you!

**Comment by plittlewood-rpt** [comment]
Hi @Daniel-GabrielN  thanks for confirming. I'll close out this ticket in that case. Just let us know if we can be of further assistance.

**Comment by kitoban** [comment]
@plittlewood-rpt 
Could the documentation be updated on this? as it is not clear within the api docs what the IsExternal flag refers to.
![image](https://user-images.githubusercontent.com/5329503/140709393-3ae1487e-5524-46b7-a968-608f32c4075d.png)

**Comment by plittlewood-rpt** [comment]
Hi @kitoban - the field is documented on the model itself. Can you not see this? Thanks

**Comment by kitoban** [comment]
Ok, yes can see that there on the model definition, only downside is the swagger page does have it fairly buried down the bottom making it difficult to find.

**Comment by plittlewood-rpt** [comment]
You can see the models relating to each endpoint inline in the main body of the page without having to go through the list at the bottom (just switch from Example Value to Model). Does this help you? Thanks
