### ISSUE TITLE
Foundations Analytics not working when filtering usage Per customer

### ISSUE THREAD

**Issue by mark-orme** [reapit/foundations#5347]
When logged into our developer account the breakdown of usage per REAPIT client has stopped working ?

https://developers.reapit.cloud/analytics

We can see a breakdown of usage for all clients in each of our applications but when trying to filter by customer the analytics data is shown as 0 for all ?

The total for all customers is showing fine but not when broken down per customer.

Please can we get this sorted?

**Comment by willmcvay** [comment]
Hi @mark-orme I can see the issue, yes we'll look into it

**Comment by mark-orme** [comment]
thanks @willmcvay

**Comment by mark-orme** [comment]
Hi @willmcvay Is this live now as I'm still seeing stats as 0 for all clients?

Thanks

**Comment by HollyJoyPhillips** [comment]
Hi @mark-orme, this has now been released and should be working.

**Comment by mark-orme** [comment]
thanks @HollyJoyPhillips, now I need to add a new feature ticket to be able to download ALL as CSV.
