### ISSUE TITLE
Unable to Access api permission items after updating in App

### ISSUE THREAD

**Issue by nbdesignstudio** [reapit/foundations#5348]
**Describe the bug**
Early this morning we requested access for our Apps to some additional Permissions. Namely the ‘Read negotiators’ and ‘Read offices’. 

It appears that this changed has been enabled by yourselves. As the extra items are checked when looking at our app details. But when we try to access those api functions from within our app we get permission denied errors saying they we don’t have access as per the supplied screenshot...

**To Reproduce**
Only possibly to reproduce in our app. If we use the API pages at https://developers.reapit.cloud/swagger the access works. So we believe it's a permissions issue for our app itself.

**Expected behaviour**

**Screenshots**
![unnamed](https://user-images.githubusercontent.com/24694998/139854831-76362404-68fd-4cdd-96e1-a618bec2e789.jpg)

**Device (please complete the following information for web issues):**
All devices. but mainly tested on Google Chrome.

**Comment by AshDeeming** [comment]
Hi @nbdesignstudio - Please can you confirm the app where the permissions have been requested to change?

**Comment by nbdesignstudio** [comment]
Hi there. The App is the Smart Compliance Stage and / or Smark Compliance Dev app for Lifetime Legal. This issue appears to have resolved itself. But has now occurred again today and we are getting the attached error message when looking at the debug console.

![Screenshot 2021-11-18 at 14 34 47](https://user-images.githubusercontent.com/24694998/142435457-660737fc-20d9-4ad8-bafb-71406bee6b2c.png)
..

**Comment by AshDeeming** [comment]
@nbdesignstudio - apologies for the delay, please could you confirm if you are still having the same issue/error?

**Comment by nbdesignstudio** [comment]
No this automatically fixed itself, without any changes made our side. 

This was the second time this had happened to us. So we now just put it down to some kind of temporary or delayed approval of an apps settings before it actually works.

**Comment by plittlewood-rpt** [comment]
Hi @nbdesignstudio sorry for the delay on responses on this ticket. It was missing a label which meant it didn't appear in the right places. After requesting new permissions, you need to completely refresh your tokens before you'll be able to interact with the new endpoints. It's likely that this appeared to resolve itself as tokens naturally expired and got refreshed. I'll close this ticket out now, but get back in touch if you run into this again and you think there is more to it than what I've described
