### ISSUE TITLE
Viewing Feedback Possible Interest Options Missing from Viewing Appointment Response

### ISSUE THREAD

**Issue by sdoonan776** [reapit/foundations#5363]
**Is your feature request related to a problem? Please describe.**

After querying the appointment endpoint, it seems that the possible interest options for viewing feedback are missing from the appointment response. There is a 'followUp' field in the response but this only has the notes and not the options that are included in the possible interest dropdown as per the screenshot below.

**Describe the solution you'd like**
Access to these possible interest options.

**Describe alternatives you've considered**
Building the feature around the feedback notes but these seem to change with each appointment.

**Additional context**

![screenshot](https://user-images.githubusercontent.com/42623560/141753799-6def977e-4685-4b26-b954-dc3d7b1c97f6.png)

**Comment by jaetooledev** [comment]
Can we have an update on this please?

**Comment by HollyJoyPhillips** [comment]
Hi @jaetooledev We will be reviewing this ticket in our next refinement session. Thanks.

**Comment by plittlewood-rpt** [comment]
Hi @jaetooledev @sdoonan776 

I think what you are asking for is actually already available. In the GET appointments response, you should see a `followUp.responseId` property. You should also see an item in the _links collection that points to `GET /configuration/followUpResponses/{id}` which will allow you to decode the id presented in the appointment model. Please can you let me know if this answers your question. Please accept my apologies for the delay in responding to this item.

Thanks
Pete

**Comment by plittlewood-rpt** [comment]
Hi @jaetooledev - I am going to close this ticket based on the response provided above. Please come back to us if there are any outstanding requests with regards to this ticket
