### ISSUE TITLE
Enable Aurora global database support for non-customer Aurora instances

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#5370]
**Background context**
Set up RDS global database on PaaS cluster to replicate to au region (region TBC). Ensure write forwarding is enabled so we can 'write' to the replica. This will offer same behaviour for orgs service, webhooks service, and marketplace (only marketplace).

**Specification**
- Turn on RDS global database functionality
- Update SSM to provide regional configuration for Aus services

**Comment by plittlewood-rpt** [comment]
Closing based on performance testing as no requirement for initial deliverable
