### ISSUE TITLE
Inputs, forms and labels in Elements v3.0

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#54]
**Background**

_Elements UI library is being refactored to ensure better DX, UX and a more lightweight, flexible library with a more consistent API_

**Task**

- To include text, password, number, email, date, time, tel, checkbox, radio, text area, file, select
- Include a separate styled label component
- Include a separate styled form component
- Create component in line with overall specification TBC
- Should implement inputs from Figma styleguide
- Should be flexible to allow use with any React Form or validation library by way of passing props to component
- Should show each component as a molecule story, as well as a form layout example with all inputs in it

**Comment by phmngocnghia** [comment]
Hi @willmcvay, I thinks there's no need to create specific variant for input type. For me, a prop named "type" seems to be enough
