### ISSUE TITLE
Define S3 Bucket Key "Prefix" for assetLocation

### ISSUE THREAD

**Issue by rpt-pneale** [reapit/foundations#5406]
**Background context**
As an SI Engineer, I wish to specify a prefix to the location of the assets.
The assetLocation attribute stored in AWS Parameter within the Platform production account holds the S3 bucket name for a client, defined by the parameter key. The assumption is that Platforms codebase must then interpret the correct prefix to the assets based on /reapit/{client-code}/rps/live/. With the introduction of multiple environments, Prod, UAT, etc., the client bucket will contain each environment's assets, requiring a separator. For production, no prefix is necessary; UAT the s3 key starts with uat etc. see below for example keys. 

**prod:** _/reapit/{client-code}/rps/live/...._
**uat:** _/**uat**/reapit/{client-code}/rps/live/..._

For clarity, an s3 key is a unique identifier for an object within the s3 store. In s3, a prefix is technically the complete path in front of the object name, including the bucket name. In the context of this ticket, I'm only referring to the prefix to the current interpreted "path".

**Specification**
- Add new `environment` property to customer object in parameter store. This stores values such as `uat`, `dev`, `test` etc and is then used downstream when building up file paths
- Update services responsible for file uploads/downloads to prefix a file path with the environment parameter. If missing, no prefix should be added and it should behave as it does now

**Comment by plittlewood-rpt** [comment]
As this is not associated with our regional work, can you let me know if there is a pressing need for it, else I'll leave it here in our mid-term column

**Comment by aalim405** [comment]
@plittlewood-rpt - so far we have had SAV requiring the Foundations access off a UAT build and we have had to set them up in PROD to achieve this (SAU). 

If we can get some high-level timelines as to when this will be looked at we can manage expectations when any existing or upcoming customers request access off a UAT build.

**Comment by plittlewood-rpt** [comment]
hi @aalim405 - can this be done outside the larger scope of more general UAT support on the Platform? There's various tickets on the milestone I've just attached to this ticket. It will depend whether or not this can be done independently of the rest of them (I think it can, but worth a wider conversation)

**Comment by aalim405** [comment]
@plittlewood-rpt  - sorry for the delayed response. I cannot seem to see the milestones attached to this ticket. Can we have a chat when you are free please? Thanks.

**Comment by aalim405** [comment]
hi @plittlewood-rpt  - this requirement has come up again from Savills. Can we discuss this when you are back please? Thanks.
