### ISSUE TITLE
Journal Entries - Arranging Tenancy

### ISSUE THREAD

**Issue by tsadlerbrs** [reapit/foundations#5412]
When using the SQL Views, we used to read the ‘JournalEntries’ table to find a record which identifies the ‘Arranging Tenancy’ date. 

When calling the new API we are calling the ‘JournalEntries’ endpoint but no records are being found. Can you please advise how we can find the ‘Arranging Tenancy Date’ from the journal entities – do we use the property id or do we use the associated id field? I have listed below an example record as an example if you can please point us in the right direction.
 
Address:             Flat B, 12 Kildare Gardens
Property ID:       NHO120194
Tenancy ID:        NHO210078

**Comment by plittlewood-rpt** [comment]
Hi @tsadlerbrs - the journal entries API will still give you the date the status of the property changed to Arranging Tenancy. In the case of your example above, you can call `GET /journalEntries/?propertyId=NHO120194&typeId=TA`. You can use the configuration APIs to see what the various typeId's are. Does this answer your question? Thanks

**Comment by tsadlerbrs** [comment]
Thanks @plittlewood-rpt  - This gave us what was needed
