### ISSUE TITLE
Interactive API explorer is not surfacing 404 errors in all cases

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#543]
As reported by https://github.com/reapit/foundations/issues/538, we can see that a 404 error hit by the API explorer by providing a bad id does not surface a 404 error in the UI in all cases.

The propertyImages and negotiators service does not - but most of the other getById type endpoints are functional.

TBC

**Comment by plittlewood-rpt** [comment]
Caused my headers not being proxied through the broker correctly. Simple solution, requires update to template project too

**Comment by plittlewood-rpt** [comment]
PR opened for property images/negotiator brokers which are the only two affecvted (PR 1616 and 1615 respectively)

**Comment by plittlewood-rpt** [comment]
PRs merged. Confirmed all resolve

**Comment by kiqbal-reapit** [comment]
Cool, thanks @plittlewood-rpt
