### ISSUE TITLE
Error when removing all users from a group 

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#5430]
**Bug:** 
When removing all users from a User Group, we get the following error: 
0: {field: "userId", message: "The value cannot be empty"}
field: "userId"
message: "The value cannot be empty"

**To replicate on Dev:**
Log in as Sales
Org 'Reapit Sales'
Go to 'User Groups' 
Remove all users from 'Marketplace Admin' group
Submit

**Comment by plittlewood-rpt** [comment]
@HollyJoyPhillips  users have to be assigned to at least one group. Can you check the payload the app is sending? I know the app hides some groups (I think) so it might be that the hidden ones aren't being sent which is an issue as we might be removing group memberships at the moment when we shouldn't be
