### ISSUE TITLE
Cost Explorer - Can you add the option of filtering / downloading via CSV api usage cost Per application 

### ISSUE THREAD

**Issue by mark-orme** [reapit/foundations#5432]
https://developers.reapit.cloud/analytics/costexplorer

On this page we can filter API costs based on Month and Client but not by our APPs.

Ideally need to be able to breakdown and download cost per month per app so we can apply costs etc, is this possible ?

**Specification**
- Mechanism to filter by app is already available in the billing service, and being utilised in the Developer Admin app
- Add App selection filter to the Cost Explorer page in the Developer Portal (should contain an All option)
- When changing the selected app, any filter present on the Client filter should be reset back to All BUT it should still be possible to use both options together. We need to reset the Client filter because an Installation lookup will need to take place when changing the app that is selected to refresh the list of Clients

**Comment by plittlewood-rpt** [comment]
Hi @mark-orme. We wouldn't be able to associate the monthly cost to you per app as the billing is based on the number of endpoints your developer account uses as a whole in the month. However, one thing we could do fairly easily is to add the Application Name to the CSV that you can already download from the Cost Explorer. I think this would give you all the bits of data you need to understand consumption by customer/app or both as required. How does this sound?

**Comment by mark-orme** [comment]
if you can add the cost field as well then this would work ?

**Comment by HollyJoyPhillips** [comment]
@willmcvay I think the format needs to be the same as the Usage in the Admin portal, must select an app first before selecting a client. 
![image](https://user-images.githubusercontent.com/52408607/159278437-dd88da04-1f5f-40d8-b3e4-d1cbe8f3823a.png)
