### ISSUE TITLE
New Desktop Integration Type - Supplier Details - Accreditations - Add

### ISSUE THREAD

**Issue by mchandler-OB** [reapit/foundations#5434]
**Is your feature request related to a problem? Please describe.**
We'd like to enforce a list of required certificates for new Suppliers within Agency Cloud

**Describe the solution you'd like**
In order to achieve this, the simplest solution would be a new integration type that allows us to open our own 'App' when 'Add ...' is clicked from the 'Company Edit' - 'Supplier Details' - 'Accreditations' panel.

**Describe alternatives you've considered**
A completely custom 'Add Company' app but this would require replacing all existing functionality on the 'New company' screen - (Staff, Supplier Details, Activity, Documentation Management etc.)

**Additional context**
![Reapit - Agency Cloud - Supplier Certificates](https://user-images.githubusercontent.com/94047997/141106969-b1d7384b-d2ae-4b95-8d86-ef0338ae4740.png)

**Comment by AshDeeming** [comment]
This request relates to the Desktop CRM AgencyCloud. 
Therefore please advise the client to log this request via the Reapit Service Desk Portal to prgress through the correct channels. (https://reapitsupport.refined.site/login)
