### ISSUE TITLE
Invoicing and Charges: Platform API

### ISSUE THREAD

**Issue by david-silverink** [reapit/foundations#5485]
We require to be able to query and return invoicing details and associated information, including payments, credit notes, outstanding balances.

- Build milestone

-- CD has a spec for this

**Comment by plittlewood-rpt** [comment]
Hi @david-silverink - we need to look at this from a product perspective before committing to any work. This will involve looking at how invoice and payment data is stored in our current systems and if/how this can be surfaced through the Platform. We will update this ticket again once we have got the resource to do the initial research

**Comment by david-silverink** [comment]
Much appreciated

**Comment by HollyJoyPhillips** [comment]
Whilst the nature of this request has been accepted, we are unable to commit to a specified sprint and therefore have assigned your issue to the ‘Long Term’ column. We will regularly review any issues and where development capacity is available, or work is aligned with our Roadmap, the issue will be updated.

**Comment by awogan06** [comment]
Thanks for update Holly,  when reviewing this piece of work can you include all payment types
Deposits 
Advertising payments
Advertising charges

**Comment by neilpellowe** [comment]
This request forms part of a larger roadmap discovery item to review our current Endpoint offering and any additional areas we may consider opening up. Accounts and related fields will be reviewed as part of this discovery. Once complete, tickets will be updated.

**Comment by BradStrutt** [comment]
Any update on this?

**Comment by HollyJoyPhillips** [comment]
This has been reviewed by the Foundations team for a specification to be added at our next refinement session.

**Comment by plittlewood-rpt** [comment]
Design meeting scheduled for 7/12/23 after which milestone will be populated and timelines agreed

**Comment by plittlewood-rpt** [comment]
The invoices API is now available through the developer portal and new invoices.read application scope.

**Comment by david-silverink** [comment]
We have access to this endpoint but testing a property that has invoice/charges data in Agency cloud produces no results. /invoices/?PageNumber=1&PageSize=25&propertyId=SUT240021

**Comment by cduggan-reapit** [comment]
Hi @david-silverlink,

I had a look into this and there are two "Pre-paid Advertising" entries for the property in question.  These will be returned by the payments endpoint rather than the invoices endpoint (which would be `/invoices/payments?pageNumber=1&pageSize=25&propertyId=SUT240021`).

Please let us know if you have any questions!
