### ISSUE TITLE
Update postman tests to include a call with the 'fromArchive' flag set

### ISSUE THREAD

**Issue by RWilcox-Reapit** [reapit/foundations#5491]
**Background context**
A recent update went out which caused issues for archived applicants.
Currently when releases go out we run out postman tests against the related service but there are no tests to hit archived data

**Specification**
Update the Postman test suite to include a test to retrieve archived data
This can probably be a duplicate of the GET request with the 'fromArchive' flag set

**Comment by plittlewood-rpt** [comment]
@RWilcox-Reapit Given this is an easy one to pick off and increases coverage of testability lets get this done sooner rather than later
