### ISSUE TITLE
SOAP API migration - Discrepancy or missing data in the /properties/{id} endpoint

### ISSUE THREAD

**Issue by richclicksmith** [reapit/foundations#5492]
I am migrating a client website over from the old SOAP API to the new Foundations Cloud REST API. 

There are property fields I can access in the old SOAP API data which do not appear or are not populated with the same data when retrieving data for the same property via the Foundations Cloud API. 

My Reapit account manager suggested I post my query on here. 

Here is an example line of code, fetching property data using the old SOAP method "GetGeneralProperty".

`$reapit_prop = $reapit_client->call('GetGeneralProperty', array( 'ID' => $id ), $reapit_ns);
`

Among the data that is returned, is a field labelled "Summary" which the client is currently using for an overview of the property - a single paragraph of text as seen in the screenshot below.

![Screenshot 2021-11-12 at 13 43 01](https://user-images.githubusercontent.com/94179432/141476765-631386f0-bcf4-4bcc-a8ab-3a11ceba351c.png)

This field - or this data rather, does not show up when I retrieve the same property via the Foundations API using the endpoint /properties/:

![Screenshot 2021-11-12 at 13 51 46](https://user-images.githubusercontent.com/94179432/141477794-bf5d1f0b-e3f1-4496-93a2-c4562983dd99.png)

In the data returned from the REST API, there is a field labelled _Summary_  but it is not the same as _Summary_ from the SOAP API. You can see what is returned in the screenshot below.

![Screenshot 2021-11-12 at 13 46 40](https://user-images.githubusercontent.com/94179432/141477406-55882257-600c-41af-811e-35733e209448.png)

How do I access the same Summary data as returned via the SOAP API?

Additionally, there are some fields returned by the "GetGeneralProperty" SOAP API call which do not exist in the data returned for the same property via the Foundations REST API.

These include the following:

- _Market_ - an array of markets in which the property is available for sale
- _Featured_ - a boolean used to indicate whether a property should be shown as featured or not
- _Portals_ - an array describing which sites or publications the property is featured in
- _Perrys_ - a field describing the geographic location of the property (specific to Guernsey)

![Screenshot 2021-11-12 at 14 00 13](https://user-images.githubusercontent.com/94179432/141479350-6609fb31-82f6-4d1a-9dc9-890062823310.png)

![Screenshot 2021-11-12 at 14 01 58](https://user-images.githubusercontent.com/94179432/141479380-7c952811-c27f-4a20-9181-78cafc691169.png)

![Screenshot 2021-11-12 at 14 02 35](https://user-images.githubusercontent.com/94179432/141479401-1d196649-da8e-4cb3-a2ae-3b0414591c9a.png)

I'm aware some of these fields may be custom fields which will be unique per this particular client but I'm not sure how to access that data via the REST API. 

I appreciate any help I can get on retrieving the data via the REST API as outlined above.

Many thanks,

Richard

**Comment by plittlewood-rpt** [comment]
Hi @richclicksmith 

Perrys / Featured / Summary are all fields we can expose very easily using our semi structured data mechanism. I'll log a separate ticket off the back of this and link here

Market is a little more difficult which we'll need to give a little thought to because of where that feature has been set up on the system for this agent.

We will get back to you soon once we've been able to review in a bit more detail

**Comment by richclicksmith** [comment]
Thanks v much.

**Comment by plittlewood-rpt** [comment]
Hi @richclicksmith - ticket #5511 has now been actioned and you should be able to access the Perrys/Featured/Summary data using our extrasField mechanism.

When querying `GET /properties` or `GET /properties/{id}` simply append the extrasField query string parameter with the following values:

Perrys - pPerrys
Featured - pFeatured
Summary - pSummary

eg

`GET /properties?extrasField=pPerrys&extrasField=pFeatured&extrasField=pSummary`

**Comment by richclicksmith** [comment]
Hello @plittlewood-rpt. That's brilliant, thank you - I'll have a go with that today. 

Do you know roughly when you might be able to look at the Market data? Looking for a guide timeline e.g. days, weeks or months?

The agent uses that field to separate property data on their existing website and we can't really launch the new website without being able to filter the properties in the same way - unless there's another field that they can use? We are hoping to have the new website launch-ready by the end of this year.

Thanks again.

**Comment by richclicksmith** [comment]
Hi @plittlewood-rpt. 

While we're waiting to hear back on getting access to the _[Market]_ field, there are a number of other fields which might be easier to expose via _extrasField_ like you did with the 3 mentioned earlier. 

Here is a list of fields that exist currently via the SOAP API for this agent which would be really helpful to have via the Foundations REST API if possible:

- _AvailableFrom_ - date YYYY-MM-DD
- _Available_ - boolean (0/1)
- _Status_ - string e.g. Under Offer
- _SaleStatus_ - string e.g. Under Offer
- _LettingStatus_ - string e.g. Under Offer
- _PriceString_ - string e.g. &#163;285,000 or Price on Application
- _SalePrice_ - number
- _SaleMaxPrice_ - number
- _SalePriceString_ - string e.g. Price on Application
- _Strapline_ - string e.g. UNDER OFFER WITH SWOFFERS
- _PrintableDetails_ - string e.g. https://webservice.reapit.net/swf/pdf.php?p=rps_swf-LMA210143

I think some of this data I can already get from the REST API e.g. _Status_ via [selling] => [status] which returns things like _underOffer_ which I can then parse / format as required at this end.

Out of all of these I would say _AvailableFrom_ is the most important - the agent uses that on their existing website to determine which properties are "New to market" and the user can filter properties this way. 

Is it possible to get any of those added to extrasField please?

Thanks v much,

Richard

**Comment by plittlewood-rpt** [comment]
Hi @richclicksmith 

I think everything your need is already available. AvailableFrom is exposed as part of the letting object in the PropertyModel. If I can point you at the Swagger documentation at https://developers.reapit.cloud/swagger you can see the PropertyModel specification along with an example value.

Let me know once you've had chance to look at it and if there's anything outstanding.

**Comment by richclicksmith** [comment]
Hi @plittlewood-rpt 

I did see AvailableFrom in the PropertyModel Letting object. 

Via the old SOAP API, AvailableFrom appears for both sales and rentals and it's used extensively on the agent's website to mark properties as "New" e.g. the latest 12 properties ordered by AvailableFrom (yyyy-mm-dd) descending order will show on the site as "New to market". 

Is there an equivalent field that can be used for both sales and lettings via the REST API? Or perhaps the AvailableFrom field in this agent's SOAP API can be passed through as an extrasField in the REST API? 

Thanks.

**Comment by plittlewood-rpt** [comment]
Hi @richclicksmith thanks for highlighting this. I don't suppose you have an example of a sales property that is returning this date do you? It might be something custom to this dataset.

**Comment by richclicksmith** [comment]
Yes certainly, here is part of the response from a _GetGeneralProperty_ SOAP call for sales property with ID _LMA210143_ (screenshot below).

![Screenshot 2021-12-02 at 09 22 07](https://user-images.githubusercontent.com/94179432/144394376-3f5f9fec-0803-4e7b-b9bd-4321cc368c44.png)

**Comment by plittlewood-rpt** [comment]
Thanks @richclicksmith - I've checked this out and the same field is exposed in the Foundations API under selling.instructed as it's actually the date the property was instructed (and typically went on the market). hope this helps!

**Comment by richclicksmith** [comment]
Ah yes that's fantastic @plittlewood-rpt. I think the other fields I can work around - with the exception of _Market_ as mentioned previously. Maybe there is another way of handling that - not sure.

Thanks again.

**Comment by plittlewood-rpt** [comment]
No problem. We are actually in the process of coming up with a suitable solution for exposing region specific content and this will form part of that work

**Comment by richclicksmith** [comment]
Hi @plittlewood-rpt. Do you know when the region specific content solution might be available? I'm just looking for a very rough idea so I can set expectations for our client. If you don't know, fair enough. 

Thanks.

**Comment by richclicksmith** [comment]
Hi @plittlewood-rpt,

Hope you had a good holiday. Just checking in on this one again. Do you have any info on when the region specific content might make it into the API? 

Thanks again.

**Comment by plittlewood-rpt** [comment]
Hi @richclicksmith - yes thanks hope you did too. I don't have a date unfortunately at the moment. I'm having a meeting early next week to discuss customer specific customisations which ultimately this fits into so I should have more of an idea about our approach after that

**Comment by plittlewood-rpt** [comment]
Hi @richclicksmith - I have logged a series of tickets to cover off the requirement for adding support for the local/open market options in Guernsey (#5829, #5830, #5831)

**Comment by richclicksmith** [comment]
There is another field which was available via the SOAP API that is missing from Foundations currently:

![Screenshot 2022-05-06 at 11 11 23](https://user-images.githubusercontent.com/94179432/167112560-8a958525-aa48-43f9-bc95-5c94a09dc323.png)

TRP (Tax on Real Property). 
(https://www.gov.gg/cadastre)

Screenshot from client website where TRP is used (via SOAP API):

![Screenshot 2022-05-06 at 11 15 32](https://user-images.githubusercontent.com/94179432/167113212-f8597d6d-e0cb-4286-a606-64d1920261f4.png)

Can we possibly have this via Foundations as well please?

Thanks.
