### ISSUE TITLE
Include version information on our Apps on the login pages

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#550]
**Summary:** To make it easier to see what version an app is currently on, we should include the GITHUB tag/version information on the login page of each of our apps. 

**Task:** To include the GITHUB tag on the login pages of our apps: 

See mockup of Marketplace: 
![MarketplaceVLogin](https://user-images.githubusercontent.com/52408607/76094899-4d61ce80-5fbb-11ea-9c61-62230c874796.jpg)

See mockup of AML:
![AMLv](https://user-images.githubusercontent.com/52408607/76094910-52268280-5fbb-11ea-890f-553b88379bb5.jpg)

See mockup of Lifetime Legal:
![LTLV](https://user-images.githubusercontent.com/52408607/76094932-5bafea80-5fbb-11ea-8f72-8dfc21fe0a40.jpg)

Should also add to GEO Diary 
Should also add to SMB

As Elements does not have a login page, we should include the version in the header, located at the top left of the navigation bar. 

See mock up of Elements: 
![ElementsV](https://user-images.githubusercontent.com/52408607/76095019-7b471300-5fbb-11ea-8e41-989d623f46b9.jpg)

**Comment by tanphamhaiduong** [comment]
- [ ] Aml-checklist
- [ ] Elements
- [ ] Geo-diary
- [ ] Lifetime-legal
- [ ] Marketplace

**Comment by tanphamhaiduong** [comment]
@HollyJoyPhillips I confirmed with @willmcvay that we cannot inject the version to the Reapit Connect screen
![image](https://user-images.githubusercontent.com/22660833/76197255-628a6780-621e-11ea-85f2-eaacb153dd80.png)
