### ISSUE TITLE
Enable access to semi structured data for SWF

### ISSUE THREAD

**Issue by plittlewood-rpt** [reapit/foundations#5511]
Following issue #5492 

- Enable access to Summary description (this is actually an additional description on the AC marketing screen - pSummary)
- Enable access to Featured flag (again on marketing screen - pFeatured)
- Enable access to Perrys field (again on marketing screen - pPerrys)

**Comment by richclicksmith** [comment]
Hi @plittlewood-rpt 

Apoligies for bringing this issue back to light, I'm no longer able to access that extrasField data. When I run an API call e.g. 

https://platform.reapit.cloud/properties/OMA150100?extrasField[0]=pSummary

I get:
_"400 - Access to one or more of the specified fields is not permitted. You must be granted access to this data beforehand"_

The above query string used to work. I have also tried formatting the query string differently in case anything has changed e.g.:

- https://platform.reapit.cloud/properties/OMA150100?extrasField=pSummary
- https://platform.reapit.cloud/properties/OMA150100?extrasField[]=pSummary

Neither of the above work either.

Could you have possibly have a look please?

Thanks,

Richard
