### ISSUE TITLE
There should be a mobile UI for the MM app, Insights and Webhooks filters

### ISSUE THREAD

**Issue by willmcvay** [reapit/foundations#5515]
**Background context or User story:**

_Currently for secondary nav filters on both the MM app and the Webhooks page in the dev portal, we don't render filters in mobile. This means the page is not functional in mobile_

**Specification or Acceptance Criteria:**

- As per designs from Ana, add filters dialog popup in mobile views and any additional control buttons for both apps
- To include any docs links on other dev portal pages eg Docs, GraphQL pages etc

**Comment by HollyJoyPhillips** [comment]
**Developer Portal**
- Tabs on the webhooks page don’t seem to be scrollable. Can’t get to the ‘Transactions Logs’
![image](https://user-images.githubusercontent.com/52408607/143848175-95628836-8029-42b4-8d51-123e52f46d53.png)

- Update the wording on the ‘Transaction Logs’
"Please select an app and date range by using the ‘Filters’ option above."
![image](https://user-images.githubusercontent.com/52408607/143848199-4c238178-6ac7-4508-bab5-a617db0c35f5.png)

- Update the wording on ‘Manage Webhooks’ when in ‘mobile’ 
"Please select an app using the ‘Filters’ option above to get started."
![image](https://user-images.githubusercontent.com/52408607/143848219-e7d42272-c152-432a-8928-739db91f2105.png)

- There doesn't seem to be an option to 'create an app' from the nav? 
![image](https://user-images.githubusercontent.com/52408607/143848641-2d82e42f-b075-416e-be70-f5a25484c101.png)

- Warehouse docs don't seem to be available? 
![image](https://user-images.githubusercontent.com/52408607/143848709-d348b503-28df-4306-b777-20b347549889.png)


**Insights**
When a report has not been selected, update the wording:
'Please select a report using the 'Select Report' option above." 
![image](https://user-images.githubusercontent.com/52408607/143849043-a9fbfe97-a3a9-433d-9d9a-8f7fc83dde73.png)

**Management App**
- When selecting 'Office Groups' without first selecting an org, no notification appears, just the loader: 
![image](https://user-images.githubusercontent.com/52408607/143849641-5c7da69b-113b-4797-8919-4bcc2fa9371d.png)

- Users
Update notification text "Please use the 'Select Org' option above to select an organisation"
![image](https://user-images.githubusercontent.com/52408607/143849868-78fcf523-f675-4790-9b90-66ab89c1217b.png)

**Comment by HollyJoyPhillips** [comment]
Manage Webhook page - i know you updated the wording to make it more generic but it doesn't quite read right. Maybe update to say: 
Old 
No app selected. Select an app to get started by using the ‘Filters’ options.

New
No app selected. Please use the 'Filters' to select an app. 

Same for 'Transaction Logs' 
Old
No app or data range selected. Select an app and date range to get started by using the ‘Filters’ options.

New 
No app or date range selected. Please use the 'Filters' option to get started.

**Comment by HollyJoyPhillips** [comment]
Hey, so it's still not quite right as we don't display the word 'Filters' when in browser mode so putting it in quotes seems odd.

Manage Webhooks
No app selected. Please use the filter option to select an app.

Transactions Logs
No app or date range selected. Please use the filters option to get started.
