### ISSUE TITLE
Fixflo Basic integration in ReapitFoundations

### ISSUE THREAD

**Issue by TomFixflo** [reapit/foundations#5516]
**Summary**

An integration currently exists between Fixflo Basic and Reapit 
The integration was built by Reapit 

The integration is soon to be deprecated 
Fixflo would like to ensure that Fixflo Basic clients continue to have access to their Reapit integration 
THEREFORE Fixflo would like to build an integration between its Basic product and Reapit Foundations 

**Detail and or supporting links and screenshots**

Given the above 
It would be useful IF
Reapit shared their spec for the integration they built between Fixflo Basic and Reapit 
AND/OR answered the questions below 

Questions that we are trying to answer: 

- The Foundations POST WorksOrder endpoint currently requires a negotiatorId and propertyId. Basic does not store these details. How did Reapit's integration with Basic circumvent this? My theory is that perhaps you only made Fixflo available via your tenant portal AND Fixflo was embedded via iFrame (see below) allowing you to pass address details as the issue is submitted: 

IFRAME ID="THE_FRAME_ID" SCROLLBARS="NO" STYLE="BORDER:0PX;WIDTH:100%;HEIGHT:700PX;OVERFLOW:HIDDEN" SRC="HTTPS://DEMO.FIXFLO.COM/ISSUE/PLUGIN?&EMAIL=USER%40EXAMPLE.COM&ADDRESS.ADDRESSLINE1=1%20EXAMPLE&ADDRESS1&ADDRESS.ADDRESSLINE2=EXAMPLE&20ADDRESS2&ADDRESS.TOWN=EXAMPLE%20TOWN&ADDRESS.POSTCODE=EX4%209LE&TITLE=MR&FIRSTNAME=FIRSTNAME&SURNAME=SURNAME&CONTACTNO=1234567890">

- IF a maintenance issue is reported in Fixflo AND the reapit propertyid and negotiatorid are not know THEN how can we pass the information to Fixflo? 
      - Must Fixflo be implemented in your tenant portal via iFrame?
      - Could a works order be raised without a property and negotiatorid and assigned once raised in Reapit? 
      - Could we raise a task instead (these do not require property or negotiatorid)? Is it easy for a Reapit user to convert a task to a works order?

**Comment by smurfoid** [comment]
More background info on set-up/configuration/how it works can be found on this Confluence page - https://reapit.atlassian.net/wiki/spaces/RW/pages/454656473/Fixflow+integration+internal

**Comment by smurfoid** [comment]
Here is the link to the sales demo...https://tracker-staging.reapit.net/demo/_demo/tracker/roles/tenant/tenancy/faults/fixflo/3-bedroom-house-to-let-in-London-N6-ghost-RPW210003

**Comment by TomFixflo** [comment]
@smurfoid 

Thank you your quick reply to my questions. 

The Sales demo answers one of them (you are passing the details to us and they are stored in the 'Renting' portal). I have a follow-up question: do you still sell Reapit Tracker and if so, are clients still able to embed their Fixflo Basic system?  

Unfortunately, I cannot access this https://reapit.atlassian.net/wiki/spaces/RW/pages/454656473/Fixflow+integration+internal as I do not have an internal login to Atlassian. 

Thank you

**Comment by dawson** [comment]
I've asked @smurfoid to kindly continue this conversation offline with @TomFixflo as this isn't the correct forum.
