### ISSUE TITLE
Add works order type to WORKS_ORDERS

### ISSUE THREAD

**Issue by matt-austin-andrews** [reapit/foundations#5517]
**Background context**
As an analyst, I want to be able to query works orders by type (e.g. general repairs) without having to use the operational database and create a manual index.

**Specification**
- Add a human-readable version of WORKDET.TYPE to REAPIT.ANALYTICS_XXX.WORKS_ORDERS
- Be sure to take the customisable work order type list into account

**Comment by matt-austin-andrews** [comment]
![image](https://user-images.githubusercontent.com/88837586/141978812-1d06f331-f843-4abe-a094-297015e0395f.png)
I don't want to create an index of this...

**Comment by matt-austin-andrews** [comment]
Come to think of it, I'm not sure works order statuses are getting pulled through properly either as we have a lot where `WORKS_ORDERS.STATUS` = `Not set` but in the front end they do actually have a status, e.g.,:
![image](https://user-images.githubusercontent.com/88837586/141980347-1ada386f-4f7e-4c50-842f-6b5d4507d1a4.png)

**Comment by plittlewood-rpt** [comment]
Hi @matt-austin-andrews thanks for raising this ticket. We've got a refinement session tomorrow so will talk about this one then

**Comment by plittlewood-rpt** [comment]
hi @matt-austin-andrews - an update had just gone out which resolves the issue with the missing statuses (Quote Accepted was missing) and also adds a new column `TYPE` which will display the type. When new fields are added it is necessary to reprovision the share to see the new fields. Let me know if you have any problems with this

**Comment by matt-austin-andrews** [comment]
Cracking stuff - thanks very much!
