### ISSUE TITLE
Apps not being able to be added to REAPit

### ISSUE THREAD

**Issue by agouriet** [reapit/foundations#5526]
Hi REAPit,

We have a third party supplier, Spectre, who has requested integration using their REAPit marketplace app. What would seem to be a simple task of clicking 'add app' from the market place and then confirm, in true form isn't.

A message is returned saying that the attached user doesn't have the required permissions to add the app.

I logged this last week with REAPit support, who came back yesterday and said that they couldn't help and that I needed to post a ticket on here.  I'm the IT manager for the Group, and been told I have a 'level 2' account which should be able to add apps.

I've already lost about 4 days on this, so is there any chance that someone could just add this app so I can get spectre to continue with the integration please. as I'm getting chased every day on this.

Regards

Andy

**Comment by HollyJoyPhillips** [comment]
Hi @agouriet it looks like your account is currently in sandbox mode, to change this please visit the the following page 'https://developers.reapit.cloud/settings/profile' to ensure that the 'Custome Data' check box option is selected.
