### ISSUE TITLE
Where is the Reapit Customer ID for the API?

### ISSUE THREAD

**Issue by james-hinton** [reapit/foundations#5542]
According to the documentation:
"Requests issued with access codes gained from the client credentials flow must also indicate which customers/agents data they wish to interact with.
You must additionally include a **reapit-customer header** in your request so that it can be fulfilled appropriately. The header should be set to the customers unique id which becomes available to view after a customer has chosen to install your application. You find out out the unique ids and names of the clients that have installed your application in the Analytics area of the developer portal. If a customer chooses to uninstall your application then your access to their data will be revoked.`

I am currently working using the SBOX reapit-customer header, where do I find my reapit-customer to switch over? It's not in the analytics panel and appears to be no reference to the name of the ID.

Sorry for having to ask on GitHub Issues, your customer support keep asking me to put this here.

**Comment by willmcvay** [comment]
@james-hinton For client side applications, you can get the reapit customer by decoding the id token you receive. The key is `custom:reapit:clientCode`. 

As you are referring to the reapit-customer header, I am inferring that you are authenticating on the server side. If this is the case, the default client code is `SBOX` for development. When you are in production, you can either ask your customer for their client code, or much better, set up a webhook in the developer portal to listen on the Application.install topic - the client code of the installing customer will be in the payload.

**Comment by james-hinton** [comment]
Apologies if I'm a bit lost here. The decrypted token contains the following headers. How do I get to the reapit customer ID?

`
Header:
{
  "kid": "E/SrunO5BGLA2MrOzacdcXY0UWjE##########",
  "alg": "RS256"
}

Payload:
{
  "sub": "38qe5jdfd552##########",
  "token_use": "access",
  "scope": "agencyCloud/images.read agencyCloud/properties.read",
  "auth_time": 1637577452,
  "iss": "https://cognito-idp.eu-west-2.amazonaws.com/eu-west-2_##########",
  "exp": 1637581052,
  "iat": 1637577452,
  "version": 2,
  "jti": "bef2b351-f224-4230-ba68-##########",
  "client_id": "38qe5jdfd552##########"
}
`

**Comment by willmcvay** [comment]
That's an access token. As I said, the client code is in the id token you receive when using the Authorization Code flow. If you are using the Client Credentials flow, you should set your app up to receive an installation webhook.

**Comment by willmcvay** [comment]
Am assuming you got sorted @james-hinton feel free to re-open if you have a further question
