### ISSUE TITLE
API Not Scoping to Reapit Customer Header

### ISSUE THREAD

**Issue by gpn273** [reapit/foundations#5546]
**Describe the bug**

Upon querying any REST API Endpoint, and providing the `reapit-customer` header, we are seeing data which is unrelated to the reapit customer we have requested. We get the same data no matter what `reapit-customer` ID we provide.

Example `x-amzn-requestid` requests:
```
# Brings back the incorrect data
346fda63-af18-454b-b577-5c749453cef5

# Brings back the correct data
ae4c5c54-f372-4426-95f8-1f8d04dbadaa
```

**To Reproduce**

Make any request with any valid `reapit-customer` ID, and the same data is returned. This applies to all endpoints.

**Expected behaviour**

For the requests to be scoped based on the provided `reapit-customer` ID

**Comment by plittlewood-rpt** [comment]
Hi @gpn273 - are you getting a new access token when you change customer ids? As a request comes into the platform the token and headers are inspected with the result being cached for 5 minutes. If you change the customer id within that 5 minute period, the new one will effectively be ignored until the cached version of the token expires, after which the token inspection runs again. does this sound the likely cause of the issue you describe? I have found both those requests from Nov 21 at 00:05:03 and 00:05:04 and both hit our platform with the same customer id so I suspect what I've said above is accurate.

**Comment by gpn273** [comment]
Hi @plittlewood-rpt,

Thank you for your reply.

I have just been looking over your documentation and I am not entirely sure how the `reapit-customer` header works in conjunction with the token request.

We only have one `client_id` and `client_secret`, we are using the client credentials flow.

For the purpose of this example, let's say I have two customers. One customer's ID is `C1` and the other is `C2`.

When I dispatch a request to Negotiators, I use the token which has been generated and pass `reapit-customer=C1` as the header. A few seconds later, I will make the same request again but this time switching the `reapit-customer` header's value to `C2`. But, I am still seeing data from `C1`, not `C2`. 

Would this be the caching you explained? Or, do I need to do something different before making the second request for another customer?

**Comment by plittlewood-rpt** [comment]
Hi there @gpn273  yes that's correct. The access token is cached as the request comes in so after the first request, changing the reapit-customer header won't make any difference for 5 minutes until the cache entry reaches it's TTL and is purged. You need to be obtaining a new token for each customer you want to access (so if you're processing a lot of data, it makes sense to do it customer by customer rather than just random records, to reduce the number of times you need to swap out your token). This probably isn't very clear in the documentation and only applies to machine to machine apps, so I'll make a note to get that documentation updated.

**Comment by gpn273** [comment]
Thanks for clearing that up @plittlewood-rpt 

Based on what has been discussed here, I will make the necessary changes on our side.

Thanks for your help @plittlewood-rpt

**Comment by plittlewood-rpt** [comment]
no problem. Thanks for getting in touch
