### ISSUE TITLE
UI Elements - Height of select has increased in v3.7.0

### ISSUE THREAD

**Issue by getupkid** [reapit/foundations#5551]
**Describe the bug**
I assume this issue is caused by the latest font size change in v3.7.0
> Input, TextArea & Select fonts all have regular body text
The height of the select input has increased and when a select and regular text input are side-by-side you can see that the bottom of the inputs are not aligned.

**To Reproduce**
Steps to reproduce the behaviour eg:
1. Create a select and text input and display them next to each other i.e. in a 2 col layout.

**Expected behaviour**
The height of select input should be the same as a text input so that the bottom alignment is equal.

**Screenshots**
Height of a regular text input in v3.7.0:
![image](https://user-images.githubusercontent.com/4795041/142971078-e38828b4-2eac-46e7-beab-bd61c3aa299d.png)

Height of a select input in v3.7.0:
![image](https://user-images.githubusercontent.com/4795041/142971156-314e6610-4c47-49ce-8b4d-fdb73e646151.png)

When the inputs appearing next to each other (2 col layout):
You can see that the bottom border of the select input appears lower than the bottom border of the text input.
![image](https://user-images.githubusercontent.com/4795041/142971271-c302d969-4007-42b7-8f4c-cb1dd07ac1c4.png)

When toggling the font-size of the select input you can see that it starts to align, hence why I feel this was bug is caused by the latest font size update for all form inputs:
![select-input-alignment](https://user-images.githubusercontent.com/4795041/142971486-a0e5ba04-3cb5-4e7e-a217-939ce73cd57a.gif)

**Device (please complete the following information for web issues):**
 - Device: PC
 - OS: Windows 10
 - Browser: Chrome
 - Version: 3.7.0

**Comment by willmcvay** [comment]
@getupkid Thanks for reporting - yes, the padding should have been reduced in line with the normalising of the font size. Will get a patch out today / tomorrow.
