### ISSUE TITLE
Extra field "Development Name" Required for client Collinson Hall(COL)

### ISSUE THREAD

**Issue by rajeshwl** [reapit/foundations#5554]
- Collinson Hall (COL)
- Development Name (Labeled in desktop Application)
- Our mutual client requires the Development name data to be displayed in the website. But currently it's not available in the API. Can you please enable the field for access and share the name to be used in the API.

**Comment by plittlewood-rpt** [comment]
Hi @rajeshwl - this has now been set up for you. The extrasfield you need to request is _pDevName_ eg `GET /properties?extrasField=pDevName` or `GET /properties/XXX123456?extrasField=pDevName`

Semi structured data is read-only
