### ISSUE TITLE
Reapit appointment notification: Contact information are missing

### ISSUE THREAD

**Issue by maxcivino** [reapit/foundations#5557]
RPS version: 12.132.2
Sandbox data

When you create an appointment in RPS with an applicant, the event is notified with no contact information about the applicant.

**To Reproduce**
Steps to reproduce the behaviour eg:
1. Go to 'Property and select Property MKT210563
2. Click on Keys
3. Add New Appointment
4.  Select Accompanied Martin King (OXF)
5.  Search for Applicant Mila Kennedy and select
6. Select date 29/11/2021
7. Select time between 9:00 and 9:00 and 10:00
8. Save

**Expected behaviour**
Reapit notify to the webhook an event with payload containing the contact information of the Application in the field
 "attendee": {
            "id": "BDF151648",
            "type": "applicant",
            "contacts": [<missing information>]
        },

Attached the log file with the event payload

[reapit-webhook-logs-payload-2021-11-23T12_01_45.449+00_00.log](https://github.com/reapit/foundations/files/7587839/reapit-webhook-logs-payload-2021-11-23T12_01_45.449%2B00_00.log)

**Comment by RWilcox-Reapit** [comment]
Hi Max,
Apologies for the inconvenience this has caused. This has since been resolved and we currently discussing an approach to ensure this issue does not crop up again.

Thanks,
Ryan

**Comment by maxcivino** [comment]
No problem and thanks for your help and support
