### ISSUE TITLE
Update password reset endpoint to account for unconfirmed users

### ISSUE THREAD

**Issue by plittlewood-rpt** [reapit/foundations#5563]
**Background context**
The customer management proxy function has handling in for the "Reset password" action invoked from the Negotiator Setup screen in AgencyCloud. Currently this only works for users who have confirmed their Reapit Connect account. For unconfirmed Reapit Connect accounts, it is not possible to use the usual Reset Password mechanism and it requires an administrative call to the Cognito SDK.

We should enhance the mechanism for managing password resets to evaluate whether or not the request to reset the user's password has failed, and if so, check the status of the user. If the users is still in the unconfirmed stat, use the admin-create-user action to resend the password. This will resolve issues that crop up in the scenario where our service team add a new user before the email account is set up, and the welcome email never gets delivered.

**Specification**
- Replicate the scenario. Add a user, ignore the temporary password, try and reset it (it will fail)
- Review the existing interaction with Cognito in the Organisations service
- Update as necessary to introduce smarter logic to deal with users in difference account states

**Comment by HollyJoyPhillips** [comment]
PL & HP: Reviewed - @HollyJoyPhillips  to verify
