### ISSUE TITLE
Add direct linking to specific sections in the documentation

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#557]
**Summary:** We should be able to link directly to sections in the API Docs but currently this isn’t possible by default in the iframe within the Developers Portal as, the URL remains the same and will always navigate to ‘Home’

**Location:** https://dev.marketplace.reapit.cloud/developer/api-docs

**Task:** To setup specific doc location linking (anchor links) in the Developers Portal for the API docs

**For example:** 
If you click on ‘Reapit Connect’ within the ‘Docs’ section in the dev portal the URL is: https://dev.marketplace.reapit.cloud/developer/api-docs

In order to be able to link direct to the ‘Reapit Connect’ section we should include #reapit-connect so when clicked will navigate direct to that section, for example: 
https://dev.marketplace.reapit.cloud/developer/api-docs#reapit-connect 

See below the # to add for each section to link directly so it is in keeping with the standalone docs here https://foundations-documentation.reapit.cloud/:  

APIs: #api
Platform: #api-documentation 
Reapit Connect: #reapit-connect
Web: #web
Desktop: #desktop-api
Open Source: #open-source
Contributing: #contributing
Packages: #package 
What’s New: #whats-new
Platform change log: #platform-changelog
Developer Portal: #developer-portal

**Comment by HollyJoyPhillips** [comment]
@tanphamhaiduong Slight typo on my part but can you change #package to #packages please? 
Other than that the links are working nicely, thank you.

**Comment by tanphamhaiduong** [comment]
@HollyJoyPhillips I fixed, could you help me to check ?

**Comment by HollyJoyPhillips** [comment]
@tanphamhaiduong That's great, thank you.
