### ISSUE TITLE
Foundations REST API - Does a change to relationships update the modified value of an entity?

### ISSUE THREAD

**Issue by BYM-Henry** [reapit/foundations#5591]
**Summary**
Hi Reapit,

We are currently investigating ways to track changes to relationships between contact/company entities and applicant/vendor/landlord/tenant entities, especially when a relationship has been removed.

**Detail and or supporting links and screenshots**
We've had a few cases reported to us where a customer has removed a relationship from a contact and added applicant/vendor/landlord/tenant involved to another contact (creating a new relationship), and we are looking to replicate this change in our system. 

We were wondering if doing this would update the 'modified' datetime value for both contacts involved?

The main issue we are trying to solve is how we can track relationships that are removed from a contact/company. Would web hooks be the only solution here?

It may be a bit unclear what I'm asking here, so please feel free to ask me any questions.

Many Thanks,

Henry Fitch
BriefYourMarket

**Comment by BenjaminBrain** [comment]
Hi,

So we can set expectations with mutual clients, could someone give me an indication of when this ticket may be looked into please.

Many thanks for your help.

**Comment by BenjaminBrain** [comment]
Hello, 

Any updates on this?

Thanks, Ben.
