### ISSUE TITLE
Access to 'Extras' Field via Foundations API for all recently migrated offices

### ISSUE THREAD

**Issue by Alec-Connells** [reapit/foundations#5608]
**Request**

In order for us to grant access to Semi-structured 'extras' field data, please provide the following information in this request:

- The name of the customer you represent - Connells Group
- as per #5158 field identity is oInetRM (Rigthmove Id)
- A screenshot of of the field(s) you require in the agency cloud user interface - not available in UI
- A short use case as to why you require this data - So we can store this and use it for external integrations

**Specification**
- Update customer configurations for the customers under the Connels group to include the oInetRM property

**Comment by plittlewood-rpt** [comment]
Hi @Alec-Connells - this field is now available for all organisations under the Connells group.
