### ISSUE TITLE
Best approach for fetching bulk property feed data

### ISSUE THREAD

**Issue by bobf** [reapit/foundations#5609]
**Summary**

We (at Homeflow) would like to migrate our property feeds away from Reapit Web Services onto Reapit Foundations. I have a few (hopefully) simple questions around this:

* Should we expect much difference in data structure and formatting between the Foundations output and Web Services ? i.e. if we handle the differences in transport/authentication/etc. then should we expect largely the same data to be returned ? Or will we need to modify our data adapters to deal with an entirely new data format ? We can deal with JSON vs XML easily but will take more work if we also need to update mapping tables, data structure changes, etc.
* We currently make periodic requests to Reapit Web Services for all of our Reapit clients' data. Using Foundations, what would be the opitmal/recommended way to do this ? Should we continue to make periodic requests to Foundations property data endpoints or should we work exclusively with webhooks ? We want to find the most cost-effective way of receiving this data while also adhering to Reapit best practices and ensuring timely delivery of client data.

**Detail and or supporting links and screenshots**
N/A

**Comment by HollyJoyPhillips** [comment]
Whilst the nature of the request has been accepted, we are unable to commit to a specified sprint and therefore will assign your issue to the ‘Long Term’ column. We will regularly review any issues and where development capacity is available, or work is aligned with our Roadmap, the issue will be updated.

**Comment by plittlewood-rpt** [comment]
Hi @bobf 

Thanks for reaching out. To answer your questions

1) The Foundations Platform APIs are brand new APIs with very different contracts to the legacy SOAP service. As such you will need to account for these differences in your application. I'd encourage you to have a look at the [Swagger API page here](https://developers.reapit.cloud/swagger) in the developer portal where you can have a look at the models that the API will respond with, and also read through our [extensive documentation here](https://developers.reapit.cloud/api-docs)

2) How you manage your data refresh is entirely up to you and it ultimately depends on your use case. Using webhooks will often mean you are sent updates that you don't really care about, which can increase cost unnecessarily. If you don't need things to be in near real-time and can afford a slight delay, it will be most cost effective polling for changes as you can keep control of how often you check for changes. With webhooks this is completely out of your hands and any batch update to data by our customers will result in you receiving notifications at the same rate. We've got developers using both mechanisms with no issues, and it does all come down to your own individual use case.

I hope this helps. Please reach out again if you need any further clarification

**Comment by bobf** [comment]
@plittlewood-rpt Thank you - that's extremely helpful.
