### ISSUE TITLE
Incorrect rent frequency

### ISSUE THREAD

**Issue by tim-west** [reapit/foundations#5619]
**Describe the bug**
When a lettings property is launched on AgencyCloud with the rent frequency set to per week, it returns "monthly" in the API. This causes the website to show the monthly prices rather than weekly. As a workaround you have to go back into the property and save the rent frequency as per month before then saving it as per week again, which then causes the API to correctly return "weekly".

It happens on all requests that would include a price for a property e.g. https://platform.reapit.cloud/properties/{{propertyID}}

**Expected behaviour**
The API should return the correct rent frequency i.e. weekly or monthly based on the on what is set in AgencyCloud.

**Specification**
- Recreate the issue. Suspicion is that this is being caused by the default value in Agency Cloud being set to weekly which does not get explicitly stored in the database. The API is likely making the assumption that customer default's are set to monthly. At the point of changing the rent frequency in agency cloud and back again, the weekly qualifier DOES get saved to the database, hence the API output corrects itself
- Review best mechanism to pass the required configuration down to the service and present back to team for agreement on approach. Consider packaging up mechanism to access config from the brokers (or services themselves) in a generic fashion

**Comment by michaelwoodCSM** [comment]
Foundations team, do we have any further update on this ticket for Druce?

**Comment by RWilcox-Reapit** [comment]
Hi both @michaelwoodCSM and @tim-west ,
We've had a discussion on this ticket today and it's being pulled into this sprint to start work on correcting the output.

**Comment by tim-west** [comment]
My client is still experiencing the same issue. Tested by adding two new properties yesterday (20/12/21).
