### ISSUE TITLE
Querying contacts by email/s times out with a 504

### ISSUE THREAD

**Issue by designreact** [reapit/foundations#5623]
**Describe the bug**

In the sandbox the following requests behave as expected

contacts/?email=vendor1@email.com
contacts/?email=vendor1@email.com&email=vendor2@email.com

Repeating this on my clients production account with valid customer email/s times out with a 504.

**Expected behaviour**
The API should return a response.

**Specification**
- Alter the contacts service to use the phone table when emailAddress parameter is passed
- Also update applicants service in the same way
- Where this parameter is passed do an explicit search on the phone table first, passing the resulting ids through to the main filter predicate builder to ensure the results are still filtered in the event any additional query string parameters are passed

**Comment by designreact** [comment]
N.B. it looks like we have the same issue with `emailAddresses` on `applicants/`

**Comment by plittlewood-rpt** [comment]
Hi @designreact - we have discussed the best short term solution to the problem you  have reported and moved it to our Near Term column. We will be planning next week's sprint tomorrow and I will do my best to ensure it is included.

@HollyJoyPhillips  FYI

**Comment by designreact** [comment]
Thank you 👍

**Comment by RWilcox-Reapit** [comment]
Hi @designreact - This has now been optimized and you should see much faster response times.

Thanks, Ryan

**Comment by designreact** [comment]
That's great news! Tested and working.

Could we get the same for `/applicants` please? As that appears to do the same.

Thanks guys, keep up the good work!
