### ISSUE TITLE
Add query param `emailAddresses` to GET /tenancies, /landlords, /vendors

### ISSUE THREAD

**Issue by stuhuntington** [reapit/foundations#5624]
**Is your feature request related to a problem? Please describe.**
Need to be able to look up landlords / tenants / vendors based upon email addresses

**Describe the solution you'd like**
To implement the ability to add `emailAddresses` query parameter in similar fashion as is allowed on GET /applicants endpoint for the /tenancies /vendors / landlords endpoints

**Specification**
- Implement email address search capability in the services mentioned above. Only do this ticket after the bug in #5623 is rolled out and follow the same approach

**Comment by designreact** [comment]
@RWilcox-Reapit FYI We noticed email params also cause a 504 on the /applicants endpoint too.
