### ISSUE TITLE
Investigate issue with LINQ query cache returning old values

### ISSUE THREAD

**Issue by plittlewood-rpt** [reapit/foundations#5636]
Ticket to account for time relating to investigation around LINQ query caching

**Comment by Daniel-GabrielN** [comment]
Hi, is there any update? 
https://github.com/reapit/foundations/issues/5680#issuecomment-1014656435

**Comment by plittlewood-rpt** [comment]
Hi @Daniel-GabrielN - that is a lot of 404s. There is no update at present unfortunately. Can you give me some example calls from today and the time frame?

**Comment by plittlewood-rpt** [comment]
@Daniel-GabrielN I've just checked our logs and can't see anywhere near that volume of 404s on the propertyImages endpoint in the last 6 hours. Are you getting 404s when hitting the propertyImages endpoint itself or when you try to access the URLs returned by that endpoint? I'm not convinced this is the same issue that this ticket relates to, so the more detail you can provide about the issue's you've experienced today the better

**Comment by Daniel-GabrielN** [comment]
can I email you some logs?

**Comment by plittlewood-rpt** [comment]
I am looking at one particular example where you attempted to access a particular property for customer LEA. There is no property with that code in that customer's dataset. Can I just check, are you getting a new access token when you switch out your reapit-customer header? If not, you'll likely run into the problems you are experiencing as the authorisation tokens are cached for a short period of time for performance reasons.

**Comment by Daniel-GabrielN** [comment]
@plittlewood-rpt We are not doing that.
It was not in the docs before 29th of November 2021 https://github.com/reapit/foundations-documentation/commit/9e9f32960d418da4cf0bcb991a0c09cc76ec6ba5

Our apps are built to work with many customers and there are a lot of requests. There could be requests for two customers at the same time. 
Should we get a token before each request?

**Comment by plittlewood-rpt** [comment]
Hi @Daniel-GabrielN  that will be the problem. Yes it was added to the docs late last year so might not be something you were aware of. I'm currently looking at if/how we can alter the authorization caching mechanism to take this header into account to prevent you having to get a new token whenever you change the value but for now yes you would need to do that.

**Comment by plittlewood-rpt** [comment]
We have been able to identify the issue in an external dependency. An update to this dependency is already planned as part of #5191 so we can now close this ticket.
