### ISSUE TITLE
Order of images in API does not match Agency Cloud

### ISSUE THREAD

**Issue by david-silverink** [reapit/foundations#5642]
Included field 'order' does not correspond with order of images as set by client. Example property is LUC210168
The API says that image _10 is order number 1, yet in Agency Cloud it is number 8.

**Comment by plittlewood-rpt** [comment]
Hi @david-silverink - thanks for raising this issue. I need to liaise with our desktop team about this because it appears the behaviour may have changed slightly in Agency Cloud when the new interface for the property images screen was introduced, which is why you are seeing what you have reported. I will get their input on this ticket before deciding how we best proceed.

**Comment by plittlewood-rpt** [comment]
@david-silverink Users can resolve this problem by dragging the main image to position 2 and then back to position 1 again. I've been able to recreate the behaviour that puts the data in the state you are seeing and will report this to our desktop developers. It might be that we have to put something into the API itself depending on what their feedback is

**Comment by david-silverink** [comment]
That's great @plittlewood-rpt, the agents have an interim solution to the problem. I'll pass on your note. Thanks

**Comment by plittlewood-rpt** [comment]
@david-silverink We've been looking at this further today and unfortunately it's going to need to be resolved in Agency Cloud. The only way we could mitigate it in the platform (without adding a load of overhead) would be to add a "main image" type identifier (`isMain: true` kind of thing) however I don't want to be adjusting the contract just to deal with a bug which, once resolved, would make that field effectively redundant (order = 1 should be enough to signify the main image). I'm going to leave this ticket in Not ready until I've got some more feedback from our desktop team

**Comment by david-silverink** [comment]
Thanks @plittlewood-rpt

**Comment by plittlewood-rpt** [comment]
Hi @david-silverink - as this needs to be resolved at source I am going to close out this ticket. Thanks
