### ISSUE TITLE
Can I get the Marketing Status when downloading reports

### ISSUE THREAD

**Issue by jennyCognio** [reapit/foundations#5664]
Hi
We're often asked to download contacts for mailing purposes and do this through the reports system, but we can't choose to include the marketing flag status in the download. 

Is it possible to add this please?

Thanks
Jenny

**Comment by plittlewood-rpt** [comment]
Hi @jennyCognio 

I'm not sure what you mean by "downloading contacts through the reports system" - can you clarify? The marketing consent status is available in the contacts model (field `marketingConsent`) which you can also filter by

Thanks
Pete

**Comment by jennyCognio** [comment]
Thanks Pete
I hadn't realised I could also add the contact marketing status filter.

I'll close this ticket
