### ISSUE TITLE
API potentially returning incorrect data

### ISSUE THREAD

**Issue by rhenesy** [reapit/foundations#5672]
A data record error has been identified whereby the landlord and property we are seeing via the API don't match what the client sees on their system. Please could you help us investigate? Currently unsure if this is your side or ours or both.

Additional sensitive information (include screenshot of the client's Reapit system and record being seeing by Helpthemove via the API integration) has been sent to the foundations support inbox. They have advised they will circulate the information to the relevant team members at the ticket review stage.

**Comment by plittlewood-rpt** [comment]
Hi @rhenesy - I have reviewed the content of your email, and we will respond to you via email
