### ISSUE TITLE
Intermittent and unexpected 404 response from GET /properties/{id}?embed=images

### ISSUE THREAD

**Issue by JamieDunstan** [reapit/foundations#5680]
**Describe the bug**
Occasionally, when we make a call to `/properties/{id}?embed=images` we will receive a 404 NotFound response. When we retry the call, the property data is correctly returned.

**To Reproduce**
I cannot be totally specific on reproduction steps for this sorry, so I will try my best to explain. Within our app, we will receive a large batch of webhooks with a `propertyimages.modified` topic. When we attempt to process this batch, we will make a call to `/properties/{id}?embed=images`. This is when the call fails with a 404 response. The image modification messages are requeued internally so that we can retry the operation. After a few retries, the call to get the property will be successful. 

Is there a delay in the property data being available at the `/properties/{id}?embed=images` endpoint after it is created in RPS? We know the property exists, because we are seeing the `propertyimages.modified` topic (and as far as I know this would not be possible without a property). We also know that the call succeeds on subsequent attempts.

Can you please investigate this issue and report back?

Our most recent logs for this problem show that we attempted this server call three times before it eventually succeeded on the fourth attempt. The failed attempts were at the following times (times are UTC):

Dec 10, 2021 @ 15:47:58.625
Dec 10, 2021 @ 15:47:28.573
Dec 10, 2021 @ 15:47:18.506

**Comment by plittlewood-rpt** [comment]
Hi @JamieDunstan - please can you send over the customer id of the customer concerned?

**Comment by plittlewood-rpt** [comment]
It's likely this is related to #5687

**Comment by JamieDunstan** [comment]
Hi @plittlewood-rpt thank you very much for your reply.

In the most recent example of this problem, the CustomerId is `NUM` and the PropertyId is `LEA210334`. The request we are attempting looks like this:

```cURL
curl --request GET \
  --url 'https://platform.reapit.cloud/properties/LEA210334?embed=images' \
  --header 'Authorization: Bearer TOKEN' \
  --header 'api-version: 2020-01-31' \
  --header 'reapit-customer: NUM'
```

The response I am seeing in our logs looks something like this:

```json
{
  "statusCode": 404,
  "dateTime": "2021-12-13T14:47:59.0518855Z",
  "description": "Entity 'Property' (LEA210334) was not found."
}
```

I also have recent log entries for other CustomerId / PropertyId combinations that have shown the exact same issue:

- CustomerId: `NUM`, PropertyId: `LEA190256`
- CustomerId: `DAH`, PropertyId: `COM210154`

Please let me know if there is anything else I can provide to assist. Many thanks for your help 👍

**Comment by plittlewood-rpt** [comment]
Hi @JamieDunstan - it looks like this is related to #5636. As a result I'm going to close this ticket. Please follow the other ticket for updates

**Comment by Daniel-GabrielN** [comment]
@plittlewood-rpt @AshDeeming Is there any update regarding this?
We have over 2.5k 404s in the last 6 hours, the situation is getting really bad.
