### ISSUE TITLE
Usage of address inside properties endpoint

### ISSUE THREAD

**Issue by Filip5991** [reapit/foundations#5686]
The properties endpoint includes an address object. The address object is split in multiple parts and lines, but with no particular order:
"address": {
        "buildingName": null,
        "buildingNumber": "15",
        "line1": "Example street",
        "line2": "Solihull",
        "line3": "West Midlands",
        "line4": "",
        "postcode": "B91 2XX",
        "countryId": "GB",
        "geolocation": {
          "latitude": 52.4158586,
          "longitude": 1.7773383
        }
      }
If I merge the non-nullable fields in a line, I'm later having problems using the generated address in other services like the land registry.
So with the example above, I'd use '15, Example street, Solihull, West Midlands' as the address, but this would not produce any results if entered in land registry.
Is there a way or rule to get/format the address that's returned by the properties endpoint, so that it looks like it was formatted by an address lookup tool, and can be later used in other services?

**Comment by plittlewood-rpt** [comment]
Hi @Filip5991 - you would need to format the address yourself as required. Typically there'll never be any punctuation between the building number and line 1 which might be your issue? Our systems don't have dedicated fields for town and the like, we just have address lines 1-4 which keeps it very flexible.

**Comment by Filip5991** [comment]
Hi @plittlewood-rpt, thank you for reaching out.
I don't think the punctuation is the problem here.

If I need the town or street, to later use them in 3rd party services, I wouldn't be able to distinguish neither the town nor the street, if they are somewhere inside the 4 lines, and we can't tell which line exactly

Is there an 'automatic' way to get only the street from the 4 lines, without the need of a human eye reading the 4 lines, and then deciding what could be the town if there is one, the region, the street etc.?

**Comment by plittlewood-rpt** [comment]
HI @Filip5991 

As mentioned our address structure is a four line structure. It is down to each customer to decide which lines to use for which part of the address. This makes the structure geographically flexible as it can translate to other global regions and still make sense. The platform does not provide an automatic means of detecting which address line is a town/street etc at this time

You can generally assume that line1 will always be the street, and line2 will normally be the town but that's not something we guarantee.

Hope this helps
Pete

**Comment by Filip5991** [comment]
Grateful for the feedback...but it doesn't really resolve the problem being posted here. Clients are asking for a solution so we need to move away from what's in place really and look to solve the problem. 

Some clients say they use address look up inside Reapit - is that true? If so can't the selected address be sent over via the api? Open to any ideas of course.

**Comment by plittlewood-rpt** [comment]
Hi @Filip5991 - there is an address lookup inside Reapit yes, typically an integration with postcode software or similar (so customers enter a postcode then get a list of addresses to pick from). The selected address is then populate on the property record. I understand your issue, but how you decide to use the data coming out of the APIs is down to you as the developer. You can either take it in the structure we provide it, or build your own intermediary step to parse it as required.

**Comment by plittlewood-rpt** [comment]
Hi @Filip5991 - I have not heard from you since my latest comment and will therefore close the ticket. As our addresses are stored in a fairly loose format it's down to you as the developer to format as required. Please reach out again if we can assist further
