### ISSUE TITLE
Unexpected empty images response from API

### ISSUE THREAD

**Issue by JamieDunstan** [reapit/foundations#5687]
For our app, we will often query for the images related to a property using the following request as an example:

```cURL
curl --request GET \
  --url 'https://platform.reapit.cloud/propertyImages/?pageSize=100&pageNumber=1&propertyId=PROPERTY_ID' \
  --header 'Authorization: Bearer TOKEN' \
  --header 'api-version: 2020-01-31' \
  --header 'reapit-customer: CUSTOMER_ID'
```

Occasionally, this request will respond back as successful (status code 200), but will not contain image data. Our deserialized response object looks like this:

```json
{
  "_embedded": [],
  "pageNumber": 1,
  "pageSize": 100,
  "pageCount": 0,
  "totalPageCount": 0,
  "totalCount": 0,
  "_links": {
    "self": {
      "href": "/propertyImages/?PageNumber=1&PageSize=100&propertyId=PROPERTY_ID"
    },
    "first": {
      "href": "/propertyImages/?PageNumber=1&PageSize=100&propertyId=PROPERTY_ID"
    }
  }
}
```

We are absolutely certain that the property/customer combination does indeed have images. This can be proven by the fact that if we repeat the exact same request, we will retrieve the correctly populated image data.

Are you aware of any intermittent issues relating to querying image data for a property? 
Do you know why we occasionally get back an incorrect/empty response from the API?
Am I right in saying that the possible responses from this endpoint are either 200 success, 400 bad request or 403 forbidden? I just want to make sure we are not receiving a "success" status code alongside an unexpected response format since we are deserializing the json response into a C# object.

I would love to get to the bottom of this since it is dramatically impacting our apps operation and importantly, I believe we are being charged for these requests that are returning incorrect empty image data.

All information and investigation is appreciated. Thank you.

**Comment by plittlewood-rpt** [comment]
Hi @JamieDunstan - this is odd behaviour. Have you seen any patterns surrounding when it seems to occur?

**Comment by JamieDunstan** [comment]
Hi @plittlewood-rpt - I can't see any obvious patterns around this problem sorry - we most commonly see it when we are attempting to resynchronise all of our property listings with the customer's property data. When this resync operation occurs, I very often see a large spike in our logs/metrics that state we are rejecting properties because of "0 images". For 99% of those properties I can simply retry the resync operation and images will be found. It's incredibly frustrating. I am very sorry that I can't be more specific. I will continue to investigate from our side but any help you can provide would be massively appreciated. Thank you 👍
