### ISSUE TITLE
GeoDiary - Viewing Arrangement & Key Details 

### ISSUE THREAD

**Issue by JoCauser** [reapit/foundations#5688]
Currently the GeoDiary app does not pull through viewing arrangements or key details. Appointments with a type of 'meeting' do not display the details as a viewing would. This means the app cannot be fully relied upon by staff always out of the office.

Meeting details, Viewing Arrangements and Key details should be included in the Geodiary appointment view. 

Staff currently having to use paper print outs to supply the extra information which is disorganised and not data secure.

**Comment by willmcvay** [comment]
@JoCauser  This should be fixed in the main GD app - as discussed, it looks like the client is using the old beta. Will update the beta - let me know if this doesn't fix it.

**Comment by JoCauser** [comment]
Thanks Will - is this just the Viewing Arrangements element that has been updated?

**Comment by willmcvay** [comment]
@JoCauser They should also now have "Add Follow Up Notes" which wasn't in the original beta plus a couple of fixes.

**Comment by willmcvay** [comment]
@HollyJoyPhillips Spoke to @JoCauser and there is a request to add keys for properties to Geo Diary. Seems a sensible feature and reasonably trivial so said we'd look at it when you're back after Christmas
