### ISSUE TITLE
Research best mechanism for implementing a cache in front of the configuration service

### ISSUE THREAD

**Issue by plittlewood-rpt** [reapit/foundations#5697]
**Background context**
A number of our services are needing to becoming more aware of customer configuration settings to allow defaults etc to be taken into account. Making an HTTP call to the configuration service every time somebody makes a request is expensive and adds unwanted latency. We should look into introducing a caching layer in front of this service, powered by something like Elasticache/Redis or similar which is hit first. Requests should only then get forwarded to the backend service to hit the database at the point a cache item has expired, or is missing entirely. The configuration client package is probably the best place to do this as this package can then just be used in any service that needs configuration data.

For phase 1 we can just use a memory cache in each service to prove the concept. Distributed caching can come later and may not even be needed

**Specification**
- Project: Reapit.Packages.ConfigurationClient
- Add `IMemoryCache` to Get mechanism in this package that stores customer configuration data in the following format:

```
{
   "key": "XXX-buyingReasons" (customer id WITHOUT office group and configuration type)
    "value": {
          // data that comes back from the configuration service
    }
}
```

- IMemoryCache instance should purge items after 30 minutes by default, but can be overridden by a configuration setting in the /Platform/Services/Common namespace
- Package update will need to go out to any service that is using it. List TBC but these ones definitely are
  - Applicants
  - Contacts
  - Properties
- Reapit.Packages.PlatformIdentityManager has an implementation of IMemoryCache and can be used as a reference point

**Comment by HollyJoyPhillips** [comment]
PL, RW & HP: Reviewed
