### ISSUE TITLE
plot issues

### ISSUE THREAD

**Issue by Z3nAg3ncy** [reapit/foundations#5699]
the plots are not separated from the land and are not loading into the plots section on our site as there is no identification coming from reapit allowing us to sort these correctly

**Comment by plittlewood-rpt** [comment]
Hi @Z3nAg3ncy - to allow us to investigate your problem, please complete all the information requested when using the Bug ticket template

**Comment by Z3nAg3ncy** [comment]
-	“it's probably because there's no categories on them so I don't know where to put them

yeah, first one "Land At Kilchamaig Gate, Tarbert", doesnt have a type, so there's no way for me to tell it's land

can they advise how I'm supposed to know... is it just if there's no type we assume it's land?

here's the data for Mabie Steadings (#2 on the list above) http://jsonblob.com/917748807622737920
12:07
You can see on line 76 there's no type, style, or situation

![image](https://user-images.githubusercontent.com/30283113/146186318-fc11125e-f8c2-406f-93cf-cee502c5737a.png)
![image](https://user-images.githubusercontent.com/30283113/146186333-1fed28a5-6b91-47ec-9e53-2e1697458b82.png)

**Comment by Z3nAg3ncy** [comment]
Hi Pete

 

Can you advise when this is implemented, and the steps required for this to be pulled through and correctly listed with the changes made from your end?

 

Kind regards

 

Alan

**Comment by plittlewood-rpt** [comment]
Hi @Z3nAg3ncy - if you subscribe to #5705 you'll get notifications when it gets completed

Thanks
