### ISSUE TITLE
brochure nor loading 

### ISSUE THREAD

**Issue by Z3nAg3ncy** [reapit/foundations#5701]
brochure is not showing on berryknowe as the feed is not supplying the information

**Comment by plittlewood-rpt** [comment]
Duplicate of #5700 and incomplete information

**Comment by Z3nAg3ncy** [comment]
brochure not loading error from feed ![image](https://user-images.githubusercontent.com/30283113/146184829-b316b99d-e9c7-4222-b10e-7981ed1ba159.png)
