### ISSUE TITLE
feed not working and locked out

### ISSUE THREAD

**Issue by Z3nAg3ncy** [reapit/foundations#5702]
we are locked out the feed from the api and the site is not updating

**Comment by plittlewood-rpt** [comment]
@Z3nAg3ncy to allow us to investigate your issue please provide comprehensive details of the problem you are facing. We do not currently have enough information to start investigating. Thanks

**Comment by Z3nAg3ncy** [comment]
this is the error we are getting the feed was not working 
![image (9)](https://user-images.githubusercontent.com/30283113/146185186-4e30ffea-ebd4-4d21-8124-0af551009ec6.png)

**Comment by Z3nAg3ncy** [comment]
![image (10)](https://user-images.githubusercontent.com/30283113/146188321-b7aa7978-6efa-46f8-b02c-175256d3c164.png)
this is what we were encountering this morning

**Comment by plittlewood-rpt** [comment]
@Z3nAg3ncy that would suggest the password for that account has been changed. If you are not Moira you will need to reach out to her, although sharing account is strictly discourages for security reasons

**Comment by Z3nAg3ncy** [comment]
its not been changed please advise

**Comment by plittlewood-rpt** [comment]
I can see invalid authentication attempts from this morning from IP address 213.xx.xxx.172 - is this you? What URL are you logging into? I need as much information as you can provide to be able to assist you

**Comment by Z3nAg3ncy** [comment]
that's all the info we have

**Comment by plittlewood-rpt** [comment]
You must know what you're attempting to log into (URL etc) and what your IP address is. The error suggests the password is wrong and I can see that there were two failed logins (due to an incorrect password) from the IP address listed above. If you are a customer of Reapit's (I don't think you are looking at your username) and are having issues logging into Agency Cloud then you need to contact our main helpdesk.

**Comment by Z3nAg3ncy** [comment]
why did it work and now is not working when we use the same account access information?

**Comment by plittlewood-rpt** [comment]
I cannot comment on why a password that appears to be for someone elses account is not working. The issue with you getting a 400 errors when requesting pDirections was sorted by our infrastructure team earlier on today. If you still have an issue please provide comprehensive information about the request you are making so I can diagnose the problem

**Comment by plittlewood-rpt** [comment]
@Z3nAg3ncy - please can you confirm if all your outstanding issues are now resolved?

**Comment by Z3nAg3ncy** [comment]
Any word on the plots

**Comment by plittlewood-rpt** [comment]
That is in a different ticket, but I have pulled it into this sprint for you and the release should go out shortly.

**Comment by Z3nAg3ncy** [comment]
Thanks

 

Alan

**Comment by plittlewood-rpt** [comment]
That update has now gone out Alan

**Comment by Z3nAg3ncy** [comment]
That’s great Pete how will we implement this from our end or Bell Ingram End 

 

Thanks

 

Alan

**Comment by plittlewood-rpt** [comment]
Any properties marked as "Building Plot" by Bell Ingram will now appear in the API as `type = developmentPlot` which is what you need to check for when processing the data
