### ISSUE TITLE
Instruction Data via REAPit front end and API are different Date Values

### ISSUE THREAD

**Issue by agouriet** [reapit/foundations#5713]
Hi REAPit,

I am currently working on the API feed we have setup from REAPit into our SQL database for our marketing system.

We are currently working on the latest properties onto the market based on the instructed date. On further investigation, it seems that the instructed date does not actually match the instructed date from the front end of REAPit in many cases.

A few examples would be as follows:

1) Ref MAS211007 - This property on the front end of REAPit provides the date 03/12/2021 but in the database, the date given via the API is 02/12/2021

2) Ref CRS210371 - This property is a pre appraisal and from the front end and has no instructed date as not been 'for sale - available. Even though, from the API it says that this property was instructed on: 2021-11-25 00:00:00.0000000

3) FNB211338 - Another pre-appraisal that has never been on the market.. This also shows an instructed date of 2021-11-08 00:00:00.0000000

In addition to this, I have also found records that are up to 2 weeks difference between the dates on the REAPit frontend and and API's selling instructed date.

Is this a known bug? Is there a more reliable way of pulling thee instructed dates?

We will be using this data to automate a marketing send out of a 'welcome pack' so for this reason, we need to the dates to be correct so that something isn't sent to people who aren't even on the market with us.

If you need any further information on this, please feel free to ask.

Regards

Andy

**Comment by plittlewood-rpt** [comment]
Hi @agouriet - please can you confirm the agent this relates to?
