### ISSUE TITLE
Journal entries post endpoint problem

### ISSUE THREAD

**Issue by Filip5991** [reapit/foundations#5725]
Hello,
Starting December 17 (Friday), I noticed that all journal entries started failing. Nothing has changed in the requests that were previously succeeding, so I was wondering if the endpoint has a problem? 

The error is '504 gateway timeout', but I think this is only because of some other unreachable resource.

Apologies if this section is not the right one for problems of such type :)

**Comment by plittlewood-rpt** [comment]
Hi @Filip5991 do you have the customer id of the customer concerned please?

**Comment by plittlewood-rpt** [comment]
Hi @Filip5991 - this should now be resolved. I will close this ticket and post updates on #5733 - many thanks

**Comment by Filip5991** [comment]
Hi @plittlewood-rpt, I'm afraid it happens for every customer that has our app installed. 2 IDs I can provide are 'MPE' and 'JOR', both have errors writing to journal
