### ISSUE TITLE
Double embedding data

### ISSUE THREAD

**Issue by Filip5991** [reapit/foundations#5726]
Hello,

I know the API offers an option to embed items with each endpoint call.
What I was interested to ask was if embedded items can have their own embedded items?

For e.g. I'm interested in appointments, for each appointment the property, and for each property the vendor/landlord 

I know that properties can be embedded in the appointments call:
https://platform.reapit.cloud/appointments/?embed=property
and that vendors/landlords can be embedded in the properties call:
https://platform.reapit.cloud/properties/?embed=landlord&embed=vendor 
But can they all be in a single call, and if so how?

**Comment by plittlewood-rpt** [comment]
Hi @Filip5991 . This isn’t something that is currently possible I’m afraid. If you think it would be something that would add value please feel free to flesh out your request with a bit more detail and we will review it in line with our published development processes. Thanks
