### ISSUE TITLE
IS_DELETED column

### ISSUE THREAD

**Issue by matt-austin-andrews** [reapit/foundations#5728]
**Background context**
As an ETL developer, I want to be able to create history tables in my own data warehouse. This is not currently possible without an `IS_DELETED` or `SYNCHDEL` equivalent column (like in the operational database). 

**Specification**
Please amend the analytics schema views to include deleted records. Please also update the `RECORD_STATE` column to also include a 'Deleted' state, or add an `IS_DELETED` column similar to that in the operational database.

**Comment by HollyJoyPhillips** [comment]
After investigating the setup between AgencyCloud and the Analytics schema, unfortunately this is not something we will be able to implement.
