### ISSUE TITLE
Error with Reapit's API / error logging journal entries

### ISSUE THREAD

**Issue by pt-deployer** [reapit/foundations#5733]
Hi There,

I'm writing from LeadPro, we have an integration in place with Reapit Foundations, that allows our users to sync their leads directly with their Reapit account.

Starting yesterday, we have been experiencing critical issues with the inability to sync those leads with Reapit, and the users trying to utilize the lead syncing feature receive the Internal Server error. 

Our developers have investigated and have found an issue with Reapit API for journal entries.

Here is request/response when trying to fetch all journal entries (the same is for CREATING Journal entry):

REQUEST:

curl -X 'GET' \

'https://platform.reapit.cloud/journalEntries/' \

-H 'accept: application/json' \

-H 'api-version: 2020-01-31' \

-H 'Authorization: Bearer eyJraWQiOiJFXC9TcnVuTzVCR0xBMk1yT3phY2RjWFkwVVdqRVB1cVB5N3hIb1FWbnJGdz0iLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiI1YjAwZDkyZS1lYmRkLTRmMzUtOGJmZi1mMGEyOTZjYWZiOTAiLCJjb2duaXRvOmdyb3VwcyI6WyJGb3VuZGF0aW9uc0RldmVsb3BlckFkbWluIiwiRm91bmRhdGlvbnNEZXZlbG9wZXIiLCJBZ2VuY3lDbG91ZERldmVsb3BlckVkaXRpb24iXSwiaXNzIjoiaHR0cHM6XC9cL2NvZ25pdG8taWRwLmV1LXdlc3QtMi5hbWF6b25hd3MuY29tXC9ldS13ZXN0LTJfZVE3ZHJlTnpKIiwidmVyc2lvbiI6MiwiY2xpZW50X2lkIjoiNGw2ajB1bnFvbDRrMDJic2w2cTg5b2RlbTUiLCJldmVudF9pZCI6ImQ2N2E4NWMzLWQ4MWItNGNjMy05NDZmLTY5MGU1ZjM4NGNlYiIsInRva2VuX3VzZSI6ImFjY2VzcyIsInNjb3BlIjoiYWdlbmN5Q2xvdWRcL2xhbmRsb3Jkcy5yZWFkIGFnZW5jeUNsb3VkXC9vZmZpY2VzLndyaXRlIGFnZW5jeUNsb3VkXC9vZmZlcnMucmVhZCBhZ2VuY3lDbG91ZFwvcHJvcGVydGllcy53cml0ZSBhZ2VuY3lDbG91ZFwvYXBwbGljYW50cy53cml0ZSBhZ2VuY3lDbG91ZFwvdGFza3MucmVhZCBhZ2VuY3lDbG91ZFwvaWRlbnRpdHljaGVja3MucmVhZCBhZ2VuY3lDbG91ZFwvcGF5bWVudHMucmVhZCBhZ2VuY3lDbG91ZFwvaWRlbnRpdHljaGVja3Mud3JpdGUgYWdlbmN5Q2xvdWRcL2tleXMucmVhZCBhZ2VuY3lDbG91ZFwvbGFuZGxvcmRzLndyaXRlIGFnZW5jeUNsb3VkXC9jb252ZXlhbmNpbmcud3JpdGUgYWdlbmN5Q2xvdWRcL2VucXVpcmllcy5yZWFkIGFnZW5jeUNsb3VkXC9zb3VyY2VzLndyaXRlIG9wZW5pZCBwcm9maWxlIGFnZW5jeUNsb3VkXC9wYXltZW50cy53cml0ZSBhZ2VuY3lDbG91ZFwvbmVnb3RpYXRvcnMud3JpdGUgYWdlbmN5Q2xvdWRcL2FwcGxpY2FudHMucmVhZCBhZ2VuY3lDbG91ZFwvbmVnb3RpYXRvcnMucmVhZCBhZ2VuY3lDbG91ZFwvdmVuZG9ycy53cml0ZSBwaG9uZSBhZ2VuY3lDbG91ZFwvam91cm5hbGVudHJpZXMucmVhZCBhZ2VuY3lDbG91ZFwvY29tcGFuaWVzLndyaXRlIGFnZW5jeUNsb3VkXC9wcm9wZXJ0aWVzLnJlYWQgYWdlbmN5Q2xvdWRcL3ZlbmRvcnMucmVhZCBhZ2VuY3lDbG91ZFwvY29udGFjdHMucmVhZCBhZ2VuY3lDbG91ZFwvaW1hZ2VzLndyaXRlIGFnZW5jeUNsb3VkXC9kb2N1bWVudHMud3JpdGUgYWdlbmN5Q2xvdWRcL3Rhc2tzLndyaXRlIGFnZW5jeUNsb3VkXC90ZW5hbmNpZXMud3JpdGUgYWdlbmN5Q2xvdWRcL2NvbXBhbmllcy5yZWFkIGFnZW5jeUNsb3VkXC9lbnF1aXJpZXMud3JpdGUgYWdlbmN5Q2xvdWRcL2NvbnZleWFuY2luZy5yZWFkIGFnZW5jeUNsb3VkXC9rZXlzLndyaXRlIGFnZW5jeUNsb3VkXC93b3Jrc29yZGVycy53cml0ZSBhZ2VuY3lDbG91ZFwvZG9jdW1lbnRzLnJlYWQgYWdlbmN5Q2xvdWRcL29mZmVycy53cml0ZSBhZ2VuY3lDbG91ZFwvam91cm5hbGVudHJpZXMud3JpdGUgYWdlbmN5Q2xvdWRcL2FwcG9pbnRtZW50cy53cml0ZSBhZ2VuY3lDbG91ZFwvdGVuYW5jaWVzLnJlYWQgZW1haWwgYWdlbmN5Q2xvdWRcL2FyZWFzLndyaXRlIGFnZW5jeUNsb3VkXC9jb250YWN0cy53cml0ZSBhZ2VuY3lDbG91ZFwvaW1hZ2VzLnJlYWQgYWdlbmN5Q2xvdWRcL3dvcmtzb3JkZXJzLnJlYWQgYWdlbmN5Q2xvdWRcL29mZmljZXMucmVhZCBhZ2VuY3lDbG91ZFwvYXBwb2ludG1lbnRzLnJlYWQgYWdlbmN5Q2xvdWRcL3RyYW5zYWN0aW9ucy5yZWFkIiwiYXV0aF90aW1lIjoxNjQwMDAwODgzLCJleHAiOjE2NDAwMDQ4NDMsImlhdCI6MTY0MDAwMTI0MywianRpIjoiYzZkYmI5ZWYtOTA5ZC00Zjk3LTgzZTQtZjZkNGEyMjAwZDY4IiwidXNlcm5hbWUiOiI1YjAwZDkyZS1lYmRkLTRmMzUtOGJmZi1mMGEyOTZjYWZiOTAifQ.Pvt40i7czy0UMF7MNFFewNuZGl6nCeimpMMx6ybKZPFQjVCn3RqLo7dtHULwKc1Ws3rdSggv5ilzqiOpINqslXu9gw8JuiOwdAh9qpa9uz10JWUrtZmFaSq-5jx8k5NVQrbsJvNmdn7lb2AHlS1WThjwyjsSzEezxibyAyT2QMyWGAosnNomGmFVjVzr9r-P6RYdozvW11oyicSjLaoKIuQndS2vz0B3Fq6F_DMRc-ZVZI3Ethoy_p_XxysGcwfajp5-G3l6E1ORXmYkMK2TvRkGKsfcfm9qHOZ3eks_fSVCCneUmjQk_-k4SrnckQCbZ3lXLDJKxns37EjjBeWBUA'

RESPONSE:

Failed to fetch.
Possible Reasons:
CORS
Network Failure
URL scheme must be "http" or "https" for CORS request.
 

A screenshot of the response is attached to this email. Any help is appreciated.

Best Regards,[](url
![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/22115028/146949035-ee1a5dc8-441d-4944-9ea2-57cc21681c96.png)
)

**Comment by plittlewood-rpt** [comment]
Hi @pt-deployer . thanks for reporting this.  Can you confirm which customers you are having this problem with, and if it’s all customers or just a selection?

**Comment by plittlewood-rpt** [comment]
Hi @pt-deployer - this issue should be resolved. For reasons currently unknown one of the API containers was not responding but continued to report as healthy so did not get automatically restarted. It will be the new year before we can investigate this properly but the immediate problem is sorted. If you can let me know if you can call these endpoints now I'd be grateful

**Comment by plittlewood-rpt** [comment]
We suspect this was down to a DNS problem which has since cleared. We have never seen this before but will continue to monitor to see if there are any reoccurrences of the problem.
