### ISSUE TITLE
/configuration/appointmentTypes endpoint not returning all types

### ISSUE THREAD

**Issue by iWader** [reapit/foundations#5737]
**Describe the bug**

Customer has an appointment type of `Inspection`, code `IV` setup in their account, however this is not visible on the `/configuration/types?type=appointmentTypes`, `/configuration/appointmentTypes`, or `/configuration/appointmentTypes/IV` endpoints

I assume this is a custom appointment type the customer has added as I do not see this in the dev sandbox

We've also noticed we are able to retrieve appointments from `GET /appointments?typeId=IV&embed=type` that have `{"type": null}` for the `_embedded` attribute

Customer is adamant they have not removed this appointment type themselves

**To Reproduce**

1. Call `GET /configuration/appointmentTypes`
2. Note missing appointment types

**Expected behaviour**

`GET /configuration/appointmentTypes` to include _all_ available appointment types for the user/account

**Specification**
- Ensure IV appointment type is returned from configuration service. Note that this is not always enabled by default, but can be returned in the standard list

**Comment by willmcvay** [comment]
@iWader So the behaviour you are describing seems correct. Customers can configure AgencyCloud and specifically in this case Appointment types to their needs. The developer sandbox only contains the "stock" appointment types, and will not contain anything specific to an individual customer. This is why we provide and endpoint to access the types as they will vary from customer to customer.

When you are in a production environment ie your customer has installed your app and has either logged in using Reapit Connect or for server side applications, you have applied the correct reapit-customer header, you should see the custom appointment types returned to you.

**Comment by plittlewood-rpt** [comment]
Hi @iWader - the inspection appointment type is only enabled in some systems as it's associated with some specific features of Agency Cloud. Can you confirm which customer is having the problem please so I can check their setup?

**Comment by iWader** [comment]
Thanks for the quick reply. I hope you both enjoyed the Christmas break :)

@willmcvay in the production environment we are not seeing the Inspection appointment type for this customer anymore. We first experienced this problem on the 18th Dec

@plittlewood-rpt the customer is Alexander & Co.

**Comment by plittlewood-rpt** [comment]
Hi @james-radweb this will be discussed in our refinement session tomorrow and scheduled. We need to add Inspection to the output from the configuration service.

**Comment by plittlewood-rpt** [comment]
Hi @james-radweb - IV is actually Inventory not Inspection. Can I just confirm that's what you're expecting?

**Comment by iWader** [comment]
Yes, sorry, Inventory is what we're after.

**Comment by plittlewood-rpt** [comment]
Hi @iWader thanks - it looks like this is actually working as intended - I've just hit the endpoint. Is your app a server-side app? If so, please ensure you are getting a new access token when switching between reapit-customer header values. It could be this that's caught you out potentially. Can you retest and let us know if the issue is still present?

**Comment by iWader** [comment]
Hi @plittlewood-rpt just confirmed this appointment type is now visible again on the customers account

Our app uses the authorization code grant, so no reapit-customer headers involved, and we've not made any changes from our side

Are you able to detail what was wrong here? I assume a setting, or feature was disabled on the customers account, so would be good to know of the future so we can advise customers on a solution

**Comment by james-radweb** [comment]
The client has reported the issue has occurred again, please look into this as soon as possible

**Comment by plittlewood-rpt** [comment]
Hi @james-radweb - this has been resolved. It appears to be related to #5636 which is currently under investigation
