### ISSUE TITLE
Write Back Question - Filtah - New App Developer 2022

### ISSUE THREAD

**Issue by AppMarketSales** [reapit/foundations#5738]
Good Morning,

This is a question from a new App Developer who has a new property portal in development.

They have asked the question about, in their words, the "re-sync of data to write back to AgencyCloud" is required for them in building their App.

Thanks
David Mann

**Comment by willmcvay** [comment]
@AppMarketSales This is part of the developer terms and conditions, yes. See schedule 3, point 3 https://foundations-documentation.reapit.cloud/developer-terms-and-conditions#schedule-3-developer-obligations

**Comment by willmcvay** [comment]
Closing as assuming this has been answered
