### ISSUE TITLE
Metadata custom API endpoints returning 500 internal server error

### ISSUE THREAD

**Issue by whanno-lsl** [reapit/foundations#5739]
Summary:
When using custom metadata endpoints, after a while ALL of the metadata API calls fail with a 500 internal server error.
This has only started happening the last couple of days, both when running an App within Dev RPS and also via the direct URL using ReapIt Connect.
It happens with our existing Apps as well as the one I am trying to develop so it's not something obvious at my end.
It feels like something to do with the Connect session expiring or something, but strangely non-metadata API calls continue to work as normal.
Once it happens, if I bounce Dev RPS and log back in the same thing happens straight away usually (so I'm struggling to use it at all at the moment).

An example API call Id to hopefully shed some light is:
x-amzn-RequestId: 4d7b5185-d164-46ab-9343-08fb18b5f43d
(this was called from an App running within Dev RPS)

Steps to reproduce:
Log into Dev RPS
Use an App that calls the Metadata API endpoint
After a while (usually an hour or so, but today almost immediately) the custom metadata API calls will fail

Expected Results:
Metadata API calls should continue to work successfully in the same manner as standard entity API calls.

Actual Results
API responds with (random) 500 Internal Server errors

**Specification**
- Replicate problem using info from comments below
- Alter appropriate logic used when copying headers to onward request to other backend services. The Via header (and others) won't be needed so can just be stripped out completely. Note that it might be more appropriate and time efficient just to resolve the bug that is causing the error to be thrown so determine this when replicating the problem

**Comment by plittlewood-rpt** [comment]
Hi @whanno-lsl - thanks for reaching out. I've had a look in the logs and found the request you mention above (thanks for the id, most helpful!). It seems there is an issue somewhere with the "Via" header that you are sending with the request which is causing the service to throw an exception. It will be the new year before we can look at this properly, but the via header is coming through in a format that for some reason the service cannot parse when it is creating onward requests to other backend services.

The Via header from that request came through in the following format. I have obfuscated the URL for security:

`Via: HTTPS/1.1 aaa-aa-00-wcg.aaaaaa.co.uk 0A20CD7E`

I'm not sure why you would suddenly see errors though, I'd expect that to be present (and probably in the same format, too) for all your requests. Are you able to give me the id of a request which was successful? If you can't work out the URL from the obfuscated version above, let me know, but it looks like some kind of gateway device on your corporate network looking at the URL.

**Comment by whanno-lsl** [comment]
Thanks, apologies for the delay during the holiday period.

An example of a successful id that I have just run is:

9b6dccac-b085-428b-9a8a-041c6a34ff1c

I’ve mentioned the “Via” header to our infrastructure team to see if they come back with anything too.

**Comment by plittlewood-rpt** [comment]
Thanks for coming back. I've just checked that request and there was no `Via` header present at all (this could be because it came from a localhost address). We'll look into it from this end too, but if we can find out where that's being added that would be useful.
