### ISSUE TITLE
Webhook gets deactived randomly

### ISSUE THREAD

**Issue by bisoh** [reapit/foundations#5745]
_Apologies if this is not the right place to post this._
Every now and then our webhook gets deactivated. Sometimes over the weekend or extended periods of no-use and sometimes its over night. Cannot replicate or pinpoint why/when it happens. Can someone please have a look at our webhook and let us know why that might happen (happy to provide details as needed)?

**Expected behaviour**
Webhook retains is status unless manually changed by a user

**Comment by plittlewood-rpt** [comment]
Hi @bisoh - webhooks subscribed to only sandbox data are automatically deactivated after a period of 2 weeks (see #3439). This is to cut down on the unnecessary traffic and processing overhead caused by developers leaving Sandbox webhooks turned on perpetually.

**Comment by bisoh** [comment]
Thanks @plittlewood-rpt . I was worried this might be happening on prod too. Thanks
