### ISSUE TITLE
Need the Priority for a Works Order available via the API

### ISSUE THREAD

**Issue by whanno-lsl** [reapit/foundations#5747]
**Is your feature request related to a problem? Please describe.**
The Works Order API doesn't seem to include the Priority field (set to High/Medium/Low in RPS).

**Describe the solution you'd like**
To be able to read/update the Works Order's priority via the API.

**Describe alternatives you've considered**
Can't think of any - we need to access via the Foundations API

**Specification**
- Consider that this field is turned OFF by default for AC customers and how that affects Platform
- Add new `priority` field to works orders API to expose workhead.extra.gwPriority field. A new enum will be needed here:

1 = high
2 = medium
3 = low

- Field should be readable and writeable
- Field is optional and when not set, field should be cleared altogether

**Comment by plittlewood-rpt** [comment]
Hi @whanno-lsl - thanks. We will review this on our next refinement. The priority field is switched off by default as it is seldom used, but we will look at how we can add support via the Platform APIs
