### ISSUE TITLE
Enhance property model to include upper price range for development master records

### ISSUE THREAD

**Issue by jaetooledev** [reapit/foundations#5751]
**Summary**
![image](https://user-images.githubusercontent.com/61322528/148193567-f8b00927-4c97-4cdb-848e-dc9f24d84499.png)
Within reapit, we have a development with an asking price range. This is exposed as max_price I believe within the RDA API. When looking at the Foundations response for the property, I am unable to find the outer price anywhere within the response. Is this something that has been missed? If so, is it a simple addition?

**Detail and or supporting links and screenshots**
`	"selling": {
		"instructed": "2019-11-01",
		"price": 129995.0,
		"qualifier": "askingPrice",
		"status": "underOffer",
		"disposal": "privateTreaty",
		"completed": null,
		"exchanged": null,
		"accountPaid": null,
		"tenure": null,
		"vendorId": "NHO190155",
		"agency": "soleAgent",
		"agencyId": "SA",
		"fee": {
			"type": "percentage",
			"amount": 1.0
		},
		"exchangedCompanyFee": null,
		"recommendedPrice": 0,
		"brochureId": null,
		"exchangedPrice": 0,
		"exchangedOfficeId": "",
		"decoration": []
	},`

**Specification**
- Add `selling.priceTo` to PropertySellingModel. This should expose the prp.maxPrice property ONLY for master records. It should not be exposed for normal properties as the same field is also used for match price ranges so will look confusing.
- Support read only for now as we will need to consider the write side in more detail

**Comment by plittlewood-rpt** [comment]
Hi @jaetooledev - this will need to be added to the properties API. We will discuss in our refinement session tomorrow.
