### ISSUE TITLE
Is there anything which differentiates a commercial property from a standard property?

### ISSUE THREAD

**Issue by jaetooledev** [reapit/foundations#5755]
**Summary**
On the old RDA api there was a seperate endpoint for getting commercial properties and a flag in the property response for is_commercial. On the foundations API, are commercial properties returned within a /properties/ response by default? If so what differentiates a commercial property from a standard property as I cannot find anything which seperates them?

**Detail and or supporting links and screenshots**
MNS Reapit (AUC210310)

**Comment by plittlewood-rpt** [comment]
Hi @jaetooledev - you can use the `departmentId` field in the property model for this purpose. Incidentally, we will shortly be working on enhancing the commercial support in terms of having better support for commercial attributes etc. You can follow ticket #5282 for updates.

**Comment by jaetooledev** [comment]
@plittlewood-rpt just to confirm - so hitting the /properties/ endpoint with a sale status of forSale (for example) would return any properties including commercial properties that hit that criterea?

**Comment by plittlewood-rpt** [comment]
Yes that's right - if you start filtering by property attributes it will default to the General department if you don't also specify a departmentId in your query parameters as we can only filter and return properties for one department at a time when using these filters, but as you are filtering by sales status, you should get properties from both departments back
