### ISSUE TITLE
/applicants times out when called with array of emailAddresses

### ISSUE THREAD

**Issue by designreact** [reapit/foundations#5765]
This was mentioned here: https://github.com/reapit/foundations/issues/5623. 

I suspect it requires the same optimisation as /contacts?

**Comment by designreact** [comment]
Related comments on linked issue:
https://github.com/reapit/foundations/issues/5623#issuecomment-984547443
https://github.com/reapit/foundations/issues/5623#issuecomment-992615741

**Comment by designreact** [comment]
N.B. we tested vendors, landlords and tenancies all appear to work as expected 👍

**Comment by designreact** [comment]
@plittlewood-rpt @HollyJoyPhillips 

Sadly this is a blocker for our Agency Cloud App. 
Given the fix is already active on contacts, landlords, vendors and tenants hopefully it is a fairly simple update?

**Comment by plittlewood-rpt** [comment]
@designreact I have brought this into the current sprint. The reason it wasn't done originally was because your comments were added to a closed ticket but I accept it was an oversight first time round. It should be done by the end of the week.

**Comment by designreact** [comment]
@plittlewood-rpt that's great news - thank you 🙏
