### ISSUE TITLE
Internal Server Error - Client code (HAI)

### ISSUE THREAD

**Issue by rajeshwl** [reapit/foundations#5782]
**Describe the bug**
We have tried to import the data for our one of our mutual client(Hastings International-HAI). But we are receiving the Internal server Error. 
The endpoint we tried are:
```
https://platform.reapit.cloud/departments/
https://platform.reapit.cloud/properties/
```

**Note:** Client is in Rackspace. 

**Expected behaviour**
Expecting the response to be successful. 

**Response received:**
```
{
    "statusCode": 500,
    "dateTime": "2022-01-06T07:38:41.2988907Z",
    "description": "An unexpected error has been encountered when fulfilling this request. This incident has been logged and will be investigated. Please try again."
}
```

**Comment by plittlewood-rpt** [comment]
Hi @rajeshwl - it looks like our infrastructure team might actively be doing some work on this database. I've dropped a note to them to find out if this is the case. I would expect this to be functional in the next 30 minutes or so, but I will wait to hear back from them and confirm back on the ticket

**Comment by plittlewood-rpt** [comment]
Hi @rajeshwl - our infrastructure team have confirmed this should now be resolved. I've successfully been able to query the API for this customer  now
