### ISSUE TITLE
How can devs fully test the API and webhooks?

### ISSUE THREAD

**Issue by Stuart88** [reapit/foundations#5783]
**Summary**

Currently working on an integration using the Reapit API and webhooks, but I can't see how to test it with anything other than the sandbox data. I need a way to test the full back-and-forth flow of data between both sides of the integration.

I see there's a desktop CRM for £300 / month. Is that the only way test everything in full?

Thanks

**Comment by AshDeeming** [comment]
Hi Stuart,
The sandbox database (SBOX) is the same structure as our clients data sets.
Testing can be done against sandbox data, please see more information here;
https://foundations-documentation.reapit.cloud/faqs#how-can-i-test-my-app-or-integration
https://foundations-documentation.reapit.cloud/api/api-documentation#sandbox-mode

Testing the data can be done via the interactive swagger or third party applications such as Postman. 
If you plan to integrate with the AgencyCloud platform or test the end user journey, the Developer Edition of AgenyCloud is available & can be subscribed to for £300 per user, per month.
