### ISSUE TITLE
Add ID column to TENANCY_CONTACTS table

### ISSUE THREAD

**Issue by matt-austin-andrews** [reapit/foundations#5791]
**Background context**
All of the other join tables in the analytics schema have a unique ID, e.g.:

**LANDLORD_CONTACTS**
ID	VARCHAR(32)
LANDLORD_ID	VARCHAR(32)
CONTACT_ID	VARCHAR(32)
IS_PRIMARY	VARCHAR(3)
_CUSTOMER_ID	VARCHAR(16777216)
_LAST_SYNCH_AT	TIMESTAMP_TZ(9)

However, the TENANCY_CONACTS table does not have this unique ID:

**TENANCY_CONACTS**
TENANCY_ID	VARCHAR(32)
CONTACT_ID	VARCHAR(32)
IS_PRIMARY	VARCHAR(3)
_CUSTOMER_ID	VARCHAR(16777216)
_LAST_SYNCH_AT	TIMESTAMP_TZ(9)

Please can this be added as (a) it seems like an unintentional omission and (b) it is the only table in the analytics schema to not have a unique id.

**Specification**
- Add ID field to tenancy contacts table
- Update analytics schema documentation to include the new field. Double check whether or not there are any ERDs with the TENANCY_CONTACTS table in, and if so ensure the new primary key is added

**Comment by plittlewood-rpt** [comment]
Hi @matt-austin-andrews - thanks for bringing this to our attention. I would agree it's an unintentional omission. We'll look at this on our next refinement
