### ISSUE TITLE
Improve multi threading to improve webhooks throughput

### ISSUE THREAD

**Issue by plittlewood-rpt** [reapit/foundations#5792]
**Background context**
A fairly simple adjustment that would improve webhooks throughput without being more costly is to increase the number of background threads being used to process webhooks notifications. This gives us the ability to process more notifications without having to spin up new container instances which can become costly at busy periods

**Specification**
- Validate comments from user below and confirm that the webhooks service is responsible for the delay, rather than another area of the pipeline
- Review best mechanism for running multiple instances of the same background worker task and implement
- Consider storing number of desired background worker threads in configuration so it can be altered (manually or programatically) based on container resource allocation. This gives us the ability to adjust it at will without having to make code changes

This thread may be useful:
https://github.com/dotnet/runtime/issues/38751

**Comment by maxcivino** [comment]
Hi, 
Our system is experiencing a significant slowness of the Webhook notifications on Reapit sandbox.

When a user creates/udpates/cancels an appointment in Reapit AgencyCloud (ver.12.139.2), it takes between 5/10mins for the notification to be send to the WebHook.

This lag is not acceptable for the correct functionalities of our system.

Furthermore, this slowness involves a lot of time to complete our tests for each feature and it has a big impact on our productivity.

I suppose this ticket is related to the issue we are facing, but please let us know as soon as possible if you need more details from us to tackle the problem.

Regards,
Max

**Comment by maxcivino** [comment]
Hi,
here few examples to have an idea:

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/maxci/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/maxci/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/maxci/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-GB style='tab-interval:36.0pt;word-wrap:break-word'>




Event   Id | Entity Id | Event Time | Notification Time | Difference
-- | -- | -- | -- | --
556ea8d2-c031-4700-8c64-5a703a78d9f1 | MKT2200126 | 2022-01-13 11:20:13.0707782Z | 2022-01-13 11:26:36 | 6+ mins
f9f3e7e4-4f04-4365-9cfd-d915837d9a77 | MKT2200126 | 2022-01-13 11:20:13.068577Z | 2022-01-13 11:26:32 | 6+ mins
876be507-47ab-45df-a812-31168843f713 | MKT2200126 | 2022-01-13 11:10:37.3915085Z | 2022-01-13 11:20:04 | 10 mins
59b9466d-2a02-490e-ae9b-3103a7c2623d | MKT2200097 | 2022-01-13 11:40:28.3480479Z | 2022-01-13 11:44:47 | 4+ mins
0f569b7f-240c-449c-9ca3-f76f2121c4f7 | MKT2200119 | 2022-01-13 10:57:26.4443641Z | 2022-01-13 11:06:19 | 9 mins




</body>

</html>
