### ISSUE TITLE
Need the ability to set a default value for the Searchable Dropdown UI component

### ISSUE THREAD

**Issue by whanno-lsl** [reapit/foundations#5814]
**Is your feature request related to a problem? Please describe.**
We use a (React) Searchable Dropdown component to search through a list of negotiators, and have a requirement to default to the negotiator currently logged in when the view is rendered

**Describe the solution you'd like**
Be able to set a default value so that, for example, the required negotiator is displayed in the Searchable Component without having to search for them first

**Describe alternatives you've considered**
We can't use a standard "Select" component due to the large number of "options" required

**Comment by willmcvay** [comment]
@whanno-lsl We can look at this - have you considered the MultiSelect component though? https://elements.reapit.cloud/?path=/docs/multiselect--react-example This supports defaultValues already out the box

**Comment by whanno-lsl** [comment]
Thanks, unfortunately we will be searching hundreds of options (negotiators) so really need something dynamic.

**Comment by willmcvay** [comment]
Cool, we've accepted the feature so in our near term backlog now. FYI I did something similar with the MultiSelect using an input for search, debouncing the query see https://github.com/reapit/foundations/blob/master/packages/marketplace-management/src/components/ui/offices/office-group-edit-form.tsx#L185 

Might be of use, but failing that just track this ticket and will be included in a version soon.

**Comment by bashleigh** [comment]
Hey @whanno-lsl 👋  I've just released @reapit/elements `v3.7.10` which I added a default value option to the searchable dropdown component. Here's a link to the docs for you https://elements.reapit.cloud/?path=/docs/searchabledropdown--default-value

Let me know if this is what you were after and or whether you have any feedback, suggestions or issues!

**Comment by whanno-lsl** [comment]
Seems spot on, cheers 😊
