### ISSUE TITLE
Build suite of automated tests for AB connector

### ISSUE THREAD

**Issue by plittlewood-rpt** [reapit/foundations#5818]
**Background context**
As the AB connector codebase is built and moves along, we should build and maintain a suite of integration tests in Postman that can be scheduled to run at suitable intervals to test and confirm the behaviour of the connector is working as intended. This should target checks in both AB and Platform sides as data synchronises between the two systems and also check that latency is acceptable

**Specification**

**Comment by HollyJoyPhillips** [comment]
PL, HP & RW: Reviewed
