### ISSUE TITLE
Latest Reapit Elements doesn't allow '<' characters in input field

### ISSUE THREAD

**Issue by nroper** [reapit/foundations#5834]
**Summary**
Issue with '<' characters after installing the latest Elements libraries

**Detail and or supporting links and screenshots**

We have a page in our Foundations app that allows a user to enter ID document details.  For passport documents this includes an entry for the full 44 character machine readable passport reference number, which includes '<' characters.
This was working fine prior to installing the latest Elements libraries, but now gives an error 'Special characters are not permitted' - see screenshot:

![image_2022_01_13T19_10_17_190Z](https://user-images.githubusercontent.com/479971/149495685-39651950-e6dc-4e35-a02b-62f130bc1eea.png)

We can't see any configurable option to address this and would be grateful if someone could advise how to resolve the issue.

For reference, our installed dependencies are as follows:

```
  "dependencies": {
    "@reapit/connect-session": "^2.0.7",
    "@reapit/elements": "^2.3.0",
    "@reapit/foundations-ts-definitions": "^1.2.0",
    "@testing-library/react": "^10.0.6",
    "@types/enzyme": "^3.10.8",
    "@types/enzyme-adapter-react-16": "^1.0.6",
    "@types/jest": "^24.0.25",
    "@types/node": "^10.17.13",
    "@types/react": "^16.9.55",
    "@types/react-dom": "^16.9.9",
    "@types/react-router-dom": "^5.1.6",
    "axios": "^0.21.4",
    "concurrently": "^5.3.0",
    "cross-env": "^7.0.2",
    "customize-cra": "^1.0.0",
    "dayjs": "^1.9.4",
    "enzyme": "^3.10.0",
    "enzyme-adapter-react-16": "^1.15.5",
    "enzyme-to-json": "^3.6.2",
    "formik": "^2.2.6",
    "jest-config": "^25.1.0",
    "linaria": "^1.4.0",
    "react": "^17.0.2",
    "react-app-rewired": "^2.1.6",
    "react-dom": "^17.0.2",
    "react-router": "^5.2.0",
    "react-router-dom": "^5.2.0",
    "react-scripts": "^3.4.0",
    "serve": "^11.3.2",
    "typescript": "^3.9.7"
  },
```

**Comment by willmcvay** [comment]
Hi @nroper that is intended behaviour. We validate against entering special characters since they are not supported by our API and because our independent Pen test advised it as a mitigation against XSS attacks.

If this is something you need, just use a native input and apply the elements CSS classes. If you need Formik, you can follow the basic outline of this component https://github.com/reapit/foundations/blob/master/packages/elements-legacy/src/components/Input/index.tsx#L39,  ensuring you import Formik from elements rather than standalone. Hope this helps.

**Comment by nroper** [comment]
Hi @willmcvay Thanks for the feedbackk and completely understand the reasoning behind that.   I've worked on other applications where simailar rules applied, but on those there was an option to provide a whitelisted pattern that would be allowed through.  Is that something that could be considered in a feature request do you think?

In the meantime we'll look into inplementing as you suggest.

**Comment by willmcvay** [comment]
@nroper I'll keep in mind a whitelist for Elements v3, this feature is currently only specific to v2 and yet to implement on the v3 package. Glad the workaround is fine for now, will close this one off.
