### ISSUE TITLE
Reapit Feed not Showing Properties belonging to Agent

### ISSUE THREAD

**Issue by mattpbs** [reapit/foundations#5835]
Ref: [https://github.com/reapit/foundations/issues/5735](url)

Hi @plittlewood-rpt

We've been through now and the app is now finally approved and we can see that it is installed by DB Roberts so that bit looks like it's all working.

We have gotten the client to reauthorize the account using Authentication code flow, but the data that is showing still appears to be sandbox data. I understand from the documentation and from what you have said that the reapit-customer header only applies to Client credentials flow so wouldn't work in our case.

Do you have any other ideas?

Thanks

Matt

**Comment by plittlewood-rpt** [comment]
Hi @AshDeeming would you be able to provide initial assistance on this? We may need to review what the app is doing

**Comment by AshDeeming** [comment]
Hi @mattpbs, please can you confirm the app name?

**Comment by mattpbs** [comment]
Hi @AshDeeming 

I have been in contact with Reapit and this has now been solved. I believe there was a setting that had to be turned on by yourselves.
