### ISSUE TITLE
Unable to create a new Webhook

### ISSUE THREAD

**Issue by azura-mg** [reapit/foundations#5836]
**Describe the bug**
The Submit button on the Add Webhook screen doesn't function and so you are unable to create a new Webhook.

**To Reproduce**
Steps to reproduce the behaviour eg:
1. Go to 'https://developers.reapit.cloud/webhooks/new'
2. Fill in the form (the options selected don't seem to affect things)
3. Try to click Submit

**Expected behaviour**
The webhook should be created on the system.

**Screenshots**
![image](https://user-images.githubusercontent.com/86250891/149506560-c53c3cbd-df51-4dc9-b78e-3443447f219f.png)

**Device (please complete the following information for web issues):**
 - Device: PC
 - OS: Windows
 - Browser: Chrome and Firefox
 - Version: Chrome 97.0.4692.71. Firefox 96.0 (64 bit)

**Additional context**
Editing an existing Webhook works, so I could modify one of my testing webhooks. I just can't create a new one.

**Comment by plittlewood-rpt** [comment]
Hi @azura-mg please advise if this issue is still present

**Comment by plittlewood-rpt** [comment]
Closing due to lack of response - no obvious problems with Webhooks systems at present
