### ISSUE TITLE
Journal Webhook

### ISSUE THREAD

**Issue by s1mtm** [reapit/foundations#5839]
**Are there any plans to implement a Journal Entries Webhook?**
This would be really to know when a new journal entry has been created.
Thanks

**Comment by plittlewood-rpt** [comment]
Hi @s1mtm - there are no plans to do this at the moment. Do you have any more information about how you would use this information? The journal is a fast moving part of the database so there is potential to generate a lot of unwanted noise so it's unlikely something we would look to implement without a compelling reason to do so, so I'd be interested in any more detail you can provide.

**Comment by HollyJoyPhillips** [comment]
Closing as no reply. If you feel this is still a requirement, please open a new ticket with more information and a use case.
