### ISSUE TITLE
The "api-version" header requirement is missing from the Swagger documentation

### ISSUE THREAD

**Issue by jpswade** [reapit/foundations#585]
Looking at the Swagger Documentation and API explorer, there's no mention of the 'api-version' header.

- https://marketplace.reapit.cloud/developer/swagger

The versioning is mentioned here:

- https://foundations-documentation.reapit.cloud/api/api-documentation#versioning

This suggests it is required.

If it's not supplied, the API will give an error 400 saying:

> HTTP resource requires that requests are issued with a 'api-version' header containing a UTC version date. Format: yyyy-MM-dd'

If you do not supply the header, it is required.

I can see that the API Explorer simply sends the header: "api-version: latest"

Can you update the swagger documentation to reflect the requirement?

**Comment by cbryanreapit** [comment]
Hi @jpswade 

The interactive API explorer is intended to give a quick start experience in a sandbox environment. As such, we took the decision to automatically insert the `api-version` header to allow users to quickly get to grips with our endpoints. 

Will give thought to how we can make this behavior clearer.

**Comment by jpswade** [comment]
To be clear, the `api-version` is completely absent from the API specification documentation, yet is a required field by your API.

Your Swagger documentation should match your API specification exactly.
