### ISSUE TITLE
Property Price - GeoDiary 

### ISSUE THREAD

**Issue by JoCauser** [reapit/foundations#5861]
Please could you add in the Property Price field in the Geodiary

**Comment by plittlewood-rpt** [comment]
@JoCauser  is there any more detail around this request (customer requirements etc)? Thanks

**Comment by JoCauser** [comment]
Hi Pete, this is the reason they require the price on the property via GeoDiary:
Hi Jo,

When our viewers are showing prospective buyers/tenants round a house, they have no idea how much the property is on the market for. IT means we have to print the paper diaries for this info – which defeats the object of us using geodiary

Hope that helps

Hass

**Comment by JoCauser** [comment]
Thank you - it's likely buyers are viewing multiple properties with varying prices, but the Julian Wadden viewing staff do not log into desk top AC and only work from GeoDiary so it's their only view of this info should they be asked the question.
