### ISSUE TITLE
"Service charge", "Ground rent" and "Council Tax"

### ISSUE THREAD

**Issue by sanjayisg** [reapit/foundations#5867]
Hi I am using reapit API for my website but I am sure not which key return "Service charge", "Ground rent" and "Council Tax", please help me to find out from bellow: 

{
    "id": "RPT211098",
    "created": "2021-09-23T13:39:16Z",
    "modified": "2021-09-24T10:07:23Z",
    "marketingMode": "selling",
    "currency": "GBP",
    "alternateId": "000114400007",
    "address": {
        "buildingName": "",
        "buildingNumber": "",
        "line1": "9 Wellum Street",
        "line2": "Lighthorne Heath",
        "line3": "",
        "line4": "",
        "postcode": "CV33 9FB",
        "countryId": "",
        "geolocation": {
            "latitude": 52.201331,
            "longitude": -1.486947
        }
    },
    "areaId": "",
    "strapline": "short",
    "description": "<p>Kings Grove, an elegant collection of new homes in the sought-after Warwickshire village of Lighthorne Heath. This beautiful development encompassing several areas of open green space is surrounded by the scenic Warwickshire countryside with excellent access to transport connections. Royal Leamington Spa, Coventry, Banbury and Birmingham are all close at hand, allowing you to enjoy the very best of both town and country living. Offering excellent transport connections throughout the area with convenient access to the motorway network. The M40 is less than two miles from the development and provides routes to Oxford, Birmingham, Banbury and London among other popular destinations. Coventry can also be reached in just under 30 minutes via the A46. Around a 15 minute drive from Kings Grove is Leamington Spa train station which serves a number of major destinations including Birmingham, London and Manchester. For those requiring international travel, Birmingham airport is just over 30 minutes away by car. The Royal Priors Shopping Centre is Leamington’s only indoor retail centre and is located under 20-minutes away by car. With spacious indoor boulevards and a mix of designer and high street brands, this impressive mall promises a satisfying retail experience, complete with quaint cafés and a family-friendly restaurant. Stunning architecture and award-winning parks provide a sophisticated backdrop to this Regency town. Victoria Park is an attractive area of green space just a 15 minute drive from Kings Grove, which provides an ideal site for walking, cycling, sport or picnicking. This brand new home benefits from a lounge/diner at the back of the house with a separate kitchen and a ground floor cloakroom. On the first floor are two double bedrooms and a bathroom whilst externally is parking and a garden.</p>",
    "longDescription": "",
    "summary": "[\"Lounge\\/diner\",\"Separate kitchen\",\"Parking\",\"Ground floor WC\",\"Integrated appliances\",\"Flooring throughout\",\"Garden\"]",
    "departmentId": "G",
    "negotiatorId": "PRH",
    "bedrooms": 2,
    "receptions": 0,
    "bathrooms": 1,
    "councilTax": null,
    "internetAdvertising": true,
    "isExternal": false,
    "viewingArrangements": null,
    "videoUrl": null,
    "videoCaption": null,
    "video2Url": null,
    "video2Caption": null,
    "notes": "",
    "boardStatus": null,
    "boardNotes": null,
    "boardUpdated": null,
    "archivedOn": null,
    "fromArchive": false,
    "externalArea": null,
    "internalArea": null,
    "epc": {
        "exempt": false,
        "eer": 0,
        "eerPotential": 0,
        "eir": 0,
        "eirPotential": 0
    },
    "selling": {
        "instructed": null,
        "price": 105750,
        "priceTo": null,
        "qualifier": "askingPrice",
        "status": "forSale",
        "disposal": "privateTreaty",
        "completed": null,
        "exchanged": null,
        "accountPaid": null,
        "tenure": null,
        "vendorId": "RPT211098",
        "agency": "soleAgent",
        "agencyId": "SA",
        "fee": null,
        "exchangedCompanyFee": null,
        "recommendedPrice": null,
        "brochureId": null,
        "exchangedPrice": 0,
        "exchangedOfficeId": "",
        "decoration": []
    },
    "letting": null,
    "type": [
        "house"
    ],
    "style": [
        "endTerrace"
    ],
    "situation": [
        "garden"
    ],
    "parking": [],
    "age": [
        "new"
    ],
    "locality": [],
    "specialFeatures": [],
    "rooms": [],
    "officeIds": [
        "SDO"
    ],
    "lostInstructionDate": null,
    "lostInstructionNote": null,
    "extrasField": {},
    "_eTag": "\"913C812ECFD4664A5001055DAFC1ACF9\"",
    "_links": {
        "self": {
            "href": "/properties/RPT211098"
        },
        "images": {
            "href": "/propertyImages/?propertyId=RPT211098"
        },
        "documents": {
            "href": "/documents/?associatedType=property&associatedId=RPT211098"
        },
        "offers": {
            "href": "/offers/?propertyId=RPT211098"
        },
        "appointments": {
            "href": "/appointments/?propertyId=RPT211098"
        },
        "negotiator": {
            "href": "/negotiators/PRH"
        },
        "offices": {
            "href": "/offices/?id=SDO"
        },
        "department": {
            "href": "/departments/G"
        },
        "vendor": {
            "href": "/vendors/RPT211098"
        },
        "sellingAgency": {
            "href": "/configuration/agencyTypes/SA"
        }
    },
    "_embedded": null,
    "metadata": {}
}

Thanks,

Sanjay Gupta

**Comment by plittlewood-rpt** [comment]
Hi @sanjayisg - there is a property in this model called councilTax which surfaces the property Council Tax (when set by the agent). Service Charge and Ground Rent are not currently covered so we will review this on our next refinement session (Thursday)

**Comment by plittlewood-rpt** [comment]
Hi @sanjayisg - we do have the capability to expose this additional information as part of the semi structured data handling. Can you confirm which customer(s) you are acting on behalf of, and whether or not you will need to write to these fields? Longer term these should become structured fields in the API so having this information will help determine the best approach

**Comment by HollyJoyPhillips** [comment]
@sanjayisg We are closing this ticket as part of our weekly refinement as no response. If this is still required, please open a semi structured ticket request here https://github.com/reapit/foundations/issues/new?assignees=&labels=back-end%2C+needs-triage&template=extras_field.md&title=
