### ISSUE TITLE
New Integration

### ISSUE THREAD

**Issue by barrydixon** [reapit/foundations#5873]
I am setting up a new Integration with Reapit. I'm connecting to and retrieving data from the Sandbox but have some anomalies:

1. None of the images retrieved on https://platform.reapit.cloud/propertyImages have propertyIds that match the property data retrieved from https://platform.reapit.cloud/properties so I am unable to create a valid sample of properties.
2. The application is to be used for a letting agency but there is only one property in the data that is letting and that has hardly any data including lat/lng values, so I have no realistic data to work with.
3. How do I distinguish between property images and floorplan images?
4. I can't find anything in the sample data for Virtual Tours or Videos. How does that come through?

**Comment by plittlewood-rpt** [comment]
Hi @barrydixon 

Thanks for reaching out. To answer your questions

1. I cannot see what you mean. I've looked at a number of entities in the `GET /propertyImages` response and the matching property is available at `GET /properties/{id}` - please can you provide some examples?
2. There is a large number of lettings properties in the Sandbox data. Can you send me an example request (curl would help) that is only returning you one property so I can try to replicate?
3. Please refer to the PropertyImageModel documentation at https://developers.reapit.cloud/swagger which outlines the values for the `type` field
4. Please refer to the PropertyModel documentation at https://developers.reapit.cloud/swagger which outlines the values for `videoUrl`, `videoCaption`, `video2Url`, `video2Caption`

Thanks
Pete

**Comment by barrydixon** [comment]
Hi Pete,

Thanks for the quick response. I am using a PHP script on a web server using the PHP Curl function.

1. What I am doing is getting a list of all images using /propertyImages and creating an array of them. Then I’m getting a list of all properties using /properties matching up the images to the properties by the id. This, to me, is the logical way of doing it do that I still get properties that are available but don’t have images. If I do it the other way round and get the list of images first then get the details of each property I would not retrieve any property that doesn’t have images. I have also tried getting the list of properties and then cycling through them getting the images of each but that is not retrieving any images for any of the properties. Here is an example:

https://platform.reapit.cloud/properties/?PageNumber=1&pageSize=100&marketingMode=lettinghttps://platform.reapit.cloud/propertyImages/?propertyId=RPT220017 <https://platform.reapit.cloud/properties/?PageNumber=1&pageSize=100&marketingMode=lettinghttps://platform.reapit.cloud/propertyImages/?propertyId=RPT220017> returns 

{
  "_embedded": [],
  "pageNumber": 1,
  "pageSize": 25,
  "pageCount": 0,
  "totalPageCount": 0,
  "totalCount": 0,
  "_links": {
    "self": {
      "href": "/propertyImages/?PageNumber=1&PageSize=25&propertyId=RPT220017"
    },
    "first": {
      "href": "/propertyImages/?PageNumber=1&PageSize=25&propertyId=RPT220017"
    }
  }
}


2. I hadn’t realised it defaulted to only returning 25 properties if no pageSize is given so I’ve corrected that now. I am also filtering on letting rather than retrieving all properties and am getting a lot more through.

3. OK, thanks. I didn’t see that. 

4. Thanks, got that now.


Regards,

Barry

**Comment by plittlewood-rpt** [comment]
Hi @barrydixon thanks for your response. On point 1, I'm not sure I follow. The property id you've used as an example doesn't have any images so I'd expect the response you're getting. I've just added an image to it so you should at least get a response back. I'd encourage you to explore using the `embed` functionality that allows you to make a request to `GET /properties` and have the property images embedded in the response. Note that the Platform will still call the propertyImages API on your behalf in the background so there's no change to how you get billed for the requests in production, it is simply a helper function to reduce the number of round trips you need to make to the server from your app

Your request would then look something like

`https://platform.reapit.cloud/properties/?PageNumber=1&pageSize=100&marketingMode=letting&embed=propertyImages`

More info about the embedding mechanism can be [found here](https://foundations-documentation.reapit.cloud/api/api-documentation#embedding-data)

**Comment by barrydixon** [comment]
Hi,

Thanks, that all makes sense now. I’ve set it up with embedding the images and it seems to be working fine.

Thanks for your help.

Regards,

Barry

**Comment by plittlewood-rpt** [comment]
Great. Thanks for confirming
