### ISSUE TITLE
Verification email for Reapit Foundations Portal have not been received 

### ISSUE THREAD

**Issue by RussellSimpson2022** [reapit/foundations#5882]
I have tried to create an account under the email address of vrinkeviciute@russellsimpson.co.uk on the https://developers.reapit.cloud/login. 

The system told me I have successfully created the account, I just need to verify it, but I have never received the verification link. See the screenshot below. 

How should I proceed please, as I need to create the account for the organization and give access to our web developers for the website scoping project? 

<img width="932" alt="Developer portal" src="https://user-images.githubusercontent.com/97975998/149983923-764a6bf3-7128-4345-b7ac-e7b3dc494d57.PNG">

Many thanks for your help,
V.

**Comment by plittlewood-rpt** [comment]
hi @RussellSimpson2022 thanks for getting in touch. I've had a look and it looks like your account has been active for some time, so presumably you're logging into AgencyCloud with it? You should be able to log into the Developer portal now. It looks like there might be an issue with the wrong feedback message going out. As you've already got a Reapit Connect account you won't actually get an email but you will have been signed up as a Developer under the same account. If you can try log in to the Developer Portal and let me know if you have any issues. I'll speak to our front-end team about the message being displayed to end users that are also customers and already have a Reapit Connect account. Thanks

**Comment by RussellSimpson2022** [comment]
Ah, amazing, Peter, yes, it's the same log ons as Reapit itself. :)

All worked now, thanks for your help.

V.
