### ISSUE TITLE
how to get property sales on which the status is past valuation? 

### ISSUE THREAD

**Issue by buonzz** [reapit/foundations#5883]
**Summary**
Hi,

I've been using `vendors.created` webhook topic  to retrieve the contact of the person who is selling the property.
Problem is our business use-case requires that valuation clients shouldn’t be contacted, and we should be only recording webhook when a property sale is have agreed (under offer) .
would you be able to advise how to do this?

Thanks

**Comment by plittlewood-rpt** [comment]
Hi @buonzz - vendors.created will be fired whenever a new sales property is registered which by the sounds of it doesn't fit your user case. If you are only interested in properties that go under offer, you can subscribe to the properties.selling.underOffer webhook topic instead. You'll be notified when the property goes to under offer status at which point you could hit the `GET /vendors/{id}` endpoint (the vendor id will always match the property id). If you need to receive further updates about changes to the vendor after the status of their property has changed to Under Offer, you can then listen to vendors.modified webhook events and look out for vendor ids that you've already seen move to the under offer state,and ignore anything else. I hope this helps

**Comment by buonzz** [comment]
Hi @plittlewood-rpt 

thanks so much for info.
We've  just talked to our client and they decided that we are gonna use `properties.selling.exchanged` instead. I've just enabled this topic in our app now, so we could start receiving these topics. 
I would like to start developing the backend codes that receives the `properties.selling.exchanged` payload in our end, but i dont have an example data to work with. Do you happen to have any sample payload I could work with to test this feature?

thanks

**Comment by plittlewood-rpt** [comment]
Hi @buonzz - the payload is the same you'll get with properties.modified, it's just a more granular topic so you only get information through as a property is exchanged. If you want to test this out end to end, register a webhook for Sandbox, then change a property status from Under Offer to Exchanged (or similar, you just need the new status to be Exchanged). That will trigger the webhook to go out with this topic identifier.  Hope this helps

**Comment by buonzz** [comment]
thank you! feel free to close this ticket
