### ISSUE TITLE
Configuration Enabled

### ISSUE THREAD

**Issue by vikiecseri** [reapit/foundations#5894]
**Is your feature request related to a problem? Please describe.**
I have raised a ticket regarding this with ticket number: RSD-162320. I am a product manager at Fixflo and there are some features that are not available on our Reapit system. We don't have configuration enabled and for this reason I cannot add the 'Property Manager' field under Key Contact in Relationships or have the 'Reserved funds' enabled. 

**Describe the solution you'd like**
Can you please change the security settings to allow this function to be enabled? The relevant account email address is thomas.desmoutier@fixflo.com

**Describe alternatives you've considered**
No alternatives, as we need access in order to continue testing and improving the integration.

**Additional context**
![image (5)](https://user-images.githubusercontent.com/97969621/150151168-0f7ed5b7-0e5d-4409-b391-0e30d8467e90.png)

**Comment by vikiecseri** [comment]
I think there is a misunderstanding - we would like to have 'Configurations' enabled. As you can see from the screenshot attached, we can add property manager because it's not available for us. Can you escalate this pls? 

![image (7)](https://user-images.githubusercontent.com/97969621/150387811-94cc8264-6eba-450b-b7d3-cc86e24aafd2.png)

![image (6)](https://user-images.githubusercontent.com/97969621/150387949-9d131b6d-ad40-42b1-9e22-e0b2b75817a8.png)

**Comment by plittlewood-rpt** [comment]
HI @vikiecseri - I am in the process of splitting this ticket into two. Unfortunately System Configuration settings will not be made available in the Developer Edition of Agency Cloud. I will link both new tickets to this item, and once the Platform APIs support the features you mention, we will be able to enabled the configuration settings in Developer Edition.

**Comment by plittlewood-rpt** [comment]
To re-review once the two linked tickets have been handled. There is no point enabling this functionality in Developer Edition until these features are supported in Platform APIs

**Comment by vikiecseri** [comment]
Thank you for letting me know - I understand that this is something that is not available in the Developer Edition, we would like to be set up with the same Edition as clients use for testing purpose as otherwise we have no other way of working on the integration. The product / QA team will need to have access in order to resolve issues that client face and without being able to test it ourselves this will be problematic.

**Comment by plittlewood-rpt** [comment]
Hi @vikiecseri - the Developer Edition is as close an environment to our customers as possible. As you'll appreciate there are a number of configurable features in AgencyCloud so it is impossible to turn them all on in Developer Edition.
