### ISSUE TITLE
Noob REST API authentication question

### ISSUE THREAD

**Issue by soilleir** [reapit/foundations#5898]
We aren't developers (we are Reapit Clients and "citizen developers" lol) and we are trying to use the API in conjunction with Power Automate to pull some data into our automation flows.  We are relatively competent in using APIs with Power Automate but in all other previous platform integrations the bearer token is set up in the 3rd party platform and doesn't expire. Our Reapit CSM advised us to post our query here.

We are struggling to request the authentication token on the Sandbox.  Please help as we are on a very tight deadline on an AML project and want to see if we can upload the output from our AML platform to the client ID Checks  section of RPS. 

Here is our  request which results in a 405 Status code. 
{
    "uri": "https://connect.reapit.cloud/token",
    "method": "POST",
    "headers": {
        "Content-Type: ": "application/x-www-form-urlencoded",
        "Authorization": "*sanitized*"
    },
    "body": "client_id=3tmatadlsfvmkjphqncdb0onpp&grant_type=client_credentials"
}

the Authorization in the header is Basic **client_id**:**secret** from our App registration

**Comment by plittlewood-rpt** [comment]
Hi @soilleir - thanks for reaching out. I've just been able to hit that endpoint using your app id and secret without any issues. Is the request definitely being sent as POST request? You'll get a 405 Method Not Allowed if it isn't going as a POST

**Comment by soilleir** [comment]
Hi @plittlewood-rpt  it's Graham at Rettie hope you are well.
Defo sent as POST and I am encoding the secret too which i forgot to mention above.  are you able to send me your request code so I can take a look at it and see where i am going wrong?

**Comment by soilleir** [comment]
![image](https://user-images.githubusercontent.com/95375239/150191594-ddcbff72-476b-438d-a19a-15fb346ec5b0.png)

**Comment by soilleir** [comment]
![image](https://user-images.githubusercontent.com/95375239/150191690-4267e9ce-932f-4fa6-a6ec-4e6d1a9269ae.png)

**Comment by plittlewood-rpt** [comment]
Thanks for the info Graham. All good here thanks hope you are too. This can happen when the base64(clientId:secret) isn't coming out right. Double check you've got your varClientId and varSecret set correctly and that there's no trailing spaces etc as that will give you the wrong value when you base64 it. If still no dice let me know and I'll get my script over to you

**Comment by soilleir** [comment]
Unfortunately no trailing or leading spaces in the secret or client id or the concat step.  Also when i decode the base64 it looks right too.

**Comment by soilleir** [comment]
Not really used github before. I take it this "ticket" is public so cant really post my encoded secret here?

**Comment by plittlewood-rpt** [comment]
Correct - I've sent you an email

**Comment by soilleir** [comment]
Thanks i've replied.  Not sure if you can make sense of it.  I need to go down and spend an hour with the kids before bed but I'll be back on later.

**Comment by plittlewood-rpt** [comment]
I think I've spotted it. You've got a colon after your Content-Type header key in the screenshot above. Just been able to replicate the problem if I do that in Postman

**Comment by soilleir** [comment]
Well thats 2 hours i wont get back!  Thanks so much Pete.
