### ISSUE TITLE
Can't access sandbox data on the RPS desktop client

### ISSUE THREAD

**Issue by soilleir** [reapit/foundations#5901]
We've registered on the developer portal and downloaded the developer instance of the desktop app.  We are also a Reapit client.  When we log into the developer instance it doesn't show us the sandbox data but our own data.  We have toggled the Client Data checkbox in our profile but it makes no difference it always shows our data in the desktop client.    Please can you investigate.  Our CSM advised us to post the issue here.

**Comment by plittlewood-rpt** [comment]
@AshDeeming would you be able to provide initial guidance on this ticket please?

**Comment by AshDeeming** [comment]
Hi @soilleir, please can you confirm that you have subscribed to the Developer Edition via the Desktop page, for the user attempting to log in? 
https://developers.reapit.cloud/desktop

**Comment by soilleir** [comment]
hi @AshDeeming   yes thats right I did subscribe in the portal and download and install the developer edition.

**Comment by AshDeeming** [comment]
Hi @soilleir, has the toggle been selected to the correct option before logging into AgencyCloud, as it may take a moment to take affect?

**Comment by soilleir** [comment]
Yes.  Tried this a few times over different days.

I've decided to register a separate user account which isn't a user on our
RPS and install the developer instance on a fresh VM to see if it works
that way as unfortunately project timelines are very tight for us.  I'll
let you know how it goes

**Comment by soilleir** [comment]
Ok so have a new user account setup on the dev portal and linked to our team.  Have installed Dev edition on a VM and tried to login as the new user account on the VM and now get this message.

![image](https://user-images.githubusercontent.com/95375239/150782683-10ea9e13-60f8-4ce7-a0a7-c2ef21093e9f.png)

but we have already subscribed and got this message when i subscribed the new account to the dev edition on the dev portal...

![image](https://user-images.githubusercontent.com/95375239/150782833-fefda4f6-7d8f-4693-9c4b-16d23e35bc3a.png)

Time is really getting short now for our project delivery so would really appreciate it if you could fast track this.

**Comment by soilleir** [comment]
Note I also get this on my own account when logging in on the VM.  When i use the dev edition on my own machine it logs in but displays our company data

**Comment by AshDeeming** [comment]
Hi @soilleir - One of our engineers will reach out via email, please could you confirm the best email for contact?

**Comment by soilleir** [comment]
graham.nicholson@rettie.co.uk

**Comment by HollyJoyPhillips** [comment]
@soilleir Just to let you know I have emailed you directly.

**Comment by soilleir** [comment]
Hi Holly

I responded to your email last night

**Comment by HollyJoyPhillips** [comment]
@soilleir This has now been resolved for you. We have identified an issue which we have logged here https://github.com/reapit/foundations/issues/5974
