### ISSUE TITLE
BER Fields required to our client - Douglas Newman Good (DNG)

### ISSUE THREAD

**Issue by rajeshwl** [reapit/foundations#5902]
Request:
Our client required BER Fields to be display in the website. Can you please enable the extras Field for the BER fields for this client. 
![bercapture (1)](https://user-images.githubusercontent.com/14073702/150289390-8642a92d-357f-4104-b133-3d57e36c2de5.jpg)

**Specification**
- Add BER fields to config for this customer

**Comment by plittlewood-rpt** [comment]
Hi @rajeshwl 

Please see below the `extrasField` query string parameter values you can now include with your request to retrieve the BER information for Douglas Newman Good:

BER Exempt -> pBERExempt
BER Rating -> pBERRating
BER Number -> pBERNumber
Energy Performance Indicator -> pEPI

As an example, to return all the above fields (where present), you would append the following to your GET request URI:
`?extrasField=pBERRating&extrasField=pBERNumber&extrasField=pEPI&extrasField=pBERExempt`

Any problems please let me know.

Thanks
