### ISSUE TITLE
{"error":"invalid_client"} - Error issue

### ISSUE THREAD

**Issue by StickManMobile** [reapit/foundations#5906]
Good morning I am getting an invalid client error each time I try to use the https://connect.reapit.cloud/token end point with the sandbox credentials I have had generated. Can you please help me as to why this might be happening?

**Comment by plittlewood-rpt** [comment]
Hi @StickManMobile - can you provide some more detail on this please? What does your request look like? Please don't post your app secret here, but provide your app id so I can replicate it at this end. If possible, please share whatever script you are using to hit the token endpoint. Thanks

**Comment by StickManMobile** [comment]
Good morning I have structured it as a cUrl request below

curl -X POST 'https://connect.reapit.cloud/token'  -H 'Content-Type: application/x-www-form-urlencoded' -H 'Authorization: Basic XXXX' -F "client_id=1bg4vkgn84en1idcherfa355fq&grant_type=client_credentials"

**Comment by plittlewood-rpt** [comment]
I think the -F parameter causes curl to use a different content type header (from https://stackoverflow.com/questions/10859374/curl-f-what-does-it-mean-php). The following curl works for me, assuming your auth header is correct:

```
curl --location --request POST 'https://connect.reapit.cloud/token' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--header 'Authorization: Basic ********' \
--data-urlencode 'grant_type=client_credentials' \
--data-urlencode 'client_id=1bg4vkgn84en1idcherfa355fq'
```

**Comment by StickManMobile** [comment]
That seem to have fixed it thanks @plittlewood-rpt
