### ISSUE TITLE
Unable to delete & recreate analytics schema share

### ISSUE THREAD

**Issue by matt-austin-andrews** [reapit/foundations#5907]
**Describe the bug**
I am unable to delete the analytics schema share and recreate it (to get access to newest version) on the DWH app page:
https://data-warehouse-app.prod.paas.reapit.cloud/data

**To Reproduce**
Steps to reproduce the behaviour eg:
1. Go to https://data-warehouse-app.prod.paas.reapit.cloud/data
2. Click on 'Delete Share' for the 'Analytics Schema' row
3. See error 'SOMETHING WENT WRONG DELETING THIS SHARE'

**Expected behaviour**
The share would be deleted, then a new share could be created (to sync the latest version of the analytics schema)

**Device (please complete the following information for web issues):**
 - Device: PC
 - OS: Win 10
 - Browser: have tried Edge and Chrome

**Additional context**
Please treat high priority because the analytics schema share we do have now seems to be bugged, so I am missing access to views that are causing report refreshes to fall over e.g.,:

`ODBC: ERROR [42S02] SQL compilation error: Object 'REAPIT.ANALYTICS_ANE.CONTACTS' does not exist or not authorized.`

**Specification**
- Check logs to understand what happened when user attempted to delete the share originally. It could be something as simple as a timeout that occureed. 
- This is lower priority now because the data marketplace app now has a refresh button so the need to delete/re-share is no longer required

**Comment by matt-austin-andrews** [comment]
![image](https://user-images.githubusercontent.com/88837586/150317610-0cd0b384-02f5-4437-8809-4ac30028a733.png)

**Comment by plittlewood-rpt** [comment]
hi @matt-austin-andrews - I've just refreshed the share for you, can you let me know if you have access again please? I'm wondering if the delete share operation only partially completed. If the refresh has sorted it out let me know and I can adjust the priority on this ticket.

**Comment by matt-austin-andrews** [comment]
Hi @plittlewood-rpt - thank you so much I can now see the analytics schema views again, including the new `ID` in the TENANCY_CONTACTS table. 

I notice that there is now a REAPIT_RAW.AURORAPROD01_RPS_XXX schema which has the operational schema tables (rather than the views shown in the REAPIT.CUSTOMERS_XXX schema. Would you advise we query the REAPIT_RAW tables or the traditional views?
