### ISSUE TITLE
`Type` Field data missing - Client (Robinson Jackson RBJ)

### ISSUE THREAD

**Issue by rajeshwl** [reapit/foundations#5925]
This is regarding the issue we raised before for the Type field data missing.
https://github.com/reapit/foundations/issues/5731

Can you map the (Flat - Purpose Built and Flat - Conversion) build type to the flatApartment for this client so we can make it use in the website.

**Specification**
- Add new value to `flatApartment` mapping for `Flats` in the Department, Applicant and Property services

**Comment by plittlewood-rpt** [comment]
Hi @rajeshwl we cannot map both options I'm afraid, otherwise write operations won't be handled correctly.

**Comment by rajeshwl** [comment]
@plittlewood-rpt ,
Currently they have mapped some properties with the above type. So we need some values to be mapped in the field to show in the website.

**Comment by plittlewood-rpt** [comment]
Hi @rajeshwl - as noted on the previous ticket, we cannot currently map these two items. The customer may choose to look at altering the options in their system.

**Comment by rajeshwl** [comment]
@plittlewood-rpt , 
How do we display `Flats` and `Apartment` for this client?

**Comment by rajeshwl** [comment]
@plittlewood-rpt ,
Any updates regarding this?

**Comment by plittlewood-rpt** [comment]
@rajeshwl - as noted previously, we cannot map two items to flatApartment like you are asking for, and we wouldn't add a new item just to support a single customer. The customer will need to consider altering the options available to them.

**Comment by rajeshwl** [comment]
@plittlewood-rpt ,
Your support team has merged this 'Flats - Conversion' and 'Flats - Purpose Built' to Flats in the desktop application. But still we can't find the value for this via API. Can you please check this and make changes in the API. The sample properties that have Flats selected are:
BLF220092
SYD190220
ORP210612

**Comment by plittlewood-rpt** [comment]
Thanks @rajeshwl - we'll get this update this week
