### ISSUE TITLE
We receive time out error on the appointments endpoint

### ISSUE THREAD

**Issue by david-silverink** [reapit/foundations#5931]
We are having a recurring issue connecting to the appointments endpoint for SFG, where the 'endpoint has timed out' error is sent back. The latest occurrence was today at 5pm.

Request headers for this connection are below.

x-amzn-RequestId: 7ae0d997-382a-413b-bc95-e525fb9fd385
x-amzn-ErrorType: InternalServerErrorException
x-amz-apigw-id: MQQ5qHEerPEF20Q=

**Specification**
- Approach in the interim is to implement a db trigger on the SFG database to ensure the amend field is always set
- We can then update the appointments API to build the modifiedFrom filter predicate in a slightly different way for this customer (only use the amend field instead of the existing COALESCE operator)
- Update the Platform Identity Package to include a new property in the customer configuration object
- Long term AC will be updated to always populate this field, at which point we can back out this mechanism and just apply the change to the filter globally across all services
- Work can be done now and should be extensively tested but CANNOT be enabled for any customer until the trigger is in place (this is being done by SI)
- We expected this to result in a dramatic  improvement in performance on this service when using the modifiedFrom filter.

**Comment by plittlewood-rpt** [comment]
Hi @david-silverink - thanks for reaching out. For info we already have some discussion in flight about how we can resolve this for you. I will endeavour to keep this ticket up to date throughout this process.

**Comment by david-silverink** [comment]
Thanks @plittlewood-rpt, there seems to be quite a few time outs today. I have logged 11 since 8am this morning.

**Comment by HollyJoyPhillips** [comment]
@david-silverink Just to let you know we will be moving this into next weeks sprint. However, whilst the work can be done now via Platform and will be extensively tested, it CANNOT be enabled for any customer until the trigger is in place (this is being done by SI)

**Comment by david-silverink** [comment]
I notice this is closed, yet we are still receiving time out errors.

**Comment by plittlewood-rpt** [comment]
Hi @david-silverink - please see commentary about. The Platform aspect of the work has been done but it relies on some work being done by our infrastructure, after which we can switch on the new feature for SFG.
