### ISSUE TITLE
Another Noob Question - Document downloads

### ISSUE THREAD

**Issue by soilleir** [reapit/foundations#5932]
Hello again.

Trying to download a document from the sandbox and getting a 406 status code in the response.  Not sure where I am going wrong.  I am working on an integration with an AML platform.

Request is 
{
    "uri": "https://platform.reapit.cloud/documents/MKT22000012/download",
    "method": "GET",
    "headers": {
        "accept": "application/octet-stream",
        "api-version": "2020-01-31",
        "Authorization": "*sanitized*"
    }
}

Reponse is 
{
    "statusCode": 406,
    "headers": {
        "Connection": "keep-alive",
        "x-amzn-RequestId": "5e9f0611-e933-44a2-9ec9-dbb88b04be43",
        "x-amz-apigw-id": "MQX19HkMLPEFeQg=",
        "x-amzn-Remapped-Server": "Kestrel",
        "X-Amzn-Trace-Id": "Root=1-61e9a025-1baad0576e1a18c3562161bb;Sampled=0",
        "x-amzn-Remapped-Date": "Thu, 20 Jan 2022 17:47:17 GMT",
        "Date": "Thu, 20 Jan 2022 17:47:17 GMT",
        "Content-Length": "0",
        "Content-Type": "application/json"
    }
}

**Comment by AshDeeming** [comment]
Hi @soilleir  - to download the file you need to use the download endpoint which is documented in the Swagger docs. Please let me know if I've misunderstood the question

**Comment by soilleir** [comment]
Hi @AshDeeming   We arent on AWS yet.  Do we need to be on AWS to be able to use Swagger to download and upload files?

**Comment by soilleir** [comment]
Please note we are already a Reapit client so there is no point me exploring this further if we need to have migrated from Rackspace to AWS to use this endpoint

**Comment by soilleir** [comment]
Hi @AshDeeming  

> Hi @soilleir - to download the file you need to use the download endpoint which is documented in the Swagger docs. Please let me know if I've misunderstood the question

Hi @AshDeeming  I think that's what i have done.  I am trying to replicate the request in our Automation platfrom (as i have done with our other requests) but get a 406 error. This error isnt documented to difficult to troubleshoot.

**Comment by soilleir** [comment]
Figured this out @AshDeeming   I hadnt requested that the App had access to read and write documents.

**Comment by AshDeeming** [comment]
Thanks for advising @soilleir
