### ISSUE TITLE
Confirmation on embedded propertyImages number of API calls

### ISSUE THREAD

**Issue by propertyhive** [reapit/foundations#5935]
If we make a request for properties with 'propertyImages' passed as 'embedded', how does this work in terms of the number of API calls made / that we get charged for?

If there are 10 properties that each have 10 images, does this count as 11 total endpoint requests (1 for the property and one for each of the properties images) or 2 (one for the properties and one for all the images associated with these properties).

On a related note, I know we can request propertyImages separately from the main request for properties (ie. separate API call and not using embeds) which accepts a 'propertyIds' parameter. If we pass 10 property IDs through to /propertyImages/, again does that count as 1 API request or 10?

With charges being per endpoint request we're keen to reduce the number of requests made so would be good to get confirmation on this.

Thanks,
Steve

**Comment by AshDeeming** [comment]
Hi @propertyhive 
For point one, they will be charged as separate requests

The charges are based on the Request not the number of results.

**Comment by propertyhive** [comment]
@AshDeeming Thanks for your response. So for point 1 it sounds like 11 requests would be made. 

Any thoughts on my other question:

> On a related note, I know we can request propertyImages separately from the main request for properties (ie. separate API call and not using embeds) which accepts a 'propertyIds' parameter. If we pass 10 property IDs through to /propertyImages/, again does that count as 1 API request or 10?

As it's one endpoint request I feel like this should only count as one API request but confirmation would be good.

Thanks,
Steve

**Comment by AshDeeming** [comment]
Hi @propertyhive  - You are correct, as its one request - the return is irrelevant.
