### ISSUE TITLE
Property Document

### ISSUE THREAD

**Issue by sanjayisg** [reapit/foundations#5937]
I need to get property related documents like browser, in bellow I get pdf name(24 Smithson Road Details.pdf) but it's not sure will be the full path that I can use to call?

Like for property images we get full path but for documents I could not see.

Please help!

{
  "_embedded": [
    {
      "id": "OXF20000060",
      "created": "2020-01-25T15:44:28.0000000Z",
      "modified": "2020-01-26T09:24:02.0000000Z",
      "associatedType": "property",
      "associatedId": "OXF190347",
      "typeId": "DET",
      "name": "24 Smithson Road Details.pdf",
      "metadata": {
        "CustomField1": "CustomValue1",
        "CustomField2": "CustomValue2"
      },
      "_links": {
        "self": {
          "href": "/documents/OXF20000060"
        },
        "download": {
          "href": "/documents/OXF20000060/download"
        },
        "type": {
          "href": "/configuration/documentTypes/DET"
        }
      }
    }
  ],
  "pageNumber": 1,
  "pageSize": 1,
  "pageCount": 1,
  "totalPageCount": 1,
  "totalCount": 2,
  "_links": {
    "self": {
      "href": "/documents/?PageNumber=1&PageSize=1"
    },
    "first": {
      "href": "/documents/?PageNumber=1&PageSize=1"
    },
    "next": {
      "href": "/documents/?PageNumber=2&PageSize=1"
    },
    "last": {
      "href": "/documents/?PageNumber=2&PageSize=1"
    }
  }
}

Thanks,

Sanjay Gupta

**Comment by plittlewood-rpt** [comment]
Hi @sanjayisg - if you are wanting to download the actual file you need to use the download endpoint which is documented in the Swagger spec. Please advise if this does not resolve your issue. Thanks

**Comment by sanjayisg** [comment]
No I don't want to download it, I just need full url of pdf that I can link in website.

**Comment by plittlewood-rpt** [comment]
You would need to link to the download endpoint, bearing in mind that the request will need to be accompanied by a valid authorization header.

**Comment by sanjayisg** [comment]
Ahh! can you please help me in finding 'Swagger spec', I mean wanted to know any example which can show this download feature/script?

**Comment by plittlewood-rpt** [comment]
Hi @sanjayisg - you can access the Swagger documentation at https://developers.reapit.cloud/swagger

**Comment by sanjayisg** [comment]
Yes I am following this, just naming convention difference. I was able to fetch all property and images with api but issue in only document.

https://www.dropbox.com/s/mlgxdl175kwvcar/prop.PNG?dl=0

**Comment by plittlewood-rpt** [comment]
I am not sure what problem you are experiencing. Is it that you cannot determine which document on a property is the brochure? If so, whenever a brochure is associated with a letting/selling property you will see a corresponding link in the _links collection called `lettingBrochure` and `sellingBrochure` respectively which you can use to access the correct document.

**Comment by sanjayisg** [comment]
Ok for now there is no such key for as sellingBrochure or lettingBrochure in documnets API

https://platform.reapit.cloud/documents/

{
  "_embedded": [
    {
      "id": "OXF20000060",
      "created": "2020-01-25T15:44:28.0000000Z",
      "modified": "2020-01-26T09:24:02.0000000Z",
      "associatedType": "property",
      "associatedId": "OXF190347",
      "typeId": "DET",
      "name": "24 Smithson Road Details.pdf",
      "metadata": {
        "CustomField1": "CustomValue1",
        "CustomField2": "CustomValue2"
      },
      "_links": {
        "self": {
          "href": "/documents/OXF20000060"
        },
        "download": {
          "href": "/documents/OXF20000060/download"
        },
        "type": {
          "href": "/configuration/documentTypes/DET"
        }
      }
    }
  ],
  "pageNumber": 1,
  "pageSize": 1,
  "pageCount": 1,
  "totalPageCount": 1,
  "totalCount": 2,
  "_links": {
    "self": {
      "href": "/documents/?PageNumber=1&PageSize=1"
    },
    "first": {
      "href": "/documents/?PageNumber=1&PageSize=1"
    },
    "next": {
      "href": "/documents/?PageNumber=2&PageSize=1"
    },
    "last": {
      "href": "/documents/?PageNumber=2&PageSize=1"
    }
  }
}

**Comment by plittlewood-rpt** [comment]
These links are included in the PropertyModel from `GET /properties` and `GET /properties/{id}`

**Comment by sanjayisg** [comment]
Ok here is that in property API 

 "sellingBrochure": {
      "href": "/documents/DOC21000002"
    },
    "lettingBrochure": {
      "href": "/documents/DOC21000001"
    },
    
    but still same issue it's not full path, I have to call this reapit API   /documents/DOC21000001
    
    and it will return as below:
    
    https://www.dropbox.com/s/zhsb7dttztz39n7/documents.PNG?dl=0

    https://www.dropbox.com/s/ozevypwjpnee35y/doc-reapit.PNG?dl=0

**Comment by sanjayisg** [comment]
Can you please show me any such property that have documents attached with that?

**Comment by plittlewood-rpt** [comment]
Hi - you will never be given the full path. You are given the filename so you can manage the name of the file when it is downloaded. The link in the _links collection points you at the documents resource, which has an associated download endpoint which you then use to access the actual file. Does that make sense?
