### ISSUE TITLE
Expose Property - Internet URL Field

### ISSUE THREAD

**Issue by stebrough** [reapit/foundations#5953]
**Is your feature request related to a problem? Please describe.**
Missing property fields

**Describe the solution you'd like**
For a property, expose the field 'Internet' -> 'URL'

**Screenshot*
![propertyreapit](https://user-images.githubusercontent.com/40298446/150565408-a402849e-6b83-48ef-9f3d-f11cd1dac2cc.jpg)
*

**Specification**
- Service: Reapit.Services.Properties
- Platform will only be able to expose URLs where they have been explicitly set by users as we cannot add the URL building mechanism into the APIs to generate them on the fly as it will generate too much overhead. 
- Add a new `url` property to the `PropertyModel` that exposes semi-structured field `extras.pUrl` in the properties service (Reapit.Services.Properties)
- This field should be both readable and writeable (GET/POST/PATCH should all be supported)
- For POST/PATCH, we should validate that it is a valid URL (there are already extension methods that do this)

**Comment by plittlewood-rpt** [comment]
Hi @stebrough - unfortunately there is no easy way to expose this information at present due to the way it is stored in AgencyCloud. That said it is something that a few people have asked for, so we can review with our desktop team when there is space in the roadmap. In the meantime, most customer URLs are built from a template and contain the property id, so you could build the URL up in your app instead

**Comment by stebrough** [comment]
> Hi @stebrough - unfortunately there is no easy way to expose this information at present due to the way it is stored in AgencyCloud. That said it is something that a few people have asked for, so we can review with our desktop team when there is space in the roadmap. In the meantime, most customer URLs are built from a template and contain the property id, so you could build the URL up in your app instead

Hi @plittlewood-rpt could you please provide an example of the URL you mentioned?

Thanks

**Comment by plittlewood-rpt** [comment]
Hi @stebrough - the format is different for each customer so you would need to liaise with them in the first instance, although you can sometimes work out the format from the customer's own website, if they use reapit references in the URL structure
