### ISSUE TITLE
AWS triggers not firing despite webhooks being created and showing as active in the portal.

### ISSUE THREAD

**Issue by bradkieser** [reapit/foundations#5956]
Please refer to Jira case RSD-163981 for the customer name and other sensitive details that cannot be posted on a public forum.

We created webhooks for the client. Webhook type was for appointments (VW) being created, modified and deleted. Client also has DLL action on set up on appointment actions. It looks like there's a bug that if DLL actions have been set up, then AWS triggers don't fire.

**Comment by plittlewood-rpt** [comment]
Hi @bradkieser - thanks for getting in touch. It looks like there's been an oversight with this specific customer when they were migrated to AWS and the webhooks pipeline hasn't been enabled. This is something our service infrastructure team manage so I have reached out to them and expressed the high priority. I will close this ticket and update the one in JIRA. Thanks
