### ISSUE TITLE
How to get live with Reapit API

### ISSUE THREAD

**Issue by sanjayisg** [reapit/foundations#5960]
Hi There,

I want to move live from Sandbox mode, for that I have ready my code which fetch all property data and show on website, I have also create a new app to get live credentials, I can see app is approved and I have to link with live customer ID but when I tried to get it from app market and then setting I get customer ID as SBOX which I think is sandbox

https://www.dropbox.com/s/emag9vxai0rtfzt/client_id.PNG?dl=0

Can you please tell me how I can get live details?

Thanks,

Sanjay Gupta

**Comment by AshDeeming** [comment]
Hi @sanjayisg 
If i understand correctly you are looking to toggle between Sandbox & Client data. 
From the screen recording you are on the Marketplace instead of Developer portal - the toggle is on the the latter; https://developers.reapit.cloud/settings/profile

**Comment by sanjayisg** [comment]
Where we can get Client ID to go live? that is not here https://developers.reapit.cloud/settings/profile

**Comment by AshDeeming** [comment]
@sanjayisg - Please see the documentation to list your app; https://foundations-documentation.reapit.cloud/listing-your-app

The client ID is used in the private apps section if you are creation an app for a specific client;
https://foundations-documentation.reapit.cloud/listing-your-app

**Comment by sanjayisg** [comment]
Hi don't think we are on same track:

See I have created a test App with name 'BR REAPIT TEST NEW' https://www.dropbox.com/s/8cp0c3e6sfwisv5/sandbox.PNG?dl=0

Which is listed and approved, I check all api and create our script to fetch data with API on our site.

Now I want to get in live environment and for that I have created another app 'Benham and Reeves Website Feeder' which has approved but it's not listed yet

https://www.dropbox.com/s/i1k1oi4739gw0uz/forlive.PNG?dl=0

Please suggest what we can do next.

Thanks,

Sanjay Gupta
