### ISSUE TITLE
How to have a single app that updates data in Reapit via backend and is able to view the data using a client UI integrated to the Desktop?

### ISSUE THREAD

**Issue by bakaevd** [reapit/foundations#5968]
**Summary**
Looking for advice on how best to implement auth.

- We are building a Marketplace App that continuously syncs contacts from another system into Reapit. 
- The app has a backend that reads contacts from the source system and creates contacts in Reapit.  

The source system has additional fields that get added as metadata on the Contact in Reapit.
We need a way for the users to view that metadata in the AgencyCloud Desktop. 
We used the Create-React-App template to create a UI and integrate it via Contact Type to the Desktop.
The UI opens up a page that retrieves the metadata from the contact and shows it to the user.

It appears that the UI needs to use the "Authorization Code flow" to get access to Reapit API to get the contact data.

The problem is that we also need to have the backend that does the syncing also authorised with the API.

We thought about saving the access token of the first person to install/open the App and use that for sync operations in the backend.  But this seems like a hack and hasn't exactly worked yet.  

It seems like having the backend use the "Client Credentials" flow would be the best approach, but from what I'm reading here: https://github.com/reapit/foundations/issues/5590  having the same app use both flows is not supported.  

What's your advice on how to handle this situation? 

Requiring users to install two apps is not great.

Thank you!
 
**Detail and or supporting links and screenshots**

**Comment by willmcvay** [comment]
Hi @bakaevd,

Firstly, just some clarity on MetaData. There is no mechanism to surface this in the AgencyCloud desktop app itself (for example on the contact screen), rather it is your application, loaded in a web view and launched from the contact screen that would have to render the MetaData. 

Moving on to the core question, yes, the two apps approach is the correct one at this point based on your use case. As you say, caching access tokens and using them to do the syncing would be a hack and we wouldn't advise as best practice.

What I would say on this approach;

- We know installing 2 apps is not ideal however, there are a few developers that are live and have handled it with a "sidekick" app for the back end functions for syncing. See https://marketplace.reapit.cloud/apps for some examples.
- A single customer admin (likely someone you will have direct contact with), handles installation for an entire org. You are not asking each user to install 2 apps individually. It's one person, 2 clicks, once, and customers so far have not found this to be too onerous when it has been explained to them.
- We are very much aware of this limitation and are actively looking at "dual auth flow apps" as a product team however, there are some technical limitations we need to overcome and the task is non trivial. What I would say is we are working on it if you can bear with us.

**Comment by bakaevd** [comment]
Thank you for the prompt reply.

Yes, since there is no mechanism to expose metadata natively we are forced to have a UI component to our application, integrated to the AgencyCloud Desktop's Contact screen (as stated in the beginning of my inquiry).  By comparison, other CRMs will let you create custom fields and expose them on the UI.   That said, we also need to request 2 configuration parameters from the admin who installs the app so even without metadata.

OK, will discuss it internally and proceed accordingly.
