### ISSUE TITLE
How to get what companies are related to a Landlord

### ISSUE THREAD

**Issue by setigallego** [reapit/foundations#5977]
**Summary**
Is there any way to identify what properties are related with what companies without having reading permissions on the  companies themselves? 

**Detail and or supporting links and screenshots**
Changing permission seem to involve a great deal of step for all our users from your support:

In order to amend the app permissions, each client will need to first Uninstall the app.
An admin on the Developer Portal will then need to untick, ‘Is Listed’ which will allow you to amend the permissions & then re-tick before submitting for approval.
Once this has been approved, clients will be able to re-install the app, agreeing to the revised permissions. 

We have a number of  clients at the moment on the integration so this doesn't feel like viable option so we are interested on any other options

**Comment by AshDeeming** [comment]
Hi @setigallego  - The related company will only be visible once a client has installed the app.

If you wish to update permissions, all clients will need to uninstall, changes made & then re-listed, allowing clients to agree to the new permission set. 
If your app update requires new permissions, you can alternatively create the new app, advise your client base to install the new & uninstall the old/original.
