### ISSUE TITLE
Information Request for Office Groups

### ISSUE THREAD

**Issue by RJA-LFS** [reapit/foundations#5984]
Where can I find documentation / information relating to Office Groups

We have developed a market place application under the assumption that a company had a unique 3-4 digit company code. However a new customer has now installed our app and the company code in the App Installation email has notified us that their code is ABC-DEF where ABC is the code we were expecting and DEF relates to a branch (I assume).

Is there any documentation that explains what this is and how a market place app integrates with theses branches? 

Is this feature available in the RPS-Developer application so we can test this scenario?

I found the following issue [Issue 5825](https://github.com/reapit/foundations/issues/5825) and want to clarify what happens to metadata that is stored against ABC as opposed to ABD-DEF, in our situation the metadata is just an Id from our system and we would want it to be visible to the whole company and not just the branch, is this possible?

**Comment by AshDeeming** [comment]
Hi @RJA-LFS 
Please see the below link to the relevant area, which has recently been updated;
https://foundations-documentation.reapit.cloud/faqs#what-are-office-groups

**Comment by RJA-LFS** [comment]
Thanks @AshDeeming ,

I am not a Reapit user so I don't know if when a user logs in they choose to log in a company wide or into an office group, could you point me to documentation on how that mechanism works?

Also I have read the FAQ but I still have an additional query can you explain what would happen in the following scenario and how it ties into the above question:

My App is installed for Office Group 1 (Customer ID: RES-GOGO): metadata from my app is stored only for RES-GOGO

My App is now installed company wide (Customer ID: RES): where is the metadata stored, either for a user that is a member of RES-GOGO or not.

Can you clarify that if it is installed company wide then even if a user logs in to a specific group (RES-GOGO) that they will see our app and that the customer ID will be RES, and that the metadata will be stored against RES.

Thanks in Advance

**Comment by AshDeeming** [comment]
Hi @RJA-LFS, i can confirm that if the app is installed company wide, the Office Group(s) within that company will also see the apps.

**Comment by RJA-LFS** [comment]
Thanks @AshDeeming, will the data stored within my app still be siloed in the office groups?

As an example there are head office users who aren't member of an office group but their permissions let them see the whole companies data. When one of these user access the metadata stored will they be able to see the metadata in my app that was stored by a user who was logged in as an office group?
