### ISSUE TITLE
App submitted for approval but not heard anything

### ISSUE THREAD

**Issue by nbdesignstudio** [reapit/foundations#5996]
I have submitted an App for submission, but have NOT heard anything in the past week. So wanted to understand if I need to do anything else to ensure the progression of this?

**Comment by AshDeeming** [comment]
Hi @nbdesignstudio  - Please can you confirm the app name?

**Comment by HollyJoyPhillips** [comment]
@nbdesignstudio As discussed via email, your app submission has been received and will be reviewed in due course. For a guide on our reviewal processes/times please see here https://foundations-documentation.reapit.cloud/listing-your-app#2.-submit-for-approval
