### ISSUE TITLE
Agent details

### ISSUE THREAD

**Issue by StickManMobile** [reapit/foundations#6002]
Is it possible to get details for the agents selling / managing the properties such as logo's, address and name of the agent? I can see office details but that does not seem to contain anything other than the address.

**Comment by AshDeeming** [comment]
Hi @StickManMobile  - The Agents details are available once the app has been installed & permissions agreed via their Customer ID.

**Comment by StickManMobile** [comment]
Thanks Ash can you point me to the API end point where they would be
retrieved?
Tom

**Comment by AshDeeming** [comment]
Hi @StickManMobile, please see the below from our FAQ's which should assist:
https://foundations-documentation.reapit.cloud/faqs#how-do-i-find-out-information-about-a-user

**Comment by StickManMobile** [comment]
Hi Ash thanks for this however its not the user we are looking for per say. 

For a property returned via https://platform.reapit.cloud/properties/ I am looking to find the address, name and a logo of the listing agent. 

From the property response I could use vendorId for example RPT220024 from which I could use the Vendors end point to get more info. However what I think I am actually in need of is the Agency which is included as an agency ID for example "agencyId": "SA" but has no end point to get more information such as the address, telephone number and a logo.

**Comment by AshDeeming** [comment]
Thanks for the detail @StickManMobile 

To clarify, the Agency fields can be found on the model section, see below;
![image](https://user-images.githubusercontent.com/61687775/151553077-7ce06676-e4a9-4734-a0aa-2c67fa3c55c7.png)

The Clients using AgencyCloud will have their own database & the properties they are selling will be listed as such as opposed to if they are a sub-agent.

**Comment by StickManMobile** [comment]
Understood thanks @AshDeeming however I still have no way of getting the agents logo, address etc  from the RestAPI is that correct? Only from RepitConnect?

**Comment by AshDeeming** [comment]
Hi @StickManMobile  - The clients organisation logo isn't currently surfaced, this would require a feature request ticket for future review. 

As for Addresses, this would be under the Offices endpoint for each Office under the Company.
