### ISSUE TITLE
Expand sample data in sandbox

### ISSUE THREAD

**Issue by bobf** [reapit/foundations#6012]
**Is your feature request related to a problem? Please describe.**
It is difficult to implement a property processing application because sample properties do not seem to have images and/or documents associated with them.

**Describe the solution you'd like**
Data provided in the `_links` section of each property (or other entity) to be populated with URLs to real images/documents.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by AshDeeming** [comment]
Hi @bobf 
Please note that the swagger documents show examples with a further breakdown within the Model section. 
You can also use the Developer edition of AgencyCloud (under Desktop on developer portal) or using an API client such as Postman to create records with relevant data.
