### ISSUE TITLE
The new app creation wizard should show relevant content at each step

### ISSUE THREAD

**Issue by willmcvay** [reapit/foundations#6015]
**Background context or User story:**

_Currently the app creation flow shows lorem ipsum at each step. Should show relevant helper text and / or images, videos_

**Specification or Acceptance Criteria:**

- Content TBC @HollyJoyPhillips @AshDeeming can you add to this when you're ready please?

**Comment by AshDeeming** [comment]
This process gives you the access & ability to change AgencyCloud screens], setup a data feeds, check scope & permissions, then test against sandbox data before having your app available to a specific client(s) or public in our AppMarket! 
With this in mind, whether you want to setup a data feed for a website, replace a screen in Agency Cloud, create an Integration or something else...In all cases you will need an 'App'

Using the Foundations Platform, we provide you with, a Client ID registered with Reapit Connect's OAuth

Please go through these steps carefully, considering your apps requirements throughout


**What kind of user**
Please choose one of the below selections which will assist you in creating an app & accessing Authentication Client ID & secret. 

**About Users** – A user of the Developer Portal relates to their role in creating an app for the Reapit Foundations AppMarket.The selections made will pre-populate or direct you to through the relevant app creation process to assist with ensuring you have the correct setup for your app. 

**Existing Reapit Customer** – A Current or On-Boarding Reapit AgencyCloud User/Company 
**3rd Party Web Developer** – A Website developer/Company, creating a site or app for a Reapit Client or for the Reapit AppMarket
**WebService to Foundations** – Converting a service/process from the previous Reapit SOAP WebService API to the Foundations Platform API
**Reapit Connect as ID Provider** – An app for OAuth only (Sign in with Reapit)
**Other** – This option allows you go through the available options manually for those who know exactly what options they require to setup/configure an app. 



**What kind of app am I building?**
Please choose which of the below best describes what you are looking to achieve

**About Apps** – These options will assist you in selecting the correct app setup for your requirements for this particular app. 

**AgencyCloud Functionality** – Add additional functionality with-in the Reapit Agency Cloud Desktop software 
**Replace an AgencyCloud Screen** – Replace a current feature/screen with-in Reapit Agency Cloud desktop software, using the available Desktop Integration types. 
**Data/Portal Feed** – Create/Setup the data to populate a Data Feed utilising the information within Reapit Agency Cloud Desktop software
**Reporting** – Create an app to analysis data for Reporting purposes. 
**Server Side** – Authenticate using a REST service on the server side. Typically for pulling data into an existing application
**Client Side** – Using Reapit Connect as Oauth provider for a Web Application either single page application  or server rendered site
**Website Feed** – Create/Setup the data to populate a Website utilising the information within Reapit Agency Cloud Desktop software


**Permissions**
Please check the below pre-selected permissions -these have been auto selected based on your previous selections through this process. If you believe you require additional permission, please go back through the setup to check if another option better suits your scopes. 

**About Permissions** – 
Permissions will allow the Client to see & accept what data you are requesting to access & potentially amend/update, when writing back through using your app. 
These are the permissions that a Company Installing the integration will agree to in order for you to access relevant data from their database.
NB: You should not drive your website directly using our API’s  - it’s better to use your intimidatory data store.



**Authentication**
Please register one or more Redirect URIs and a Sign Out URIs to allow Reapit Connect to direct traffic back to your application securely.

**About Authentication**
The Foundations platform uses OpenID Connect for authenticating requests. OpenID Connect is a protocol for authenticating users, built on top of the OAuth 2.0 specification.

**Redirect URI(s)** - Please enter a Redirect URI(s) to define the route Reapit Connect is permitted to redirect to after a successful authentication.
**Sign Out URI(s)** – Please enter to define the route Reapit Connect is permitted to redirect to after successfully logging out.
