### ISSUE TITLE
Can't get all property listing 

### ISSUE THREAD

**Issue by sanjayisg** [reapit/foundations#6027]
Hi,

I am using desktop s/w for property management, but hit api to get data with API I can see only 2 properties are listed where as we have more then this there in APP.

https://www.dropbox.com/s/9pyr686osjsq9p4/live.PNG?dl=0

Can  you please help me in finding out the reason why not all property are synced?

Here is the listed data with API:

{
    "_embedded": [
        {
            "id": "TXX190002",
            "created": "2019-07-16T15:03:56Z",
            "modified": "2019-07-26T14:31:51Z",
            "marketingMode": "letting",
            "currency": "GBP",
            "alternateId": null,
            "address": {
                "buildingName": "",
                "buildingNumber": "29",
                "line1": "The Drive",
                "line2": "Sharnbrook",
                "line3": "Bedford",
                "line4": "Bedfordshire",
                "postcode": "MK44 1HU",
                "countryId": "GB",
                "geolocation": {
                    "latitude": -45.107799,
                    "longitude": 170.963114
                }
            },
            "areaId": "",
            "strapline": null,
            "description": "The property has countryside views and the  accomodation comprises a sitting room, open plan kitchen/dining room, conservatory, two double bedrooms with built in wardrobes, and bathroom with shower over bath. There is a garden with countryside views,  garage and off street parking.  Available early March, unfurnished.",
            "longDescription": "The property has countryside views and the  accomodation comprises a sitting room, open plan kitchen/dining room, conservatory, two double bedrooms with built in wardrobes, and bathroom with shower over bath. There is a garden with countryside views,  garage and off street parking.  Available early March, unfurnished.\r\rThe property has accommodation of approx. 820 sq. ft. set over two floors and includes two double bedrooms and two bath/shower rooms on the first floor. To the ground floor there is a kitchen/dining room, a sitting room and a cloak room. There is an enclosed garden and a single garage with off street parking for a car.",
            "summary": "• 4 bedrooms\r• Quiet location\r• Refitted Kitchen\r• Ensuite master bedroom\r• Indoor swimming pool\r• Large garden\r• Gated Entrance\r• Security System\r• Guard Dogs available",
            "departmentId": "G",
            "negotiatorId": "TXX",
            "bedrooms": 3,
            "receptions": 2,
            "bathrooms": 1,
            "councilTax": "A",
            "internetAdvertising": false,
            "isExternal": false,
            "viewingArrangements": null,
            "videoUrl": "Virtual Tour",
            "videoCaption": "www.youtube.com",
            "video2Url": null,
            "video2Caption": null,
            "notes": "Property copied from reference: TXX190001",
            "boardStatus": "FS",
            "boardNotes": null,
            "boardUpdated": null,
            "archivedOn": null,
            "fromArchive": false,
            "externalArea": null,
            "internalArea": {
                "type": "squareFeet",
                "min": 450,
                "max": 0
            },
            "epc": {
                "exempt": true,
                "eer": 0,
                "eerPotential": 0,
                "eir": 0,
                "eirPotential": 0
            },
            "selling": null,
            "letting": {
                "instructed": "2019-07-16",
                "availableFrom": "2020-07-24",
                "availableTo": null,
                "rent": 750,
                "rentFrequency": "monthly",
                "furnishing": [
                    "furnished"
                ],
                "term": "short",
                "status": "tenancyCurrentUnavailable",
                "agentRole": "managed",
                "landlordId": "TXX190002",
                "brochureId": null,
                "managementFee": {
                    "type": "percentage",
                    "amount": 10
                },
                "lettingFee": {
                    "type": "percentage",
                    "amount": 12
                },
                "qualifier": "askingRent",
                "utilities": {
                    "gasCompanyId": null,
                    "gasMeterPoint": null,
                    "electricityCompanyId": null,
                    "electricityMeterPoint": null,
                    "waterCompanyId": null,
                    "waterMeterPoint": null,
                    "telephoneCompanyId": null,
                    "internetCompanyId": null,
                    "cableTvCompanyId": null
                }
            },
            "type": [],
            "style": [
                "detached"
            ],
            "situation": [
                "garden"
            ],
            "parking": [],
            "age": [
                "modern"
            ],
            "locality": [
                "village"
            ],
            "specialFeatures": [
                "Children"
            ],
            "rooms": [
                {
                    "name": "Entrance Hall",
                    "dimensions": "12*10",
                    "description": "entrance hall text"
                },
                {
                    "name": "Cloakroom",
                    "dimensions": "5*5",
                    "description": "cloakroom text"
                },
                {
                    "name": "Kitchen",
                    "dimensions": "15*25",
                    "description": "Extended modern kitchen"
                },
                {
                    "name": "Utility Room",
                    "dimensions": "10*10",
                    "description": "utility room text"
                },
                {
                    "name": "Living Room",
                    "dimensions": "30*25",
                    "description": "Living room text"
                },
                {
                    "name": "Landing",
                    "dimensions": "",
                    "description": "leading to:"
                },
                {
                    "name": "Master Bedroom",
                    "dimensions": "25*20",
                    "description": "master beroom text"
                },
                {
                    "name": "Ensuite Bathroom",
                    "dimensions": "5.5*5.5",
                    "description": "ensuit text"
                },
                {
                    "name": "Bedroom 2",
                    "dimensions": "15*15",
                    "description": "Bedroom 2 text"
                },
                {
                    "name": "Bedroom 3",
                    "dimensions": "20*20",
                    "description": "Bedrom 3 text"
                },
                {
                    "name": "Bedroom 4",
                    "dimensions": "10*10",
                    "description": "Bedrom 4 text"
                },
                {
                    "name": "Garden",
                    "dimensions": "",
                    "description": "garden text"
                },
                {
                    "name": "Swimming Pool",
                    "dimensions": "",
                    "description": "swimming pool text"
                }
            ],
            "officeIds": [
                "TXX"
            ],
            "lostInstructionDate": null,
            "lostInstructionNote": null,
            "extrasField": {},
            "_eTag": "\"EE0D4D529C52214E0DA52E4B8A8491D6\"",
            "_links": {
                "self": {
                    "href": "/properties/TXX190002"
                },
                "images": {
                    "href": "/propertyImages/?propertyId=TXX190002"
                },
                "documents": {
                    "href": "/documents/?associatedType=property&associatedId=TXX190002"
                },
                "offers": {
                    "href": "/offers/?propertyId=TXX190002"
                },
                "appointments": {
                    "href": "/appointments/?propertyId=TXX190002"
                },
                "negotiator": {
                    "href": "/negotiators/TXX"
                },
                "offices": {
                    "href": "/offices/?id=TXX"
                },
                "department": {
                    "href": "/departments/G"
                },
                "landlord": {
                    "href": "/landlords/TXX190002"
                },
                "boardStatus": {
                    "href": "/configuration/boardStatuses/FS"
                }
            },
            "_embedded": null,
            "metadata": {}
        },
        {
            "id": "TXX190001",
            "created": "2019-07-16T14:53:24Z",
            "modified": "2019-07-26T14:34:32Z",
            "marketingMode": "selling",
            "currency": "GBP",
            "alternateId": null,
            "address": {
                "buildingName": "Oaklands",
                "buildingNumber": "12",
                "line1": "Leyland Close",
                "line2": "Gawcott",
                "line3": "Buckingham",
                "line4": "Buckinghamshire",
                "postcode": "MK18 4FG",
                "countryId": "GB",
                "geolocation": {
                    "latitude": -45.107799,
                    "longitude": 170.963114
                }
            },
            "areaId": "",
            "strapline": null,
            "description": "The stable block comprises five stables, a tack room and a hay store.  The 14 acres of paddock land have a water supply and are enclosed by post and rail fence.",
            "longDescription": "A beautifully presented and substantially improved detached bungalow with a charming southerly garden in a much sought after residential area of Eastbourne. The generously proportioned accommodation has been substantially and tastefully improved by the present owners in recent years and is now offered with the benefit of an early possession date if required. Only an internal inspection will convey the high merit and appeal of this delightful home.",
            "summary": "• 4 bedrooms\r• Quiet location\r• Refitted Kitchen\r• Ensuite master bedroom\r• Indoor swimming pool\r• Large garden\r• Gated Entrance\r• Security System\r• Guard Dogs available",
            "departmentId": "G",
            "negotiatorId": "TXX",
            "bedrooms": 3,
            "receptions": 2,
            "bathrooms": 1,
            "councilTax": "A",
            "internetAdvertising": false,
            "isExternal": false,
            "viewingArrangements": "Beare of the dog",
            "videoUrl": "Virtual Tour",
            "videoCaption": "www.youtube.com",
            "video2Url": null,
            "video2Caption": null,
            "notes": "",
            "boardStatus": "FS",
            "boardNotes": null,
            "boardUpdated": null,
            "archivedOn": null,
            "fromArchive": false,
            "externalArea": null,
            "internalArea": {
                "type": "squareFeet",
                "min": 450,
                "max": 0
            },
            "epc": {
                "exempt": false,
                "eer": 56,
                "eerPotential": 65,
                "eir": 44,
                "eirPotential": 75
            },
            "selling": {
                "instructed": "2019-07-16",
                "price": 459950,
                "priceTo": null,
                "qualifier": "guidePrice",
                "status": "completed",
                "disposal": "privateTreaty",
                "completed": "2019-07-26",
                "exchanged": "2019-07-17",
                "accountPaid": null,
                "tenure": {
                    "type": "freehold",
                    "expiry": null
                },
                "vendorId": "TXX190001",
                "agency": "soleAgent",
                "agencyId": "SA",
                "fee": {
                    "type": "percentage",
                    "amount": 2
                },
                "exchangedCompanyFee": 12000,
                "recommendedPrice": 450000,
                "brochureId": null,
                "exchangedPrice": 600000,
                "exchangedOfficeId": "TXX",
                "decoration": [
                    "veryGood"
                ]
            },
            "letting": null,
            "type": [
                "house"
            ],
            "style": [
                "detached"
            ],
            "situation": [
                "garden"
            ],
            "parking": [],
            "age": [
                "modern"
            ],
            "locality": [
                "village"
            ],
            "specialFeatures": [
                "Swimming Pool"
            ],
            "rooms": [
                {
                    "name": "Entrance Hall",
                    "dimensions": "12*10",
                    "description": "entrance hall text"
                },
                {
                    "name": "Cloakroom",
                    "dimensions": "5*5",
                    "description": "cloakroom text"
                },
                {
                    "name": "Kitchen",
                    "dimensions": "15*25",
                    "description": "Extended modern kitchen"
                },
                {
                    "name": "Utility Room",
                    "dimensions": "10*10",
                    "description": "utility room text"
                },
                {
                    "name": "Living Room",
                    "dimensions": "30*25",
                    "description": "Living room text"
                },
                {
                    "name": "Landing",
                    "dimensions": "",
                    "description": "leading to:"
                },
                {
                    "name": "Master Bedroom",
                    "dimensions": "25*20",
                    "description": "master beroom text"
                },
                {
                    "name": "Ensuite Bathroom",
                    "dimensions": "5.5*5.5",
                    "description": "ensuit text"
                },
                {
                    "name": "Bedroom 2",
                    "dimensions": "15*15",
                    "description": "Bedroom 2 text"
                },
                {
                    "name": "Bedroom 3",
                    "dimensions": "20*20",
                    "description": "Bedrom 3 text"
                },
                {
                    "name": "Bedroom 4",
                    "dimensions": "10*10",
                    "description": "Bedrom 4 text"
                },
                {
                    "name": "Garden",
                    "dimensions": "",
                    "description": "garden text"
                },
                {
                    "name": "Swimming Pool",
                    "dimensions": "",
                    "description": "swimming pool text"
                }
            ],
            "officeIds": [
                "TXX"
            ],
            "lostInstructionDate": null,
            "lostInstructionNote": null,
            "extrasField": {},
            "_eTag": "\"46A76913A1DEE87CB4250C05FC49AD85\"",
            "_links": {
                "self": {
                    "href": "/properties/TXX190001"
                },
                "images": {
                    "href": "/propertyImages/?propertyId=TXX190001"
                },
                "documents": {
                    "href": "/documents/?associatedType=property&associatedId=TXX190001"
                },
                "offers": {
                    "href": "/offers/?propertyId=TXX190001"
                },
                "appointments": {
                    "href": "/appointments/?propertyId=TXX190001"
                },
                "negotiator": {
                    "href": "/negotiators/TXX"
                },
                "offices": {
                    "href": "/offices/?id=TXX"
                },
                "department": {
                    "href": "/departments/G"
                },
                "vendor": {
                    "href": "/vendors/TXX190001"
                },
                "boardStatus": {
                    "href": "/configuration/boardStatuses/FS"
                },
                "sellingAgency": {
                    "href": "/configuration/agencyTypes/SA"
                }
            },
            "_embedded": null,
            "metadata": {}
        }
    ],
    "pageNumber": 1,
    "pageSize": 100,
    "pageCount": 2,
    "totalPageCount": 1,
    "totalCount": 2,
    "_links": {
        "self": {
            "href": "/properties/?PageNumber=1&PageSize=100"
        },
        "first": {
            "href": "/properties/?PageNumber=1&PageSize=100"
        }
    }
}

Thanks,

Sanjay Gupta

**Comment by plittlewood-rpt** [comment]
Hi @sanjayisg - which customer is this data from please?

**Comment by sanjayisg** [comment]
Customer ID is BAR

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by sanjayisg** [comment]
We are using RPS desktop app for property management, I can see data is in RPS but we are not able to get them from api. What could be the reason?

**Comment by plittlewood-rpt** [comment]
Thanks @sanjayisg I think I see the problem. I need to liaise with another team internally who deal with some of the platform configuration. I'll get back to you as soon as I can

**Comment by sanjayisg** [comment]
Hi is there any update?

**Comment by plittlewood-rpt** [comment]
Hi @sanjayisg - I've chased this already this morning and will update you as soon as I can

**Comment by plittlewood-rpt** [comment]
@sanjayisg - this should be resolved in the next 15 minutes or so

**Comment by sanjayisg** [comment]
HI,

Thanks, now I am getting data with Reapi API.

Thanks a lot!!.
