### ISSUE TITLE
Getting 422 error but data is correct

### ISSUE THREAD

**Issue by bisoh** [reapit/foundations#6033]
**Describe the bug**
Creating an event that spans all day throws an Http error 422 "`The end date must be on the same day as the start date`" although 
the start and end date _are_ on the same day. It appears to work with end time 23:59:00.

**To Reproduce**

1. Make the following call to the api **POST** _https://platform.reapit.cloud/appointments_
Body:

```
{
    "Start": "2022-02-08T08:00:00Z",
    "End": "2022-02-08T23:59:59Z",
    "TypeId": "MI",
    "Description": null,
    "OrganiserId": "MRAD",
    "NegotiatorIds": ["MRAD"],
    "OfficeIds": null,
    "Attendee": null,
    "PropertyId": null,
    "Accompanied": false,
    "NegotiatorConfirmed": true,
    "AttendeeConfirmed": false,
    "PropertyConfirmed": false,
    "Cancelled": false,
    "metadata":null,
    "_embedded": null,
    "Id": null,
    "_etag": null
}

```
**Response**
```
{
    "errors": [
        {
            "field": "",
            "message": "The end date must be on the same day as the start date"
        }
    ],
    "statusCode": 422,
    "dateTime": "2022-02-01T11:57:40.7194468Z",
    "description": "One or more validation failures have occurred. Please refer to Errors list for details"
}
```

**Expected behaviour**
The appointment to be created and get a 201 response 

**Screenshots**
![image](https://user-images.githubusercontent.com/3708220/151965208-872f7e48-017c-494d-a35b-dfbad0d9e41c.png)

**Device (please complete the following information for web issues):**
 - Device: PC
 - OS: Win10

**Specification**
- This occurs because seconds are not stored in the Platform database and as such we round the timestamp up to the nearest minute. In the example above, this results in the end date being midnight on the date after the start date
- To prevent this, subtract a second from the end date when validating the payload. Do NOT adjust the alterations we already make in the command constructor

**Comment by plittlewood-rpt** [comment]
Hi @bisoh - this will be happening because the time is rounded to the nearest minute for diary appointments. You should find it works up to 23:59:29 and then starts to throw this validation warning. The warning is slightly incorrect though and we should sort that out.

**Comment by bisoh** [comment]
Hey @plittlewood-rpt - I thought it might be something along those lines. Its the error message that threw me off. Thanks for confirming. Do you think this is something that will be changing soon or should I stick to 23:59:00 ?

**Comment by plittlewood-rpt** [comment]
Hi @bisoh - sticking to 23:59:00 is the safest bet right now.
