### ISSUE TITLE
API Endpoints for Reserve funds

### ISSUE THREAD

**Issue by vikiecseri** [reapit/foundations#6035]
**Is your feature request related to a problem? Please describe.**

Majority clients of Fixflo and Reapit want the reserved funds populated when they enter the details in on Fixflo so that funds are held back for instructed jobs. For the amount to sync across, Fixflo needs the endpoint for the functionality to be available. 

**Describe the solution you'd like**
An endpoint from Reapit added for Reserved Funds so that we can use this to automatically populate the reserved funds field once an amount has been entered into on Fixflo. 

**Describe alternatives you've considered**
The current alternative where clients manually populating the reserved funds field isn't working as sometimes agent forget to upload the amount on Reapit / causes problems for the finance departments. 

**Additional context**

This has been requested by the majority of mutual clients and is high priority.

**Comment by vikiecseri** [comment]
Hi Ash,

I was wondering if there is an update and expected timeline. We now have multiple enterprise clients who have requested this to be added urgently. 

Please get back to us as soon as you can. 

Thanks, Viki

**Comment by Julianstirlingackroyd** [comment]
is there an update please?

**Comment by Julianstirlingackroyd** [comment]
?
