### ISSUE TITLE
Possibility for a pop-up when booking Market Appraisals

### ISSUE THREAD

**Issue by Filip5991** [reapit/foundations#6040]
A while ago we developed a webhook app on the foundations platform. It was based on the appointments webhook, and it's main purpose was finding all the Market Appraisals booked by certain people from a client that has installed our app, and then sending those to our app Acaboom.

When a Market Appraisal is booked within Reapit a pop up should appear asking so that the user can: 
 
-       Verify/amend that the Acaboom template about to be used is the one required - it may be a sales, lettings, or customized valuer template.
-       Confirm whether a Pre-Appointment (i.e. appointment confirmation) presentation should be sent.
-       Check the details, including the office, valuer, and account where the presentation should be placed, are correct.
-       Format the address (line 1, address line 2, town, etc) so that the address can be used to collect property data from other sources and data be added to client presentations.

There has been strong client demand for this with specific requests including those listed below:
Leaders/Gibbs Gillespie
Stirling Ackroyd
The Frost Partnership
Greenslade Taylor Hunt

Mutual client are reporting that without this pop up (or some other way to achieve the same end result) the app is not delivering true value to them.

**Comment by plittlewood-rpt** [comment]
Hi @AshDeeming - this seems like an AgencyCloud change to me? Would you agree?

**Comment by HollyJoyPhillips** [comment]
@Filip5991 How are you? If you remember we spoke about this last October (via email) and I had said that this would require both development for AgencyCloud (possibly a new desktop type) and from yourselves to build a user interface (app). It's not something that the Platform team can develop. As part of our processes for AgencyCloud related requests, please can you ask one of the customers listed above, to raise a service desk ticket. They can also link to this ticket for more detail. 

For more information on our requesting desktop types [please click here](https://foundations-documentation.reapit.cloud/dev-requests#requesting-a-new-desktop-integration-type)

**Comment by HollyJoyPhillips** [comment]
The desktop team have added the 'Diary' desktop integration type and will be available in build 12.151 going forward. The Developer Edition will be updated in the next week or so. The Platform team will also need to add this in our production environment, please see ticket https://github.com/reapit/foundations/issues/7396

**Comment by HollyJoyPhillips** [comment]
The Developer Edition update has been scheduled for Monday where the interaction with the diary integration type will be available. We have updated the Desktop API documentation ahead of the release.

**Comment by HollyJoyPhillips** [comment]
The Developer Edition has now been updated to include the 'Diary' desktop integration type.
