### ISSUE TITLE
Integration with Reapit in inside and outside AgencyCloud scenarios

### ISSUE THREAD

**Issue by ricardo-jsd-santos** [reapit/foundations#6052]
Please take a look at our FAQ's before submitting an issue, as your question may already be covered in the documentation https://foundations-documentation.reapit.cloud/faqs

**Summary**

I am the CTO of Monadd.io, and I am currently trying to scope a potential integration with Reapit. We are still deciding if our app should be integrated within or outside AgencyCloud and/or Desktop CRM, though most of the documentation and examples refer to the "inside" scenario. This decision is materialized by the first question/prompt presented when creating a new app. I was referred to this service by Reapit's sales team. 

**Detail and or supporting links and screenshots**

1. The [development documentation](https://foundations-documentation.reapit.cloud/developer-portal), mentions:

"Moving on, you will be asked if you wish to integrate with the AgencyCloud and if so, what page you would like to integrate with. This will allow your app to be launched as a screen direct from AgencyCloud by a user."
 
- Where is the app launched from if it is NOT integrated with AgencyCloud/Desktop CRM, and how is it made available to users in that scenario?

2. What are the branding guidelines, assuming that a developer wants to integrate AgentCloud, but does NOT use the Elements UI library?  

3. Can we have an example/demo of outside AgencyCloud app integrations?

Thank you

**Comment by plittlewood-rpt** [comment]
Hi @ricardo-jsd-santos - please can you give some detail about what the app would do? We've had a few people asking about how to interact with AgencyCloud when the app is not running inside it (ie from a browser) so are wanting to understand developer's use cases so we can have a discussion around this topic.
