### ISSUE TITLE
GeoDiary

### ISSUE THREAD

**Issue by HassanJW** [reapit/foundations#6055]
When using GeoDiary, users are only able to see a maximum number of appointments. So for example on a day full of viewing appointments users can see appointments upto 2.30pm and nothing after. Additionally, we would like 'cancelled' appointment removed from GeoDiary so that they do no appear in a users diary.

**Comment by willmcvay** [comment]
@HassanJW Thanks for this. There are 2 requests here;

Firstly, the reason you are not seeing all the appointments is a default soft limit on the number of appointments returned for performance reasons. We will get this limit increased for you no problem, obviously this will make the app more usable. Glad you are using Geo Diary!

Secondly on the cancelled requests; this is actually a feature another customer asked for ie they wanted to see the cancelled requests in the lists. As such, we will leave the feature in for now but will review if we receive more feedback from other customers that they want it removed.

**Comment by HassanJW** [comment]
Thank you. If you can let me know when the number of appointments has increased so I can update our colleagues. Will it be increased so that all appointments show. The reason I ask is because we will be asking colleagues from Monday not to print paper diaries anymore, so they will be reliant on using GeoDiary

**Comment by willmcvay** [comment]
@HassanJW We will update on this ticket but understand the urgency and should be able to get it to production before Monday.

**Comment by willmcvay** [comment]
@HassanJW This has just been released to production. Geo Diary uses a browser cache so it performs well on phones and works offline. Users now have an upper limit of 100 appointments, the previous was 25.

If anyone is not seeing the change, get them to log out and they should see this version at the login screen:

<img width="405" alt="Screenshot 2022-02-03 at 17 06 22" src="https://user-images.githubusercontent.com/4630495/152392765-838cddf0-9fc3-4a58-bf21-82fa144c85ea.png">

If it is an earlier version, get them to refresh / clear browser history. Geo Diary uses a cache to work well offline so sometimes an older version is held locally on the device until you clear but hopefully not.
