### ISSUE TITLE
Driving the RPS desktop app "from the outside"

### ISSUE THREAD

**Issue by sgregory6767** [reapit/foundations#6056]
This is a similar question to that raised in ##6052.

I have a requirement to integrate from **outside** the RPS application (the .NET Framework WPF going live in March 2022 across my clients branches) as follows:

1) Drive an Oauth client credential flow
2) Use the resulting access token to drive APIs to get contacts matching a phone number
3a) If a match is found, use a piece of info in that contact to "launch RPS into screen-popping the details of the contact"
3b) If a match is not found, "launch RPS into screen-popping a 'new contact'' panel"

Using the sandbox, and having created my app, I have 1) and 2) working really well and I can get records back.

3 is the problem - is there any information about how I can coerce a running RPS desktop instance to navigate to an existing contact or new contact panel ?  e.g. on object model to converse with.

I need to be able to drive RPS screen flows from outside of RPS.

Is there any way to do that - or an alternative approach to get me where I need to be ?

If is helps my version is RPS 12.138.6.

Many thanks,
Simon.

**Comment by sgregory6767** [comment]
Hi Ash - thanks for the quick response,

I have read this with interest. But I may be misunderstanding - as follows:

>> When a AppMarket application is launched and hosted within AgencyCloud...

I should be clear - we have a personal productivity application (separate process / separate Windows desktop exe). This process cant be hosted within your RPS app nor act as an extension of your RPS app (I don't believe).

I want to be able to drive those useful-looking screen navigations from my process. Am I able to drive RPS.exe from ****outside**** the process space with a Contact ID (and whatever you deem as appropriate creds e.g. the access token I have just had to get to drive the Contacts API to give me the Contact which exposes the Contact ID).

The steps to get me from unauthenticated to "the ContactID for a telephone number" are brilliantly trivial. But they mean little if I cant then drive the RPS UI from outside its process space to pop that contact record.

P.S> In addition to #6052, #6057 is also asking for the same sort of thing I believe.

**Comment by sgregory6767** [comment]
Thanks.

Do you have any information on how others may be using the results of an API to interact with Ui elements of a CRM system be that desktop based on web based.

I would be surprised if, having gone to the effort of exposing a very tidy publicly useable API, it could only really be used by apps that ran within the RPS environment itself if the desire were to drive that UI in some way off the back of the API results.

We are trying to achieve telephony integration with screen pop-up which, by its nature, can mean we wish to drive the incumbent CRM system navigation from outside that environment. So trying to avoid writing a desktop extension to do so.

In any case I have asked the customer to ask the questions posed in this thread to the correct support team.

Many thanks for your help.

**Comment by HollyJoyPhillips** [comment]
We have raised a ticket with the Desktop team (PBI-3493). We will close this ticket as it's not something the Platform team can develop.
