### ISSUE TITLE
Patches to reapit system seems to trigger webhooks with default data

### ISSUE THREAD

**Issue by kitoban** [reapit/foundations#6061]
**Describe the bug**
When patches are applied to the customer system this seems to trigger updates to propagate out the newly added fields via webhooks, which for missing data that is now available this is fine. 
However this is also happening for new fields with default data, i.e. null, etc, which is triggering an incurred cost to anyone subscribed to these webhooks for what is essentially a useless message.

**To Reproduce**
Steps to reproduce the behaviour eg:
1. Update a reapit customer where new fields are added to the customer database
2. Observe the webhook output for messages being triggered with new fields with default data.

**Expected behaviour**
Should not receive webhooks for patch updated fields that are not now exposing data, i.e. fields with default data.

**Data example**
Example of a diff section from a live message post the update of a customer system between 2022-02-03T12:40:00Z - 2022-02-03T12:50:00Z (can provide further details if required) 

 ``` json
"diff": {
        "selling": {
            "priceTo": [
                null
            ],
            "agencyId": [
                ""
            ],
            "exchangedCompanyFee": [
                null
            ],
            "decoration": [
                []
            ]
        },
        "isExternal": [
            false
        ],
        "boardStatus": [
            null
        ],
        "boardNotes": [
            null
        ],
        "boardUpdated": [
            null
        ],
        "specialFeatures": [
            []
        ]
    },
```

**Additional context**

**Comment by plittlewood-rpt** [comment]
Hi @kitoban - the current webhooks mechanism will detect any changes between the old copy of an entry (which may be stored in an older version of the contract) and new copy (which will be based on the latest API contract, which can have new fields added which we do without versioning). Unfortunately there's no easy solution to this. We are however looking at the possibility of providing a mechanism to allow developers to specify explicitly which changes they are interested in which puts them in complete control to remove any unnecessary noise. This will effectively negate this problem as you can specify which fields you care about being notified about. This is currently in our long term feature list (#4290) and we are going to pick up the discussions around this topic again.
