### ISSUE TITLE
Need to download document

### ISSUE THREAD

**Issue by sanjayisg** [reapit/foundations#6065]
Hi,

I am using api 

https://platform.reapit.cloud/documents/?associatedType=property&associatedId=TXX220001

and got below result:

{
    "_embedded": [
        {
            "id": "RPT22006260",
            "created": "2022-02-03T15:34:18Z",
            "modified": "2022-02-03T15:34:18Z",
            "associatedType": "property",
            "associatedId": "TXX220001",
            "typeId": "LET",
            "name": "Distillery Wharf.pdf",
            "_eTag": "\"FCBB3E4544C76996BF99FD7B84012A9E\"",
            "_links": {
                "self": {
                    "href": "/documents/RPT22006260"
                },
                "download": {
                    "href": "/documents/RPT22006260/download"
                },
                "type": {
                    "href": "/configuration/documentTypes/LET"
                }
            },
            "metadata": {}
        }
    ],
    "pageNumber": 1,
    "pageSize": 25,
    "pageCount": 1,
    "totalPageCount": 1,
    "totalCount": 1,
    "_links": {
        "self": {
            "href": "/documents/?PageNumber=1&PageSize=25&associatedId=TXX220001&associatedType=property"
        },
        "first": {
            "href": "/documents/?PageNumber=1&PageSize=25&associatedId=TXX220001&associatedType=property"
        }
    }
}

Now I want to download this but when I am trying to get it by https://platform.reapit.cloud/documents/RPT22006260/download

But can't get it can you please help,

Thanks,

Sanjay Gupta

**Comment by plittlewood-rpt** [comment]
@sanjayisg - when you say you can't download it, what happens when you try?

**Comment by plittlewood-rpt** [comment]
Your accept header needs to be `application/octet-stream` - please refer to the Swagger documentation. Thanks

**Comment by sanjayisg** [comment]
yes Thanks
