### ISSUE TITLE
Look at possibility of providing an endpoint to retrieve details about the current user

### ISSUE THREAD

**Issue by plittlewood-rpt** [reapit/foundations#608]
It would possibly add some benefit to be able to access a particular endpoint to get details about the 'current' user (when in a user context), such as contact details, registered office etc.

We should look at whether or not this is feasible or not

**Comment by iWader** [comment]
We have a couple of use cases for an endpoint like this.

Firstly it would allow us to pre-populate several fields on our booking form, mainly name, email, phone number, company, etc.

It would also be useful if this endpoint could return a unique identifier for an account/estate agent. This would allow us to automatically register accounts on InventoryBase without any further information from the user, and book future jobs under that account.

**Comment by cbryanreapit** [comment]
You should find the the identity token issued from Reapit Connect contains  information about the current users identity. Please fire up another issue if you want to request additional information.
