### ISSUE TITLE
Redirecting to developers.marketplace instead of localhost

### ISSUE THREAD

**Issue by sagarwal3005** [reapit/foundations#6088]
**Describe the bug**
We developed a small app to update a app using reapit scaffolding app and api connection. When we run the app on localhost, after authenticating using reapi user ame and password, it redirects user to the developers link instead of the authenticted platform. The app was working 1.5 years ago but now it does not work. The redirect urls are correct in the app and I updated the urls from old dev.connect to the new developer url. The application is on localhost so please let me know how can I help you to reproduce the issue.

**To Reproduce**
Steps to reproduce the behaviour eg:
1. Go to '...' localhost:8080
2. Click on '....' after authentication it should redirect to the authenticated app instead it redirects to Developers link

**Expected behaviour**

**Screenshots**
If applicable, add screenshots to help explain your problem. Please ensure that screenshots do not include sensitive data such as personally identifiable information.

**Device (please complete the following information for web issues):**
 - Device: [e.g. iPhone6, PC, Mac]
 - Browser [e.g. Chrome, Safari]

**Additional context**

**Comment by sagarwal3005** [comment]
Hi, I did register myself on "developers.reapit.cloud" and made changes to
the local application. But it's not working. To explain the issue, I
recorded a video. Please find attached the video of the issue.

If you notice, the redirect_url passed was localhost:8081 but when the
authentication is completed it returns to the
https://developers.reapit.cloud/authorize and says page not found.

Not sure what am I doing wrong as it was working fine when I had it
installed and modified 2 years back.

Regards
Sneha

 screen-capture (3).webm
<https://drive.google.com/file/d/1Rre0OUGGZ5rlN0hCz0fMCR_7RhoIX7oK/view?usp=drive_web>

**Comment by AshDeeming** [comment]
Hi @sagarwal3005  - What is the name of your app please?

**Comment by sagarwal3005** [comment]
GazealApp

**Comment by HollyJoyPhillips** [comment]
@sagarwal3005 For the app 'Gazeal' which is registered under the developer organisation 'Gazeal Limited'  it looks like the redirect URL Is 8080/ not 8081 as mentioned above, can you please verify where you are seeing it set as 8081?

**Comment by sagarwal3005** [comment]
Hello,

Yes the redirect url is 8080 but the application is also running on 8080.
please check the video attached
 screen-capture (4).webm
<https://drive.google.com/file/d/1QM5_BTp1EnaQodPRzkCfiDwah0FgO0pY/view?usp=drive_web>

**Comment by HollyJoyPhillips** [comment]
@sagarwal3005 Could you confirm how you have integrated Reapit Connect? It may seem that if you are using connect session, the 'connectLoginRedirectPath' is pointing to the wrong location. This section in the documentation may help: https://foundations-documentation.reapit.cloud/app-development/connect-session#basic-browser-usage

**Comment by sagarwal3005** [comment]
Hi, I had created this app 2 years back using the scaffolding app sample
that time. Please find below the screenshot of my config file.

[image: image.png]

This does not have a connectLoginRedirectPath. Should I add the value
manually here?

**Comment by HollyJoyPhillips** [comment]
@sagarwal3005 Unfortunately, the image you provided is not showing in the above comment. 

It’s quite difficult for us to debug this with you seeing as the app was created quite a long time ago. I would suggest using the create react scaffolding app to re scaffold your app which will include connect session by default. This will ensure everything is up to date and using the latest components etc. 

You can take your components from the old repo into the new one, then if you have any issues, it will be easier for us to help/for you to debug. 

You can see more information here https://foundations-documentation.reapit.cloud/app-development/create-react-app-template
and https://foundations-documentation.reapit.cloud/app-development/connect-session

**Comment by sagarwal3005** [comment]
Hello,

I did create the new scaffolding app using the link you sent. I updated the
redirect url path in index.tsx. Please find the index.tsx file attached to
this email. i get an error redirect_mismatch on running the application.

I changed the connectLoginRedirectPath: 'https://localhost:8080/',to '/',
'/login', '' but all returns same.

Please let me know what am I missing.

Regards
Sneha

**Comment by HollyJoyPhillips** [comment]
@sagarwal3005 Unfortunately, the file didn't attach. Please can you add it direct on this github issue rather than replying to the email and i'll take a look.  

Thanks.

**Comment by willmcvay** [comment]
@sagarwal3005 The redirect path must be exactly the same as those set in your Developer Portal app so if you have `http://localhost:8080` set in the app page, the `connectLoginRedirectPath` should be set to `''`, not `/`

**Comment by willmcvay** [comment]
@sagarwal3005 Can you confirm this has been fixed. Will close the issue off if I don't hear back.
