### ISSUE TITLE
extrasField data no longer accessible via the API

### ISSUE THREAD

**Issue by richclicksmith** [reapit/foundations#6097]
See https://github.com/reapit/foundations/issues/5511#issuecomment-1031538010 

- The name of the customer you represent
Swoffers - SWF

- The name of every field you need surfaced (if known)
pSummary, pFeatured, pPerrys

- A screenshot of of the field(s) you require in the agency cloud user interface
I don't have access to this (agent is based in Guernsey  - I'm based in the UK).

- A short use case as to why you require this data
The agent is using this information on the front-end of their website. I did have access to it, but I don't seem to any more. 

Thanks.

**Comment by plittlewood-rpt** [comment]
@richclicksmith We know what has caused this and it's with our internal infrastructure team to resolve the underlying issue. I've corrected the configuration which should sync round to the service estate in the next 15 minutes or so. If you can try again after this time to make sure access to this data is restored I'd be grateful
