### ISSUE TITLE
Provide ability to search for a contact by email address

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#610]
## Overview
We provide a means to allow for contacts to be identified by providing their email address. Email address is a common method that developers will want to use to look up contact details as it is simpler and a more reliable attribute than name/address for locating a contact.

### Expectation
`GET /contacts` should provide an additional query string parameter: `email` (string / optional)

Eg. `GET /contacts?email=jsmith@example.com`

Upon providing this query string and it being validated as an email address the API should return a paged response containing contacts that exactly match the email address provided (case insensitive). 

- Add parameter to /contacts and clearly document purpose
- Validate that the parameter provided is in fact an email, return appropriate error response if not
- Build functionality to identify one or more contacts by email address (case insensitive)
- Present results in the existing paged fashion
- Tests where appropriate

**Comment by plittlewood-rpt** [comment]
PR 1736 opened
