### ISSUE TITLE
What would cause 'related' tenant data to be missing from 'tenancies' endpoint?

### ISSUE THREAD

**Issue by hivetom** [reapit/foundations#6105]
Please take a look at our FAQ's before submitting an issue, as your question may already be covered in the documentation https://foundations-documentation.reapit.cloud/faqs

**Summary**
Tenant details are not present in the 'related' key of a tenancy array returned from GET @ tenancies endpoint

**Detail and or supporting links and screenshots**
We expect to gather the tenant details (tenant ID, name, email etc.) from within the 'related' key of each tenancy array returned from the GET @ tenancies endpoint. 

For some tenancies, the 'related' key is empty despite the tenant details showing in the Reapit account for the particular client ID. 

Why would this be? 

Is there a specific process the client needs to follow in order for the tenant details to appear within the 'related' key of the tenants array returned from the GET @ tenancies endpoint?

**Comment by plittlewood-rpt** [comment]
Hi @hivetom - as per the Swagger documentation, the related collection on this endpoint is only populated when the tenant moves into the property and the tenancy status changes to current. Up to that point, they are just an applicant and contact information should be captured from the associated applicant record. Please let me know if this does not fit with what you are seeing.
