### ISSUE TITLE
Apps menu not appearing

### ISSUE THREAD

**Issue by LFS-DMB** [reapit/foundations#6109]
We have an developed an app that has been installed company wide.

The head office user who is linked to a branch can use the app for properties listed for that branch but not for other branches despite being an admin user with access to all branches via the main application.

Other users at other branches do not have an apps menu in the main application.

We are not very familiar with the main ReapIt application so have 2 questions.
1. Why would users in other offices not see the Apps menu when the app is installed companywide
2. are the permissions for users treated differently through the Foundations platform than vai the main application.

**Comment by AshDeeming** [comment]
Hi @LFS-DMB  - All users who have the AppMarket available should be able to see the Apps menu on their AgenyCloud. 
There are some remaining clients awaiting this to be enabled so it may be that they fall into this category. 
With regards to standard permissions, the platform will recognise two levels, i.e. general user or an Admin user  - only an admin user can install apps from the AppMarket.

**Comment by LFS-DMB** [comment]
Hi @AshDeeming thanks for replying we have had an Admin user install our app for everybody but users in the remote branches do not see the Apps menu.  How do we get support for this specific customer as our app works fine for others but this customer has a more complex office setup with a head office and various branches is it possible the branches need to do something additional to a see the Apps menu.

**Comment by LFS-DMB** [comment]
OK cheers I'll ask them to raise this
