### ISSUE TITLE
API End Point for Solicitors/Mortgages/Removals

### ISSUE THREAD

**Issue by AppMarketSales** [reapit/foundations#6118]
Summary of Request:
Hi Foundations Team, I had a call with a current App Partner, Go to Group yesterday and we looked at the AgencyCloud platform and they asked the question if end points existed for the referral panel on the bottom right hand side so they could set up a link via that to open their App for let's say Mortgages. Does this currently exist as a Foundations end point they can build on? Thanks, David

Expected Behaviour

**Comment by HollyJoyPhillips** [comment]
Internal question - answered via email
