### ISSUE TITLE
Form handling with Elements v3.x

### ISSUE THREAD

**Issue by nroper** [reapit/foundations#6128]
**Summary**
We are in the process of converting existing forms from Elements v2 to v3 components and would be grateful for some clarification and advice regarding some aspects of v3 form handling.

**Detail and or supporting links and screenshots**

At present we're using the Reapit/Formik components to handle initial values, validation and error display for form components.  The Reapit/Formik elements are currently still available via Elements 2.3.0,  but are not part the v3 library that's included in the 2.3.0 release. 

At some point we assume that we will move to a  v3-only installation, in which case the original Reapit/Formik elements would no longer be available, so we don't want to be dependent on them.  

It would help to understand how Reapit would recommend replacing the existing Formik functionality for initialising  values, applying validation and handling error display etc. in a  v3-only environment. 

We can't find any examples of input, validation or error handling/display in the v3 Elements documentation, so would the expectation be that we implement this functionality ourselves, using native html5 attributes and handlers for example, or is there something in the documentation that we've overlooked?

Thanks

**Comment by nroper** [comment]
@willmcvay OK, thanks for clarifying - hence my original question referring to a v3-only environment.  

The Formik components currently available via v2 reapit/elements appear to be modified versions of the vanilla Formik components and not directly interchangeable, so we are anticipating that there may need to be some refactoring to account for that.  Does that sound correct to you?

**Comment by willmcvay** [comment]
@nroper Can I close this one off now or is there anything else?

**Comment by nroper** [comment]
@willmcvay could you keep it open for a while longer? We tried importing Formik and using it as you suggested, but got some errors. Will take another look later today or over the weekend.

**Comment by willmcvay** [comment]
Sure, no worries

**Comment by nroper** [comment]
@willmcvay we have something working on this now.
