### ISSUE TITLE
 Use of MultiSelectInput component

### ISSUE THREAD

**Issue by nroper** [reapit/foundations#6129]
**Summary**
Questions relating to use of MultiSelectInput component

**Detail and or supporting links and screenshots**

The MultiSelectInput component does not appear fire any `onChange` or `onSelect` event when a chip is selected.

There is a 'parent' input carrying the id of the component, but this seems to always have a value of undefined, regardless of what chips appear as selected. 

Is this by design, and if so how do we validate?

**Comment by willmcvay** [comment]
Hi @nroper the MultiSelect does respond to onChange. See screengrab from our webhooks page, I am console logging out the change event here as I toggle items

https://capture.dropbox.com/FCM6KsnEXBAO959w?src=ss

2 things that could be happening;

1. Formik is overriding the onChange event (when you apply the field values with a `...rest` operator), so adding an additonal onChange will not work
2. You may have a version of v2 Elements where the v3 onChange isn't working. I re-released v2 with the latest v3 this morning so try to update to 2.3.1 to be sure you have the latest

**Comment by nroper** [comment]
Hi @willmcvay  thanks for getting back and the link.  

Yup, we're on v2 Elements 2.3.0 - so will update to 2.3.1 this morning and try again.

**Comment by willmcvay** [comment]
Cool thanks @nroper let me know if this resolves and if I can close the issue.

**Comment by nroper** [comment]
Hi @willmcvay we probably won't get a chance to look at this for another day or two, so feel free to close and we'll raise another issue or re-open if we need any further assistance.

**Comment by willmcvay** [comment]
Cool, thanks @nroper will do.
