### ISSUE TITLE
Availability of getMarketplaceGlobalsByKey in Elements v3.x

### ISSUE THREAD

**Issue by nroper** [reapit/foundations#6130]
**Summary**

Can you confirm whether `getMarketplaceGlobalsByKey` will still be available in a Elements v3.x-only environment (as oppsed to Elements 2.3.0environment that includes v3 Elelemnts)?

Thanks

**Comment by willmcvay** [comment]
No worries @nroper can I close this one now?

**Comment by nroper** [comment]
Yup, please go ahead and close this one @willmcvay - thanks
