### ISSUE TITLE
eTag field includes quotes

### ISSUE THREAD

**Issue by jpswade** [reapit/foundations#615]
The eTag field appears to include quotes.

This means you get things like this:

`"_eTag": "\"582A891A3DE6DB2ECC4807E3BBA5634A\"",`

**Comment by plittlewood-rpt** [comment]
Hi @jpswade 

Thanks for getting in touch 

As per our documentation at https://foundations-documentation.reapit.cloud/api/api-documentation#optimistic-concurrency we follow RFC 7232 for our eTag format which specifies that the tags should be wrapped inside quotation marks.

Thanks
Pete
