### ISSUE TITLE
Investigate possibility of embedding the associated role into the contact relationships endpoint

### ISSUE THREAD

**Issue by plittlewood-rpt** [reapit/foundations#617]
Being able to embed each role's entity into the response from `GET /contacts/{id}/relationships` would add value and make the platform a little more user friendly. We should investigate the possibility of adding this support, paying attention to the fact the some contacts have quite a large number of roles which would inhibit performance if not correctly applied.

**Comment by cbryanreapit** [comment]
No longer a known requirement
