### ISSUE TITLE
v2 Elements - embedded Embedded v3 Elements support

### ISSUE THREAD

**Issue by nroper** [reapit/foundations#6177]
**Summary**
Some general questions regarding continued support for embedded v3 Elements 

**Detail and or supporting links and screenshots**

We are starting to incrementally convert existing v2 layouts and components to v3, further to which it would be useful to get a feel for the following:

- Is there an expectation that at some point all applications are using v3-only packages and components?
- Will support for the embedded v3 library terminate at some point?
- If so, are there anticipated timelines/deadlines for the above?
- Subject to the above, will the components etc. in the embedded v3 Elements be kept in sync with the core v3 equivalents?
- Is there any documentation that identifies changes, and in particular any breaking changes, that need to be taken into account when migrating from a v2 to v3 installation?

Many thanks

**Comment by willmcvay** [comment]
Hi @nroper this is largely covered in the docs https://foundations-documentation.reapit.cloud/app-development/elements#elements-v2-long-term-support

To answer your points in order:

`Is there an expectation that at some point all applications are using v3-only packages and components?`

Ideally yes, but it's up to individual developers. Certainly new applications for review all have to use v3.

`Will support for the embedded v3 library terminate at some point?`

Yes

`If so, are there anticipated timelines/deadlines for the above?`

No, it will largely depend on demand based on continued installation of the v2 package as per NPM stats.

`Subject to the above, will the components etc. in the embedded v3 Elements be kept in sync with the core v3 equivalents?`

Not for minor patches but yes, for breaking changes and significant fixes.

`Is there any documentation that identifies changes, and in particular any breaking changes, that need to be taken into account when migrating from a v2 to v3 installation?`

No, as per the docs, v2 is incompatible with v3 as v3 is a re-write. It wouldn't make sense to list breaking changes in this context.

**Comment by nroper** [comment]
Many thanks @willmcvay  - all understood so closing this one.
