### ISSUE TITLE
Allow filtering of contacts by role type

### ISSUE THREAD

**Issue by plittlewood-rpt** [reapit/foundations#618]
A common requirement is to be able to retrieve a list of contacts who have a specific role (ie retrieve a list of contacts who are tenants or buyers etc). At the moment the only way to get to this information is to use the role related endpoint (ie /tenancies) and read through the `related` collections which is a bit cumbersome and can probably be neatened up to make the platform a little friendlier.

We should look at any performance impact this might introduce so we can fully assess it before implementing anything.

**Comment by cbryanreapit** [comment]
No longer a known requirement.
