### ISSUE TITLE
Endpoint for additional contacts

### ISSUE THREAD

**Issue by vikiecseri** [reapit/foundations#6181]
**Is your feature request related to a problem? Please describe.**

Some agencies use an additional field under Relationships to display the Agent that is responsible for maintenance issues. Currently the basic and the advance integration with Fixflo uses the Key Contact field on Reapit to sync across the Agents responsible for maintenance. For the agencies, that use the custom field, we have no way of syncing across the Agents on properties and this can only be resolved manually.

**Describe the solution you'd like**

There is an endpoint on your API that enabled us to sync across that additional field.

**Describe alternatives you've considered**
Manually importing the data, however considering it's an advanced integration, it wouldn't really work. 

**Additional context**
I have checked the documentation, but couldn't find an endpoint that we could use - can you tell me if there is already an endpoint for this or if it would be possible to add this?

**Specification**
- Understand the AC behaviour and where the data sits when creating additional relationships (and also what entities are involved)
- Consider if/how this can be exposed in the properties API, bearing in mind that it needs to be a generic approach
- Discuss with platform owner this request from a product perspective before deciding how to proceed and where this should sit in the roadmap if it can be done

![image](https://user-images.githubusercontent.com/97969621/154305974-d7d9a7da-9b71-402c-890c-39ff57e80b71.png)

**Comment by plittlewood-rpt** [comment]
Hi @vikiecseri - we have reviewed this and looking at your requirements it looks specific to the additional contact type of "Management Company" - can you confirm if this is the case as it will allow us to ensure this gets implemented in the most appropriate way.

**Comment by plittlewood-rpt** [comment]
Hi @vikiecseri - if you can come back to us on the above I'd be grateful. We have scoped out the work for specifically supporting the Management Company relationship so just need to check that this will suit your use case here

**Comment by RWilcox-Reapit** [comment]
Hi @vikiecseri , We have scoped out the changes required for this but are just waiting on you to confirm the relationship you want. I'm going to close this ticket. Please raise another referencing this one if this is still a requirement.

Thanks
