### ISSUE TITLE
Safeguard schema against multiple schemas matching the same customer id

### ISSUE THREAD

**Issue by plittlewood-rpt** [reapit/foundations#6182]
**Describe the bug**
When setting up the analytics schema in #6041, the import job suddenly started incorrectly importing 2 billion rows. After investigation it transpired that there were two connectors running the same dataset under different schema names into Snowflake which caused the database joins to have a field day. I will pick this up with the SI team from a setup perspective, but we should see if there is a way to ensure we only process a single schema for each customer, even when multiple are found (or better still, omit it altogether)

**Specification**
- Confirm with SI the naming convention for all new customer databases that will be synchronised into Snowflake from Fivetran
- We can then update the mechanism which determines the schema to include in the DBT job to be more specific about the name of the schemas we are looking for (at the moment it is very loose "RPS_XXX" which resulted in multiple schemas being detected for the same customer)
- Change is in the DBT project

**Comment by HollyJoyPhillips** [comment]
PL & HP: Reviewed

**Comment by plittlewood-rpt** [comment]
Cannot do this until SFG and ANE are moved over to new naming convention

**Comment by plittlewood-rpt** [comment]
Fixed in #9269 without needing to migrate the two customers above. This can be closed
