### ISSUE TITLE
Unable to save details added to the Organisation screen

### ISSUE THREAD

**Issue by AshDeeming** [reapit/foundations#6187]
**Describe the bug**
When an admin goes to settings, they have the additional tabs Organisation & Billing. 

It was reported that a user was updating the fields in the Organisation tab however when clicking save, nothing happens,

**To Reproduce**
Steps to reproduce the behaviour eg:
1. Go to: https://developers.reapit.cloud/settings/organisation
2. Add additional information 
3. Click on 'save'
4. Nothing appears to happen. 
5. Refresh page (to check if data stored) but only original data remains.

**Comment by plittlewood-rpt** [comment]
@AshDeeming does this happen for any organisation or is it a specific one, and is it specific details?

**Comment by AshDeeming** [comment]
Hi @plittlewood-rpt, yesterday it was reported by a developer & i also tested updating existing details on the tab with no ability to save. I've also tested on a new account this morning & have the same issue of filling out the details but unable to save
