### ISSUE TITLE
Ability to resolve a user to a reapit customer

### ISSUE THREAD

**Issue by kiqbal-reapit** [reapit/foundations#619]
Background:
In our application, we have a front end that will utilise ReapIT Connect to authenticate a user.

A backend API that serves this front end with ReapIT data as well a few other services.

Issue:
When a user has been authenticated via Reapit Connect, the backend API will need 'reapit-customer' header for any requests made for the data for this particular user.  Currently, the API has no endpoints that allow me to resolve a given user to a particular customer.

**Comment by kiqbal-reapit** [comment]
I have spoken briefly with Pete regarding this issue, as well as Paul Neale.

**Comment by plittlewood-rpt** [comment]
Possibly linked to #608 depending on how/if it gets implemented

**Comment by cbryanreapit** [comment]
No longer relevant
