### ISSUE TITLE
Request could not be fulfilled

### ISSUE THREAD

**Issue by barrydixon** [reapit/foundations#6191]
Hi,

I am getting an error when accessing data from the live server:

statusCode: 401
dateTime: 2022-02-17T17:20:17Z
description: The request could not be fulfilled as the reapit customer specified by the provided credentials does not have the application installed.

We are trying to access data for Abode Property Management.

I am using Client ID: 1khrt8n8usnggor8ae1ejsqbfc

It works fine on the Sandbox but not live.

**Comment by AshDeeming** [comment]
Hi @barrydixon - from the description provided, the app will need to be Installed by the Client in order for you to access their dataset.

**Comment by barrydixon** [comment]
It is showing as installed by them on our App page.

**Comment by barrydixon** [comment]
![Screenshot 2022-02-18 at 10 23 32](https://user-images.githubusercontent.com/6463443/154664543-2d592dbf-9cb7-4e85-babd-45569ff10171.png)

**Comment by barrydixon** [comment]
Just tried it again and still the same error.

The access token is:

eyJraWQiOiJFXC9TcnVuTzVCR0xBMk1yT3phY2RjWFkwVVdqRVB1cVB5N3hIb1FWbnJGdz0iLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiIxa2hydDhuOHVzbmdnb3I4YWUxZWpzcWJmYyIsInRva2VuX3VzZSI6ImFjY2VzcyIsInNjb3BlIjoiYWdlbmN5Q2xvdWRcL2ltYWdlcy5yZWFkIGFnZW5jeUNsb3VkXC9wcm9wZXJ0aWVzLnJlYWQiLCJhdXRoX3RpbWUiOjE2NDUyMDQ0NzcsImlzcyI6Imh0dHBzOlwvXC9jb2duaXRvLWlkcC5ldS13ZXN0LTIuYW1hem9uYXdzLmNvbVwvZXUtd2VzdC0yX2VRN2RyZU56SiIsImV4cCI6MTY0NTIwODA3NywiaWF0IjoxNjQ1MjA0NDc3LCJ2ZXJzaW9uIjoyLCJqdGkiOiI3M2FlYmQzMy1mOGYzLTQ5YzYtYTcxZS1jYjI1YWQ3MzdhMjIiLCJjbGllbnRfaWQiOiIxa2hydDhuOHVzbmdnb3I4YWUxZWpzcWJmYyJ9.OVKZo_xRufu1gXGX3JfMDSewIroYpyNAw_IoUD-ryTGg-rObHEpEH6hjFmn_BkU9XsWkt_rxiWCIlBGL3ZtX3XNlyokwLuVpNOYKVC5Rw1vQS_QeOzCK5FrCJB84mr_79JpZqOA0c9QTbPzg-b0jjIvwN_70yAQx4L7nHlE2sMwwNSyUA5c8bV13cTFvP1T-T7rtX08K3OfQcPhk6S_h0jjGsNTs4CQ5uxRP6cf2P6ueVCY3iZ650i61YM5cCth0NCXKWo2M_RqfZcD1bqkrRFBuia1aVq29w2c2vvCfVZM87tditbsFZ25qSEvFRHKhWYFsjMnBar2a0HuEIUcemg

**Comment by plittlewood-rpt** [comment]
Hi @barrydixon  I've found the request and it looks like you are using the app client id as the reapit-customer header which is incorrect. YOu need to pass the id of the customer from the installations table (in your case ABD) as the reapit-customer header. If you can retry, you should find that works.

**Comment by barrydixon** [comment]
Thanks, that has fixed it. Thanks for your help.

**Comment by plittlewood-rpt** [comment]
Great - thanks for confirming.
