### ISSUE TITLE
Mapping additional AC/Desktop URL 

### ISSUE THREAD

**Issue by AshDeeming** [reapit/foundations#6192]
**Background context**
Following on from original GitHub req: https://github.com/reapit/foundations/issues/5936 & subsequent Jira ticket: https://reapit.atlassian.net/browse/AC-5258

Mapping of this new Desktop to URL Scheme to AC & Platform - Note below from JIRA Ticket;
_MarketplaceUrlProcessor class needs to be able to handle links of the form:

agencycloud://worksorders/{id} - this will launch a specific works order screen

agencycloud://worksorders?address={abc}&supplier={def}&status={ghi}&desc={jkl} - this will launch works order search screen and prepopulate any search criteria as specified.  As with other search urls it should also support the appId and appParam which will allow the selected item in the search to be sent back to an app._

**Specification**
- This is just a documentation piece for the Platform team

**Comment by HollyJoyPhillips** [comment]
@AshDeeming The work by the Desktop team has been completed, it will be available in Agency Cloud from version 12.145 onwards.
