### ISSUE TITLE
Unable to mark tenancy "End confirmed" checkbox

### ISSUE THREAD

**Issue by andytait** [reapit/foundations#6221]
**Summary**

We are investigating the potential to take some action on properties whenever a tenancy has its "End confirmed" checkbox checked.

To do so, we were looking to use a webhook which could detect when this has happened.

An issue we are having is that in our QA/staging environment the "End confirmed" checkbox is greyed out, with the message "Your security settings do not allow this field to be edited".

Can you confirm how we can have this checkbox enabled so we can test this process?

We can see that we have the following roles applied to our App user:

- Developer Edition Subscriber
- App Developer
- Developer Admin

**Detail and or supporting links and screenshots**

See video of behaviour: [simplescreenrecorder-2022-02-21_16.48.15.zip](https://github.com/reapit/foundations/files/8126015/simplescreenrecorder-2022-02-21_16.48.15.zip)

**Comment by plittlewood-rpt** [comment]
Hi @andytait - it should now be possible to alter the End Confirmed checkbox on the tenancy screen in AgencyCloud Developer Edition. If you are already logged in, you will need to log out and back in again to pick up the new configuration. Thanks
