### ISSUE TITLE
Reapit clients converted to AWS from Rackspace or new to AWS don't have the trigger queue/marshalling enabled

### ISSUE THREAD

**Issue by Speedway1** [reapit/foundations#6223]
Hi Support,

Reapit clients Harris Shields Scarborough do not have triggers firing despite the webhooks being set up.

This is a repeating problem with AWS / Foundations clients. Please see this ticket where an earlier client had the same problem: https://github.com/reapit/foundations/issues/5956﻿ 

The webhooks pipelines are failing to be enabled.

Please can you ensure that Harris Shields Scarborough and Harris Shields  Bridlington are enabled.

Can you also fix this bug so that the pipelines get enabled automatically? So far ever single client has has this problem. That's a 100% failure rate.

**Comment by Speedway1** [comment]
Steps to Replicate:
1) Take on a new client onto AWS
2) Register a webhook trigger on their account (e.g. appointment created).
3) Do the action to fire it (e.g. create an appointment)
4) Check if you received the webhook call on the receiving endpoint.

**Comment by plittlewood-rpt** [comment]
Hi @Speedway1 - thanks for raising this issue. It's another team that manage the enablement of the webhooks pipeline at the point of migration. I will raise this with them and try and find out what has happened.

**Comment by plittlewood-rpt** [comment]
@rpt-pneale please be advised of this ticket. I have logged SI-15602 for your team's review. Is there any way this can be dropped into the current sprint please?

**Comment by plittlewood-rpt** [comment]
Hi @Speedway1 - this has been resolved. Our infrastructure team are analysing what went wrong here
