### ISSUE TITLE
Applicant metadata field not set filter operator

### ISSUE THREAD

**Issue by jphgardner** [reapit/foundations#6229]
Hi,

I am currently working on a Reapit marketplace app that provides the ability to send an applicant to Mortgage Advice Bureau.

I'm having an issue with fetching applicants that either have a sentToMidas metadata field of false **_or are not set._**
![image](https://user-images.githubusercontent.com/226000/155703472-4257a587-a438-4058-8563-177f0ab5d4c8.png)

The problem is that applicants with empty metadata are not covered by the $ne true filter above.

Ideally, my app should cover the two scenarios of sent Applicants and unsent applicants.

**Comment by jphgardner** [comment]
Just tried testing this again this morning but I get the same issue, the applicants with empty metadata do not get added to the response

**Comment by skhaitan** [comment]
any solution provided to this?
