### ISSUE TITLE
Patching appointment with 'null' attendee does not update it

### ISSUE THREAD

**Issue by bisoh** [reapit/foundations#6233]
**Describe the bug**
I have created an appointment (MKT2200748) with an applicant. I tried removing the applicant by patching the appointment with a 'null' attendee but the applicant was not removed even tho the API returned a 204 response

**To Reproduce**
Steps to reproduce the behaviour:
1. Create an appointment with an applicant on RPS
2. Perform a patch '`{reapitApiUrl}/appointments/{id}`' with the body
```
{
  "attendee": null
}
```
4. Check the appointment on the API - attendee would still be populated. This is also visible on RPS

**Expected behaviour**
The applicant should be removed.

**Device (please complete the following information for web issues):**
 - Device: PC
 - OS: Win10
 - RPS version 12.139.2-Dev

**Specification**
- Service: Reapit.Services.Appointments
- Update the `PATCH /appointment/{id}` handler to allow a blank string to be passed as the attendee id:

```
  "attendee": {
    "id": "",
    "type": "applicant",
    "confirmed": false
  },
```

The behaviour here should be to clear the attendee completed (clear the tableCode and extra.yCnt fields)
- May need to adjust existing validation rules
- Ensure that commentary model is updated to make this behaviour clear
- Ensure tests are added for this scenario

**Comment by rochellelevy** [comment]
Thanks for getting this in the current sprint Holly!

**Comment by bisoh** [comment]
Hi, has this been deployed? I just ran a test on sandbox and setting the patching the appointment and setting attendee to null did not clear it from the appointment.
Thanks

**Comment by RWilcox-Reapit** [comment]
Hi @bisoh, It has been deployed to production. 
To clear an attendee you'll need to set the attendee.id to an empty string: 
```
  "attendee": {
    "id": "",
    "type": "applicant",
    "confirmed": false
  },
```

Thanks

**Comment by bisoh** [comment]
Thanks @RWilcox-Reapit. Tried it and it worked.
