### ISSUE TITLE
Applicant metadata field not set filter operator

### ISSUE THREAD

**Issue by jphgardner** [reapit/foundations#6246]
Hi,

I opened a ticket last Friday with a problem I am having related to applicant metadata and the filters.
#6229 

Seems it has been closed with a commit to a React Component but no response from yourselves.

I have tested this morning and I am still experiencing the same issue.

Could I please have some support?

Thanks

**Comment by plittlewood-rpt** [comment]
Hi @jphgardner - sorry that this got closed, it looks like a typo in a commit message inadvertently closed it in error. We have a refinement session today and will review and come back to you

**Comment by plittlewood-rpt** [comment]
Hi @jphgardner - please can you provide some further information about your use case here and why you want to run this kind of search operation?

**Comment by mabcj** [comment]
So I see the issue here.

So say you have metadata. And someone has a lot of existing data. You then start adding a metadata item, like a boolean, for "done some action".

You probably then need a filter to exclude this item or show those that have been actioned (which will have it set to true).

The current combination of filters do not seem to react to the fact that metadata item does not exist (on existing data) or is essentially NULL (existing data so is not there and wont be set to false).

I cannot see any of the current filters allow data to come back if not set (existing data).

I had a play with workarounds with what is available and none seem to be able to enable this type of functionality?

**Comment by jphgardner** [comment]
So we are using the applicant's endpoint, basically, in our app we want to get 2 sets of applicants based on the metadata property "sentToMidas". The applicants that are already sent and have that property set to true. And the applicants that either have the property set as false or are simply not set in their metadata.

![image](https://user-images.githubusercontent.com/226000/156742520-97ba26d3-8fc3-4e76-9db5-2f4961a2476c.png)

The problem we are having is there is no way to add a filter where the metadata.sentToMidas $ne true or the metadata.sentToMidas does not exist.

the query for $ne true does not return the applicants that do not have that metadata property.

**Comment by plittlewood** [comment]
Hi @jphgardner - the metadata filter mechanism is designed to operate against metadata that has been set. As this is stored outside the primary AgencyCloud database it's technically very difficult to achieve what you are wanting to do and impossible to do in a performant way, particularly on large datasets, as we'd have to grab all entities from a particular dataset and churn through all metadata to work out which entities didn't have it set. Subsequently to do what you are wanting would need to be something managed by yourself in your app. You could upon installation of an app, page through customer data setting up metadata flags for each record, then use webhooks to capture subsequently added records to do the same thing (ie set it to false on every record).

**Comment by mabcj** [comment]
I understand what you are saying here about that data being stored separately.

And you may not want to change existing operators to support it as they become none performant.

You are replicating what are some basic database operators.

Is it not possible to have a ins (Is Not Set) operator?

Agencies could have thousands of existing records so going through and adding metadata to each of these is also probably not going to be friendly to your data store either. This seems  to me a pretty common use case?

**Comment by mabcj** [comment]
Plus the API is rate limited. And if several thousand existing records would have to throttle it to stop it getting perimeter throttled.

I assume this 20/s is across all installations of the app and by doing this cursor trawl could end up throttling other users of the application too by hitting API rate limiting. 

What am saying is a filter for is not set, does not exist, is null in metadata as in a store filter is a better approach than what seems like a awkward hack to me?

**Comment by plittlewood-rpt** [comment]
Hi @mabcj - thanks for coming back to me. Unfortunately this isn't something we can support right now. The filter mechanism will only work against metadata that has been set.

**Comment by mabcj** [comment]
Oh dear, I find that very disappointing indeed, as it seems a pre-requisite for adding an app to someone who already has lots of existing data that do not want to retrospectively flood with metadata as by it not being there is a flag in itself :(

**Comment by HollyJoyPhillips** [comment]
@mabcj Unfortunately, as this feature request is not technically possible, we will close the ticket.
