### ISSUE TITLE
Additional type required - Woodland

### ISSUE THREAD

**Issue by gfyans** [reapit/foundations#6255]
Bell Ingram have requested a new type of property - Woodland - be added to their account.

As far as I know, this isn't available to them to mark properties as Woodland, and I don't see it in the API response in either `/properties` or `/properties/[property-id]`.

**Comment by AshDeeming** [comment]
Hi @gfyans 
Please can you confirm if the 'Departments' endpoint has been called against the client database - this will return the available property types i.e; 
![image](https://user-images.githubusercontent.com/61687775/156153605-d10b2c68-6f4b-450b-aed1-bedab8621a14.png)

**Comment by gfyans** [comment]
Hi Ash,

These are the options I get when I call the departments endpoint:

[image: image.png]

**Comment by AshDeeming** [comment]
Hi @gfyans - Please can you confirm the additional type has been added to the clients AgencyCloud system & can be selected by users?

**Comment by gfyans** [comment]
I don't have access to AgencyCloud, but the client has confirmed they can
see "Forestry/Woodland".

**Comment by AshDeeming** [comment]
Hi @gfyans 
You may need to check the other departments by ID, the client has, for example you may be calling 'General/Residential' & the attribute you are looking for be under the 'Commercial' Attributes.

**Comment by JoWiseman** [comment]
Hi @gfyans  and @AshDeeming I can confirm that on the Agency Cloud Forestry/Woodland is under the commercial department. Therefore @gfyans having spoken to Adam you should be able to see this through the commercial department.  If not please let @AshDeeming know so that we can have this resolved.
