### ISSUE TITLE
to find out deleted properties (ids)

### ISSUE THREAD

**Issue by erhan-mv** [reapit/foundations#6257]
I'm using the parameters "modifiedFrom or createdFrom" in query ( while calling "/properties/" ) in order to pull only "inserted or updated" properties. Because, there's no need to pull all the unchanged data every day. 

But if I do not pull all the data every day, then I cannot know which properties are deleted/removed daily. Is there a way to pull deleted properties ids for a specific date interval?

Thanks in advance

**Comment by plittlewood-rpt** [comment]
Hi @erhan-mv - it is not possible to surface deleted records directly from the API endpoints. Using webhooks for this purpose would be our recommended approach. You can view [documentation about webhooks here](https://foundations-documentation.reapit.cloud/api/webhooks)
