### ISSUE TITLE
property type list

### ISSUE THREAD

**Issue by erhan-mv** [reapit/foundations#6260]
The "model" content in https://developers.reapit.cloud/swagger refers to the department page as 
https://foundations-documentation.reapit.cloud/platform-glossary#department

And all possible values for property types aren't listed there, either.

#6256

**Comment by AshDeeming** [comment]
Hi @erhan-mv 
Please see the Departments endpoint, on the swagger page, which shows this breakdown & neds to be called to check which are applicable to the relevant client(s)
![image](https://user-images.githubusercontent.com/61687775/156144827-3bab9746-6970-490d-a0cc-00bb50bbf498.png)

**Comment by erhan-mv** [comment]
Thank you very much @AshDeeming
