### ISSUE TITLE
Clarification on descriptions

### ISSUE THREAD

**Issue by propertyhive** [reapit/foundations#6264]
In the /properties/ endpoint we seem to get a few text/description related fields:

strapline
description
longDescription
summary

In the UI you also have a few text based fields:

<img width="480" alt="OyHjQa5NzzxVm6Fs7silh1RmywYnXkVJ" src="https://user-images.githubusercontent.com/13717200/156199941-3061bfc8-2f95-455f-9f6c-0b9b3f50830e.png">

Are you able to confirm which fields in the UI relates to which fields in the API response? Had a mutual client saying that they're filling in the Internet Text and Location fields but they're not coming through in the API and just want to know which fields I should be looking at for this information.

Many thanks,
Steve

**Comment by AshDeeming** [comment]
Hi @propertyhive 
The names of these Extra Descriptions may vary per client in AgencyCloud based on their requirements however they are available via the Properties Endpoint under ; extrasField

Please see related ticket; https://github.com/reapit/foundations/issues/5284

**Comment by propertyhive** [comment]
Thanks @AshDeeming.

I can see that to include this information you need to pass it through in the extrasFields parameter of a call to /properties/, however how do I know what these fields are called.

In the related ticked that you linked to it references a field in the UI called 'Standard Description' but the field name passed through in the query string to get this field is `pStdDesc`. How would one get the ID of the description field to use in the querystring?

Thanks,
Steve

**Comment by AshDeeming** [comment]
Hi @propertyhive 
These  fields would need exposing (in a read-only form) - Please use the below template to request this access: https://github.com/reapit/foundations/issues/new?assignees=&labels=back-end%2C+needs-triage&template=extras_field.md&title=

If you are unaware of the field names - Please confirm which customer you are working on behalf of and we can obtain on your behalf.

**Comment by propertyhive** [comment]
Thanks. Have submitted request using link provided
