### ISSUE TITLE
Research use of SES configuration sets to better track email bounces

### ISSUE THREAD

**Issue by plittlewood-rpt** [reapit/foundations#6273]
**Background context**
We have recently undertaken some work to move our Cognito email capabilities over to SES from the built-in Cognito emailer. This was done because of the high bounce rate which was exceeding AWS's fair rate policies. The bounce rate stll continues to be high from emails being sent from other internal services which were already using SES. We should look at using configuration sets which can be applied to SES environments so we can better track emails that are bouncing so we have better visibility of what is going on (all we can see by default is the bounce rate as a percentage of the overall email send rate)

**Specification**
- Read up on [AWS SES Configuration Sets](https://docs.aws.amazon.com/ses/latest/dg/using-configuration-sets.html)
- Consider if and how it can be implemented in Platform so we can log email metrics, preferably out to our ELK stack. Assuming this is possible, we should add something to our Kibana dashboard so we can set up automatic alerting policies in appropriate scenarios
- This is a research ticket only with a view to architecting an approach to implementing the above which will be handled with separate tickets. Whoever does the research should come back to the group with a proposal for further discussion

**Comment by HollyJoyPhillips** [comment]
PL & HP: Reviewed

**Comment by plittlewood-rpt** [comment]
Moved up to Near Term as we need to get better visibility of this as AWS keep contacting us regarding bounce rate

**Comment by RWilcox-Reapit** [comment]
Closing as investigation on approach has been done, subsequent tickets have been raised and work has been started
