### ISSUE TITLE
Add 'Delete' option on the MM app - Office Groups

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#6278]
**Summary**: We need to provide the option to allow users to delete office groups

**Task:** Add a ‘Delete’ option to allow a user to delete a group. Must check on ‘Active’ installations first and if true, cannot delete. 

**Route**: /offices/groups

- **Active Installations**
CTA Delete
Check active installations – if true, render the following: 
Title: Unable to Delete
Unfortunately, as there are active app installations associated to this group, the group cannot be deleted. Please uninstall any installations associated to this group. 
To uninstall, please visit https://marketplace-management.reapit.cloud/marketplace-apps 
CTA Close

- **No Active Installations**
CTA Delete 
Check active installations – if false, render the following: 
Confirm Office Group Deletion
Are you sure you want to delete this office group? 
CTA Close
CTA Procced/Delete (/Organisations/{id}/officeGroups/{groupId}) 

- Present notification to confirm successful deletion.

**Comment by HollyJoyPhillips** [comment]
@willmcvay, just a couple of points: 

1. Can you change the last line on the modal to: 

To uninstall, please visit the AppMarket page. 

Should still link to /marketplace-apps

2. When making a request to delete an office group, we need to include the ‘Reapit Customer’ header in the request. 

To replicate issue: 
Login as sales to MM app on dev
Switch to Reapit Ltd 1
Attempt to delete an office group

3. When deleting an office group with no installations, the modal about installations is incorrectly appearing, although it does actually delete the group and shows a confirmation notification . 

The modal should only show, if there are any active installations.

**Comment by willmcvay** [comment]
@HollyJoyPhillips I have a PR for issue 1, not sure about the other 2 though.

2. We pass the org id so you don't pass the Reapit Customer header - that's only a thing for the Offices endpoint
3. Can't replicate, seems to be working fine for me. Can I have some more info please!

**Comment by HollyJoyPhillips** [comment]
@willmcvay Re point 2, the request came from the BE team, we need to pass the reapit customer header too for deleting groups. 

Please see video for point 3: https://www.dropbox.com/s/cubksb22o997hnv/Office%20Group%20Delete.mp4?dl=0

To replicate: 
Login as sales 
Create a new office group 
Delete the office group
Confirmation message correctly appears but so does the uninstall modal
