### ISSUE TITLE
Marketplace Elements menu item results in page not found error

### ISSUE THREAD

**Issue by kiqbal-reapit** [reapit/foundations#628]
When clicking the elements menu item from the market place side navigation bar, it results in a "Page Not Found" error.

**Comment by willmcvay** [comment]
Confirmed https://marketplace.reapit.cloud/developer/elements

**Comment by willmcvay** [comment]
Looks like this is because the URL to elements is incorrect in Config Manager

**Comment by willmcvay** [comment]
@kiqbal-reapit Thanks for reporting this - was fixed a couple of days ago on prod. FYI was a config issue causing a dead link.
