### ISSUE TITLE
Config manager should not reference local config

### ISSUE THREAD

**Issue by willmcvay** [reapit/foundations#629]
The current config manager update function makes it too easy to override the remote config. 

Currently;
- Fetches remote config, copies local config, then merges and pushes. This means a stale local config can override a newer remote.

Should;
- Fetch remote config, user should make their changes manually to this file and push. 

Or;
- Better still, diff changes and give a command prompt for each change asking the user to confirm each one is correct. This should prevent accidental overrides.

**Comment by tanphamhaiduong** [comment]
I think we should separate local, production and, dev environment to 3 secrets management and we should update on AWS instead of run CLI
