### ISSUE TITLE
Changing App description and feature image

### ISSUE THREAD

**Issue by WeCOMPLETE** [reapit/foundations#6310]
Hi,

We would like to change the feature image and description of our APP. 

My question - while the new changes are pending approval, I assume our exiting version will still be live in APP market for clients to install it or the current version will be pulled down?

Rgds
Suraj

**Comment by AshDeeming** [comment]
Hi Suraj,

Only changes to an apps permissions will require the app to to be uninstalled & de-listed from the AppMarket, allowing Client/Users to install & accept the new permissions. 

The above changes, i.e. Images and Description, can be submitted for approval without affecting the install(s)

**Comment by WeCOMPLETE** [comment]
HI Ash,

We have made the changes and submitted the app.

Please reapprove it.

Kind regards
Suraj

**Comment by AshDeeming** [comment]
Thanks @WeCOMPLETE
