### ISSUE TITLE
API /appointments endpoint unauthorized with good request

### ISSUE THREAD

**Issue by Filip5991** [reapit/foundations#6314]
Today (07.03) at 11 GMT a lot of our requests to the /appointments endpoint of the API were rejected with a 401 Unauthorized response. This is an app that runs daily, yesterday's request to the same endpoint with the same credentials was successful, and the same goes for the request after 11 (around 1:00 GMT).
No credentials/tokens were changed between the requests so I was wondering if there was possibly an issue with the API (or the appointments endpoint) around 11?

**Comment by Filip5991** [comment]
It is an integration app (not launched through the CRM) called Acaboom.
The access token is generated from the client id and secret, so not something that expires and the customer token used when making a request is one from the list of clients that have installed the app. One example would be 'WEB'.
At 11 GMT multiple requests to the /appointments endpoint for different customers all returned 401.
Please let me know if I need to supply anything else :)

**Comment by plittlewood-rpt** [comment]
Hi @Filip5991 - thanks for letting me know. Is this the first time you have experienced this problem? It looks like there may have been a database server failure at 11:00:16 yesterday (07/03) which will have initiated an automatic fail-over which could have made the record of installations unavailable for a very short period of time so when your request came in, the authorization flow would have failed thinking the app wasn't installed. We'll look into this further to see what caused the failover activity

**Comment by Filip5991** [comment]
Hi @plittlewood-rpt , I don't check our logs daily, but from what I've seen so far *i think* it was the first time. I'm only reporting it because our job runs daily and no changes were added in-between, so I wasn't sure why the authorization would stop, and then start working again. Thank you anyway, if I spot something similar I'll let you know :)

**Comment by plittlewood-rpt** [comment]
Thanks - we've actually got a ticket in this week's sprint to look at an issue with the same server (#6280) so I will close this ticket and you're welcome to follow the linked ticket.
