### ISSUE TITLE
URGENT: New Applicants are getting unexpected/uneditable attributes added to Reapit

### ISSUE THREAD

**Issue by eazynow** [reapit/foundations#6316]
**Describe the bug**
Since Friday, a number of our clients have reported that new Applicant's created with POST have got additional attributes like "Double Bedrooms" in Reapit itself. And furthermore they are unable to edit these attributes.

We have not changed the JSON payload to POST /applicants so it seems that something further backend in Reapit is setting this.

**THIS IS STOPPING PROPERTY MATCHING FROM WORKING**

As I said, this is not isolated to one client.

Client No.1:
![Screenshot 2022-03-07 at 15 46 52](https://user-images.githubusercontent.com/612686/157072588-1115b130-3f09-4812-9131-0e62caa97abb.png)

Client No.2:
> All the applicant leads I now suck through into reapit are automatically putting 1 double bedroom on the all the applicants file, this criteria doesn't exist and I don't know how to erase from our system? thanks

Client 3:
![Screenshot 2022-03-07 at 16 14 03](https://user-images.githubusercontent.com/612686/157073249-251f27ed-855b-4a8c-8143-87feb27f1538.png)

**To Reproduce**
1. POST a new applicant - here is an example payload
```
{
    "marketingMode": "buying",
    "active": true,
    "notes": "Area Lead 2022-03-07 10:29:44\nAm I able to view this property this upcoming week?",
    "bedroomsMin": 1,
    "receptionsMin": 0,
    "bathroomsMin": 0,
    "nextCall": "2022-03-14",
    "departmentId": "G",
    "officeIds":
    [
        "AAA"
    ],
    "negotiatorIds":
    [
        "AAA"
    ],
    "related":
    [
        {
            "associatedId": "AAA",
            "associatedType": "contact"
        }
    ],
    "metadata":
    {
        "areaLeadId": "aaaaaaaaa-caab-4d75-b605-aaaaaaaa",
        "areaPropertyId": "aaaaaaaaa-45a3-4b64-a2b9-aaaaaaaaa"
    },
    "buying":
    {
        "priceFrom": 1,
        "priceTo": 325000
    },
    "source":
    {
        "id": "ADV001",
        "type": "source"
    }
}
```
2. In Reapit:
![Screenshot 2022-03-07 at 16 11 33](https://user-images.githubusercontent.com/612686/157073436-873fce1e-efb1-4818-ba5e-57366f76cb5b.png)

**Comment by plittlewood-rpt** [comment]
hi @eazynow - can you confirm which customers (or just one) as an example please?

**Comment by eazynow** [comment]
@plittlewood-rpt Ryder & Dutton, Keatons, Sarah Mains, Oasis

**Comment by eazynow** [comment]
Thanks @plittlewood-rpt

**Comment by plittlewood-rpt** [comment]
We will be pushing a patch out to resolve this shortly and will correct any data in the new records that have been added since Friday

**Comment by eazynow** [comment]
@plittlewood-rpt hi - any news on when this will be resolved? We've had another client - Alexander & Co report it also now.

**Comment by plittlewood-rpt** [comment]
Hi @eazynow - we have just pushed the patch out to resolve this issue. We will be going round the affected datasets and cleaning up the applicants that have been added since Friday in due course

**Comment by plittlewood-rpt** [comment]
@eazynow data for the customers you have mentioned above has now been corrected and I can confirm those applicants now match as intended. There are a few other customers I need to get through but that shouldn't take much longer.

**Comment by plittlewood-rpt** [comment]
@eazynow All affected customer data has now been rectified.

**Comment by eazynow** [comment]
Thanks for the update @plittlewood-rpt - I'll let our clients know

**Comment by plittlewood-rpt** [comment]
No problem. Some of the customers have been in touch with our service desk directly so we may already have fed back to them also.
