### ISSUE TITLE
Can't get areaId in property api call

### ISSUE THREAD

**Issue by sanjayisg** [reapit/foundations#6327]
Hi,

I am calling property api like https://platform.reapit.cloud/properties/xxxxxxx

In which I am getting all property data but areaId column always get blank for almost all properties.

My Customer ID is BAR for your reference.

Please can you suggest? why this column is blank?

Thanks,

Sanjay Gupta

**Comment by sanjayisg** [comment]
Hi,

Is there anyone looking my concern?

Thanks,

Sanjay Gupta

**Comment by plittlewood-rpt** [comment]
@sanjayisg you logged this ticket at 5.33pm yesterday and our office hours are typically 9am-5.30pm. Details of our development processes [can be found here](https://foundations-documentation.reapit.cloud/dev-requests). We will review this as soon as we can. Thanks

**Comment by AshDeeming** [comment]
Hi @sanjayisg 
Apologies for the delay - please can you confirm the app name & that it is installed by the mentioned client?

**Comment by sanjayisg** [comment]
Hi @AshDeeming ,

App name is: Benham and Reeves Website Feeder
Customer ID: BAR

Thanks,

Sanjay Gupta

**Comment by plittlewood-rpt** [comment]
Hi @sanjayisg - this customer uses a feature in AgencyCloud called Lat/Long matching which means all their property and applicants are matched based on property coordinates (latitude/longitude). When this feature is enabled, the areaId does not get populated, you would need to use the address coordinates to ascertain the geographic location of the property
