### ISSUE TITLE
New Instructions and mappings for property types

### ISSUE THREAD

**Issue by MSB89** [reapit/foundations#6328]
We are switching over from the old SOAP to new Foundations API, we have found properties with a status of New Instruction. This does not appear in our legacy code so looks like it's coming over from Reapit. How are new instructions defined, I can't find anything on this?

We also have the property types detailed per below

House
Farm | Retail
Flat / Apartment
Estate
Office
Estate
Industrial
Land
Land / Development
Development Opportunity
Restaurant
Bungalow
Licensed Premesis 
New Homes
Hotel / Guesthouse 
Farm
Warehouse / Distribution 
Small Holding
Investment 
Building plot
Catering 
Care Home
Holiday Lets

However, I note that there is a discrepancy in naming conventions between our records and the data in Reait, for example:

Flat / Apartment: flatApartment
Office: office
Development Opportunity: developmentPlot

Please can you provide an explicit mapping of Reapit data values to each of the provided property types detailed above, in order to correctly allocate the correct type to each imported property?

**Comment by AshDeeming** [comment]
Hi @MSB89 
Please can you confirm if the 'Departments' endpoint has been called against the client database - this will return the available property types i.e;
![image](https://user-images.githubusercontent.com/61687775/157513799-918490df-4fd9-461c-b823-5f1a4db3be6f.png)
