### ISSUE TITLE
Properties not coming into Property Hive on website

### ISSUE THREAD

**Issue by scruffmcduff** [reapit/foundations#6329]
Hi support

We are struggling with hooking up Reapit Foundations to a website that we are currently building.
We have installed the Property Hive APP on Reapit Cloud for the customer.
It looks as though the import is connecting, but It's almost like there are no properties coming through
See screenshot of log https://share.getcloudapp.com/4guZvqkB

See screenshot of import details.
https://share.getcloudapp.com/Blude8Xz

See details below for the agent.
Estate Agency Name: Bancroft Property
Reapit Customer ID: ASZ
Billing Email Address: [andrea.vickers@bancroftproperty.co.uk]

I hasked Property Hive to look at this and they can confirm that they are also not seeing any properties coming through

Is there something that Bancroft Property needs to do to enable the feed through? Can you check this for us?
FYI we are building the website under a development environment (with a dev URL). Would this make any difference?
Website in development is at https://wordpress-668817-2316591.cloudwaysapps.com/ (login to dev site using U=iamdev P=letmein )
I look forward to hearing from you

Kind regards

**Specification**
- Tunnel to production service and request data for the customer mentioned
- If data is returned, work with app developer to debug the problem via this ticket

**Comment by AshDeeming** [comment]
Hi @scruffmcduff 

In order to investigate this, we will require the App developer to create a ticket with examples of the issue. 

Thanks & regards,
Ash

**Comment by propertyhive** [comment]
@AshDeeming App developer here. I'm afraid I don't have examples as we're just the tool used to import data and don't get involved in the setup or have any correspondence with the end user. I would've thought you could pick any on market property as an example though seeing as nothing is coming through.

It's the same tool used by 12 other agents so suspect maybe they're not ticking a box or something in the UI. I'm not familiar with the Reapit UI I'm afraid.

Let me know if you require any further information,
Steve

**Comment by HSnipe-RPT** [comment]
Hello @scruffmcduff,

We've had a look into this, we can see that the Customer Bancroft Property does have Property Hive installed, we can also see that when logged in as that user the endpoint is returning the correct data.

Can you give us some more information about the request you're making as well as how you are authenticating?

Kind regards,
Harry

**Comment by propertyhive** [comment]
Just to confirm for the purposes of this ticket, the properties now seem to be coming through.

**Comment by HSnipe-RPT** [comment]
Excellent, are you happy for me to close it?

**Comment by propertyhive** [comment]
Yes, Thanks.
