### ISSUE TITLE
Staff names / profiles

### ISSUE THREAD

**Issue by madebyparent** [reapit/foundations#6330]
Are staff names / titles / profiles stored anywhere in Reapit and how can we access them from the feed / API?

Thanks!

**Comment by AshDeeming** [comment]
Hi @madebyparent 
Please see the Negotiators Endpoint via the swagger page.

**Comment by madebyparent** [comment]
Sorry, where's that?

**Comment by AshDeeming** [comment]
https://developers.reapit.cloud/swagger & then Scroll down to Negotiators

**Comment by madebyparent** [comment]
Thanks, does that return;

Name
job role
image

?

**Comment by AshDeeming** [comment]
Hi @madebyparent 

Values are available in the example response or model on the previously mentioned page, example below;
![image](https://user-images.githubusercontent.com/61687775/157458640-b5c89f98-dcfa-428e-936d-47d305cf8815.png)

**Comment by madebyparent** [comment]
Thanks
