### ISSUE TITLE
Extra Fields Request for LUR

### ISSUE THREAD

**Issue by propertyhive** [reapit/foundations#6332]
Customer: Lurot Brand (LUR)

Fields Needed: Internet Text, Location

<img width="480" alt="156199941-3061bfc8-2f95-455f-9f6c-0b9b3f50830e" src="https://user-images.githubusercontent.com/13717200/157480415-f98605b0-25f9-4bd4-8b6d-5a530fc39130.png">

Reason: For displaying on website 

**Specification**
- Identify the semi structured field names for Text and Location from the customer system
- Update the customer configuration with the new fields

**Comment by HSnipe-RPT** [comment]
Hi
Please see below the extrasField query string parameter values you can now include with your request to retrieve the additional information
Long Description -> pLongDesc
URL Test -> pURLTest
As an example, to return all the above fields (where present), you would append the following to your GET request URI:
?extrasField=pLongDesc&extrasField=pURLTest
Any problems please let me know.
Thanks

**Comment by propertyhive** [comment]
@HSnipe-RPT Thanks. Can you confirm it's pURLTest and not pURLText ? 

There was also a request for the Strapline Description field earlier in this ticket if you can confirm the field name for that also.

Thanks,
Steve

**Comment by HSnipe-RPT** [comment]
It is pURLText not pURLTest that was a typo

**Comment by HSnipe-RPT** [comment]
Here is the additional field we missed:
Strapline Descriptor -> pDescriptor
Thanks

**Comment by sam98brown** [comment]
Hi there. I'm working on this project along with @propertyhive .

We need the "Location" description to be made available on import - can you get this field imported please?
I tried adding "pLocation" to my URL parameters but no joy.
