### ISSUE TITLE
Enhance the properties endpoint to display ManagementCompanyIds

### ISSUE THREAD

**Issue by RWilcox-Reapit** [reapit/foundations#6337]
**Background context**
Users are able to store a management company against additional contacts in AC. 
Add functionality to retrieve and display the 'ManagementCompanyIds' alongside the 'PropertyManagerId'

**Specification**
- Add new `managementCompanyIds` array property to `PropertyLettingModel` to display id(s) of the related management companies
- Add new item to `_links` collection to provide relative link to companies endpoint

- Update payload (irrelevant data redacted for brevity)
```
{
	"lettings": {
		"managementCompanyIds": [
			"ABC123456778",
			"ABC123456779"
		]
	},
	"_links": {
		"managementCompanies": "/companies?id=ABC123456778&id=ABC123456779"
	}
}
```
- Data is stored against the ADDSTORE table typefrom = 'prp', typeto = 'add', CntType = 'Management Company' and there may be multiple entries per property
- Consider performance on the GET endpoint. It is probably more appropriate to fetch these records and process them separate to the initial query that gets the paged data, rather than using another `.Include()` on the query
- This mechanism should be read-only at this point
- Ensure this is tested against a large dataset to assess performance impact. If there is any doubt about performance this should be discussed prior to work being merged

**Comment by plittlewood-rpt** [comment]
Carrying to current sprint as some PR comments outstanding
