### ISSUE TITLE
Creating appointments in summer at midnight returns incorrect start datetime

### ISSUE THREAD

**Issue by bisoh** [reapit/foundations#6339]
**Describe the bug**
If you create an appointment that starts at midnight during summer using RPS, the webhook notification will contain an incorrect start datetime. This will also be visible on the API. This fails on our systems because the dates do not make sense.

**Steps to reproduce the behaviour:**
1.On RPS go to July
2. Create a new appointment that starts at midnight and ends at 00:30
3. Save
4. Either check the notification sent on the webhook or use the api to find that appointment.
5. The start end datetimes would be 
```
"start": "2021-07-18",
"end": "2021-07-17T23:30:00Z",
```
Another scenario would be to set the appointment times from midnight -> 1 am. The result then would look like 
```
    "start": "2021-07-11",
    "end": "2021-07-11T00:00:00Z",
```

**Expected behaviour**
Start date should be in UTC. In both scenarios it should be the previous day at 23:00

**Screenshots**
Including a screenshot of an appointment that I created with this issue
![image](https://user-images.githubusercontent.com/3708220/157702804-9ad43534-e16a-437f-872a-78c958467495.png)
![image](https://user-images.githubusercontent.com/3708220/157707053-ce56d945-83e8-40ae-93b1-2be9b105346c.png)

**Device (please complete the following information for web issues):**
 - Device: PC
 - OS: win 10
 - RPS 12.139.2

**Additional context**
It seems to work correctly for summer times that are not midnight and works fine for winter.

**Comment by rochellelevy** [comment]
@HollyJoyPhillips could this be a candidate to be fixed in next sprint please? It affects a feature we're building and in sprint

**Comment by plittlewood-rpt** [comment]
Hi @rochellelevy - I've pulled this into the current sprint. Depending on what we find when we start debugging the issue it might mean a fix isn't necessarily complete this week, but we'll keep you posted on the ticket
