### ISSUE TITLE
GraphQl getProperties doesn't seem to allow the REST API's officeId filter

### ISSUE THREAD

**Issue by whanno-lsl** [reapit/foundations#6344]
**Describe the bug**
The REST API allows us to GET properties for one or more officeId, but the GraphQL interface doesn't seem to allow use of officeId as a filter.

**To Reproduce**
I'm assuming that the following GraphQL query should work, but it doesn't like officeId:
{
  GetProperties(officeId: "MKT", pageSize: 100) {
    totalCount
  }
}

**Expected behaviour**
Be able to filter GraphQL properties using officeId like we can via the REST endpoint.

**Comment by willmcvay** [comment]
@whanno-lsl Thanks for Reporting, agreed, we need to add this filter.

FYI, the GraphQL schema is behind the REST API in a number of areas. We are working on a 1:1 mapping for a full release later this year - see: https://github.com/reapit/foundations/milestone/100 There are a few additional tickets to add here and although currently scheduled for the end of April but it may be pushed back by a month or so subject to change.

While the service is still in Beta, if you need the full feature set of the REST API, we would advice sticking with the main Foundations API for now.

**Comment by whanno-lsl** [comment]
Ok cheers for the info.
