### ISSUE TITLE
Trading Standards Requirements for Council Tax and Tenure

### ISSUE THREAD

**Issue by NBareham** [reapit/foundations#6364]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by NBareham** [comment]
There are trading standards changes that are coming in over the next few months with mandatory information required when selling / letting houses, the first of which is the following and is required by **1st May 2022**:

**Lettings**
- Council tax band
- Local Authority

**Sales**
- Council tax band _(already available)_
- Local Authority
- Ground rent for leasehold properties
- Maintenance charges for leasehold properties
- Leasehold length _(TenureEnd exists in Webservice so we think we can use this)_

We need to be able to easily display this information to potential buyers and tenants on the Your Move and Reeds Rains websites. Therefore we would like the above available within the Foundations web service. See attached for where we believe our staff will complete this information in the front end. 

[Council Tax & Tenure - 10.03.22.pptx](https://github.com/reapit/foundations/files/8244156/Council.Tax.Tenure.-.10.03.22.pptx)

**Comment by plittlewood-rpt** [comment]
Hi @NBareham 

Thanks for reaching out. As you've noted, councilTax is already available for both sales and lettings properties

Tenure expiry is also already available, and you can find this information in the selling.tenure model object ie:

```
    "tenure": {
      "type": "leasehold",
      "expiry": "2019-05-01"
    },
```

Local authority, ground rent and maintenance charges are currently not presented in the output from the properties API. We'll split this out into separate tickets and link back to this one so you can track them individually

Thanks

**Comment by plittlewood-rpt** [comment]
Hi @NBareham - this ticket has now been split into individual items which can be tracked at https://github.com/reapit/foundations/milestone/131. Please feel free to subscribe to all/any of these issues are you see appropriate as this ticket will now be closed
