### ISSUE TITLE
Appointment with empty officeIds array

### ISSUE THREAD

**Issue by bisoh** [reapit/foundations#6365]
**Describe the bug**
Our system made a call to the appointments/{id} call and received an appointment with an empty officesId array. My understanding is that it should have atleast the negotiator's office in there. The json from the request can be found here with sensitive data removed

[appointmentWithNoOffice-min.txt](https://github.com/reapit/foundations/files/8245504/appointmentWithNoOffice-min.txt)

**To Reproduce**
do not know how to reproduce this issue unfortunately

**Expected behaviour**
The `officesId` array to have atleast one value in there

**Specification**
- Service: Reapit.Services.Appointments
- Goal of ticket is to try ascertain whether this is a platform problem or not. If not, divert to correct department
- Check whether it is possible to create a negotiator with no office code, and check what happens when a negotiator id that doesn't exist is used on an appointment (does the appointments service set the officeId to blank/null). General troubleshooting from there

**Comment by plittlewood-rpt** [comment]
Hi @bisoh - I can confirm that this problem does not seem to stem from the Foundations Platform and seems spread across a number of customer datasets, albeit in very low volume. To that end, I have opened ticket RSD-174301 with our servicedesk so the issue can be identified and resolved at source (in AgencyCloud), and will therefore close this ticket

**Comment by rochellelevy** [comment]
@plittlewood-rpt is there a link to that ticket so we can track it in our bug ticket on our board please?

**Comment by plittlewood-rpt** [comment]
Hi @rochellelevy - the reference is in my comment above, RSD-174301. Thanks :)

**Comment by rochellelevy** [comment]
sorry @plittlewood-rpt I'm new to the team and I don't how to access the agency cloud board. help?

**Comment by plittlewood-rpt** [comment]
Understood - that's an internal service desk ticket which you may not have access to. The service team would be able to update you on it, however

**Comment by rochellelevy** [comment]
Thanks, can you add that comment to that ticket then please, to update us once resolved?
