### ISSUE TITLE
Location (description) field request

### ISSUE THREAD

**Issue by dan-purr** [reapit/foundations#6381]
**Request**

In order for us to grant access to Semi-structured 'extras' field data, please provide the following information in this request:

- The name of the customer you represent

Cluttons

- The name of every field you need surfaced (if known)

Location (description)

- A screenshot of of the field(s) you require in the agency cloud user interface

![image](https://user-images.githubusercontent.com/70022613/158382243-4de6b679-2b0d-42e1-bbe8-d0bc46fef0c1.png)

- A short use case as to why you require this data

To display on new Cluttons website

**Comment by dan-purr** [comment]
@plittlewood-rpt @HSnipe-RPT Can you please confirm what the name of this field is for /properties/{id} extrasField?

**Comment by plittlewood-rpt** [comment]
Hi @dan-purr - sorry for the delay. @HSnipe-RPT will come back to you this morning

**Comment by HSnipe-RPT** [comment]
Hi
Please see below the extrasField query string parameter values you can now include with your request to retrieve the additional information
Location -> pLocation
As an example, to return all the above fields (where present), you would append the following to your GET request URI:
?extrasField=pLocation
Any problems please let me know.
Thanks
