### ISSUE TITLE
Cost Calculator Not Showing

### ISSUE THREAD

**Issue by simon-cg** [reapit/foundations#6390]
**Describe the bug**
[The cost calculator is not showing where expected on this page](https://developers.reapit.cloud/analytics/costexplorer)

**To Reproduce**
Steps to reproduce the behaviour eg:
1. Log in as either mine or Brian Shaw's @addland e-mail
2. Navigate to https://developers.reapit.cloud/analytics/costexplorer
3. Scroll down to find the cost calculator
4. Don't see it

<img width="1494" alt="reapit" src="https://user-images.githubusercontent.com/64349881/158567234-bfab6fe5-9aac-4964-aa8f-16e31c5bc7b2.png">

**Expected behaviour**
A cost calculator to show

**Additional context**
I experienced this on desktop using latest Firefox on Windows, ditto for Brian Shaw using latest Chrome on iOS

**Comment by HollyJoyPhillips** [comment]
@simon-cg That is correct, the calculator is no longer available. You can find information about API consumptions costs on the T&C's here: https://foundations-documentation.reapit.cloud/developer-terms-and-conditions#schedule-2-fees alterntivley, if you have a question about pricing, please contact dmann@reapit.com (our partnerships lead)
