### ISSUE TITLE
Create Query to populate 'Offices' table in SMB App

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#64]
**Relates to ticket**: https://github.com/reapit/foundations/issues/63

**Summary**: Create Apollo server side query to populate the 'Offices' table on the SMB App

- Query Apollo service to get Offices by company id
- Should also support upload of offices by CSV
- Table should populate with correct data

**Comment by trankhacvy** [comment]
Hey @HollyJoyPhillips where do I get the `company id` ?
At the moment, I'm querying all offices.

**Comment by HollyJoyPhillips** [comment]
@trankhacvy Hi, it should be just by 'id' not 'company id'. 

You are correct, supporting the upload should be on #63 or possibly it's own ticket, I will sort, thanks.
