### ISSUE TITLE
Enhance support for a Tenancies Journal Entries

### ISSUE THREAD

**Issue by RWilcox-Reapit** [reapit/foundations#6400]
**Background context**
Currently AC and Platform behave different when created certain journal entries.
AC write 'tenancy' based journal entries to the 'jnlmisc' table whereas Platform writes them to the 'jnl' table.
Changes need to be made to the platform API to start reading and writing against the correct table based on the 'AssociatedType'

**Specification**
- Services: Reapit.Services.JournalEntries
- Before proceeding ensure we are clear on which journal entries live in which table. These are defined by journal entry type
- Create a new controller action to support 'GET' with a new 'api-version' tag as this will be a breaking change
- Update the POST endpoint to write to the correct table based on the 'AssociatedType' provided. ('tenancy' should go to 'jnlmisc', there may be others)
- Update the validation on the GET endpoint to only allow 'AssociatedTypes' of the same table to be selected. (Breaking change)
- No Get By Id endpoint in this service
- Once this change is done ensure versioning will not break swagger & the  swagger merger
- This is a slightly experimental ticket that is a fairly safe way of testing the waters with regards to API versioning
- DO NOT DEPLOY this change to production until we know what any fallout downstream will be

**Comment by HollyJoyPhillips** [comment]
PL, HP & RW: Reviewed
