### ISSUE TITLE
Properties return metadata and extraField. What do these fields relate to in the front end? Where could a user add to these in the crm?

### ISSUE THREAD

**Issue by mikeyeah29** [reapit/foundations#6412]
Please take a look at our FAQ's before submitting an issue, as your question may already be covered in the documentation https://foundations-documentation.reapit.cloud/faqs

**Summary**

**Detail and or supporting links and screenshots**

**Comment by AshDeeming** [comment]
Hi @mikeyeah29 
The user will enter this information in the Property record - the extrafield may vary depending on the client's requirements.
Please note metadata is data stored via the Platform & can not be utilised within the CRM (AgencyCloud)

**Comment by AshDeeming** [comment]
Hi @mikeyeah29 

The user will enter this information in the Property record - the extrafield may vary depending on the client's requirements. 
Please note metadata is data stored via the Platform & can not be utilised within the CRM (AgencyCloud)
