### ISSUE TITLE
Define available values for `typeId` in `documents` output

### ISSUE THREAD

**Issue by bobf** [reapit/foundations#6413]
**Summary**

Swagger documentation does not provide definitions for possible values that might be included in the `typeId` field for `documents`:

```
The unique identifier of the type of document
```

Comparatively, `propertyImages` defines `type` as:

```
The type of image (picture/floorPlan/epc/map)
```

Could the Swagger document be updated to include potential values and what they represent ?

**Comment by AshDeeming** [comment]
Hi @bobf 

You will need to call the relative configuration endpoint to understand the options available for that client;;
![image](https://user-images.githubusercontent.com/61687775/158976171-b087492f-74dc-4b25-8bd4-4c193f1d6fde.png)

**Comment by bobf** [comment]
@AshDeeming Thanks a lot, I didn't think to look under `/configuration` - will check there first in future. :+1:
