### ISSUE TITLE
Do relations set a new `modified` timestamp on the parent object when modified/created ?

### ISSUE THREAD

**Issue by bobf** [reapit/foundations#6417]
**Summary**

When a related entity (e.g. `properytImages` or `documents`) are updated, should we expect the root entity's (e.g. a property's) `modified` field to also be updated, i.e. if a new property image is added, is this considered to be an update to the property as well ?

I believe that [this comment](https://github.com/reapit/foundations/issues/5229#issuecomment-941090563) confirms this as being the case but it would be helpful for us to get a concrete answer (as the linked comment is related to webhooks, which we are not using in this instance).

**Comment by plittlewood-rpt** [comment]
Hi @bobf - no the modified date will not change on the parent entity when a child entity is updated. The webhooks system is slightly different in that it will notify you when a child entity that contains part of the parent entity has changed, so you can reimport if necessary (for example in the event the name of a contact changes, you'd want to know that the details of the vendor or landlord entity associated with that contact had also changed, assuming they held those roles).

**Comment by plittlewood-rpt** [comment]
Hi @bobf 

Unfortunately such a change would need to be applied in the source data which in this case would be AgencyCloud. The problem we have when building out the Platform, is that we obviously need the APIs to be as responsive as possible, and to do what you describe would mean adding potentially a lot of overhead doing extra database joins in the background to work out if child entities had been updated, and that's something that could spiral out of control to a point where the APIs become unusable. I can certainly raise it with the desktop team (and will do so), however I can't guarantee that it will get changed, and any change in the desktop CRM can take a long time to get rolled out as it has to go through development, testing, and release to the customer so the process end to end is a lot longer than with Platform

I think in your situation right now, you'd need to use a polling strategy that hits multiple endpoints (ie hit `GET /propertyImages?modifiedFrom=XXX` AND `GET /properties?modifiedFrom=XXX`. That way you can understand the bigger picture, without having to go down the webhooks route.

Does this help at all?

Thanks

**Comment by bobf** [comment]
@plittlewood-rpt Thanks again for the thorough response, and thanks for the suggestion for fetching property images separately without a property ID filter - that's something I hadn't considered and is certainly worth looking into as it would be significantly less work than integrating with webhooks.

Understandable that these things can take a long time to roll out - we are not expecting anything to change overnight. I had imagined that a property image update would update the property `modified` field directly in your DB (or perhaps updating another field e.g. `children_modified`) so that you wouldn't have to deal with the performance issues of joining on the fly. I'm sure your devs will know the best course of action here.

Thanks for the help ! Hopefully that should keep us going for a while.
