### ISSUE TITLE
Enquiry created via API not visible in Reapit

### ISSUE THREAD

**Issue by manishautomatic** [reapit/foundations#6439]
We created an Enquiry via the {POST] https://platform.reapit.cloud/enquiries/ endpoint. 
The API returned  a 204-Created response. 
However, the enquiry  is not visible in the Reapit CRM to the client.

I can share additional payload details if required.

Regards

**Comment by plittlewood-rpt** [comment]
Hi @manishautomatic - if you can share some details that would be helpful. Thanks

**Comment by manishautomatic** [comment]
Hello @plittlewood-rpt !

Is there an email ID I can share the request payload for you review.
Regards

**Comment by plittlewood-rpt** [comment]
Hi @manishautomatic - if you can provide the name of your app, the customer id and the rough time you made the request I should be able to find it. Thanks

**Comment by manishautomatic** [comment]
App name -- CommVersion
Request was made on March 9 2022
client_id - 355sfsib6e93igjutevgn4j90a

**Comment by plittlewood-rpt** [comment]
Thanks. I can see a single request for test9march@... on that day which did get added to AgencyCloud, however it looks like the customer concerned have an auto responder set up which might be part of the issue here. 

There was another request which was returned as a 422 response so there must have been something wrong with that payload at the time. 

Does this sound like the enquiry you're talking about?

**Comment by manishautomatic** [comment]
That is correct!
 test9march@... is the one, the API returned a success response but the client is not able to see it. 
 Could you please help with this. 
 
 Thank you

**Comment by plittlewood-rpt** [comment]
Hi @manishautomatic - this client have our Property Pulse product running against their dataset however I have confirmed with our Digital team that Property Pulse does not automatically reject enquiries, only sends out automatic emails when a new enquiry comes in. It looks therefore that a user has actually rejected the test enquiry, something the customer would need to confirm. The customer can however view this record by running an Internet Registrations report in AgencyCloud (Reports -> Portal Analysis -> Applicant Registration Analysis) which will confirm that it indeed was added to their system

![image](https://user-images.githubusercontent.com/30798627/159717885-b8fc2282-67d0-4dd2-875e-14b284fed575.png)

As a result of the above I'm afraid I can't really do much more to assist. The only thing I can suggest is for you to send another test lead through and ask the users not to reject it

**Comment by manishautomatic** [comment]
HI @plittlewood-rpt !

I created another Inquiry on 5th April with the email -- test05-04-2022@xxxxxxxxx for the same client.
We again received 201 success, but the client is not able to see it. 
We shared your response with the client regarding running a report (Reports -> Portal Analysis -> Applicant Registration Analysis) apparently they are not able to see it there. 

Could you please guide further. 
Regards
