### ISSUE TITLE
Can't see "Accommodation Summary" in property results

### ISSUE THREAD

**Issue by mikeyeah29** [reapit/foundations#6440]
I'm looking for where ever I can find the accommodation summary in properties but can't seem to see it anywhere, there is a field for it in the crm, see screen shot

![Screenshot 2022-03-22 at 08 02 14](https://user-images.githubusercontent.com/20769976/159435136-ed2fa2e3-cefc-4d6e-bf9c-b10de336430b.png)

**Comment by plittlewood-rpt** [comment]
Hi @mikeyeah29 - this should be being returned via the API in the `summary` property in the model returned from `GET /properties` and `GET /properties/{id}` - please let us know if you have trouble locating it.
