### ISSUE TITLE
Allow identity checks to be created without supplying accompanying documents

### ISSUE THREAD

**Issue by nroper** [reapit/foundations#6442]
**Summary**
Managaing a new Identity Check status when using an integration app to push data to a Reapit client

**Detail and or supporting links and screenshots**
We are testing the use of an integration app to push data and updates from a service provider application to a Reapit client (SBOX) account.  Part of the processing includes the setting of a contact's identity check status, which is done by patching the latest `identityChecks` record for the contact.

We have identified a scenario where the back end service has determined a status for a contact, but the contact currently has no associated `identityChecks` records in the Reapit environment.  Ideally, the integration app would post an initial `identityChecks` record with the appropriate status in this situation but, as we understand it, this isn't possible without including details of at least one identity document, which won't be available at that point.

Can you confirm whether our understanding is correct, and that we wouldn't be able to post without document details, or whether we have any other options for this scenario?

Many thanks.

**Specification**
- Project: Reapit.Services.IdentityChecks
- Update the CreateIdentityCheckCommandValidation to allow a new id check entity to be created without any documents only in the case where the status is `unchecked` or `pending`. Any other status requires the document(s) to be provided
- This may have downstream effect on the associated command handler which will be expecting at least one document to be provided, so ensure this does not break anything
- Add appropriate tests to suit

**Comment by plittlewood-rpt** [comment]
Hi @nroper - currently that is correct, you have to supply at least one document. I have reviewed the behaviour in AgencyCloud however and noted that it is now possible to create an identity check with no documents as long as the status is set to either Unchecked or In Progress. I will review this behaviour in Platform with our product owner to determine if this is something that can be adjusted so the functionality is more aligned

**Comment by nroper** [comment]
Hi @plittlewood-rpt - thanks for the feedback on this, that's interesting to know and I'll wait to hear more from you in due course.

**Comment by nbdesignstudio** [comment]
To help us understand timescales for this task, is back end sprint 54 actually being actioned this week?

@plittlewood-rpt

**Comment by nbdesignstudio** [comment]
@plittlewood-rpt 
Ok thanks. I hadn't seen that page appreciated.

Can you please clarify what is being done here. As our required is for the ability to be able to input a Status to an identity check even if there are NO identity documents. Is this what is being worked on?

**Comment by nbdesignstudio** [comment]
Ok that does help in that this work will NOT resolve the problem @nroper was trying to resolve. We need to be able to input a Status without any Identity documents being uploaded. 

@plittlewood-rpt  are we able to have a phone conversation at all about the reason and requirement? as it would be easier to explain.
