### ISSUE TITLE
Feed Not Working 

### ISSUE THREAD

**Issue by EdDempsey** [reapit/foundations#6459]
Hello

Leacam acting as my IT partner built an App in Foundations to feed data from Reapit to my website via Umbracco. I have recently parted compnay with Leacam and as of today the feed is not working. Mark Darcy from Leacam sent the mail below last night....

Hey Ed,

I’ve no idea why they’d stop. 
1.	Have Reapit switched the Reapit account to your name yet? Maybe they stopped the “Webhooks” during the transfer? 
2.	Has Donal switched the resources to the new subscription? If he has, it’s possible the FunctionApp URL hasn’t been updated in the WebApp configuration.

I don’t have any access to any system to check it out - we’re not able to make any changes that would break it. 

From: Ed Dempsey <[Ed@eddempsey.ie](mailto:Ed@eddempsey.ie)> 
Sent: Tuesday 22 March 2022 18:49
To: Mark Darcy <[mark.darcy@leacam.ie](mailto:mark.darcy@leacam.ie)>
Cc: Adam Syme <[asyme@reapit.com](mailto:asyme@reapit.com)>; [donal@bcsireland.net](mailto:donal@bcsireland.net)
Subject: Reapit Feed 
Importance: High

Hi Mark

For some reason properties are not feeding from Reapit to the back end of my site – do you know why?

Could you please investiagte - can you mail to ed@ed@eddempsey.ie

Many thanks

**Comment by AshDeeming** [comment]
Hi @EdDempsey 
Please can you confirm which app is feeding to your site?

**Comment by EdDempsey** [comment]
Hi

Leacam App



***@***.***
Ed Dempsey
Managing Director
MSCSI MRICS

M   086 172 4449               T    01 288 0004
E   ***@***.******@***.***>   W   Eddempsey.ie

8 The Forge, Bakers Corner, Dun Laoghaire,
Co. Dublin, A96 RC2K

RICS Registered Valuer No. 5615035
PRSA Licence No. 003903 – 007244

RESIDENTIAL & COMMERCIAL SALES, LETTINGS / MANAGEMENT & VALUATIONS
The contents of this e-mail are subject to contract/contract denied. Without Prejudice. This email, its attachments and any other items transmitted with it are confidential and intended solely for the information and use of the individual or entity to whom the email is addressed. If you are not the addressee of the email or the duly authorised agent of such addressee kindly delete this email, attachments and other items transmitted with it.

**Comment by AshDeeming** [comment]
Hi @EdDempsey 
Is the service that Leacam built still in production? If not, the new website company will need to register an app to gain access to the API's to update the website.

**Comment by EdDempsey** [comment]
Hi Ash

Therein is the problem. I'm getting a new website built by Reapit but it won't be ready for a number of weeks. We can't build an app for foundations in time.

I need to use the Leacam app to feed my existing website - can you set this up

Ed Dempsey
PSRA Licence No. 003903 - 007244
________________________________

**Comment by AshDeeming** [comment]
Hi @EdDempsey 
It may be that Leacam can extend their service for a short period, whilst the new site is being created.

**Comment by EdDempsey** [comment]
Can you reach out to Leacam… ***@***.***



***@***.***
Ed Dempsey
Managing Director
MSCSI MRICS

M   086 172 4449               T    01 288 0004
E   ***@***.******@***.***>   W   Eddempsey.ie

8 The Forge, Bakers Corner, Dun Laoghaire,
Co. Dublin, A96 RC2K

RICS Registered Valuer No. 5615035
PRSA Licence No. 003903 – 007244

RESIDENTIAL & COMMERCIAL SALES, LETTINGS / MANAGEMENT & VALUATIONS
The contents of this e-mail are subject to contract/contract denied. Without Prejudice. This email, its attachments and any other items transmitted with it are confidential and intended solely for the information and use of the individual or entity to whom the email is addressed. If you are not the addressee of the email or the duly authorised agent of such addressee kindly delete this email, attachments and other items transmitted with it.

**Comment by AshDeeming** [comment]
Hi @EdDempsey 
You will need to discuss this directly with Leacam - we have no involvement.

**Comment by EdDempsey** [comment]
Hi Ash

Any update on this?



***@***.***
Ed Dempsey
Managing Director
MSCSI MRICS

M   086 172 4449               T    01 288 0004
E   ***@***.******@***.***>   W   Eddempsey.ie

8 The Forge, Bakers Corner, Dun Laoghaire,
Co. Dublin, A96 RC2K

RICS Registered Valuer No. 5615035
PRSA Licence No. 003903 – 007244

RESIDENTIAL & COMMERCIAL SALES, LETTINGS / MANAGEMENT & VALUATIONS
The contents of this e-mail are subject to contract/contract denied. Without Prejudice. This email, its attachments and any other items transmitted with it are confidential and intended solely for the information and use of the individual or entity to whom the email is addressed. If you are not the addressee of the email or the duly authorised agent of such addressee kindly delete this email, attachments and other items transmitted with it.
