### ISSUE TITLE
Additional Permissions on a Live Private App

### ISSUE THREAD

**Issue by soilleir** [reapit/foundations#6466]
Hi

We have a live private app which we need additional permission added to.  The app is heavily used by staff and clients and can’t have any downtime.

Is it possible for you to add permission to Write to Contacts without the app being disabled or uninstalled?  

To emphasise the App cannot be offline at all as it ties into other systems using webhooks which our clients could update/access at any time.

Look forward to hearing from you.

**Comment by AshDeeming** [comment]
Hi @soilleir 

Currently the app will need to be uninstalled, permission changes made & then re-submitted for approval

If you can arrange for the above out of busy business hours, we will work with you to ensure a limited timeframe for downtime.

**Comment by soilleir** [comment]
Unfortunately as it would impact our clients and because of the nature of
the app the above isnt an option as clients could be processing their AML
checks on the partner system at any point day or night.   I'll speak with
our internal team as another option is to create a v2 version of our
existing foundations App with the upgraded permissions then swap over the
Client and Secret keys to the new app on our side then decommission the
original app.    Does that sound ok at your end if we do that?
