### ISSUE TITLE
Where can I get list of possible property selling and letting statuses?

### ISSUE THREAD

**Issue by mikeyeah29** [reapit/foundations#6474]
I'm trying to map statuses in the website I'm working on with reapit. The statuses I can see are like 'forSale' or 'toLet', but I need to know what others might be set. 

I have mapped these so far with the reapit statuses on the right...

AV_LET ( Available to Let )                  = toLet
AVAI ( For Sale )                                   = forSale 
SOLD ( Sold )                                       = underOffer
U_O ( Under Offer )                             = underOffer
UODS ( Under Offer - Unavailable )  = underOfferUnavailable
VALUE ( Valuation )                             = valuation
WITH ( Withdrawn )                            = withdrawn
LET ( Let )                                            = ???
TO_LET_DIS (To Let - Discreet )       = ???
DISCR ( For Sale - Discreet )             = ???

Are there any statuses that would be appropriate for the last three?

**Comment by AshDeeming** [comment]
Hi @mikeyeah29 

Please refer to the API section in the Developer Portal - This will show you the swagger documents along with examples, however you can also select the 'model' option to provide a further breakdown;
For statuses you will need to see the /Properties/[id} Endpoint, then 'Selling'(as below) and 'Letting'

![image](https://user-images.githubusercontent.com/61687775/159913640-a332e0ad-bc3e-4812-a9e3-8e0361e22fcb.png)

**Comment by mikeyeah29** [comment]
Ah yes, I've never noticed the model tab before thanks a lot
