### ISSUE TITLE
Add caching layer to SUMS Proxy

### ISSUE THREAD

**Issue by plittlewood-rpt** [reapit/foundations#6483]
**Background context**
AgencyCloud runs a periodic request to an /appcontrol endpoint to manage ejection of users and system upgrades. This happens every five minutes for every user that is logged in. As the proxy has to check the state of a user, it has to hit the internal organisations service for every request which is causing very high load during working hours. As more and more customers migrate over to Reapit Connect, this problem gets worse. We should consider introducing a caching layer on the appcontrol endpoint handler only to dramatically reduce the requests that get right through to the database

**Specification**
- Project; Reapit.Lambdas.CustomerManagementProxy
- Setup a small redis elasticache instance (add to project's cloudformation stack). Consider the number of concurrent connections could potentially be very high given we have upwards of 20,000 active users
- Ensure customer management proxy IAM policies are updated as required to give read/write access to new cache instance
- Update the /appcontrol endpoint handler to check the cache for the user making the request before calling out to the organisations service. This should be the first thing it does entering the handler as it will also vastly reduce the number of API calls to the parameter store to check the Reapit Connect migration status for the user
- Cache entries should live for a maximum of 15 minutes and should be keyed with the user's email address, along with the full appcontrol response. Use the redis TTL to automatically expire old cache entries. If there is no cache entry found for the user's email address, run the existing logic in full
- In the event the cache cannot be accessed, we should always run the existing logic to prevent users being ejected from the system 
- We have used Redis in the RequestConcurrency package which can be used as a reference point to get started

**Comment by HollyJoyPhillips** [comment]
Slight change or direction for development
