### ISSUE TITLE
Document download 502

### ISSUE THREAD

**Issue by mikeyeah29** [reapit/foundations#6484]
I'm calling the endpoint /documents/{ id }/download. Sometimes I get 200 and everything is find but on other id's I get 502.

The download link does exist for the property as its in..  _embedded > [0] > _links -> download when I search for a property

Do you have any suggestions on how to trouble shoot this? 

**Specification**
- Review requests to GET /documents/{id}/download for the Seymours New Homes app and pull out those requests timing out (use Platform monitoring dashboards to do this)
- Look at the actual file sizes involved in the failing requests and check whether or not the redirections are happening as they should be. If they are, this could be an app issue, if they are not, we may need to alter the threshold for using the redirect mechanism over direct download from this endpoint.
- The threshold is stored in parameter store (shared common configuration setting)

**Comment by plittlewood-rpt** [comment]
Hi @mikeyeah29 - this will likely be happening due to the size of the document. Can you confirm the name of your app and I'll find some requests. We recently introduced a redirect for larger files so you get redirected to a URL that allows you to download the file directly rather than through the Platform to circumvent this problem, but you'd need to be following redirects in your application to benefit from this.

**Comment by mikeyeah29** [comment]
Hi, the app is called "Seymours New Homes". I don't mind using a redirect if the files are too big but theres no redirect response all I get is a 502

**Comment by HSnipe-RPT** [comment]
Hello Mike,

You should no longer get a 502 error when trying to download your documents, instead Platform should now return a 302 and redirect you to a download link.
The swagger page in the developer portal doesn't support the redirect currently.
Hopefully this has fixed you issue.

Let me know if you have any more questions.

Kind regards,
Harry

**Comment by mikeyeah29** [comment]
Hi Harry,

Thanks for that - yes I am getting a 302 now which is great but I'm not being redirected and it's not returning any kind of link to redirect to...

Thanks,
Mike
________________________________

**Comment by plittlewood-rpt** [comment]
Hi @mikeyeah29 - you should be getting a Location header that you can follow. Is that not the case?

**Comment by mikeyeah29** [comment]
Hi Pete,

Yep, no worries I am getting the location header

Thanks,
Mike
________________________________
