### ISSUE TITLE
Update apps that are integrations 

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#6487]
**Summary**: We have now removed the option to allow integrations the ability to set desktop types as it's not relevant. However, we still have some apps that have it (from a previous version). Going forward it won't be an issue but we should do a clear up

**Specification**
- Update all apps where IsDirectApi=true to remove Desktop Integration Types. This will need to happen on the current app revision. If the current app revision is not in a listed state, the same update should be applied to the listed app revision also
- This will need to be done directly on the database. The apprevisions table should be backed up before work commencing and a log of any statements being run should be kept (off this ticket - data should be held internally only)
- Speak to team if further info about data structure required

**Comment by gnthackray-reapit** [comment]
spoke to holly change needs making manually. 
so will close ticket.
