### ISSUE TITLE
Installing a private app - error message

### ISSUE THREAD

**Issue by gmortlock** [reapit/foundations#6489]
I am working with our developers to build an integration between Reapit and our website. They have built a private app that we have linked to from our organisational account. They cannot see live data because we have not yet installed the app, but when I try to install the app it says 'Your organisation settings prevent you from installing this app, please contact an Administrator.' (screenshot attached). Please can you tell me how to install the app? My main administrator also could not see how to do this.

We need to deploy to live on Monday as our developers are only available for this time so a fast response would be appreciated!

![Reapit Ticket](https://user-images.githubusercontent.com/102365853/160155828-7faea98b-9d19-41a7-a2d4-0409723c7751.PNG)

**Comment by gmortlock** [comment]
I am an admin, but the warning message is still coming up...

**Comment by AshDeeming** [comment]
Hi @gmortlock 

Just to clarify, are you an AgencyCloud user for Carter Jones who can access the CRM software? 
As per the error message, you're account doesn't have the permissions to install & it may need to be referred internally

**Comment by gmortlock** [comment]
Hi Ash, 

You're right - even though I was an admin I wasn't an admin level 2 or above. The main account manager has now successfully installed the app - thank you for all your help!

**Comment by AshDeeming** [comment]
No problem, thanks for confirming @gmortlock
