### ISSUE TITLE
Problems pulling in property info on Commercial properties via our market place app

### ISSUE THREAD

**Issue by mark-orme** [reapit/foundations#6497]
We have a market place application and it pulls in address info from REAPIT when a customer loads our app from the property record on REAPIT.

We have a customer who has been using our app fine since we launched but they are now finding on commercial properties only that the address info doesnt pull in from REAPIT into our app nor can they see the address when trying to select from the list of addresses on REAPIT.

As we dont control what addresses REAPIT exposes to us then there must be a restriction that has been applied as its only stopped working recently.

The last successful property was:

11 Market Place, Gainsborough, DN21 2BP

Property record  > Apps > NicheCom Orders then REAPIT should provide the address of the property to our app to drop onto the order but for some reason on Commercial properties only we don’t get an address so we can’t use one and one isn’t dropped onto our app.

Also if the branch tries to select an address manually REAPIT isn’t providing our app any addresses ( screen shot showing no addresses available) for them to select so not sure if there has been something changes for commercial properties as when the same users order for sales properties there is no issue at all and it was working up until a few weeks ago.

We have spent lots of time and tried to diagnose but as we are getting the addresses available for the user from REAPIT and we don’t control what addresses are available to us we think its something your end but if you can assist then all the better in trying to diagnose the issue to fix for our mutual customer.

**Comment by AshDeeming** [comment]
Hi @mark-orme 
Please can you confirm the departments endpoint is being used to check the departments/id

**Comment by mark-orme** [comment]
@AshDeeming We don't use the departments endpoint to list properties. We use that when they first connect to niche to get their office/client/branch address.

To list properties we use `GET /properties?page=1&perPage=25`, or `GET /properties?page=1&perPage=25&address=Some%20road` if the user has entered anything in the search box

If the app loads with `prpCode` from the marketplace globals then we call `GET /properties/:propertyId`

Once the user selects a property, or we load one via marketplace globals, then we call `GET /properties/:propertyId/contacts` to retrieve contact data

Departments shouldn't have anything to do with this afaik.

In this case I think we would have `prpCode` from the marketplace globals as they've opened our app from a property already selected in REAPIT.

Calling `GET /properties/:propertyId` should give us the data about that property regardless of which department it's assign to, the only time it wouldn't is if the user doesn't have access to that property, but given they've selected it from REAPIT already they should have access to it.

**Comment by AshDeeming** [comment]
Hi @mark-orme 
The Departments Endpoint will allow you to check which departments that client utilises i.e. Residential (General), Commercial etc depending on their DepartmentsID.

If the ID = 'G' for example you will know it relates to General/Residential properties. If the ID differs to this, you will need to get Departments to check that that ID relates to & its associated values.

**Comment by mark-orme** [comment]
Hi @AshDeeming  but we are looking for **properties** based on the above info supplied and we dont pass any dept info to get the residential / general properties from the properties endpoint.

 We just use the above based on the property code so I'm not clear what info we would get from the depts. endpoint other than the dept. of the user as it doesnt look like it contains any properties at all ? when we are looking for the properties they have access to so we can load them in our application ?

please advise what we need to do to get access to the properties for commercial properties when querying the properties endpoint with their prop code etc as we have a client who handles both depts from one REAPIT login.

Thanks

Mark

**Comment by AshDeeming** [comment]
Hi @mark-orme 
Please see the documentation around this which may help; https://foundations-documentation.reapit.cloud/platform-glossary#department

You will need to include the relevant call to departments to check the department id's that are relevant to that Client.
![image](https://user-images.githubusercontent.com/61687775/160860412-38a31f34-e718-4cb9-9b75-ec5be7301e8b.png)


 Then under the properties endpoint, you will see the department: 
![image](https://user-images.githubusercontent.com/61687775/160860203-f5994690-38b3-4c4e-bb46-c721ff691cdb.png)

**Comment by mark-orme** [comment]
Hi @AshDeeming 

we have just tested in the reapit sandbox account, and I can see a mixture of general and commercial properties on the `GET /properties` endpoint without specifying a department, so departments are completely irrelevant to this issue.

Theres something different about that user's account that's preventing us access to their properties so can you check for us with Pygott and Crone on these properties and let us know why we dont get any properties when using the get properties endpoint for their commercial properties

**Comment by plittlewood-rpt** [comment]
Hi @mark-orme I've had a look into this and have a few early observations from my tests and your comments above

- I can query the properties end point for this customer using just an address filter and do get properties from both General and Commercial properties back in the result set (an example is `GET /properties?address=wea` which will return 6 results, 5 of those are Commercial properties and 1 is a General property)
- The URLs you've listed in one of your earlier comments contain query string parameters that don't conform to what Platform expects (perPage and page are not the correct values). Also there is no /contacts subresource on `GET /properties/{id}/`. Are these definitely the URLs you are calling?

Do you have any more specific examples you can share - even a specific timestamp will help as I can look the request up at this end? We can provide a way to send any sensitive details over to us off this ticket.

Thanks
Pete

**Comment by plittlewood-rpt** [comment]
Hi @mark-orme are you able to provide any more information please?

**Comment by mark-orme** [comment]
Hi @plittlewood-rpt thanks for your last comment which has helped us resolve with some additional sentry logging we have added.

Now the customer has confirmed this is working for them,

Thanks again

Mark

**Comment by plittlewood-rpt** [comment]
Thanks for coming back to me Mark
