### ISSUE TITLE
National Home Move Contact Issue

### ISSUE THREAD

**Issue by BYMIntegrations** [reapit/foundations#6502]
Hello Support,

I hope you are well.

While pulling the files for the customer code NHM we only received 7 files but we are expecting around 11. We believe that only one branch has migrated over.

Can you confirm this? If this is the case then what can we do to get them fully migrated over?

Thanks in advance,

Toby Hunter 
Integrations and Support Analyst

0344 800 84 24 (Ext 222) | [TobyH@briefyourmarket.co.uk](mailto:TobyH@briefyourmarket.co.uk)
[www.briefyourmarket.com](http://www.briefyourmarket.com/)

**Comment by BYMIntegrations** [comment]
Hello Pete,

I hope you are well.

By files I mean XML files. We are currently only pulling through 7 XML files instead of 11 as we are expecting.

We have also discovered that the customer has around 36k contacts would should be a lot more than 7 XML files. We also discovered that a lot of their branches seamed to be closed.

Is there any information that you can give us on this?

Thanks in advance,

Toby Hunter
Integrations and Support Analyst

0344 800 84 24 (Ext 222) | [TobyH@briefyourmarket.co.uk](mailto:TobyH@briefyourmarket.co.uk)
[www.briefyourmarket.com](http://www.briefyourmarket.com/)

**Comment by plittlewood-rpt** [comment]
Hi @BYMIntegrations - the Platform doesn't return data in XML format so it sounds like there is a process at your end that is transforming the data into XML format.

**Comment by BYMIntegrations** [comment]
Hello Pete,

I hope you are well.

Our dev guy Henry has been looking into this on our side and he has discovered an error on your side.

I have attached screenshots of his comments and images supplied to me. Hopefully, this will aid us in sorting this issue.

Thanks,

Toby Hunter
Integrations and Support Analyst

0344 800 84 24 (Ext 222) | [TobyH@briefyourmarket.co.uk](mailto:TobyH@briefyourmarket.co.uk)
[www.briefyourmarket.com](http://www.briefyourmarket.com/)
![Henry Comments](https://user-images.githubusercontent.com/102583061/161043504-4b1124fd-e73d-484c-a350-850e98b3c6db.png)
![Returned Error](https://user-images.githubusercontent.com/102583061/161043508-e3c1e7ae-e6b8-421c-9c18-973959b5e7df.png)

**Comment by HollyJoyPhillips** [comment]
Hi Toby @BYMIntegrations, Please could you ask Henry to provide the request that was made that resulted in the 500 error please?

**Comment by BYMIntegrations** [comment]
Hello Holly,

I hope you are well.

The request was Vendor Type.

Thanks,

Toby Hunter
Integrations and Support Analyst

0344 800 84 24 (Ext 222) | [TobyH@briefyourmarket.co.uk](mailto:TobyH@briefyourmarket.co.uk)
[www.briefyourmarket.com](http://www.briefyourmarket.com/)

**Comment by HollyJoyPhillips** [comment]
@BYMIntegrations Sorry, I mean the actual request that was made. Vendor Type isn't a set request we have. It's the endpoint and the query that was made that will help us review this? 

Also, could you verify who NHM is please as we don't seem to have a customer with that code?

**Comment by BYMIntegrations** [comment]
Hello Holly,

I hope you are well.

I am just obtaining the request from our dev guy Henry. The customer is Your Move with the customer code: YOM-GNHM

Thanks,

Toby Hunter
Integrations and Support Analyst

0344 800 84 24 (Ext 222) | [TobyH@briefyourmarket.co.uk](mailto:TobyH@briefyourmarket.co.uk)
[www.briefyourmarket.com](http://www.briefyourmarket.com/)

**Comment by HollyJoyPhillips** [comment]
@BYMIntegrations It looks like at that time of day the only requests for your app were for QES (Q Estates). No requests for Your Move based on the screenshot have sent. 

Looking at the history for QES there was an issue with the configuration that was resolved later in the day on the 17th. Please can you re run any queries to validate if the issue has now been resolved.

**Comment by BYMIntegrations** [comment]
Hello Holly,

I hope you are well.

I have looked into this this morning and found that it is now working correctly. Whatever the issue was it appears to have resolved its self.

Thanks,

Toby Hunter
Integrations and Support Analyst

0344 800 84 24 (Ext 222) | [TobyH@briefyourmarket.co.uk](mailto:TobyH@briefyourmarket.co.uk)
[www.briefyourmarket.com](http://www.briefyourmarket.com/)
