### ISSUE TITLE
PDF Brochure

### ISSUE THREAD

**Issue by madebyparent** [reapit/foundations#6508]
Help! — We can see brochures get stored in 'Predefined Details' in Reapit by the agent, and it uses the Address line 2 as the default name.pdf
What we need to know, is where to find that PDF and how to call it to display on our 'Brochure' button. PLEASE!

**Comment by AshDeeming** [comment]
Hi @madebyparent 

Please see the Properties Endpoint where you should see 'brochureId' under Selling & Letting
