### ISSUE TITLE
Update Reapit Connect templating mechanism to be aware of different products

### ISSUE THREAD

**Issue by plittlewood-rpt** [reapit/foundations#6510]
**Background context**
Now that other Reapit group companies are starting to integrate Reapit Connect into their products, the email templates that are sent out from Reapit Connect need to be adjustable based on the product. At the moment all the emails going out from Reapit Connect are branded in the same manner. We should consider what will be involved here to allow these products to retain their existing email templates for a smoother transition for the end user to Reapit Connect

**Specification**
- Project: Marketplace / Reapit.Services.Organisations
- We need to update the mechanism that is used to send the Reapit Connect welcome/forgot password/temporary password emails to allow information for different products to be injected into the text, as well as potentially altering the branding. There will be some cross over with the frontend team here, who manage the Lambda function that is used in some cases to fire these emails out. There is functionality in our Organisations service too however that does the same thing (triggered on the delete password endpoint etc)
- Custom information will be stored in the claims associated with the organisation. This could be something like the AgentBox login URL

**Comment by plittlewood-rpt** [comment]
Still in flight from last week

**Comment by RWilcox-Reapit** [comment]
Implementation ticket raised: #6898
