### ISSUE TITLE
Reapit - API "Pop"

### ISSUE THREAD

**Issue by Grant-Dynamic** [reapit/foundations#6529]
**Is your feature request related to a problem? Please describe.**
This is not related to a problem.

**Describe the solution you'd like**
We are in the process of integrating the Reapit API into a new 3CX telephony platform, I would like to discuss the development of the pop up option for example.

A user takes a call within our 3CX platform > reapit API calls and the user received a pop up from Reapit with the callers information.

We want this to only occur for specific groups of users,

**Comment by AshDeeming** [comment]
Hi @Grant-Dynamic 

The platform allows for 'Desktop integration types' which can be associated with certain actions, please see more information: 
https://foundations-documentation.reapit.cloud/api/desktop-api#desktop-types

**Comment by Grant-Dynamic** [comment]
Hi @AshDeeming 

Can this be restricted? for example.

We have a telephony base of around 60 users, we only require 15 of these to have the "pop" is this a permission-based or can we restrict this to a group of extension numbers?

Thanks
Grant

**Comment by AshDeeming** [comment]
Hi @Grant-Dynamic 
This could potentially be available by Office or OfficeGroups however not by user currently.

**Comment by Grant-Dynamic** [comment]
Hi Ash,

Thank you, if possible could you send me a run down of how this would work please.

**Comment by AshDeeming** [comment]
Hi @Grant-Dynamic 
Please see more information regarding OfficeGroups here: https://foundations-documentation.reapit.cloud/faqs#what-are-office-groups
