### ISSUE TITLE
BriefYourMarket Contact and Property Feed for Ellis and Co Willesden Green

### ISSUE THREAD

**Issue by BYMIntegrations** [reapit/foundations#6532]
Hello Support,

I hope you are well.

We have been looking into why we are only receiving 900 contacts for the Willesden Green branch of Ellis and Co when there should be 8000.

We have had the following screenshot which shows the customer has downloaded the app. Can you inform us as to why we haven't received all their data yet?

Customer code: MAC

Thanks,

Toby Hunter
Integrations and Support Analyst

0344 800 84 24 (Ext 222) | TobyH@briefyourmarket.co.uk
www.briefyourmarket.com
![Willesden Green](https://user-images.githubusercontent.com/102583061/161273700-0b4bf55e-90c5-42e3-a8a5-ba05ea11ad03.jpg)

**Specification**
- Project: Reapit.Services.Contacts
- Run the contacts API against the customer mentioned. Filter that results from `GET /contacts` using the `officeId` query string parameter. The office id for the office(s) in question can be obtained from AgencyCloud
- Log into the customers CRM build and run a report for contacts belonging to the office(s) mentioned. Validate whether or not the results match the API output and if not, troubleshoot the discrepancy so we can feed back appropriately

**Comment by AshDeeming** [comment]
Hi @BYMIntegrations 
Thanks for raising this - can you confirm which OfficeGroup has installed the app as above i.e. is the above user a member of MAC or are they part of a segmented group such as  MAC-****

**Comment by BYMIntegrations** [comment]
Hello Ash,

I hope you are well.

It is the Head Office that have installed the app and its been confirmed that that's all they needed to do.

The customer code for all the data is MAC.

Thanks,

Toby Hunter
Integrations and Support Analyst

0344 800 84 24 (Ext 222) | [TobyH@briefyourmarket.co.uk](mailto:TobyH@briefyourmarket.co.uk)
[www.briefyourmarket.com](http://www.briefyourmarket.com/)

**Comment by AshDeeming** [comment]
Thanks @BYMIntegrations 
Just before this goes into review, can i ask why you expect 8000 - are these all active contacts, registered to that Office, etc?

**Comment by BYMIntegrations** [comment]
Hello Ash,

I hope you are well.

8000 contacts are the number of contacts in their old Reapit System and we are unable to see how many contacts they have per office.

Thanks,

Toby Hunter
Integrations and Support Analyst

0344 800 84 24 (Ext 222) | [TobyH@briefyourmarket.co.uk](mailto:TobyH@briefyourmarket.co.uk)
[www.briefyourmarket.com](http://www.briefyourmarket.com/)
