### ISSUE TITLE
Query on location of Lettings Agency Cloud Data within Foundations API

### ISSUE THREAD

**Issue by david-silverink** [reapit/foundations#6542]
We are attempting to locate specific data within the Foundations API. We have listed the equivalent locations in Agency Cloud below. Please advise if and how this data can be accessed.

Attributes screen (Appliances, insurance & Safety tab)

MPRN 
GPRN 
 
![image](https://user-images.githubusercontent.com/80890331/161507709-c9e15736-3da7-4953-8959-f1defa491ad0.png)

Keys & Alarm
 
![image](https://user-images.githubusercontent.com/80890331/161507757-499c75ec-19d8-45ca-8600-0e5cc3fef43a.png)

Multiple & Single Auctions Venue date and time

![image](https://user-images.githubusercontent.com/80890331/161507792-70106655-2b04-4d40-966d-e5715d768926.png)
![image](https://user-images.githubusercontent.com/80890331/161507804-38a15be5-f166-4900-809d-bf0b7ab69c9d.png)

PPS Number, on ID check screen

![image](https://user-images.githubusercontent.com/80890331/161507905-e3025043-322c-42da-b3e9-2398dcda00ea.png)

Thanks

**Comment by AshDeeming** [comment]
Please see the relevant endpoint values on the swagger documentation. I hope the below is of use;

1) Properties/{id}
![image](https://user-images.githubusercontent.com/61687775/161721308-8d6e3b7b-fc56-49aa-8700-8009a95e80ee.png)


2) 
![image](https://user-images.githubusercontent.com/61687775/161721544-af4b35d5-c57b-4e17-b3fe-c7b9b1f9db9d.png)

3) Disposal type - under Property Endpoint, cna be used to differentiate if a property is an Auction etc;
![image](https://user-images.githubusercontent.com/61687775/161725979-39668a0d-710d-4c1d-b488-f1cd03668317.png)

4) I don't beleive the PPS number is currently surfaced via the Platform - a 'feature request' will need to be raised for this to be removed

**Comment by AshDeeming** [comment]
Hi @david-silverink 

Closing this ticket as no follow up response. 

Please feel free to open a new ticket if you have any further issues.
