### ISSUE TITLE
Extra field required for our mutual client(Martyn Gerrard-MTG)

### ISSUE THREAD

**Issue by rajeshwl** [reapit/foundations#6545]
Currently we are using the SOAP API for integrating the data with website. In that we have two fields called **Owners** and **Noticed** used in the API. Can you please enable this field in PAAS API and share the field name for this. So that we can make use of the data.

Attached the sample data for a property. 
![image (7)](https://user-images.githubusercontent.com/14073702/161568579-8aa1b1e6-9be7-4981-97a4-f376d62944d8.png)

**Specification**
- For the customer concerned, confirm the names of the fields to expose, and enable access to these fields for customer MTG in the properties API

**Comment by AshDeeming** [comment]
Hi @rajeshwl 
Please can you confirm which areas of AgencyCloud these relate to & where the above screenshot is from?

**Comment by rajeshwl** [comment]
@AshDeeming ,
We are using the `getGeneralProperties` call in the Rest API .

We took that screen shoot using the reapit tracker. 
https://tracker.reapit.net/demo/_support/web-service/method/results/

**Comment by AshDeeming** [comment]
Thanks @rajeshwl 

I have checked & these are ExtraDescriptions custom to that client; 
![image](https://user-images.githubusercontent.com/61687775/161762738-a8806cbc-c42c-454a-a45e-379ae236005b.png)


Please populate the details below relating to the request; 

In order for us to grant access to Semi-structured 'extras' field data, please provide the following information in this request:

- The name of the customer you represent
- The name of every field you need surfaced (if known)
- A screenshot of of the field(s) you require in the agency cloud user interface
- A short use case as to why you require this data

**Comment by rajeshwl** [comment]
@AshDeeming ,
Thanks for the details.
 
The requested details are given below.
**Customer Name:** Martyn Gerrard-MTG
**Fields:** `The Owners Love & We've Noticed`
Screenshot:
![161762738-a8806cbc-c42c-454a-a45e-379ae236005b](https://user-images.githubusercontent.com/14073702/161771336-73fcb70b-07ce-451d-b1d6-b63a1a7006fd.png)
 
 **Use Case:** In the website we are showing description, owners love, noticed information separately in different places for the property. So we require this field separately.

**Comment by rajeshwl** [comment]
@plittlewood-rpt ,
Can you please prioritize this and enable this extra fields as quick as possible. It's a dependency for us to migrate to PAAS. Kindly  share us the field name's for the above which needs to be used in the request.

**Comment by plittlewood-rpt** [comment]
@rajeshwl as you can see this is in the sprint for next week. If we have any capacity to do it sooner I'll do my best for you

**Comment by rajeshwl** [comment]
Thanks @plittlewood-rpt.

**Comment by rajeshwl** [comment]
@gnthackray-reapit  @plittlewood-rpt ,
Can you please share the field names for the above field to be requested in the extrasField.

**Comment by gnthackray-reapit** [comment]
Hi
Please see below the extrasField query string parameter values you can now include with your request to retrieve the additional information
Noticed-> pNoticed
Owners-> pOwners
As an example, to return all the above fields (where present), you would append the following to your GET request URI:
?extrasField=pNoticed&extrasField=pOwners
Any problems please let me know.
Thanks
