### ISSUE TITLE
Enable access to semi-structured Directions field for customer

### ISSUE THREAD

**Issue by madebyparent** [reapit/foundations#6550]
Hi — We're trying to access directions text, but getting the error;

Access to one or more of the specified fields is not permitted. You must be granted access to this data beforehand

I can't see any potential permissions it could be that we don't have
![image001](https://user-images.githubusercontent.com/45567266/161718041-33973d32-2fe8-4299-90ea-c1c865939055.png)

**Specification**
- For customer Curchods (CRC), enable the directions field on the properties API

**Comment by AshDeeming** [comment]
Hi @madebyparent 

I assume you are referring to the Directions text box within a Property Record. (If so, only Read properties permissions, would be needed) 
If so, these may be custom descriptions, per client - In order to open these for you, please populate a ticket for 'Semi-structured 'extras' field request' (https://github.com/reapit/foundations/issues/new/choose) which can then be processed by the relevant team

**Comment by madebyparent** [comment]
![chris1](https://user-images.githubusercontent.com/45567266/161732802-c23e7eed-0b4c-4bd9-a5a9-cd2c6ab4a874.JPG)
It's just this one box, we can get all the rest strangely.

**Comment by AshDeeming** [comment]
Hi @madebyparent 
That should relate to the property 'description', on the Properties endpoint. 

Other client builds may also have the 'strapline' on this page too, with additional 'ExtraDescriptions' within the Marketing Screen - These can sometimes include a Directions section.

**Comment by madebyparent** [comment]
Sorry, I meant this field;
![BtesmydNU82lvTN3](https://user-images.githubusercontent.com/45567266/161762474-6af9c966-14a1-4d89-9781-227fc0437537.png)
It's the 'directions' field within Reapit

**Comment by AshDeeming** [comment]
Thanks @madebyparent 

Please complete the below & the relevant team will be able to review. 

In order for us to grant access to Semi-structured 'extras' field data, please provide the following information in this request:

- The name of the customer you represent
- The name of every field you need surfaced (if known)
- A short use case as to why you require this data

**Comment by madebyparent** [comment]
All I can say is this property - https://curchods.designbyparent.co.uk/display/CER220115/ is bringing the floorplan as the featured main image, but it's not set to that in the Reapit front-end (see images above)

**Comment by gnthackray-reapit** [comment]
Hi
Please see below the extrasField query string parameter values you can now include with your request to retrieve the additional information
Directions -> pDirections
As an example, to return all the above fields (where present), you would append the following to your GET request URI:
?extrasField=pDirections 
Any problems please let me know.
Thanks
