### ISSUE TITLE
Webhooks not being called on marketing data update

### ISSUE THREAD

**Issue by sanjayisg** [reapit/foundations#6556]
HI,

My Application name is: Benham and Reeves Website Feeder
Client ID: 7cfp03p7p94m2gbptghf6ffilm
Reapit Customer Code: BAR

I get many complaints from our different team that property is updated before a day in RPS desktop app but site is not updated.

We have implemented webhooks for the same and I can see many entry are there but why some of them get missed?

When we ping manually from webhooks it's called but not on marketing data update like description/price etc 

Thanks,

Sanjay Gupta

**Specification**
- Check app is installed by customer mentioned above (marketplace can be used for this)
- Obtain URL for the webhook(s) in question. Check opensearch logs for any send failures to this URL. There is a backoff mechanism in the webhooks service that will attempt to send a notification up to 6 times over a period of time before it will dead letter the event and stop attempting to send it
- Run some tests from BAR live system if possible (on a test record) to track changes being sent through the pipeline

**Comment by AshDeeming** [comment]
Hi @sanjayisg 

Please can you provide an example, along with date/time etc so this can be reviewed by the relevant team. 

Thanks

**Comment by plittlewood-rpt** [comment]
Hi @sanjayisg - sorry for the delay in responding to this ticket. We can see a large number of transmission failures when trying to communicate with your endpoints. Our system expect a response within 10 seconds to prevent slow endpoints causing a backlog of events to be sent out. If a successful response is not received in this time frame, the request will terminate and the notification goes into a retry queue (see [documentation here](https://foundations-documentation.reapit.cloud/api/webhooks#failure-handling-and-exponential-backoff)( where we will retry another five times before giving up. I'd also encourage you to review the Transaction Log in the [Webhooks dashboard ](https://developers.reapit.cloud/webhooks/logs) in the developer portal which should give you an indication of the events we've attempted to send (and the response we've received in each case). If you can review the above and let us know if you still can't get to the bottom of the problem that would be great. I'll close out this ticket for now. Please open a new one once you've had chance to review this. The webhooks system itself is operating as we would expect.
