### ISSUE TITLE
Marketplace App Description not allowing over 150 characters

### ISSUE THREAD

**Issue by r-wilson-ire** [reapit/foundations#6558]
**Describe the bug**
Marketplace App Description should allow between 150 and 1500 characters
When you enter in more than 150 characters, this is producing an error 'Must be between 150 and 1500 characters' and does not allow you to save.

**To Reproduce**
1. Go to https://developers.reapit.cloud/
2. Click on Apps, open unsubmitted app
3. Go to Edit App, AppMarket Listing
4. Enter in description more than 150 characters
5. See error

**Expected behaviour**
Being able to save a description with 150-1500 characters

**Device (please complete the following information for web issues):**
 - Device: PC
 - OS: Windows
 - Browser: Chrome

**Comment by AshDeeming** [comment]
Hi @r-wilson-ire 

I'm unable to replicate this issue. Please could you provide a screen shot or any other details for investigation please.

**Comment by r-wilson-ire** [comment]
![image](https://user-images.githubusercontent.com/103089332/161944440-152bfca7-9250-43d5-a81c-f79c9422e25c.png)

Is an example of the error we see - however, I think I have found what the issue was
When the Bold / H5 function is used, then that text is copied and pasted - the pasted styling is causing the character limit to be exceeded.

So in the screenshot, if you type that text and add bold/H5 styling to the second line - character limit is not exceeded
If you then copy that text, delete it from the description, and then paste the same text in - the character limit is exceeded
