### ISSUE TITLE
Properties patch rest api is throwing error

### ISSUE THREAD

**Issue by skhaitan** [reapit/foundations#6559]
**Describe the bug**
We are trying to run a patch request on the properties to update a metadata custom field but everytime we do that, we get a CORS error.

We tried using the rest api explorer in the reapit developer platform and it return the same cors error. Please guide how to fix it. 

**To Reproduce**
Steps to reproduce the behaviour eg:
1. Go to '...' developer rest api console
2. Click on '....' properties patch request
4. See error core error

**Expected behaviour**

Should update the metadata custom field

**Screenshots**
If applicable, add screenshots to help explain your problem. Please ensure that screenshots do not include sensitive data such as personally identifiable information.

**Device (please complete the following information for web issues):**
 - Device: [e.g. iPhone6, PC, Mac]
 - Browser [e.g. Chrome, Safari]

**Additional context**

**Comment by AshDeeming** [comment]
Hi @skhaitan 
Please can you provide more information or example call for further investigation.

**Comment by skhaitan** [comment]
Hi,

I am making the call from localhost. Please check the screenshot below



[image: image.png]

Below is the payload of the request to : PATCH
*https://platform.reapit.cloud/properties/MKT220414
<https://platform.reapit.cloud/properties/MKT220414>*

[image: image.png]


I tried using the reapit developer console with following input

[image: image.png]

and I still get CORS erro

[image: image.png]


Please refer to responses.doc file in case screenshots are not visible in
the mail

Regards
Sneha

**Comment by skhaitan** [comment]
Hi any update on this?

**Comment by skhaitan** [comment]
HI @AshDeeming, can you please help? I am still stucked on this issue.

**Comment by AshDeeming** [comment]
Thanks @skhaitan 
The images do not appear to have come though? 

Please could you also provide any details regarding the request be used.

**Comment by skhaitan** [comment]
Hi, PLease find the export pdf attached to see the errors in details with screenshot
We are not able to run PATCH properties as it gives the cors error. 

[export.pdf](https://github.com/reapit/foundations/files/8489316/export.pdf)

**Comment by HSnipe-RPT** [comment]
If-Match requires double-quotes around it 
and
Id doesn't need quotes.
