### ISSUE TITLE
Rate limits, automated testing and the sandbox.

### ISSUE THREAD

**Issue by mike-mccormick** [reapit/foundations#6562]
**Summary**
Hi, 

I'm the test engineer on a project that's investigating a Reapit integration, where we'd be syncing property and conctact information from Reapit into a local system via the REST API.

This would be a one-way sync, with Reapit data coming into the system. Given the size of these operations, and the potential size of each individual property, I want to add automated regression tests to flag regressions with how we parse the data. 

I'd be creating a handful of properties and contacts , having our system perform the sync and parse from Reapit, then test our output matches whats expected.

Is there any issues with me using the sandbox for this? I can't see any technical reason not to use the sandbox (we've been using it during development), but before I spend time implementing these tests, I'd like some assurance that running small scale automated tests isn't a breach of terms of service, and that the sandbox shares the same API request limits as the standard API. 

Thanks, 
Mike

**Comment by AshDeeming** [comment]
HI @mike-mccormick 

The rate limits in SBOX are as per the docs (https://foundations-documentation.reapit.cloud/api/api-documentation#rate-limits)

**Comment by mike-mccormick** [comment]
@AshDeeming OK, that's good to know, I've seen many applications apply much tighter API rate limits to their sandboxes. 

Are you aware of any other reasons that would prevent me from writing these integration tests against our sandbox account?

**Comment by AshDeeming** [comment]
No problem @mike-mccormick 
I don't believe so & the sandbox should replicate a standard database config.
