### ISSUE TITLE
Retrieving Marketing Details from Webhooks

### ISSUE THREAD

**Issue by MSB89** [reapit/foundations#6567]
When retrieving a property we are aware we need to include PAdvertText to get the full description however we are using webhooks to make the necessary changes when a property is either created or updated and unfortunately the PAdvertText is not included. 

Can we include PAdvertText into what we receive from the webhooks?

**Comment by AshDeeming** [comment]
Hi @MSB89 

Please note that this request is already logged under #5671 

Please feel free to comment or subscribe to show your interest
