### ISSUE TITLE
Webhooks in test environment keep failing - Failed queue?

### ISSUE THREAD

**Issue by Speedway1** [reapit/foundations#6571]
Webhooks frequently stop firing. There can be very long delays before they come back to life, or else they are only reinstated when we raise a bug report such as this one:
   "Webhooks not firing #6560"

It looks like there's a queue posting process that periodically fails and needs to have an auto-restart in it. Always when the postings start up again, we get the full whack of stalled posts coming to us, indicating that the requests are being queued (in a DB?) but not being actioned (process that pops the queue and calls our end point).

Today we raised ticket #6560 which was resolve (thank you Ash), but then it failed again this afternoon.

This very seriously impacts our development, it can stall an entire team of people for many hours when this happens.

Can you please put in an auto-restart for the processor so that we can stop this happening?

Thank you.

**Comment by Speedway1** [comment]
They failed again overnight. 
Events from 2022-03-06 only came through today, 2022-03-07. We noted that this was for properties being created/modified. Appointment modifications seemed to be working ok.

Here is one of the event IDs where this happened: 
"eventId": "ad8e084b-629f-47cd-a003-921484e4cafa",
  "entityId": "OXF220177",
  "customerId": "SBOX",
  "eventTime": "2022-04-07T10:21:21.7559589Z",

**Comment by Speedway1** [comment]
Right now property triggers are extremely slow coming through, appointment triggers are performing ok.

**Comment by AshDeeming** [comment]
Hi @Speedway1 - I understood that this is now resolved however please let us know if you are still experiencing any issues 

Please note that ticket #6579 has been created for improvements.

**Comment by Speedway1** [comment]
Hi @AshDeeming - It's failed again this afternoon, been off for at least 4 hours.
