### ISSUE TITLE
Sort order of journal entries in activity feed

### ISSUE THREAD

**Issue by nroper** [reapit/foundations#6573]
**Summary**
Journal entries not always displayed in the order created

**Detail and or supporting links and screenshots**
We are using an integration app to update and add records on Reapit client data and are testing with the SBOX account.  The requests are sent via a scheduled cron task and are working OK.  These include POST requests to the journalEntries endpoint.

We've noticed that after creating journal entries they may not appear in the order that the requests were submitted when  viewed in the associated case's activity feed.  

For example, see the screenshot from our local logs that show 2 journal entries being created for vendor case BCK130074.  The entries are both timed at 10:40, but there would actually have been a difference in milliseconds between the request times.

![162017061-7e90806f-a9aa-4923-8bee-eb31d25e9006](https://user-images.githubusercontent.com/479971/162129275-21be0a07-f2f6-443f-b4e6-a0b2c1edbb5b.png)

When viewing the activity feed for the case these entries are sometimes displayed in the order in which they were created and sometimes the other way round.  

Entries displayed in order created:

![161971927-486ab390-9662-481d-a22b-2b621763682c](https://user-images.githubusercontent.com/479971/162131255-ef546410-5f50-4430-8661-7c2f866ba2c3.png)

Same entries displayed in different order:

![162004636-5d404941-74f5-455d-b6cf-a95c08b021ab](https://user-images.githubusercontent.com/479971/162131329-72668b40-93d9-434e-b2b9-4335b9f743d6.jpg)

Looking at the associated records that were created in the SBOX data, it would appear that the `created` field is able to store times with a precision in milliseconds or greater, but that all times are actually stored to the nearest whole second, which we assume is the reason that sorting by the `created` value wouldn't necessarily reflect the actual order of creation.

![162018614-6d07f8df-17db-458f-8793-4ad7d0aaa037](https://user-images.githubusercontent.com/479971/162130046-3e6a77c4-c71b-4f3f-a4a9-eb4ee5b734a1.png)

Would it be possible for the APIs to utilise the greater precision when storing the `created` value - or is there any other way that we can ensure that entries are displayed in the order created?  We could introduce a delay in our integration app, so that at least a second expires between POST requests, but that then adds to the cumulative processing time for the scheduled task, which we don't really want to do.

Many thanks.

**Comment by plittlewood-rpt** [comment]
Hi @nroper - this would actually need to be an AgencyCloud alteration in the first instance. The database does not use millisecond precision on the column that stores the created dates which is why you get a slightly different order when you refresh the activity feed. If this is deemed an issue by a mutual customer, they can raise it with our helpdesk. Thanks

**Comment by nroper** [comment]
Thanks for getting back on this @plittlewood-rpt - I'll ask the client to follow up accordingly.

**Comment by plittlewood-rpt** [comment]
@nroper  for info we already have an internal ticket running since November last year with ref AC-4874 if you want to include this in any correspondence back to the customer

**Comment by nroper** [comment]
Thanks @plittlewood-rpt - useful to know

cc @nbdesignstudio for reference
