### ISSUE TITLE
Setup alarms for webhooks functions to alert when they exceed the maximum run duration

### ISSUE THREAD

**Issue by plittlewood-rpt** [reapit/foundations#6579]
**Background context**
For better visibility of the webhooks pipeline, we should enhance the automatic alerting for functions in the pipeline so we are notified immediately when the max duration of each run is hit

**Specification**
- Projects: Reapit.Lambdas.DatabaseEventHandler and Reapit.Lambdas.EventsTransformer
- Review best practice for alerting on Lambda failures and/or max duration. This might be a combination of utilising Lambda Dead Letter policies and/or Cloudwatch alarms
- Hold discussion around implementation as necessary
- Implement new alarm/alerting mechanisms

**Comment by rochellelevy** [comment]
watching ticket as blocker for rollout of DiarySync to further offices

**Comment by Mike-PygottandCrone** [comment]
Also watching this one, is this going to be looked at this week?

**Comment by plittlewood-rpt** [comment]
Moved to this week's sprint as the work is not yet complete.

**Comment by plittlewood-rpt** [comment]
As above, due to staffing issues this is taking longer to implement.

**Comment by plittlewood-rpt** [comment]
Hi @rochellelevy - part of this work has been completed yes. It's worth pointing out that there is nothing externally facing being done here, it's our internal monitoring systems that are being updated. We are also looking at potential bottleneck areas in the webhooks pipeline with a view to implementing any changes that may improve the architecture of it.

**Comment by rochellelevy** [comment]
yes, I understand that Pete but as discussed with Holly, we dont have confidence at the moment that Reapit will pick up and fix webhook issues before our users notice issues , then we contact Reapit and issue is fixed. We have therefore halted our rollout of our DiarySync product we have been building for the past year

**Comment by plittlewood-rpt** [comment]
Rest of work for this ticket to be completed today

**Comment by plittlewood-rpt** [comment]
Alarms now in place in production. If timeouts start to occur, monitoring channels will be alerted automatically

**Comment by plittlewood-rpt** [comment]
For anyone following this ticket, we will be implementing more measures to remove bottlenecks in the data streaming pipeline as part of #6815
