### ISSUE TITLE
Bradleys having issues with our images displaying since migration to your AWS hosting

### ISSUE THREAD

**Issue by mark-orme** [reapit/foundations#6582]
We have a mutual client Bradleys who have reported an issue with our property images displaying in REAPIT.

This has only started happening since Tuesday when they were migrated to your AWS hosting.

We have not changed how we are uploading the images for any customers they are all going in the same way as usual and no other customers have reported any issues at all.

The error the customer gets within REAPIT When clicking on image – says the larger file isn’t found. 

They reported to your support who directed them to us but we can see in our logs we are still uploading the images in the same way

Please can you have a look and confirm the resolution as none of the images are working.,

**

**Comment by AshDeeming** [comment]
Hi @mark-orme 
Please can you advise if you still seeing the issue for newly added images this afternoon?

**Comment by mark-orme** [comment]
We have not had any issues before tuesday its been since then that nothing has been working.


@AshDeeming

**Comment by AshDeeming** [comment]
Thanks @mark-orme - Can you confirm if you're now seeing the images as expected, since around 1pm today?

**Comment by mark-orme** [comment]
whats the process for the client to fix the photos uploaded before 1pm today do they have to just deleted and upload manually from us ?

ill have to check with the client as they have reported to us after reporting to you guys, is there no way your support can check with issues before pushing this back to us etc ?

**Comment by AshDeeming** [comment]
HI @mark-orme 

The images may need to be re-uploaded however in order to confirm, please can you provide any specific examples for the team to review?

**Comment by mark-orme** [comment]
we have sent some images today at 2pm on HEL22063 and client has confirmed still not working etc.

**Comment by mark-orme** [comment]
a branch as received images today and its working fine now thank you.
