### ISSUE TITLE
BYM Contact Feed sending date/times an hour behind

### ISSUE THREAD

**Issue by BYMIntegrations** [reapit/foundations#6587]
Hi Support,

We recently had an email from Winkworth Kennington saying that they had a valuation booked on 04/04/22 at 14:00 however the I did an api call to see what data was sent over to us and the valuation was sent over with a start time of 13:00.

You can see the results of my api call below:

{
  "id": "KEN2201356",
  "created": "2022-03-29T09:45:18Z",
  "modified": "2022-03-29T10:10:49Z",
  "start": "2022-04-04T13:00:00Z",
  "end": "2022-04-04T14:00:00Z",
  "typeId": "VL",
  "description": "",
  "recurring": false,
  "recurrence": null,
  "cancelled": false,
  "followUp": {
      "due": "2022-04-05",
      "responseId": "",
      "notes": ""
  }

I have included a screenshot below of the appointment in Winkworth's System

(Screen shot with AD)

I suspect this is wider than just the one feed however I currently don't have any other examples but I will look out for any.

Please can you include alexc@briefyourmarket.co.uk in the reply

**Comment by AshDeeming** [comment]
Hi @BYMIntegrations 

Please note that this relates to daylight savings & platform using UTC date/times, please see more information in the docs; 

https://foundations-documentation.reapit.cloud/api/api-documentation#issuing-requests

**Comment by AshDeeming** [comment]
Hi @BYMIntegrations 
I'll close this ticket as there's been no update but please let us know you are still experiencing any issues.
