### ISSUE TITLE
Inquiry visibility within Reapit

### ISSUE THREAD

**Issue by manishautomatic** [reapit/foundations#6588]
This is in continuation of the earlier issue #6439 
We created another inquiry with the email -- test05-04-2022@...
We received a 201 success response, but the client is unable to see the record on their end.

**Comment by plittlewood-rpt** [comment]
Hi @manishautomatic - I've just checked the customers system and it is in there. Same situation as last time, someone has marked it as rejected. Your best bet is to find out who is doing this and asking them not to do it. Hope this helps

**Comment by plittlewood-rpt** [comment]
I should add that this is in the system for customer KYC. Is that the intended target customer? If not, check that you are sending the correct reapit-customer header with your request.
