### ISSUE TITLE
LSL: Selected documents sent via web service

### ISSUE THREAD

**Issue by NBareham** [reapit/foundations#6601]
We are launching a new portal for landlords and tenants and need the ability to only be able to show certain documents to the users. Where is this within the web service?

**Specification**
- Project: Reapit.Services.Documents
- For the read side: Add new property `isPrivate` bool property to `DocumentModel` that surfaces the semi-structured field `fileman.extra.gfPrivate` (false when not set)
- For the write side: Add new property `isPrivate` bool property to `CreateDocumentModel` and `UpdateDocumentModel` that allows the same field to be set. Note that it should be a nullable bool in `UpdateDocumentModel` as it won't always be provided in the PATCH payload.

**Comment by robchett** [comment]
Hi Ash, we're looking at the Foundations APIs here as we know the webservice doesn't support this and won't be amended to do so.

From what we can see in the documentation there is no filter to exlude documents that are set as private or show on Tracker (I'm not sure on the terminology used in the RPS interface).
There also doesn't appear to be a field on the DocumentModel to see if these are private after retrieval.

Can you let us know if this information is exposed in the API and if not can we create a
