### ISSUE TITLE
LSL: Displaying booked appointments

### ISSUE THREAD

**Issue by NBareham** [reapit/foundations#6602]
We are relaunching our My Reeds Rains and My Move accounts and need to be able to show booked appointments within them. Where do we go to get booked valuation appointments? Cheers.

**Comment by AshDeeming** [comment]
Hi Both, (@robchett & @NBareham )

Please note that in order to obtain a clients custom config, including Appointment types, the configuration endpoint can be used to get these:
![image](https://user-images.githubusercontent.com/61687775/163196197-fdef859f-12cb-4f0e-ab5c-9e7324042c3b.png)

**Comment by robchett** [comment]
Thanks @AshDeeming, I think we can close this issue down as we have sufficient details on how the APIs work an the remaining issues are with data which we can attempt to poplulate ourselves.

Before you do that though, could you confirm for me that the `attendee` should be `null` for all the results of `https://platform.reapit.cloud/appointments/?typeId=VL`. It strikes me as odd that 100% of the vals in the SBOX account have no attendee.

**Comment by AshDeeming** [comment]
Hi @robchett 

That does make sense as most MA will just be the Negotiator 

If however the MA has an Applicant/Contact/Landlord or Tenant - this will show under the Attendee section.
![image](https://user-images.githubusercontent.com/61687775/163389854-b7ce9520-0d6e-4fd3-b003-2d5c87bc48ca.png)

SBOX example; 
![image](https://user-images.githubusercontent.com/61687775/163390144-779778fe-bca2-439c-8656-c05a5ba7f76a.png)
![image](https://user-images.githubusercontent.com/61687775/163390200-6d32bc4e-d94e-47ea-b13f-915b4e05204b.png)
