### ISSUE TITLE
LSL: Inspection appointments - where are they?

### ISSUE THREAD

**Issue by NBareham** [reapit/foundations#6603]
We are relaunching the landlord and tenant portals and need to show both landlords are tenants when inspection appointments are due (month / year) and when they have been complete (date / month / year). I can see when in the tenancy under 'Management'. Where are they in the web service please? Cheers.

**Comment by NBareham** [comment]
Done. Thank you!

**Comment by AshDeeming** [comment]
Hi @NBareham 
I'll close this issue- If you have any further issues, please create a new ticket. 
Thanks & regards
