### ISSUE TITLE
LSL: Statements 

### ISSUE THREAD

**Issue by NBareham** [reapit/foundations#6604]
We are launching a new landlord and tenant portal. We need to be able to show landlords their statements so they can then print them off and give them to HMRC, their account etc. so they can do things like tax returns. As these are system generated and sent to the landlords already we simply want to then get hold of these to keep in then portal for them. How do we do this? Cheers. 

**Specification**
- Understand where statements are stored in AgencyCloud against landlords and tenants. 
- Once mechanism is understood in AgencyCloud review with PL about best approach for Platform (it's likely this is something we can expose in the documents API as once the statement has been generated it does get saved in the doc store)

**Comment by AshDeeming** [comment]
Hi @NBareham 
I believe you may need to call the configuration/documentTypes (as below via swagger page) to check if this is configured. 
![image](https://user-images.githubusercontent.com/61687775/163194999-d3304683-f2bb-4b0e-b696-5dc65911bd32.png)

Please let me know if this is not available & i'll check with the relevant team.
