### ISSUE TITLE
Trying to get Token

### ISSUE THREAD

**Issue by skhaitan** [reapit/foundations#6606]
**Describe the bug**
I am trying to get the reapit token using https://connect.reapit.cloud/token but when I make the call I get the response invalid_request.

**To Reproduce**
Steps to reproduce the behaviour eg:
1. Go to '...' Postman Api Explorer
2. Click on '....' Add POST request : https://connect.reapit.cloud/token
Click On Headers > add following
Content-Type :  application/x-www-form-urlencoded
Authorization : Basic NGhhbm5mcTM2b2lnMm0xNjhvNm9vYm1kZWU6ZDIzZTViNDktMDNjNC00MjMyLTg0M2QtN2Y3OTA3MzI2YWNh
Click on Body > select x-www-form-urlencoded radio button
client_id : 2qm3aeonacjqgce3takkg8nb2t
grant_type: client_credentials
4. Scroll down to '....' Click Send
5. See error

I also tried to call the token calling function using node request
const responseReapITAuth = await axios.post(
            `https://connect.reapit.cloud/token`, {
                client_id: '4hannfq36oig2m168o6oobmdee',
                grant_type: 'client_credentials'
            }, {
                headers: {
                    'Content-Type': 'application/x-www-form-urlencoded',
                    Authorization: 'Basic ' + Buffer.from('4hannfq36oig2m168o6oobmdee:d23e5b49-03c4-4232-843d-7f7907326aca').toString('base64'),
                },
            },
        )

But I still gt the error : invalid_request

Please let me know what am I missing? Is the secret_code correct? I am using app id as te secret code because I could find only that in the App page along with client ID

**Expected behaviour**

**Screenshots**
If applicable, add screenshots to help explain your problem. Please ensure that screenshots do not include sensitive data such as personally identifiable information.

**Device (please complete the following information for web issues):**
 - Device: [e.g. iPhone6, PC, Mac]
 - Browser [e.g. Chrome, Safari]

**Additional context**

**Comment by AshDeeming** [comment]
Hi @skhaitan 

Please ensure that the clientId & clientSecret are the correct way around. 
Having checked your code, it looks very similar to: https://github.com/reapit/foundations/blob/master/packages/connect-session/src/server/index.ts#L39 
Which has been used successfully internally. Please check the credentials being used and please feel free to revert back to the code example.

**Comment by HollyJoyPhillips** [comment]
Hi @skhaitan, please can you confirm if this has now been resolved?

**Comment by HollyJoyPhillips** [comment]
Closing this ticket as no response. Please raise another ticket if it's still an issue. Thanks.
