### ISSUE TITLE
Semi structured data request: pNoWebsite

### ISSUE THREAD

**Issue by madebyparent** [reapit/foundations#6614]
We need access to Field name = pNoWebsite

- The name of the customer you represent - CRC / Curchods
- The name of every field you need surfaced (if known) - pNoWebsite
- A screenshot of of the field(s) you require in the agency cloud user interface
- A short use case as to why you require this data - So users can remove a property from the website but still remain on portals
![image001](https://user-images.githubusercontent.com/45567266/163166540-be6c4c94-adc3-4444-a9d6-8b7f10506882.png)

**Comment by gnthackray-reapit** [comment]
Hi
Please see below the extrasField query string parameter values you can now include with your request to retrieve the additional information
Disable Website Feed -> pNoWebsite
As an example, to return all the above fields (where present), you would append the following to your GET request URI:
?extrasField=pNoWebsite 
Any problems please let me know.
Thanks
