### ISSUE TITLE
Developer Edition: In the Developer Edition, enable security so that a user can raise rent invoices for a tenancy record. 

### ISSUE THREAD

**Issue by Speedway1** [reapit/foundations#6618]
**Background context or User story:**
We are trying to develop functionality around arrears but cannot do so because we are unable to raise a rent invoice.
In the Developer Edition, enable security so that a user can raise rent invoices for a tenancy record. 

**Specification or Acceptance Criteria:**
Must be able to raise a rent invoice and access payment history in the Developer Editiion.

**Comment by HollyJoyPhillips** [comment]
Unfortunately, the developer edition has been setup to be as vanilla/generic as possible for testing. Not every customer has client accounts enabled so therefore it cannot be enabled in the Developer Edition.
