### ISSUE TITLE
Webhooks continue to fail in the developer environment - Related to #6571

### ISSUE THREAD

**Issue by Speedway1** [reapit/foundations#6619]
**Background context**

Please see issue #6571 
The problem continues. The webhooks have been down again this afternoon, for at least 4 hours, in the developer enviornment.

**Specification**

**Comment by AshDeeming** [comment]
Hi @Speedway1

Please note that the below ticket, which will resolve webhook issues, will be prioritised for next weeks sprint; https://github.com/reapit/foundations/issues/6579
