### ISSUE TITLE
Running late with a Private app revision review

### ISSUE THREAD

**Issue by bakaevd** [reapit/foundations#6621]
**Describe the bug**
I needed to make a change to the permissions of a privately published app. It's supposed to be reviewed in 1 - 2 days.  We are going onto day 4.  I need the change to be reflected.  It's a blocker.

App name: MovePal Sync 
Privately installed by Choices.

Check status says it's still pending.   Only option is to cancel the revision.

**Expected behaviour**
Please review and approve.
Allow permissions changes without having to re-review.

**Comment by AshDeeming** [comment]
Hi @bakaevd 

An email was sent to the App owner but no reply has been received - Please see details below;

In order for permission changes to be implemented correctly, we need to ensure that all current installations of the app are uninstalled beforehand. These can then be re-installed & client(s) agree to new permission set.
 
Please confirm that no installs remain (these can be seen on the app details, installations page & i'll get the revision approved.

**Comment by bakaevd** [comment]
Uninistalled
