### ISSUE TITLE
Move existing areas library dataset into AWS hosting

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#663]
We need to be able to provide a high quality list of maintained geocoded areas for the areas setup process of the onboarding wizard. Customers should be able to select pre-built areas from our area library and import them into their environment - where they can subsequent tweak if they wish.

We already have a database that fits this purpose. We need to move it to AWS hosting and let Simon Ogden know once this has happened. Speak to CB for connectivity details and AWS infrastructure requirement.

**Comment by plittlewood-rpt** [comment]
Data migrated across to AWS. Details circulated internally
