### ISSUE TITLE
SMS URL - unique message ID parameter macro

### ISSUE THREAD

**Issue by Speedway1** [reapit/foundations#6631]
**Background context or User story:**
A Microsoft Windows 10 bug means that we need to add an extra parameter into the URL that is used by the DLL to send text messages. We are looking for a macro that the RPS system will substitute that will give a unique value to that URL call. Please note that a timestamp isn't guaranteed to be unique.

Is there such a parameter that can be used? One possible way of achieving this would be to concatenate the office code and a timesatamp togther such as this:
   message_id={LoggedNegotiator.Office.Code}{System.Timestamp}

If you don't have a unique ID, then what is the correct macro for a Timestamp? Is {System.Timestamp} correct?

**Specification or Acceptance Criteria:**

**Comment by HollyJoyPhillips** [comment]
@Speedway1 This is related to Agency Cloud and not something that can be managed/resolved from Platform. I understand a ticket has already been raised with the Agency Cloud team which you can follow.
