### ISSUE TITLE
Install/Uninstall webhooks lost.

### ISSUE THREAD

**Issue by bakaevd** [reapit/foundations#6632]
**Describe the bug**
I had install/uninstall webhooks created.   I noticed that the application was uninstalled by the webhooks didn't get triggered.  Looks like there has been a change to the configuration.  I no longer see the webbhooks.  

**Expected behaviour**
If webhooks have been defined, I don't expect them to disappear in a production app.

**Screenshots**
![image](https://user-images.githubusercontent.com/28220619/163497968-d05e241a-89b5-48e8-8296-4e0154d2ba50.png)

**Comment by plittlewood-rpt** [comment]
Hi @bakaevd - I can't see that there has ever been a webhook setup for the MovePal Connector app before today (18/04). I can however see several webhooks (some now deleted) associated with the MovePal Sync app, some of which were capturing application.install and application.uninstall events. Could this just be that you were perhaps looking at the wrong app on the Developer Portal webhooks dashboard?

**Comment by bakaevd** [comment]
I may have been.  I ended up re-creating webhooks so can't tell now.

**Comment by plittlewood-rpt** [comment]
Thanks - I can see what's been deleted as we only soft delete and this does seem to be what's happened here. I'll close this issue out, just get back in touch if you notice anything further. Thanks
