### ISSUE TITLE
`propertyImage` `type` does not match documentation

### ISSUE THREAD

**Issue by bobf** [reapit/foundations#6636]
**Summary**

When fetching `propertyImage` items, the `type` is usually `photograph` which is not documented in the model for `propertyImage` here: https://developers.reapit.cloud/swagger

Is the list of `type` values intended to be exhaustive and should I expect `picture` to sometimes be returned, or is this a mistake in the documentation ?

**Detail and or supporting links and screenshots**

From documentation:
```
type	string
The type of image (picture/floorPlan/epc/map)
```

**Specification**
- Project: Reapit.Services.PropertyImages
- Review enumeration used for image type and ensure swagger documentation is correct. Be aware that multiple models might contain the incorrect enum value (picture instead of photograph)

**Comment by HollyJoyPhillips** [comment]
Hi @bobf, yes the swagger documentation requires an update. We will be addressing this in this week's sprint. Thanks. Holly.

**Comment by bobf** [comment]
Cool, thank you for confirming, @HollyJoyPhillips

**Comment by bobf** [comment]
That looks good now, thank you.
