### ISSUE TITLE
Is MovePal Sync revision going to be approved soon?

### ISSUE THREAD

**Issue by bakaevd** [reapit/foundations#6637]
**Describe the bug**
We have a private listing of MovePal Sync app.  A revision has been submitted more than a week ago (which includes requesting access to one more resource). Apparently, it needed to be uninstalled and re-installed for all clients (even though it's a private listing) when resource access permissions change.  I've uninstalled it from all clients (Sandbox and the private client).   When is the revision going to be approved?  

We have it installed for a reason.  So asking to have it uninstalled from all clients for an indefinite amount of time so that permissions can be re-requested is significant.  It's blocking our work.

**Expected behaviour**
Minimal uninstall time.  Or not having to uninstall/reinstall at all.

**Comment by HollyJoyPhillips** [comment]
Hi @bakaevd, it looks like you confirmed the uninstallations on Friday (15th) which was a bank holiday and the office was closed. You're revision has now been approved.
