### ISSUE TITLE
Control of window size when a Foundations application is launched

### ISSUE THREAD

**Issue by nroper** [reapit/foundations#6647]
**Summary**

Question as to whether it's possible to control the dimensions of the window that is opened when a Foundations app is launched from Agency Cloud.

**Detail and or supporting links and screenshots**
We are in the process of converting a Foundations app from Elements v2 to Elements v3.

The application includes a case search page that is displayed when the app is launched from the Apps menu in Agency Cloud - with search results displayed in a table.

In the v2 version, the table is displayed in a non-responsive layout, whereas the v3 version uses a responsive layout.

In the v3 version, the default width of the window that the app launches in is triggering a breakpoint that causes the table to be displayed in a mobile/tablet layout, which means that the width has to be increased manually in order to display in a desktop layout with each row spreading across the page.

Is it possible to control the default window width that's applied when an app is launched - and therefore avoid having to make manual adjustments to the width?

Thanks

**Screenshots**

 **v2 default width layout**
<img width="951" alt="Screenshot 2022-04-19 at 11 07 35" src="https://user-images.githubusercontent.com/479971/163983892-c1b03742-9a55-496d-b345-22a5202dc624.png">

**v3 default width layout**
<img width="944" alt="Screenshot 2022-04-19 at 11 08 36" src="https://user-images.githubusercontent.com/479971/163983992-35391675-da04-45f3-9aec-c0b331f98fa4.png">

**v3 layout after increasing window width**
<img width="1048" alt="Screenshot 2022-04-19 at 11 09 06" src="https://user-images.githubusercontent.com/479971/163984045-a709a608-cbd1-48ec-bb1d-2dc029e68e5c.png">

**Specification**
- Project: Marketplace
- Add new nullable `int` fields `launchWindowSizeX` and `launchWindowSizeY` to `AppRevision` entity, and setup relevant mappings to allow fields to be read/written in `AppRevisionModel`, `CreateAppRevisionModel` and `UpdateAppRevisionModel`
- Validate input on the write size as follows:
  - When either field is provided, both must be provided
  - It must not be possible to go smaller than 640 x 480 (or 480 x 640)
  - It must not be possible to larger than 3840 x 2160 (or 2160 x 3840)
  - It should only be possible to set these fields against an app that has one or more desktopIntegrationTypes set
- New fields should be returned from `GET /apps` as well as `GET /installations` as these are the endpoints AgencyCloud uses when loading the installed apps list and subsequently manage app launch control. When fields are not set, return null.

**Comment by HollyJoyPhillips** [comment]
Hi @nroper, the size is set by Agency Cloud and not Platform so I will need to refer this to another department. I'll move to our 'Agency Cloud' column whilst I wait for a reply. 

Thanks
Holly

**Comment by nroper** [comment]
Understood, thanks @HollyJoyPhillips

**Comment by HollyJoyPhillips** [comment]
Hi @nroper, I have had a discussion with the team and whilst this is possible, it will require development work for both Platform and Desktop. At the moment it's not something we can do, so I will move your ticket to our mid term column for when have team capacity to develop.

**Comment by nroper** [comment]
Understood @HollyJoyPhillips - thanks for the update.

**Comment by willmcvay** [comment]
@nbdesignstudio A few points here;

Firstly, yes, all users of Agency Cloud do use it on their desktop. It's non-mobile compatible. However, the whole point is our users need apps that work in both AC and on mobile devices.

Secondly, a lot of time and effort has gone into ensuring the Table is optimised correctly. You have a very small table however, if you have more columns at that resolution there will be overflow text issues and the table will not be readable.

Thirdly, you have chosen to remove the Nav and Sidebar from the CRA template. This is fine and your decision but we have optimised the table to work with the suggested UI.

The example image from our docs illustrates the problem. If you have more columns and more text, plus a nav, you can't see properly the text. The Elements v2 table was not responsive at all and was unusable at lower resolutions. We know we can't optimise for every use case but we try to give a reasonable experience at all resolutions.

![image](https://user-images.githubusercontent.com/4630495/165257788-c16d78c0-ac91-4d7a-b5f3-acb799b1428a.png)

Finally, I get your point on the browser window size. It would be nicer for all developers if this were larger and this is the correct solution to your problem. As Holly said, we'll get it in the backlog for AgencyCloud but until then, the users can just re-size a window.

**Comment by JonSaSS** [comment]
Hello - I require this for Outbound Mobile and email validation on behalf of Loqate GBG

**Comment by HollyJoyPhillips** [comment]
AC related ticket PBI-4685
