### ISSUE TITLE
Property filter by metadata not working

### ISSUE THREAD

**Issue by skhaitan** [reapit/foundations#6648]
Related to issue: #6229

**Describe the bug**
We have patched the property to include a custom metadata field(customGID) using the rest API. When trying to filter all the properties without the customGID, it does not return the correct results. It only searches against properties that has "metadata" object. 

For example, I patched the property with body object as "{"metadata":{"customGID":true}}". It patches correctly. Now I want to search all properties using GET /properties?metadata=metadata.customGID $eq false It does not return any results. 

**To Reproduce**
Steps to reproduce the behaviour eg:
a. Goto Developer.reapit.cloud
b. Go to API
c. Click on REST API
d. Click on Properties
e. Go to PATCH /properties/ -> Try it out
f. Enter following details : 
 If-Match : "EC327435EE98A6F6470F2C838489A835" ,
 ID: OXF220238, 
Body: {
"metadata": {
    "customGID": true
  }
}
g. Click on Execute
h. Go to GET /properties -> Try it out
i. Enter metadata -> metadata.customGID $eq true 
j. Returns one property
k. Enter metadata-> metadata.customGID $eq false
l. Returns 0 properties

**Expected behaviour**
Should return all properties except the one with customGID as true

**Screenshots**
If applicable, add screenshots to help explain your problem. Please ensure that screenshots do not include sensitive data such as personally identifiable information.

**Device (please complete the following information for web issues):**
 - Device: [e.g. iPhone6, PC, Mac]
 - Browser [e.g. Chrome, Safari]

**Additional context**

**Comment by HollyJoyPhillips** [comment]
Hi @skhaitan - the metadata filter mechanism is designed to operate against metadata that has been set. 

As this is stored outside the primary AgencyCloud database it's technically very difficult to achieve what you are wanting to do and impossible to do in a performant way, particularly on large datasets, as we'd have to grab all entities from a particular dataset and churn through all metadata to work out which entities didn't have it set. 

Subsequently to do what you are wanting would need to be something managed by yourself in your app. You could upon installation of an app, page through customer data setting up metadata flags for each record, then use webhooks to capture subsequently added records to do the same thing (ie set it to false on every record).

**Comment by HollyJoyPhillips** [comment]
Closing this ticket as it's not something we can implement as mentioned in the above comment.
