### ISSUE TITLE
Certain tags in properties not being returned in API.

### ISSUE THREAD

**Issue by jonlemarquand** [reapit/foundations#6652]
**Summary**

Hi, we're using Reapit Foundations with a client. Properties are mostly syncing ok, but with some of the properties certain results aren't pulling through.

**Detail and or supporting links and screenshots**

In the property featured in the screenshots, 'Juliette Balcony' is selected but the property is returning blank for situation. This is also happening with 'studio' in style.

In another property, 'terrace' is also not returning in the api results.

These are the only ones we've picked up on so far, all others seem to be pulling through in single/multiple values. Is it possible to confirm that these results are all being returned correctly?

<img width="938" alt="Screenshot 2022-04-19 at 13 52 56" src="https://user-images.githubusercontent.com/38497188/164248189-dd113196-6845-479f-92e1-31a06afbe634.png">
<img width="938" alt="Screenshot 2022-04-19 at 13 52 56" src="https://user-images.githubusercontent.com/38497188/164248211-bd389bc3-52de-4e10-965d-19a3069bf289.png">

**Specification**
- Projects: Reapit.Services.Departments, Reapit.Services.Properties, Reapit.Services.Applicants
- First stage is to research the use of "Studio" as a Style and "Juliette Balcony" as a situation option. Studio is already in our mapping as a property type, rather than a style. Circulate findings
- Depending on how common these options are, we may choose to add one or both of these options to the mapping list
- Put together a document on confluence of existing mappings that can be shared with the wider business so they can understand the ramifications of non-standard attribute configurations

**Comment by AshDeeming** [comment]
Hi @jonlemarquand 
Please can you confirm you have used the /departments/ endpoint to return any none standard attribute a client may have?
![image](https://user-images.githubusercontent.com/61687775/165045537-17c3e6e4-c6da-40f5-a97c-11513248e718.png)

**Comment by jonlemarquand** [comment]
Hi Ash, thanks for getting back to me. I can't see the non-standard attributes in the departments. Is there anything the I/client need to do to get them to pull through?

<img width="458" alt="Screenshot 2022-04-25 at 10 24 02" src="https://user-images.githubusercontent.com/38497188/165062939-3f1d078f-806b-4a9d-8fa7-1feb02f6b8e0.png">

**Comment by plittlewood-rpt** [comment]
Hi @jonlemarquand from your examples above Flat/Apartment and Terrace are already mapped in the API to flatApartment and roofTerrace respectively. When designing the Platform we had a very difficult challenge of putting a standard API on top of what are effectively completely customisable lists, so a lot of research was done to find the commonly used options, and setup appropriate mappings. The key here is the standard values that you see in the platform (ie flatApartment). This does mean that some values, like Juliette Balcony are not currently supported because it only appears in one or two customer systems

**Comment by plittlewood-rpt** [comment]
Hi @jonlemarquand 

There are some updates just in review that will added `julietBalcony` as a new situation option, and `studio` as a Style option (currently this is only supported as a property type but on reviewing configurations across our customer base a number of them do have Studio in the style column instead).

It is worth giving some background into why some options appear to be 'missing'. The attributes list is completely customisable from customer to customer, and putting a standard API contract on top of that was a complex challenge when we built the Platform originally. When we started out, we did a lot of research about what the common options were across our customer base and wrapped those up into a mapping layer. As an example in the Platform you may see a property type of `flatApartment` which is mapped to the following Agency Cloud options (as customers have differentiations in the text they see in the CRM): `Flat/Apartment, Flat / Apartment, Flat, Apartment, Unit/Apartment, Flats`

Juliet Balcony is only in use in two systems and so at the time it was decided to omit it from the Platform. As time goes on however we will get the odd request to support these options. Some of the less common options to really add any value to Platform endpoints so we need to review them on an adhoc basis. I am speaking with our product owner here to see if we can publish a mapping document somewhere as that would answer your other comment above about `terrace` not being supported. The mapping for out `roofTerrace` situation option is `Roof Terrace, Terrace, Roof Terrace/Terrace` so the property you mention wasn't showing terrace should actually be displaying `roofTerrace` in the output.

I hope this helps. If you continue to track this ticket through to it being closed you'll know when the `julietBalcony` and `studio` changes are out in production.

Thanks
Pete
