### ISSUE TITLE
Ability to see "Extra Applicants" data on Applicant record

### ISSUE THREAD

**Issue by stebrough** [reapit/foundations#6653]
**Is your feature request related to a problem? Please describe.**
Our customer would like to process and perform actions on the Email address against Extra Applicants.

**Describe the solution you'd like**
To be able to obtain the Extra Applicant data via the API Applicant endpoint

**Additional context**
![image](https://user-images.githubusercontent.com/40298446/164249859-d9b41cb6-0318-42e5-890a-f1419eba1e97.png)

**Comment by plittlewood-rpt** [comment]
Hi @stebrough - this functionality is already available. All contacts associated with an application record are available in the `related` collection of the applicant model. As the [Swagger documentation ](https://developers.reapit.cloud/swagger) describes, the first item in the collection is the primary contact. If you have a specific example where this is not working, it's likely there's an underlying data issue. Please advise if this is the case and I can get it looked into for you.

**Comment by plittlewood-rpt** [comment]
Hi @stebrough please can you let me know if the above answered your query?
