### ISSUE TITLE
Deprovision webhooks for customer GOC

### ISSUE THREAD

**Issue by plittlewood-rpt** [reapit/foundations#6656]
**Background context**
Webhooks need turning off for customer GOC on 21/04

**Specification**
- Turn off DMS task goc-cdc
- Delete respective cloudformation stack
- We need to log a ticket to clean up any GOC data in the Platform_GlobalData* tables which should be a general ticket that allows us to clear data up for ANY customer as required. We currently do not have a cleanup mechanism for this data which we'll need if we ever need to completely reindex a customer's data, or a customer leaves etc

**Comment by RWilcox-Reapit** [comment]
Closing this ticket as GOC has now been disabled. 
Subsequent ticket for final bullet point raised: #6659
