### ISSUE TITLE
NHM Foundations Property Feed

### ISSUE THREAD

**Issue by BYMIntegrations** [reapit/foundations#6658]
Hello Support,

I hope you are well.

It has been brought to our attention that we have no properties with the status SSTC.

Can you confirm if this matches what you have on your end?

Thanks in advance,

Toby Hunter 
Integrations and Support Analyst

0344 800 84 24 (Ext 222) | [TobyH@briefyourmarket.co.uk](mailto:TobyH@briefyourmarket.co.uk)
[www.briefyourmarket.com](http://www.briefyourmarket.com/)

**Comment by HollyJoyPhillips** [comment]
Hi @BYMIntegrations, you an find the available property types that we support in the property > selling/letting model which can be accessed through our swagger documentation: 
![image](https://user-images.githubusercontent.com/52408607/164719341-3a583216-2853-4ddb-b954-354cc6ddfb2e.png)

**Comment by HollyJoyPhillips** [comment]
Hi @BYMIntegrations closing this ticket as no response and answer provided. If you still have a question please raise another ticket.
