### ISSUE TITLE
500 response when POSTing a new contact, but just for one client

### ISSUE THREAD

**Issue by eazynow** [reapit/foundations#6664]
**Describe the bug**
We are trying to POST a new contact for a client of ours. Client is DLE. We are getting a 500 back. 

**Other clients are unaffected.**

**To Reproduce**
Steps to reproduce the behaviour eg:
1. Perform a POST to `https://platform.reapit.cloud/contacts` with a payload like:
```
{
    "title": "",
    "forename": "Joe",
    "surname": "Smith",
    "active": true,
    "marketingConsent": "notAsked",
    "officeIds":
    [
        "BSL"
    ],
    "negotiatorIds":
    [
        "XXX"
    ],
    "metadata":
    {
        "areaCustomerId": "XXX-XXX-XXX"
    },
    "primaryAddress":
    {
        "type": "primary",
        "line1": "some drive",
        "line2": "",
        "line3": "",
        "line4": "",
        "postcode": "AL0 0AA",
        "buildingNumber": "1"
    },
    "email": "joesmith@example.com",
    "mobilePhone": "07000000000"
}
```

**Expected behaviour**
Getting a 201 back for created

**Actual response**
```
{
    "statusCode": 500,
    "dateTime": "2022-04-21T15:52:01.4543243Z",
    "description": "An unexpected error has been encountered when fulfilling this request. This incident has been logged and will be investigated. Please try again."
}
```

**Comment by plittlewood-rpt** [comment]
Hi @eazynow - I have isolated the problem here and raised an internal ticket for our infrastructure team to correct some permissions on the database. Once this is done this should be resolved but I'll confirm when that's the case.

**Comment by plittlewood-rpt** [comment]
Hi @eazynow - this should now be resolved

**Comment by eazynow** [comment]
Thanks @plittlewood-rpt !
