### ISSUE TITLE
Ability to create a record of a Match between a property and an applicant

### ISSUE THREAD

**Issue by Mike-PygottandCrone** [reapit/foundations#6668]
We would like a POST endpoint in the api that would enable us to register a Match between a property and an applicant.

For example if an applicant sees and actively engages with a given property - by seeing it online, receiving it in an email outside of the scope of RPS or in an app push notification for instance - then we would want to create a record of this event by saving it as a Match. 

This would then mean that we could avoid duplication if a staff member then decides to run a property match in RPS - we wouldn't necessarily want to email a property to someone if they'd already seen it by another method.

I think such an endpoint would be very useful and it could literally take the Property ID in the URI and the Applicant ID as an argument.

Is this something you could do?

**Specification**
- Project: Reapit.Services.JournalEntries
- Familiarise yourself with matching mechanism in AC to ensure accurate testing of the updates
- Enhance the `POST` payload (`CreateJournalEntryModel` and `CreateJournalEntryCommand`) to accept a `typeId` parameter which can accept either `MA` or `MI`. When not provided, the default should be `MI` to match current behaviour (we already expose the typeId in the GET endpoint)

```
{
  "propertyId": "OXF190022",
  "associatedType": "applicant",
  "associatedId": "OXF190001",
  "typeId": "MA"
  "description": "Property match created",
  "negotiatorId": "JAS"
}
```
- When the typeId is `MA` the `propertyId` and `associatedId` MUST be populated and the `associatedType` MUST be `applicant`. This validation can be done in the `CreateJournalEntryCommandValidation` class. The description must also be populated
- Ensure validation of typeId is tight. Developers should only be able to create two types of journal entry currently as we do not want them to be able to create automatic entries that the CRM writes
- Test thoroughly with Agency Cloud that when these entries are written via the Platform, the same property and applicant do not match when using the match facility in the CRM

**Comment by plittlewood-rpt** [comment]
Hi @Mike-PygottandCrone this is now being deployed to production. Please feed back if you have any issues. Writing a match entry via the API will prevent the same applicant/property matching in AgencyCloud so duplicate information will not be sent out from the branches unless they explicitly uncheck the "Exclude Previous Matches" box on the match results panel.
