### ISSUE TITLE
Unable to logout of the Developer Portal

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#667]
**Summary:** At times, when clicking on ‘Logout’ in the Developers portal, instead of logging out, it redirects you to the ‘Apps’ page. This seems to be on occasion and looks to be because of ‘reapit-marketplace-session-marketplace'. If 2 of these cookies are present, logout does not work. 
At present I have been unable to replicate  it to provide further detail,  however it has happened for others. 

**Current behaviour:**  From the settings page (https://dev.marketplace.reapit.cloud/developer/settings) click 'LOGOUT', instead of succesfully logging out, you are navigated to the Apps page (https://dev.marketplace.reapit.cloud/developer/apps) 

**Expected behaviour:** To click 'LOGOUT' and be navigated to the login page of the Developers portal. 

**Things to note:** If you are unable to logout from the developers portal, check the application cookie to see if 2 ‘reapit-marketplace-session-marketplace' are present. If so, delete one and attempt to log out again. 

If we are able to replicate we should try to debug and resolve. 

Will add more detail when I can replicate consistently.

**Comment by willmcvay** [comment]
The issue is when you have logged in as a Client then as a Developer separately with different credentials I think

**Comment by tanphamhaiduong** [comment]
@willmcvay  so after I tried to log in as client and signout and login as a developer I cannot replicate the bug. So I also tried to log in by client and developer parallel but cannot. So do you have any advise?
