### ISSUE TITLE
Cannot find some of the properties from a customer via the API

### ISSUE THREAD

**Issue by enricsangra** [reapit/foundations#6677]
**Describe the bug**
When trying to get a property via ID, the API is returning a 404. According to the customer, this is in their Reapit platform.

**To Reproduce**
Steps to reproduce the behaviour eg:
1. Call the endpoint: `/properties/BIL220699` with the client id `MAC-GCHG`. It happens with BIX080141 and BIX150067 as well.
2. 404 is returned

**Expected behaviour**
The API should be able to return the data instead of returning a 404.

**Screenshots**
We have screenshots from the customer but they all contain a lot of personal information.

**Device (please complete the following information for web issues):**
 - API integration

**Additional context**
Ticket submitted by Goodlord regarding the API integration.

**Specification**
- Clear pDepReq value from properties BIL220699, BIX080141, and BIX150067 in the MAC build. Remainder of records to be cleaned up by service team a per notes below

**Comment by plittlewood-rpt** [comment]
Hi @enricsangra - thanks for getting in touch. This is happening to some bad data in their system which our service team will need to resolve. There are around 300 properties which will be being omitted from our APIs which all have the same problem. If you need access to the properties you mentioned quickly, I can run a data cleanup on these few entities. Thanks

**Comment by plittlewood-rpt** [comment]
Service desk ref RSD-178780 - customer can chase as required. I will update this ticket once I receive an update from our service team.

**Comment by enricsangra** [comment]
That would be amazing, thanks! Those are the only ones we know of right now.

**Comment by plittlewood-rpt** [comment]
@enricsangra I have corrected the two properties with BIX references. Unfortunately I can't find the reference with the BIL prefix in their system anywhere. Please let me know if there's a typo in the id above
