### ISSUE TITLE
AcLink - can't make it work

### ISSUE THREAD

**Issue by MarcinuB** [reapit/foundations#6679]
Hi Team.

I'm looking into the ability to open URL in the browser from our app. I'm using Elements 2.x at the moment and following this:

https://elements-legacy.prod.paas.reapit.cloud/?path=/story/components-dynamiclinks--dynamic-buttons-and-links

![image](https://user-images.githubusercontent.com/8589350/164892274-f72e307a-e58e-4a18-b684-a39aba6e7902.png)

It doesn't seems to work for me. Also I've noticed that this feature is missing from Elements 3.x. Do you still offer this feature or it is scrapped? If not - would you be able to provide me with a working example?

**Comment by willmcvay** [comment]
Hi @MarcinuB a few things on this;

Firstly, we would advise strongly not to use Elements v2.x anymore, it will be deprecated eventually and while we are supporting it for now, there will not be the same LTS as for v3.x.

To answer your question directly, you don't need the useEffect and setState, the component is entirely declarative. This is a working example in production https://github.com/reapit/foundations/blob/master/packages/aml-checklist/src/components/pages/client-search/client-search.tsx#L77

No, this is not something we plan to add to Elements v3. Reason being, the API for the component is not something we can give a reasonably fallback to to non-React users, also it makes something that is actually not that hard, much more complicated than it needs to be.

Pseudo code;

```
const isDesktop = Boolean(window['__REAPIT_MARKETPLACE_GLOBALS']
const url = isDesktop
  ? 'agencycloud://process/webpage?url="https://foo.com"'
  : 'https://foo.com'
```

No need to overcomplicate things for your use case. Hope this helps.

**Comment by willmcvay** [comment]
@MarcinuB Has this answered your question, will close tomorrow if I don't hear back, thanks

**Comment by willmcvay** [comment]
@MarcinuB See the pseudo code above, that will work

**Comment by MarcinuB** [comment]
@willmcvay - I think I understand how to create the URL - that wasn't my issue. I have a problem where Reapit doesn't trigger the browser. I did a quick test where i created a simple link :
![image](https://user-images.githubusercontent.com/8589350/165394014-1c984f47-f4e7-4cff-bd93-bace58ad5283.png)

And when running app in Reapit - this is what I'm getting on click:
![image](https://user-images.githubusercontent.com/8589350/165394109-652ed7d4-082d-439a-a1cf-6ae4b76843ce.png)

**Comment by willmcvay** [comment]
It looks like you are loading this in a browser, it's hard to tell from the screenshot. If so, it will not load the page, the API is intended to launch a browser window from within agency cloud.

**Comment by MarcinuB** [comment]
I'm running that from Reapit. Bigger screenshot for reference below:
![image](https://user-images.githubusercontent.com/8589350/165474631-8476cb49-c1ba-48e0-a642-ad7431191c4c.png)

**Comment by willmcvay** [comment]
Are you using target="_blank" on your anchor?

**Comment by MarcinuB** [comment]
Just tried now - and nothing happens - it doesn't open the external browser or log anything in the console

**Comment by willmcvay** [comment]
I will need to have some more info to diagnose your issue further.

Can you provide your OS Version, Default Browser, AgencyCloud version and the exact anchor tag you are using please?

**Comment by MarcinuB** [comment]
Sure.

OS : Windows 11 Home 21H2 Build: 22000.613
Default Browser: Firefox 99.0.1
AgencyCloud Developer Version 12.145.1

Anchor tag code: 
`<a href='agencycloud://process/webpage?url="https://foo.com"' target="_blank">TEST</a>`

**Comment by HollyJoyPhillips** [comment]
@MarcinuB we believe the issue maybe related to this https://github.com/reapit/foundations/issues/6730. We will be in touch once it has been resolved. Thanks.

**Comment by MarcinuB** [comment]
@HollyJoyPhillips @willmcvay - thanks for keeping me informed. Top service!!!
I've subscribed to the other issue and will test it once it's resolved. 

Thanks

**Comment by HollyJoyPhillips** [comment]
@MarcinuB It looks like that bug was not actually a bug and was unrelated (it has now been deleted). I will add myself to your organisation so that I can replicate this issue. I'll keep you posted of the results.

**Comment by MarcinuB** [comment]
@HollyJoyPhillips - I had this test button on my local environment. Please try to install FluxPro Test in a couple minutes - releasing version with that button now.

**Comment by HollyJoyPhillips** [comment]
HI @MarcinuB, sorry for the delay. I'm trying to load your app in AC (SBOX) but it is saying "OOPS! LOOKS LIKE YOU DON'T HAVE ANY ACCOUNTS CONNECTED TO FLUXPRO. CONTACT ...."

Can you setup an account so I can test the AC link please? User: hollyjoyphillips+flux@gmail.com

**Comment by HollyJoyPhillips** [comment]
@MarcinuB I'm still getting the same message?

**Comment by MarcinuB** [comment]
@HollyJoyPhillips - FluxPro Test app please

**Comment by HollyJoyPhillips** [comment]
Resolved - removed target blank from agencycloud URL and "'s. @MarcinuB Thanks for your patience whilst we debugged this.
