### ISSUE TITLE
Add properties link to landlords resource

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#668]
### Overview
Presently, we don't provide a link from the landlords GET response to the properties that they are in their portfolio. This would be useful and opens the door on a `embed` operation for this property data in this service.

### Requirement
Add "properties" link to the hypermedia `_links` collection for the response of `GET /landlords` and `GET /landlords/{id}`.  `GET /properties` already supports a landlordId parameter.

#### Example

```
  "id": "OXF180001",
  "created": "2018-12-12T12:30:23.0000000Z",
  "modified": "2019-01-08T12:30:34.0000000Z",
  <other data>
 
  "_links": {
    "self": {
      "href": "/landlords/OXF180001"
    },
    "properties": {
      "href": "/properties/?landlordId=OXF180001"
    },
   <other links>
```

**Comment by plittlewood-rpt** [comment]
PR 1744 opened containing this work
