### ISSUE TITLE
Opening marketplace app directly to the applicant open in Reapit

### ISSUE THREAD

**Issue by jphgardner** [reapit/foundations#6682]
Hi,

I am currently developing a Reapit marketplace app in react, to give us the ability to transfer an applicant to MAB.

The react app has two pages, 
- List of Sent Applicants (Default view after authentication)
- Applicant Overview

What I'm hoping to achieve is when we are on an applicant in the Reapit app and select to open the marketplace app, the marketplace app should launch directly to the applicant overview screen, displaying information about the applicant open in reapit, and giving the user the ability to transfer to MAB.

Could you assist me in how I am to achieve this?
Many thanks

**Comment by AshDeeming** [comment]
Hi @jphgardner 
Please see the below area of the documentation: https://foundations-documentation.reapit.cloud/api/desktop-api

**Comment by jphgardner** [comment]
Ah perfect, that's exactly what I need.
Many thanks
