### ISSUE TITLE
Create or update Identity Check status - validation

### ISSUE THREAD

**Issue by nroper** [reapit/foundations#6683]
**Summary**

Apparent anomaly between validation for POST or PATCH of identityChecks records

**Detail and or supporting links and screenshots**
It is currently possible to use the platform APIs to create a new identityChecks record with a 'pass' status and document details as shown in the example below. 

`POST: https://platform.reapit.cloud/identityChecks`

```
    {
         "contactId": "BEL22000009", 
         "checkDate": "2022-04-22", 
         "status": "pass", 
         "negotiatorId": "JAS", 
         "identityDocument1": { 
             "typeId": "RF", 
             "expiry": "2024-04-22", 
             "details": "Test document details", 
             "fileData": null, 
             "fileUrl": null, 
             "name": null
         }
     }

```

However, when attempting to update an existing identityChecks record with a 'pass' or 'fail' status, a validation error is returned unless the fileData or fileUrl fields are populated:

`PATCH:https://platform.reapit.cloud/identityChecks/MKT22000137`

```
    { 
         "checkDate": "2022-04-22", 
        "status": "fail"
    }
```

Response:

```
{
  "errors": [
    {
      "field": "Status",
      "message": "It is only possible to change status to `unchecked`, `pending` or `cancelled` when no documents are present."
    }
  ],
  "statusCode": 422,
  "dateTime": "2022-04-25T09:40:55.4963875Z",
  "description": "One or more validation failures have occurred. Please refer to Errors list for details"
}

```

Could you clarify whether this is intended behaviour, or whether the PATCH should actually validate if there are  existing typeId, expiry and details values for a document?

Thanks

**Specification**
- Project: Reapit.Services.IdentityChecks
- Revert validation rules that were introduced recently to enforce file attachments when a status of an id check is going to pass/fail. The only mandatory fields for this status change should be typeId/expiry/details

**Comment by plittlewood-rpt** [comment]
HI @nroper thanks for reaching out with the above. We will review the behaviour and compare it to how AgencyCloud behaves which is the validation we've modelled the API on, however it does look like there may be an issue with it on the POST. From what you've said above, the PATCH is working as intended as you shouldn't be able to change the status to pass/fail if there is no documentation (as you've had nothing to check), but the POST is potentially missing some validation. Just so I'm clear can you just confirm the issue the current behaviour is giving you and your team in terms of what your app is trying to do, along with what your expectation is?

**Comment by nroper** [comment]
Hi @plittlewood-rpt thanks for getting back.  Yup, sure, here's the background:

Our Fooundations app hooks into the Identity Check action and displays a custom screen/form.  As well as fields for selecting document types and entering details, there is a status dropdown,  This had allowed the user to change the status from/to any value defined in the model (as requested after a review by Reapit)  This was working by either PATCHing an existing `identityChecks` record, or POSTing a new one if none existed.  

We've also been working on a server-side integration app, which uses the `platform.reapit.cloud` APIs to make updates to client data in RPS.  We had implemented similar functionality for the POST approach described above for situations where no existing identityChecks records existed (and including document `typeId`, `expiry` and `details` fields) and then last week added a PATCH to update the status of an existing record.  However, this was failing and giving the validation error around document requirements.

We're pretty sure that the PATCH was working originally, but has subsequently had the validation tightened up?

So, long story short, we need to be able to update a status in both situations (existing or no existing `identityChecks` records)  From what you say, once the POST validation is tightened up then that will require an actual document upload, with either fileData or fileUrl set accordingly)  If so, then that's not necessarily an issue, and the requirement is understood.  

Just to confirm though,  is it definitely the case that providing `typeId`, `expiry` and `details` is not considered sufficient for a pass or fail status (albeit that it's allowed for POST at the moment) and that an actual document must be uploaded?

 I've tested a `fileData` update and that looks pretty straightforward (once I realised I'd missed the initial data header) but it would be useful to have some guidance on the use of the pre-signed URLs for larger files - both from withing a Foundations app and via the server-side integration app.  I created [an issue relating to that here:](https://github.com/reapit/foundations/issues/6684)

Let me know if you need any more info.

Thanks

**Comment by plittlewood-rpt** [comment]
Hi @nroper thanks for the information. The change to the PATCH endpoint was deliberate, in fact the POST should be behaving in the same way so something is obviously not right somewhere. I need to just liaise with Holly to agree what action we will take on this. It feels more correct to disallow identity checks in a pass/fail state when there's no physical document attached as how can that id have been checked, without the document being physically available.

**Comment by nroper** [comment]
Hi @plittlewood-rpt no problem and thanks for the update.

I understand what you are saying with regard to a requirement for a physical document, and I don't think availability will be an issue as our client will have genereated a compliance pack PDF  for any AML pass/fail results.

For smaller file sizes it should be pretty straightforward to encode and submit the file data with a PATCH or POST, but we may need to give some thought to how best to handle larger files in our apps (particularly the server-side integration app)  via pre-signed URLs.  If it would be to get some examples or guidance on options for writing file data to the AWS URLs once the'yve been obtained from the `i/identityChecks/signedUrl` endpoint then that woul be appreciated - re my associated issue/question below:

https://github.com/reapit/foundations/issues/6684

Thanks

**Comment by nroper** [comment]
Hi @plittlewood-rpt 

Just another thought.  

We'll already have a secure URL/endpoint available for the compliance documentation on our client's servers.  

Would it be possible to use that as the `fileUrl` in a PATCH/POST payload, instead of uploading via the pre-signed S3 URLs?  

That would also avoid duplicating the file and mean that any updates to the document were centralised and available without having to re-upload.

Thanks

**Comment by plittlewood-rpt** [comment]
Hi @nroper - at the moment fileUrl can only be used for document uploads/pre signed URLs as there's nowhere to store external document links. We've chatted through this issue today and agreed that perhaps we did make the wrong decision around the validation and the suggestion is to revert the recent change so that you can change status of the identityCheck entity regardless of what state the physical document is in. Will this resolve your problem?

**Comment by nroper** [comment]
Hi @plittlewood-rpt thanks for the update on this and the info regarding the use of fileUrl.

Yep, reverting the recent changes would resolve our problem.  Any idea when that might happen?  The reason for asking is that I'll be away from early next week, so would be good just to manage the client's expectations.

Cheers

**Comment by plittlewood-rpt** [comment]
We'll get this done next week. Do we need to drop the validation completely or will there always at least be some document details of some description? I think allowing pass/fail if there's no document AT ALL is probably a bad idea, but we should allow the basic info (type/description)
