### ISSUE TITLE
Document upload via pre-signed AWS URL

### ISSUE THREAD

**Issue by nroper** [reapit/foundations#6684]
**Summary**

Examples for using a pre-signed URL to upload a documentfile?

**Detail and or supporting links and screenshots**

I understand that the process for uploading a document with a file size between 6MB & 30MB is to use a pre-signed URL and that one or more temporary URLs can be requested via the `documents/signedUrl` endpoint.

The documentation says that, once the file has been uploaded, then a POST request including the URL  should be made to the appropriate platform endpoint and the platform will transfer the file to the customer's file system.

Is any example documentation available for the process of uploading the file to the pre-signed URL?  Should that be done via a curl request to the URL, including an encoded version of the file for example? If so, are there any specific headers and field names that should be used?

Many thanks

**Specification**
- Enhance Developer documentation to include commentary about the pre-signed URLs (both uploads and downloads). A screencast will probably also be useful here to demonstrate the mechanism. For the video, have a session with Holly to walk through the steps and she will record it for consistency and then we can link to it on our Youtube channel

**Comment by nroper** [comment]
> * Enhance Developer documentation to include commentary about the pre-signed URLs (both uploads and downloads). A screencast will probably also be useful here to demonstrate the mechanism. For the video, have a session with Holly to walk through the steps and she will record it for consistency and then we can link to it on our Youtube channel

@plittlewood-rpt Thanks for following up on this. Sounds great, do we get popcorn as well ;-)

**Comment by plittlewood-rpt** [comment]
Don't push it ;) 

![image](https://user-images.githubusercontent.com/30798627/165783098-6fb4cf57-5e43-4b28-9cf5-a3f63501dd91.png)

**Comment by nroper** [comment]
Hi @HollyJoyPhillips @plittlewood-rpt - could you advise on the status of this documentation please?

**Comment by HollyJoyPhillips** [comment]
Hi @nroper we should have it update this week. Thanks

**Comment by HollyJoyPhillips** [comment]
Hi @nroper, we've updated the documentation and added a short video: 

https://foundations-documentation.reapit.cloud/api/api-documentation#using-pre-signed-urls
https://www.youtube.com/watch?v=lBYzD7T5_bQ 

Let me know if you have any questions.

**Comment by nroper** [comment]
Hi Holly,

Thanks for this. 

The notes and video are very useful in terms of using Postman or Insomnia to PUT a file with a pre-signed URL and then POST an `identityChecks` record with the URL specified for the `fileUrl` property.  I've been through the process in Insomnia and have successfully added a document to a new identityChecks record and can download and open it OK from our app when viewing ID Checks for the contact.

However, the issue that I'm having is when trying to replicate the process programatically.   I don't get any errors for the PUT or POST, and a new `identityChecks` record is created with a document attached, but when I download the document and then try and open it, I get an error saying that the file can't be opened and may be damaged.  It also appears to be somewhat larger in size than when I process manually in Insomnia.

I've even used the cURL generated by Insomnia and then plugged that in to my code, but I still end up with a corrupted file.  

Would it be possible to have a http request specification for the PUT - with details of all required headers and body - ideally an example of an Axios request or similar?

Thanks
