### ISSUE TITLE
Customers can't find live app in marketplace

### ISSUE THREAD

**Issue by FrankieMalpass** [reapit/foundations#6687]
**Describe the bug**
Atkinson McLeod is reporting that they cannot find the Goodlord app in the marketplace. We have checked that the app is live and it is. We have no idea why they can't find it but obviously this means that they can't install it. 

**To Reproduce**
Steps to reproduce the behaviour eg:
1. Go to the markeplace
2. Search apps by entering 'Goodlord' 
3. Apparently Goodlord doesn't appear for the customer

**Expected behaviour**
The customer can see the Goodlord app and install it. 

**Screenshots**
If applicable, add screenshots to help explain your problem. Please ensure that screenshots do not include sensitive data such as personally identifiable information.

**Device (please complete the following information for web issues):**
 - Device: [e.g. iPhone6, PC, Mac]
 - Browser [e.g. Chrome, Safari]

**Additional context**

**Comment by HollyJoyPhillips** [comment]
Hi @FrankieMalpass, this section in the documentation should help: https://foundations-documentation.reapit.cloud/faqs#why-is-my-app-not-showing-in-the-appmarket

**Comment by FrankieMalpass** [comment]
Thanks @HollyJoyPhillips for getting back so quickly. Does this mean that they have to be moved off of the Rackspace environment before they can use the Goodlord app?

**Comment by HollyJoyPhillips** [comment]
@FrankieMalpass Yes, if you want to continue using Webhooks. If they want to know when they will be migrated (if they don't already) they can speak with their CSM.

**Comment by HollyJoyPhillips** [comment]
Hi @FrankieMalpass closing this issue as an answer has been provided. If you have any further questions please raise another ticket. Thanks. Holly
