### ISSUE TITLE
Add support for lettings properties to be embedded in the landlord response

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#669]
### Overview
We should provide the ability to embed property data within the landlord response - this would be a common shortcut a developer may want to use.

### Requirement
Add "properties" entry to the hypermedia `_embedded` collection for the response of `GET /landlords` and `GET /landlords/{id}`.

**Comment by plittlewood-rpt** [comment]
PR 1754 opened to update landlord broker
PR 1755 opened to update API documentation
