### ISSUE TITLE
GetProperties not working

### ISSUE THREAD

**Issue by skhaitan** [reapit/foundations#6694]
**Describe the bug**
Hi, Since last 1 day, when I am running my application I am getting 403 CORS error even though it was working fine 2 days back. There was no changes uploaded to the code. Also when my colleague opens the application from another country ( London, United Kingdom) it appears to be working okay and fetching all the properties. 

Below is the curl request :

curl 'https://platform.reapit.cloud/properties/?pageNumber=1&pageSize=25&sellingStatus=forSale&sellingStatus=forSaleUnavailable&sortBy=-created&metadata=metadata.sentToGazeal%20%24eq%20true' \
  -H 'sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="100", "Google Chrome";v="100"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'Authorization: Bearer eyJraWQiOiJFXC9TcnVuTzVCR0xBMk1yT3phY2RjWFkwVVdqRVB1cVB5N3hIb1FWbnJGdz0iLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJjNjBlZDQwYi0xOTIyLTQ5YmYtODI2MC1lYWMzZDBkYjZhZjEiLCJjb2duaXRvOmdyb3VwcyI6WyJBZ2VuY3lDbG91ZERldmVsb3BlckVkaXRpb24iLCJGb3VuZGF0aW9uc0RldmVsb3BlckFkbWluIiwiRm91bmRhdGlvbnNEZXZlbG9wZXIiXSwiaXNzIjoiaHR0cHM6XC9cL2NvZ25pdG8taWRwLmV1LXdlc3QtMi5hbWF6b25hd3MuY29tXC9ldS13ZXN0LTJfZVE3ZHJlTnpKIiwidmVyc2lvbiI6MiwiY2xpZW50X2lkIjoiNGhhbm5mcTM2b2lnMm0xNjhvNm9vYm1kZWUiLCJldmVudF9pZCI6IjJlNDVlMzNmLTA0ZmMtNDJiZC04MGU4LTMxYjc4ZThhN2UwYiIsInRva2VuX3VzZSI6ImFjY2VzcyIsInNjb3BlIjoiYWdlbmN5Q2xvdWRcL2NvbXBhbmllcy5yZWFkIG9wZW5pZCBwcm9maWxlIGFnZW5jeUNsb3VkXC9vZmZlcnMucmVhZCBhZ2VuY3lDbG91ZFwvcHJvcGVydGllcy53cml0ZSBhZ2VuY3lDbG91ZFwvYXBwbGljYW50cy5yZWFkIGFnZW5jeUNsb3VkXC9uZWdvdGlhdG9ycy5yZWFkIGFnZW5jeUNsb3VkXC9kb2N1bWVudHMucmVhZCBwaG9uZSBhZ2VuY3lDbG91ZFwvb2ZmaWNlcy5yZWFkIGFnZW5jeUNsb3VkXC9wcm9wZXJ0aWVzLnJlYWQgYWdlbmN5Q2xvdWRcL3ZlbmRvcnMucmVhZCBhZ2VuY3lDbG91ZFwvY29udGFjdHMucmVhZCBhZ2VuY3lDbG91ZFwvZW5xdWlyaWVzLnJlYWQgZW1haWwiLCJhdXRoX3RpbWUiOjE2NTA5NjM3MTQsImV4cCI6MTY1MDk2ODE1NCwiaWF0IjoxNjUwOTY0NTU1LCJqdGkiOiI4NjMzZmVmYi1lNzRlLTRjOTAtYjdiZC0wNzJkOTllMTdkYzgiLCJ1c2VybmFtZSI6ImM2MGVkNDBiLTE5MjItNDliZi04MjYwLWVhYzNkMGRiNmFmMSJ9.BJ9cEafm7_FEmB4wJM74cW5aXt-waeyOTPCVPfCWQkPvtDdb4pbczkXU_vXMHlN7OX4p4Um-2u6Rdg-8ntHFB1hWFwKaI1Qj2nN6ykDGVN9HkXlk4bvNrS4qJBsK3fxhGiUBXwt4VNPORs-a0b84TCXOdo6ce3NfQj1AmrXa3PbVchkSaHdCV2WoNkWbGwrMTuYWLO2zEJa3a0aY_0s44rZBvtU8_UYNyDl_pRLaKJXnSoH_fZSArPz7Y71KU73ooStpKi8v9DEEOk6Vvr4seHj0n2xiPE33ibFvZCwIXfMhBfLX0tcDKn8BFOvhoxMLqxIgOg9nRGPNg-C-7if4Rw' \
  -H 'Access-Control-Allow-Origin: *' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Referer: http://localhost:8080/' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36' \
  -H 'api-version: 2020-01-31' \
  -H 'sec-ch-ua-platform: "Windows"' \
  --compressed

**To Reproduce**
Steps to reproduce the behaviour eg:
1. Go to '...' https://reapittest.gazeal.co.uk, login
2. Click on '....' login to Gazeal as dagent/gaz123
3. Scroll down to '....' /table and see properties are not getting loaded. (It is possible that it will load for you but for me I am getting error. please see the screenshot. 
![image](https://user-images.githubusercontent.com/5029236/165267515-d892c5b9-ecce-42d7-9b33-d2d3bf0fb211.png)

What could have gone wrong? I am getting a CORS error from reapit API console. 

![image](https://user-images.githubusercontent.com/5029236/165267955-4cd92d82-4ec7-408f-8c72-05935cf9ce26.png)

I tried restarting my router, clearing cache, another browser, phone but everywhere its the same issue. 

**Expected behaviour**

It should display the list of properties from Reapit

**Screenshots**
If applicable, add screenshots to help explain your problem. Please ensure that screenshots do not include sensitive data such as personally identifiable information.

**Device (please complete the following information for web issues):**
 - Device: [e.g. iPhone6, PC, Mac]
 - Browser [e.g. Chrome, Safari]

**Additional context**

**Comment by plittlewood-rpt** [comment]
@skhaitan this should now be resolved. Please can you check and confirm back to me please
