### ISSUE TITLE
Update App not working from Developer platform

### ISSUE THREAD

**Issue by skhaitan** [reapit/foundations#6696]
**Describe the bug**
Hi, When I am trying to edit the app to edit the redirect URL it says I cannot save it as it shows "Cancel Revision" and when I do Cancel Revision it shows the request cannot be cancelled, Trying to edit "Gazeal App".

It is very urgent as our whole development has stopped because of this issue

**To Reproduce**
Steps to reproduce the behaviour eg:

**Expected behaviour**

**Screenshots**
If applicable, add screenshots to help explain your problem. Please ensure that screenshots do not include sensitive data such as personally identifiable information.

**Device (please complete the following information for web issues):**
 - Device: [e.g. iPhone6, PC, Mac]
 - Browser [e.g. Chrome, Safari]

**Additional context**

**Comment by plittlewood-rpt** [comment]
@skhaitan please can you try this again and let me know if you have been able to cancel the revision. We will work to address the underlying cause

**Comment by plittlewood-rpt** [comment]
Hi @skhaitan please can you confirm if this is now working as intended?
