### ISSUE TITLE
Unable to push and pull documents for customers WAS & IMG 

### ISSUE THREAD

**Issue by pnGL20** [reapit/foundations#6697]
Customers are having issues downloading docs when they push through to Reapit after a tenancy has been completed, when our Dev support team tried to manually do this we received the following error messages. 

We've tried to ReapitClient createDocument failed for reapitCustomerId WAS. Error: {"statusCode":500,"dateTime":"2022-03-24T17:22:02.5929076Z","description":"An unexpected error has been encountered when fulfilling this request. This incident has been logged and will be investigated. Please try again

["message" => "reapit","pms_tenancy_id" => "BUS220035","total_files" => 6,"file" => ["url" => **URL has been Redacted**=> 1963316],"exception" => ["message" => "ReapitClient createDocument failed for reapitCustomerId IMG. Error: {"statusCode":500,"dateTime":"2022-04-04T15:13:58.3437145Z","description":"An unexpected error has been encountered when fulfilling this request. This incident has been logged and will be investigated. Please try again."}"]]

This has been ongoing for over a month now with both customers being sent between Reapit and GL, could we investigate and resolve asap.

**Comment by plittlewood-rpt** [comment]
Hi @pnGL20 thanks for reaching out. This is something that our monitoring tools picked up and is with another team currently. IMG should already be resolved (7th April) and WAS should be resolved this morning. Please can I ask you to keep an eye on your own logs and confirm if these problems stop occurring?

**Comment by pnGL20** [comment]
Thank you Pete, does this apply to new tenancies or will it work for all?

**Comment by plittlewood-rpt** [comment]
The underlying issue was caused during a migration of file assets from our legacy system to our new environment. I have asked the team concerned to audit any other customer configurations that may be incorrect as a result of the same problem so we should find any others and be able to deal with them, but if you do run into trouble with any other customers please just let  us know

**Comment by pnGL20** [comment]
Brilliant thank you!
