### ISSUE TITLE
Incremental Property Feed

### ISSUE THREAD

**Issue by DanSayer** [reapit/foundations#6707]
Please can you detail how i would request all property for a client to propagate a register, and then the call i can make 1 hour later to get all changed properties

For example. I need all non-archived, internet advertised property matching for sale and to let on my initial propagation
ie: 

https://platform.reapit.cloud/properties/?lettingStatus=toLet&marketingMode=sellingAndLetting&sellingStatus=forSale&internetAdvertising=true&fromArchive=false

(which returns 0 properties in the sandbox!! (can i mix sales and lettings status's??)

The next call specifies a modifiedfrom time but i need all properties that have changed out of the original scope (for deletion) and properties that need to beadded or updated. What i don't want to do is call the whole register again and compare to our uploaded properties to work out what needs to be deleted/modified

This would be a very lean system allowing small, regular data calls.

**Comment by AshDeeming** [comment]
Hi @DanSayer 

From a quick glance at the call example - you appear to be specifying each of the marketingModes - you shouldn't need to specify this in the call if you wish to return them all. 
![image](https://user-images.githubusercontent.com/61687775/165538195-5694c384-031b-4cc4-9750-f74dd96797fc.png)

With regards to updating these, you may wish to review the properties modified parameter. The below video may be of use to navigate the swagger docs: https://www.youtube.com/watch?v=JGrUHbhoRgY&t=2s

**Comment by DanSayer** [comment]
I just need to see all modified properties from a specific date/time regardless of archive/internet advertising or status. If i have that list i can work out programatically which ones to delete/update or add

**Comment by AshDeeming** [comment]
Hi @DanSayer 

In order to include archive records, these will need to be a 2nd call. 

It may be easer to utilise the property status as most clients will use these i.e. start as MA, then move to For Sale - Available once instructed etc & then end of Completed/Sold before Archiving. 

This would then allow for an initial sync of available properties stored your end, followed by an hourly* sync with any changes to the status.

**Comment by AshDeeming** [comment]
Hi @DanSayer 
I'll close this ticket now but please open another ticket if you have further questions or issues.
