### ISSUE TITLE
Retrieve tenants according to their startDate

### ISSUE THREAD

**Issue by asif-sms-speedway** [reapit/foundations#6708]
I was searching for tenants based on their "created" date using this Get request : https://platform.reapit.cloud/tenancies?createdFrom=2021-04-27T07:45:40Z
and it worked fine.

Our requirement is to instead search for tenants using their "startDate" field and I tried running this Get request: https://platform.reapit.cloud/tenancies?startDateFrom=2023-04-27T07:45:40Z
But this didn't seem to work because I am guessing that the startDate value is being ignored.

Am I doing anything wrong? Or is the functionality to search using "startDate" field isn't yet available?

**Comment by Speedway1** [comment]
This ticket can be closed. The filter doesn't exist. We will create a request to add the filter.
