### ISSUE TITLE
how to use logout button clickable in a page

### ISSUE THREAD

**Issue by emspratap** [reapit/foundations#6709]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour eg:

**Expected behaviour**

**Screenshots**
If applicable, add screenshots to help explain your problem. Please ensure that screenshots do not include sensitive data such as personally identifiable information.

**Device (please complete the following information for web issues):**
 - Device: [e.g. iPhone6, PC, Mac]
 - Browser [e.g. Chrome, Safari]

**Additional context**

**Comment by AshDeeming** [comment]
Hi @emspratap 
I can't see that any details have been populated other than the subject. 
Please see the documentation around app development & revert with more information if your question is not covered; https://foundations-documentation.reapit.cloud/app-development

**Comment by emspratap** [comment]
> Thank you for taking the time to report a bug. We prioritise bugs depending on the severity and implications, so please ensure that you have provided as much information as possible. If you haven’t already, it really helps us to investigate the bug you have reported if you provide ‘Steps to Replicate’ and any associated screenshots. Please ensure any personal information from the production database is obscured when submitting screenshots. This issue will be reviewed in our weekly refinement sessions and assigned to a specific project board. We may also update the ticket to request additional information, if required. For more information on our processes, [please click here](https://foundations-documentation.reapit.cloud/dev-requests)

Hi, thanks for your reply, what i want to use of logout session button in a page.

How i can use this reapit functionality ?

is it possible please me help out of it?

**Comment by emspratap** [comment]
> Hi @emspratap I can't see that any details have been populated other than the subject. Please see the documentation around app development & revert with more information if your question is not covered; https://foundations-documentation.reapit.cloud/app-development


Hi, thanks for your reply, what i want to use of logout session button in a page.

What should be the code for it. i have tried in different ways to do this.

How i can use this reapit functionality ?

is it possible please me help out of it?

please see the screenshot below to understand more about the logout button.

![Screenshot from 2022-04-28 13-56-16](https://user-images.githubusercontent.com/98327017/165710816-46bee07b-e90f-43a8-809d-ee68a02a52e1.png)

**Comment by AshDeeming** [comment]
Hi @emspratap 
If you are using a Connect session the below doc may be of use: https://foundations-documentation.reapit.cloud/app-development/connect-session
If however you are using Reapit Connect, please see the below;
https://foundations-documentation.reapit.cloud/api/reapit-connect

You will need to provide a logout URI for your app, this can be added via the app details page.

**Comment by emspratap** [comment]
Thank you.

i need another help?

how can i get property image?

**Comment by AshDeeming** [comment]
Hi @emspratap 
Please confirm you are using the /propertyImages/ endpoint?

**Comment by AshDeeming** [comment]
Hi @emspratap -as there has been no response, i'll close this ticket.
