### ISSUE TITLE
Management fee

### ISSUE THREAD

**Issue by elizabethhamlin** [reapit/foundations#6735]
Using Reapit to get our data but I cannot pull the management fee field

**Specification**
- Project: Analytics Schema
- Add new properties to properties output `lettings_management_fee_percentage` and `lettings_management_fee_amount` that expose the management fee set on the property. This should only be set when the property role is set to Managed. Only one of these fields will ever be set, as is the case with the corresponding sales fields.
- Ensure Analytics Schema Documentation is updated

**Comment by AshDeeming** [comment]
Hi @elizabethhamlin 

Please see the REST API section of the Developer portal - https://developers.reapit.cloud/swagger

Under Properties/  there is a letting section relating to said property, within there is the below;
![image](https://user-images.githubusercontent.com/61687775/173358945-b28fc5d8-e4b7-4164-a988-99cdeb8b938a.png)

**Comment by elizabethhamlin** [comment]
Hi

Sorry but this is not present for me.

In Power BI I can see the following (none of these list the management fee) –

***@***.***

When I look at REST API there is also no where under these that shows the management fee –

***@***.***

Please advise of the exact location as I cannot locate this at all.

Thanks

Elizabeth Hamlin MARLA
Reporting and Systems Manager
The Lomond Group

Tel: 07443 188920
Email: ***@***.******@***.***>
Web: https://lomond.group<https://lomond.group/>

***@***.***

**Comment by AshDeeming** [comment]
Thanks @elizabethhamlin 

As this relates to an Analytics schema field request, i've updated the ticket for the relevant team to review.

**Comment by plittlewood-rpt** [comment]
Hi @elizabethhamlin 

Two new properties have now been added to the PROPERTIES view in the Analytics Schema (LETTINGS_MANAGEMENT_FEE_AMOUNT and LETTINGS_MANAGEMENT_FEE_PERCENTAGE for fixed fee/% fee respectively). To refresh your copy of the schema, you can hit the Refresh Share button in the Data Warehouse AppMarket app.

Updated documentation for the analytics schema is available at https://developers.reapit.cloud/analytics-schema-docs

Thanks
Pete

**Comment by elizabethhamlin** [comment]
Hi 
Sorry for the delay but this is not completed. I have refreshed the data and the management fee and % are missing from the schema
