### ISSUE TITLE
App working in Sandbox but not live environment

### ISSUE THREAD

**Issue by vibrantenergy** [reapit/foundations#6746]
Our app is currently working in the Reapit Sandbox environment, however in the live environment we get an error 'Property Address not found for id' in the live environment.

Why would this be the case?

**Comment by AshDeeming** [comment]
Hi @vibrantenergy 

Please confirm you are toggled to the correct dataset via your profile page:
https://developers.reapit.cloud/settings/profile

Thanks & regards

**Comment by vibrantenergy** [comment]
hi @AshDeeming - there's no option showing to do this - The only info on this page is name, job title and github username?

**Comment by AshDeeming** [comment]
Hi @vibrantenergy 
Thanks for checking & advising - Please could you provide the query your running including the requested prop ref & i'll refer to the wider team for review.

**Comment by HollyJoyPhillips** [comment]
Hi @vibrantenergy, are you using the interact swagger to try and return that property? If not and it's a server side request, what is the property reference and what is the error/message that is being returned?

**Comment by vibrantenergy** [comment]
hi @HollyJoyPhillips - here's the response back from our dev team

a.	We don’t have access to the live swagger, we only have access to the UAT swagger and it works from there.
b.	Its all properties (I believe)?
c.	The error returned was the one on our application (Property not found).

**Comment by HollyJoyPhillips** [comment]
HI @vibrantenergy, please can you ask your dev team to provide the CURL request they are making and the exact error? Thanks.

**Comment by HollyJoyPhillips** [comment]
HI @vibrantenergy The 2 screenshots are referencing 2 different property ID's and 2 different requests times. The first looks to be a sandbox property reference. 

I've looked at the request made around 13:57 for the property reference (ABS220043) and it is passing the reapit-customer header as SBOX. You will need to pass the customer header as the organisation that has installed your app. 

More information can be found here: https://foundations-documentation.reapit.cloud/api/api-documentation#accessing-customer-data
Also here https://foundations-documentation.reapit.cloud/faqs#installation

**Comment by UKMKEA1** [comment]
Hi Reapit, when a user accesses our application they are authenticated and therefore we “think” we have the correct “reapit-customer” (see screenshot below showing “NEW-GVEP”). 
![image](https://user-images.githubusercontent.com/105654459/169283066-8665971a-f580-45d9-ad56-5e90ffc2ce7d.png)

 

When we make the call to the Property method we do not explicitly add any header information to the request as we would have assumed this would have been taken from the user token (which seems to be set correctly, as per the screenshot).

Have we missed something?
As the screenshot above shows a validated user (Adam Baker) trying to get the property details of a property he already has open in Reapit (but our Property request says “Property Address Not Found For ID”)?

**Comment by HollyJoyPhillips** [comment]
Hi @UKMKEA1 That user can only access properties that is associated to his office 'AC Cheadle Team 1'. That properties has the main office set as 'Abersoch'.

**Comment by UKMKEA1** [comment]
The user can access the property details in Reapit but when they launch our app the property details are not being passed over, hence the error.  If the user can access in Reapit then the should be able to access in our App?

**Comment by HollyJoyPhillips** [comment]
No, office grouping has been setup for that office. Office grouping is applied to the Platform API and doesn't effect the security in Agency Cloud. 

If you launch the app from a property assigned to AC Cheadle Team 1 it will work.
