### ISSUE TITLE
Why are some fields from the AgencyCloud not available in the Foundations API?

### ISSUE THREAD

**Issue by ianyoung** [reapit/foundations#6754]
**Summary**
I am trying to retrieve details entered into the AgencyCloud desktop application but they do not appear to be available via the Foundations API. 

**Detail and or supporting links and screenshots**
The details I'm looking to retrieve appear in the Marketing Screen of the AgencyCloud software and include:

- Property URL
- TRP
- Summary Text

<img width="1374" alt="reapit-agencycloud-marketing-details" src="https://user-images.githubusercontent.com/66717/166689793-3b3c874b-a565-4be7-a368-ef0a31505d78.png">

How may I access these fields via the Foundations API?

**Specification**
- Customer configuration object for SWF
- Add two fields to the allowed semi structured fields that correlate to the Summary Text and TRP number (I think summary text is already set up)
- Nothing to do on the URL field as this is already exposed, but they are not being explicitly set in AgencyCloud

**Comment by AshDeeming** [comment]
Hi @ianyoung 

Please note that custom 'extraDescriptions' require a custom 

**Please populate the below for this to be associated to the relevant team;
In order for us to grant access to Semi-structured 'extras' field data, please provide the following information in this request:

- The name of the customer you represent
- The name of every field you need surfaced (if known)
- A screenshot of of the field(s) you require in the agency cloud user interface
- A short use case as to why you require this data**


Please see the below article relating to the URL too;
https://foundations-documentation.reapit.cloud/whats-new#property-url

**Comment by ianyoung** [comment]
Hi @AshDeeming.

> The name of the customer you represent
Swoffers (SWF)

> The name of every field you need surfaced (if known)
TRP, Summary Text

> A screenshot of of the field(s) you require in the agency cloud user interface
Provided above

> A short use case as to why you require this data
I need to extract a TRP value for display on the website.
I need to extract the Summary Text for display on the website. Strangely what appears in the Marketing Details window doesn't seem to match what is in `summary` or `description` fields in the API.

> Please see the below article relating to the URL
Thanks. I'm seeing `null` values for all properties in the system in the `url` field. I'll confirm with the client that those fields are definitely populated.

**Comment by plittlewood-rpt** [comment]
HI @ianyoung 

To access the Summary Text and TRP you will need to use the extrasField query string parameter as follows:

To access summary text: `GET /properties?extrasField=pSummary`
To access TRP: `GET /properties?extrasField=pTRP`
To access both: `GET /properties?extrasField=pSummary&extrasField=pTRP`

I have just updated the customer's configuration so you can access these fields in the Platform. It can take 15 minutes or so for the changes to sync across the Platform estate.

The URL field is already exposed, however the CRM makes use of a templating mechanism where it will attempt to build the URL in memory for a user to click on. In this scenario the URL is not actually stored anywhere in the database (and it will appear in grey text). The user would need to explicitly store it in the database for it to be accessible in the API (in which case it will appear in black text on the screenshot above)

Thanks
Pete
