### ISSUE TITLE
Waiting for a revision approval for a privately published app - permissions changes.

### ISSUE THREAD

**Issue by bakaevd** [reapit/foundations#6758]
Hi!

Hi!  I had to add another set of permissions to the MovePal Sync privately listed app and submitted a revision last week.  It hasn't been approved yet.   

I was trying to add the journal and enquiries permissions (Read + Write).

Online it still shows "Revision Outstanding".  Under Edit App->Permissions I actually don't see the permissions added even though I'm sure I added them when submitting the revision.

When can this be approved?  Do I need to raise a GitHub ticket every time?  

Thank you.

**Comment by AshDeeming** [comment]
Hi @bakaevd 
I've just sent you an email. 
I'll close this ticket.
