### ISSUE TITLE
`Type` Field data missing - Client (Hus & Haus - HAH)

### ISSUE THREAD

**Issue by rajeshwl** [reapit/foundations#6790]
**Describe the bug:** The client has the `Type` attributes value as `**Villa**`  for nearly 1500 properties. Unfortunately we are not receiving this value in the PAAS API. Can you please update this values in the API. The data is currently available in the existing API(SOAP). 

**NOTE: We have migrated the API in live website.  It will be helpful if you prioritize the issue.**

![reapit-web](https://user-images.githubusercontent.com/14073702/166925247-6817ad36-9fd2-43e6-b915-31ea590f9334.png)

![reapit-paas](https://user-images.githubusercontent.com/14073702/166925238-405aab08-470f-4b11-a503-0ac6897fac81.png)

Similarly we have other type values missing for commercial properties as well. 
```
Retail
Showroom
Office Space
Warehouse
Commercial Villa
Labour Camp

```

**Specification**
- Projects: Reapit.Services.Departments, Reapit.Services.Properties, Reapit.Services.Applicants
- Add `Villa` as property type (surfaced as `villa` in respective models)
- Schedule and hold a discussion around the commercial types as the department configuration for Commercial differs a lot from the UK and we can't just keep adding to the mappings. Outcome here is another ticket to look at implementing a more long term solution

**Comment by AshDeeming** [comment]
Hi @rajeshwl 

These attributes are custom to the Client therefore we require a Semi-structured 'extras' field request.

Please populate the below if not already included above & I'll associate this to the relevant team to complete;
In order for us to grant access to Semi-structured 'extras' field data, please provide the following information in this request:

- The name of the customer you represent
- The name of every field you need surfaced (if known)
- A screenshot of of the field(s) you require in the agency cloud user interface
- A short use case as to why you require this data


Thanks,

**Comment by plittlewood-rpt** [comment]
PRs opened to add villa to supported property types list. Discussion to be had around commercial dept

**Comment by plittlewood-rpt** [comment]
@rajeshwl Villa will now be being exposed as a property type for this customer. We need to have a more thorough look at how their commercial department is set up

**Comment by rajeshwl** [comment]
Thanks @plittlewood-rpt . We will check on the Villa type properties. Let us know once you have made the setup for commercial department.

**Comment by plittlewood-rpt** [comment]
Remainder of ticket to be discussed as part of #6910
