### ISSUE TITLE
Missing Fields

### ISSUE THREAD

**Issue by Karltatlerdata** [reapit/foundations#6792]
I am attempting to view Chain, Mortgage and Solicitor information through Data Warehouse. However the Analytic fields end at 'Mortgage ID' and 'Solicitor ID' without letting me get the actual name for both fields. As well as this I can not see chain information for our agreed sales and this would be highly beneficial! are there potentially missing fields in the Analytics schema that I am missing or don't have access to?

**Specification**
- Project: Analytics Schema
- Check that mortgage and solicitor ids are primary keys that can be used to join back to the contacts table
- Check that the documentation describes the relationship between mortgage id/solicitor id and the contacts table, it could be that this was missed
- Add new fields to surface offers.vchain and offers.bchain as VENDOR_CHAIN_LINK_ID and BUYER_CHAIN_LINK_ID respectively which contain generated keys to the next link in the chain
- Ensure new fields are appropriately documented in the analytics schema

**Comment by plittlewood-rpt** [comment]
Hi @Karltatlerdata  - it would be useful to understand more about what you are wanting to achieve with the data warehouse in respect of chains and sales progress. As you've already found, the solicitor for both the buyer and vendor is already available in the Offers table, as is the id of the company carrying out the mortgage survey/lending etc. To get the name of the companies involved, you would need to join back to the contacts table using the id to do the join. This is detailed in the Offers module in the Warehouse documentation you can view in the [DeveloperPortal](https://developers.reapit.cloud/analytics-schema-docs)

**Comment by Karltatlerdata** [comment]
Hi,

Essentially I want to monitor chain information linking it to properties and our pipeline figures. As an example if I can split out a property pipeline into the type of chain the property is a part of (Open or Closed). This can be accessed through Power reports in a worst case scenario, but under my OFFERS section of my Scheme I cant get any chain information.



Edward Francis
Data Analyst
DDI: 0151 342 0458

[signature_1805979853]<https://www.karltatler.com/>

[signature_1271568633]<https://www.karltatler.com/pages/sell?request-valuation>

***@***.***,-3.1687615,12z/data=!4m8!4m7!1m0!1m5!1m1!1s0x487ad7f52a06699b:0x4e232142b9104029!2m2!1d-3.098722!2d53.329358>

[signature_549509221]<https://www.facebook.com/karltatler>

[signature_1915107555]<https://www.instagram.com/karl_tatler/>

[signature_21968547]<https://twitter.com/karl_tatler>

[signature_477271765]<https://www.linkedin.com/company/karl-tatler-estate-agents-&-lettings>

***@***.***<https://www.youtube.com/channel/UCZsPDw8R8MwnbklZXcEBugA>

**Comment by plittlewood-rpt** [comment]
PL/HP to review further as a milestone. Need to understand best format for chain data before committing to updates in the analytics schema

**Comment by plittlewood-rpt** [comment]
Chain information now available in the offers table of the analytics schema. Please refer to updated analytics schema documentation for further details
