### ISSUE TITLE
Reapit login is not working in google chrome

### ISSUE THREAD

**Issue by emspratap** [reapit/foundations#6818]
Hi Support Team,

I am trying to implement the reapit API but Reapit login is not working in google chrome.

Except google chrome , it is working in all other browser.
Each time it is creating a new code , you can get an idea from below screenshoot.

Please help me on it, i halt my development for this issue.

![Screenshot from 2022-05-04 20-30-12](https://user-images.githubusercontent.com/98327017/167418509-5820915e-dad4-4d18-b9cc-75b3c05846a1.png)
![Screenshot from 2022-05-04 20-30-14](https://user-images.githubusercontent.com/98327017/167418538-59b716
![Screenshot from 2022-05-04 20-30-15](https://user-images.githubusercontent.com/98327017/167418553-cad013c3-da2e-4eea-9822-3f3c48b2d90a.png)
b2-581c-4e83-b54f-ea2fc90acb51.png)

**Comment by AshDeeming** [comment]
Hi @emspratap 

As Per #6756 - please provide the code used so this can be reviewed by the relevant team.

**Comment by emspratap** [comment]
> Hi @emspratap
> 
> As Per #6756 - please provide the code used so this can be reviewed by the relevant team.

Hi @AshDeeming,

i am happy to share you the code, please check

const connectHasSessionCallback = (reapitConnectBrowserSession) => {
        reapitConnectBrowserSession.connectSession().then(session => {
          console.log('Session is22', session)
          sessionStorage.setItem('logdata',session);
          
          //console.log(session.loginIdentity.email, session.loginIdentity.developerId)
          fetch('https://platform.reapit.cloud/properties', {
              headers: {
                'Content-Type': 'application/json',
                'Authorization': `Bearer ${session.accessToken}`,
                'api-version': '2020-01-31'
              }
            })
          .then(res => res.json())
          //.then(properties => document.getElementById("jsondata").innerHTML = JSON.stringify(properties._embedded[1]))
          .then(properties => document.getElementById("properties").value = JSON.stringify(properties._embedded),)
          .then(properties => document.getElementById("email").value = session.loginIdentity.email)
          //.then(properties => console.log('properties are', properties))
        })
          
      }
      ReapitConnectComponent && new ReapitConnectComponent({
        connectClientId: '28f4q8cqnr5712c2es7oh1ampu',
        connectUserPoolId: 'eu-west-2_eQ7dreNzJ',
        connectOAuthUrl: 'https://connect.reapit.cloud',
        connectLoginRedirectPath: '/reapit',
        connectLogoutRedirectPath: '/reapit',
        rootElement: '#reapit-connect-component',
        connectHasSessionCallback,
        companyName: 'My Company',
      })

**Comment by AshDeeming** [comment]
Hi  @emspratap 
Please can you confirm the app name so i can investigate further.

**Comment by emspratap** [comment]
> Hi @emspratap Please can you confirm the app name so i can investigate further.

Hi @AshDeeming ,

Sure, please check the below screenshot to know about app name - "HiveTestNew1"


![Screenshot from 2022-05-18 09-43-47](https://user-images.githubusercontent.com/98327017/168956078-0819897f-4a70-466a-a9d9-45836b324eb3.png)

**Comment by emspratap** [comment]
Hi @AshDeeming ,

It's been two days late but still not get my solution, please do it fast for me, our client is awaiting for this ?

Thanks,
Pratap Kumar

**Comment by AshDeeming** [comment]
Hi @emspratap 
Thanks for this - it appears your redirect & sign out URI's are pointing to the same place which could be causing you to be stuck in a loop: 

![image](https://user-images.githubusercontent.com/61687775/169484757-ca296668-e6d6-4e61-9364-dfa6c0fea70e.png)


https://foundations-documentation.reapit.cloud/troubleshooting/reapit-connect#reapit-connect

**Comment by emspratap** [comment]
Hi,I tried to change this url but no luck.Sent from Android deviceOn May 20, 2022 2:34 PM, Ash ***@***.***> wrote:
Hi @emspratap
Thanks for this - it appears your redirect & sign out URI's are pointing to the same place which could be causing you to be stuck in a loop:

https://foundations-documentation.reapit.cloud/troubleshooting/reapit-connect#reapit-connect

**Comment by AshDeeming** [comment]
Hi @emspratap - Are you receiving an error message or a notification to indicate why you can't change the URL?

**Comment by emspratap** [comment]
Hi @Ash,No error message or notification is showing.I told you,app is working fine in other browser except chrome browser.If you think there is an issue with url redirect then how it is working in other browser and client is using now.Please do something from your sideOn May 20, 2022 3:20 PM, Ash ***@***.***> wrote:
Hi @emspratap - Are you receiving an error message or a notification to indicate why you can't change the URL?

**Comment by AshDeeming** [comment]
Hi @emspratap 
Please can you confirm which client is using this as the app is not listed currently

The two URIs need to be different in order for the flow to work correctly.
