### ISSUE TITLE
Access to information on the user of an Agencycloud CRM App

### ISSUE THREAD

**Issue by ricardo-jsd-santos** [reapit/foundations#6821]
I'm trying to scope the implementation of an Agency CRM app that requires access to the information on the estate agent/user that started/invoked the app. The information required is the user's email, first and last name, and ideally the company associated with that agent. 

The target use case is to allow estate agents to send affiliate links to applicants. I've looked at the documentation of both Desktop API and REST API, but it is not clear how it would be possible to access that user/estate agent information.

Could you help clarify?

**Comment by AshDeeming** [comment]
Hi @ricardo-jsd-santos 

I believe you are referring to the AgencyCloud user i.e. Negotiator - Please see the API Swagger page - Negotiators ;
https://developers.reapit.cloud/swagger

**Comment by AshDeeming** [comment]
Hi @ricardo-jsd-santos 
I'll close this ticket due to no further response. Any further issues, please create a new ticket.
