### ISSUE TITLE
Can an Agencycloud CRM app add content to communications with applicants

### ISSUE THREAD

**Issue by ricardo-jsd-santos** [reapit/foundations#6822]
I'm developing an app that ideally would add affiliate links to communications sent by estate agents to applicants. I understand that Agencycloud CRM handles such communications, but I was not able to find a 'Desktop Type' that supports that scenario (from the documentation https://foundations-documentation.reapit.cloud/api/desktop-api#desktop-types).

Is adding information to applicant communications supported by agency cloud? And if so, could you point to the relevant information?

Thanks and regards.

**Comment by AshDeeming** [comment]
Hi @ricardo-jsd-santos 

Please could you provide examples of the types of communication you require?

**Comment by AshDeeming** [comment]
Hi @ricardo-jsd-santos 
I'll close this ticket due to no response however please open a new ticket if you have another question.
