### ISSUE TITLE
Update property images service to be able to generate public URLs for JET SMB customers

### ISSUE THREAD

**Issue by plittlewood-rpt** [reapit/foundations#6825]
**Background context**
The property images service currently explicitly only generates public URLs to assets.reapit.net. We are starting to roll out platform to JET SMB customers which has a different URL structure and so we will need to be able to differentiate between the two base URIs (assets.reapit.net and assets.jetsoftware.co.uk for Reapit and JET respectively) based on the customer configuration

**Specification**
- Project: Reapit.Packages.PlatformIdentityManager
- Add new entry to CustomerConfiguration for `PublicAssetsLocation` - which should default to https://assets.reapit.net when not set. This will store the base URI to the assets for the customer. When setting this value, we should format it correctly (remove trailing slashes OR make sure there is a trailing slash) so that when we come to use it in the property images service we don't have to perform these checks

- Project: Reapit.Services.PropertyImages
- Alter mechanism in `PropertyImageInfoHelper` class that generates the public URL to utilize the new property in the PlatformIdentity.CustomerConfiguration object. The result should be a configurable public assets location which can feed into the JET/SMB Foundations deployment process
- PL to update AA on process once this is complete
- PL to manage update to customer configuration for customer MRC who logged original ticket.

**Comment by aalim405** [comment]
@plittlewood-rpt - using database names may not be a watertight approach considering we may standardize database names as part of the migration to AWS.

**Comment by plittlewood-rpt** [comment]
@aalim405 @rpt-pneale We need to have a collective discussion about this to figure out how we move forwards with SMB customers.

**Comment by plittlewood-rpt** [comment]
Have held a discussion around this today, follow up discussion this afternoon
