### ISSUE TITLE
Notifications not being generated for Active Webhook from SBOX

### ISSUE THREAD

**Issue by s1mtm** [reapit/foundations#6827]
**Problem**
Webhooks not being received from SBOX.  
On looking at the transaction Logs for today (10 May 2022), they are empty when we are expecting some logs.

**To Reproduce**
Go to the Reapit > Webhooks > transaction logs
Select the app
Set the from and to dates to today.

**Expected behaviour**
See a list of logs for today.

**Additional context**
The webhooks seemed to be working yesterday

Last transaction log received: 2022-05-09T08:15:45.336+00:00
Vendor modified
MKT220483

**Comment by s1mtm** [comment]
Hi, 
Thanks for looking into this. 
We are now getting new webhooks through, however the Reapit API transaction logs are still currently empty.

**Comment by plittlewood-rpt** [comment]
Hi @s1mtm thanks - it looks like there might be a strange bug in the UI where it's not requesting the correct data. I've just been able to get some data to come back by manually setting the To date to 12/05/2022 and then switching between apps. Can you try the same and let me know the result? I'll speak to our frontend team about it.

**Comment by plittlewood-rpt** [comment]
Thanks - will get this logged with our frontend guys

**Comment by plittlewood-rpt** [comment]
@HollyJoyPhillips can you tag the new ticket with 6827 please so they are linked :)

**Comment by HollyJoyPhillips** [comment]
@plittlewood-rpt done :)  https://github.com/reapit/foundations/issues/6846
