### ISSUE TITLE
Deep Dive into Contact Categories

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#6829]
Relates to: https://github.com/reapit/foundations/issues/6539

The ticket mentioned above asks for exposure of contact category data in the contacts API. There is currently no support for this.

Before we can embark on the journey of enhancing the API, we need to understand the AgencyCloud behaviour, and also consider this feature on a more global scale (rather than just AC).

Specification
- Deep dive contact categories functionality in AgencyCloud (contacts screen -> Categories & Mailings tab)
- Understand how categories are configured, and where this data is stored
- Understand how categories are assigned to contacts, and how the data is stored
- Understand any gotchas due to category nesting. Is it possible to have a global selector, or are there explicit values stored in the database regardless of how the checkbox values are arranged
- Outcome of this ticket is a rough API design

**Comment by plittlewood-rpt** [comment]
Logged implementation tickets #6971 and #6972
