### ISSUE TITLE
Internal server error on brochure API call

### ISSUE THREAD

**Issue by Vytautas-Unrvld** [reapit/foundations#6851]
**Describe the bug**
When making API call to retrieve brochure 'internal server error' happens 
![image](https://user-images.githubusercontent.com/102576931/168034096-9985e56c-ce20-4b01-8f6d-665f3d3efd9f.png)

**To Reproduce**
Steps to reproduce the behaviour eg:
1. Make authenticated call to https://platform.reapit.cloud/documents/OXF21000266/download
2. As response it returns internal server error

**Expected behaviour**
It should return brochure file.

**Device (please complete the following information for web issues):**
 - Device: [PC]
 - OS: [Windows 10]
 - Browser [Edge]
 - Version [101.0.1210.39 (Official build) (64-bit)]

**Additional context**
Only certain brochure IDs fail
Failing ID Example:
OXF21000266
OXF21000527

Working ID Example:
OXF17000713

Ids are retrieved from Reapit API, so they are present on the system.

**Comment by Vytautas-Unrvld** [comment]
Hi @AshDeeming property in question is: oxf210073
other examples of not working include: 
oxf210049
oxf210132
oxf200109
oxf200148

Also here's property that doesn't have the issue: oxf170066

**Comment by AshDeeming** [comment]
Hi @Vytautas-Unrvld  - please also note that if these codes relate to the clients data, the app will need to be installed beforehand to access. The below video may be of use; 
https://www.youtube.com/watch?v=EJWB5u1ja_U

**Comment by Vytautas-Unrvld** [comment]
@AshDeeming I'm not aware of Sandbox environment, so we're most likely talking about live database here.

**Comment by AshDeeming** [comment]
Thanks @Vytautas-Unrvld 
Just to confirm - has the client, who's data you're attempting to download, got your app installed?

**Comment by AshDeeming** [comment]
Thanks @Vytautas-Unrvld 
Could you advise your app name please?

**Comment by pmonno** [comment]
Hi @AshDeeming the app is "Carter Jonas Website Integration".
![image](https://user-images.githubusercontent.com/106077049/170017517-8301bf30-3558-457a-9ff5-ebd3986f3414.png)

**Comment by RWilcox-Reapit** [comment]
Hi @pmonno, @gmortlock and @Vytautas-Unrvld ,

We have recently resolved some file location issues our end related to the documents download endpoints. 
I've just tested the failing files listed in the ticket and are now able to download them. 

If you see this issue elsewhere please let me know. I'll leave this ticket open until you confirm the fix.

Thanks,
Ryan

**Comment by pmonno** [comment]
@RWilcox-Reapit we will need to reopen this ticket - after testing, the pdfs still aren't loading for us

https://uat.carterjonas.co.uk/house/for-sale/oxford/oxf210049
https://uat.carterjonas.co.uk/api/downloadBrochure?id=OXF21000527
