### ISSUE TITLE
Missing fields in API + request for additional fields in the API

### ISSUE THREAD

**Issue by scruffmcduff** [reapit/foundations#6853]
We seem to be missing fields in a API feed

See client details below.
Estate Agency Name: Bancroft Property
Reapit Customer ID: ASZ

We do not get the following fields coming through into the API

1. Property Type
2. Property Style etc
See https://share.getcloudapp.com/04uEp45Y

We would also like to request permission for the following fields to be enabled to come through the API
Number of units
See https://share.getcloudapp.com/04uEp45Y

Extra description fields including Directions, Situation and Advert text
https://share.getcloudapp.com/YEurLnkq

Many Thanks

**Comment by plittlewood-rpt** [comment]
Hi @scruffmcduff - the vast majority of those property attributes should be coming back to you in the API. Can you provide an example of a property where these are not being returned. It's worth pointing out here that not all attributes are supported by the Platform, however you can see which options you can expect to get back for any given customer by calling `GET /departments`

We will review the rest of this ticket in our refinement session tomorrow.

**Comment by scruffmcduff** [comment]
Sure please see attached XML of one of the properties.
I have also attached a word document showing what fields were filled in on the Reapit platform for this property. Most of the fields are just numbered from 1 upwards.

FYI we are using the Property Hive APP from the Reapit Marketplace to import the API
[Bancroft-test-property.txt](https://github.com/reapit/foundations/files/8726122/Bancroft-test-property.txt)
[Reapit website feed exercise.docx](https://github.com/reapit/foundations/files/8726124/Reapit.website.feed.exercise.docx)
.

**Comment by plittlewood-rpt** [comment]
Hi @scruffmcduff  thanks - I've had a look at that property and its because it's set to use a non-standard department for which there are no mappings. In your original screenshot the department was set to General and I would expect most of the options in the General department to have mappings in the properties API.

**Comment by scruffmcduff** [comment]
Hi @plittlewood-rpt can you be more specific and give me a screenshot of where we set the property to be General from within the Reapit environment.

**Comment by plittlewood-rpt** [comment]
Hi @scruffmcduff - on the Attributes panel in the top left hand corner there is a drop down for selecting the property's department. For normal residential sales/lettings this will almost always be set to General. Other departments are sometimes setup for different agency operations (Rural/Land and Commercial being a couple of more obvious examples). Hope this helps

**Comment by scruffmcduff** [comment]
Hi

We did some experimentation with the test property and set the tab as you suggested to General.

For the first test we checked every single check box 
See screenshot "23rd May screenshot - 001.jpg"
You can see the API output at "Bancroft-test-property XML output on 23rd May - 001.txt"

None of the data checked is coming through


For part 2 of the test we checked individual checkboxes
See screenshot "23rd May screenshot - 002.jpg"
You can see the API output at "Bancroft-test-property XML output on 23rd May - 002.txt"

Again, none of the data checked is coming through.

It seems to me that we are not getting all of the data through the API.

![23rd May screenshot - 002](https://user-images.githubusercontent.com/4266129/169807404-0963f43d-9573-4cbd-8fd8-ec6cd90f95bf.jpg)
[Bancroft-test-property XML output on 23rd May - 002.txt](https://github.com/reapit/foundations/files/8754029/Bancroft-test-property.XML.output.on.23rd.May.-.002.txt)
[Bancroft-test-property XML output on 23rd May - 001.txt](https://github.com/reapit/foundations/files/8754030/Bancroft-test-property.XML.output.on.23rd.May.-.001.txt)
![23rd May screenshot - 001](https://user-images.githubusercontent.com/4266129/169807414-da20ff97-c26b-4224-b1a8-04edde7ec750.jpg)


Can you please advise of next steps.

**Comment by plittlewood-rpt** [comment]
In addition, the following fields are now available to you for this customer only:

Directions, Situation, Advert Text.

These can be obtained using the extrasField query string parameter and the values pDirections, pSituation, and pAdvert respectively eg

`GET /properties?extrasField=pDirections&extrasField=pSituation&extrasField=pAdvert`

or 

`GET /properties/HQQ220611?extrasField=pDirections&extrasField=pSituation&extrasField=pAdvert`

In addition, I have logged a separate request #6968 to deal with the Number of Units request. This will be triaged soon.

Thanks
Pete

**Comment by scruffmcduff** [comment]
Pete

Let me check these things out.
We do now indeed seem to get the fields through the API as depicted in the screenshots. However I need to check with the client if he can check just one of each of the checkboxes to make sure that is working (rather than all of them).

I will revert to you regarding the Directions, Situation, Advert Text fields if I have any questions.

Many Thanks

**Comment by plittlewood-rpt** [comment]
Hi @scruffmcduff - based on the feedback above I will close out this ticket. If there are specific requirements, please can you log each requirement separately. Thanks
