### ISSUE TITLE
Is there a publicly available link to property brochures?

### ISSUE THREAD

**Issue by ianyoung** [reapit/foundations#6859]
The `/documents` endpoint allows for accessing a particular document such as the property brochure as a PDF. However the download URL is an API request rather than a publicly available download link. E.g.

```
"download": {
    "href": "/documents/OXF20000060/download"
}
```

Is it possible to get a publicly accessible download URL as per the images? E.g.

https://assets.reapit.net/path/to/image.jpg

Or, is the only way to download the brochure onto a external storage and serve from there?

**Specification**
- Understand how we send public URLs for brochures to portals. When PL last looked at this we send a link out to PHP script which manages the routing to the backend file system. We can leverage this or build our own mechanism. 
- Scope out best approach as above. We should speak with SI about the implementation here as they may prefer this to remain in the Platform
- If it is to remain in the Platform:
  - Update Reapit.Services.Documents to surface a public link to a document, when it can be accessed publically (which should ONLY be the case for brochures assigned to properties, and it should also take into account whether or not the associated property is on the market or not)
- If we use the PHP links as per all existing portal feeds, instead of using the documents service, update the properties service to surface a public brochure url in the links collection to the file. Again, it should take into account whether or not the associated property is on the market or not before deciding whether or not to surface the link. We should also have two links as it's possible to have difference brochures for sales/lettings mode for dual marketed properties (publicSalesBrochureUrl / publicLettingsBrochureUrl)

**Comment by AshDeeming** [comment]
Hi @ianyoung 

An Agent/Company will need to have the app Installed in order for documents to be accessible.

**Comment by ianyoung** [comment]
Hi @AshDeeming 

To clarify, the client has installed the app, and I have access to the data. 

What I was expecting was to find a publicly accessible link to the brochure (not authenticated), as per the image URLs. E.g.
https://assets.reapit.net/path/to/image.jpg

Instead however, it seems that links to the brochure are not publicly available (require authentication). E.g
https://platform.reapit.cloud/documents/OXF20000060/download

I presume that the only way to get hold of the brochure is for the developer to make an authenticated request to the API to download all the brochures, then host them somewhere on cloud storage, setup a CDN in front, and replace the URL for that of the developer hosted version?

This seems like a lot of extra effort for a document which is intended to be made public (a property brochure). Could this not be hosted on Reapit's CDN like the images?

**Comment by ianyoung** [comment]
Great! Thanks for the very quick turnaround on this one. Much appreciated.

**Comment by richclicksmith** [comment]
What was the solution to this in the end? I have the same question / issue. Is there a way to access brochures on a publicly accessible URL? 

Thanks.

**Comment by richclicksmith** [comment]
> Hi @richclicksmith - there is a new property `publicBrochureUrl` returned from `GET /properties` and `GET /properties/{id}` which will be populated if there is a brochure available

Thanks. I know that our client (Swoffers - SWF) has assigned a brochure to some of their properties e.g. on this page, I can access a brochure clicking the link shown here:

![Screenshot 2022-06-16 at 16 10 47](https://user-images.githubusercontent.com/94179432/174102536-2cf60739-0ca2-4b0e-a26a-3bda0115845d.png)


(SOAP API) URL: https://webservice.reapit.net/swf/pdf.php?p=rps_swf-OMA150043 

I don't see this when I retrieve the same property's data via Foundations API. 

What am I missing? Or is there a field in the client's agency software that they haven't populated?

Thanks.

**Comment by richclicksmith** [comment]
Apologies I was looking for it in the parent node, didn't see it within the selling node. Thanks very much.

**Comment by plittlewood-rpt** [comment]
@richclicksmith No problem - there's a property with the same name in the letting object too. As a property can be dual marketed there could be two different brochures attached, hence their position in the JSON schema.

**Comment by richclicksmith** [comment]
@plittlewood-rpt That makes sense. That's great. Thanks again.
