### ISSUE TITLE
Remove the default month selection in the Admin Portal /billing 

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#6861]
**Tasks:** 
- Remove the default previous month/current year selection on the /billing tab 
Should be 'please select' for both month and year - should select a month before the year

- Only allow the 'Download' to be actioned when the request has completed
- Remove the Data Warehouse Billing section

**Comment by willmcvay** [comment]
@HollyJoyPhillips Closing as I think this one was completed last week. Please confirm if I've missed anything

**Comment by willmcvay** [comment]
Ahh, ok, will re-open
