### ISSUE TITLE
Webhook double call

### ISSUE THREAD

**Issue by colearymyhome** [reapit/foundations#6882]
**Describe the bug**
On property modified webhook, events are being triggered twice.

Event1 Received at 2022-05-17T15:14:57.5502834Z:

  "eventId": "81da0f77-17ca-4bb2-b3ff-44d64c0989c0",
  "entityId": "RED220154",
  "customerId": "EDD",
  "eventTime": "2022-05-17T14:17:28.9950774Z",
  "topicId": "properties.modified",

Event2 Received at 2022-05-17T15:14:57.5830774Z:

  "eventId": "4394f085-80c4-4849-97ad-16323d1de501",
  "entityId": "RED220459",
  "customerId": "EDD",
  "eventTime": "2022-05-17T13:56:54.9261176Z",
  "topicId": "properties.modified",

**Expected behaviour**
Even though its clear that this is two separate updates by the agent, if a second update happens before the webhook is triggered, then I would expect the first update's webhook to be cancelled, and only the last update webhook triggered. Both events are being triggered within half a second of each other.

**Screenshots**
Attached

![WebhookDoubleCall](https://user-images.githubusercontent.com/68847301/168845097-11baad0e-4d5a-4139-95c4-7bcbef5b3580.PNG)

**Comment by plittlewood-rpt** [comment]
Hi @colearymyhome - each event in the customer CRM will be emitted to you as a separate webhook. There is no way of getting around that as each event will result in a different diff being produced. Our webhooks pipeline is complex and as such you will need to handle this appropriate. It's worth just making sure you're not receiving notifications where only the modified date/eTag has changed (you can prevent these coming through to you by using the Ignore option when setting up your webhook).
