### ISSUE TITLE
How do we request access to see the "extras" fields

### ISSUE THREAD

**Issue by s1mtm** [reapit/foundations#6887]
**Summary**
400 response returned - You must be granted access to this data beforehand

**Detail and or supporting links and screenshots**
How do we get this permission granted?  

The following is an example, but we'd need a number of extras fields from a number of endpoints.

https://platform.reapit.cloud/properties/MKT220555?extrasField=pEPCFPURL

Response
{
  "statusCode": 400,
  "dateTime": "2022-05-18T09:12:34.2283212Z",
  "description": "Access to one or more of the specified fields is not permitted. You must be granted access to this data beforehand"
}

**Comment by AshDeeming** [comment]
Hi @s1mtm 

In order for us to grant access to Semi-structured 'extras' field data, please provide the following information in this request:

- The name of the customer you represent
- The name of every field you need surfaced (if known)
- A screenshot of of the field(s) you require in the agency cloud user interface
- A short use case as to why you require this data
