### ISSUE TITLE
Token generated from the token endpoint doesn't work on the properties endpoint

### ISSUE THREAD

**Issue by CarlPiper** [reapit/foundations#6889]
The token being provided by the token endpoint (https://connect.reapit.cloud/token) doesn't work on the properties endpoint (https://platform.reapit.cloud/properties). I was also experiencing the same issue when I used Insomnia.

My Functions file contains the following two functions, one to get the token and one to get the properties.

```
function getToken($clientID, $clientSecret) {
    $authorisationToken = base64_encode($clientID.':'.$clientSecret);

    $ch = curl_init();

    curl_setopt($ch, CURLOPT_URL, 'https://connect.reapit.cloud/token?client_id='.$clientID.'&grant_type=client_credentials');
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_POST, 1);
    
    $headers = array();
    $headers[] = 'Authorization: Basic '.$authorisationToken;
    $headers[] = 'Content-Type: application/x-www-form-urlencoded';
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
    
    $result = json_decode(curl_exec($ch));
    if (curl_errno($ch)) {
        echo 'Error:' . curl_error($ch);
    }
    curl_close($ch);

    return $result;
}

function getProperties($props) {
    $ch = curl_init();

    curl_setopt($ch, CURLOPT_URL, 'https://platform.reapit.cloud/properties/?pageSize='.$props->page_size.'&pageNumber='.$props->page_number.'&embed=images&internetAdvertising=true');
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');


    $headers = array();
    $headers[] = 'Accept: application/json';
    $headers[] = 'Api-Version: 2020-01-31';
    $headers[] = 'Authorization: Bearer '.$props->token;
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

    $result = json_decode(curl_exec($ch));
    if (curl_errno($ch)) {
        return 'Error:' . curl_error($ch);
    }
    curl_close($ch);

    return $result;
}
```

Then my import script uses these functions. The getToken seems to work correctly, and it returns a token which I then use as below.

```
require __DIR__.'/functions.php';
$clientID = '*********************';
$clientSecret = '***************************************************';

$propertyQuery = array(
    'page_size' => '10',
    'page_number' => '1',
    'token' => getToken($clientID, $clientSecret)->access_token
);

echo '<pre>';
print_r(getProperties($propertyQuery));
echo '</pre>';
```

This code above then gives me the below output, the same as I was experiencing in Insomnia.

```
stdClass Object
(
    [statusCode] => 401
    [dateTime] => 2022-05-18T10:31:59Z
    [description] => The request could not be completed due to a missing or invalid authorization token. Please generate a new access token and try again.
)
```

The only way I seem to be able to successfully retrieve properties is by first going to the API docs (https://developers.reapit.cloud/swagger) and clicking 'Try it out' on the properties endpoint. I then copy the bearer token and use that in my script rather than the generated one.

**Comment by plittlewood-rpt** [comment]
Hi @CarlPiper - I'm assuming because you are using the token endpoint to get your token that your app is a client credentials app (server side). You need to also pass the reapit-customer header with your request which seems to be missing in your examples above. See https://foundations-documentation.reapit.cloud/api/api-documentation#accessing-customer-data for more information. Please let us know if this resolves your problem. Thanks

**Comment by CarlPiper** [comment]
Thank you for the response.

I can confirm that yes the app is a server side script to access our clients property data.

The retrieval of the token and I receive one.

The issue is that this token then doesn’t seem to work when used to access property data.

For the reapit-customer header, what should the value of this be?

Many thanks,

Carl

On 18 May 2022, at 22:58, Pete Littlewood ***@***.***> wrote:

﻿

Hi @CarlPiper<https://github.com/CarlPiper> - I'm assuming because you are using the token endpoint to get your token that your app is a client credentials app (server side). You need to also pass the reapit-customer header with your request which seems to be missing in your examples above. See https://foundations-documentation.reapit.cloud/api/api-documentation#accessing-customer-data for more information. Please let us know if this resolves your problem. Thanks

**Comment by plittlewood-rpt** [comment]
Hi @CarlPiper please refer to the link to the documentation in my previous comment.

Thanks
Pete

**Comment by CarlPiper** [comment]
Much appreciated, when I viewed from my phone I missed that bit yesterday. I will give it a go and come back if any issues but this is almost certainly the problem.

Thanks again!

**Comment by plittlewood-rpt** [comment]
No problem - SBOX is the id you want for dev purposes. Once a customer installs your app in production you'll be able to see the customer id in the installations table, or alternatively you can subscribe to application.install webhook events so you can programatically invoke any setup processes at your end. Cheers
