### ISSUE TITLE
Add support for non-standard attribute options

### ISSUE THREAD

**Issue by plittlewood-rpt** [reapit/foundations#6910]
**Background context**
The Platform is designed to be able to operate between Reapit group products rather than just being a REST API on top of AgencyCloud. As a result, various decisions had to be made when it comes to supporting the plethora of customisations in the AgencyCloud CRM. One of these decisions was around how to come up with a standard approach to heavily customised department attributes. What we have now works very well, in that we have a defined list of options available for things like property type, style, situation etc in the Platform which have mappings back to the various different versions of the same item in AgencyCloud (ie flatApartment maps to Flat, Apartment, Flat/Apartment, and so on). A common question is around how the options that did not make it onto the standard list get surfaced, which at the moment they don't. We need to come up with an appropriate way of surfacing this data

**Specification**
- Projects: Reapit.Services.Properties, Reapit.Services.Applicants
- Add mechanism to retrieve items not included in the standard set of attributes. Approach TBD however it may be something that is not returned by default and uses a query string parameter. This data will not be filterable at this time (but could be later in an Elasticsearch world)
- Add `unmappedAttributes` array to `PropertyModel` and `ApplicantModel` whose purpose is to expose any attributes that are NOT part of the standard platform mapping. Any attributes which are should be omitted to avoid any confusion. This is readonly

As an example, a property with a type of "House" selected and style of "Some Style Value" would return the following content. Note that "House" is NOT returned in the `unmappedAttributes`

```
"type": [
  "house",
],
"style": [],
"unmappedAttributes": [
    { "type": "Style" , "value": "Some Style Value"}, 
]
```

The `type` value should be the column header
The `value` value should be selected option value in plain text

- A method on `AttributeType` (or `RequirementType` in applicants service) to remove mapped options is probably a winner here

**Comment by rajeshwl** [comment]
@plittlewood-rpt ,
Regarding the commercial setup can you prioritize and enable options to have the `type` attribute values that are available in the agency cloud application for this client (Hus & Haus - HAH). 

https://github.com/reapit/foundations/issues/6790#issuecomment-1129961443

**Comment by RWilcox-Reapit** [comment]
RW/PL Discussion around if this is required for POST/PATCH as well. @plittlewood-rpt

**Comment by rajeshwl** [comment]
@RWilcox-Reapit , Currently we require this in the get call.
