### ISSUE TITLE
Attendee on Appointment is null

### ISSUE THREAD

**Issue by stebrough** [reapit/foundations#6913]
**Describe the bug**
A specific Appointment has 'null' for Attendee on a valuation (VL) type.

**To Reproduce**
Request Appointment from API

**Expected behaviour**
The Attendee contains the owners details

**Additional context**
I have a specific example, please contact for details.

**Comment by AshDeeming** [comment]
Hi @stebrough 
Please could you advise the appointment reference?

**Comment by stebrough** [comment]
Hi @AshDeeming it's CIT2201091.

Apologies with the duplicate tickets, not sure what happened there.

**Comment by AshDeeming** [comment]
Thanks @stebrough 

I can't locate this reference under sandbox, does this relate to a client's database? If so, could you advise who please? 

Thanks & regards,
Ash

**Comment by stebrough** [comment]
Hi @AshDeeming I can but not on a public ticket. Please email me steven.brough@integratedinterest.com and I will reply with the info.

Thanks

**Comment by AshDeeming** [comment]
Thanks @stebrough 

Please send any sensitive data to: sinfo@reapitfoundations.zendesk.com - I'll then update this ticket with any progress/info

Thanks & regards,
Ash

**Comment by stebrough** [comment]
@AshDeeming done!

**Comment by AshDeeming** [comment]
Thanks @stebrough 
From checking the appointment in question, there is no applicant attending the MA/Valuation & therefore no attendee.
