### ISSUE TITLE
DB Roberts(DBR) - Extra field from Marketing Details section(Sprift  Report)

### ISSUE THREAD

**Issue by rajeshwl** [reapit/foundations#6915]
Hi,

Can you please enable and share the extra field name for the details mentioned below.

Customer Name:  **DB Roberts (DBR)**

Field Required: **Sprift Report** in Extra descriptions section.

Screenshot:
![Inkedimage_LI](https://user-images.githubusercontent.com/14073702/169757953-3ae6e1ee-418e-43de-a37a-ae807edee9ef.jpg)

Use Case:
We are displaying the field data in website for customers.

**Comment by AshDeeming** [comment]
Hi @rajeshwl 
This will go through our process, outlined below & the ticket will be updated during refinement.
https://foundations-documentation.reapit.cloud/dev-requests

**Comment by plittlewood-rpt** [comment]
Hi @rajeshwl - you can now access the Sprift data for this customer using extrasField `pSprift` 

eg

`GET /properties?extrasField=pSprift`

Thanks
