### ISSUE TITLE
Tasktypes configuration fetch returns the error message on PAAS API

### ISSUE THREAD

**Issue by gokulngk** [reapit/foundations#6917]
When we try to import the `taskTypes` data from the reapit PAAS API on `configuration` calls, it returns the following error(For customer ID: DNG). 

'Unable to access Reapit!Error: Request failed with status code 500'.

**Endpoint:** https://platform.reapit.cloud/configuration/taskTypes

Can please check and share your comments.

**Comment by plittlewood-rpt** [comment]
moving into this sprint as I've also picked up on this in the error logs. Looks to be caused by a bad configuration so will liaise with service desk to resolve

**Comment by plittlewood-rpt** [comment]
@gokulngk this issue is now resolved.
