### ISSUE TITLE
Live Private App - No longer receiving Webhook notifications for customer

### ISSUE THREAD

**Issue by s1mtm** [reapit/foundations#6934]
**Describe the bug**
No longer receiving Webhook notifications for customer - WIL

The customer installed the App on 18th May 2022
We received the Application.install webhook notification and not received any other webhook notifications since for this customer.

We are receiving webhooks for different customers

**Comment by plittlewood-rpt** [comment]
Hi @s1mtm thanks for flagging this. It appears the the data streaming infrastructure has not been set up for this customer. This is managed by a different department who I will contact now
