### ISSUE TITLE
Receiving webhook requests from an unknown application

### ISSUE THREAD

**Issue by whitfieldn** [reapit/foundations#6943]
We're currently receiving webhook requests from one of our clients with an Authentication Client ID which doesn't match any of our apps.

The payload appears to be what we would be expecting, but for this one specific user, we are receiving webhooks containing an unknown Authentication Client ID.

We have not deleted any applications which could have led to the client using an application we no longer support.

Our earliest log of this happening occurred on 20/05/2022.

I will send through the Authentication Client ID and customer name separately via email referencing this issue.

**Comment by plittlewood-rpt** [comment]
Hi @whitfieldn - thanks for bringing this to our attention. There is a fix in progress and I've responded with a bit more detail on the ZenDesk ticket

**Comment by BoominJim121** [comment]
This is happening again. We're recieving a large number (nearly 400 in an hour) of requests for an app id that doesn't exist. I have sent a new email to [sinfo@reapitfoundations.zendesk.com](mailto:sinfo@reapitfoundations.zendesk.com) with the email trail from https://github.com/reapit/foundations/issues/6943#issue-1246398258 the above commenter.
