### ISSUE TITLE
API GET /documents/{id}/download returns 404 for an existing document ID

### ISSUE THREAD

**Issue by twentyci-nathan** [reapit/foundations#6952]
**Background context**

When calling get documents API, I receive a list of documents as follow:
![image](https://user-images.githubusercontent.com/101310415/170176564-afd59efe-d850-4a15-b12a-0f3276ebac37.png)
=> It works as expected

Next, I get a random document ID from the resulted list, then call API to retrieve the document with the ID `RPT22000560`:
![image](https://user-images.githubusercontent.com/101310415/170176705-8498b9f3-060e-41cb-8edd-3e2d9c28b015.png)
=> It works as expected

Finally I call the API to download the file:
![image](https://user-images.githubusercontent.com/101310415/170176813-d95ecefe-974b-4e27-a2cb-d155809d1db3.png)
=> I receive `404` error
```json
{
    "statusCode": 404,
    "dateTime": "2022-05-25T03:51:11.8690483Z",
    "description": "Entity \"Document\" (RPT22000560) was not found."
}
```

**Specification**
NA

**Expectation**
The API call should work normally and return `200`

**Note**
The API worked normally for me just couples day ago (last checked on May 23)

Please help to take a look if this is an issue for you. Thank you!

**Comment by plittlewood-rpt** [comment]
Hi @twentyci-nathan - thanks for reaching out. At the start of last week there was an issue with DNS resolution of some parts of the Developer Edition Sandbox environment. As a result anyone that attempted to post a file to the documents service during this time would have received an error. Any documents added between Monday 23rd and Tuesday 24th at around 4pm will be affected. One thing I will check as part of the ticket is the behaviour when we fail to reach the filesystem to store the document. The APIs should be returning an error and soft deleting the database record. If this isn't working as intended it would explain why you can still see the data and not access the file.

**Comment by twentyci-nathan** [comment]
@plittlewood-rpt Thank you so much for the response and for moving this into action

**Comment by plittlewood-rpt** [comment]
HI @twentyci-nathan I have removed documents that were added during the DNS failure window (this only affected the Sandbox environment). I have also logged a separate ticket to deal with the underlying bug which you can track using the link above. Thanks

**Comment by twentyci-nathan** [comment]
@plittlewood-rpt If this only affects the Sandbox env then it is no longer an issue. Thank you so much!
