### ISSUE TITLE
properties.modified webhook

### ISSUE THREAD

**Issue by stebrough** [reapit/foundations#6956]
**Describe the bug**
We are receiving webhook calls for this event, when we do not have a webhook set up to receive this.

**Additional context**
It does seem to be for a specific customer

**Comment by plittlewood-rpt** [comment]
Hi @stebrough - thanks for bringing this to our attention. Is the customer id BRG any chance? If so, it is fallout from an issue reported yesterday which we are actively working on

**Comment by stebrough** [comment]
Hi @plittlewood-rpt yes it is.

**Comment by stebrough** [comment]
@plittlewood-rpt brill, can you confirm we won't be charged for these calls?

**Comment by plittlewood-rpt** [comment]
Hi @stebrough yes I'll ensure these are not billed events.

**Comment by plittlewood-rpt** [comment]
hi @stebrough - you may have received some more webhook events overnight for other customers you have a subscription for - this was an error on my part which I've now corrected. I've been back over billing to ensure any erroneous entries are removed, and I've also flagged with our billing team to double check next months invoice before it comes out to you.
