### ISSUE TITLE
Update the URLs for desktop to use agencycloud:// 

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#697]
**Summary**: We were previously using the scheme desktop:// for the URL's when in desktop mode (through the desktop software) however this was updated to agencycloud://. In some instances for the marketplace we are still using desktop://

**Task:** Update the schemes used for the desktop URLs from desktop:// to agencycloud://

**Comment by willmcvay** [comment]
I think this is before we had the DynamicLink component - applies to the installed apps page
