### ISSUE TITLE
Issues loading Geo Diary if an appointment does not have a property ID associated with it 

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#698]
**Summary:** GEO Diary should show all types of appointments regardless if they have a property ID associated with it. At the moment it is not loading if an appointment doesn't not have a propertyID. 

For example, an appointment type 'Check In' may only contain a Time, Negotiator, Attendee and Viewing Arrangements but not a property. This should still be displayed: 

![image](https://user-images.githubusercontent.com/52408607/77325224-d2651b80-6d0f-11ea-9a3f-5da12ec63428.png)

**Location:** https://dev.geo-diary-app.reapit.cloud/ 

Currently, GEO will not load if an appointment does not have an associated property ID. See error 

**Error reported by Sentry:** key propertyId of appointment id AYL2000003 is required
**URL for full details on the error:** https://sentry.io/organizations/reapit-ltd/issues/1577154317/?project=1885608&referrer=slack

I am currently testing with negotiatorID 'FGM', if you require the username and password, please message me directly. 

To replicate: Create an appointment but do not had a propertyID. I can do this directly in the Desktop software if needed.

**Loading screen:** 

![image](https://user-images.githubusercontent.com/52408607/77323415-20c4eb00-6d0d-11ea-84c3-d5a38b9e1d3b.png)

**Comment by tanphamhaiduong** [comment]
Hi @HollyJoyPhillips could you help me to create an appointment like this?
