### ISSUE TITLE
API Usage

### ISSUE THREAD

**Issue by jwwjp** [reapit/foundations#6984]
Please take a look at our FAQ's before submitting an issue, as your question may already be covered in the documentation https://foundations-documentation.reapit.cloud/faqs

**Summary**

Currently, we are trying to work out the costs involved as a result of moving from a flat web service fee to a service based on endpoints and API calls. (we are moving from SOAP to REST/foundations).

**Detail and or supporting links and screenshots**

We need some clarification as to how the billing will work and these are the most obvious examples:

1. A Property Search

A customer goes on to our website and runs a search for a property. Our understanding is that this will be two API calls as it requires two endpoints - properties and images. Is this correct? (example page https://jww.co.uk/buy/search?q=). Also will this then be repeated for each page of results (assuming search returns more than one page of results, for example 10 per page?

2. A Property Page

A customer goes onto a specific property page on our website. This we assume will then be four API calls as it requires multiple endpoints for property, negotiator, images and documents. Is this correct? (example page https://jww.co.uk/buy/view/DUR210321)

We are updating our contract with Reapit at the moment so need to get some clarification on costs before we can move forward so any assistance you can offer would be much appreciated.

Thanks in advance

James

**Comment by AshDeeming** [comment]
Hi @jwwjp 

Please see the details on the below link which should be of use;
https://foundations-documentation.reapit.cloud/app-development/website-development

**Comment by jwwjp** [comment]
this was very useful thanks

as a follow up can I ask if any charge is made for the use of webhooks?

**Comment by jwwjp** [comment]
and also do they emit events as soon as data is changed?
