### ISSUE TITLE
Feedback on Issue #6965 regarding offer time offset by 1 hour

### ISSUE THREAD

**Issue by david-silverink** [reapit/foundations#6988]
Feedback from SFG, "It looks like it’s adding the offer at the correct time now, see below example that came in at 9:09 am this morning, but is still rejecting the old offer an hour early". Could it be that the fix is only in place for new offers?

**Comment by plittlewood-rpt** [comment]
Hi @david-silverink - when you say "it is still rejecting the old offer an hour early" please can you elaborate? If there's some data that needs cleaning up, we'll need to be able to identify it from the problem the customer is reporting. Thanks
