### ISSUE TITLE
Internal server error on brochure API call

### ISSUE THREAD

**Issue by pmonno** [reapit/foundations#6991]
[**I am reopening this ticket - as it was set as complete, but the issue persists.**](https://github.com/reapit/foundations/issues/6851)

**Describe the bug**
When making API call to retrieve brochure 'internal server error' happens
![image](https://user-images.githubusercontent.com/106077049/171217146-a2549513-4669-41e4-81e4-d2fd8718e694.png)

**To Reproduce**
Steps to reproduce the behaviour eg:

Make authenticated call to https://platform.reapit.cloud/documents/OXF21000266/download
As response it returns internal server error

**Expected behaviour**
It should return brochure file.

**Device (please complete the following information for web issues):**
Device: [PC]
OS: [Windows 10]
Browser [Edge]
Version [101.0.1210.39 (Official build) (64-bit)]

**Additional context**
Only certain brochure IDs fail
Failing ID Example:
OXF21000266
OXF21000527

Working ID Example:
OXF17000713

Ids are retrieved from Reapit API, so they are present on the system.

**Specification**
- Project: Reapit.Services.Documents
- This feature applies to customers whose assets are still hosted in Rackspace ONLY
- On the `{id}/download` endpoint, add a filesize check and if over a configured size (where we would normally do a redirect in the case of an AWS customer), push the file into a staging bucket and then generate a pre-signed URL to that file so we can perform a 307 temporary redirect to the file
- The staging bucket should be created as part of the CF stack for this service and must have a lifetime policy applied so files are automatically remove from the bucket after X hours (X should be a parameter in the cloudformation template and default to 1 hour)
- This needs to be tested well, and should be written in a way that it isn't too difficult to remove once the code becomes redundant at the point all customers have migrated to AWS

**Comment by AshDeeming** [comment]
Follow on from #6851

**Comment by RWilcox-Reapit** [comment]
Hi @pmonno 

This service has now been updated to support pulling these larger files. 
I've just tested against the files listed in your example and can see it working end to end.

Thanks
