### ISSUE TITLE
When is price used in properties endpoint compared to priceTo?

### ISSUE THREAD

**Issue by jonlemarquand** [reapit/foundations#6994]
Please take a look at our FAQ's before submitting an issue, as your question may already be covered in the documentation https://foundations-documentation.reapit.cloud/faqs

**Summary**

Hi all,

The client's international properties, have a value on the price input in reapit but are returning a 0 on the selling > price. There are some values on priceTo but they aren't matching what's in reapit.

Is there something we're missing to get the right price on the properties endpoint?

**Detail and or supporting links and screenshots**

<img width="398" alt="Screenshot_2022-05-20_at_16 03 38" src="https://user-images.githubusercontent.com/38497188/171347773-a78cb0d6-7c35-45fa-aac8-6b0b89678a3c.png">
<img alt="Screenshot_2022-05-20_at_16 03 38" src="https://user-images.githubusercontent.com/38497188/171348172-3bd33246-f283-4b49-a18d-efea662b2d64.png">

**Specification**
- Project: Reapit.Services.Properties
- At the moment the Platform API detects the customers system base currency, and uses this when setting the currency flag in the property model. If a property is created in AC that is NOT in the base currency, the price information is stored elsewhere in the system. Before tackling this ticket be sure to fully understand the behaviour in AC with regard to multi currency systems. Liaise with the desktop team if required
- When a property is returned from the database whose currency does NOT match the customer's default currency (available in the identity object), we should use extras.pPriceC to populate the PropertySellingModel.Price field. The same behaviour should apply for the MaxPrice (extras.pMaxPriceC to populate the PropertySellingModel.PriceTo field). The same needs to happen for rental properties (extras.pWRentC to populate the PropertyLettingModel.Rent field - remember we always store rental amounts in a Weekly format)
- We should review the commentary on the price filter on the GET endpoint to make sure it's clear how this works in a multi-currency environment
- The same needs to happen for PATCH operations. POST operations will always inherit the customer's default currency at this time. For PATCH we will need to do a conversion back to the base currency for storage in prp.price otherwise matching won't work. When handling a write back, the value passed by the caller should be stored in extras.pPriceC, and the same value in the system base currency (converted) should be stored in prp.price. The work in #7342 and #7343 needs to be completed ahead of this ticket. When utilising the cache, it's probably best to build this directly into the service for now, with a view to packaging it up later for use in other services. When the price is adjusted, minPrice/maxPrice/extras.minPriceC and extras.maxPriceC should also be updated at the same time. minPrice/maxPrice as always in the system base currency

**Comment by plittlewood-rpt** [comment]
More scoping required as we need to take exchange rates into account for write operations coming back into the Platform when prices for non-default currency properties
