### ISSUE TITLE
Update the 'Desktop Search' URL to use the correct App ID

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#700]
**Summary:** When in 'Desktop' mode, the AML app presents a 'Desktop Search' button which when clicked uses an agencycloud:// URL to open the search in desktop. Currently this is using the incorrect App 'ID'

**Location:** https://dev.aml-app.reapit.cloud/

**Task:** To update the 'Desktop Search' URL App 'ID' in AML when in 'Desktop' mode

**Example of current URL:** agencycloud://contacts?name=bryan&address=&appId=77f7c64f-0214-49eb-8963-f0b98f747072&appParam=cntCode

**Should use app ID:** 242601c2-f4fa-4471-99f2-6155027e8b74

![image](https://user-images.githubusercontent.com/52408607/77326894-61733300-6d12-11ea-8f6b-34f9b232ae65.png)

**Comment by willmcvay** [comment]
This should be added to the config for the app so it can be updated without doing a code deploy

**Comment by HollyJoyPhillips** [comment]
@phmngocnghia I have now been able to test this in Desktop but it is still surfacing the incorrect APP ID: See the URL it tries to reach: MarketplaceLoadHandler_MarketplaceResponseEvent: agencycloud://contacts?name=holly&address=&appId=77f7c64f-0214-49eb-8963-f0b98f747072&appParam=cntCode

Can you have another look please?
