### ISSUE TITLE
New persistent notification child element missing opacity declaration when is active

### ISSUE THREAD

**Issue by getupkid** [reapit/foundations#7001]
**Describe the bug**
When `.el-is-active` is added .el-perist**a**nt-notification it adds `opacity: 1;` to the `.el-pn-content` child element.
However, since 3.8.4's spelling change, adding `.el-is-active` to .el-perist**e**nt-notification doesn't add `opacity: 1;` to `.el-pn-content`.

**To Reproduce**
1. Create a PersistentNotification using .el-persist**e**nt-notification class.
2. Add .el-is-active to the .el-persist**e**nt-notification class.
3. `.el-pn-content` does not display.

**Expected behaviour**
`.el-pn-content` should be set to `opacity: 1;`

**Screenshots**
![image](https://user-images.githubusercontent.com/4795041/171572004-0854c08f-8226-4f0a-85f1-6f2620d35f3e.png)
![image](https://user-images.githubusercontent.com/4795041/171572126-08c6e7a1-cf8e-45fe-bcd7-fe91b23e6994.png)

**Comment by willmcvay** [comment]
@getupkid Not strictly a bug, the markup and classnames have changed with the spelling fix. That said, we can just share the same modifier classes to make it easier for you to migrate without changing all the sub classes. Will get it changed today.
