### ISSUE TITLE
Refresh link when in 'Desktop' mode

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#701]
**Summary**: When in 'Desktop' mode (RPS) after an installation, the ‘Back to List’ button should trigger a refresh and close the ‘Success’ message modal, however this doesn't seem to be working. 

This was addressed in January so it could be that it is no longer there or has not been added correctly. 

**Task**: To investigate to see if when in 'Desktop' mode a refresh link (agencycloud://apps/refresh) is added to the ‘Back to list’ button on the ‘Success’ modal after installation an App 

The refresh link should should also apply when ‘uninstalling’ app from the ‘Manage’ apps page and the 'Back to List' button to. 

![image](https://user-images.githubusercontent.com/52408607/77327924-c24f3b00-6d13-11ea-9967-26953b729086.png)

**Comment by HollyJoyPhillips** [comment]
Hi @vuhuucuong, it looks like the refresh is now working for the marketplace but something is still not working. The desktop is not picking up that an agency link is being detected only that the page is refreshing (which it wasn't before).  Can you check the link in 'Desktop' mode to see what is being triggered please?

**Comment by vuhuucuong** [comment]
@HollyJoyPhillips  I checked and saw that it's only a normal "Back to List" button without "Desktop Refresh". Fixing it now

**Comment by vuhuucuong** [comment]
Sorry, I checked again, it cause by wrong marketplace url
