### ISSUE TITLE
App Approval

### ISSUE THREAD

**Issue by jwwjp** [reapit/foundations#7012]
Please can you approve an app we have included on app store labelled 'JWW site feed'.

This is for internal use only and will be the link between our new website which we are developing and Reapit.

<img width="975" alt="app-store" src="https://user-images.githubusercontent.com/106545118/172340413-788b6a2d-a1bd-40b1-810a-c3ba9cddeaea.png">

**Comment by AshDeeming** [comment]
Hi @jwwjp 

The Developer Portal account this app is created under is currently set to Incomplete - meaning the app can not be submitted for approval. 
I can see that the email address used to create the above account does not relate to the Client named in the Organisation. 

Please confirm if the account will be used for the specified client only or if you plan to create apps for the Public AppMarket too?

**Comment by jwwjp** [comment]
thanks for quick reply. This is another ticket that I have open with reapit support as when I asked them to change my email account from james@fatcatit.co.uk to it@jww.co.uk they only did some areas. everything I do should be registered as it@jww.co.uk including foundations, atlassian etc.

I can confirm that this app is only for us (JW Wood) and we have no intentions of ever creating something for the public appmarket.

**Comment by AshDeeming** [comment]
Hi @jwwjp 
The account registered on the dev portal is currently James@fatcatit.co.uk - If you can log in with this account, you can go to the link below & invite the other it@ email (Making it an admin & then disable the @fatcatait account) along with any other users that may be required.

**Comment by jwwjp** [comment]
ive tried to login but dont know password - when I try to reset it says I cant and that I have to contact support? I'm trying to login at https://developers.reapit.cloud/

<img width="265" alt="screenshot" src="https://user-images.githubusercontent.com/106545118/172364733-bfdeebd0-eae8-4160-88b2-49fa05d03586.png">

**Comment by AshDeeming** [comment]
Hi @jwwjp 

Thanks for this detail - i've realised that the account associated to James@ is not associated to the Client Organisation as the user/email was not under the Organisation when it was created. 

Please could i ask you to go to the link below & select 'Existing Customer' - Then log in with your IT@ account. 
https://developers.reapit.cloud/select-role

From here you will be associated to the Client Database & be able to re-create the app to submit without issue.

**Comment by jwwjp** [comment]
Hi @AshDeeming 
![CleanShot 2022-06-16 at 16 38 53@2x](https://user-images.githubusercontent.com/106545118/174110374-8484ac80-b684-4f4e-af21-37c4843fe81c.png)

I did as you suggested and we then re-created the app but have got back to exactly the same place and unable to submit. It looks like still linked to the wrong admin account and also it says price not complete despite us ticking as free in setup?

**Comment by AshDeeming** [comment]
Hi @jwwjp 

As the account is not associated to a Reapit Client, the account status is currently _pending_. 
In order for an account to be confirmed, it will need to be associated to an Existing Client or an account (for billing) setup for the 3rd party developer. 

As it seems you are working on behalf of J W Wood - in order for a developer account to be created for the client, an admin AgencyCloud user from the business will need to register via; https://developers.reapit.cloud/select-role 

Once they have created their developer account, they can then invite you as a member (https://developers.reapit.cloud/settings/members) to create & submit an app on their behalf.
