### ISSUE TITLE
No Energy Rating information being sent

### ISSUE THREAD

**Issue by colearymyhome** [reapit/foundations#7017]
There is no Energy rating information being sent in the webhook.

Will need BER info, Energy Ratings and anything else that all Irish agents would put into that section

**Specification**
- Project: Reapit.Services.Properties
- Follow same precedent that was used for marketing information specific to Guernsey
- Add new `IrelandPropertyModel` with a `IrelandBERPropertyModel` that surfaces the semi structured data as below. When setting up the semi structured fields on the entity please prefix them with BER or similar so we have differentiation between EPC in the UK. This should be returned in the `Regional` object under a new key `irl` (3 letter ISO code for Ireland) for the `IrelandPropertyModel` and `ber` for the `IrelandBERPropertyModel` which should only be set when the property's country is set to Ireland OR the default country for the system is Ireland and the country is not set (refer to same behaviour for setting of the Guernsey object)
- Add new `CreateIrelandPropertyModel` and `UpdateIrelandPropertyModel` (and associated BERPropertyModels) that allows setting of the semi structured data below

| Property Name | Property Type | Semi Structured Field Name | Model Comment |
| ----------- | ------------- | -------------- | -------------- |
| exempt | bool? | pBERExempt | A flag determining whether or not this property is exempt from requiring an BER certificate |
| rating | varchar(2) | pBERRating | The current Building Energy Rating (BER) |
| refNumber | varchar(30) | pBERNumber | The BER document reference number |
| epi | varchar(50) | pEPI | The building's energy performance indicator |

**Validations**
- When provided, rating must be a valid value on the BER scale (G, F, E2, E1, D2, D1, C3, C2, C1, B3, B2, B1, A3, A2, A1), so an enum should be used for this purpose
- When provided, rating must not exceed 2 characters (but can be 1)
- When provided, refNumber must not exceed 30 characters
- When provided, epi must not exceed 50 characters
- All fields are optional

**Behaviours**
- When exempt == true, the rating, refNumber, and epi values should be cleared (in the case of an update) or not set at all (in the case of a create)

**Comment by plittlewood-rpt** [comment]
PL to review AC mechanism and complete ticket spec

**Comment by plittlewood-rpt** [comment]
I have had a look across our Irish customers and it does seem that a standard BER screen is now in use and as such standard fields are used across the board so this can now be scoped.

**Comment by plittlewood-rpt** [comment]
Hi @colearymyhome - this has been QA'd and will ship to production on Monday next week.
