### ISSUE TITLE
Unable to Utilise Tax Band Information

### ISSUE THREAD

**Issue by Rudi-AC** [reapit/foundations#7033]
**Is your feature request related to a problem? Please describe.**
We are currently using Reapit for our property based websites and I require more information on how to retrieve council tax bands from Reapit.  We have looked at our Restful API on Swagger and traversed through all our fields in relation to properties but we cannot seem to find anything storing tax bands.  We are utilising the Tax Band field within the Marketing Details in RPS but unfortunately we are still unable to retrieve the data dynamically for the website. 

**Describe the solution you'd like**
I would like to know if retrieving the Tax Band information is possible.  And if so, where and how to implement it into out individual property pages.  If you need anymore information please let me know.

**Describe alternatives you've considered**
N/A

**Additional context**
https://www.acandco.com/

**Comment by plittlewood-rpt** [comment]
Hi @Rudi-AC - this information is available in the PropertyModel returned from `GET /properties` and `GET /properties/{id}`

![image](https://user-images.githubusercontent.com/30798627/173112003-3214e61c-d354-44fe-b101-01eb2997e178.png)

Please let me know if this does not resolve your query.

**Comment by Rudi-AC** [comment]
Hi,

Thank you for the reply.  We updated our soap and it appears that the field is still not available.  I have had a look at our our property model and I can't find anything related to Tax Bands.  I also carried out a "Find In Files" search on Visual Studio across our whole solution for "councilTax" with no results.  Would it be possible to get the endpoint of the field so I can locate it?  This has become quite an urgent matter now for our business.

Many thanks,

**Rudi | Aberdein Considine**

**Comment by Rudi-AC** [comment]
Hi Pete,

I'm getting a 401 unauthorised error when I try to access https://platform.reapit.cloud/properties.  I believe our endpoint is at http://webservice.reapit.net/aac/.

![image](https://user-images.githubusercontent.com/107257980/173337605-ede0d790-6837-4a8f-95cb-85b052c27f4f.png)

I'm not very familiar with backend terminology as our primary web developer left the company several months ago which has left me in charge of things.  If this doesn't look correct then please let me know and I can l have another look at our code.  It does appear to be the SOAP API.

Many thanks,

**Rudi | Aberdein Considine**

**Comment by Rudi-AC** [comment]
Just reopening this ticket as I didn't mean to close it.

**Comment by plittlewood-rpt** [comment]
Ah, that explains things. This project is for Reapit Foundations which I'd encourage you to consider moving over to as it replaces our old SOAP service. I'm afraid for information about the SOAP service you would need to go through our normal helpdesk.

**Comment by Rudi-AC** [comment]
Hi Pete, 

Thanks for getting back to me so quickly.  I was advised by the Reapit Support to log a ticket here.

![image](https://user-images.githubusercontent.com/107257980/173360561-8e5b16d4-fe93-4664-aacd-1051cbb3f342.png)

Do you think if I mention the Reapit Foundations with my issue they will be able to take things from there?  I wouldn't want to get stuck in a loop and directed back here.  If you could let me know of any important tithings to include in my 2nd ticket to get the ball rolling it would be much appreciated.

Many thanks,

**Rudi | Aberdein Considine**

**Comment by Rudi-AC** [comment]
Hi @plittlewood-rpt ,

Thanks for letting me know.  I'll submit another ticket with these details and hopefully get this sorted.

Kind regards,

**Rudi | Aberdein Considine**
