### ISSUE TITLE
Missing workPhone for Offices for specific customer

### ISSUE THREAD

**Issue by stebrough** [reapit/foundations#7038]
**Describe the bug**
Missing workPhone for Offices for specific customer

**Additional context**
Customer has reached out to their Reapit account manager and they say they can see the telephone number and aren't sure what field maps to workPhone.

**Specification**
- Project: Reapit.Services.Offices
- Apply same mechanism as in #6760  to expose any communication details stored against an office that aren't exposed in the standard fields

**Comment by AshDeeming** [comment]
Hi @stebrough 
Please could you provide an example for the team to review. 

This detail is stored in the /Offices/ Endpoint;
![image](https://user-images.githubusercontent.com/61687775/173330450-3aea5ef4-bd92-4aff-bf6f-8e56877a8cf9.png)

**Comment by stebrough** [comment]
@AshDeeming I can provide the customer details via a private channel.

**Comment by AshDeeming** [comment]
Thanks @stebrough  - Please send any sensitive data/details to; sinfo@reapitfoundations.zendesk.com

**Comment by stebrough** [comment]
@AshDeeming sent!
