### ISSUE TITLE
Identifying if a PropertyImage has been deleted within RPS

### ISSUE THREAD

**Issue by waters-chris** [reapit/foundations#7056]
**Is your feature request related to a problem? Please describe.**
Currently you cannot find out if a PropertyImage has been deleted or not.  If you use the 'propertyImages' end point (either the GET all or GET single) then the Property Image is not included in the list (or you get a 404 error for the single)

**Describe the solution you'd like**
It would be great if the API returned any deleted images as regular images, but with a 'deleted' (or similar) flag included.

**Describe alternatives you've considered**
Alternatively, perhaps there could be a webhook created that would fire when a Property Image was deleted.

**Comment by plittlewood-rpt** [comment]
Hi @waters-chris - the APIs do not surface deleted records but I can understand the nature of your request. If you subscribe to propertyImages.modified webhook events, deletions are surfaced here. In a deletion scenario you will receive a modified event where the new property is null and the old property is populated. A modification that is an update to a non-deleted record will have both new and old properties populated. This behaviour is noted in https://foundations-documentation.reapit.cloud/api/webhooks#payload-schema

Please let me know if this answers your question. Thanks

**Comment by plittlewood-rpt** [comment]
Hi @waters-chris - thanks for flagging that omission in the documentation. I'll make sure that's updated. I can confirm you can subscribe to property image change webhook events in the Developer portal:

![Uploading image.png…]()
