### ISSUE TITLE
Delete contact API

### ISSUE THREAD

**Issue by sanjayisg** [reapit/foundations#7059]
HI I just wanted to know, like in case of add/edit contact we get hooks call for the same, what will be the case when we delete any contact from reapit, I can't see any hooks event for delete. Can you suggest please.

Thanks,

Sanjay Gupta

**Comment by AshDeeming** [comment]
Hi @sanjayisg 

We do not allow for Contacts to be deleted via the Platform. 

You have the ability to patch the Contacts Endpoint & suggest if a Contact is no longer being used, the Active marker can be made Inactive;
![image](https://user-images.githubusercontent.com/61687775/173777195-1c9e5a19-291b-40ff-988c-6d6909d3f119.png)
