### ISSUE TITLE
API Access to List Guarantors for Tenancy

### ISSUE THREAD

**Issue by jwr8385** [reapit/foundations#7079]
We need to be able list Guarantors for a tenancy so that documents can be issued for signing to the guarantors via our app.  We can list tenants, landlords, agents but not guarantors.  It's causing a headache for all clients so please do consider.

**Comment by plittlewood-rpt** [comment]
Hi @jwr8385 - we already have a ticket to track interest in guarantor information in #3312. I have linked the tickets and will close this one. 

@HollyJoyPhillips FYI
