### ISSUE TITLE
App Submission / additional permisssions

### ISSUE THREAD

**Issue by s1mtm** [reapit/foundations#7093]
**Adding additional Journal Entry permissions**

When adding additional permissions to a Private Integration App that is being trialed with 3 customers.
Will there be any impact on these customers?
Will there be any further APP review needed by Reapit developers?

Many thanks

**Comment by AshDeeming** [comment]
Hi @s1mtm 

Currently the app would need to be uninstalled by any clients, submit the app with amended permissions & then once approved, clients can re-install. 

This process has been reviewed and an update due by the end of the month. This can be monitored via the below milestone. 
https://github.com/reapit/foundations/milestone/101

**Comment by AshDeeming** [comment]
Hi @s1mtm 
Please see the revised process now in place; https://foundations-documentation.reapit.cloud/listing-your-app/app-permissions
