### ISSUE TITLE
Receiving error when trying to write contacts 

### ISSUE THREAD

**Issue by TaylorMadeDigital** [reapit/foundations#7098]
**Describe the bug**
Am receiving a 403 response when trying to send a PATCH request. The error I am receiving is

`This application has not been granted the required scope to interact with this endpoint. If your application requires access to this resource, please use the Reapit Foundations Developer portal to request permission to access this resource`

I am using the Reapit App I created `savills-uat--aws-flimsy-wind`. This app has been set up with `Read Contacts` and `Write Contacts`. Am using the reapit-customer `SBOX`. Am able to send a GET request successfully. Have tried debugging with Platform Support and they requested a bug be raised here. 

**To Reproduce**
Steps to reproduce the behaviour eg:
1. Go to Postman
2. Use the following request
`curl --location --request PATCH 'https://platform.reapit.cloud/contacts/MKT22001164' \
--header 'api-version: 2020-01-31' \
--header 'reapit-customer: SBOX' \
--header 'If-Match: "A81D2CF70E4ADBBA9B03E07A61878986"' \
--header 'Authorization: Bearer eyJraWQiOiJFXC9TcnVuTzVCR0xBMk1yT3phY2RjWFkwVVdqRVB1cVB5N3hIb1FWbnJGdz0iLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiI2dDdwbWNub3BvaW5nYjE2aWI2Z2ZuMDJjNSIsInRva2VuX3VzZSI6ImFjY2VzcyIsInNjb3BlIjoiYWdlbmN5Q2xvdWRcL2NvbXBhbmllcy5yZWFkIGFnZW5jeUNsb3VkXC9sYW5kbG9yZHMucmVhZCBhZ2VuY3lDbG91ZFwvaW1hZ2VzLnJlYWQgYWdlbmN5Q2xvdWRcL2FwcGxpY2FudHMucmVhZCBhZ2VuY3lDbG91ZFwvbmVnb3RpYXRvcnMucmVhZCBhZ2VuY3lDbG91ZFwvam91cm5hbGVudHJpZXMucmVhZCBhZ2VuY3lDbG91ZFwvb2ZmaWNlcy5yZWFkIGFnZW5jeUNsb3VkXC9wcm9wZXJ0aWVzLnJlYWQgYWdlbmN5Q2xvdWRcL3ZlbmRvcnMucmVhZCBhZ2VuY3lDbG91ZFwvY29udGFjdHMucmVhZCBhZ2VuY3lDbG91ZFwvYXBwb2ludG1lbnRzLnJlYWQgYWdlbmN5Q2xvdWRcL3RlbmFuY2llcy5yZWFkIGFnZW5jeUNsb3VkXC9lbnF1aXJpZXMucmVhZCIsImF1dGhfdGltZSI6MTY1NTQ3MzI1NSwiaXNzIjoiaHR0cHM6XC9cL2NvZ25pdG8taWRwLmV1LXdlc3QtMi5hbWF6b25hd3MuY29tXC9ldS13ZXN0LTJfZVE3ZHJlTnpKIiwiZXhwIjoxNjU1NDc2ODU1LCJpYXQiOjE2NTU0NzMyNTUsInZlcnNpb24iOjIsImp0aSI6IjMyYWQ3MTYyLWM0YTAtNDY3Ni1iZDJiLTc4YmNjNTRlNmUyYyIsImNsaWVudF9pZCI6IjZ0N3BtY25vcG9pbmdiMTZpYjZnZm4wMmM1In0.aVm-B24OccGd7eQs6jUM_NwvYtEL4uYqzbn0arw3whh6Hr2PGWnHuKzEUN4Zxg5DEPHVJ2WGTZTGUaoOhrYNsBdgjKoe3jMv4fibinJ_Md9DQ6Jl-wKUOoyuUhixWEYKNuKejWxVuZsuZZckz5yo9NVdOujtiBYweJahr8MYl1CDe-a8p9huzJ4tzR_3Swds31M-LIu7cxPqlVk4UHSPT1Iag3bLLZDZPJlcjAneSqlwstMoFDljXnNsAkoQzweQtakbNtASCVOhksBe2CTG1UxT8Tob0Uuoszs0_gV7ii2UzNmYEstLknVPilLB4GRsp8RPZFhDXS3w0SN6BqbMNw' \
--header 'Content-Type: text/plain' \
--data-raw '{
    metadata: {
        MYSAccountEnabled: true
    }
}'`
3. See error
`{ "statusCode": 401, "dateTime": "2022-06-17T13:34:20Z", "description": "The request could not be fulfilled as the reapit customer specified by the provided credentials does not have the application installed." }`

**Expected behaviour**
Request returns a 200 response and the contact (MKT22001164) has the metadata fields - 

`{ 
    metadata: {
      MYSAccountEnabled: true
   }
 }
`

**Comment by plittlewood-rpt** [comment]
Hi @TaylorMadeDigital - there are two different error messages in your report above but I'm assuming it's the first one that's causing you trouble. I've had a look at the access token and it doesn't have the contacts.write scope (you can decode the access token yourself to check this). If you've created the app and then changed the permissions, it's likely you just need to get a fresh access token for your app and it will include the new scope. Can you try this and report back?
