### ISSUE TITLE
Create Journal

### ISSUE THREAD

**Issue by komalpuri27** [reapit/foundations#7101]
**Describe the bug**
When trying to create new journal entry 

We were using these Journal Types since the beginning : 
Renew tenant -> TC 
Update User Setting -> EM
Update Price -> PC
Make an Offer -> OF

for now api only accept match (MA) & miscelaneus (MI)

**To Reproduce**
Steps to reproduce the behaviour eg:
1.  API response
{
  "errors": [
    {
      "field": "typeId",
      "message": "Unsupported typeId. The following typeIds can be used when creating a new journal entry: MA,MI"
    }
  ],
  "statusCode": 422,
  "dateTime": "2022-06-10T08:54:58.2003737Z",
  "description": "One or more validation failures have occurred. Please refer to Errors list for details"
}

**Expected behaviour**
We should be able to use all the JournalType ids.

**Comment by AshDeeming** [comment]
Hi @komalpuri27 
Please can you confirm you have used the below endpoint to check the possible Journal entry types:

![image](https://user-images.githubusercontent.com/61687775/174550150-da1dadd1-a77f-4127-94b0-71a6c9b07a89.png)

**Comment by komalpuri27** [comment]
Yes, @AshDeeming we use the same. 

Here is the request payload, also note it was all working few days back.

request payload:
{
  "typeId": "PC",
  "propertyId": "RPT170002",
  "associatedType": "landlord",
  "associatedId": "RPT170002",
  "description": "Update price 53/Surrey Lane, Battersea Park",
  "negotiatorId": "RPT"
}

response:
{
  "errors": [
    {
      "field": "typeId",
      "message": "Unsupported typeId. The following typeIds can be used when creating a new journal entry: MA,MI"
    }
  ],
  "statusCode": 422,
  "dateTime": "2022-06-10T08:54:58.2003737Z",
  "description": "One or more validation failures have occurred. Please refer to Errors list for details"
}

**Comment by AshDeeming** [comment]
Hi @komalpuri27 
Thanks for the details. 
Please note that previously the Platform, although you would be able to submit 'PC' as a journal type in the request, these would be posted as MI - for Miscellaneous. 
This has recently been updated & additional logic included to allow for other types to be included. Currently these are MA - for Property Matches and MI - For Miscellaneous
Additional types can be requested along with a requirement case for review.
