### ISSUE TITLE
uploadDocuments API not working

### ISSUE THREAD

**Issue by komalpuri27** [reapit/foundations#7102]
**Describe the bug**
The Uploads document API is throwing error

**To Reproduce**
Steps to reproduce the behaviour eg:

Calling the API is giving this API response:
{"statusCode":500,
"dateTime":"2022-06-16T09:35:42.7609253Z",
"description":"An unexpected error has been encountered when (truncated...)

**Expected behaviour**
We should be able to upload documents using the uploadDocuments API

**Comment by AshDeeming** [comment]
Hi @komalpuri27 
Please can you provide the request & confirm if this is against Sandbox (SBOX)?

**Comment by komalpuri27** [comment]
We are using https://developers.reapit.cloud/apps/5981104d-040f-462e-bfd2-8b3ee956d67b
in the sandbox environment

**Comment by AshDeeming** [comment]
Thanks @komalpuri27 
This will be reviewed by the relevant team.

**Comment by plittlewood-rpt** [comment]
Hi @komalpuri27 - this should now be working for the Sandbox environment. Please can you retest and confirm?

**Comment by komalpuri27** [comment]
@plittlewood-rpt this works for us now, thanks a lot for the fix.
