### ISSUE TITLE
Download documents

### ISSUE THREAD

**Issue by komalpuri27** [reapit/foundations#7103]
**Describe the bug**
The Downloads document API is throwing error

**To Reproduce**
Steps to reproduce the behaviour eg:
Calling the API is giving this API response:
{"statusCode":500,
"dateTime":"2022-06-16T09:35:42.7609253Z",
"description":"An unexpected error has been encountered when (truncated...)

**Expected behaviour**
We should be able to download documents using the downloadDocuments API

**Comment by AshDeeming** [comment]
Hi @komalpuri27 
Please can you provide more information to be reviewed

**Comment by komalpuri27** [comment]
Sure

**Comment by komalpuri27** [comment]
https://platform.reapit.cloud/documents/MKT22000050/download/

FYI @AshDeeming

**Comment by AshDeeming** [comment]
Thanks @komalpuri27 
This will be reviewed by the relevant team

**Comment by komalpuri27** [comment]
@plittlewood-rpt this works for us now, thanks a lot for the fix.
