### ISSUE TITLE
uploadPropertyImages API

### ISSUE THREAD

**Issue by komalpuri27** [reapit/foundations#7104]
**Describe the bug**
uploadPropertyImages API is not working as expected

**To Reproduce**
Steps to reproduce the behaviour eg:

Calling the API is giving this API response:
{
  "statusCode": 500,
  "dateTime": "2022-06-17T06:51:17.7254232Z",
  "description": "An unexpected error has been encountered when fulfilling this request. 
This incident has been logged and will be investigated. Please try again."
}

**Expected behaviour**
We should be able to use uploadPropertyImages API to upload property images

**Comment by AshDeeming** [comment]
Hi @komalpuri27 
Please provide more details for this to be reviewed.

**Comment by komalpuri27** [comment]
FYI @AshDeeming 

request payload:
{
  "data": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXwBFRcXHhoeOyEhO3xTRlN8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fP/AABEIAIIArgMBIgACEQEDEQH/xAAbAAABBQEBAAAAAAAAAAAAAAACAAEDBAUGB//EAEAQAAIBAwICBQcJCAEFAAAAAAECAwAEERIhBTETQVFhcRQiMoGRodEGFSNCUlOTscEkNFRyc5Lh8LIzRGKD8f/EABgBAAMBAQAAAAAAAAAAAAAAAAABAgME/8QAIBEBAQADAAMAAwEBAAAAAAAAAAECERIDITFBYXEEE//aAAwDAQACEQMRAD8A1DgU2KLFPiujaNA002ipKbNGz5iMqKEiptqBhTlKxHikFzT4pDarRoineKYJR0QftFLdVJEejFMfCpSARtUZFEF9AJ7qbNHppae2mj2AUWnFFjHKlmg5AYp8YpHenCmgGosU+kjnSNLatBxT0qemSamOaIjFNvWTTRAUjSGafcUjDilpzRYzT6R20bPQClNoqQ04UU9puMRaPVS0d9TCOjEVHRcq4Wloqz0fdTdHR0WkGgDqoGWrJSgKU5kFfTQlasGMnkKHoz1iq6LlBinAqUrjqpvVRsuQbdppY8aLemOaDNilS3pqZLJ8QadRnnR6R1U4AFc9ydEhvNFNlac02mkdpZFLT3UYSjCUbkLVqMLRqlGFosYpdDRggotIrnpPlZbxyugtpGCsQGDDB76ntPlGLrUYrKQKvN3cBR66rmluNeaSKCMvKwVR7/CoLS+huyVXKP8AYbGSO6uYuOKPxO+WCGTJbI6QDYbE4UernUTa+FRpMHkljaTBDHcHGcg1cx9M9u1KUBSsWDjZWBriNWvNZGVDYZcD7PwquflhHn9yf8QfClJT9Og04oStY9j8po729itxasnSHGoyA491bxWi+vp7VitAUFWSlAUpykrlaEr41ZK0BWnstRXK02KmK0JWq2nSfFNilinArm26dHC0YWkoqQUui0QWixWB8p+JPawJbwSFJpDqLKcFVH+a5xeJX/8AGT/3mqmO5srdPQwKp8ZufIuGTz5wQuF8TsK4r5zvgM+WT/3mtMyNbogubh766YB0i1lo07zVc6TazrbhqRwi54ixhgHop9eTuoLu9e8URRIILVdljXbPjW1FDLc4muLZJpOXnDIHcOyrItSoAFjB3/R1p/UOcsHS0vYpmBKpnIHgR+taNw3zvEkFsjKqPrd3GAowR21em6GHU1xFbwRouWYoNRz2CoUkkucRQQCK3z5qdbd52pkzJL2GwBh4aVeTP0lww59w7qL9l4v5raLW/PX9WX/f9zXQLBKqj6CMHs0jH5U0lvKUI6JMdZKr7tqRuURZ+FX8bTRlZIm1BTyb19lbQ+V0xH7nF+IfhUt3IggK8Rj6S2XGHHpoScc/99dYN5bR21yY4ZhMmAQw7+o99P79Dq+C8afik8sUkCxFU1LpJOd62Cvca84GV5EjwpF3+23tNK4Sjb0QrjqoD3150zP9tvbUZZjzY+2jj9jp6OVoCtVOAXflvDIyxzJH5j+rl7sVpFKjeqNB00YSnxRAGsWx1WnYrGhZyAqjJJ6hTisT5U3vQ2YtlOHn546lHP28qJ7ug5biN01/fS3DZwx80HqUchUKrRBaMCuqRlaDTtV/gMYbiDAjIERx7RVQjarfCbiOzumlmzpKFfNG/MfCkHSNArQgf+RPuFW7SFFhxjrrIHH7ILgiXnn0aNflJaKMKsuO9a5c/Fnln1GmOcmOkvFraOV/OA9Hso4YlWRMADcVQuOPWcpziTOMejVpOKWIdT5VFsftV0z1GN+nt7RYr5tw2W1eGa0mjAVsD6prNXiPDhL0nliEnqzUg4tYDJ8rU5GMZrjxw8ky3Y6bljZpR46g+Z5tutf+QrmEGd66Xi95a3HDJYoZkd204A/mFc8i4rtYQ+mmZdqkxVyy4ZLeAu5ENuvpStyHhVEz4LSa7mEUCa2PsHeeyi4hwyewYdKA0Z5SL6JroLOaFpWs7FeigCEtKT50h291R3RPDkiijiWeCTIeHqx3e2lci0o/JmaSG8CiQJFMwU7ZyR1d3Z667YrXE3FvBGVewkOCQwQjdGG/rrsOHXQvrGG4GAXUah2HrHtrnuW7tcgpZBEmoj31TTi8Rm0HrJVRjGSCNvGouLSrDAzzMyDGlD1Fj/8AK5K3vZ1u0BchulySDnGeeOrNRzW3p6IsivGHUgqRkHO2K4XiklxxC+knWCUp6KYQ+iOXx9ddjZN+yQrINDsnoNz5dlUeKWkb39koUKuDkLtWnj9Iycotpdfw039hqVbK6P8A20v9hqaS+uI7h40tomVGIzkj9akTiE+kk28QbqGTv7616rPSv5DdHbyaXftWpG4XdJgOsa+MqD9ak+cLrP7rFjt1H41v21kLi3ik0qWKgkE7DO9Fy0NOYPD5ftQfjp8ab5vk+3B+Onxrb4jcT2988MMUBUYxqTeqrX16okJt7fYDSNPpUdUaZvzc/wB5b/jr8aXzdJ97b/jL8a0E4jelvOt4FXtCA/rRm/u9eBFb6e3RR1Rpmjh7/fW/4y0Q4e331t+MtX1vr4x56G3D6sadPVUtre3slzFHNDAqswDEAZFLqnpnDh7/AH1v+KKi8glWRvOhIzz6ZfjXVXtqlvBNPJGhVQWIGN6orOgkhja16PpW0KRoO+M9XcKxz81x+Ta8cJfyo2dhBGOlvpkwCNMSMCXJ5cuqtdgtwqpJbr0KjzYxsF9nOhVMvblAAvSAYwO2q3ErLp+NRk8tIH50YebvHrQy8erpa8ltf4SL2c/fUM8FtFGzraxKyjI7vfUtvAgIAHqzVbiES4bRDp07525cjXPP9kz3JFZeHn8siUBTqiVQ6ksGUb/6N61+CXsixyRqGL6izakypz1jHKslolEy9Kz4Jy2Ps91dDw2e2sLdjLIUJcgxk+j2e4VfjrNhcTuDNbo0sTHWSq5lY4x171kSqHuDpQxrnxxXRHyKW2iEzFtGSAmTnPhVR3sIZSGik3JGWkK42H+a6crDkulVZGjEemWTVjIbG43O9a/AgHcsHkduk3L8+VRRx2EsCyZKbEDziceutDhsUUMiiFg4LZJBz1UsKWUsYkw/bJv6jfnRD1VFOw8rn/qN+dOHHdW0RUpIxXTWkqR2cKtIikopwzAdVcoZBirXEpFElsGI3t12PXzqc5uDG+1ziTA8VdgQR5pBHgKGQ6hyqtMwWdf6af8AEUfSjHKjSpT4pAUPSDspxIOymSePamiJ8ti7OkH50AkA6qeBwbqL+cUtHtqcSngayu9MsbM0bYAkBPsrmOGXcs/ErVZZWYCTI1HO+DSk1a500b6SB7Ki4bbXEXELd5IXVVfJJGwqJMZKLu2Ot8yIQ5KoiuCSTsNzTXMyLO0ylZNA3AYeyq946PAVDruD19xoICn0qtpILcj4CsvHjJjY1z+sU/KGaOfUsSqnLSQc1uhheWQnI0Fl1Lnt22qKK1sEuGCQQhwo+qOW9WtSAYyg9dZ3/NhbLDudZJDrKr+apG5J5L3HPL10o0jlkdJS9yq40LAwwO3c4q5fuvkkmkrq2xgis+2vLaDaR9EmNyDin/zmMZz6zme7Sa3aNJwERVZTnn14x1VamNxxDXB5G4DkHaMqR6zXRR8FWNlZXiYg5DPGWI9pq2sN3rz5TGf/AFf5rf8ApbrIsPk9MYVS4uDHGowERgffVm94fbW0ltHFFkbktzJPea0zBcMmDNFnt6M/GoZ4rlFH0iS9+n/NOfRXIyp9PKTG3pH6lP0cQXdHz15XatwtcByTBMT/AD7ezNAWuCwPQTbdWxB9prRLJjgi2LRsxPJQDvU91aQyTx5Up9EpOR+VX83bPuLkDs1KAPYau+TXEwVjcSrgY0g1nndLxYVxEqzIBuNC7nwpGNsZ0gDurUumkR9BEhGOYA39tRKX0n0xnn5o+FOZehYoCLPUdqSxsATgY7zVjpGT602e7ApluAGyUlJ72HxqvqUGD9j30dqA1zH5jekPrVOpL7jph6xVqDpNakyvt1M2350svhxQi4YXuSyIp07+kM1Xa5WJ9OrSynkz5roJreV0/emUY2wagMEnNZsHG50A59ormsuS7+mG16Sd5Ux3YFQK6o2VunXu1j4VvNBLnedz4InwoRbPy6aQ+Kr8Kc8eX4RusRVhMnSeWzo5GCQ43qbEL4zxGc47xWv5K2Nrhwf5V+FRz22uPQ8zkdyr8KfOY3WZJFbtEVN/JIGI9LqxvUL2ls5DSXBY4xktWgnD4/tN4siH9KuRWKKvm8QijzzACj9KfGcJ0LejURJpUqoz9VQuTk70qVOAAAOc0LbHbalSq0m54qZdhSpVOfxeCjdk6xvTj0BSpUKqjf7AY2qknpCmpVrj8Z1ow1ahAzyp6VKhPpGOQqI0qVTiKbroj6NKlWqELE9tRzf9I0qVRVIrUknc5rRVFI3UH1U1KgP/2Q==",
  "fileUrl": null,
  "propertyId": "RPT170002",
  "caption": "Front view",
  "type": "photograph"
}

response:
{
  "statusCode": 500,
  "dateTime": "2022-06-17T06:51:17.7254232Z",
  "description": "An unexpected error has been encountered when fulfilling this request. 
This incident has been logged and will be investigated. Please try again."
}

**Comment by AshDeeming** [comment]
Thanks @komalpuri27 
This will be reviewed by the relevant team.

**Comment by plittlewood-rpt** [comment]
Hi @komalpuri27 - this should now be working for the Sandbox environment. Please can you retest and confirm?

**Comment by komalpuri27** [comment]
@plittlewood-rpt this works for us now, thanks a lot for the fix.
