### ISSUE TITLE
Integrations Questions

### ISSUE THREAD

**Issue by amirpulse** [reapit/foundations#7122]
Hi there,

Our questions are mainly related to the web development for an external website for our client.
- Is there a payment integration to be used in the external website web development (Please clarify the full payment process)?
- What is the payment integration approaches? through an API? or through a payment gateway page redirection?
- Are there API methods for the property retrieval (search, filter, sort)?
- Are there API methods for the property rent process (including data collection, approvals, payments)?
- Are there API methods for the property maintenance process?
- Are there API methods for leads subscriptions through the website forms?
- Are there any white-label integrations for Reapit services to be used in the external website development?
- What are the limits and cost rates for using Reapit APIs in the external website development?

Thanks

**Comment by AshDeeming** [comment]
Hi @amirpulse 
Please can you confirm you have registered for the developer portal & have read through the documents?
The below in particular relates to website development; https://foundations-documentation.reapit.cloud/app-development/website-development
