### ISSUE TITLE
Expose Properties RightMove URL to the LSL Group

### ISSUE THREAD

**Issue by robchett** [reapit/foundations#7125]
**Request**

In order for us to grant access to Semi-structured 'extras' field data, please provide the following information in this request:

- The name of the customer you represent: LSL Group
- The name of every field you need surfaced (if known): oInetRM 
- A screenshot of of the field(s) you require in the agency cloud user interface: Not sure it's visible
- A short use case as to why you require this data: To be able to link vendors to their property on RM from external applications

**Specification**
- Customer configuration update to add offices.oInetRm to list of allowed fields for customers YOM/RER/THA/LSI

**Comment by plittlewood-rpt** [comment]
Hi @robchett - do you know the customer ids of the brands under the LSL banner just so we can be sure this is applied to all configurations that will need it?

**Comment by plittlewood-rpt** [comment]
Thanks - that tallies with what I've got here. We'll get this set up

**Comment by plittlewood-rpt** [comment]
@gnthackray-reapit I think LSI might be an internal database so won't work with Platform. Just trying to confirm with our infra guys then I'll get back to you

**Comment by plittlewood-rpt** [comment]
Hi @robchett - I can't see that LSI are configured to use Platform services - would that align with your expectation? This has been set up for YOM/RER/and THA and you can access the data using the extrasField query string parameter on the offices endpoint ie

`GET /offices?extrasField=oInetRM`

and

`GET /offices/{id}?extrasField=oInetRm`

**Comment by robchett** [comment]
Ah, you are correct, LSI hasn't been moved to Foundations yet, I was under the impression it had been. Sorry.

Should I be able to see this now for YOM/RER/THA or is it after the next release?
