### ISSUE TITLE
Foundations - Field Request

### ISSUE THREAD

**Issue by BYMIntegrations** [reapit/foundations#7128]
Hi,

Hope you are well.

Can you send us the data for "Offer Date Accepted" and "Offer Rejected Date"? A customer is wanting us to use those fields in BriefYourMarket, but I'm not able to use them as we don't receive them from the json/API.

![Screenshot 2022-06-22 140604](https://user-images.githubusercontent.com/102583061/175036275-305df8b7-83fa-48b0-bd97-1b233b1be86d.png)

Speak soon.

**Comment by plittlewood-rpt** [comment]
The behaviour in AgencyCloud around setting this data has changed and so we need to understand the current AC behaviour. I have reached out to the desktop team for their assistance

**Comment by plittlewood-rpt** [comment]
Hi @BYMIntegrations 

AgencyCloud no longer explicitly stores this information against the offer and it is managed through recording the state changes in the journal. Journal entries are not currently associated directly back to offers, the relationship being between the applicant and property instead. Can you confirm if you've tried to handle this using data from the journalEntries API?

Thanks
Pete
