### ISSUE TITLE
Expose commercial property types [Galbraith]

### ISSUE THREAD

**Issue by MSB89** [reapit/foundations#7129]
We recently had property types exposed, which is now working. See ticket https://github.com/reapit/foundations/issues/7009

Is it possible to also expose all property types for the commercial property department? 

Property types in use:

Retail
Office
Industrial
Land / Development
Restaurant
Licensed Premises
Hotel / Guesthouse
Warehouse / Distribution
Investment
Catering
Care Home
Holiday Lets

**Comment by AshDeeming** [comment]
Hi @MSB89 
Please confirm you have used the GET /departments/ endpoint to call the departments, i.e. General (for Residential) and Commercial attribute sets for the specified client? 

https://foundations-documentation.reapit.cloud/platform-glossary#department

**Comment by MSB89** [comment]
@AshDeeming I have used the GET /departments/ and GET /departments/C endpoints.

**Comment by plittlewood-rpt** [comment]
This is part of a wider item #6910 and as such will close this ticket. The ticket mentioned has been moved To Review to discuss with the team again this week
