### ISSUE TITLE
Timeout when querying for properties with large pageSize

### ISSUE THREAD

**Issue by NickStallman** [reapit/foundations#7156]
**Describe the bug**
We are doing periodic checks for changed data (a backup mechanism to webhooks) and are sometimes inconsistently getting timeouts when querying for properties.

**To Reproduce**
curl API request which experiences the issue.
Valid authorisation token has been removed, as well as the specific client I verified this issue with (but confirmed with multiple clients).

Parameters:
- pageNumber=1
- pageSize=100
- modifiedFrom=2022-06-05T06:33:46Z
- officeId=XYZ

```
curl "https://platform.reapit.cloud/properties?pageNumber=1&pageSize=100&modifiedFrom=2022-06-05T06%3A33%3A46Z&officeId=XYZ" -H "Accept: application/json" -H "api-version: 2020-01-31" -H "Authorization: Bearer xxyyzz" -H "reapit-customer:XYZ" -v
```

Result after a relatively long time (30 seconds?)
```
< HTTP/2 504 
< date: Mon, 27 Jun 2022 04:41:28 GMT
< content-type: application/json
< content-length: 41
< x-amzn-requestid: 370ad733-d4e3-409f-9203-435c9b881411
< x-amzn-errortype: InternalServerErrorException
< x-amz-apigw-id: UXUyQHBUSwMF13g=
< 
{"message": "Endpoint request timed out"}
```

**Expected behaviour**
Expected the details of up to the 100 most recently modified properties from the specified date. I would also generally expect a query like that to take at most a few seconds to return.

For the moment we are doing a reduced pageSize of 25 to work around this issue, which is less efficient and could result in 4x more API calls. I'm unsure at what pageSize the API becomes unreliable.

Also pageSize=100 does sometimes work fine. It's taken us several weeks to notice this issue. I'm also not sure what the contributing factors are but once it starts failing for a particular client or date range, it will fail reliably.

**Comment by AshDeeming** [comment]
Hi @NickStallman 
Please confirm you are attempting to access sandbox (SBOX) data as i'm unsure where the 'XYZ' officeID relates to

**Comment by plittlewood-rpt** [comment]
PL to speak to PN about this as this is a result of global routing policies

**Comment by plittlewood-rpt** [comment]
@NickStallman I have reached out to you via email

**Comment by plittlewood-rpt** [comment]
PL to split this out into a new milestone with the respective tickets to see the routing changes through to implementation

**Comment by plittlewood-rpt** [comment]
Hi @NickStallman  we have made changes to the way traffic is routed to customer databases and I would expect this issue to now be resolved. Please can you come back to me and let me know if you are still experiencing problems. Thanks

**Comment by NickStallman** [comment]
Fantastic, we've reduced the page sizes for all our API calls to mitigate this issue, but if the API's are now being routed to be more local to the DB we should be able to increase the page sizes again.

We'll add this to the todo list.
