### ISSUE TITLE
Fetching Images for a property returns with a null url field.

### ISSUE THREAD

**Issue by NickStallman** [reapit/foundations#7157]
**Describe the bug**
When querying for images for a property, we are sometimes seeing a null url.

**To Reproduce**
curl reproducing the issue, with the client details and authorisation key removed.

API: propertyImages
Parameters:
- pageNumber=1
- pageSize=100
- propertyId=ABC12345
```
curl "https://platform.reapit.cloud/propertyImages?pageNumber=1&pageSize=100&propertyId=ABC12345" -H "Accept: application/json" -H "api-version: 2020-01-31" -H "Authorization: Bearer xxyyzz" -H "reapit-customer:XYZ"
```

Result:
```
{
  "_embedded": [
    {
      "id": "propertyId_15.jpg",
      "created": "2022-05-26T13:15:17Z",
      "modified": "2022-05-26T13:15:17Z",
      "propertyId": "propertyId",
      "url": null,
      "caption": "Floorplan",
      "type": "floorPlan",
      "order": 13,
      "_eTag": "\"3FA7DA50689FF3316F4C21A0898A6785\"",
      "_links": {
        "self": {
          "href": "/propertyImages/propertyId_15.jpg"
        },
        "property": {
          "href": "/properties/propertyId"
        }
      },
      "_embedded": null,
      "metadata": {}
    },
    {
      "id": "propertyId_14.jpg",
      "created": "2022-05-26T11:12:35Z",
      "modified": "2022-05-26T11:12:40Z",
      "propertyId": "propertyId",
      "url": null,
      "caption": "Picture No. 14",
      "type": "photograph",
      "order": 10,
      "_eTag": "\"3E1905E4918578012CE19CC9EFC42F33\"",
      "_links": {
        "self": {
          "href": "/propertyImages/propertyId_14.jpg"
        },
        "property": {
          "href": "/properties/propertyId"
        }
      },
      "_embedded": null,
      "metadata": {}
    },
...snip...
  ],
  "pageNumber": 1,
  "pageSize": 100,
  "pageCount": 13,
  "totalPageCount": 1,
  "totalCount": 13,
  "_links": {
    "self": {
      "href": "/propertyImages/?PageNumber=1&PageSize=100&propertyId=propertyId"
    },
    "first": {
      "href": "/propertyImages/?PageNumber=1&PageSize=100&propertyId=propertyId"
    }
  }
}
```

**Expected behaviour**
Images should be returned with a valid url for each image.

I'm not sure if this one will be tricky to isolate without the specific customer information. Let me know if that's the case.

This issue seems to affect all url fields. It's not a case of some having a url and some do not. Also we were definately getting a URL previously for the same listings.

**Specification**
- Project: Reapit.Services.PropertyImages
- Step through code locally running against production for customer CSP (it's also worth seeing if this is a global problem for all customers by checking a couple of other customers
- Likely this might be something to do with the configuration object for this customer
- Apply appropriate fix

**Comment by NickStallman** [comment]
@AshDeeming no problem, I wasn't sure if specific customer information was permitted on the open bug tracker or not.

Reapit Customer: CSP
PropertyId: BAT160436

I can provide further examples if required, it's not a isolated case.

**Comment by plittlewood-rpt** [comment]
@NickStallman this should now be resolved if you can please validate for me and confirm

**Comment by plittlewood-rpt** [comment]
Confirmed via NW that this is resolved
