### ISSUE TITLE
Enquiry create via API not visible in Reapit

### ISSUE THREAD

**Issue by manishautomatic** [reapit/foundations#7165]
We created an Enquiry via the {POST] https://platform.reapit.cloud/enquiries/ endpoint.
The API returned a 204-Created response.
However, the enquiry is not visible in the Reapit CRM to the client.

App name -- CommVersion
Request was made on June 27 2022
client_id - 355sfsib6e93igjutevgn4j90a

I can share additional payload details if required.

Regards

**Comment by plittlewood-rpt** [comment]
Hi @manishautomatic  - this has previously been discussed in #6439 and #6588 and is likely the same issue, given the date you have provided. I'm assuming it's the same customer?

**Comment by manishautomatic** [comment]
Hello @plittlewood-rpt !

Correct! Same client, though I again made the test today. I have updated the date in my original message. 
Regards

**Comment by plittlewood-rpt** [comment]
Hi @manishautomatic - if the email address you used was test-27-06-2022@... I can see it has been rejected and marked as spam by the branch so it's the same case as last time. You need to speak to the branch to find out who is handling these leads as someone is manually marking them as spam. Hope this helps
