### ISSUE TITLE
Ed Dempsey's BER Details for MyHome.ie

### ISSUE THREAD

**Issue by MatthewGoddard** [reapit/foundations#7168]
**Request**

In order for us to grant access to Semi-structured 'extras' field data, please provide the following information in this request:

- Ed Dempsey (EDD)
- pBERRating, pBERNumber, pBERExempt, pEPI
- ![image](https://user-images.githubusercontent.com/10115484/175977047-a4b0af59-9cde-44ba-95c6-aec52be49028.png)
- This information needs to be displayed on property portals in Ireland

**Comment by colearymyhome** [comment]
If possible, could this be made available on the webhook as well as the API please?

**Comment by MatthewGoddard** [comment]
@colearymyhome This is for the API only.

**Comment by plittlewood-rpt** [comment]
Hi @MatthewGoddard this will be added as per #7017 where webhooks will also benefit.

**Comment by gnthackray-reapit** [comment]
Looked at whitelist in AWS(see below). It already contains  the extras fields.

"extrasWhitelist": "properties.pBERExempt,properties.pBERRating,properties.pBERNumber,properties.pEPI,properties.pFeatured"}

**Comment by plittlewood-rpt** [comment]
@MatthewGoddard  as above this is already configured. MyHome just need to use the ?extrasField query string parameter to get it back from the API for this customer.

ie: `GET /properties?extrasField=pBERRating&extrasField=pBERExempt&extrasField=pBERNumber&extrasField=pEPI`

The same parameter is available on the `GET /properties/{id}` endpoint.

Any issues let me know 
Thanks

**Comment by MatthewGoddard** [comment]
Thanks @plittlewood-rpt, very much appreciated. As always.

**Comment by plittlewood-rpt** [comment]
For info the update to include this information in the core property model has now hit production so you should start getting this information back in webhooks for properties in Ireland.
