### ISSUE TITLE
BER details in Webhook for Irish Property Agents 

### ISSUE THREAD

**Issue by colearymyhome** [reapit/foundations#7169]
please provide the following information in this request:

![175977047-a4b0af59-9cde-44ba-95c6-aec52be49028](https://user-images.githubusercontent.com/68847301/175979097-ae463a04-edb4-422a-91d7-6eb59e003ca4.png)

pBERRating, pBERNumber, pBERExempt, pEPI

This information needs to be displayed on property portals in Ireland

**Comment by plittlewood-rpt** [comment]
Closing as an exact duplicate for #7017
