### ISSUE TITLE
API to get a list of App Installations

### ISSUE THREAD

**Issue by NickStallman** [reapit/foundations#7176]
**Describe the solution you'd like**
Currently we can log in to developers.reapit.cloud and view which clients have installed a particular App.

Unless I'm mistaken, this is the only way currently to get that customer list.
It would be great if this list was also available as an API as well which could be very useful in certain circumstances.

As an example, there is the AppInstall webhook which gives us similar information when the client first installs the app.
However when we were doing our initial development and debugging that particular webhook and our account creation code we could not programmically get the list of customers.
Webhooks should be reliable but if one was lost (bug in the processing code, internet outage, etc...) there's currently no alternative way to find out about a new customer from code.

It's likely a fairly easy addition, and whilst it wouldn't be used day to day it could be a very handy extra API.

**Comment by HollyJoyPhillips** [comment]
Hi @NickStallman Unfortunately the marketplace API is not publicly available. You will need to manage your installations/uninstallation data using the webhooks as mentioned above. You could create your own data store to manage this based on the webhook and or email notification that is generated at the point of install/uninstall.
