### ISSUE TITLE
Missing appointments when retrieving negotiator appointments

### ISSUE THREAD

**Issue by r-wilson-ire** [reapit/foundations#7179]
**Describe the bug**
We call the /appointments/ endpoint to retrieve appointments for a negotiator
The returned appointments do not match those visible in the negotiator's Reapit diary - it appears that recurring appointments are not being returned

**To Reproduce**
Steps to reproduce the behaviour
1. Negotiator had three appointments in their Reapit diary for 1st July:
  8:00 AM recurring appointment, 
  9:00 AM recurring appointment, and 
  1:00 PM non-recurring appointment

2. On the API, when performing a GET call to /appointments/ endpoint, for that negotiator for appointments that start on 1st July and end before 2nd July, only 1:00 PM appointment was returned from the API call

**Expected behaviour**
All appointments that appear in the negotiators diary for 1st July, would be returned on the GET /appointments/ call for that time period

**Screenshots**
![image](https://user-images.githubusercontent.com/103089332/176398900-7b378877-5c11-4213-9521-c06fbe9cb5f9.png)

**Specification**
- Project: Reapit.Services.Appointments
- Look at what mechanism used to do and assess performance (this is commented out in `AppointmentRepository` and previously made use of some unreferenced methods in that class also (ie `SortAndPageResultsAsync`). We need to do a stringent performance analysis here as there'll likely need to be a refactor so we can fetch the appointments in one query with no joins, and then get the related data separately. 
- Outcome of this ticket is to update this service to return the original appointment and NOT duplicated copies of the appointment

**Comment by RWilcox-Reapit** [comment]
Hi @r-wilson-ire 

I have update the endpoint to now display recurring appointments that fall within a specified `start` and `end` date.

There are however a few requirements for these to be display which is documented on the endpoint as:
_Recurring appointments can also be retrieved by specifying a `start` and `end` date along with any of the following query parameters: Id, NegotiatorId, PropertyId, AttendeeId_
