### ISSUE TITLE
determining compliance type from the compliance documents 

### ISSUE THREAD

**Issue by raymond2323** [reapit/foundations#7182]
When querying GET /properties/{id}/certificates you are unable to determine whether a compliance document is an EPC, Gas Safety or EICR. Is there a way from the API to determine this?

**Comment by AshDeeming** [comment]
Hi @raymond2323 
Please see the GET Configuration/certificateTypes on the swagger page 
![image](https://user-images.githubusercontent.com/61687775/176483189-97704318-f9bc-44e5-90c2-f0113b7a2539.png)
https://developers.reapit.cloud/swagger

**Comment by raymond2323** [comment]
@AshDeeming this only shows the following:

`The certificate's category (safetyCertificate/insurancePolicy/warranty)`

It doesn't specify if it is an EPC, Gas Safety or EICR. Is there a way to find this out?

**Comment by AshDeeming** [comment]
Hi @raymond2323 

The certificate types can vary dependant on the customers configuration setup. 

The results shown relate to sandbox data (SBOX) which is the generic 3 listed above.
