### ISSUE TITLE
Default filter values for Properties API endpoint

### ISSUE THREAD

**Issue by diger74** [reapit/foundations#7188]
**Summary**
Hi guys! Having checked the docs I wasn't able to find what are the default values for filters on /properties/ API endpoint.
[Swagger](https://developers.reapit.cloud/swagger) says there are parameters like lettingStatus, marketingMode, sellingStatus, etc but what are the actual values taking into account when I'm not passing this parameter (or passing an empty value)? Is it just returning everything if not specified, or are there any exceptions?

**Comment by AshDeeming** [comment]
Hi @diger74 

Please see the 'model' option next the example provided on the swagger page - i trust this is what you are looking for however if I've mis-understood, please revert :)

![image](https://user-images.githubusercontent.com/61687775/176725600-9d876af0-c84b-4119-8982-f511dbf3ed1e.png)

![image](https://user-images.githubusercontent.com/61687775/176725550-46f09699-8317-40eb-9b0b-02ff4dd2a749.png)

**Comment by AshDeeming** [comment]
Hi @diger74 
Please see the below:

1) This artical on the FAQs, may be useful: https://foundations-documentation.reapit.cloud/faqs#embedding
2) Yes, if no parameter provide, all will be returned
3) as above
4) Yes - Not returning a value, will return both True & False -'fromArchive' is the only exception to that in platform is you have to declare you want archived. Not specifying it will only return live entities

**Comment by diger74** [comment]
Thanks @AshDeeming, this is helpful.

Regarding Archived though, is it possible to return in one request both archived and live entities together?

**Comment by AshDeeming** [comment]
Hi @diger74 
Not currently, as per the below section of the swagger docs, the property record parameters allow for Archive = True or False 

![image](https://user-images.githubusercontent.com/61687775/179476807-93fd759c-c110-4adc-a094-241ebffe784b.png)
