### ISSUE TITLE
Issue with disable portals data not exposed within the property data structure.

### ISSUE THREAD

**Issue by kitoban** [reapit/foundations#7189]
**Describe the bug**
Within the property data structure there is no data to indicate if certain portals have been disabled from displaying a property.
Unfortunately the settings don't appear to be setup within the sandbox portal so we are unable to check this, but we are receiving reports of the "disable portals" flag being set but cannot respect the data when it is not included within the Property structure.
![image](https://user-images.githubusercontent.com/5329503/176724498-485b3c99-3d62-4e07-89b7-47bf47b5eb11.png)

**To Reproduce**
Steps to reproduce the behaviour eg:
1. Go to market details
2. Click on disable portals
3. check exposed property json structure on update.

**Expected behaviour**
To be able to see this data within json structure in order to respect the setting correctly.

**Comment by plittlewood-rpt** [comment]
Hi @kitoban - we actually refined the following tickets which are directly related to this yesterday for inclusion in an upcoming sprint (likely next week or the week after). 

#4421 
#7184 

I'd ask that you subscribe to these tickets for updates and I will close this one as a duplicate. Thanks
