### ISSUE TITLE
AgencyCloud Image Sizes

### ISSUE THREAD

**Issue by NickStallman** [reapit/foundations#7191]
**Summary**

It appears we currently get 1024x768 images for most clients by default from AgencyCloud.
We typically recommend and prefer 1920x1080 or 1920x1440 for our websites.

![image](https://user-images.githubusercontent.com/136553/176805152-a882c08f-2b74-4517-bc96-4d22408cca91.png)
We've seen this setting in AgencyCloud.

Questions:
1. Is this limiting all photos uploaded in AgencyCloud by clients to 1024x768?
2. Are there any limits or restrictions with changing this? Can a client easily increase this to 1920x1440?
3. If the setting gets changed, will it apply only to new images uploaded? Or can it apply to previously uploaded images.
4. Could there be any problems if we ask clients to increase this with any other services the client may have?
5. Is there any chance of the default value being changed in the future? These days 1024x768 is quite low resolution.

Thanks

**Comment by plittlewood-rpt** [comment]
Hi @NickStallman 

Answers as follows:

1. In a nutshell yes. This configuration setting forces all images added via AgencyCloud to be resized to those dimensions (taking the max dimension to keep the aspect ratio in check)
2. This can be increased on a client by client basis and this would be something our service team would need to do. Typically when a request like this comes in there'll be a high level evaluation to ensure that there'll be no downstream effects. 
3. Changing this setting will only apply to new images - increasing the size of images would have ramifications on image quality
4. There could be problems but it's unlikely unless they go crazy big. The only real impact will be to the customer's storage costs. Larger files = more storage
5. You're right that 1024x786 is low res these days. I'll check with the AgencyCloud product team on this point. I've a feeling there might have been a piece of work to increase the max resolution across all our customers at some point.

**Comment by NickStallman** [comment]
Great. We'll put in requests for our website customers for 1920x1440.
If the default could be changed that would also be awesome.

We aren't yet doing 4k sizes (3840x2880) but if you were wanting a new future proof size that would be what I'd aim at.
Storage costs for these sorts of things are relatively neglibible (we store over helf a billion image objects). We also handle CDN for our website customers so no additional costs for transfer on your side.

**Comment by plittlewood-rpt** [comment]
Hi @NickStallman - I've just checked in with the desktop team and they've confirmed the default now is actually 1600px on the larger dimension. The Platform API doesn't actually resize images when they are sent to us at the moment (only to create the thumbnail), but it's something we will be dealing with at some point in #7233 so it's worth being aware of that. 

Based on the above I'm going to close this ticket as your conversations from here are likely to be with our service team rather than here on Github with us.
