### ISSUE TITLE
End to end testing of organisations API updates

### ISSUE THREAD

**Issue by plittlewood-rpt** [reapit/foundations#7194]
**Background context**
The work completed in #7040, #7134, and #7135 enhances our central user service in various ways. This is a complex piece of work and time should be allocated to do some in depth testing before this goes to production

**Specification**
- Project: Reapit.Services.Organisations
- Test all features in the aforementioned tickets throughly, and document a production release plan, being mindful of migrations AND prerequisite scripts that need to be run before the release goes out

**Comment by RWilcox-Reapit** [comment]
Closing ticket, production release ticket raised: #7311
