### ISSUE TITLE
Client libraries / SDKs for the REST API?

### ISSUE THREAD

**Issue by rattrayalex** [reapit/foundations#7197]
**Is your feature request related to a problem? Please describe.**
Right now, you have to manually compose HTTP requests to use the API, and don't get the benefits of in-editor documentation, types, autocomplete, etc that you might get from something like Stripe's [Node](https://github.com/stripe/stripe-node) and [Python](https://github.com/stripe/stripe-python) libraries. You also have to manually handle retries (in case of network failure, etc) and pagination.

**Describe the solution you'd like**
If you'd like, I could [talk](alex@stainlessapi.com) about building & providing these for you 😄 After building the codegen system that powers the Stripe API libraries, I'm starting a company to do this for others like yours.

**Describe alternatives you've considered**
You could also:
1. Write client libraries by hand
2. Use [openapi-generator](https://github.com/OpenAPITools/openapi-generator)
3. Create your own codegen system for producing api client libraries

In my experience, (1) and (3) are a ton of work to get right, and (2) has sadly poor quality, but I'd be happy to talk about them more!

**Additional context**
I heard about Reapit through @shaneosullivan; we worked together at Stripe, and he had great things to say about your API & dev team.

**Comment by willmcvay** [comment]
@rattrayalex Closing to follow up via email.
