### ISSUE TITLE
Company opt out

### ISSUE THREAD

**Issue by elizabethhamlin** [reapit/foundations#7200]
We want to be able to report on companies that have opted out of marketing - located in the attached 
![Opt out](https://user-images.githubusercontent.com/104636752/177157333-ecde03af-3e4e-440f-bb13-6e9dfffa8311.png)

**Specification**
- Project: Analytics Schema
- Take into account cnt.cmpMktOptOut semi structured field when populating CONTACTS.MARKETING_CONSENT
- Ensure analytics schema documentation is updated when this update goes out

**Comment by plittlewood-rpt** [comment]
HI @elizabethhamlin - is this a request to add a field to the analytics schema? If you can include as much information about which area of Foundations this request relates to that would be great.

**Comment by elizabethhamlin** [comment]
Yes, please. From the screen shot there is an opt out of marketing ticket box for companies. I need this field to be available to report on if possible

**Comment by plittlewood-rpt** [comment]
@elizabethhamlin this is now in production. You do not need to refresh your data share on this occasion as the existing field CONTACTS.MARKETING_CONSENT has been used. The value returned will be Denied (where the checkbox is ticked) or Not Asked (where the checkbox is unticked) as it would be incorrect to assume consent has been given where there is no value set.
