### ISSUE TITLE
All developer editions are subscribed to Steph Mollins

### ISSUE THREAD

**Issue by rochellelevy** [reapit/foundations#7202]
**Background context**

One of our developers was having a problem logging into the developer version Reapit Agency Cloud with his alias .co.uk credentials. He said he was able to do so 2-3 weeks ago. To my knowledge no one has unsubscribed him. 
user: bassem.murad@savills.com

I checked the subscriptions page and the only subscriptions I see are for Steph Mollins. I know that my team have subscribed the developer edition (e.g. Gareth Evans and Paul Nisbett). Please could someone explain why this would happen and fix it please

**Specification**

**Comment by HollyJoyPhillips** [comment]
Closing this ticket as the issue has been resolved
