### ISSUE TITLE
Cannot find a property from a customer via the API

### ISSUE THREAD

**Issue by enricsangra** [reapit/foundations#7203]
**Describe the bug**
When trying to get a property via ID, the API is returning a 404. According to the customer, this is in their Reapit platform.

**To Reproduce**
Steps to reproduce the behaviour eg:
1. Call the endpoint: /properties/LMR160023 with the client id NOC.
2. 404 is returned

**Expected behaviour**
The API should be able to return the data instead of returning a 404.

**Screenshots**
We have screenshots from the customer but they all contain a lot of personal information.

**Device (please complete the following information for web issues):**
 - API integration

**Additional context**
Ticket submitted by Goodlord regarding the API integration.

This happened in the past with a different company and it was related to some bad data, in case that helps.

**Comment by plittlewood-rpt** [comment]
@AshDeeming this is due to bad data in a few records in the customer's system. Please can you liaise with service and ask them to clean up records with a bad pDepReq value.

**Comment by AshDeeming** [comment]
RSD-188995
