### ISSUE TITLE
Management fee

### ISSUE THREAD

**Issue by elizabethhamlin** [reapit/foundations#7215]
This has not been actioned. Please refer to ticket - Management fee #6735

**Comment by AshDeeming** [comment]
Hi @elizabethhamlin 

Please could you detail what has not been actioned? 

As per previous ticket, there are two additional fields in the Analytics Schema 
LETTINGS_MANAGEMENT_FEE_AMOUNT 
LETTINGS_MANAGEMENT_FEE_PERCENTAGE 
(for fixed fee/% fee respectively)

To refresh your copy of the schema, you can hit the Refresh Share button in the Data Warehouse AppMarket app.

Updated documentation for the analytics schema is available at https://developers.reapit.cloud/analytics-schema-docs

**Comment by elizabethhamlin** [comment]
Please can I have an update on this

**Comment by elizabethhamlin** [comment]
@AshDeeming please see above

**Comment by AshDeeming** [comment]
Hi @elizabethhamlin 
Please can you send any supporting screenshots of the fields missing for yourself please? 
These are showing on the docs & should be available to you:
![image](https://user-images.githubusercontent.com/61687775/180984636-86976c4f-d818-4758-8df0-b220ee1e20d2.png)

**Comment by AshDeeming** [comment]
Thanks @elizabethhamlin 
Please could you refresh the schema through the data warehouse app to return and updated fields

**Comment by elizabethhamlin** [comment]
Hi @AshDeeming it still isnt there I am afraid. I have refreshed the data and it still isn't there

**Comment by plittlewood-rpt** [comment]
Hi @elizabethhamlin please can you confirm what application you are viewing your data in? I've just checked the data in Snowflake (in your account) and can see the new fields are there, so it looks potentially like you need to refresh the local schema in whatever you are using to view your data. Here's a screenshot showing the fields in Snowflake which confirms that the data has refreshed correctly in Snowflake

![image](https://user-images.githubusercontent.com/30798627/182667063-0171da91-ac3a-4607-ab49-be4b1e9b3c66.png)

**Comment by plittlewood-rpt** [comment]
HI @elizabethhamlin - have you been able to resolve this?

**Comment by elizabethhamlin** [comment]
Hi @plittlewood-rpt  yes it is there now.

Thanks for the help
