### ISSUE TITLE
UploadProperty Image error

### ISSUE THREAD

**Issue by komalpuri27** [reapit/foundations#7220]
**Describe the bug**
When we try to upload the property Image we are getting 403 forbidden error.

The app id used is 5981104d-040f-462e-bfd2-8b3ee956d67b 
App name : AgentPoint test App

I have checked the permissions on the app and we have "Write property images" permission.

Error Message:

{
  "statusCode": 403,
  "dateTime": "2022-06-27T04:32:28.3663395Z",
  "description": "This application has not been granted the required scope to interact with this endpoint. If your application requires access to this resource, please use the Reapit Foundations Developer portal to request permission to access this resource"

**Expected behaviour**
Upload property image should work since the app has the permissions to do so.

**Screenshots**
![image](https://user-images.githubusercontent.com/94682169/177438479-a60f23a3-72f8-4c50-80af-d156b9ac84b8.png)

**Comment by plittlewood-rpt** [comment]
Hi @komalpuri27 - the app does not appear to have the properties.write scope which will be why you are receiving this message

**Comment by komalpuri27** [comment]
Thanks @plittlewood-rpt  and @AshDeeming , i will add the permission and test it out. 
Currently, I can not access the developers portal any idea why 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/94682169/178175061-5f1a2a24-d4d6-4d4a-a541-50ca58a796c3.png">

**Comment by plittlewood-rpt** [comment]
Hi @komalpuri27 - this should be resolved, please can you confirm.
