### ISSUE TITLE
Discrepancy between returned data on SOAP API vs Foundations API - property "type"

### ISSUE THREAD

**Issue by richclicksmith** [reapit/foundations#7228]
When I retrieve property OMA170036 via the SOAP API, the returned data contains a "type" array with 2 items:

- House 
- Development/Renovation

When I query the same property via Foundations API, the "type" element contains a single item: 

- house

See screenshots of returned data below:

![Screenshot 2022-07-06 at 11 19 57](https://user-images.githubusercontent.com/94179432/177530300-036cb262-75ff-41b6-8144-11b93053c6c9.png)

![Screenshot 2022-07-06 at 11 21 01](https://user-images.githubusercontent.com/94179432/177530314-98512d1f-0944-4f81-aefb-b70762c4eb9c.png)

The client wishes to filter properties via the "Development" type which I currently can't do without it being pulled into our dataset.

Reapit account: SWF

Many thanks.

**Comment by AshDeeming** [comment]
Hi @richclicksmith 

I believe the fields expected in Platform API return may relate to custom data in the clients database - this will need to be requested via a [Semi Structured data req ](https://github.com/reapit/foundations/issues/new?assignees=&labels=back-end%2C+needs-triage&template=extras_field.md&title=)

**Comment by richclicksmith** [comment]
Hi @AshDeeming. Is there any way you can see what that custom data / field is called for this client? I don't have access to their Cloud Agency software. I can ask the client otherwise.

Thanks.

**Comment by AshDeeming** [comment]
Hi @richclicksmith 
This detail can be obtained via the client & complete the details on the below form;
[Semi-structured data request](https://github.com/reapit/foundations/issues/new?assignees=&labels=back-end%2C+needs-triage&template=extras_field.md&title=)
