### ISSUE TITLE
No webhook received after changing solictor from sales progress screen and offer screen

### ISSUE THREAD

**Issue by lcantrell79** [reapit/foundations#7230]
**Describe the bug**
If only change the solicitor company in the sales progress screen or the offer screen then NO webhook is sent with the new solicitor information.

**To Reproduce Sales progress screen**
from property view
click offers
click sales progress
click on Solicitor name
click on "Change the currently selected company"
search for a new Solicitor company to add
select company and exit and save

**To Reproduce Offer screen**
from property view
click offers
click on Solicitor name
click on "Change the currently selected company"
search for a new Solicitor company to add
select company and save

**Expected behaviour**
A webhook should be sent showing the diff from Solicitor company A to mortgage company B

**Specification**
- Project: Reapit.Lambdas.DatabaseEventHandler
- Update `LookupChangeEventHandler` class to react to app -> sol lookup events. When this occurs we should lookup all offers associated to the applicant and create a `CascadeDataChangeEvent` for each offer and/or conveyancing entity. We should check which of these two entities expose the applicant solicitor
- Ensure tests are updated to cater for these scenarios

**Comment by plittlewood-rpt** [comment]
Hi @lcantrell79 - this should have been addressed in #6741 - can you confirm if the description from your previous ticket is still presenting itself as a problem? Thanks

**Comment by lcantrell79** [comment]
The previous ticket was the mortgage broker company (which is working) but the new ticket is for the solicitor company on the same view

**Comment by plittlewood-rpt** [comment]
Sorry for the lack of contact on this item - it got missed due to a missing label. We will refine next week and look at resolving soon afterwards

**Comment by plittlewood-rpt** [comment]
#7651 required to be able to properly implement this as we need to look up all conveyancing records relating to a specific buyer (applicant) and emit a notification for each of those records when the applicant's solicitor changes
