### ISSUE TITLE
Reapit Api Webhook Topic - Document Deleted

### ISSUE THREAD

**Issue by maxcivino** [reapit/foundations#7241]
Hi,
Reapit Api provides the possibility to register a webhook to the topic Document Created and Document Modified.

In order to make consistent our integration with Reapit we would also need a notification when a Document is deleted.

This is quite important and urgent for us.

Could you please let me know if it's possible to introduce this feature, the complexity and and estimation on how long is going to take it to be delivered?

Regards,
Max

**Comment by plittlewood-rpt** [comment]
Hi @maxcivino - deletions are surfaced as `.modified` events in webhooks. The difference is that the diff will be empty and the `new` object will be null. More info available at https://foundations-documentation.reapit.cloud/api/webhooks#payload-schema

Please let me know if this does not resolve your query.

**Comment by maxcivino** [comment]
Thanks Peter. We'll verify it and we'll let you know

**Comment by paulnisbettsavills** [comment]
Retested and can confirm that this is now working correctly - we've received the expected notification.
Thanks for your assistance
