### ISSUE TITLE
Provide the ability to filter users by role 

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#7242]
**Summary**: It would be good to see at a glance, who in an certain organisation is a Level 2 (ReapitUserAdmin), Marketplace Admin and has the ability to install apps. 

**Task**: 
Add the ability to filter by 'user role' so we can extend the RC service app

**Comment by plittlewood-rpt** [comment]
Hi @HollyJoyPhillips - was just about to spec this out and realised we already have this endpoint. Will send you the details
