### ISSUE TITLE
Difference between data received from legacy API and Foundations API

### ISSUE THREAD

**Issue by TobyDunnEPS** [reapit/foundations#7244]
**Is your feature request related to a problem? Please describe.**
I have a batch of properties which show as Reserved status when fetched from Foundations, but show as either Let, or Under Offer when fetched from the legacy API
This applies to data received from The Frost Partnership (FRO), I don't know if would also apply to others.

**Describe the solution you'd like**
I need to know if this is due to customisation in the legacy API that affects some but not all customers, so I can make appropriate configuration options to alter data received from Foundation

**Describe alternatives you've considered**
We have considered making this a default change to all data we import, but have concerns that if this is a customer level change, it will cause future issues as we extend the number of clients moving from legacy to Foundation.

**Additional context**
Example data attached.  availability / Favailability show the status from legacy and Foundations APIs respectively
[Reserved_examples_for_Reapit.xlsx](https://github.com/reapit/foundations/files/9073365/Reserved_examples_for_Reapit.xlsx)
:
Thanks,
Toby

**Comment by plittlewood-rpt** [comment]
Hi @TobyDunnEPS I've just had a look at the first property on your list (BUL210015) and that's correctly being returned as arrangingTenancyUnavailable from the Foundations properties API which is accurate based on the data in the customers' CRM. Can you post a snippet of what you're seeing please?

**Comment by plittlewood-rpt** [comment]
housekeeping - closing due to inactivty
