### ISSUE TITLE
Developer Portal not loading; API calls (including sandbox) returning unauthorized

### ISSUE THREAD

**Issue by r-wilson-ire** [reapit/foundations#7245]
**Describe the bug**
After logging into the developer portal, the pages do not fetch any data.
Calls to the API, which were previously working, are now returning 401 error - even for the SBOX account

**To Reproduce**
Steps to reproduce the behaviour eg:
1. Go to https://developers.reapit.cloud/
2. Log into account
3. Apps, Analytics, API etc don't load any data, the loading gif remains on the page, and a 'Failed to fetch' error appears

In terms of the API calls, calls to endpoints
https://connect.reapit.cloud/token - return fine
https://platform.reapit.cloud - not working, 

eg calling 
/properties?pageSize=1&pageNumber=1 
for SBOX account with valid token, is returning 401 error

**Expected behaviour**
The pages to load with data
API calls with valid token and the Customer ID return successfully

**Screenshots**
![image](https://user-images.githubusercontent.com/103089332/178165630-16ed9296-f2bb-4bd1-b198-a2cbaef09da6.png)
![image](https://user-images.githubusercontent.com/103089332/178165648-c2c1d69d-36a5-4d2e-b531-7244f3061df0.png)
![image](https://user-images.githubusercontent.com/103089332/178165657-9fad6a61-28e3-4db4-9bcc-135f8506a520.png)

**Device (please complete the following information for web issues):**
 - Device: PC
 - OS: Windows 10
 - Browser Chrome
 - Version 103.0.5060.114 

**Additional context**

**Comment by plittlewood-rpt** [comment]
@r-wilson-ire this issue should now be resolved

**Comment by r-wilson-ire** [comment]
Can confirm it's now working, thank you :)
