### ISSUE TITLE
Datetime saved in DB

### ISSUE THREAD

**Issue by komalpuri27** [reapit/foundations#7246]
**Summary**

Which timezone is used to save the datetime in the DB for checkout time?

I had a quick word with Craig from QA team and he brought to my notice that there is a value in the CONFIG table/ column called 'uDbTimeZone' set at company level in AgencyCloud, it seems that this value will always match the server time.

If this is the case how can we fetch this config so that we can use the same for the client(company) to show the checkout  datetime matching to AC on the MyAgency app.

**Detail and or supporting links and screenshots**
![image](https://user-images.githubusercontent.com/94682169/178226069-d8ab4773-7ba2-4053-b3e5-e61d22a91b67.png)
![image](https://user-images.githubusercontent.com/94682169/178226101-bb97fcbf-e852-4dce-ab98-707e34bfffe9.png)

**Comment by plittlewood-rpt** [comment]
Hi @komalpuri27 - that Platform APIs use UTC explicitly, so you can just display the time in the client's native timezone on their device. I'm not sure I fully understand the problem you are reporting. In your example above, I'm guessing the timezone you are working in is 7 hours ahead of UTC, which explains the difference between the API output and what you see in AgencyCloud (as it will display the appointment in your local time)

**Comment by komalpuri27** [comment]
ok got it thanks a lot again @plittlewood-rpt
