### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#7251]
Update our docs to include information about interacting with our documents/download endpoint 

e.g. ‘application/octet-stream’.  

Add comment to Glossary (documents entry) that explains this being a required value for the Accept header

Look at whether we can somehow include this in the Swagger spec

**Comment by plittlewood-rpt** [comment]
Documentation is already on the swagger endpoint but we have to adjust the behaviour of the swagger UI component so that the endpoint works, which is why it is not visible currently.
