### ISSUE TITLE
Reapit Foundations REST API - Collection calls occasionally returning duplicate data.

### ISSUE THREAD

**Issue by BYM-Henry** [reapit/foundations#7258]
Hi Reapit Team,

Hope you are all doing well.

**Describe the bug**
Reapit Foundations REST API is occasionally returning duplicate data and not respecting page sizes.

**To Reproduce**
Making an API call for a specific page of data, the same entity will be duplicated and the page count will include the duplication. The bug seems to be related to specific entities within that page. (It's the same entity every time).

An example property that seems to cause this is **HWD210021** for customer Miller Metcalfe. And the duplication can be caused at the time of writing this with the following API call:

https://platform.reapit.cloud/properties/?pageSize=100&pageNumber=16&sortBy=-modified&modifiedFrom=1900-01-01&fromArchive=true

Please note - I have only found this issue with the property entity.

Additional examples can be provided if required.

**Expected behaviour**
Entities not to be duplicated in response and the response body to respect the given page size if in the correct bounds.

**Screenshots**

![image](https://user-images.githubusercontent.com/51915903/178365985-64aa841a-04ec-4549-b8b2-83940b30d750.png)

Can provide additional screenshots if required.

**Device (please complete the following information for web issues):**
N/A

**Additional context**
N/A

Many Thanks,

Henry Fitch
Integrations Developer

BriefYourMarket

**Specification**
- Project: Reapit.Services.Properties
- Try to replicate this issue and understand why it is occurring. The behaviour described is odd and the result containing more records than it should do is equally puzzling. Discuss with team any fixes if required
- If this is an issue with how we handle archived data it's likely the same problem will exist in other services with archive support
- Update: This is happening due to a duplicate RM entry in the extra table for this record. The duplicate will be being caused due to the join happening on the database. This is bad data that should be cleaned up, however we should try to safeguard against this in the service

**Comment by plittlewood-rpt** [comment]
Hi @BYM-Henry - is it just this customer you have noticed this with or have you seen this elsewhere. The underlying cause is bad data which we can get cleaned up and ask the desktop team to try and work out how it got into that state, but if you've seen this with other customers it might be a bug that's been lurking in the CRM for a while and so we might need to safeguard against this scenario in the API.

**Comment by BYM-Henry** [comment]
Hi @plittlewood-rpt ,

Cheers for taking a look at this.

I have only noticed this on the one customer mentioned above, the reason I raised it was because it was causing our integration to be unable to process that page. We have since done some work our side to fix this, so for us this is no longer a burning issue.

Henry

**Comment by plittlewood-rpt** [comment]
@BYM-Henry  thanks - we'll be pushing an update out soon to safe-guard against this data which looks like it's being caused by a bug in AgencyCloud.
