### ISSUE TITLE
app-builder ux overhaul

### ISSUE THREAD

**Issue by joshbalfour** [reapit/foundations#7265]
First page is created via "create app"-esque wizard.
Contained in slide-out panel from the left.

Page selector dropdown is now a tab bar
* New page screen appears if no pages are created, has big button options: [table page] or [form page] or (later) [content page]

On table & form pages:
* There's a big placeholder block in the middle of the page which lets you select an entity for your form or table
* When an entity is selected the customise panel is usable
* user-created form page form can only be create forms

With the customise panel for a table, if the user specifies:
* The entity is editable -> form page is created with the same fields as are on the form
* The entity isn’t editable -> above mentioned form page is deleted
* The entity is create-able -> secondary nav is added with create button

Navigation bar:
* When you select an entity for a page, a navigation item is added to the navigation bar (with the name of the entity, and a suitable icon for that entity which we pick)
* If you have multiple table/form pages for the same entity they come under the secondary nav
* Content pages can sit top level for now

The only components available in the components panel are content ones.
You can’t put things next to each other (no grid), so on form/table pages you can only put content above and below the form/table.

If anyone requests features we've taken out we can always add them back later.

Hold on a branch

**Comment by willmcvay** [comment]
Broken down into separate tickets @joshbalfour
