### ISSUE TITLE
Bad Request from PUT to /contacts/{id}/subscriptions/{subscriptionId}

### ISSUE THREAD

**Issue by stebrough** [reapit/foundations#7274]
**Describe the bug**
400 - Bad Request - Value cannot be null. (Parameter 'contact')

**To Reproduce**
PUT request to /contacts/DBI21012506/subscriptions/CONT5

{"status":"subscribed"}

**Expected behaviour**
200 Response Code

**Additional context**
Client supplied by email to sinfo@

**Comment by AshDeeming** [comment]
Hi @stebrough 
The contact referenced above appears to be archived.

**Comment by stebrough** [comment]
Hi @AshDeeming so we cannot update these for archived?

**Comment by stebrough** [comment]
Hiya @AshDeeming we could do with talking about this further, we would like to be able to update both non-archived and archived customers ideally.
