### ISSUE TITLE
Finding who is holding security deposit

### ISSUE THREAD

**Issue by LouisaEvosite** [reapit/foundations#7278]
Hi,

We are struggling to find who is holding the security deposit for tenancies.
Have had a look through the tenancy and conveyancing endpoints among others but not having any luck,

Thanks,
Louisa

**Comment by AshDeeming** [comment]
Hi @LouisaEvosite 
Although we surface the Deport Amount & Type in the Properties Endpoint - the deposit 'holder' is not currently surfaced on the Platform. 

This can be requested for review via; [Feature Request](https://github.com/reapit/foundations/issues/new?assignees=&labels=external-request%2C+needs-triage&template=feature_request.md&title=)

**Comment by LouisaEvosite** [comment]
Have created a feature request, thank you
