### ISSUE TITLE
Property Status

### ISSUE THREAD

**Issue by LouisaEvosite** [reapit/foundations#7279]
Hi again,

Hopefully quick question- Reapit users have properties set to Market Appraisal.
However we don't have that status in the property endpoint. Am I correct in assuming that "Market Appraisal" is mapped to the status "valuation"?

Thanks,
Louisa

**Comment by AshDeeming** [comment]
Hi @LouisaEvosite 
That's correct, Market Appraisal & Valuation are interchangeable  

Property status ; 
![image](https://user-images.githubusercontent.com/61687775/178709234-fcf695b3-9c55-464d-b80d-634d5b7df544.png)

**Comment by LouisaEvosite** [comment]
Lovely, thank you!
