### ISSUE TITLE
Finding buyer progress

### ISSUE THREAD

**Issue by LouisaEvosite** [reapit/foundations#7281]
Hi,

With previous webservice API we would receive a chain / offer list which contained the following:

                    [Mortgage] => Not needed
                    [MortgageValuation] => Pending
                    [SurveyCarriedOut] => Pending
                    [AdditionalSurvey] => Pending
                    [AdditionalSurveyCarriedOut] => Pending
                    [AdditionalSurveyType] => Pending
                    [AdditionalSurveySurveyorID] => Pending
                    [AdditionalSurveyCompleted] => Pending
                    [LeaseholdPackRequested] => Pending
                    [LeaseholdPackReceived] => Pending
                    [BuyerSolInstructionsReceived] => Pending
                    [SellerSolInstructionsReceived] => Pending
                    [BuyerandSellerIDSigned] => Pending
                    [DraftContractRequested] => Done
                    [DraftContractReceived] => Done
                    [LocalSearchRequested] => Done
                    [EnquiriesRaised] => Pending
                    [ChainProgressCheck] => Pending
                    [LocalSearchRecieved] => Done
                    [AllContractEnquiriesAnswered] => Pending
                    [ChainReady] => Pending
                    [BuyerReportedto] => Pending
                    [BuyerContractSigned] => Pending
                    [SellerContractSigned] => Pending

I've found something similar in Foundation's conveyancing but we are missing a few key values we require which were in the original webservice chain (eg LeaseholdPackRequested, BuyerSolInstructionsReceived, SellerSolInstructionsReceived, BuyerandSellerIDSigned)

Could you point me in the direction to find them please?

Thanks,
Louisa

**Comment by AshDeeming** [comment]
Hi @LouisaEvosite 
Any endpoints not currently covered can be requested via the link below
[Log a Feature Request](https://github.com/reapit/foundations/issues/new?assignees=&labels=external-request%2C+needs-triage&template=feature_request.md&title=)

These will then be reviewed by the relevant team & updated accordingly

**Comment by LouisaEvosite** [comment]
Thank you, issue raised here: https://github.com/reapit/foundations/issues/7319
