### ISSUE TITLE
some marketplace listings links are assumed to be relative but should be absolute

### ISSUE THREAD

**Issue by joshbalfour** [reapit/foundations#7283]
**Background context or User story:**
I don't know if this should be solved at render level or input, or if it's just user error that could be caught on review.

www.justmovein.com/agencies -> https://developers.reapit.cloud/www.justmovein.com/agencies
https://marketplace.reapit.cloud/apps/a3830910-e205-4585-a13d-5653b923f0d4 

hello@homeppl.com -> https://marketplace.reapit.cloud/hello@homeppl.com
https://marketplace.reapit.cloud/apps/accb8c8a-a07b-48c6-9259-1d08954af7ae

**Specification or Acceptance Criteria:**

**Comment by willmcvay** [comment]
Down to poor customer data
