### ISSUE TITLE
PropertyImage:Modified webhook not firing?

### ISSUE THREAD

**Issue by waters-chris** [reapit/foundations#7287]
Good morning,

We are not receiving the `propertyimage:modified` webhook whwen changes are made in Agency Cloud.

We do receive the `ping` when we test it via the web portal.

As far as I can see, it looks as though I have set it up correctly?

![image](https://user-images.githubusercontent.com/57227713/178939609-f185f830-3193-460a-89ac-594b88642ab0.png)

Do we need to turn it on at the Agency Cloud level (it appears as though this is possible in this issue? https://github.com/reapit/foundations/issues/6650)

The app in question is "you-group-youq-importer", id: `efdb39d8-45f9-4b4e-bca4-f7a47d3d4aec`

Thanks for your help,
Chris.

**Comment by HollyJoyPhillips** [comment]
SI ticket for reference SI-17846

**Comment by waters-chris** [comment]
Thanks @HollyJoyPhillips .

However we're still not receiving anything via the webhook.  

In AgencyCloud I've tried changing an existing picture's name, a pictures type (from photo to floorplan), and uploading a new image and subsequently deleting it, yet neither have triggered a webhook.  All after closing and restarting AgencyCloud.

Specifically I've done this to pictures of property BOU220041.

Is there anything else that I need to have done?

Thanks,
Chris.

**Comment by HollyJoyPhillips** [comment]
Hi @waters-chris, i'm looking into this now. Cheers, Holly

**Comment by HollyJoyPhillips** [comment]
Hi @waters-chris I believe this should now be resolved, please can you confirm?

**Comment by waters-chris** [comment]
Hi @HollyJoyPhillips 

Yes - the webhook appears to be firing now, thank you.

**Comment by HollyJoyPhillips** [comment]
Thank you for letting us know.
