### ISSUE TITLE
statusCode 403 for Applicant Endpoint despite permission added to the app profile

### ISSUE THREAD

**Issue by jasdigital** [reapit/foundations#7289]
We're getting the following response from the SBOX account when trying to retrieve applicant details. 

`"statusCode": 403,
    "dateTime": "2022-07-14T10:47:07.8088760Z",
    "description": "This application has not been granted the required scope to interact with this endpoint. If your application requires access to this resource, please use the Reapit Foundations Developer portal to request permission to access this resource"`

The app has been setup with the 'Read Applicant' permissions etc, the swagger bearer token returns the result but our Bearer tokens in app do not.

We expect the applicant information to be returned.

Can you confirm we can access the SBOX applicant details? All other endpoints are returning data with the same headers and authentication.

**Comment by jasdigital** [comment]
We've managed to find the issue, it was conflict in clientId's on our end.

**Comment by AshDeeming** [comment]
Thanks for the update @jasdigital
