### ISSUE TITLE
Client Bradford and Howley is not set up to allow access to documents via the API

### ISSUE THREAD

**Issue by jwr8385** [reapit/foundations#7291]
Our app is having API requests to download documents for this specific client refused.

This is not a bug or a feature request.  It's a request to have the appropriate permissions rectified on the above named client so that our app can access this client's documents, as it does successfully for all other clients so far.

**Comment by jwr8385** [comment]
This issue has been resolved.  No changes made to our app so I presume
permissions have been granted to the account by Reapit or it was an
intermittent issue with Reapit.

**Comment by HollyJoyPhillips** [comment]
Hi @jwr8385 that's good news but we hadn't changed anything. Please let us know if it happens again and thanks for the update.
