### ISSUE TITLE
Client Winkworth - return some custom fields for properties in Foundations API

### ISSUE THREAD

**Issue by diger74** [reapit/foundations#7295]
Hi guys!

We are migrating our property feed for Winkworth from old Reapit API to Foundations API. As part of the mapping excersise I've found that there are a few fields (perhaps custom fields?) that are not returned in Foundations API. Would you be able to add these fields into the response of Properties API endpoint of Foundations API, please?

Here are the fields:

- [x] 1. PrpInFocus (bool) - _used as a "featured" flag on the website_ #7452 
- [x] 2. IsDevelopment (bool) - _fields 2-6 are used to present developments and their plots_
- [x] 3. IsSubPlot (bool)
- [ ] 4. SubPlots (e.g. "SubPlots": [ { "ID": "rps_wnk-HEN210052" } ])
- [ ] 5. Developer (e.g. "Developer": [ { "ID": "rps_wnk-BAT18000837" } ])
- [ ] 6. PrimaryDevelopment (e.g. "PrimaryDevelopment": { "ID": "rps_wnk-PGN180186" })
- [ ] 7. Location (string?)
- [x] 8. LocationExtra (string) #7452 
- [x] 9. MaximumReceptionRooms (int) #7453
- [x] 10. MaximumBathrooms (int) #7453

**Comment by diger74** [comment]
@AshDeeming Hi! I've added 2 more fields required in Foundations API - MaximumReceptionRooms and MaximumBathrooms

**Comment by plittlewood-rpt** [comment]
hi @diger74 - please can confirm what the difference is between items 7 and 8? I can see this customer only have a single "Location" description so I'm not sure what you are expecting here.

I'm going to start breaking this ticket down. Some of the items can be handled by existing mechanisms, and some a new features so it makes sense to split this up. I will link any new tickets back to this one

**Comment by plittlewood-rpt** [comment]
Hi @diger74 to answer your queries regarding developments, at the moment the way developments are understood via the API is through the _links collection only. If a property is a sub plot, it will contain a link back to the master record (called `master`). On the other side if a property is a master record, it will contain a link to the sub plots called `subPlots`. This lets you deduce wether or not a property is a subplot/master record. With this information I think you can answer points 2-6 as follows:

2. IsDevelopment (bool) - `true` if a `master` or `subPlots` link appears in the `_links` collection
 3. IsSubPlot (bool) - `true` if a `master` link appears in the `_links` collection
 4. SubPlots (e.g. "SubPlots": [ { "ID": "rps_wnk-HEN210052" } ]) - use the `subPlots` link in the `_links` collection which is visible on a master record
 5. Developer (e.g. "Developer": [ { "ID": "rps_wnk-BAT18000837" } ]) - this is the only one I'm not quite sure of yet. If the developer is selling the property (which is normally the case) you can access this information from `GET /vendors/{id}` when {id} is the id of the property that is the master record. There'll be a link in the `_links` collection called `vendor` to allow your consuming application to self-follow links
 6. PrimaryDevelopment (e.g. "PrimaryDevelopment": { "ID": "rps_wnk-PGN180186" }) - assuming this is a link back to the master record, this is accessed using the `master` link in the `_links` collection, included when the property is a sub plot

Please can you review the above and let me know if this answers your questions on developments?

**Comment by plittlewood-rpt** [comment]
Hi @diger74 

Ticket #7452 has now been completed and the data should be available within the next 15 minutes once the configuration changes have synchronised to the whole estate:

Use pPrpInFocus and pLocation variables to access ie GET /properties?extrasField=pPrpInFocus&extrasField=pLocation or GET /properties/XXX123456?extrasField=pPrpInFocus&extrasField=pLocation

Thanks
