### ISSUE TITLE
Type "PH" insert into journal gives an error

### ISSUE THREAD

**Issue by Speedway1** [reapit/foundations#7296]
POSTing into journal entries using type "PH" gives an unsupported type error, even though it's in the listed of supported types and that journal has such entries in it, albeit posted there by Reapit itself.

**SCREENSHOTS**
Here is the screenshot of the error in the API call: https://drive.google.com/file/d/1ou1nZZw58gMzA3gkMQYg0e5jLKUlOITQ/view?usp=drivesdk

Here are the screenshots showing the send and the corresponding Journal entry (with type "PH") in the Reapit RPS application:
Step 1: https://drive.google.com/file/d/12V3TtOVylCdkZCuY-PWF5thY5lMiK6me/view?usp=sharing
Step 2: https://drive.google.com/file/d/1YTCM4bxjk_AaZ1IMDdQLm8jj4VyFladj/view?usp=sharing
Step 3: https://drive.google.com/file/d/17uvWRTW7rtMyuRQCQo-GRW7yKFbOEdJT/view?usp=sharing
Step 4 (showing the journal entry): https://drive.google.com/file/d/1HsnhWkQyDuAIeOiNcrn5l6AXyIDwMStY/view?usp=sharing

**Comment by Speedway1** [comment]
Giving this a bump

**Comment by plittlewood-rpt** [comment]
Just doing some housekeeping. This is now available and was completed as part of #9903
