### ISSUE TITLE
Enhance filters on webhook transaction logs

### ISSUE THREAD

**Issue by rochellelevy** [reapit/foundations#7299]
**Is your feature request related to a problem? Please describe.**
When we receive queries from users, we rely on a quick efficient ways to query transaction logs so that we can respond to incidents raised to us. New Relic provides us with a really quick way to query our own logs, but thats only from the point we receive  a message from ReapitApi. Today, I spent at least 45 minutes in the transaction logs looking for one appointment that was set up at  'roughly' 10.30. We're a small team and really pressed for time and spending time searching through logs isnt ideal and slows us down. 

**Describe the solution you'd like**
at the very least, 
- A way to get the Reapit ID so that we can search for the event (we have no visibility of ReapitID's or property IDs)
- Filter the logs by Negotiator ID
Even better:
- A way for us to load the logs into New Relic so we can query it

**Describe alternatives you've considered**
I dont think there are any alternatives

**Additional context**

**Specification**
- Project: Reapit.Services.Webhooks
- Add additional filters to GetLogsQuery():
  - EntityId -> converts to Payload.Contains
  - EventId -> converts to EventId.Equals
  - TopicId -> converts to TopicId.Equals
 - As per existing rules, applicationIds MUST be set to be able to use any of the additional filters (this is the current behaviour anyway)
 - Once backend updates are made, liaise with frontend team

**Comment by RWilcox-Reapit** [comment]
Requires further investigation/discussion into querying this at a DB level. @plittlewood-rpt

**Comment by plittlewood-rpt** [comment]
Hi @rochellelevy - please see specification on the ticket above. The way to combat this looks likely to be to provide additional filters on that transactions page. The obvious ones are entity id/event id. Can you let me know your thoughts on the suggested implementation

**Comment by plittlewood-rpt** [comment]
Backend work has been released. Ticket logged for frontend to implement new filters
