### ISSUE TITLE
Unable to connect to the 'Reapit Online Demo UAT' 

### ISSUE THREAD

**Issue by komalpuri27** [reapit/foundations#7303]
**Describe the bug**
We need to connect to 'Reapit Online Demo UAT' (client id = REP) client's database in order to hand over the 'UK myAgency app' for UAT purposes to the UK team, but we are blocked by a 500 server error.
This  'Reapit Online Demo UAT' has already installed the MyAgency app from the marketplace, which has the app id = f5cc2f15-db3e-4cb2-8339-4809ac49e4ee

**To Reproduce**
Steps to reproduce the behaviour eg:
1. When we do this request to fetch negotiator and offices 

`method : "get" 
url: "https://platform.reapit.cloud/negotiators/"
array:4 [
  "query" => "pageNumber=1&pageSize=100&modifiedFrom=2016-11-03T09%3A20%3A14%2B00%3A00&sortBy=modified"
  "headers" => array:4 [
    "api-version" => "2020-01-31"
    "Accept" => "application/json"
    "Authorization" => "Bearer eyJraWQiOiJFXC9TcnVuTzVCR0xBMk1yT3phY2RjWFkwVVdqRVB1cVB5N3hIb1FWbnJGdz0iLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiI3ZDA1OGVmNjQ0aWU2ZDNxN3RqaG44bjFyOSIsInRva2VuX3VzZSI6ImFjY2VzcyIsInNjb3BlIjoiYWdlbmN5Q2xvdWRcL2NvbXBhbmllcy5yZWFkIGFnZW5jeUNsb3VkXC9sYW5kbG9yZHMucmVhZCBhZ2VuY3lDbG91ZFwvb2ZmZXJzLnJlYWQgYWdlbmN5Q2xvdWRcL2VucXVpcmllcy53cml0ZSBhZ2VuY3lDbG91ZFwvdGFza3MucmVhZCBhZ2VuY3lDbG91ZFwvY29udmV5YW5jaW5nLnJlYWQgYWdlbmN5Q2xvdWRcL2lkZW50aXR5Y2hlY2tzLnJlYWQgYWdlbmN5Q2xvdWRcL3dvcmtzb3JkZXJzLndyaXRlIGFnZW5jeUNsb3VkXC9kb2N1bWVudHMucmVhZCBhZ2VuY3lDbG91ZFwvcGF5bWVudHMucmVhZCBhZ2VuY3lDbG91ZFwvaWRlbnRpdHljaGVja3Mud3JpdGUgYWdlbmN5Q2xvdWRcL29mZmVycy53cml0ZSBhZ2VuY3lDbG91ZFwvam91cm5hbGVudHJpZXMud3JpdGUgYWdlbmN5Q2xvdWRcL2tleXMucmVhZCBhZ2VuY3lDbG91ZFwvbGFuZGxvcmRzLndyaXRlIGFnZW5jeUNsb3VkXC90ZW5hbmNpZXMucmVhZCBhZ2VuY3lDbG91ZFwvZW5xdWlyaWVzLnJlYWQgYWdlbmN5Q2xvdWRcL2NvbnRhY3RzLndyaXRlIGFnZW5jeUNsb3VkXC9pbWFnZXMucmVhZCBhZ2VuY3lDbG91ZFwvd29ya3NvcmRlcnMucmVhZCBhZ2VuY3lDbG91ZFwvYXBwbGljYW50cy5yZWFkIGFnZW5jeUNsb3VkXC9uZWdvdGlhdG9ycy5yZWFkIGFnZW5jeUNsb3VkXC92ZW5kb3JzLndyaXRlIGFnZW5jeUNsb3VkXC9qb3VybmFsZW50cmllcy5yZWFkIGFnZW5jeUNsb3VkXC9vZmZpY2VzLnJlYWQgYWdlbmN5Q2xvdWRcL3Byb3BlcnRpZXMucmVhZCBhZ2VuY3lDbG91ZFwvdmVuZG9ycy5yZWFkIGFnZW5jeUNsb3VkXC9jb250YWN0cy5yZWFkIGFnZW5jeUNsb3VkXC9hcHBvaW50bWVudHMucmVhZCBhZ2VuY3lDbG91ZFwvdHJhbnNhY3Rpb25zLnJlYWQgYWdlbmN5Q2xvdWRcL2RvY3VtZW50cy53cml0ZSBhZ2VuY3lDbG91ZFwvdGFza3Mud3JpdGUgYWdlbmN5Q2xvdWRcL3RlbmFuY2llcy53cml0ZSIsImF1dGhfdGltZSI6MTY1Nzg1NjkyOSwiaXNzIjoiaHR0cHM6XC9cL2NvZ25pdG8taWRwLmV1LXdlc3QtMi5hbWF6b25hd3MuY29tXC9ldS13ZXN0LTJfZVE3ZHJlTnpKIiwiZXhwIjoxNjU3ODYwNTI5LCJpYXQiOjE2NTc4NTY5MjksInZlcnNpb24iOjIsImp0aSI6ImU0NTJmMDQyLWIxM2ItNDE1OS1iM2UzLWQzNjRkYWQ1NmJmMyIsImNsaWVudF9pZCI6IjdkMDU4ZWY2NDRpZTZkM3E3dGpobjhuMXI5In0.SUE1x0BqdhDpVuJe3iKF8gQQRDBA_I4Lg_PVgGG-XVjfiZg0Mu4R0NliWr79MMPZ-LWu9BgEyHmuV2xpW7IwHclto_R9A1koNqm2oOWOnFhI5NsdSqc0oBPL4puotRg4GBckSZaPHMVzXq76Rou-p2q1uMGmeqfXRUt9On1fcKT-nRd3x_U53_Jod7wbyCueWXqt-dw6mBmXg2M5goAtQxhuZnxK3JIWCXS0AknMji7TsBK7HzTSYA60q3yCvlIQKxzuRGgpnSMJEEXd61kPemYHzXZp6XALvN8OUfZBeiSvFiA9AdH597TBwOkAupmIa7775fs0YJ9LTPWPc6epSw"
    "reapit-customer" => "REP"
  ]
]`

The error :

`[2022-07-15 03:32:15] local.ERROR: Server error: `GET https://platform.reapit.cloud/negotiators/?pageNumber=1&pageSize=100&modifiedFrom=2016-11-03T09%3A20%3A14%2B00%3A00&sortBy=modified` resulted in a `500 Internal Server Error` response:
{"statusCode":500,"dateTime":"2022-07-15T03:32:09.9921356Z","description":"An unexpected error has been encountered when (truncated...)`

`{"statusCode":500,"dateTime":"2022-07-15T03:56:51.7874352Z","description":"An unexpected error has been encountered when fulfilling this request. This incident has been logged and will be investigated. Please try again."}`

Same error we get when we  try to use the /Offices API.

**Expected behaviour**
We have been able to connect to sandbox client and 'Ed Dempsey' client in the past and expect the same from this new UAT client created for UAT purposes.

**Additional context**
This is very critical for us to be able to hand over the 'Myagency app' for UAT to be done by UK team before 22nd July.

**Comment by plittlewood-rpt** [comment]
Hi @komalpuri27 there is already a ticket logged with our infrastructure team about this as I spotted it in our logs the other day. I'll chase them up today

**Comment by komalpuri27** [comment]
Thanks a lot @plittlewood-rpt.

**Comment by plittlewood-rpt** [comment]
Hi @komalpuri27 you should now be able to access data using this customer id. Please let me know if it does not work as there's some odd setup here with it being an internal build

**Comment by komalpuri27** [comment]
Thanks @plittlewood-rpt the 500 error is gone now. However, now we are getting 400 error
Client error: `GET https://platform.reapit.cloud/offices/?pageNumber=1` resulted in a `400 Bad Request` response:
response:
{"statusCode":400,"dateTime":"2022-07-19T01:55:13.536029Z","description":"Option 'rpt-uat-db-clients-01.cluster-ro-ckv6cfvgq4zq.eu-west-2.rds.amazonaws.com;database' not supported."}

**Comment by komalpuri27** [comment]
@plittlewood-rpt we can close this ticket. We were provided with another UAT account and that worked for us.
