### ISSUE TITLE
Data retrieved via API different to Sandbox desktop display

### ISSUE THREAD

**Issue by lcantrell79** [reapit/foundations#7306]
**Summary**
While testing, the data retrieved via our API for vendor  MKT220642 relating to the second contact MKT22001292 was different to what was showing in the desktop.  The data had to be changed in the desktop UI for the data in the API to update so that the two were aligned again.

Is this something that could happen on live? Where the API data is out of sync with the desktop UI?

**Comment by lcantrell79** [comment]
We have another scenario which has been raised today. In Reapit we have a buyer solicitor set on applicant MKT200005. The desktop app shows the solicitors details (Buckles Solicitors LLP). In the Reapit api we do not see a solicitorId on the applicants data.

**Comment by AshDeeming** [comment]
Hi @lcantrell79 
We have been unable to replicate this issue. 

Can you confirm if there have been any other examples, please advise & we'll review.
