### ISSUE TITLE
Can't put type ID DC when we create new journal entry via api

### ISSUE THREAD

**Issue by sanjayisg** [reapit/foundations#7318]
Hi There,

Can you please let me know why we can't put DC when we create a journal entry via api, it allow us to put only MI.

Below are the response when we use DC type id:

```
{

"errors": [{

"field": "typeId",

"message": "Unsupported typeId.The following typeIds can be used when creating a new journal entry: MA,MI"

}],

"statusCode": 422,

"dateTime": "2022-07-15T12:36:46.2822282Z",

"description": "One or more validation failures have occurred. Please refer to Errors list for details"

}
```

Thanks,

Sanjay Gupta

**Comment by sanjayisg** [comment]
Hi Ash,

I am waiting for the response.

Thanks,

Sanjay Gupta

**Comment by AshDeeming** [comment]
Hi @sanjayisg 
Please note that currently there are limited Journal entries allowed, these are MA - for Property Matches and MI - For Miscellaneous
Additional types can be requested along with a requirement case for review.

**Comment by sanjayisg** [comment]
We want to put DC type, is this possible?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by sanjayisg** [comment]
HI Ash,

We do contact registration from API and once contact is registered we want to make a general entry against that which signify that contact added/detail change. When we make any entry direct with RPS the general entry says Detail Change which is DC type but we can't put DC type with API, there is restriction that we can put only MI with API.

Hope you understand the requirement.

Thanks,

Sanjay Gupta

**Comment by AshDeeming** [comment]
Hi @sanjayisg 
Currently the platform only allows MA & MI. 

You can request DC via a feature request for review, along with supporting case for the requirement.
