### ISSUE TITLE
Data retrieved via API different to Sandbox desktop display

### ISSUE THREAD

**Issue by lcantrell79** [reapit/foundations#7322]
**Describe the bug**
We have another scenario which has been raised today 18/07/22. 
In Reapit we have a buyer solicitor set on applicant MKT200005. The desktop app shows the solicitors details (Buckles Solicitors LLP). In the Reapit api we do not see a solicitorId on the applicants data.
Previous issue raised #7306

**Expected behaviour**
The solicitor shown in the desktop view should be the same as what is retrieved via the API

**Comment by AshDeeming** [comment]
Hi @lcantrell79 

The above referenced Applicant record appears to be Archived

**Comment by lcantrell79** [comment]
@AshDeeming The property was set to Completed status and may have set the applicant to an ex-applicant. The applicant still shows against the property and all other data comes through the api. Just not the solicitor. 
Would an archived applicant not have the solicitor id available as normal behaviour?
