### ISSUE TITLE
Cant see transaction logs for 18/07/2022

### ISSUE THREAD

**Issue by rochellelevy** [reapit/foundations#7325]
**Describe the bug**
Cannot see transaction logs for webhooks for DiarySync for 18/07/2022. I can see 17/07/2022 and 19/07/2022

**To Reproduce**
Steps to reproduce the behaviour eg:
1. Go to 'webhooks'
2. Click on 'transaction logs'
3. Select date range 18/07/2022
4. See error failed to fetch

**Expected behaviour**
The transaction logs described above

**Comment by plittlewood-rpt** [comment]
Likely related to #7323

**Comment by plittlewood-rpt** [comment]
Closing as part of general cleanup. This should have been addressed by ticket above
