### ISSUE TITLE
RPS software installation error

### ISSUE THREAD

**Issue by subin-roundr** [reapit/foundations#7329]
**Background context or User story:**
While installing rps sandbox environment on windows 10 machine, it doesn't install and throws an error.
Error is 
**_Component mysql-connector-odbc-8.0.15-win32.msi has failed to install with the following error message:
"Fatal error during installation. "
The following components were successfully installed:
- PDF creator
The following components failed to install:
- mysql-connector-odbc-8.0.15-win32.msi_**

**Specification or Acceptance Criteria:**

**Comment by jaetoole** [comment]
@subin-roundr you'll want to log this with the Reapit Support desk

**Comment by subin-roundr** [comment]
@jaetoole  can you please provide me the link of reapit support desk.

**Comment by subin-roundr** [comment]
hi please provide the link

**Comment by AshDeeming** [comment]
Hi @subin-roundr 
Please attempt to install again via: [AC Install](https://updates.reapit.net/install/setupdev.exe)

[Reapit Support Desk](https://reapitsupport.refined.site/)
