### ISSUE TITLE
Apps for integration do we need more than one?

### ISSUE THREAD

**Issue by Philip-CJ** [reapit/foundations#7332]
Hello, we currently have 2 integrations with Reapit, one for our website and one for Dotdigital (Email software). We have an app created for our website but do we need a separate app to be created for Dotdigital? Or can the same app be used for both integrations?

We are in a testing phase with Dotdigital and they have been using our website app, will this cause problems?

Thank you

Philip

**Comment by AshDeeming** [comment]
Hi @Philip-CJ 

If the two apps/integrations have different purposes, these should be created as separate apps.
