### ISSUE TITLE
Unable to register a new webhook

### ISSUE THREAD

**Issue by NickStallman** [reapit/foundations#7333]
**Describe the bug**
I am trying to add a new Application Install and Application Uninstall webhook to a new url for this app: f5cc2f15-db3e-4cb2-8339-4809ac49e4ee

After hitting save it pauses for several seconds (5 to 10) before returning the below error:
```
The identity attached to this request does not have the required permission to access the requested data. If you think you should be able to access this data, please use the Reapit Foundations Developer Portal to contact us to discuss the problem
```
Tweaking the settings doesn't seem to help. I haven't had issues with this in the past.

**To Reproduce**
Steps to reproduce the behaviour eg:
1. Go to Add Webhook
2. Select app
3. Enter in the URL
4. Select "Application Install and Application Uninstall"
5. Select All Customers (also does not work with just Sandbox)
6. Set as Active (also does not work if set to Inactive)
7. Hit save

The error appears across the top of the screen.

**Comment by HollyJoyPhillips** [comment]
@NickStallman Please could you log out and back in and try again?

**Comment by NickStallman** [comment]
Hi @HollyJoyPhillips this was tried over two different days, on three differett computers by two different people. We got the same thing every time.

It looked like the other functions of the Developer site were working fine although I didn't do an exhaustive test.

**Comment by HollyJoyPhillips** [comment]
@NickStallman Thank you for the feedback. I'll take another look and come back to you asap

**Comment by HollyJoyPhillips** [comment]
@NickStallman I've just tested it with an example url as the location for the app ID you provided (MyAgency) and it works. Can you see if you can edit it please?

**Comment by NickStallman** [comment]
Hi @HollyJoyPhillips 

I just tried (fresh login just now) and I get the same error when editing your example url.

I also tried just hitting Edit then clicking Update without changing any values. Same thing.

Other functions like Swagger API calls are working fine so it shouldn't be my browser session.

**Comment by HollyJoyPhillips** [comment]
@NickStallman Can you confirm which email address you are logging in with please?

**Comment by NickStallman** [comment]
nick@agentpoint.com

**Comment by HollyJoyPhillips** [comment]
Hi Nick, can you do me a favour please, can you go to 'settings' & 'profile' and send me a screen grab?

**Comment by komalpuri27** [comment]
hey @HollyJoyPhillips sorry for jumping in, I am also getting the exact same error.
This is how my profile looks like, sharing this so that we can find the solution faster.
<img width="1135" alt="image" src="https://user-images.githubusercontent.com/94682169/180415997-c70657fa-0c30-45ef-9eac-2cb6a657962a.png">

**Comment by NickStallman** [comment]
More or less the same profile for me.

![image](https://user-images.githubusercontent.com/136553/180418095-89df18e2-a4ca-49da-8a5a-b5896275d598.png)

**Comment by HollyJoyPhillips** [comment]
@NickStallman & @komalpuri27 Thank you both for your patience whilst we had a look. I can confirm it should be working for you now. Please let me know if you have any further issues.

**Comment by komalpuri27** [comment]
yeah @HollyJoyPhillips this worked, thanks.

**Comment by HollyJoyPhillips** [comment]
@komalpuri27 Thank you for confirming.
