### ISSUE TITLE
Field Availability - No Internet Advertising

### ISSUE THREAD

**Issue by BYMIntegrations** [reapit/foundations#7336]
Please take a look at our FAQ's before submitting an issue, as your question may already be covered in the documentation https://foundations-documentation.reapit.cloud/faqs

**Summary**
Hello! do you know if the field "No Internet Advertising" is available on the API?
**Detail and or supporting links and screenshots**
![image](https://user-images.githubusercontent.com/102583061/180232456-b3fa8d89-317f-43bf-a9c2-02aa128a05d2.png)

**Comment by AshDeeming** [comment]
Hi @BYMIntegrations 
Please see the swagger API page via;https://developers.reapit.cloud/swagger

In the example provided, you'll see the below; - where InternetAdvertising is 'true'  
![image](https://user-images.githubusercontent.com/61687775/180398151-08ba0c7f-6aab-4400-b76d-5251e8f8e479.png)
