### ISSUE TITLE
Unable to login via Reapit Connect 

### ISSUE THREAD

**Issue by nroper** [reapit/foundations#7339]
**Summary**

My colleague is unable to login or change password despite their developer account being shown as active.

**Detail and or supporting links and screenshots**

Tried loging in but gets:

![image_2022_07_19T15_13_20_771Z (1)](https://user-images.githubusercontent.com/479971/180246342-8a02bd1e-d1a7-431f-b810-dec417ae7bd7.png)

Tried resetting password but gets:

![image_2022_07_19T15_13_57_081Z (1)](https://user-images.githubusercontent.com/479971/180246634-6df33b79-0237-4aca-9526-3553206b3370.png)

As I say, the account is shown as active in the Developer Portal.

If someone could investigate and advise that would be much appreciated.

**Comment by AshDeeming** [comment]
Hi @nroper 
The user should have now had an email to reset their password

**Comment by nroper** [comment]
Hi @AshDeeming - yup, that seems to have worked, thanks for looking into it.
