### ISSUE TITLE
Listing images not accessible 

### ISSUE THREAD

**Issue by komalpuri27** [reapit/foundations#7341]
**Describe the bug**
We are not able to access the listing images for the UAT client details provided to use. 
Client name Reapit Online Demo, (ROD)

**To Reproduce**
Steps to reproduce the behaviour eg:
1. Go to property id : BCK150066
https://assets.reapit.net/sbox/live/pictures/BCK/15/BCK150066_46.jpg
https://assets.reapit.net/sbox/live/pictures/BCK/15/BCK150066_38.jpg
https://assets.reapit.net/sbox/live/pictures/BCK/15/BCK150066_41.jpg
3. See error
And the error we are getting 
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>HZG1SGEC2HY6J8ZK</RequestId>
<HostId>OULMoGgi8/Ut+FRHXYXTILlXDbE4/zm+ZcDrYzbHUfEzs7wDZQpdPMW7go6u9kNn1P0NELaales=</HostId>
</Error>
**Expected behaviour**
The foundations API should return us the image url which is accessible

**Screenshots**
Logging into AC shows us the property images
![image](https://user-images.githubusercontent.com/94682169/180347620-f5e4e1f2-d860-498b-9a10-262dd8a7d31e.png)

**Comment by aalim405** [comment]
The company code for the new environment is ROD therefore we should be using the following URL: 

https://assets.reapit.net/rod/live/pictures/BCK/15/BCK150066_46.jpg
https://assets.reapit.net/rod/live/pictures/BCK/15/BCK150066_38.jpg
https://assets.reapit.net/rod/live/pictures/BCK/15/BCK150066_41.jpg

**Comment by komalpuri27** [comment]
Got it, thanks @aalim405

**Comment by komalpuri27** [comment]
Hi @aalim405 , when I try the property Image API for the property id  BCK150066  
<img width="917" alt="image" src="https://user-images.githubusercontent.com/94682169/180397091-2578b84a-8fbb-4001-8c80-fa7d2ab8489b.png">
It has sbox in the url. 

Will we always get the urls like this and then we have to replace sbox with the client id (ROD) in this case, or should the urls be correct in the response itself.

**Comment by plittlewood-rpt** [comment]
Hi @komalpuri27 you must be using the Sandbox customer id here and not ROD. It's not possible to end up with URLs containing sbox if you use another customer id as that URL is built based on the caller identity which in the case of ROD would have ROD set as the customer id.  If you can provide a full request I can look at that would be useful.

**Comment by komalpuri27** [comment]
This can be closed.
