### ISSUE TITLE
Where does existing DLL Extension store it's data?

### ISSUE THREAD

**Issue by nbdesignstudio** [reapit/foundations#7346]
Can you please help identify WHERE data is stored for our old DLL Extension setup, as we need to have access to this data within our new App and therefore your API.

The data can be seen in the Agency Cloud setup using the DLL Extension on the Identity Check popup panel.

And therefore we have been led to believe that the data would be available via the API when using the /IdentityChecks/ API method?

However when we pull the client Identity Check data, the expected document details and linking file is NOT available.

Therefore, where is this data stored within Agency Cloud, and how can we access it via the API to preserve data connections for thousands of existing case records.

I have also messaged Holly and Pete directly asking about this and our client has message Alex as well.

**Comment by AshDeeming** [comment]
Hi @nbdesignstudio 
Please can you confirm the app name & what DLL was previously used?

**Comment by nbdesignstudio** [comment]
Hi Ash. 

Yes sure, we are developing the Smart Compliance App for Lifetime Legal.

And it is the pre-existing DLL extension for Lifetime Legal that existing EA partners are currently using.

**Comment by nbdesignstudio** [comment]
@AshDeeming, are you able to help with this issue

**Comment by AshDeeming** [comment]
Thanks @nbdesignstudio 
I'm awaiting confirmation however my understanding is that the data from this may be stored in 'extra' 
If you know the fields required, you can log a [Semi-structured 'extras' field request](https://github.com/reapit/foundations/issues/new?assignees=&labels=back-end%2C+needs-triage&template=extras_field.md&title=)  to be reviewed

**Comment by nbdesignstudio** [comment]
Hi @AshDeeming ok thanks, hopefully you can get some more information.

No we do NOT know the fields required, that is the point, we don't know where the DLL extension saves the file at all, we just know it does save the file and that your Users can access it on the normal Identity Check page, once it has been saved. But we believe this download button is held outside of the normal Identity Check document data, which we can access via your API.

What is 'extra'? Is this 'extra' something we would be able to access via your API, and if so how?

If someone was able to have a phone conversation with me about this, that would be really helpful.

**Comment by plittlewood-rpt** [comment]
hi @nbdesignstudio - I responded to your email on this today. Can you let me know if that's clarified things?

**Comment by nbdesignstudio** [comment]
Hi @plittlewood-rpt 

Yes your email was helpful and without it, we had no idea where the files where being saved.

**Comment by plittlewood-rpt** [comment]
Thanks - I'll close out this ticket in that case.
