### ISSUE TITLE
Update Reapit Employee accounts

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#7347]
**Summary**: All reapit employee accounts should be associated to our main reapit developer account and have access to the AppMarket

PL/HP to review previous spreadsheet... 

- Move all reapit.com accounts over to the main reapit developer account

Tasks
- [x] Identify existing developer accounts that can be moved immediately (ones with no apps)
- [x] Identify existing developer accounts that have apps and need more attention - emailed four remaining devs
- [x] Construct mechanism to add any existing employees who do not currently have developer accounts to the Reapit developer org (this will require a member and group memberships) - scripts build. Pending discussion with HP
- [ ] Understand the process for new starters

**Comment by plittlewood-rpt** [comment]
I'm going to close this item - there's separate conversations which will continue about new starter process but the main objective of this ticket has been handled
