### ISSUE TITLE
Selecting only commercial or residental

### ISSUE THREAD

**Issue by DanSayer** [reapit/foundations#7353]
How would I go about selecting only commercial entries or only residential entries?

**Comment by AshDeeming** [comment]
Hi @DanSayer 
Please see the Departments Endpoint;
https://foundations-documentation.reapit.cloud/platform-glossary#department

![image](https://user-images.githubusercontent.com/61687775/180737703-ebf8e822-4582-4750-ac82-fbbb2be84e21.png)
https://developers.reapit.cloud/swagger
