### ISSUE TITLE
Gas safety start date and expiry date

### ISSUE THREAD

**Issue by LouisaEvosite** [reapit/foundations#7357]
**Is your feature request related to a problem? Please describe.**
We require the start date and expiry date for gas safety certificates.
We need this to know when a gas safety certificate is no longer valid and which is the most recent one.

**Describe the solution you'd like**
Dates to come through new fields in the document response.
Currently we get the gas safety certificate by doing a call to the document end point like this:  /documents?associatedId=[propertyID]&associatedType=property&typeId=GSC

**Describe alternatives you've considered**
N/A

**Additional context**
Screenshot of the data in Reapit we need:

![image](https://user-images.githubusercontent.com/109209591/180607495-ffc88dc2-9584-4c06-842b-d4d082a3dd5f.png)

**Comment by plittlewood-rpt** [comment]
Hi @LouisaEvosite this information should already be available at `GET /properties/{id}/certificates`

**Comment by NBareham** [comment]
Hi! Louisa is on holiday this week - she'll come back to you when she's back in on Monday.

**Comment by plittlewood-rpt** [comment]
Hi @NBareham that should be the case yes. Any certificates stored against a property should show their dates on the same endpoint

**Comment by plittlewood-rpt** [comment]
@NBareham @LouisaEvosite have you had chance to review my notes above?

**Comment by LouisaEvosite** [comment]
Hi @plittlewood-rpt - looks like we've got what we need for this one, thank you

**Comment by plittlewood-rpt** [comment]
Thanks for confirming
