### ISSUE TITLE
Clarification about appInstall webhook fields

### ISSUE THREAD

**Issue by NickStallman** [reapit/foundations#7359]
**Summary**

I've been diagnosing why we could not correctly determine which app was installed, when supporting multiple apps from a single endpoint.

The app I was looking at has the following identifiers:
```
Authentication Client Id: 7d058ef644ie6d3q7tjhn8n1r9
App Id: f5cc2f15-db3e-4cb2-8339-4809ac49e4ee
```

And it turns out we were getting this from the app install webhook:
```
    "applicationId": "7d058ef644ie6d3q7tjhn8n1r9",
    "internalAppId": "f5cc2f15-db3e-4cb2-8339-4809ac49e4ee",
```

From our (external) perspective, this is very wrong, the applicationId in the webhook is not the application Id at all! We were reviwing our code which wasn't functioning and of course the code looked correct.

It may not be possible to fix these mis-named fields if they are used by live applications, however there should be clear documentation highlighting the mismatch between field names.

I reviewed https://foundations-documentation.reapit.cloud/api/webhooks which doesn't mention it at all, and Google can't find any mention of what "internalAppId" is at all.

**Specification**
- Update webhooks documentation to make the definition of these fields clear. There isn't much we can do to change the webhook payload now without introducing a breaking change

**Comment by plittlewood-rpt** [comment]
Hi @NickStallman this could be a result of some terminology changes in the frontend at some point. I'll see if I can confirm this from the frontend team. Like you say we won't be able to change these very easily but can clarify this in the documentation
