### ISSUE TITLE
Intermittent 502 Bad Gateway

### ISSUE THREAD

**Issue by jaetoole** [reapit/foundations#7361]
**Describe the bug**
Our property feed tool is reporting intermittent 502 bad gateway with the error 'Internal Server Error' (https://sentry.io/share/issue/4d70fa98235a4d85baf52016df975d39/) Jul 22, 2022 2:01:24 PM UTC

**To Reproduce**
Seems to be intermittent.

**Expected behaviour**
200 response

**Additional context**
I've got 23 instances of this happening within the last 30 days, I'm happy to go through all of these if someone wanted to give me a call?

**Specification**
- Look at the size of some of the files listed in the screenshot. It's likely these are close to the threshold for auto-redirect to the pre-signed URL download in which case it may be appropriate to tweak that threshold (lower it a bit)
- One option here could be to allow developers to specify a redirect in ALL instances of hitting the download endpoint (which is safer than us making that decision for them)
- Confirm whether the 502 is being caused by the gateway or the broker. If it's the broker another option would be to bypass it entirely for the download endpoint - approach taken

**Deployment Notes**
- Remove existing resources first (do NOT deploy the change)
- As a separate update, apply new CF template
- Monitor closely as endpoint definitions for this service have all had to change. Also monitor 502/504 as these should reduce (with no uptick in other status codes like 404s)
Not using staged approach will cause an error due to the endpoint configurations

**Comment by AshDeeming** [comment]
Hi @jaetoole 
Please could you confirm the effected app name & any other details for investigation.

**Comment by jaetoole** [comment]
@AshDeeming its NEA Sync 

If you want, if you give me a call, I can show you our more in-depth logs, I'm just limited as to what I can display in the public domain.

**Comment by AshDeeming** [comment]
Thanks @jaetoole 
The relevant team will review this. 
Please feel free to send any sensitive data that may be useful to: sinfo@reapitfoundations.zendesk.com

**Comment by jaetoole** [comment]
@AshDeeming I don't even have the ability to share that data, it has to be a logged in user. The most I can provide is this:
![image](https://user-images.githubusercontent.com/61322528/180776359-a7984b95-8493-425e-97a0-e45450178b3d.png)

**Comment by jaetoole** [comment]
Had an event 2 hours ago of the same 502 error

**Comment by jaetoole** [comment]
1 hour ago - 502

**Comment by plittlewood-rpt** [comment]
Hi @jaetoole this is likely something to do with the size of the files and the time it takes to fetch the file. When a file is detected as being over a certain size, we do a 301 redirect so the file can be downloaded directly from S3 which gets around some infrastructure limitations. We'll have a look at how big these files are as it could just be that the threshold needs adjusting slightly

**Comment by plittlewood-rpt** [comment]
Incidentally, it's worth noting that if the files you are trying to download are brochures, you can now access a public link from the properties endpoint for these documents (`.selling.publicBrochureUrl` and `.letting.publicBrochureUrl`) which might help you out here

**Comment by jaetoole** [comment]
Ah okay @plittlewood-rpt. Is there a per request charge though for every click on the publicBrochureUrl?

**Comment by plittlewood-rpt** [comment]
@jaetoole not currently no, and I'm not aware of any plans to change it. The URLs exposed in those fields are the same links we send through to the likes of Rightmove etc. If you wanted to protect yourself against any changes here though, you could just download that file from that URL instead of using the documents API.

**Comment by jaetoole** [comment]
@plittlewood-rpt Okay - we can add that into our backlog to look at but if we could stop that 502 that would be great.

**Comment by plittlewood-rpt** [comment]
After some investigation the best approach here is to bypass the broker entirely for document downloads as it removes a point of failure entirely. Have done this in dev environment but will need all endpoints testing

**Comment by plittlewood-rpt** [comment]
@jaetoole I've made some infrastructure changes so downloads are managed slightly differently internally to hopefully alleviate this issue. I'll be monitoring over the next few days to see if it's had the desired effect, but if you spot anything (good or bad) would you mind letting me know please?

**Comment by jaetoole** [comment]
@plittlewood-rpt That's great - we'll continue to monitor it our side and report back if we have any further issues.
