### ISSUE TITLE
Multiple file upload

### ISSUE THREAD

**Issue by MarcinuB** [reapit/foundations#7363]
Hello Team.
We're using the Elements UI v2 in our app. We have a facility to upload files, using FileUpload control provided by the framework. this control supports only single file upload. I've checked the v3 and FileUpload control supports single file upload too. Would it be possible to enable the multiple file upload with FileUpload control? If not possible and we would create our own implementation - would that work within Reapit?

Thank you

**Comment by willmcvay** [comment]
@MarcinuB We've considered this in the past however, as our document upload endpoint only supports single documents, it was felt that adding UI complexity was not desirable. By this I mean, we would need to support multiple images for previewing, cropping and potentially different callbacks for different image types.

You can use Elements with your own multiple file upload functionality by simply adding the relevant classes to any html file input eg from the docs https://elements.reapit.cloud/?path=/docs/fileinput--default-usage

```
<div class="el-file-input-wrap">
  <label class="el-label">Some Label</label>
  <div class="el-flex-align-center el-flex-container">
    <button class="el-mr4 el-intent-low el-button" type="button">Upload</button
    ><input
      data-testid="el-file-input"
      type="file"
      class="el-file-input"
    /><input id="random-jozgvl" class="el-file-input-hidden" value="" />
    <p class="el-has-grey-text el-has-no-margin el-small-text">Upload File</p>
  </div>
</div>
```

**Comment by MarcinuB** [comment]
@willmcvay - understood. Thank you. I was suspecting you have your reasons for that and that's ok. I just wanted to confirm that this behavior will not be prevented when app is used within Reapit - so all good.
