### ISSUE TITLE
No negotiator webhooks

### ISSUE THREAD

**Issue by NickStallman** [reapit/foundations#7370]
**Describe the solution you'd like**
Negotiators are available in the API, however there are no matching webhooks to subscribe to for negotiators.created or negotiators.modified.

This necessitates polling for any negotiator profile changes which is less than ideal and laggy.

**Comment by AshDeeming** [comment]
Hi @NickStallman 
Please could you provide any user case details for this request & i'll ensure it's reviewed

**Comment by NickStallman** [comment]
@AshDeeming for our websites or other products we are often showing an Agent (negotiator) Profile. Our clients often complain if they make changes to their profile that are not reflected in the products promptly.

Webhooks mean that it updates nearly instantly. Otherwise they could be waiting 1+ hours for our polling check to detect new data.

**Comment by plittlewood-rpt** [comment]
Hi @NickStallman - this is something in the long term roadmap and is reliant on some changes to AgencyCloud first. AgencyCloud currently updates negotiator information extremely frequently as the entity stores session information. This would lead to a huge volume of webhooks which would be undesirable for all parties. You can subscribe to the long term ticket #6297 if you wish.
