### ISSUE TITLE
Missing commercial property types in API results [Galbraith]

### ISSUE THREAD

**Issue by MSB89** [reapit/foundations#7374]
We are experiencing issues with property types not coming through in the foundations API. 

These seem to be commercial property types:

Retail 
Office 
Industrial 
Land / Development 
Restaurant 
Licensed Premises 
Hotel / Guesthouse 
Warehouse / Distribution 
Investment 
Catering 
Care Home 
Holiday Lets

These were available in the old SOAP API but not Foundations.

We previously had a similar issue with Residential properties that was resolved fairly quickly however these are still an issue and is now a blocker for us.

Is it possible to make these accessible to Galbraith and get an update on how long it may take?

**Comment by AshDeeming** [comment]
Hi @MSB89 
Please confirm you are using the Departments endpoint to call the relevant departments for the client? 
Any none standard attributes will need to be requested via a [Semi-structured 'extras' field request](https://github.com/reapit/foundations/issues/new?assignees=&labels=back-end%2C+needs-triage&template=extras_field.md&title=)

**Comment by MSB89** [comment]
@AshDeeming 

We have tried to use the GET /departments/ and GET /departments/C endpoints.

Only Office and Industrial are available, the remaining are not, I will raise a field request.

**Comment by AshDeeming** [comment]
#7378
