### ISSUE TITLE
Request for Open house semi structured property field.

### ISSUE THREAD

**Issue by rajeshwl** [reapit/foundations#7375]
For one of our client we have `Open House flag `field in the marketing section of property details. Can you please enable the extras field for the property API and share the field details.

**Customer Code:** TLC(TLC London)
**Field:** Open House in Marketing section.
**Screenshot:**
![image001](https://user-images.githubusercontent.com/14073702/181453476-453631a4-ba5c-4adc-bccf-49dba1293a2b.png)

**Comment by plittlewood-rpt** [comment]
Hi @rajeshwl 

This has now been enabled for this customer

The extrasField you should request is "pOphou" eg

`GET /properties?extrasField=pOphou`

and

`GET /properties/{id}?extrasField=pOphou`

Please let me know if you encounter any issues
Thanks
