### ISSUE TITLE
Making commercial property types available to Galbraith.

### ISSUE THREAD

**Issue by MSB89** [reapit/foundations#7378]
**Request**

**Customer**: Galbraith

**Fields**:
Retail
Office
Industrial
Land / Development
Restaurant
Licensed Premises
Hotel / Guesthouse
Warehouse / Distribution
Investment
Catering
Care Home
Holiday Lets

**User Interface**:
![Screenshot (4) copy](https://user-images.githubusercontent.com/14941884/181512913-9a9294cd-7ac0-4887-a7c0-eb9647d292b6.png)

**Reason**:
To allow property categorisation on our new website following a move from the old SOAP API to Foundations, these property types were previously accessible in SOAP but are no longer available to us. We've previously had retail property types made accessible.

**Comment by plittlewood-rpt** [comment]
Hi @MSB89 this is something that keeps cropping up so we have spec'd out a solution as part of #6910 which will be scheduled soon
