### ISSUE TITLE
Webhook Permissions Issue? 

### ISSUE THREAD

**Issue by gazeal-uk** [reapit/foundations#7379]
Our Apps have been downloaded and installed by active users (Gazeal and Gazeal Background App). This has worked perfectly for a the first few agents. 

But we seem to have an issue with the last couple of agents with regard to webhooks, for example both Mackenzie Smith and Balgores have installed the apps but we are not receiving any webhooks at all for them. MCK in particular had permission granted by the owner so that the individual branches could download the apps, which they did. We have successfully linked them and they can send information through to us manually using the app but we are not getting the webhooks.

We do however receive all webhooks for other clients such as Cooper Adams and Ben Siggins. Is this is permission issue on the agents side? I would be grateful if you could clarify.

Many thanks

**Specification**
- Check whether or not webhooks for these customers are setup. If not, liaise with SI team. Feedback to developer as appropriate

**Comment by AshDeeming** [comment]
SI-18127

**Comment by plittlewood-rpt** [comment]
Hi @gazeal-uk 

Hooks for the agents mentioned above are all running now. Please can you confirm if there are any others you are missing.

Thanks

**Comment by gazeal-uk** [comment]
Hi Pete

Thanks, we now appear to be receiving hooks from Mackenzie Smith which 
is great, thanks.

But we are still not getting anything from Balgores (BGR) and Cooper 
Adams (COA). I'm not sure if both of these agencies have moved over to 
AWS so if you could confirm that would be great!

Many thanks



*

Bully Rai

Chief Technical Officer


Winner of PropTech Company of the Year


T: +44 (0)207 760 7582


***@***.***


A:35 Catherine Place, Victoria, London, SW1E 6DY

	

<https://www.linkedin.com/in/bully-rai-1b66489a/><https://www.instagram.com/gazeal_uk/><https://www.facebook.com/GazealUK/><https://twitter.com/gazeal_uk?lang=en>




*


Pete Littlewood wrote on 09/08/2022 08:19:

**Comment by plittlewood-rpt** [comment]
Hi @gazeal-uk - in your original report you mentioned that you ARE receiving them for Cooper Adams. Can you confirm which is accurate? Thanks

**Comment by gazeal-uk** [comment]
Hi

Apologies, Cooper Adams hooks are not being received, but I'm not sure 
if they are on AWS which may be the reason.

Balgores and Cooper Adams are the 2 that we are not receiving webhooks for.

Many thanks


*

Bully Rai

Chief Technical Officer


Winner of PropTech Company of the Year


T: +44 (0)207 760 7582


***@***.***


A:35 Catherine Place, Victoria, London, SW1E 6DY

	

<https://www.linkedin.com/in/bully-rai-1b66489a/><https://www.instagram.com/gazeal_uk/><https://www.facebook.com/GazealUK/><https://twitter.com/gazeal_uk?lang=en>




*


Pete Littlewood wrote on 09/08/2022 16:31:

**Comment by plittlewood-rpt** [comment]
Thanks @gazeal-uk I have now been able to identify the issue for both customers

Hooks for Cooper Adams should be coming through to you now
Hooks for Balgores will begin shortly - the setup task is currently re-running as there was an invalid configuration when this was initially set up.

**Comment by gazeal-uk** [comment]
Hi Pete

That's fantastic, many thanks!

Kind regards



Bully Rai

Chief Technical Officer


Winner of PropTech Company of the Year


T: +44 (0)207 760 7582


***@***.***


A:35 Catherine Place, Victoria, London, SW1E 6DY

	

<https://www.linkedin.com/in/bully-rai-1b66489a/><https://www.instagram.com/gazeal_uk/><https://www.facebook.com/GazealUK/><https://twitter.com/gazeal_uk?lang=en>






Pete Littlewood wrote on 10/08/2022 10:51:

**Comment by plittlewood-rpt** [comment]
Webhooks for Balgores are also now functioning. Thanks
