### ISSUE TITLE
First image returned from old API does not match Foundations image order, which is correct?

### ISSUE THREAD

**Issue by TobyDunnEPS** [reapit/foundations#7394]
When we pull images from Foundation, they appear with an Order attribute.  If we put the images in that order, they are the same as from the SOAP API, except for the first image from SOAP, which is out of sequence, and isn’t the Featured Image.
 
Eg for Property Ref FHH210109, Customer FRO (The Frost Partnership) Soap gives me:
```
<Filepath>[https://assets.reapit.net/fro/live/pictures/FHH/21/FHH210109_03.jpg</Filepath](https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fassets.reapit.net%2Ffro%2Flive%2Fpictures%2FFHH%2F21%2FFHH210109_03.jpg%253c%2FFilepath&data=05%7C01%7Ctoby.dunn%40epropservices.com%7Cb3eee53552024f644e7208da73b7aa75%7Cc624288244904c71b218fad48ef37b99%7C0%7C0%7C637949529937991191%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=0HyfCxTW0Z%2FchD%2FzahyCPVoZv7rMe%2Bc0uspgLILZEa0%3D&reserved=0)>
<Filepath>[https://assets.reapit.net/fro/live/pictures/FHH/21/FHH210109_01.jpg</Filepath](https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fassets.reapit.net%2Ffro%2Flive%2Fpictures%2FFHH%2F21%2FFHH210109_01.jpg%253c%2FFilepath&data=05%7C01%7Ctoby.dunn%40epropservices.com%7Cb3eee53552024f644e7208da73b7aa75%7Cc624288244904c71b218fad48ef37b99%7C0%7C0%7C637949529937991191%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=zl50bLF0FzB9FQZo5SaVGGALRnd2qz%2FAaLm01VLGino%3D&reserved=0)>
<Filepath>[https://assets.reapit.net/fro/live/pictures/FHH/21/FHH210109_02.jpg</Filepath](https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fassets.reapit.net%2Ffro%2Flive%2Fpictures%2FFHH%2F21%2FFHH210109_02.jpg%253c%2FFilepath&data=05%7C01%7Ctoby.dunn%40epropservices.com%7Cb3eee53552024f644e7208da73b7aa75%7Cc624288244904c71b218fad48ef37b99%7C0%7C0%7C637949529937991191%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=WKa%2Fc%2BS05XfbFfOdP1GMyUglfxmAka69TOusI5yV2I8%3D&reserved=0)>
<Filepath>[https://assets.reapit.net/fro/live/pictures/FHH/21/FHH210109_04.jpg</Filepath](https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fassets.reapit.net%2Ffro%2Flive%2Fpictures%2FFHH%2F21%2FFHH210109_04.jpg%253c%2FFilepath&data=05%7C01%7Ctoby.dunn%40epropservices.com%7Cb3eee53552024f644e7208da73b7aa75%7Cc624288244904c71b218fad48ef37b99%7C0%7C0%7C637949529937991191%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=xt7dMZ0VuEM1jIOdSkIXKwe1S7GHtsIAOEXimfF2jpQ%3D&reserved=0)>
```
…
 
Foundations gives me the following in the image API response - to make it more readable I’ve trimmed out some fields:
```
{
      "order": 1,
      "url ": [https://assets.reapit.net/fro/live/pictures/FHH/21/FHH210109_01.jpg](https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fassets.reapit.net%2Ffro%2Flive%2Fpictures%2FFHH%2F21%2FFHH210109_01.jpg&data=05%7C01%7Ctoby.dunn%40epropservices.com%7Cb3eee53552024f644e7208da73b7aa75%7Cc624288244904c71b218fad48ef37b99%7C0%7C0%7C637949529937991191%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=qrf1mIV5bRcH20NdVRYIqxaEqSeZyUnvrjrWl7ivRR4%3D&reserved=0)
},
{
      "order": 2,
      "url ": [https://assets.reapit.net/fro/live/pictures/FHH/21/FHH210109_02.jpg](https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fassets.reapit.net%2Ffro%2Flive%2Fpictures%2FFHH%2F21%2FFHH210109_02.jpg&data=05%7C01%7Ctoby.dunn%40epropservices.com%7Cb3eee53552024f644e7208da73b7aa75%7Cc624288244904c71b218fad48ef37b99%7C0%7C0%7C637949529937991191%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=T%2B9X0G%2FAly4ErIbZ%2B7lwUsHqJhyrdUMYps2acAb5fik%3D&reserved=0)
},
{
      "order": 3,
      "url ": [https://assets.reapit.net/fro/live/pictures/FHH/21/FHH210109_03.jpg](https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fassets.reapit.net%2Ffro%2Flive%2Fpictures%2FFHH%2F21%2FFHH210109_03.jpg&data=05%7C01%7Ctoby.dunn%40epropservices.com%7Cb3eee53552024f644e7208da73b7aa75%7Cc624288244904c71b218fad48ef37b99%7C0%7C0%7C637949529938147437%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=TVOxkSJbmcw0mOAM0nN%2FzyJlsPyGqChienndhiAfbEc%3D&reserved=0)
}
```
 
And on the property, the featured image is FHH210109_01.jpg:
`"featuredImageUrl": [https://assets.reapit.net/fro/live/pictures/FHH/21/FHH210109_01.jpg](https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fassets.reapit.net%2Ffro%2Flive%2Fpictures%2FFHH%2F21%2FFHH210109_01.jpg&data=05%7C01%7Ctoby.dunn%40epropservices.com%7Cb3eee53552024f644e7208da73b7aa75%7Cc624288244904c71b218fad48ef37b99%7C0%7C0%7C637949529938147437%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=95qe3zneOYvOtTZjvgkkm481v2ghUCmfhwhfLJzBg7I%3D&reserved=0),
 `
There’s nothing in the exported Foundation data to indicate what’s significant about Image 03 and why it should jump to the top of the list.
 

**Describe the solution you'd like**
Guidance on which is correct, and if SOAP is correct, how to get the equivalent data from Foundation

**Describe alternatives you've considered**
Persuade the clients to accept that Foundations is correct, disregard the data from SOAP

**Additional context**
Tested on several properties, the consistent pattern is an unexpected image returned first, then a match to the Foundation data

All the best,
Toby

**Comment by AshDeeming** [comment]
Hi @TobyDunnEPS 
Please note that platform API - the PropertyImages endpoint has an order option; 
![image](https://user-images.githubusercontent.com/61687775/182339015-2740590a-e606-4e2c-a3c7-02c09e63eb4b.png)

We are unable to advise regarding the SOAP API

**Comment by TobyDunnEPS** [comment]
Thanks Ash.  We are using order from the platform API already.  Is there anyone who can advise on the old API?


Toby Dunn
Head of Development

***@***.******@***.***>
121 Park Lane, Mayfair, London W1K 7AG
epropservices.com<https://www.epropservices.com/>

[cid:epsbar_3e39f08d-3fbb-48b9-9232-8ea2fd950058.jpg]<https://www.epropservices.com/>
[cid:fineandcountry_a87aae4c-7515-46df-aba8-7c2a4252e513.jpg]<https://www.fineandcountry.com/uk>        [cid:theguild_2c988f60-5328-4759-8da3-46e8486be818.jpg] <https://www.guildproperty.co.uk/>      [cid:gogetdigital_251cede1-65aa-4201-bb98-7ce0689c4f5f.jpg] <https://gogetdigital.co.uk/>       [cid:offerhive_2785ed63-a2ca-4984-bcac-6cf90c6ee920.jpg] <https://www.offerhive.co.uk/>         [cid:property_jungle_acb7dc7d-ce18-4463-826e-bf4174c23b62.jpg] <https://www.thepropertyjungle.com/>     [cid:starberry_008e761b-b143-49ed-af01-1b029851e13e.jpg] <https://starberry.tv/>        [cid:leadpro_e974befc-a33f-499f-b7be-3202e926b7a9.jpg] <https://www.lead.pro/>

(c) 2022 eProp Services Ltd: A company registered in England and Wales with registered number 09210707 and registered office 121 Park Lane, Mayfair, London W1K 7AG. All rights reserved. This email is intended for the named recipient only. It may contain privileged and confidential information. If you are not the intended recipient, please notify the sender immediately and destroy this email. You must not copy, distribute or take action in reliance upon it. Whilst all efforts are made to safe-guard emails, eProp Services Ltd cannot guarantee that attachments are virus free or compatible with your systems and does not accept liability in respect of viruses or computer problems experienced. eProp Services Ltd reserves the right to monitor all email communications through its internal and external networks. Any offer or acceptance contained within or implied by this email is made subject to contract. Additionally, where this email message is sent in connection with a contentious issue, the contents are without prejudice.

From: Ash ***@***.***>
Sent: 02 August 2022 10:16
To: reapit/foundations ***@***.***>
Cc: Toby Dunn ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [reapit/foundations] First image returned from old API does not match Foundations image order, which is correct? (Issue #7394)


Hi @TobyDunnEPS<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FTobyDunnEPS&data=05%7C01%7Ctoby.dunn%40epropservices.com%7C7b79a6aa2cea45d3eeff08da746796f2%7Cc624288244904c71b218fad48ef37b99%7C0%7C0%7C637950285533733835%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=WqhdNkW1pIcWe6ygog%2F0DJgC7OULKBzjWLJXpQyOicA%3D&reserved=0>
Please note that platform API - the PropertyImages endpoint has an order option;
[https://user-images.githubusercontent.com/61687775/182339015-2740590a-e606-4e2c-a3c7-02c09e63eb4b.png]<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F61687775%2F182339015-2740590a-e606-4e2c-a3c7-02c09e63eb4b.png&data=05%7C01%7Ctoby.dunn%40epropservices.com%7C7b79a6aa2cea45d3eeff08da746796f2%7Cc624288244904c71b218fad48ef37b99%7C0%7C0%7C637950285533733835%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ULq7wtAu1sCWZXdV%2FGWsDfRCnjLFVIGV5l02b492%2B0w%3D&reserved=0>

We are unable to advise regarding the SOAP API

-

**Comment by AshDeeming** [comment]
Hi @TobyDunnEPS 
Please see the below re old API:

It will be ordered in the same way as it is stored in AgencyCloud;

e.g if property ref is abc123 with 3 images , it will be stored in this order

abc123_01.jpg, abc123_02.jpg, ,abc123_03.jpg,
