### ISSUE TITLE
identityChecks API  is not working in Sandbox env

### ISSUE THREAD

**Issue by ViswanathanShan** [reapit/foundations#7397]
Trying to invoke identityChecks Api since last week. It always gives an error in postman as well as reapit swagger env.

here is the request details:

```
curl -X 'GET' \
  'https://platform.reapit.cloud/identityChecks/' \
  -H 'accept: application/json' \
  -H 'api-version: xxxxxxx' \
  -H 'Authorization: Bearer xxxxxxx'
```

Expected -> It should return list of identityDetails
Actual ->```
 {

    "statusCode": 500,

    "dateTime": "2022-08-01T04:54:52.7175103Z",

    "description": "An unexpected error has been encountered when fulfilling this request. This incident has been logged and will be investigated. Please try again."

}
```
Here is the screenshot:

It's not working in any API client tool like postman, soapUI, insomnia etc..
![notworking](https://user-images.githubusercontent.com/41724450/182300538-a1ccba25-75af-4b9f-ae43-60e360a49be9.png)


But same request working only on web.postman.co (online version of postman).

![working](https://user-images.githubusercontent.com/41724450/182300583-dd0ce818-e1ab-4a97-a3ed-d7cf5cb89c60.png)

**Comment by ViswanathanShan** [comment]
It's just RestApi call to identityChecks

And `This is a sandbox environment, with anonymised test data and isolated from production`

**Comment by plittlewood-rpt** [comment]
@ViswanathanShan thanks for raising this ticket I actually noticed this in our logs just yesterday. The issue should now be resolved, please let me know if that's not the case. Many thanks

**Comment by ViswanathanShan** [comment]
Now I can able to fetch identityChecks. Thank you @plittlewood-rpt
