### ISSUE TITLE
`longDescription` field always an empty string even though corresponding data entered in AgencyCloud

### ISSUE THREAD

**Issue by adam-hf** [reapit/foundations#7401]
I am having an issue with the `longDescription` field always containing a blank string when requesting property data from the Foundations REST API even though the agent has confirmed they have text entered in the 'Long Desc' box in the Marketing Details > Extra Descriptions section of AgencyCloud. Is there some extra configuration that needs to be done on the AgencyCloud side for the `longDescription` data to be present in the property data received from the Foundations REST API?

**Research**
- 786 out of 790 (99.4%) customers use pLongDesc as the field for Long Description
- Customer concerned with this request uses pLongAd
- Expose this field via semi structured mechanism and provide usage instructions to developer

**Comment by AshDeeming** [comment]
Hi @adam-hf 
As the description is not one of the standard fields, this would require a Semi-structured 'extras' field request. 

Please use the below ticket structure & i'll update the ticket for the relevant team. 



In order for us to grant access to Semi-structured 'extras' field data, please provide the following information in this request:

- The name of the customer you represent
- The name of every field you need surfaced (if known)
- A screenshot of of the field(s) you require in the agency cloud user interface
- A short use case as to why you require this data

**Comment by adam-hf** [comment]
Hi @AshDeeming

Thank you for your prompt response.

- The name of the customer is Greenslade Taylor Hunt (Reapit customer ID: GTH)
- The name of the field we need surfaced in the Foundations REST API is: `longDescription`
- A screenshot of the field in the AgencyCloud user interface is attached.
- We require the data as this is where the client stores the full description of the property, which we need to fetch from the Foundations REST API to display on the individual property listing page of the customer's website.

![long_description](https://user-images.githubusercontent.com/110461568/182408470-693beebe-442b-43ac-a34a-1ba45e84bb57.png)

**Comment by plittlewood-rpt** [comment]
This is happening because this agent uses a non-standard custom database field to store the long description that the API is not aware of. We are currently reviewing the best approach to resolving this

**Comment by HollyJoyPhillips** [comment]
Hi @adam-hf You should now be able to access the long description by including the 'extrasfield' on your queries. For example:

https://platform.reapit.cloud/properties/OXF220020?extrasfield=pLongAd
