### ISSUE TITLE
Property Brochures Broken

### ISSUE THREAD

**Issue by Katflap74** [reapit/foundations#7411]
We have integrated the API feed on the following dev link (sale properties only):-

https://lands.ina4devel.co.uk/

Property Address
Burnholme Avenue, York, North Yorkshire has a brochure in the property details, when you click on the brochure form the dev site the folliwing error occurs

Failed to Load PDF Document - see attached screenshot

When you look in the Reapit Portal the document states that it is blank and is also broken there.

Can you help pleas
![brochure-error](https://user-images.githubusercontent.com/84779724/182393214-9bc41f88-5480-44ec-8d71-67662452459d.jpg)
e

**Comment by AshDeeming** [comment]
Hi @Katflap74 
Please can you advise the property reference(s) for review along with confirm the database being used?

**Comment by Katflap74** [comment]
Hi Ash

How do we retrieve this file (the PDF) as both the RPS software and API return an empty file





[http://www.ina4.com/images/email-signature/katy.jpg]   [http://www.ina4.com/images/logo.png]
Catherine Taylor
Project Manager

Wigan  t. 01942 366 420  /  Leeds t. 0113 322 1555
w. ina4.com

We're Social

[http://www.ina4.com/images/email-signature/icon-facebook.png]<https://www.facebook.com/ina4digital/>    [http://www.ina4.com/images/email-signature/icon-twitter.png] <https://twitter.com/ina4digital>     [http://www.ina4.com/images/email-signature/icon-instagram.png] <https://www.instagram.com/ina4digital/>     [http://www.ina4.com/images/email-signature/icon-linkedin.png] <https://www.linkedin.com/company/ina4-com/>

________________________________

**Comment by HollyJoyPhillips** [comment]
Hi @Katflap74, please can you confirm the company code (client ID of the agent) and the property reference? Was the brochure uploaded via AgencyCloud?

**Comment by Katflap74** [comment]
Hi Holly

It is either LOC or LOC-GLAS

I have no idea how this was added we are the web developers completing the integration, all we know is that the PDF brochure appears broken in the portal and on the front end of our dev site.

Thanks

Cath

[http://www.ina4.com/images/email-signature/katy.jpg]   [http://www.ina4.com/images/logo.png]
Catherine Taylor
Project Manager

Wigan  t. 01942 366 420  /  Leeds t. 0113 322 1555
w. ina4.com

We're Social

[http://www.ina4.com/images/email-signature/icon-facebook.png]<https://www.facebook.com/ina4digital/>    [http://www.ina4.com/images/email-signature/icon-twitter.png] <https://twitter.com/ina4digital>     [http://www.ina4.com/images/email-signature/icon-instagram.png] <https://www.instagram.com/ina4digital/>     [http://www.ina4.com/images/email-signature/icon-linkedin.png] <https://www.linkedin.com/company/ina4-com/>

________________________________

**Comment by Katflap74** [comment]
Hi Holly,

LOC is the client code and I believe LOC-GLAS is the code linked to Linley & Simpson within the Lomond build

Carl sent me a link to the test website and one of the properties we can use as an example is LSY220048, there is a brochure added to the property.

Hope this helps, thanks for picking this up.

***@***.***

**Comment by HollyJoyPhillips** [comment]
@plittlewood-rpt I've verified that the office that brochure belongs (LSY) to is associated to that office group and it's available to view in AC, please can you check the backend to see if the brochure is accessible?

**Comment by plittlewood-rpt** [comment]
Hi @Katflap74 - Can you confirm how you are accessing the brochures? It looks like they are stored on your own system after being pulled from our Platform. I've accessed `GET /platform.reapit.cloud/properties/LSY220048` which is the example you gave most recently, and can open the brochure just fine. If you can let us know how you are downloading and storing the documents I may be able to assist further as it looks like the version you've got hosted on your own system is corrupt/missing

**Comment by Katflap74** [comment]
Hi Cath,

I can see an update posted on the ticket, this morning. - can you review and advise please, thanks

Hi @Katflap74<https://github.com/Katflap74> - Can you confirm how you are accessing the brochures? It looks like they are stored on your own system after being pulled from our Platform. I've accessed GET /platform.reapit.cloud/properties/LSY220048 which is the example you gave most recently, and can open the brochure just fine. If you can let us know how you are downloading and storing the documents I may be able to assist further as it looks like the version you've got hosted on your own system is corrupt/missing

From: Khuram Mahmud
Sent: 04 August 2022 13:19
To: Cath Taylor ***@***.***>; reapit/foundations ***@***.***>; Carl Willock ***@***.***>; reapit/foundations ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [reapit/foundations] Property Brochures Broken (Issue #7411)

Hi Holly,

LOC is the client code and I believe LOC-GLAS is the code linked to Linley & Simpson within the Lomond build

Carl sent me a link to the test website and one of the properties we can use as an example is LSY220048, there is a brochure added to the property.

Hope this helps, thanks for picking this up.

***@***.***

**Comment by Katflap74** [comment]
HI All

We don't know how to retrieve the document - we have been unsuccessful in the API and the RPS software - both show documents exist and neither allow access to those documents

This is what we see when we use 'Try it Out' in swagger:

[cid:a67296cc-55fe-41df-b4ef-65248844704f]

Please let us know how to retrieve the contents of a document via its ID using the API - worked example would be great - any code will do

[http://www.ina4.com/images/email-signature/katy.jpg]   [http://www.ina4.com/images/logo.png]
Catherine Taylor
Project Manager

Wigan  t. 01942 366 420  /  Leeds t. 0113 322 1555
w. ina4.com

We're Social

[http://www.ina4.com/images/email-signature/icon-facebook.png]<https://www.facebook.com/ina4digital/>    [http://www.ina4.com/images/email-signature/icon-twitter.png] <https://twitter.com/ina4digital>     [http://www.ina4.com/images/email-signature/icon-instagram.png] <https://www.instagram.com/ina4digital/>     [http://www.ina4.com/images/email-signature/icon-linkedin.png] <https://www.linkedin.com/company/ina4-com/>

________________________________

**Comment by plittlewood-rpt** [comment]
Hi @Katflap74 

You can get the brochures via two methods:

Either used `GET /documents/{id}/download`

or you can use the `selling.publicBrochureUrl` and `letting.publicBrochureUrl` links in the response from `GET /properties` and `GET /properties/{id}`

The latter may be more appropriate as it means you can access the brochures without having to have read access to all a customers' documents.

Hope this helps

**Comment by Katflap74** [comment]
Hi

Thanks for that will look at this and let you know.

Regards

Cath

[http://www.ina4.com/images/email-signature/katy.jpg]   [http://www.ina4.com/images/logo.png]
Catherine Taylor
Project Manager

Wigan  t. 01942 366 420  /  Leeds t. 0113 322 1555
w. ina4.com

We're Social

[http://www.ina4.com/images/email-signature/icon-facebook.png]<https://www.facebook.com/ina4digital/>    [http://www.ina4.com/images/email-signature/icon-twitter.png] <https://twitter.com/ina4digital>     [http://www.ina4.com/images/email-signature/icon-instagram.png] <https://www.instagram.com/ina4digital/>     [http://www.ina4.com/images/email-signature/icon-linkedin.png] <https://www.linkedin.com/company/ina4-com/>

________________________________

**Comment by Katflap74** [comment]
Hi

Any update on this at all?

Thanks

Cath

[http://www.ina4.com/images/email-signature/katy.jpg]   [http://www.ina4.com/images/logo.png]
Catherine Taylor
Project Manager

Wigan  t. 01942 366 420  /  Leeds t. 0113 322 1555
w. ina4.com

We're Social

[http://www.ina4.com/images/email-signature/icon-facebook.png]<https://www.facebook.com/ina4digital/>    [http://www.ina4.com/images/email-signature/icon-twitter.png] <https://twitter.com/ina4digital>     [http://www.ina4.com/images/email-signature/icon-instagram.png] <https://www.instagram.com/ina4digital/>     [http://www.ina4.com/images/email-signature/icon-linkedin.png] <https://www.linkedin.com/company/ina4-com/>

________________________________

**Comment by plittlewood-rpt** [comment]
HI @Katflap74 - the last update from yourself was that you would look into what was suggested. The links themselves are working fine. If there is still an issue please can you open a new item as this is now closed

**Comment by Katflap74** [comment]
Hi Kam

I am currently waiting for a developer to look at this as soon as they let me know I'll come back to you.

Cath

[http://www.ina4.com/images/email-signature/katy.jpg]   [http://www.ina4.com/images/logo.png]
Catherine Taylor
Project Manager

Wigan  t. 01942 366 420  /  Leeds t. 0113 322 1555
w. ina4.com

We're Social

[http://www.ina4.com/images/email-signature/icon-facebook.png]<https://www.facebook.com/ina4digital/>    [http://www.ina4.com/images/email-signature/icon-twitter.png] <https://twitter.com/ina4digital>     [http://www.ina4.com/images/email-signature/icon-instagram.png] <https://www.instagram.com/ina4digital/>     [http://www.ina4.com/images/email-signature/icon-linkedin.png] <https://www.linkedin.com/company/ina4-com/>

________________________________
From: Khuram Mahmud ***@***.***>
Sent: 05 August 2022 15:14
To: Cath Taylor ***@***.***>; reapit/foundations ***@***.***>; Carl Willock ***@***.***>; reapit/foundations ***@***.***>
Cc: Mention ***@***.***>; Carrie d'Arcy ***@***.***>; Brad Ogden ***@***.***>; Elizabeth Hamlin ***@***.***>
Subject: RE: [reapit/foundations] Property Brochures Broken (Issue #7411)


Hi Cath,



I can see an update posted on the ticket, this morning. – can you review and advise please, thanks



Hi @Katflap74<https://github.com/Katflap74> - Can you confirm how you are accessing the brochures? It looks like they are stored on your own system after being pulled from our Platform. I've accessed GET /platform.reapit.cloud/properties/LSY220048 which is the example you gave most recently, and can open the brochure just fine. If you can let us know how you are downloading and storing the documents I may be able to assist further as it looks like the version you've got hosted on your own system is corrupt/missing



From: Khuram Mahmud
Sent: 04 August 2022 13:19
To: Cath Taylor ***@***.***>; reapit/foundations ***@***.***>; Carl Willock ***@***.***>; reapit/foundations ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [reapit/foundations] Property Brochures Broken (Issue #7411)



Hi Holly,



LOC is the client code and I believe LOC-GLAS is the code linked to Linley & Simpson within the Lomond build



Carl sent me a link to the test website and one of the properties we can use as an example is LSY220048, there is a brochure added to the property.



Hope this helps, thanks for picking this up.



***@***.***
