### ISSUE TITLE
API functionality to identify repeat appointments

### ISSUE THREAD

**Issue by david-silverink** [reapit/foundations#7430]
We are looking to identify repeat appointments within the API, emulating the checkbox within Agency Cloud. Is this feature on the development roadmap? Thanks

**Comment by HollyJoyPhillips** [comment]
Hi @david-silverink There is a flag on the appointments endpoint to determine if an appointment is recurring: 

![image](https://user-images.githubusercontent.com/52408607/183411018-091d8eee-60d2-48f8-b8b4-bf3e4639d3fc.png)

**Comment by david-silverink** [comment]
Hi @HollyJoyPhillips - thanks for coming back, I'm not sure this is the same as the 'repeat' tick box in Agency Cloud. See attachment. Can you confirm? Thanks again.
<img width="498" alt="image" src="https://user-images.githubusercontent.com/80890331/183429861-82a9104d-8c48-4174-8292-d1c1d4dc085a.png">

**Comment by HollyJoyPhillips** [comment]
Hi @david-silverink My apologies, I misread the ticket. That field is stored in extras (semi-structured data). Is is for a specific customer?

**Comment by david-silverink** [comment]
Yes, it's for SFG, thanks.

**Comment by HollyJoyPhillips** [comment]
@david-silverink Thank you for confirming, we have ticket, currently in progress that needs to be completed before this can be available https://github.com/reapit/foundations/issues/7483. I'll update you once it has.

**Comment by HollyJoyPhillips** [comment]
Hi @david-silverink I can confirm that field is now available when making an extras request. Thanks.

**Comment by david-silverink** [comment]
Thanks @HollyJoyPhillips can you let me know the syntax to use please?

**Comment by HollyJoyPhillips** [comment]
@david-silverink You'll need to add the 'extrafield' on your queries, for example:

https://platform.reapit.cloud/appointments/OXF220020?extrasfield=yrepeat
