### ISSUE TITLE
Feature request - Update marketing consent

### ISSUE THREAD

**Issue by BYMIntegrations** [reapit/foundations#7433]
Our customer knightedmonds.briefyourmarket.com are having issues with a customer contact no updating in our system after updating it in the Reapit system.

Id like if this could update in our BYM system after being changed in Reapit to avoid GDPR issues

Alternative being the customer does both, but that is not as efficient 

![image](https://user-images.githubusercontent.com/102583061/182821577-3723840c-af35-415b-bc92-40fc5807a814.png)

**Comment by plittlewood-rpt** [comment]
Hi @BYMIntegrations I have checked AgencyCloud and the Platform is returning `"marketingConsent": "deny"` for both these contacts as I'd expect so I don't see an issue with the API here. Can you elaborate on what the problem is?

**Comment by BYMIntegrations** [comment]
knightedmonds.briefyourmarket.com has raised an issue where they changed the marketing consent in Reapit but it didn't change in BYM, leading to emails still being sent out to this customer.

**Comment by plittlewood-rpt** [comment]
Hi @BYMIntegrations that would point to a problem with your app not processing the updated data. If the API is returning the correct data, which it is in this case, I'm not sure how else we can assist unless I'm missing something about the problem. Please let me know if I can be help further

**Comment by BYMIntegrations** [comment]
``Hi Guys

Thank you for looking into this.

when calling your api I receive the following json. I have XXXX all of the personal information.
```
{
    "id": "MDS21006804",
    "created": "2021-12-28T15:20:22Z",
    "modified": "2022-04-03T12:26:28Z",
    "title": "",
    "forename": "xxxx",
    "surname": "xxxxx",
    "dateOfBirth": null,
    "active": true,
    "marketingConsent": "notAsked",
    "identityCheck": "unchecked",
    "source": {
        "id": "RM",
        "type": "source"
    },
    "homePhone": null,
    "workPhone": null,
    "mobilePhone": "07941729914",
    "email": "xxxxxx",
    "archivedOn": null,
    "fromArchive": false,
    "primaryAddress": {
        "type": "primary",
        "buildingName": "",
        "buildingNumber": "4",
        "line1": "xxxx",
        "line2": "",
        "line3": "",
        "line4": "",
        "postcode": "xxxxxx",
        "countryId": ""
    },
    "secondaryAddress": null,
    "workAddress": null,
    "officeIds": [
        "MDS"
    ],
    "negotiatorIds": [
        "SR1"
    ],
    "categoryIds": [],
    "communicationPreferenceLetter": false,
    "communicationPreferenceEmail": false,
    "communicationPreferencePhone": false,
    "communicationPreferenceSMS": false,
    "additionalContactDetails": [],
    "_eTag": "\"5AAD0E3F070ABDE66CBF0E46DA0D9BA3\"",
    "_links": {
        "self": {
            "href": "/contacts/MDS21006804"
        },
        "documents": {
            "href": "/documents/?associatedType=contact&associatedId=MDS21006804"
        },
        "identityChecks": {
            "href": "/identityChecks/?contactId=MDS21006804"
        },
        "offices": {
            "href": "/offices/?id=MDS"
        },
        "negotiators": {
            "href": "/negotiators/?id=SR1"
        },
        "relationships": {
            "href": "/contacts/MDS21006804/relationships"
        },
        "subscriptions": {
            "href": "/contacts/MDS21006804/subscriptions"
        }
    },
    "_embedded": null,
    "metadata": {}
}
```

![image](https://user-images.githubusercontent.com/102583061/183388958-6fc6aed3-f73b-4463-ab7f-e103515fb134.png)


Would you be able to show me what you get when you call the api for them ?

The reapit customer Id is  KEL

**Comment by plittlewood-rpt** [comment]
Ah, that's a different Leslie Lloyd. The one from the screenshot is MDS22000493 which is returning the correct data so it looks like you are looking at a different record to the customer.
