### ISSUE TITLE
No recent records for "Enquiries" for specific customer.

### ISSUE THREAD

**Issue by stebrough** [reapit/foundations#7441]
**Describe the bug**
When calling the Enquiries endpoint, we aren't seeing enquires newer than 20/07/2022.

**To Reproduce**
Perform GET request to /Enquiries

**Expected behaviour**
All enquiries received returned.

**Additional context**
Only for one customer, details emailed to sinfo.

**Comment by HollyJoyPhillips** [comment]
Hi @stebrough Looking at the logs it seems there is an issue accessing their mailbox which feeds into the enquires endpoint. It's not something we can resolve but I've flagged it with the support team and will update this ticket where possible.

**Comment by HollyJoyPhillips** [comment]
@stebrough The customer has already raised a ticket with the support team and it's being reviewed/actioned (RSD-192634)

**Comment by stebrough** [comment]
@HollyJoyPhillips thanks for the response, I will await the outcome of the other ticket.

**Comment by HollyJoyPhillips** [comment]
Closing this ticket as the issue with RSD-192634 has been resolved
