### ISSUE TITLE
Spike: CDK localstack for local dev envs

### ISSUE THREAD

**Issue by willmcvay** [reapit/foundations#7457]
**Background context or User story:**

_Investigate the possibility of running a localstack scaffolded with CDK for local dev work, especially on our more complex services. Would work nicely alongside #7350 and #7351 as we can use the same stack for dev and deployed_

**Comment by plittlewood-rpt** [comment]
Crossover with #3953 here as this is something we've wanted to explore too so would be interested on any findings
