### ISSUE TITLE
Grid Improvements

### ISSUE THREAD

**Issue by roscoe2001** [reapit/foundations#7462]
We have used the Framework Grid within the Apps we've built using the Foundations Framework. This has given as a great starting point but they're limited in the there usability. 

We'd like to be able to : -
- Sort using column headings.
- Search (not only within the page displayed but within all the pages)
- Be able to jump to End/Start/Certain page number (rather than just being able to page forward/back 1 page at a time)
- Allow the user to select page size

Ideally we don't really want to move away from the grids provided by the framework so wanted to ask if this is something you are looking at enhancing but if not we'll need to look at alternatives.

On a side note I'm doing quite a lot of setup in the App Marketplace so feel the pain of the users trying to use them (the grid improvements would have the added benefit of improving that App)!

**Comment by willmcvay** [comment]
Hi @roscoe2001 

Looking at your request by `Framework Grid` I am assuming you are referring to the `Table` component i.e. https://elements.reapit.cloud/?path=/docs/table--react-shorthand-usage Please let me know if I have misunderstood this.

Assuming so, I think there is some confusion about what the table is - it doesn't actually fetch the data, rather it presents the data to the user. We are agnostic about what API you might be using, how you manage state in your application or how you fetch data.

We can definitely make a couple of enhancements as per below though;

> * Sort using column headings.

You can do this today by adding a click event to the table header cells eg the very basic example here adapting this https://elements.reapit.cloud/?path=/docs/table--basic-usage

```tsx
...
const mySortFunction = () => {
  // Sort my fetchedData here
}

...

return (
  <Table>
      <TableHeadersRow>
        <TableHeader onClick={mySortFunction}>First Header</TableHeader>
      </TableHeadersRow>
     {fetchedData.map(item => (
        <TableRow>
          <TableCell>{item.value}</TableCell>
        </TableRow>
      )}
   </Table>
)
```
It would be nice to do this using the React shorthand, so I have added a ticket so you can add a click event to column headers and an icon to indicate sort direction. https://github.com/reapit/foundations/issues/7463 

> * Search (not only within the page displayed but within all the pages)

Search is a function of an API request, the result of which you can render in the table, not a property of the table itself. We just use an `InputGroup` with an on change method that fetches your data eg below

```tsx

   const fetchData = (e) => {
     fetch('https://some-api?query=' + e.target.value).then(data => // render me in a table)
   }

   <InputGroup>
      <Input id="myId" type="search" onChange={fetchData} />
      <Icon icon="searchSystem" />
      <Label htmlFor="myId">Search</Label>
    </InputGroup>
   <Table>
   .......

> * Be able to jump to End/Start/Certain page number (rather than just being able to page forward/back 1 page at a time)

Yes, this would be useful, have logged this ticket to look at it https://github.com/reapit/foundations/issues/7464

> * Allow the user to select page size

I would use exactly the same pattern as the search above, just ask a user to input the desired page and let the onChange event trigger a change to the data set.

**Comment by roscoe2001** [comment]
It does help, thanks for the quick response. We'll have a look at those (sorry if the original request was a little vague - I'm 1 step away from the actual coding side these days!)

**Comment by willmcvay** [comment]
Sure no worries @roscoe2001 will leave this open for a few days, if I don't hear back by the end of the week will assume you got sorted.

**Comment by roscoe2001** [comment]
Hi Will, after a few more conversations I'm not sure we can do some of what we want i.e. I want to be able to sort on the whole result set (lets say we are on page 1 of 5 I want the sort to work across the 5 pages) NB An actual filter would do the job as well so we could use the search method instead but the problem is we can't filter on Works Order Priority - https://github.com/reapit/foundations/issues/5952. So in effect the user has no way(?) of seeing their top priority WorksOrders (unless I'm missing something).

**Comment by willmcvay** [comment]
@roscoe2001 So I see your point but that is an issue with the Table component in Elements, rather it's an issue with the API not supporting sorting for works orders. If you can confirm, I can get the team to update that separate issue accordingly.

**Comment by roscoe2001** [comment]
@willmcvay - yes that's right but because the works order ticket is long term (and was created in Jan) I'm guessing it's a big job so was trying to workaround the issue (all be it with a less friendly solution) by allowing the user to sort the full results set and then at least the high priority jobs would be all together .

**Comment by willmcvay** [comment]
@roscoe2001 Understood. So the only workaround you can do in the front end is to request all the data you need and sort and paginate in the front end. You can request up to 100 records per request but I would recommend keeping it as small as possible by use of additional filters like "status" and "createdFrom". This will reduce the heavy lifting you have to do in the front end.

Just to be clear though, this fetching and data manipulation is a separate concern to Elements which is just a UI library.

**Comment by willmcvay** [comment]
@roscoe2001 Can you let me know if there are any further queries on this ticket, otherwise will close off on Monday. Thanks

**Comment by roscoe2001** [comment]
Feel free to close, thanks.
