### ISSUE TITLE
Is there a limit in the Subscription customers field in webhooks?

### ISSUE THREAD

**Issue by lcantrell79** [reapit/foundations#7467]
Is there a limit as to how many customers can be selected in this field?
I ask because there is a limit of 3 for the private customers in the main app so just wondering if it is the same in webhooks.

**Summary**

**Detail and or supporting links and screenshots**
![image](https://user-images.githubusercontent.com/93535875/183366181-cbab235c-6db7-42c1-9010-34a1ade4241a.png)

**Comment by HollyJoyPhillips** [comment]
Hi @lcantrell79, no, there is no limit for the amount of customers you can select. Thanks.
