### ISSUE TITLE
Appointment follow-up feedback

### ISSUE THREAD

**Issue by NBareham** [reapit/foundations#7471]
Please take a look at our FAQ's before submitting an issue, as your question may already be covered in the documentation https://foundations-documentation.reapit.cloud/faqs

**Summary**
We want to be able to display the viewing feedback, that's shown as a dropdown on the appointment, in our online account area.

**Detail and or supporting links and screenshots**
See the attached screenshot of the drop down we'd like access to via Foundations. Thank you!
![Viewing follow-up GITHUB](https://user-images.githubusercontent.com/101395511/183393173-e6a2c856-8477-4b63-867e-d2dca2e58178.png)

**Comment by plittlewood-rpt** [comment]
Hi @NBareham this is already exposed in `AppointmentModel.followUp.responseId` - as this list if configurable per customers, the response from `GET /appointments` and `GET /appointments/{id}` just returns the id of the item selected in the list. This can be converted back to text using `GET /configuration/followUpResponses` and `GET /configuration/followUpResponses/{id}`. 

Please let me know if this doesn't answer your question.
