### ISSUE TITLE
Assigning Areas to Properties

### ISSUE THREAD

**Issue by jashiels99** [reapit/foundations#7474]
**Summary**
We are pulling in a list of areas from the live app via the /areas REST API endpoint.

However, no properties are being assigned to an area as the areaId field is null.

We use areas to run a property search on the website.

However, we have been told that in the Reapit CRM, there is no way to assign an area to a property.

Please could you advise?

**Comment by AshDeeming** [comment]
Hi @jashiels99 
The area can be set per property in AgencyCloud, directly below the address;
![image](https://user-images.githubusercontent.com/61687775/183617631-97792d4c-e6f3-42da-86ed-8ae638759700.png)
