### ISSUE TITLE
CRM data not matching with API response

### ISSUE THREAD

**Issue by jashiels99** [reapit/foundations#7475]
I am trying to create an import script to import properties from the Reapit API to our system.

I have a couple of queries about the response data. I have pasted the API response for one of the properties we are trying to import: https://pastebin.com/ZWw450NG

Here is a screenshot of it in the CRM:
***REMOVED*** 
Firstly, where am I able to find the bullet-pointed 'Attributes' data in the API response? I thought it might be in 'specialFeatures' but this is null.

Also, in the CRM it says that the properties status is equal to 'Sold STC - Available'. However, in the API response it says the status is 'underOffer'. We need to know if the property is Sold STC but I can't see any indication of this in the response?

Please could you advise?

**Comment by AshDeeming** [comment]
Hi @jashiels99 
Please see the API section of the developer portal, where each endpoint & example standard fields can be seen;

Attributes relate to departments therefore if the Client has custom fields here, these will need to be requested via semi structured data request ticket. 

With regards to statuses, as per above - these can be found via the below link under the relevant endpoint; 
https://developers.reapit.cloud/swagger
![image](https://user-images.githubusercontent.com/61687775/183617060-ada487c9-da7a-451c-849b-fe22ba93974a.png)

**Comment by ElliottRowland** [comment]
@AshDeeming We have a similar issue at Webdadi with our Property Uploader for Webdadi Website App using the endpoint is /property and /propertyimages

If a Reapit user is marking a property as Sold STC available in their software and the API is returning the property with the status as underOffer how do you differentiate between properties marked as Under Offer or Sold STC in Reapit's software if the API status itself doesn't differentiate between the two and gives the same label?
