### ISSUE TITLE
Missing Lettings Financials

### ISSUE THREAD

**Issue by Karltatlerdata** [reapit/foundations#7484]
While connecting to Lettings properties to determine financials I only have access to rental values instead of being able to see commission % or fixed values. I can access this information for sales properties but not lettings!

Ideally I need to access all financial data for a property to determine potential income and comparisons between Valuation financials and what a property let agrees at. See attached screenshot!
![Screenshot 2022-08-09 095459](https://user-images.githubusercontent.com/105005487/183608058-8de1106b-13ec-4daa-8771-520864bc5b60.jpg)

**Specification**
- Project: Analytics Schema
- Add new fields `prps.lettings_agreed_fee_percentage` and `prps.lettings_agreed_fee_amount` to the properties view model in the same way we do for sales fees that expose the respective values from the AC schema

**Comment by plittlewood-rpt** [comment]
Hi @Karltatlerdata - are you able to be a bit more specific about which fields you need access to? Introducing all these fields will be a big job so I'd want to break this down if possible. Thanks

**Comment by Karltatlerdata** [comment]
Hi Pete, if you're able to see the original image I opened the ticket with then the information I cant access is the:
- Letting fee
- Management Fee %
- Management fee £

Ideally id love to be able to access the entire lettings Commission box, however as mentioned I know that's a big job!

Many thanks

**Comment by plittlewood-rpt** [comment]
Thanks - we actually added management fee information in #6375 recently. You just need to refresh your data share through the management app to get this data. We will look at adding the letting fee soon
