### ISSUE TITLE
Missing Agency labels

### ISSUE THREAD

**Issue by Karltatlerdata** [reapit/foundations#7485]
Our custom Sales Agency labels seem to be missing in the schema, I can clearly see on Reapit that the agency is set to 'Super Scrape' but my schema bundles quite a few into the 'Not Set' Category.

Can this be changed to allow me to filter through our own custom selections?
![Screenshot 2022-08-09 095853](https://user-images.githubusercontent.com/105005487/183608820-5f41f8d4-7ee4-4642-b51c-4df102e56455.jpg)

**Specification**
- Project: Analytics Schema
- Update property model to account for customisations of the sales agency list (switch from using `lookup_static_name` to `lookup_dynamic_name` - use other implementations of this macro in the project for refrence.

**Comment by plittlewood-rpt** [comment]
Hi @Karltatlerdata - you should be able to used the `agencyId` property to deal with this (added in #5448) . When the Platform was originally developed the ability to customise the agency list was unfortunately overlooked. It's likely that the `agency` field will get deprecated eventually, but they'll live side by side for the time being.

**Comment by plittlewood-rpt** [comment]
Sorry I've just realised you are talking about the analytics schema - we'll get this looked at in next refinement

**Comment by Karltatlerdata** [comment]
Hi Pete, No worries! 
When roughly will this occur?

**Comment by plittlewood-rpt** [comment]
Refinement sessions are on a Thursday each week so we'll be having our next one in two days time

**Comment by Karltatlerdata** [comment]
Amazing thank you, will this also link into my other issue (Issue #7485) of the lettings financials fields seeming to be missing?

Many thanks

Edward Francis
Data Analyst
DDI: 0151 342 0458

[signature_1805979853]<https://www.karltatler.com/>

[signature_1271568633]<https://www.karltatler.com/pages/sell?request-valuation>

***@***.***,-3.1687615,12z/data=!4m8!4m7!1m0!1m5!1m1!1s0x487ad7f52a06699b:0x4e232142b9104029!2m2!1d-3.098722!2d53.329358>

[signature_549509221]<https://www.facebook.com/karltatler>

[signature_1915107555]<https://www.instagram.com/karl_tatler/>

[signature_21968547]<https://twitter.com/karl_tatler>

[signature_477271765]<https://www.linkedin.com/company/karl-tatler-estate-agents-&-lettings>

***@***.***<https://www.youtube.com/channel/UCZsPDw8R8MwnbklZXcEBugA>

**Comment by plittlewood-rpt** [comment]
They will be dealt with as independent tickets but will be refined tomorrow.
