### ISSUE TITLE
Changing Redirect URL

### ISSUE THREAD

**Issue by jphgardner** [reapit/foundations#7486]
Hi, 

We currently have an app listing up on your marketplace, but it has the wrong redirect & sign-out URLs, this is causing a reapit connect redirect_missmatch error.

I have tried various ways to change it to the right URLs but when I try, it reverts back to the wrong one.

Can I have some assistance with this, please?

**Comment by AshDeeming** [comment]
Hi @jphgardner 
Once change(s) have been made to a listed app, you should see the below option appear to create a revision on the left hand side:
![image](https://user-images.githubusercontent.com/61687775/183617944-f022854d-e676-4c65-b261-8d93824594c5.png)

Please confirm if this is not the case and provide any relevant screenshots please?

**Comment by AshDeeming** [comment]
Hi @jphgardner 
Please can you submit the changes (the URL may still show as the old/existing URL until the revision is approved) & we'll get this approved for you.
