### ISSUE TITLE
Properties endpoint returning permissions error

### ISSUE THREAD

**Issue by david-silverink** [reapit/foundations#7487]
We are having an issue with the properties endpoint. It keeps returning "access to one or more of the specified fields is not permitted. You must be granted access to this data beforehand", since about 11am GMT. Other endpoints OK. This is for SFG data.

**Comment by plittlewood-rpt** [comment]
This should be resolved in the next 15 minutes

**Comment by plittlewood-rpt** [comment]
@david-silverink Please can you confirm that this is resolved? It was related to a change that was made this morning that will have affected access to semi structured data for SFG only. The original configuration has now been restored

**Comment by david-silverink** [comment]
@plittlewood-rpt Yes, thanks all OK now, offline for about 3 hours.
