### ISSUE TITLE
Access To Featured Property Flag from API

### ISSUE THREAD

**Issue by nick-dilley** [reapit/foundations#7488]
Hi, I need access to the featured property flag for customer HUD.

They have it set up in Agency Cloud, I just need access to it from the API, I believe it may be available in the Extras field, however I can't see anything in the extras field from any properties in the feed

Is this something that needs to be enabled your end? Thanks

**Comment by HollyJoyPhillips** [comment]
Hi @nick-dilley You should now be able to access the featured flag by including the 'extrasfield' on your queries. For example: 

https://platform.reapit.cloud/properties/OXF220020?extrasfield=pFeatured
