### ISSUE TITLE
Restrict Manage / Browse sections

### ISSUE THREAD

**Issue by roscoe2001** [reapit/foundations#7491]
Is it possible to allow a user to see their installed Apps but not get into the Manage / Browse sections?

NB I know you can make Apps invisible but I want to hide the whole sections from the users.

Thanks

![1](https://user-images.githubusercontent.com/96238131/183668412-42f0155c-2ce4-400c-8093-fe3021bfd456.png)

**Comment by HollyJoyPhillips** [comment]
Hi @roscoe2001 The manage apps section is only visible to Reapit User Admins. You can control the user roles via the Users section in the Management app. Similar, although Reapit Users can browse the AppMarket, unless they are a Reapit User Admin or Marketplace Admin, they cannot install apps on view.

**Comment by roscoe2001** [comment]
I thought I'd tried that so I've just been back to check. I've used Ian Lazenby as the example on YOM. 

I've attached 5 screens shots - 3 showing he's not a Reapit User Admin (or in any of the the users groups) and 2 showing that he still has the manage/browse options (with options to install)

![MarketplaceAdmin](https://user-images.githubusercontent.com/96238131/183672808-46c2b85f-3ee0-40d0-bc9b-3d97955787f0.png)
![OA](https://user-images.githubusercontent.com/96238131/183672817-fe31dd12-9cf5-42de-aeec-31051aa7115d.png)
![RUA](https://user-images.githubusercontent.com/96238131/183672823-4496a69d-1de9-4717-b6c0-a5af9e3e68d3.png)
![Ian Screenshot1](https://user-images.githubusercontent.com/96238131/183672826-1940868b-9c35-4914-808b-cf5984cf4c8b.png)
![Ian Screenshot2](https://user-images.githubusercontent.com/96238131/183672832-dd23f083-7ef8-4914-a041-f84dca9e3e2a.png)
)

**Comment by HollyJoyPhillips** [comment]
@roscoe2001 also, we've now added the search functionality on the apps page and resolved the issue with the office group searching :)

**Comment by roscoe2001** [comment]
He is logging into YM as ian.lazenby@your-move.co.uk

**Comment by HollyJoyPhillips** [comment]
Did you change his account access at all recently?

**Comment by roscoe2001** [comment]
> @roscoe2001 also, we've now added the search functionality on the apps page and resolved the issue with the office group searching :)

Great - is that just requiring release? (not sure how the releases work for the Foundation stuff)

**Comment by HollyJoyPhillips** [comment]
It's there now. If you log out and back in again you should see it on the left hand nav 
![image](https://user-images.githubusercontent.com/52408607/183689354-a0da0d72-f254-4c05-ba5e-c94aac69c9bf.png)

**Comment by roscoe2001** [comment]
The search is nice - thanks

**Comment by roscoe2001** [comment]
> Did you change his account access at all recently?

I wouldn't like to 100% say! I probably did, I was changing the permission User Groups of a few of the guys in my team to try and work out what we could / couldn't change (using the 3 groups)

**Comment by HollyJoyPhillips** [comment]
It might just be worth asking him to log out of AC and back in again. Based on his permissions he shouldn't see 'Manage'. He will still 'Install' but if he tries a message will appear saying he doesn't have the permissions to do so.  Worth checking his roles here https://foundations-documentation.reapit.cloud/troubleshooting/installation

**Comment by roscoe2001** [comment]
Thanks - I'll get him to check now.

**Comment by roscoe2001** [comment]
It half works. He's still seeing the Manage option but when he goes to install it doesn't let him (permissions below)

![ianreapitpermissions](https://user-images.githubusercontent.com/96238131/183698430-b8deb056-2028-4390-8da2-0455e75ec968.png)

**Comment by HollyJoyPhillips** [comment]
Hi @roscoe2001 It looks like a bug. However, the same message would appear if a user attempted to uninstall the app. I have raised a ticket for the team to update the behaviour. You can follow here https://github.com/reapit/foundations/issues/7499

**Comment by roscoe2001** [comment]
Hi @HollyJoyPhillips thanks for raising a ticket.

I presume the answer to this is no (and I need to raise a request) but is there any way we can turn on screen related Apps (Property/Applicant etc) but not the main Apps section? 

This is so our 'normal' branch users would see any Property/Applicant (etc) level Apps within the relevant screen but they wouldn't be able to access the 'main' Apps section (on the main AC left hand menu)

**Comment by HollyJoyPhillips** [comment]
Hi @roscoe2001 I believe this had already been answered on another thread/issue but before closing the ticket, please can you confirm?

**Comment by roscoe2001** [comment]
I don't think this particular question was answered (unless I missed it)

**Comment by HollyJoyPhillips** [comment]
Hi @roscoe2001 Thanks for getting back to us. So the visibility toggle in the Marketplace Management app (on the app listing) will control the visibility but still allow for installation: https://managementapp-foundations.reapit.cloud/marketplace-visibility-and-installation-management#marketplace-visibility. Does that help?

**Comment by roscoe2001** [comment]
Sorry I think I've probably confused the issue with my wording - I've attached a screenshot which hopefully explains the question better
![image](https://user-images.githubusercontent.com/96238131/191224127-fd00a812-8634-4ac1-8e42-cf8c29a0c003.png)

**Comment by HollyJoyPhillips** [comment]
Hi @roscoe2001 No problem, that does help thank you. So unfortunately not, the AppMarket is either turned on or it is not. If we hide the 'AppMarket' from the left (it will be switched off) and accessing apps via a property etc will not work. As it's an AgencyCloud feature, you could raise a ticket with the service desk/AgencyCloud team to see if it's something they can do but it's not something we can control in the Platform team.

**Comment by roscoe2001** [comment]
No problem. I thought that would be the answer but just wanted to double check (this can be closed, thanks).
