### ISSUE TITLE
Need "hasGas" value to pull through

### ISSUE THREAD

**Issue by LouisaEvosite** [reapit/foundations#7492]
**Is your feature request related to a problem? Please describe.**
In webservice properties would pull through "HasGas" eg:

![image](https://user-images.githubusercontent.com/109209591/183675495-dc2106f2-b107-459b-b829-cc2526f3a7d0.png)

**Describe the solution you'd like**
We need this value adding to Foundations on the properties so we know whether a gas safety certificate is missing.

**Specification**
- Project: Reapit.Services.Properties
- Add new `hasGas` property to `PropertyLettingUtilitiesModel` that exposes the INVERSE of prp.NoGas
- Allow write back of this value so same property on respective write models
- Add tests

**Comment by AshDeeming** [comment]
Hi @LouisaEvosite 

Please see the /properties/{ID}/certificates endpoint, example details & model available on the API/swagger page;
https://developers.reapit.cloud/swagger

https://foundations-documentation.reapit.cloud/whats-new#certificates

**Comment by LouisaEvosite** [comment]
Hi @AshDeeming 

Thank you but we need to know if a property has gas or not.
If it does we will then fetch the GS certificate and either display it's expiry date or flag it as missing and needed.

Thanks,
Louisa

**Comment by AshDeeming** [comment]
Thanks @LouisaEvosite 
This will need to be reviewed as a potential feature - I've updated the ticket to be reviewed by the relevant team
