### ISSUE TITLE
Webhook Issue (for modifying and creating properties)

### ISSUE THREAD

**Issue by ebuildwebsolutions** [reapit/foundations#7498]
Hi,

I have a webhook in place to check for new properties or property updates.

The issue I am having is that the customer does not want to receive properties on his website with these statuses for Letting and Sales. 

Letting Status:  Valuation

Selling Status:
- PreAppraisal
- Valuation
- PaidValuation

He does a lot of these and does not want to be charged for them to come across in the webhook.
I was told that this was adjusted for the previous developer who's app is no longer used.

I have tried not to use the standard Property modify or Property Create to see if I could get around this issue. See attached graphic.

I have used the following options but it is not firing the webhook when the agent modifies a property:

- Selling property under offer
- Selling property instructed
- Selling property withdrawn
- Selling property exchanged
- Selling property completed
- Selling property asking price change.

Can you let me know how to get around this problem please?

![webook](https://user-images.githubusercontent.com/25635668/183874752-7b98afd6-0e33-42e4-89c0-95c179d23b67.PNG)

**Comment by AshDeeming** [comment]
Hi @ebuildwebsolutions 

Please could you provide a screenshot of the webhook configuration? 
It currently appears the app is only installed for 'SBOX' & the webhook is inactive.

**Comment by ebuildwebsolutions** [comment]
Hi Ash,

Here you go.

![webhook2](https://user-images.githubusercontent.com/25635668/183884270-8d2e58e1-abf8-4cde-a6a9-9ba401631395.PNG)

Thanks,

**Comment by AshDeeming** [comment]
Thanks @ebuildwebsolutions 
Please could you confirm the app name for the above?

**Comment by ebuildwebsolutions** [comment]
Its a webhook but use the credentials from "Property Feed".

**Comment by AshDeeming** [comment]
Thanks @ebuildwebsolutions 
Please could you ping the webhook (https://developers.reapit.cloud/webhooks/about) & also provide the property ref of  the prop record the client has advised has been updated?

**Comment by ebuildwebsolutions** [comment]
Hi Ash,

If I understand you correctly, I don't want to modify a property in Reapit. I want to retrieve the property data from Reapit using the webhook when the agent has modified or created a new property within Reapit.

The issue I am having is I don't want to valuations to be in the webhook feed (hence why I didn't use the standard 'create' or 'modified'). Hope that makes sense.

Is it possible to restrict data from Reapit using the webhook out to an external database?

**Comment by AshDeeming** [comment]
Hi @ebuildwebsolutions 

That's currently not possible however please see the below page regarding website development,
https://foundations-documentation.reapit.cloud/app-development/website-development

You may also wish to follow: https://github.com/reapit/foundations/issues/4289 relating to potential future webhook enhancements.

**Comment by plittlewood-rpt** [comment]
Hi @ebuildwebsolutions as Ash has pointed out yesterday, #4289 is something we may look at in the future that will allow you to achieve these results. The only real suggestion at the moment is to not use webhooks if this is a big issue for you, and instead poll for data changes. This will likely work out cheaper as you retain more control over your API consumption. Webhooks are tied to user actions. I will close this ticket now, but you are welcome to track the other ticket and comment as appropriate
