### ISSUE TITLE
User Created User Groups

### ISSUE THREAD

**Issue by roscoe2001** [reapit/foundations#7500]
We need a way of adding additional security around Apps. The example being we need to install an App for the whole organisation because it will be used by a central hub/team to manage the Works Orders on behalf of the network. What we 'really' need is when you install an App you say "These are the users who need access to the App" AND "everyone who can access the app can access the data for these Branches".

Given that is probably a big job for yourselves we're looking at alternatives. One thing we've considered is using the User Groups but we would need the ability to add them ourselves - would that be possible?

If we could do this then we would assign certain Apps to people this way i.e. Create a User Group called 'Works Order App' for example when someone tried to access the 'Works Order App' we would check if they had the relevant access (as app App might be installed for Branch A but we don't want a user from Branch A to have access).

Does this make sense? If there's other alternatives please let me know.

**Comment by HollyJoyPhillips** [comment]
@roscoe2001 Unfortunately it's not possible to create additional user groups. The only alternative would be for the developer to implement within the app a list of users that could or could not use the app. They may still be able to launch it but the app could then use the ID token provided by Reapit Connect to obtain the email address and to check it against the apps 'whitelist'. 

Please see more information here https://foundations-documentation.reapit.cloud/faqs#how-do-i-find-out-information-about-a-user
