### ISSUE TITLE
Authentication failure for new client - Kay and Co(KYC)

### ISSUE THREAD

**Issue by gokulngk** [reapit/foundations#7506]
When we try to import the property data from the reapit PAAS, it returns the following error(For customer ID: KYC).

statusCode: 401,
dateTime: '2022-08-11T05:22:37Z',
description: 'The request could not be fulfilled as the reapit customer specified by the provided credentials does not have the application installed.'

**Note :** The App was installed 3 days before and it is listed in the foundation dashboard. 
![image](https://user-images.githubusercontent.com/69853902/184071810-01c109b1-7cb0-40d8-a7db-287000a36675.png)

**FYR Foundation screen shot:**

Can please check and share your comments.

**Comment by AshDeeming** [comment]
Hi @gokulngk 
Please could you confirm the app name?

**Comment by gokulngk** [comment]
Hi @AshDeeming  

Thank you for your reply. The App name is Starberry DataXchange RCK.  Looks like we are now receiving the data from the API. Will reach out to you if in case of any further details.

**Comment by AshDeeming** [comment]
Thanks @gokulngk
