### ISSUE TITLE
Office Groups 

### ISSUE THREAD

**Issue by roscoe2001** [reapit/foundations#7508]
When we install an App for 2 (or more) Office Groups we want a user to be able to access the data for all the offices in any of the assigned groups (not just the ones in the group they are allocated to). This is because we have central users who are managing some of the workload for the branch network.

Is there anyway of doing this (from my tests it seems if you install an App for many Office Groups an individual user can only access data for the Office Group they are assigned to)?

**Comment by plittlewood-rpt** [comment]
Hi @roscoe2001 - the office groups mechanism was designed to allow data to be ringfenced to users in those groups and as such there's no real scope for allowing this kind of crossover. As a user can only belong to one office it would soon become incredibly complex to manage that kind of security model both technically and for the administrators managing installations.

**Comment by roscoe2001** [comment]
Hi @plittlewood-rpt. Thanks for the reply. The underlining issue is not being able to have an Office in multiple Office Groups. If we could do all the other issues go away.

An example : -
- 10 offices are assigned to use an App A (and need to share data)
- 5 of those Offices use App B

The only way we can do this is create 2 Office Groups with 5 branches in each (assign 2 OG's to App A and 1 Office group to App B). The problem is the 10 offices in App A can't then share data across all 10 branches NB this is just a made up example to explain the issue but it's more fundamental than that as some of this is across network and franchise branches so will become a big issue for us going forward
