### ISSUE TITLE
Ability to filter Metadata records via array values

### ISSUE THREAD

**Issue by whanno-lsl** [reapit/foundations#7516]
**Is your feature request related to a problem? Please describe.**
Is there any way of searching for Metadata records using an array field in the metadata? 
i.e. say I have created a "Team" metadata entity and it contains an array of negotiatorIds. 
Can I find all the teams which contain a specific negotiatorId? 

**Describe the solution you'd like**
Basically I think I may need some sort of CONTAINS filter to return Metadata entities where an array contains the value(s) I am interested in.

**Describe alternatives you've considered**
I've read the docs but haven't spotted a way to do this.

**Specification**
- Project: Reapit.Services.Metadata
- Construct a `ContainsMetadataFilterType` that allows a developer to pass a `$contains` filter query string parameter that maps to the respective DynamoDb operation. Contains operator should allow one or more values
- Ensure tests are added to cover new filter class
- Ensure Metadata documentation is updated (Gitbook) when this is ready to go out
- Ensure array example above is specifically tested - desired syntax `metadata.myArray $contains 'A','B'`

**Tasks**
- [ ] Service update
- [ ] Documentation update

**Comment by plittlewood-rpt** [comment]
Hi @whanno-lsl - we are just QA'ing this work. Do you have any examples of metadata you already store that we could run the updated version of this service against?

**Comment by whanno-lsl** [comment]
Sure, we have a "maintenanceTeam" entity and would like to find the teams that a specific negotiator is a member of. 

For example:
{
  "entityType": "maintenanceTeam",
  "metadata": {
    "teamName": "My New Team",
    "hidden": false,
    "teamMembers": [
      {"negotitatorId": "ADV"},
      {"negotitatorId": "MKT"}
    ]
  }
}

**Comment by plittlewood-rpt** [comment]
Thanks for that - glad I asked that question as I dont' think the way we've implemented it will work. It's been designed to operate on an array of values, rather than an array of objects ie

```
{
	"entityType": "maintenanceTeam",
	"metadata": {
		"teamName": "My New Team",
		"hidden": false,
		"teamMembers": ["ADV","MKT"]
	}
}
```

I'll run some tests and see if further changes are required

**Comment by plittlewood-rpt** [comment]
Hi @whanno-lsl - I'm afraid what you're wanting to do isn't actually possible. 

Effectively you'd need to be able to do something like this:

`metadata.teamMembers[*].negotiator $eq "ADV"`

or this

`metadata.teamMembers $contains [some object]`

From your original post it did seem to suggest that your data was in the format I've posted in my previous comment, in which case the contains filter will work. What's the likelihood of remodelling your data?

**Comment by whanno-lsl** [comment]
Okay if it's not possible then we can look at working your suggested way.
It just seems a bit limited to me but I'm no expert in this area so no problem as you've given us something to work with, thanks.

**Comment by plittlewood-rpt** [comment]
The $con operator has been added as above and released to production. If you still have difficulties please dome back to me
