### ISSUE TITLE
Request for Open house semi structured property field.

### ISSUE THREAD

**Issue by rajeshwl** [reapit/foundations#7519]
This is related to the existing request:
https://github.com/reapit/foundations/issues/7375

Still the extrasField is empty. We couldn't find the field in the extrasFields.

![image](https://user-images.githubusercontent.com/14073702/184289839-909e956c-8f43-4887-b83f-92a6da569ea6.png)

**Comment by plittlewood-rpt** [comment]
Hi @rajeshwl please can you give me an example of a property where you would expect this to be populated? It could just be that the customer is not using this feature. Extrasfield data will only be returned if it is explicitly set in the database.

**Comment by rajeshwl** [comment]
Hi @plittlewood-rpt ,
The property reference is OBR220080.

**Comment by plittlewood-rpt** [comment]
Hi @rajeshwl I've just checked that property and the box isn't ticked in the customers' system which is why it is not displaying. In fact, I've checked their entire system and no properties have it selected.

**Comment by rajeshwl** [comment]
Thanks for checking @plittlewood-rpt . We will check with client and come back to you.
