### ISSUE TITLE
Be able to generate a pre-signed s3 bucket url for existing documents

### ISSUE THREAD

**Issue by gareth-evans** [reapit/foundations#7525]
**Is your feature request related to a problem? Please describe.**
We want to allow our customers to download their documents in our customer portal. We would like to avoid proxying any of the document data and redirect to s3.

**Describe the solution you'd like**
When a customer tries to download a document from our API we would like to return a 302 response with a location header containing a signed s3 URL with read permissions.

**Describe alternatives you've considered**
For larger files, hitting the Foundations API to download a file, the response redirects to s3, so we could ignore the redirect and take the location header and pass it back. However, for smaller files the raw file is served.

The architecture we have would make it difficult to return the response that is either a redirect or raw binary data. It would be simpler if we could get a signed url for any document.

**Specification**
- Project: Reapit.Services.Documents
- For any customer using S3 file storage, always redirect to pre-signed URL. This removes a lot of pressure of the service itself and also gives a more direct route for consumers wanting to download document assets

**Comment by rochellelevy** [comment]
@HollyJoyPhillips if its possible to prioritise this, I would really appreciate as it help us meet our deadlines. The alternative solution that Gareth has outlined will add a significant amount of complexity and time taken to code the solution.

**Comment by rochellelevy** [comment]
Brilliant @plittlewood-rpt thanks!

**Comment by RWilcox-Reapit** [comment]
Hi @gareth-evans and @rochellelevy 

This change has just been released to production. For any customer on AWS now you'll receive a redirect to S3 as per you request.

Thanks
Ryan

**Comment by plittlewood-rpt** [comment]
For info we have had to roll this back due to a CORS issue - we'll update this ticket again once the change is re-released

**Comment by gareth-evans** [comment]
@plittlewood-rpt is there any update on this?

It sounds like what has been implemented is now all calls to `document/[document id]/download` will redirect to a signed s3 url. Is that correct?
