### ISSUE TITLE
Can't Add inquiries without title and suname

### ISSUE THREAD

**Issue by sanjayisg** [reapit/foundations#7527]
Hi There,

I would like to share my feedback about foundation API for enquiries: 

I can't add entry with api if people do not have entered their title and surname.  Is it possible we can add record without title and surname. In many case people have name of single word, in that case it become problem. For easiness of our customer in our web form we don't make it compulsory (title and surname).

Can we escape this validation, please help.

Thanks,

Sanjay Gupta

**Specification**
- Project: Reapit.Services.Enquiries
- Update CreateEnquiryCommandValidation to allow items with no title or first name (validation should then match the contacts API)
- Make sure there's no issue with non-nullable fields in the database as a result of this change
- Ensure SwaggerRequired attributes are removed from model spec

**Comment by sanjayisg** [comment]
In contact API title and firstname is not required then we must be able to do the same here.

**Comment by sanjayisg** [comment]
Hi There,

Is there any update on the requirements.

Thanks,

Sanjay Gupta

**Comment by RWilcox-Reapit** [comment]
Hi @sanjayisg 

This release has just gone out to production. You should now be able to create enquiries without a forename or title

Thanks,
Ryan

**Comment by sanjayisg** [comment]
Thanks a lot Ryan!
