### ISSUE TITLE
Integration question

### ISSUE THREAD

**Issue by roscoe2001** [reapit/foundations#7529]
We're trying to setup a third party with access to foundations but having a couple of issues.

If an integration is switched on for 2 office groups (YOM_OG1 and YOM_OG2) - does the third party use: - 
- Those 2 code (i.e. the codes of the office groups - YOM_OG1 and YOM_OG2)
or
- The organizational code - YOM (so in effect they use YOM and the actual Install limits it to the 2 Office Groups)
----------------------------------------------------------------------------------------------------------------------
The App in question is LeadPro - it's installed for a number of Office Groups - I said they need to use YOM (and the data will be restricted by the actual install) - I presumed that is right but wanted to double check as they have said they are getting an unauthorised error when trying to call the API NB I've asked for more detail on the exact message.

**Comment by AshDeeming** [comment]
Hi @roscoe2001 
The LeadPro app is public therefore it could be installed by either the entire database for YOM (by the relevant admin user) or Installed against specific office groups, depending on how the Office Groups are managed. 
I hope this clarifies?

**Comment by roscoe2001** [comment]
Hi @AshDeeming - On the Foundations side I've installed it for the relevant Office Groups.

The question is more around how LeadPro call it from their side (which they seem to be struggling with but I can't really help them as I'm blind to their side). When they call the API, do they configure the calls to use 'YOM' (rather than passing in a list of Office Groups)?

**Comment by plittlewood-rpt** [comment]
Hi @roscoe2001 - if the app is installed for an office group, they should use the customer id with the group suffix to call the API - eg YOM-GABC (otherwise they'll get an Unauthorized message). Only if an app is installed for the whole organisation would they just use YOM. Hope this helps

**Comment by roscoe2001** [comment]
Thanks @plittlewood-rpt - last question (hopefully)

So if it's installed for multiple Office Groups (lets say 5) - can they use a list? - The main reason for this question is LeadPro have said:- 
>> On our side we can only connect one Reapit ID to your account

(or do they use 1 at a time but make multiple calls (1 per office group)?)

On a side note - because an office can only be in 1 office group it is causing us to split Office Groups into small parts and assign multiple to the Apps/Integrations.

**Comment by plittlewood-rpt** [comment]
Hi @roscoe2001 - they can only hit the API for one customer id at a time so they would need to make multiple requests

**Comment by roscoe2001** [comment]
OK thanks. I've informed LeadPro that's what they need to do.

On a side note this isn't ideal for the third party as the list Office Group list can change e.g. if an office is part of an office group installed against an App 1 and we need to give that office access to App 2 (but not all the other offices in that group) we have to : -
1 - Remove that office from it's current OG
2 - Create a new OG with that Office in
3 - Add the new OG to App 1 and App 2
4 - So the third party will now have to make an additional request 

But that's an aside - this can be closed now as it answers the original question. Thanks.
