### ISSUE TITLE
Tenancy deposits not coming through - related to #7280

### ISSUE THREAD

**Issue by LouisaEvosite** [reapit/foundations#7530]
Related to https://github.com/reapit/foundations/issues/7280

I can see where the deposit should be:
![image](https://user-images.githubusercontent.com/109209591/184606373-4745cab5-c3c0-4516-a8aa-d2162ddbd888.png)

But none of the tenancies I look up seem to be returning a value in those fields.

Thanks,
Louisa

**Comment by plittlewood-rpt** [comment]
Hi @LouisaEvosite please can you confirm which customer this relates to

**Comment by LouisaEvosite** [comment]
Hi @plittlewood-rpt  just been choosing random ones but looked at tenancies:
WRE220228
PON220058
LIV220148 and all had empty deposit heldBy and deposit sum
Thanks,
Louisa

**Comment by plittlewood-rpt** [comment]
Hi @LouisaEvosite I need to know which customer this relates to so I can have a look at their data. Can you provide the name or three letter id of the customer concerned please?

**Comment by LouisaEvosite** [comment]
@plittlewood-rpt - Oh I see. It is RER

**Comment by plittlewood-rpt** [comment]
Hi @LouisaEvosite this is now resolved

**Comment by LouisaEvosite** [comment]
Great, thank you!
