### ISSUE TITLE
Server Side App Authentication - 3CX

### ISSUE THREAD

**Issue by jordanlewis-dngl** [reapit/foundations#7531]
Creating a CRM template via 3CX CRM Template Generator to integrate Reapit with 3CX VOIP system:

https://www.3cx.com/docs/crm-integration/]

The aim is to pull a contact based on phone number or email address when a call is received.

Produced an XML file using the above tool but having issues with authentication.

Please see attached XML file (.txt format) and error received via 3CX when testing.

@willmcvay - `Removed reference to client secret`

**Comment by AshDeeming** [comment]
Hi @jordanlewis-dngl 

Please could you clarify the request? Please note the above link goes to a 404?

**Comment by jordanlewis-dngl** [comment]
https://www.3cx.com/docs/crm-integration/

The above link should work.

The 3CX template generator just uses URIs to call an API to retrieve info basic info about contacts, name, company etc. OAuth 2.0 is supported but I may not be passing the correct info?

There is also an option to authorise via 3CX by specifying the client ID and secret:

![image](https://user-images.githubusercontent.com/108016524/184645225-efd52f7f-6780-402a-bf1f-feeda020b0aa.png)

Selecting authorise takes me to this link: https://connect.reapit.cloud/?response_type=code&client_id=52nt0tanor3dugcepa2v382vtd&redirect_uri=https%3A%2F%2Fypp.3cx.uk%2Fapi%2Foauth2crm&state=90aa2486-ef3a-4589-95c4-0fab38118037

which is just a white blank page.

I'm just after a bit of guidance with regards to authenticating against your OAuth2.0.

**Comment by AshDeeming** [comment]
Hi @jordanlewis-dngl 
the below should be of use however please let me know if there is something else: 
https://foundations-documentation.reapit.cloud/api/reapit-connect#authentication-flow

**Comment by jordanlewis-dngl** [comment]
hi Ash,

I used that documentation to create the initial xml and got the error that I sent. Any chance you could advise what I'm missing for auth/why it's throwing errors?

Cheers

**Comment by willmcvay** [comment]
@jordanlewis-dngl 

> Selecting authorise takes me to this link: https://connect.reapit.cloud/?response_type=code&client_id=52nt0tanor3dugcepa2v382vtd&redirect_uri=https%3A%2F%2Fypp.3cx.uk%2Fapi%2Foauth2crm&state=90aa2486-ef3a-4589-95c4-0fab38118037

This is an Authorization Code flow see: https://foundations-documentation.reapit.cloud/api/reapit-connect#authentication-flow - this requires a user login. 

Your app has been registered as a Client Credentials app - I can see this from the Client Secret you have obtained. See: https://foundations-documentation.reapit.cloud/api/api-documentation#client-credentials-flow

The authentication flow is different in both cases. Please refer to the documentation linked on the different implementations. 

In addtion, I have edited your comments to remove your references to Client Secrets. These are, by definition secret and should not be shared in the public realm. Please delete your app in the developer portal immediately and re-register with the desired OAuth flow.

**Comment by jordanlewis-dngl** [comment]
Afternoon,

Authentication is sorted, thanks for the assistance.

Could you advise of any contacts within the Sandbox database that have a unique contact number? Or create a new contact with a unique number?

We're only trying to pull one contact when testing and I think it may be the returning multiple contacts that's causing issues.

Cheers

**Comment by jordanlewis-dngl** [comment]
Any update on the above team?

Thanks

**Comment by HollyJoyPhillips** [comment]
Hi @jordanlewis-dngl, please can you confirm that the information above has answered your question before we close this issue?
