### ISSUE TITLE
Webhook duplicate entry showing

### ISSUE THREAD

**Issue by subin-roundr** [reapit/foundations#7536]
**Describe the bug**
Whenever a webhook is added it shows 2 entries instead of single entry 

![image](https://user-images.githubusercontent.com/78721314/184790312-d1a6257a-fde4-48be-84f3-10b073b52269.png)

Browser chrome

**Comment by subin-roundr** [comment]
to reproduce , click create twice

**Comment by AshDeeming** [comment]
Hi @subin-roundr 
This appears to have occurred due to, as per your comment, from clicking on the create button again before the action has had time to respond/completed.

**Comment by subin-roundr** [comment]
@AshDeeming  ok , but there is no indication whether the action is being performed, like loader , so its confusing , whether the action has been saved or not
