### ISSUE TITLE
Outstanding balance of a tenancy?

### ISSUE THREAD

**Issue by WayneRobshaw** [reapit/foundations#7539]
Hi there,

I'm brand new to the reapit API so just finding my way around.  So far, I found tenancies, contacts, transactions that we need to work with, but I'm still looking for a tenancy outstanding balance.  Is this found using the transaction endpoint call looking for outstanding?

Also, is there anything in the API to expose tenancy arrangements (ie, arrears pay back arrangements)?  Similarly, does the system support action codes and Universal Credit?

Kind regards,

Wayne.

**Comment by AshDeeming** [comment]
Hi @WayneRobshaw 
Outstanding balances is part of the Client Accounts solution within AgencyCloud, which is not currently included in the Platform API. 

Details around a tenancy can be found in the /Tenancies/{id} Endpoint example & model, on the Swagger page (https://developers.reapit.cloud/swagger); 
![image](https://user-images.githubusercontent.com/61687775/185112760-6e4a7836-745a-48d8-b09e-4bcaa7e70e43.png)

I'm unsure regarding action codes & Universal credit in AgencyCloud - Does this relate to a specific Reapit Customer?

**Comment by WayneRobshaw** [comment]
Hi @AshDeeming,

Many thanks for the reply and clarification.

This is with regards to the Pinnacle Group.

Kind regards,

Wayne.

**Comment by AshDeeming** [comment]
Thanks @WayneRobshaw 
I've checked the build for this client however I am unable to locate any reference to Action Codes or Universal Credit. 
Please obtain a screen shot for this to be reviewed if required.
