### ISSUE TITLE
Where to find Accommodation Summary in the API Response?

### ISSUE THREAD

**Issue by jashiels99** [reapit/foundations#7543]
**Summary**
I am working with the foundations API and I am trying to find the 'Accommodation Summary' in the properties API response.

The section in the bottom right:
![accommodation summary](https://user-images.githubusercontent.com/40760694/185067724-615d18b0-df84-4b83-be2d-d03df44c56c2.png)

Apparently, this shows up in the 'rooms' section of the response but I'm not seeing it there.

Any advise on where I can find this data?

**Comment by AshDeeming** [comment]
Accommodation summary, shown under 'Summary' once populated; 
![image](https://user-images.githubusercontent.com/61687775/185080384-f8c80f54-633b-41c7-ad3a-d2400662f0b2.png)
