### ISSUE TITLE
Predefined Details Document

### ISSUE THREAD

**Issue by jashiels99** [reapit/foundations#7544]
I am trying to import documents from the Foundations API.

I have noticed there is a 'typeId' parameter for the documents endpoint. The client I am working with only wants the document that falls under 'Predefined Details':

![predefined details](https://user-images.githubusercontent.com/40760694/185069348-e09ae210-4540-418d-bb31-7ae1a897c179.png)

Does this fall under a specific typeId?

**Comment by AshDeeming** [comment]
Hi @jashiels99 

Please see Properties endpoint, with 'brochureId' held in either Selling or Letting dependant on marketing. 
The below article may also be useful regarding updating these:
https://foundations-documentation.reapit.cloud/whats-new#setting-predefined-property-brochure-details
