### ISSUE TITLE
Access denied when accessing Property Image Url

### ISSUE THREAD

**Issue by stebrough** [reapit/foundations#7547]
**Describe the bug**
When attempting to access a property image for a specific customer/property via the URL, we get access denied.

**To Reproduce**
1. Call PropertyImage endpoint and receive images for property
2. Access first via it's URL
3. See access denied

**Expected behaviour**
We are able to view the image

**Additional context**
Customer/Property/Image details submitted via email

**Comment by AshDeeming** [comment]
https://reapitfoundations.zendesk.com/agent/tickets/290

**Comment by stebrough** [comment]
Hi @AshDeeming sorry I don't have access to that system, are you requesting your customer logs a ticket via that portal?

**Comment by AshDeeming** [comment]
Hi @stebrough 
Apologies, nothing for you to action - I just wanted to include the additional data for the team when reviewing

**Comment by stebrough** [comment]
No worries cheers @AshDeeming

**Comment by AshDeeming** [comment]
Jira ticket SI-18398 created for internal PropertyImages Response Code review

**Comment by Paul-Barnett-Reech** [comment]
I'm having the same issue. Was any progress made on this?

**Comment by HollyJoyPhillips** [comment]
Closing due to housekeeping, please comment if this is still an issue.
