### ISSUE TITLE
Offr option not appearing in property feed.

### ISSUE THREAD

**Issue by ebuildwebsolutions** [reapit/foundations#7554]
Hi,

A new tick function was added to the Ed Dempsey's Marketing section in Reapit. See screen shot.

The issue I am experiencing is that I am not see this information in the APP feed. 

My APP name is called Property Feed and the App ID is 6ca8a3f7-1137-4257-90a2-8e1a5f829495

Where should this information appear in the feed when using https://platform.reapit.cloud/properties/
![offr-option](https://user-images.githubusercontent.com/25635668/185583422-56130ade-5ae9-4706-8b84-a38b5e095869.png)

Kind regards,

Philip

**Comment by plittlewood-rpt** [comment]
Hi @ebuildwebsolutions this is a custom field and as such doesn't form part of the standard Foundations models. I have enabled access to this field for you and it will appear in the `extrasField` object when you explicitly request it. You need to use the `extrasField` query string parameter to retrieve this data using the field name `pOffr` eg

`GET /properties?extrasField=pOffr` and/or `GET /properties/{id}?extrasField=pOffr`

Note that the value will only be returned if explicitly set in the database.
