### ISSUE TITLE
Marketing consent for solicitors 

### ISSUE THREAD

**Issue by BYMIntegrations** [reapit/foundations#7556]
**Is your feature request related to a problem? Please describe.**
We have had a ticket raised regarding the marketizing consent being changed in ReapIT but not BYM. This was for a solicitors. Please see below, on their company record there is no marketing consent field, however I have been sent a screenshot from the customer of them opting them out of marketing. 
![image](https://user-images.githubusercontent.com/102583061/185593804-71d325e4-91fe-493d-8867-c8874bae6b23.png)
![image](https://user-images.githubusercontent.com/102583061/185593821-1173c380-c423-4891-8a70-8f9c1a26001b.png)
![image](https://user-images.githubusercontent.com/102583061/185594093-8ed45ac0-e95b-475e-83b3-2764111a345a.png)

**Describe the solution you'd like**
Are we able to add the marketing consent field into your API/Company for solicitors? 
**Describe alternatives you've considered**

**Additional context**

**Comment by AshDeeming** [comment]
Hi @BYMIntegrations 
Please can you confirm where the above CompanyModel is from? 
As per our Platform Swagger docs (https://developers.reapit.cloud/swagger), the Companies Model, shows: 
![image](https://user-images.githubusercontent.com/61687775/185630578-3d012f1b-b83a-43d1-ab69-bb05372e2d42.png)
