### ISSUE TITLE
Webhooks not firing for CHB

### ISSUE THREAD

**Issue by Speedway1** [reapit/foundations#7559]
Customer ID CHB has webooks defined on it, but they are not firing. We removed them all and recreated, still not firing. These were working when we set the client up, but they dropped off. We have seen this with other clients previously.

**Specification**

**Comment by plittlewood-rpt** [comment]
Hi @Speedway1 - I can't see that webhooks have ever been enabled for this customer, though you would have got application.install events (as these aren't tied to the database events). The setup process is just running so you should start to see webhooks come through for this customer soon
