### ISSUE TITLE
Documents endpoint - increase the pageSize

### ISSUE THREAD

**Issue by maxcivino** [reapit/foundations#7560]
At the moment the max page size is 100.

Documents endpoint body response payload doesn't look too big and it would be good to extend that threshold to 1000 or a bigger number, so we can avoid to send more requests to get the documents.

Please let me know if you need more details.

Thanks

**Comment by plittlewood-rpt** [comment]
Hi @maxcivino - the maximum page size is set across all endpoints for consistency. Introducing differences could create confusion and have a negative impact on the user experience of the Platform. As such this isn't something we will be able to do unfortunately.
