### ISSUE TITLE
Documents endpoint timing out - response time performance

### ISSUE THREAD

**Issue by maxcivino** [reapit/foundations#7562]
Hi,
the documents endpoint on Prod has really bad performance.

Often a request is timing out. When a filter on a date is applied, it is taking between 3 and 6 secs to get the response.

Example
documents?createdFrom=2020-01-01&pageSize=100&pageNumber=1

This is a real issue for our system and its SLA.

Please let us know if you can look into is as soon as possible.

Regards,
Max

**Specification**
- Project: Reapit.Services.Documents
- Review the queries that get run when using this service to see if there are any performance improvements that can be made. 
- Work with SI to understand if there are any index inefficiencies or additional indexes that could be added to improve the performance on such a large dataset

**Comment by maxcivino** [comment]
Hi Peter, thanks for your Reply.
I would like to add that the timing out is happening even on UAT (CustomerId SAU).

This is quite critical for us, because we would need to show the documents in the last 5years for any contact.

Please let us know if there is any alternative.

Regards,
Max

**Comment by rochellelevy** [comment]
@HollyJoyPhillips Is sprint 76 the current sprint? As Max said, this is really critical for us.

**Comment by HollyJoyPhillips** [comment]
Hi @rochellelevy, yes 76 is our current sprint.

**Comment by plittlewood-rpt** [comment]
Hi @maxcivino 

I've had a look at this and it ultimately stems from the sheer amount of data in your system - the query being run is pretty simple and there isn't really anything we can do in the short term to optimize it - we do have a long term plan to move away from MySQL driving read operations in the Platform, but there's a long road ahead to get to that point so we need to look at alternatives in the meantime. 

I'm due to speak to our infrastructure team about the query performance later this week, however I would like to understand more about the requests you are making. It's likely that you'll get better results if you are able to include more filters in your request (ie fetch documents for a specific entity since the date provided. This will allow the compiler to make better use of indexes). Is it feasible to look at the way you are requesting this data to see if we can come up with something here?

I'll be in touch again once I've got more to relay back to you

**Comment by plittlewood-rpt** [comment]
Internal ref: SI-18586

**Comment by maxcivino** [comment]
Dear @plittlewood-rpt ,
thanks for your reply.

As you probably know, Reapit documents can be associated to different entities (property, landlord, tenancy, applicant, contact, ect.). 
Our requirement is to get all the Reapit documents directly or indirectly related to a specific contact (contactId). 
Also, we would need to extend those document information with some fields related to our new project.

One solution we are trying to implement is to project the current documents data from Reapit into a NoSql database (based on Contact). The provided Reapit Webhook feature will sync the data on our repository,

In order to deliver this solution, we would need to migrate the data in the past. That's why we would need to run a job with some queries (split in batches) to get all the documents in a range of dates.

The filter I have applied so far is based on:
CreatedTo
CreatedFrom
IsPrivate (not available)
AssociatedTypes: contact, landlord, property, tenancy, applicant

As you know the response is paged, and I'm using a max pagesize of 100.

I'm splitting the batches in period of 6months, but still facing some performance issues. (timeout, or response time > 5secs, etc.)

The other solution we can think of is to get the documents per contact from Reapit Api on the fly. This means that for each contact we would need first to get all the entities related to it and then get the documents.
I suppose this won't overcome the performance issue and will add an overhead to the response time. (We would like to get the response time < 100ms). It's a solution that probably will require to add some data cache.
Considering that they are data in Reapit, not sure if the implementation of this endpoint is something feasible on your side? 

I hope this summary provides you a better understanding of our requirements. Please don't hesitate to ask more questions.
We can discuss via chat if this can facilitate the conversation.

Thanks,
Max

**Comment by plittlewood-rpt** [comment]
Thanks Max - I'm just waiting to hear back from our internal infrastructure team on this as they are responsible for the database.

**Comment by plittlewood-rpt** [comment]
Hi @maxcivino can you let me know if you've seen any improvement in performance? Our DB team have looked at the indexing on the database from a performance tuning perspective and we seem to see < 2s response times pretty consistently. This is still too long, but it is progress none the less.

**Comment by plittlewood-rpt** [comment]
Hi @maxcivino can you come back to me on the above? We are having separate discussions about how we can improve performance of services on larger datasets like yours. If there is no immediate problem I'd suggest we close out this ticket in favour of the Performance Enhancements milestone

**Comment by maxcivino** [comment]
Hi @plittlewood-rpt.  
Sorry for the late reply and thanks for your message.
I agree with your suggestion because we are following a different solution where this issue is not critical anymore.
