### ISSUE TITLE
App installed email not received 

### ISSUE THREAD

**Issue by Filip5991** [reapit/foundations#7566]
This is related to the emails that are auto-sent when an app is (un)installed.

The documentations states: An email will be sent to the email address used to register your [developer organisation] (office email) and to the support email address you have provided on your app listing

The support email on our app (Acaboom) is **tech@acaboom.co.uk** - and we always receive all installations and uninstallations here. 
The email address that was used to register the developer organization is **support@acaboom.co.uk**, but we only receive half of the installation emails here. (sometimes they arrive, sometimes there's nothing, no specific pattern)

Is there something that needs to be activated for both email addresses to work properly, or is there some issue with the email sending?

**Specification**
- Project: Marketplace
- Debug behaviour in `EmailNotificationClient` to understand why the wrong email addresses are sometimes being picked up

**Comment by HollyJoyPhillips** [comment]
The notification email is correctly set to support@ and the main account is Brian's. It's seems to not be respecting the alternative notification email. We will get this looked into. 

Note: Ask HP for details
