### ISSUE TITLE
Updating info on the financials & renewals tab of tenancies via the API

### ISSUE THREAD

**Issue by FrankieMalpass** [reapit/foundations#7572]
Please take a look at our FAQ's before submitting an issue, as your question may already be covered in the documentation https://foundations-documentation.reapit.cloud/faqs

**Summary**
Hello, 

I haven't been able to find this in the API documentation so I wanted to check with you. Is it possible to update the information in the financials & renewals tab on tenancies via the API? 

In particular I'm interested in adding renewal information to an existing tenancy (start and end date of the renewal, Rent and payable). 

Thanks in advance,
Frankie

**Detail and or supporting links and screenshots**
<img width="515" alt="image" src="https://user-images.githubusercontent.com/31128382/186203882-241ebc64-fd13-4969-8c72-afe3e2f898cb.png">

**Comment by AshDeeming** [comment]
Hi @FrankieMalpass 
The fields currently available can be found against the Tenancies Endpoint - model screenshot below; (Includes Rent & RentFrequency) 
![image](https://user-images.githubusercontent.com/61687775/186392635-0c8d10ad-2427-48f9-af03-1293a6442680.png)

The renewal section is not currently available however if you would like to raise a [Feature Request here ](https://github.com/reapit/foundations/issues/new?assignees=&labels=external-request%2C+needs-triage&template=feature_request.md&title=) this can be reviewed by the relevant team.
