### ISSUE TITLE
Negotiator webhook

### ISSUE THREAD

**Issue by komalpuri27** [reapit/foundations#7580]
**Summary**

Is there any webhook available for negotiators creation/updation?

I was not able to find it in the topics list. Kindly guide me in the right direction.

**Comment by AshDeeming** [comment]
Hi @komalpuri27 

All currently available webhook topics are listed via the below; https://foundations-documentation.reapit.cloud/api/webhooks#available-topics

There is not currently a webhooks for Negotiators - If this is required, please raise a feature request with supporting information around the requirements/business case

**Comment by komalpuri27** [comment]
Thanks @AshDeeming
