### ISSUE TITLE
Tenancy start and end date getting updated

### ISSUE THREAD

**Issue by komalpuri27** [reapit/foundations#7581]
**Summary**
When we try to update the meter readings:

Example given below

endpoint:
[PATCH] https://platform.reapit.cloud/tenancies/RPT170002
payload
(update water meter reading and add meter reading water last read):
{
  "meterReadingWater": "140",
  "meterReadingWaterLastRead": "2022-08-17"
}
header
reapit-customer: SBOX
Authorization: Bearer <token>
api-version: 2020-01-31
Content-Type: application/json
Accept: application/json
If-Match: <_eTag>

The tenancy start and end date are getting cleared. 

Please help us check why this is happening and what we can do to not update it from our end.

**Comment by plittlewood-rpt** [comment]
Thanks for raising this item - a fix will be in QA shortly
