### ISSUE TITLE
martyn gerrard estate agents field request

### ISSUE THREAD

**Issue by BYMIntegrations** [reapit/foundations#7582]
**Is your feature request related to a problem? Please describe.**
Martyn Gerrard have requested if we could receive the field Interests - the tag is called MY-MG
**Describe the solution you'd like**
We would like to receive this in BYM if possible. 
**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/102583061/186634708-698b17cb-7397-4699-834b-efacb2d72c34.png)

**Comment by HollyJoyPhillips** [comment]
Hi @BYMIntegrations, we provide on the contacts endpoint, a collection of category ID's which you can then use the configurations/contactcategories to identify. 

![image](https://user-images.githubusercontent.com/52408607/186641352-1447eed3-5646-4889-813d-ec8011828fce.png)
![image](https://user-images.githubusercontent.com/52408607/186641979-6c06a027-9a84-4a77-a963-36f2b5d5ee6a.png)

Is that what you require?

**Comment by BYMIntegrations** [comment]
Hi Holly,

Just to be clear, is this something you are already sending to us? If so is it something we need to do on our end?

**Comment by HollyJoyPhillips** [comment]
Hi @BYMIntegrations I'm not sure I follow, the data is available in the contacts endpoint. If you are using webhooks it will be included in the payload. To understand what the ID's map to, you'll need to make a call to the configurations endpoint.

**Comment by BYMIntegrations** [comment]
Ah my apologies. Raised this with our Dev team. Thank you!
