### ISSUE TITLE
Getting Home Reports

### ISSUE THREAD

**Issue by propertyhive** [reapit/foundations#7597]
A mutual Scottish client has had the Home Reports section enabled within their Reapit account, but I can't see anyway to import these. 

There doesn't seem to be a field for this returned when making requests to /properties/, nor any permissions relating to Home Reports.

Can you confirm how we might access these so we can display them on the clients website?

Thanks,
Steve

**Comment by AshDeeming** [comment]
Hi @propertyhive 
Please can you confirm the client name along with where this report sits within AgencyCloud?

**Comment by propertyhive** [comment]
@AshDeeming Client is Paton & Co. They have said "we now have a home report section which is under HR on Reapit".

Hope that helps,
Steve

**Comment by propertyhive** [comment]
Thanks. We don't have the ReadDocuments permission applied to the app yet so I'll need to add that and try to get everyone using the app to accept the new permissions. Will look to do this this week.
