### ISSUE TITLE
Fetching Tenants from Tenancy 

### ISSUE THREAD

**Issue by raymond2323** [reapit/foundations#7599]
We are trying to use GET Tenancies endpoint to import Tenancies into our system. 

What is the most effective way to fetch all tenants related to a Tenancy?

We noticed that there is an ApplicantID, but this is not a list, and thefore we can only fetch one Tenant per Tenancy. 

Can we use the related fields to fetch Tenants? From the docs it looks like you list related contacts but how do we distinguish which one is a tenant or a landlord? 

Please advise what is the most effective call to coduct as we trying to build a page where we should fetch all tenancies for a particular property with the corresponding Tenant, start and end date and rental price for a Tenancy. We noticed that if we ran GET Applicant endpoint after Fetching the Tenancy the response time on Staging was too slow to conduct on a page load. 

**Specification**
- Project: Reapit.Services.Tenancies
- Currently when the tenancy is in an arranging status, we do not expose the contacts associated to the attached applicant in the `related` collection. Given the service is already aware of the lookup and contact entities we can make the developer experience of using this endpoint much nicer.
- When tenancy status is arranging, we should lookup the contacts associated with the applicant and build the related collection accordingly, ensuring that the primary contact is listed first (this can be ascertained from the contact code on the applicant record)
- When ternancy status is current, existing behaviour should be retained

**Comment by raymond2323** [comment]
Additional Question:

We tested fetching the GET Applicant after we have Fetched Tenancy on production and the response time actually seems to be okay, however it still raises the question on how we Fetch all Tenants, as within the Tenancy response it only offers one Applicant ID.

**Comment by raymond2323** [comment]
@plittlewood-rpt how is this a  platform backlog? This is a question - could you provide an answer?

**Comment by plittlewood-rpt** [comment]
HI @raymond2323 I'm not sure what your comment is regarding - we have made a decision to make this API easier to use as per the specification so associated contacts will always appear in the `related` collection of the tenancy model, regardless of the tenancy status

**Comment by raymond2323** [comment]
okay but for the time being how can I pull all Tenants and Landlords for a tenancy?

**Comment by plittlewood-rpt** [comment]
Hi @raymond2323 

The landlord is attached to the property not the tenancy, so you'd need to lookup the property and you can access the landlord from there

If a tenancy is in the arranging state, to get the associated contacts you need to hit the applicants endpoint using the `applicantId` returned from the tenancy endpoint

If a tenancy is in the current state, the tenants on the tenancy will be shown in the `related` collection.

Let me know if this doesn't make sense

Thanks

**Comment by raymond2323** [comment]
@RWilcox-Reapit @plittlewood-rpt 

Just a follow-up to your last point. 

Your Tenancy end-point only provides us with one Applicant ID. How do we fetch multiple Tenants/applicants related to a Tenancy, as we can only fetch one?

**Comment by raymond2323** [comment]
@plittlewood-rpt 
the `related` collection of the tenancy does not contain tenants when the tenancy is in `arranging` status. 
So we should use the `related` contacts of the applicant?

**Comment by plittlewood-rpt** [comment]
@raymond2323 this ticket actually altered that behaviour so if the status is arranging they should actually be listed in the `related` collection on the tenancy. Is this not happening?

**Comment by raymond2323** [comment]
@raymond2323 we use it for other states as well including offerPending

**Comment by raymond2323** [comment]
Would we still use the related collection of the Tenancy for this or use the Applicant ID route?

**Comment by plittlewood-rpt** [comment]
You can use either, we updated the tenancies API as part of this ticket to return the related contacts regardless of the status to save the extra call

**Comment by raymond2323** [comment]
@plittlewood-rpt we aren't able to see anything in the related collection. For example, this tenancy (production) NEL220839 which has arranging tenancy status.

I am conscious this might not be a private chat, so I have not shared the response, but if you want me to please let me know what I can do.

**Comment by raymond2323** [comment]
@plittlewood-rpt This appears to be happening on all Tenancy request responses. Please advise if we are doing something wrong here. Thanks.

**Comment by plittlewood-rpt** [comment]
@raymond2323 please can you let me know of the ID of the customer concerned? Thanks

**Comment by raymond2323** [comment]
@plittlewood-rpt JOR

**Comment by plittlewood-rpt** [comment]
Hi @raymond2323 I've just checked this tenancy in the API and the related collection is populated with a single tenant as I would expect looking at the AgencyCloud data. Can you email the response you're getting to [sinfo@reapitfoundations.zendesk.com](mailto:sinfo@reapitfoundations.zendesk.com) for my attention? It sounds like you're looking at stale data

**Comment by raymond2323** [comment]
@plittlewood-rpt i have just sent you the response via email where you can see the empty related response. Let me know what we are doing wrong.

**Comment by plittlewood-rpt** [comment]
Issue highlighted when tenancy is in offer state and fix in PR

**Comment by plittlewood-rpt** [comment]
This is now be resolved. I have responded via Zendesk. Thanks
