### ISSUE TITLE
Do BYM receive Lost MA Date field

### ISSUE THREAD

**Issue by BYMIntegrations** [reapit/foundations#7605]
Please take a look at our FAQ's before submitting an issue, as your question may already be covered in the documentation https://foundations-documentation.reapit.cloud/faqs

**Summary**
Hello, I was just confirming If we receive the Lost MA Date field under the property record for the instance dafyddhardy.briefyourmarket.com. If so need to raise a ticket with our Development team.
**Detail and or supporting links and screenshots**
![image](https://user-images.githubusercontent.com/102583061/187720227-f1babdc1-4da6-47d4-8083-22b0388d1033.png)

**Comment by plittlewood-rpt** [comment]
Hi @BYMIntegrations - as per the Swagger documentation this is available in the response from the properties endpoint in the `lostInstructionDate` and `lostInstructionNote` fields. Thanks
