### ISSUE TITLE
Works Order Extras Fields

### ISSUE THREAD

**Issue by otrace** [reapit/foundations#7611]
Is your feature request related to a problem? Please describe.

- As part of the Savills Migration Project, a Foundations App is being built to replace the existing AC Works Order screen
- An approvals process will be built into the app, allowing management of works orders valued over certain amounts
- The app needs to be able to pass the approvals data back into Agency Cloud, to display as columns in Power Reports and act as additional reporting criteria
- In order to pass data back into AC, we need four additional fields exposed within extras of the Works Order end point. This will allow the app developers to read and write data back to AC and facilitate the Power Reporting requirement above

Describe the solution you'd like

The below four fields exposed in extras of the Works Orders end point:

WorkHead.Extra		-	Type

gwApprovalRequired	-	Boolean
gwApproved			-	Boolean
gwApprovedDate		-	DateTime
gwApprovedNeg		-	String

Describe alternatives you've considered

None, as this was the best option we could think of. Happy to be advised if there is a more suitable option

Additional context

Likely that the app will contain two buttons:

Button 1: Approval Required
Button 2: Approved (Recording the User and DateTime stamp)

**Comment by plittlewood-rpt** [comment]
We need to look at the works order approval process in agencycloud which looks like it may have configuration tied to it somehow.

**Comment by plittlewood-rpt** [comment]
Closing on the basis of internal discussions as this is not an appropriate solution for the requirements
