### ISSUE TITLE
Soap API: Virtual tour data coming through to propertyUrl fields

### ISSUE THREAD

**Issue by adamjamesevans** [reapit/foundations#7612]
**Describe the bug**
For our mutual client, we are receiving Virtual tour data inside the PropertyUrl field. Effects all properties where the virtual tour is used. Client has shown that they are entering the data into the correct place in the CRM as shown in the screenshots. 

**To Reproduce**
Have included screenshots to show what we are receiving in the Soap API. 

**Expected behaviour**
We expect the virtual tour data to come through to the "videourl1" fields. 

**Screenshots**
![image002](https://user-images.githubusercontent.com/793018/187895113-db62895f-1482-43d1-b0a9-978ca8378e6e.png)
![attachment-2](https://user-images.githubusercontent.com/793018/187895115-3716c894-dc37-426b-ac14-12a399f33fe4.png)
![Screenshot_20220826_130748-1](https://user-images.githubusercontent.com/793018/187895116-5dc6378d-d6ac-4ab4-a346-e235026ee795.png)

**Comment by plittlewood-rpt** [comment]
Hi @adamjamesevans this project is for Reapit Foundations only. For support with the legacy SOAP services you will need to contact our support team. Thanks

**Comment by adamjamesevans** [comment]
When I called support, they directed me to the foundations API support team email. When I emailed, they said to log it here. Can you direct me to the correct place or who to contact please.

**Comment by plittlewood-rpt** [comment]
Hi @adamjamesevans  thanks and apologies you're being sent between departments. Your first screenshot seems to be from the Swagger specification for the Foundations API not the SOAP API. Are you therefore saying there's in issue with how the data is appearing in the Foundations API? If so can you let me know the code of the customer you are acting on behalf of?

**Comment by adamjamesevans** [comment]
@plittlewood-rpt No worries, it's defo the soap api for this client we are using. 

I included the client in my last email to the foundations email but I don't have their code. Shall email the zendesk email the details for reference. There was no reference to foundations or Soap in the reply with the swagger screengrab I was sent so excuse the confusion.

Is it just the normal support channel of 0345 330 2965 to go via? I don't have access to the client customer portal to log through there.

**Comment by plittlewood-rpt** [comment]
Hi @adamjamesevans - I've just spoken to the Software Support Manager. The best thing to do is go to https://www.reapit.com/contact-us/ and click "Log a Ticket" - you'll have the option to create an account. If you let me have the reference once you've logged it I'll pass it on to the management team so we can try and expedite it getting where it needs to go.

**Comment by adamjamesevans** [comment]
@plittlewood-rpt Managed to get a workround for the video tour on our end, basically accepting the data in a different unexpected field however more issues have arisen so have finally logged the ticket with support as you suggested. Ticket number is RSD-206287. 

Thanks. 

Unsure if this ticket needs to be kept open now so feel free to close if that is the case.

**Comment by plittlewood-rpt** [comment]
Hi Adam. Thanks - I'll close this down now it's with the right department. Cheers
