### ISSUE TITLE
Tenancy extra fields

### ISSUE THREAD

**Issue by rushikesh-obx** [reapit/foundations#7628]
**Is your feature request related to a problem? Please describe.**

The tenant onboarding app needs to be able to pass data back into Agency Cloud.
In order to pass data back into Agency Cloud, we need additional fields exposed within tenancy end point. This will allow the app developers to read and write data back to Agency Cloud

**Describe the solution you'd like**

below fields exposed in tenancy end point:

    1. Is holding deposit shared equally between all tenants or paid by only lead tenant - Boolean
    2. tenancyAgreement - document/file
    3. rentPaidTo - possible values landlord/agent
    4. tenancyDepositScheme - string
    5. depositProtectionCertificate - document/file
 
**Describe alternatives you've considered**
No.

**Comment by plittlewood-rpt** [comment]
Some of this is already available. I will respond with further information in due course.

**Comment by plittlewood-rpt** [comment]
Hi @rushikesh-obx 

To answer your queries above:

1. Is holding deposit shared equally between all tenants or paid by only lead tenant - Boolean
AgencyCloud does not store this information so you would need to use metadata to store it if it was something you needed to do

2. tenancyAgreement - document/file
This will be stored by the agent as a document against the tenancy. The filename etc is completely up to the agent so there's no 'standard' filename you can look for. To access documents associated to a tenancy call `GET /documents?associatedType=tenancy&associatedId=XXX123456` where XXX123456 is the id of the tenancy you are interested in

3. rentPaidTo - possible values landlord/agent
There is no such field in AgencyCloud to denote who the rent is paid to, however you can infer this from the `agentRole` property returned in the `TenancyModel` returned from `GET /tenancies` and `GET /tenancies/{id}`

4. tenancyDepositScheme - string
This information is already available in the `TenancyModel` returned from `GET /tenancies` and `GET /tenancies/{id}`. Please refer to the [documentation ](https://developers.reapit.cloud/swagger) for more details

5. depositProtectionCertificate - document/file
As point 2, this will be stored by the agent as a document against the tenancy if they choose to store it. Access it in the same way as noted above passing `associatedType` as `depositCertificate` - it is worth noting that not all agents will have the option to store the certificate in this manner and some agents _may_  just store the certificate against the tenancy directly. 

Based on the above I don't believe there is any action required here, but if you can review and come back to me before I close the item I'd be grateful. Thanks

**Comment by rushikesh-obx** [comment]
Hello @plittlewood-rpt ,

It appears that we have everything required. Thank you

**Comment by plittlewood-rpt** [comment]
Thanks for confirming. I'll close the ticket
