### ISSUE TITLE
Renewal Negotiation Checks

### ISSUE THREAD

**Issue by otrace** [reapit/foundations#7629]
**Is your feature request related to a problem? Please describe.**
Savills are building a Renewals Negotiation Application as part of their Lettings Migration project. This application will replace elements of the AC core Renewal Negotiation Screen.

One of the elements they are looking to replace is based on the recent update made to Renewals Checks (see link to confluence article below).

https://reapit.atlassian.net/wiki/spaces/RW/pages/1821966465/Standard+format+checklist+available+for+renewal+negotiation+checks+-+configuration+option

**Describe the solution you'd like**
Foundations End Point for the new Renewal Checks Option to allow the app to read and write data back to the AC Database

**Describe alternatives you've considered**
None as this is new AC Functionality

**Additional context**
See confluence article

**Specification**
Project: Reapit.Services.Tenancies
- Add new endpoints:
  - `GET /tenancies/{id}/renewalNegotiations/checks`
  - `GET /tenancies/{id}/renewalNegotiations/checks/{checkId}`
  - `POST /tenancies/{id}/renewalNegotiations/checks/`
  - `PATCH /tenancies/{id}/renewalNegotiations/checks/{checkId}`
  - `DELETE /tenancies/{id}/renewalNegotiations/checks/{checkId}`
- New endpoints to operate in the same way the tenancy checks endpoint work, operating on src records with a type of `RC` (Renewal Check)
- Entities get stored in TENCHK in the same manner as normal tenancy checks
- Advertise metadata support in the respective models (like we do with normal tenancy checks)

This ticket should be followed by #7853 BEFORE being released to production (they should both go out together)

**Comment by plittlewood-rpt** [comment]
HI @otrace - I have assigned this to the tenancy renewals/extensions milestone. Ultimately until that work is done this isn't something we'd be able to move on as without the renewal you can't have the associated checks

**Comment by plittlewood-rpt** [comment]
Requires #7708 and #7709 to be completed

**Comment by plittlewood-rpt** [comment]
Work to introduce renewalNegotiations endpoint is nearing completion so this can be spec'd out
