### ISSUE TITLE
Company filtering by Offices - Fixflo

### ISSUE THREAD

**Issue by NorbiSamu** [reapit/foundations#7631]
We are looking to create a way for a client to segment their Companies (Contractors) between their Offices in Fixflo, as we do for other entities (Properties, Occupiers etc.) - they create a Relationship between the Office and the Company, which is what we should use to decide which Companies should sync into Fixflo as Contractors.

We are struggling to find a way to access these Relationships in your API - the obvious place we were looking is the GET companies/id/relationships EP, but we are not seeing any relationships there.

Is there a way for us to filter for Offices related to a Company using your API at the moment?

**Specification**
- Project: Reapit.Services.Companies
- Added support for `officeIds` and `negotiatorIds` in the same way it is implemented in the contacts service. Ensure the behaviour to put the primary office/negotiator as the first array item is retained.
- Filtering support should also be included on the `GET` endpoint, again in the same way it is implemented in the contacts service
- This should be read-only data for now to limit the scope of what is required here

**Comment by AshDeeming** [comment]
Hi @NorbiSamu 
Please could you clarify with more details - Offices are generally used to segments our Customers branches. 

Does this relate to a specific client that is structed differently?

**Comment by NorbiSamu** [comment]
Hi @AshDeeming - sure! 

Our understanding is that Offices are used to segment the entities of Branches (Properties, Landlords, etc.) - we are using the office codes + office groups on our end to pull in only those specific entities to a Fixflo Agency. Eg. in the case of Lomond, we have various Agencies set up for them, but they use one Reapit system - using these office codes, we can sync the correct data to the correct Agency.

They have recently raised that they assign Offices to Companies as well - in a screenshot, I can see that this is done in the 'Contact details ' -> 'Negotiators / Offices' section.

We don't have this same section in our test Reapit system and we're also unable to find these relationships in the API docs provided to us.

Hopefully this makes sense?

Many thanks,

Norbert

**Comment by NorbiSamu** [comment]
Hi @AshDeeming - please see the screenshot below in your UI for what we would need in the Companies API. The offices selected in the right-hand side are added in the 'Negotiators / Offices' tab by the client. They only want to sync the Company to the corresponding Agencies (segmented by office group codes) in Fixflo.

OfficeIDs and/or Office Group codes would be best - apologies for not being able to be too specific here, our Reapit test system doesn't have the offices feature so the only way I can see this is via a call with our mutual client Lomond Group - they are the ones who asked for this functionality.

Please let me know if this makes sense.

![wdafdawfawf](https://user-images.githubusercontent.com/112699246/188841479-426d8974-84f2-4ee4-ab1f-c1020c582f59.png)
