### ISSUE TITLE
Missing features from test system - Fixflo

### ISSUE THREAD

**Issue by NorbiSamu** [reapit/foundations#7632]
Hi Reapit team,

We have encountered a few times that our test system is not up-to-date / lacks some features that clients have access to. The 3 that come to mind are Property Manager Relationships to Properties, Invoices section and Office Codes + Office Groups. Is there a possibility for us to have access to the latest version of Reapit / these features turned on for us?

Thanks,

Norbert Samu - Product Manager - Fixflo

**Comment by NorbiSamu** [comment]
We have also discovered that our current system doesn't have the 'Certificate type = CO Detectors' as shown here by a client:

![IMG_4279](https://user-images.githubusercontent.com/112699246/189351974-cc8055a9-4cf1-4003-9289-e13a9b6c0b9d.png)

Ours only has the following:

![image](https://user-images.githubusercontent.com/112699246/189352014-77ebb2a6-c9f9-408f-ba86-9790bda1dc4b.png)

Missing features like these makes it more difficult for us to build comprehensive feature to our integration, anticipate client requests and test any changes we make on the back of those.

**Comment by HollyJoyPhillips** [comment]
It is important to be aware, that the Developer Edition of Agency Cloud is designed to be customer agnostic to make it easier for multiple external developers to work with the CRM across different customers. Adding custom configurations and enabling features that aren’t available to all customers can cause issues. Custom config (out of the standard core fields) will differ per customer. 

For example, I have added 'CO Detectors' which has an ID of ‘CD’. However, it may be setup with a different ID for another customers. Therefore, we provide the configurations endpoint, specially related to certificates ‘/configuration/certificateTypes’ which should be used for mapping certain types for a specific customer. 

I have enabled the property management relationship feature. 

Please could you elaborate on ‘Office Codes + Office Groups’ & 'Invoices' please as I am unsure what you are referring too?

**Comment by NorbiSamu** [comment]
Hi Holly,

Thank you so much for turning on these features - much appreciated - and for clarifying why they were missing before.

Regarding invoices, I have received a response on https://github.com/reapit/foundations/issues/7633 that you don't expose accounts data in your API, hence why it's missing from the Developer Edition. This makes sense.

What I meant by Office Codes + Office Groups (apologies if my terminology is off here) is eg. in Lomond's system, they are able to segment their Reapit data into branches using offices and group those offices using office groups (?) - we then use the id of these groups to segment their data in Fixflo. Is there any chance we could have access to a similar feature set so that we can test our changes? - related to https://github.com/reapit/foundations/issues/7631

Many thanks for your help again!

**Comment by HollyJoyPhillips** [comment]
Hi @NorbiSamu Thank you for clarifying. I'm checking with the team to see if this is possible. I'll come back to you as soon as possible. Thanks.

**Comment by HollyJoyPhillips** [comment]
Hi @NorbiSamu Unfortunately, due to the shared environment and the unique account setup for the Developer Edition, it's not currently possible to create office groups within the sandbox environment. 

We did put together the following documentation that outlines what office grouping is and how it works within the Platform API, which may help https://foundations-documentation.reapit.cloud/faqs#what-are-office-groups

Failing that I'm happy to assist if you have any questions regards office groups.

**Comment by NorbiSamu** [comment]
@HollyJoyPhillips thank you for your help and for sending through the documentation!
