### ISSUE TITLE
Perry Bishop - what seller loves data field 

### ISSUE THREAD

**Issue by MarkFieldhouse** [reapit/foundations#7640]
@plittlewood-rpt @AshDeeming

Hi Guys,

We have taken a extract of a property - [https://www.perrybishop.co.uk/property/FAR220259/] please see below; But we can't see anywhere in the data dump from swagger/ grapql where the 'what seller love' appears within the api? Can you please highlight within the code where this data field can be found? I have also attached screenshots below of the What seller loves data field looks like in Reapit.

____

Data removed by AD

Request for semi structured data for Customer: PBA

ExtraDescription fields

**Comment by MarkFieldhouse** [comment]
@AshDeeming can you come back to me on this point please?

**Comment by AshDeeming** [comment]
Hi @MarkFieldhouse 
This ticket has been updated & associated to the relevant team to review when possible - NB, this is a 'Semi-structured 'extras' field request'

Please see more information in the docs here: 
https://foundations-documentation.reapit.cloud/dev-requests 
https://foundations-documentation.reapit.cloud/dev-requests#columns-definitions

**Comment by MarkFieldhouse** [comment]
@AshDeeming When can we expect a response about semi structured data for extra description fields?

**Comment by MarkFieldhouse** [comment]
@plittlewood-rpt Hello, are you able to provide me an update on my last comment please?

**Comment by HollyJoyPhillips** [comment]
Hi @MarkFieldhouse The field is now available and can be returned using the additional query param &extrasfield=pwhat

**Comment by MarkFieldhouse** [comment]
@HollyJoyPhillips can you send me an example property with property id that we can see the query parameter for extra descriptions what seller loves text.

**Comment by HollyJoyPhillips** [comment]
Hi @MarkFieldhouse 

Property: FAR220259 
So the query would be https://platform.reapit.cloud/properties/FAR220259?extrasfield=pWhat

**Comment by MarkFieldhouse** [comment]
Is Perry bishop able to associate the name of the seller and branch with the 'what seller loves' extra descriptions data field?

**Comment by plittlewood-rpt** [comment]
Hi @MarkFieldhouse the `What Seller Loves` field is a free text description field. We do not dictate how the agent decide to use it so any queries about it's use would need to be forwarded to the agent themselves. The property itself is the thing that would be associated to a particular seller (contact) and branch
