### ISSUE TITLE
Determining the main office for a property

### ISSUE THREAD

**Issue by adam-hf** [reapit/foundations#7647]
Hello,

In the 'Relationships' section for a property in AgencyCloud it indicates there is a 'Main Office' (see attached screenshots), however the property data received from the Foundations REST API can include multiple office IDs in the `officeIds` field (examples of properties with multiple offices for client GTH would be TAU220591, ILM220184, HON220174, NEW220121). How can you determine which is the main office from this? Is it the first in the array?

Many thanks.

![HON220174](https://user-images.githubusercontent.com/110461568/188657070-e7d731a7-0557-4b03-b9b7-1aaf934bfe7c.png)
![ILM220184](https://user-images.githubusercontent.com/110461568/188657076-b7525b41-feb4-481d-aa25-0151979d9c84.png)

**Comment by AshDeeming** [comment]
Hi @adam-hf 
That's correct, the main office will be first in the return
