### ISSUE TITLE
Correct listing photo ordering

### ISSUE THREAD

**Issue by NickStallman** [reapit/foundations#7648]
We've had a report that we are sorting listing photos incorrectly, and we are getting conflicting/confusing information.

```
"images" => array:18 [
      0 => array:11 [
        "id" => "BDF140024_26.jpg"
        "created" => "2016-11-22T09:25:00Z"
        "modified" => "2016-11-22T09:25:24Z"
        "propertyId" => "BDF140024"
        "url" => "https://assets.reapit.net/rod/live/pictures/BDF/14/BDF140024_26.jpg"
        "caption" => "Side Of Property"
        "type" => "photograph"
        "order" => 2
      ]
      1 => array:11 [
        "id" => "BDF140024_25.jpg"
        "created" => "2016-11-20T16:16:20Z"
        "modified" => "2016-11-20T16:16:35Z"
        "propertyId" => "BDF140024"
        "url" => "https://assets.reapit.net/rod/live/pictures/BDF/14/BDF140024_25.jpg"
        "caption" => "Front Of Property"
        "type" => "photograph"
        "order" => 1
      ]
```
Currnetly we sort the photos by the "order" field which makes sense.

Apparently instead we should be using the array index for ordering?
And the "featuredImageUrl" should always be the first photo? That field is not directly usable by us since it lacks the metadata that regular photos have. Or will that url always be guarenteed to match a regular photo's url in which case we could integrate it with the sorting function.

What's the correct behaviour? What order is used when exporting to websites/portals?
If the "order" field isn't the correct photo order, then what is that for exactly?

Thanks

**Comment by plittlewood-rpt** [comment]
Hi @NickStallman there was a bug in AgencyCloud that was fixed fairly recently where the image order didn't always update correctly. Judging from the dates on the examples given it's likely this particular data was affected by the bug. If this is indeed the case, the user just needs to make an adjustment to the image order and then revert the change to resolve the issue. Can you ask the user you are speaking to to try this on the property above and confirm if it does indeed resolve the problem, please?

**Comment by HollyJoyPhillips** [comment]
Hi @NickStallman Please can you confirm if this has resolved your issue before we close this ticket?

**Comment by NickStallman** [comment]
I believe this has been resolved.
