### ISSUE TITLE
FluxPro

### ISSUE THREAD

**Issue by eanno71** [reapit/foundations#7649]
**Request**

In order for us to grant access to Semi-structured 'extras' field data, please provide the following information in this request:

- The name of the customer you represent - Humberts (HUM) plus others likely to required content from these fields
- The name of every field you need surfaced (if known) - 'Directions', 'Surrounding Areas' (can we also include 'Situation' and 'Ground & Garden' too?)
- A screenshot of of the field(s) you require in the agency cloud user interface - see attached from client (Duncan Ley) to us
- A short use case as to why you require this data - A majority of Agents that are either trialling with us or in discussion have observed that the content that would be in these fields is not present in our artwork templates and have indicated that they would this data in the property brochures.
![thumbnail_Untitled](https://user-images.githubusercontent.com/31958757/188796944-d2a7d519-2411-460d-bf64-578a39dfdea2.png)

**Comment by HollyJoyPhillips** [comment]
Hi @eanno71, the following fields are now available for HUM only: 

Directions: pDirections
Surrounding Area: pSurrounds
Situation: pSituation
Ground and Garden: pGarden

The data is stored in a separate table (extras) as semi structured fields and is unique to HUM. If these fields are required for another organisation, you will need to raise a request for that too. 

To obtain the information you simply add the parameter of ?extrasfield=FIELDNAME 

For example for directions: https://platform.reapit.cloud/properties/ABC00000?extrasfield=pDirections

Thanks
Holly
