### ISSUE TITLE
Add support for agent role to be used as a parameter for querying properties

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#765]
### Overview
We should add `agentRole` to GET /properties so that it is possible to identify properties by the agents role in a lettings capacity. 

- Add `agentRole` as a query string. Support array.
- Must be one of the acceptable values for `agentRole` (managed/rentCollection/collectFirstPayment/collectRentToDate/lettingOnly/introducingTenant)

**Comment by plittlewood-rpt** [comment]
PR 1179 opened
