### ISSUE TITLE
Add new Webhook Topic to track Sale Board Field Changes

### ISSUE THREAD

**Issue by azura-mg** [reapit/foundations#7656]
**Is your feature request related to a problem? Please describe.**
We've implemented an integration which is making use of the Sale Board fields on a Property, under Property > Marketing Details. We're making use of the fields `boardStatus`, `boardNotes` and `boardUpdated` fields that are provided by the API. 
Due to the current granularity of webhooks, we can only get this data by listening to requests on `properties.created` and `properties.modified`. This results in us getting a lot of webhooks which we don't need, since they don't modify the data that we are wanting to monitor. This is also resulting in additional costs due to the charge for each webhook.

**Describe the solution you'd like**
We would like the creation of a more granular webhook which triggers when any of the Sale Board fields change, similar to how the `properties.sales.*` webhooks work.

**Describe alternatives you've considered**
There is no way for us to get the data more efficiently.

**Additional context**
![Marketing Details](https://user-images.githubusercontent.com/86250891/188858011-a7d495b7-e74d-4541-9507-e2bd89020635.png)
The fields in question are the Sale Board ones in the top left.

**Comment by plittlewood-rpt** [comment]
Hi @azura-mg, we have been talking about #4289 today with a view to completing that work in the fairly near term (1-4months). This will allow you to set up your own event filters, removing the need for us to provide specific granular topics

**Comment by plittlewood-rpt** [comment]
Closing as this is covered by #4289
