### ISSUE TITLE
Agency cloud referral button

### ISSUE THREAD

**Issue by Filip5991** [reapit/foundations#7658]
Hello, 

We were informed that a referral button inside the agency cloud is now available, and it allows partners to replace workflows within the agency cloud. (Released with the latest version).

I'm guessing that's related to ticket #7396 ?

If it was released, and we want to incorporate it in our app integration, I was wondering what the next steps are, and if the usage of this button is documented somewhere? (I was following the 'What's new on Foundations' emails, but couldn't find anything there)

We were advised it's probably best to open a ticket here and ask, so that's the main purpose of this 'question'. Any help or advice would be greatly appreciated :-)

**Comment by HollyJoyPhillips** [comment]
Hi @Filip5991 There are 2 parts for desktop integration types, one to make it available in AgencyCloud and other to make it available in the platform. Both parts have been completed but it won't be available until we do an upgrade for the Developer Edition (scheduled for monday). The referral type should be included, however, we have detected a slight issue so it's possible that whilst the Diary type will be available, there maybe a slight delay with the referral type. 

I'm talking with the Desktop team and will update you where possible.

**Comment by Filip5991** [comment]
Hi @HollyJoyPhillips ,
Thank you for the detailed response :-)

I was wondering if there is any documentation available so we can start planning what's required to be done our-side?

Is this link the right place to start at?
https://foundations-documentation.reapit.cloud/api/desktop-api#diary

**Comment by HollyJoyPhillips** [comment]
Hi @Filip5991 Yes, that documentation should be sufficient to work with. I'll keep you posted on the upgrade and the status of the referral type.

**Comment by HollyJoyPhillips** [comment]
Internal ticket raised (PBI-4045) to address refinements required before releasing the referral type @Filip5991 FYI.

**Comment by Filip5991** [comment]
Hi @HollyJoyPhillips ,

We're aware this is progressing internally but could you give us an update as to where things stand currently and what the new estimated timescale is for the full release? (I'm asking as we have a large number of mutual clients who are in need of a fix to the problem outlined previously and we are hoping what's being released here will offer a solution.)

**Comment by HollyJoyPhillips** [comment]
Hi @Filip5991 The desktop team have updated the ticket to be included in refinement at the end of October. However, there is something that I might be able to do to help in the interim. It might be worth us setting up a demo so I can show you how it will work which may allow you to continue development whilst the work is being completed. 

I'll reach out to you via email to set up a meeting.

**Comment by HollyJoyPhillips** [comment]
Closing this ticket as we discussed the referral integration type is not part of your requirements.
