### ISSUE TITLE
Quick question of sandbox environment

### ISSUE THREAD

**Issue by andortamas** [reapit/foundations#7659]
Hi,

Re the #7576 issue, can you confirm how we can test our app in the sandbox please? We use an account with SBOX, is this what you mean?

Regards,
Andor

**Comment by AshDeeming** [comment]
Hi @andortamas 
This should now work whilst against sandbox. I'll update you once this is released to prod too. 

If this relates to pre-signed URL downloads, pleas follow; https://github.com/reapit/foundations/issues/7600

**Comment by andortamas** [comment]
Sorry, but it's not clear to us. How we can test here that your changes will work fine with our app? Using sandbox is enough as you do the s3 redirections behind of the scene?

**Comment by plittlewood-rpt** [comment]
Hi @andortamas the redirections happen behind the scenes. If you test your application against sandbox and hit GET /documents/{id}/download you'll find you are now redirected to an S3 location. As long as your file download works, you know it's behaving as it should be. If you can test ASAP and let me know I'd be grateful as we need to get these changes rolled out

**Comment by jwr8385** [comment]
We've tested against the SBOX client ID with no issues found.   Presumably that is the "test against the sandbox" required.   We've not made any changes to handle the redirect - theoretically none required.  The issue was a CORS policy issue which I understand you've now resolved.

**Comment by plittlewood-rpt** [comment]
Thanks that’s correct.the CORS issue is the thing that needed fixing. We will get this released later today. Thank you for confirming
________________________________
