### ISSUE TITLE
Is there any reserved property key in Metadata API?

### ISSUE THREAD

**Issue by abrahamseni** [reapit/foundations#7662]
**Summary**
When using a certain word for a property key, getting it with filter params throws an error

Given this metadata structure:
```json
"metadata": {
  "active": true,
  "type": "subsection",
  "value": "Financial",
  "parentId": "AD"
}
```

I try to GET it with `filter` params like `metadata.type $eq 'subsection'`, but it throws me a `400` error:
```json
{
    "statusCode": 400,
    "dateTime": "2022-09-07T07:49:31.9433475Z",
    "description": "An unexpected error has been encountered when fulfilling this request. This incident has been logged and will be investigated. Please try again."
}
```

But it is fine if I change the property key from `type` to `typeName`.
So far we find the same behaviour with other property key such as `user` and `name`

**Specification**
- Project: Reapit.Services.Metadata
- We already know about some reserved terms however we should check that this list is not missing some items and also ensure that the appropriate validations are being applied when metadata is sent to the Platform
- We should ensure that reserved terms are covered in the documentation
- We should update the metadata service to use parameters when building up the filters which negates the issue with reserved terms. See Expression Attribute Names section [here](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_Query.html)
- It may be that we can catch a specific exception. We could try to run the query as it is and only retag the query properties if it fails

**Comment by plittlewood-rpt** [comment]
Hi @abrahamseni - you can find the list of reserved terms here

https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/ReservedWords.html

I'll look at getting the documentation for Metadata updated to include a link to this information.

**Comment by abrahamseni** [comment]
Thanks for the update @plittlewood-rpt

**Comment by plittlewood-rpt** [comment]
Hi @abrahamseni we have updated the service to deal with reserved keywords correctly. You should still be able to use them so won't need to go back and make changes to your existing apps. Any issues let me know. Thanks
