### ISSUE TITLE
Feature to patch nested object or array data in Metadata API

### ISSUE THREAD

**Issue by abrahamseni** [reapit/foundations#7663]
**Background context**
Given this metadata structure:
```json
"metadata": {
  "description": {
    "someText": "hello"
  }
}
```

If I try to change the `hello` value to `world` with `PATCH` it didn't work.
This is the patch body
```json
[
  {
    "value": "world",
    "path": "/description/someText",
    "op": "replace"
  }
]
```

It give me this error:
```json
{
  "statusCode": 400,
  "dateTime": "2022-09-08T08:39:00.8110878Z",
  "description": "An invalid json patch operation has been request. 'The path segment 'someText' is invalid for an array index.'"
}
```

Please add a feature to patch nested objects or array

**Specification**
- Unknown whether this is a bug or feature request at this stage. Discovery stage needed to understand the issue in more detail

**Comment by plittlewood-rpt** [comment]
Hi @abrahamseni after a lot of fun this should now be functioning as you require. Please let me know if you hit any snags with it. Thanks
