### ISSUE TITLE
Messages received have lower case property ID's

### ISSUE THREAD

**Issue by rochellelevy** [reapit/foundations#7665]
**Describe the bug**
We are receiving messages with a propertyID in lower case and our system rejects the messages. This is intermittent. 

**To Reproduce**
N/A

**Expected behaviour**
PropertyID's should be in upper case

**Screenshots**

Example below: 

`{
    "id": "CND2201583",
    "created": "2022-09-08T13:05:14Z",
    "modified": "2022-09-08T13:05:14Z",
    "start": "2022-09-09T17:00:00Z",
    "end": "2022-09-09T18:00:00Z",
    "typeId": "VW",
    "description": "",
    "recurring": false,
    "recurrence": null,
    "cancelled": false,
    "followUp": {
        "due": "2022-09-10",
        "responseId": "",
        "notes": ""
    },
    "propertyId": "cnd150204",
    "organiserId": "NJRT",
    "negotiatorIds": [
        "NJRT"
    ],
    "officeIds": [
        "CND"
    ],
    "attendee": {
        "id": "CND222174",
        "type": "applicant",
        "contacts": [
            {
                "id": "CND22001922",
                "name": "",
                "homePhone": null,
                "workPhone": null,
                "mobilePhone": "",
                "email": "",
                "fromArchive": false
            }
        ]
    },
    "accompanied": true,
    "virtual": false,
    "negotiatorConfirmed": true,
    "attendeeConfirmed": true,
    "propertyConfirmed": true,
    "fromArchive": false,
    "extrasField": {},
    "_eTag": "\"F673272916E62F15D19838BFF44B2476\"",
    "_links": {
        "self": {
            "href": "/appointments/CND2201583"
        },
        "type": {
            "href": "/configuration/appointmentTypes/VW"
        },
        "organiser": {
            "href": "/negotiators/NJRT"
        },
        "property": {
            "href": "/properties/cnd150204"
        },
        "offices": {
            "href": "/offices/?id=CND"
        },
        "negotiators": {
            "href": "/negotiators/?id=NJRT"
        },
        "attendee": {
            "href": "/applicants/CND2201583"
        }
    },
    "_embedded": null,
    "metadata": {}
}`

**Device (please complete the following information for web issues):**
 N/A

**Additional context**

**Specification**
- Project: Reapit.Services.Appointments
- Due to a bug in AgencyCloud there is a possibility that data will hit the diary table with lowercase ids. As part of the mapping configuration in this service we should force these keys to uppercase to ensure output from Platform APIs remains consistent

**Comment by plittlewood-rpt** [comment]
Hi @rochellelevy this is happening because of the underlying data in the database. I'm trying to see where this data is coming from as the property itself has an uppercase property code. Do you know by any chance how that appointment was added as it doesn't seem to have been done via the Platform APIs. There's records going back quite a long way in this format, but it's definitely intermittent

**Comment by plittlewood-rpt** [comment]
This looks to be a bug in AgencyCloud itself. If you type the property code in lowercase when creating an appointment it is saved in the database in that format. I'll get this logged and let you have the reference. We'll review this anyway as we can look at transforming this data in the APIs regardless as they should be uppercase in all circumstances

**Comment by plittlewood-rpt** [comment]
Internal AC ref: ACB-1619

**Comment by rochellelevy** [comment]
I dont know Pete, I am assuming this was created by the negotiator in their reapit calendar in agency cloud
