### ISSUE TITLE
UK National Trading Standards industry guidance on material information for property listings

### ISSUE THREAD

**Issue by adam-hf** [reapit/foundations#7669]
Hello,

The Foundations REST API contains some of the information needed to comply with the recent UK National Trading Standards industry guidance on material information for property listings. Do you have plans to include any of the the following property data in the Foundations REST API:

- Council tax exemption status
- Number of years left on lease
- Ground rent review period years
- Security deposit
- Tenancy length

https://www.nationaltradingstandards.uk/uploads/Industry%20guidance%20for%20material%20information%20on%20property%20listings%20-%20July%202022.pdf

**Comment by AshDeeming** [comment]
Hi @adam-hf 
Please see the What's New section for more information; 
https://foundations-documentation.reapit.cloud/whats-new#trading-standards-material-information-requirement
