### ISSUE TITLE
Property status: New Instruction removed?

### ISSUE THREAD

**Issue by quigger** [reapit/foundations#7672]
Has the old WebServices NEW INSTRUCTION status been removed.

We used to get NEW INSTRUCTION status for properties when they have been created in the last 14 days.
This property status was sent through WebServices as the status overriding For Sale/To Let.

I can only see these sales and letting status now. Is that correct?

Sales:
preAppraisal/valuation/paidValuation/forSale/forSaleUnavailable/underOffer/underOfferUnavailable/reserved/exchanged/completed/soldExternally/withdrawn

Lettings:
valuation/toLet/toLetUnavailable/underOffer/underOfferUnavailable/arrangingTenancyUnavailable/arrangingTenancy/tenancyCurrentUnavailable/tenancyCurrent/tenancyFinished/tenancyCancelled/sold/letByOtherAgent/letPrivately/provisional/withdrawn

**Comment by AshDeeming** [comment]
Hi @quigger 
That's correct, the Platform API does not include a new instruction status. 

The statuses can be found under the properties Endpoint model (see selling & letting) along with an instructed date;
![image](https://user-images.githubusercontent.com/61687775/189638648-0aa01707-8c06-4521-af6e-690afb95dfe7.png)

**Comment by quigger** [comment]
Thanks.
