### ISSUE TITLE
UK National Trading Standards: full guidance on property attributes

### ISSUE THREAD

**Issue by quigger** [reapit/foundations#7673]
**UK National Trading Standards: full guidance on property attributes**

_Can we have some guidance on matching up the fields we require for NTS vs. the available fields in Foundations?_

We did originally ask this question: https://github.com/reapit/foundations/issues/7669 and were sent this: https://foundations-documentation.reapit.cloud/whats-new#trading-standards-material-information-requirement but it only lists a few fields?

Is there full documentation on all the required NTS fields please?

We have this set of field to map.

Available fields:
- council_tax_band
- council_tax_exempt
- tenure
- number_of_years_on_lease
- annual_service_charge
- annual_ground_rent
- ground_rent_review_period_years
- ground_rent_percentage_increase
- shared_ownership
- shared_ownership_percentage
- shared_ownership_rent
- security_deposit
- tenancy_length

We have tried to match up the Foundations fields to these (please see below).

Foundation attribute - Homeflow attribute

councilTax - council_tax_band
what field? - council_tax_exempt

tenure: type - tenure
what field? - number_of_years_on_lease

what field? - annual_service_charge
groundRent - annual_ground_rent
groundRentReviewDate - ground_rent_review_period_years
groundRentIncrease - ground_rent_percentage_increase

Is this needed: groundRentComment ?

disposal: sharedOwnership (converted to boolean) - shared_ownership
sharedOwnership: sharedPercentage- shared_ownership_percentage
sharedOwnership: rent- shared_ownership_rent

Is this needed: sharedOwnership: rentFrequency

deposit: amount - security_deposit

tenure: expiry - tenancy_length

**Can you help confirm or edit?**

**Comment by AshDeeming** [comment]
Hi @quigger 

Please see the below which should cover the above: 

council_tax_exempt – This is not available in AgencyCloud

number_of_years_on_lease - this isn't stored in AgencyCloud, you may want to review calculating it based on the lease expiry which is a core AgencyCloud field.

annual_service_charge - serviceCharge

groundRentComment - Dependant on a Customer use.

sharedOwnership – Please see the details included in: https://github.com/reapit/foundations/issues/6841

Deposit Data (Type & Amount) available. See: - https://foundations-documentation.reapit.cloud/whats-new#additional-fields

**Comment by AshDeeming** [comment]
Hi @quigger 
I'll close this ticket now - if you have any other questions, please raise a new ticket.
