### ISSUE TITLE
Amendments to Offices Page of SMB App

### ISSUE THREAD

**Issue by AshDeeming** [reapit/foundations#768]
**Summary:** Enhancements and bug fixes required to Offices Page of SMB App to improve UX & some UI

**Location:** https://dev.smb-app.reapit.cloud/Offices

**Task:**

Amendment to the 'Download File' feature – 
- When I select 'download file', it only downloads the first page. (12 records). This should show all Office data.
- 'Office reference' column is not being downloaded
- 'Building name' currently pulling through as code – 'Building name' to be pulled through
 
![image](https://user-images.githubusercontent.com/61687775/78029937-411e2680-7359-11ea-9be2-a78087b2b05f.png)

- Postcode, Telephone & Email in incorrect column format/alignment; Column alignment to be corrected so correct information showing in relevant column.
 
![image](https://user-images.githubusercontent.com/61687775/78030042-690d8a00-7359-11ea-83e5-df98ecdf7987.png)

- After I clicked 'upload file' & clicked Next Page - The below error was shown:
![image](https://user-images.githubusercontent.com/61687775/78030142-8b9fa300-7359-11ea-89cb-dbbdb7bee533.png)

 
- On the Office table, if there is an error on any single row, any additional row(s) should not be editable, allowing error(s) only on one line at a time.
 
![image](https://user-images.githubusercontent.com/61687775/78030264-b7228d80-7359-11ea-8047-5a8ccd4d95b0.png)

- Email column to fit wording within field – Wrap
![image](https://user-images.githubusercontent.com/61687775/78030397-ef29d080-7359-11ea-9958-7ee546ae6131.png)

- Email column – Rename 'Email' to ‘Office Email’

**Comment by phmngocnghia** [comment]
Hi, @AshDeeming 

After verifying the bugs, I found that some of the bugs written above have been fixed. Could you verify it on your side. They are:

- 'Office reference' column is not being downloaded
- 'Building name' currently pulling through as code – 'Building name' to be pulled through
- Postcode, Telephone & Email in incorrect column format/alignment; Column alignment to be corrected so correct information showing in relevant column.

There's a bug that I couldn't verify, I'm not really sure if I replicate it correctly:

> After I clicked 'upload file' & clicked Next Page - The error was shown". 
^ Could you give me the file you are trying to upload and receive the error. Thanks

**Comment by phmngocnghia** [comment]
Hi, @AshDeeming 
I'm unable to reproduce this issue:

> Email column to fit wording within field – Wrap

Could you reproduce it again on your side, and provide me information about your browser? Thanks

**Comment by phmngocnghia** [comment]
@AshDeeming 
Would you like other spreadsheet component to have the same validation behaviour as this one?

`On the Office table, if there is an error on any single row, any additional row(s) should not be editable, allowing error(s) only on one line at a time.`

**Comment by HollyJoyPhillips** [comment]
@phmngocnghia You are correct, the office, building, postcode and email are now showing correctly when downloading the file and the format now looks good. 

With reference to the email wrapping, this is what i see when lading on the offices page: 
![image](https://user-images.githubusercontent.com/52408607/81827091-55486c80-9530-11ea-8cd2-123353429cd1.png)

Yes, i would agree that the validation needs to be applied to both the users and offices table. 

Thanks

**Comment by phmngocnghia** [comment]
Hi @HollyJoyPhillips Would like the down CSV file behaviour of the spreadsheet component on negotiator list page like the one on the office tab page
