### ISSUE TITLE
Review ex Reapit RC/SUMS accounts 

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#7680]
**Relates: ** to SI-17849 / SI-18905

Requires initial review and discussion. 

Linked to #7458

**Comment by plittlewood-rpt** [comment]
Reached out to SI for list of current staff

**Comment by plittlewood-rpt** [comment]
Chased SI as we cannot proceed without this information

**Comment by plittlewood-rpt** [comment]
Accounts have been cleaned. To follow up with @HollyJoyPhillips

**Comment by plittlewood-rpt** [comment]
#7778 logged as a follow up
