### ISSUE TITLE
Make 'Summary Text' available on 'Property'

### ISSUE THREAD

**Issue by stebrough** [reapit/foundations#7681]
**Is your feature request related to a problem? Please describe.**
Out customer would like to push this text on communications from our platform.

**Describe the solution you'd like**
The 'Marketing Details' > 'Summary Text' field added to the Property Object for GET requests.

![Capture](https://user-images.githubusercontent.com/40298446/189677161-ce4c1eed-4595-4c32-a127-9634610bede9.JPG)

**Comment by stebrough** [comment]
Customer details and un-blurred screenshot email to sinfo.

**Comment by HollyJoyPhillips** [comment]
Hi @stebrough This field is already available via the 'extrasFields' request for 'pSummary'. Please can you confirm you can retrieve the information required please? 

More information on semi structured data can be found here https://foundations-documentation.reapit.cloud/faqs#certain-fields-are-not-exposed-by-default-in-the-platform

**Comment by stebrough** [comment]
Thanks Holly,

Have you already given permission to our “Integrated Interest” app for Swoffers?

Steven Brough
Director
[A close up of a logo  Description automatically generated]<https://www.integratedinterest.com/>


Phone: 0114 40 55 777
Web: www.integratedinterest.com<http://www.integratedinterest.com>

27A Tapton Innovation Centre,
Birmingham Road, Chesterfield, S41 0TZ

[signature_1606722053]<https://www.facebook.com/IntegratedInterest/>   [signature_409944761] <https://www.linkedin.com/company/integrated-interest>    [signature_344634568] <https://twitter.com/int_interest>

[A close up of a sign  Description automatically generated]<https://www.integratedinterest.com/post/your-best-practice-guide-to-welcome-campaigns>

The information transmitted in this electronic mail message may contain confidential and or privileged materials.
Integrated Interest is a limited company registered in England and Wales. Registered number: 10378987

**Comment by HollyJoyPhillips** [comment]
Hi @stebrough the access to that field is per customer not per app. If the customer has installed your app and you have permissions to access that endpoint (properties) you'll have access to that field. Thanks.
