### ISSUE TITLE
Retrieve Sale / Purchase Property based on Buyer/Seller ID (Contact Id)

### ISSUE THREAD

**Issue by indysingh** [reapit/foundations#7688]
Please take a look at our FAQ's before submitting an issue, as your question may already be covered in the documentation https://foundations-documentation.reapit.cloud/faqs

**Retrieve Sale / Purchase Property based on Buyer/Seller ID (Contact Id)**

**I am using your APIs for an app development and stuck with a requirement. Can you please help me on how can I retrieve a Property being sold or a Property being purchased based on Buyer and Seller Id(Contact Id) or information? **

Thanks in advance
Indy Singh

**Comment by AshDeeming** [comment]
Hi @indysingh 
It may be beneficial to review our Glossary: https://foundations-documentation.reapit.cloud/platform-glossary

As AgencyCloud is a contact centric software, the Contact record has associated roles such as Applicant (Buyer), Property (to be sold/ Let) Vendor (seller) etc
