### ISSUE TITLE
SBox reapit connect callback question

### ISSUE THREAD

**Issue by unkn0wn-kgb** [reapit/foundations#7701]
***
Regarding to the Login Via Reapit, according to the FAQ's on
[FAQ's - Reapit Foundations](https://foundations-documentation.reapit.cloud/faqs#reapit-connect)

it should return 
Email Address ‘email’
Negotiator ID ‘userCode’
Customer ID ‘clientCode’
Office ID ‘officeId’

However, when we test it on a development account. it only returns below data:
name
email
username ***

We need a customerId from the login user, would you please kindly confirm, how can we get this data on SandBox mode?
some code sample will show as below

-------------------------------------------------------------------------------------------------------------------------------
Code:
request(options, function (error, response) {
          let access_token = 'xxxxxxxxxxxxxxxxxxxxx';
          let options = {
                    'method': 'GET',
                    'url': 'https://connect.reapit.cloud/oauth2/userInfo',
                    'headers': {  'Authorization': `Bearer ${access_token}` }
          };

          request(options, (error, response) =>  {
                    console.log(response.body);
          }); 
});

Response:
{
    "sub": "03b0b4cb-15f4-485b-a68c-35bda2c4a1f6",
    "email_verified": "true",
    "name": "Wing ***",
    "email": "[win***@listinglogic.com](mailto:win***@listinglogic.com)",
    "username": "03b0b4cb-15f4-485b-a68c-35bda2c4a1f6"
}

**Comment by AshDeeming** [comment]
Hi @unkn0wn-kgb 
Please see the below article in our docs, which may be of use, however please revert if still having issues;
https://foundations-documentation.reapit.cloud/faqs#how-do-i-find-out-information-about-a-user

**Comment by HollyJoyPhillips** [comment]
Hi @unkn0wn-kgb For user information you should use the ID Token as outlined in the docs Ash shared above. This is where full information (Neg, Office, Customer ID's etc) will be available.

**Comment by unkn0wn-kgb** [comment]
Hi Holly and Ash,

As you can see our request at the top we believe exactly the same as you have outlined in the documentation

Code:
request(options, function (error, response) {
let access_token = 'xxxxxxxxxxxxxxxxxxxxx';
let options = {
'method': 'GET',
'url': '**https://connect.reapit.cloud/oauth2/userInfo**',
'headers': { 'Authorization': Bearer ${access_token} }
};

      request(options, (error, response) =>  {
                console.log(response.body);
      }); 
});

Response that we get is only partial:
{
"sub": "03b0b4cb-15f4-485b-a68c-35bda2c4a1f6",
"email_verified": "true",
"name": "Wing ***",
"email": "[win***@listinglogic.com](mailto:win***@listinglogic.com)",
"username": "03b0b4cb-15f4-485b-a68c-35bda2c4a1f6"
}

Response that you have in your documentation

![IDtoken](https://user-images.githubusercontent.com/5547896/190262991-cf12aed5-03f8-4047-b58c-f5f4431a2437.png)

As you can see we are getting some fields back but not all.
So we are not getting back **custom:reapit:clientCode** 

Is there is any additional steps do we need to do to get full response oppose to partial?

Thanks

**Comment by unkn0wn-kgb** [comment]
Hi all,

Thanks for your assistance we have worked out the issue, missing step is to perform decoding for the token.
let ids =   JSON.parse(Buffer.from(id_token.split('.')[1], 'base64').toString());

Thanks
