### ISSUE TITLE
Cannot update archived contacts 

### ISSUE THREAD

**Issue by BYMIntegrationsDev1** [reapit/foundations#7710]
When consuming the /contacts/{id} Patch endpoint on the API, we receive a 400 error when trying to update a customers "marketingConsent". This only happens when the customer is archived and the error returned says that archived customers con not be update.

As we deal mainly with archived data it is important to be able to writeback when a customer opts-out of marketing.

In an ideal solution for us would be a new PUT endpoint on /contacts/{id} when the marketingConsent etc. could be updated without the need of the etag.

**Specification**
- Project: Reapit.Services.Contacts
- Build mechanism to allow certain fields to be updated on archived contacts. eTag must still be present, there is no way around this due to the need for ensuring a caller has the most up to date version of a record. A generic mechanism that can be reused elsewhere could be key here (custom attribute on command properties perhaps?)
- Mechanism above should ONLY allow marketingConsent to be changed. Changes to any other fields should not be permitted

**Comment by plittlewood-rpt** [comment]
Hi @BYMIntegrationsDev1 - if we enabled this feature it would not be possible to fire a webhook as archived data is not currently supported on the webhooks pipeline. Would this be a problem for you?

**Comment by BYM-Ricky** [comment]
@plittlewood-rpt no I don't think it would be a problem for us as we aren't using webhooks currently.

**Comment by BYM-Ricky** [comment]
Hi @plittlewood-rpt , noticed this is still pending a response from us. Is there anything else you need apart from the above?

Cheers

**Comment by plittlewood-rpt** [comment]
Apologies - thanks for the chase. Nothing further required from yourselves
