### ISSUE TITLE
Document download not returning any data

### ISSUE THREAD

**Issue by LouisaEvosite** [reapit/foundations#7717]
**Describe the bug**
Trying to download a document through /documents/[id]/download endpoint but is returning an empty string.

**To Reproduce**
Steps to reproduce the behaviour eg:
1. On RER. Example document-  /documents/HCM21000408/download
2. Sending headers: 

```
Array
(
    [type] => get
    [options] => Array
        (
            [64] => 0
            [81] => 0
        )
    [headers] => Array
        (
            [0] => accept: application/octet-stream
            [1] => Content-Type: application/octet-stream
            [2] => Authorization: Bearer **************
            [3] => api-version: 2020-01-31
            [4] => reapit-customer:RER
        )
)

```
Returns the following: 
string(163) "{ "type": "https://tools.ietf.org/html/rfc7231#section-6.5.13", "title": "Unsupported Media Type", "status": 415, "traceId": "|4b214cc-426a3fe3f3b86036." }" 

3. Sending the headers without  [0] => accept: application/octet-stream [1] => Content-Type: application/octet-stream set just returns an empty string

**Expected behaviour**
Document should download. This has previously been working and have been downloading documents successfully.

**Comment by plittlewood-rpt** [comment]
HI @LouisaEvosite - please ensure you configure your client fetch call to follow redirects. Assets are now served directly from S3 for customers hosted on our AWS infrastructure. I've just checked the example above and it is redirecting to the file correctly
