### ISSUE TITLE
Transactions - debit and credit

### ISSUE THREAD

**Issue by LouisaEvosite** [reapit/foundations#7720]
**Is your feature request related to a problem? Please describe.**
We need to see if a transaction is a debit or a credit.

In Repit there are two columns, Debit and Credit which we need:
![image](https://user-images.githubusercontent.com/109209591/190620782-48339de0-90b4-40d4-8de2-41d61a5349b7.png)

**Describe the solution you'd like**
A new value in the response stating either "debit" / "credit" or similar

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Specification**
- Project: Reapit.Services.Transactions
- Add new string property to `TransactionModel` called `transactionType` which will signify whether or not a transaction is a debit or credit transaction. Applicable values are `credit` or `debit`
- Following a discovery exercise with the client accounts team, the value should be inferred based on the following rules:

For the tenant ledger (nomtran.ledger = 'T')
  - When nomtran.drnom = 'debtor' transaction type is ALWAYS debit
  - When nomtran.crnom <> 'debtor' transaction type is ALWAYS debit (crnom accounts are configurable so this logic accounts for that)
  - When nomtran.crnom = 'debtor' and nomtran.type is one of the credit note types, this should be badged as a credit

For the supplier ledger (nomtran.ledger = 'S')
  - When nomtran.drnom = 'crdtor' transaction type is ALWAYS debit
  - When nomtran.crnom <> 'crdtor' transaction type is ALWAYS debit (crnom accounts are configurable so this logic accounts for that)
  - When nomtran.crnom = 'crdtor' and nomtran.type is one of the credit note types, this should be badged as a credit

For the landlord ledger (nomtran.ledger = 'L')
  - When nomtran.drnom = 'lldacc' transaction type is ALWAYS debit
  - When nomtran.crnom <> 'lldacc' transaction type is ALWAYS debit (crnom accounts are configurable so this logic accounts for that)
  - When nomtran.crnom = 'lldacc' and nomtran.type is one of the credit note types, this should be badged as a credit

- In SQL this looks to boil down to something along the lines of the following. The discriminating factor is the ledger and account id (these are fixed and are never changed)

```
CASE
   WHEN nomtran.ledger = 'T' AND nomtran.crnom = 'debtor' AND nomtran.type IN ('CRN', 'CRP', 'CRR', 'CRW', 'CRO', 'CRG') THEN 'credit'
	WHEN nomtran.ledger = 'T' AND nomtran.drnom = 'debtor' THEN 'debit'
   WHEN nomtran.ledger = 'T' AND nomtran.drnom <> 'debtor' THEN 'credit'
   WHEN nomtran.ledger = 'L' AND nomtran.crnom = 'lldacc' AND nomtran.type IN ('CRN', 'CRP', 'CRR', 'CRW', 'CRO', 'CRG') THEN 'credit'
	WHEN nomtran.ledger = 'L' AND nomtran.drnom = 'lldacc' THEN 'debit'
   WHEN nomtran.ledger = 'L' AND nomtran.drnom <> 'lldacc' THEN 'credit'
	WHEN nomtran.ledger = 'S' AND nomtran.crnom = 'crdtor' AND nomtran.type IN ('CRN', 'CRP', 'CRR', 'CRW', 'CRO', 'CRG') THEN 'credit'
	WHEN nomtran.ledger = 'S' AND nomtran.drnom = 'crdtor' THEN 'debit'
   WHEN nomtran.ledger = 'S' AND nomtran.drnom <> 'crdtor' THEN 'credit'
	ELSE 'unknown'
END as transactionType 
```

- I have checked couple of tenancies/landlords/suppliers in a live system running client accounts (speak to PL for examples) and this seems to behave as we need it do, but we should do a bit more due diligence in this area.
- There is an agent ledger but this is not exposed in the transactions API so does not need to be considered here

**Comment by LouisaEvosite** [comment]
Hi Pete, is there any news on this one? Thank you!

**Comment by plittlewood-rpt** [comment]
HI @LouisaEvosite - sorry for the delay in responding to this item. We need some input from our product team on this one as it's not just a simple case of exposing a new field in the database as this information is inferred from various different pieces of the transaction record (account codes etc). We'll catch up with them and come back to you soon.

**Comment by NBareham** [comment]
@plittlewood-rpt Are you able to get hold of the rules you use to infer whether they are debits or credits that you mentioned on 13th December so we could use them in the interim? 

_This information is inferred from various different pieces of the transaction record (account codes etc)._

**Comment by neilpellowe** [comment]
This request forms part of a larger roadmap discovery item to review our current Endpoint offering and any additional areas we may consider opening up. Accounts and related fields will be reviewed as part of this discovery. Once complete, tickets will be updated.

**Comment by LouisaEvosite** [comment]
Would there be a way of seeing the overall balance on the account?
