### ISSUE TITLE
Data Warehouse

### ISSUE THREAD

**Issue by DannySteptoe** [reapit/foundations#7727]
Hoping for access to more data as the current data is very similar to what's available on power reports. 

For example, I cannot report on property inspections due

**Comment by DannySteptoe** [comment]
Hi Pete,

Thanks for the below which is really helpful. The issue I had is that I could not see some of the fields you mention below so therefore didn’t know their name to include them etc. (there is nothing in the schema re inspection dates).

I am also very rusty on this after being a guru on SQL 20 years ago I haven’t really touched it since!

Thanks again

Danny


Danny Steptoe | ACMA | CGMA | MARLA
Finance & Operations Director
​07487 706282       
alexanderandco.co.uk | peterball.co.uk
Lettings | Sales | Property Management | Financial Services | Land & New Homes
Bedfordshire | Buckinghamshire | Gloucestershire | Hertfordshire | Oxfordshire | Northamptonshire
Should this email be received pre-contract, all details within are subject to contract.
​
​This email is confidential and intended solely for the use of the individual to whom it is addressed. If you are not the intended recipient be advised that you have received this email in error and that any use, dissemination, forwarding, printing or copying of this email is strictly prohibited. ​ & Co Group Limited is a limited liability company registered in England and Wales with registration number 07435711 and VAT number 123 3997 07. The registered address is at Pevensey House, 27 Sheep Street, Bicester, Oxfordshire, OX26 6JF. ​Whilst & Co Group Limited have anti-virus protection systems installed, you should carry out your own virus check before opening any attachment. We accept no liability for any loss or damage which may be caused by viruses or interception/interruption of this mail or any attachments.

**Comment by plittlewood-rpt** [comment]
Thanks - we are discussing the possibility of enhancing the documentation around the topic of recreating Power Reports using Analytics Schema data so please watch for updates on that. In the meantime feel free to keep asking questions on here and we'll do our best to help
