### ISSUE TITLE
fromArchive incorrect on Applicant.related contacts

### ISSUE THREAD

**Issue by robchett** [reapit/foundations#7728]
**Describe the bug**
fromArchive data is inconsistant on the related Contacts for an Applicant, one shows true, the other false.

**To Reproduce**
Look at Customer RER
See that /contacts/PRS21003463 is not archived
![image](https://user-images.githubusercontent.com/5231691/190695298-457b560f-6acc-4344-a836-528693d081b4.png)
See that /applicants/PRS212757 shows PRS21003463  as archived.
![image](https://user-images.githubusercontent.com/5231691/190695113-2cb54801-aa29-4ad4-98e2-1b43c5fbdd64.png)

**Expected behaviour**
The contact in the related objects to not be archived

**Specification**
- Project: Reapit.Services.Applicants / Reapit.Services.Vendors
- The ContactLookupConverter is currently using the lookup location to determine whether or not the record is archived which relates to the parent role (eg Applicant) not the contact it is associated with. When setting the `fromArchive` property on the contact in the related collection, it needs to use the location of the contact rather than the lookup. This might need an additional join potentially to determine if the contact is of type `LiveContact` or `ArchivedContact`

**Comment by AshDeeming** [comment]
Hi @robchett 
Although the Applicant is Archived, the Contact remains in place. 

As AgencyCloud has the Contact as the Centric Individual - their associated records can be dealt with separately, i.e. an active Landlord record, an inactive Applicant etc an all be linked to their Contact record. 

In the above example, the Applicant was archived as they became an Active Tenant - see PRS210655

**Comment by robchett** [comment]
Hi Ash,

I can understand why the applicant and contact would have different archived statuses but this is the same contact being shown in different contexts with different statues. When queried directly it is not archived but when shown as a `related` of the applicant it is archived.

**Comment by AshDeeming** [comment]
Thanks @robchett 
I've moved this into the relevant project for review by the team
