### ISSUE TITLE
Brochure Links - Perry Bishop

### ISSUE THREAD

**Issue by MarkFieldhouse** [reapit/foundations#7733]
It seems in Swagger that when we call brochure links via the api we are getting a server 500 error? Please see screenshot below: 

@plittlewood-rpt  - Can you help or advise with this? 

<img width="1268" alt="Screenshot 2022-09-20 at 10 22 51" src="https://user-images.githubusercontent.com/108399838/191220652-6c2f11a8-a3d8-44bb-8493-751ce7a7b8fa.png">

**Specification**
- Documents service is failing to stage files for UK customers from ANZ regional infrastructure. This could be a permissions issue between the two environments. To replicate tunnel to ANZ and try to download a file for Perry Bishop (or any other UK customer)

**Comment by AshDeeming** [comment]
Hi @MarkFieldhouse 
Could you confirm that your profile toggle (https://developers.reapit.cloud/settings/profile) is on the correct dataset for the above request? 
i.e. is using swagger for sandbox, the toggle needs to be on SBOX

**Comment by MarkFieldhouse** [comment]
this is the current setting: @AshDeeming  - we are trying to get the data of live property ( real refId ) so the above condition should be correct? Please confirm. 

<img width="1195" alt="Screenshot 2022-09-20 at 11 59 16" src="https://user-images.githubusercontent.com/108399838/191240871-ef553b4c-153b-4a7f-bd9f-c11479ff5984.png">

**Comment by plittlewood-rpt** [comment]
@MarkFieldhouse I can see an error coming from our infrastructure in Australia so I suspect your app is hosted somewhere in the Asia Pacific region. This problem doesn't seem to be present in our European infrastructure so we will need to take a look into this

**Comment by MarkFieldhouse** [comment]
@plittlewood-rpt any news on this issue with the server 500 error?

**Comment by plittlewood-rpt** [comment]
@MarkFieldhouse this has not been looked at yet but we will post updates here once it has been. Thanks

**Comment by plittlewood-rpt** [comment]
@MarkFieldhouse there isn't going to be a quick solution to this unfortunately - is there a reason you're calling our APIs from so far away from the customer's data? We are looking at our traffic routing policies to route requests to the infrastructure closest to the customer data (rather than closest to the caller which is how it works currently) but there's a fair bit of work involved in that

**Comment by plittlewood-rpt** [comment]
@MarkFieldhouse I have done some work to try and at least alleviate the problem for now. Please can you confirm if you can now access the documents you need? Unfortunately you might find that it is quite slow as the files have to be copied to the infrastructure in the region you're app is closest to which appears to be APAC (so files are being staged in APAC from EU before they can be downloaded). This is something that we will need to live with until we look at the traffic routing changes mentioned above.

**Comment by plittlewood-rpt** [comment]
Thanks - please can you try and download a document from the Sandbox (SBOX) system and see if you get the same error/result?

**Comment by MarkFieldhouse** [comment]
Hello @plittlewood-rpt We checked the sandbox data and its still showing 404 error? 

![image-3](https://user-images.githubusercontent.com/108399838/191774246-f4b35666-2c9c-49a6-9f00-a37eacfea630.png)

**Comment by plittlewood-rpt** [comment]
@MarkFieldhouse good news - this should now be resolved. I managed to speak with our infrastructure team again and have been able to address the issue with permissions between regions. If you can retest with Perry Bishop and let me know I'd be grateful. I've just successfully downloaded some files from their build from the APAC region

**Comment by plittlewood-rpt** [comment]
HI @MarkFieldhouse I can see that you've made a large number of successful file downloads now - can you just confirm all OK so I can close out this item?
