### ISSUE TITLE
Submitting for revew

### ISSUE THREAD

**Issue by LukeKlyant** [reapit/foundations#7745]
Hi,

I am trying to submit an integration for an App but I get the below message.

However, before you can list an app in the AppMarket ('Submit for approval'), you will first need to submit your account information.

I cannot find any where to fill in any account details.  Can you point me in the right direction and also what account details does in refer to,  Bank details to register the app or Logon details for the integration.

Thanks,
Luke

**Comment by AshDeeming** [comment]
Hi @LukeKlyant 
Please could you confirm the company name?

**Comment by LukeKlyant** [comment]
@AshDeeming Klyant Accounts.     www.klyant.com

**Comment by AshDeeming** [comment]
Thanks @LukeKlyant 
I'll refer this to our Partnerships Manager, who should be in touch via your registered email address.
