### ISSUE TITLE
Extras Fields not working

### ISSUE THREAD

**Issue by eanno71** [reapit/foundations#7746]
**Request**

In order for us to grant access to Semi-structured 'extras' field data, please provide the following information in this request:

- The name of the customer you represent = Humberts
- The name of every field you need surfaced (if known) = pDirections, pSurrounds, pSituation, pGarden

We were led to believe that the above fields were made available to the Humberts (HUM) account. We're getting an error when we try to call them. Can you confirm these have been made available?

See original post https://github.com/reapit/foundations/issues/7649

**Comment by HollyJoyPhillips** [comment]
Hi @eanno71 The fields were made available. Can you provide the query and the error you are getting please?

**Comment by eanno71** [comment]
This is the query url :
https://platform.reapit.cloud/properties/<property_id>?extrasfield=pDirections,pSurrounds,pSituation,pGarden
Error we're getting:
[400] - Access to one or more of the specified fields is not permitted. You must be granted access to this data beforehand

Is there any way we can test this as we are having to rely on a potential customer to point out error?

Thanks.

**Comment by HollyJoyPhillips** [comment]
@eanno71 Ok, the query needs to be:
https://platform.reapit.cloud/properties/<property_id>?extrasfield=pDirections&extrasfield=pSurrounds&extrasfield=pSituation&extrasfield=pGarden

I'll update the documentation to make this clearer.

**Comment by eanno71** [comment]
OK thanks,

I'll pass on to Marcin our developer.

--

Ian Mahony

Operations & Design Manager


[cid:1a6fd4b0-7b9f-4d8f-a859-13433fef648f]<https://realmedia.group>


T | 0044 (0)20 3468 7949

W | www.realmedia.group<http://www.realmedia.group/>

--

This e-mail contains information which is confidential and privileged.
If you are not the intended recipient please note that any copying, use,

dissemination or taking any action in reliance on the contents of this

e-mail is prohibited and unlawful. If you have received this e-mail in

error, please return the original message to Real Media Group Holdings Ltd

by e-mail to ***@***.******@***.***>

________________________________

**Comment by HollyJoyPhillips** [comment]
No problem, please reach out if you are still having an issue
