### ISSUE TITLE
Increase refresh time for Snowflake/Snowsight

### ISSUE THREAD

**Issue by tdstirling** [reapit/foundations#7748]
**Background context**
Database refresh in Snowflake/Snowsight is currently 15 minutes behind the Windows application.  Can this be brought much closer to realtime like the old MySQL databases?

**Comment by plittlewood-rpt** [comment]
Hi @tdstirling we can have a look at the options here. Can you confirm which agent you are working on behalf of/at?

**Comment by tdstirling** [comment]
Thanks Pete,
Its Stirling Ackroyd.

**Comment by plittlewood-rpt** [comment]
Hi @tdstirling the fastest we can sync updates through is on a 5 minute interval (this is an external limitation not something we set). I'll increase the frequency of the sync of your data now

**Comment by tdstirling** [comment]
@plittlewood-rpt  Nice one, thanks.
