### ISSUE TITLE
Create a pending approval supplier invoice

### ISSUE THREAD

**Issue by MatthewGoddard** [reapit/foundations#7764]
**Is your feature request related to a problem? Please describe.**
I would like to be able to add a supplier invoice that a property manager can then review.

**Describe the solution you'd like**
A single API end point that I can POST a new supplier invoice to with the status of awaiting approval.

**Describe alternatives you've considered**
Property Managers carry on doing this manually via the New Supplier Invoice screen in Reapit's AgencyCloud product.

**Additional context**
![image](https://user-images.githubusercontent.com/10115484/191812653-12c8e6ea-7c90-4240-8913-ea1e1b902fee.png)

**Specification**
- Note that we may need to iterate over this work and it should **not** be released to production until signed off my client accounts team
- Project: Reapit.Services.Transactions
- New endpoint `POST /supplierInvoice` and required scope `transactions.write` (which may not exist yet)
- Payload:
```
{
  "worksOrderId": "ABC12345676", -- optional
  "propertyId": "AAAAA" -- optional, required when worksOrderId is not provided
  "companyId": "DDD" - optional, required when worksOrderId is not provided
  "tenancyId": "JJJ", --optional
  "description": "abc" -- required
  "accountId": "cleang", -- drnom required
  "invoiceRef": "abc123", -- required
  "negotiatorId": NEG", -- required
  "invoiceDate: "2022-01-01" -- required
  "dueDate": "2022-02-01", -- optional
  "netAmount": 100, -- optional
  "taxAmount": 20, <--- optional, cannot exceed netamount
}
```

**Validations**
- Supplied ids must be validated in all cases to ensure data accuracy
  - When a property id is specified, ensure it exists
  - When a tenancy id is specified, ensure it exists
  - When a property AND tenancyId are provided, ensure that the tenancy is associated to the specified property
  - When a worksOrderId is provided, propertyId/landlordId should be omitted (OR should match the respective ids on the works order)
  - When parentId is passed, ensure this is a valid supplier invoice that is still awaiting authorisation
- Type must be a valid enum value (only one option for this phase of work)
- AccountId must be valid (validate against nomacct table - only accounts where Works Order is selected can be applied to supplier invoices)
- NegotiatorId MUST be provided in all cases (even for server side applications), and must be valid format (2-4 alphanumeric characters)
- When type is `supplierInvoice` (which it always will be for now, but add this validation so we don't forget later), `invoiceRef` and `invoiceDate` must be supplied

**Behaviours**
- Supplier Invoice transactions should ALWAYS go on the supplier ledger (code S) and have an authorisation status of Awaiting Approval (authStat = 'A') - this is the data state that ensures no crossover with lettings accounts processes and causes the invoices to appear in the Invoices Awaiting Approval screen
- Type of `supplierInvoice` to map to `nomtran.type = 'INV'`
- Data stored in nomtran table
- When parentId is not supplied, it should be set to the id of the new nomtran record
- Where propertyId/landlordId are NOT supplied, they should be retrieved from the associated worksOrder and stored against the nomtran entity

**Comment by plittlewood-rpt** [comment]
Desktop team to check over validations

**Comment by plittlewood-rpt** [comment]
PBI-4099 logged internally
