### ISSUE TITLE
Webhook request not receiving 

### ISSUE THREAD

**Issue by gokulngk** [reapit/foundations#7767]
One of our mutual client Kayandco (KYC) has installed our AWS app. But still we are not receiving the webhook request for this client. The test ping is working. But the actual data is not triggering the webhook. Can you please check and update regarding this.

**Comment by plittlewood-rpt** [comment]
Hi @gokulngk this should now be resolved - if you can confirm I'd be grateful

**Comment by plittlewood-rpt** [comment]
Hi @gokulngk - are you now receiving the notifications as expected? Thanks

**Comment by gokulngk** [comment]
Hi @plittlewood-rpt 
Thanks for the reply. We are currently receiving the webhook request as expected.
