### ISSUE TITLE
Parent AreaId on Property API Response

### ISSUE THREAD

**Issue by darren-sudonum** [reapit/foundations#7768]
**Is your feature request related to a problem? Please describe.**
I need to establish the community from the properties API endpoint, currently, the areaId for sub-communities are listed.

**Describe the solution you'd like**
Add a field for community areaId to the GET properties API response.

**Specification**
- Adding additional data to the properties API does not make sense here as it is area configuration data in scope therefore:

- Project: Reapit.Services.Areas
- Spec to be agreed. Options:
  - Add a link to the _links collection to the parent group(s) (where applicable) which will allow you to navigate around to build up a picture of the hierarchical structure
  - Add a parentIds array to the model that is set to the id of the parent group/supergroup which is set for all levels except the most inward level. Be aware that the same area can exist inside multiple groups (

**Comment by AshDeeming** [comment]
Hi @darren-sudonum 
Please can you clarify, with screenshots as I'm unsure of 'sub-communities' in AgencyCloud

**Comment by MatthewGoddard** [comment]
@AshDeeming This is Dubai terminology. In AC, it relates to Location, Groups and Super Groups.
![image](https://user-images.githubusercontent.com/10115484/191973706-906faba1-637b-4df8-8f52-2af4ccf98066.png)

**Comment by AshDeeming** [comment]
Thanks @MatthewGoddard / @darren-sudonum 
Could you confirm which customer this relates to please? 
(If sensitive, please send to: sinfo@reapitfoundations.zendesk.com)

**Comment by plittlewood-rpt** [comment]
Hi @darren-sudonum - we will look at some enhancements to the areas API however this information can be inferred already in the following way. 

- The properties API will return the `areaId` that the property resides in (where it's been set)
- Using data from the areas API, you need to look for results where `type == group` and `area` contains the `areaId` from the properties endpoint. As the data from the areas API doesn't change that frequently with it essentially being configuration data, it's recommended to cache this information locally. 

In terms of enhancements, we'll spec this out later today but the options are likely to be:
- Add a link to the _links collection to the parent group (where applicable) which will allow you to navigate around to build up a picture of the hierarchical structure
- Add a parentId to the model that is set to the id of the parent group/supergroup which is set for all levels except the most inward level.

**Comment by Jennidut** [comment]
@plittlewood-rpt hi, thanks for the update. You mentioned we should review the detail but I can't seem to find the link to the spec?

**Comment by darren-sudonum** [comment]
> This issue has been updated and moved to our ‘Near Term’ column (typically completed within 0 - 4 months). We have assessed the effort required and outlined a technical specification - please take the time to review this detail.

Where/how do I review the detail?

**Comment by plittlewood-rpt** [comment]
Hi Darren

The specification is at the top of the issue. When we refine the issue we edit the original description

Thanks
Pete
________________________________
From: Darren ***@***.***>
Sent: Friday, September 30, 2022 9:59:00 AM
To: reapit/foundations ***@***.***>
Cc: Pete Littlewood ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [reapit/foundations] Parent AreaId on Property API Response (Issue #7768)


External Message - Please be cautious when opening links or attachments in email
________________________________
This issue has been updated and moved to our ‘Near Term’ column (typically completed within 0 - 4 months). We have assessed the effort required and outlined a technical specification - please take the time to review this detail.

Where/how do I review the detail?

**Comment by darren-sudonum** [comment]
Ah thanks.

**Comment by darren-sudonum** [comment]
Morning, I'd just like to clarify this on a more practical level.

> Using data from the areas API, you need to look for results where type == group and area contains the areaId from the properties endpoint.

Seeing as, according to the API documentation, I cannot do a get to areas and pass `type=group` in the query string I also can't do a GET for (parent group) areas  that the contain the `areaId` (that I get from the property).

So you're proposing add `parentId` to the area. So I would: look up the property, look up the aera (from the property's `areaId` and then use the area's `paerentId` as the id of the _community_.

This seems workable, except for: 
> Be aware that the same area can exist inside multiple groups

Are the multiple groups on different hierarchical levels or can an area only ever have one parentId?

**Comment by darren-sudonum** [comment]
Morning, I'd just like to clarify this on a more practical level.

> Using data from the areas API, you need to look for results where type == group and area contains the areaId from the properties endpoint.

Seeing as, according to the API documentation, I cannot do a get to areas and pass `type=group` in the query string I also can't do a GET for (parent group) areas  that the contain the `areaId` (that I get from the property).

So you're proposing add `parentId` to the area. So I would: look up the property, look up the aera (from the property's `areaId` and then use the area's `paerentId` as the id of the _community_.

This seems workable, except for: 
> Be aware that the same area can exist inside multiple groups

Are the multiple groups on different hierarchical levels or can an area only ever have one parentId?

**Comment by darren-sudonum** [comment]
I reopened the issue, oh github-actions... becuase I had trouble seeing my post.
:roll_eyes:

**Comment by MatthewGoddard** [comment]
@darren-sudonum I've already responded to @Jennidut's email on this one. An AreaID can only be a member of one Group.

**Comment by MatthewGoddard** [comment]
> Morning, I'd just like to clarify this on a more practical level.
> 
> > Using data from the areas API, you need to look for results where type == group and area contains the areaId from the properties endpoint.
> 
> Seeing as, according to the API documentation, I cannot do a get to areas and pass `type=group` in the query string I also can't do a GET for (parent group) areas that the contain the `areaId` (that I get from the property).
> 
> So you're proposing add `parentId` to the area. So I would: look up the property, look up the aera (from the property's `areaId` and then use the area's `paerentId` as the id of the _community_.
> 
> This seems workable, except for:
> 
> > Be aware that the same area can exist inside multiple groups
> 
> Are the multiple groups on different hierarchical levels or can an area only ever have one parentId?

@darren-sudonum I've responded to @Jennidut's email on this one last week. An AreaID can only be a member of one Group
