### ISSUE TITLE
merge data warehouse at source

### ISSUE THREAD

**Issue by elizabethhamlin** [reapit/foundations#7771]
I currently pull data from 3 different Reapit systems and have to merge them in power BI. 

Is there any way that these can be merge together at the source before they hit my power BI app so I do not have to keep appending the queries?

**Comment by plittlewood-rpt** [comment]
Hi @elizabethhamlin - which data sources are you merging currently? Thanks

**Comment by elizabethhamlin** [comment]
Hi Pete so I have Lomond Capital Reapit, Michael Jones Reapit and will be getting Julian Wadden Reapit

**Comment by plittlewood-rpt** [comment]
Thanks - so we have a mid term issue #5114 whose aim is to provide a single data warehouse account (single set of credentials) that provides access to multiple organisation's data which I think will do what you require. As it's in the mid term column on the backlog we'd anticipate delivery of this feature in 5-8 months as per our [development processes ](https://foundations-documentation.reapit.cloud/dev-requests#columns-definitions).

**Comment by elizabethhamlin** [comment]
Thanks Pete - fingers crossed it will come sooner :)

**Comment by plittlewood-rpt** [comment]
No problem - I'll close this ticket as it's now linked to the other one.

@HollyJoyPhillips FYI for scheduling
