### ISSUE TITLE
Permission for resthooks

### ISSUE THREAD

**Issue by komalpuri27** [reapit/foundations#7779]
**Summary**
I would like to understand how to get permissions for resthooks.  Our system add webhooks(with desired topics) for the clients that install our app. But we are getting this error.
We never faced this while working with sandbox account.

**Detail and or supporting links and screenshots**
![image](https://user-images.githubusercontent.com/94682169/192226711-93061628-6316-48a4-8ad3-e666f527df82.png)

For the app 'Consumer Portal' created by Endlay. 

Kindly help.

**Comment by HollyJoyPhillips** [comment]
Hi @komalpuri27 Would you mind please trying again with the net customer you onboard and if it's still an issue, send over the payload request and we can take a look?

**Comment by komalpuri27** [comment]
sure sounds good @HollyJoyPhillips
