### ISSUE TITLE
Estate management

### ISSUE THREAD

**Issue by elizabethhamlin** [reapit/foundations#7790]
Hi

Reapit have just released an estate management part of their system and we need to have this added to the data warehouse

**Comment by plittlewood-rpt** [comment]
BA/GTM required

**Comment by craigforrest** [comment]
Hi @elizabethhamlin, I'm currently outlining the requirements for the work required to support estate/ Block management data in Data Warehouse and it would be good to have a chat about what's required when you're available. Could you please email me at cforrest@reapit.com so we can arrange a call when convenient?
