### ISSUE TITLE
Ability to upload files to a specified sub folder via documents endpoint?

### ISSUE THREAD

**Issue by hivetom** [reapit/foundations#7791]
Is it possible to upload a file using the documents endpoint to a specific sub folder of the default location?

**Comment by AshDeeming** [comment]
Hi @hivetom 
Please could you provide more details regarding which sub folders you are referring to?

**Comment by hivetom** [comment]
Hi @AshDeeming 

The client has a folder called 'Draft Reports' and it sits in the letters section of the tenancy.
