### ISSUE TITLE
Webhooks not received from one customer, fine from others

### ISSUE THREAD

**Issue by TobyDunnEPS** [reapit/foundations#7800]
**Describe the bug**
We have multiple customers registered for our app and using webhooks to notify us of updates.  We never receive webhooks for one customer, although they are present in the Subscription Customers section of the Webhook configuration of the app.  The affected customer is Rockett Home Rentals (RHR)

Due to the lack of webhooks we are having to pull from the API every 15 minutes which will increase costs and is taking up time from our admin and support teams.

**To Reproduce**
Alter a property in Reapit for Rockett Home Rentals (RHR), there is no webhook
Alter a property for any other subscribed customer, there is a webhook

**Expected behaviour**
All customers listed in Subscribed Customer should generate webhooks

**Screenshots**
![image](https://user-images.githubusercontent.com/65494260/192841936-4dd771ba-6a5a-472a-a085-3df541ae4b24.png)

Analytics reports webhooks are being generated (~200 in last 7 days) but none are received:
![image](https://user-images.githubusercontent.com/65494260/192843232-962630b3-7408-40f4-8709-10191a774332.png)

**Device (please complete the following information for web issues):**
AWS EC2 running PHP8.1

**Additional context**

**Comment by plittlewood-rpt** [comment]
Hi @TobyDunnEPS - I actually ran the setup mechanism for this customer yesterday so you should be receiving them now. Please can you confirm?

**Comment by TobyDunnEPS** [comment]
Hi Pete,
I can confirm we are now seeing webhooks for for Rockett (RHR) properties in the transaction logs.

Should we expect a delay between a customer installing the app and us starting to see webhooks propagating?  If so, we'll build that delay into our processes and manage expectations of the clients.

All the best,
Toby


Toby Dunn
Head of Development

***@***.******@***.***>
121 Park Lane, Mayfair, London W1K 7AG
epropservices.com<https://www.epropservices.com/>

[cid:epsbar_3e39f08d-3fbb-48b9-9232-8ea2fd950058.jpg]<https://www.epropservices.com/>
[cid:fineandcountry_a87aae4c-7515-46df-aba8-7c2a4252e513.jpg]<https://www.fineandcountry.com/uk>        [cid:theguild_2c988f60-5328-4759-8da3-46e8486be818.jpg] <https://www.guildproperty.co.uk/>      [cid:gogetdigital_251cede1-65aa-4201-bb98-7ce0689c4f5f.jpg] <https://gogetdigital.co.uk/>       [cid:offerhive_2785ed63-a2ca-4984-bcac-6cf90c6ee920.jpg] <https://www.offerhive.co.uk/>         [cid:property_jungle_acb7dc7d-ce18-4463-826e-bf4174c23b62.jpg] <https://www.thepropertyjungle.com/>     [cid:starberry_008e761b-b143-49ed-af01-1b029851e13e.jpg] <https://starberry.tv/>        [cid:leadpro_e974befc-a33f-499f-b7be-3202e926b7a9.jpg] <https://www.lead.pro/>

(c) 2022 eProp Services Ltd: A company registered in England and Wales with registered number 09210707 and registered office 121 Park Lane, Mayfair, London W1K 7AG. All rights reserved. This email is intended for the named recipient only. It may contain privileged and confidential information. If you are not the intended recipient, please notify the sender immediately and destroy this email. You must not copy, distribute or take action in reliance upon it. Whilst all efforts are made to safe-guard emails, eProp Services Ltd cannot guarantee that attachments are virus free or compatible with your systems and does not accept liability in respect of viruses or computer problems experienced. eProp Services Ltd reserves the right to monitor all email communications through its internal and external networks. Any offer or acceptance contained within or implied by this email is made subject to contract. Additionally, where this email message is sent in connection with a contentious issue, the contents are without prejudice.

**Comment by plittlewood-rpt** [comment]
Hi Toby - thanks for confirming. There shouldn't be any need to expect a delay - the webhooks setup process is actually part of a migration from our old infrastructure over to AWS. Sometimes the jobs don't get set up until a few days post-migration which can be the reason for the delay

**Comment by TobyDunnEPS** [comment]
Hi Pete,
In this case we've had a considerable delay - the app was installed on 30th August according to the Foundation UI.  I expect it was a few days later when we requested the webhooks,

Yesterday I removed and re-added RHR in the list of Subscription Customers, which may have triggered the job your side?

Cheers,
Toby


Toby Dunn
Head of Development

***@***.******@***.***>
121 Park Lane, Mayfair, London W1K 7AG
epropservices.com<https://www.epropservices.com/>

[cid:epsbar_3e39f08d-3fbb-48b9-9232-8ea2fd950058.jpg]<https://www.epropservices.com/>
[cid:fineandcountry_a87aae4c-7515-46df-aba8-7c2a4252e513.jpg]<https://www.fineandcountry.com/uk>        [cid:theguild_2c988f60-5328-4759-8da3-46e8486be818.jpg] <https://www.guildproperty.co.uk/>      [cid:gogetdigital_251cede1-65aa-4201-bb98-7ce0689c4f5f.jpg] <https://gogetdigital.co.uk/>       [cid:offerhive_2785ed63-a2ca-4984-bcac-6cf90c6ee920.jpg] <https://www.offerhive.co.uk/>         [cid:property_jungle_acb7dc7d-ce18-4463-826e-bf4174c23b62.jpg] <https://www.thepropertyjungle.com/>     [cid:starberry_008e761b-b143-49ed-af01-1b029851e13e.jpg] <https://starberry.tv/>        [cid:leadpro_e974befc-a33f-499f-b7be-3202e926b7a9.jpg] <https://www.lead.pro/>

(c) 2022 eProp Services Ltd: A company registered in England and Wales with registered number 09210707 and registered office 121 Park Lane, Mayfair, London W1K 7AG. All rights reserved. This email is intended for the named recipient only. It may contain privileged and confidential information. If you are not the intended recipient, please notify the sender immediately and destroy this email. You must not copy, distribute or take action in reliance upon it. Whilst all efforts are made to safe-guard emails, eProp Services Ltd cannot guarantee that attachments are virus free or compatible with your systems and does not accept liability in respect of viruses or computer problems experienced. eProp Services Ltd reserves the right to monitor all email communications through its internal and external networks. Any offer or acceptance contained within or implied by this email is made subject to contract. Additionally, where this email message is sent in connection with a contentious issue, the contents are without prejudice.

**Comment by plittlewood-rpt** [comment]
Hi Toby - it's a manual process which is run by another team - I will speak with them to find out why there was such a delay here and see if we can get to the bottom of it

**Comment by TobyDunnEPS** [comment]
Much appreciated.  If we have similar in future what's the best course of action?

- Remove and re-add to the Webhook Subscribers list
- Mail your team
- All of the above

Thanks,
Toby



Toby Dunn
Head of Development

***@***.******@***.***>
121 Park Lane, Mayfair, London W1K 7AG
epropservices.com<https://www.epropservices.com/>

[cid:epsbar_3e39f08d-3fbb-48b9-9232-8ea2fd950058.jpg]<https://www.epropservices.com/>
[cid:fineandcountry_a87aae4c-7515-46df-aba8-7c2a4252e513.jpg]<https://www.fineandcountry.com/uk>        [cid:theguild_2c988f60-5328-4759-8da3-46e8486be818.jpg] <https://www.guildproperty.co.uk/>      [cid:gogetdigital_251cede1-65aa-4201-bb98-7ce0689c4f5f.jpg] <https://gogetdigital.co.uk/>       [cid:offerhive_2785ed63-a2ca-4984-bcac-6cf90c6ee920.jpg] <https://www.offerhive.co.uk/>         [cid:property_jungle_acb7dc7d-ce18-4463-826e-bf4174c23b62.jpg] <https://www.thepropertyjungle.com/>     [cid:starberry_008e761b-b143-49ed-af01-1b029851e13e.jpg] <https://starberry.tv/>        [cid:leadpro_e974befc-a33f-499f-b7be-3202e926b7a9.jpg] <https://www.lead.pro/>

(c) 2022 eProp Services Ltd: A company registered in England and Wales with registered number 09210707 and registered office 121 Park Lane, Mayfair, London W1K 7AG. All rights reserved. This email is intended for the named recipient only. It may contain privileged and confidential information. If you are not the intended recipient, please notify the sender immediately and destroy this email. You must not copy, distribute or take action in reliance upon it. Whilst all efforts are made to safe-guard emails, eProp Services Ltd cannot guarantee that attachments are virus free or compatible with your systems and does not accept liability in respect of viruses or computer problems experienced. eProp Services Ltd reserves the right to monitor all email communications through its internal and external networks. Any offer or acceptance contained within or implied by this email is made subject to contract. Additionally, where this email message is sent in connection with a contentious issue, the contents are without prejudice.

**Comment by plittlewood-rpt** [comment]
Hi Toby
You can just log a ticket here. Readding the webhook won’t make any difference

Thanks
Pete
________________________________
From: Toby Dunn ***@***.***>
Sent: Thursday, September 29, 2022 5:39:20 PM
To: reapit/foundations ***@***.***>
Cc: Pete Littlewood ***@***.***>; State change ***@***.***>
Subject: [EXTERNAL] Re: [reapit/foundations] Webhooks not received from one customer, fine from others (Issue #7800)


External Message - Please be cautious when opening links or attachments in email
________________________________
Much appreciated. If we have similar in future what's the best course of action?

- Remove and re-add to the Webhook Subscribers list
- Mail your team
- All of the above

Thanks,
Toby



Toby Dunn
Head of Development

***@***.******@***.***>
121 Park Lane, Mayfair, London W1K 7AG
epropservices.com<http://epropservices.com><https://www.epropservices.com/<https://www.epropservices.com/>>

[cid:epsbar_3e39f08d-3fbb-48b9-9232-8ea2fd950058.jpg]<https://www.epropservices.com/<https://www.epropservices.com/>>
[cid:fineandcountry_a87aae4c-7515-46df-aba8-7c2a4252e513.jpg]<https://www.fineandcountry.com/uk<https://www.fineandcountry.com/uk>> [cid:theguild_2c988f60-5328-4759-8da3-46e8486be818.jpg] <https://www.guildproperty.co.uk/<https://www.guildproperty.co.uk/>> [cid:gogetdigital_251cede1-65aa-4201-bb98-7ce0689c4f5f.jpg] <https://gogetdigital.co.uk/<https://gogetdigital.co.uk/>> [cid:offerhive_2785ed63-a2ca-4984-bcac-6cf90c6ee920.jpg] <https://www.offerhive.co.uk/<https://www.offerhive.co.uk/>> [cid:property_jungle_acb7dc7d-ce18-4463-826e-bf4174c23b62.jpg] <https://www.thepropertyjungle.com/<https://www.thepropertyjungle.com/>> [cid:starberry_008e761b-b143-49ed-af01-1b029851e13e.jpg] <https://starberry.tv/<https://starberry.tv/>> [cid:leadpro_e974befc-a33f-499f-b7be-3202e926b7a9.jpg] <https://www.lead.pro/<https://www.lead.pro/>>

(c) 2022 eProp Services Ltd: A company registered in England and Wales with registered number 09210707 and registered office 121 Park Lane, Mayfair, London W1K 7AG. All rights reserved. This email is intended for the named recipient only. It may contain privileged and confidential information. If you are not the intended recipient, please notify the sender immediately and destroy this email. You must not copy, distribute or take action in reliance upon it. Whilst all efforts are made to safe-guard emails, eProp Services Ltd cannot guarantee that attachments are virus free or compatible with your systems and does not accept liability in respect of viruses or computer problems experienced. eProp Services Ltd reserves the right to monitor all email communications through its internal and external networks. Any offer or acceptance contained within or implied by this email is made subject to contract. Additionally, where this email message is sent in connection with a contentious issue, the contents are without prejudice.

**Comment by TobyDunnEPS** [comment]
Hi Pete,
It looks like we've stopped getting webhooks again for RHR, last one was 20th November.  Since then we've had property updates only when we've pulled manually.  Other clients appear unaffected.  Could you check?

Thanks,
Toby


Toby Dunn
Head of Development

***@***.******@***.***>
121 Park Lane, Mayfair, London W1K 7AG
epropservices.com<https://www.epropservices.com/>

[cid:epsbar_3e39f08d-3fbb-48b9-9232-8ea2fd950058.jpg]<https://www.epropservices.com/>
[cid:fineandcountry_a87aae4c-7515-46df-aba8-7c2a4252e513.jpg]<https://www.fineandcountry.com/uk>        [cid:theguild_2c988f60-5328-4759-8da3-46e8486be818.jpg] <https://www.guildproperty.co.uk/>      [cid:gogetdigital_251cede1-65aa-4201-bb98-7ce0689c4f5f.jpg] <https://gogetdigital.co.uk/>       [cid:offerhive_2785ed63-a2ca-4984-bcac-6cf90c6ee920.jpg] <https://www.offerhive.co.uk/>         [cid:property_jungle_acb7dc7d-ce18-4463-826e-bf4174c23b62.jpg] <https://www.thepropertyjungle.com/>     [cid:starberry_008e761b-b143-49ed-af01-1b029851e13e.jpg] <https://starberry.tv/>        [cid:leadpro_e974befc-a33f-499f-b7be-3202e926b7a9.jpg] <https://www.lead.pro/>

(c) 2022 eProp Services Ltd: A company registered in England and Wales with registered number 09210707 and registered office 121 Park Lane, Mayfair, London W1K 7AG. All rights reserved. This email is intended for the named recipient only. It may contain privileged and confidential information. If you are not the intended recipient, please notify the sender immediately and destroy this email. You must not copy, distribute or take action in reliance upon it. Whilst all efforts are made to safe-guard emails, eProp Services Ltd cannot guarantee that attachments are virus free or compatible with your systems and does not accept liability in respect of viruses or computer problems experienced. eProp Services Ltd reserves the right to monitor all email communications through its internal and external networks. Any offer or acceptance contained within or implied by this email is made subject to contract. Additionally, where this email message is sent in connection with a contentious issue, the contents are without prejudice.

**Comment by plittlewood-rpt** [comment]
hi Toby

Webhooks for this customer do still seem to be functioning. Do they still have your app installed?

Pete

**Comment by TobyDunnEPS** [comment]
Yep, still installed.

There's also odd behaviour in the Webhooks UI as it's showing no traffic after the 20th when searching for entity ROC for 20th to 25th October
https://developers.reapit.cloud/webhooks/logs?applicationId=3507d0eb-6b8f-4530-a544-1de6fcd409be&from=2022-10-20&to=2022-10-25&entityId=ROC1

... and nothing at all for entity ROC190012 for the range 20th October to 25th October, although that property has been updated.

Interestingly, changing the start date causes massive changes in the volume of records returned, so a search for ROC from 22nd to 25th gives six results, all for 22nd, 23rd to 25th gives one result for 24th , from 24th to 25th returns 16 results from 24th, and 25th to 25th gives 17 results including hooks for FLS, BEA and HTN

I've tried reconciling these figures against the data in API calls but there's a very low degree of matching.

All the best,
Toby


Toby Dunn
Head of Development

***@***.******@***.***>
121 Park Lane, Mayfair, London W1K 7AG
epropservices.com<https://www.epropservices.com/>

[cid:epsbar_3e39f08d-3fbb-48b9-9232-8ea2fd950058.jpg]<https://www.epropservices.com/>
[cid:fineandcountry_a87aae4c-7515-46df-aba8-7c2a4252e513.jpg]<https://www.fineandcountry.com/uk>        [cid:theguild_2c988f60-5328-4759-8da3-46e8486be818.jpg] <https://www.guildproperty.co.uk/>      [cid:gogetdigital_251cede1-65aa-4201-bb98-7ce0689c4f5f.jpg] <https://gogetdigital.co.uk/>       [cid:offerhive_2785ed63-a2ca-4984-bcac-6cf90c6ee920.jpg] <https://www.offerhive.co.uk/>         [cid:property_jungle_acb7dc7d-ce18-4463-826e-bf4174c23b62.jpg] <https://www.thepropertyjungle.com/>     [cid:starberry_008e761b-b143-49ed-af01-1b029851e13e.jpg] <https://starberry.tv/>        [cid:leadpro_e974befc-a33f-499f-b7be-3202e926b7a9.jpg] <https://www.lead.pro/>

(c) 2022 eProp Services Ltd: A company registered in England and Wales with registered number 09210707 and registered office 121 Park Lane, Mayfair, London W1K 7AG. All rights reserved. This email is intended for the named recipient only. It may contain privileged and confidential information. If you are not the intended recipient, please notify the sender immediately and destroy this email. You must not copy, distribute or take action in reliance upon it. Whilst all efforts are made to safe-guard emails, eProp Services Ltd cannot guarantee that attachments are virus free or compatible with your systems and does not accept liability in respect of viruses or computer problems experienced. eProp Services Ltd reserves the right to monitor all email communications through its internal and external networks. Any offer or acceptance contained within or implied by this email is made subject to contract. Additionally, where this email message is sent in connection with a contentious issue, the contents are without prejudice.
