### ISSUE TITLE
Data population issues for martyn gerrard

### ISSUE THREAD

**Issue by BYMIntegrations** [reapit/foundations#7816]
Please take a look at our FAQ's before submitting an issue, as your question may already be covered in the documentation https://foundations-documentation.reapit.cloud/faqs

**Summary**
The Branches field in the tenancy related object is populating for some customers but not for others. Can we check why this is? Please see a list of people who should have this field populated but haven't
**Detail and or supporting links and screenshots**
CSV removed by AD

**Comment by BYMIntegrations** [comment]
Hello,

Do we have an update on this?

**Comment by BYMIntegrations** [comment]
Hello, 

Can we get a timescale for this as customer is chasing.

**Comment by plittlewood-rpt** [comment]
@BYMIntegrations we will be refining this shortly and will come back to you

**Comment by plittlewood-rpt** [comment]
Hi @BYMIntegrations I'm not sure I understand the problem you are reporting. Are you able to elaborate on the issue for me please? The related object in the TenancyModel doesn't have any branch information at all (and never has done).

**Comment by BYMIntegrations** [comment]
PropertySchemaBranches is the field in question, sorry for the confusion.

**Comment by plittlewood-rpt** [comment]
Hi @BYMIntegrations that field isn't something that Platform emits. It sounds like something that's part of your import routine. Please can you let me know the issue in the contact of the Platform APIs? Thanks

**Comment by plittlewood-rpt** [comment]
Hi @BYMIntegrations please can you come back to us on the above.

**Comment by HollyJoyPhillips** [comment]
Due to inactivity we are closing the ticket, if it's still an issue or you have further questions, please open an a new issue.
