### ISSUE TITLE
Foundations Webhook - Inconsistent Data to identify Commercial properties

### ISSUE THREAD

**Issue by colearymyhome** [reapit/foundations#7817]
**Describe the bug**
We are getting two different methods for determining whether a property is commercial or not between two different estate agents via the Foundations webhook.

For DNG, we are receiving the following field when it is a Commercial Property (eg FOH200584 - Gortnaboul for DNG O'Sullivan Hurley):

"commercial": {
                "useClass": [],
                "floorLevel": []
            },
            
For Sherry Fitzgerald (TER220202 for SF Terenure) this becomes:

"commercial": {
                "useClass": null,
                "floorLevel": null
            },
            
For both agents, when it is NOT a commercial property it looks like this:
"commercial": null,

Is there a reason that they are different?

**Expected behaviour**
As far as I can tell, both are tick boxes in RPS, so I would expect useClass to be a boolean

**Comment by AshDeeming** [comment]
Hi @colearymyhome 
Could you confirm you are using the departments endpoint to differentiate between a clients setup for Attribute groups  i.e. Residential/General or Commercial etc

**Comment by colearymyhome** [comment]
Hi @AshDeeming Can you direct me to that part of the documentation please? We're not calling anything because we're using the webhook.

**Comment by AshDeeming** [comment]
Hi @colearymyhome 

Sure - please see some info around the terminology: https://foundations-documentation.reapit.cloud/platform-glossary#department

the example values & model can be found on the API/REST API/swagger page: https://developers.reapit.cloud/swagger
![image](https://user-images.githubusercontent.com/61687775/193233215-ca9c099a-e619-420e-8ad4-f1c4ad103e65.png)

**Comment by plittlewood-rpt** [comment]
Hi @colearymyhome this is happening due to differences in the client's configuration. DNG have an attribute columns titled Use Class and Floor Level whereas Sherry Fitzgerald do not. As the API cannot determine the column containing these values in the latter customer's dataset, they are returned as null. You should find however that when items in these unsupported columns are selected, the values will appear in the `unmappedAttributes` collection in the `PropertyModel` response from `GET /properties` and `GET /properties/{id}` - please let me know if this does not answer your question

**Comment by colearymyhome** [comment]
Hi @plittlewood-rpt thank you for your response. Are there any other variations of these client configurations possible as we look to add other clients to this webhook?

**Comment by plittlewood-rpt** [comment]
HI @colearymyhome unfortunately it's likely that there will be, although it's likely to be older customers with variations now as we try to use a standard configuration across the board. As our CRM is so heavily customisable we've had a lot of fun deciding how to build a standard API contract with standard behaviours on top of it - handling department attributes is probably one of the most challenging aspects we've had to deal with. The APIs get smarter with each iteration and should be able to detect the correct configuration and behave accordingly. The best advice is to always check a customers' configuration at setup, by using the various endpoints available (departments for understand attribute setup, configuration for understanding customisable lookup list values etc)
