### ISSUE TITLE
Not able to work on two instances of reapit at the same time

### ISSUE THREAD

**Issue by scruffmcduff** [reapit/foundations#7818]
Please see my video explainer at https://share.getcloudapp.com/wbuQYZxm

If I accept an invite from an agent, any details from existing agents seem to disappear.
Are you able to allow access to more than one agents invite?

**Comment by AshDeeming** [comment]
Hi @scruffmcduff 
Thank you for the video explaining the issue. 
Currently an email address is used as the unique identifier for each user & therefore can only be associated to one Customer/Developer account. 
If you need to access multiple, different email addresses will need to be used.
