### ISSUE TITLE
Webhooks are not firing

### ISSUE THREAD

**Issue by bva-tom** [reapit/foundations#7824]
**Summary**

We have setup a webhook to respond to the _Property created_ and _Property modified_ events, and whilst the manual ping function reaches our application we haven't seen any autonomous webhook calls. Is there any additional configuration required?

Customer: RUS
App: 34a66d3d-ab89-46a5-8e11-5db9801fd431

**Comment by plittlewood-rpt** [comment]
Hi @bva-tom - it looks like some prerequisite work for this customer has not been completed as part of their migration to AWS which happened quite a while ago. I've picked this up with the team responsible and will report back ASAP

**Comment by plittlewood-rpt** [comment]
Hi @bva-tom events for this customer should now be being sent. Please let me know if you still do not receive them

**Comment by plittlewood-rpt** [comment]
I've checked logs and can see that we are successfully sending events to you for this customer.

**Comment by bva-tom** [comment]
Thank you @plittlewood-rpt!
