### ISSUE TITLE
Webhook Update 6.5 hour delay

### ISSUE THREAD

**Issue by alanmcgrane** [reapit/foundations#7835]
**Background context**
Please see the below analysis regarding 15b Trimleston Avenue (PropertyReference RRD220093) that we (MyHome.ie) received at 4.58 pm 27th September:

Reapit's webhook logs indicate that the property was updated at 10 am and 10.02am on the 27th of September - with both cases the no internet advertising flag was ticked - meaning the property was not supposed to be live.
 
According to email from DNG contact (Ultan), his records indicate that this "No Internet Advertising" tickbox on RPS was unticked at 10.24am: 
![image](https://user-images.githubusercontent.com/114994876/193801585-7e550eaa-3dd2-45d1-a6fd-c7f7e356b4da.png)

There is no record from Reapit's logs of this property being sent to us (MyHome) between 10.21am and 11.33am on the 27th of September.
The next webhook triggered on RPS according to their logs was at 16.58 - which is when we put the property live. Moreover, in this 4.58pm trigger, the listed difference that the webhook has is as follows:
```
"diff":{
      "internetAdvertising":[
         false,
         true      ],
      "address":{
         "geolocation":{
            "latitude":[
               0,
               53.311102            ],
            "longitude":[
               0,
               -6.203905            ]
         }
      },
      "modified":[
         "2022-09-27T09:02:08Z",
         "2022-09-27T15:58:30Z"      ],
      "selling":{
         "status":[
            "forSaleUnavailable",
            "forSale"         ]
      },
     "_eTag":[
         "\"C897E243BBD1579F43C4280CA2234B3A\"",
         "\"04EAA9639CC79F51BF3BA0DCD7BCB3B6\""      ]
   }
```
 
We can see here that this message at 4.58pm is the update setting internetAdvertising to true, thus putting the property live on our end.

**Specification**
The only thing I can deduce here is that there was a 6.5 hour delay from when the DNG agent updated the property to be live and when we received that update from Reapit. Can Reapit please investigate this or comment on the above? The same property was live on Daft (who are using the legacy custom batch feed built by Reapit) at around 13:19.

We may not have full logs far back enough to determine what has occurred here, but we should review the information available to see if we can understand what happened here

Updated spec 26/01

- Tasks with a type of RM are being partially processes as properties which could cause a batch to fail if records arrive in a specific order. This is being caused by the IsRoomType check on the extra data event handler which is not checking the table

**Comment by plittlewood-rpt** [comment]
Hi @alanmcgrane - can you confirm if you have had any other instances of this happened? I've had a look in logs today and can see that at exactly the same time (10:02:08 BST) the same record has it's featured image changed. This did successfully get sent to you as you can see from the transaction logs. I'm trying to see if there is any place in the code where this could have caused one of the events to be treated as a duplicate and therefore omitted. I've checked the general health of the system at that time and whilst there was a short delay (~10 mins) around that time due to higher than normal load, there's nothing that seems related.

**Comment by colearymyhome** [comment]
Hi @plittlewood-rpt yes, we think it happened 12 days ago for about an hour as mentioned here: https://github.com/reapit/foundations/issues/6815

**Comment by plittlewood-rpt** [comment]
Thanks very much. I'm making some changes overnight tonight all being well to alter some of the scaling policies on the event streaming infrastructure to try and alleviate these issues. I've also found a small bug that could have caused the event in your original report to be omitted - the likelihood of this happening frequently is very very low but we will get this addressed as soon as possible

**Comment by plittlewood-rpt** [comment]
hi @colearymyhome - the scaling policy changes were successful (I was off last week so wanted to review logs on my return) and we can now process double the volume of changes during peak periods. The bug fix mentioned above went out to production a week or so ago so I will close this issue down now. Webhooks is something I will be continuing to monitor closely to see if there are any other areas where we might need to make architectural changes where scaling is concerned. I'd invite any feedback at any point if you notice anything unexpected.
