### ISSUE TITLE
Company filtering follow-up - Fixflo

### ISSUE THREAD

**Issue by NorbiSamu** [reapit/foundations#7856]
**Is your feature request related to a problem? Please describe.**
Following on from https://github.com/reapit/foundations/issues/7631#event-7442374422 - we are unable to filter the correct companies by OfficeIds, as we can't work out which OfficeIds belong to particular Office groups. 

The way we ensure we only sync the correct data from Reapit to Fixflo at the moment is passing in the Office Group Id (eg. LOC-GBRV in the case of Brand Vaughan) and Reapit's APIs return the relevant Properties, Landlords etc. 

**Describe the solution you'd like**
We would either need a way to get the OfficeIds associated with the existing Office Groups, or we would need Reapit to do the filtering for Companies as you already do for other entity types.

**Additional context**
This is one of the biggest outstanding requests for Lomond Group and we're keen to add this feature to our integration as soon as possible.

**Specification**
- Project: Reapit.Services.Companies
- Add office group filtering to `GET companies` and `GET /companies/{id}` endpoint:
  - For users who do not use office groups, do not apply filtering
  - For users who do use office groups, companies assigned to any of the offices in the users' office group list OR companies with no office assigned at all should be returned (the latter part here is the difference to way this has been implemented in other services)

**Comment by plittlewood-rpt** [comment]
Hi @NorbiSamu - it's a little more difficult is this one because a lot of customers don't actually use the office assignment mechanism for companies in our CRM. We would probably have to do something where companies with either no office at all, or an office that matches the office group configuration would be returned. I will have a look at Lomond's data and we can try and work a specification from there

**Comment by NorbiSamu** [comment]
Hi @plittlewood-rpt - that logic makes sense to me, it's all about making sure it's communicated to our customers well. Please let me know what the final implementation will be. Thank you for your help!
