### ISSUE TITLE
How to connect external component to Desktop API

### ISSUE THREAD

**Issue by EnreachTEST** [reapit/foundations#7857]
Good morning, 

I am trying to connect our softphone to you Desktop CRM  but I am facing some issues. 

_**Scenario description**_
**A.** We expect when receiving a call on our Softphone to pop up Reapit Desktop CRM. 
**B**. to do that, our softphone will request your API to search for the caller who is a known contact 
According to Reapit documentation, we can use the following URL to search for a contact.

**agencycloud://contacts?name=ABCD**

- Both your CRM and our application are installed in the same laptop.
- workflow is shown in the attached picture :

Issue, when we request ReapitCRM, the CRM doesn't process our request.

Can you please advise me to understand what I need to do to solve that issue ?

**Comment by AshDeeming** [comment]
Hi @EnreachTEST 
Please could you confirm the app name?

**Comment by EnreachTEST** [comment]
Reapit  AgencyCloud

**Comment by AshDeeming** [comment]
Hi @EnreachTEST 
Apologies for the delay - i wanted to understand your app name that you are looking to integrate with AgencyCloud. 

Please see the documentation below relating to our Desktop API which allows for access to Outbound however Inbound is not currently possible. 
https://foundations-documentation.reapit.cloud/api/desktop-api#desktop-types

**Comment by EnreachTEST** [comment]
Thank you very much for your answer. 

You said that "Inbound Connection" is not supported, you mean that other applications can not make calls to "Reapit Desktop API" to get information or to pop-up the application ? 
Do you confirm ?

**Comment by AshDeeming** [comment]
Hi @EnreachTEST 
That's correct however this being reviewed by the Core AgencyCloud product team https://reapit.atlassian.net/browse/PBI-3995

**Comment by AshDeeming** [comment]
Hi @EnreachTEST 
I'll close this ticket down however if you have any other questions or issues, please open a new relevant ticket.
