### ISSUE TITLE
Issues using pre signed URL for file uploads via APAC infrastructure

### ISSUE THREAD

**Issue by andortamas** [reapit/foundations#7859]
Good afternoon,

**Describe the bug**
When I try to upload a document which is bigger than 4MB, the request returns with the following response:

Array
(
    [header] => HTTP/1.1 100 Continue

HTTP/1.1 413 Request Entity Too Large
Date: Thu, 06 Oct 2022 09:54:32 GMT
Content-Type: application/json
Content-Length: 48
Connection: keep-alive
x-amzn-RequestId: ****masked****
x-amzn-ErrorType: BadRequestException
x-amz-apigw-id: ****masked****=

    [body] => {"message":"The request could not be completed"}
)

Can you let me know the maximum file size I can upload?

Thanks,
Andor

**Specification**
- I have been able to replicate this:
   - Generate a pre signed URL via the developer portal for SBOX
   - Upload file to pre signed URL
   - Try create the document (passing the fileUrl parameter) but send the request to the APAC gateway. Error will occur because that region can't access the bucket in Europe
   - Think this needs to be tackled from the pre signed URL generation handling rather than the POST /document handler. The pre signed URL generated should be for the bucket in the region that the request has hit. This way we know that subsequent request to create the document are likely to hit the same region and therefore not have file access issues

**Comment by andortamas** [comment]
Hi @AshDeeming - thanks for the info. As I see the signedURL allows _'To upload files between 6Mb and 30Mb in size'_ I assume it will reject the file upload when the file size is < 6MB

My problem: our PDF file is 4.6MB, but the base64 string for this file is 6.1MB. So the base64 string exceeds the limit, whilst the file for the signedURL doesn't reach the minimum limit.

**Comment by andortamas** [comment]
Hi @plittlewood-rpt,

It helps, thank you.

My last question: the documentation [here](https://foundations-documentation.reapit.cloud/api/api-documentation#uploading-files) doesn't say anything about the file uploading to the signed URL. How can I upload? Which params I need to use?

I've tried sending it with curl_setopt($ch, CURLOPT_POSTFIELDS, $fileBase64); but no luck yet.

Many thanks,
Andor

**Comment by plittlewood-rpt** [comment]
We are actually due to update the docs with examples, but all you need to do is issue a PUT request to the pre signed URL with your file data:

```
curl --location --request PUT '<pre-signed-url-goes-here>' \
--header 'Content-Type: text/plain' \
--data-binary '@/C:/Users/plittlewood/another file.txt'
```

**Comment by andortamas** [comment]
Many thanks for your help. I'm a bit closer, but still having a problem.

When I PUT the document to the presigned URL it doesn't return any error. However when trying to POST this fileUrl to documents API, it says: Reapit response: Failed to retrieve file from: 'https://reapit-file-uploads-prod.s3.eu-west-2.amazonaws.com/bd2fe574-7c36-4a1b-bf0b-018a54936515' (Code: 400) 

Any idea?

**Comment by andortamas** [comment]
Hi,

Can you please answer to this case? This issue causes a problem with our client.

Regards,
Andor

**Comment by plittlewood-rpt** [comment]
Hi @andortamas - please can you email the file you are trying to upload to [sinfo@reapitfoundations.zendesk.com](mailto:sinfo@reapitfoundations.zendesk.com) so we can take a look at the specific example? There's nothing obvious going on here and other developers are using this mechanism without a problem, so I'm wondering if there's something in the file that the system doesn't like

**Comment by andortamas** [comment]
Hi @plittlewood-rpt 

Sure, I've sent it. Many thanks in advance.

**Comment by plittlewood-rpt** [comment]
Thanks I think I know what's happening here. Your file is being uploaded to our Europe data centre due to the pre signed URL you're getting back, but your requests are hitting our APAC data centre. It looks like there's a permission issue somewhere which we'll need to track down. I've been able to replicate the problem now so we'll look at this as soon as we are able to

**Comment by andortamas** [comment]
Thank you. Can you update me here when I can re-test?

**Comment by RWilcox-Reapit** [comment]
Hi @andortamas 

This issue has just been resolved. Please let us know if you experience anything similar.

Thanks
Ryan
