### ISSUE TITLE
Property metadata field

### ISSUE THREAD

**Issue by quigger** [reapit/foundations#7861]
In the Foundations API spec there is a `metadata` field on a property which is described as `App specific metadata that has been set against the property`.

Looking at a property for GTH (ILM220134) it appears to return a hash, an empty hash in this case.

Is the Reapit agent user able to store data directly in the `metadata` field via the Reapit admin?
And then we can parse it from the API?

**Comment by AshDeeming** [comment]
Hi @quigger 
Metadata is a way for a developer to store data via the Platform that can not be stored in AgencyCloud
I'm unsure why there would be a hash populated however there is no field available in AgencyCloud for a user to input data into this.

**Comment by quigger** [comment]
Thanks @AshDeeming 

Is there a link to the documentation for storing via the Platform?
I recall that there might be some Foundation tools for external devs to create "stuff/admin/buttons/etc." inside the client admin?

**Comment by AshDeeming** [comment]
No problem @quigger 
Please see the below which may be of use: https://foundations-documentation.reapit.cloud/api/api-documentation#attaching-metadata-to-our-entities

**Comment by quigger** [comment]
Thanks @AshDeeming 

OK, that's not quite what I recall (or maybe imagined).

I thought there was some Reapit Foundations tooling to allow us as a 3rd party developer to create new "screens"/"options" inside the Reapit Cloud portal for the client admin?

**Comment by AshDeeming** [comment]
Hi @quigger 

No problem - I think my may be referring to our Desktop API. 
This can be used to replace certain screens in AgencyCloud: 
https://foundations-documentation.reapit.cloud/api/desktop-api#desktop-types 
https://foundations-documentation.reapit.cloud/api/desktop-api

Please let me know if I've misunderstood & i'll try again :)

**Comment by quigger** [comment]
@AshDeeming 

Yes, that seems more like it - thanks.
