### ISSUE TITLE
Alterations in Analytics Schema

### ISSUE THREAD

**Issue by MatthewGoddard** [reapit/foundations#7870]
**Background context**
At present, we record mid-term changes to the rent amount, letting fee or management fee of a tenancy using an alteration. 
Alterations of type 'E' (Renewals or Extensions) are already included in the TENANCY_RENEWALS view, but those of type 'A' are not.

**Specification**
We would like to report on when an alteration has been added against a tenancy to change a rent amount, letting fee or management fee. 

- Project: Analytics Schema
- Add new table TENANCY_ALTERATIONS whose structure matches TENANCY_RENEWALS with the exception of the ENDDATE which does not need to be present
- Data for the new table will come from the same staging table that populates TENANCY_RENEWALS, filtering to only Alteration (A) a type records. These records will need to be added to the staging table (and subsequently filtered from the TENANCY_RENEWALS table as well)
- Update Analytics Schema documents (separate project)
- When releasing this to production remember to update the list of analytics schema table names in parameter store so that when customers provision the dataset they get the new table

**Comment by plittlewood-rpt** [comment]
This has now been released to production. Please use the Data Warehouse App to refresh the data share to use the new TENANCY_ALTERATIONS view, and refer to [the documentation](https://developers.reapit.cloud/analytics-schema-docs) for further information.
