### ISSUE TITLE
Address security vulnerability in kind-of package

### ISSUE THREAD

**Issue by willmcvay** [reapit/foundations#788]
<img width="860" alt="Screenshot 2020-04-02 at 13 55 51" src="https://user-images.githubusercontent.com/4630495/78251923-f41d8a00-74e9-11ea-8962-a16c2350b0ea.png">

See screenshot, looks like a sub-dependency of some dev-dependencies. Lerna and Sass look like the main culprits here.

**Comment by willmcvay** [comment]
Really annoyingly the same vulnerability still exists and the minimist / acorn issues reported earlier have returned... sorry, going to have to re-open.

<img width="855" alt="Screenshot 2020-04-06 at 15 54 34" src="https://user-images.githubusercontent.com/4630495/78572428-5c88a600-781f-11ea-873b-c933ec40fab6.png">
<img width="797" alt="Screenshot 2020-04-06 at 15 54 43" src="https://user-images.githubusercontent.com/4630495/78572438-5f839680-781f-11ea-9956-6a140fd0379e.png">
<img width="852" alt="Screenshot 2020-04-06 at 15 54 53" src="https://user-images.githubusercontent.com/4630495/78572442-601c2d00-781f-11ea-9c9c-e419bdd0dd13.png">

**Comment by vuhuucuong** [comment]
That's weird, and why it's showing `geo-diary/yarn.lock` despite that we don't have `yarn.lock` in geo-diary`

**Comment by willmcvay** [comment]
@vuhuucuong Closing issue with the addition of Snyk security tooling to monitor our app.
