### ISSUE TITLE
App/webhook issue with one client

### ISSUE THREAD

**Issue by Speedway1** [reapit/foundations#7896]
Possible Webhook not firing
Our client has installed the Core Features and Nurture pack apps but we are not seeing any activity

Upon installation we should be receiving data but nothing is returned.
Due to client confidentiality, we are not able to share their name.  The application was installed yesterday 10/10 11:39.
Thank you

**Comment by plittlewood-rpt** [comment]
Hi @Speedway1 - thanks for reaching out. As was the case previously I cannot see that you have subscribed this customer to your configured webhooks. Please note that the act of a customer installing an application does _not_ automatically subscribe them to your webhooks UNLESS you have a global webhook subscription setup (that is, where All Customers is selected). As soon as you explicitly choose customers to listen to events for, you must remember to add any additional ones that install your application in the future. If you can review your webhook configuration and come back to us if the problem persists that would be great.

**Comment by plittlewood-rpt** [comment]
Hi @Speedway1 please can you come back to me on the above?
