### ISSUE TITLE
2 Agents missing from API - Fixflo

### ISSUE THREAD

**Issue by NorbiSamu** [reapit/foundations#7902]
**Describe the bug**

2 agents (Negotiators) seem to be missing from the Negotiators API.

The organisation is National Home Move. They share a Reapit with LSL Property Services and have office groups set up for the sync. The code is YOM-GNVS

The branches sync'd under this office group are QAN, QBO, QBG, BRG, QNH. The two staff IDs that we are looking for are Luke (XKUI) and Christine (QEIN).

Would you be able to advise us on why these 2 Agents are seemingly not returned in your API?

**Comment by AshDeeming** [comment]
Hi @NorbiSamu 
I'm unable to locate the two users/negotiators - Luke (XKUI) and Christine (QEIN).

Could you confirm their email address for further review please - please send to sinfo@reapitfoundations.zendesk.com
