### ISSUE TITLE
Auction Date and adding an extra descriptive field within Reapit AC

### ISSUE THREAD

**Issue by quigger** [reapit/foundations#7930]
I have a query in Reapit Support:
https://reapitsupport.refined.site/portal/1/RSD-202589

Where Ankit says:
```
Jason, there is an Auction Date field present in the system that could be utilised within the Foundations feed to Homeflow

Rachel, regarding the EIG URL this can be added as an extra description field within the marketing screen where the URL can be added and potentially be picked up by the API feed
```

Would either of those fields be directly available via the Foundations API please?

**Comment by AshDeeming** [comment]
Hi @quigger 
Apologies for the delay - Auction Date & EIG Url are not currently surfaced via the platform. 
These can be requested via the feature request option for future review.

**Comment by quigger** [comment]
Hi Ash, thanks.

In this ticket: https://reapitsupport.refined.site/portal/1/RSD-202589 Ankit is asking if we want these new fields added. However, it depends on if we can access the data.
When might (how soon?) this work be completed if we do request it please?

Kind regards,
Jason.

**Comment by AshDeeming** [comment]
Hi @quigger 
Apologies for any confusion caused.

The fields currently available can be seen in the model under each endpoint via the swagger page:
https://developers.reapit.cloud/swagger

Unfortunately I'm unable to provide a timeframe as each ticket will need to be reviewed - please see the link below with regards to the request process: 
https://foundations-documentation.reapit.cloud/dev-requests#how-long-will-it-take-for-my-issue-to-be-reviewed

A feature request can be logged [Here](https://github.com/reapit/foundations/issues/new?assignees=&labels=external-request%2C+needs-triage&template=feature_request.md&title=)

**Comment by quigger** [comment]
Added:
https://github.com/reapit/foundations/issues/7947
and
https://github.com/reapit/foundations/issues/7948
