### ISSUE TITLE
Please add extra description field within the marketing screen to Foundation API

### ISSUE THREAD

**Issue by quigger** [reapit/foundations#7948]
Related to: https://github.com/reapit/foundations/issues/7930

In ticket: https://reapitsupport.refined.site/portal/1/RSD-202589

Ankit said:
_"In Rachel, regarding the EIG URL this can be added as an extra description field within the marketing screen where the URL can be added and potentially be picked up by the API feed"_

Can this be utilised within the Foundations feed to Homeflow please.

**Comment by plittlewood-rpt** [comment]
Hi @quigger - apologies you've been passed round a bit here. I've dropped a note on the service desk ticket to advise that they are fine to add this field. They will need to add it to the CRM first and then they can let us know what the field is so we can expose it (in a read only fashion) using the semi structured extrasField mechanism that's already available in Platform. I'll move this issue to Not Ready until the service team have done their bit then get this set up for you. Thanks

**Comment by quigger** [comment]
Thanks @plittlewood-rpt 👍

**Comment by plittlewood-rpt** [comment]
Hi @quigger this has now been added to Greenslade Taylor Hunt's configuration for Platform. You can access using the extrasField query string parameter using the field name pEigUrl

`GET /properties?extrasField=pEigUrl` and `GET /properties/{id}?extrasField=pEigUrl`

I have added a test URL to property CHA180298 if you need one for testing as the field has not been utilised by the agent yet

Thanks
