### ISSUE TITLE
Is there a way to automate token refresh using Postman?

### ISSUE THREAD

**Issue by ianyoung** [reapit/foundations#7953]
I am using Postman and can successfully generate a token using the [client credentials flow](https://foundations-documentation.reapit.cloud/api/api-documentation#client-credentials-flow) (server-side app). I can then copy and paste the returned token into my saved requests for the API and authenticate. However, the token only lasts for 60 minutes and having to manually generate the token and then copy and paste into all saved requests in Postman is quite tedious when actively developing. Is there a way to automate the token generation on each request in Postman (as we do in code)?

**Comment by plittlewood-rpt** [comment]
Hi @ianyoung - we don't support Postman but happy to share what we do. I'd recommend using the [pre-request script feature ](https://learning.postman.com/docs/writing-scripts/pre-request-scripts/ ) in Postman to do this. We do something similar to run some of our integration tests (fetch a token before the test run that's used for each request in the run)

Here is an example. We store the date/time we last fetched the api key in a variable so we can tell if we should fetch another one before subsequent runs. You could be smarter and check to see if it's actually expired, but this works for us as we don't run the collection that often. Obviously this only works for client_credentials flow apps

```
const moment = require('moment');

var lastFetched = pm.environment.get("api-key-lastFetched");
let getNewToken = false;

if (lastFetched) {
    var lastFetchedDate = moment(lastFetched);
    var allowedMinimum = moment().add(-30, 'm').toDate();

    if (lastFetchedDate < allowedMinimum) {
        console.log("Api key more than 30 minutes old. New token will be requested");
        getNewToken = true;
    }
}
else {
    console.log("No record of api key last fetch date. New token will be requested");
    getNewToken = true;
}

if (getNewToken) 
{
    console.log("Fetching new access token");
    let tokenUrl = 'https://connect.reapit.cloud/oauth2/token';
    let clientId = '[CLIENTID]';
    let clientSecret = '[CLIENTSECRET]';

    let getTokenRequest = {
        method: 'POST',
        url: tokenUrl,
        auth: {
            type: "basic",
            basic: [
                { key: "username", value: clientId },
                { key: "password", value: clientSecret }
            ]
        },
        body: {
            mode: 'urlencoded',
            urlencoded: [
                { key: 'grant_type', value: 'client_credentials' }
            ]
        }
    };

    var requestTimestamp = moment().format("YYYY-MM-DDTHH:mm:ssZ");
    pm.sendRequest(getTokenRequest, (err, response) => {
        let jsonResponse = response.json(),
            newAccessToken = jsonResponse.access_token;

        pm.environment.set('api-key', newAccessToken);
        pm.environment.set('api-key-lastFetched', requestTimestamp);
    });
}

```

Hope this helps
