### ISSUE TITLE
JournalEntries endpoint

### ISSUE THREAD

**Issue by s-finny** [reapit/foundations#7954]
**Describe the bug**
Trying to use the JournalEntries endpoint and have been returned an error.
The error is unexpected and used a valid typeId and associatedId

**To Reproduce**
Post to the endpoint 'journalEntries'

Data posted was as below:
{
  "typeId": "EM",
  "propertyId": "REN220016",
  "associatedType": "contact",
  "associatedId": "REN220016",
  "description": "Valuation Tracker: Email sent to Sophie Craske at s.craske@beresfords.co.uk"
}

Error Received:
{
    "errors": [
        {
            "field": "typeId",
            "message": "Unsupported typeId. The following typeIds can be used when creating a new journal entry: MA,MI,WO"
        },
        {
            "field": "associatedId",
            "message": "The value provided must be in a valid format and contain 11 characters"
        }
    ],
    "statusCode": 422,
    "dateTime": "2022-10-19T14:21:24.2411168Z",
    "description": "One or more validation failures have occurred. Please refer to Errors list for details"
}

**Expected behaviour**
There is no mention in the documentation the limitation of typeId's being used in creating new Journal Entries.
The error states to use MA, MI, WO -  WO does not exist?

We are trying to log back to Reapit when we have sent an Email, Letter, Leaflet and SMS, for this we was looking to use the following:

Emails - EM
Letters/Leaflets - LE
SMS - Telephone Contact

On the othere side of the error '"message": "The value provided must be in a valid format and contain 11 characters"'
I'm posting the contact reapitId that is associated with the property with the associatedType set to contact - Is this not correct?
The Developer Portal Swagger seems to show this as being correct?

**Comment by AshDeeming** [comment]
Hi @s-finny 
Currently there are only two journalTypes that can be used:  MA - for Property Matches and MI - For Miscellaneous

**Comment by s-finny** [comment]
Hi @AshDeeming,

Thank you for confirming that, can you let me know when you will be allowing other types as we send letters and emails on behalf of clients it would be good to put it in the right entry.

Also can you answer the part on the associatedId?

**Comment by plittlewood-rpt** [comment]
Hi @s-finny - you are getting an error on the associatedId because the id you have passed is not a valid contact id. Contact ids have 11 characters, not 9 like some of the other entities. It looks like you've passed the code of the property (or vendor?) but not the contact itself.

**Comment by s-finny** [comment]
@plittlewood-rpt Thanks I was passing the vendorId this has been updated the to contactId and has worked thank you.
