### ISSUE TITLE
Rent being returned incorrectly

### ISSUE THREAD

**Issue by LouisaEvosite** [reapit/foundations#7961]
**Describe the bug**
Rent is showing in Reapit program against a tenancy as £475.
Rent is being returned in Reapit API in tenancy as £450.

(We need the rent that is against the tenancy, not the property)

**To Reproduce**
See screenshots.

**Expected behaviour**
Rent to be the same

**Screenshots**
![image](https://user-images.githubusercontent.com/109209591/196928221-f5e13d38-69e9-4370-baa9-4a77b4a377f2.png)

Data against tenancy:
![image](https://user-images.githubusercontent.com/109209591/196928337-1472411a-4acb-4522-9f9c-5db6ad9f022c.png)

**Device (please complete the following information for web issues):**
N/A

**Additional context**
N/A

**Specification**
- Project: Reapit.Services.Tenancies
- Enhance `TenancyExtensionAlterationModel` as follows:
```
   "oneOffFee": true,
   "feeAmount": 500.0,
   "feeNarrative": "Renewal Fee",
   "feeType": "landlordLettingFee`,
```

These new fields should be populated based on data from the tenExt table. Data warehouse can be used as a reference point here. New enum will be needed for feeType

- Look into bug reported where rent amount is incorrect when opting to embed tenancy extensions ([see notes](https://github.com/reapit/foundations/issues/7961#issuecomment-1355008599) below)

**Comment by plittlewood-rpt** [comment]
Hi @LouisaEvosite - this is currently by design. Renewals are not currently supported in the API and the rent you are wanting is associated to a renewal and not the tenancy directly. If we were to update the rent on the tenancy you'd lose sight of the original rent. We will consider this item and look at the best approach

**Comment by NBareham** [comment]
@plittlewood-rpt This is making no sense to landlords and we are getting around 3 complaints a day on this and we're only live on about 15% of properties. This is the latest one: 
COL160005 The rent increased to £525 from 28 August 22. Please amend the portal
Everything is the front end of Reapit on the tenancy (COL220240) is stating £525 so I don't know why the API is different.
@LouisaEvosite FYI

**Comment by LouisaEvosite** [comment]
Just to confirm we are getting £440 for that tenancy

![image](https://user-images.githubusercontent.com/109209591/197175144-ff25e7d4-4559-421f-8636-ad12dd987109.png)

**Comment by LouisaEvosite** [comment]
Hi @plittlewood-rpt - is there any update on this one please?

**Comment by roscoe2001** [comment]
Morning @plittlewood-rpt , would it be possible to get some kind of timescales on this one please?

Currently we are showing incorrect Rent amounts to Tenants / Landlords which is causing a lot of complaints / problems so it would be good to get some kind of timescale so we can manage expectations.

Thanks

**Comment by plittlewood-rpt** [comment]
I will review this again today. The underlying issue is that the tenancies API does not currently cater for renewals (which will be a subresource). To try and tackle the immediate issue, we'll look at adding a new property to the TenancyModel called `originalRent` so we can retain the original rent amount, then update the values for `rent` and `rentInstallments` as appropriate based on renewal status.

**Comment by plittlewood-rpt** [comment]
Hi @LouisaEvosite can you confirm if you are using tenancy webhooks currently? We can make the change above but this won't be reflected in webhooks (ie you won't receive a tenancies.modified event when a renewal becomes active).

**Comment by plittlewood-rpt** [comment]
For information, we cannot implement this in the manner described above as it will cause too many issues with webhooks not respecting extensions when the 'active' date suddenly comes into play. As a result, we will be adding a new /extensions endpoint that will allow you to understand changes to rent amounts. The rent on the main tenancies endpoint will remain as the original rent. I wanted to let you know as it will mean changes are required to your app

**Comment by LouisaEvosite** [comment]
Hi @plittlewood-rpt - we are not using webhooks at moment.
If it would be possible to embed the extensions with a tenancy call to minimise our API calls that would be even better.
Thanks,
Louisa

**Comment by LouisaEvosite** [comment]
Hi @plittlewood-rpt is there an update on this one please? We are still getting an awful lot of feedback about incorrect rents displaying so would appreciate this one being resolved.

Thanks,
Louisa

**Comment by plittlewood-rpt** [comment]
Hi @LouisaEvosite the changes are currently in review so the new endpoints should go out this week.

**Comment by plittlewood-rpt** [comment]
HI @LouisaEvosite these endpoints are now available. For the time being we have kept the payload lightweight to deal with the immediate issue with the rent. It's likely we'll need to iterate over this to enhance support for other alterations (one off fees etc) but can you have a look and let me know any feedback. I've checked the example from your original screenshot and you will now see the extension showing the rent increase to £475p/m from 03/09/22 at `GET /tenancies/BES220029/extensions`. In addition, you can embed extensions information into both the main GET endpoints for convenience eg `GET /tenancies?embed=extensions` and `GET /tenancies/{id}?embed=extensions`

**Comment by LouisaEvosite** [comment]
Hi @plittlewood-rpt Fantastic! It seems to contain what we need. I'll make a few updates and let Nicola have a review.
Thanks,
Louisa

**Comment by robchett** [comment]
Hi @plittlewood-rpt, the lightweight payloads have caused some confusion. 
We're seeing some entites with type:"alteration" whcih have a rent value but which are in fact one off fees. 

For example Extension REE21000214 on YOM is a one off fee but it is indistinquishable from an actual alteration. It also has a rent value that is incorrect, it appears to be the original tenancy rent and not the rent at the time of the alteration.

Could fees be typed differently?

**Comment by plittlewood-rpt** [comment]
Hi @robchett thanks for getting in touch - ironically i've been looking at the same issue with the Analytics Schema today so we need to circle back and just have a look at this. There's perhaps an argument for exposing one off fees from a different endpoint entirely. We'll re-review this in due course and update you

**Comment by plittlewood-rpt** [comment]
Hi @robchett the extension id you've provided above is an extension and does appear to have the correct values. That said, I do still understand your point. We'll discuss this in our refinement session today. 

![image](https://user-images.githubusercontent.com/30798627/207833520-7a30e348-5ddc-422d-b6e8-fd2a1e10502c.png)

**Comment by robchett** [comment]
Ah yes, I gave you the wrong ID, I meant to give you an alteration, eg: /tenancies/HIC210305/extensions/REE22007374

**Comment by robchett** [comment]
Yes, those changes sound great. 

On closer inspection it appears that we're getting a different rent value for alterations depending on if they're loaded through 
?embed=extensions or /extensions

/tenancies/HIC210305?embed=extensions gives (incorrectly)

```
{
    "id": "REE22007374",
    "created": "2022-11-14T14:08:31Z",
    "modified": "2022-11-14T16:48:12Z",
    "startDate": "2022-11-14",
    "endDate": null,
    "type": "alteration",
    "negotiatorId": "YRMN",
    "rent": 685,
    "rentFrequency": "monthly",
    "tenancyId": "HIC210305",
    "_eTag": null,
    "_links": {
        "self": {
            "href": "/tenancies/HIC210305/extensions/REE22007374"
        },
        "tenancy": {
            "href": "/tenancies/HIC210305"
        },
        "negotiator": {
            "href": "/negotiators/YRMN"
        }
    },
    "_embedded": null
},
```

while /tenancies/HIC210305/extensions gives (correctly)

```
{
    "id": "REE22007374",
    "created": "2022-11-14T14:08:31Z",
    "modified": "2022-11-14T16:48:12Z",
    "startDate": "2022-11-14",
    "endDate": null,
    "type": "alteration",
    "negotiatorId": "YRMN",
    "rent": 700,
    "rentFrequency": "monthly",
    "tenancyId": "HIC210305",
    "_eTag": "\"A91570441D0D55F1CB3A822CA7DB7B77\"",
    "_links": {
        "self": {
            "href": "/tenancies/HIC210305/extensions/REE22007374"
        },
        "tenancy": {
            "href": "/tenancies/HIC210305"
        },
        "negotiator": {
            "href": "/negotiators/YRMN"
        }
    },
    "_embedded": null,
    "metadata": {}
},
```

**Comment by plittlewood-rpt** [comment]
HI @robchett this update is just going out to production now so shoudl be available in the next 15 mins or so. Can I ask you to review when you get a few minutes and let me have any feedback? I've added the one off fee information in a slightly different way which is a better structure, and resolved the issue with the rent being incorrect when embedding the extensions

**Comment by robchett** [comment]
That looks great, thank you @plittlewood-rpt
