### ISSUE TITLE
Is Alternate Code available in the Reapit Foundations API?

### ISSUE THREAD

**Issue by quigger** [reapit/foundations#7967]
Is Alternate Code available in the Reapit Foundations API?

See under the Additional section here:
![image](https://user-images.githubusercontent.com/644502/197151600-c55dbbcd-73dc-4d82-b830-e3e9d69c7451.png)

What is the Alternate Code data type please?

**Comment by plittlewood-rpt** [comment]
Please see the [Swagger documentation](https://developers.reapit.cloud/swagger) for `PropertyModel` to understand this information. (field `alternateId` of type `string`)

![image](https://user-images.githubusercontent.com/30798627/197152282-79ec6f1d-62f1-4b89-941c-58a973ff98da.png)

**Comment by quigger** [comment]
Thanks @plittlewood-rpt
