### ISSUE TITLE
Customer modified a property - webhook not fired

### ISSUE THREAD

**Issue by stebrough** [reapit/foundations#7976]
**Describe the bug**
A customer we have webhooks set up for modified a property yesterday 20/10/2022 @ 16:02:12 and we did not get a webhook call for it. I also cannot see a call in the Transaction Logs.

**Expected behaviour**
Webhook call received.

**Additional context**
Sensitive info emailed to sinfo@

**Comment by plittlewood-rpt** [comment]
Hi @stebrough can you confirm if you've had any webhooks at all for this customer, other than install/uninstall events? I'm expecting you to say no but just want to check. It doesn't look like Webhooks have been enabled for this customer, something I will pick up with the appropriate team

**Comment by stebrough** [comment]
Hi @plittlewood-rpt You're right I can't see anything ...

**Comment by plittlewood-rpt** [comment]
Thanks - I'll get this seen to. Their webhooks have never been enabled since moving to AWS

**Comment by plittlewood-rpt** [comment]
Hi @stebrough this is resolved. I can see you've received some webhooks for the customer concerned so will close this down.
