### ISSUE TITLE
is there a way to remove additionalContactDetails from a contact record using the API? 

### ISSUE THREAD

**Issue by AdamHall12** [reapit/foundations#7979]
Please take a look at our FAQ's before submitting an issue, as your question may already be covered in the documentation https://foundations-documentation.reapit.cloud/faqs

**Summary**
I am using the PATCH /contacts/{id} endpoint to update a contact record. I am able to update standard contact details e.g. homePhone, email but unable to update any custom contact details that are shown in the additionalContactDetails section of the GET /contacts/{id} endpoint.
**Detail and or supporting links and screenshots**
See below what I mean by the custom contact details of a contact record. How would I format the API request body if I would like to remove these contact details? Thanks
![image](https://user-images.githubusercontent.com/102241930/197563621-f7b5f876-e247-42f9-ba09-a6b7774edf53.png)

**Specification**
- Project: Reapit.Services.Contacts
- Support PATCHing of additionalContactDetails collection. Expected behaviour
  - Developer must past entire collection when patching
  - To remove all additional items, pass empty array (instead of null)
  - Ensure that the phone string stored back in AgencyCloud is build correctly, and then items in the phone table are populated
  - Emit a journal notification for the journal service to create an entry in the assoicated journal. Ensure the format is consistent with AgencyCloud
  - Validate no duplicate contact details between this collection and the core properties
  - Documentation about how this works is key here, so ensure Swagger is updated accordingly

**Comment by AshDeeming** [comment]
Hi @AdamHall12 
From the screen shot provided, these appear to be homePhone, workPhone or mobilePhone 

Could you confirm which fields you are referring please?

**Comment by AdamHall12** [comment]
Hi @AshDeeming,

Thanks for your response. No these are customisable fields, on the contact record you have the ability to change the name of the field. When you do this they come through as additionalContactDetails in the http response. See below: 
![image](https://user-images.githubusercontent.com/102241930/197571908-33e418f0-1573-4264-b59d-dd1fae152143.png) 
![image](https://user-images.githubusercontent.com/102241930/197572117-28f5de95-c866-40ac-bea8-844a6a0fef28.png)

**Comment by AdamHall12** [comment]
Hopefully the below screenshots help clarify what I mean:

![image](https://user-images.githubusercontent.com/102241930/197577888-6eb1c498-2802-468b-b094-b25b37360b81.png)
![image](https://user-images.githubusercontent.com/102241930/197577965-ab6f7ce1-1719-463a-93a7-ebef23d57767.png)

I would like to use the update contact endpoint to remove mobile2 from the contact record.

**Comment by plittlewood-rpt** [comment]
Hi @AdamHall12 - this is not currently possible and won't be that easy to implement due to it being an array collection. Due to other priorities currently in motion it's unlikely we'll be able to do something in the short term
