### ISSUE TITLE
Pre Instruction Check List Data

### ISSUE THREAD

**Issue by DannySteptoe** [reapit/foundations#7983]
Hi,

We are utilising the new pre instruction check lists in RPS but we have no way of reporting on it and would appreciate it being added to the data warehouse. 

Regards

Danny

**specification**
- Project: Analytics Schema

**Comment by plittlewood-rpt** [comment]
Hi @DannySteptoe this is now available. You will need to refresh your data share through the Data Warehouse app to see the new view PROPERTY_INSTRUCTION_CHECKS. Documentation is available in the Developer Portal as always. Thanks
