### ISSUE TITLE
Is it possible to update an archived contact using the API?

### ISSUE THREAD

**Issue by AdamHall12** [reapit/foundations#7988]
Please take a look at our FAQ's before submitting an issue, as your question may already be covered in the documentation https://foundations-documentation.reapit.cloud/faqs

**Summary**
I would like to update details of specific archived contacts using the API.
**Detail and or supporting links and screenshots**
When I try to do this I get the below error message:

    "body": {
        "statusCode": 400,
        "dateTime": "2022-10-25T14:58:39.2247810Z",
        "description": "Unable to perform update operations on archived contacts."
    }

Thanks,

Adam

**Comment by plittlewood-rpt** [comment]
Hi @AdamHall12 - can you confirm what updates you are wanting to make? We've actually just about completed some work to allow updating of an archived contact's marketing consent in this cycle. See #7710

**Comment by AdamHall12** [comment]
Hi @plittlewood-rpt , I would be looking to either unarchive the contact (which would then allow all other changes to be made) or update the surname field and all contact details (contact numbers, email addresses and home/work/secondary addresses). Thanks

**Comment by plittlewood-rpt** [comment]
Thanks - we'll need to review this. Blocking updates to archived entities was a conscious decision because we cannot currently support webhooks for archived entities which would leave a gap. We're due to review our backlog tomorrow

**Comment by plittlewood-rpt** [comment]
Unfortunately due to the way the underlying database operates, it won't be possible for us to allow third parties to manage unarchiving/archiving of records. As there are also no webhooks for archive tables, allowing a more open update or archived contacts would likely raise more problems. As such we are not in a position to be able to action this item.
