### ISSUE TITLE
Enquiries API issue - Client(Robinson Jackson - RBJ)

### ISSUE THREAD

**Issue by rajeshwl** [reapit/foundations#7997]
**Describe the bug**
We are posting Valuation and viewing enquiries from website via the enquiries API in Foundations. But the client couldn't able to see the leads sent from website. The lead statuses are updated as **spam** in the entry, unfortunately we don't have the option to post the status field in enquiries API.  

**NOTE:** 
Randomly the entries are marked as spam it seems. Some entries are in pending status. Entries posting via API will have the source marked as  **Online - Robinson Jackson**

**Expected behaviour**
We expecting the status to be updated as **pending** and visible to the client in Reapit agency cloud system. 

**Additional context**
We have added the sample enquiry data which has been received from get call that has been updated with status **spam** in your end, But while we post the data the status information is not been passed. For security reasons i am removing the personal information's.

`{
    "id": 841338,
    "created": "2022-10-12T14:49:25.0000000Z",
    "modified": "2022-10-13T15:19:20.0000000Z",
    "title": "Sir/Mam",
    "forename": "M*******",
    "surname": "D********",
    "enquiryType": "salesProperty",
    "message": "valuation for salesProperty",
    "status": "spam",
    "marketingConsent": "notAsked",
    "position": "",
    "officeId": "ELT",
    "sourceName": "Online - Robinson Jackson",
    "homePhone": null,
    "workPhone": null,
    "mobilePhone": "0********",
    "email": "d**********@gmail.com",
    "address": {
        "buildingName": "",
        "buildingNumber": "",
        "line1": "",
        "line2": "",
        "line3": "******",
        "line4": "LONDON",
        "postcode": "**********",
        "countryId": "GB"
    },
    "buying": null,
    "renting": null,
    "bedrooms": null,
    "propertyIds": [],
    "_links": {
        "self": {
            "href": "/enquiries/841338"
        }
    },
    "_embedded": null
}`

**Comment by plittlewood-rpt** [comment]
Hi @rajeshwl - a user in one of the branches will have marked this is spam as there is no automated process to do so. I would encourage you to speak with the agent in the first instance.

**Comment by rajeshwl** [comment]
@plittlewood-rpt ,
We checked with the branch earlier regarding this and they said no action done from their end. That's why we thought of confirming from your end as we don't have any option to send the status but in the middle the leads are marked as **spam**. Can you please confirm is there any chance that from your end the status has been marked as **spam**.

**Comment by rajeshwl** [comment]
@plittlewood-rpt ,
We don't have any recent records with the status **spam**.

**Comment by rajeshwl** [comment]
@plittlewood-rpt ,
Is there any updates on this issue?
