### ISSUE TITLE
Write access request

### ISSUE THREAD

**Issue by MarcinuB** [reapit/foundations#8002]
**Describe the solution you'd like**
Can I ask for a write permission  to the “text” field in the AC marketing screen “extras” category for a customer Savills. 

**Additional context**
We're working with Savills on integration and we need access to this field to be able to update some data for them. 

**Specification**
- Project: Reapit.Services.Properties
- Add `urlCaption` property to `PropertyModel` (underneath `url`) and respective write models that allow prp.extras.pURLText to be read/updated accordingly

**Comment by AshDeeming** [comment]
Hi @MarcinuB 
Please could you confirm you are requesting the Extra Descriptions, from the Marketing Screen within the clients AgencyCloud system?
