### ISSUE TITLE
Property Inspection Frequency

### ISSUE THREAD

**Issue by DannySteptoe** [reapit/foundations#8007]
Hi,

I want a pull a report that shows Visits due but different properties have different frequencies in RPS so I need to be able to pull that field. 

Thanks 

Danny

**Specification**
- Project: Analytics Schema
- Add INSPECTION_FREQUENCY_DAYS field to TENANCIES model that displays the inspection frequency for a rental property. Should use configuration value if not explicitly set on the tenancy, and should be set to zero if not configured
- [ ] Update documentation with production release

**Comment by plittlewood-rpt** [comment]
Hi @DannySteptoe  apologies for the delay in responding to this - there seems to have been an issue with Github not auto assigning the ticket to our project board so it got missed. We'll review ASAP and come back to you

**Comment by plittlewood-rpt** [comment]
Hi @DannySteptoe  this is now available as per the specification on this ticket. Please note you will need to log into the Data Marketplace app and click Refresh Share to be presented with the new columns in the models. Thanks
