### ISSUE TITLE
Property PublicBrochureURL are invalid for many properties

### ISSUE THREAD

**Issue by rajeshwl** [reapit/foundations#8026]
**Describe the bug**
Some of the property Public Brochure URL's are not working. Can you please check whether the issue is in your end. Shared some of the Property ID's and URL's.

**PropertyId : publicBrochureUrl**
BAT220173 : https://assets.reapit.net/csp/live/pdf.php?p=BAT220173&t=S
BAT220149 : https://assets.reapit.net/csp/live/pdf.php?p=BAT220149&t=S
BAT220137 : https://assets.reapit.net/csp/live/pdf.php?p=BAT220137&t=S
BAT220134 : https://assets.reapit.net/csp/live/pdf.php?p=BAT220134&t=S
BAT220125 : https://assets.reapit.net/csp/live/pdf.php?p=BAT220125&t=S

**Client:** Crisp Cowley(CSP)
**Endpoint Used:** properties

Expected to have a valid URL are the link to be empty.

**Specification**
- Project: Reapit.Services.Properties
- Update `PublicUriHelper` to take the following into account and only display brochure URI if all points validate:
   - Internet Advertising must be enabled
   - Status must be one of `'FA', 'SA'` if property is sales (or dual marketed) - use enum
   - Status must be one of `'LA', 'UA', 'TA', 'AA', 'AC', 'TC'` if property is lettings (or dual marketed) - use enum
   - Property must have a brochure assigned (dictated by presence of pDetails in prp.extra
- Update tests in appropriate places, adding new tests as necessary

**Comment by ianyoung** [comment]
Coincidental timing. I've just come across the same issue. Examples:

**PropertyId : publicBrochureUrl**
GUE141237: https://assets.reapit.net/sau/live/pdf.php?p=GUE141237&t=S
GUE141613: https://assets.reapit.net/sau/live/pdf.php?p=GUE141613&t=S
GUE141806: https://assets.reapit.net/sau/live/pdf.php?p=GUE141806&t=S
GUE150592: https://assets.reapit.net/sau/live/pdf.php?p=GUE150592&t=S
GUE150585: https://assets.reapit.net/sau/live/pdf.php?p=GUE150585&t=S

Client: Savills
Endpoint Used: properties

**Comment by HollyJoyPhillips** [comment]
Hi @ianyoung Can you confirm the field name please because we have both a 'url' field (on the Marketing screen) and a Property Brochure URL: publicBrochureUrl?

**Comment by ianyoung** [comment]
I was referring to the `publicBrochureUrl` field. However, in my case it may very well be because it is a UAT environment and the property brochures aren't attached...

**Comment by rajeshwl** [comment]
@HollyJoyPhillips ,
We use the field `selling->publicBrochureUrl` and `letting->publicBrochureUrl`  in the property data.

**Comment by HollyJoyPhillips** [comment]
Thank you for verifying. We'll take a look and come back to you.

**Comment by plittlewood-rpt** [comment]
Hi @rajeshwl - this is happening because the properties are no longer on the market and as a result the brochures should not be public anymore. The URL shouldn't really be being surfaced in these cases as you point out, so we'll get that looked at when we can.
