### ISSUE TITLE
Potential Client - Field name: aPotClient

### ISSUE THREAD

**Issue by ebuildwebsolutions** [reapit/foundations#8027]
Hi,

Could you make available the Field name: aPotClient for Ed Dempsey in the API feed please?

![image](https://user-images.githubusercontent.com/25635668/198681143-a9624210-ce38-4714-8157-f51ee501cf86.png)

If you could let me know how I could access this.

Philip.

**Specification**
- Project: Reapit.Services.Applicants
- Add new bool property `potentialClient` to `ApplicantModel` and associated write models to allow app.extra.aPotClient to be retrieved and written to applicant entities 
- Property in the Update model and command needs to be a nullable bool

**Comment by ebuildwebsolutions** [comment]
Hi Holly,

Thanks for the update. 

Can this method be used when posting and patching the applicant record, or is this to only access the information?

i.e. https://platform.reapit.cloud/applicants/?extrasfield=aPotClient  
or 
https://platform.reapit.cloud/applicants/******?extrasfield=aPotClient 

Kind regards,

Philip.

**Comment by HollyJoyPhillips** [comment]
Hi @ebuildwebsolutions, semi structured data is read only.

**Comment by ebuildwebsolutions** [comment]
Hi Holly,

The estate agent needs to be able to update this field when adding or editing an applicant record.

Kind regards,

Philip.

**Comment by HollyJoyPhillips** [comment]
Hi @ebuildwebsolutions, unfortunately, it is only read only at the moment because of the way the data is structured. However, there maybe another option. I will put this ticket into review for a wider discussion with the team and update this ticket following that discussion.

**Comment by ebuildwebsolutions** [comment]
Hi Pete,


How is the aPotClient<https://platform.reapit.cloud/applicants/******?extrasfield=aPotClient> field updated when posting and patching the applicant record, as I don't see it in the API?

Kind regards,

Philip.

________________________________

**Comment by plittlewood-rpt** [comment]
Hi @ebuildwebsolutions please see note on the original comment that describes how this has been implemented. potentialClient has now been added as a structured field so we can support writeback. You will need to update your app accordingly. Thanks
