### ISSUE TITLE
Add Renting Position information to ApplicantRentingModel REST API 

### ISSUE THREAD

**Issue by ss-dimasm** [reapit/foundations#8035]
**Is your feature request related to a problem? Please describe.**
We can't add the `Renting Position` information via REST API, because we couldn't find the value of `Renting Position` in `ApplicantRentingModel` that could handle it.

**Describe the solution you'd like**
Is it possible to add a value of `Renting Position` in `ApplicantRentingModel`? so we can use it in some of HTTP operations

**Additional context**
![Screenshot 2022-11-01 163321](https://user-images.githubusercontent.com/96416644/199204979-1affe932-04b5-47fe-a152-7872e3cf24b2.png)

**Specification**
- Project: Reapit.Services.Applicants
- Add `positionId` to the CreateApplicantRentingModel and UpdateApplicantRentingModel so that this field can be updated accordingly. Validate the ids in the same way we do for some existing fields using the `RetrieveValidateConfigurablePropertiesAsync` method. This list is configurable so needs validating against data from the configuration service

**Comment by AshDeeming** [comment]
Hi @ss-dimasm 
This is currently available using both the Configuration &  Applicant endpoints:

![image](https://user-images.githubusercontent.com/61687775/199223750-ca2329b8-d592-4a1f-a51e-18e4a78b7864.png)
![image](https://user-images.githubusercontent.com/61687775/199223816-6da9e6f0-9b8d-4c33-9f32-57fdb80c1088.png)
https://developers.reapit.cloud/swagger

**Comment by ss-dimasm** [comment]
Hi @AshDeeming , thanks for the reply

From my side I didn't found the `positionId` of `renting` object, is it in Applicant model?
here is what I can see about the `renting` object of Applicant Model
![Screenshot_2](https://user-images.githubusercontent.com/96416644/199226176-7f0f83ba-2f7d-44d6-a1f5-e1aa7a2a0dee.png)

**Comment by ss-dimasm** [comment]
Hi @AshDeeming , now I got the point thanks and it's already on the platform
the picture above is a screenshot when I saw the POST Applicant model
is clear now

**Comment by AshDeeming** [comment]
Thanks @ss-dimasm 
My screenshot is from the /applicants/[id] model

**Comment by ss-dimasm** [comment]
Hi @AshDeeming , have give a try to POST and PATCH the request to Applicant Endpoint with the `renting.positionId` payload but it won't work. Could we add this feature in the Platform that able to handle this? 

Thanks

**Comment by ss-dimasm** [comment]
hi @AshDeeming , sorry to mention again but is it possible to have this feature in the Platform? (with POST and PATCH operations)

**Comment by AshDeeming** [comment]
HI @ss-dimasm 
I've associated this ticket to #8036 for review
