### ISSUE TITLE
How to add information of `Potential Client`, `Property`, and `Agent` in Applicant record via REST API

### ISSUE THREAD

**Issue by ss-dimasm** [reapit/foundations#8036]
**Summary**
1. We have a requirement that need to add `Potential Client` in Applicant record via REST API, is there any way that we able to do that? if so how can be? is it possible to have them in some of http operations?
2. How can we add the `property` and `agent` value from Applicant status modal (see appendix 1 and 2) in Applicant record via REST API?. Any guide or implicit requirement to handle and have this on some of http operations?

**Detail and or supporting links and screenshots**
![Appendix 1](https://user-images.githubusercontent.com/96416644/199207948-da385e88-6c59-48da-8d41-bcc8936b2657.png)
Appendix 1
![Appendix 2](https://user-images.githubusercontent.com/96416644/199207821-de887bcd-6a04-4d5c-9355-b50750926df6.png)
Appendix 2

**Comment by AshDeeming** [comment]
Hi @ss-dimasm 
The information held within the selling position & status is Agency Cloud config driven. 
These configurations are not currently editable via the Platform however you can call the relative config to check what each client has setup

**Comment by ss-dimasm** [comment]
Hi @AshDeeming , thanks for the reply.
Is it clear for question two, what about the first question? can I get more details about it?

**Comment by AshDeeming** [comment]
No problem @ss-dimasm 
Am I correct in understanding that you're requirement is to be able to PATCH the /applicants/[id] with the 'potential client' string?

**Comment by ss-dimasm** [comment]
more like when we create new applicant, so using the POST method with the possibility to have a 'potential client' payload also

**Comment by ss-dimasm** [comment]
but for further, we will also use it with PATCH the /applicants/[id]

**Comment by ss-dimasm** [comment]
Hi @AshDeeming , want to summarize of the 2 comments above there, the requirement is to have a `potential client` payload with the POST and PATCH method

**Comment by AshDeeming** [comment]
Thanks @ss-dimasm 
I'll put this in the relevant project for review during the next refinement session

**Comment by HollyJoyPhillips** [comment]
Relates to ticket https://github.com/reapit/foundations/issues/8027, requires further refinement

**Comment by HollyJoyPhillips** [comment]
Hi @ss-dimasm, we've completed the work on #8027, please can you confirm this has resolved your issue so we can close this ticket. Thank you.

**Comment by HollyJoyPhillips** [comment]
Great, thank you for confirming.
