### ISSUE TITLE
Cannot create WorksOrders without typeID or tenancyId

### ISSUE THREAD

**Issue by jaketpmadev** [reapit/foundations#8039]
**Describe the bug**
Cannot make successful POST request to WorksOrders without 'typeId' or 'tenancyId'

**To Reproduce**
Submit POST request to 'WorksOrders' without 'TypeId' or 'TenancyId'.

**Expected behaviour**
Create the WorksOrder as other records exist without TypeId, WorksOrders may be necessary for a property without an active tenancy.

--- API Response ---
```
{
  "errors": [
    {
      "field": "typeId",
      "message": "'typeId' must not be empty."
    },
    {
      "field": "tenancyId",
      "message": "The value provided must be in a valid format and contain 9 characters"
    }
  ],
  "statusCode": 422,
  "dateTime": "---",
  "description": "One or more validation failures have occurred. Please refer to Errors list for details"
}
```

**Specification**
- Project: Reapit.Services.WorksOrders
- Remove requirement for TypeId being present in CreateWorksOrderCommandValidation - I'm not sure why we did this originally but it doesn't need to be there
- Where we are validating for TenancyId, check for null OR empty string (rather than just null)
- Ensure tests are updated to cater for these changes

**Comment by jaketpmadev** [comment]
Hi Ash, 

Thanks for your response, the field is required in the API but not for existing records? Is there a list of values we should use?

Regarding the tenancyId, API dos state this is not a required field but the reponse states it is. Do you know why this is?

Kind regards, Jake.

**Comment by HollyJoyPhillips** [comment]
Hi @jaketpmadev this section in the documentation should help: https://foundations-documentation.reapit.cloud/whats-new#journals-api

Also, we have created the following ticket to update the documentation to make the typeId's visible: https://github.com/reapit/foundations/issues/8056

**Comment by jaketpmadev** [comment]
Hi Holly, 

Thank you for your resonse and updating the API documentation. 

How do we overcome tenancyId coming back as required if the property does not have an active tenancy while posting worksOrders?

Kind regards, Jake.

**Comment by HollyJoyPhillips** [comment]
Hi @jaketpmadev, we'll check the validation for typeID but tenancyID is not required if you pass it as null/emit it it should work. It will error if you pass it as blank.
