### ISSUE TITLE
Transaction download error

### ISSUE THREAD

**Issue by quigger** [reapit/foundations#8042]
On this page:
https://developers.reapit.cloud/analytics/costs

I try to download my transaction history:
![image](https://user-images.githubusercontent.com/644502/199313027-4bcd8a77-60eb-4439-9ee4-0ef98e8da730.png)

But I get this error:
![image](https://user-images.githubusercontent.com/644502/199312937-f6d81d34-3f92-4920-aed5-2343afee3bf8.png)

Is there an issue?

Or is this the data that may have been downloaded/expected:
![image](https://user-images.githubusercontent.com/644502/199313298-0d8cceb5-ce84-470f-bf2b-485e83a02532.png)

**Comment by HollyJoyPhillips** [comment]
Hi @quigger, we've identified the issue and it will be resolved as part of this ticket https://github.com/reapit/foundations/issues/8077

**Comment by plittlewood-rpt** [comment]
Please track #8077 for updates

**Comment by HollyJoyPhillips** [comment]
Hi

**Comment by quigger** [comment]
Sorry I missed this.

> Please can you try and select an app first before downloading the transaction history and verify if it allows you to download the CSV?

It doesn't do anything. Doesn't error either. Seems it does nothing.

**Comment by quigger** [comment]
Before selecting an app:
![image](https://user-images.githubusercontent.com/644502/205711461-e9eee7c7-ae1b-47df-84ee-4d0efb468862.png)

After selecting an app:
![image](https://user-images.githubusercontent.com/644502/205711540-09c8365d-3016-4f59-9c7d-407b1b9be47b.png)

After pressing the icon:
![image](https://user-images.githubusercontent.com/644502/205711789-0302ed4e-7187-4d82-a90f-55f669e5fd3a.png)

Sometimes I get this error:
![image](https://user-images.githubusercontent.com/644502/205712089-35888312-1892-48a6-83de-b38466559851.png)

Sometime I do get some data (it seems) - 2 attempts out of 6 worked.

However, I do not see any billing information in the data received?
It's called transaction history but it's only logs of calls and not costs - is that correct?

---

The overall aim (for your reference) is to see costs per client per app per dated period. So we can see what charges are incurred per client/app/period. We want to use this to optimise our setup.

**Comment by quigger** [comment]
Hi @AshDeeming - any update on this one?

**Comment by HollyJoyPhillips** [comment]
Hi @quigger, are you still getting an error downloading the transaction data? 

Yes, it is by design due to the how the data is extracted. We have the following ticket https://github.com/reapit/foundations/issues/8041 in our long term backlog to look into surfacing this information by client. It's not a feature we can commit to developing at the moment due to other priorities but understand it would be beneficial to you going forward. We regularly review our backlog and will update the ticket where applicable.

**Comment by quigger** [comment]
> are you still getting an error downloading the transaction data?

Yes.

**Comment by HollyJoyPhillips** [comment]
Hi @quigger, thanks for confirming, we'll take another look.

**Comment by HollyJoyPhillips** [comment]
Hi @quigger Sorry for the delay, we have created the following ticket which we believe will resolve the issue: https://github.com/reapit/foundations/issues/8379
