### ISSUE TITLE
Need to know where to add strapline field so that we can fetch in api call

### ISSUE THREAD

**Issue by sanjayisg** [reapit/foundations#8044]
Hi There,

I just wanted to know where to add strapline field in RPS, so that we can fetch in property api call.

[areaId] => 
[strapline] => 
[description] => 
[longDescription] =>

Thanks,

Sanjay Gupta

**Comment by AshDeeming** [comment]
Hi @sanjayisg 
Please see the swagger details on;https://developers.reapit.cloud/swagger
![image](https://user-images.githubusercontent.com/61687775/199471970-4455f25e-92dd-4b85-b9e6-f21859dc33b3.png)
