### ISSUE TITLE
Download certificate documents via the Rest API

### ISSUE THREAD

**Issue by andortamas** [reapit/foundations#8054]
Hi,

Our app needs to download the certificate documents (Gas, Electrical, EPC) via your Rest API. These documents are not associated to a tenancy/property, so filtering by passing the associatedType and associatedId is not working. Can we download them somehow?

Kind Regards,
Andor

**Comment by AshDeeming** [comment]
Hi  @andortamas 
Please see the below areas of the documentation:
https://foundations-documentation.reapit.cloud/platform-glossary#document
https://foundations-documentation.reapit.cloud/api/api-documentation#retrieving-data

**Comment by andortamas** [comment]
Hi Ash,

Sorry, but this is not what I have asked. I can download the documents by ID without any problem.

I'd like to download the **gas certificate document**:

1) I get the certificate types with {{platform_api}}/configuration/certificateTypes It says that Gas safety id is GS
`{
    "id": "GS",
    "value": "Gas Safety"
}`

2) Calling the {{platform_api}}/documents/GS/download returns with this:

`{
    "statusCode": 404,
    "dateTime": "2022-11-10T13:45:47.6805975Z",
    "description": "Entity \"Document\" (GS) was not found."
}`

Hope you make sense.

**Comment by AshDeeming** [comment]
Thanks @andortamas 
I've moved this for our back end team to review.

**Comment by plittlewood-rpt** [comment]
Hi @andortamas I'm not completely sure I follow your initial report however based on what I think I understand:

- Certificates are associated to a property, and will therefore be accessible at /properties/{id}/certificates
- The model returned from this endpoint will contain an item in the _links collection that allows you to navigate to the document(s) associated with the certificate. Each certificate has it's own reference number.
- You can use the information from the /documents endpoint to then download the appropriate file. Please note that the document id is NOT the same as the certificate id. They are two separate entities.

Can you review based on your requirements and let me know if this resolves your issue please?

**Comment by andortamas** [comment]
Hi @plittlewood-rpt,

Thanks for your answer. It seems I can download the certificate files now.

Many thanks for your help.

Regards,
Andor
