### ISSUE TITLE
Can I use Foundations for a client?

### ISSUE THREAD

**Issue by adamjamesevans** [reapit/foundations#8055]
**Summary**
I have been asked by the support team (Ticket #RSD-206287) to raise this ticket to ask if our mutual client, Harris Shields can use the foundations API and our app.

**Detail and or supporting links and screenshots**
Currently, we use the SOAP API but there are issues that can not be resolved due to it being a legacy API so investigating if we can upgrade them to Foundations App API. 

The support agent did not know if this was possible with the client's current version of the platform. 

Do note, I am **not authorised** to speak on the client's behalf for any Reapit product and service upgrades which may or may not involve change in CRM, process or cost. This is purely an investigatory question of if they are currently compatible with the Foundations App API so the correct steps can be taken. Thanks

**Comment by AshDeeming** [comment]
Hi @adamjamesevans 
The developer portal is available to our clients & they can speak to their CSM regarding this. 

If you are looking to develop an app via the Developer Portal for Reapit Customers to access via our AppMarket, you can speak to our Partnership Manager:  jhennessy@reapit.com

The documentation can be accessed via the below in the interim;
https://foundations-documentation.reapit.cloud/api/api-documentation

**Comment by adamjamesevans** [comment]
Hi @AshDeeming 

We already have a Foundations App that we use with several other clients. The question is, if we can install that app with this client. 

I am not sure what you mean that the client can use the dev portal as I thought that was for suppliers mainly to create apps for integrations. 

We were told when they became a new client that we could not use our Foundations App and had to use the SOAP API. I am trying to figure out if the service or product they use with you is compatible with the Foundations API/App as I understand it is a new product. 

The support team have asked me to mention to you that they are a Guild client to assist.

I am struggling to get ahold of their CSM, Carly Sullivan, at the moment. The client or support team do not have their contact details. If you happen to know them, please pass them on.

**Comment by AshDeeming** [comment]
Hi @adamjamesevans 
The mentioned client has other apps installed/enabled via the AppMarket, therefore they will be able to do the same with your app once submitted & approved

**Comment by adamjamesevans** [comment]
oh! Odd that we were told that we couldn't then. Ok, will speak with the client about installing our app then. Thanks
