### ISSUE TITLE
Spike: AgencyCloud login screen

### ISSUE THREAD

**Issue by willmcvay** [reapit/foundations#8075]
**Background context or User story:**

_We need to investigate any additional custom work and considerations to make RC work inside of AC as a straight drop in_

**Specification or Acceptance Criteria:**

Outcome;

- Report and track any work in AC itself
- Raise any additional tickets to make RC work with AC in the SSO project

**Comment by joshbalfour** [comment]
Broken out into #8583 #8584  #8599, Duplicated by #8617
