### ISSUE TITLE
There should be a self service settings page for RC users

### ISSUE THREAD

**Issue by willmcvay** [reapit/foundations#8078]
**Background context or User story:**

_Users need to be able to manage their password, set up and configure MFA devices inside of RC_

**Specification or Acceptance Criteria:**

- User should be able to change a password
- User should be able to follow a forgotten password flow to re-set their PW
- Users should be able to setup an MFA device
- Users should be able to manage MFA devices

**Comment by bashleigh** [comment]
Unable to use recovery flow, seems the flow needs to be enbled? Guessing ory kratos setup?

Unable to start password reset flow (whilst logged in) password rejected for reason "password vulnerable" found in leaked db
