### ISSUE TITLE
The platform token authorizer should be able to switch validation keys

### ISSUE THREAD

**Issue by willmcvay** [reapit/foundations#8079]
**Background context or User story:**

_The platform token authorizer should be able to toggle which .jwks file it uses to validate tokens, either Cognito or Ory for testing until migrating fully to Ory_

**Specification**
- Project: Reapit.Lambdas.GatewayAuthorizer
- Update `TokenInspector` class to be able to dynamically determine which set of JWKs to use based on content from the token. This should be fairly straightforwards as the token is read to understand the issuing user pool (in the case of Cognito) before hitting the JWKs endpoint

**Comment by plittlewood-rpt** [comment]
Agreed this can be merged
