### ISSUE TITLE
Spike: Investigate cross region replication

### ISSUE THREAD

**Issue by willmcvay** [reapit/foundations#8090]
**Background context or User story:**

_We need out IDP solution to operate in two regions for greater redundancy and reduced latency, with cross region replication_

**Specification or Acceptance Criteria:**

- Investigate how best to configure our core Ory services to manage multi region replication
- Excludes lambdas and web apps that are served at the Edge by default

**Comment by joshbalfour** [comment]
Work done here https://github.com/reapit/reapit-connect/pull/85
Issue discovered and raised is opened here #8619
