### ISSUE TITLE
Add "specialFeatures" information via Applicant's REST API

### ISSUE THREAD

**Issue by ss-dimasm** [reapit/foundations#8092]
**Is your feature request related to a problem? Please describe.**
We have requirement to add "Must Have" options value information via Applicant REST API, we only able to do that in AC but not with REST API.

**Describe the solution you'd like**
Add "specialFeatures" value to Applicant's model REST API with HTTP operations especially on POST and PATCH operations.

![Screenshot 2022-11-07 113213](https://user-images.githubusercontent.com/96416644/200227386-1d9be4c7-5ec7-42f0-950c-b6ebd006fe30.png)

**Specification**
- Projects: Reapit.Services.Applicants
- Review whether the existing department handling mechanism can be used to handle the special attributes column
- Add a new `string[]` property `specialFeatures` to the `CreateApplicantModel` and `UpdateApplicantModel` classes and associated commands
- Build in ability for a developer to provide a collection of specialFeatures that are then stored against the applicant. 
- Special features can be tied to the type of applicant (so there can be sales specific special features and lettings specific special features). We should build some validation around this that:
  - Ensures any specialFeatures are valid
  - Ensures any specialFeatures are valid for the specific type of applicant (where applicable)
  - Any validation failure should result in an appropriate message with a 400 Bad Request response
- Ensure this is appropriate tested

**Comment by AshDeeming** [comment]
Hi @ss-dimasm 
Which client does this relate to please?

**Comment by ss-dimasm** [comment]
Hi @AshDeeming , it's Reapit Digital Product Team
