### ISSUE TITLE
Update Marketplace API to include implementation of IdentityClient for Ory

### ISSUE THREAD

**Issue by plittlewood-rpt** [reapit/foundations#8093]
**Background context**
The Marketplace API is one of the projects that interacts dircetly with Cognito. We should add a second implementation of IIdentityClient that interfaces with Ory. There may not be an SDK we can use, so will need to craft something (a package is sensible here, given it'll be used in other services)

**Specification**
- Project: Marketplace
- Understand Cognito interactions and implement same logic for Ory

**Comment by joshbalfour** [comment]
Child of #8582
