### ISSUE TITLE
Keeping separate production and sandbox environments

### ISSUE THREAD

**Issue by nikolai-momot-thirdfort** [reapit/foundations#8095]
**Summary**
Our team is currently developing an integration with Reapit and are preparing for a launch in the immediate future.
 
We prefer to keep two environments: sandbox for testing new features, and production for customer ready deployments.

We require some clarification to make sure that we are aligned with what is required:
1. Does keeping separate environments require us to create separate apps in the Reapit interface?
2. Do new releases to our production app require any sort of approval from the Reapit side?
3. Since the Reapit IaaS offering is still in Beta, would self hosting the application be the recommended approach to serving a production integration?

**Comment by AshDeeming** [comment]
Hi @nikolai-momot-thirdfort 

Please see the FAQ section of the documentation which may assist with your first two questions:
https://foundations-documentation.reapit.cloud/faqs#my-app-is-live-and-has-been-installed-how-do-i-request-a-new-permission

With regards to Iaas - If you are interested in potentially trailing this please see the below details, alternatively hosting yourself:
https://foundations-documentation.reapit.cloud/app-development/iaas-coming-soon#public-beta

**Comment by nikolai-momot-thirdfort** [comment]
Hi @AshDeeming 

> Please see the FAQ section of the documentation which may assist with your first two questions:
https://foundations-documentation.reapit.cloud/faqs#my-app-is-live-and-has-been-installed-how-do-i-request-a-new-permission

This link deals with assigning new permissions to an installed app, my questions pertained to separating sandbox/production environments and release processes.

**Comment by AshDeeming** [comment]
Hi @nikolai-momot-thirdfort 
you can utilise sandbox data for any none listed apps - once in production, any releases you do can be within unless additional permissions are required.

**Comment by nikolai-momot-thirdfort** [comment]
@AshDeeming Apologies for the delay.

The issue came from one of our partners and we are awaiting further details.

What we know for certain is that the error occurs when they try to launch the app from the apps section of Reapit.

**Comment by AshDeeming** [comment]
Hi @nikolai-momot-thirdfort I'll close this ticket due to no further info however please create a new ticket if further details provided etc
