### ISSUE TITLE
413 response when sending fileData for file < 6MB

### ISSUE THREAD

**Issue by nroper** [reapit/foundations#8098]
Please take a look at our FAQ's before submitting an issue, as your question may already be covered in the documentation https://foundations-documentation.reapit.cloud/faqs

**Summary**

**Describe the bug**

A 413 response is sometimes being returned when attempting to POST a new identityChecks record with `fileData` for a file less than the specified 6MB limit.

**Detail and or supporting links and screenshots**

We are using an integration app to make updates to client data. This includes updates to contact statuses by POSTing new `identityChecks` records with associated files. 

At present we are using the `fileData` property and passing the appropriate raw file data and this has been working fine, but we have recently had some issues where the API request has returned a 413 response, indicating that the file size is too large, but where the size is actually around 4.9MB - which is under the 6MB limit specified.

Are there any circumstances that could apparently cause this limit to be exceeded even though the size of the original file is less than 6MB?

We could try using the pre-signed URL approach, but would prefer to only do that if the file is large.  We're also awaiting Reapit's completion of more extensive documentation for that - see ticket here: https://github.com/reapit/foundations/issues/6684

Thanks

**Comment by plittlewood-rpt** [comment]
Hi @nroper - the base64 encoded version of the file could take the payload over the 6mb limit. Can you check the size of the entire payload (including the other properties) to see if that's under 6Mb or not?

**Comment by nroper** [comment]
Hi @plittlewood-rpt thanks for the quick response.  Ah, hadn't thought of that - yeah I'll try checking that shortly and will post details.

**Comment by nroper** [comment]
If we need to use the pre-signed url approach, can you confirm whether the request to submit the file to the pre signed URL would be a PUT or POST, and what the payload/body should look like?  Does the file data need encoding for example? Thanks

**Comment by plittlewood-rpt** [comment]
Hi @nroper - a video to support pre signed URLs is now live at https://www.youtube.com/watch?v=lBYzD7T5_bQ - hopefully this helps - please let me know

**Comment by HollyJoyPhillips** [comment]
Closing due to housekeeping.
