### ISSUE TITLE
Is it possible to get Tenancy Guarantor information via the Applicant or Tenancy API?

### ISSUE THREAD

**Issue by otrace** [reapit/foundations#8103]
Is it possible to get Tenancy Guarantor information via the Applicant or Tenancy API?

**Comment by AshDeeming** [comment]
Hi @otrace 
Guarantor information from the Tenant details is not currently surfaced via the Platform

**Comment by otrace** [comment]
Thanks @AshDeeming do you know if it is on the roadmap?

**Comment by AshDeeming** [comment]
Hi @otrace,
There isn't any open feature requests or milestones for this. 
I would therefore suggest logging a [feature request](https://github.com/reapit/foundations/issues/new?assignees=&labels=external-request%2C+needs-triage&template=feature_request.md&title=) for review
