### ISSUE TITLE
Patching unmapped attributes

### ISSUE THREAD

**Issue by soilleir** [reapit/foundations#8104]
Are we able to patch unmapped attributes in applicant and property records?

**Comment by AshDeeming** [comment]
Hi @soilleir 
These are GET only 
Any new attributes would need to be requested by the client to be added to their Company configuration via AgencyCloud.

**Comment by soilleir** [comment]
I am the client as this is an internal app and the attributes are already
in the configuration and I can see them in get requests as unmapped.  The
issue is we cannot Patch these attributes.   Is this on the dev road map to
allow patching of these attributes or is there a way to map them?

**Comment by soilleir** [comment]
Hi ash are you able to elaborte on the above please?  Not entirely sure what you mean about "mapped using the unmappedAttributes value"

**Comment by AshDeeming** [comment]
HI @soilleir 
Following on from the previous documentation section provided, this links to the below, which should provide more detail;
https://foundations-documentation.reapit.cloud/platform-glossary#interpreting-department-data
