### ISSUE TITLE
Patching sellingPositon doesnt seem to be working

### ISSUE THREAD

**Issue by soilleir** [reapit/foundations#8105]
We are working on some automation to update Applicant information.  The seems to be an issue with Patching the sellingPosition getting a success status (204) but the record isnt updating. I've masked the customer ID (***)  in the example below.  Ive tried nothingToSell and sellingWithUs so far but still nothing updating.  Please note reasonId is working fine  it just seems to be the sellingPosition

e.g. 

{
    "uri": "https://platform.reapit.cloud/applicants/EDI123084",
    "method": "PATCH",
    "headers": {
        "accept": "application/json",
        "api-version": "2020-01-31",
        "Authorization": "*sanitized*",
        "reapit-customer": "***",
        "If-Match": "\"CD85FEAD5A5BA12CA2FFCE0CB1B83C2B\""
    },
    "body": {
        "sellingPosition": "nothingToSell"
    }
}

**Specification**
- Project: Reapit.Services.Applicants
- Try to replicate the issue by setting an applicant's selling position to `nothingToSell` via the PATCH endpoint and observe results. Try with different iterations of data that get amalgamated together for storage in the app.position field

**Comment by soilleir** [comment]
sorry forgot to include the resulting output 
{
    "statusCode": 204,
    "headers": {
        "Connection": "keep-alive",
        "x-amzn-RequestId": "452ada0b-1cc1-483b-870c-01c647dbeb6e",
        "x-amz-apigw-id": "bEhjfGiFLPEF77g=",
        "x-amzn-Remapped-Server": "Kestrel",
        "X-Amzn-Trace-Id": "Root=1-6364e2e2-2aaf93af66567fb400ee327e;Sampled=0",
        "x-amzn-Remapped-Date": "Fri, 04 Nov 2022 10:01:10 GMT",
        "Date": "Fri, 04 Nov 2022 10:01:10 GMT",
        "Content-Length": "0",
        "Content-Type": "application/json"
    }
}

**Comment by soilleir** [comment]
Slightly worried that this is now working despite us not amending our code/automation.

**Comment by AshDeeming** [comment]
Hi @soilleir 
Please could you advise the CustomerId via the below email: 
sinfo@reapitfoundations.zendesk.com
Thanks in advance

**Comment by AshDeeming** [comment]
Hi @soilleir 
Thanks for advising - from reviewing the Applicant record in question, they appear to be Inactive

**Comment by soilleir** [comment]
What would that matter though? Applicant records marked as inactive simply
mean they aren't actively matched to properties.  It doesn't mean that we
shouldn't be able to update their information via the api.  Some agents
wouldn't mark the applicant active for matching without being verified and
all the requirements filled in.  Also some applicants only interested in a
particular property wouldn't be marked as active and therefore matched to
other properties they are not interested in.

**Comment by AshDeeming** [comment]
Apologies @soilleir 
I'll move this ticket for the relevant team to review in more detail
