### ISSUE TITLE
Nicol & co Estate agents - Soap Api endpoint

### ISSUE THREAD

**Issue by MarkFieldhouse** [reapit/foundations#8110]
@joshbalfour @Shaun-Farrell @bashleigh 

Hi 

I hope you're well. 

We are developing a new site for Nicol and Co estate agents. To get the data our developer needs a SOAP endpoint. We are working with a plugin for Hive that requires a soap api endpoint. Can you please keep or add the live property data in the soap endpoint as well.

Please don't remove/stop the current REST api endpoint as we are using that on the live site. Once our development is done, we will let you know to disable the rest endpoint. 

If you can come back to me on this that would be great. 

Thanks again, 

Mark

**Comment by AshDeeming** [comment]
Hi @MarkFieldhouse 
I'm not sure I understand you're request 

The SOAP API is the older webservice API - This is unsupported & we now advise 3rd parties to use the Foundations Developer portal (REST API)
Are you or the Client registered for the Developer Portal?

**Comment by MarkFieldhouse** [comment]
@AshDeeming Yes Nicol and Co https://www.nicolandco.co.uk live site uses rest api.

**Comment by MarkFieldhouse** [comment]
@AshDeeming  can you come back to me on this asap? As its quite urgent.

**Comment by AshDeeming** [comment]
Hi @MarkFieldhouse 
We can only assist with Platform/REST API queries here
We do not support the SOAP API however we'll make the relevant CSM aware of this ticket

**Comment by MarkFieldhouse** [comment]
@AshDeeming can you show me where to log this ticket with them directly in that case?

**Comment by MarkFieldhouse** [comment]
HI @AshDeeming Who is the relevant CSM for Nicol and co? And how do I get into contact with them?

**Comment by AshDeeming** [comment]
Hi @MarkFieldhouse 
I understand the CSM has provided any required details.
