### ISSUE TITLE
Error on import processes

### ISSUE THREAD

**Issue by scruffmcduff** [reapit/foundations#8111]
We have an issue tryig to import properties from reapit.
We use the Property Hive import tool to do this.

We set up the customer ID on import and other configurations related to the Reapit foundation API last week.

https://developers.reapit.cloud/apps
However, we were getting an error on import processes. We have tried the import again this morning and still get the same error.

See
https://share.getcloudapp.com/lludPnGx
https://share.getcloudapp.com/rRuQYjLO

Is that something you can help with?

**Comment by AshDeeming** [comment]
Hi @scruffmcduff 
Have you reported this to Property Hive? 
If you are using a 3rd party app to import properties, they will be best placed to review & advise. 

If they believe there is a bug on the Platform, we will need them to report with details and examples.
