### ISSUE TITLE
Applicant EndPoint not returning Buying Postion when it is set to Pending Mortgage

### ISSUE THREAD

**Issue by soilleir** [reapit/foundations#8112]
When an Applicant's has Pending Mortgage set as their buying position the get Get Applicant\{id} endpoint is returning null for buying positions (positionId).  See example below.  We dont have this issue with the other buying position options only Pending Mortgage.

Similarly we get a failure when trying to patch an applicant with a buying status Pending Mortgage

https://platform.reapit.cloud/applicants/EDI123084

![image](https://user-images.githubusercontent.com/95375239/201135071-03d2dc64-2c4e-4919-9d44-f0870fb75760.png)

![image](https://user-images.githubusercontent.com/95375239/201136235-1a5c9287-e838-46cc-a139-4d1eb41cfc59.png)

**Specification**
It looks like this is being caused by an incorrect configuration of the core options in the configuration service. I suspect resolving this will resolve the issue with patching. Before proceeding replicate this problem by running both the configuration and applicant services locally

- Service: Reapit.Services.Configuration
- Correct the core list configuration in the `ApplicantBuyingPosition` enum. 
- Correct default options and codes are: Cash Buyer (CB), First Time Buyer (FB), Pending Own Sale (PS), Pending Mortgage (PM), Buying Agent (BA)
- Once this is done, run GET tests in the applicants service to check that the problem with mapping the value in the read model is resolved. If it is, also confirm the issue with POST/PATCH is also resolved

**Comment by AshDeeming** [comment]
Hi @soilleir 
Please could I confirm that you have used the configuration/buyingPosition  endpoint to obtain the possible options? 
![image](https://user-images.githubusercontent.com/61687775/201296599-d4079e76-8be5-41bb-b26f-2f9050f01283.png)

**Comment by soilleir** [comment]
I will do that later but Pending Mortgage it is a core Reapit option.

It wouldn't explain why it is null with a get request  though on a core
status

**Comment by soilleir** [comment]
This is so daft.  Why is the API not using AgencyCloud's own core default statuses?!!
![image](https://user-images.githubusercontent.com/95375239/201300743-e6bead58-f30d-4b36-8d90-8d5b1b95afb0.png)

We havent reconfigured any buying statuses and are using the core statuses and the API doesnt return the Statues for Pending Mortgage which is already set against our applicant records and is a core status.  

![image](https://user-images.githubusercontent.com/95375239/201301079-6753882e-097a-470b-bd42-f8ca630f5d1d.png)

**Comment by AshDeeming** [comment]
Hi @soilleir 
I've moved this into the relevant project for review

**Comment by soilleir** [comment]
Any update on this?  It is definatley not working as it should  and is a fault.

Just ran a patch using on Buying Position based on the configuration/buyingpositions options and according to the options listed "BA" should be "Pending Mortgage" but the end result in the front end on the Reapit Applicant record is "Buying Agent" which ties in with the default core list I screenshot and send over in an earlier update

**Comment by plittlewood-rpt** [comment]
Hi @soilleir please can you let me know the id of the customer this relates to?

**Comment by plittlewood-rpt** [comment]
@soilleir I think I've found the issue here and have added a specification to this ticket so we'll get this resolved as soon as we can
