### ISSUE TITLE
API Endpoint not returning an AgentRole

### ISSUE THREAD

**Issue by katedeedman** [reapit/foundations#8124]
**Describe the bug**
My company (Fixflo) uses the Reapit API to import entities onto our system. We've had a report of an API endpoint not returning the agentRole. 

**To Reproduce**
Steps to reproduce the behaviour eg:

- When making an api call to "properties/HEO220142" endpoint to get the property it returns no agentRole 
- When making an api call to "tenancies/HEO220142" endpoint to get the tenancy details of that same property, it returns the agentRole. 

**Expected behaviour**
- It is expected to get the same agentRole on both property and tenancy api calls.
- For any other property, the property api call returns the agentRole as expected.

**Additional context**
Hi Reapit team,

This bug has been raised by our client. 

Would you please investigate why this API endpoint is not returning the agentRole as expected? 

Many thanks!

Kate

**Comment by AshDeeming** [comment]
Hi @katedeedman 
Please could you confirm the customer(s) this is impacting please - sensitive info can be sent to: sinfo@reapitfoundations.zendesk.com

**Comment by katedeedman** [comment]
Hey @AshDeeming,

It's Hunters Lettings - Burgess Hill.

**Comment by AshDeeming** [comment]
Thanks @katedeedman 
From checking the customers database - properties/HEO220142 - This is set as a 'Not Managed' property

with regards to tenancies/HEO220142 - this records relates to a Finished tenancy
