### ISSUE TITLE
What updates the updated date?

### ISSUE THREAD

**Issue by katedeedman** [reapit/foundations#8125]
Please take a look at our FAQ's before submitting an issue, as your question may already be covered in the documentation https://foundations-documentation.reapit.cloud/faqs

**Summary**

Hello Reapit team!

I wondered if you had a list of things that do and don't update the updated date? It would be useful for us to know for troubleshooting purposes.

Thank you!

Kate (Fixflo)

**Detail and or supporting links and screenshots**

**Comment by AshDeeming** [comment]
Hi @katedeedman 
Please could you confirm what record type you are referring to?

**Comment by AshDeeming** [comment]
Hi @katedeedman 
I'll close this ticket due to no further information provided however please feel free to create a new ticket with any questions & associated information for review.
