### ISSUE TITLE
Ability to access certain fields or types in API 

### ISSUE THREAD

**Issue by awogan06** [reapit/foundations#8128]
We are looking to ringfence specific referral types for the development of an private app with our Financial Services systems provider.

**Comment by AshDeeming** [comment]
Hi @awogan06 
Please could you provide more information/details

**Comment by awogan06** [comment]
We are looking to build an app that will integrate with AC allowing up pass Financial Services referrals directly into our FS system.    We need to be able to ringfence the type of referrals to our financial referrals element only  ie. using codes  RPT02 (Mortgages) and RPT03 (L&P), we do not want access to any other referrals types for this function.   
 
We are hoping to include the following data within the referral for both Mortgages and Life & Pension referrals:-
 
Applicant name
Mobile phone number
e-mail address
Notes field (to be developed using meta data within RPS for supporting referral context)
Neg name
Neg branch
Reapit Referral ID

**Comment by HollyJoyPhillips** [comment]
Internal session scheduled 21/11 @plittlewood-rpt, @willmcvay to outline specification

**Comment by plittlewood-rpt** [comment]
The work has now been scoped in the following tickets:

#8189 #8190 #8192

**Comment by plittlewood-rpt** [comment]
Hi @awogan06 - Please see the above tickets for further updates. I'll close this one now to avoid duplication
