### ISSUE TITLE
Expected commission field

### ISSUE THREAD

**Issue by elizabethhamlin** [reapit/foundations#8130]
Morning,
Please can you add the expected commission to the schema. It is a pick column in Reapit but I cannot see where it actually pulls from.
Thanks 
Lill

**Comment by plittlewood-rpt** [comment]
Hi @elizabethhamlin - I can't see which column you are referring to and don't want to make any assumptions. Please can you email a screenshot along with which brand's database you're looking at over to [sinfo@reapitfoundations.zendesk.com](mailto:sinfo@reapitfoundations.zendesk.com) please?

**Comment by elizabethhamlin** [comment]
Hi Pete
I've sent over an email as requested.
Thanks 
Lill

**Comment by plittlewood-rpt** [comment]
Thanks for that. I've had a look and I think the information you want is already in the schema. If you have a look at the PROPERTY_SALES_PIPELINE_FEES data, you will see a FEE column. If the property has a fixed commission, it will be displayed here regardless of the offer price. If it is a percentage commission, the fee will be calculated against the offer price. Does this give you what you need?

**Comment by elizabethhamlin** [comment]
Hi Pete

Thanks, possibly yes. I need to try and build what I want based on this and see if it works. Will let you know if this isn’t quite right 😊

Thanks

Lill

Elizabeth Hamlin MARLA
Reporting and Systems Manager
The Lomond Group

Tel: 07443 188920
Email: ***@***.******@***.***>
Web: https://lomond.group<https://lomond.group/>

***@***.***
TO DONATE PLEASE FOLLOW LINK BELOW
Lomond Group Operations Team is fundraising for Sleep Out 2022 (centrepoint.org.uk)<https://sleepout.centrepoint.org.uk/fundraising/lomond-group-operations-team>


***@***.***
Lomond Group is a network of leading Lettings and Estate Agents across the UK, with regional branches across Aberdeenshire, Glasgow, Edinburgh, Yorkshire, Manchester and the North West, Birmingham and the West Midlands and Brighton & Hove. Registered office address 1 Wemyss Place, Edinburgh, EH3 6DH. registered in Scotland under registration number SC373580.

This email is confidential and intended solely for the use of the individual to whom it is addressed. Any views or opinions presented are solely those of the author and do not necessarily represent those of Lomond Group. If you are not the intended recipient, be advised that you have received this email in error and that any use, dissemination, forwarding, printing, or copying of this email is strictly prohibited. If you have received this email in error please contact the sender. Finally, the recipient should check this email and any attachments for the presence of viruses. The company accepts no liability for any damage caused by any virus transmitted by this email.

**Comment by plittlewood-rpt** [comment]
Thanks - I've just checked the calculations and it works as follows:

-- If there is an exchange fee already stored against the property, this should be used over everything else otherwise
-- If there is a fixed fee record on the property, always return it otherwise
-- If the fee percentage is zero, return zero, otherwise
-- If there is an accepted offer, use it to calculate the fee amount against the fee percentage, otherwise
-- Finally fallback to using the asking price to calculate the fee - this should never get hit
