### ISSUE TITLE
Start filter on appointments api does not work as expected

### ISSUE THREAD

**Issue by iWader** [reapit/foundations#8132]
**Describe the bug**

Calling the appointments api with a start and/or end date does not filter appointments as expected.

**To Reproduce**

1. Call `GET /appointments/?start=2022-11-15T00%3A00%3A00Z`
2. Events before 2022-11-15 are included in the response

**Expected behaviour**

- If using the `start` filter I expect to only receive appointments after this date
- If using the `end` filter I expect to only receive appointment before this date
- If using both the `start` and `end` filters I expect to receive appointments that intersect these dates

**Screenshots**

<img width="688" alt="Screen Shot 2022-11-15 at 15 11 11" src="https://user-images.githubusercontent.com/2007548/201954729-c789a5b9-0493-456c-8e5e-992f4af7451b.png">

**Device (please complete the following information for web issues):**
 - Device: [e.g. iPhone6, PC, Mac]
 - Browser [e.g. Chrome, Safari]

**Additional context**

N/A

**Comment by plittlewood-rpt** [comment]
Hi @iWader you will probably find that the events that fall outside the timeframe specified are recurring events (so have a recurrence that is within the timeframe specified). Please can you check and see if this is the behaviour you are seeing? If so, this is intended. If not, please provide further details. Thanks

**Comment by iWader** [comment]
Ah I didn't realise about the recurring appointments. It does seem thats the case, although it is giving me recurring events that don't fall within the start and end dates. Is this intentional?

Either way we can work with this now I know about the recurrence data

**Comment by plittlewood-rpt** [comment]
Great - thanks for coming back to me. I'll close this item down
