### ISSUE TITLE
App installation access

### ISSUE THREAD

**Issue by PaulUniHomes** [reapit/foundations#8133]
When a new user installs our app, they can then send new and updated properties to our website, but their current portfolio won't come through to us until they make changes to invoke the call to our webhook.

Ideally there would be a way of them 'forwarding' their entire portfolio to the webhook in one go.

We have in the past had a setup where we could talk to the Foundations API to retrieve property lists, so we have some code in our repository that already talks to the foundations API from other non-app clients which we could re-use if we have a way of authenticating a request to the foundations API.

If there is a way of gaining access after we receive an application installation notification to the webhook then that would work for us.

Thanks

**Comment by AshDeeming** [comment]
Hi @PaulUniHomes 
Once a customer has installed an app, the data permissions the app requested, will be available to call 

The parameters to Get a collection of properties can be found under the relevant endpoint on the swagger docs: https://developers.reapit.cloud/swagger
![image](https://user-images.githubusercontent.com/61687775/202173562-05ab4f79-1b73-4570-a133-4b030a58a25d.png)

**Comment by AshDeeming** [comment]
Hi @PaulUniHomes 
Apologies for the delay - application installation notification(s) should be sent as clients install the app & agree to the permissions - I can see one client install, was this received?

**Comment by PaulUniHomes** [comment]
Hi @AshDeeming 

Yes we received the notification of the install and the calls to the API were successful in retrieving the property data. We have another client installing today hopefully so assuming that also works correctly I'll close this up.

Thanks for your help

**Comment by AshDeeming** [comment]
Thanks @PaulUniHomes 
I'll close this ticket but please open a new one if required
