### ISSUE TITLE
Accessing Agent Data Originating from before App installation

### ISSUE THREAD

**Issue by gazeal-uk** [reapit/foundations#8138]
We have written a call to retrieve historic property statuses (whether exchanged, completed etc). But the response doesn't seem to provide any data from before the installation of the app. 

Is this is a deliberate limit or are we doing something wrong in the call?

**Comment by AshDeeming** [comment]
Hi @gazeal-uk 
Is the data active or archived property records in AgencyCloud?

**Comment by gazeal-uk** [comment]
Hi Ash

It seems to be related to active data.

Thanks





Bully Rai

Chief Technical Officer


Winner of PropTech Company of the Year


T: +44 (0)207 760 7582


***@***.***


A:35 Catherine Place, Victoria, London, SW1E 6DY

	

<https://www.linkedin.com/in/bully-rai-1b66489a/><https://www.instagram.com/gazeal_uk/><https://www.facebook.com/GazealUK/><https://twitter.com/gazeal_uk?lang=en>






Ash wrote on 18/11/2022 14:17:

**Comment by plittlewood-rpt** [comment]
Hi @gazeal-uk 

I have reviewed the email sent to our inbox

I think there are a few things at play. The createdFrom and createdTo query string parameters filter on the data the property was CREATED, not when the status changed to exchanged/completed - so I'm not sure if there is a misunderstanding there. You cannot currently filter on exchanged/completion dates. 

I have checked this customer's dataset and they do actually only have 4 live and 8 archived properties that meet the criteria you are submitting (created between 01/01/2021 and 21/10/2021) that are of status exchanged or completed. It would be that the client is not updating the property records correctly.

Please let me know if you need any further assistance. I'll leave this item open to give you chance to respond

Pete

**Comment by plittlewood-rpt** [comment]
Hi @gazeal-uk please can you confirm if you need any more assistance with this or if it can be closed
