### ISSUE TITLE
Companies collection endpoint is not working

### ISSUE THREAD

**Issue by BYM-Henry** [reapit/foundations#8141]
**Describe the bug**
The companies collection endpoint is not working and returns a 404 error no matter what is inputted.

It returns the following response:

"Entity \"Applicant\" (companies) was not found."

**To Reproduce**
This is reproducible by calling the company endpoint on the swagger page: https://developers.reapit.cloud/swagger

**Expected behaviour**
N/A

Any questions please let me know.

Many Thanks,

Henry Fitch
BriefYourMarket

**Comment by plittlewood-rpt** [comment]
Hi @BYM-Henry - this was resolved shortly after 5pm on Friday. If the issue persists for you, please let me know
