### ISSUE TITLE
Can't return applicant record in a bulk request

### ISSUE THREAD

**Issue by pmonno** [reapit/foundations#8144]
**Describe the bug**
While an Applicant can be returned individually by ID, when that same ID is used in a bulk request the Applicant record is not returned. Please see an example of this below:

**Screenshots**
![individual ID](https://user-images.githubusercontent.com/106077049/202999231-9545d30d-2e98-45fa-98bf-7e2152015239.png)
![bulk ID](https://user-images.githubusercontent.com/106077049/202999247-86044a2e-0eff-4db2-94d1-502bbc1de5a8.png)

**Additional context**
This request has come from DotDigital, as part of a project to integrate DD with Reapit Foundations.

**Comment by plittlewood-rpt** [comment]
Hi @pmonno - if this applicant is archived, you need to include `fromArchive=true` in your second request
