### ISSUE TITLE
500 status when Applicant is not found

### ISSUE THREAD

**Issue by pmonno** [reapit/foundations#8145]
**Describe the bug**
When an Applicant is not found (404 error status) the Reapit API is returning a 500 status (internal server error) instead of 404. This doesn't seem to be an issue for other entities that we're using such as Contact - which does return a 404 status. Please see an example of the not found Applicant issue below:

**Screenshots**
![500 status error](https://user-images.githubusercontent.com/106077049/202999827-a83a3292-73e0-4cc1-a6d9-f731876a7074.png)

**Additional context**
This request has come from DotDigital, as part of a project to integrate DD with Reapit Foundations.

**Comment by plittlewood-rpt** [comment]
@pmonno this is now resolved. Many thanks
