### ISSUE TITLE
Lomond Group Branch Issue

### ISSUE THREAD

**Issue by BYMIntegrations** [reapit/foundations#8161]
**Describe the bug**

A branch under the code LOC-GJOS comes through as blank for the PropertySchemaBranches field. There are 146,057 contacts assigned to it and we need to know what branch these should come under. I can't find this branch using postman. An example contact is dawsonandrew600@gmail.com. He has the attached contact information. I can't find his record in postman either.

Are you able to help?

**To Reproduce**
Steps to reproduce the behaviour eg:

**Expected behaviour**

**Screenshots**
If applicable, add screenshots to help explain your problem. Please ensure that screenshots do not include sensitive data such as personally identifiable information. If you do have private or sensitive information you need to share that will help with aiding resolution of this issue, please email sinfo@reapitfoundations.zendesk.com adding the issue number as the subject line. Please only use this mailbox to share information you cannot add to this issue.

![Branches](https://user-images.githubusercontent.com/102583061/203359088-00911582-232f-4117-ae18-d771a1a01cca.png)
![Dawson](https://user-images.githubusercontent.com/102583061/203359464-bfc1f9e6-45ea-40e3-9d8a-5325f1e98e7c.png

**Device (please complete the following information for web issues):**
 - Device: [e.g. iPhone6, PC, Mac]
 - Browser [e.g. Chrome, Safari]

**Additional context**

**Comment by BYMIntegrations** [comment]
Hello Support,

I hope you are well.

Please can we have an update on this?

The customer is coming into our office today so we would like to be able to update them regarding this.

Thanks,

Toby Hunter 
Integrations and Support Analyst

0344 800 84 24 (Ext 222) | [TobyH@briefyourmarket.co.uk](mailto:TobyH@briefyourmarket.co.uk)
[www.briefyourmarket.com](http://www.briefyourmarket.com/)

**Comment by HollyJoyPhillips** [comment]
Hi @BYMIntegrations we will need to investigate this. Unfortunately we cannot provide any further update at this moment.  As soon as we have more information we will update the ticket accordingly.

**Comment by BYMIntegrations** [comment]
Hello Holly,

I hope you are well.

Is there any update to this? I am being pushed for an update.

Thanks,

Toby Hunter
Integrations and Support Analyst

0344 800 84 24 (Ext 222) | [TobyH@briefyourmarket.co.uk](mailto:TobyH@briefyourmarket.co.uk)
[www.briefyourmarket.com](http://www.briefyourmarket.com/)

**Comment by HollyJoyPhillips** [comment]
Hi Toby, it's been assigned to our current sprint which starts today. As soon as we have an update the ticket will be updated. Thanks.

**Comment by plittlewood-rpt** [comment]
Hi @BYMIntegrations please can you let me know what "PropertySchemaBranches" is? The screenshot you've provided looks to be from one of your own systems and not ours so that data is post-processing at your end presumably?

**Comment by plittlewood-rpt** [comment]
Thanks - so is the problem here that you need to understand why you're getting a load of contacts through which aren't being attributed to a branch?

**Comment by BYMIntegrations** [comment]
Hello P Littlewood,

I hope you are well.

That is correct, we have been told that the customer is expecting to see an acquisitions branch and which we currently are not getting. We are wondering if some of these contacts may be it.

Thanks,

Toby Hunter
Integrations and Support Analyst

0344 800 84 24 (Ext 222) | [TobyH@briefyourmarket.co.uk](mailto:TobyH@briefyourmarket.co.uk)
[www.briefyourmarket.com](http://www.briefyourmarket.com/)

**Comment by plittlewood-rpt** [comment]
It's also worth noting that LOC-GJOS isn't a branch identifier, it's an office GROUP identifier (where GJOS is the identifier of a group of offices that have been setup by the customer themselves). The office ids in that group are

JAE,JSU,JSB,JSC,JSX,JSO,JSE,JSH,JLA,JSN,JSL,JSS,JSA,JSD,JSV,JBG

I'm not sure if this helps at all yet but just thought that was worth raising in case there is a misunderstanding of what these longer customer ids mean

**Comment by BYMIntegrations** [comment]
Hello P Littlewood,

I hope you are well.

The PropertySchemaBranches filed is set by the value of the name in the office API endpoint. "John Shepherd - Conversions" is the branch we are needing but like you said it doesn't explain the rest.

Are these other contacts assigned a branch ID? is the conversion contacts assigned one? If so then can you let me know what it is. That way I can check the API and see whether we are seeing it under that customer code.

Thanks,

Toby Hunter
Integrations and Support Analyst

0344 800 84 24 (Ext 222) | [TobyH@briefyourmarket.co.uk](mailto:TobyH@briefyourmarket.co.uk)
[www.briefyourmarket.com](http://www.briefyourmarket.com/)

**Comment by plittlewood-rpt** [comment]
Hi Toby

I’m really struggling to understand the issue you are reporting here sorry. You’ve got that count of 140k based on “something”. Is that a list of contacts? And if so did you pull those contacts from the contacts API? If you can see the contacts there’s no reason you can’t see the office too. The print screen you’ve given us is your system after processing, it’s not telling me anything about a possible issue with our APIs. Is there a developer from your end we can bring into the conversation?

Thanks
Pete
________________________________
From: BYMIntegrations ***@***.***>
Sent: Monday, November 28, 2022 5:17:48 PM
To: reapit/foundations ***@***.***>
Cc: Pete Littlewood ***@***.***>; Assign ***@***.***>
Subject: [EXTERNAL] Re: [reapit/foundations] Lomond Group Branch Issue (Issue #8161)


External Message - Please be cautious when opening links or attachments in email
________________________________
Hello P Littlewood,

I hope you are well.

The PropertySchemaBranches filed is set by the value of the name in the office API endpoint. "John Shepherd - Conversions" is the branch we are needing but like you said it doesn't explain the rest.

Are these other contacts assigned a branch ID? is the conversion contacts assigned one? If so then can you let me know what it is. That way I can check the API and see whether we are seeing it under that customer code.

Thanks,

Toby Hunter
Integrations and Support Analyst

0344 800 84 24 (Ext 222) | ***@***.******@***.***>
www.briefyourmarket.com<http://www.briefyourmarket.com>

**Comment by BYMIntegrations** [comment]
Hello Pete,

I hope you are well.

I am speaking with one of our devs internally as this is also affecting another Lomond Branch. Please keep this ticket open with I speak with them and I'll come back to you on whether the issue is on our side.

Thanks,

Toby Hunter
Integrations and Support Analyst

0344 800 84 24 (Ext 222) | [TobyH@briefyourmarket.co.uk](mailto:TobyH@briefyourmarket.co.uk)
[www.briefyourmarket.com](http://www.briefyourmarket.com/)

**Comment by plittlewood-rpt** [comment]
Thanks - will wait to hear from you

**Comment by plittlewood-rpt** [comment]
Great - thanks for confirming Toby
