### ISSUE TITLE
Not able to find a specifiic Negotiator by Email

### ISSUE THREAD

**Issue by robchett** [reapit/foundations#8164]
**Describe the bug**
In the YOM account the using the /negotiators api returns YTWN for an ?id and ?name search by not a ?email search

**To Reproduce**
1. Use GET /negotiators?id=YTWN to get the email address
2. Use GET /negotiators?email=c......t......@y............ (redacted)

**Expected behaviour**
The search for ?email= to return the negotiator in the same way that searching by ID or name does.

**Screenshots**
N/A

**Device (please complete the following information for web issues):**
API

**Additional context**
Other negotiators are working fine and I can't see anything in the APIs that would indicate an issue with this specific neg and why they would be visible by other information, but not their email address.
I have seen from the clients RPS interface that the email is entered the same as is shown in the API response.

**Comment by robchett** [comment]
It turns out that the entered Neg email address had a space on the end.
This was not returned in the API response

"email": "xxx@xxx.co.uk"

The priority of this issue is now very low, but it would be useful if spaces were trimmed from email addresses?

**Comment by plittlewood-rpt** [comment]
Hi @robchett this should now be resolved. It was caused by some ill-formatted data in AgencyCloud. I'm trying to work out how it got into the state it was in so I can report it to the desktop developers

**Comment by plittlewood-rpt** [comment]
I have found the issue in AgencyCloud and logged it with our desktop developers
