### ISSUE TITLE
forename or surname length issue

### ISSUE THREAD

**Issue by sanjayisg** [reapit/foundations#8165]
Hi There,

We have found a very usual error that comes when we use api, the forename or surname can't be more the 12 char where as it is very usual with that we get name that is more then this, So request to allow at least 20 char for the same:

**With internet registration api.**
{
	"errors": [{
		"field": "forename",
		"message": "The value provided exceeds the maximum length of 12 characters"
	}],
	"statusCode": 422,
	"dateTime": "2022-11-12T19:52:02.3554225Z",
	"description": "One or more validation failures have occurred. Please refer to Errors list for details"
}

Some name: example: Sachchidanand, Chandershekhar, Harishchandra and Muraleedharan and many more we have to add.

Please do the needful soon.

Thanks,

Sanjay Gupta

**Comment by plittlewood-rpt** [comment]
HI @sanjayisg - you've logged this before under #7598 - we cannot make these alterations unfortunately. The source data (AgencyCloud CRM) is where this would need to be adjusted first
