### ISSUE TITLE
How to add negotiator in agency developer platform??? 

### ISSUE THREAD

**Issue by subin-roundr** [reapit/foundations#8170]
How to add negotiator in agency developer platform???  using CRM not the api
![image](https://user-images.githubusercontent.com/78721314/203696430-27748507-09c2-4c8f-8ee7-9da517a0395c.png)

**Comment by AshDeeming** [comment]
Hi @subin-roundr 
Adding new AgencyCloud users/Negotiators is normally handled by our support team or self service portal - This can only be done by Admin users as would have cost implications.

**Comment by JansenMyburgh** [comment]
Hi @AshDeeming 
What we're actually trying to find out is whether the users/negotiators that have been added to an AgencyCloud profile shows up anywhere in AgencyCloud?

**Comment by JansenMyburgh** [comment]
Like is there a list somewhere on AgencyCloud where an admin user can see a list of the users/negotiators that has been added to the profile?

**Comment by JansenMyburgh** [comment]
@AshDeeming for a negotiator to establish the connection/integration between Roundr and Reapit he is required to input the email which was used to load him onto AgencyCloud. Therefore we need to be able to show users where to find this email ID on Reapit AgencyCloud.

<img width="377" alt="Screenshot 2022-11-24 at 14 26 55" src="https://user-images.githubusercontent.com/67146234/203761299-c205f277-09e7-4855-bf9d-9a4f9e969a47.png">

**Comment by AshDeeming** [comment]
Hi @JansenMyburgh 
There is a config option in AgencyCloud to view/setup negs -however this may not be avaliable to all users;
![image](https://user-images.githubusercontent.com/61687775/203768764-bce9ab49-15ce-4000-9f7d-5db1c18746ac.png)

**Comment by JansenMyburgh** [comment]
Thanks @AshDeeming this is helpful.

**Comment by AshDeeming** [comment]
No problem, thanks @JansenMyburgh 
I'll close this ticket. Any other issues, please open a new relevant ticket.
