### ISSUE TITLE
InsType from Webservice Properties not exposed to Foundations Properties

### ISSUE THREAD

**Issue by robchett** [reapit/foundations#8171]
**Describe the bug**
Webservice Properties had an InsType field that could contain AU (Auction) or NH (New Homes).
Foundations provides selling.disposal but this does not appear to be be same thing.

**To Reproduce**
Steps to reproduce the behaviour eg:
Compare COS220335 on RER between Webservice and Foundations Property APIs

**Expected behaviour**
Seeing a representation of the InsType in Foundations

**Screenshots**
N/A

**Device (please complete the following information for web issues):**
API

**Additional context**
-

**Comment by AshDeeming** [comment]
Hi @robchett 
Please could you confirm where/which fields the InsType is in AgencyCloud?

**Comment by plittlewood-rpt** [comment]
Hi @robchett - InsType refers to a custom field "Instruction Type" that has been added to RER's marketing screen in the AgencyCloud CRM. Custom fields are not surfaced by default in the Foundations APIs however can be exposed in a read-only fashion using the extrasField mechanism. I have added this field to the list of fields that can be requested for this agent and you can do so in the following manner

`GET /properties?extrasField=pInsType` and/or `GET /properties/COS220335?extrasField=pInsType`

Where properties have an instruction type set, pInsType will be present in the `extrasField` collection in the response

For reference the values and their meaning are below

AU - Auction
LD - Land
NH - New Homes
NR - New Homes Referral
PX - Part Ex / Easy Move
RP - Repossession
SH - Second Hand
SO - Shared Ownership

The configuration changes should become effective in the next 15 minutes. If you get a 400 error with a message about not being permitted to request that field when you initially attempt this, please wait a little while longer whilst the configuration synchronises across the service estate.
