### ISSUE TITLE
Webhook events missing for Works Order Created events

### ISSUE THREAD

**Issue by whanno-lsl** [reapit/foundations#8175]
**Describe the bug**
We have a webhook listening to YOM "Works Order Created" events but some just seem to be missing.
They are missing from the Foundations "Transactions Log" view so it looks like the events are not being created at all from the Foundations side (we never receive them).

**To Reproduce**
Very sporadic, but an example for works orders created on 23/11/22 for YOM customer:

BPG22002999 worked
BPG22003000 MISSING FROM THE TRANSACTION LOG
BPG22003001 worked

**Expected behaviour**
If we are to rely on the events for our business process it is imperative that the events are fired for every works order rather than losing say 3 out of every 100.

**Additional context**
This has been happening sporadically for a good while and has been discussed on the chat previously where we were told to wait until some potentially related back-end fixes were happening, but the issue is still occurring.

**Comment by plittlewood-rpt** [comment]
Hi @whanno-lsl sorry for the delay in responding to this ticket. There seems to be a scenario that can cause small batches of events to fail to reach the end of the processing queue. I can see evidence of it happening (on a tiny percentage of batches) but can't spot the cause just yet. I've added some logging to the area that appears to be at fault to try and track this down.

**Comment by whanno-lsl** [comment]
Okay thanks for the update.

**Comment by plittlewood-rpt** [comment]
Hi @whanno-lsl the change that went out around lunchtime on Monday looks to have had the desired effect and the error that was being seen intermittently has not occurred since so I'm satisfied this should be fully resolved. If you see any other odd behaviours please do get back in touch. Thanks
