### ISSUE TITLE
Featured properties and Dircections extraFields

### ISSUE THREAD

**Issue by ServonSupport** [reapit/foundations#8177]
Hi

On Bourne Estate Agents we are using property Hive from the marketplace to import properties into their website.

We would like to pull in the Directions field (see attached) and also featured properties.

Can you confirm if these extra fields are available for Bourne as we do not see them in the feed.

![image](https://user-images.githubusercontent.com/61687775/204008765-251a8145-cadc-415e-b8ad-1da5b116d2f7.png)

![image](https://user-images.githubusercontent.com/61687775/204014876-b16a8178-5d53-4234-a293-8b7426411dc0.png)

**Comment by AshDeeming** [comment]
Hi @ServonSupport 
Please see the documentation below regarding  Semi-structured 'extras' field requests;
https://foundations-documentation.reapit.cloud/faqs#certain-fields-are-not-exposed-by-default-in-the-platform

I've updated this ticket for the relevant to review.

**Comment by ServonSupport** [comment]
- Bourne Estate Agents
- Directions and Featured properties
- Already supplied
- To show it on the Bourne website

**Comment by plittlewood-rpt** [comment]
Hi @ServonSupport these fields are now available to you. Extras field names:

Featured Property: pFeaturedProperty
Directions Description: pDirections

Request them when calling the API by using the `extrasField` query string parameter eg

`GET /properties?extrasField=pFeaturedProperty&extrasField=pDirections` or `GET /properties/{id}?extrasField=pFeaturedProperty&extrasField=pDirections`

Applicable values will be returned in the `extrasField` collection of each property model in the response. Please note that if there is no value stored against the entity it will not be returned in the collection.

Finally please allow up to 15 minutes from receipt of this notification for the changes to become active as it can take this long for new configurations to synchronise across the service estate. If after this time you cannot access the data please get back in touch.
