### ISSUE TITLE
Extra field "pOldCode" Required for client Gibbs Gillespie(ROM-GGAN) - (Part of Leaders Romans(ROM)

### ISSUE THREAD

**Issue by rajeshwl** [reapit/foundations#8184]
Client: **Gibbs Gillespie(ROM-GGAN)**
Field Required: **pOldCode**
- Our mutual client is migrating their data from the Gibbs Gillespie environment(GIB) to the Leaders Romans environment(ROM). The migration from reapit end going live by tomorrow. So we need to starting pulling the data from new environment for the website, as the property ID's are been changed we need to map the old records in website to avoid SEO ranking drop. So can you please enable this field as priority which helps us in migrating the data smoothly.

**Comment by HollyJoyPhillips** [comment]
Hi @rajeshwl we have added the field 'pOldCode' as an extra field for ROM. You will need to include the field name within your query parameters to return the value, if set. For example: 

https://platform.reapit.cloud/properties/PROPERTYID?extrasfield=poldcode

More information on extra fields (semi structured data) can be found here: https://foundations-documentation.reapit.cloud/faqs#certain-fields-are-not-exposed-by-default-in-the-platform
