### ISSUE TITLE
Query about value of property.letting.agentrole

### ISSUE THREAD

**Issue by matt-fixflo** [reapit/foundations#8186]
Hello,

A query regarding REU220173 for customer RPP.

The property.letting.agentrole is coming back as an empty string, so we are not flagging for import with the Fixflo middleware.  However, looking at screenshots provided by the client they seem to have set the role as Managed tenancy.  Is this the correct place that it needs to be set to populate letting.agentrole? If not can you advise where?

Thanks.
![image](https://user-images.githubusercontent.com/20279235/204758377-db36e7f1-31b1-4e9f-bdfd-6c7d85c9cb6a.png)

**Comment by AshDeeming** [comment]
Hi @matt-fixflo 
That is the correct location in AgencyCloud & the below from swagger shows the potential options surfaced via the Platform:
![image](https://user-images.githubusercontent.com/61687775/204818090-ef5cac62-c0df-48e3-ba86-45b9833cb9c0.png)

Is this the above client using the Platform app or the SOAP webservice API?

**Comment by matt-fixflo** [comment]
Hi @AshDeeming 

Thanks for that.

Can you confirm what screen users set the agent role on the property?

**Comment by AshDeeming** [comment]
Hi @matt-fixflo 
The AgencyCloud property screen has the below;

![image](https://user-images.githubusercontent.com/61687775/205616271-b75f223f-ff10-4b59-9d84-d95f96c75525.png)
