### ISSUE TITLE
Property API - Licensing Tab Data Exposed on the Property API

### ISSUE THREAD

**Issue by otrace** [reapit/foundations#8196]
AC now has the functionality to handle Property Licensing data (https://reapit.atlassian.net/wiki/spaces/RW/pages/1618378943/Lettings+property+licensing+-+configuration+option)

These fields need to be exposed, via the Property API, to allow for integrations with Partners such as Kamma and Yuno.

In order for us to grant access to Semi-structured 'extras' field data, please provide the following information in this request:

- Reapit
- Screenshot of Licensing Section in AC:
- ![image](https://user-images.githubusercontent.com/78555300/205032899-be982ca0-19b2-4dd4-8dee-af450ffb737b.png)
- Fields required:
- Licence Required = pLicReq (Boolean)
- Licence Type = pLicType= (String - [Picker - following options Additional (A),Mandatory (M),Selective (S),None (N)])
- Households = pLicHseHolds (String - 0+)
- Licence Status = pLicStat=(String - [Picker - following options Applied (A),Landlord Applying (L),Granted (G),N/A (N)])
- Application Date = pLicApplDate (DateTime)
- Licence Granted = pLicGranted (DateTime)
- Licence Expirty = pLicExpiry= (DateTime)
- Application Ref = pLicRef (String)
- Floor Level = pFloor 
- Internal Floors = pPrpInternalFloors
- Total Building Floors = pTotalBldgFloors

**Comment by plittlewood-rpt** [comment]
We should not use the semi structured mechanism for this and should treat this as a new feature. Will need to deep dive the functionality before designing any new endpoints

**Comment by otrace** [comment]
@plittlewood-rpt do you need me to raise a new feature request for this or are you happy to work from this ticket? Only reason for raising it under Semi Structured is because all of the data is stored in prp.extra

**Comment by plittlewood-rpt** [comment]
We can use this ticket - was more a note for our team. Cheers

**Comment by plittlewood-rpt** [comment]
Requires #8244

**Comment by RLAV1** [comment]
Hey @HollyJoyPhillips this ticket is now ready to be progressed - can this be added to the next review session please? 
Thank you

**Comment by HollyJoyPhillips** [comment]
Hi @RLAV1 we have multiple tickets relating to Property Licencing and have added a specification to https://github.com/reapit/foundations/issues/8948 which is in near term. I'll close this ticket so if you can please subscribe to #8948 for updates. Thanks.
