### ISSUE TITLE
Property in focus field

### ISSUE THREAD

**Issue by wtienzo** [reapit/foundations#8199]
**Request**

In order for us to grant access to Semi-structured 'extras' field data, please provide the following information in this request:

- The name of the customer you represent
Winkworth
- The name of every field you need surfaced (if known)
Property in focus

- A screenshot of of the field(s) you require in the agency cloud user interface

![image](https://user-images.githubusercontent.com/28800868/205275403-ec0a10cd-2106-47b7-82b8-c96706b99704.png)

- A short use case as to why you require this data
We need this field to show featured properties on our website.

**Comment by plittlewood-rpt** [comment]
Hi @wtienzo 

I have now enabled access to this field, called `pPrpInFocus` - to access your data use the extrasField query string parameter ie:

`GET /properties?extrasField=pPrpInFocus` and/or `GET /properties/{id}/?extrasField=pPrpInFocus`

Multiple extrasField parameters can be used in the same request.

Please allow up to 15 minutes for the configuration change to become effective. If you still cannot access the data after this time, please get back in touch. Thanks
