### ISSUE TITLE
Developer Analytics costs - grouped brands/agents?

### ISSUE THREAD

**Issue by quigger** [reapit/foundations#8208]
In the Developer Analytics pages I can see the list of "Clients":
https://developers.reapit.cloud/analytics/costs

I can see the Team Association (TEA-GSLG) group, however, there are many clients / brands in that group.

Can we see those individual clients stats listed individually?

**Comment by quigger** [comment]
@AshDeeming 

I see other clients now - so perhaps it was an individual Team client, and not a group.

Is TEAM-GSLG the code for Slades?

![image](https://user-images.githubusercontent.com/644502/205952571-0e055865-3bb7-42d6-b7df-5611d2414ed0.png)

**Comment by plittlewood-rpt** [comment]
Hi @quigger - this isn't possible unfortunately as traffic is not attributed to a specific office. The only way to achieve something like this would be for the customer to have a separate office group for each office, which would be an incorrect use of office groups.

**Comment by quigger** [comment]
@plittlewood-rpt 

I think I was wrong.

Team Association (TEA-GSLG) is NOT a group account.

Team Association (TEA-GSLG) is the SLADES HOMES agency as part of Team Group.
So it is the just individual agency.

**Comment by plittlewood-rpt** [comment]
Hi @quigger is the main issue here that you can't see the name of the office group (so you can't translate "GSLG" into something meaningful?)

**Comment by quigger** [comment]
@plittlewood-rpt 

The first issue was I didn't realise the Team Association (TEA-GSLG) was a single agent.

However, now I do, yes, I confirm it's not clear what the Team Association (TEA-GSLG) means.

TEA -  Team group?
G - something?
SLG - something short for Slades Homes?
