### ISSUE TITLE
Analytics cost mismatch

### ISSUE THREAD

**Issue by quigger** [reapit/foundations#8212]
Using the page here:
https://developers.reapit.cloud/analytics/costs

And checking data for December so far.

I have two clients using data and the pages report:
{Redacted} 

if we add these together we get:
£51.07

However, if we select "no client" the page says:
Total for period: £43.69

What has gone wrong please?

**Comment by AshDeeming** [comment]
Hi @quigger 
Please could you provide an email address?

**Comment by quigger** [comment]
From ZenDesk

---

Hi Jason,

There will be a slight difference in customer amounts against what you see when breaking down by ‘Client’. The reason is that in the Developer Portal, we bill the developer (you) as a whole. We look at how many endpoints and requests a Developer has made in total (across all of their apps) and we then apply that to the sliding scale API consumption billing modal.

However, when the developer views the API consumption break down by customer (what you see in the Developer Portal ), the individual requests are applied to the sliding scale and the cost is slightly higher per client. 

Best regards,
Ash

**Comment by quigger** [comment]
@AshDeeming 

Did you want me to reply on email and not paste the information here?
e.g. as above?

**Comment by AshDeeming** [comment]
Hi @quigger 
If the information is sensitive or personal, please send it via the ZenDesk as per documentation (https://foundations-documentation.reapit.cloud/faqs#i-have-an-issue-that-requires-sharing-private-sensitive-information-that-i-do-not-wish-to-be-made-pu)

**Comment by quigger** [comment]
I've deleted the comment.

**Comment by AshDeeming** [comment]
Thanks @quigger 
I'll close this ticket down but please create a new ticket if you have any further questions etc
