### ISSUE TITLE
How to turn off client sign up notification emails

### ISSUE THREAD

**Issue by nikolai-momot-thirdfort** [reapit/foundations#8216]
**Summary**
Whenever a new client signs up to use our reapit app, the `Office Email` receives a notification email.

The [docs mention](https://foundations-documentation.reapit.cloud/faqs#notification-email) that this can be disabled by setting a `Notifications Email`.

However, after setting a `Notification Email`, the `Office Email` still receives the notifications emails.

Is there a reason the office email is still receiving the emails, and is there a way to turn them off?

**Comment by AshDeeming** [comment]
Hi @nikolai-momot-thirdfort 
The notification will only sent to the notification email once added. 

It may be that you have the app's support email setup on the app listing, which is notified too.

**Comment by nikolai-momot-thirdfort** [comment]
@AshDeeming We have both the `Office Email` _and_ the `Notification Email` set but the notification emails come through to the `Office Email` and the `Support Email`

Here are the emails set in the Company Page - A is the `Office Email` and B is the `Notification Email`
<img width="785" alt="Screenshot 2022-12-07 at 09 52 15" src="https://user-images.githubusercontent.com/109656933/206149600-151e6cec-1add-4e21-b956-14a539c2411f.png">

Here is the email set on the App page - C is the `Support Email` 
<img width="386" alt="Screenshot 2022-12-07 at 09 56 20" src="https://user-images.githubusercontent.com/109656933/206149944-806bf27c-c5dc-42ab-a97a-898de2c3567f.png">

Here is a notification email sent, after the `Notifications Email` was set, addressed to emails A and C - the `Office Email` and `Support Email` 
<img width="435" alt="Screenshot 2022-12-07 at 09 55 55" src="https://user-images.githubusercontent.com/109656933/206150388-de47a895-1307-4971-8549-aca346b48101.png">

Do you know why email are getting sent to the `Office Email`  instead of the `Notification Email`?

> It may be that you have the app's support email setup on the app listing, which is notified too.

Does this mean that the `Support Email` gets notified even if the `Notification Email` is set?

**Comment by AshDeeming** [comment]
Hi @nikolai-momot-thirdfort 
This is currently being reviewed & the ticket will be updated once more details are gathered

**Comment by nikolai-momot-thirdfort** [comment]
Hi @HollyJoyPhillips 

Has there been any progress on this issue?

**Comment by HollyJoyPhillips** [comment]
Hi @nikolai-momot-thirdfort, sorry for the delay. Would you mind forwarding me a copy of the installation email you received please to sinfo@reapitfoundations.zendesk.com

**Comment by nikolai-momot-thirdfort** [comment]
@HollyJoyPhillips the email has been forwarded, please let me know when you have received it

**Comment by HollyJoyPhillips** [comment]
Hi @nikolai-momot-thirdfort thank you for the email. We have located the issue and it will be resolved once this bug has been fixed: https://github.com/reapit/foundations/issues/8290

**Comment by HollyJoyPhillips** [comment]
hi @nikolai-momot-thirdfort we have fixed the issue, please review your notification email again on the company page (https://developers.reapit.cloud/settings/company) as you may need to re enter it. Thanks.

**Comment by nikolai-momot-thirdfort** [comment]
@HollyJoyPhillips I can confirm that the Office Email no longer gets notification emails, but the support email still does - is this the intended functionality?

**Comment by HollyJoyPhillips** [comment]
Hi @nikolai-momot-thirdfort Thank you for confirming and yes, that is the intended behaviour.

**Comment by nikolai-momot-thirdfort** [comment]
Thanks @HollyJoyPhillips. To confirm, there is no way to disable Notification emails from being sent to the support email?

**Comment by HollyJoyPhillips** [comment]
Hi @nikolai-momot-thirdfort That is correct. You can of course raise a feature request which we can review but as it stands currently, no you cannot disable notifications being sent to the support email address.

**Comment by nikolai-momot-thirdfort** [comment]
Thanks @HollyJoyPhillips Would raising a new GH issue be the best way to raise a feature request?

**Comment by HollyJoyPhillips** [comment]
Hi @nikolai-momot-thirdfort Yes please.

**Comment by nikolai-momot-thirdfort** [comment]
Thanks again @HollyJoyPhillips I've created the feature request in #8328
