### ISSUE TITLE
Client does not have option to install app

### ISSUE THREAD

**Issue by PaulUniHomes** [reapit/foundations#8217]
Our app is locked down to only Reapit users that we add the customer IDs for.

We currently have one successful application enable but having added a second ID to the list as a CSV, they are not seeing the yellow enable integration button on visiting the app page?

**Comment by AshDeeming** [comment]
Hi @PaulUniHomes 
Please can you confirm that the user is an Admin user for their organisation? 

This can be checked via their 'settings' at the bottom left of the AppMarket screen

**Comment by AshDeeming** [comment]
This ticket will be closed due to inactivity/response. 
If you have any further issues, please open a new ticket, referencing this ticket, if relevant.
