### ISSUE TITLE
Receiving data of other tenant in the Multi Tenant installation customer - Lomond Capital(LOC)

### ISSUE THREAD

**Issue by rajeshwl** [reapit/foundations#8221]
**Describe the bug**
We have a client with multi tenant installation setup. In this we are receiving data related to other agent inside the group. Few API's are listed below.
1. Negotiators
2. Office
3. Companies

**To Reproduce**
If we import data for Customer ID `LOC-GHRD`, we are receiving data from other tenant's of Lomond Capital(LOC) as well( `LOC-GJOS` , `LOC-GBRV`, `LOC-GTHG`, etc...).

**Expected behaviour**
We expect the API's to return data specific to the customer ID like `LOC-GHRD`.

**Additional context**
Seems the property end point alone working fine specific to the Customer.

**Comment by plittlewood-rpt** [comment]
Hi @rajeshwl - not all APIs can automatically apply filtering based on the office group the app is installed for. Customer ids starting LOC-* actually target the same database. The suffix is the office group that has installed the app. As some APIs relate to entities that have no office attachment, it's not possible for these APIs to automatically filter the data in the same way that the contacts API, which has explicit office codes in the entities would do, which is why you get the same data back. I hope this makes sense

**Comment by rajeshwl** [comment]
@plittlewood-rpt ,
Is there anyway you can apply the office group filter for all API's ? Because filtering with Office codes will make us adding additional office ID's when ever new office added by client from their end and we might need to be keep informed of addition of new office across group.

**Comment by rajeshwl** [comment]
@plittlewood-rpt ,
Any updates regarding this?

**Comment by plittlewood-rpt** [comment]
Hi @rajeshwl - unfortunately there is no easy way of doing this. The problem you have is that some developers/customers would expect the 'office id' to be inferred based on one thing and others might expect the 'office id' to be inferred on another (for example, the first might want to do it based on the office of the associated contact, another might want to do it based on the office of the associated negotiator, and so on)

**Comment by plittlewood-rpt** [comment]
Hi @rajeshwl to update you on this. The following endpoints groups have office group filtering which will be applied when a user associated to a company using office groups makes a request (or you call the API from a machine to machine app with a group suffixed customer id like in your example on this issue):

Applicants
Appointments
Companies
Contacts
Conveyancing
Documents (file downloads)
Enquiries
Identity Checks
Landlords
Negotiators
Offers
Offices
Properties
Property Images
Referrals
Tenancies
Vendors
Works Orders

Any endpoints not listed above are configuration style endpoints and don't really fit with this kind of filtering. 

Can this item be closed based on the above?

**Comment by rajeshwl** [comment]
@plittlewood-rpt ,
We tried using the request suffix, but we received other tenant data in the above mentioned endpoints as well. Few are listed below which are in your list.
1. Negotiators
2. Office

**Comment by plittlewood-rpt** [comment]
Hi @rajeshwl can you provide a bit more clarity on what you are reporting please? Can you give me examples of calls you are making, the data you are receiving back, and what you are expecting to not be returned in the results. It could just be that there is a misunderstanding about how this mechanism actually works, in which case we can clear that up.

Please email sinfo@reapitfoundations.zendesk.com with this information 

Thank you

**Comment by rajeshwl** [comment]
@plittlewood-rpt ,
I am making a get call for `/negotiators/` endpoint with customer code `LOC-GHRD`, I expect the response to be filtered for that office group. But i am receiving other tenant(Ex: LOC-GJOS) data as well. Hope this gives some clarity

**Comment by plittlewood-rpt** [comment]
Hi @rajeshwl I've just run some tests using LOC-GHRD and the negotiators endpoint is behaving as expected and only returning data for the three offices in that group (defined by the suffix)

Please can you provide some specific examples to the email address above so I can try and assist further? Everything looks to be as it should be from this end. Thanks

**Comment by plittlewood-rpt** [comment]
Hi @rajeshwl can this now be closed? Thanks

**Comment by gokulngk** [comment]
@plittlewood-rpt Please hold on. Do not close this ticket, We are still testing this. Will get back to you once we are done with the testing.

**Comment by rajeshwl** [comment]
@plittlewood-rpt ,
Seems still we are receiving the data of other tenants in negotiator call. I have tried to import data for negotiators using different tenant ID's but still its receiving. . One of the example is given below. 
1. We imported negotiators using the customer code as `LOC-GBRM`.
2. But in this received negotiators from other offices. Few examples are given below.
**Example 1:**
Negotiator ID: ASC
Office ID: DJD
Email: username@johnshepherd.com (Removed the first part and replaced with username). 
**Example 2:**
Negotiator ID: AFB
Office ID: PMY
Email: username@braemore.co.uk (Removed the first part and replaced with username). 
**Example 3:**
Negotiator ID: APL
Office ID: DJS
Email: username@djalexander.co.uk(Removed the first part and replaced with username). 

Seems these are from other client i think.

**Comment by plittlewood-rpt** [comment]
Hi @rajeshwl thanks for the examples. I've just had a look and the LOC-GBRM group of offices contains all the office ids you've listed above, so the API is behaving as I'd expect. The customer themselves are responsible for the office grouping which controls the behaviour of the automatic filters in the API that get applied when groups are configured so you would need to speak to them directly if this is causing you a problem as they would need to make any changes.

**Comment by plittlewood-rpt** [comment]
For reference, the following office Ids are in the LOC-GBRM office group:

ACC,CTY,CTS,HDO,HDS,MNG,MNS,PMB,PMG,BPP,PMY,BSA,BSS,DJA,DJD,DJG,DJH,DJC,DJW,DJS,DJT,DJK,DJX,DHO,MUA

**Comment by rajeshwl** [comment]
Thanks for the details @plittlewood-rpt . I will have a check with client and get back to you if any issues.
