### ISSUE TITLE
Data Warehouse - How to link New Homes Master and Sub plot records

### ISSUE THREAD

**Issue by LyndsayCremin** [reapit/foundations#8224]
Hi There,

Can you let me know if there is a way to link a New Homes sub plot record to the Master record in the data warehouse please?

Many thanks,

Lyndsay

**Specification**
- Project: Analytics Schema
- Add master_property_id and site_type columns to PROPERTIES model (with associated staging changes) which is the generated composite key. This column should be null if the record is not a sub plot
- [x] Update documentation with production release

**Comment by plittlewood-rpt** [comment]
Hi @LyndsayCremin this is now available as per the specification on this ticket. Please note you will need to log into the Data Marketplace app and click Refresh Share to be presented with the new columns in the models. Thanks

**Comment by LyndsayCremin** [comment]
Hi Pete,

Apologies about my delay in responding, I was out of the office.

I have refreshed the data share but, unfortunately can not see the columns master_property_id and site_type in the PRP table. Is there something I am doing wrong here?

Many thanks,

Lyndsay


Lyndsay Cremin
IT Project Lead
Sherry FitzGerald
Silverstone House, Ballymoss Road, Sandyford, Dublin 18, D18 A7K7

Direct: +353 1 237 6340
Mobile: +353 861566082
Email: ***@***.***
Web: www.sherryfitz.ie

I have sent this email at a time that is convenient for me. I do not expect you to respond to it outside of your usual working hours.
​
Sign up to mySherryFitz now to book viewings, make offers, see existing bids, arrange property notifications and chat to us online – we’re here to help!
Click here to view the Sherry FitzGerald Privacy Policy
Please consider the environment before printing this email 
 
Sherry FitzGerald Group Ireland Holdings Limited. Registered in Ireland, CRO no 623927. 
Registered office: Silverstone House, Ballymoss Road, Sandyford, Dublin 18. D18 A7K7.
 
The contents of this e-mail are Subject to Contract /Contract denied. 
​
​This e-mail and any files transmitted with it are confidential and are intended solely for the use of the intended recipient. Any unauthorised direct or indirect dissemination, distribution or copying of this message and any attachments is strictly prohibited. If you have received this e-mail or any file attachment transmitted with it in error, please notify Sherry FitzGerald at ***@***.*** 
​
​This email has been scanned for computer viruses.
 
A part of the Sherry FitzGerald Group
Residential | New Homes | Lettings |  Mortgages

**Comment by plittlewood-rpt** [comment]
Hi @LyndsayCremin apologies I've completed missed an important part of this ticket. You're using the operational schema not the analytics schema aren't you. In the operational schema, you need to use the lookup table to understand development/land site relationships in conjunction with the `site` column in the PRP table.

PRP.SITE denotes whether the property is a Master record (M) or Child/Sub Plot record (C). Land Sites have a value of L
The relationships are manged by records in the lookup table with typeFrom = 'PRP' and typeTo = 'PRP'

We typically don't support the operational schema and a better understanding of it's format can be seen in the Data Dictionary which is available in AgencyCloud under User Profile (top left) -> System Information -> Data Dictionary
