### ISSUE TITLE
spike: Deep dive and design contracts for exposure of property licensing data

### ISSUE THREAD

**Issue by plittlewood-rpt** [reapit/foundations#8244]
**Background context**
To allow us to implement the requests in #8196 we should deep dive the property licensing functionality in AgencyCloud to understand how it works and how the data is stored. From this we should be able to design any schema changes and new endpoints (if a sub-resource is more appropriate) to expose this information

**Specification**
- Deep dive AC functionality
- Design API changes/enhancements and scope out on the aforementioned ticket

**Comment by RLAV1** [comment]
@HollyJoyPhillips once this work has been completed in Sprint 92 can we also update the associated Github #8196 to confirm so that the work can then start on, as 8196 is waiting the work to be completed on this ticket - thank you

**Comment by plittlewood-rpt** [comment]
Closing this as it looks like the data may be getting restructured in AC to address some performance concerns so we will need to revisit this at the appropriate time. Internal ref PBI-4709
