### ISSUE TITLE
Martyn Gerrard Missing Contacts

### ISSUE THREAD

**Issue by BYMIntegrations** [reapit/foundations#8254]
Please take a look at our FAQ's before submitting an issue, as your question may already be covered in the documentation https://foundations-documentation.reapit.cloud/faqs

**Summary**

Hey Guys,

We have been asked to identify why we are missing contacts for Martyn Gerrard. I have checked the spreadsheet and I can't find any of the references in the Reapit API.

The customer is confident the contacts exist but I can't find them in the customer code.

Can you confirm if any exist in the Reapit CRM?

Cheers

**Detail and or supporting links and screenshots**
**Excel data redacted **

**Comment by AshDeeming** [comment]
Hi @BYMIntegrations 
From checking an random sample of the provided list - these have all been located on the Clients CRM however please note that these are Applicant references, not Contact ref. 

For example, the first on the list is an Applicant ref that relates to their Contact record: BAR13000310

**Comment by BYMIntegrations** [comment]
Hello Ash,

I hope you are well.

Thank you for that, I didn't know they were applicant references.

Cheers
