### ISSUE TITLE
Getting companies where a contact is a staff member

### ISSUE THREAD

**Issue by gareth-evans** [reapit/foundations#8257]
Please take a look at our FAQ's before submitting an issue, as your question may already be covered in the documentation https://foundations-documentation.reapit.cloud/faqs

**Summary**
I'd like to retrieve a list of companies for which a contact record has been added as a staff member. Is that possible?

**Detail and or supporting links and screenshots**
We currently have an app that retrieves a list of properties for a contact. We do this by looking at the vendors related to the contact and then getting the properties for those vendors.

We would like to extend this to include properties where the vendor is a company and the contact is staff member for that company.

**Specification**
- Project: Reapit.Services.Contacts
- Include cmp -> cnt lookups when retrieving contact relationships. Data should be surfaced in the same format as existing relationships with `associatedType` set to _company_
- Add new `company` link to `ContactRoleModel` when type is _company_

**Comment by AshDeeming** [comment]
RES example:
1 Contact & 1 staffMember: 
![image](https://user-images.githubusercontent.com/61687775/207597352-ce5628cb-4309-46eb-8ac6-d3719b98ee33.png)

![image](https://user-images.githubusercontent.com/61687775/207597260-85cd060b-6f37-4a6c-8e21-18be30d4c20f.png)

**Comment by gareth-evans** [comment]
Hi @AshDeeming I found that but it doesn't provide the contact ID. Also it's the wrong way around for what I'm looking for. I want to find companies related to a contact not contacts related to a company.

**Comment by plittlewood-rpt** [comment]
One consideration with this is that it will always rely on a customer's use of the CRM. There are two ways of attaching a 'contact' to a company as you can determine from the screenshot above. The staff member with a little person icon is a contact in the system, the staff member without is a contact associated directly to the company and is NOT an explicit contact entity. This may cause confusion if we start allowing API consumers to filter by this data.

@gareth-evans are you able to elaborate further on your use case here? I'm not sure I understand the benefit of being able to drill down that extra layer yet.

**Comment by gareth-evans** [comment]
@plittlewood-rpt to be clear we don't want to get a list of contacts for a property, we want to get a list of companies for which a contact is a staff member, I envisage it would be available on /contacts/{id}/relationships.

The use case we have is we want to list all properties for a contact. Where the contact is the vendor we can navigate `Contact => Vendor => Property`.

**Comment by gareth-evans** [comment]
@plittlewood-rpt is there any update on this?

**Comment by plittlewood-rpt** [comment]
HI Gareth - not as yet no, it will be re-reviewed in due course

**Comment by rochellelevy** [comment]
@plittlewood-rpt Hi ! and Happy New Year. What does due course mean? Can we have a timeline?

**Comment by plittlewood-rpt** [comment]
HI @rochellelevy our next refinement session in Thursday. We will need to review the data structures in AgencyCloud to determine if it's appropriate to do this in the API or not.

**Comment by plittlewood-rpt** [comment]
@gareth-evans  from a usage scenario, is this more about us surfacing the fact that a contact has an association to a company, or having the ability to search `GET /vendors` by contactId - it seems there might be two separate requirements here?

**Comment by gareth-evans** [comment]
@plittlewood-rpt it is about surfacing the association between a contact and a company. But critically by navigating from the contact to the company or companies of which the contact is a staff member. 

We don't have a requirement to GET /vendors by contactId as we currently navigate this using the contact relationships. As I mentioned previously it would feel natural for us to be able access companies as relationships on the contact although I appreciate this might not be feasible.

**Comment by plittlewood-rpt** [comment]
Thanks - would adding this information to `GET /contacts/{id}/relationships` as you describe fulfil your requirement? Your original comment says you want to be able to find companies where a specific contact record has been added as a staff member which would mean you needed a filter on `GET /companies` unless you process the contact relationships yourself then run your search at your end.

**Comment by gareth-evans** [comment]
Hi @plittlewood-rpt yes adding the company to the relationships would fulfil our requirement. We wouldn't need a filter on `/GET companies`

**Comment by plittlewood-rpt** [comment]
Thanks for clarifying that - yes all makes sense
