### ISSUE TITLE
Data feed app

### ISSUE THREAD

**Issue by ianmintouch** [reapit/foundations#8263]
Hello,

Our company, Intouch Display, provide display / digital signage solutions to the Property Industry.  Up until recently we have been able to obtain RMv3 type feeds from Reapit but as these are now deprecated we have been advised to move our data retrieval over to Foundations.

We have developed a server side app to retrieve the data we need from the REST Api, using sandbox data.  

We're at the point now where we need to submit the 'app' so that we can use it with our clients. 

We're initially going to have it privately listed for 2 or 3 clients and then move it to being a public listing once we're a bit more familiar with the platform.  In reality we'd prefer to have it privately listed for all of our clients as it's only of use to customers that have our products.

My question is about submission of the app. As far as our needs are concerned, the only 'app' is our retrieval software that runs on a private server and seeds and maintains our database.  Having read through the documentation there doesn't seem to be a provision for this type of scenario, 

The way I initially understood this was that a mutual client would install the app, this would give us their Customer Code, which we would add to our system for processing.  Therefore, I'm not sure what a customer facing app would do in this case or how we would submit for review.

I would be grateful if you could let me know what we need to do for the next stage.

Kind regards

Ian Marsden

**Comment by AshDeeming** [comment]
Hi @ianmintouch 
When going through the 'create new app' flow - you should be able to choose the relevant options for the possible app types. 
Once the app is setup correctly, you will be able to input a client(s) ID into the private apps section, meaning only that customer can see the option to install, agree to the permissions & grant you access

**Comment by AshDeeming** [comment]
This ticket will be closed due to inactivity/response. 
If you have any further issues, please open a new ticket, referencing this ticket, if relevant.
