### ISSUE TITLE
Identity Check Icons status

### ISSUE THREAD

**Issue by nikolai-momot-thirdfort** [reapit/foundations#8265]
**Summary**
When inspecting a contact in Agency Cloud there is an icon beside for `Identity Check` that changes based on the status the check.

Is there a guide for which statuses result in which icons?

Here are sceencaps of the icons that I am referring to:
<img width="107" alt="Screenshot 2022-12-15 at 10 45 34" src="https://user-images.githubusercontent.com/109656933/207840899-4017e6dc-a91d-4653-8178-6197bc729259.png">
<img width="106" alt="Screenshot 2022-12-15 at 10 39 23" src="https://user-images.githubusercontent.com/109656933/207840905-a7e548b0-b4b7-48bb-bbd4-53d76cefa5fc.png">
<img width="101" alt="Screenshot 2022-12-15 at 10 23 05" src="https://user-images.githubusercontent.com/109656933/207840907-d567870d-5079-4854-bcf6-ca501a848ada.png">
<img width="101" alt="Screenshot 2022-12-15 at 10 22 12" src="https://user-images.githubusercontent.com/109656933/207840909-18c5c8e1-bacf-4445-899b-ab25f213c56e.png">
<img width="112" alt="Screenshot 2022-12-15 at 10 06 24" src="https://user-images.githubusercontent.com/109656933/207840912-677bdd0a-e8b9-4cb3-be57-104e9548a1d8.png">

**Comment by AshDeeming** [comment]
Hi @nikolai-momot-thirdfort 

The statuses can be hovered over - see the below examples;

![image](https://user-images.githubusercontent.com/61687775/207849590-9cf36bd0-b45e-4983-b6df-e12a08d49db7.png)

![image](https://user-images.githubusercontent.com/61687775/207849729-9b64a620-6951-45ac-a4d0-1122ee163461.png)

![image](https://user-images.githubusercontent.com/61687775/207850313-e4286ca6-28b9-478f-964d-2cfb435dd539.png)

![image](https://user-images.githubusercontent.com/61687775/207850762-cda68335-78f2-43f0-8fe5-2042a6bf02ee.png)

![image](https://user-images.githubusercontent.com/61687775/207850862-327c5d76-eaf8-44fd-833f-d70657ae4b83.png)

**Comment by AshDeeming** [comment]
Hi @nikolai-momot-thirdfort 
the status & their tooltips should relate easily - is there a particular one that requires clarification?

**Comment by nikolai-momot-thirdfort** [comment]
Hi @AshDeeming can you please clarify which status and conditions cause "check expired"?

**Comment by AshDeeming** [comment]
Hi @nikolai-momot-thirdfort 
The ID checks expired status relates to AgencyCloud config i.e. a Reapit Client could request this to be 12 months etc depending on their policy 

Via the Platform, each ID check has its own Expiry date, relevant to that ID (see identityDocument1 & identityDocument2) - below example payload from SBOX:
![image](https://user-images.githubusercontent.com/61687775/208899323-d1a520d9-0784-402f-8268-cb9edf2d5a50.png)

**Comment by AshDeeming** [comment]
This ticket will be closed due to inactivity/response. 
If you have any further issues, please open a new ticket, referencing this ticket, if relevant.
