### ISSUE TITLE
Management percentage on tenancy

### ISSUE THREAD

**Issue by elizabethhamlin** [reapit/foundations#8267]
Hi
I am aware that you can get the management fee from the property but this can differ on the tenancy so please can you arrange to pull the management fee on the tenancy through to the data warehouse

Thanks 

Lill

**Specification**
- Project: Analytics Schema
- Enhance Tenancies model to include management fee amount/percentage as per lettings property fields (but for the tenancy). We should NOT fall back to the values on the property at this time if they are not set explicitly against the tenancy as this should be left up to the report developer as different users will want different behaviours
- If letting fees are not included in this model we should add them at the same time for consistency
- Remember to update analytics schema documentation with these changes

**Comment by elizabethhamlin** [comment]
Hi @plittlewood-rpt 
I cannot see that this is available in the data Warehouse yet. Can you point me in the right direction.

Thanks 

Lill

**Comment by plittlewood-rpt** [comment]
Hi @elizabethhamlin you will need to refresh your data share in the data warehouse app to see the new fields.

**Comment by elizabethhamlin** [comment]
Hi @plittlewood-rpt 
I have it now but it does not appear as a column in my Power Query in Power BI so I cannot merge this column into the tenancy alterations table. It should appear after periodic but it's not there. I need to be able to merge the queries so I can work out what the management fee was before the increase
![image](https://github.com/reapit/foundations/assets/104636752/158512bc-4aa2-479f-97d5-d9b3f0ac41e6)

**Comment by plittlewood-rpt** [comment]
Hi @elizabethhamlin I've just checked your data warehouse via Snowflake and the fields are definitely there so it's likely you need to refresh the view of your data in Power BI

**Comment by plittlewood-rpt** [comment]
Unfortunately I can't assist with Power BI. This is your analytics schema in Snowflake so the fields are definitely in there ready for you to use.

![image](https://github.com/reapit/foundations/assets/30798627/656217b4-9480-47bc-ba90-da548f34b78d)

**Comment by elizabethhamlin** [comment]
Hi @plittlewood-rpt I have looked into this and is the tenancy management fee a calculated column? If so is there no way that it can be different as I cannot model this in it's current form. We need to be able to match the old management fee with the new management fee on the tenancy alterations but can't as the data you have added does not appear for me to be able to merge the queries together. 
Also you have said that this shows in Snowflake but the tables I pull are from the below so are they in the correct place -
![image](https://github.com/reapit/foundations/assets/104636752/6d10d05e-4482-4ec6-879f-d8f8cb3c41d4)

As you can see here, the columns are not there - 

![image](https://github.com/reapit/foundations/assets/104636752/d6626556-0ca4-4ee7-8cb6-c1bbe051c750)

**Comment by plittlewood-rpt** [comment]
Hi @elizabethhamlin no it's not a calculated column. Can you try logging into Snowflake directly yourself to see if you can see the fields (just go to the [Snowflake URL](https://tj14055.eu-west-2.aws.snowflakecomputing.com/) and login with the credentials you've set up in the Data Marketplace app

**Comment by elizabethhamlin** [comment]
I'm an idiot. It was the type of the data my end. It had summarised it so wouldn't pull through. Fixed it and thanks for your help :)

**Comment by plittlewood-rpt** [comment]
Don't be so harsh on yourself on a Monday ;) Thanks for confirming, glad you've sorted it
