### ISSUE TITLE
Webhooks have stopped being sent

### ISSUE THREAD

**Issue by tim-west** [reapit/foundations#8269]
My client's (Druce) webhook has stopped working. It can be pinged successfully from the admin area, but when changes are made to properties the webhook does not appear to be sent.

**Comment by HollyJoyPhillips** [comment]
Hi @tim-west, when did this stop working? We can only see 1 webhook has been omitted this month for Druce. Do you have an example property reference and the changes that were made that you would expect to see please?

**Comment by tim-west** [comment]
Based on the api analytics it looks like it has never worked for V2 of the app which has been live since 31/10/2022.

**Comment by HollyJoyPhillips** [comment]
Hi @tim-west, V2 has only been installed for URA (Druce & Co (International) Limited) and webhooks have not yet been enabled. Druce (DRU) haven't installed V2 and their existing webhook is inactive.

**Comment by tim-west** [comment]
URA is the correct reference now. The webhook for V2 shows that it is active in the admin interface. Please can you do whatever is necessary to enable webhooks and let me know what is required for doing so in the future? I made the webhook for V1 inactive today (as it has been phased out) and I was testing if it might somehow be conflicting.

**Comment by HollyJoyPhillips** [comment]
Hi @tim-west I've raised a service infrastructure ticket as it's not something we enable via the Platform team. I'll keep you updated and find out the steps required going forward.

**Comment by HollyJoyPhillips** [comment]
SI ticket for reference: SI-20164
