### ISSUE TITLE
Extra Description 'Situation' not present on property model

### ISSUE THREAD

**Issue by TobyDunnEPS** [reapit/foundations#8271]
**Describe the bug**
Using Morris Marshall and Poole (MMA) property NEW220398 as an example, the property has an Extra Description 'Situation' set in Reapit.  The text of the Situation field is not present in the Foundations request for the same property.

The property has the Situation description as follows:
'Integral Garage with metal up and over door, power and light, mains gas central heating boiler.
Tarmacadam front parking area with space to accommodate several vehicles. Side pathway leading to enclosed spacious rear garden comprising raised paved patio and decked seating area with lower lawn area and garden shed'

**To Reproduce**
curl --location --request GET 'https://platform.reapit.cloud/properties?id=NEW220398' \
--header 'reapit-customer: MMA' \
--header 'api-version: 2020-01-31' \
--header 'Authorization: Bearer **TOKEN**'

The text listed above is not present in the data returned.  There is a property for situation, but is an array containing only "garden","patio"

**Expected behaviour**
The text 'Integral Garage ...' to be returned as part of the property model for NEW220398

**Screenshots**
![image](https://user-images.githubusercontent.com/65494260/208151687-3965c39e-9a4f-46f2-a9b9-96f8de828ade.png)

**Device (please complete the following information for web issues):**
N/A

**Additional context**
The data is returned in the BLM feed for the property as the last part of the DESCRIPTION field

**Comment by AshDeeming** [comment]
Hi @TobyDunnEPS 
This relates to semi-structured data - access to data held in the 'extras' Agency Cloud data format

This ticket has been updated for the relevant team to review

**Comment by HollyJoyPhillips** [comment]
Hi @TobyDunnEPS The field 'pSituation' will now be surfaced under the extrasField section for Morris Marshall and Poole (MMA). 

For more information on extra fields, please visit: https://foundations-documentation.reapit.cloud/faqs#certain-fields-are-not-exposed-by-default-in-the-platform

**Comment by TobyDunnEPS** [comment]
Thanks @HollyJoyPhillips , that's confirmed working, very much appreciated
