### ISSUE TITLE
How to edit page layouts for existing real estate listing pages

### ISSUE THREAD

**Issue by czei** [reapit/foundations#8272]
My apologies if this answer was obvious.  I've spent the last two hours reading through documentation and FAQ and could not find the answer.

A client has requested changes to the way their real estate listings appear.  For example, the TTFB is pushing 30 seconds, leading to a very slow overall customer first impression, as well as a handful of other changes they've requested.

Looking at the developer FAQ there is a lot of information regarding app development, and there is extensive UI documentation, but I didn't see anything on how to edit the layout of existing pages.

Thanks,

**Comment by AshDeeming** [comment]
Hi @czei 
The desktop API will need to be used for an app to replace AgencyCloud screens 
Please see : https://foundations-documentation.reapit.cloud/api/desktop-api

**Comment by czei** [comment]
Thank you for the pointer.   Does that mean the AgencyCloud screens are available for editing in the Desktop API, or rather that any replacement would have to be written from scratch?

**Comment by AshDeeming** [comment]
Hi @czei 
It depends what your app is trying to do - you can launch your app from a specific section of AgencyCloud or replace a screen. 
https://foundations-documentation.reapit.cloud/api/desktop-api#agencycloud-interaction-api

Please also note that if you wish to replace a screen, we provide the design layouts & icons etc, to do so via the Elements library: https://foundations-documentation.reapit.cloud/app-development/elements
https://foundations-documentation.reapit.cloud/app-development/elements
