### ISSUE TITLE
How we can connect the api and can get the redirect URL.

### ISSUE THREAD

**Issue by ServonSupport** [reapit/foundations#8279]
Hello

We have to insert form data into Reapit using Reapit API. So we need your help.

Please check the below screenshot to know about the app name - "bourne-estate-agents-naive-distribution"
See - https://share.getcloudapp.com/GGuJ6GEB

We face problems while generating state value and authorization code value. 
    1. See the error - https://share.getcloudapp.com/YEuDXAdL
    2. We are following the below documentation for the **Authentication flow**
        - https://foundations-documentation.reapit.cloud/api/reapit-connect#authentication-flow
        - https://developer.okta.com/blog/2018/04/10/oauth-authorization-code-grant-type
        - https://foundations-documentation.reapit.cloud/troubleshooting/reapit-connect
        
Where can we get the redirect URL, can you share the steps?
Also please share the format of the PHP code, and how we can connect to your API to get the access token.

Can you give me some guidance on this?

Many thanks,

**Comment by AshDeeming** [comment]
Hi @ServonSupport 
The error screen shot appears to show your log-in session - this should be the email addressed used to access the developer portal.  
Please confirm the steps taken before seeing this screen?

**Comment by ServonSupport** [comment]
Hii @AshDeeming 

**Please confirm the steps taken before seeing this screen?**
We are logged in using a developer account. And then we called the following URL to Chrome browser.
https://connect.reapit.cloud/authorize?response_type=code&client_id=774rukvjcdik5fmmcekrika7q5&redirect_uri=https://developers.reapit.cloud/

Then we are getting this type of error. https://share.getcloudapp.com/YEuDXAdL
I think after entering the Redirect URL correctly the error will not occur.

**Questions:**
Where can we get the redirect URL, can you share the steps?
Share the format of the PHP code, and how we can connect to your API to get the access token.

**Comment by ServonSupport** [comment]
Any update on the above?

Thanks!

**Comment by AshDeeming** [comment]
Hi @ServonSupport 
Please could you check the below section of the documentation & confirm if this helps resolve:
https://foundations-documentation.reapit.cloud/troubleshooting/reapit-connect

**Comment by ServonSupport** [comment]
Hi @AshDeeming

We checked the documentation as suggested and it seems that we had not set the Redirect URL.

However it seems that only the client can set the redirect URL as we do not have access to do this as developers.

We asked the client (Bourne), via a zoom meeting, to login to the Reapit Cloud so that we could guide them how to do this, however they do not have the same APP as we have created in our developer account. (See screenshot below)

So this means we can not ask them to set the redirect URL, and since we as developers do not have access to do this we are stuck.


<img width="1086" alt="Screenshot 2023-01-05 at 11 57 57" src="https://user-images.githubusercontent.com/117939110/210776417-d5cc8bb7-5688-4542-84cc-095eee5e8cca.png">

Please also see the screenshot of the APP we are developing

![Developers 2023-01-03 at 7 45 31 PM](https://user-images.githubusercontent.com/117939110/210776654-23fd1b67-7fa3-4e32-882b-1909e77a16cb.jpg)

Can you please let us know the exact steps of how we are supposed to do this?

**Comment by ServonSupport** [comment]
Hi @plittlewood-rpt 

Thanks for your help.

We have created a new app with the correct type(AgencyCloud Functionality) and set the redirect URL.
See the newly created app screenshot - https://share.getcloudapp.com/5zu2n66q

Now the Authentication flow is completed and we can get instant access to data hosted in your sandbox environment using reapit API.

How we can add data into reapit(live account) using API? 

Thanks!

**Comment by plittlewood-rpt** [comment]
Hi @ServonSupport glad you got the auth sorted. You cannot access live production data until your app is listed and installed by the relevant customer. Please see [this documentation ](https://foundations-documentation.reapit.cloud/listing-your-app)about the listing and app approval process.

**Comment by ServonSupport** [comment]
Hii @plittlewood-rpt 

Thanks for your help.

We are facing an issue generating new a access token using a refresh token.

We generated an access token using the authentication flow and the access token expires in 60 minutes.
When we try to generate a new access token using the refresh token we get a 400 error(invalid_request).
[response] => Array
        (
            [code] => 400
            [message] => Bad Request
        )
See - https://share.getcloudapp.com/ApuegdYW

We also checked in the documentation why this error is coming but we didn't find any solution so please help us to generate a new access token using the refresh token.

Many thanks!

**Comment by plittlewood-rpt** [comment]
Hi @ServonSupport assuming your client id and refresh token are being set in your PHP code correctly, that request looks OK. What are you getting in the response body?

**Comment by ServonSupport** [comment]
@plittlewood-rpt 

What are you getting in the response body?
**Ans:** [body] => {"error":"invalid_request"}

**Comment by plittlewood-rpt** [comment]
You'll get an invalid request error if your refresh_token is blank. Can you double check that your variables are being set correctly?

**Comment by ServonSupport** [comment]
@plittlewood-rpt 

I appreciate your help so much.
The access token issue is fixed.

Thank you.

**Comment by ServonSupport** [comment]
Hii @plittlewood-rpt 

We have one query.

We have used Gravity Forms to add valuation request form data. The data entered in the valuation form is to be inserted into enquiries in Reapit.
See the valuation form screenshot - https://share.getcloudapp.com/yAuABvdy

We have created an app for Authentication flow and Client credentials app which you can see in this screenshot. https://share.getcloudapp.com/mXubzB9o

We are also going to insert the data from the Valuation Request Form into the Reapit (Live Account) using the API.

So which of these 2 methods is suitable for it?
1) Authentication flow
2) Client credentials flow

Please can you tell us?

Many thanks!
