### ISSUE TITLE
GetExtra Function not available in Snowflake when trying to use Snowflake instead of mySQL

### ISSUE THREAD

**Issue by Shiva-Bluerunner** [reapit/foundations#8286]
GetExtra Function not available in Snowflake when trying to use Snowflake instead of mySQL

Some of our few queries using GetExtra, Please help to migrate this function to Snowflake- https://g***174.**-west-2.aws.snowflakecomputing.com/

Below screenshot from Mysql

![image](https://user-images.githubusercontent.com/121673080/210086500-4dfe4aae-0eaf-4a8d-9541-602981c25f77.png)

Below screenshot from Snowflake

![image](https://user-images.githubusercontent.com/121673080/210086684-253c1ecf-82bf-45d2-b556-668a23575965.png)

**Comment by plittlewood-rpt** [comment]
Hi @Shiva-Bluerunner you should find you can now use the GETEXTRA function in your Snowflake demo account. Let me know if any issues. Thanks
