### ISSUE TITLE
YourMoveFirst - Permissions for Data incorrect (GDPR)

### ISSUE THREAD

**Issue by BYMIntegrations** [reapit/foundations#8291]
**Describe the bug**
When we initially set up YourMoveFirst on the BriefYourMarket App for Foundations there was 95k contacts given to us from branches that we shouldn't have permissions for. They have come through without branch names.

What happened with the permissions for this account to allow us to pull these contacts initially?

Company Name: Your Move
App Code: YOM-GHNV
Date of Install: 24-11-2022

**Expected behaviour**
Only expected two branches, Wishaw and Lanark

**Screenshots**
If applicable, add screenshots to help explain your problem. Please ensure that screenshots do not include sensitive data such as personally identifiable information. If you do have private or sensitive information you need to share that will help with aiding resolution of this issue, please email sinfo@reapitfoundations.zendesk.com adding the issue number as the subject line. Please only use this mailbox to share information you cannot add to this issue.

**Device (please complete the following information for web issues):**
 - Device: [e.g. iPhone6, PC, Mac]
 - Browser [e.g. Chrome, Safari]

**Additional context**

**Comment by HollyJoyPhillips** [comment]
Hi @BYMIntegrations please could you provide an example contact record?

**Comment by roscoe2001** [comment]
@HollyJoyPhillips would you be able to provide an update direct to us on the latest on this one please.

**Comment by HollyJoyPhillips** [comment]
Hi @roscoe2001 I'm just waiting for an example reference at the moment so I can investigate. Thanks.

**Comment by plittlewood-rpt** [comment]
Carrying to new sprint due to ongoing discussions

**Comment by plittlewood-rpt** [comment]
Closing item down as email exchanges ongoing between both parties
