### ISSUE TITLE
Developer App Consent view vs. Agent view

### ISSUE THREAD

**Issue by quigger** [reapit/foundations#8292]
On the APP CONSENT PAGE:
https://developers.reapit.cloud/apps/XXXXXXXXXXXXXXXXXXXXXX/consents

I can see one user has not accepted:
![image](https://user-images.githubusercontent.com/644502/210620911-dcfae049-38f2-4f96-abcf-1582d246f15e.png)

However, they say that there is nothing to accept in their admin.

One side says NOT OK (Dev) and the other view (Agent) says OK.

How can we fix please?

**Comment by AshDeeming** [comment]
Hi @quigger 
The email address stated on the pending line would have received an email with an 'approval link' & this user should be the original admin/app installer. 

If they are experiencing issues with this process, please could you forward the clients consent for the revised permissions to the below & i'll pick up directly: support@reapitfoundations.zendesk.com

**Comment by quigger** [comment]
Thanks @AshDeeming 

I've sent two related emails to: support@reapitfoundations.zendesk.com

**Comment by AshDeeming** [comment]
Thanks @quigger 
I've pushed the approval through, following consent via email for the pending client.
