### ISSUE TITLE
Creating a document with type of 'OR' fails with a validation error

### ISSUE THREAD

**Issue by garrym** [reapit/foundations#8295]
**Describe the bug**
When creating a document via the platform API the document type of `OR` is rejected and returns a 422 response even though it is on the list of accepted document types on the [Swagger documentation page](https://developers.reapit.cloud/swagger).

Example CURL request:

```
curl --location --request POST 'https://platform.reapit.cloud/documents/' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json' \
--header 'reapit-customer: [REMOVED]' \
--header 'api-version: 2020-01-31' \
--header 'Authorization: Bearer [REMOVED]' \
--data-raw '{
  "associatedType": "property",
  "associatedId": "[REMOVED]",
  "typeId": "OR",
  "name": "file.pdf",
  "isPrivate": true,
  "fileData": "data:application/pdf;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg=="
}'
```

Returns response:

```
{
    "errors": [
        {
            "field": "type",
            "message": "The value provided must be exactly 3 characters"
        }
    ],
    "statusCode": 422,
    "dateTime": "2023-01-06T10:43:37.7403517Z",
    "description": "One or more validation failures have occurred. Please refer to Errors list for details"
}
```

According to the document types endpoint here: https://platform.reapit.cloud/configuration/documentTypes the document type of `OR` should be accepted. Excerpt below:

```
...
  {
    "id": "OFF",
    "value": "Offers"
  },
  {
    "id": "OR",
    "value": "Other"
  },
  {
    "id": "PAD",
    "value": "Payment Advice"
  },
...
```

When 

**To Reproduce**
Steps to reproduce the behaviour:
1. Perform the CURL request above ensuring that the bearer token, customer ID and associated ID are replaced with valid values for your account.
2. A 422 HTTP response code is returned with an error response, example above.
3. Modify the `typeId` value to be another document type but with a 3 letter type code, e.g. `CRT`
4. Make the request and a 201 response is returned.

**Expected behaviour**
- The request should return a 201 Created HTTP response status code.
- A private document should be created with the type category of 'Other' within Reapit. 

**Screenshots**
None

**Device (please complete the following information for web issues):**
- Device: PC
- OS: Microsoft Windows 11 Pro 10.0.22621 Build 22621
- Browser: N/A
- Software: Postman v10.6.7

**Additional context**
After speaking with Reapit support the agent suggested that certain document types may be disabled for specific accounts. If this is the case I can provide more details about the account in question if required.

This request is not being made against sandbox.

**Specification**
- Project: Reapit.Services.Documents
- Update CreateDocumentCommandValidation and UpdateDocumentCommandValidation rulesets to allow typeId of length 2 OR 3. Ultimately this issue is down to misconfiguration of AgencyCloud however there are no controls to prevent short codes being used (I will log this separately with the AC team)
- Ensure tests are updated to suit these changes

**Comment by plittlewood-rpt** [comment]
Logged item with AC development team for review: PBI-4350

**Comment by rochellelevy** [comment]
@plittlewood-rpt is there somewhere I can view that ticket, see the status?

**Comment by plittlewood-rpt** [comment]
Hi @rochellelevy unfortunately that's an internal ticket - we are still going to adjust the validation on this endpoint for you though so it will be fixed soon. I'm just keen to try and get some controls into AgencyCloud surrounding this for the future.. Hope this helps

**Comment by rochellelevy** [comment]
Thanks Pete, its going to block us from releasing a new feature to users, so would be good to get an idea of when this will be done. We're due to release at the end of the month.

**Comment by plittlewood-rpt** [comment]
Someone is working on it now, so it should go out later today or tomorrow

**Comment by rochellelevy** [comment]
Brilliant :) thank you!

**Comment by garrym** [comment]
Many thanks to you and your team for the quick turnaround on this @plittlewood-rpt
