### ISSUE TITLE
Areas API return duplicate area name

### ISSUE THREAD

**Issue by bva-clara** [reapit/foundations#8300]
**Describe the bug**
Different areaIds return the same area name

**To Reproduce**
Steps to reproduce the behaviour eg:
1. Go to 'https://platform.reapit.cloud/areas/FFC'
2. Go to 'https://platform.reapit.cloud/areas/FFH'
3. Both endpoints return "Fforest-Fach" in name field

**Expected behaviour**
Each area id would refer to a different area

**Comment by plittlewood-rpt** [comment]
Hi @bva-clara - please can you let me know the customer id this issue is in relation to? Ultimately we don't control what goes into some systems and the customer manages it themselves so what you are getting back will be accurate, it will have just been added twice.

**Comment by plittlewood-rpt** [comment]
Hi @bva-clara  do you need any further assistance? Thanks

**Comment by plittlewood-rpt** [comment]
Closing due to lack of response
