### ISSUE TITLE
How we can fetch the area data from api

### ISSUE THREAD

**Issue by sarinwebch** [reapit/foundations#8310]
We have connect the website with reapit api code. We would like to fetch the area name from each property.
On API its showing [areaId] => far or [areaId] => jfe
We couldn't find the actual area name from the API. But on CRM its showing the actual name of the location/ area.

https://www.webchannel.agency/projects/lux/feed 
Feed api link.

**Comment by AshDeeming** [comment]
Hi @sarinwebch 
Please confirm you are using the Areas endpoint? 
See below from swagger;
![image](https://user-images.githubusercontent.com/61687775/211763197-2b150be7-f9d4-481a-85ea-8c42f2b45367.png)
****

**Comment by sarinwebch** [comment]
https://www.webchannel.agency/projects/lux/feed

We tried to fetch the areas but it's showing an error.

https://platform.reapit.cloud/areas/

**Comment by AshDeeming** [comment]
Hi @sarinwebch 

Please can you confirm/screenshot what error is being surfaced? 


In order to see the Areas associated with the client, you will need to Get /areas/
this will then show details for each, i.e. the below from sandbox:
![image](https://user-images.githubusercontent.com/61687775/212324445-0a323faa-381c-4d4c-a218-87bff741bf76.png)

**Comment by sarinwebch** [comment]
https://www.webchannel.agency/projects/lux/feed
On accessing the feed we are getting this as output

$curl = curl_init();
            
            curl_setopt_array($curl, [
              CURLOPT_URL => "https://platform.reapit.cloud/areas/",
              CURLOPT_RETURNTRANSFER => true,
              CURLOPT_ENCODING => "",
              CURLOPT_MAXREDIRS => 10,
              CURLOPT_TIMEOUT => 30,
              CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
              CURLOPT_CUSTOMREQUEST => "GET",
              CURLOPT_POSTFIELDS => "",
              CURLOPT_HTTPHEADER => [
                "Authorization: $token",
                "accept: application/json",
                "reapit-customer: LXB",
                "api-version: 2020-01-31"
              ],
            ]);
            
            $response = curl_exec($curl);
            $err = curl_error($curl);

**Comment by sarinwebch** [comment]
![Screen Shot 2023-01-16 at 1 56 33 PM](https://user-images.githubusercontent.com/117635005/212649980-85c34e54-580c-44c0-bf36-841061838be2.png)

**Comment by AshDeeming** [comment]
Hi @sarinwebch 

The team have reviewed & advised that you appear to be using: 

"accept: application/json",


This should be:

'Content-Type': 'application/json',

**Comment by sarinwebch** [comment]
https://www.webchannel.agency/projects/lux/feed/areas
Still the same issue.
curl_setopt_array($curl, [
              CURLOPT_URL => "https://platform.reapit.cloud/areas/",
              CURLOPT_RETURNTRANSFER => true,
              CURLOPT_ENCODING => "",
              CURLOPT_MAXREDIRS => 10,
              CURLOPT_TIMEOUT => 30,
              CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
              CURLOPT_CUSTOMREQUEST => "GET",
              CURLOPT_POSTFIELDS => "",
              CURLOPT_HTTPHEADER => [
                "Authorization: $token",
                "Content-Type': 'application/json'",
                "reapit-customer: LXB",
                "api-version: 2020-01-31"
              ],
            ]);

**Comment by sarinwebch** [comment]
![Screen Shot 2023-01-23 at 10 44 50 AM](https://user-images.githubusercontent.com/117635005/213980035-ee490f65-486e-44ab-b0cc-5a53f9006020.png)

**Comment by AshDeeming** [comment]
Hi @sarinwebch 
I assume your app is 'luxbridge-international-realty-sulky-treatment' - This currently does not have the 'area' permission(s) selected 
This can be done via 'Edit App' & then the installed client will need to approve before the revision itself can be approved.

**Comment by sarinwebch** [comment]
![Screen Shot 2023-01-25 at 9 25 41 AM](https://user-images.githubusercontent.com/117635005/214486797-886d6658-4fb7-414d-beda-824585ae3cfb.png)

Read areas option is not there. I have selected write area

**Comment by sarinwebch** [comment]
There is no option to update it. I have selected the write areas option. But i couldnt find any section to save

**Comment by AshDeeming** [comment]
Thanks @sarinwebch 
This is being reviewed & the ticket updated asap

**Comment by AshDeeming** [comment]
Hi @sarinwebch 
Please could you send the full request (including the access token) to: sinfo@reapitfoundations.zendesk.com
Thanks in advance

**Comment by AshDeeming** [comment]
Hi @sarinwebch 
An email response was sent last week, please can you confirm you have received, this has resolved the issue?

**Comment by sarinwebch** [comment]
Hi, 
issue is resolved. Now we are able to fetch the locations.
