### ISSUE TITLE
Developer Analytics updating realtime

### ISSUE THREAD

**Issue by quigger** [reapit/foundations#8313]
Hi

Are the statistics reported in the Developer Analytics section of RF admin real-time? or delayed?

e.g.
https://developers.reapit.cloud/analytics/calls
https://developers.reapit.cloud/analytics/costs

I think they might be on a schedule? not real-time?

**Comment by AshDeeming** [comment]
Hi @quigger 
These are almost real-time (>5 minutes delay)

**Comment by quigger** [comment]
Thanks @AshDeeming 

> These are almost real-time (>5 minutes delay)

I think you mean (about) smaller than 5 mins?

It's not my experience but I'll accept your answer.

**Comment by AshDeeming** [comment]
Hi @quigger 
Correct, up to 5 mins max delay. 

If you have any examples please let me know & I can request for this to be reviewed.

**Comment by quigger** [comment]
Thanks @AshDeeming 

I'll take screenshots if I spot it again.
