### ISSUE TITLE
Is it possible to retrieve a collection of applicant that do not have a lastCall date set?

### ISSUE THREAD

**Issue by AdamHall12** [reapit/foundations#8320]
Please take a look at our FAQ's before submitting an issue, as your question may already be covered in the documentation https://foundations-documentation.reapit.cloud/faqs

**Summary**
I would like to gather a collection of applicants that have a lastCall date before a certain date or null. I can get the ones before a certain date using "/applicants/?lastCallTo=2022-01-01" but this does not include applicants without a lastCall date. 

**Detail and or supporting links and screenshots**
![image](https://user-images.githubusercontent.com/102241930/211866299-86ab38b4-0444-40a3-8bb8-c23eef5d83ea.png)

**Comment by AshDeeming** [comment]
Hi @AdamHall12 
Please see the swagger docs to see the endpoints & their associated parameters & payloads:

Below is a screenshot of the GET Applicants with the lastCall (to & from) as parameters;
![image](https://user-images.githubusercontent.com/61687775/211868846-8bf678ba-a74d-4748-b12a-c83e32d3704e.png)

![image](https://user-images.githubusercontent.com/61687775/211868784-d92ab7ef-edf9-4b60-9774-af48cff9f4ea.png)

**Comment by AdamHall12** [comment]
@AshDeeming Thanks for getting back to me.

I have found that the lastCallTo does not pick up applicants that have not been contacted i.e. the lastCall value is null.

Is it possible to do this? If so, can you please explain how? Thanks

**Comment by AshDeeming** [comment]
Hi @AdamHall12 
This isn't currently possible
