### ISSUE TITLE
request call POST/Task API to create tasks time out

### ISSUE THREAD

**Issue by haitt** [reapit/foundations#8323]
**Describe the bug**
I call reapit api from server (and postman)
![Screenshot from 2023-01-12 15-18-32](https://user-images.githubusercontent.com/8380562/212036092-e9bb6c82-d16f-472f-a9c1-1e8e35f76796.png)
 to create journal entries and tasks. The api for journal entries work well but for create task return error

**To Reproduce**
Steps to reproduce the behaviour eg:
1. I call api ```https://platform.reapit.cloud/tasks```
2. See error:
```
{
    "message": "Endpoint request timed out"
}
```

**Specification**
- Look at tasks service in Australia and ensure it is functioning correctly. This is a fairly lightweight API so should be responding even considering the traffic routing that will be going on.

**Comment by ashindey12** [comment]
@haitt - May I know the geographical location the api was called from? It will help us understand if there was any region specific infrastructure issue.

**Comment by haitt** [comment]
@ashindey12 I call it from Viet Nam. Please check it out and let me know

**Comment by plittlewood-rpt** [comment]
Hi @haitt this should now be resolved. Please can you retest from your location and confirm. The service running on our Sydney infrastructure had hung. I'm looking into why the monitoring platform did not pick this up and alert us. Thanks
