### ISSUE TITLE
Access issue for Rest API

### ISSUE THREAD

**Issue by Shiva-Bluerunner** [reapit/foundations#8330]
Hi,

We have app created in https://developers.reapit.cloud/apps/11250701-9797-4620-929b-c277dc4659f6

AppName: BlueRunner Sales Dealbook
App Id: 11250701-9797-4620-929b-c277dc4659f6
We can create Token using clientID, secret and APPid but not able to access any entities, as it throws 401 error even though we have permission to access

Response we got is 
 {
    "statusCode": 401,
    "dateTime": "2023-01-13T16:42:23Z",
    "description": "The request cannot be fulfilled because it lacks the authentication credentials required to access the resource. Please generate a new access token and try again."
}
![image](https://user-images.githubusercontent.com/121673080/212373825-f72fd36f-c0de-4151-af79-185c10d08dbf.png)

Can you please check if we are missing any permission

![image](https://user-images.githubusercontent.com/121673080/212374071-857a5437-fcd7-4ce9-af42-6a6ff0090eb8.png)

**Comment by AshDeeming** [comment]
Hi @Shiva-Bluerunner 
An email was sent to the apps developer, regarding this app on Monday (16th) which may relate to your issue

**Comment by Shiva-Bluerunner** [comment]
hi @AshDeeming,

Who needs to look into this? Even we create another app having the same error over there as well.

**Comment by AshDeeming** [comment]
Hi @Shiva-Bluerunner 
There is an app revision pending, which has not yet been approved by the installed client & therefore the revision itself it pending.

**Comment by AshDeeming** [comment]
Hi @Shiva-Bluerunner 
I'm yet to receive a response regarding the pending revision (tsadler).
There is also a client with the app installed who will need to agree to the new permissions beforehand 
I'll close this ticket but please raise a new ticket if the problem persists once the revised permissions agreed & approved.
