### ISSUE TITLE
Date range for Completed properties

### ISSUE THREAD

**Issue by quigger** [reapit/foundations#8333]
Hi Reapit Foundations,

The GTH client has requested I place the following query into the Issue board. Ros (Reapit) requested it. Please see below.

It's regarding "completed" properties being auto removed based on a time period after completion. I suspect `internetAdvertising` is set to false? 

----
Hi Jason,

I have spoken to Ros about the open ended completion data coming through on Foundations and she has requested that you raise a ticket with Github to the Reapit dev team. We should be able to set a date range to avoid any manual data entry our side. I suggest we stick to roughtly 4/5 months as we currently have on our site.

Thank you,
Rachel
---

Kind regards,
Jason.

**Comment by AshDeeming** [comment]
Hi @quigger 

There are no automations in the Platform. You can obtain the completed data from the property.selling modal & control via this: 
![image](https://user-images.githubusercontent.com/61687775/212860277-976147e9-ca5c-44bf-8cd0-e72be0308041.png)

**Comment by quigger** [comment]
Thanks @AshDeeming 

Is there an equivalent 'date' for when a letting is "completed" please?

**Comment by quigger** [comment]
@AshDeeming 

Sorry to chase, any feedback on this one please?

**Comment by quigger** [comment]
Hi @AshDeeming 

Thanks.

Do you meant the Tenancy `startDate` and `endDate`? (where the `startDate` might signify the completed date? as it's when the letting starts?)

or

Do you mean: `endDateConfirmed` ? or is that not a data and something else?

**Comment by quigger** [comment]
Thanks @AshDeeming 

What do "Reapit" mean by End confirmed please?

---

The reason we are asking is the client wants to hide (after a certain time) "finished" lettings after they are let.
We can hide after say 2 months but what date would we use? and would we need the "End confirmed" flag?

I know that's for the client to decide but Tenancy start would be more relevant for a newly let letting, rather then when the tenancy ends? I don't know how the "End confirmed" flag could be relevant for this?

**Comment by AshDeeming** [comment]
Hi @quigger 
Please see the below from the AC user guide which should help on how end users use AgencyCloud: 
![image](https://user-images.githubusercontent.com/61687775/214264828-c4380951-d9e6-451d-b77f-a6db70e0171d.png)

**Comment by quigger** [comment]
Thanks @AshDeeming 

Is the Tenancies endpoint a new permissions request for the AppMarket app?

What happens if there is a letting with no tenant? what date is used then?
What happens if there is a letting with a tenant who is leaving, are the current renting tenant dates relevant?
