### ISSUE TITLE
Property is not marked as modified when set to withdrawn

### ISSUE THREAD

**Issue by eddybennett** [reapit/foundations#8337]
**Describe the bug**
When a property is set as withdrawn in the CRM on Foundations it does not come through as modified in the feed data, therefore it's not possible to remove properties in an efficient manner when they are made withdrawn. 

**To Reproduce**
We are using a query that checks the last X number of days of modified properties and the withdrawn properties do not come back in the results.

**Expected behaviour**
We expect the properties that have been made withdrawn to have their modified date updated so we can then return them in our query.

**Comment by plittlewood-rpt** [comment]
Hi @eddybennett - when a property is withdrawn the modified and eTag are indeed updated. Can you give some more information about why you believe this not to be the case so we can investigate further? Thanks

**Comment by plittlewood-rpt** [comment]
Closing due to lack of response
