### ISSUE TITLE
Unable to get certificates for certain reapitCustomerIds

### ISSUE THREAD

**Issue by ethangates** [reapit/foundations#8338]
**Describe the bug**
When using our application which is integrated with Reapit's API, users may download ('import') certificates stored within Reapit from time to time, when trying to do this certain customers are being met with the following exception from Reapit:

```
{"statusCode":403,"dateTime":"2023-01-17T09:39:48.3657098Z","description":"The identity attached to this request does not have the required permission to access the requested data. If you think you should be able to access this data, please use the Reapit Foundations Developer Portal to contact us to discuss the problem"}
```

It is likely you will see a collection of failed requests from us in the last 24 hours on certain certificateIds. We are unsure why this is happening and the affected customers don't seem to know either.

Is it possible to look at the error from the above datetime to see what issue is happening here please?

**To Reproduce**
Steps to reproduce the behaviour eg:
1. Make a GET request to Reapit's API for certificates associated with a certain property (200 - OK)
2. Attempt to download a specific certificate from Reapit - (403 - see above)

**Expected behaviour**
We should be able to download the requested certificate from Reapit.

**Screenshots**
N/A

**Device (please complete the following information for web issues):**
N/A

**Additional context**
N/A

**Comment by AshDeeming** [comment]
Hi @ethangates 
Please could you provide addtional details for review including any customers IDs and document references
If sensitive please send to: sinfo@reapitfoundations.zendesk.com

**Comment by ethangates** [comment]
Hey @AshDeeming - I've emailed in the requested information 🙂

**Comment by plittlewood-rpt** [comment]
Hi @ethangates I've responded to you via Zendesk. This should be resolved but if you could confirm that would be great. Thanks

**Comment by ethangates** [comment]
Hi @plittlewood-rpt 👋 

This has been confirmed as resolved from my end now, so I'll close this - thank you!
