### ISSUE TITLE
Request for extrasField "Strapline"

### ISSUE THREAD

**Issue by richclicksmith** [reapit/foundations#8341]
- The name of the customer you represent

SWF (Swoffers) 

- The name of every field you need surfaced (if known)

"Strapline" 

- A screenshot of of the field(s) you require in the agency cloud user interface

<img width="434" alt="Screenshot 2023-01-18 at 10 19 45" src="https://user-images.githubusercontent.com/94179432/213146530-e9698117-b541-45d6-ac49-d6a566f366c8.png">

- A short use case as to why you require this data

The Strapline field is used to show key information on customer website.

Thanks.

**Comment by AshDeeming** [comment]
Hi @richclicksmith 
The strapline field should be available via the Properties endpoint, see example from SBOX below;
![image](https://user-images.githubusercontent.com/61687775/213191766-83d8bad4-f957-4f3e-a34c-df6505c4e9dd.png)

**Comment by richclicksmith** [comment]
Ah yes I see it. Apologies.
