### ISSUE TITLE
Etag didn't refresh after patching

### ISSUE THREAD

**Issue by abrahamseni** [reapit/foundations#8343]
**Summary**
After patching `metadata` property in `tenancies/{id}/checks/{id}`, the e-tag didn't refresh.
Does this the way it is or it should refresh with a new e-tag?

I mean if I patch the `status` property, the e-tag will refresh.

**Detail and or supporting links and screenshots**
Before:
![Screenshot from 2023-01-19 09-40-40](https://user-images.githubusercontent.com/94949137/213343429-4e266676-512a-4b7d-ae6a-93dff926834c.png)

After patching metadata property:
![Screenshot from 2023-01-19 09-41-23](https://user-images.githubusercontent.com/94949137/213343387-45c941ac-a54a-4320-ac09-510aa41c43ee.png)

**Specification**
- Project: Reapit.Services.Tenancies
- Review why modified date is not updated when metadata is the only thing that is patched when updating a tenancy check. This is different behaviour to when patching a tenancy. Ensure that fix is applied to any tenancy subresources that support metadata (I think this is just checks and renewalChecks). The way modified timestamps are applied to parent entities is done by the PlatformDatabase package and it may not be handling child objects correctly, however the fix may just be as simple as calling SetModified from within the update handles on the respective entity objects

**Comment by plittlewood-rpt** [comment]
Hi @abrahamseni I can see why this wouldn't be updating if your patch operation ONLY updates metadata. We'll discuss this in our refinement session today and report back

**Comment by abrahamseni** [comment]
For your benefit, if I patch only `metadata` property in `tenancies/{id}` it will refresh the e-tag.
So the behaviour is different.

**Comment by plittlewood-rpt** [comment]
Thanks @abrahamseni that's useful information

**Comment by plittlewood-rpt** [comment]
HI @abrahamseni I misread your initial ticket - this is actually by design at the moment for consistency with AgencyCloud. AgencyCloud does not update the modified date of the parent entity (in this case the tenancy) when one of it's children is amended (in this case the check). We match this behaviour in the API and this will be the same across all endpoints where there is a subresource available. Can you review and let me know your comments, along with any problems this might be causing you? To alter this is quite fundamental and will need fairly careful planning so if you can advise on the issues you're having because of it I'd be grateful. Thanks

**Comment by abrahamseni** [comment]
The problem that we face is there are two entities using this `metadata` property, ex. S and R
so currently we design it like this:
```javascript
metadata: {
  lettings: {}, // use by R
  others: {} // use by S
}
```

if S changes the `metadata` property in `others` and if the e-tag didn't change, R will think nothing changes and might patch different data. 
What we can do right now is refetching the data just before we patch it.

**Comment by abrahamseni** [comment]
I'm also thinking about another feat if possible to add into this metadata patching, so just like patching it in `Metadata` endpoint.
So if the payload body can accept an array:
```js
[
  {
    "value": true,
    "path": "CustomBoolField",
    "op": "replace"
  }
]
```
It will update specific property in metadata.
We try to not using `metadata` endpoint to avoid making two calls.

**Comment by plittlewood-rpt** [comment]
Hi @abrahamseni I've spec'd out fixing this bug which we'll get into a sprint soon. Please can I ask you to log the separate feature as a new issue if it's something you'd like us to look at. Many thanks

**Comment by plittlewood-rpt** [comment]
Hi @abrahamseni I can see you've closed this. Do you still need us to look at the eTag patching issue?
