### ISSUE TITLE
Unable to get property from API

### ISSUE THREAD

**Issue by ethangates** [reapit/foundations#8368]
**Describe the bug** When trying to get a property via ID, the API is returning a 404. According to the customer, this is in their Reapit platform.

**To Reproduce** Steps to reproduce the behaviour eg:
 
1. Call the endpoint: `/properties/VGN220421` with the client ID `LOC-GMOC`.
2. 404 is returned
 
**Expected behaviour** The API should be able to return the data instead of returning a 404.
 
**Screenshots** We have screenshots from the customer but they all contain a lot of personal information.
 
**Device (please complete the following information for web issues):**
* API integration
 
**Additional context** Ticket submitted by Goodlord regarding the API integration.

This happened in the past with a different company and it was related to some bad data, in case that helps, [Issue #7203](https://github.com/reapit/foundations/issues/7203). The provided propertyId is just one example of several where this is happening, they allege that there are multiple properties on their side in Reapit that they are unable to interact with using our integration.

I believe the customer has been in touch with you about this, I cannot access the ticket but its reference is [RSD-214395](https://reapitsupport.refined.site/portal/1/RSD-214395).

[RSD-214395]: https://reapit.atlassian.net/browse/RSD-214395?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by plittlewood-rpt** [comment]
Hi @ethangates - please can you provide the `x-amz-request-id` you are getting back from the server when you make your request? I've just tried this for this client id and am getting the property returned without issue

**Comment by plittlewood-rpt** [comment]
Hi @ethangates please can you confirm if you are still experiencing this problem?

**Comment by ethangates** [comment]
Hi @plittlewood-rpt -- apologies, I've been somewhat of a headless chicken this week! I think we can close this for now as we haven't heard back from the customer since an internal resolution attempt, it seems to be working for me now 🙂

**Comment by plittlewood-rpt** [comment]
Hi @ethangates to make you feel better you win the award for the best Github comment this week ;) thanks for confirming

**Comment by ethangates** [comment]
Hey @plittlewood-rpt - me again, apologies but I've had to reopen this. We're trying to GET this property using the same details as above, however we seem to be getting back that the landlords are `NULL`? I've seen screenshots from the client's end and everything appears to be fine. I remember something like this happened in the past (I think I referenced the issue in my original post) and it was to do with several Reapit clients merging and associations not being as they should.

We get a response back from the API, but at the point our client tries to handle the landlord it fails as we don't expect `NULL`. The datetime of my most recent request was `2023-02-07T10:40:49.689603+00:00`.

Would someone be able to take a look at this for us please?

**Comment by plittlewood-rpt** [comment]
Hi @ethangates I've just had a look at this using the example in this ticket, and the reason you cannot access the landlord is because it is associated to an office that doesn't exist as part of the LOC-GMOC group of customer offices (it is owned by a different brand operating within the main LOC database)

**Comment by ethangates** [comment]
@plittlewood-rpt you have just made my month, thank you so much! That's all I needed to know and I'll keep it in mind for the future too.

**Comment by plittlewood-rpt** [comment]
Great stuff. Thanks for confirming all OK :)
