### ISSUE TITLE
Error creating Applicant "WeeklyRentFrom must be provided for renting"

### ISSUE THREAD

**Issue by richclicksmith** [reapit/foundations#8375]
When creating a "renting" Applicant, I get the following error message:

{"errors":[{"field":"weeklyRentFrom","message":"WeeklyRentFrom must be provided for renting"}],"statusCode":422,"dateTime":"2023-01-20T09:18:45.0916158Z","description":"One or more validation failures have occurred. Please refer to Errors list for details"}

I've not seen weeklyRentFrom in any documentation and I've tried setting it to "1" and still get the error message.

**Specification**
- Project: Reapit.Services.Applicants
- Review error messages that come out of the validation ruleset for the create applicant command and ensure that the messages returned use the model property names rather than the command property names as they do not always match

**Comment by AshDeeming** [comment]
Hi @richclicksmith 
Please can you confirm if this is relating to a specific client or Sandbox data?

**Comment by richclicksmith** [comment]
Hi @AshDeeming 
Client is "SWF".

**Comment by plittlewood-rpt** [comment]
Hi @richclicksmith please can you email your payload over to sinfo@reapitfoundations.zendesk.com

Thanks

**Comment by richclicksmith** [comment]
Great. I've sent emailed that now @plittlewood-rpt

**Comment by richclicksmith** [comment]
Having done a little more testing it seems the error appears when rentFrom equals zero or is not provided. I'm okay to make changes at my end to accommodate that. I'll run some more tests and if all okay, I can close the issue.

**Comment by plittlewood-rpt** [comment]
Hi @richclicksmith I've just checked the validation rules and yes, when creating a renting applicant the rent from must be provided and be greater than zero. We'll look at correcting that validation error though because the property name being surfaced is incorrect
