### ISSUE TITLE
Reapit Foundations Apps key / secret rotation

### ISSUE THREAD

**Issue by designreact** [reapit/foundations#8376]
**Is your feature request related to a problem? Please describe.**

To increase security for production and UAT data we would like to rotate our application keys so that keys can be made invalid.

Currently this can only be done by creating, having approved and installing a new app and then removing the previous version, this is clunky and not ideal (we have lots of apps).

**Describe the solution you'd like**

**Option 1**
Provide a way to support 2 secrets which can be rotated, much like AWS IAM API Keys work.
https://aws.amazon.com/blogs/security/how-to-rotate-access-keys-for-iam-users/

**Option 2** (possibly easier to implement)
Add a new field to the app settings "Customer Secret", "App Secret" or similar.
Where this secret has been populated update API handling to check the secret is in a header "x-customer-secret" or "x-app-secret"
This would allow us as app developers to specify a parameter which we could rotate as required.

**Describe alternatives you've considered**

None that we know. Presently we are looking at replacing all of our apps (>20 in UAT) and moving calls to https://connect.reapit.cloud/token to a proxy, our developers and apps can then authenticate with the proxy which means we can control the access downstream from Reapit, though this isn't ideal and doesn't 100% satisfy our requirement to rotate API keys.

**Comment by designreact** [comment]
@AshDeeming further to our feature request we have another related request, I can raise a new issue or leave it here for you please advise.

Can we also request that client secrets are initially displayed after being copied, they are then hidden for good? Again much like AWS API keys work in IAM.

The reason we would like this is; even after we have cycled keys, developers can freely access App secrets in foundations this means if they were a bad actor they can still access sensitive information from Reapit or distribute the id and secret to an outsider.

**Comment by plittlewood-rpt** [comment]
Hi @designreact - this isn't something we can do at the moment but is on our roadmap for later in the year as part of an overhaul of the Reapit Connect system.

**Comment by RWilcox-Reapit** [comment]
Hi @designreact 

We do have a route to support this functionality.
It can be tracked here #8409 

Thanks

**Comment by rochellelevy** [comment]
@RWilcox-Reapit and @plittlewood-rpt we have created this feature request that Martin noted 

https://github.com/reapit/foundations/issues/8425

We think that this is pretty critical for securing customer data

**Comment by joshbalfour** [comment]
@plittlewood-rpt Implementation in the new version of reapit connect is being tracked over at #8621, when #8425 and #8376 are completed please close this ticket.

**Comment by plittlewood-rpt** [comment]
Backend work is done. Frontend work planned in #8475. Please track these tickets as this one will now be closed.
