### ISSUE TITLE
Data Refresh

### ISSUE THREAD

**Issue by DannySteptoe** [reapit/foundations#8382]
Last Data Sync Showing as 13th January 

I understand the data should update every 15 minutes.

We are using PowerBi using DirectQuery method. 

Pulling the Offers table as an example it shows the last  sync was 13th Jan and it doesn't seem to be regularly updating. 

![image](https://user-images.githubusercontent.com/103189661/213757111-e316189a-0688-4eaa-a53a-2575bf617a30.png)

**Comment by plittlewood-rpt** [comment]
Hi @DannySteptoe thanks for reaching out. We are investigating this now and will provide an update shortly

**Comment by plittlewood-rpt** [comment]
Hi @DannySteptoe  The warehouse should be up to date now - we are investigating and monitoring some intermittent connectivity faults between our data centre and Snowflake but your connector has been stable for the last hour or so. I will let you know on this ticket if the situation changes

**Comment by plittlewood-rpt** [comment]
Hi @DannySteptoe your data sync is currently stable and is being closely monitored
