### ISSUE TITLE
Data Warehouse issue Sherry FitzGerald 

### ISSUE THREAD

**Issue by awogan06** [reapit/foundations#8386]
Our BA has just noticed that the RPS data warehouse appears to only contains data up to 13/01/2023 and nothing since.

Audrey

**Comment by plittlewood-rpt** [comment]
Hi @awogan06 we are currently investigating the underlying issue

**Comment by plittlewood-rpt** [comment]
@awogan06 the warehouse should be up to date now - we are investigating and monitoring some intermittent connectivity faults between our data centre and Snowflake but your connector has been stable for the past few hours. I will let you know on this ticket if the situation changes

**Comment by awogan06** [comment]
Thanks for update Pete

**Comment by plittlewood-rpt** [comment]
HI @awogan06 just to let you know your data sync is still stable and is being closely monitored. The connectivity issue is ongoing but is not affecting your sync at all at the moment and we are working on the issue as a priority with one of our partners.
