### ISSUE TITLE
How to add Valuation Request Form data into the Reapit (Live Account) using the API

### ISSUE THREAD

**Issue by ServonSupport** [reapit/foundations#8388]
Hii @plittlewood-rpt 

We have one query.

We have used Gravity Forms to add valuation request form data. The data entered in the valuation form is to be inserted into enquiries in Reapit.
See the valuation form screenshot - https://share.getcloudapp.com/yAuABvdy

We have created an app for Authentication flow and Client credentials app which you can see in this screenshot. https://share.getcloudapp.com/mXubzB9o

We are also going to insert the data from the Valuation Request Form into the Reapit (Live Account) using the API.

So which of these 2 methods is suitable for it?
1) Authentication flow
2) Client credentials flow

Please can you tell us?

Many thanks!

_Originally posted by @ServonSupport in https://github.com/reapit/foundations/issues/8279

**Comment by ServonSupport** [comment]
Any update on the above?
Issue number for reference - https://github.com/reapit/foundations/issues/8279

Thanks!

**Comment by ServonSupport** [comment]
Hello @plittlewood-rpt 

Can you please answer the above question?
Please let us know if you need more details.

Many thanks,

**Comment by plittlewood-rpt** [comment]
Hi. As this is a new ticket it will be picked up in our next refinement session as per our development processes.  Thank you
________________________________
From: ServonSupport ***@***.***>
Sent: Wednesday, January 25, 2023 5:17:01 AM
To: reapit/foundations ***@***.***>
Cc: Pete Littlewood ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [reapit/foundations] How to add Valuation Request Form data into the Reapit (Live Account) using the API (Issue #8388)


External Message - Please be cautious when opening links or attachments in email
________________________________
Hello @plittlewood-rpt<https://github.com/plittlewood-rpt>

Can you please answer the above question?
Please let us know if you need more details.

Many thanks,

**Comment by ServonSupport** [comment]
Hi @plittlewood-rpt 

We have created an app for Authentication flow and Client credentials app which you can see in this screenshot. https://share.getcloudapp.com/mXubzB9o

We are also going to insert the data from the Valuation Request Form into the Reapit (Live Account) using the API.

So which of these 2 methods is suitable for it?
1. Authentication flow
2. Client credentials flow

We are waiting for your response.

Thanks!

**Comment by plittlewood-rpt** [comment]
@ServonSupport it sounds like a machine to machine configuration here which is the client credentials flow. Authorization code flow is used when a user is physically logging in to your application, which is not the case here. 

One important point to note is that I would not recommend calling the enquiries endpoint from directly on the public facing website as this will expose the short lived access tokens to public users and malicious actors could use the tokens in an undesirable way, causing risk to customer data. Instead, I would build a mechanism that sits between the website and our Platform APIs to hide this interaction

I'd recommend reading our documentation, specifically [the part around OAuth2 grants ](https://foundations-documentation.reapit.cloud/api/api-documentation#oauth-2.0-grants) which would have helped you here

Thanks

**Comment by ServonSupport** [comment]
@plittlewood-rpt 

Thank you for response.
We will check the documentation and get back to you if there is anything.

Many thanks!
