### ISSUE TITLE
Downloading developer edition

### ISSUE THREAD

**Issue by Ivana90GS** [reapit/foundations#8389]
We are trying to create agency cloud app and we need to have developer edition, however the page is empty and we cannot register and download it. 
![marketplace](https://user-images.githubusercontent.com/123378245/214056448-2d0879e3-7f59-48f5-bb9b-a82fa5d23ae8.png)

**Comment by AshDeeming** [comment]
Hi @Ivana90GS 
The provided screenshot relates to the AppMarket however to download developer edition, you will need to do this via the Developer portal: https://developers.reapit.cloud/desktop
