### ISSUE TITLE
Data warehouse not updating

### ISSUE THREAD

**Issue by pswire** [reapit/foundations#8393]
Hello,
The snowflake / data warehouse data has not updated since yesterday.
Can this be looked at?
Agent is Stirling Ackroyd.

**Comment by plittlewood-rpt** [comment]
Hi @pswire this is due to an ongoing incident which you can track at http://status.reapit.com/ - we are making good progress on a resolution and hope to have things back up and running properly today

**Comment by pswire** [comment]
Thanks for confirming, will keep an eye on the status page.

**Comment by plittlewood-rpt** [comment]
Hi @pswire your data should now be up to date. Connectivity is stable however we continue to work with our partners to fully resolve the underlying issue. We have increased monitoring of this area of the network so we can respond quickly if there are any further failures
