### ISSUE TITLE
Property Model url attribute is not reliably returned

### ISSUE THREAD

**Issue by Nialld** [reapit/foundations#8406]
We have 2 separate clients who use the Desktop / Marketing Details page / Internet - URL field to store a link to the property on their website

For one client this data is returned via the Property url field as expected

For another client, this data is not returned 

Your service desk did not seem to know what determines if this data is returned or not and directed us to create a ticket, can you please advise what determines if the url field is returned for the property model

thanks

**Comment by Nialld** [comment]
Any update on this? i have a feeling that this is a config switch that is missing but both clients are unaware what was set to make this data available

**Comment by plittlewood-rpt** [comment]
HI @Nialld this property is currently only returned if it has been explicitly set by the agent. AgencyCloud has a 'merge' mechanism which will try to build the property URL from parameters on the property record but will not actually persist it in the database (this is shown by grey text in the URL box). If the agent explicitly saves a URL against the record (at which point the text changes to black), it WILL be persisted in the database and be returned by the API

**Comment by Nialld** [comment]
Sorry for the delay in coming back, i just had a demo with a client who showed me this on his account, when he loads up the marketing tab on a property we can see the greyed out text, but no matter what he tried it cannot change it to black and persist it?

We tried to X the marketing tab and then save the property, that didn't work
We tried copying the text out and pasting it back in, but no joy.. any suggestions where we are going wrong here?

**Comment by plittlewood-rpt** [comment]
Hi @Nialld if you copy and paste the templated text back into the box it will result in it not being saved as AgencyCloud knows that the value is the same as what would be auto-generated and so doesn't save it. The reason it behaves in this manner is to protect us from needing to run massive data updates if the format of the URL for a specific property on the customer's website ever changes. Not storing it in the database means we don't have to update 000s records. It's likely this might end up being a long running ticket looking at the various URL templates we've got out there so it might be faster on this occasion for us to let you know the format of the URL if you're only working with a small handful of customers whilst we work out the best solution here. Let me know if this sounds feasible and if so which customers you need the format for.

**Comment by Nialld** [comment]
Hi @plittlewood-rpt , thanks for that info, it makes sense now. 

We had another client who was totally changing the URL as his website was independent of RPS and did NOT contain the property RPS ID as part of the URL. 

The 2nd client (the one this was not working for) was using the ID as part of the URL and was the one being suggested (in grey text) by you guys. We can work with this knowledge as we have a way of also creating the URL using a template such as https://agentsite.com/property/rps-[ID] and replace ID with the propertyId, giving us the URL as we need it.

So it would seem that the solution you have is fine, if a client changes the URL it will persist and we get it via the API, if it is default we can use URL template to build the URL ourselves.
