### ISSUE TITLE
Request for Open house semi structured property field

### ISSUE THREAD

**Issue by rajeshwl** [reapit/foundations#8408]
For one of our client we have Open House flag field being pulled in extra fields now, similarly now they got fields for updating dates for open house in the marketing section of property details. Can you please enable the extras field for the property API and share the field details.

Customer Code: TLC(TLC London)
Field: Open House Date Fields in Marketing section.

Screenshot:
![openhouse](https://user-images.githubusercontent.com/14073702/215036259-d99b8e18-b990-4304-802e-e6b8d099a569.png)

**Comment by plittlewood-rpt** [comment]
Hi @rajeshwl. Open house information is exposed as part of the appointments API. Please see the swagger documentation for the set of `/appointments/{id}/openHouseAttendees` endpoints which will begin to return data if you create (or amend) an open house parent appointment. If you can review and let me know if this answers your question I'd be grateful. Thanks

**Comment by rajeshwl** [comment]
Thanks for the information @plittlewood-rpt . We will check the appointment section and come back to you.
