### ISSUE TITLE
Add URL merge mechanism to properties API

### ISSUE THREAD

**Issue by MarcinuB** [reapit/foundations#8411]
Can I ask for a read permission to the “URL” field in the Agency Cloud marketing screen for a customer Savills.

Additional context
We're working on the integration for Savills and I was reading that URL field from the standard property model  using the "url" field. But this field seems to be returning null for both sandbox and Savills. 
We've raised a write request before for the Text field below (see [here](https://github.com/reapit/foundations/issues/8002) ) so my assumption is that this Url field is in extras too? If that's the case - could you grant us an access to it and if not - can you advise why we're getting null?
Attaching screenshots of example property from sandbox where Url field is not blank in the app but it is null in the response
![image](https://user-images.githubusercontent.com/8589350/215064086-cecc8ea4-9a14-4444-af09-864adb56f884.png)

![image](https://user-images.githubusercontent.com/8589350/215063861-4730e3dc-c69e-499e-acc4-dc99908a46ef.png)

**Specification**
- Project: Reapit.Services.Properties
- Assess feasibility of building merge mechanism into this service for handling the uPrpUrl merge format into a readable/usable URL. Speak to PL before proceeding. The outcome of the assessment will depend on any actions required as this may not be doable performantly so we may have to go back to the desktop team to see if they can store the URL explicitly in all cases
- Things to consider
  - Office level configuration values (based on property office) would need to be checked/used for customers with a franchise model
  - There is a plethora of possibilities with this mechanism, so we should review what is out there prior to making a call on whether or not we do this

**Comment by plittlewood-rpt** [comment]
Hi @MarcinuB this property is currently only returned if it has been explicitly set by the agent. AgencyCloud has a 'merge' mechanism which will try to build the property URL from parameters on the property record but will not actually persist it in the database (this is shown by grey text in the URL box). If the agent explicitly saves a URL against the record (at which point the text changes to black), it WILL be persisted in the database and be returned by the API

**Comment by MarcinuB** [comment]
Hi @plittlewood-rpt . 
Thanks for that info - I guess it makes sense :) Is there any way that I can do the same on my side based on the property model I'm getting from API? The client requests that we put the url to the website in our brochures - but if it's empty we can't do that really.

**Comment by MarcinuB** [comment]
Hi @plittlewood-rpt - can you answet to my question from the last comment please?

**Comment by plittlewood-rpt** [comment]
HI @MarcinuB - whilst you could do this at your end we are going to have a look and see what's involved doing it at our end. The problem you'll have doing it at your end is that the URL format will differ between customers, which makes it a bit of a maintenance headache for you. This has gone into the 2-weel sprint starting next week so we'll know more in the next couple of weeks

**Comment by plittlewood-rpt** [comment]
Hi @MarcinuB this is unfortunately going to be too complex and introduce too much latency to generate this on the fly as part of the API itself. I will however speak to our desktop developers to see if we can always store this in the database, but that introduces it's own problems with the number of records that would have to be adjusted if the customer's website URL format changed. One thing we could do fairly quickly in the meantime is to provide a means for you to access the URL format for each customer from the configuration service so you can build the URL at your end. Would that suffice for now?

**Comment by MarcinuB** [comment]
Hi Pete.
If all required variables are available to work with the URL format - then I probably can work with that. Can you provide a example of that URL format?

**Comment by plittlewood-rpt** [comment]
Hi @MarcinuB it's different for each customer and something out of our control as we don't typically build the websites for those agents. An example might look like `https://www.myagencywebsite.com/property-{Property.Code}`

**Comment by MarcinuB** [comment]
Hi @plittlewood-rpt - I wasn't clear enough - will the URL format only use Property.Code or other values from the Property model? If it's a simple enough job that I can handle with String.Replace - then I'm happy to go with that. If there is a more logic behind it - then it might be a problem.

**Comment by plittlewood-rpt** [comment]
Again it depends on the customer unfortunately. The majority ONLY use the property code, but some enterprise agents have more complicated formats that might use the office id and additional properties. Everything you should need should be in the property model but I can't guarantee that I'm afraid

**Comment by MarcinuB** [comment]
Understood. 
Let's go with that for now then. I will add it to my checklist to verify that per customer. If I will stumble upon some custom case - then I will annoy you here again. 
Please just let me know when this config will be applied and how can I access it.

Thank you for all support. I know you're busy with stuff but your service is top notch so far 👍

**Comment by plittlewood-rpt** [comment]
No problem at all Marcin. Glad you're happy with the responses even if they might not always be the ones you want :) We'll flesh out what we can do to surface the URL format and update you here

**Comment by MarcinuB** [comment]
Hi @plittlewood-rpt @HollyJoyPhillips 

I can see that this one was closed but I don't see the resolution. Is there anything I need to do on our side to have that working?

**Comment by plittlewood-rpt** [comment]
Hi Marcin - apologies. There is a huge amount of complexity in building these URLs on the fly so we've raised a ticket with our desktop team to consider whether or not we can explicitly store this in the database for all properties. I've not seen any update on that as yet. If there's specific customers you are working with, we can provide the URL format to you in the meantime

**Comment by MarcinuB** [comment]
Hi @plittlewood-rpt. 
This one was quiet for a while, but we have a customer asking about this again. Is there any progress on that one? 
As I said we're working with Savills on this and if you would be able to provide me with a url "template" that would help us a lot.

Thanks

**Comment by plittlewood-rpt** [comment]
Hi @MarcinuB I sent over the Savills URL format template via Zendesk on 28th April. Did you not receive it? Let me know if not and I will resend.

**Comment by MarcinuB** [comment]
Hi @plittlewood-rpt - you're absolutely right. I've just forgot about zendesk. Apologies for that.
