### ISSUE TITLE
How can I update the extrasField for a customer

### ISSUE THREAD

**Issue by MarcinuB** [reapit/foundations#8412]
Hi Team.

I have a general question.
How can I update the extrasField through the API call for a customer? I was looking for information on it in the API docs and FAQs but can't find it. 
Also - is there any extrasField exposed for the sandbox so I can test my code? 

Thank you kindly.

**Comment by AshDeeming** [comment]
Hi @MarcinuB 
Please see the below;
https://foundations-documentation.reapit.cloud/faqs#certain-fields-are-not-exposed-by-default-in-the-platform

**Comment by MarcinuB** [comment]
Hi Ash.
I've read that but that just explains how to read and not how to update the extras field with API. 
Also is there any extras field example enabled within the sandbox environment?

**Comment by AshDeeming** [comment]
Hi @MarcinuB 
The extrasField can not be updated.
Access to these need to be requested as per the above as can be Client specific. 

In the sandbox environment extrasFields include; Accommodation summary (on the rooms screen) and Valuation/MA date (Financial screen) are exposed for a property record.

**Comment by MarcinuB** [comment]
We've already requested access to the field (https://github.com/reapit/foundations/issues/8002#event-7776869207) and it seems to be write access granted. Are you sure we can't update any extras field in any way?

**Comment by AshDeeming** [comment]
Hi @MarcinuB 
Unfortunately it is not possible to update the extraFields

**Comment by MarcinuB** [comment]
Hi @AshDeeming - I didn't noticed that the update model for property was extended to accomodate that, so all good
