### ISSUE TITLE
Rental Protection Functionality 

### ISSUE THREAD

**Issue by pnGL20** [reapit/foundations#8415]
Hello, 

I've had a request from some large mutual customers of ours asking us to push their Rental protection policy numbers and Rental Protection start and end dates to Reapit via the Foundations API. They have indicated it is now possible for us to do that, however I'm struggling to find this in the API documentation. 

Is this possible? 

Thank you
Phil Noble
Product Lead 
Goodlord 

**Specification**
Project: Reapit.Services.Configuration
- Add new GET /rentInsuranceCancellationReasons and GET /rentInsuranceCancellationReasons/{id}  endpoints that exposes the config setting for `uRICancelList` (when configured this list replaces the default list, rather than the options being additive)
---
Project: Reapit.Services.Properties
- Add new `PropertyLettingRentInsuranceModel` to `PropertyLettingModel` above the utiltiies object as follows:
```
"rentInsurance": {
    "status": "enum",
    "referenceNumber": "string",
    "start": "shortdate",
    "end": "shortdate",
    "cancelledReasonId": "string", -- configurable list of cancellation reasons which will require a call to the configuration service
    "cancelledComment": "string",
    "autoRenew": bool
},
```

- If functionality is not enabled in configuration, this object should be set to null. The handler is already calling the configuration cache/service so we can determine this here without adding any additional latency to the request.
- For write operations we should only add this to the PATCH functionality. Model looks the same (`UpdatePropertyLettingRentInsuranceModel`), with the following validations:

- Start cannot be after end
- Status must be one of the actual values in the enum
- Reference number cannot exceed 100 characters
- When status is cancelled, a cancellation  reason is mandatory, but a cancelledComment is optional. Validate that the cancellationReasonId is valid for the dataset
- If functionality is not enabled in the customer's dataset, we should block the request (BadRequest 400)

**Comment by plittlewood-rpt** [comment]
To review with AgencyCloud BA to understand functionality.

**Comment by AshDeeming** [comment]
Client: ANE requires this too

**Comment by HollyJoyPhillips** [comment]
It seems to be stored as semi structured fields, example below for LOC: 

pRentInsFr={18/05/2023 00:00:00}
pRentInsTo={19/05/2023 00:00:00}
pRIPolicyRef='XXXXXXXXXXXXXXXX'

TBC if it needs to be requested on a customer by customer basis. 

Approved by Foundations team and moved to review, refinement session to be held today 18/05/23.

**Comment by plittlewood-rpt** [comment]
Need to dive into this functionality a bit more and understand any impact on client accounts as any rules here will need to be adhered to (ie if property is in a certain status, values should not be editable etc)

**Comment by HollyJoyPhillips** [comment]
The Foundations team have reviewed and confirm no risk to accounts so we can proceed.

**Comment by elizabethhamlin** [comment]
Hi @plittlewood-rpt  
Can I have an update on this one as Goodlord have advised that they are waiting on you but looks like you have closed the ticket? Wondering whether the best place for this API to be linked to is the Rent insurance premium functionality?
Thanks
Lill

**Comment by plittlewood-rpt** [comment]
Hi @elizabethhamlin this work has been completed as per the spec on the ticket so it will be with Goodlord to implement any changes at their end in their app now :) Hope this helps
