### ISSUE TITLE
Truncated description in the GET /configuration/preTenancyCheckTypes

### ISSUE THREAD

**Issue by abrahamseni** [reapit/foundations#8417]
**Background context**
When GET query to this endpoint `https://platform.reapit.cloud/configuration/preTenancyCheckTypes`
Some of the value has truncated description.

For example:
```json
[
  {
    "id": "PRE003",
    "value": "5 working days between tenancies (manage"
  },
  {
      "id": "PRE005",
      "value": "All details added (stepped rents/fees/cl"
    }
]
```

Expected
```json
[
  {
    "id": "PRE003",
    "value": "5 working days between tenancies (managed)"
  },
  {
      "id": "PRE005",
      "value": "All details added (stepped rents/fees/clauses/deposit/CPRs/special conditions/cladding clause)"
    }
]
```

This also has an effect in this endpoint: `https://platform.reapit.cloud/tenancies/CPL220008/checks`
It will also return a `preTenancyCheck` with a truncated description.
```json
{
      "id": "RPT23000674",
      "created": "2023-01-18T03:59:44Z",
      "modified": "2023-01-18T12:13:45Z",
      "description": "All details added (stepped rents/fees/cl",
```

**Comment by plittlewood-rpt** [comment]
Hi @abrahamseni this is due to the underlying AgencyCloud database field being limited to 40 characters.  The values are truncated in the AgencyCloud system also. Unfortunately there is nothing we can do to deal with this in our team as it would need a change to the database itself

**Comment by abrahamseni** [comment]
Thanks @plittlewood-rpt
