### ISSUE TITLE
Update/patch "regional" Applicant data via API

### ISSUE THREAD

**Issue by richclicksmith** [reapit/foundations#8420]
Client account: SWF 

I'm trying to update an Applicant with regional data but I'm not 100% sure how I should format the data. 

E.g. if I fetch Applicant OMA230016, I can see the following data:

![Screenshot 2023-01-30 at 16 58 02](https://user-images.githubusercontent.com/94179432/215543277-da0a9012-87d5-4d35-a9f9-5c8dd727fed4.png)

I would like to change that data via a Patch request e.g.:

![Screenshot 2023-01-30 at 17 00 23](https://user-images.githubusercontent.com/94179432/215543871-c9460849-629b-4e54-bef7-83d439a92967.png)

Which would appear in the client's RPS interface here:

![PXL_20230130_170258429 MP](https://user-images.githubusercontent.com/94179432/215544699-7b386317-9fdc-449f-b66d-c7e7b9d623db.jpg)

Is this possible? If so, how do I need to format my request?

**Specification**
- Project: Reapit.Services.Applicants
- Add ability to patch the regional Guernsey object (this only contains the `market` collection at the moment and uses the existing department behaviour in the service.
- Validate the options supplied against the list of options in the `market` type enum

**Comment by richclicksmith** [comment]
Hi. Just wondering if there is any update on this one? Our client (SWF) allows users to create their own property searches but without being able to set the region ( regional -> ggy -> market ) via the API, SWF have to manually collect and set this data via AgencyCloud.

Thanks.

**Comment by ashindey12** [comment]
Hi @richclicksmith you can check the model description, the list of market types can be mapped to:

![image](https://github.com/reapit/foundations/assets/111923754/c3b6f0d8-8e8b-4cf5-af1d-c07a1ab850f3)

**Comment by richclicksmith** [comment]
Awesome.. thanks v much.

**Comment by richclicksmith** [comment]
Is there any chance the same method could be applied to POST when creating new Applicants? Shall I submit as a feature request?
