### ISSUE TITLE
Post a document against a pending approval supplier invoice

### ISSUE THREAD

**Issue by MatthewGoddard** [reapit/foundations#8432]
**Is your feature request related to a problem? Please describe.**
I would like to be able to add a supplier invoice document against a pending approval supplier invoice transaction.

**Describe the solution you'd like**
A single API end point that I can POST a supplier invoice document against a transaction.

**Describe alternatives you've considered**
Property Managers can do this manually via the Pending Approval screen in Reapit's AgencyCloud product.

**Additional context**
![image](https://user-images.githubusercontent.com/10115484/215999255-81d8d887-63d4-497b-9dee-88667291166d.png)

**Comment by plittlewood-rpt** [comment]
HI @MatthewGoddard I think this should actually already work. You need to use POST /documents and set `associatedType` to `nominalTransaction` and `associatedId` to whatever ID you get back when you create the invoice (or from the transactions API). Let me know if this doesn't work but it looks like the support is already there. Cheers

**Comment by plittlewood-rpt** [comment]
Hi @MatthewGoddard can you let me know once you've reviewed this please? Thanks
