### ISSUE TITLE
Private APP clarification

### ISSUE THREAD

**Issue by ServonSupport** [reapit/foundations#8434]
Hi 

We are developing an APP to allow one of our client to be able to push valuation requests from their own website directly into reapit. My team doing this have come back and said that in order to do this we need to supply the following data as seen on:

https://foundations-documentation.reapit.cloud/listing-your-app/app-listing-review

- Icon, Featured Image, Summary, Description etc etc

However as this is a private APP and wont be available to the general marketplace, is this still necessary?

Can you also confirm that if we create and publish this APP we would be liable for the fees as published on https://foundations-documentation.reapit.cloud/developer-terms-and-conditions#schedule-2-fees
(Just to confirm this is for one client, and not available to the marketplace).

If the APP we are building does incur fees, is there any other recommended way for us to approach this project?

Sorry for a basic question but the documentation around this is not clear to me.

Kind regards

**Comment by AshDeeming** [comment]
Hi @ServonSupport 
the required fields are needed even if an app is private

with regards to charges this will need to be discussed with our partnerships team. Please let me have your email & i'll send an intro email

**Comment by ServonSupport** [comment]
Hi

***@***.***

**Comment by AshDeeming** [comment]
Hi @ServonSupport 
Just to advise that no message appears to have come through.

**Comment by ServonSupport** [comment]
Is that because I was asked for my email address and it is not displaying it?
Can I sent that to you privately

**Comment by AshDeeming** [comment]
Apologies @ServonSupport 
Please send to: support@reapitfoundations.zendesk.com & i'll introduce to our partnerships manager
