### ISSUE TITLE
Ability to filter out webhook calls by the resource Id

### ISSUE THREAD

**Issue by MarcinuB** [reapit/foundations#8437]
**Is your feature request related to a problem? Please describe.**
We're integrated our app with Reapit and we're providing ability to create brochures using Reapit property data. 
We're using webhooks to listen to data changes on property because we want to know about the price change (for selling and letting), location change, EPC and council tax. In the future we might extend this list and also work with property images updates. 
 
We have a two major problems with that: 
1. We're notified about all our customer properties changes, even if we're interested only in ones that was used to create a brochure. 
2. The topics are very wide. To accomodate our use case we need to use the **property.modified** webhook and we don't want to be notified about all changes for the property. 

**Describe the solution you'd like**
Below is just an highlevel idea:

1. Ability to create subscription through API that would take the resource type and resource Id and maybe topic name (or other way of defining the change that we're interested in). This returns the subscription object /id that client can store for updates later. 
2. Another version of webhook that would be called only for the resources that the subscription was created for. 
3. The subscription itself would have a lifetime of 72 hours (for example) - after that it would become expired unless it would be renewed through the API.

I think this would be really usefull for the property and property images resources, We're not using webhooks for other resource types so not sure if that would be beneficial.
The only problem I have with this solution within your context is that we would need some kind of longlife app token for updating this subscription as client token could be expired by the time the subscription would need to be renewed.
 
Above idea is based on the way that Microsoft have done with their API:
https://learn.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-1.0

**Describe alternatives you've considered**
What I had to do now is change the topic to **properties.selling.askingpricechanged** to lower the cost of webhook calls because it is unsustainable for us. 

**Additional context**
None, just a random emoji:🧑‍🔬

**Comment by plittlewood-rpt** [comment]
Hi @MarcinuB we are actually in the final stages of beta testing a new feature that gives developers the ability to build their own webhook filters. The documentation for this feature is here: https://foundations-documentation.reapit.cloud/api/webhooks#building-event-filters

It sounds like it will do exactly what you need, and you would keep the subscriptions up to date via the resthooks endpoints. Can you review and let me know your thoughts? Thanks

**Comment by MarcinuB** [comment]
Hi @plittlewood-rpt - that looks very promising. Can you confirm that I will be able to filter out by the property ids too?

**Comment by plittlewood-rpt** [comment]
Hi @MarcinuB you'll be able to build a filter on specific property ids yes as you'll have full control over how events get filtered etc with the new mechanism. Thanks for taking the time to review.

**Comment by MarcinuB** [comment]
@plittlewood-rpt - fantastic. Do you know the date when this will be available to use?

**Comment by plittlewood-rpt** [comment]
Hi @MarcinuB I've spoken to our PO here and we'd be happy for you to look at using this whilst it's in beta. If that's something you're interested can you let me know and we'll drop you an email separately?

**Comment by MarcinuB** [comment]
HI Pete. 
That would be awesome. will wait for an email from you. 

Cheers

**Comment by plittlewood-rpt** [comment]
HI @MarcinuB I've just sent over details about this. I'll leave this ticket open until you've had chance to review and have a play around with the filters to see if it fits your use case. Thanks

**Comment by plittlewood-rpt** [comment]
Hi @MarcinuB did you get chance to look at this to see if it would satisfy your needs?

**Comment by MarcinuB** [comment]
Hi Pete.
I did look into it briefly but didn't get a chance to work on it yet. Never enough time 🙄

**Comment by MarcinuB** [comment]
Hi Pete.
I finally found some time to look into the filters option. I was trying to create my first filter but I'm getting the 403 from API.
I was trying to use user token and also token obtained through the "Client credentials flow". Only listing webhooks works, but creating webhooks, creating filters and listing filters associated with webhook is not working. Using my account and app FluxPro Dev against sandbox. 

Apart from that I have a general question: 
Would you be able to provide me with example filter for a change? I'm not interested in properties created, so I will use diff, but how to define filter where price is different from the previous one. Your example only provide the example for Asking price being above 500k, and I'm a json schema noob :/.

And also general observation I figured that if I want to listen to a changes to multiple property attributes I need to create a multiple filters (property.id and price, property.id and location etc). It would be nice if you would provide more examples in the doc in the future that will show different angles and strategies to use that feature.

**Comment by MarcinuB** [comment]
Hi Pete.
I finally found some time to look into the filters option. I was trying to create my first filter but I'm getting the 403 from API.
I was trying to use user token and also token obtained through the "Client credentials flow". Only listing webhooks works, but creating webhooks, creating filters and listing filters associated with webhook is not working. Using my account and app FluxPro Dev against sandbox. 

Apart from that I have a general question: 
Would you be able to provide me with example filter for a change? I'm not interested in properties created, so I will use diff, but how to define filter where price is different from the previous one. Your example only provide the example for Asking price being above 500k, and I'm a json schema noob :/.

And also general observation I figured that if I want to listen to a changes to multiple property attributes I need to create a multiple filters (property.id and price, property.id and location etc). It would be nice if you would provide more examples in the doc in the future that will show different angles and strategies to use that feature.

**Comment by MarcinuB** [comment]
@plittlewood-rpt - see my previous comment. I forgot to tag you in 🤦. Would you be able to look into that? I will try to get to it over the weekend again.

**Comment by plittlewood-rpt** [comment]
Hi @MarcinuB I'll definitely look at this and come back to you. Not sure why you'd be getting a 403. Just need a bit of time to focus on the problem then I'll be able to respond :)

**Comment by MarcinuB** [comment]
Hi @plittlewood-rpt . 
did you get a chance to look into that issue with 403? I would like to start looking into that soon as we're getting a lot webhook calls for stuff that we don't need and we will have more installations soon

**Comment by plittlewood-rpt** [comment]
Hi @MarcinuB please accept my apologies for the delay on this one. It's on my to-do list for this week

**Comment by plittlewood-rpt** [comment]
Hi @MarcinuB - I'll close this down as we can continue the chat on Zendesk. Thanks
