### ISSUE TITLE
Completed properties not in feed

### ISSUE THREAD

**Issue by TheMoonman10** [reapit/foundations#8438]
I'm using the PropertyHive wordpress plugin to administer the properties from Foundations for Bell Ingram.  The following is a sample of properties that have not been included the feed, but should be:

AC Property Ref | Address | Status
-- | -- | --
PER220048 | Culloden House Court, PH1 3LU | Completed
OBN220032 | Lealt, PA60 7XW | Completed
INE220080 | Slumbay House, Church Street, IV54 8YP | Completed
PER220052 | Gallowhill Road, Kinross, KY13 0RD | Missives Concluded

Thanks

**Comment by AshDeeming** [comment]
Hi @TheMoonman10 
Please could you confirm that Property Hive have reviewed this as it may depend on their app & how they filter properties through

**Comment by TheMoonman10** [comment]
They haven't seen it yet, no.  Other completed properties are on the feed
though

**Comment by AshDeeming** [comment]
Thanks @TheMoonman10 
As its will be their app filtering these out, they will be best placed to review 

In the interim, please could you confirm a property ref (completed) which is appearing & I'll check if i can see any differences which could be affecting this.

**Comment by propertyhive** [comment]
@TheMoonman10 So to confirm you're saying that some completed properties are coming through, but others aren't? I think a good next step as @AshDeeming mentions would be to get an example of a completed one that is coming through and we can compare what's different between this one, and one that isn't importing.

Maybe the ones that aren't showing are archived or unavailable?

By default we don't import completed properties and a snippet like so would be needed to do this

https://gist.github.com/propertyhive/aa15ae08232f08c0d78aecfda63e2ba8

Not sure if any custom snippets have been implemented already to try and get this working?

**Comment by AshDeeming** [comment]
Hi @TheMoonman10 
Please could you advise if you're still experiencing any issues or if this is now resolved?
