### ISSUE TITLE
Reapit Foundations

### ISSUE THREAD

**Issue by oxinternet** [reapit/foundations#8439]
I have set up a Reapit Foundations API, installed the plugin and also updated the property import plugin. I need the following...

If this is a new import please email info@wp-property-hive.com with the following information:

Estate Agency Name
Reapit Customer ID
Billing Email Address

Any help appreciated. I'm baffled.

Simon Bennett
Oxinternet.

**Comment by AshDeeming** [comment]
Hi @oxinternet 
The requested information relates to & would need to be provided to the app 3rd party by the Customer?
