### ISSUE TITLE
404 errors on getting property through API

### ISSUE THREAD

**Issue by MarcinuB** [reapit/foundations#8441]
**Describe the bug**
Getting 404 errors on some calls to properties endpoint https://platform.reapit.cloud/properties/{id}
Customer: Savills
A couple of id's that are returned 404 for our background process for existing properties. I assume that token was right because it's 404 and not 403 error: 

https://platform.reapit.cloud/properties/RES160221 at Feb  1 16:37:55
https://platform.reapit.cloud/properties/CIS140005 at Jan 31 16:55:02 

I'm also assuming that you can't change the Property Id so it will be the same.
**To Reproduce**
No steps to reproduce as this seems to be happening only for some properties

**Expected behaviour**
Data is returned. 

**Additional context**

**Comment by MarcinuB** [comment]
Hi @plittlewood-rpt - that call against sandbox was just me trying to see if unauthorized call will in fact return 403 or 404 (like it would on some multi-tenant api's)

**Comment by plittlewood-rpt** [comment]
Thanks - can you let me know the id of the customer you're trying to locate these properties for?

**Comment by MarcinuB** [comment]
Hi. 
I just have a recent example - property id : KNH210104, Customer: SAvills Knightsbridge, user: emily.bell@savills.com

**Comment by MarcinuB** [comment]
Sure. 
Whenever customer is trying to publish a brochure in FluxPro - it will try to do two things:
1. Update Property in Reapit with the brochure url
2. Upload brochure pdf to the Reapit (through s3 upload and then by assiociating that document with the property)
For both our process tries to get the property details first and it will use the access token of logged in user (I've double checked and it's the fresh token that is taken on user login)
Below is a snippet from our logs:
![image](https://user-images.githubusercontent.com/8589350/216400113-b2c18b1c-2c16-4923-be68-23ef691cb4a3.png)

**Comment by plittlewood-rpt** [comment]
Hi - there's definitely something going on with your token handling - all the 404s are linked to Sandbox, not Savills. This is what I can see at this end for the same time period:

![image](https://user-images.githubusercontent.com/30798627/216402335-4bc04336-d89f-42e1-bc41-93330c3b6321.png)

**Comment by MarcinuB** [comment]
Right! I will keep digging.
it is always nice when both sides have a proper logging with a timestamps and all. Will let you know if I will need any more help on that one

**Comment by plittlewood-rpt** [comment]
No problem at all. I’ll leave the issue open for now until we’ve got to the bottom of it.

Cheers
________________________________
From: Marcin Blaszyk ***@***.***>
Sent: Thursday, February 2, 2023 5:51:15 PM
To: reapit/foundations ***@***.***>
Cc: Pete Littlewood ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [reapit/foundations] 404 errors on getting property through API (Issue #8441)


External Message - Please be cautious when opening links or attachments in email
________________________________
Right! I will keep digging.
it is always nice when both sides have a proper logging with a timestamps and all. Will let you know if I will need any more help on that one

**Comment by plittlewood-rpt** [comment]
Hi @MarcinuB can this one be closed? Cheers

**Comment by MarcinuB** [comment]
Hi @plittlewood-rpt - yup, this can be closed. Cheers
