### ISSUE TITLE
leaseRemaining validation while creating/updatingon Applicants endpoint

### ISSUE THREAD

**Issue by ss-dimasm** [reapit/foundations#8449]
**Summary**
When we're trying to create/update an sales applicant we're not allow to pass `0` on `minLease` or `maxLease` payload, it will throw an validation message "The value provided must be a positive integer". The weird case is while we're trying to create new applicant without any payload for `leaseRemaining` or given `null` to them, the created record will automatically have `0` value on `minLease` and `maxLease`, does it mean we're actually allowed to pass `0` on those payload while we're creating/updating the applicant? or that is how it works?

Thanks

**Specification**
- Project: Reapit.Services.Applicants
- Review create/update validation rules as the report above does suggest there's some odd behaviour. Passing 0 in min/max lease should be possible so likely just a > check that needs adjusting
- Ensure any tests are updated as appropriate

**Comment by plittlewood-rpt** [comment]
Hi @ss-dimasm thanks for reporting this. It does sound like there's something odd going on. I think passing zero should be acceptable, so we'll have a look to confirm and make any changes as necessary. Thanks
