### ISSUE TITLE
Request for Web Description field in Extra Description section- (Robinson Jackson - RBJ)

### ISSUE THREAD

**Issue by rajeshwl** [reapit/foundations#8450]
**Request**
Our client wants to show the Web Description in the Extra Descriptions section in the website. It's currently not available in the default API response. So we request you to enable the extras field for this and share the field name. 

Customer Code: Robinson Jackson - RBJ
Field: Extra Descriptions - Web Description

![image009](https://user-images.githubusercontent.com/14073702/216545580-80ca504a-854c-4985-8808-7e6364455681.jpg)

**Comment by rajeshwl** [comment]
@ashindey12 , Can you share the Field name for this.

**Comment by ashindey12** [comment]
@rajeshwl , The field name is pWebDesc.
