### ISSUE TITLE
Installation button missing on app in Market Place

### ISSUE THREAD

**Issue by Speedway1** [reapit/foundations#8463]
Customer reports that "SMS Speedway Nurture Pack add on" app no longer has the "Install" option. 
Please see screenshot below.

Reapit Support confirms that customer is on Agency Cloud (AWS). Customer was able to install the SMS Speedway Core Features. 

![BB_screenshot](https://user-images.githubusercontent.com/100301611/217099325-dd19a22e-0ff9-4a71-a774-0e1012c192bf.png)

Many thanks

**Comment by AshDeeming** [comment]
Hi @Speedway1 
The above screenshot is of the 'My Apps' section which would be where the app is located once installed, from the AppMarket. 

Only Admin users will have the ability to install an App or enable an integration
