### ISSUE TITLE
Name of user in Agency Cloud differs from that in ReapitConnectSession

### ISSUE THREAD

**Issue by simplychrisb** [reapit/foundations#8470]
**Describe the bug**
The name of the user displayed in the top left of Agency Cloud does not match that exposed to a market place app by the loginIdentity.name field defined on the ReapitConnectSession interface.

**To Reproduce**
1. Create a new user in Agency Cloud.
2. Sign into Agency Cloud as that user and launch your market place app.
3. Within the app access the loginIdentity.name field defined on the ReapitConnectSession interface; it will contain the expected value.
4. Update the name of the user.
5. Sign back into Agency Cloud and confirm that it displays the updated name.
6. Launch the app as and access the loginIdentity.name field; it still contains the previous name.

**Expected behaviour**
The loginIdentity.name field should contain the updated name.

**Additional context**
I will email additional customer related information to sinfo@reapitfoundations.zendesk.com.

**Specification**
- Consider approach to this problem which stems from AgencyCloud not updating Reapit Connect when the user's name changes from the negotiator setup or user profile screen. The easiest solution here may be to check the Reapit Connect vs AgencyCloud negotiator name at the point tokens are generated and run an update if the AgencyCloud name has been changed. Further details TBC in refinement
- Capture differences in pre token generator. If name in negotiator model does not match name currently held in Reapit Connect, fire event to SQS that the organisations service can pick up and process

**Comment by plittlewood-rpt** [comment]
Hi @simplychrisb thanks for reaching out. We'll discuss this on our refinement session today but it's not going to be the quickest thing to resolve unfortunately. The reason this is happening is because there is a particular area of AgencyCloud that does not automatically synchronise with Reapit Connect. This is something we are working on as part of an overhaul of Reapit Connect which is due  later on in the year. We'll look at what we might be able to do in the meantime.

**Comment by simplychrisb** [comment]
Thanks for the update.
In the meantime should I raise an issue if other users are affected?

**Comment by plittlewood-rpt** [comment]
Hi @simplychrisb you're welcome to yes if it's something anybody notices/is bothered about. We'll try and get something in place soon to deal with it
