### ISSUE TITLE
Receiving a 504 Gateway Timeout response periodically

### ISSUE THREAD

**Issue by ElliottRowland** [reapit/foundations#8474]
**Describe the bug**
We are sporadically receiving a "The remote server returned an error: (504) Gateway Timeout 

Steps to reproduce the behaviour eg:
Cannot consistently recreate the bug as I don't believe it is anything we're doing. It simply occurs sporadically for certain clients and certain times during the day and does resolve itself. However, it would be good to understand why this is occurring?

This happened yesterday (7/2/23) at:

11:05
12:07
17:12

**Expected behaviour**
We would normally expect to simply connect to the server without issue

**Screenshots**
NA

**Device (please complete the following information for web issues):**
Not entirely relevant as it's not specific to a device/operating system

**Additional context**
We can provide further details if necessary (don't want to post specific client information here)

**Comment by ElliottRowland** [comment]
Hi @plittlewood-rpt. It's the Property Uploader for Webdadi Websites App. The endpoint is /property and /propertyimages

Could I send a message separately with the specific client details as I don't want to publicly list them here?

**Comment by AshDeeming** [comment]
Hi @ElliottRowland 
Please send any sensitive details to: sinfo@reapitfoundations.zendesk.com

**Comment by ElliottRowland** [comment]
Hi @plittlewood-rpt . Is there any update on this issue? If it helps, we havent' seen any errors in the last 7 days.

**Comment by ElliottRowland** [comment]
Hi @plittlewood-rpt. I sent it to across to sinfo@reapitfoundations.zendesk.com back on the 8th Feb but have forwarded it again marked FAO Peter Littlewood for reference.

**Comment by plittlewood-rpt** [comment]
Hi @ElliottRowland we've made some changes recently to how traffic is routed internally. Can you confirm if you are still seeing these issues?

**Comment by plittlewood-rpt** [comment]
Hi @ElliottRowland please can you come back to me on the above?

**Comment by ElliottRowland** [comment]
Hi @plittlewood-rpt we haven't seen this error now in quite some time. We can raise if we come across it again, but we've not seen it since you've made the change so probably safe to assume it's fixed.
