### ISSUE TITLE
500 error when calling Properties/Get API

### ISSUE THREAD

**Issue by MarcinuB** [reapit/foundations#8481]
**Describe the bug**
500 error when calling Properties/Get API endpoint
![image](https://user-images.githubusercontent.com/8589350/217504181-88b85d4a-0433-4146-8a1d-3334a478c826.png)

Could you see what is the issue - this is affecting our customer (Savills)

Thank you

**Comment by AshDeeming** [comment]
Hi @MarcinuB 
This may be due to an issue this morning, which has now been resolved - please could you confirm the 500 error have stopped now?

**Comment by MarcinuB** [comment]
hi @AshDeeming 
It seems to be there still. See below call
![image](https://user-images.githubusercontent.com/8589350/217547124-5c7d46f0-2ef4-4d3f-b46a-6b60255209f5.png)

**Comment by plittlewood-rpt** [comment]
Hi @MarcinuB I can call the properties endpoint for the 2 properties with no issues. Can you confirm if this is still happening and if so does the issue seem to be intermittent or always affect the same resource ids? It would be good to understand a bit more about what you are seeing. I will have a look in the logs at this end too

**Comment by MarcinuB** [comment]
Hi @plittlewood-rpt - yeah we can close that one. Will report if anything like that will happen again.
