### ISSUE TITLE
URGENT: 401 error on Foundations API

### ISSUE THREAD

**Issue by NBareham** [reapit/foundations#8484]
**Describe the bug**
Foundations API not working

**To Reproduce**
Steps to reproduce the behaviour eg:
string(287) "{ "statusCode": 401, "dateTime": "2023-02-08T10:08:13Z", "description": "The request could not be fulfilled because the application associated with the request could not be located in the Reapit Foundations Marketplace. Please generate a new access token with the correct credentials." }" 

**Expected behaviour**
Should be able to call data

**Comment by AshDeeming** [comment]
Hi @NBareham 
Please could you confirm the app name?

**Comment by LouisaEvosite** [comment]
Hi @AshDeeming - I have discussed with Nicola, please close

**Comment by AshDeeming** [comment]
Thanks @LouisaEvosite
