### ISSUE TITLE
Find customerId when we click on agency cloud app from Diary

### ISSUE THREAD

**Issue by Ivana90GS** [reapit/foundations#8491]
After an appointment is created by a user, and our agency cloud app has been selected from the "Apps" button in the Diary window can we get the "customerId" of the user who creates that appointment?

**Comment by plittlewood-rpt** [comment]
Hi @Ivana90GS you should be able to ascertain all information related to the user making the request from the identity token. Please see documentation [here](https://foundations-documentation.reapit.cloud/api/reapit-connect#using-identity-tokens) and [here](https://foundations-documentation.reapit.cloud/app-development/connect-session) for more information. Thanks

**Comment by Ivana90GS** [comment]
When someone installs an application we have developed, we get an email stating:

We just wanted to let you know that 'test app' has just been installed by 'ivana@blafsoft.com' for the following client:
Sandbox Estates (SBOX)

Then in App -> Installations there's a list of installations with 'Reapit customer code' as one of the columns. 
This is the field we are interested in, and I believe 'SBOX' here is the 'CustomerId'.
Is this the same as the clientId that's retrieved with the session? (I can see agencyCloudId and clientId are both 'SBOX' in the session, so I'm uncertain which one is the customer id)

**Comment by plittlewood-rpt** [comment]
Hi @Ivana90GS clientId is the one you need :)
