### ISSUE TITLE
Can we customize Reapit elements or use different plugins when creating agency cloud app in react

### ISSUE THREAD

**Issue by Ivana90GS** [reapit/foundations#8492]
We need to add rich text editor in our agency cloud app which can display a html, however the Reapit elements support only basic text area. Can we use different text editor, or are there any different approaches to this problem?

**Comment by AshDeeming** [comment]
Hi @Ivana90GS 
Yes, no problem - we do the same ourselves on the app listing description page: (https://developers.reapit.cloud/apps/appId/edit/app-listing

We would just ask you make best efforts to keep to the style guide from Elements either by using the CSS classes or with your own styles. See screenshot for an example from our Geo Diary app listing;
![image](https://user-images.githubusercontent.com/61687775/217784038-03dd894b-fb21-4cf4-a2e4-25e13dc158cc.png)

**Comment by Ivana90GS** [comment]
Thank you I'll use this text area from app listing as an example.
