### ISSUE TITLE
How does a Reapit Client create an Office Group in their account?

### ISSUE THREAD

**Issue by jamieredfern** [reapit/foundations#8494]
Please take a look at our FAQ's before submitting an issue, as your question may already be covered in the documentation https://foundations-documentation.reapit.cloud/faqs

**Summary**
We are trying to help an estate agent set up an integration in the Reapit Foundations Marketplace, and need them to break up their account into Office Groups. They are unable to find this option in their account, and their Reapit Customer Success Manager has been unable to tell them how to do it and advised that we ask here on the agents behalf. Any information you can provide would be very helpful, the agent is quite frustrated at this point.

**Detail and or supporting links and screenshots**

**Comment by AshDeeming** [comment]
Hi @jamieredfern 
The customers CSM will be able to assist them as they will need to use the Marketplace Management app. see the below docs for more information; https://foundations-documentation.reapit.cloud/faqs#what-are-office-groups

**Comment by jamieredfern** [comment]
Would you be able to tell me what I should go back to them with? Because the Customers CSM has told us to ask here because they don't know

**Comment by AshDeeming** [comment]
Thanks @jamieredfern 
Please could you confirm the client - if sensitive pleases send to: sinfo@reapitfoundations.zendesk.com

**Comment by jamieredfern** [comment]
The client is Choices

**Comment by AshDeeming** [comment]
Thanks @jamieredfern 
The clients CSM has been made aware & will contact the client to discuss the potential app requirement 
Their contact email is: atownsend@reapit.com
