### ISSUE TITLE
Foundations Api default Image not showing as default image.

### ISSUE THREAD

**Issue by carl-humpherson-property-logic** [reapit/foundations#8501]
**Describe the bug**
The feature image in the foundations API (STE220302_08.jpg) doesnt match the image the customer has picked as their main image it is displaying (STE220302_22.jpg)

**Expected behaviour**
The image selected in their screenshot that is starred should be the image displaying as their main image.

**Screenshots**
![image](https://user-images.githubusercontent.com/55381582/217826348-fb493a52-7391-4556-98be-362ccba34cdb.png)

**Device (please complete the following information for web issues):**
 - N/A

**Comment by plittlewood-rpt** [comment]
HI @carl-humpherson-property-logic this is a known issue caused by a slight oddity in behaviour in AgencyCloud itself. If the user moves one of the images to a different position and then back again, it should resolve it as the index order for the images will be reset.

**Comment by TobyDunnEPS** [comment]
Thanks @plittlewood-rpt, we will add this as a standard response from our service desk to any clients who raise similar issues.  Is there a timeline for a bugfix?
