### ISSUE TITLE
Unable to Download an App

### ISSUE THREAD

**Issue by ewseygod** [reapit/foundations#8510]
Help needed! Trying to download an app through the RPS AppMarket but there is no button to download/install the app. After speaking to RPS support they have advised that the issue is with the Foundations API. 

App wanted is Integrated Interest v2.0, I am in contact with the team at Integrated Interest who have said that i should be able to click download instead of 'enquiring about integration'. 

I am the correct level user to download but still no way around it. 

Please contact me for more information.

**Comment by AshDeeming** [comment]
Hi @ewseygod 
Only a company admin user will have the ability to install apps or enable integrations
If you could confirm your email address via the below, i can check your access?
support@reapitfoundations.zendesk.com

**Comment by ewseygod** [comment]
Hi @AshDeeming 
This has now been resolved. Turns out that someone had already downloaded it from our office so no app download was needed! 
Thank you!
