### ISSUE TITLE
 Soap API for sub plots is not in rest API

### ISSUE THREAD

**Issue by sanjayisg** [reapit/foundations#8513]
Hi There,

I check soap API getPropertySubPlots is there any possibility we get same api in rest? 

We used rest api in our all development for most of the api work so it will be very helpful if we can get rest versio of api.

Thanks,

Sanjay Gupta

**Comment by AshDeeming** [comment]
Hi @sanjayisg 
The details around this would fall under Department data - Platform value; 'developmentPlot' 
https://foundations-documentation.reapit.cloud/platform-glossary#interpreting-department-data

See unmappedAttributes on the swagger docs

**Comment by sanjayisg** [comment]
Hi Ash,

One more question, is there any option in RPS where we can add multiple price bed wise Like:

Studio  - £10000
1 Bedroom - £12000
2 Bedroom - £15000

and so on..

Thanks,

Sanjay Gupta

**Comment by AshDeeming** [comment]
Hi @sanjayisg 
The current data surfaced via the Platform API is on a per property basis

**Comment by plittlewood-rpt** [comment]
Hi @sanjayisg please refer to the documentation on `PropertyModel._links` to understand how development sites are described in the JSON model. In addition, you can use the `masterId` query string parameter on a call to `GET /properties` to return sub plots of a specific site. Please let me know if this does not answer your query. Thanks
