### ISSUE TITLE
Proffitt & Holt property data attributes query

### ISSUE THREAD

**Issue by quigger** [reapit/foundations#8514]
We are trying to process this property ref: LNH220302 and retrieve some property attribute data.

From here:
https://reapit.atlassian.net/wiki/spaces/RW/pages/912326673/Prepare+a+property+for+marketing

We see these property attributes:
![image](https://user-images.githubusercontent.com/644502/218521839-7fb4af21-12a6-454b-b837-44cd7bca5721.png)

However, the client has sent us this version which he sees:
![image](https://user-images.githubusercontent.com/644502/218522093-d7bc6538-9e86-4e31-b99d-30094d7df4fd.png)

We are trying to access the property data for AGE where the client has set "New" but the API is not returning any properties with an "Age" value of New. We couldn't find any property with any Age values.

Note:
The clients version of the attributes are different to the documentation.

How do we access this clients `Age` data please?

We also noticed that "Village" wasn't available and "Off Street Parking" was only listed in `unmappedAttributes` and it was listed three times.

**Can you explain what's going on please?**

**Comment by AshDeeming** [comment]
Hi @quigger 
The property attributes can differ per client & dependant on the department selected (in the above case, General) 
Please see the below around interpreting this data:
https://foundations-documentation.reapit.cloud/platform-glossary#interpreting-department-data

**Comment by quigger** [comment]
@AshDeeming 

We didn't see “Age” data in `unmappedAttributes` as we did check. We will check again.

Can you check this particular property please?

**Comment by AshDeeming** [comment]
Hi @quigger 
Apologies, Age is part of the payload, Department depending, see the below from swagger docs model (https://developers.reapit.cloud/swagger);
![image](https://user-images.githubusercontent.com/61687775/218530586-6cc4db5d-be00-4337-a822-11e8dce7b55e.png)

**Comment by quigger** [comment]
Thanks @AshDeeming 

However, even though the client has ticked Age in admin it's not in any Foundation data as far as we can tell?

Can you check this property please: LNH220302 

Are we doing something wrong?

**Comment by AshDeeming** [comment]
Hi @quigger 
Please see the below attribute table in AgencyCloud for the referenced property: 
![image](https://user-images.githubusercontent.com/61687775/218533465-f8ae5352-6c2b-4817-bbe3-9f2f05741cda.png)

**Comment by quigger** [comment]
Thanks @AshDeeming 

That matches the screen I sent but the client did remove Character. So yours is newer.

Where do we find "Age" in the Foundation data - we've tried the suggestions you've made.

We also noticed that "Village" wasn't available and "Off Street Parking" was only listed in unmappedAttributes and it was listed three times.

**Comment by AshDeeming** [comment]
Thanks @quigger  - That was going to be my next question, if you can't see Village & Off Street parking either - it may be that the gap on the list is causing an issue/bug.
I'll amend this ticket for the back end team to review however it may require AgencyCloud config change to correct - The ticket will be updated accordingly.

**Comment by AshDeeming** [comment]
Hi @quigger 
The attribute titles have been added to this build (Parking, Age & locality) which should now allow for the sub-fields to be surfaced. Please could you test & confirm when possible?

**Comment by quigger** [comment]
Thanks @AshDeeming 

I queried using Postman - looks good.

![image](https://user-images.githubusercontent.com/644502/218739483-04a67a1e-dba7-4cc0-8343-37e3d6c6c5e9.png)

I'll close and ask my devs to check too.
