### ISSUE TITLE
Do these fields still exist in Foundations like WebServices?

### ISSUE THREAD

**Issue by quigger** [reapit/foundations#8515]
Do these fields still exist in Foundations like WebServices?

e.g.
        d = @data.xpath('//Directions').text
        d = @data.xpath('//Mileage').text
        d = @data.xpath('//Location').text
        d = @data.xpath('//Situation').text

Are there new equivalents please?

We have a client asking about "Location" data.

**Comment by AshDeeming** [comment]
Hi @quigger 
Please see the below which will best explain: 
https://foundations-documentation.reapit.cloud/faqs#certain-fields-are-not-exposed-by-default-in-the-platform

**Comment by quigger** [comment]
@AshDeeming 

Do we need to ask for extra permissions? or is this a config Reapit side on the client?

{
    "statusCode": 400,
    "dateTime": "2023-02-14T14:47:38.7486463Z",
    "description": "Access to one or more of the specified fields is not permitted. You must be granted access to this data beforehand"
}

**Comment by AshDeeming** [comment]
Thanks @quigger 
the data has been made available for the requested client on #8520
