### ISSUE TITLE
Renewal Checks desktop Integration

### ISSUE THREAD

**Issue by abrahamseni** [reapit/foundations#8516]
Regarding the integration, I think we basically need two types of code back:
```js
{
  tenCode: "MKT123",
  renewalCode: "MKT789",
}
```
Because the API for `renewalNegotiations` checks needs `tenancyId` and `renewalId`:
`tenancies/{id}/renewalNegotiations/{renewalId}/checks`

So if I can only check for `renewalCode` then it will be impossible to get the renewal negotiations checks.

Is there any idea how to solve this?
Thanks.

I think this one link to #8498

**Comment by plittlewood-rpt** [comment]
Hi @abrahamseni 

I've caught up with my colleagues on this but just to confirm what you are wanting to do here as it doesn't seem like what you are talking about on this issue, you are asking for a way to return all renewal negotiation checks in a single call, without needing to hit `GET /tenancies/{id}/renewalNegotiations/{renewalId}`

If this is the case, the easiest and probably more correct thing for us to look at doing is to allow embedding of checks into the response from `GET /tenancies/{id}/renewalNegotiations`. Would this work for you?

I'm not sure if you are asking for changes to the behaviour of AgencyCloud when using the desktop integration type, so apologies if there's been some misunderstanding here.

Thanks
Pete

**Comment by plittlewood-rpt** [comment]
hi @abrahamseni please ignore the above as I've spoken to Matt G :)

**Comment by HollyJoyPhillips** [comment]
Integration type is in production
