### ISSUE TITLE
Add nominal code to works order service

### ISSUE THREAD

**Issue by RLAV1** [reapit/foundations#8517]
Savills are looking to Partner with Bricks and Agents for their Invoice Automation solution 

as such Bricks and Agents require the Property Work Order Nominal Code to be exposed within the API 

**Specification**
- Project: Reapit.Services.Transactions
- Remove the need for a scope on the nominal account endpoints. These should be treated as configuration appointments (otherwise developers need transactions.read permissions just to get access to the different nominal account codes)

- Project: Reapit.Services.WorksOrders
- Add `nominalAccountId` string property to WorksOrderItemModel that exposes workdet.nomcode
- When a nominal code is set, add a new link to `WorksOrderItemModel._links` to allow self navigation to GET /transactions/nominalAccounts/{id}`

**Comment by AshDeeming** [comment]
Hi @RLAV1 
Does this relate to Data Warehouse or the worksOrders endpoint on the API?

**Comment by RLAV1** [comment]
Hey Ash, Correct this will be the Works Order endpoint on the API

**Comment by plittlewood-rpt** [comment]
PL to speak with NM to understand this functionality before proceeding

**Comment by plittlewood-rpt** [comment]
hi @RLAV1 will you need write access to this field or just read? Thanks

**Comment by neilpellowe** [comment]
This request forms part of a larger roadmap discovery item to review our current Endpoint offering and any additional areas we may consider opening up. Accounts and related fields will be reviewed as part of this discovery. Once complete, tickets will be updated.
