### ISSUE TITLE
Soap Credientails

### ISSUE THREAD

**Issue by sanjayisg** [reapit/foundations#8518]
Hi There,

I just wanted to know how I can get soap credentials from reapit, we are already using Rest API of reapit.

Thanks,

Sanjay Gupta

**Comment by AshDeeming** [comment]
Hi @sanjayisg 
This forum is for Platform related requested - SOAP is due to be deprecated & we therefore recommend using the Platform API 
A client who requires SOAP credentials will need to request this via their CSM

**Comment by sanjayisg** [comment]
Hi Ash,
Just query for this because my requirement was to store property price bed wise and after little research I think this can be achieve via getPropertySubPlots soap api so just wanted to check.

Can you please suggest what we can do get this done.

Thanks,
Sanjay Gupta

**Comment by AshDeeming** [comment]
Hi @sanjayisg 
Each property record will have its own price details under the selling section of the Properties endpoint

**Comment by sanjayisg** [comment]
Hi Ash,

I am not getting this, can you please explain. You mean each property can have only single price, it's not possible to add multiple price. is there any way we can add property in a way like bellow:

Main Property(and within that )
> Prop1 - 1 Bed
> Prop2 - 3 Bed
> Prop3 - 5 Bed

etc.

And there must be some relation to link them?

Thank,

Sanjay Gupta

**Comment by AshDeeming** [comment]
Hi @sanjayisg please refer to the documentation on PropertyModel._links showing how development sites are described in the JSON model.
In addition, you can use the masterId query string parameter on a call to GET /properties to return sub plots of a specific site
