### ISSUE TITLE
Extras Location

### ISSUE THREAD

**Issue by Simon-Homeflow** [reapit/foundations#8520]
**Request**

In order for us to grant access to Semi-structured 'extras' field data, please provide the following information in this request:

- ClientID: PRH
- All fields in Location
- Client requires that data stored in extrasLocation is displayed on website.
![image](https://user-images.githubusercontent.com/119927358/218791428-349aef6c-3df1-4db2-b3f7-bcf28a71d10b.png)

**Comment by quigger** [comment]
Can we make all fields available if present?

d = @data.xpath('//Directions').text
d = @data.xpath('//Mileage').text
d = @data.xpath('//Location').text
d = @data.xpath('//Situation').text

Maybe close related issue:
https://github.com/reapit/foundations/issues/8515

**Comment by RWilcox-Reapit** [comment]
Hi @Simon-Homeflow 

This is now done for client PRH. You can now specify 'extrasField=pLocation' as a query parameter to retrieve the location information requested above.

Thanks

**Comment by RWilcox-Reapit** [comment]
> Can we make all fields available if present?
> 
> d = @data.xpath('//Directions').text d = @data.xpath('//Mileage').text d = @data.xpath('//Location').text d = @data.xpath('//Situation').text
> 
> Maybe close related issue: #8515

Hi @quigger 

Please could you raise a separate ticket for this showing the fields requested in the format of this one along with the clientId.

Thanks,
Ryan

**Comment by quigger** [comment]
> Please could you raise a separate ticket for this showing the fields requested in the format of this one along with the clientId.

Added:
https://github.com/reapit/foundations/issues/8542
