### ISSUE TITLE
Possible to show metadata in AgencyCloud / RPS interface?

### ISSUE THREAD

**Issue by richclicksmith** [reapit/foundations#8524]
Question on behalf of client: SWF 

Is it possible to get an additional field added into a client's RPS / Agency Cloud interface? 

We are using a metadata / custom field for capturing additional Applicant data via the API and would like this data to be shown somewhere in the client's RPS user interface. 

Or perhaps it's already accessible and I'm not looking in the correct place?

The metadata key we are using is labelled "furtherInformation". In an ideal world, if it is possible, we would like it to show in the Requirements tab that they currently have (screenshots below).

![PXL_20230215_095916512](https://user-images.githubusercontent.com/94179432/218996336-5f2cd662-cf89-4ab0-b357-44c36f400438.jpg)
![PXL_20230215_095929033](https://user-images.githubusercontent.com/94179432/218996397-f07fed74-447a-4df5-8874-c08fa1cfd62e.jpg)

**Comment by AshDeeming** [comment]
Hi @richclicksmith 

The screen provided relates to property attributes - Please see the below:
https://foundations-documentation.reapit.cloud/whats-new#properties-api-2
 
If you are looking to use metadata to store additional details/information, an app will need to be create that launches from the relevant screen in the core software - see Desktop integration types; https://foundations-documentation.reapit.cloud/whats-new#desktop-integration-types
