### ISSUE TITLE
Several information on Applicant that need Configuration API values couldn't got stored properly

### ISSUE THREAD

**Issue by ss-dimasm** [reapit/foundations#8529]
**Summary**
Hi, recently we're faced this issue when we trying to create new applicant or patching some applicants with some information that relates to "positionId" and "reasonId" on Sales mode and "positionId" on Renting mode.
On the example payload below the missing information that couldn't got stored are `buying.positionId` and `buying.reasonId`, and about the "BA" and "AR" values, they're come from the configuration endpoint with type 'buyingPositions' and 'buyingReasons'. How can we make sure that the given payload is stored properly? Thanks

The given payload for creating new applicant
```json
{
    "departmentId": "G",
    "negotiatorIds": [
        "ADV"
    ],
    "officeIds": [
        "MKT"
    ],
    "marketingMode": "buying",
    "buying": {
        "priceFrom": 123,
        "priceTo": 333,
        "positionId":"BA",
        "reasonId":"AR"
    },
    "related": [
        {
            "associatedId": "MKT22002301",
            "associatedType": "contact"
        }
    ],
}
```

**Detail and or supporting links and screenshots**
- Using Sandbox data

**Specification**
- Project: Reapit.Services.Applicants
- Reproduce bug to understand the incorrect behaviour. This could be related to a recent bug that was identified with configuration cache data not being presented properly in the properties API which will need rolling out to this service also.

**Comment by ss-dimasm** [comment]
Hi @AshDeeming , no there aren't
After sending that payload its return 201 staus and I could see the created applicant record but without any information of buying position and/or buying reason, they have `null` values

**Comment by ss-dimasm** [comment]
I attach the created applicant record here
![image](https://user-images.githubusercontent.com/96416644/219355266-81129f95-c6cf-4eaf-baab-073a649c7df6.png)

**Comment by AshDeeming** [comment]
Thanks @ss-dimasm

**Comment by plittlewood-rpt** [comment]
Hi @ss-dimasm has this issue only just started happening recently, and if so, did it work before? Thanks

**Comment by ss-dimasm** [comment]
Hi @plittlewood-rpt!
I am not sure enough but on 10 Feb 2023 the payload of 'buying.positionId' and 'buying.reasonId' are not gets saved also, so I guess its not work properly on last 2 weeks. Thanks
