### ISSUE TITLE
Extras Field access request

### ISSUE THREAD

**Issue by MarcinuB** [reapit/foundations#8532]
Describe the solution you'd like
Can I ask for a write permission to the “Directions” field in the AC Extra Descriptions screen for a customer Rettie.

Additional context
We're working with Rettie on integration and we need access to this field to be able to update some data for them.

**Comment by plittlewood-rpt** [comment]
Hi @MarcinuB this has now been enabled and can be access using the extrasField query string parameter with value `pDirections`

eg

`GET /properties?extrasField=pDirections` or `GET /properties/{id}?extrasField=pDirections`

Many thanks
Pete
