### ISSUE TITLE
Directions, Mileage, Location and Situation

### ISSUE THREAD

**Issue by quigger** [reapit/foundations#8542]
Client: PRH but relevant to any mutual clients.

Do these fields still exist in Foundations like WebServices?
"Directions, Mileage, Location and Situation"

See request for Location here:
https://github.com/reapit/foundations/issues/8520

See query from by: https://github.com/RWilcox-Reapit here:
https://github.com/reapit/foundations/issues/8520#issuecomment-1434739969

See my previous request here:
https://github.com/reapit/foundations/issues/8515

See some screens from the WebServices tool:
![image](https://user-images.githubusercontent.com/644502/219686097-c6bc06bc-fa55-4d39-870a-9197a8a4da30.png)

and some clients (GAC) have various other fields:
![image](https://user-images.githubusercontent.com/644502/219686455-5f1a39b2-4a5e-465a-899d-15f218226231.png)

**Specification**
- Get SOAP configurations from SI (or someone with access to web service configuration)
- Analyse which customers have the four fields mentioned above
- Ensure these fields are all accounted for in the respective platform configurations

**Comment by plittlewood-rpt** [comment]
Hi @quigger these can be surfaced to you using the [extrasField mechanism](https://foundations-documentation.reapit.cloud/api/api-documentation#retrieving-data). They are not displayed by default (and would not have been in the SOAP API either) as they as customer specific fields that don't form part of the core JSON contracts.

**Comment by quigger** [comment]
Thanks @plittlewood-rpt 

> They are not displayed by default (and would not have been in the SOAP API either)

Doesn't my screenshot show them in the SOAP API?

**Comment by plittlewood-rpt** [comment]
It does... but you can only see them because they've been configured in the SOAP API (in a similar way to what we need to do for the Foundations APIs due to them being custom fields for the customer). Thanks

**Comment by quigger** [comment]
Thanks @plittlewood-rpt 

Why was these request made then?

https://github.com/reapit/foundations/issues/8520#issuecomment-1434739969

**Comment by plittlewood-rpt** [comment]
The previous ticket was just for the Location field. To prevent scope creep on tickets, we prefer new items to be opened. Hope this clarifies the situation. Thank you

**Comment by ashindey12** [comment]
@quigger  - The fields Directions, mileage and Situations are not configured for client PRH, in order to give permission for accessing these extra fields they need to be configured first. If this is not the case can you please confirm what exactly is needed here. Thanks

**Comment by quigger** [comment]
@ashindey12 

I was initially asking about the availability of these fields in Reapit Foundations cf. Web Services.
It seems from this ticket that some internal work was needed on the Reapit Foundations side for that access.
If you are saying we now need to request access for any client when required - we can do this as needed.

**Comment by plittlewood-rpt** [comment]
Hi @quigger I've asked the team who look after the old web service to look at which customers already have these fields exposed so we can marry that up on the Foundations side. We'll wait for their feedback and do any necessary updates before we close this as it should just make it slightly easier for you going forwards.

**Comment by quigger** [comment]
Thanks @plittlewood-rpt

**Comment by plittlewood-rpt** [comment]
Hi @quigger looking at the additional description settings across our client base there's a huge variance. It's probably easier for now if you can just request them as you need them and we will set them up. In the meantime I'm going to log a separate ticket about looking at the feasibility of exposing all additional descriptions in a consistent way. I'll link it to this one

**Comment by plittlewood-rpt** [comment]
#8708 logged to see if there's something better we can do with regard to extra description content
