### ISSUE TITLE
Document modified event not firing when SignatureSense document is signed

### ISSUE THREAD

**Issue by garrym** [reapit/foundations#8543]
**Describe the bug**
We are using the SignatureSense plugin for Reapit and have noticed some webhooks not arriving for certain events.

When a document is uploaded to Reapit we use the plugin to send details to the users to sign. When the document is signed by the end user through SignatureSense, a new document is created in Reapit with the `-signed` suffix on the name. The original document is removed.

The new `-signed` document has a new ID, so presumably it is a completely new document and the old document is deleted.

Presumably the SignatureSense plugin is using the Reapit API to both create the new signed document and delete the original unsigned document.

We receive both `document.created` webhook events for the original and signed documents, but the issue we are facing is that we do not receive a `document.modified` event for the deletion of the original document.

We would expect a webhook similar to the following below, (please note the `new` value of `null` to show that it has been deleted) but we do not receive a webhook when this is done through SignatureSense.

```
{
    "eventId": "xxx",
    "entityId": "ENT123",
    "customerId": "CUST123",
    "eventTime": "2023-01-25T15:12:04.6348498Z",
    "topicId": "documents.modified",
    "new": null,
    "old": {
        "associatedId": "ASSOC123",
        "typeId": "LET",
        "isPrivate": false,
        "associatedType": "property",
        "created": "2023-01-25T15:02:27Z",
        "id": "DOC123",
        "name": "original-file-name.pdf",
        "_eTag": "\"C865697173D6DC8D2BE22E94170F7977\"",
        "modified": "2023-01-25T15:03:12Z"
    },
    "diff": {},
    "SendAttempts": 1
}
```

We have checked that `document.modified` events are fired when a document is deleted through the Reapit API and this does happen.

**To Reproduce**

1. Upload a document to Reapit
3. Check webhook transactions to see a corresponding `document.created` event
4. Change the document status to public
5. Check webhook transactions to see a corresponding `document.modified` event
6. Go through the Signature Sense signing flow
7. Sign the document
8. Check webhook transactions to see a new `document.created` event with a new document ID and new file name with `-signed` suffix.
9. Notice in Reapit that the new document is present, original document no longer present.
10. Notice that no `document.modified` webhook event has been raised for the original document

**Expected behaviour**
Once the document is signed using Signature Sense, new signed document is created and original is removed, a `document.modified` webhook should be fired for the original document ID so that we know it has been removed from Reapit.

**Screenshots**
None

**Device (please complete the following information for web issues):**
 - Device: PC
 - OS: Windows 11
 - Browser: N/A
 - Version: N/A

**Additional context**
None

**Comment by AshDeeming** [comment]
Hi @garrym 
Has this been flagged to the 3rd party, Signature Sense?

**Comment by rochellelevy** [comment]
@AshDeeming are you pointing out that this is not a Reapit issue?

**Comment by garrym** [comment]
Hey @AshDeeming , no I haven't as I was under the assumption that Signature Sense don't have direct control of Reapit's webhooks. I can raise it with them if it is possible for them to modify or delete documents without a Reapit webhook being fired. Please let me know, thanks.

**Comment by plittlewood-rpt** [comment]
Hi @garrym. Just to confirm my understanding of what are reporting 

- You are subscribed to documents.created and documents.modified events
- When a document is signed using the SignatureSense app, the expected behaviour is that the original document is deleted and replaced with a new, signed document
- The `documents.modified` webhook signalling the deletion of the original document is not being sent to you

If this is correct, are you able to provide an example where this has happened so I can have a look at what calls the app itself is making (the reference of the associated property/applicant/contact should be fine, along with a rough time that the document would have been signed)? The webhook events are triggered by database change events so there's no reason that I can immediately think of as to why this wouldn't be being fired, so i'd like to try and understand the requests to help debug what's going on here.

Thanks

**Comment by garrym** [comment]
@plittlewood-rpt yes that's correct. An example was observed on 17/02/2023 between 16:14 and 16:19 roughly.

1) We uploaded a document and received a `document.created` event with Event ID: `701d2ce4-f63f-4a57-8e54-da42f8cb03b8`
2) Changed the document from private to public. Received a `document.modified` event with Event ID: `8ce70479-495d-4b8f-81ef-7c06b06b399e`
3) Completed the signing process with Signature Sense
4) Received a `document.modified` event, but doesn't show any diff apart from the eTag and modified date. Event ID: `c968577d-89d1-4530-bef6-79f6f5886b87`
5) Received a `document.created` event for new Signature Sense signed copy of original with Event ID: `03dcea35-e216-4471-90d7-904c5f663730`
6) No `document.modified` event was received for the document specified in events `701d2ce4-f63f-4a57-8e54-da42f8cb03b8`, `8ce70479-495d-4b8f-81ef-7c06b06b399e` or `c968577d-89d1-4530-bef6-79f6f5886b87`

I hope this is enough information to go on, please let me know if you need any more.

Thanks

**Comment by garrym** [comment]
We've also seen another occurrence this evening, following the same pattern as above. First 3 events are for the original document, 4th event is for the new signed document.

Event IDs:

`document.created` : `65cad2da-e52e-4f0d-80e0-2298d0ee1d37`
`document.modified`: `7d1eed4c-b264-4560-a1f5-bd71c08db15a`
`document.modified`: `d33a03d4-216e-4441-ba08-0cd8757fe15f`
`document.created`: `742e7640-c915-44d5-b991-15b59ef2d123`

**Comment by plittlewood-rpt** [comment]
Hi @garrym thanks for the information. I _think_ I might know what's going on here and will look at it with a fresh pair of eyes in tomorrow. It looks it might be a timing issue where the PATCH and DELETE in very quick succession is resulting in the events being processed in the wrong order. I can see the missing event being omitted in the logs for your first example so want to try and recreate the behaviour myself then I've got something that I can debug! Thanks

**Comment by rochellelevy** [comment]
@plittlewood-rpt do you think there is a chance this will be completed this week?

**Comment by plittlewood-rpt** [comment]
Hi @rochellelevy possibly. I've been able to reproduce thing and think the best solution is to hold back deletion events for a (very) short period to give the modified events chance to fire first. That way even if they enter to processing queue out of order, they'll still get processed in the right order as the deletion should always be the last thing. I'm just doing some analysis to see if there's any reason I shouldn't implement that

**Comment by plittlewood-rpt** [comment]
Hi @garrym I've turned on some more verbose logging in the webhooks pipeline just so I can absolutely confirm what's actually going on here. When you become aware of this happening again would you mind just letting me know please so I can grab the logs?

**Comment by rochellelevy** [comment]
@plittlewood-rpt we have asked one of QA's to test this when he gets the chance

**Comment by plittlewood-rpt** [comment]
Hi @garrym - appreciate things got held up a bit here with the issue on Friday which should now be resolved. I think Ash has responded with the mitigating actions that have taken place but let me know if you need any more detail. Could you run the signature sense test again please so I can capture the behaviour in the logs?

**Comment by garrym** [comment]
Morning @plittlewood-rpt  - the QAs have replicated again with the following events that triggered between 2023-03-07 14:59:30 and 2023-03-07 15:04 yesterday.

Event IDs:

`document.created` : `3a38cb5e-a401-4b9d-9913-3e8d0ec3e2a5`
`document.modified`: `d1a467fc-90b6-4c6d-92c4-55927131bdec`
`document.modified`: `ab02c83d-4900-45a4-ab73-9491e47f3bf1`
`document.created`: `b7412790-5498-4fb4-bf4a-4afe2064cd43`

Thanks for looking into this, if you need any more information please let me know.

**Comment by plittlewood-rpt** [comment]
Thanks very much. I'm hopeful I'll have all the info I need now so will come back to you as soon as I can

**Comment by plittlewood-rpt** [comment]
@garrym  one more thing actually. Is this an intermittent problem or does it happen every time (from your testing?)

**Comment by yeliz-tacel** [comment]
@plittlewood-rpt I have tested and can confirm it is not a intermittent issue. It can be replicated consistently.

**Comment by garrym** [comment]
It's also worth noting that we believe the behaviour of the webhook was working correctly in the past when we've QA'd it. We have historical documents that have gone through the SignatureSense process and I can only assume that our application received an event that let it know it had to delete the original file. Unfortunately our logs don't go back that fire so I can't verify it.

However, I do have an event ID for a successful `document.created` event we received after the document signed is here: `b8a7ddd7-0842-4dc3-930e-b8b4f2d91166`

Unfortunately I can't find the original pre-signed document ID to go with this though. Hope this helps.

**Comment by plittlewood-rpt** [comment]
@garrym  I've just QA'd this and it looks OK. I'm out of the office tomorrow so will release this on Friday morning and get back to you to run your own tests if that's OK. Thanks

**Comment by garrym** [comment]
Great, thanks @plittlewood-rpt . We'll test it when you give us the go-ahead.

**Comment by plittlewood-rpt** [comment]
Hi @garrym I've pushed this out now. Please can you test when it's convenient and let me know if it's resolved the issue when you're using the app itself? Thanks

**Comment by ytacel** [comment]
@plittlewood-rpt @garrym I have retested and can confirm the signed document replaces the unsigned document as expected.

**Comment by garrym** [comment]
@plittlewood-rpt yes we can confirm it is now working as expected and we are receiving a deletion event for the old document. Thanks for fixing this and happy to close this issue as fixed now.

**Comment by plittlewood-rpt** [comment]
Excellent news. Thanks for confirming
________________________________
From: Garry Marsland ***@***.***>
Sent: Friday, March 10, 2023 12:42:17 PM
To: reapit/foundations ***@***.***>
Cc: Pete Littlewood ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [reapit/foundations] Document modified event not firing when SignatureSense document is signed (Issue #8543)


<https://github.com/plittlewood-rpt>

External Message - Please be cautious when opening links or attachments in email
________________________________
@plittlewood-rpt yes we can confirm it is now working as expected and we are receiving a deletion event for the old document. Thanks for fixing this and happy to close this issue as fixed now.
