### ISSUE TITLE
Error when trying to pull data for Customers that have installed our NicheCom Print Property Feed application

### ISSUE THREAD

**Issue by mark-orme** [reapit/foundations#8545]
We have 2 new customers install our application the same as any other a couple of weeks ago.

When we try and pull the data for the 2 below companies that have installed the app:

Jackson Stops Country
JCK-GBUM

Jackson Stops Country
JCK-GAAH

We get the following error:

"The request could not be fulfilled as the Reapit customer specified by the provided credentials does not have the application installed."

We have other customers that we are pulling their data in the same way without problem and the customer is showing to have installed our app on REAPIT marketplace.

Thanks.

**Comment by plittlewood-rpt** [comment]
HI @mark-orme please can you send me an example request you are making? As the Nichecom Property Feed app is a client_credentials application, it's likely something to do with the reapit-customer header you are passing with the request.

**Comment by mark-orme** [comment]
hi @plittlewood-rpt  all our other customers are working fine though which is odd that these 2 specific customers with the same request say the customers dont have the app installed.

**Comment by mark-orme** [comment]
hi @plittlewood-rpt 

Here are the cURL versions of the requests we're making...

curl --location 'https://platform.reapit.cloud/properties?PageSize=100' \
--header 'Accept: application/json' \
--header 'api-version: 2020-01-31' \
--header 'reapit-customer: BRP' \
--header 'Authorization: Bearer eyJraWQiOiJFXC9TcnVuTzVCR0xBMk1yT3phY2RjWFkwVVdqRVB1cVB5N3hIb1FWbnJGdz0iLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiI3NmhqZHRydTlobjY2NDRkdm43am5tMmltYyIsInRva2VuX3VzZSI6ImFjY2VzcyIsInNjb3BlIjoiYWdlbmN5Q2xvdWRcL2RvY3VtZW50cy5yZWFkIGFnZW5jeUNsb3VkXC9pbWFnZXMucmVhZCBhZ2VuY3lDbG91ZFwvcHJvcGVydGllcy5yZWFkIGFnZW5jeUNsb3VkXC90cmFuc2FjdGlvbnMucmVhZCIsImF1dGhfdGltZSI6MTY3NjkxMDM4MiwiaXNzIjoiaHR0cHM6XC9cL2NvZ25pdG8taWRwLmV1LXdlc3QtMi5hbWF6b25hd3MuY29tXC9ldS13ZXN0LTJfZVE3ZHJlTnpKIiwiZXhwIjoxNjc2OTEzOTgyLCJpYXQiOjE2NzY5MTAzODIsInZlcnNpb24iOjIsImp0aSI6ImU0Y2I4M2RjLTRmODktNDczNS04ZWU1LTgwYTU4ZTM5NzdkYSIsImNsaWVudF9pZCI6Ijc2aGpkdHJ1OWhuNjY0NGR2bjdqbm0yaW1jIn0.OxoCms6c1pslsci02QEBiK5JlKThuhpBvZscDBm5qeTvthOIzS3eFakR_yUxEJUSU7XkbImqNGgyMW8AFmc4bgvlDmCF-9Lj9j8hUI3Tn3x7qWrkrHM98h2QZ0yHV_0ttN13rx5Rd-nubz3dYNGaT1Ocj7bTJsNoz6RVOkybUwsfEVKNTatsLj-BdST4ajWuPrwRzF7ROklXwx0VsVgNGfcvixmJBcnVaqMx6jX9V_rBk8rGCFW-hQIHINYVq2XYolsMZUJgY_WLafGs_UTp2W5lnGT51CHiAIVByFJ7TMEcxa0JKk-bCmXML1_AxirLsnkr2JnY5rKbYsxYQBnfTA'

*WORKS*


curl --location 'https://platform.reapit.cloud/properties?PageSize=100' \
--header 'Accept: application/json' \
--header 'api-version: 2020-01-31' \
--header 'reapit-customer: JCK' \
--header 'Authorization: Bearer eyJraWQiOiJFXC9TcnVuTzVCR0xBMk1yT3phY2RjWFkwVVdqRVB1cVB5N3hIb1FWbnJGdz0iLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiI3NmhqZHRydTlobjY2NDRkdm43am5tMmltYyIsInRva2VuX3VzZSI6ImFjY2VzcyIsInNjb3BlIjoiYWdlbmN5Q2xvdWRcL2RvY3VtZW50cy5yZWFkIGFnZW5jeUNsb3VkXC9pbWFnZXMucmVhZCBhZ2VuY3lDbG91ZFwvcHJvcGVydGllcy5yZWFkIGFnZW5jeUNsb3VkXC90cmFuc2FjdGlvbnMucmVhZCIsImF1dGhfdGltZSI6MTY3NjkxMDM4MiwiaXNzIjoiaHR0cHM6XC9cL2NvZ25pdG8taWRwLmV1LXdlc3QtMi5hbWF6b25hd3MuY29tXC9ldS13ZXN0LTJfZVE3ZHJlTnpKIiwiZXhwIjoxNjc2OTEzOTgyLCJpYXQiOjE2NzY5MTAzODIsInZlcnNpb24iOjIsImp0aSI6ImU0Y2I4M2RjLTRmODktNDczNS04ZWU1LTgwYTU4ZTM5NzdkYSIsImNsaWVudF9pZCI6Ijc2aGpkdHJ1OWhuNjY0NGR2bjdqbm0yaW1jIn0.OxoCms6c1pslsci02QEBiK5JlKThuhpBvZscDBm5qeTvthOIzS3eFakR_yUxEJUSU7XkbImqNGgyMW8AFmc4bgvlDmCF-9Lj9j8hUI3Tn3x7qWrkrHM98h2QZ0yHV_0ttN13rx5Rd-nubz3dYNGaT1Ocj7bTJsNoz6RVOkybUwsfEVKNTatsLj-BdST4ajWuPrwRzF7ROklXwx0VsVgNGfcvixmJBcnVaqMx6jX9V_rBk8rGCFW-hQIHINYVq2XYolsMZUJgY_WLafGs_UTp2W5lnGT51CHiAIVByFJ7TMEcxa0JKk-bCmXML1_AxirLsnkr2JnY5rKbYsxYQBnfTA'

*DOESN'T WORK*

The only different is the reapit-customer value.

Regards,

**Comment by mark-orme** [comment]
thanks it seems we already have this customer more than once so they seem to have branch level clients on your end
