### ISSUE TITLE
'MarketingMode' in UI vs API

### ISSUE THREAD

**Issue by Filip5991** [reapit/foundations#8549]
We've been using the 'MarketingMode' setting that's part of the property object in the API for quite some time now to determine the type of a property (sales/lettings). I know that the possible values for this field are sales/lettings/salesAndLettings.

What I was wondering is what's the UI equivalent of this field? Is it the field labeled 'Active' inside the property page?
![image](https://user-images.githubusercontent.com/23519137/220418003-bec0c2bd-d7a4-492f-b7d8-474f37bfa5a3.png)

If so, in what scenario would a user set this to 'salesAndLettings'? 
If possibly 'MarketingMode' is not the right setting to use to determine the property's type, is there another one that can be used instead?

**Comment by AshDeeming** [comment]
Hi @Filip5991 
The 'Active' area is the correct association to a property record to differentiate between Sales & Lettings. 
The ability to market as property as Sales & Lettings is a feature of the software

**Comment by Filip5991** [comment]
Hi @AshDeeming, thanks for the initial answer.

We had an internal discussion on this - our understanding is that at the point of booking the MA there is only the option to select Sales or Lettings and that after the appointment it can then be set to be marketed for both - is that correct? 

The reason I ask is - we are seeing a high number of properties/MA bookings coming through as both Sales and Lettings which just seems a tad odd?

**Comment by AshDeeming** [comment]
Hi @Filip5991 
In AgencyCloud, when the appointment is created, it can have a property associated to it - It is the property record that holds the MarketingMode detail.
![image](https://user-images.githubusercontent.com/61687775/221839340-b037d276-a8a8-4e30-92de-aa3f9b3b6950.png)

It's generally client specific if they use sales and/or lettings, each client may use or setup properties slightly differently in the CRM. If you can provide some example references re salesAndLettings i can review in more detail?

**Comment by Filip5991** [comment]
Thank you for the answers @AshDeeming , I think this can be closed now :-)
