### ISSUE TITLE
Works Order type locked - Fixflo Integration

### ISSUE THREAD

**Issue by TMoffat** [reapit/foundations#8555]
**Summary**

Hi team,

Our shared client Life Residential [LIR] came to us with a question today that I need your input on.

When a Works Order is created on RPS from a Fixflo issue the Works Order type field is blank and they are unable to manually change it. They use this field to pull a number of internal reports. Is this something which can be changed or shall I send them to you to discuss other ways that they can potentially relook at their reporting?

Many thanks in advance!

**Comment by AshDeeming** [comment]
Hi @TMoffat 
The work order types are configurable please client, please see the swagger docs highlighted below(https://developers.reapit.cloud/swagger):

![image](https://user-images.githubusercontent.com/61687775/220638506-dc4bd725-96ba-4d01-ae6f-28c8d314c69b.png)

**Comment by TMoffat** [comment]
Hi @AshDeeming, thanks for the speedy response. Is it possible for us/you to amend the configuration so the customer can apply the work type once Fixflo created the issue through the integration as currently they are unable to.

**Comment by AshDeeming** [comment]
Hi @TMoffat 
Currently any changes to config will need to be requested by the customer via Reapit Service Desk
