### ISSUE TITLE
Meaning of document typeIds and intended usage

### ISSUE THREAD

**Issue by joe-at-github** [reapit/foundations#8560]
**Summary**
Would it possible to get a mapping of all documents types, e.g LET, DET. that would include the typeId and a description / semantics / intended use.

**Detail and or supporting links and screenshots**
I haven't found on the documentation a section explaining what kind of document each type might include.
I would like to make sure sensitive documents like tenancy agreements are not pulled.

Thank you.

**Comment by AshDeeming** [comment]
Hi @joe-at-github 
Please review the Configuration endpoint detailed below (https://developers.reapit.cloud/swagger) - These types can be custom per client;
![image](https://user-images.githubusercontent.com/61687775/220856840-5015923a-180d-4e6a-a711-76507bf5cd83.png)

**Comment by joe-at-github** [comment]
thank you @AshDeeming 
I did check the configuration endpoint however, taking as an example, see below, "property particulars" is vague.
From this, it is not clear wether the documents using that category could be sensitive or not.
Do you have any recommendation to make sure sensitive documents are filtered out?

`  {
    "id": "DET",
    "value": "Property Particulars"
  },`

**Comment by bobf** [comment]
Hi, @AshDeeming I am a colleague of @joe-at-github 's

I mentioned in an internal Reapit ticket a while ago that we are not very comfortable with requiring that customers give us access to (e.g.) tenancy agreements in order for us to have access to things like Floor plans and EPC documents.

From our side, we feel that the `Documents` endpoint could be split into two endpoints (secure/non-secure) where permissions from the customer could be granted to the Foundations app. This would provide a safer development process for us and your customers would have more control of their sensitive data.

Do you think it is worth raising a separate ticket for this ?

**Comment by AshDeeming** [comment]
Thanks for the additional details @bobf & @joe-at-github 
I'll convert this ticket to a feature request for review by the relevant team

**Comment by plittlewood-rpt** [comment]
Please track #7929 which has now been scoped and will be picked up soon.
