### ISSUE TITLE
Sales price change incorrect

### ISSUE THREAD

**Issue by elizabethhamlin** [reapit/foundations#8564]
Hi

The data from Michael Jones is not correct. The new price column and the old price column are the wrong way around. They need to be the same as the Lomond layout so that when I append the tables from the different databases, they match.

Thanks 

Lill

**Comment by plittlewood-rpt** [comment]
Hi @elizabethhamlin please can you give some more detail here (table name, entity ids should suffice). There is no different to how they are generated so it's odd that they are correct in one database but not the other.

**Comment by plittlewood-rpt** [comment]
Hi @elizabethhamlin - have you been able to resolve this based on the above? Thanks

**Comment by plittlewood-rpt** [comment]
HI @elizabethhamlin  - I'll close this item as the sprint has now finished. Just reach out if you need any further assistance. Thanks :)
