### ISSUE TITLE
User was set up incorrectly on foundations

### ISSUE THREAD

**Issue by rochellelevy** [reapit/foundations#8570]
Please take a look at our FAQ's before submitting an issue, as your question may already be covered in the documentation https://foundations-documentation.reapit.cloud/faqs

**Summary**
SAU: User = yeliz.tacel@savills.co.uk
SAV: User = yeliz.tacel@savills.com

settings incorrect = should be SAV-GMYS and SAU-GMYS

Has no toggle to toggle between DBs

Dev access was set up before agency cloud access erroneously. Apologies for the hassle

**Detail and or supporting links and screenshots**

**Comment by plittlewood-rpt** [comment]
Hi @rochellelevy it might be easier if we can just delete these two accounts and start over. Is that feasible?

**Comment by rochellelevy** [comment]
Whatever is easier for you. But if you do and you need to resend the invite, its best to do it on Monday as I know the emails are only valid for 24 hours

**Comment by plittlewood-rpt** [comment]
Thanks Rochelle - I'll get this done shortly. I'll just delete the users and let you re-add at your leisure if that's easier?

**Comment by plittlewood-rpt** [comment]
The users have now been deleted so feel free to go through the setup process again. I'll leave this open until I've heard back that everything's ok. Cheers

**Comment by rochellelevy** [comment]
Thanks @plittlewood-rpt I'm just getting round to doing the setup now. I'll let you know if we have any issues. Thank you again!

**Comment by plittlewood-rpt** [comment]
Hi @rochellelevy am I OK to close this?

**Comment by rochellelevy** [comment]
almost! I'm confirm. we were having trouble setting her up on agency cloud
yesterday so havent gotten to setting up foundations yet!

**Comment by plittlewood-rpt** [comment]
HI @rochellelevy - I'll close this item as the sprint has now finished. Just reach out if you need any further assistance. Thanks :)
