### ISSUE TITLE
Sales Status

### ISSUE THREAD

**Issue by elizabethhamlin** [reapit/foundations#8574]
There are two sales status that I need to be able to differential between, Currently I only have For Sale - Available and this brings through For Sale -available and For Sale - Available (lost MA).

I need these separated asap please as they are causing all my advertised stock figures to be incorrect.

This is what I currently have -

![image](https://user-images.githubusercontent.com/104636752/221526333-015f8888-2cbd-4bfb-9022-36af7fcfda51.png)

Thanks 

Lill

**Specification**
- Projects: Analytics Schema
- Add IS_EXTERNAL bool property to PROPERTIES model that is set based on PRP.EXTERNAL
- Ensure documentation updated

**Comment by plittlewood-rpt** [comment]
Hi @elizabethhamlin  with the current schema, you can use the PROPERTY_SALES_LOST_INSTRUCTIONS table to understand which properties are lost MA. We can look at adding a new fields to the base PROPERTIES table to denote the current Lost MA state of a property though to make this easier.

**Comment by elizabethhamlin** [comment]
This will not work as the for sale - available includes For Sale - Available (Lost MA) and there looks like there is more available than there is

**Comment by plittlewood-rpt** [comment]
I'm not sure I follow. If you join to PROPERTY_SALES_LOST_INSTRUCTIONS you can omit the entry if there's a match as part of your filters. What BI tooling are you using?

**Comment by plittlewood-rpt** [comment]
Hi @elizabethhamlin, if you include the PROPERTY_SALES_LOST_INSTRUCTIONS table and set up your relationship, you can just omit rows where there is a record for the property in PROPERTY_SALES_LOST_INSTRUCTIONS (which will be the Lost MA properties)

**Comment by elizabethhamlin** [comment]
Hi @plittlewood-rpt this seems like a very long winded way of doing something when purely a straight forward status option would be much more convenient and be more user friendly for those looking at the data

**Comment by plittlewood-rpt** [comment]
I appreciate what you are saying. For Sale - Available (Lost MA) isn't actually a 'status' as such in AgencyCloud. The Lost MA indicator is added if a lost MA date is stored against the property. You'll note that in AgencyCloud General/Power Reports you don't get "For Sale - Available (Lost MA)" as a status option either, for the same reason. THis is why the data is separate in this manner in the Analytics Schema. What you are wanting to achieve can be done with a join and I would recommend exploring this avenue. We will look at adding an indicator to the PROPERTIES view though as mentioned above, which will make this easier going forwards. I'm unable to give a timescale on this until we review the item in our next refinement session.

**Comment by elizabethhamlin** [comment]
Hi @plittlewood-rpt 
In Reapit you have this -

![image](https://user-images.githubusercontent.com/104636752/221874294-8cad8bbf-9b8b-466a-8a3d-a838283fd789.png)

If you select External as false it will then remove the lost MA ones. This would be a far quicker and easier option then merging two tables. The property table is already huge, doing this will cause it to slow up

**Comment by plittlewood-rpt** [comment]
We will review this in our next refinement session on Thursday and come back to you. I'm not against putting something in to make this easier, however we need to follow our development processes so the solution I have provided above can be used in the meantime if you need to do this urgently. We'll be in touch towards the back end of the week to give you an idea of when we can fit this work in.

**Comment by elizabethhamlin** [comment]
Thanks @plittlewood-rpt

**Comment by plittlewood-rpt** [comment]
Hi @elizabethhamlin - I've just come to do this and spotted that we already expose the external flag in the PROPERTIES model. The field is called ON_MARKET_WITH_OTHER_AGENT.

Can you review and let me know if this is what you need. You should be able to just filter out any properties where ON_MARKET_WITH_OTHER_AGENT = 'Yes'

**Comment by plittlewood-rpt** [comment]
Hi @elizabethhamlin have you had chance to review the above? Thanks

**Comment by elizabethhamlin** [comment]
Hi Pete

Sorry I didn't see your message. I have merge the sheets now and it has worked as you suggested before so I will give this a go when I get a moment. Thanks for showing this though.

**Comment by plittlewood-rpt** [comment]
Great! Thanks for coming back to me. Have a good weekend
