### ISSUE TITLE
500 error when getting property from API

### ISSUE THREAD

**Issue by MarcinuB** [reapit/foundations#8581]
Hi Team.

I've observed another 500 errors when getting property info from API. See the screenshot for the details.

![image](https://user-images.githubusercontent.com/8589350/221847852-c3522787-af69-4621-8066-507c6e8b0e9b.png)

**Comment by plittlewood-rpt** [comment]
Hi @MarcinuB thanks for reporting this. I can see a couple of timeouts from this time which we'll look into. Have you since been able to retrieve this property?

**Comment by MarcinuB** [comment]
Hi @plittlewood-rpt - It looks to be ok after that.

**Comment by plittlewood-rpt** [comment]
Thanks - I've just checked with our database team and they've said there's a notable spike in CPU usage on the database cluster at that time which would explain why it might time out. I've asked them to see if we can pinpoint what caused it so we can take steps to mitigate.

**Comment by plittlewood-rpt** [comment]
Hi @MarcinuB we've tracked down what is causing the spikes in CPU on the database server. The way our database clusters scale means there's definitely a chance of this happening again as it stands at the moment, however I've opened up a conversation with them to see if some of the resource can be reserved for API consumption to mitigate the immediate issue. It won't be an overnight solution unfortunately but I'll keep you posted with how that progresses.

**Comment by MarcinuB** [comment]
Hi @plittlewood-rpt - thanks for let me know. I'm thinking about adding some kind of a retry mechanism to my calls. Can you advise if that is something that could potentialy make things worse on your side if I would retry 2-3 times in case of a 500 error?

**Comment by plittlewood-rpt** [comment]
Thanks for checking. You should be fine to implement a retry mechanism, and this is good practice. I'd recommend using some sort of exponential backoff so you leave a bit of breathing space between calls. The load is coming from our CRM rather than anything the APIs themselves are generating.

**Comment by MarcinuB** [comment]
@plittlewood-rpt -  yup absolutely. [Poly](https://github.com/App-vNext/Polly#retry) to the rescue!
Thanks again.

**Comment by plittlewood-rpt** [comment]
Hi @MarcinuB are you happy for me to close this based on the fact we're having a number of internal discussions to try and improve things? Coding for failure with Poly is definitely recommended as we'll never be able to guarantee that this will never happen
