### ISSUE TITLE
Problem submitting integration for review

### ISSUE THREAD

**Issue by MattRey** [reapit/foundations#8589]
Please take a look at our FAQ's before submitting an issue, as your question may already be covered in the documentation https://foundations-documentation.reapit.cloud/faqs

**Summary**
I cannot submit my app for review as the system tells me I haven’t filled in my details properly. I have filled in all the details that there are to be filled in as far as I can see. 
Ink to app here - https://marketplace.reapit.cloud/apps/279b8d76-2b49-402e-898c-16de80421c65

**Detail and or supporting links and screenshots**

**Comment by AshDeeming** [comment]
Hi @MattRey 
Please could you advise what error is being shown, if any, once 'submit review' is clicked?

![image](https://user-images.githubusercontent.com/61687775/221862315-63d69f2a-9b6d-4c6b-8b69-f1fc5fff6f41.png)

**Comment by AshDeeming** [comment]
Please also note that the 'private app' section will need to be populated with the Clients 3 digit ID before submitting.
