### ISSUE TITLE
Having issue accessing customer data using the API.

### ISSUE THREAD

**Issue by ServonSupport** [reapit/foundations#8623]
Hello

We are facing an issue, when we are getting enquiries from **Reapit live account** using Reapit API we get this error: "The request could not be completed because the Reapit customer specified by the provided credentials does not have the application installed".
See - https://share.getcloudapp.com/z8uGvv8g

Please check the below screenshot to know about the app - "**Bourne Estate Agents - Valuation Form Data**"
See - https://share.getcloudapp.com/Apuv111y
App Listing Status - https://share.getcloudapp.com/2NubKKKz

We have set the App as **Private**. Private App Client Ids - BOU

We followed the below documentation to fix this error but the issue is not fixed. https://foundations-documentation.reapit.cloud/troubleshooting/accessing-customer-data

Can you help us how we can fix this issue?

Kind regards

**Comment by AshDeeming** [comment]
Hi @ServonSupport 
The app is listed privately to the client however it does not appear to have been installed/enabled by one of the admin AgencyCloud users. 
This can be done via the AppMarket in AgencyCloud by one of their Admin users or with a browser via the integrations AppMarket URL: https://marketplace.reapit.cloud/apps/d244001f-8dc1-4d6b-b3fd-548ecce82b34
