### ISSUE TITLE
Linley & Simpson's - Reapit Data Configuration

### ISSUE THREAD

**Issue by jwkelsall** [reapit/foundations#8638]
Hi Reapit, 

I've attached a document which explains the required configuration of Linley & Simpson's data so that the properties, occupiers, contractors and landlords that they manage repairs and maintenance for sync over to Fixflo when the integration is set up. If they don't match this criteria, they will not.  Please could you make sure that the required properties, occupiers, contractors and landlords that Linley & Simpson use for the repairs and maintenance process match this configuration?

One thing to note, and which has previously meant certain properties haven't synced over is the letting status. If any properties are configured with the following letting status, they will not sync over and therefore occupiers won't be able to raise repair issues against: 

- letbyotheragent
- letprivately
- withdrawn 
- valuation
- sold

Please could you also provide me the Linley & Simpson main Reapit Code? Please could you also provide the offices groups (+ any associated codes) that will sit under the Linley & Simpson Office?

Any questions or problems please let me know. 

James

[Reapit Advanced Integration Configuration.pdf](https://github.com/reapit/foundations/files/10863053/Reapit.Advanced.Integration.Configuration.pdf)

**Comment by AshDeeming** [comment]
Hi @jwkelsall 
Please could you clarify what you're question or request is relating to the Platform? 
The Reapit code/ClientID for the client can be obtained from them or their CSM

**Comment by jwkelsall** [comment]
Hey Reapit,

I'm not entirely sure what you mean by 'relating to the platform' means?
This is related to the configuration (document attached to ticket) of their
lettings properties that require repairs and maintenance so that they
transfer successfully over to Fixflo.

@Vikki Clayton ***@***.***> Would you be able to confirm
what the Reapit code/Client ID for Linley & Simpson is?

Thanks,

James

[image: Fixflo's Referral Scheme]
<https://www.fixflo.com/referral-signup?utm_campaign=referrals&utm_medium=email_only&utm_source=gmail&utm_content=referral_program_2022_email_signature>

[image: James Kelsall]                       James Kelsall

                         Senior Customer Success Manager
                            ***@***.***>
***@***.***

**Comment by jwkelsall** [comment]
Hi Reapit,

I've been informed that Linley's Reapit Code is GLAS. As well confirming
that the properties match the correct configuration to sync over to Fixflo,
could you confirm  Linley & Simpson Reapit Code and office code ID to be
used with the integration? Please could you also provide the offices groups
e.g. Linley & Simpson - Hessle (+ any associated codes) that will sit under
the Linley & Simpson Office.

Thanks,

James






[image: Fixflo's Referral Scheme]
<https://www.fixflo.com/referral-signup?utm_campaign=referrals&utm_medium=email_only&utm_source=gmail&utm_content=referral_program_2022_email_signature>

[image: James Kelsall]                       James Kelsall

                         Senior Customer Success Manager
                            ***@***.***>
***@***.***

**Comment by jwkelsall** [comment]
Hi Reapit,

Apologies to chase on this but this is quite time sensitive. Would you be
able to provide this information today?

Thanks,

James

[image: Fixflo's Referral Scheme]
<https://www.fixflo.com/referral-signup?utm_campaign=referrals&utm_medium=email_only&utm_source=gmail&utm_content=referral_program_2022_email_signature>

[image: James Kelsall]                       James Kelsall

                         Senior Customer Success Manager
                            ***@***.***>
***@***.***

**Comment by AshDeeming** [comment]
Hi @jwkelsall 
I'm still unsure on the original question & will discuss internally with the clients Project Manager.

Please note that the OfficeGroup would be LOC-GLAS which is showing as installing the Fixflo app on 06-10-2022

**Comment by jwkelsall** [comment]
Hi Ash,

Currently the Reapit integration doesn't pull through the branches that are
set up on the property profile. In order to set up issue
assignment by branch, we need to investigate whether it's possible to pull
these through. I was provided with the example branch/office from Larards
as to where this is stored currently on their Reapit. Larards is currently
live with Reapit, Fixflo PRO and the Reapit Advanced Integration e.g.
Linley & Simpson - Hessle from Larards (Image B). Nicola has also provided
me with a screenshot from their test environment (image A).

This seems to be an office included on each property profile under the
relationships tab. We're not currently sure what those offices are, I
imagine something along the lines of 'Linley & Simpson - York', 'Linley &
Simpson - Wetherby'. However without confirmation we're unable to
investigate automatically assigning issues by those branches. So basically
we need a list of what those branches (+any associated codes if any) will
be in Reapit when they're set up?

Thanks,

James

*Image A*

[image: image.png]
*Image B*
[image: image.png]



[image: Fixflo's Referral Scheme]
<https://www.fixflo.com/referral-signup?utm_campaign=referrals&utm_medium=email_only&utm_source=gmail&utm_content=referral_program_2022_email_signature>

[image: James Kelsall]                       James Kelsall

                         Senior Customer Success Manager
                            ***@***.***>
***@***.***

**Comment by AshDeeming** [comment]
Hi @jwkelsall 
I believe the office details have been provided by the Project Manager however please note that these details can be obtained by the GET Offices/ Endpoint as per the swagger docs below;

![image](https://user-images.githubusercontent.com/61687775/224086803-2f9656f9-a6a7-4b42-92ad-f9d3d61c47d9.png)
