### ISSUE TITLE
New option "Fortnightly" for rentFrequency field (Applicant)

### ISSUE THREAD

**Issue by ss-dimasm** [reapit/foundations#8640]
**Is your feature request related to a problem? Please describe.**
We have a new request to add the "Fortnightly" option when choosing the rentFrequency on Renting Applicant while creating and updating the record.

**Describe the solution you'd like**
Add the "Fortnightly" option to rentFrequency field options

**Comment by plittlewood-rpt** [comment]
Hi @ss-dimasm AgencyCloud does not currently support Fortnightly as an Applicant rent frequency (it is supported for tenancy rent collect but that's a different use case). As a result we can't add Fortnightly in the API at this time as it would need to be done in AgencyCloud first. Have I misunderstood the requirement? Thanks

**Comment by ss-dimasm** [comment]
Hi @plittlewood-rpt
No, you're right about the requirement and thanks about the explanation. Thank you

**Comment by ss-dimasm** [comment]
After reach out with the team, we agreed not to have this requirement. So would be better if I close this issue

Thanks
