### ISSUE TITLE
Syncing invoices to Supplier invoices section from Fixflo

### ISSUE THREAD

**Issue by katedeedman** [reapit/foundations#8643]
Please take a look at our FAQ's before submitting an issue, as your question may already be covered in the documentation https://foundations-documentation.reapit.cloud/faqs

**Summary**

Hey Reapit! 

Our ex-colleague, Norbi raised ticket (#7633 ) before he left in October to request that we can automate sending invoices into the Accounts department. I can see that since then, your team have replied a few times and linked it to #7764 . Would you mind letting me know what the status is for these tickets? Would it be possible to sync invoices into the accounts dept?

Thank you!

-Kate, PM, Fixflo

**Detail and or supporting links and screenshots**

**Comment by plittlewood-rpt** [comment]
HI @katedeedman - #7764 was completed and I think it fits what you are asking here. Please can you review and let us know?

**Comment by katedeedman** [comment]
Yes, I think it does! Thanks so much!

**Comment by plittlewood-rpt** [comment]
Great stuff thanks. I'll close this issue down in that case.
