### ISSUE TITLE
Property included in feed when it belongs to another agent. 

### ISSUE THREAD

**Issue by ynwaJon** [reapit/foundations#8644]
We have the foundations app running on the Mitchell Williams website.  https://www.mitchellwilliams.co.uk/ 

For some reason another agents properties are included in their feed and are showing on the website.   As expected they're not too happy about it. 

Here is a link to the property 

https://www.mitchellwilliams.co.uk/property-details/CHE210244/buckinghamshire/chesham/ley-hill

It actually belongs to The Frost Partnership and can be found here (Another of our websites but it's not running on Foundations yet)

https://www.frostweb.co.uk/property-details/rps_fro-CHE210244/buckinghamshire/chesham/ley-hill-3

I have spoken to our tech team and they have said 

"When hitting the api endpoint with their customer ID and this Specific Property they are indeed sending it to us, so they would need to remove it at their end."

Please can this be looked into?

**Comment by plittlewood-rpt** [comment]
Hi @ynwaJon 

I have hit the properties API for that property code in your issue summary for both customers and it returns the correct property in each case. Both customers do indeed have a property with that reference (as they are not globally unique across our customers as we run a single-tenant system) so you will get a property back using both customer IDs, it's just a different property in each system. 

The API is behaving as it should do which typically points to access tokens not being switched out, or the reapit-customer header not being updated correctly when switching datasets.

If you can provide some more information we'd be happy to help. Please ask your tech team to review how they are using the access tokens and calling the API. If they can provide some example requests they've made (specifically the time they made the request, I'll be able to see from our logs if there is an issue where the reapit-customer header is not being updated or similar.

Thanks
Pete

**Comment by ynwaJon** [comment]
We have another client with the same issue. 

https://www.stonesresidential.co.uk/property-details/BEP230004/-/-/london-49

Customer ID - STO
Branch ID - BEP. 

Could you check to see why this property is being pulled through when its another agents.

**Comment by plittlewood-rpt** [comment]
Hi @ynwaJon please refer to my post yesterday. The APIs are returning the correct information so there is something wrong with the way you are calling it. We need detailed information about the requests you are making so we can try and diagnose what the issue might be, if this can please be provided. Thanks

**Comment by ynwaJon** [comment]
Ok.  Thanks for confirming.  I shall look into this.

**Comment by ynwaJon** [comment]
Thanks for looking into that further.  That makes sense.  Who would be the best person at Reapit to speak to client about this?

**Comment by ynwaJon** [comment]
Will do.  Thanks :)

**Comment by ynwaJon** [comment]
Hi @plittlewood-rpt - All good thanks :)
