### ISSUE TITLE
isPrivate flag - can it be trusted?

### ISSUE THREAD

**Issue by quigger** [reapit/foundations#8650]
See related tickets:
https://github.com/reapit/foundations/issues/8560#issuecomment-1441394152
https://github.com/reapit/foundations/issues/7929

When checking GTH DET documents and the specs we see this flag:
"isPrivate"

e.g.
![image](https://user-images.githubusercontent.com/644502/222489802-c5f9b767-8a06-4bb0-bf3f-06469b8d97a6.png)

Should we trust that to signify if the DET document is safe to show on public domain?
Or do the clients not use it consistently?

**Comment by AshDeeming** [comment]
Hi @quigger 
The isPrivate flag can be marked as such automatically for clients via the system config - It can vary per client

**Comment by quigger** [comment]
Thanks @AshDeeming 

Should we trust that to signify if the DET document is safe to show on public domain?

**Comment by AshDeeming** [comment]
Hi @quigger 

If a document has been marked as isprivate it's been done to note it is not safe to share in a public domain. 

How customers use it, either automatically or manually setting it can vary however if it's private it's not something that should be shared

**Comment by quigger** [comment]
Thanks @AshDeeming 

> If a document has been marked as isprivate it's been done to note it is not safe to share in a public domain.

We understand this tells us that `isPrivate` is the flag that we are meant to use to distinguish between document we should pull and those we should not.
 

> How customers use it, either automatically or manually setting it can vary however if it's private it's not something that should be shared

However this also tells us that we have no guarantee the customers are setting them accordingly, thus making it  completely unreliable?

Additionally, while manually looking at the data across all live RFPF clients, no DET documents for any of them was using `isPrivate`. Some of those docs were definitely not safe for front end websites.

As it currently stands, we can’t download documents, as it doesn't feel safe to do so.

**Comment by AshDeeming** [comment]
Hi @quigger 
As you've mentioned, using the document TypeId 'DET' (from the configuration endpoint) will only pull the the document that  been uploaded to the property particulars section on the Property record

**Comment by quigger** [comment]
@AshDeeming 

OK, but as it currently stands, we can’t download documents, as it doesn't feel safe to do so.
We can't be sure if we will get private or non private documents.
So can't be sure if we can show these on front end websites.
The secure document data filtering is not present.
