### ISSUE TITLE
400 errors when using refresh tokens

### ISSUE THREAD

**Issue by SteveRad** [reapit/foundations#8655]
**Describe the bug**
Since yesterday multiple customers are reporting that property and appointment data is not syncing, our logs show 400 errors ongoing, and it seems to be returning an Invalid grant type error when using the ‘refresh_token’ type. 

Usually this would suggest we’re reusing a refresh token twice but we can’t find anywhere that could cause that

**Expected behaviour**
Valid grant type response when using the `refresh_token` type 

**Example errors**
`POST https://connect.reapit.cloud/documents/signedUrl` resulted in a `400 Bad Request`

`GET https://connect.reapit.cloud/appointments?pageSize=100&embed=property&embed=type&embed=negotiators&pageNumber=1&typeId=CO&typeId=PI&typeId=&typeId=IV&start=2023-03-03T00%3A00%3A00%2B00%3A00&includeCancelled=true&end=2024-03-03T23%3A59%3A59%2B00%3A00` resulted in a `400 Bad Request`

**Additional context**
Nothing has changed in the way data is fetched or posted since these errors started happening yesterday

**Comment by HollyJoyPhillips** [comment]
Hi @SteveRad, following on from our email, did you check the expiry on the token?

**Comment by SteveRad** [comment]
Thanks for the support Holly. We've worked it out
