### ISSUE TITLE
Differentiating between properties marked as Sold STC and Under Offer properties

### ISSUE THREAD

**Issue by ElliottRowland** [reapit/foundations#8665]
At Webdadi we have a question relating to our Property Uploader for Webdadi Website App using the endpoint is /property and /propertyimages

We've searched github and can see an issue was raised and closed last year https://github.com/reapit/foundations/issues/7475 

From your documentation https://developers.reapit.cloud/swagger there is no API status specifically for Sold STC. The statuses available are:
preAppraisal/valuation/paidValuation/forSale/forSaleUnavailable/underOffer/underOfferunavailable/reserved/exchanged/completed/soldExternally/withdrawn 

If a Reapit user is marking a property as Sold STC available in their software and the API is returning the property with the status as underOffer how do you differentiate between properties marked as Under Offer or Sold STC in Reapit's software if the API status itself doesn't differentiate between the two and gives the same label of underOffer?

As we are advertising the properties on the client's website, the website needs to mirror the portals as display properties with a label of under offer or Sold STC. How can we do this if your API isn't differentiating between the two and simply giving both those statuses the same API label?

We only want to display properties which are active and mirror those displayed on the portals on the website, so won't pull exchanged or completed properties. From your options, we only pull forSale and underOffer so how would you get the properties marked in the Reapit software as Sold STC - Available? 

![183617060-ada487c9-da7a-451c-849b-fe22ba93974a](https://user-images.githubusercontent.com/124774637/223082292-34f62584-e899-44eb-9d12-e302198a22b2.png)

**Specification**
- Project: Reapit.Services.Configuration
- Add new endpoint GET /configuration/terminology whose purpose is to describe the way any terminology related configuration settings are applied in a customer's system. Initially the model will be very light as below
- Add new `TerminologyModel` (with embedded `PropertyTerminologyModel` as follows):

```
{
    "properties": {
        "useSoldStc": true,
        "useMarketAppraisal": true
    }
}
```

- The fields should be set as follows

| Database field  | Model value | Model comment |
| ------------- | ------------- | ------------- |
| configsetting.name where name = 'uUO'  | true when database value is false or not set (inverted)  | A flag denoting whether the agent's CRM is configured to use "Sold STC/SSTC" terminology instead of "Under Offer"
| configsetting.name where name = 'uUseMA' | true when database value is true or not set (true is the default)  | A flag denoting whether the agent's CRM is configured to use "Market Appraisal" terminology instead of "Valuation"

These fields are set in the CRM under System Configuration -> Properties which you will need to know for testing

**Comment by AshDeeming** [comment]
Hi @ElliottRowland 
SSTC & UnderOffer terms mean the same for AgencyCloud- In the system config of a clients database they can choose which of the terms they wish to use during their on-boarding.

**Comment by plittlewood-rpt** [comment]
Hi @ElliottRowland it's an either/or situation yes. I accept it might be helpful for you as a third party developer to understand what terminology a particular customer is using though, so we'll talk about that part of it on our refinement session later this week as we can probably add something to the configuration API to help you with understanding this so you can automate the process to decide what to display at your end.

**Comment by HollyJoyPhillips** [comment]
As discussed @plittlewood-rpt example below: 

GET /configuration/terminology
{
   "properties": {
      "useSoldStc": true,
      "useMarketAppraisal": true
   },
   "applicants": {
   // applicants API specific data etc
  }
}
