### ISSUE TITLE
Adding in Referral webhook topics

### ISSUE THREAD

**Issue by jaetoole** [reapit/foundations#8671]
**Is your feature request related to a problem? Please describe.**
We'd like a way to be notified once someone has been sent a referral from Reapit.

**Describe the solution you'd like**
Not tested this, but not sure if this triggers an update topic from the relevant record? Maybe Reapit can answer this>

**Describe alternatives you've considered**
Having to scrape every update which just seems a tad strange.

**Additional context**
We'd ideally like this ASAP! We presumed this was already a topic.

**Comment by plittlewood-rpt** [comment]
Hi @jaetoole. Referrals are already available as webhook events and I can see that they are being captured from your database as I'd expect. Your app will need to have the appropriate permission (referrals.read) for you to be able to subscribe to those webhooks. Let me know if you can't find it. Cheers

**Comment by jaetoole** [comment]
@plittlewood-rpt https://foundations-documentation.reapit.cloud/api/webhooks#available-topics

Want me to submit a PR to the docs to update that ha?

**Comment by plittlewood-rpt** [comment]
Woops. Good spot - that one's on me because I added support for it. Don't worry I'll sort it. Thanks for pointing that out
