### ISSUE TITLE
Transactions API not working

### ISSUE THREAD

**Issue by rajeshwl** [reapit/foundations#8677]
**Describe the bug**
For one of our client the transactions api call is returning **403** response. But in the app we have requested the permission for the transactions endpoint.

Client: **John Shepherd**(LOC-GJOS) - Part of Lomond Group
 
 Request URL: `https://platform.reapit.cloud/transactions/`
 
 Receiving the below response.
 `data: {
       statusCode: 403,
       dateTime: '2023-03-08T07:59:02.2828682Z',
       description: 'The identity attached to this request does not have the required permission to access the requested data. If you think you should be able to access this data, please use the Reapit Foundations Developer Portal to contact us to discuss the problem'
     }
`

**Comment by AshDeeming** [comment]
Hi @rajeshwl 
Please could you confirm the app name

**Comment by rajeshwl** [comment]
@AshDeeming ,
App Name: Starberry DataXchange AWS

**Comment by plittlewood-rpt** [comment]
Hi @rajeshwl currently the transactions API can only be used when an app is installed at an organisation level. This is because there are too many different ways of determining ownership of a record to be able to performantly apply security around the data exposed by this endpoint. A transaction does not have explicit office ownership, it might be inferred from the associated property/contact/landlord etc.

**Comment by rajeshwl** [comment]
@plittlewood-rpt ,
Do these client have not installed in Organisation level? If so, Is there a way for the multi tenant clients to install the App at  organisation level?

**Comment by plittlewood-rpt** [comment]
@rajeshwl when you received a client id/customer id in the format XXX-GYYY it means the app has been installed for a specific group of offices in the organisation. A client/customer id in the format XXX means the app has been installed for the whole organisation. This is something that organisation administrators can manage themselves.

**Comment by rajeshwl** [comment]
@plittlewood-rpt ,
Is there any way to import transactions for the clients installed app for specific office groups?

**Comment by plittlewood-rpt** [comment]
hi @rajeshwl as noted above the transactions API can currently only be used by apps installed at an organisational level. If it's a server-side app the customer may agree to install the app at that level, but that is a conversation you would need to have with them initially.

**Comment by rajeshwl** [comment]
@plittlewood-rpt ,
Using the current setup(Customer code: XXX-GXXX) is it possible to import the transactions specific to property / landlord?

**Comment by plittlewood-rpt** [comment]
Hi @rajeshwl no, any query to the transactions API must come from an app that is globally installed for an organisation as it stands at the moment

**Comment by rajeshwl** [comment]
@plittlewood-rpt , Sorry for another quick question regarding this, Previously we had tested the API in early December and we received data from this endpoint but not now. Is this due to any fixes done from your end in between this period?

**Comment by plittlewood-rpt** [comment]
@rajeshwl In December we made some security enhancements to the transactions endpoints to prevent undesired sharing of transactional data to third parties. It’s likely that the way you are calling the API is the reason your requests are now met with a 403. In light of your report we have had another discussion about how we could introduce new rules to this API that will allow safe access to transactional data for office group installations, however it would be helpful if you could confirm exactly how you are calling this endpoint, and also what you are doing with the data upon receipt. It’s likely that the enhancement will make it mandatory for at least one of the propertyId/landlordId/tenancyId query string parameters to be provided in your request so the appropriate filtering can be applied.

**Comment by rajeshwl** [comment]
@plittlewood-rpt ,
We import transactions based on modified Date(Incremental) periodically. We use this transactions details in our website to show the transactions for Landlords and tenant. It will be great if you sort the access for office group installations.

On the other hand as you mentioned of using at least one parameter of propertyId/landlordId/tenancyId . The problem here is we are not sure for which property the transactions has been added today or in sometime. Making calls for all properties / tenancies will create a cost impact for us as the no of requests will be increased significantly. On the other hand when we use modified date filter the calls will be limited to the frequencies we import like 10 times a day or something similar.

**Comment by HollyJoyPhillips** [comment]
We carried out an an initial test on the data last night out of hours (to prevent any disruption) and have a possible solution but we are still validating the results. We hope to have a further update shortly.

**Comment by HollyJoyPhillips** [comment]
Thank you for your patience whilst we carry out the validations. As mentioned above, we may have a potential route but we need to involve another department. Once we have had confirmation, we will be in touch to discuss further.

**Comment by plittlewood-rpt** [comment]
HI @rajeshwl we've been able to validate the approach we are taking and I'm actively working on this now. We should be in a position to release the changes early next week (Monday morning all being well).

**Comment by rajeshwl** [comment]
Thanks for the updates @plittlewood-rpt

**Comment by plittlewood-rpt** [comment]
Hi @rajeshwl this has now gone out to production. Please can I ask you to run your tests and confirm back to me that the required access is now open to you. For reference, transaction data will be filtered based on the client account the transaction is associated with. If the user/office group has access to the client account in AgencyCloud, you'll see all that accounts' transactions

**Comment by rajeshwl** [comment]
@plittlewood-rpt ,
I have tried importing transactions for the **John Shepherd client**(LOC-GJOS) and now it's working. Do we need to test all other brands or will it work fine as similar to **John Shepherd**?

**Comment by plittlewood-rpt** [comment]
All should be fine now if it’s working for one brand the behaviour will be the same for the others

Are you happy for this to be closed? Thanks
________________________________
From: rajeshwl ***@***.***>
Sent: Tuesday, March 28, 2023 3:47:27 PM
To: reapit/foundations ***@***.***>
Cc: Pete Littlewood ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [reapit/foundations] Transactions API not working (Issue #8677)


<https://github.com/plittlewood-rpt>

External Message - Please be cautious when opening links or attachments in email
________________________________
@plittlewood-rpt ,
I have tried importing transactions for the John Shepherd client(LOC-GJOS) and now it's working. Do we need to test all other brands or will it work fine as similar to John Shepherd?

**Comment by rajeshwl** [comment]
I am happy to close this ticket @plittlewood-rpt .
