### ISSUE TITLE
GET worksOrders does not seem to be embedding associated records anymore

### ISSUE THREAD

**Issue by whanno-lsl** [reapit/foundations#8680]
**Describe the bug**
We have an app in production that reads worksorders and embeds property, negotiator & company records.
We have just noticed today that the _embedded json field is being returned as null, rather than the arrays of related data.
This is happening in SBOX as well as our production environment.

**To Reproduce**
Do a GET /worksOrders query and try to "embed" an entity.
We have been using "&embed=property&embed=company&embed=negotiator".
The _embedded json field comes back as null.

**Expected behaviour**
The _embedded json field should contain the arrays of related data like it used to.

**Additional context**
Our app has been live for several months and the code has not changed in recent times.
The interactive API Swagger page in the Developer Portal seems to have the same issue.

**Comment by plittlewood-rpt** [comment]
Hi @whanno-lsl thanks for reporting this - we've got a fix incoming

**Comment by plittlewood-rpt** [comment]
Hi @whanno-lsl this should now be resolved. Please let me know if you still experience problems
