### ISSUE TITLE
API Diary Performance

### ISSUE THREAD

**Issue by danielalmeidaconnellsgroup** [reapit/foundations#8681]
Following on from https://github.com/reapit/foundations/issues/8548 - we're still seeing performance of 20s and we need to find ways to get this down to 5s or less.

Currently we need to get the entire branch diary  where as we just want to get the listers. Is there any way to filter particular users on the API?

Branches don't want to have to amend their diary, are there any ways we can tackle this to help improve performance?

Branches in the CWX instance are taking between 52 and 55 seconds to open - i'm guessing due to number of staff and appointments coming back.

**Comment by danielalmeidaconnellsgroup** [comment]
https://platform.reapit.cloud/appointments/?pageNumber=1&pageSize=100&negotiatorId=HRD3&negotiatorId=AAR5&negotiatorId=CHDA&negotiatorId=HDM7&negotiatorId=NQA1&officeId=NFI&start=2023-03-02T00%3A00%3A00.0000000Z&end=2023-04-20T00%3A00%3A00.0000000Z – 

This URL is an example of a call we’re making… this is on the CWC  instance.

What we’re seeing is sometimes its 2s, sometimes 3 and sometimes 7. This is with only 5 negs – when we bring back the entire diary, that makes it even slower – it feels like something is blocking calls on your end?

Questions we have:

1.	Is there a way to only bring back listers (e.g. a way of bring back users by type)
2.	Is there any way we can optimise this call? As I’ve said, it’s not practical to do housekeeping on the diary – but we want to leave as is and make this faster.

We will be currently when we go live on Monday making the call for all the users diary so…

https://platform.reapit.cloud/appointments/?pageNumber=1&pageSize=100&officeId=NFI&start=2023-03-02T00%3A00%3A00.0000000Z&end=2023-04-20T00%3A00%3A00.0000000Z

**Comment by danielalmeidaconnellsgroup** [comment]
The feedback is also that all branches on the CWX instance are poor in performance. Two more recent tests show

Bitterne  ABT
Canford Heath CAH
Gosport MGT

Are examples of branches which had poor performance during testing.

**Comment by plittlewood-rpt** [comment]
Closing issue as agreed with customer
