### ISSUE TITLE
Document Endpoint getting Timeout issue

### ISSUE THREAD

**Issue by rajeshwl** [reapit/foundations#8683]
**Describe the bug**
When we are trying to import documents for one of our mutual client John Shepherd(Lomond Capital), we are getting gateway timeout while using additional params like **associatedType**.

Request URL: `/documents/?modifiedFrom=2023-03-03T11:59:00.010Z&associatedType=property&associatedType=tenancy`

Response: `data: { message: 'Endpoint request timed out' }`

Client Code: John Shepherd(**LOC-GJOS**)

**Expected behaviour**
Expect the API to respond with the list of documents of pageSize 25.

**Comment by AshDeeming** [comment]
Hi @rajeshwl 
Please could you confirm the app name

**Comment by rajeshwl** [comment]
@AshDeeming ,
App Name: Starberry DataXchange AWS

@plittlewood-rpt ,
We are trying to fetch only one day data, but also it's getting timeout.

**Comment by plittlewood-rpt** [comment]
Same issue as #6176

**Comment by plittlewood-rpt** [comment]
Update sort operation behaviour for this customer in lieu of full feature change

**Comment by plittlewood-rpt** [comment]
@rajeshwl we have brought forwards some work we were planning to do more globally once all customers were on the correct AgencyCloud version, however in light of the problems you are having we will address this in the next week for LOC. There is some database maintenance we need to do before you'll see the benefit and it will affect this API only for the time being but I'll report back early next week once we are ready to go with it.

**Comment by rajeshwl** [comment]
@rajeshwl ,
Yes we can access the documents using modified date filter and it's working without timeout issue. Thanks for the updates @plittlewood-rpt
