### ISSUE TITLE
Rent arrears - "Manual Chase" tag

### ISSUE THREAD

**Issue by Speedway1** [reapit/foundations#8688]
**Background context**
Request is to add support for the "With Legal" status options which can be assigned to a tenancy on the chase arrears screen in AgencyCloud. This is not used by all agents so will need consideration and terminology will need to be appropriate to the use case.

**Specification**
- Project: Reapit.Services.Configuration
- Add new `GET /tenancyLegalStatuses` and `GET /tenancyLegalStatuses/{id}` endpoints that surface the `uWithLegalStatuses` custom list in configuration

- Project: Reapit.Services.Tenancies
- Add new `string legalStatusId` property to `TenancyModel` and `UpdateTenancyModel` (NOT create as a tenancy would never be created with a legal status set) that surfaces semi structured field ten.extra.tWithLegalStatus and allows write back for PATCH
- Introduce configuration client package with cache to validate that the provided legalStatusId is a valid option for the dataset concerned
- When set, add `legalStatus` link to `TenancyModel._links` collection to provide self describable link back to the configuration service

**Comment by AshDeeming** [comment]
Hi @Speedway1 
Please could you advise if there was a previous ticket logged for this request?

**Comment by Speedway1** [comment]
Hi Ash,  No.

**Comment by plittlewood-rpt** [comment]
There is no Manual Chase tag currently exposed in any of the endpoints. Can you confirm which endpoint you would like to see this introduced on?

**Comment by Speedway1** [comment]
Hi We are just confirming. Thank you

**Comment by Speedway1** [comment]
Hi, here is the endpoint as requested:
https://platform.reapit.cloud/transactions/?type=invoice&category=rent
Thank you

**Comment by Speedway1** [comment]
Hi, please see above.

**Comment by Speedway1** [comment]
Hi Team, any update on this please?

**Comment by plittlewood-rpt** [comment]
Hi @Speedway1 we do not have a Manual Chase flag. The closest thing that I can see that might relate to what you are describing is a Do Not Chase option which is stored against a tenancy (not against the transaction itself). Is this what you are looking for us to add?

**Comment by plittlewood-rpt** [comment]
Thanks - I've found what you are referring to. This isn't assigned to a specific transaction but is associated to the tenancy so it would be something added to the tenancy endpoint. As it's not a feature that all customers use we'll need to consider how best to implement this, so we'll review as soon as we can.

**Comment by Speedway1** [comment]
Thanks, really appreciate!

**Comment by Speedway1** [comment]
Is there any work-around that you can suggest in the mean time? We have clients champing at the bit for this. 

Is this "do not chase" boolean not something that can be included in the /tenancies/{id} end point? Seems a logical place for it to be.

Best,
Brad

**Comment by HollyJoyPhillips** [comment]
Following on from a discussion with the Foundations team, we will re review this ticket in our next refinement session scheduled for 25/05/23 (subject to change)
