### ISSUE TITLE
Access 'Noir' David Cliff (DAL)

### ISSUE THREAD

**Issue by legrandsolutions** [reapit/foundations#8690]
**Request**

In order for us to grant access to Semi-structured 'extras' field data, please provide the following information in this request:

David Cliff Estate Agents
Noir

Please can you enable the Noir field as shown in the screenshot in the API so that we use this field to filter properties on the website. 

We have a private app setup but looking to use the Property Hive app if possible instead so please can you let me know the next steps. 

Many thanks,
Alex

[Screenshot removed due to PII inclusion]

**Comment by plittlewood-rpt** [comment]
Hi @legrandsolutions this will be exposed in the `unmappedAttributes` collection on the properties endpoint when it has been specified by the branch. Please let me know if you need any more information on this. Thanks
