### ISSUE TITLE
How to access `Other Agent` for an appointment

### ISSUE THREAD

**Issue by iWader** [reapit/foundations#8693]
**Summary**

Access `Other Agent` data for an appointment via the api

**Detail and or supporting links and screenshots**

In the SBOX account I've got appointment MKT2300275 set up with HEO14000022 as the Other Agent.

I can retrieve the company from the `GET companies/HEO14000022` endpoint, but I can't see any way on the api that this agent is associated with the appointment.

Is it possible to access the related company to the appointment? If not, can this be updated so it is exposed?

**Specification**
- Project: Reapit.Services.Appointments
- Add `otherAgentId` property to AppointmentModel, CreateAppointmentModel and UpdateAppointmentModel that allows reading and writing `diary.extra.CmpCode`
- Add `otherAgent` link to `_links` collection when `otherAgentId` is populated that exposes a self-describing route to the companies API

**Comment by AshDeeming** [comment]
Hi @iWader 
Does this relate to comparable properties, i.e. properties that are on a clients database but being sold/Let by another agent?

**Comment by iWader** [comment]
In this case it's a diary appointment for a property (under viewings and keys) for a property inspection

**Comment by AshDeeming** [comment]
Thanks @iWader 
If a property is having an inspection, this would normally mean the property is instructed to that agent, not an other agent. 

Generally, any property on the system which is not under the agents remit, would be marked as a 'comparable' via the 'agency' field, under selling on the Properties endpoint

**Comment by SteveRad** [comment]
@AshDeeming we're actually looking for these attributes, specifically Provider, on the Diary appointment
![image](https://user-images.githubusercontent.com/1046960/224377681-05997492-2161-42c4-9690-1c1a2361ac3c.png)
