### ISSUE TITLE
Collinson Hall - different users showing different customer codes 

### ISSUE THREAD

**Issue by HomeflowSupport** [reapit/foundations#8702]
**Describe the bug**

Collinson Hall are trying to integrate with our Area software.

The issue is, some users have a Reapit Customer Code of COL and others have a code of COL-GMIO

The below screenshot is taken directly from the users Reapit account

eg

![image](https://user-images.githubusercontent.com/125559324/224272452-2eb87b7b-e1c2-4930-9d84-dc50fce3c772.png)

Please can you explain why this is happening? 

 We have implemented Reapit connect as per https://foundations-documentation.reapit.cloud/api/reapit-connect

When a user signs in using Reapit Connect, they are forwarded to a Reapit hosted sign-in page, and if they sign in correctly, Reapit Foundations forwards them on to us, with an authenticated single-use JSON Web Token (JWT). 

The details that are inside this token are what we can act upon as they have been signed and sent to us. They include Client Code which as the documentation states is the Reapit customer Id. This is in the  custom:reapit:clientCode field as per https://foundations-documentation.reapit.cloud/faqs#im-unsure-what-some-of-the-fields-in-the-id_token-relate-to
which states:

![image](https://user-images.githubusercontent.com/125559324/224273075-2e969fa5-fea1-4d52-8376-8de4ea2bfbc0.png)

In these instances, we are receiving a token containing the following:

![image](https://user-images.githubusercontent.com/125559324/224273158-aa739378-07f2-48f3-8ce9-d6b6edeffac7.png)
This does not match the installation Customer Code, and as such we cannot match it.

**Comment by AshDeeming** [comment]
Hi @HomeflowSupport 
The below section of the docs should assist with this but please revert if you have any further questions: https://foundations-documentation.reapit.cloud/faqs#what-are-office-groups

**Comment by HomeflowSupport** [comment]
Are we able to get everyone under the “COL” customer code or is there a reason that we have the “COL-GMIO” customer code in place?
