### ISSUE TITLE
Hardisty Integration Issue

### ISSUE THREAD

**Issue by BYMIntegrations** [reapit/foundations#8713]
Hello Support,

I hope you are well.

When pulling the data for code LOC-GHRD, we received the following response from the API, "The request cannot be fulfilled because it lacks the authentication credentials required to access the resource. Please generate a new access token and try again."

Please can we be given a new code for the data so that we can try pulling the data again.

I you have any questions, then please let me know 😊

Thanks,

Toby Hunter 
Integrations and Support Analyst

0344 800 84 24 (Ext 222) | TobyH@briefyourmarket.co.uk
www.briefyourmarket.com

**Comment by plittlewood-rpt** [comment]
Hi @BYMIntegrations which endpoint are you trying to reach?

**Comment by AshDeeming** [comment]
Hi @BYMIntegrations 
Your app does not appear to currently been installed by LOC-GHRD

**Comment by BYMIntegrations** [comment]
Hello Ash,

I hope you are well.

I see, I read the notification wrong.

I missed the "that 'LeadPro' has just been installed"

We can close this request.

I you have any questions, then please let me know 😊

Thanks,

Toby Hunter
Integrations and Support Analyst

0344 800 84 24 (Ext 222) | TobyH@briefyourmarket.co.uk
www.briefyourmarket.com
