### ISSUE TITLE
What response code and http status is returned when hitting rate limits?

### ISSUE THREAD

**Issue by joe-at-github** [reapit/foundations#8715]
Hi, 

I would like to know what response code and http status would be returned if we were to hit rate limits while querying the Foundations API?

I checked on the api documentation, we are using the properties, documents, negotiators and property images endpoints.
I am not seeing any reference to rate limits in the sample responses (200, 400, 403) so I just wanted to check.

Thank you.

**Comment by AshDeeming** [comment]
Hi @joe-at-github 
Please see the below & let me know if this doesn't answer your question;
https://foundations-documentation.reapit.cloud/api/api-documentation#rate-limits

**Comment by joe-at-github** [comment]
thank you @AshDeeming, it does indeed.
