### ISSUE TITLE
Property Type not coming through in 'type' field, but in 'unmappedAttributes'

### ISSUE THREAD

**Issue by propertyhive** [reapit/foundations#8718]
Client: Bell Ingram
Property: Mid Street, Beauly, Highland, IV4 7DP (INE220132)

In the data the property type isn't coming through the in normal 'type' field but instead in 'unmappedAttributes'

![Screenshot_1](https://user-images.githubusercontent.com/13717200/224783009-17c0d9f0-f47c-4ee0-a4c2-f9774bf6acac.png)

Can you confirm why this would be different for this client/property and if there's anyway to make it work like normal where it comes through as 'type'?

**Comment by LouiseSupport** [comment]
You are wonderful @plittlewood-rpt! Thank you!
