### ISSUE TITLE
Appointment codes

### ISSUE THREAD

**Issue by Speedway1** [reapit/foundations#8720]
Appointment codes associate with appointment types - 
AP - Appointment - 8
CI - Check In - 9
CO - Check Out - 10

We do not have a code for Unaccompanied Viewing - please see the screenshot.

<img width="755" alt="Screenshot 2023-03-14 at 13 12 12" src="https://user-images.githubusercontent.com/100301611/224998130-e167ef1e-d442-4226-a010-8f4a3617a4fb.png">

Would it be possible to request all available appointment codes please?

**Comment by AshDeeming** [comment]
Hi @Speedway1 
Please see the swagger docs section highlighted below - (https://developers.reapit.cloud/swagger) 
configuration/appoointmentTypes

![image](https://user-images.githubusercontent.com/61687775/225020278-a0fb2e56-88b2-4b81-9877-bf74c341b58b.png)
