### ISSUE TITLE
Unarchiving a contact

### ISSUE THREAD

**Issue by MatthewGoddard** [reapit/foundations#8724]
We want to add an applicant against an archived contact record.

At present, AgencyCloud checks existing contacts (Archived/and Unarchived) when adding a new applicant record and allows you to add the new applicant against an existing archived contact, if found. In the process, AgencyCloud unarchives the contact record.

Either creating a brand new contact (creates duplicate records) or having a user manually unarchive the record in AgencyCloud (not scalable).

**High level requirements**
- Support `fromArchive` flag in PATCH operations which governs archive/unarchive behaviour
- Journal entries to be created when operations executed

**Specification**
- Project: Reapit.Services.Contacts
- Add support for patching of the `fromArchive` property in the contact model. When we detect that this value has changed, run new business logic as per the process below
- Process for unarchiving:
  - Record in cnt_a is copied across to cnt (the record may already exist in cnt with the soft deletion marker set). The desired result is that the version of the record in the cnt_a table becomes present in cnt. Remember that the version of the archived record may have been updated, so simply flipping the deletion markers is NOT sufficient
  - Clear cntArch in cnt.cntExtra
  - Set cntRecovered in cnt.cntExtra to true
  - Emit a journal entry in the format generated by AgencyCloud so that there is an appropriate record of this action:
    - Type: DA
    - Text: `Contact recovered from archived: [name]`

**Comment by MatthewGoddard** [comment]
I now have a second integration requiring a similar flow.

As stated above, the only option presently available is to not dedupe on the contact, and simply create new contacts when the existing one is archived, but that approach will cause bigger problems due to the duplicate contacts and the knock on around GDPR etc.

**Comment by HollyJoyPhillips** [comment]
This has been approved by the Foundations team and will be re reviewed in our next refinement session.
