### ISSUE TITLE
Please expose the "unaccompanied" component for viewings: yUnacc

### ISSUE THREAD

**Issue by Speedway1** [reapit/foundations#8725]
Please expose the "unaccompanied" component for viewings: yUnacc. This is required for us to be able to support triggers for unaccompanied viewings. We have had client requests for this feature but cannot proceed until this has been implemented.

Thank you.

**Comment by AshDeeming** [comment]
Hi @Speedway1 
Please see the below screenshot from the swagger docs - which can be used for the above;
![image](https://user-images.githubusercontent.com/61687775/225261172-2e3de232-252d-42aa-a3e4-b2d4271b9896.png)

**Comment by Speedway1** [comment]
Thanks Ash, we missed that one. Appreciate it!
