### ISSUE TITLE
Is searching for offices that cover a postcode area possible?

### ISSUE THREAD

**Issue by robchett** [reapit/foundations#8728]
**Summary**
In webservice we were able to query `/postcodes/XXX+XXX/offices` and we'd be given a list of Offices that cover that postcode.
Is this possible in Foundations? 

**Detail and or supporting links and screenshots**

**Comment by AshDeeming** [comment]
Hi @robchett 
Using Areas and their associated polygons

**Comment by robchett** [comment]
Hi Ash,

In webservice we're using this API to decide which branch to assign a new contact to based on their postal address.
Correct me if I'm wrong but to check this using the areas API we'd need to load every area and see if they contain a point to then see which Office the area belongs to.

I'm not sure if it was a specific LSL development in webservice, but the Offices had catchment areas assigned based on postcodes and these were used to route new Contacts and leads to the correct branch.

**Comment by robchett** [comment]
Hi Ash, 

After an internal review, we will no longer be needing this endpoint.
