### ISSUE TITLE
Semi-structured 'extras' field request: "Rent Includes" field for Linley & Simpson

### ISSUE THREAD

**Issue by Tomtalus** [reapit/foundations#8729]
**Request**

In order for us to grant access to Semi-structured 'extras' field data, please provide the following information in this request:

**- The name of the customer you represent**
Linley & Simpson, Vikki Clayton (Linley & Simpson) & Elizabeth Hamlin (Lomond Group)

**- The name of every field you need surfaced (if known)**
The 'Rent Includes' field which is highlighted on the screenshot below, and is found on the Rent/Financial screen on the property record.

**- A screenshot of of the field(s) you require in the agency cloud user interface**
![image](https://user-images.githubusercontent.com/126699655/225368339-5f1f215e-35e9-4896-8a80-62b04b1823aa.png)

**- A short use case as to why you require this data**
This field is going to be used by Linley & Simpson to determine whether a landlord is responsible for bills for a property and subsequently whether we should send utility notifications for that move. 

**Specification**
- Project: Reapit.Services.Properties
- Add new string field `rentIncludes` to `PropertyLettingModel`, `UpdatePropertyLettingModel` and `CreatePropertyLettingModel` that allows the reading and writing of semi structured field prp.extra.pRentIncludes

**Comment by Tomtalus** [comment]
Thank you,

When is this deployed or is it now already available?

**Comment by dantherussell** [comment]
@ashindey12 I didn't know if you received notifications on closed issues by default or not so I wanted to tag you in case you'd missed Tom's question. Thanks from us for getting this done by the way, we really appreciate how transparent your processes are.
