### ISSUE TITLE
Property Type

### ISSUE THREAD

**Issue by Jejin** [reapit/foundations#8730]
Is the property type, Apartment, Terrace etc. available in any of the tables in the DW ?

**Comment by plittlewood-rpt** [comment]
Hi @Jejin 

You can use the PROPERTY_ATTRIBUTES view model data to access this information

Thanks
Pete

**Comment by Jejin** [comment]
There seems to be multiple entries with different values for the Attribute Type column with the same time stamp against the same property ID. Is this an issue with the data load or is there an explanation why this is the case ?

![image](https://user-images.githubusercontent.com/6023154/228421275-e777ba5b-2f7b-4f4b-8978-9b600b8ea5b4.png)

**Comment by plittlewood-rpt** [comment]
Hi @Jejin there is one row per attribute column/checkbox value. In your screenshot above you can see the the ATTRIBUTE_VALUE is different so there are no duplicates, it's just telling you that this property has Ground Floor and Terraced ticked in the Style column, for example. The sync date is based on the date the property was last updated. Hope this helps

**Comment by Jejin** [comment]
Amazing, that helps and thank you for the prompt response.

**Comment by plittlewood-rpt** [comment]
No problem at all - are you happy for me to close this issue now?
