### ISSUE TITLE
Document not being propagated to the website for customer

### ISSUE THREAD

**Issue by MarcinuB** [reapit/foundations#8733]
We working with Savills on creating pdf brochures.  We're uploading them to the property documents and then set as particulars. We've been told that after uploading - those should be picked up and added to the property rightmove page. It doesn't happen for some properties (examples: NOH220224, NOH220008). This is related to the  Reapit support ticket RSD-221773. 

Below is a list of steps that we do in this process:
1. Creating signed url with the documents/signedUrl endpoint
2. Upload document with presigned url
3. Trying to delete previous brochure version (if exists). The id is taken from property.selling.brochureId or property.letting.brochureId fields (depending on the property.marketingMode)
4. POST to documents where associatedId is set to the property code and typeId is set to "LET"
5. Update property and setting selling.brochureId or letting.brochureId to the id of the newly created document (depending on marketingMode)

We were given a summary of the support ticket:

> “The following query is run, inserting an entry into the FILEMAN table
> 
> INSERT INTO FILEMAN ( extra, synchdel, synchrec, register, amend, code, tblname, tblcode, type, filename) VALUES ('gfPrivate=.T.gfAddedBy=''RPT''', '0', NOW(), NOW(), NOW(), 'RPS23000006', 'PRP', 'CTS230011', 'LET', 'test PDF.pdf');
> 
> It also place the file in the relevant directory, prplet (s3://reapit/sav/rps/live/prplet/CTS23/PRP/CTS230011_RPS23000006.pdf)”

We've actually did set the typeId to "DET" before because we misunderstood this property, but it was fixed 2 days ago but it still doesn't work for customer. It is probably something that we set wrong but we need your help in understaning what we should change.

Thank you

**Specification**
- Project: Reapit.Services.Properties
- Add lightweight fileman entity to allow us to look up the filename and set `pDetails` in prp.Extra which is the field the custom Savills web feed is looking for. When handling changes to the brochureId for selling/letting properties, ensure pDetails is set according to the filename on the fileman resource. Some important points
  - pDetails doesn't have a concept of dual market, so only set it if either of the brochure ids are set and it isn't already set to one of the matching documents

**Comment by MarcinuB** [comment]
Hi Team.

Is there any update on this one? I've noticed you've added this to your sprint which is great. Can you just let me know when you will be able to look into it  so I can notify the customer?

Thank you.

**Comment by plittlewood-rpt** [comment]
Hi @MarcinuB is there an example that has not been fixed yet that you are aware of? I just need to catch up on how the customer's website gets fed so we can start unpicking what might be going on here

**Comment by MarcinuB** [comment]
Hi @plittlewood-rpt - it looks like it is caused by file being too big. 
We have a release due for our pdf generator that will help with the size, but please keep this open until next week and I will confirm if that was the only reason. 

Thank you

**Comment by plittlewood-rpt** [comment]
HI @MarcinuB  thanks for letting me know. I'll stand down for now until I hear back from you

**Comment by MarcinuB** [comment]
Hi @plittlewood-rpt .

We need to have that investigated again. We still have some files not being propagated. 
I will raise a Zendesk ticket with details.

**Comment by plittlewood-rpt** [comment]
Hi @MarcinuB thanks - if you can include as much info as possible that would be great. I'll try get someone to look at it today.

**Comment by MarcinuB** [comment]
@plittlewood-rpt .
Thanks for looking into that. Appreciate it.

**Comment by plittlewood-rpt** [comment]
@MarcinuB just to let you know the work to resolve this is done and pending QA. As it's Friday this won't go out till Monday but I'll prioritise it next week.

**Comment by plittlewood-rpt** [comment]
@MarcinuB sorry for the delay on this - we've had a problem with our build server which I think is now sorted so I just need to get this QA'd before I can get it out to Production but it should drop soon.

**Comment by plittlewood-rpt** [comment]
Hi @MarcinuB this is just going out to production. Can you let me know when you next post a brochure for Savills and I'll make sure everything is as it should be. It's worth noting that as part of this ticket we've added some additional validation to prohibit you from attaching private documents as brochures which is something that was missing before. Let me know if you run into any trouble but it should be OK from here.

**Comment by MarcinuB** [comment]
Hi @plittlewood-rpt . 
Thank you a lot. If all works then we will have so much easier with support queries so we really appreciate your intervention.
A couple brochures were posted this morning so you can double check if everything works on your side.

Thank you

**Comment by MarcinuB** [comment]
Hi @plittlewood-rpt. 
Some examples below:

ELS230042
FUS220074
STS230004
BIX220189
NES230033
GLS230024

I've also noticed I've got an error when setting the brochureId for this property:  STS230004. 
Failed to set the document Id on the property url: https://platform.reapit.cloud/properties/STS230004 - Error:  Call failed with status code 412 (Precondition Failed): PATCH https://platform.reapit.cloud/properties/STS230004.
but that is probably not related.

**Comment by plittlewood-rpt** [comment]
Hi @MarcinuB I've checked one of the properties and it's showing the brochure on the website now: eg https://search.savills.com/property-detail/gbbyrsbix220189

They might not all show yet as the web feed will need to run to pick up all the changes and I'm not sure what the frequency is but the data looks right now so I'm confident this should be resolved.

**Comment by MarcinuB** [comment]
@plittlewood-rpt - fantastic.

Thanks again and to the next time :)
