### ISSUE TITLE
Internal server error ,while creation of contact in SBOX through API

### ISSUE THREAD

**Issue by subin-roundr** [reapit/foundations#8734]
**Describe the bug**
Internal server error ,while creation of contact in SBOX through API

![image](https://user-images.githubusercontent.com/78721314/225591724-eae4313d-c82e-407a-8e51-e486bef47cad.png)

**Comment by plittlewood-rpt** [comment]
HI @subin-roundr this issue should be resolved. There was an issue with a service release which has now been rectified
