### ISSUE TITLE
Ability to restrict user access to specific tables in Data Warehouse

### ISSUE THREAD

**Issue by GilesVMP** [reapit/foundations#8742]
We operate a principle of least privilege across all systems.  When providing a third party with access to our data in the data warehouse, it's vital we can limit this access to only specific tables in order to protect our data and our customer's data.

**Comment by HollyJoyPhillips** [comment]
To review and deep dive impact/possibilities

**Comment by HollyJoyPhillips** [comment]
Milestone to be assigned and scoping tickets to be created.
