### ISSUE TITLE
Expandable content being truncated in table

### ISSUE THREAD

**Issue by nroper** [reapit/foundations#8745]
Please take a look at our FAQ's before submitting an issue, as your question may already be covered in the documentation https://foundations-documentation.reapit.cloud/faqs

**Summary**
Need to be able to display complete content in an expander row of a table

**Detail and or supporting links and screenshots**
We're using a table with expandable content to display additional notes where appropriate.  

The content is being displayed across two columns, which we're achieving by applying a `el-span2 ` class per the documentation.  However, if the content is more than two rows then it is truncated and an an ellipsis is appended - see screen shot:

<img width="491" alt="Screenshot 2023-03-17 at 08 08 43" src="https://user-images.githubusercontent.com/479971/225851465-316ccacf-ed78-4962-aa42-22e739412cc9.png">

Inspecting the page shows that there is a `el-table-cell-content` class applied and that's setting the following:

```
max-height: calc(60px - 0.75rem);
overflow: hidden;
line-height: 1.5rem;
text-overflow: ellipsis;

```
Disabling the overflow setting allows the full content to be viewed by scrolling, but still with the ellipsis in place - disabling that seems to have no effect.

The documentation suggests that longer content can be displayed by adding a `data-force-narrow-table="true"` attribute to the Table, but that doesn't seem to work either.

Would be grateful for advice on the correct approach to display/scroll long content.

Many thanks.

**Comment by willmcvay** [comment]
@nroper Looks like you are inserting a table cell into the expandable content. Just use a <p> or <BodyText> component and the expandable content will expand to the height of your content.

**Comment by nroper** [comment]
Thanks @willmcvay I'll give that a try.

**Comment by nroper** [comment]
Yup, that's done the trick, many thanks @willmcvay - closing this now.
