### ISSUE TITLE
Can't find Company/Contact for a Tenancy which is being let by a Company

### ISSUE THREAD

**Issue by robchett** [reapit/foundations#8750]
**Describe the bug**
Tenancies only embed Applicants, in cases where the renter is a Company no Applicant is returned. 

**To Reproduce**
Steps to reproduce the behaviour eg:
1. Lookup tenancyId=WDE210220 on RER

**Expected behaviour**
Some way to access the details of the renter though the API

**Screenshots**
N/A

**Device (please complete the following information for web issues):**
N/A

**Additional context**
N/A

**Specification**
- Project: Reapit.Services.Tenancies
- Investigate and reproduce the issue. It could just be an incorrect query filter being applied depending on if there is a difference between contact/company lookup record types.
- This should work so fix as appropriate

**Comment by NBareham** [comment]
This is a screenshot of the company as a tenant in Reapit:

![image](https://user-images.githubusercontent.com/101395511/226589560-ea2bfa3e-b15b-463c-84a3-62221e23a54a.png)

**Comment by NBareham** [comment]
And the company itself:

![image](https://user-images.githubusercontent.com/101395511/226589660-73bef440-844e-4a57-8aa9-bf2139dae045.png)

**Comment by RWilcox-Reapit** [comment]
Hi @robchett 

I'm just looking into this now and can see that the company is returned in the 'related' collection as type 'company'.
In your request to the platform are you using the query parameter 'embed=applicant' and expecting to see the company in that collection? 

If so I can see the issue. Just trying to confirm expectations before tackling the issue. 

Thanks
Ryan

**Comment by robchett** [comment]
Thanks, not sure how we missed that entirely but I think we were expecting the same flow of `Tenacy.applicantId -> Applicant -> Contact` as there would be for a normal tenancy. 

We also didn't think it could be embedded as Companies are not listed in the documentation

![image](https://user-images.githubusercontent.com/5231691/231202888-9dc73d39-e33e-4f46-b55c-53b29f580806.png)

Now we can see it in `related` that should do us fine, assuming we can always expect a `related.company` to be the Tenant and not some other relationship?

**Comment by RWilcox-Reapit** [comment]
Hi @robchett 

That's correct you can always assume that a 'related' entity of type 'company' is the tenant.
You can't currently embed companies although it would be possible for us to implement this. 

I'll make a note to flag this with colleagues during the next refinement/planning session.

Thanks
Ryan
