### ISSUE TITLE
Query Get properties endpoint based on their Date of Entry/Completed date

### ISSUE THREAD

**Issue by AdamHall12** [reapit/foundations#8752]
**Is your feature request related to a problem? Please describe.**
Not a problem as such but more a limitation. We would like a way to find properties that have a date of entry in the past but their status is not set to be completed. 

**Describe the solution you'd like**
Query based on the property's completed date and status e.g. &completedTo=2023-03-17&sellingStatus=....(everything but completed)

**Describe alternatives you've considered**
The only way we can do this (we think) is to get all properties with status not equal to completed and filter based on the completed date in the next step.

**Additional context**

**Comment by plittlewood-rpt** [comment]
Hi @AdamHall12 I can see you've logged this before in #8480. Unfortunately the same response still applies, although we are making progress internally on refactoring how we store this data to make it queryable. Please subscribe to your original ticket and I'll close this one down.

**Comment by AdamHall12** [comment]
Ah sorry Pete my mistake. We started another small project which made it pop up again. Thanks for the update.


Adam Hall
Business Systems & Automation Technician
Rettie & Co Ltd
4 Jamaica Street, Edinburgh, EH3 6HH
phone: 0131 322 2657
email: ***@***.***

Rettie & Co. Ltd is a limited company registered in Scotland. Registration Number: SC144330. Registered Office: Deuchrie, Dunbar, East Lothian, EH42 1TG. VAT Registration Number: 593 2816 16.
​Our email confidentiality and email disclaimer policy can be found on our website. Click here to view.
