### ISSUE TITLE
Retrieve applicants collection related to property in REST API

### ISSUE THREAD

**Issue by david-silverink** [reapit/foundations#8754]
We don't seem to be able to retrieve a collection of applicants that are matched to a property record via the REST API. This is possible via Agency Cloud, and our client would like us to access this list of applicants without involving an export/import into our system.

**Comment by plittlewood-rpt** [comment]
Refinement note: This would need a matching API dedicated to this purpose. To be reviewed as part of Foundations roadmap

**Comment by neilpellowe** [comment]
After reviewing the feature request the changes required do not align to our current priorities and this item isnt something that we will proceed with as part of our product roadmap. 
Our Roadmap priorities are reviewed regularly and if this changes in the future we will create a new ticket for progression. This ticket will now be closed
