### ISSUE TITLE
Endpoint request: Clearing funds in Reapit & Fixflo

### ISSUE THREAD

**Issue by katedeedman** [reapit/foundations#8758]
Hello Reapit!

Our mutual client, DJ Alexander, has been in touch with us about clearing funds in Fixflo. They've requested a workflow in FF whereby the reserved funds would be cleared by the PM if the works order is removed in Fixflo. This would then sync into Reapit. Do you have an endpoint for this? 

Thanks in advance!

-Kate (Product Manager at FF) 

**Specification**
- Project: Reapit.Services.WorksOrders
- Add new `decimal? reserveAmount` to `WorksOrderItemModel` that maps to workdet.maintfloat` with the following comment: `The amount of funds to be held back by the agent in landlord payment runs to cover the cost of any works required by the works order item`
- This should be both readable and writeable. Write side should follow the validations and behaviours. Consider using the repository in the validation class to simplify validation that usually sits in the handlers, as this means all validation rules sit in one class which is easier to manage

**Write validations**
- It should not be possible to set the reserveAmount to a negative value
- It should only be possible to set or change the reserveAmount to when chargeTo = landlord
- It should not be possible to set or change the reserveAmount when the works order status is cancelled

**Write behaviour**
- When works order status is changed to cancelled, workdet.maintfloat should set to zero (for all the items on the works order)
- Patch to work like any other field. Null means do nothing, else set to value provided
- When chargeTo changes from landlord to tenant (as part of a patch) the reserve funds on the item should be zeroed

**Comment by HollyJoyPhillips** [comment]
Product decision required from the Foundations team as it relates to transactional data.

**Comment by neilpellowe** [comment]
This request forms part of a larger roadmap discovery item to review our current Endpoint offering and any additional areas we may consider opening up. Accounts and related fields will be reviewed as part of this discovery. Once complete, tickets will be updated.

**Comment by HollyJoyPhillips** [comment]
Moving into refinement as confirmed with Foundations no direct relation to client accounts (transactional data).

**Comment by HollyJoyPhillips** [comment]
Emailed Foundations for further clarification.

**Comment by plittlewood-rpt** [comment]
Hi @katedeedman we need to just do some further investigation on this to ensure there'll be no impact to other areas of the system. We'll do this as part of the linked ticket above and then come back to this item and add a proper specification.

**Comment by plittlewood-rpt** [comment]
@neilpellowe we've scoped this out and can proceed. Please can you schedule.

**Comment by plittlewood-rpt** [comment]
HI @katedeedman please see the spec above for the work being done. In summary, the information is available on the existing endpoints

![image](https://github.com/reapit/foundations/assets/30798627/3fb5f21f-6bd5-474b-a44e-9e8a7c0111a0)

Hope this helps :)

Pete
