### ISSUE TITLE
Properties Table - Lettings Agency Missing Custom Agency Types

### ISSUE THREAD

**Issue by kmacgregorPR** [reapit/foundations#8759]
**Background context**
Following Custom Agency Types not appearing in analytics schema, please can they be added:

In Jeopardy - For Sale
In Jeopardy - Let By Other Agent
In Jeopardy - LL Reoccupying
In Jeopardy - LL Self Managing
In Jeopardy - Other
In Jeopardy - Service Issue
Lost Management
Lost Management - LL Reoccupied
Lost Management - Let By Other Agent
Lost Management - LL Self Managing
Lost Management - Other
Lost Management - Service Issue
Lost Management - Sold 
Managed if Let
Potential Management - Didn't Go Ahead
Potential Management - Switched to LO 
Retained From In Jeopardy
Won Management 

**Specification**
- Project: Analytics Schema
- Update custom list handler to take into account custom agency types when generating properties model view data

**Comment by plittlewood-rpt** [comment]
Hi @kmacgregorPR I've just looked into this and it is working as intended as far as I can tell. Looking at your dataset there's only a single property using one of the custom options (property JES220001 which is a test property) and this is showing as "Managed if Let" correctly in the data warehouse. If you can give me any specific examples where you are seeing this not working please let me know but I think it's just a case of none of your properties are using those custom agency types. Thanks

**Comment by kmacgregorPR** [comment]
Hi @plittlewood-rpt - thank you for coming back to me. We now have numerous properties in various ones of the status in the original background context, however, in the data tables (via powerquery editor) we are only presented with the options within the screenshot attached. 
![Lettings Agency](https://user-images.githubusercontent.com/128388971/229839922-692695eb-0da6-45ea-969c-92e0a9c855b6.JPG)

**Comment by plittlewood-rpt** [comment]
Hi @kmacgregorPR the analytics schema will need to refresh before you get the updated data. Can you check in an hour or so as I'd expect it to have updated by then. I think the refresh run starts at half past the hour and it takes about 20 minutes.

**Comment by plittlewood-rpt** [comment]
I've got a fix pending for this - just waiting for QA so this should be resolved today. Sorry for the confusion, I was convinced I'd read "lettings" somewhere then couldn't see it in the description of the issue (need to check the title next time!!)

**Comment by plittlewood-rpt** [comment]
This should now be resolved. Thanks

**Comment by kmacgregorPR** [comment]
Good morning,

I logged the above query on GitHub last week but it has not been assigned to anyone yet, I wondered if I should be submitting this a different way?

Kind regards,

Katherine MacGregor (FARLA)
Director
0191 20 90 100
***@***.******@***.***>

***@***.***
www.patrobson.com<http://www.patrobson.com/>   [Join us on Facebook] <https://www.facebook.com/pat.robson.35?fref=ts>   [Follow us on Twitter] <https://twitter.com/pat_robson>
[http://www.patrobson.com/email-signatures/mp-button.png]<https://www.patrobson.com/make-a-payment/>[http://www.patrobson.com/email-signatures/rr-button.png]<https://www.patrobson.com/report-a-repair/>


This email is intended solely for the named recipient(s) only. It may contain privileged and/or confidential information. If you are not one of the named recipients, please notify the sender immediately, and destroy this email; you must not copy, distribute or take any action in reliance upon it. Whilst all efforts are made to safeguard inbound and outbound emails, Pat Robson & Co Ltd cannot guarantee that attachments are virus-free or compatible with your systems and does not accept any liability in respect of viruses or computer problems experienced. If you no longer wish to receive emails from Pat Robson & Co Ltd you can unsubscribe from ***@***.***?subject=Please%20Unsubscribe%20Me>. Our privacy policy can be viewed at www.patrobson.com/about-us/cookies-privacy<https://www.patrobson.com/about-us/cookies-privacy>
