### ISSUE TITLE
Please create a desktop type for licensing

### ISSUE THREAD

**Issue by Speedway1** [reapit/foundations#8760]
Hi Team,

In order to implement service requests from some of Reapit's larger customers, we require a desktop type for licensing. Please can you create this?

Thank you.

**Comment by HollyJoyPhillips** [comment]
Waiting for AC-8165 to be completed (requires development work from the Desktop Team)

**Comment by HollyJoyPhillips** [comment]
Relates to: https://github.com/reapit/foundations/issues/8901

**Comment by othyn** [comment]
Hi team, just leaving a comment to say this would be a feature also required for Kamma's integration as well 👍

**Comment by HollyJoyPhillips** [comment]
Integration type is now available https://foundations-documentation.reapit.cloud/api/desktop-api#property-licensing
