### ISSUE TITLE
Charging for API requests even when the customer has the "website integration service"

### ISSUE THREAD

**Issue by ElliottRowland** [reapit/foundations#8761]
Hi,

Our Property Uploader for Webdadi websites app uses the endpoints /property and /propertyimages to download the property information for display on the client's website.

Our understanding is any client with the website integration service from Reapit is entitled to 600k API calls a year before the website provider is charged. We've moved several clients to the service who have confirmed with their reapit account manager that they have this service. Our understanding was there would be no charge to Webdadi for these api calls.

However, I have noticed that we have been charged for API calls to these clients. Could you outline the circumstances in which we'd be charged directly even when the client has the website integration service? We need to ensure our commercials are correct. We can work out a charging model for clients who do not have this service, but have been working on the assumption that those with this service would be free to download their data (unless they breach their 600k limit).

Happy to provide details of the client's to a secure email address rather than posting here.

Many thanks,

Elliott

**Comment by AshDeeming** [comment]
Hi @ElliottRowland 
I'll refer this to our Partnerships team to review & revert

**Comment by ElliottRowland** [comment]
Thanks @AshDeeming. John has been in touch so i'll pick it up with him.
