### ISSUE TITLE
Property status change to prospecting/pre-appraisal

### ISSUE THREAD

**Issue by ErnstHavenga001** [reapit/foundations#8763]
We currently report on property status' changed to prospecting/pre-appraisal in a given date range. We don't appear to be able to do this at the moment in the data warehouse.
 
 
![Journal criteria for Prospecting](https://user-images.githubusercontent.com/128135294/226522249-246137a8-f0c6-4d71-96a4-9b3939d30195.png)

**Comment by ErnstHavenga001** [comment]
@plittlewood-rpt Just wanted to check if you received my comment?

**Comment by plittlewood-rpt** [comment]
Hi @ErnstHavenga001 as discussed yesterday this will be taken care of as part of #9357 where you'll get a view of all property status change data to use as you like. I'll close this issue - please track the other one for updates.
