### ISSUE TITLE
Getting results from offices that are not selected for the group

### ISSUE THREAD

**Issue by matt-fixflo** [reapit/foundations#8764]
**Describe the bug**
Getting results from offices that are not selected for the group (Based on customer reports of their configuration)

**To Reproduce**
Make a request to https://platform.reapit.cloud/properties?officeId={OFFICECODENOTINGROUP}

**Expected behaviour**
Result set to be empty

**Screenshots**
N/A

**Additional context**
I will send the Reapit customer and Office code by email

**Comment by AshDeeming** [comment]
Project Manager confirmed issued resolved
