### ISSUE TITLE
Property status change to For Sale

### ISSUE THREAD

**Issue by ErnstHavenga001** [reapit/foundations#8772]
We currently report on property status' changed to For Sale in a given date range. We don't appear to be able to do this at the moment in the data warehouse.

![For Sale](https://user-images.githubusercontent.com/128135294/226903826-de48625e-9e2d-41b7-a314-bd50429bbe05.png)
" from the Journal entries.

**Comment by plittlewood-rpt** [comment]
Hi @ErnstHavenga001 

The existing PROPERTY_SALES_WON_INSTRUCTIONS and PROPERTY_LETTINGS_WON_INSTRUCTIONS model views in the analytics schema are largely based on journal data and should allow you to achieve what you are trying to do. Can you confirm if you've reviewed the data in these tables before we look into this further?

Thanks
Pete

**Comment by ErnstHavenga001** [comment]
@plittlewood-rpt

Thank you very much for your reply.

If I look at the PROPERTY_SALES_WON_INSTRUCTIONS table, I only see 1173 rows under Column INSTRUCTED_DATE for 2023 so far. The Reapit report we are trying to duplicate is producing 1406 rows.

![For Sale Availible report](https://user-images.githubusercontent.com/128135294/227862931-41412d8b-565d-43d6-accf-1d81010c7ff0.png)
![For Sale Availible](https://user-images.githubusercontent.com/128135294/227862938-834a690f-783b-499f-9619-3c898ec33660.png)
![VALUATION_DATE](https://user-images.githubusercontent.com/128135294/227862940-388e5fd1-706e-4acc-b30c-5ca6df9d28f0.png)

**Comment by ErnstHavenga001** [comment]
@plittlewood-rpt Just wanted to check if you received my comment?

**Comment by plittlewood-rpt** [comment]
Hi @ErnstHavenga001 are you happy with the response above and can this be closed?

**Comment by ErnstHavenga001** [comment]
@plittlewood-rpt Yes Thank you very much
