### ISSUE TITLE
Frontend for semi-structured fields in webhook configurations

### ISSUE THREAD

**Issue by plittlewood-rpt** [reapit/foundations#8773]
**Background context or User story:**
#8258 introduced backend changes to allow developers to 'opt-in' to receiving extra semi structured data in their webhook notifications. This has now gone out to production so we can think about what the frontend should look like.

Extra field configuration is related to a specific webhook
Developers need to be able to specify one or more fields in their webhook configuration which are then included in the POST/PUT body to the webhooks service (see Swagger page for updates)

**Specification or Acceptance Criteria:**
- As a developer I should be able to specify one or more semi structured fields to include in my webhook notifications
- As a developer I should be able to remove any previously configured semi structured field items in my webhook notifications
- As a developer, making any change to a webhook configuration's extra fields should persist the changes in the webhooks database
- As a developer, when creating a new webhook any extra fields included in the configuration should be persisted in the webhooks database

**Comment by joshbalfour** [comment]
@HollyJoyPhillips I've had a stab at this, ping me when you're back and I'll show you what I've done, hopefully it's what you had in mind!
