### ISSUE TITLE
Reapit logout to revoke session tokens

### ISSUE THREAD

**Issue by sarangnff** [reapit/foundations#8776]
We want to trigger a logout for Reapit-user-session through our backend (Node.js) so that the access-tokens and refresh-tokens for the logged in user become invalid.  Is there an API endpoint or any other way this can be achieved ?

**Specification**
- Review /oauth2/revoke endpoint [documentation ](https://docs.aws.amazon.com/cognito/latest/developerguide/revocation-endpoint.html) as this likely fits the bill here. Confirm back to developer if this does what is required

**Comment by plittlewood-rpt** [comment]
Hi @sarangnff - you should be able to use the "revoke" endpoint at https://connect.reapit.cloud/oauth2/revoke to revoke the refresh token(s) generated for your app. We use AWS Cognito under the hood and you can view the documentation for that [endpoint here](https://docs.aws.amazon.com/cognito/latest/developerguide/revocation-endpoint.html). I've just done some testing with this myself and it works as I'd expect. Can you have a look and see if that fits your use case?
