### ISSUE TITLE
Responses in some API calls (502, 504)

### ISSUE THREAD

**Issue by abrahamseni** [reapit/foundations#8786]
HI,

Currently, our clients face this issue when they try to interact with Property / Contacts API calls.

Could someone please investigate what is the bottleneck when querying the API?
An example is searching Contacts by name `Smith` we sometimes get 502 / 504, it is not all the time, but quite often.

![Screenshot from 2023-03-23 16-43-43](https://user-images.githubusercontent.com/94949137/227404813-48f5bedf-4384-476d-a7aa-0a15216ed8b6.png)
![Clipboard - March 23, 2023 4_33 PM](https://user-images.githubusercontent.com/94949137/227465664-cc7d3967-aa7b-4932-9ab0-66460ad6c760.jpg)

**Comment by RLAV1** [comment]
Hi @AshDeeming  do you know when your team will be able to review this item or if theres been any updates?

**Comment by abrahamseni** [comment]
Hi @AshDeeming, we propose adding `nameType` params to search in GET `/Contacts`, just like in applicants or tenancies.
What do you think?

**Comment by abrahamseni** [comment]
refer to new ticket: #8832

**Comment by RLAV1** [comment]
Added comment to Bump so this can be reviewed

**Comment by johnpenrose** [comment]
@abrahamseni @AshDeeming @RLAV1 

The original bug description on this ticket talks about getting 502/504s on both Contacts and Property API calls.

I understand the new feature request (8832) is billed as a fix for this ticket, but to my untrained eye the new feature will only apply to the contacts end point, leaving us still with 502/504s when using the property end point.

Am I missing something? Thanks.

**Comment by RLAV1** [comment]
Hey @AshDeeming could you add the date of when this will be reviewed to set expectations with Savills?

**Comment by johnpenrose** [comment]
@AshDeeming I'd also appreciate your initial thoughts on my questions above, if you're able. Thanks.

**Comment by plittlewood-rpt** [comment]
Please can you provide some detail on the filters you are using that result in timeouts on the properties endpoint? We are aware of intermittent timeouts on larger enterprise databases and unfortunately there is no magic answer however it's something we are actively looking at resolving. A key area that is in the spotlight is the use of the modifiedFrom/modifiedTo query string parameters on a number of APIs which can often timeout. We have been making some changes to the core CRM to alter how it stores data to allow us to more efficiently query the database when using these filters which should be rolled out fairly soon.

**Comment by abrahamseni** [comment]
Hi @plittlewood-rpt , Thanks for the feedback.
For properties API, we usually use this param/filter:
```js
pageSize, pageNumber, marketingMode, lettingStatus, address, id: []
```

I believe querying some address street names often results in a timeout.

**Comment by johnpenrose** [comment]
@plittlewood-rpt we are currently using a work-around, filtering the search to look for only current tenancies. I may be mixing my terminology here, but I think the guys said this is known as 'quick search'.

The timeouts mostly occur when we do not use this work-around (which is activated via a checkbox in the UI). See screengrab below for an example:

![image](https://user-images.githubusercontent.com/130659584/234801508-2b14c2c7-a3c0-4210-8cbc-a5b13f604ea8.png)

**Comment by johnpenrose** [comment]
@plittlewood-rpt @AshDeeming can you please respond to Ross' previous request for an indication of timescale on this? Thanks.

**Comment by plittlewood-rpt** [comment]
Closing as agreed with MG
