### ISSUE TITLE
Integration with "Recent" list feature in AC when creating/updating records via REST API

### ISSUE THREAD

**Issue by ss-dimasm** [reapit/foundations#8787]
**Summary**
How could we add the record that created/updated via REST API to the "Recent" list feature in AC without search/open the record first? is there any thing that we could do to achieve this? I've also include the flow for easy understanding about this requirement. Thanks

**Explained flow:**
1. create new applicant record via REST API
2. record created, open the AC with same account
3. go to the Applicant tab and take a look at "Recent Applicants" list
4. the record that has been create from point 1 is not listed in the recent applicants list

**Additional context**
-  using same account to create the record and access AC

**Comment by Endlay** [comment]
hi @AshDeeming, I have read the comments above, what exactly do you need from the product team to proceed?

**Comment by AshDeeming** [comment]
Hi @Endlay 
This will need to be discussed at AgencyCloud level, once any actions agreed, this will then go through Foundations before Platform team can update our tools.

**Comment by HollyJoyPhillips** [comment]
This is with @Endlay to gather further requirements
