### ISSUE TITLE
Rental applicants not receiving bedroomsMin/Max

### ISSUE THREAD

**Issue by robchett** [reapit/foundations#8788]
**Describe the bug**
Creating/Updating an applicant with marketingMode = renting will not save the submitted values for bedroomsMin/Max

**To Reproduce**
Steps to reproduce the behaviour eg:
```
Create an applicant with this post body:
{
  "active": true,
  "marketingMode": "renting",
  "notes": "Created on the Your Move website.",
  "type": [],
  "bedroomsMin": 1,
  "bedroomsMax": 2,
  "age": [],
  "departmentId": "G",
  "officeIds": [
    "LSH",
    "QYO",
    "NEA",
    "ABB"
  ],
  "negotiatorIds": [
    "YNIB"
  ],
  "locationType": "areas",
  "locationOptions": [
    "DEG"
  ],
  "metadata": {
    "WEBSITE_AREAS": "[{\"title\":\"Hoo Areas\",\"radius\":0,\"reference\":268435839}]",
    "WEBSITE_AUCTION": false,
    "WEBSITE_KEYWORDS": "",
    "WEBSITE_SALE_AGREED": true,
    "WEBSITE_CHAIN_FREE": false,
    "WEBSITE_STUDENT": false
  },
  "renting": {
    "rentFrom": 1,
    "rentTo": 10000,
    "rentFrequency": "monthly",
    "furnishing": []
  },
  "related": [
    {
      "associatedId": "LSH19000003",
      "associatedType": "contact"
    }
  ]
}
```

**Expected behaviour**
Bedroom values to be stored.

**Screenshots**
N/A

**Device (please complete the following information for web issues):**
N/A

**Additional context**
Updating a sales search to rental leaves the existing bedrooms values but they can't be updated or removed.

**Specification**
- Project: Reapit.Services.Applicants
- Review customer's department configuration. It is possible that the labels on the room fields are not on our lookup list in the `DepartmentNumTitle` enum as there is handling for both split single/double bedroom fields and single field for both in the service
- Replicate issue and understand what we need to do to resolve it. Fix with appropriate tests

**Comment by RWilcox-Reapit** [comment]
Hi @robchett 

Can I get the name of the customer you are experiencing this issue with? 
It works on our Sandbox environment so I'm assuming it's related to the department setup but I'll need to customer details to check. 

With this info I'll be able to update the service to handle this edge case.

Thanks,
Ryan

**Comment by robchett** [comment]
Sure, I was testing with YOM.

**Comment by RWilcox-Reapit** [comment]
Hi @robchett 

Based on the clients department setup I'd have expected the extras field 'dOnlyTotalBedsL' to have been set to true like it has been for 'dOnlyTotalBeds'. 

I have a fix waiting for this but I'd like to talk to @plittlewood-rpt before pushing this out as it's an edge case which could interrupt the flow for all customer so it may not be until Monday.

Thanks,
Ryan

**Comment by RWilcox-Reapit** [comment]
Hi @robchett 
Happy to confirm a fix for this has gone in. It was indeed an issue specific to lettings properties and related to the associated departments setup. 

Thanks
Ryan
