### ISSUE TITLE
Validation errors when lower/upperbound not present on applicant record

### ISSUE THREAD

**Issue by soilleir** [reapit/foundations#8793]
**Describe the bug**
This patch request on an applicant record is failing saying that the max room attribute needs to be the same or more than the min room attribute.  An almost identical request 40mins previous did not have this error.  This needs looked at urgently as this is going to affect our customers (i.e. our customers as we are Rettie and co and not a third party developer). **We dont set Max on rooms as 99% of applicants dont want to set a max limit on these only a min limit.**

**FAILING REQUEST**
{
  "sellingPosition": "notYetOnMarket",
  "type": [
    "house",
    "flatApartment"
  ],
  "style": [
    "detached",
    "semiDetached",
    "terraced",
    "bungalow",
    "steading",
    "upperFloor"
  ],
  "situation": [],
  "bedroomsMin": "2",
  "bedroomsMax": 0,
  "receptionsMin": "1",
  "receptionsMax": 0,
  "bathroomsMin": "1",
  "bathroomsMax": 0,
  "buying": {
    "priceFrom": 200000,
    "priceTo": 350000,
    "reasonId": "TL",
    "positionId": "CB"
  },
  "locationType": "areas",
  "locationOptions": [
    "NRV"
  ],
  "notes": "===RettieConnect====\nDate: 2023-03-24T11:03:59.2519871Z\nHow soon looking to buy: 3-6 months\nSeparate kitchen\n\n===============\n Hello, Holly.\r\n\r\nI have a flat to sell but some repairs need to be done first. I am a cash purchaser.\r\nRegards,\r\nHelen.",
  "lastCall": "2023-03-24",
  "nextCall": "2023-04-07",
  "active": "true"
}

**ERROR FOR THE FAILING REQUEST**
{"errors":[{"field":"BathroomsMax","message":"Applying this update is not possible. The value provided must be greater than or equal to 2"},{"field":"BedroomsMax","message":"Applying this update is not possible. The value provided must be greater than or equal to 4"},{"field":"ReceptionsMax","message":"Applying this update is not possible. The value provided must be greater than or equal to 1"}],"statusCode":422,"dateTime":"2023-03-24T12:06:07.1598916Z","description":"One or more validation failures have occurred. Please refer to Errors list for details"}

**REQUEST 40mins previous to the one above and worked fine which you can see is also setting the Max room attributes to 0.**
{
  "sellingPosition": "notYetOnMarket",
  "type": [
    "house",
    "flatApartment"
  ],
  "style": [
    "detached",
    "semiDetached",
    "terraced",
    "bungalow",
    "steading",
    "upperFloor"
  ],
  "situation": [],
  "bedroomsMin": "2",
  "bedroomsMax": 0,
  "receptionsMin": "1",
  "receptionsMax": 0,
  "bathroomsMin": "1",
  "bathroomsMax": 0,
  "buying": {
    "priceFrom": 200000,
    "priceTo": 350000,
    "reasonId": "TL",
    "positionId": "CB"
  },
  "locationType": "areas",
  "locationOptions": [
    "NRV"
  ],
  "notes": "===RettieConnect====\nDate: 2023-03-24T11:03:59.2519871Z\nHow soon looking to buy: 3-6 months\nSeparate kitchen\n\n===============\n Hello, Holly.\r\n\r\nI have a flat to sell but some repairs need to be done first. I am a cash purchaser.\r\nRegards,\r\nHelen.",
  "lastCall": "2023-03-24",
  "nextCall": "2023-04-07",
  "active": "true"
}

**Comment by soilleir** [comment]
Ok this is serious and needs addressed immediately.  More responses from our customers are failing now.

**Comment by soilleir** [comment]
We re getting the same  error even when not patching any room attributes 
{
  "active": "false",
  "nextCall": "2123-01-01",
  "lastCall": "2023-03-24",
  "notes": "===RettieConnect Update====\nDate: 2023-03-24T12:40:37.0318449Z\nNo Longer Looking Reason:\n I've found the property I was looking for \nAdditional Comments:\n\n===============\n ",
  "negotiatorIds": [
    "TBA"
  ]
}
ERROR
{"errors":[{"field":"BedroomsMax","message":"Applying this update is not possible. The value provided must be greater than or equal to 3"}],"statusCode":422,"dateTime":"2023-03-24T12:40:42.0152633Z","description":"One or more validation failures have occurred. Please refer to Errors list for details"}

**Comment by soilleir** [comment]
it appears to be affecting any applicant record who had a room requirement set which we are trying to patch based on their response to a request from us.

We have 5000 Reponses from applicants due over the weekend. which is why this is so serious

**Comment by soilleir** [comment]
I suspect attempts to fix this bug is the root of the issue https://github.com/reapit/foundations/issues/8788

@plittlewood-rpt I've emailed you direct about the seriousness of this one for us.

**Comment by plittlewood-rpt** [comment]
Hi @soilleir - looking at this now. I'm just rolling back to the previous version
