### ISSUE TITLE
Best approach for contacts and identity checks shared between Customer IDs

### ISSUE THREAD

**Issue by nikolai-momot-thirdfort** [reapit/foundations#8795]
**Summary**
Our company has 2 apps: the main app that uses Reapit Connect and a companion app that uses Client Credentials

The main app is used for fetching contact details as well as creating identity checks and journal entries.

The companion app is used for asynchronous updates to the identity checks such as updates in status and uploading documents.

Both apps have the same permission set: Read Contacts, Write Contacts, Read Identity Checks, Write Identity Checks

There are no pending revisions and the permissions have been accepted by all users of our app.

Both the main app and companion app have been installed by our users - there are no active users that don't have both apps installed.

The flow taken by our user follows this patters:
1. The frontend uses Reapit Connect to authorise it's calls to the Agency Cloud API
2. The frontend uses Reapit Connect fetch the contact details and populates a requests to our backend
3. The backend uses Reapit Connect to create an identityCheck and a journalEntry
4. The backend stores the identityCheck ID, the contact ID, and the customer ID that created that check for later use
5. The backend receives an asynchronous update to the identity check
6. The backend uses Client Credentials to update the identityCheck and create a journalEntry

This flow generally works without issue but we have found that in about 10% of cases we receive a 404 not found error on the contactId, identityCheck, or journalEntry.

By comparing our logs and database records, we are confident that this issue is **not** caused by an incorrect value stored in our database.

On further investigation, we found that the contact IDs that experience the issues described above are created by one Customer ID and the identityCheck process is initiated by *another* customer ID - both of these customers are from Savills.

We have not been able to find anything in the documentation to explain why this issue would occur.

Please advise on how to best address this issue

**Specification**
- Project: Reapit.Services.IdentityChecks
- Ensure that the check that runs when creating a new identity check to validate the contact id applies the office group filtering (`IdentityChecksRepository.GetContactByIdAsync`)
- Ensure appropriate tests added for this use case. It should not be possible to create an identity check for a contact you don't have access to when office groups are enabled as part of the user context

**Comment by AshDeeming** [comment]
Hi @nikolai-momot-thirdfort 
Please could you provide any example references for this to be reviewed further?

**Comment by nikolai-momot-thirdfort** [comment]
Hi @AshDeeming 

We get the customer ID using the `custom:reapit:clientCode`  property that is in the Reapit Connect `id_token` and set it as the `reapit-customer` header when making a request to the Agency Cloud API

When the Identity Check is initiated using the POST identityChecks endpoint, we do not check for which customer ID originally created the contact - we always defer to the Reapit Connect `id_token`

An Identity Check `PHS23000019` was created for contact ID `HAH06000220` with the customer ID `SAV-GPRH`

Using the PATCH identityChecks endpoint for Identity Check `PHS23000019` with customer ID `SAV-GPRH` resulted in a 404 error

Later we found out that the contact ID `HAH06000220` is owned/created by customer ID `SAV-GHMP` :
using the GET contacts endpoint for contact ID `HAH06000220` with the `reapit-customer` header `SAV-GHMP` was successful
using the GET contacts endpoint for contact ID `HAH06000220` with the `reapit-customer` header `SAV-GPRH` was unsuccessful

Using the same methodology we discovered, that the identityCheck `PHS23000019`  also belongs to  customer ID `SAV-GHMP`  :
using the GET identityChecks endpoint for Identity Check `PHS23000019`  with the `reapit-customer` header `SAV-GHMP` was successful
using the GET identityChecks endpoint for Identity Check `PHS23000019` with the `reapit-customer` header `SAV-GPRH` was unsuccessful

**Comment by nikolai-momot-thirdfort** [comment]
@AshDeeming any update?

**Comment by AshDeeming** [comment]
Hi @nikolai-momot-thirdfort 
This ticket has been updated, ready for refinement this week - please see more details around this process below;
https://foundations-documentation.reapit.cloud/dev-requests#our-processes

**Comment by plittlewood-rpt** [comment]
Hi @nikolai-momot-thirdfort we cannot change the security controls around the APIs and the way the office group mechanism works (which is in play wherever you see a GXXX suffix on the client code). The actual issue here is more that you shouldn't be able to create an identity check for a contact you don't have access to. The validation that checks the contact exists isn't taking account the same security controls applied to the contacts API. With this in mind, you'll no longer be able to create identity checks for contacts that the office group doesn't have access to, and you'll see consistency between behaviour in the identity checks and contacts APIs

**Comment by nikolai-momot-thirdfort** [comment]
@plittlewood-rpt Can you provide some guidance on how we are meant to handle this instead?
We have lots of offices(from the the same company) sharing contacts and creating identity checks for them

**Comment by plittlewood-rpt** [comment]
Hi @kithmini 

The security in the Platform APIs won't necessarily match up with what's set up in AgencyCloud which is much more fine grained as more can be done in memory. The APIs use an office grouping mechanism to apply filtering as it pulls data back from the database. This needs to remain performant for the API to be usable.

We can proceed (and will, as it needs fixing) with the update mentioned above which will resolve your problem if the customer has set up office groups in a manner that fits their AgencyCloud setup, but we have no control over how they set their groups up. Can I suggest we put this fix out first then we can re-review once it's bedded in a bit as from what you've said above I think it'll resolve most of your problems.

Thanks
Pete
