### ISSUE TITLE
Incorrect areaId still being passed when querying /properties/{id}

### ISSUE THREAD

**Issue by tim-west** [reapit/foundations#8806]
Incorrect `areaId` still being assigned to properties e.g.

1. If you query the endpoint `/properties/NHO220194`, you will see the `areaId` returned is **HON**.
2. If you then query the endpoint `/areas/HON` you will see a list of coordinates returned under `area` that makes up a polygon.
3. When you plot the polygon on a map, you will see that the  latitude/longitude for the property falls outside the defined polygon. See [demo](https://codepen.io/timwestdesigns/pen/gOdEdya).

(Originally reported in #8561)

**Comment by plittlewood-rpt** [comment]
Hi @tim-west, this is something that we've raised with the desktop development team. The areaId field is actually based on a legacy part of the CRM and is only populated for older properties. When you change the latitude and longitude of the property, the CRM is not currently checking (and updating if required) the location id. We've asked if this can be addressed but I don't have a timescale currently.

**Comment by tim-west** [comment]
@plittlewood-rpt, if `areaId` is not populated on newer properties, is there an alternate method to get the area?

**Comment by tim-west** [comment]
@plittlewood-rpt, I have just checked the one of the newest properties, KOF230040, created on 07/03/2023 and the `areaId` has been populated.

**Comment by plittlewood-rpt** [comment]
I've just checked the example and it was duplicated from KOF220146 which was duplicated from KOF120121 (the latter is a very old property)

**Comment by tim-west** [comment]
@plittlewood-rpt
> Where areaId is not set, you would interrogate the areas configuration data (from GET /areas/{id}) to understand which area or areas the coordinates from the property fall in. Areas can overlap and it's down to individual agents to determine their own preference here

So am I right in thinking, for any new property or broken old property where you need the correct area, you would have to:

1. Query the `/properties/` endpoint
2. Store the property's lat and lng in a variable
3. Make another query to the '/areas/' endpoint (possibly multiple depending on how many there are)
4. Store the areas in a variable 
5. Loop through every single area in the organisation using an algorithm to determine which of the areas the lat and lng fall inside

If this is the case, this seems incredibly inefficient and surely makes more sense to keep the `areaId` and update the software to allow an override by the agent if necessary.

**Comment by plittlewood-rpt** [comment]
HI Tim, understand your comments and this is why we've asked the desktop team to look at it. The more efficient way of you handling this as things stand now would be to keep a copy of the customers' area configuration that you can reference as part of your processing function (assuming it's a server-side app which I presume is the case). You can then refer to it as you process each property.

**Comment by plittlewood-rpt** [comment]
Update from AC team:
- Item to be added to next refinement session (PBI-4528)
- Additional enhancement logged to allow users to manually change the location id if it is incorrect or doesn't match geo coordinates

**Comment by HollyJoyPhillips** [comment]
This has been resolved in AgencyCloud version 12.168.
