### ISSUE TITLE
'Modified' timestamp not updating when Selling->Qualifier is changed

### ISSUE THREAD

**Issue by mc1906** [reapit/foundations#8811]
**Describe the bug**
If the price qualifer for a property is updated this does not seem to update the modified timestamp for the property.

The effect of this is that these properties are not included in API requests when filtering by 'modifiedFrom' parameter.

**To Reproduce**
Steps to reproduce the behaviour eg:
1. 06:00 AM - API Request for property via the 'properties' endpoint (without setting a modifiedFrom URL parameter)
2. 06:00 AM - Property comes through in JSON response and is updated on website
3. 09:00 AM - Agent updates the property price qualifer in the Reapit system for a property
4. 10:00 AM - API Request property via the 'properties' endpoint (with setting a modifiedFrom URL parameter as 06:00 today)
5. 10:00 AM - Property with changed price qualifier is not included in JSON response

**Expected behaviour**
We would expect the property that has had price qualifer modified since the 'modifiedFrom' date to be included in the API response.

**Comment by AshDeeming** [comment]
Thanks @mc1906 
Please could you provide the example ref for review.

**Comment by mc1906** [comment]
Hi @AshDeeming 

Sure .. the ref for the property in question is [WKY230009]

The 'modifiedFrom' timestamp for this proeprty has now been updated - which was achieved by editing the property description.

**Comment by plittlewood-rpt** [comment]
Hi @mc1906 as dates are returned in UTC this could be to do with the clocks changing potentially. Can you confirm what you are passing as your modifiedFrom parameter? If you are passing local time you need to make sure you are passing the offset correctly eg

?modifiedFrom=2023-04-06T13:10:00+00:00 if passing UTC dates or
?modifiedFrom=2023-04-06T14:10:00+01:00 if passing 'local' dates (BST right now)

I've just tested this on the Sandbox and it seems to behave as I would expect but would invite your feedback.
