### ISSUE TITLE
Automatic Import function not working since website migration

### ISSUE THREAD

**Issue by potooleaindale** [reapit/foundations#8818]
Please take a look at our FAQ's before submitting an issue, as your question may already be covered in the documentation https://foundations-documentation.reapit.cloud/faqs

We are trying to migrate the website to a new web host but the Reapit automatic import function is no longer functioning since the migration. It works if I click on Run Now but the next due to run shows nothing. This should be set to run hourly but again it shows nothing and does not ever run.

![image](https://user-images.githubusercontent.com/129301561/228587473-1445b1c8-06ee-43d8-a35b-a756e3fdbb27.png)

**Comment by AshDeeming** [comment]
Hi @potooleaindale 
Please could you provide more details - this will be down to the web dev to choose how to best update the site

**Comment by potooleaindale** [comment]
Reapit support has set up a temp feed for us to set up the migrated website but has pointed me to the Development team to resolve this issue. Hence me asking here.

**Comment by potooleaindale** [comment]
I managed to fix this issue. The problem was that the corn job that is used to run the property update automatically wasn't functioning correctly. Once this was fixed the issue was resolved.
