### ISSUE TITLE
Appointments starting a midnight during DST get set back 1 hour

### ISSUE THREAD

**Issue by iWader** [reapit/foundations#8819]
**Describe the bug**

We're updating an appointment via the api to start a midnight, the request is successful, but when we retrieve that appointment it now starts at 23:00:00 the day before

**To Reproduce**

```json
{
    "start": "2023-03-29T00:00:00Z",
    "end": "2023-03-29T01:00:00Z"
} 
```

1. `PUT /appointments/:id` with the above payload
2. Now `GET /appointments/:id`
3. See the start date is now `2023-03-28T23:00:00Z`

**Expected behaviour**

Should not modify the start date 

**Screenshots**

N/A

**Device (please complete the following information for web issues):**

N/A

**Additional context**

https://github.com/reapit/foundations/issues/6339 seems to explain the same issue, but theres no confirmation that it was fixed

**Comment by plittlewood-rpt** [comment]
Hi @iWader 

Is this just happening when setting the time to midnight?

**Comment by iWader** [comment]
That seems to be the case.

I was testing with various times between 08:00 and 18:00 and they all worked fine. 

We noticed the issue as customers are booking all day appointments on our system, so we're trying update the appointment on RPS and set the times to start at 00:00:00, end at 01:00:00

**Comment by plittlewood-rpt** [comment]
Thanks @iWader - we'll take a look at this

**Comment by RWilcox-Reapit** [comment]
Hi @iWader 

I'm happy to confirm a fix has gone in for this now.
If your still experiencing any issues let me know

Thanks
