### ISSUE TITLE
Revisit office group filtering on documents API

### ISSUE THREAD

**Issue by rajeshwl** [reapit/foundations#8825]
**Describe the bug**
We tried to import the documents use the document API but for many document the download call return 403 Forbidden response. Can please check and fix it out.

Client Code: John Shepherd(LOC-GJOS)
Documents we tried downloading: 
LCC23000290
LYH23000200
BSA23003021
BSA23003020

**Error we receive:**  Request failed with status code 403

**Specification**
- Project: Reapit.Services.Documents
- Revisit office group filtering
- Update DocumentModel to only expose download link if user is allowed to download the document

**Comment by plittlewood-rpt** [comment]
Hi @rajeshwl the download endpoint is protected by office group security. It's likely the owning entity (eg property) is not accessible to that office group. I will check shortly and confirm

**Comment by rajeshwl** [comment]
@plittlewood-rpt , If download endpoint is protected by office group we shouldn't receive that document in the `/documents/` get call as well right?

**Comment by plittlewood-rpt** [comment]
@rajeshwl that is a necessary trade off between performance and being able to protect the actual document content which can contain sensitive information whereas the JSON resource does not. We may be able to remove the download link so you can understand whether or not you Will be able to access the physical document

**Comment by rajeshwl** [comment]
@plittlewood-rpt , Will the JSON be limited to office group? Because receiving all office documents for each sub tenant(LOC-GJOS) will increase the number of calls and impact in the cost as well.

**Comment by plittlewood-rpt** [comment]
@rajeshwl no the json is not limited by office group currently

**Comment by rajeshwl** [comment]
@plittlewood-rpt , Can you raise a ticket internally to fix this? As that will help us reducing billing and number of requests.

**Comment by plittlewood-rpt** [comment]
Hi @rajeshwl this is not a bug but is by design due to the performance impact that we would see if we tried to filter the data. It's on the list of things we need to revisit and we will look at it in due course as part of this ticket.

**Comment by rajeshwl** [comment]
Thanks for the details @plittlewood-rpt . Let us know once this has been fixed.

**Comment by plittlewood-rpt** [comment]
HI @rajeshwl will do - just to clarify this isn't _broken_ but we will look at whether or not we can improve the mechanism

**Comment by rajeshwl** [comment]
Hi @plittlewood-rpt ,
Is this been fixed? When can we expect this to be working? Client has asked us to enable the documents listings to the landlords in the website. So can you please prioritize this.

**Comment by plittlewood-rpt** [comment]
Hi @rajeshwl as mentioned above this isn't broken, it's working as intended. We will update the issue once it is reviewed further.

**Comment by rajeshwl** [comment]
Okay @plittlewood-rpt .

**Comment by plittlewood-rpt** [comment]
Hi @rajeshwl we are going to run a bit of a spike on this ticket so see if the performance degradation is acceptable if we make the necessary adjustments. Please note this is not a commitment to changes being made in production as we will need to test this thoroughly against large datasets before making a decision about how we move forwards.

**Comment by plittlewood-rpt** [comment]
Hi @rajesh I've had another look at this. The issue for you here is that you don't know if you will be allowed to _download_ a document. Is that correct? Instead of filtering the data out, would it work for you if we omitted the `download` link in the `_links` collection for any file that you won't be able to download based on the owning entities office ownership information? This will allow us to get to a result which works for you, but that doesn't upset the performance of the API

**Comment by plittlewood-rpt** [comment]
HI @rajeshwl this change has now been made. You will only receive a download link in the _links collection for files you will have access to. It's been quite a refactor to do this so please let me know if you encounter any issues. Thanks
