### ISSUE TITLE
Additional info field 

### ISSUE THREAD

**Issue by MarcinuB** [reapit/foundations#8836]
Hi Team.

Can I ask for granting us access to the below: 

- Customer: Savills
- Field required: Extras description -> Additional info (see screenshot below)
- Use case: to get the data from that field to populate brochure.

![image](https://user-images.githubusercontent.com/8589350/229487576-8fbd446f-fe66-4125-98a7-8139193962ea.png)

Thank you
Marcin

**Comment by MarcinuB** [comment]
Hi @AshDeeming. What's the ETA for this one. We would need it enabled as soon as possible as we have a number of offices going live and in need for that field.

Thank you

**Comment by plittlewood-rpt** [comment]
Hi @MarcinuB - this has now been enabled for you. The field name to include in your request is `pAreaGuide` (slightly confusing I know, it looks like the label has been changed at some point over the years). Please allow up to 15 minutes for the configuration changes to synchronise across the API estate.

Usage examples:

`GET /properties?extrasField=pAreaGuide` or `GET /properties/XXX000000?extrasField=pAreaGuide`

Any issues let me know. Thanks

**Comment by MarcinuB** [comment]
Hello @plittlewood-rpt .

Thanks for sorting that out for us.

Have a good day!
