### ISSUE TITLE
Foundations API explorer companies/{id}/staffMembers endpoint error

### ISSUE THREAD

**Issue by AdamHall12** [reapit/foundations#8837]
**Describe the bug**
The companies/{id}/staffMembers endpoint is not working for me on the API explorer. It is returning an 'undocumented' error code. I have tried refreshing so that it renews the bearer token but this does not fix the issue. I am not sure if this issue is limited to the API explorer but have not been able to test outside of it.

**To Reproduce**
Steps to reproduce the behaviour eg:
1. Go to the foundations API explorer.
2. Click on the GET companies/{id}/staffMembers endpoint and 'Try it out'
3. Test using any company ID

**Expected behaviour**
Produce a response with the company's staff members

**Screenshots**
![image](https://user-images.githubusercontent.com/102241930/229524879-d6379dd9-3121-448d-8d39-389db075fac6.png)

**Device (please complete the following information for web issues):**
 - Device: HP Elitebook x360 1030 G4
 - OS: Windows 10 Pro
 - Browser: Edge
 - Version: 111.0.1661.62

**Additional context**

**Comment by plittlewood-rpt** [comment]
HI @AdamHall12 - I'm not getting the same behaviour and get a 404 using the same id you are using. Is your account associated with a customer account, and if so, can you let me know which one and if your account is in Customer or Sandbox mode (you can see this on the Settings page). Thanks

**Comment by plittlewood-rpt** [comment]
Hi @AdamHall12 thanks - please can you confirm the customer id?

**Comment by AdamHall12** [comment]
@plittlewood-rpt RET is the customer id I believe

**Comment by HollyJoyPhillips** [comment]
Hi @AdamHall12 is this still an issue or can this be closed?

**Comment by HollyJoyPhillips** [comment]
Great, thank you for the reply.
