### ISSUE TITLE
Telephone number not saving when creating a new app

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#884]
**Describe the bug**
The 'Telephone' field is not saving when submitting or editing an app. After submitting a new app and clicking on 'Edit Detail', the telephone number is missing. Even after adding it again, approving the revision, it is no longer there. 

**To Reproduce**
Submit App > Save > App > Edit Detail > observe the telephone number is missing
Add telephone number > approve revision > Edit Detail > telephone number is again missing 

**Expected behavior**
Telephone should be saved 

**Screenshots**
See telephone has been added 
![image](https://user-images.githubusercontent.com/52408607/79108048-6ead9b80-7d6d-11ea-9b25-5b9a206eba5b.png)

See revision has been approved: 
![image](https://user-images.githubusercontent.com/52408607/79108085-7bca8a80-7d6d-11ea-9f04-9f26fc3216c5.png)

See telephone number is no longer saved :
![image](https://user-images.githubusercontent.com/52408607/79108110-8edd5a80-7d6d-11ea-80d1-09eb14c93619.png)

**Comment by cbryanreapit** [comment]
Ticket is back end related. The response from GET /apps/{id} is presenting the telephone number associcated with the developer rather than the app revision specifically. We should switch to display the revision detail instead. PR in review.
