### ISSUE TITLE
Add support for Goldcircle, USP

### ISSUE THREAD

**Issue by joe-at-github** [reapit/foundations#8840]
See response to bullet points below:

- The name of the customer you represent
GAC

- The name of every field you need surfaced (if known)
Coming in via Reapit Live feed, the fields are nested in XML as
'//Property/Keywords' #8859
'//Property/Goldcircle'
'//Property/USP'
'//AltCode' #8858 

- A screenshot of of the field(s) you require in the agency cloud user interface
N/A

- A short use case as to why you require this data
We process property data on behalf of Grant & Co.
We are preparing migration towards Foundations API feed and would need access to these fields in Foundations.

**Specification**
- Enable access to semi structured fields pUSP and pGoldcircle using build in extrasField mechanism for customer GAC

**Comment by plittlewood-rpt** [comment]
Hi @joe-at-github I've split this ticket up into a few different items.

Exposing pGoldcircle and pUSP can be exposed using our existing extrasField mechanism as these fields are custom to this specific agent
I have logged two additional tickets to add structured fields to the property API to expose the alt code and keywords.

**Comment by joe-at-github** [comment]
thank you @plittlewood-rpt 
Do I need to submit a request [via this form](https://github.com/reapit/foundations/issues/new?assignees=&labels=back-end%2C+needs-triage&template=extras_field.md&title=), to request access to  pGoldcircle and pUSP?

I have made a request specifying these fields using the extrasField, but got the following response:
`{
    "statusCode": 400,
    "dateTime": "2023-04-06T15:46:25.3529946Z",
    "description": "Access to one or more of the specified fields is not permitted. You must be granted access to this data beforehand"
}`

**Comment by plittlewood-rpt** [comment]
Hi @joe-at-github these fields are now available for the customer mentioned above. Please use extrafields pUSP and pGoldCircle for the USP and Gold Circle descriptions respectively eg

`GET platform.reapit.cloud/properties?extrasField=pUSP&extrasField=pGoldCircle` or  `GET platform.reapit.cloud/properties/ABC123456?extrasField=pUSP&extrasField=pGoldCircle`

Please note it may take up to 15 minutes for the changes to take effect across the service estate, so please wait until this period has passed before attempting to call the APIs as above.

**Comment by ashindey12** [comment]
AltCode (AlternateId) field is already available in Properties service Get and Patch endpoints.
