### ISSUE TITLE
Ellis and Co Enfield - Lettings branch not pulling feed through. 

### ISSUE THREAD

**Issue by BYMIntegrations** [reapit/foundations#8843]
Please take a look at our FAQ's before submitting an issue, as your question may already be covered in the documentation https://foundations-documentation.reapit.cloud/faqs

**Summary**
We created a feed for the customer, but one of the feeds are not pulling through. 

Ellis and CO enfield Sales - FDTN14939001

Ellis and Co Enfield Lettings - FDTN14939002

Could you please confirm if these branch ID's are correct as the lettings feed isn't pulling through. 

Thanks
**Detail and or supporting links and screenshots**

**Comment by plittlewood-rpt** [comment]
HI @BYMIntegrations the Platform does not use branch ids. Please confirm how you are calling the API and with which client id(s)

**Comment by HollyJoyPhillips** [comment]
Closing due to no response.
