### ISSUE TITLE
Requesting access to Featured property flag from API (Fisher German - FSG)

### ISSUE THREAD

**Issue by asif-startberry** [reapit/foundations#8846]
Request
Our client wants to show the featured property in the website. The featured property flag is currently not available in the default API response. So we request you to enable the extras field for this and share the field name.

Customer Code: Fisher German - FSG
Field: Featured

**Comment by AshDeeming** [comment]
![image](https://user-images.githubusercontent.com/61687775/230095759-25180457-eb46-458a-9d6d-48d1690659d9.png)

**Comment by asif-startberry** [comment]
@AshDeeming 
Yes, we need this data to be accessed via property end point. Can you please give access to pFeatured in the extra fields of property end point.

**Comment by plittlewood-rpt** [comment]
Hi @asif-startberry this has now been enabled and you can request inclusion of this field using the `extrasField` query string parameter. The field name is pFeatured eg

`GET /properties?extrasField=pFeatured` or `GET /properties/XXX000000?extrasField=pFeatured`

Please allow up to 15 minutes before testing this as it can take a few minutes for configuration changes to synchronise around the API estate. Thanks

**Comment by asif-startberry** [comment]
Thanks for the update @plittlewood-rpt
