### ISSUE TITLE
Getting a 500 error when  posting to /properties/{propertyId}/certificates

### ISSUE THREAD

**Issue by matt-fixflo** [reapit/foundations#8852]
I am getting the below error when posting a new certificate to this endpoint.

`{"statusCode":500,"dateTime":"2023-04-06T09:23:03.7500203Z","description":"An unexpected error has been encountered when fulfilling this request. This incident has been logged and will be investigated. Please try again."}`

I will send the customer, request body and property id via sinfo.

**Specification**
- Project: Reapit.Services.Properties
- Try to reproduce issue locally. This may only be affecting a single databases so bear this in mind. Speak to Ash Deeming for detail from Zendesk

**Comment by RWilcox-Reapit** [comment]
Hi @matt-fixflo 

This issue has now been resolved. If your issue persists let me know. 

Thanks,
Ryan
