### ISSUE TITLE
Add CollNote properties in Tenancies

### ISSUE THREAD

**Issue by abrahamseni** [reapit/foundations#8853]
We need to access an extra field in the tenancies like this one in AC

![Clipboard - April 6, 2023 4_19 PM](https://user-images.githubusercontent.com/94949137/230334191-451a0edf-8202-4dcf-a615-6a00165db316.jpg)

![Clipboard - April 6, 2023 4_16 PM](https://user-images.githubusercontent.com/94949137/230334082-2a636f59-dddc-424c-9f94-c9fab893a490.jpg)

**Describe the solution you'd like**
Add properties CollNote in tenancies.

**Specification**
- Project: Reapit.Services.Tenancies
- Add new string property `feeNotes` to `TenancyModel` that exposes semi structured field ten.extra.tCollNote
- Add new string property `feeNotes` to `UpdateTenancyModel` and `CreateTenancyModel` that allows semi structured field  ten.extra.tCollNote to be written to. We should validate that the length of this field does not exceed 300 characters

**Comment by plittlewood-rpt** [comment]
To discuss with lettings team

**Comment by plittlewood-rpt** [comment]
Reached out to lettings team to understood intended use of this field so we can evaluate how best to expose and label this property

**Comment by MatthewGoddard** [comment]
@plittlewood-rpt This is used to records notes and and additional information about the fees that are being charged on a tenancy. In this example, we're going to be storing whether the fee collection is a 6-4-6 month schedule.

**Comment by plittlewood-rpt** [comment]
HI @MatthewGoddard thanks and I agree, my main concern is that it's not that obvious that it's meant to be a note relating to the fees so it's likely we've got customers out there using it for something different which will look confusing if we add a field called `feeNote` to the API (or similar)

**Comment by MatthewGoddard** [comment]
Thanks @plittlewood-rpt Is it Ross or Nicky you're waiting on?

**Comment by plittlewood-rpt** [comment]
I've had a response and we are in discussions :)

**Comment by MatthewGoddard** [comment]
I'll butt out then :)

**Comment by johnpenrose** [comment]
@plittlewood-rpt do you have an update on this?

As far as what values will be added to the field, we expect the app to set it to one of the following three values at any given time:

 - *Do not edit* - Not 646 Deal
 - *Do not edit* - 646 Deal
 - null / empty string

Hopefully this will inform your thinking on the validation rules to apply in the API.

If the field can be made non-editable/disabled in the core software, even better.

**Comment by HollyJoyPhillips** [comment]
Hi @johnpenrose this is with our Foundations team currently. As soon as we have more information or an update will update the ticket. Thanks.

**Comment by johnpenrose** [comment]
@HollyJoyPhillips if you could let me know by Wednesday mid-afternoon, I'd appreciate it as it is a hot topic on our daily update call/ Thanks

**Comment by HollyJoyPhillips** [comment]
Hi @johnpenrose this has been approved by the Foundations team and will be moved into our current sprint. Any updates as development progresses will be automatically sent. Thanks.

**Comment by johnpenrose** [comment]
@HollyJoyPhillips according to Ross, your current sprint ends on Friday 28th. Should we hope for this to be complete by then? Or have we got the wrong dates?

**Comment by HollyJoyPhillips** [comment]
Hi @johnpenrose that is correct, you can view our sprint dates here: https://github.com/reapit/foundations/projects?type=classic

I shouldn't see a reason for this not to be completed this sprint.
