### ISSUE TITLE
Invalid client error when trying to generate a token for Tatlers

### ISSUE THREAD

**Issue by adamboother** [reapit/foundations#8855]
**Describe the bug**
I am getting the following response when trying to generate the access token for Tatlers:

{
    "error": "invalid_client"
}

**To Reproduce**
1. Pass auth token and 'client_id' body param to https://connect.reapit.cloud/token

**Expected behaviour**
I expect an access token to be returned instead

**Comment by AshDeeming** [comment]
Hi @adamboother 
Please see the below section which should be of use; 
https://foundations-documentation.reapit.cloud/troubleshooting/authentication-issues#error-invalid_client
