### ISSUE TITLE
Julian Wadden

### ISSUE THREAD

**Issue by elizabethhamlin** [reapit/foundations#8864]
Hi

There seems to be an issue with the Julian Wadden offers table. When connecting to the data to load it into Power BI, the Lomond and Michael Jones datasets load but it gets stuck when trying to load the Julian Wadden data. 

We were going to migrate Julian Wadden into the Lomond build but this did not happen and it has been since this point that the Julian Wadden data seems to be an issue so not too sure if something has been turned off.

Please can you take a look asap.

THanks 

Lill

**Comment by plittlewood-rpt** [comment]
HI @elizabethhamlin sorry for the delay in responding to this. Can you let me know what you mean by "gets stuck"? I can see the Julian Wadden data in the analytics schema dataset and it all looks accurate so it sounds like this might be something to do with the report itself.

**Comment by plittlewood-rpt** [comment]
Hi @elizabethhamlin please can you come back to me on the above?

**Comment by elizabethhamlin** [comment]
Hi @plittlewood-rpt I'm so sorry for the delay. All is ok now. I am not too sure what happened and I haven't tried to upload to Power BI again but it just freezers on the JW data refreshing/loading. For now it all seems ok though.
Thanks 
Lill

**Comment by plittlewood-rpt** [comment]
Thanks for coming back to me. I'll close this for now, but please reach out if there's anything you need help with.
