### ISSUE TITLE
LETTINGS_NEGOTIATOR_ACTIVITY_SNAPSHOT

### ISSUE THREAD

**Issue by ErnstHavenga001** [reapit/foundations#8874]
The Analytics Schema refers to LETTINGS_NEGOTIATOR_ACTIVITY_SNAPSHOT, but it is however not available on Snowflake.

Could you please assist?
![LETTINGS_NEGOTIATOR_ACTIVITY_SNAPSHOT](https://user-images.githubusercontent.com/128135294/231539308-f278a45c-03b8-4787-9378-35c571f18b33.png)

**Comment by plittlewood-rpt** [comment]
Hi @ErnstHavenga001 this was resolved a while ago. You should just need to use the "Refresh Data Share" option in the Data Warehouse app. Can you try this and let me know if you then have access? Thanks

**Comment by MatthewGoddard** [comment]
Thanks @plittlewood-rpt 

@ErnstHavenga001 I've just refreshed the Data Share and I can now see the LETTINGS_NEGOTIATOR_ACTIVITY_SNAPSHOT. Let me know if you have any issues.
