### ISSUE TITLE
Lots of inactive properties in product feed despite being active in old reapitAPI feed. 

### ISSUE THREAD

**Issue by BYMIntegrations** [reapit/foundations#8876]
Please take a look at our FAQ's before submitting an issue, as your question may already be covered in the documentation https://foundations-documentation.reapit.cloud/faqs

**Summary**
Hello, our mutual customer Miller Metcalfe seem to have many inactive properties on the foundation's feed, however their old reapitAPI product feed is bringing back the same products as active.
BRY230169
BRY230170
Above is an example of the products from the foundations feeds that are inactive

The same products in their old product feed are active. 

Do we know the reason for the discrepancy?

**Detail and or supporting links and screenshots**

**Comment by AshDeeming** [comment]
Hi @BYMIntegrations 

Please note that the old webservice worked differently to the Platform API
Via the platform, using property statuses are recommended to retrieve the available properties

please see the swagger documentation, to show the payloads & their associated model: https://developers.reapit.cloud/swagger
