### ISSUE TITLE
Obtaining company name from localAuthorityCompanyId

### ISSUE THREAD

**Issue by propertyhive** [reapit/foundations#8877]
We're importing properties for a client and in the response I can see the field _localAuthorityCompanyId_. Is there anyway to get the company name from this ID without having to make an extra request for companies?

Our app doesn't have the '_read companies_' permission and updating permissions isn't going to be possible. Is there anyway to get this added to the property response, maybe as an extraField? Or maybe the client puts it in a custom field or similar?

Any help appreciated.
Steve

**Specification**
- Project: Reapit.Services.Properties
- This is a legitimate request and means we retain control of security better than if apps required access to all company data just to obtain this information.
- Add relevant entity to properties API (there is some work going on in the PlatformDatabase package to make this easier). Fetch properties as normal then make a secondary request to the data layer to fetch companies related to the paged result set before populating a new `localAuthorityCompanyName` string property in the `PropertyModel` - is a read only change as the write back requires the company id to be provided
- Use new database package from #8923 to add new entity

**Comment by HollyJoyPhillips** [comment]
Foundations approved. Moving to near term to allocate to a sprint.

**Comment by plittlewood-rpt** [comment]
Hi @propertyhive this has now been implemented. Many thanks
