### ISSUE TITLE
Testing agency cloud application before listing it

### ISSUE THREAD

**Issue by Ivana90GS** [reapit/foundations#8878]
We have developed an agency cloud application which has only been tested using the developer edition on one device where the app was running locally. We wanted to test this by multiple people, on multiple devices.
Is there a way to test the application among a group of testers, before listing the application on the AppMarket? I know there's an option to list the app 'privately' for a limited group of customers, but we don't have a Reapit customer outside of SBOX?

**Comment by AshDeeming** [comment]
Hi @Ivana90GS 

As you have mentioned, the developer edition of AgencyCloud, using sbox environment can be used to test & can be ran by multiple users 
https://foundations-documentation.reapit.cloud/faqs#testing

It may be that you wish to test this further via sbox or have a client who can be your beta?
