### ISSUE TITLE
UI Reapit Elements modification

### ISSUE THREAD

**Issue by Ivana90GS** [reapit/foundations#8879]
Is it possible to use the reapit element for input date but change the formatting to 'dd/mm/yyyy' instead of 'mm/dd/yyyy'?

**Comment by willmcvay** [comment]
@Ivana90GS The Date input is just a native HTML input so follows the standard spec https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date. It displays in the format dd/mm/yyyy in the docs see https://elements.reapit.cloud/?path=/docs/input--type-date so perhaps something going on your end, browser localisation or similar?
<img width="398" alt="Screenshot 2023-04-14 at 09 17 33" src="https://user-images.githubusercontent.com/4630495/231986455-50cb376f-05ff-4ceb-8aeb-853ad4c30fd2.png">

**Comment by willmcvay** [comment]
@Ivana90GS Can you confirm this is now resolved please? Will assume so and close if I don't hear back. Thanks

**Comment by Ivana90GS** [comment]
Yes, this issue has been resolved. Thank you.
