### ISSUE TITLE
Ideal Homes Website Integration

### ISSUE THREAD

**Issue by supportagentmedium** [reapit/foundations#8880]
Hi Team,

We are trying to integrate the feed for Ideal Homes, when click "New App" the next screen comes with "Create App" after that we are getting this error message" **Unable to register client app: Invalid scope requested: agencyCloud/images.read"**

Kindly do the needful.

![bug](https://user-images.githubusercontent.com/130666121/231758393-5ecf070c-54c9-4d83-b028-3eeb87ba8e22.jpeg)

**Comment by supportagentmedium** [comment]
> Invalid scope is being passed but not selected on the UI

Are we missing anything here, im not able to understand what exactly we should do here

**Comment by AshDeeming** [comment]
Hi @supportagentmedium 
An update has been released - please could you attempt to create the app now & the steps should now work as expected.
