### ISSUE TITLE
Webhooks not working for client CHC

### ISSUE THREAD

**Issue by bakaevd** [reapit/foundations#8888]
We have two apps (MovePal Connector, MovePal Sync) that we have installed with CHC. 

I added a webhook for "Contact created" and "Contact modified" topics for All Customers for with one app, and when it didn't work with the other app. 

When I modify or create a contact in CHC, the webhook is not called.  

I also tried configuring the webhook to fire for CHC only instead of All Customers - no difference.

I created another webhook for SBOX and it works fine.  I can modify a contact and the webhook fires.

What could be the issue?

**Comment by plittlewood-rpt** [comment]
Hi @bakaevd this should now be resolved. Please can you come back to me to confirm receipt of these events before I close the issue down? Thanks

**Comment by bakaevd** [comment]
Yes, the issue has been resolved. Thank you!
