### ISSUE TITLE
Unable to get Configuration companyTypes 500 Error

### ISSUE THREAD

**Issue by s-finny** [reapit/foundations#8889]
**Describe the bug**
This is only for Beresfords (BEF) endpoint of https://platform.reapit.cloud/configuration/types/?reapit-customer=BEF

With data of {"pageSize":100,"type":["companyTypes"]}

Get the response: {"statusCode":500,"dateTime":"2023-04-17T09:45:35.2633745Z","description":"An unexpected error has been encountered when fulfilling this request. This incident has been logged and will be investigated. Please try again."}

**To Reproduce**
Send the above data to the above endpoint

**Expected behaviour**
List of Compay Types returned

**Screenshots**
![image](https://user-images.githubusercontent.com/45770940/232452896-32a4a3ae-cfe8-4bf0-a874-5a402a487ad0.png)

Other companies are working fine.

**Comment by plittlewood-rpt** [comment]
Hi @s-finny I saw this one pop up and it should be resolved. Can you retry and let me know please? There was a misconfiguration in this customers database which I have resolved. Thanks

**Comment by s-finny** [comment]
@plittlewood-rpt Yes this has resolved the issue and I have now got the correct configuration types.

Thank you.
