### ISSUE TITLE
Data Mismatch at Data Warehouse vs Reapit UI

### ISSUE THREAD

**Issue by jessieip** [reapit/foundations#8891]
Our team found out the data is different at Reapit UI vs Weekly Report. 

Our weekly reports' data are from Reapit Datawarehouse - Snowflake which is built via your team.

Is it possible to set up a meeting with your team to run through the data warehouse set up? It will be good to know which dataset/reports are connected to Data Warehouse's tables.

Happy to set up a call and here's my contact - Jip@andrewsonline.co.uk

Many thanks,
Jessie Ip

**Comment by jessieip** [comment]
Hi there,

Can I get any response for this question?

Best,
Jessie

**Comment by HollyJoyPhillips** [comment]
This has been referred to your CSM to review. If applicable we will update the ticket.
