### ISSUE TITLE
Allow reading and writing to Total building floors attribute in property API

### ISSUE THREAD

**Issue by GoYuno** [reapit/foundations#8896]
These fields are available in AC so looking for the Foundations team to support adding this to the API.

Floor Level - handled in #9146 
Property Internal Floors - new ticket #9162
Total Building Floors - this ticket

**Background context**
AgencyCloud now has a "Total building floors" property on the attributes screen for a property. We should allow this field to be readable and writeable from the properties API where the configuration has been enabled for a customer's build

**Specification**
- Project: Reapit.Services.Properties
- It may be easier to do the three floor related tickets together as it's likely there will be an opportunity to share code
- Add `totalFloors` nullable int property to `PropertyModel` that exposes prp.extras.pTotalBldgFloors. This should appear underneath `internalFloors` in the model
- Add `totalFloors` nullable int property to `CreatePropertyModel` and `UpdatePropertyModel` that allows prp.extras.pTotalBldgFloors to be set. This should appear underneath `internalFloors` in the model
- Logic in the handler should check that the configuration for the property's department has the internal floors option enabled, which is governed by deps.extras.dTotalBldgFloors being set to true. The property's department will already be in scope in the handler. If it is not enabled, but totalFloorsis set to anything other than null in the command, a ValidationFailedException should be thrown with an appropriate message
- We should also validate that when not null, the value specified is >= 0

**Comment by GoYuno** [comment]
Well first client is Savills but is required for others to meet regulations across the UK.

**Comment by plittlewood-rpt** [comment]
Hi @GoYuno please advise if you have been able to review the above? For reference, we are adding support for the fairly new Floor Level int in our CRM as part of #9146

**Comment by plittlewood-rpt** [comment]
Separate tickets logged for each feature. This is now ready to review again
