### ISSUE TITLE
Confirm accuracy of total Tenant/Occupant count on Current and Arranging tenancies

### ISSUE THREAD

**Issue by GoYuno** [reapit/foundations#8897]
To perform a correct licensing and planning response, Yuno will been to be able count the amount of Tenants and Occupants for a specific Current and Arranging tenancy.

Please confirm you supply the correct information on your API  to allow us to count everyone listed via the tenancies end point? 
Tenants (Tenant) and Occupants (Tocname1)

**Comment by AshDeeming** [comment]
Hi @GoYuno 
The data provided through the API is accurate based on the data entered via AgencyCloud by the end user

**Comment by GoYuno** [comment]
thanks Ash

**Comment by GoYuno** [comment]
We cant see occupiers now?

**Comment by jamesgoyuno** [comment]
![image](https://github.com/reapit/foundations/assets/102355892/d45eb6b0-a45b-4cc3-8c2a-7291130ce068)

`{
  "id": "MKT230350",
  "created": "2023-08-30T11:05:47Z",
  "modified": "2023-08-30T11:06:51Z",
  "startDate": null,
  "endDate": null,
  "status": "arranging",
  "agentRole": "",
  "rent": 2000,
  "rentFrequency": "monthly",
  "endDateConfirmed": false,
  "isPeriodic": false,
  "rentInstalmentsFrequency": "monthly",
  "rentInstalmentsAmount": 2000,
  "rentInstalmentsStart": null,
  "meterReadingGas": null,
  "meterReadingGasLastRead": null,
  "meterReadingElectricity": null,
  "meterReadingElectricityLastRead": null,
  "meterReadingWater": null,
  "meterReadingWaterLastRead": null,
  "typeId": "PL",
  "negotiatorId": "ADV",
  "propertyId": "MKT232646",
  "applicantId": "BCK150378",
  "groupPaymentReference": null,
  "lettingFee": {
    "type": "percentage",
    "amount": 0,
    "frequency": ""
  },
  "managementFee": {
    "type": "percentage",
    "amount": 0,
    "frequency": "sameAsLettingFee"
  },
  "source": {
    "id": "SRC93",
    "type": "source"
  },
  "deposit": {
    "heldBy": "notSet",
    "sum": 0
  },
  "related": [
    {
      "id": "BCK15000484",
      "name": "Mr Charlesfthh Agnew",
      "title": "Mr",
      "forename": "Charlesfthh",
      "surname": "Agnew",
      "dateOfBirth": null,
      "type": "contact",
      "homePhone": "01632 960053",
      "workPhone": "020 7946 0053",
      "mobilePhone": "07087323212",
      "email": "cagnew690@rpsfiction.net",
      "paymentReference": null,
      "fromArchive": false,
      "primaryAddress": {
        "buildingName": "Flat 1",
        "buildingNumber": "",
        "line1": "28 Sanderson Road,",
        "line2": "Jesmond",
        "line3": "Newcastle",
        "line4": "Tyne and Wear",
        "postcode": "NE1 2DS",
        "countryId": "GB"
      },
      "additionalContactDetails": null
    }
  ],
  "fromArchive": false,
  "feeNotes": null,
  "legalStatusId": null,
  "renewalOptions": null,
  "_eTag": "\"FFA1218DF60EF0E798A44B909D6D9C15\"",
  "_links": {
    "self": {
      "href": "/tenancies/MKT230350"
    },
    "documents": {
      "href": "/documents/?associatedType=tenancy&associatedId=MKT230350"
    },
    "tasks": {
      "href": "/tasks/?tenancyId=MKT230350"
    },
    "checks": {
      "href": "/tenancies/MKT230350/checks"
    },
    "appointments": {
      "href": "/appointments/?attendeeType=tenancy&attendeeId=MKT230350"
    },
    "extensions": {
      "href": "/tenancies/MKT230350/extensions"
    },
    "type": {
      "href": "/configuration/tenancyTypes/PL"
    },
    "negotiator": {
      "href": "/negotiators/ADV"
    },
    "property": {
      "href": "/properties/MKT232646"
    },
    "applicant": {
      "href": "/applicants/BCK150378"
    },
    "source": {
      "href": "/sources/SRC93"
    }
  },
  "_embedded": null,
  "metadata": {}
}`
