### ISSUE TITLE
How can we identify properties which have changed status

### ISSUE THREAD

**Issue by danielalmeidaconnellsgroup** [reapit/foundations#8898]
We would like to use your APIs to identify properties which have fallen through so we can trigger activity based on that.

We would ideally like schedule a job to run every hour or once a day to call your endpoints to gather the details.

Could you advise on our options please?

**Comment by AshDeeming** [comment]
Hi @danielalmeidaconnellsgroup 

Please see the property status under the selling section of the Properties payload;
![image](https://user-images.githubusercontent.com/61687775/233135775-7fc00a84-eccc-4155-a5da-f5966365f851.png)
https://developers.reapit.cloud/swagger

Please also note the below which may be useful for more granular webhook filtering;
https://foundations-documentation.reapit.cloud/api/webhooks#building-event-filters

**Comment by plittlewood-rpt** [comment]
Hi @danielalmeidaconnellsgroup I've just responded to you via email. Let me know if anything's unclear
