### ISSUE TITLE
Tenancy Type correct end point and and data

### ISSUE THREAD

**Issue by GoYuno** [reapit/foundations#8899]
1 - Is this correct for endpoint Tenancy Type 

/tenancies
},
"type": {
"href": "/configuration/tenancyTypes/AZR"

2 - what are the standard codes used and what do each of the mean?

**Comment by plittlewood-rpt** [comment]
@GoYuno  please also make use of the `_links` collection provided in the response models as these will help you navigate between endpoints to lookup associated information. Thanks
