### ISSUE TITLE
Website/Emailing link problems 

### ISSUE THREAD

**Issue by imansfieldkeane** [reapit/foundations#8900]
Please see below issues we are having since moving to Reapit Foundations:

Avatar image
Ayomide
18 hours ago
Thank you for sending that information Sophie.

Hi Imogen,

I have been advised by a senior on the escalation team that this issue needs to be raised with the foundations team.

Please click on the link below to raise a ticket with them. Just copy and paste the information you sent on this ticket and they will get back to you as soon as possible.

Contact Foundations Team:

https://github.com/reapit/foundations/issues/new/choose

If you don’t have an account, please create one and then raise the ticket.

Helpful links

Request a feature (Requires login): [Sign in to GitHub](https://github.com/reapit/foundations/issues/new?assignees=&labels=feature-request%2C+needs-triage&template=feature_request.md&title=)

Raise an issue (Requires login): [Sign in to GitHub](https://github.com/reapit/foundations/issues/new?assignees=&labels=bug%2C+needs-triage&template=bug_report.md&title=)

Backlog board (Public): [Foundation Platform Backlog](https://github.com/reapit/foundations/projects/6)

Future Roadmap (Public): [Foundations Product Roadmap](https://github.com/reapit/foundations/milestones?direction=asc&sort=due_date&state=open)

All further detailed in the public readme section seen here: [Foundations ReadMe](https://github.com/reapit/foundations#readme)

Kind regards,
Ayo

Your request status changed to Be on it Shortly ..., 18 hours ago
Avatar image
sophie.wright@webdadi.com
18 hours ago
External Message - Please be cautious when opening links or attachments in email

Hi Ayo,

Below are the instructions that need to be changed for the property alerts:

Do I need to do anything to ensure my property alert emails work correctly once my import is setup?

Yes. Reapit should ensure your property alert emails are set up to link to your property listings on the website correctly. They will need to generate a URL to the property online in their email templates, so you need to ensure they have the following setup correctly to ensure they work.

To link to any property on the website, simply enter your website address followed by

/property/property.id

Plus S or L if the property is a sales or lettings listing

eg: https://protect-eu.mimecast.com/s/8OxxCBBMGiV7WVmczy1cQ?domain=estateagentwebsite.com<https://protect-eu.mimecast.com/s/K_dRCDkOKhB5YBms53tAl?domain=estateagentwebsite.com>

You can also pass on the following format to your Reapit Account Manager in relation to property alert emails: https://protect-eu.mimecast.com/s/o2wbCERgLfW34WGtpJqaL?domain=estateagentwebsite.com<https://protect-eu.mimecast.com/s/4ax-CG6kNUJ13JlhQb82n?domain=jt-homes.co.uk> == "L" ? "L" : "S"}

Please let me know if you have any further questions on this.

Best wishes,

Sophie

Your request status changed to Please let us know ..., 18 hours ago
Avatar image
Ayomide
18 hours ago
Hi Sophie ([sophie.wright@webdadi.com](https://reapit.atlassian.net/secure/ViewProfile.jspa?accountId=qm%3A3e48d5f4-2598-4bfd-af14-53f9e989bd3f%3A816e14f7-28b0-489b-8618-cb5365762cdf)),

Can you please confirm whether this link is the updated property link we need to add into Reapit?

https://protect-eu.mimecast.com/s/OK8qCG6kNUJ1ox9cppU9p?domain=estateagentwebsite.com%3Chttps://protect-eu.mimecast.com/s/IsbgCJ6nkU8qPGoSLe7_m?domain=jt-homes.co.uk > == "L" ? "L" : "S"}

Many thanks,
Ayo

Avatar image
Imogen Mansfield-Keane
19 hours ago
External Message - Please be cautious when opening links or attachments in email

Unfortunately whenever we try it we get this[image0.jpeg]

Imogen Mansfield-Keane
Associate Director
Company Administration
Featherstone Leigh

On 19 Apr 2023, at 14:07, Ayomide <jira@reapit.atlassian.net> wrote:

﻿

Your request status changed to Be on it Shortly ..., 19 hours ago
Your request status changed to Please let us know ..., 20 hours ago
Avatar image
Ayomide
20 hours ago
Hi Imogen,

I clicked on this link - https://protect-eu.mimecast.com/s/idaRC4xrnCJB892UODUZB?domain=featherstoneleigh.co.uk%3Chttps://protect-eu.mimecast.com/s/ZeQaC5yvoI0ZlpPSOcvIT?domain=featherstoneleigh.co.uk >

it took me to this page below:

Pleaser confirm if this is the link you forwarded? If not, please forward the link as I don’t believe the forwarded email came through.

Many thanks,
Ayo

Your request status changed to We're on it ..., 20 hours ago
Your request status changed to Be on it Shortly ..., a day ago
Avatar image
Imogen Mansfield-Keane
a day ago
External Message - Please be cautious when opening links or attachments in email

Good afternoon,

There still seems to be a problem with the links, I will forward you an email if you can please click on the link and see what it takes you too but not our website?

Kind regards

Imogen

Imogen Mansfield-Keane
Associate Director
Company Administration

[resizedlogo]

Tel: 020 8332 2662
https://protect-eu.mimecast.com/s/idaRC4xrnCJB892UODUZB?domain=featherstoneleigh.co.uk<https://protect-eu.mimecast.com/s/ZeQaC5yvoI0ZlpPSOcvIT?domain=featherstoneleigh.co.uk>

Your request status changed to Please let us know ..., 2 days ago
Avatar image
Ayomide
2 days ago
Hi Imogen,

I have added the new Property url link that you provided. Please log out and log back into Reapit and let me know if this has worked.

Many thanks,
Ayo

Avatar image
Imogen Mansfield-Keane
2 days ago
External Message - Please be cautious when opening links or attachments in email

This is what I have sent to our account manager:

Do I need to do anything to ensure my property alert emails work correctly once my import is setup?
Yes. Reapit should ensure your property alert emails are set up to link to your property listings on the website correctly. They will need to generate a URL to the property online in their email templates, so you need to ensure they have the following setup correctly to ensure they work.
To link to any property on the website, simply enter your website address followed by
/property/property.id
Plus S or L if the property is a sales or lettings listing
eg: https://protect-eu.mimecast.com/s/0y12CDkOKhB5Q2ZHWirWq?domain=estateagentwebsite.com<https://protect-eu.mimecast.com/s/ruJDCERgLfW3KrjIwJLjT?domain=estateagentwebsite.com>
You can also pass on the following format to your Reapit Account Manager in relation to property alert emails: https://protect-eu.mimecast.com/s/OK8qCG6kNUJ1ox9cppU9p?domain=estateagentwebsite.com<https://protect-eu.mimecast.com/s/IsbgCJ6nkU8qPGoSLe7_m?domain=jt-homes.co.uk> == "L" ? "L" : "S"}

Imogen Mansfield-Keane
Associate Director
Company Administration

[resizedlogo]

Tel: 020 8332 2662
https://protect-eu.mimecast.com/s/3pUsCKrolUq20gkTpSGSa?domain=featherstoneleigh.co.uk<https://protect-eu.mimecast.com/s/mlHiCL9pmUPR5x2HgBsu6?domain=featherstoneleigh.co.uk>

Your request status changed to Be on it Shortly ..., 2 days ago
Your request status changed to Please let us know ..., 2 days ago
Avatar image
Ayomide
2 days ago
Hi Imogen,

This is the old property URL link we have for the company:

[https://featherstoneleigh.co.uk/property/RPS_FEL-

{Property.Code} {LoggedNegotiator.Config.CurrentAppMode|https://featherstoneleigh.co.uk/property/RPS_FEL-%7BProperty.Code%7D%7BLoggedNegotiator.Config.CurrentAppMode] == "S" ? "S" : "L"}
Can you please provide the new property link we should have please?

Many thanks,
Ayo

Avatar image
Ayomide
2 days ago
Hi Imogen Mansfield-Keane

Your ticket has now been assigned to me and I’ll be in touch with an update or resolution very soon.

If you have any questions or comments in the meantime please feel free to reply to this email, or comment on the ticket in our Customer Portal.

Kind regards

Ayomide

**Comment by plittlewood-rpt** [comment]
Hi @imansfieldkeane I have had a look at the internal support ticket and have the following feedback:

- Your website providers are the ones who govern the properties that are displayed on your website. It's likely they have are using the wrong filters when calling our API
- Your website providers control how the links in your email templates work. They need to make sure that the existing link style still continues to function, otherwise any emails you've previously sent out will also be broken, not just new ones.

I would advise you to ask them if they can comment on this issue with any problems they need help with, and we can advise accordingly. They will need to give us specific examples and details so we can understand the issues they are experiencing and allow us to provide the best support

**Comment by ElliottRowland** [comment]
Hi @plittlewood-rpt 

The URL/property alert issue has been fixed.

In regards to properties missing from the site. We have applied the following codes:

Accounts - HEA
East Sheen - EAL, EAS
Richmond Lettings - RIL
Twickenham - TWL,TWS
West Kensington - WKL,WKS
Kew - KEW
Teddington - TEL,TES
Battersea - BAL,BAS
Chiswick - CHL,CHS
Richmond Head Office - HEO
Richmond Sales - RIS

Reapit Customer - FEL
Deaprtment - G
SaleStatus - forSale,underOffer,exchanged
RentalStatus - toLet,underOffer,sold

The codes match (or have an equivalent to) what was setup previously. We also matched the same statuses which we were previously downloading from the REST API.

In regards to missing properties, I can't see why this would be the case. We seem to have all the offices setup correctly, so unless FL are allocating properties to offices outside of this list they should download. For example, we have no properties for the Twickenham Lettings branch, but this code is correct so should download if properties are being allocated to this branch (could you perhaps check properties are being allocated?)

In regards to properties displaying online which shouldn't be. We matched the statuses to pull the same properties as we were previously. However, the Foundations statuses are slightly different so don't match exactly.  THe site previously showed sold properties which we want to continue, but is there perhaps a time limit which used to exist on the old REST api which doesn't exist now? Clearly it is pulling more exchanged properties than it used to.

Advise here would be useful, we can't see an obvious reason why properties would be missing if allocated properly, and can only assume the statuses are somehow different to cause more properties to display on line than used to.

If you need anything further from me please let me know.

Elliott

**Comment by plittlewood-rpt** [comment]
To anyone tracking this ticket, conversations are continuing by email
