### ISSUE TITLE
Semi-structured field Request 

### ISSUE THREAD

**Issue by MarcinuB** [reapit/foundations#8912]
Hi Team.

Could you enable access to the **pSituation** field for the customer **Rettie** (RET).  
It is required by them for the digital brochures. 

Thank you kindly
Marcin

**Comment by plittlewood-rpt** [comment]
@MarcinuB this has now been enabled. Please allow 15 mins or so for the new configuration to sync round the service estate. Thanks

**Comment by plittlewood-rpt** [comment]
Hi @MarcinuB - not sure if there's some crossed wires, this ticket isn't to do with the property URL?

**Comment by MarcinuB** [comment]
@plittlewood-rpt  - apologies for that. There is some crossed wire in my head today. I need some 😴.

Thank you
