### ISSUE TITLE
"officeIds" not having proper validation in appointment endpoint

### ISSUE THREAD

**Issue by ss-dimasm** [reapit/foundations#8916]
**Describe the bug**
When I update one of appointment record via API, I could pass random office Id to the appointment record

**To Reproduce**
Steps to reproduce the behaviour eg:
1. go to dev portal swagger
2. navigate to GET single office endpoint swagger, find the office with ID "`LTY`"
3. it should return Not Found Exception
4. navigate to PATCH single appointment swagger, and fill the body with the attached payload
5. See the unexpected behavior (got 204)

**Expected behaviour**
instead returning 204, it should return the Bad Request exception because the "`LTY`" office doesn't exist

**Additional context**
Sandbox data

**patch appointment payload**
```json
{
  "officeIds": [
    "OXF",
    "LTY"
  ]
}
```
**Specification**
Prerequisite to this is #8923 
- Project: Reapit.Services.Appointments
- Once aforementioned ticket is complete, we should look at add validations to this service that check the ids provided exist in the system. This includes at least officeIds and negotiatorIds but should also consider propertyId, applicantId etc. Build a smart reusable way to do this.

**Comment by plittlewood-rpt** [comment]
Same track as #8210

**Comment by plittlewood-rpt** [comment]
Hi @ss-dimasm this is something we are already aware of in other services and are actively looking to address. There's some prerequisite work that needs to be completed first, then we'll look at picking this up. Thanks
