### ISSUE TITLE
Source Of Truth Data?

### ISSUE THREAD

**Issue by dogzy** [reapit/foundations#8918]
**Summary**

Using WordPress Property Hive I am importing properties, however depending on the time of day the data appears to change drastically. Is there a way I can get a definitive export of what data should be showing at my endpoint when querying it? My client "Seddons" have requested this however been told to raise it as a github issue... So here we are :)

Can you please advise?

Thanks,

**Detail and or supporting links and screenshots**

**Comment by AshDeeming** [comment]
Hi @dogzy 
The payload from the 3rd party app may differ however the standard payloads for each endpoint can be found via the swagger docs, link below;
https://developers.reapit.cloud/swagger
