### ISSUE TITLE
WebHooks enabled for another client

### ISSUE THREAD

**Issue by NicolaTPJ** [reapit/foundations#8919]
Please take a look at our FAQ's before submitting an issue, as your question may already be covered in the documentation https://foundations-documentation.reapit.cloud/faqs

**Summary**
Nova Haus London have reported that their website feed is not updating. Can you confirm if their WebHooks are enabled within Foundations?

Going forward, is this something that a client can turn on when I initially ask them to setup a feed to us or do I need to raise an issue here each time?

novahauslondon.co.uk

**Detail and or supporting links and screenshots**

**Comment by plittlewood-rpt** [comment]
HI @NicolaTPJ you should not need to request this no as they should already be setup. I've logged #8927 to look into what might be going wrong with an internal process here so we can plug the gap. I'll get this customer sorted out shortly for you. Thanks

**Comment by plittlewood-rpt** [comment]
HI @NicolaTPJ I've just checked and we already have webhooks configured for this customer and everything seems to be working as I'd expect. Can you confirm you've got a subscription set up?
