### ISSUE TITLE
Add core implementation of entities to DB package

### ISSUE THREAD

**Issue by RWilcox-Reapit** [reapit/foundations#8923]
**Background context**
There are a few circumstances which require one service to know about data in another service. 
The most performant approach is to call the DB directly for a lightweight representation but this code is duplicated across our services.
Entity representations could be added to the db package to prevent code duplication

**Specification**
Add a lightweight representation of platform entities to the db package

**Comment by plittlewood-rpt** [comment]
@RWilcox-Reapit do you think we should have a 'full' and 'lightweight' representation of each resource? Just a thought I had earlier
