### ISSUE TITLE
Push to journal

### ISSUE THREAD

**Issue by Speedway1** [reapit/foundations#8932]
When returning data to Reapit for two clients, this is not working. A message is sent to an applicant and that action is not being recorded in the journal.
**To Reproduce**
Click on Send SMS
Write message
Send - 
Message is delivered to handset
Not recorded in the client's journal

**Expected behaviour**
The action above should be recorded in the journal 

**Screenshots**
We will Send this separately

**Comment by plittlewood-rpt** [comment]
Hi @Speedway1 this sounds like an issue being reported for AgencyCloud rather than the API. You cannot send an SMS message via our API. Can you confirm if it's an AgencyCloud support request? If so this would need raising with our main helpdesk. Thanks

**Comment by Speedway1** [comment]
Hi, so the issue isn't about being able to send a message, it's about recording the message sent, back in to the journal.
Although this is a screenshot of the Activity Panel, the screenshot shows that it has recorded a message being sent. This is not happening for the clients affected.  Thank
<img width="511" alt="Screenshot 2023-04-26 at 13 24 29" src="https://user-images.githubusercontent.com/100301611/234560805-89dab172-6e83-4443-ad47-482403572cd7.png">

**Comment by plittlewood-rpt** [comment]
Hi @Speedway1 is the issue therefore that you're making a call to POST /journalEntries and the data isn't being displayed in AgencyCloud?

**Comment by Speedway1** [comment]
Yes, that is correct. For data protection reasons, we have forwarded the relevant information by email.

**Comment by Speedway1** [comment]
Closing this as the issue appears to be resolved.
