### ISSUE TITLE
Lettings missing from feed

### ISSUE THREAD

**Issue by tpjsupport** [reapit/foundations#8934]
Hi Pete, Roseberry Newhouse, branches ING, NOR, STO, YAR don't appear to have any lettings in the foundations feed despite having live listings, are you able to check what's happening with them possibly? Many thanks

**Comment by AshDeeming** [comment]
Hi @tpjsupport 
Please could you confirm the relevant app name is 'Property Feeder'?

**Comment by tpjsupport** [comment]
Hi Ash, it is indeed. We're getting sales instructions no bother just not the lettings (unless they're listed under a different id)

**Comment by AshDeeming** [comment]
Thanks @tpjsupport 
Can I just check that you are using the marketingMode to segment the possible sellingStatus & lettingStatus as show below; (https://developers.reapit.cloud/swagger)
![image](https://user-images.githubusercontent.com/61687775/234589930-55cfc333-269b-4444-a8ad-a3e2d996a9f5.png)

**Comment by tpjsupport** [comment]
Hi Sam, it will be set up to pull all the correct sales and lettings status's, we've countless feeds set up on Foundations and no other client set up has experienced this issue afaik. Tx

**Comment by tpjsupport** [comment]
Hi Ash, any update on this?

**Comment by plittlewood-rpt** [comment]
Hi @tpjsupport it doesn't look like these branches have any available lettings properties. If you think certain properties are missing please can you provide more information (addresses or references). All the available lettings stock for this agent appears to be assigned to office YRL. Please can you review again at your end and let me know if there is indeed a problem. Thanks

**Comment by tpjsupport** [comment]
Hi Pete, unfortunately nobody informed us there was a seperate branch for lettings, I've tried to set up a new feed for bid YRL under office RSB and no properties are being fetched from yourselves. Thx.

**Comment by plittlewood-rpt** [comment]
hI @tpjsupport can you let me know what request you are making? There's definitely properties associated to that branch id (eg YRL220094)

**Comment by plittlewood-rpt** [comment]
HI @tpjsupport webhooks are running for this customer yes. You can see who has your app installed in the developer portal (if you are able to request data on their behalf then they have the app installed as you'd get blocked from making calls for their data if they didn't). Thanks

**Comment by plittlewood-rpt** [comment]
@tpjsupport please can you confirm if you need any further assistance? Thanks
