### ISSUE TITLE
Add the ability to create/view Draft & Final Reports

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#8939]
**Summary:** For some customers, a property inspection appt with a tenancy, they can add a draft and final report document which is stored against the property/tenancy/letters section in AC. 

**Task**: 
Add the ability to read and write (when configured) the draft and final report document. 

![image](https://user-images.githubusercontent.com/52408607/234547560-61b25bd2-d0d9-4ad3-9fff-43d1b0d4e0b8.png)

**Specification**
- Project: Reapit.Services.Configuration
- Update the handler that exposes the document type ids to also check whether the "Show advanced PI buttons" option is enabled in System Config -> Diary. If it is, we should append the Final and Draft report document type ids to the list that is returned from this endpoint. This allows developers to understand what typeId to post to the documents API

- Project: Reapit.Services.Appointments
- Add `documents` object to the various appointment models:

```
"documents": {
     "draftInspectionReportId": "ABC1233456", 
     "finalInspectionReportId": "ABC1233457", 
}
```

- For the read side, expose `diary.extra.yDraftPIRptCode` and `diary.extra.yFinalPIRptCode` for the draft and final report codes respectively
- For the write side, set the fields above and additionally a timestamp of when the request was handled:
`diary.extra.yDraftPIRptDateTime` and `diary.extra.yFinalPIRptDateTime` 
- It should only be possible to set these fields when the "Show advanced PI options" setting is enabled
- When the reports are added/cleared/updated, emit journal entries that are associated to the tenancy in the following format:
typeId: "PN"
text for draft report added: Draft property inspection report uploaded
text for draft report deleted:  Draft property inspection report deleted
text for final report added: Final property inspection report uploaded
text for final report deleted:  Final property inspection report deleted
- When the new properties are set, add a corresponding link to the document get by id endpoint in the _links collection for each respective item

- Project: Reapit.Services.Documents
- Check that documents with type of PN are supported. This is where the documents will actually be uploaded to
- It should only be possible to upload documents of this type if the "Show advanced PI options" setting is enabled

**Comment by neilpellowe** [comment]
Hi @HollyJoyPhillips  - Happy to move this one forward if we can add to the relevant backlog for review and prioritisation.

**Comment by HollyJoyPhillips** [comment]
Additional information provided by the developer: 

- Primary objective is to 'mark complete' the inspection appointment (be it a single appointment, or a recurring appointment), so that it triggers the next inspection due date field to update on a recurring. This is the most important requirement. 

- Reports that look up inspections due should then show those inspections as completed/when they were completed and the correct Next Due according to Frequency 

- Secondary objective would be to store a PDF or a URL against the 'Final Report' (again on both a single or recurring appointment), resulting in the 'tick' on Final Report and hopefully triggering the above also, if not a separate endpoint

**Comment by plittlewood-rpt** [comment]
Spec'd for final point above. I don't think the top two points are anything to do with this.

**Comment by SteveRad** [comment]
What is the update with this please?
