### ISSUE TITLE
Ability to get Guarantor information to an application

### ISSUE THREAD

**Issue by TheLettingsHub** [reapit/foundations#8940]
Currently we are able to pull the tenant information to our application so that the tenant can be referenced however we are unable to get the guarantor information stored within Reapit and this causes an issue. 
we need a get guarantor details to be added in the same way that get tenant details exists so that we can use the data within our application and the user does not have to reenter it again.

**Comment by HollyJoyPhillips** [comment]
It is now possible to retrieve guarantor information via the Platform, please see https://foundations-documentation.reapit.cloud/whats-new#id-31-12-23
