### ISSUE TITLE
Sync Legionella certificates from Fixflo <> Reapit 

### ISSUE THREAD

**Issue by katedeedman** [reapit/foundations#8943]
Hello Reapit team,

We have a mutual client (can share name separately) that has requested we sync over Legionella certificates from Fixflo into Reapit. We already do this for EPC, Gas Safety and Electrical Safety.  Do you have the endpoint for us to do that?

Thank you!

-Kate
(PM at Fixflo)

**Comment by plittlewood-rpt** [comment]
HI @katedeedman presumably you are using GET/POST /properties/{id}/certificates for this purpose? You should be able to use the same endpoint to read/write the legionella certificates too as it uses the same mechanism. The certificates just have a different typeId which you can lookup from GET /configuration/certificateTypes. If I've misunderstood your request though, please can you send some more detail over to sinfo@reapitfoundations.zendesk.com with this issue reference (8943) in the email subject? Thanks

**Comment by katedeedman** [comment]
That's great! Thanks, Pete.

**Comment by plittlewood-rpt** [comment]
No worries - are you happy for this to be closed based on the above?
