### ISSUE TITLE
Applicant Data Issue - Incorrect RentTo Value

### ISSUE THREAD

**Issue by IICHewlett** [reapit/foundations#8954]
**Describe the bug**
When we receive an applicant record the Renting.RentTo property value is incorrect.

**To Reproduce**
1. Request specific applicant record. (Applicant ID and sensitive info emailed to sinfo@)

**Expected behaviour**
This value is returned as per the customers screenshot from RPS (Included in email)

**Specification**
- Project: Reapit.Services.Applicants
- This likely relates to work we did a few months ago to read the default rent period setting from configuration when fetching applicant data. It's likely there is either an edge case with the functionality that was not considered at the time, or the configuration setting is not coming back/being cached correctly for the customer concerned. We should replicate this using the example provided (speak to Pete or Ash for sensitive info) and resolve as necessary

**Comment by AshDeeming** [comment]
Thanks @IICHewlett 
Information received - see 723

**Comment by AshDeeming** [comment]
Apologies for any confusion @IICHewlett  - the number if for internal reference

**Comment by HollyJoyPhillips** [comment]
Hi @stebrough It has been allocated to our next sprint (starting 02/05 because of the bank holiday). Once the team have investigated, we'll update the ticket.

**Comment by RWilcox-Reapit** [comment]
Hi @stebrough 

This has now been resolved. Thanks for flagging it.

Ryan

**Comment by stebrough** [comment]
@RWilcox-Reapit thanks for letting me know. Can I ask for an explanation of the issue? Also has this affected all Applicant records? Or just this one specifically?

**Comment by RWilcox-Reapit** [comment]
Hi @stebrough there is a configuration setting which returns weekly rent values for applicants when one is not specifically set. 
For 99% of customers this is set to true however in this instance it was not set so the default should have been monthly.

This would only have effected this customer for applicants which had not selected a rent frequency.

Thanks
