### ISSUE TITLE
Ability to see which set of property requirements an applicant has via the API

### ISSUE THREAD

**Issue by AdamHall12** [reapit/foundations#8955]
**Is your feature request related to a problem? Please describe.**
As far as I'm aware there is no way to tell what set of requirements an applicant has. This causes problems when updating an applicant as the api call will return an error if the field you are updating is not within the selected front end requirement set.

**Describe the solution you'd like**
A field in the get applicant JSON with the applicants requirement set type

**Describe alternatives you've considered**
We are building a mechanism to deal with errors but would rather the error did not occur in the first place.

**Additional context**
This is what I mean by set of requirements: 
![image](https://user-images.githubusercontent.com/102241930/234851640-40e81ea5-0919-441b-a2bf-0f66a0e9a702.png)

**Comment by AshDeeming** [comment]
Hi @AdamHall12 
Please confirm you are using the Departments endpoint to check which departments an AgencyCloud client has setup.

**Comment by AdamHall12** [comment]
Hi @AshDeeming, thank you I hadn't noticed the departments endpoint! All sorted now.
