### ISSUE TITLE
Possible set up of Sandbox feed account with Auction Properties. 

### ISSUE THREAD

**Issue by ynwaJon** [reapit/foundations#8956]
Please take a look at our FAQ's before submitting an issue, as your question may already be covered in the documentation https://foundations-documentation.reapit.cloud/faqs

You are in the process of onboarding one of our clients and I want to make sure something works before the live feed change takes place. 

The client in question has Residential, Auction and Commercial properties. 

I've emailed your team and he's suggested that you might be able to set up a Sandbox account so i can make sure that some of our Tech we've got built on top, of the current feed supplied by another CRM, will still work on the Reapit Foundations one. 

I could do with a feed that has Residential, Commercial and Auction properties.  

Is this possible?

**Comment by AshDeeming** [comment]
Hi @ynwaJon 
Please confirm you are using the Departments endpoint to check which of these are setup (per client) & their associated attributes?
