### ISSUE TITLE
Add AdditionalContactDetails collection to Related collaction in VendorModel and LandlordModel

### ISSUE THREAD

**Issue by paganvarg** [reapit/foundations#8962]
**Is your feature request related to a problem? Please describe.**
When I read all contact related to vendor/landlord I can only see their predefined contacts/email (work, home, mobile, email) anything that's not any of those contacts is not available and I have to make additional call to get ContactModel to read AdditionalContactDetails

**Describe the solution you'd like**
AdditionalContactDetails collection is available on RelatedModel inside VendorModel, LandlordModel

**Describe alternatives you've considered**
The alternative is to call contact endpoint to retrieve AdditionalContactDetails collection which mean significant increase in number of calls made by our software to Reapit

**Specification**
- Add `additionalContactDetails` array which exposes non-standard contact details in the contact model in the following services:
  - Reapit.Services.Applicants
  - Reapit.Services.Landlords
  - Reapit.Services.Tenancies
  - Reapit.Services.Offers
  - Reapit.Services.Vendors

- This is read only as the details are always updated via the contacts API. Lift the code for generating the additional contact details collection from this service

**Comment by rochellelevy** [comment]
Hi @plittlewood-rpt we are reluctant to add additional calls given we already make a lot of calls already. The reason why we need this added is because users often change the contact fields (e.g. changing from Mobile to Mobile 2). For DiarySync we need these details to sync to an appointment. 

Would it be possible for this to be added to next sprint? or if you have any other suggestions for us that would prevent us from making additional calls, please let us know.

**Comment by HollyJoyPhillips** [comment]
This has been referred to our Foundations team for further validation. I will update the ticket with more information where possible.

**Comment by HollyJoyPhillips** [comment]
This has been approved and will be picked up in our next refinement session for a specification to be added.

**Comment by rochellelevy** [comment]
Hi @HollyJoyPhillips thanks so much! when is the next refinement session?

**Comment by HollyJoyPhillips** [comment]
Hi @rochellelevy our next session in on Thursday 18th. Thanks.

**Comment by rochellelevy** [comment]
@HollyJoyPhillips and @plittlewood-rpt this feature is rather urgent for us. So, we may have to go ahead and implement our first solution which involves additional calls which you have asked us to avoid. What are your thoughts?

**Comment by HollyJoyPhillips** [comment]
Hi @rochellelevy, we won't be able to look at this feature request until the next sprint which starts 29th. I'm not sure who had previously advised avoiding the additional calls but it's not an issue for us just something that can be avoided for you and your use case, once this feature has been developed.

**Comment by rochellelevy** [comment]
@HollyJoyPhillips it was @plittlewood-rpt thats why I tagged him in a previous message. Unless I misunderstood

**Comment by plittlewood-rpt** [comment]
HI @rochellelevy I think there's been a miscommunication somewhere so please accept my apologies. Can you let me know which ticket I responded to so I can try and clear up any confusion?

**Comment by rochellelevy** [comment]
Hi @plittlewood-rpt its related to an email you sent on Feb 9th of this year. The changes we need to make are for DiarySync
