### ISSUE TITLE
SQL syntax error when searching name Yeliz in applicants 

### ISSUE THREAD

**Issue by yeliz-tacel** [reapit/foundations#8973]
**Describe the bug**
I am getting a syntax error when I search for my name in Applicants. Looks like database query issue. 

**To Reproduce**
Steps to reproduce the behaviour eg:
1. Go to 'reapit uat.'
2. Click on 'applicants'
3.  Search 'Yeliz'
4. Observe issue: Syntax error

Report: 
The report states the following: 

The following exception was encountered at 14:21:24 on 02/05/2023
 
Company: Savills
Office: MySavills
User: Yeliz Tacel
AgencyCloud Version: 12.159.3
 
Message: SELECT app.*, cnt.* FROM app INNER JOIN lookup on lookup.typeFrom = 'app' AND lookup.typeTo = 'cnt' AND app.code = lookup.codeFrom AND lookup.synchDel = 0 INNER JOIN cnt ON lookup.codeTo = cnt.cntCode INNER JOIN (SELECT cnt.cntCode, MATCH(cntCmpName,cntTitle,cntInitials,cntSurname,cntPhone) AGAINST('YELIZ*' IN BOOLEAN MODE) + 100 as sort  FROM cnt WHERE cnt.synchDel = 0 AND cntSurname <> 'Erased' AND (cntCmpName != '' OR cntOffCode NOT IN ('ALG','ATA','AUL','AUN','AUS','BAH','BRB','BRC','BRU','CMI','COG','CRO','CYP','CZR','DBA','FIN','GEN','GIB','GRC','GRE','HOD','IBZ','LAB','LAK','LCP','ISV','LAX','MAD','MLG','MAO','MAB','MAU','MIA','MON','MNT','MRZ','NYO','OMA','PAR','PDG','PDL','LBN','PRO','PUG','ROE','SAN','SDA','SIR','SOT','SOA','DOR','SPA','SAE','SLU','SPL','TUR','TUC','UMB','VEN','WAG','ZAS')) AND MATCH(cntCmpName,cntTitle,cntInitials,cntSurname,cntPhone) AGAINST('YELIZ*' IN BOOLEAN MODE) UNION SELECT cnt.cntCode, MATCH(cntHseName,cntHseNo,cntAddress1,cntAddress2,cntPostcode) AGAINST('YELIZ*' IN BOOLEAN MODE) as sort  FROM cnt WHERE cnt.synchDel = 0 AND cntSurname <> 'Erased' AND (cntCmpName != '' OR cntOffCode NOT IN ('ALG','ATA','AUL','AUN','AUS','BAH','BRB','BRC','BRU','CMI','COG','CRO','CYP','CZR','DBA','FIN','GEN','GIB','GRC','GRE','HOD','IBZ','LAB','LAK','LCP','ISV','LAX','MAD','MLG','MAO','MAB','MAU','MIA','MON','MNT','MRZ','NYO','OMA','PAR','PDG','PDL','LBN','PRO','PUG','ROE','SAN','SDA','SIR','SOT','SOA','DOR','SPA','SAE','SLU','SPL','TUR','TUC','UMB','VEN','WAG','ZAS')) AND MATCH(cntHseName,cntHseNo,cntAddress1,cntAddress2,cntPostcode) AGAINST('YELIZ*' IN BOOLEAN MODE)) cnts ON cnts.cntCode = cnt.cntCode WHERE app.synchDel = 0  AND app.type = 'S' AND APP.offCode NOT IN ('ALG','ATA','AUL','AUN','AUS','BAH','BRB','BRC','BRU','CAN','CDA','CMI','CLT','COG','CUL','CRO','CYP','CZR','DBA','ELT','FIN','GEN','GIB','GRC','GRE','VAR','HOD','IBZ','LAB','LAK','LCP','ISV','LAX','MAD','MLG','MAO','MAB','SLO','MAU','MER','MIA','MNO','MON','MNT','MRZ','NYO','NIC','OMA','OLT','PAR','PDG','PDL','LBN','PRO','PUG','RSR','ROE','STZ','SAN','SDA','SIR','SOT','SOA','DOR','SPA','SAE','SLU','JCP','SKN','SPL','TUR','TUC','UMB','VBE','VEN','WAG','ZAS') ORDER BY sort DESC LIMIT 120  AND (app.depCode = 'G')
 
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AND (app.depCode = 'G')' at line 1
 
Stack Trace
   at RPS.UI.MainWindow.<>c__DisplayClass65_0.<OnDbCommandError>b__0(Object <p0>)
   at RPS.App.InitializeAndRun(Dictionary`2 initialisationInfo)
   at RPS.EntryPoint..ctor(String[] applicationArguments, Dictionary`2 initialisationInfo)
 
 
Error Log Entry
02/05/2023 14:21:24    v:12.159.3    o:MYS    n:YZTC    u:SOLAR\yeliz.tacel    m:PDVMXA7SGA027    w:Windows Server 2016 Datacenter    trace:at RPS.UI.MainWindow.<>c__DisplayClass65_0.<OnDbCommandError>b__0(Object <p0>)    message:SELECT app.*, cnt.* FROM app INNER JOIN lookup on lookup.typeFrom = 'app' AND lookup.typeTo = 'cnt' AND app.code = lookup.codeFrom AND lookup.synchDel = 0 INNER JOIN cnt ON lookup.codeTo = cnt.cntCode INNER JOIN (SELECT cnt.cntCode, MATCH(cntCmpName,cntTitle,cntInitials,cntSurname,cntPhone) AGAINST('YELIZ*' IN BOOLEAN MODE) + 100 as sort  FROM cnt WHERE cnt.synchDel = 0 AND cntSurname <> 'Erased' AND (cntCmpName != '' OR cntOffCode NOT IN ('ALG','ATA','AUL','AUN','AUS','BAH','BRB','BRC','BRU','CMI','COG','CRO','CYP','CZR','DBA','FIN','GEN','GIB','GRC','GRE','HOD','IBZ','LAB','LAK','LCP','ISV','LAX','MAD','MLG','MAO','MAB','MAU','MIA','MON','MNT','MRZ','NYO','OMA','PAR','PDG','PDL','LBN','PRO','PUG','ROE','SAN','SDA','SIR','SOT','SOA','DOR','SPA','SAE','SLU','SPL','TUR','TUC','UMB','VEN','WAG','ZAS')) AND MATCH(cntCmpName,cntTitle,cntInitials,cntSurname,cntPhone) AGAINST('YELIZ*' IN BOOLEAN MODE) UNION SELECT cnt.cntCode, MATCH(cntHseName,cntHseNo,cntAddress1,cntAddress2,cntPostcode) AGAINST('YELIZ*' IN BOOLEAN MODE) as sort  FROM cnt WHERE cnt.synchDel = 0 AND cntSurname <> 'Erased' AND (cntCmpName != '' OR cntOffCode NOT IN ('ALG','ATA','AUL','AUN','AUS','BAH','BRB','BRC','BRU','CMI','COG','CRO','CYP','CZR','DBA','FIN','GEN','GIB','GRC','GRE','HOD','IBZ','LAB','LAK','LCP','ISV','LAX','MAD','MLG','MAO','MAB','MAU','MIA','MON','MNT','MRZ','NYO','OMA','PAR','PDG','PDL','LBN','PRO','PUG','ROE','SAN','SDA','SIR','SOT','SOA','DOR','SPA','SAE','SLU','SPL','TUR','TUC','UMB','VEN','WAG','ZAS')) AND MATCH(cntHseName,cntHseNo,cntAddress1,cntAddress2,cntPostcode) AGAINST('YELIZ*' IN BOOLEAN MODE)) cnts ON cnts.cntCode = cnt.cntCode WHERE app.synchDel = 0  AND app.type = 'S' AND APP.offCode NOT IN ('ALG','ATA','AUL','AUN','AUS','BAH','BRB','BRC','BRU','CAN','CDA','CMI','CLT','COG','CUL','CRO','CYP','CZR','DBA','ELT','FIN','GEN','GIB','GRC','GRE','VAR','HOD','IBZ','LAB','LAK','LCP','ISV','LAX','MAD','MLG','MAO','MAB','SLO','MAU','MER','MIA','MNO','MON','MNT','MRZ','NYO','NIC','OMA','OLT','PAR','PDG','PDL','LBN','PRO','PUG','RSR','ROE','STZ','SAN','SDA','SIR','SOT','SOA','DOR','SPA','SAE','SLU','JCP','SKN','SPL','TUR','TUC','UMB','VBE','VEN','WAG','ZAS') ORDER BY sort DESC LIMIT 120  AND (app.depCode = 'G')
 
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AND (app.depCode = 'G')' at line 1
<img width="1250" alt="Screenshot 2023-05-02 at 14 34 06" src="https://user-images.githubusercontent.com/127317362/235682170-f961f83c-733c-4a5b-873d-d0b765764c00.png">
<img width="1254" alt="Screenshot 2023-05-02 at 14 34 16" src="https://user-images.githubusercontent.com/127317362/235682180-f0b581e6-c62e-4ccd-b6eb-073b6e63c0b3.png">

**Comment by plittlewood-rpt** [comment]
Hi @yeliz-tacel this looks like an issue regarding AgencyCloud and should be logged with our main helpdesk. This Github board is for Foundations related items only. Many thanks
