### ISSUE TITLE
Appointment Webhooks not firing

### ISSUE THREAD

**Issue by stebrough** [reapit/foundations#8979]
**Describe the bug**
We've setup Appointment webhooks ("Appointment confirmed"/"Appointment cancelled"/"Appointment created"/"Appointment modified") and we've not received any.

Sensitive info email to sinfo@

**Comment by plittlewood-rpt** [comment]
Hi @stebrough I think I can see the problem. Please leave this with me.

**Comment by plittlewood-rpt** [comment]
@stebrough events for the customer concerned should now be starting to come through to you. I'll leave this issue open until you can confirm receipt it you'd kindly do so when you get a minute or two. Thanks

**Comment by stebrough** [comment]
Hi @plittlewood-rpt thanks, could you explain the issue please? Also it being Appointment webhook we will have to wait for activity to confirm everything is OK. Or is it possible the ones that should have come through over the past few days could be resent?

**Comment by plittlewood-rpt** [comment]
Hi @stebrough there was a step missed when this customer migrated over to AWS which meant their data was never added to the event streaming pipeline. As a result it's difficult to resend events for the past few days as it never got captured. We've actually got [another issue ](https://github.com/reapit/foundations/issues/8927 )in this sprint to just make sure there aren't any others as we've had a couple of similar reports recently.

**Comment by stebrough** [comment]
@plittlewood-rpt still no webhooks received as yet ....

**Comment by plittlewood-rpt** [comment]
Hi @stebrough does the customer in question have the app installed and is your webhook active and subscribed to their data? I can see events from their database being captured now. Thanks
