### ISSUE TITLE
Investigate the getAccessToken method is returning the same token after expiry

### ISSUE THREAD

**Issue by willmcvay** [reapit/foundations#900]
**Describe the bug**
Report from developer that the getAccessToken method we ship with the React App Scaffolder (used internally in Marketplace etc), is returning an expired token after 1hr (should be invalid and a new one refreshed).

**To Reproduce**
Either scaffold a redux app or just go to marketplace and log out the return value of getAccessToken.
https://github.com/reapit/foundations/blob/master/packages/marketplace/src/utils/session.ts#L6

It will get called on every protected route here:

https://github.com/reapit/foundations/blob/master/packages/marketplace/src/utils/route-dispatcher.ts#L21

Adjust the time before invalidating the token here in Cognito Auth to say 1min

https://github.com/reapit/foundations/blob/master/packages/marketplace/src/utils/route-dispatcher.ts#L21
&
https://github.com/reapit/foundations/blob/master/packages/cognito-auth/src/utils/cognito.ts#L116

Wait for the time to expiry and refresh page.

**Expected behavior**
Should return a fresh token after each expiry, if not, investigate and fix issue

**Comment by nphivu414** [comment]
Hi @willmcvay , @HollyJoyPhillips ,
I adjusted `TOKEN_EXPIRY` value, waited for for the time to expiry and found that we still get a fresh token after each expiry. Please check my screenshot below:
<img width="2046" alt="Screen Shot 2020-04-17 at 10 27 28" src="https://user-images.githubusercontent.com/22409039/79529589-3e306f00-8097-11ea-96b3-4afe9f416e2c.png">
