### ISSUE TITLE
Extra Field for Feature Property

### ISSUE THREAD

**Issue by ebuildwebsolutions** [reapit/foundations#9007]
Hi,

The original extra field (extrasfield=pFeatured) was updated to a new tick option in the API feed:
https://platform.reapit.cloud/properties/#id#?extrasField=pOffr&extrasfield=pFeatured

Can you supply me with the new naming convention for the new featured property extra field, so I can reference which properties are marked as featured properties please?

**New option:**
![feature_property](https://user-images.githubusercontent.com/25635668/236439901-28b74b10-1378-4d43-a5e7-99b4aae67c78.PNG)

**Original Option:**
![old featured property](https://user-images.githubusercontent.com/25635668/236440514-ace62338-2623-4279-9349-ef0dbbf7ff10.PNG)

My APP name is called Property Feed and the App ID is 6ca8a3f7-1137-4257-90a2-8e1a5f829495

Kind regards,

Philip.

**Comment by ebuildwebsolutions** [comment]
This was resolved. https://github.com/reapit/foundations/issues/9030

**Comment by plittlewood-rpt** [comment]
Housekeeping - closing as above
