### ISSUE TITLE
Possibility to create/update the follow up details in appointment endpoint

### ISSUE THREAD

**Issue by ss-dimasm** [reapit/foundations#9011]
**Is your feature request related to a problem? Please describe.**
We want to store the "follow up details" via API (follow up response Id, and follow up note) with POST and PATCH methods, but it's not get cover in the API model with those methods at this time.

**Describe the solution you'd like**
Have an ability to store the "follow up details" with POST and PATCH methods in appointment endpoint

**Additional context**
Here is our aim (highlight yellow)
![image](https://user-images.githubusercontent.com/96416644/236722137-b19c3cc5-27e7-498a-8167-7f7df74b554f.png)

**Comment by plittlewood-rpt** [comment]
Hi @ss-dimasm this is already possible. Please see the followUp object in the PATCH payload. Note that this is only available on PATCH as it doesn't make sense to set follow up information when initially creating a new appointment.

**Comment by ss-dimasm** [comment]
that was 100% make sense, while raising this ticket am looking at POST not PATCH model as a reference, and yes it's already available in PATCH

**Comment by ss-dimasm** [comment]
thanks, will close this ticket since the request already there
