### ISSUE TITLE
Support the "Followed Up" data access in appointment endpoint

### ISSUE THREAD

**Issue by ss-dimasm** [reapit/foundations#9012]
**Is your feature request related to a problem? Please describe.**
Would have the "Followed Up" data access that stored in AC via API, also we would want to update the "Followed Up" data via API

**Describe the solution you'd like**
Support the "Followed Up" data on appointment endpoint with create, read, and update operations

**Additional context**
Followed Up tick box in AC
![image](https://user-images.githubusercontent.com/96416644/236724584-b398d100-4655-4fb2-aa78-dacd03597fcc.png)

**Comment by plittlewood-rpt** [comment]
Hi @ss-dimasm this is inferred based on the presence of a `followUp.due` date and not something that is actually stored in the database. You should therefore have the information you need to make this inferrence in your app. Please let me know if this is unclear. Thanks

**Comment by ss-dimasm** [comment]
correct me if am getting wrong @plittlewood-rpt , so when the appointment is past and `followUp.due` has `null` value the followed up tick box got ticked

**Comment by plittlewood-rpt** [comment]
That should be the behaviour yes.  Please let me know if you see something different
