### ISSUE TITLE
GraphQL: add email parameter to query GetContacts as API GET /contacts

### ISSUE THREAD

**Issue by nguyenduc2112** [reapit/foundations#9015]
**Describe the bug**
I want to switch from using Platform API to GraphQL to improve the performance of web app.
But GraphQL GetContacts does not have the parameter `email` as API `GET /contacts`

**To Reproduce**

1. Go to GraphQL playground
2. Create a query with GetContacts
3. Can not find parameter email (like an API `GET ./contacts`)

**Expected behaviour**
The GraphQL should provide the parameters as well as schemas like API Platform

**Device (please complete the following information for web issues):**
 - Browser [Chrome]

**Screenshot**
GetContacts parameters on GraphQL docs
<img width="272" alt="image" src="https://user-images.githubusercontent.com/60997635/237025255-b755a312-b537-48f8-ab75-4a9b7a0e2fe0.png">

Thanks for reading.

**Comment by HollyJoyPhillips** [comment]
Hi @nguyenduc2112  we can certainly get these fields added to the current version but you may find that there will still be fields missing as the beta version is not feature complete. I would suggest waiting until we release the production version as it will be in line with the current Platform REST APIs. 

We have a milestone for this release which you can follow here: https://github.com/reapit/foundations/milestone/100

However, it’s worth pointing out that it will not help performance as the Graph QL service is a layer that sits on top of the Platform APIs and will be slower than interacting the with API’s directly. 

If you can please confirm you would still like these fields added or you are likely to wait until the milestone has been completed, I can triage this ticket accordingly? 

Thanks
 
Related ticket: https://github.com/reapit/foundations/issues/9014

**Comment by nguyenduc2112** [comment]
Hi, @HollyJoyPhillips Thanks for your response.

Currently, we mostly use the Platform API for the main features, GraphQL is optional.

Nice to know that you are still working on that, so we'll back to using the Platform API and wait for the original release of GraphQL.

Thanks
