### ISSUE TITLE
When posting a new tenancy check, `checkTypeId` always have empty value

### ISSUE THREAD

**Issue by dinasoftwareseni** [reapit/foundations#9022]
**Describe the bug**
When posting a new tenancy check, add property checkTypeId e.g "MKT005" and then get tenancy check always have empty value in checkTypeId

**Screenshots**
1. Add property checkTypeId e.g "MKT005 in id:MKT230097
![New Project (1)](https://github.com/reapit/foundations/assets/99008109/0bff8b82-4a96-4430-b682-72bd18adaf85)

2. Success post
![New Project (2)](https://github.com/reapit/foundations/assets/99008109/12385d31-cd71-40e8-8ee9-623701312824)

3. Search id:MKT230097
![New Project (3)](https://github.com/reapit/foundations/assets/99008109/46767dc8-72d7-478b-b2eb-3ac92f881333)

4. checkTypeId have empty value
![New Project (4)](https://github.com/reapit/foundations/assets/99008109/670a61a1-c9f6-4538-aee7-ee5a5e70e97c)

**Specification**
- Project: Reapit.Services.Tenancies
- Replicate the problem which could be caused by:
  - The presence of a description is causing the service to treat the check as a custom one rather than using the associated source denoted by checkTypeId
  - There is a mismatch between the provided description and the description on the source denoted by checkTypeId
- Check whether or not the check id is being stored in the database as this will outline whether the issue relates to the read or write operation

**Comment by ashindey12** [comment]
"checkTypeId" is not part of the CreateTenancyCheckModel and cannot be added while creating tenancy checks, please check the sample payload model for the list of properties used to create tenancy checks

**Comment by MatthewGoddard** [comment]
@ashindey12 That is the issue here and why the ticket has been logged. You _should_ be able to post checkTypeId. Unfortunately, the modal doesn't appear to have been updated when this was added. You can look at GET tenancies/{id}/renewalNegotiations/{id}/checks/ for an example of the modal.
