### ISSUE TITLE
Extra Field for Feature Property 

### ISSUE THREAD

**Issue by ebuildwebsolutions** [reapit/foundations#9030]
Hi,

The original extra field (extrasfield=pFeatured) was updated to a new tick option in the API feed:
https://platform.reapit.cloud/properties/#id#?extrasField=pOffr&extrasfield=pFeatured

Can you supply me with the new naming convention for the new featured property extra field, so I can reference which properties are marked as featured properties please?

New option:
![feature_property](https://github.com/reapit/foundations/assets/25635668/dde1b751-26e4-437c-b2c8-a95c4d3bb39c)

Original Option:
![old featured property](https://github.com/reapit/foundations/assets/25635668/8a6e7947-48ad-4f4e-8d10-ce5aec8b531a)

My APP name is called Property Feed and the App ID is 6ca8a3f7-1137-4257-90a2-8e1a5f829495

Kind regards,

Philip.

**Comment by plittlewood-rpt** [comment]
Hi @ebuildwebsolutions - I'm just liaising with our service desk about this as the field names should not have been changed. I'll come back to you as soon as I can

**Comment by plittlewood-rpt** [comment]
Internal ref: RSD-222948

**Comment by ebuildwebsolutions** [comment]
Hi @plittlewood-rpt,

Thanks for coming back to me.

Just to confirm that I can use it in the following manner: https://platform.reapit.cloud/properties/#id#?extrasField=RSD-222948

Kind regards,

Philip.

**Comment by plittlewood-rpt** [comment]
Sorry that's an internal service desk reference. I'll come back to you with the details of the new field once I've spoken to them. Thanks

**Comment by plittlewood-rpt** [comment]
Hi @ebuildwebsolutions this should be sorted. The field is pFeatured as before so you shouldn't need to update anything. Please let me know if you have any further issues
