### ISSUE TITLE
As a ‘Member of the Public’, I want to filter and sort my search results 

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#904]
**Summary**: We will be adding a filtering/advance search option to the search widget 

Given that I am a ‘Member of the Public’ and I am searching for property, I want to have the option to do an Advanced search when searching for a property

**Related to:** https://github.com/reapit/foundations/issues/921

**Task:** To create an ‘Advanced Search’ form when ‘Advanced Search’ link has been clicked 
- Should be hidden by default
- Form should slide down into view when ‘Advanced Search’ is clicked
- If ‘Advanced Search’ has been clicked again hide (slide out of view)
- Should hide automatically after search
- Should display filters based on the toggle setting ‘For Sale’ or ‘To Rent’ 

**Filters** 
- Bedrooms: 2 drop down menus’ bedroomsFrom’ and ‘bedroomsTo’
Default should be ‘No Min’ and ‘No Max’
- Property Type: Drop down menu  ‘type’
- Price: 2 drop down menus ‘priceFrom’ and ‘priceTo’ 
Default should be ‘No Min’ and ‘No Max’
- Order Results By: Drop down menu for price ascending or price descending
- Added in: Drop down menu to include ‘Last 24 Hours’, ‘3 days’, ‘7 days’, ’14 days’ should calculate based on date ‘created’

Example UI: 
![image](https://user-images.githubusercontent.com/52408607/79353047-766a6d00-7f32-11ea-861b-df0b81f6f2a9.png)

**Comment by HollyJoyPhillips** [comment]
@trankhacvy , Please see filtering options below: 

- Beds min & Max  1, 2, 3, 4 & 5 

- Price From and To: **Start at £50,000** and increment by £10,000
So £50,000, £60,000, £70,000 etc 
Go up to £300,000 and from there increment by £25,000 
So £300,000, £325,000, £350,000
**Stop at £2,000,000**

See example: 
![image](https://user-images.githubusercontent.com/52408607/79464219-b04e7880-7ff1-11ea-9ac9-cc42036cd5ac.png)

- Property Types 
Use the list from ‘types’
 
![image](https://user-images.githubusercontent.com/52408607/79464232-b6445980-7ff1-11ea-8c05-bd5a8f4d5635.png)

**Comment by trankhacvy** [comment]
![oop2](https://user-images.githubusercontent.com/8068926/79541582-44811400-80b4-11ea-9b94-29c9dadb3207.gif)
@HollyJoyPhillips @willmcvay I have some questions about this ticket.
- For `Added in` option,  which parameter we use to call api ?
- When user selects `For sell`, the min price and max price will match with `priceFrom` and `priceTo `, when user selects `To Rent`, the min proce and max price will match with `rentFrom` and `rentTo` params, is it correct ?

This above video is which I have done. Is it correct with the requirement ?

**Comment by HollyJoyPhillips** [comment]
@trankhacvy 
Hi Vy, yes you are correct regarding the price and rent from. You can ignore the 'Added In' filter for the time being. I will create a separate ticket once i've confirmed the details. 

Just a thought and it might be just the video but the results line (Properties for sale in...) shouldn't display until there are property results.

Otherwise the video is great, please proceed.
