### ISSUE TITLE
Could Not Detect A Property TYPE

### ISSUE THREAD

**Issue by sanjayisg** [reapit/foundations#9040]
Hi There,

We manage property from RPS and there are 3 types of property there.

Resale Property, New Homes(Master), Subplot

With an API I am able to detect which property is  Resale Property, New Homes(Master), Subplot 

Like 

if (!empty($propdata['_links']['master']['href'])) {
	$inputs['master_id'] = str_replace("/properties/", "", $propdata['_links']['master']['href']);
	$inputs['property_type'] = 'Subplot';
} else if (!empty($propdata['_links']['subPlots']['href'])) {
	$inputs['master_id'] = NULL;
	$inputs['property_type'] = 'Master';
} else {
	$inputs['property_type'] = 'Resale';
}

But in webhooks I can not determine what is the property type by any key.

![Screenshot 2023-05-12 182504](https://github.com/reapit/foundations/assets/89017410/63f6a3d2-9c5c-4d72-94e1-928cd5e889ee)

In attached it shows that I am not getting in hooks.

Thanks,

Sanjay Gupta

**Comment by AshDeeming** [comment]
Hi @sanjayisg 
Please note that the above is broken down into two separate parts of the core software;

New Homes is a Department type such as Residential or Commercial (https://foundations-documentation.reapit.cloud/platform-glossary#department) 

With regards to the Plots and subplots, this is also within Departments however this is sub catergory, please see more details under (https://foundations-documentation.reapit.cloud/platform-glossary#interpreting-department-data) 

![image](https://github.com/reapit/foundations/assets/61687775/bffe2f88-ddcd-488a-b4b9-8b23b8bab221)
