### ISSUE TITLE
Ability to filter embedded property documents by document type

### ISSUE THREAD

**Issue by joe-at-github** [reapit/foundations#9056]
**Is your feature request related to a problem? Please describe.**
As a user querying the properties endpoint and asking for embedded documents, I would like to have control over which type of documents are being fetched to minimise the amount of sub calls made to the documents endpoint.

i.e I would like to be able to query all relevant properties (matching given search criteria), have their documents as embedded data but only if the documents are of type `DET` or `EPC`.

**Describe the solution you'd like**
When querying the properties endpoint I would like to be able not just pass an array of embedded objects (e.g document, negotiator, images) but also a type e.g (document: ['DET', 'EPC']).

**Describe alternatives you've considered**
The alternative to the Foundation API having this feature would mean
- fetching all relevant properties, without embedded documents
- making calls to the document endpoint specifying the document types ('DET', 'EPC'), and property ids as associatedId
- manually build a data packet consolidating properties with their respective documents

**Additional context**
N/A

**Comment by HollyJoyPhillips** [comment]
Hi @joe-at-github, it's not technically possible to pass query parameters for embedded data, therefore this ticket will be closed.
