### ISSUE TITLE
General queries related to data properties and events within Reapit webhooks and REST API

### ISSUE THREAD

**Issue by shanelilly** [reapit/foundations#9077]
Please take a look at our FAQ's before submitting an issue, as your question may already be covered in the documentation https://foundations-documentation.reapit.cloud/faqs

**Summary**

1. On the property.created webhook payload, Is entityId and new.id the same value always? If so, which property should we use?

2. I understand there is no event available to notify us when a negotiator gets added/modified or deleted. How do you recommend we keep up-to-date negotiator information on our properties?

3. The webhook is not sending the full description. For entity RED221300, the description is missing information. This is what is received from Reapit

      "description": "Welcome to Avalon, a magnificent five-bedroom family home perfectly located on a quiet cul-de-sac setting with the added benefit of a 100-foot rear garden. Likely to appeal to a wide audience the sale of this wonderful home represents a superb opportunity to gain a foothold in this popular location....\r\n\r\nConstructed in 1947 and extending to c. 190 sq. m. internally the accommodation comprises an entrance hall, living room, interconnecting double doors to a dining room, sitting room to the front and an open plan kitchen/breakfast room to the rear with utility room and showroom off. Upstairs there are five bedrooms and a main bathroom with the master bedroom benefitting from an en-suite shower room and walk-in wardrobe. Outside there is off street parking for two cars while to the rear the garden is walled and laid in lawn.  \r\n\r\nSarah Curran Road is off Sarah Curran Avenue and benefits from one of south Dublin’s most convenient locations. St Enda’s Park, Rathfarnham Village and Rathfarnham Shopping Cente are all within a stone’s throw and provide a wide choice of amenities including supermarkets, grocery shops, cafes, pharmacy, hair salon, dry cleaners, and a church to name but a few. The area also offers a range of leisure facilities at the nearby Marlay Park which as everything from sports pitches to tennis courts to an extremely popular children’s playground. Many fine national and secondary schools are in the area including St Marys National School, Sancta Maria College, Colaiste Eanna, Terenure College, Templeogue College and Loreto Beaufort. Dublin Bus provides superb public transport facilities to the city centre and surrounding suburbs.\r\n\r\nA brief description does not do justice to this spacious house – inspection is highly recommended.",

And comparing this to the property on Daft - https://www.daft.ie/for-sale/semi-detached-house-avalon-avalon-3-sarah-curran-road-rathfarnham-dublin-16/4648379 you’ll note that the description includes additional detail at the end regarding Entrance Hall, Living Room etc. This information is sent to us in the XML feed from Reapit but not in the webhook. 

4. Can you please provide a list of sample values we can expect to receive for the following data properties within the property topic; 
- areaId 
- viewingArrangements
- externalArea.type
- specialFeatures

5. What is the typical use case and sample values for these data properties within the property topic; 
- alternateId 
- strapline, description, summary, longDescription (are any of these data properties used as the ‘primary’ or mandatory / default description field)
- departmentId 
- bedroom and maxBedrooms (what is the use case for maxBedrooms and what scenarios would there be a difference in values for these fields for a property object)
- featuredImageUrl
- url
- externalArea.type, externalArea.min, externalArea.max (are these used for commercial or sites? Do they support acres and hectares as area values?)
- selling.Instructed
- situation

6. Where can we retrieve mapping information for these data properties in the property topic; 
- areaId (i.e. what does the sample value ‘DBL’ map to)
- specialFeatures (are these free text or a set list of values)

**Detail and or supporting links and screenshots**

**Comment by AshDeeming** [comment]
Hi @shanelilly 

1
I'm not sure i understand the question, when a propert is created, the propertyID can then be used. 

2
Please see the json filtering details below;
https://foundations-documentation.reapit.cloud/api/webhooks#building-event-filters

3.
Please could you confirm these addtional details are being held in the extra descriptions within Marketing in AgencyCloud.
If so, this is semi structured data & a request will need to be made per client: 
[Semi-structured 'extras' field request](https://github.com/reapit/foundations/issues/new?assignees=&labels=back-end%2C+needs-triage&projects=&template=extras_field.md&title=)

4.
Please refer to the configuration endpoint via the swagger docs to see how to call these to check each clients config: 
(https://developers.reapit.cloud/swagger)

5.
As point 4, please see the swagger page for sample payloads along with model

6.
As above - you can also see the below documentation regarding specialFeatures below;
https://foundations-documentation.reapit.cloud/whats-new#applicants-api
