### ISSUE TITLE
Payment reference for Lettings Transactions

### ISSUE THREAD

**Issue by raymond2323** [reapit/foundations#9082]
Not exactly a bug but a question/clarification. We have a client, who use our system for Pre-Tenancy but would like to have a way to pull payment reference for a specific property/tenancy so that when the Tenant pays via our system (for Holding Deposit and Move-in monies), they use the correct payment reference that we have fetch from Reapit. Is there a way to fetch the payment reference for a specific property/tenancy prior to payment having been made as this happens via our system? I can see there is an end-point called Transactions but don't see any mention of a payment reference. 

**Specification**
- Project: Reapit.Services.Tenancies
- Add new `string paymentReference` property to `RelatedContactModel` that exposes ten.extra.tStatRef (for main tenant) and addstore.extra.StatRef (for additional tenants). Model comment `An optional payment reference to be used for transactions related to this tenancy associated with this tenant`
- Add new `string groupPaymentReference` property to `TenanyModel` the exposes ten.extra.tGroupStatRef. Model comment `An optional payment reference to be used for transactions related to this tenancy associated with all tenants in the property`

**Comment by plittlewood-rpt** [comment]
Hi @raymond2323 there are two places in our AgencyCloud CRM where a payment reference can be stored:

1. Against the tenancy itself
2. Against each individual tenant

It is up to agents which field and naturally relies on them entering this information for us to be able to expose it. Is there a particular customer you are working with? I can have a look in their system to see if/how they are using these fields. We'll need to do a little review to see what's feasible and come back to you.

**Comment by plittlewood-rpt** [comment]
Hi @raymond2323 have you had a chance to review the above?

**Comment by raymond2323** [comment]
@plittlewood-rpt yes, we need a read-only access. So which endpoint can I use to gather this data?

**Comment by HollyJoyPhillips** [comment]
The Foundations team have confirmed we can progress on this on read only basis
