### ISSUE TITLE
Foundations API not returning data stamp when the property was launched online 

### ISSUE THREAD

**Issue by RussellSimpson2022** [reapit/foundations#9088]
![No Internet Advertising time stamp1](https://github.com/reapit/foundations/assets/97975998/28a6c633-089e-4ca4-a955-6bf914af3b5c)
Our web developers are not able to filter buy and rent properties from the newest oldest based on the launch on the market date on this page: https://www.russellsimpson.co.uk/buy

They are saying that Foundations API is not giving them a data stamp when the No Internet Advertising under Marketing on Reapit was switched off. 

However, this data is available under the Property record/Journal; Rightmove, Zoopla and On the Market portals are also able to pull this information and filter properties from the newest to the market to the oldest ones. 

Could you please advise our web developers on how they can implement this functionality best from the data available within Foundation API?

Please, see the correspondence with our web developers about the issue attached. 

Many thanks,
V.

**Comment by AshDeeming** [comment]
Hi @RussellSimpson2022 
Please could you advise the app name along with any examples to: sinfo@reapitfoundations.zendesk.com

**Comment by jaetoole** [comment]
@RussellSimpson2022 sorry to wade in here, but, your developers should be running a task regularly enough to keep the data on the website up-to-date. I would guess this is run at-least once daily. If this is the case, if a property comes up with no internet advertising off, but previously had no internet advertising on, they should be able to use this date as the launched online date.

It might not be that simple! Just my 2-pence as a fellow foundations user & developer.

**Comment by plittlewood-rpt** [comment]
Hi @RussellSimpson2022 - the recording of this field being changed in the activity feed is custom to this agent (though other agents do have the same customisation). As a result there's no immediate way to include this data in the response from the properties endpoint, but you can access it by calling GET /journalEntries?typeId=DC&propertyId=ABC123456 and looking for the relevant entry
