### ISSUE TITLE
Write permission required

### ISSUE THREAD

**Issue by timr-yougroup** [reapit/foundations#9090]
I'm trying to add 'Write properties' permission to our app - you-group-youq-importer as a request returned `RuntimeError (failed to POST to properties: 403 - {"statusCode":403,"dateTime":"2023-05-18T12:45:03.9592626Z","description":"This application has not been granted the required scope to interact with this endpoint. If your application requires access to this resource, please use the Reapit Foundations Developer portal to request permission to access this resource"})`

I've added the relevant permission on the Edit App/Permissions tab and submitted a revision. This emailed the one user account we have
![image](https://github.com/reapit/foundations/assets/105444862/b5c0e96b-cc69-4a4f-95dd-a68b978c7ec4)

but when I click through to accept the requested permissions I get the error;

'The identity attached to this request does not have the required permissions to access the requested data`

![image](https://github.com/reapit/foundations/assets/105444862/3d83a487-caf5-4e65-9691-b5dbfa184923)

**Comment by AshDeeming** [comment]
Hi @timr-yougroup 
There are currently no pending revisions for this app, please confirm if you're still experiencing the issue?

**Comment by timr-yougroup** [comment]
Hi,

This has been resolved

Thanks
