### ISSUE TITLE
Internal images not displaying correctly on appMarket listings 

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#9092]
The internal images (screenshots) are appearing as small images rather than scrollable images on app listings. See example below: 

![image](https://github.com/reapit/foundations/assets/52408607/7a1411e8-b0a3-400b-baed-e9a0c2940b53)

**Comment by bashleigh** [comment]
<img width="329" alt="Screenshot 2023-06-06 at 10 27 31" src="https://github.com/reapit/foundations/assets/11574250/ec666195-5261-4da8-bc06-09ce44f41940">
Appears to be a bug with linaria where the above is outputted as `@media (min-width: 768px)`. Potential fix would be to rollback the version and see if that resolves the issue
