### ISSUE TITLE
Help With API?

### ISSUE THREAD

**Issue by themindman10** [reapit/foundations#9099]
Hi, im looking to obtain the api documentation as im looking to develop an application that works with the Reapit CRM, can you please help me?

**Comment by AshDeeming** [comment]
Hi @themindman10 
Please see the open link below however to create an app & test in sandbox etc, you will need to register for the Developer portal.
https://foundations-documentation.reapit.cloud/

Please confirm if you are you planning on building an app for a specific client or an app for all Reapit clients so i can refer you to the correct team.

**Comment by themindman10** [comment]
Hi, 

the application will be for all and any reapit clients.

**Comment by AshDeeming** [comment]
Thanks @themindman10 
Please see the registration link below - Please follow the relevant flow;
https://developers.reapit.cloud/select-role
