### ISSUE TITLE
Cannot find a property from a customer via the API

### ISSUE THREAD

**Issue by lucajackal85** [reapit/foundations#9102]
**Describe the bug**
When trying to search a property by address, the API is not returning any result. but the property we're looking for is returned if we call the get property endpoint

**To Reproduce**
The client id is `DBR`
1 - Searching for property by address
2 - no result has been found (tried with partial address, postcode only etc...)

BUT calling the endpoint `/properties/LET230070` the property is returned successfully

**Expected behaviour**
Searching by address, the API should returns the result

**Screenshots**
We have screenshots from the customer but they all contain personal information.

**Device (please complete the following information for web issues):**
 - API integration

**Additional context**
Ticket submitted by Goodlord regarding the API integration.

**Comment by plittlewood-rpt** [comment]
Hi @lucajackal85 this seems to be working OK for me. I've just tried the following requests and get the address back each time

GET platform.reapit.cloud/properties?address=The%20Cloisters
GET platform.reapit.cloud/properties?address=TF4%202GH

Can you let me have the detail of the requests you've tried?

**Comment by enricsangra** [comment]
Hello! Taking over from @lucajackal85 because he is away right now.

After digging a bit more with your data, we can find it but it seems to have `Not set` as Marketing mode, which is causing issues because we have a filter for lettings.

Is it possible to have properties without marketing mode? How can we tell them to set this up? Or is it some problem in your side?

Thanks,

Enric

**Comment by plittlewood-rpt** [comment]
Hi @enricsangra thanks for pointing this out (and sorry I didn't spot it myself!). I'm not sure how the data has ended up in that state, but I've just corrected it so it should get returned in your filter now and the `marketingMode` should be set correctly. Please can you confirm back to me if this is now OK?

**Comment by enricsangra** [comment]
All sorted, thank you!
