### ISSUE TITLE
Referrals API is broken

### ISSUE THREAD

**Issue by Tj3n** [reapit/foundations#9108]
Hi, I'm using [Referrals API](https://developers.reapit.cloud/swagger) for a company app project, but then this API is very unstable and return 502 error halves of the time. It will work again if I keep trying to reload for few mins and start working ok once it got the data, the issue seems to happen on all referrals api: `/referrals/`, `/referrals/{id}`,... Please help take a look, thanks!

Note: Issue does not happen on others API e.g. Contacts or Properties.

**Comment by AshDeeming** [comment]
Hi @Tj3n 
Please could you provide examples along with the timeframes for the issue faced - any sensitive details can be sent to: 
sinfo@reapitfoundations.zendesk.com

**Comment by Tj3n** [comment]
@AshDeeming It happens for both normal API call and try it out on GET `/referrals`, timeframes is pretty much always, weird thing is that it resolved itself after few reloads, but user would report bug anyway. I've sent a sample cURL to the email above, thanks!

![image](https://github.com/reapit/foundations/assets/13995715/2c28a38e-64fc-4b46-8a25-e6efde22d281)

**Comment by plittlewood-rpt** [comment]
Hi @Tj3n I have just checked the configuration of this particular endpoint and it's timeout settings were not correct which will have been leading to premature timeouts. I have resolved this so you should see a marked improvement in the issues you have been facing. I'll monitor from this end, but I'd appreciate your feedback. Many thanks

**Comment by Tj3n** [comment]
Sounds great! I'll check back tomorrow to see if it works. Thanks!

**Comment by Tj3n** [comment]
Hi @plittlewood-rpt this seems to works well on our end, please feel free to close if needed.

**Comment by AshDeeming** [comment]
Thanks @Tj3n & @plittlewood-rpt
