### ISSUE TITLE
Recurring charges

### ISSUE THREAD

**Issue by elizabethhamlin** [reapit/foundations#9113]
Please can I ask that recurring charges are available in the data warehouse. Much like the tenancy alterations, I would like to have the tenancy recurring charges too

**Specification**
- Analytics Schema
- Look at AC data structures for tenancy charges and design appropriate model view for the analytics schema

**Comment by elizabethhamlin** [comment]
Hi 
Any update on when this will be looked at?
Thanks 
Lill

**Comment by HollyJoyPhillips** [comment]
Hi @elizabethhamlin this will be picked up in our refinement session today. Thanks.

**Comment by plittlewood-rpt** [comment]
This data is now available in the TENANCY_RECURRING_CHARGES view. Please refresh your data share in the Data Warehouse app and refer to the updated documentation in the Developer Portal. Thanks

**Comment by elizabethhamlin** [comment]
Hi @plittlewood-rpt 
I have just refreshed my data share and TENANCY_RECURRING_CHARGES is not a table that appears. Please can this be looked at.
Thanks 
Lill

**Comment by plittlewood-rpt** [comment]
Hi @elizabethhamlin sorry that's my fault, I missed a step during the release so the service responsible for provisioning the data shares was not 'aware' of the new view. I've updated that now so it you hit Refresh Share it should appear. Let me know if you continue to have problems. Thanks

**Comment by elizabethhamlin** [comment]
Thanks @plittlewood-rpt However the Michael Jones one is throwing up a fault - any ideas?
![image](https://github.com/reapit/foundations/assets/104636752/ec37ab12-a851-49e6-a6ae-4f0aeb629580)

**Comment by plittlewood-rpt** [comment]
Hi @elizabethhamlin have you been able to resolve this? It looks like an issue with POWER BI perhaps not being configured correctly.

**Comment by elizabethhamlin** [comment]
Hi @plittlewood-rpt I have just kept them separate rather than merging so it works for now. Thanks for checking
