### ISSUE TITLE
Access to Office Group configuration

### ISSUE THREAD

**Issue by stebrough** [reapit/foundations#9114]
**Is your feature request related to a problem? Please describe.**
We are getting more and more requests from customers to be able to separate their data

**Describe the solution you'd like**
Access to the "Office Group" data as per below screenshot.

**Additional context**
![2023-05-22_12h31_39](https://github.com/reapit/foundations/assets/40298446/bffe2aef-9aaf-4d1f-88e7-3e5b6b390cf1)

**Comment by plittlewood-rpt** [comment]
Hi @stebrough - we've actually recently released an update to the DeveloperPortal which should help you here. If you open your App listing page and go to the Installations tab, you will see an arrow on the right hand side of the table. When an app is installed for an office group, you can use this functionality and click Show Installed Offices to get at the list of offices in that group. Please let me know if this does not answer your query

**Comment by stebrough** [comment]
Hi @plittlewood-rpt, thanks for the response, but unfortunately no that doesn't help. We need to be able to let our customers segment their feeds, and I want to mimic how this happens when the app is installed for a office group in Reapit. Allowing our customers to controlling this grouping via Reapit office groups is by far the best solution.

**Comment by plittlewood-rpt** [comment]
Thanks - so are you saying you would like us to look at giving you a programmatic capability to understand office groups?

**Comment by stebrough** [comment]
HIi @plittlewood-rpt ahh yes, sorry I should have stipulated. Yes if these could be exposed via the API that would be great.

**Comment by stebrough** [comment]
Hi @plittlewood-rpt, as a short term solution that would work, but long term as you mention it can be changed after full access via it's own endpoint would be needed.

**Comment by stebrough** [comment]
Hi @plittlewood-rpt is there anything more on this?

**Comment by plittlewood-rpt** [comment]
Not as yet - unfortunately this won't be the easiest task so we need to consider the options and see if we can come up with a sensible route. Can you just provide some more context around the real world problems you have not being able to programatically access this information?

**Comment by stebrough** [comment]
@plittlewood-rpt Sure no probs. Some of our customers only wanted to give us access to certain office groups rather than the whole lot. So our configs were built on this. Now some of those customers want to open up and give access to everything, but still direct data to multiple II accounts. As we have already built our integration around Office Groups, it is a natural fit to still keep these in the equation. Does that make sense?

**Comment by plittlewood-rpt** [comment]
Hi @stebrough if I've understood correctly, it sounds like the customer is wanting to go from office group level installations of your app, to an organisation level. If this is correct, the office groups at our end become irrelevant and managing some kind of office to instance mapping at your end would become a requirement.  

As an example, you would go from having 3 group level installations for a customer, eg ABC-GAAA, ABC-GBBB and ABC-GCCC to having a single organisation level installation for customer ABC. The office groups are no longer applied to your app access in any context as it is a server side integration (if it was a user centric app the data would still get filtered).

I think the only way to safeguard the app and your data is to build something into the app itself so users with the right levels of access can manage a mapping such as the one described above. The issue you would have if using our office groups is that they can be changed so suddenly data could start going to instances that you wouldn't normally expect it to.

**Comment by HollyJoyPhillips** [comment]
Hi @stebrough, based on what Pete has commented above, are you happy for us to close this ticket?

**Comment by stebrough** [comment]
Hi @plittlewood-rpt @HollyJoyPhillips sorry I did meant to respond sooner, yes I completely agree with what Pete said and this can be closed.
