### ISSUE TITLE
/enquiries/ POST request slow and not going into 'Internet Registration'

### ISSUE THREAD

**Issue by propertyhive** [reapit/foundations#9117]
We're POST'ing enquiries for a mutual client (B&C London Investment Solutions) from their website to Reapit using the `https://platform.reapit.cloud/enquiries/` endpoint.

Two issues are arising:

1) Timing out: It was taking longer than 5 seconds for the request to complete so was timing out. I extended the timeout and now we get a response in about 6-7 seconds. Should it really take this long for a request to be processed? Or can you think of anything that might slow it down?

2) The data we post isn't appearing in the clients 'Internet Registrations' section of Reapit. I'm assuming they should? Can you see the data being received and tell why they might not be going into this section of Reapit?

Thanks in advance, 
Steve

**Specification**
- Project: Reapit.Services.Enquiries
- Point 1 relates to the execution time of the serverless API. It is likely that the slow requests are due to a cold start in which case we should investigate whether or not the keep-warm events are firing properly and at the right interval. 
- Point 2 is likely due to the data being included/omitted in the request body. We should be able to determine if this is the case by looking in the appimp table in the customer's database to find some of the entries from this app and from there work backwards to determine why the enquiries aren't being displayed in the CRM.
  - Issue confirmed. Will update service to validate officeId when presnet

**Comment by AshDeeming** [comment]
Hi @propertyhive 
Please could you provide any examples to the below email;
sinfo@reapitfoundations.zendesk.com

**Comment by plittlewood-rpt** [comment]
PR opened to improve cold start performance and add validation to POST payload to check office ids exist before being committed to db
