### ISSUE TITLE
error when attempting to cancel subscriptions 

### ISSUE THREAD

**Issue by AshDeeming** [reapit/foundations#9120]
**Background context**

When attempting to cancel existing Subscriptions, the below error is being thrown:

![image](https://github.com/reapit/foundations/assets/61687775/8ae0e9b3-be28-427b-8c18-13a77eabe1eb)

**Specification**

**Comment by RWilcox-Reapit** [comment]
This appears to be a front end issue. 
When attempting to cancel the subscription the identifier is not passed to the DELETE endpoint as the last parameter.
Instead 'null' is passed.
