### ISSUE TITLE
Ability to edit individual instances of recurring appointments

### ISSUE THREAD

**Issue by iWader** [reapit/foundations#9121]
**Is your feature request related to a problem? Please describe.**

The API currently exposes recurring appointments, however on RPS customers are saying they can edit individual instances of these recurring appointments. (e.g Customer has an appointment recurring on the 10th day of every month. However customer can edit June's event to be on the 11th.)

**Describe the solution you'd like**

Expose this behaviour on the API, or document how it can be achieved if it is already available.

**Describe alternatives you've considered**

N/A.

**Additional context**

N/A

**Comment by plittlewood-rpt** [comment]
Hi @iWader - it's not possible for users to amend individual instances of recurring appointments in the CRM and as such it is also not possible to do this in the API either. I'm not sure where the information you've been given has come from but unfortunately it is incorrect. There would need to be a fundamental update to the core CRM before this could be supported in our API. The customer can reach our to their CSM if they wish to raise this as a feature request for the AgencyCloud CRM

**Comment by iWader** [comment]
Hi @plittlewood-rpt, thanks for clarifying. I'll confirm with the customer and Radweb what behaviour they're expecting here.
