### ISSUE TITLE
Add 'Status' to GET /properties/{id}/certificates/ model  

### ISSUE THREAD

**Issue by MatthewGoddard** [reapit/foundations#9126]
A 'Status' field has been added to the Cert table to support new functionality in AC.

Please can this be exposed in the GET /properties/{id}/certificates/ model.

![image](https://github.com/reapit/foundations/assets/10115484/ef9b86c6-7235-4f20-b919-d5f1a905f43f)

This will likely also need a corresponding /configuration/certificateTypes endpoint, as it is a configurable field... :)

**Specification**
- Project: Reapit.Services.Properties
- Add new `statusId` column to PropertyCertificateModel that exposes the value stored in cert.status
- If cert.status is null/empty, model property should be null. Statuses do not apply to all certificate types
- This should be read only for now as the write side is complex

- Project: Reapit.Services.Configuration
- Alter model returned from certificateTypes endpoint to include a new `statuses` collection of `ConfigurationItemModel` which contains an id and value property (use existing model) and exposes the unpacked configuration option value `configsetting.uCertFollowUpStatuses` - be sure to understand how to parse this field before proceeding. Output should look like this:

```
{
    "id": "AI",
    "value": "Appliance Insurance", 
    "statuses": [
      { 
         "id": "NV",
         "value": "Not Valid"
      },
      { 
         "id": "US",
         "value": "Unsatisfactory"
      }
    ]
}
```

**Comment by plittlewood-rpt** [comment]
Internal ticket SI-21439 opened for applying db field to all datasets to make introduction of this feature easier to handle

**Comment by plittlewood-rpt** [comment]
Field now present in all databases, so we can get this picked up and ready to merge
