### ISSUE TITLE
Adding additional fields to client Foundations feed

### ISSUE THREAD

**Issue by propertyhive** [reapit/foundations#9130]
Can you please add the following fields to the https://platform.reapit.cloud/properties feed for Laura Warren at MyLondonHome:

Hot Property

.. and let me know where they've been added? I think in the past we've used the extraFields node.

Thanks in advance, 
Steve

**Specification**
- Floor Level has been separated out into a separate issue #9146 as this is a core field and should be handled outside the extrasField mechanism. This ticket is now just to expose Hot Property for the customer
- Enable extrasField support for the Hot Property field for customer MLH and notify developer when complete

**Comment by AshDeeming** [comment]
Hi @propertyhive 
Please can you confirm which screen in AgencyCloud this relates to? 
I've checked the build and unable to see these fields.

**Comment by Martin-PH** [comment]
> Hi @propertyhive Please can you confirm which screen in AgencyCloud this relates to? I've checked the build and unable to see these fields.

Hi Ash,

Hot Property is on the Marketing Details screen
Floor Level is on the Attributes screen
(both on the Property record)

![Attributes Screen](https://github.com/reapit/foundations/assets/130488836/33292ba8-2000-470e-898f-18d9e7f63004)
![Marketing Details Screen](https://github.com/reapit/foundations/assets/130488836/df765424-2705-4ae4-8912-68f7a4122b3f)

**Comment by AshDeeming** [comment]
Thanks @Martin-PH

**Comment by plittlewood-rpt** [comment]
Hi @Martin-PH, I've split this ticket in two as the requests need handling separately. We'll review both of them in our refinement session later on today.

**Comment by ashindey12** [comment]
Hi @Martin-PH , extra field support for Hot Property field is now added for customer MLH, the field named configured is "pHotProperty" and can be accessed via extra  field i.e. extra.pHotProperty
