### ISSUE TITLE
500 Error Rest API

### ISSUE THREAD

**Issue by mrkmaulik** [reapit/foundations#9135]
I am getting error while trying to access API. Please guide.

**Comment by willmcvay** [comment]
@mrkmaulik You have just posted confidential security information in a public forum. Please supply us the app id for your application so we can re-cycle your keys

**Comment by mrkmaulik** [comment]
Hi,

We are not using basic authorization, its ignored parameter. Still if you think is crucial information please reset

App Id: d3464073-6308-4d6c-979a-4a66cf02329

Thanks & Regards

Maulik Shah
[https://ci5.googleusercontent.com/proxy/VH2DXkVwaASOjLMK04Jc5s3d3SQxA414Es-tQ_mVByR7Kl1qmvl3_cILKLrppWsHheeZXlLf4TzKHHAHNLlw3j9HLuXm5EwvujesIAI24pLFZGhcUlHHIoiVW51xQZmn8RZsfQ=s0-d-e1-ft#https://markteq.com/wp-content/themes/twentyeleven/images/MarkTeQ_Websitelogo.png]
MARKTEQ IT SOLUTIONS LLP
(M). +91 78741 44999
OFFSHORE STAFFING | BUSINESS MANAGEMENT SOFTWARE| E-LEARNING SOLUTION | CUSTOMIZED SOFTWARE, MOBILE & WEB APPLICATION DEVELOPMENT | BULK SMS | WEBSITE DESIGNING | PAYROLL SOLUTION
Skype: markteq
www.markteq.com<http://www.markteq.com/> | www.markteqwms.com<http://www.markteqwms.com/> | www.tuitionplusplus.com<http://www.tuitionplusplus.com/>


DISCLAIMER:
The information transmitted is intended only for the person or entity to which it is addressed and may contain confidential and/or privileged material which is the intellectual property of MarkTeQ. Any review, retransmission, dissemination or other use of, or taking of any action in reliance upon this information by persons or entities other than the intended recipient is strictly prohibited. If you are not the intended recipient, or the employee, or agent responsible for delivering the message to the intended recipient and/or if you have received this in error, please contact the sender and delete the material from the computer or device. MarkTeQ does not take any liability or responsibility for any malicious codes/software and/or viruses/Trojan horses that may have been picked up during the transmission of this message. By opening and solely relying on the contents or part thereof this message, and taking action thereof, the recipient relieves the MarkTeQ of all the liabilities including any damages done to the recipient's pc/laptop/peripherals and other communication devices due to any reason

________________________________

**Comment by AshDeeming** [comment]
Hi @mrkmaulik 
Please could you double check the AppID provided or provide the app name - If sensitive, please sent to: sinfo@reapitfoundations.zendesk.com

**Comment by mrkmaulik** [comment]
Please update on the incident. 
![image](https://github.com/reapit/foundations/assets/39938801/ff218b43-72f7-42f8-b528-f3f9f43a93f2)

**Comment by AshDeeming** [comment]
Ticked responded to via Zendesk directly
