### ISSUE TITLE
API Endpoints for Reserve Funds

### ISSUE THREAD

**Issue by katedeedman** [reapit/foundations#9143]
Hello Reapit,

Fixflo has previously requested the endpoints for reserve funds (#6035) and I understand it was placed into your Product-decision area. I wondered if you had an update on this at all? Is this likely to be something that you release? 

We have another shared enterprise client who has requested the reserved funds field is populated to match an amount entered into Fixflo. 

We've had multiple clients request this endpoint as it is currently causing a lot of double-keying between the two systems. 

Thanks in advance!

Best,

Kate

(PM at Fixflo)

**Comment by AshDeeming** [comment]
Hi @katedeedman 
This relates to a wider ticket - #6322 which is currently with our Foundations Team, as per the ticket - Accounts and related fields will be reviewed as part of a wiser discovery piece

**Comment by katedeedman** [comment]
Thank you!

The million dollar question but I don't suppose you have an idea of a
timeline do you?

Best,

Kate

**Comment by katedeedman** [comment]
Hi Ash,

I wondered if there was an update on this at all?

Best,

Kate

**Comment by AshDeeming** [comment]
Hi @katedeedman 
Apologies for the delay - please note that any updates relating to this will be via the below ticket. please feel free to subscribe to receive updates:

https://github.com/reapit/foundations/issues/6322
