### ISSUE TITLE
Intermittently missing _eTag value in GET IdentityChecks

### ISSUE THREAD

**Issue by nikolai-momot-thirdfort** [reapit/foundations#9152]
**Describe the bug**
Over the past few month, we have experienced a recurring error where the `_eTag` property of the Identity Checks model returned from the `GET /identityChecks/{id}` endpoint is undefined.

This results in a `Precondition Failed 412` error due to the invalid `If-Match` header value.

We have been circumventing this by re-fetching the Identity Checks model which usually results in an `eTag` with a proper value.

Starting around noon on May 23rd we noticed a sharp uptick this type of errors when calling the Agency Cloud API -  over 30 in the course of the afternoon.

Can you please look into the cause of this behaviour and provide strategies for remediating it going forward.

**Screenshots**
Here is the Sentry log for one of these Precondition Errors
![Screenshot 2023-05-26 at 10 51 55](https://github.com/reapit/foundations/assets/109656933/7bef6eaf-283f-48c2-ab60-3de9b4231f5a)

Here is a GCP Histogram filtering for Cloud Run logs containing "Precondition Failed"
![Screenshot 2023-05-26 at 11 11 42](https://github.com/reapit/foundations/assets/109656933/3925eb70-cc80-4836-8803-d68d2ada54d5)

**Specification**
- Project: Reapit.Services.IdentityChecks
- Write a postman test/collection (speak to PL) and page through a couple of live customer's data to ensure that all the entities do indeed have eTags. If they don't, investigate and resolve any bug that is found. If they do, there is no issue with the eTag mechanism and this is just an exercise in liaising with the developer about how this mechanism works.

**Comment by nikolai-momot-thirdfort** [comment]
> @plittlewood-rpt would adding a signed URL to an identity check constitute a change that requires a new _eTag Value?

@plittlewood-rpt Can you please confirm this?

**Comment by plittlewood-rpt** [comment]
Hi @nikolai-momot-thirdfort when you say "adding a signed URL" do you mean calling POST platform.reapit.cloud/identityChecks/signedUrl or calling PATCH platform.reapit.cloud/identityChecks/{id} with a signed URL in the payload. If the latter, yes this would update the eTag as you've made a change to the resource.

**Comment by nikolai-momot-thirdfort** [comment]
@plittlewood-rpt I am referring to using `POST identityChecks/signedUrl` - would that affect the eTag Value?

**Comment by plittlewood-rpt** [comment]
No it wouldn't, because you're not updating any of the identity check resources, you've just requesting URLs for uploading documents.

**Comment by nikolai-momot-thirdfort** [comment]
@plittlewood-rpt Would uploading a file to the signedUrl affect the eTag value?

**Comment by plittlewood-rpt** [comment]
No it wouldn't. The eTag will only change if you PATCH the resource, but remember it will also change if _anyone else_ patches the same resource

**Comment by nikolai-momot-thirdfort** [comment]
Thanks @plittlewood-rpt is there any way to check if someone else has made a change aside from comparing etags?

**Comment by plittlewood-rpt** [comment]
Hi @nikolai-momot-thirdfort I've run some checks against the databases of the customers that have your app installed and so far haven't come across any yet that do not have eTags. Have you been able to understand anything from your own investigations yet? I do strongly suspect you're just running in trouble because the eTags have changed due to an external update to the resource.
