### ISSUE TITLE
Extra Fields Request for OPL

### ISSUE THREAD

**Issue by Adkar** [reapit/foundations#9154]
Customer: Oliver Bernard Private (OPL)

We're migrating their property feed from Reapit JET to Foundations API and have a few fields I'm not sure about the naming of in Foundations API, namely:

Fields needed:
1. SituationExtra - Currently being used to display a list of amenities and using Parsedown library here to generate HTML from Markdown
2. LocationExtra (string) - looking through old Issues this is most likely pLocation
3. Available (bool)

Reason: For displaying on website

If any other information needed let me know.

Thank you

**Specification**
- Log into customer build to ascertain the field names for items 1 and 2 above
- Item 3 is likely just an educational piece as this would typically use the sales/lettings status options and/or the internetAdvertising flag. We may need to liaise with the developer to understand this requirement but it should already be being handled in the API in some capacity.

**Comment by plittlewood-rpt** [comment]
Hi @Adkar 

The Location and Situation extra fields have now been enabled for this customer. You need to explicitly request them using the `extrasField` query string parameter:

eg

`GET https://platform.reapit.cloud/properties?extrasField=pLocation&extrasField=pSituation`

and

`GET https://platform.reapit.cloud/properties/ABC123456?extrasField=pLocation&extrasField=pSituation`

Where a property has these values set, they will be returned in the `extrasField` collection in the response model for each resource.

The Available flag is governed by the property status. Please refer to the Swagger documentation for more details on understanding the options available.

Many thanks
Pete
