### ISSUE TITLE
Client Code not being sent with user information

### ISSUE THREAD

**Issue by NicolaPease** [reapit/foundations#9157]
We are having a problem ingesting a new client's information - we are not receiving the client code within the user information for Kevills.  

It looks like there may have been a recent change to the way users are created.  We created a new account to test this and where SBOX (as the client code) would normally have been created it is blank.  Can someone look into this please as a matter of urgency as we are  not able to ingest client details.

**Comment by NicolaPease** [comment]
Update - we have noticed that for the same user - sometimes the clientcode is displaying and sometimes it is not when we are ingesting their properties.  The properties were ingested on the same day.

**Comment by plittlewood-rpt** [comment]
Hi @NicolaPease - the client code does not get returned in the models from our APIs so I am not sure what problem you are reporting. Can you give us some more information about what you are experiencing please? If it is easier, you can send us requests/responses to sinfo@reapitfoundations.zendesk.com - please do not post sensitive information on this issue as it is public.

**Comment by plittlewood-rpt** [comment]
Hi @NicolaPease please let us know if you need any further assistance otherwise we'll close this issue down at the end of the week. Thanks
