### ISSUE TITLE
Add metadata support to tenancies service

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#918]
Presently, we don't support metadata for our tenancies entity. This is because we're about to release a brand new metadata mechanism with new features and functionality. We should turn out attention to this service as a good candidate to be one of the first to receive the update.

See milestone for metadata enhancements here: https://github.com/reapit/foundations/milestone/10

**Comment by plittlewood-rpt** [comment]
PRs 1941 and 1943 opened
