### ISSUE TITLE
Aberdein Considine agent import to Fixflo

### ISSUE THREAD

**Issue by charlies-fixflo** [reapit/foundations#9181]
Hi Support,

A mutual client, Aberdein Considine, has reached out to us regarding some oddities they're seeing with their agents in Fixflo - agents who left the company years ago suddenly being unarchived, agents becoming associated with the wrong AG number, etc.

Having checked the integration logs, I can see that an unusually high number of records were processed and updated via the Agent import task on Friday 19th. This would usually be caused by changes being made to the users on Thursday. Can you see any evidence of such changes on your end please? Apologies for the delayed report - I mistakenly reported this with you support team, instead of on Github.

One of the ways this affected entities in Fixflo is for the agents with Fixflo IDs AG04294212 and AG08965814. The agency reported that issues assigned to Jordan Jack were showing as assigned to Julie Justice, who left the company 15 years ago. We looked at the audit of one of these issues and saw that Jack's AG number AG04294212 became associated with Julie at some point in May, causing all his issues to show as assigned to her. As the agency reported this on Friday/Monday, I believe it's to do with this agent import. Jordan's new AG number is AG08965814. Do you use Fixflo IDs as external references on your end? Could they have gotten mixed up somehow? 

![image (1)](https://github.com/reapit/foundations/assets/135134703/4706e5d6-9e1b-4698-9704-8e07ef21181b)

![image (2)](https://github.com/reapit/foundations/assets/135134703/f6ed432b-60c2-4932-a76d-658902a8bf3f)

**Comment by HollyJoyPhillips** [comment]
Hi @charlies-fixflo, What entities are you referring too? Properties, applicants, worksorders etc 
Do you have an example AgencyCloud reference where the entity was assigned to Jordan and then to Julie? Also, we don't use FixFlo ID's. Thanks

**Comment by charlies-fixflo** [comment]
Hi Holly,

I don't think entities are being reassigned, it seems like Jordan and
Julie's profiles 'swapped' in Fixflo, causing issues and properties
assigned to Jordan to appear as though they were assigned to Julie. An
example of one of these issues is IS10458800.

For example, you can see here that, on 4th May, Jordan's Fixflo ID
is AG04294212 but by 23rd May it's AG08965814. There is no way of changing
an agent's AG number, you can only change the information associated with
that number. Jordan's reapit ID is currently listed as JOJ and Julie's as
JXJ.

[image: image.png]

If I follow the links to those agent profiles now, the AG numbers were
swapped at some point in May. The unusually large number of records
processed in the agent import task on 19th May, leads us to believe that
this is what triggered this anomaly. Can you see if these agent profiles
were updated in the days leading up to this please?

[image: image.png]
[image: image.png]

Many thanks,

[image: Alice Hill]

Charlie Smith

Customer Support Executive

Book a 10 min Q&A with me
<https://fixflo.na.chilipiper.com/book/me/charlotte-smith>
Access our Guides and Videos <http://help.fixflo.com/>


[image: Fixflo logo] <https://www.fixflo.com/>   [image: facebook]
<https://www.facebook.com/Fixflo/>   [image: twitter]
<https://twitter.com/fixflo>   [image: linkedin]
<https://www.linkedin.com/company/fixflo/>

[image: Fixflo's Referral Scheme]
<https://www.fixflo.com/referral-signup?utm_campaign=referrals&utm_medium=email_only&utm_source=gmail&utm_content=referral_program_2022_email_signature>

**Comment by plittlewood-rpt** [comment]
Hi @charlies-fixflo - I've moved this thread onto our Zendesk Portal so it's a bit easier to share information out of the public domain. Please let me know if you don't get an email.

**Comment by plittlewood-rpt** [comment]
Closing as agreed on Zendesk.
