### ISSUE TITLE
Array parsing issue with product query param

### ISSUE THREAD

**Issue by bashleigh** [reapit/foundations#9186]
When passing 1 or 2 products I get the below error response (same error occurs on GET /config/{organisationId}):

Likely caused by the .net way of interpretating array query params? Will lookup how to resolve this, might need more info on how he sent the array

Repsonse 
```json
{
      "statusCode": 400,
      "message": "Validation failed (parsable array expected)",
      "error": "Bad Request"
    }
```

400 is bad data sent?

**Comment by bashleigh** [comment]
<img width="477" alt="Screenshot 2023-06-01 at 10 13 20" src="https://github.com/reapit/foundations/assets/11574250/32f90cff-1217-47c9-ab20-398765d0c59a">

**Comment by HollyJoyPhillips** [comment]
Verified working as expected.
