### ISSUE TITLE
Change serialise method for returnType on /config endpoint

### ISSUE THREAD

**Issue by bashleigh** [reapit/foundations#9187]
GET /config/{organisationId}
- When returnType=entity, can we change the "defaultValue" property to "value" to make consuming the service easier
     - Example response:
    {
      "key": "1",
      "defaultValue": "DefaultText",
      "level": "setting"
    }
    
    
 On the GET /config/{organisationId} endpoint, add a seialise method to change the property from defaultValue to value.

**Comment by HollyJoyPhillips** [comment]
Verified as working :)
