### ISSUE TITLE
config-service GET /config/{organisationId} query is incorrect

### ISSUE THREAD

**Issue by bashleigh** [reapit/foundations#9188]
GET /config/{organisationId}/{key}
GET /config/{organisationId}
- Inheritance not working
    - When passing org ID = 2 entity is as below, when passing other IDs it just returns default values instead of inheriting from org:
        "1": {
            "inherited": true,
            "key": "1",
            "organisationId": "2",
            "franchiseId": null,
            "officeId": null,
            "userId": null,
            "value": "String",
            "settingConfigParent": {
              "key": "1",
              "defaultValue": "DefaultText",
              "level": "setting"
            },
            "level": "organisation"
          },
    - Passing orgId, franchiseId and officeId returns user level setting

**Comment by bashleigh** [comment]
<img width="864" alt="Screenshot 2023-06-05 at 15 42 42" src="https://github.com/reapit/foundations/assets/11574250/48a890f4-52cc-4f01-bbb0-8a3ee03d88a2">
@HollyJoyPhillips  All good to QA now, using the entities we created Friday you should be able to query for each level and get the correct one 


level | userId | officeId | franchiseId | orgId | value
| --- | --- | --- | --- | --- | --- |
user | test | test | test | test | user-level
office | null | test | test | test | office-level
franchise | null | null | test | test | franchise-level
organisation | null | null | null | test | organisation-level

**Comment by HollyJoyPhillips** [comment]
Hi @bashleigh, looking good :): 

**Org level (company):** 
![image](https://github.com/reapit/foundations/assets/52408607/932f4a1c-79da-4842-a567-088936f1fe42)


**Org & Franchise:** 
![image](https://github.com/reapit/foundations/assets/52408607/ba182e73-f0e0-4b19-8424-12ae6724ab71)


**Org, Franchise & Office:** 
![image](https://github.com/reapit/foundations/assets/52408607/872d534d-42da-41eb-a2ed-99c80c851303)


**Org, Franchise, Office & User:** 
![image](https://github.com/reapit/foundations/assets/52408607/c3195cc8-979e-4f59-a4fb-9b5db1eb18c1)
