### ISSUE TITLE
Verify that phone table data is updated when handling contact details updates in the contact API

### ISSUE THREAD

**Issue by david-silverink** [reapit/foundations#9195]
We are receiving the correct 201 response when posting a new applicant to the API, yet a subsequent search for the email address in question does not retrieve any matches. The associated ID is an existing contact record.

**Specification**
- Project: Reapit.Services.Contacts
- There should be nothing to do here but we need to make sure that there are no scenarios in the contacts service where we skip/omit the updating of phone table entries when handling changes to contact details. The example given below looks to have been updated via a different systems (eg AgencyCloud). If it had come through the API, we would have seen a journal entry and also a PATCH operation in the gateway logs and neither of these things exist. We should however do our due diligence to ensure there are no issues with this API before closing the issue down

**Comment by HollyJoyPhillips** [comment]
Hi @david-silverink do you have the applicant reference please?

**Comment by david-silverink** [comment]
Hi @HollyJoyPhillips it's LIM23000752 (contact)

**Comment by david-silverink** [comment]
{ "marketingMode": "buying", "active": false, "officeIds": ["LIM"], "negotiatorIds": ["EDN"], "departmentId": "S", "buying": { "priceFrom": 0, "priceTo": 99999999 }, "related": [ { "associatedId": "LIM23000752", "associatedType": "contact" } ] }

**Comment by david-silverink** [comment]
https://platform.reapit.cloud/applicants/?emailAddresses=[emailaddress]&officeId=LIM&officeId=LIM&officeId=LNH (I've removed the customer email for privacy reasons)

**Comment by david-silverink** [comment]
Thanks @HollyJoyPhillips

**Comment by RWilcox-Reapit** [comment]
Hi @david-silverink 
I can confirm that there are no scenarios that skip writing to the contact details to the phone table via the platform API.

Thanks
