### ISSUE TITLE
User name change events being sent to wrong SQS queue

### ISSUE THREAD

**Issue by plittlewood-rpt** [reapit/foundations#9197]
**Describe the bug**
In #8470 we added a mechanism to capture changes to user names which get sent to SQS and are then meant to be processed by the organisations API so we can ensure that the name of the user in Cognito is also updated. This is currently sending the message to a queue that isn't actually being polled by the Organisations service. We should correct this.

**Specification**
- Ensure handler sends events to the same queue that the internal user service reads from. We can just update the existing environment variable but should rename it in code for consistency

**Comment by joshbalfour** [comment]
Could we read their name from the id token on request rather than having to store it somewhere?

**Comment by plittlewood-rpt** [comment]
AgencyCloud displays data from our organisations service (via the SUMS Proxy) so there'd need to be a product change somewhere along the line to do it that way

**Comment by joshbalfour** [comment]
Does the SUMS proxy have access to the user's id token for that request?

**Comment by plittlewood-rpt** [comment]
Afraid not as it uses a different auth mechanism (HMAC)

**Comment by plittlewood-rpt** [comment]
@joshbalfour I've logged a separate ticket #9328 to do with a new post auth Lambda. As part of this I'd suggest moving the name change checks into this Lambda so it's a bit less chatty, and can include the auditing we spoke about today
