### ISSUE TITLE
Question r.e POST / supplierinvoice

### ISSUE THREAD

**Issue by katedeedman** [reapit/foundations#9201]
Hello Reapit! 

We're currently doing the dev work to post invoices from Fixflo to supplierinvoice. We've noticed that there's a difference between manually raising a Works Order on Reapit and posting it from Fixflo. 

1 - The image below is an invoice manually created in Reapit. Note that the Landlord information is filled in.

![image](https://github.com/reapit/foundations/assets/117754771/b884b8d6-e10b-4017-bcf3-9ce583e207f0)

2. The image below is an invoice posted from Fixflo into Reapit. Note that the Landlord information is missing. 

![image](https://github.com/reapit/foundations/assets/117754771/67e99d7b-09e2-4335-99f4-bf6eb2974374)

Can you advise what we can do to fill this in when posting the invoices?

Thank you in advance!

Best,

Kate

**Specification**
- Project: Reapit.Services.Transactions
- Ensure nomtran.lldcode is set when creating a new supplier invoice where the property has a landlord associated. There are already methods for fetching the associated property etc which should be utilised
- TDD should be used here to make sure the functionality gap is properly closed

**Comment by katedeedman** [comment]
Thanks, Pete!

Let me know how you get on.

cc @Andre Sovde ***@***.***>

**Comment by plittlewood-rpt** [comment]
HI @katedeedman this issue should now be resolved. Thanks
