### ISSUE TITLE
Update Search Widget component 

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#921]
**Summary**: We will be adding a filtering option to the search widget so we should update the format of the current search widget to add an additional option ‘Advanced Search’ and toggle feature

**Task**: To add a ‘Search Properties’ button, a toggle option for ‘For Sale’ & ‘To Rent’ and change the default text for the search field
- Change the placeholder text in the search field from ‘Town or Postcode’ to ‘e.g. London or EC1N
- Add ‘London’ and ‘EC1N’ as configurable option in the theming
- A toggle option ‘For Sale’ and ‘To Rent’ (default on ‘For Sale’) 
- Add link ‘Advanced Search’ 
- Use icon GoSearch 
- Replace ‘TO RENT’ and ‘FOR SALE’ buttons to one single button ‘SEARCH PROPERTIES’ 
- After entering a postcode if the user clicks ‘Enter’ it should ‘SEARCH PROPERTIES’ 

See mockup: 
![image](https://user-images.githubusercontent.com/52408607/79352480-d3195800-7f31-11ea-83e4-7b37d97543ce.png)

**Comment by nphivu414** [comment]
Hi  @HollyJoyPhillips , @willmcvay 
@trankhacvy  will take care of this ticket because he's currently working on issue #992 (https://github.com/reapit/foundations/issues/922). We can put this ticket in QA once @trankhacvy  finish the issue #992
