### ISSUE TITLE
Geo Diary

### ISSUE THREAD

**Issue by EckersleyWhite** [reapit/foundations#9210]
**Describe the bug**
The Geo Diary diary no longer functions, only displaying a white screen now.

**To Reproduce**
Steps to reproduce the behaviour eg:

**Expected behaviour**
Previously the app worked fine, but now we only get a blank screen. 

**Screenshots**
If applicable, add screenshots to help explain your problem. Please ensure that screenshots do not include sensitive data such as personally identifiable information. If you do have private or sensitive information you need to share that will help with aiding resolution of this issue, please email sinfo@reapitfoundations.zendesk.com adding the issue number as the subject line. Please only use this mailbox to share information you cannot add to this issue.

**Device (please complete the following information for web issues):**
 - Device: Google Pixel and Iphone
 - Browser [e.g. Chrome, Safari]

**Additional context**

**Comment by AshDeeming** [comment]
Hi @EckersleyWhite 
A recent update should now force a user's cache to clear, please could you request users clear their cache & log back in. 
 
Please see the links below that run through clearing the Cache on iOS and Android;

https://support.apple.com/en-gb/guide/iphone/iphacc5f0202/ios
https://support.google.com/accounts/answer/32050?hl=en&co=GENIE.Platform%3DAndroid


Please also note that any previously saved bookmarks or links to the app may need to be removed & then re-saved.
