### ISSUE TITLE
Webhooks not sent when adding additional buyers to an offer

### ISSUE THREAD

**Issue by jmsfwk** [reapit/foundations#9213]
**Describe the bug**
Webhooks not sent when adding additional buyers to an offer

**To Reproduce**
1. Create a property
2. Create an offer (webhook `offer.created` is sent)
3. Add an additional buyer to the offer
4. No webhook is sent

**Expected behaviour**
When adding additional buyers the `offer.modified` webhook would be sent, like for vendors.

**Comment by plittlewood-rpt** [comment]
Hi @jmsfwk when you say "add additional buyers to the offer" do you mean adding additional contacts to the associated applicant record? Please can you just expand on your reproduction steps above, specifically point 3. Thanks

**Comment by jmsfwk** [comment]
Property record > "Offers" > Double click on the name of the applicant.
 
<img width="93" alt="Screenshot 2023-06-06 095517" src="https://github.com/reapit/foundations/assets/9892048/f1ccda18-ba30-4ab8-9ce9-adbb8ac3691c">

**Comment by plittlewood-rpt** [comment]
Thanks - that info is normally only populated once an offer is accepted and the property exchanges. We'll look into why the webhook isn't firing as soon as we can.

**Comment by plittlewood-rpt** [comment]
Hi @jmsfwk we've been looking into this further and I think there's some confusion around the information that gets sent in the offer webhook. Buyer information is not included in this payload, in fact the ultimate buyer of a property isn't exposed at all from the APIs at the moment so subsequently this information isn't sent through the webhooks pipeline. You can usually infer the buyer from an accepted offer on an exchanged property, but that's the not same as what you see on the Buyer & Sale Details screen in AgencyCloud. Additional buyers added to the offer itself (which is the other tab on the same screen, and involves adding an "Extra Applicant" to the main applicant record. This is more easily handled. Can you just confirm your requirements  so we make sure we look at this in the right context?
