### ISSUE TITLE
WebHooks enabled for spencerandsener.com

### ISSUE THREAD

**Issue by NicolaTPJ** [reapit/foundations#9222]
spencerandsener.com is currently not updating. Our team have confirmed WebHooks are enabled at our end. Could you please ensure these are turned on at yours?

**Comment by plittlewood-rpt** [comment]
Hi @NicolaTPJ webhooks are indeed enabled. I was speaking to someone on our service team yesterday about this. Can you confirm your app id? It's likely a configuration issue somewhere with your webhook so I will be able to check if you can confirm your app id. Thanks

**Comment by NicolaTPJ** [comment]
Thanks Peter. The App is called Property Feeder and it is by Property Technology.

**Comment by plittlewood-rpt** [comment]
Hi @NicolaTPJ thanks for coming back to me. I've just checked our logs and we are sending these events to you. We are successfully getting a 200 response back from your configured endpoint as well

![image](https://github.com/reapit/foundations/assets/30798627/a38fb18c-b3b3-41ed-83d7-41d5abd6cb8f)

Please can you have another look at your import processes at your end? Thanks

**Comment by plittlewood-rpt** [comment]
Hi @NicolaTPJ can you confirm if this is resolved? Many thanks

**Comment by plittlewood-rpt** [comment]
As everything seems to be in order, I will close this issue down. Please open a new item if you need any further assistance. Thanks
