### ISSUE TITLE
Semi-structured 'extras' request | cntRestrictAccess=.T.

### ISSUE THREAD

**Issue by MatthewGoddard** [reapit/foundations#9227]
Please grant access to Semi-structured 'extras' field data, cntRestrictAccess=.T.

- haus & haus
- CNT.EXTRA {cntRestrictAccess=.T.}
- ![image](https://github.com/reapit/foundations/assets/10115484/8308928b-d2c3-4737-a3fd-b4d5e1e3b28a)
- To ensure that our off plan integration knows that these contacts are to be restricted

**Comment by HollyJoyPhillips** [comment]
Foundations team have agreed to proceed. It will be reviewed in our next refinement session.

**Comment by HollyJoyPhillips** [comment]
Hi @MatthewGoddard, this field has now been enabled and should be requested using the extrasField mechanism. The field name is cntRestrictAccess.

Example:

GET https://platform.reapit.cloud/contacts/CONTACTID?extrasField=cntRestrictAccess

Please allow up to 15 minutes for the configuration changes to sync across the service estate. Many thanks.
