### ISSUE TITLE
Config Service: cookie secret is generated per-execution

### ISSUE THREAD

**Issue by joshbalfour** [reapit/foundations#9233]
Doesn't scale to lambdas or multiple instances

https://github.com/reapit/foundations/blob/a2ab3a829ac7f8ea699922d35d87496f82ef1a33/packages/config-service/src/core/server.ts#L18

**Comment by willmcvay** [comment]
@joshbalfour @plittlewood-rpt You can tear it down, it's used by Un CRM but there's no plan to develop that. We can also remove the Events Service too, both in Foundations and on your side Pete
