### ISSUE TITLE
Admin billing enhancements 

### ISSUE THREAD

**Issue by neilpellowe** [reapit/foundations#9238]
Enhancements needed for internal processes to the Admin portal billing area. 

please see zendesk ref -(777)

**Comment by plittlewood-rpt** [comment]
@AshDeeming @HollyJoyPhillips I think this can now be closed after the work done in this sprint. Please can one of you confirm?

**Comment by neilpellowe** [comment]
Hi @plittlewood-rpt  - I've sent a couple of queries to Holly on this one if we could consider those before closing? Thanks.
