### ISSUE TITLE
Disable next day Viewing Request

### ISSUE THREAD

**Issue by ynwaJon** [reapit/foundations#9239]
We have a client using Reapit and they have their viewing requests plugged into Reapit. 

They have sent through the following request. 

----
We’ve had a few situations where applicants have booked viewings on Friday afternoon for Saturday and assumed the viewing is going ahead and turned up.

Are we able to blank out Saturdays for both lettings and sales after say 2pm on the Friday?
----

Do you know if this is possible?

**Comment by plittlewood-rpt** [comment]
Hi @ynwaJon apologies if I'm missing some context here, but I would have thought your app should be the thing responsible for managing whether or not it should accept viewings on given days. Presumably there's a calendar picker or something that you could just disable weekend days on?

**Comment by plittlewood-rpt** [comment]
Hi @ynwaJon thanks - I think this is one of our other web products in which case I'd need to put you in touch with our main helpdesk as this Github project is just for the Foundations product suite. Can you confirm which customer this is in relation to and I'll see you get to the right person. Thanks

**Comment by ynwaJon** [comment]
Aspire

**Comment by plittlewood-rpt** [comment]
Hi @ynwaJon I can confirm that it is possible to configure this but the agent will need to contact our service team for support, with information about what days/times they want to block out from being bookable. The agent will know the process for interacting with our service team. Hope this helps :)
