### ISSUE TITLE
API: For Sale – Available (Lost MA) and For Sale – Unavailable (Lost MA)

### ISSUE THREAD

**Issue by janchimugica** [reapit/foundations#9249]
A client has requested that any properties with the statuses below are excluded from their site:

- For Sale – Available (Lost MA)
- For Sale – Unavailable (Lost MA)

However, the only statuses available to filter in/out properties are:

preAppraisal
valuation
paidValuation
forSale
forSaleUnavailable
underOffer
underOfferUnavailable
reserved
exchanged
completed
soldExternally
withdrawn

Is there a different field/flag that identifies properties with the statuses above?

Thanks

**Comment by AshDeeming** [comment]
Hi @janchimugica 

In AgencyCloud when a property is set as Lost MA, via the Platform API you'll see the property is marked as 'isExternal'  - meaning its now marketed by another agent. 

Calling GET /properties?isExternal=false should give you the result you are wanting here.

**Comment by janchimugica** [comment]
Hi @AshDeeming,

Thanks a lot for your quick reply, really appreciate it.

That's brilliant, I can confirm that it worked.

Thank you
