### ISSUE TITLE
Data not being written back to Reapit

### ISSUE THREAD

**Issue by Speedway1** [reapit/foundations#9259]
Our client sends a message to a mobile number, the message contains a link where their client selects relevant data and this data should then be written back to Reapit, in the Follow-up/Feedback section of the appointment.

This is not happening. 
Company ID: BRL & SPD

Please can you check.

<img width="752" alt="Feedback_followup_entered" src="https://github.com/reapit/foundations/assets/100301611/a17efab9-782d-44bc-8906-1472e9d5e6c3">

**Comment by plittlewood-rpt** [comment]
Please can you provide an example payload you are sending to PATCH /appointments/{id} so we can troubleshoot? Many thanks

**Comment by Speedway1** [comment]
Hi this is the payload that I have downloaded for this particular appointment. To be clear, the viewing confirmation is created on DLL but the feedback request is a trigger that we have set up. For this particular payload, the feedback request is queued to be sent on 16/6. If you need anything else, please let us know. PS this is for Company ID: ROO
Here is payload link:
https://docs.google.com/document/d/1L2fBpef_WocTajFMaLAM6dBTcrFncGmxNb3PP3pCai8/edit?usp=sharing

**Comment by plittlewood-rpt** [comment]
Thanks for this. This looks like a webhook event though, not a request to our API to update the follow up feedback. To set the follow up feedback you need to call PATCH /appointments/{id} setting the followUp object properties according to the user feedback eg:

```
PATCH https://platform.reapit.cloud/appointments/ABC1234567

"followUp": {
    "responseId": "SML",
    "notes": "Mr Smith liked the property but thought it was too small for what he needed"
  },
```

**Comment by Speedway1** [comment]
Thanks - am referring to the team and will revert asap.

**Comment by Speedway1** [comment]
This has been resolved. Thank you
