### ISSUE TITLE
Awaiting verification - 2 month delay

### ISSUE THREAD

**Issue by BootSonEA** [reapit/foundations#9260]
**Summary**

We are in the process of creating a new Wordpress based website and wish to feed properties to the website. In order to make this possible I understand an App is required.

I have created an App called 'Boot Son App'

Image 1 attached shows I am unable to install the created App to Reapit as notification in top right explains the App is not in the Marketplace.~

Image 2 attached shows that I have submitted the App for approval and it is waiting for Verification. This has a quoted time scale of 1-2 working days; however it was first submitted on 14th April, some 2 months have passed.

Please can someone see why this process has stalled as it is preventing our website development and causing significant additional manual work.

If there is alterations required for the App, please let us know as currently in a state of limbo.

Please send any information / updates to email amy.bishop@bootandson.co.uk

I look forward to hearing from you as soon as is convenient and your assistance in resolving this issue.

**Detail and or supporting links and screenshots**
redacted

**Comment by AshDeeming** [comment]
Hi @BootSonEA 
I can see that your developer portal account is currently set to pending - meaning you are unable to submit apps for technical review currently. 

I'll flag this with our Partnerships team who will be in touch with the point of contact on the developer account (matches the same as above email)

**Comment by BootSonEA** [comment]
Hi,

This process is making me very frustrated. I am still attempting to progress each week.

I now have the Developer App approved and installed on Reapit. I have added the Customer Code, Authentication Key and Client Secret Key as required by the Wordpress Property Feed Plugin. It states success; but 0 properties listed.

I intend to raise this with the plugin developer but fear it may lead me back to here. I believe there may need to be a payment account established for the accessing of Reapit servers to pull the property details into the plugin? If so, is this the missing piece of the puzzle? How is this overcome?

Alternatively, maybe there is another stage of development / approval required?

I very much hope to get this sorted soon as been a project ongoing for me for months now.

I look forward to hearing from you, many thanks
