### ISSUE TITLE
Need additional column in enquiries API to send 

### ISSUE THREAD

**Issue by sanjayisg** [reapit/foundations#9267]
Hi There,

I am using enquiry API to add internet registration on reapit, a standard enquiries API need bellow info:
{
  "title": "Mr",
  "forename": "John",
  "surname": "Smith",
  "position": "renting",
  "enquiryType": "salesApplicant",
  "message": "Sales enquiry from Rightmove for 10 High Street, Solihull",
  "officeId": "OXF",
  "marketingConsent": "grant",
  "sourceName": "Rightmove",
  "homePhone": "01234 567890",
  "workPhone": "01234 567890",
  "mobilePhone": "07890 123456",
  "email": "example@email.com",
  "address": {
    "buildingName": null,
    "buildingNumber": "15",
    "line1": "Example street",
    "line2": "Solihull",
    "line3": "West Midlands",
    "line4": null,
    "postcode": "B91 2XX",
    "countryId": "GB"
  },
  "buying": {
    "priceFrom": 0,
    "priceTo": 0
  },
  "renting": null,
  "bedrooms": null,
  "propertyIds": [
    "OXF190012"
  ]
}
I would like to address a requirement regarding the leads we receive for our website from various sources such as Facebook, Google, email, and more. We usually run multiple campaigns on Facebook for the same pages, and it is necessary for us to categorize these leads based on their sources and campaigns separately.

To fulfill this need, I kindly request the option to add an additional column, specifically a "Campaign Name" column, in our API. This will enable us to accurately categorize and track leads based on their respective campaigns. Furthermore, it would be greatly beneficial if we could also download these categorized records from the RPS platform, specifically in the Power Report section.

Having these capabilities will greatly enhance our ability to analyze and optimize our campaigns effectively. I appreciate your attention to this matter and look forward to your support in implementing these features.

In addition to the campaign information, I would also like to inquire if it is possible to include the first comment made on an enquiry in the RPS report. This information would be valuable for us to assess the quality of the lead and make more informed decisions regarding our marketing efforts.

Having these capabilities, including the ability to download the first comment on an enquiry, will greatly enhance our ability to analyze and optimize our campaigns effectively. I appreciate your attention to this matter and look forward to your support in implementing these features.

Thank you for your cooperation. 

Sanjay Gupta

**Comment by plittlewood-rpt** [comment]
Hi @sanjayisg - my immediate response to this would be to look at adding metadata support to the enquiries API as we cannot add new fields without them being supported by AgencyCloud first. Whether this is an appropriate solution or not though depends on where you want to be able to see this additional data. As you will be aware, metadata is not visible in AgencyCloud natively, and is only available to the apps that created it. Does this sound like a workable solution, if so we will look at this further.

**Comment by sanjayisg** [comment]
Hi Ash, 

Based on my understanding, there are two key points to address. First, it is not possible to include meta data in the enquiry API as it is intended for the contact API. Second, even if we were able to include meta information somehow, it would not be exportable through the power report section in RPS. Therefore, it doesn't appear to be a viable solution.

Thank you for sharing your insights. 

Thanks,

Sanjay Gupta

**Comment by plittlewood-rpt** [comment]
HI @sanjayisg based on the above it looks like you do want to be able to access this information from within AgencyCloud.. To facilitate this, it would need a change to the core CRM before we can add this functionality to the Foundations API. As such, the customer should contact our service team or their customer success manager to discuss opening a new development request.

**Comment by HollyJoyPhillips** [comment]
As this sits with the customer to raise with our service desk we will close this ticket as it doesn't require any development from Platform.
