### ISSUE TITLE
Journal Entries

### ISSUE THREAD

**Issue by elizabethhamlin** [reapit/foundations#9282]
Hi

I would really love to be able to report on journal entries from Reapit.

For example, I cannot see how many lets have been agreed within the month as I cannot currently report on when a property has moved from a To Let status to Arranging tenancy. 

All journal entries would be great for both sales and lettings

Thanks 

Lill

**Specification**
- Project: Analytics Schema
- Consider adding a new view that deals with To Let -> Arranging Tenancy status changes in the same manner we have things like PROPERTY_SALES_WON_INSTRUCTIONS for Market Appraisal -> For Sale on sales properties. We don't want to expose the whole journal as it's very difficult to work with so we need to take each use case as it comes and build out functionality in a more controlled manner
- Spec needs re-reviewing. It may be better to work from tenancies and go backwards on this one

**Comment by plittlewood-rpt** [comment]
Hi @elizabethhamlin we deliberately aren't exposing the raw journal entries in the analytics schema because of the requirement to parse the data in them, however I understand the immediate requirement and your use case. As you'll know already we have various views in the schema that are tied to property status changes (ie PROPERTY_LETTINGS_WON_INSTRUCTIONS) and your use case lends itself to a PROPERTY_LETTINGS_ARRANGING_TENANCIES view or something similar. Altenratively an enhancement to the TENANCIES view itself to include the date of the different status changes might be more appropriate. It's something we are going to look at to just determine the best route so you can get these metrics.

**Comment by elizabethhamlin** [comment]
Hi @plittlewood-rpt 
I don't have PROPERTY_LETTINGS_ARRANGING_TENANCIES. I have refreshed the schema as well but it's not there
<img width="206" alt="image" src="https://github.com/reapit/foundations/assets/104636752/116a0404-9fb8-4a7c-bcef-247e6f18e4ef">

**Comment by plittlewood-rpt** [comment]
Hi @elizabethhamlin we haven't build it yet - sorry I was just feeding back letting you know what the plan for this item was :)

**Comment by elizabethhamlin** [comment]
Any update please?

**Comment by plittlewood-rpt** [comment]
Hi @elizabethhamlin this has not been scheduled yet no, however there is a new view introduced as part of #9357 which will give you what you want if you don't want to wait for a specific arranging tenancy status change view. The new view, which exposes all property status changes is called `PROPERTY_STATUS_CHANGES` and you'll be able to query that view for any properties that went from status X to status Y. You'll just need to refresh your data share to see it.

**Comment by elizabethhamlin** [comment]
Ooo this will help, thanks
Lill

**Comment by plittlewood-rpt** [comment]
@elizabethhamlin can you give me a couple of property references where you'd expect to see this and I'll take a look?

**Comment by elizabethhamlin** [comment]
Hi Pete

Here you go

Julian Wadden - Marple
JWA230358
17 Printers Drive, Strines, Stockport, Greater Manchester, SK6 7GT
Julian Wadden - Marple
JWA230362
4 East Vale, Marple, Stockport, Greater Manchester, SK6 6BP
Julian Wadden - Marple
JWA230407
6 Gloucester Avenue, Marple, Cheshire, SK6 6LZ
Julian Wadden - Marple
JWA230418
34 Buxton Road, Disley, Stockport, Cheshire, SK12 2EY
Julian Wadden - Marple Lettings
JWA230445
80 Church Lane, Marple, Stockport, SK6 7AW
Julian Wadden - Didsbury
JWD190011
Flat 15 Didsbury Court, Wilmslow Road, Didsbury, Manchester, M20 6AD
Julian Wadden - Didsbury
JWD190031
23 Shippey Street, Manchester, Greater Manchester, M14 6TR
Julian Wadden - Didsbury
JWD190032
11 Stephens Terrace, Manchester, Greater Manchester, M20 6WB
Julian Wadden - Didsbury
JWD190045
1 Shippey Street, Ladybarn, M14 6TR
Julian Wadden - Didsbury
JWD190050
19 Parrs Wood Road, Didsbury, Greater Manchester, M20 4WJ
Julian Wadden - Didsbury
JWD190051
7 Sarnesfield Close, Belle Vue, Manchester, M12 4PZ


[A screenshot of a computer  Description automatically generated]

Thanks

Lill

Elizabeth Hamlin MARLA
Reporting and Systems Manager
07443 188920
***@***.******@***.***>

[Text  Description automatically generated]

Lomond is a group of leading Lettings and Sales Agents across the UK. Lomond is the trading name of Chianti Holdings Ltd. Registered office address 70 St. Mary Axe, London, EC3A 8BE. Registered in England and Wales. Registered Company No. 13075482. This email is confidential and intended solely for the use of the individual to whom it is addressed. Any views or opinions presented are solely those of the author and do not necessarily represent those of Lomond. If you are not the intended recipient, be advised that you have received this email in error and that any use, dissemination, forwarding, printing, or copying of this email is strictly prohibited. If you have received this email in error please contact the sender. Finally, the recipient should check this email and any attachments for the presence of viruses. The company accepts no liability for any damage caused by any virus transmitted by this email.

**Comment by plittlewood-rpt** [comment]
Hi @elizabethhamlin the properties I've checked haven't had a status change from Market Appraisal to To Let. I've not checked them all but I'm not sure what the expectation is here? Is the problem that properties are being registered with a status of To Let so they never go through that status change?

**Comment by elizabethhamlin** [comment]
Hi Pete

Here you go

[A screenshot of a computer  Description automatically generated]

Elizabeth Hamlin MARLA
Reporting and Systems Manager
07443 188920
***@***.******@***.***>

[Text  Description automatically generated]

Lomond is a group of leading Lettings and Sales Agents across the UK. Lomond is the trading name of Chianti Holdings Ltd. Registered office address 70 St. Mary Axe, London, EC3A 8BE. Registered in England and Wales. Registered Company No. 13075482. This email is confidential and intended solely for the use of the individual to whom it is addressed. Any views or opinions presented are solely those of the author and do not necessarily represent those of Lomond. If you are not the intended recipient, be advised that you have received this email in error and that any use, dissemination, forwarding, printing, or copying of this email is strictly prohibited. If you have received this email in error please contact the sender. Finally, the recipient should check this email and any attachments for the presence of viruses. The company accepts no liability for any damage caused by any virus transmitted by this email.

**Comment by plittlewood-rpt** [comment]
Hi @elizabethhamlin any chance you can send that email to reapitfoundations.zendesk.com as the Github mail processor seems to have got rid of it!

**Comment by elizabethhamlin** [comment]
![image](https://github.com/reapit/foundations/assets/104636752/e22ca854-3812-4e9a-ab19-1b084dbc7862)
 Here you go

**Comment by plittlewood-rpt** [comment]
Thanks - think I've found where these are getting stripped out. It's due to the interchangeable terminology between Market Appraisal and Valuation. The new model is only accounting for Valuation which isn't the terminology used in your builds. Leave it with me, should have it sorted soon

**Comment by plittlewood-rpt** [comment]
Hi @elizabethhamlin the issue with those status changes missing from the PROPERTY_STATUS_CHANGES view is now resolved. I'll be adding the new view specific to To Let -> Arranging Tenancies this sprint all being well, however it needs a bit more thought as for lettings it's likely it won't just be To Let -> Arranging Tenancy that needs considering here, it's likely [Any Status] -> Arranging Tenancy that should be included as in the lettings world it's likely that new tenancies will be set up without the status going back to To Let (ie it a property might go from Tenancy Current - Available -> Arranging Tenancy etc)

**Comment by elizabethhamlin** [comment]
Hi Pete

Thanks for this however any type to Arranging is not going to be able to give the same result.

What I need is anything that is set to valuation, then moves to To Let. This then shows all of the properties that are new instructions.

We need to be able to specify the starting status and then the moved to status to be able to see what is a new let Vs a relet.

Thanks

Lill

Elizabeth Hamlin MARLA
Reporting and Systems Manager
07443 188920
***@***.******@***.***>

[Text  Description automatically generated]

Lomond is a group of leading Lettings and Sales Agents across the UK. Lomond is the trading name of Chianti Holdings Ltd. Registered office address 70 St. Mary Axe, London, EC3A 8BE. Registered in England and Wales. Registered Company No. 13075482. This email is confidential and intended solely for the use of the individual to whom it is addressed. Any views or opinions presented are solely those of the author and do not necessarily represent those of Lomond. If you are not the intended recipient, be advised that you have received this email in error and that any use, dissemination, forwarding, printing, or copying of this email is strictly prohibited. If you have received this email in error please contact the sender. Finally, the recipient should check this email and any attachments for the presence of viruses. The company accepts no liability for any damage caused by any virus transmitted by this email.

**Comment by plittlewood-rpt** [comment]
Hi @elizabethhamlin - given your requirement there, I'd recommend using the PROPERTY_STATUS_CHANGES view model data explicitly then I think as you can chain your status changes in whatever fashion you like, and we might reconsider the new view mentioned because I can see agents wanting different things from it. Does this sound sensible from your perspective, and does the PROPERTY_STATUS_CHANGES view give you everything you need to achieve that?

**Comment by elizabethhamlin** [comment]
Hi Pete

If we can get it to show Valuation or Market Appraisal as an option, then this will work. Have you added MA/Val now?

Thanks

Lill

Elizabeth Hamlin MARLA
Reporting and Systems Manager
07443 188920
***@***.******@***.***>

[Text  Description automatically generated]

Lomond is a group of leading Lettings and Sales Agents across the UK. Lomond is the trading name of Chianti Holdings Ltd. Registered office address 70 St. Mary Axe, London, EC3A 8BE. Registered in England and Wales. Registered Company No. 13075482. This email is confidential and intended solely for the use of the individual to whom it is addressed. Any views or opinions presented are solely those of the author and do not necessarily represent those of Lomond. If you are not the intended recipient, be advised that you have received this email in error and that any use, dissemination, forwarding, printing, or copying of this email is strictly prohibited. If you have received this email in error please contact the sender. Finally, the recipient should check this email and any attachments for the presence of viruses. The company accepts no liability for any damage caused by any virus transmitted by this email.

**Comment by plittlewood-rpt** [comment]
Yep that's all sorted now :)

**Comment by elizabethhamlin** [comment]
Perfect. One more questions, is there a Tenancy Status Change table?

**Comment by elizabethhamlin** [comment]
That was going to be my next question if you said know. 😊

Will do.

Thanks

Lill

Elizabeth Hamlin MARLA
Reporting and Systems Manager
07443 188920
***@***.******@***.***>

[Text  Description automatically generated]

Lomond is a group of leading Lettings and Sales Agents across the UK. Lomond is the trading name of Chianti Holdings Ltd. Registered office address 70 St. Mary Axe, London, EC3A 8BE. Registered in England and Wales. Registered Company No. 13075482. This email is confidential and intended solely for the use of the individual to whom it is addressed. Any views or opinions presented are solely those of the author and do not necessarily represent those of Lomond. If you are not the intended recipient, be advised that you have received this email in error and that any use, dissemination, forwarding, printing, or copying of this email is strictly prohibited. If you have received this email in error please contact the sender. Finally, the recipient should check this email and any attachments for the presence of viruses. The company accepts no liability for any damage caused by any virus transmitted by this email.

**Comment by plittlewood-rpt** [comment]
Hi @elizabethhamlin there is now a new view available if you refresh your data share through the Data Warehouse app called PROPERTY_LETTINGS_ARRANGED_TENANCIES which looks at all tenancies that have been arranged at any point (this looks at tenancy status NOT property status). Thanks
