### ISSUE TITLE
Deploy custom mailer lambda to Reapit Connect ANZ dev account

### ISSUE THREAD

**Issue by plittlewood-rpt** [reapit/foundations#9287]
**Background context**
Speak to DevOps to work out how we get the custom mailer Lambda out to the new Reapit Connect AWS account in ANZ

**Comment by joshbalfour** [comment]
blocked by devops

**Comment by joshbalfour** [comment]
auto-PR-thingy part of this is done https://github.com/reapit/devops-infrastructure-core/pull/277

**Comment by plittlewood-rpt** [comment]
Thanks for your help on this @joshbalfour
