### ISSUE TITLE
Blackstone Customer ID TEA-GBLC

### ISSUE THREAD

**Issue by Simon-Homeflow** [reapit/foundations#9293]
**Request**

In order for us to grant access to Semi-structured 'extras' field data, please provide the following information in this request:

- Blackstone TEA-GBLC
- Situation
-
![Blackstone](https://github.com/reapit/foundations/assets/119927358/202375f1-dd58-438b-abfd-7ac10b785c54)
-Required to display information that cannot be accessed via Foundations currently and was previously available thru BLM

**Comment by plittlewood-rpt** [comment]
Hi @Simon-Homeflow this has now been enabled. To include the Situation text in responses for this customer, use the `extrasField` query string parameter with value `pSituation` eg

`GET https://platform.reapit.cloud/properties?extrasField=pSituation` and
`GET https://platform.reapit.cloud/properties/{id}?extrasField=pSituation`

The situation text will be included in the extrasField collection where it has been set on the property resource.
