### ISSUE TITLE
Reapit Elements: Icons in card variations

### ISSUE THREAD

**Issue by craigforrest** [reapit/foundations#9303]
**Is your feature request related to a problem? Please describe.**
Currently, the design system suggests that the icons in cards should have a grey background, and having any other background colour would be a customisation

**Describe the solution you'd like**
We would like to be able to use icons that have a background colour that matches the colour of the card, so in this instance we would have a white, or no background on the icon, rather than grey:
![image](https://github.com/reapit/foundations/assets/26924168/a7e9cfe6-3097-4b97-8abb-ada05d111545)

**Describe alternatives you've considered**
This could be done outside of Elements, but SoftwareSeni are hesitant to do so as it'll require some customisation to an existing component which we are trying to avoid

**Comment by plittlewood-rpt** [comment]
@HollyJoyPhillips I think you were picking this up but I can't remember now?

**Comment by craigforrest** [comment]
No longer required following the release of Elements V4
