### ISSUE TITLE
Is it possible to patch the management fee of a tenancy?

### ISSUE THREAD

**Issue by AdamHall12** [reapit/foundations#9304]
Please take a look at our FAQ's before submitting an issue, as your question may already be covered in the documentation https://foundations-documentation.reapit.cloud/faqs

**Summary**
I cant figure out how to patch the management fee of a tenancy. I can update the property management fee but it doesn't pull through to the tenancy. Is it possible?
**Detail and or supporting links and screenshots**

**Comment by HollyJoyPhillips** [comment]
@AdamHall12 unfortunately, it's not possible as it has a direct relation to client accounts.
