### ISSUE TITLE
Look into linking federated users to an existing user profile

### ISSUE THREAD

**Issue by joshbalfour** [reapit/foundations#9321]
**Background context or User story:**
To reduce the MAU count and save us some £££

**Specification or Acceptance Criteria:**
https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-identity-federation-consolidate-users.html
https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_AdminLinkProviderForUser.html

**Comment by plittlewood-rpt** [comment]
Possible link to #9328

**Comment by joshbalfour** [comment]
Closing as will be done as part of #9328
