### ISSUE TITLE
Acaboom app - I want to download the apps but there is no option to do so

### ISSUE THREAD

**Issue by JeremyRichardson3971** [reapit/foundations#9326]
We have subscribed to Acaboom and want to make use of the Reapit integration but cannot access the Acaboom Apps on the Marketplace - there is no option to download them, just to request further information about them.

Please get back to me with a solution.

![Screenshot 2023-06-19 104422](https://github.com/reapit/foundations/assets/137315442/b1d3ff0c-f5f4-48aa-847b-7c893a4854f8)
![Screenshot 2023-06-19 104359](https://github.com/reapit/foundations/assets/137315442/81e8fa92-f3ef-4a55-97be-b890c28ceddf)

**Comment by JeremyRichardson3971** [comment]
Hi, thanks for getting back to me - please see my email sign off below for the relevant details. Let me know if you need anything else.

Kind regards,
Jeremy


<https://www.instagram.com/finecountryreigateastgrinstead/>

Jeremy Richardson | Fine & Country | Reigate & East Grinstead

E: ***@***.***

T: +44 (0)1737 789177

M: +44 (0)7539 331709

www.fineandcountry.com<https://www.fineandcountry.co.uk/reigate-and-east-grinstead-estate-agents>

Fine & Country | Reigate & East Grinstead

Chancery House, 3 Hatchlands Road, RH1 6AA

Fine & Country Head Office: 119-121 Park Lane, Mayfair, London, W1K 7AG

[http://fcmedia.propertylogic.net/email_footer/New/Line.jpg]
[http://fcmedia.propertylogic.net/email_footer/New/FB.png]<https://www.facebook.com/FineandCountry/>    [http://fcmedia.propertylogic.net/email_footer/New/Twitter.png] <https://twitter.com/FineandCountry>    [http://fcmedia.propertylogic.net/email_footer/New/LinkedIn.png] <http://www.linkedin.com/company/fine-&-country>       [http://fcmedia.propertylogic.net/email_footer/New/YouTube.png] <http://www.youtube.com/user/FineAndCountryEA>  [http://fcmedia.propertylogic.net/email_footer/New/Pinterest.png] <http://www.pinterest.com/FineCountryPin/>    [http://fcmedia.propertylogic.net/email_footer/New/Instagram.png] <https://www.instagram.com/fineandcountryhomes/>
[http://fcmedia.propertylogic.net/email_footer/New/Animated.gif]
[http://fcmedia.propertylogic.net/email_footer/New/FCBanner.jpg]<https://www.fineandcountry.com/>
[http://fcmedia.propertylogic.net/email_footer/New/Refined_sml.jpg]<https://www.fineandcountry.com/uk/refined>
[cid:10404493-cb68-4220-a1ba-0b880f0a93db]


________________________________

**Comment by AshDeeming** [comment]
Hi @JeremyRichardson3971 
We are unable to install apps on the Agency's behalf - I believe the Reapit support desk team have advised who the admin users are - One of these users will need to give you admin access or install on your behalf.

**Comment by JeremyRichardson3971** [comment]
Thanks, Ash - all clear now and I will chase up with F & C.

Kind regards,
Jeremy


  *   Property in Surrey - click here<https://www.fineandcountry.co.uk/sales/property-for-sale/surrey?lat=&lng=&country=GB&address=Surrey>

  *   Property in West Sussex - click here<https://www.fineandcountry.co.uk/sales/property-for-sale/west-sussex?currency=GBP&lat=&lng=&country=GB&address=West%20Sussex>

  *   Property in East Sussex  - click here<https://www.fineandcountry.co.uk/sales/property-for-sale/east-sussex?currency=GBP&sortBy=price-high&lat=&lng=&country=GB&address=East%20Sussex>

  *   Property in Kent  - click here<https://www.fineandcountry.co.uk/sales/property-for-sale/kent?currency=GBP&sortBy=price-high&lat=&lng=&country=GB&address=Kent>

  *   National & Regional Market Reports<https://www.fineandcountry.com/uk/market-report?dm_t=0,0,0,0,0>

Please follow us on Facebook & Instagram -

  *   www.facebook.com<https://www.facebook.com/fineandcountryreigate>

  *   www.instagram.com<https://www.instagram.com/finecountryreigateastgrinstead/>

<https://www.instagram.com/finecountryreigateastgrinstead/>

Jeremy Richardson | Fine & Country | Reigate & East Grinstead

E: ***@***.***

T: +44 (0)1737 789177

M: +44 (0)7539 331709

www.fineandcountry.com<https://www.fineandcountry.co.uk/reigate-and-east-grinstead-estate-agents>

Fine & Country | Reigate & East Grinstead

Chancery House, 3 Hatchlands Road, RH1 6AA

Fine & Country Head Office: 119-121 Park Lane, Mayfair, London, W1K 7AG

[http://fcmedia.propertylogic.net/email_footer/New/Line.jpg]
[http://fcmedia.propertylogic.net/email_footer/New/FB.png]<https://www.facebook.com/FineandCountry/>    [http://fcmedia.propertylogic.net/email_footer/New/Twitter.png] <https://twitter.com/FineandCountry>    [http://fcmedia.propertylogic.net/email_footer/New/LinkedIn.png] <http://www.linkedin.com/company/fine-&-country>       [http://fcmedia.propertylogic.net/email_footer/New/YouTube.png] <http://www.youtube.com/user/FineAndCountryEA>  [http://fcmedia.propertylogic.net/email_footer/New/Pinterest.png] <http://www.pinterest.com/FineCountryPin/>    [http://fcmedia.propertylogic.net/email_footer/New/Instagram.png] <https://www.instagram.com/fineandcountryhomes/>
[http://fcmedia.propertylogic.net/email_footer/New/Animated.gif]
[http://fcmedia.propertylogic.net/email_footer/New/FCBanner.jpg]<https://www.fineandcountry.com/>
[http://fcmedia.propertylogic.net/email_footer/New/Refined_sml.jpg]<https://www.fineandcountry.com/uk/refined>
[cid:6fd62d3d-694f-45e5-ad2f-96c9fe1da320]


________________________________
