### ISSUE TITLE
Journal Entries not being created automatically through API

### ISSUE THREAD

**Issue by raymond2323** [reapit/foundations#9327]
We have a client, who when they change various things like updating the status of a property or adding an offer(tenancy status: pending) via the UI of Reapit Cloud automatically generates Journal entries with pre-defined wording structure, without their involvement. They use these journal entries to run reports that are important to the client. 

When we replicate the same behaviour via the API, (changing the status of property for example) no journal entries are created, like they are automatically when the client does them via the UI. 

I can see that there is a journal entry endpoint in the API docs, however, my expectation would be that something changed in UI would mirror what is done via the API. 

Can you shed some light on the above and let us know what we can do in order to get these automatic journal entries created for the client?

**Comment by AshDeeming** [comment]
Hi @raymond2323 
Actions that are done via workflow in AgencyCloud are separate to the API
If a journal entry is required, this can be posted following the selected action

**Comment by raymond2323** [comment]
@AshDeeming ok.

Looking into the API for journal entries, how can I create journal entries on the property page with a journal type for tenancies?

Which journal entries will appear on the activity section of the property page, as when I used the typeID `MI` it didn't add on the activity feed of the property.

**Comment by AshDeeming** [comment]
Hi @raymond2323 
Please see the configuration endpoint, shown below (1) to check which JournalTypes a client has & then use the associatedType to associate to the relevant entity type (2)

1)
![image](https://github.com/reapit/foundations/assets/61687775/a285b9c6-e4c4-4e9d-83b6-938e63f869ff)
2)
![image](https://github.com/reapit/foundations/assets/61687775/5221fa70-a4d3-4f56-b475-ccd070d51258)

**Comment by raymond2323** [comment]
@AshDeeming 

I have looked at the Journal Entry Types but I can't marry them up on the Sandbox to what I see in the UI. 

For example on the Sandbox you have entry types of Tenancy cancelled and Tenancy Finished, but which one will show up under the Tenancy section of the Journals on the property page. See screenshot below. 

<img width="1485" alt="image" src="https://github.com/reapit/foundations/assets/17427875/f1fc6cbe-d391-4582-9f8f-ec9e7daf3920">

Also, can you please confirm how we can ensure that the Journal entries go on the activity feed of the property?

**Comment by AshDeeming** [comment]
Hi @raymond2323 

Certain action completed within AgencyCloud will have journal entries added automatically - as AgencyCloud standard functionality.

This auto journal entry does not occur when an action is completed via the API, the post to this endpoint will need to be added.

**Comment by raymond2323** [comment]
@AshDeeming - Not sure you have read my last comment, as wasn't answered with your comment above - Can you respond to my latest comment?

**Comment by AshDeeming** [comment]
Hi @raymond2323 
Please see the below which should assist with posting the entry to the property record:
![image](https://github.com/reapit/foundations/assets/61687775/b652f60a-b724-459f-b6fa-9af8b83bca14)

**Comment by raymond2323** [comment]
@AshDeeming that is not what I am asking. 

If you see my screenshot you will the journal entries against the property are allocated to different headings. Some for example have Tenancies. How do I add a journal within those headings?

Also, you have not responded to my question regarding the activity feed.

**Comment by AshDeeming** [comment]
Hi @raymond2323 
journal types can vary per client, please use the below config endpoint to call which are available ;
![image](https://github.com/reapit/foundations/assets/61687775/d4c69b2c-e65a-4d21-aad3-bf8c64ab11cc)

The activity feed and journal are one & the same, however depending on the associated type of the entry will change where this is shown i.e. Tenancy, Applicant, Property etc

**Comment by raymond2323** [comment]
@AshDeeming - As I mentioned in my first comment I have done this already, but there is no EntryType called Tenancy in sandbox which pushes that desire section. I used the JorunalEntryTypes endpoint. 

Regarding the activity feed, I tried this but when I put it on the property journal it didn't appear on the property activity feed.

**Comment by AshDeeming** [comment]
Hi @raymond2323 
Apologies if i've misunderstood the above however you meantioned that there is no EntryType for Tenancy, however this is referred to as the associatedType 
![image](https://github.com/reapit/foundations/assets/61687775/dab3f11f-342e-4bd0-a288-457c7a4b6133)

The Entry Type relates to the purpose of the entry, so Tenancy is not its own but as per the below from SBOX options, you can see the other EntryTypes - Please note that these can differ per client, hence it being stored in Configuration:
![image](https://github.com/reapit/foundations/assets/61687775/99d8beeb-d99a-4657-98b2-a007774deafb)
