### ISSUE TITLE
Create GraphQL resolvers for Appointments in GQL Server 

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#933]
**Summary:*
_The Apollo Server should have resolvers to query and mutate Appointments endpoint_

**Acceptance Criteria:**
- Should have a filterable query for paginated appointments by negotiator id
- Should be able to query an appointment by id
- Should be able to mutate a single appointment
- Should be able to create or delete a appointment

**Comment by phmngocnghia** [comment]
This task is blocked as there's no REST API to delete appointment at the moment
