### ISSUE TITLE
What is needed to make publicBrochureUrl appear in the feed?

### ISSUE THREAD

**Issue by fenty17** [reapit/foundations#9341]
**Summary**
Client: Dundas (DUN)

Question: We are seeing 'null' in the publicBrochureUrl field for the properties endpoint, even though the client has uploaded a PDF Brochure to the Details > pre-defined details section in Reapit. What else is required for the publicBrochureUrl to show up in the API response?

I have searched previous issues, documentation and FAQs but didn't find a clear answer.

**Comment by AshDeeming** [comment]
Hi @fenty17 
Do you have an example reference please? 
As per the swagger docs this is only retrievable on properties being actively marketed. 

![image](https://github.com/reapit/foundations/assets/61687775/fa751a19-6e23-4030-a683-4a4a4bd46c82)

**Comment by fenty17** [comment]
ID for the property in question is DUN230202

I'm just looking for clarification on what the client needs to set their end for the property to be considered as 'actively marketed'. internetAdvertising? selling > instructed?

**Comment by AshDeeming** [comment]
Hi @fenty17 
Please note that status will be the main trigger for properties to be marketable 

![image](https://github.com/reapit/foundations/assets/61687775/7407f027-91ee-486b-bfcc-d85afc3eab79)
those highlighted, when in AgencyCloud are called For Sale - Available & Under Offer - Available
