### ISSUE TITLE
Enable new field

### ISSUE THREAD

**Issue by Starberry-Senthil** [reapit/foundations#9344]
**Request**

Please grant access to Semi-structured 'extras' field data

- One of our client Lomond Group-Thornley Groves (LOC-GTHG) has **Investment Property** field added in Marketing Details
- Please find the screenshot of the field that we requires in the feed
![Thornley Groves Investment Properties](https://github.com/reapit/foundations/assets/137503347/0020b12a-b01e-4f8b-a889-b79316a908b7)
- We need this field enabled in the feed so that we can identify and showcase them as an investment property
Many Thanks 
Senthil

**Comment by plittlewood-rpt** [comment]
Hi @Starberry-Senthil this field has now been enabled and should be requested using the `extrasField` mechanism. The field name is `pFeatured` (it's just been relabelled for this customer).

Examples:

`GET https://platform.reapit.cloud/properties?extrasField=pFeatured`

and/or

``GET https://platform.reapit.cloud/properties/ALM110363?extrasField=pFeatured`

Please allow up to 15 minutes for the configuration changes to sync across the service estate. Many thanks
