### ISSUE TITLE
Populating property data on website before portals

### ISSUE THREAD

**Issue by tpjsupport** [reapit/foundations#9352]
Hi there, we have a mutual customer who has contacted you to make the relevant changes at your end to enable property data to populate their website before any other portal, client is urbanandrural.com. Can you contact the client and us when this is complete please? craig@urbanandrural.com

**Comment by AshDeeming** [comment]
Hi @tpjsupport 
I believe the request you may be referring to is a Reapit Support Desk ticket, which does not relate to Platform
For data to populate a clients website via the Platform, the required App will need to be installed/enabled first.

**Comment by tpjsupport** [comment]
Hi Ash, as this customer is using foundations creating a support desk ticket is pointless as they just ask us to raise it as an issue on Github, this client is on Foundations and already has our property feeder app installed.

**Comment by tpjsupport** [comment]
Hi Ash, apologies, they're looking to list properties on their website while delaying them from showing on RM/OTM etc. Is that possible? Your support desk has told our client it is, if it's not I'm happy to let them know.

Cheers

**Comment by AshDeeming** [comment]
Hi @tpjsupport 

The Platform API can be used to feed/update properties asap. 

With regards to portal feeds, these can be 'delayed' however this request will need to go through the Reapit Support Desk for confirmation & setup
