### ISSUE TITLE
Paramount additional fields request

### ISSUE THREAD

**Issue by Simon-Homeflow** [reapit/foundations#9354]
Request

- Paramount - Reapit Customer ID - PAR
- Fields required:

1. Property Highlights
- <Broadband>
- <Quick Highlights>
- <Points of Note>

![image](https://github.com/reapit/foundations/assets/119927358/d5cd83ee-7c2f-429c-b279-b7bb972a2cc8)

2. Council Tax per Annum
![image](https://github.com/reapit/foundations/assets/119927358/b05e3ebe-4b3c-4cc7-9446-5af3b84cd9e1)

Data required to display information that cannot be accessed via Foundations currently and was previously available thru BLM

**Comment by plittlewood-rpt** [comment]
Hi @Simon-Homeflow  these fields have now been enabled and should be requested using the extrasField mechanism. The field names are as follows:

Highlights: `pPropHighlights`
Council Tax Per Annum: `pRentalValue` (I'm not sure why the field is called this, I suspect at some point an existing field has been relabelled. I'll flag it with our service desk but for now this is the correct field)

Examples:

GET https://platform.reapit.cloud/properties?extrasField=pRentalValue&extrasField=pPropHighlights

and/or

``GET https://platform.reapit.cloud/properties/PAR200433?extrasField=pRentalValue&extrasField=pPropHighlights`

Please allow up to 15 minutes for the configuration changes to sync across the service estate. Many thanks
