### ISSUE TITLE
Unable to register a developer account

### ISSUE THREAD

**Issue by SofttrainCloud** [reapit/foundations#9356]
**Describe the bug**
Trying to register on the developer portal here...

https://developers.reapit.cloud/developer/register/

But getting the following error...

Unable to create new organisation for developer: 63488d8a-b40b-40b6-bbe8-2c0c8ab3c4cd

**To Reproduce**
Steps to reproduce the behaviour eg:
1. Go to https://developers.reapit.cloud/developer/register/
2. Enter details
3. Click [Register] button
4. Scroll to bottom of Terms and Conditions page 
5. Click [Accept] button
6. Error message appears as per description

**Expected behaviour**
Register the developer account

**Screenshots**
![image](https://github.com/reapit/foundations/assets/137888677/8935f3af-717a-454d-a336-c50db6d5a282)

**Device (please complete the following information for web issues):**
 - Device: PC
 - OS: Windows 10
 - Browser: Edge
 - Version:  114.0.1823.58

**Additional context**

**Comment by plittlewood-rpt** [comment]
Hi @SofttrainCloud you should now be able to register. Thank you for highlighting this issue to us.

**Comment by SofttrainCloud** [comment]
Hi @plittlewood-rpt  - I am now able to register, but unable to login to the AgencyCloud Developer version.  Please see attached screenshot..

![image](https://github.com/reapit/foundations/assets/137888677/077894e1-ab14-41a5-a2fb-0752597f41aa)

**Comment by plittlewood-rpt** [comment]
Hi @SofttrainCloud  is this error still occurring?
