### ISSUE TITLE
Add view model of property status changes

### ISSUE THREAD

**Issue by plittlewood-rpt** [reapit/foundations#9357]
**Background context**
Logged from #8770 

To give the most flexibility for reporting on property status changes in the analytics schema, and to support the plethora of different ways our customers use the CRM, we should look to expose a simple view of property status changes.

**Specification**
- Project: Analytics Schema
- Add new view PROPERTY_STATUS_CHANGES with the following fields:
  - ID - use same mechanism to build a unique key as in the PROPERTY_MATCHES view
  - PROPERTY_ID
  - PROPERTY_CODE
  - OLD_STATUS - parse entry text
  - NEW_STATUS - parse entry text
  - CHANGED_AT
  - _CUSTOMER_ID
  - _LAST_SYNCH_AT
- View data should be populated from all journal status change entries, and the old/new text should be parsed
- Consider using a status lookup list to protect us from exposing badly converted data. It's better that this is omitted than included in the dataset
- Remember to update documentation and SSM param with new view

**Comment by ErnstHavenga001** [comment]
@plittlewood-rpt Thank you very much for raising this ticket on our behalf

**Comment by HollyJoyPhillips** [comment]
Agreed with Foundations team it would be a good feature to include

**Comment by plittlewood-rpt** [comment]
@ErnstHavenga001 just to let you know this new view is now available which should give you all the flexibility you need for reporting on status changes. The updated documentation will update in our production environment shortly, but if you log onto the data warehouse app and click Refresh Share, you should see the new view PROPERTY_STATUS_CHANGES added to your warehouse.
