### ISSUE TITLE
Intermittent Time-Outs

### ISSUE THREAD

**Issue by rlockett1121** [reapit/foundations#9362]
**Describe the bug**
We are getting intermittent time-outs when querying reapit's API

**To Reproduce**
This happens when we query "https://platform.reapit.cloud/contacts" with the following parameters:
- modifiedFrom: "2023-06-27T11:03:07+00:00"
- fromArchive: "true"
- pageSize: "100"
- pageNumber: 1
- embed: "relationships"

**Additional context**
This is an intermittent issue, and re-running the query after a few seconds is successful, more often than not.

**Specification**
- Project; Reapit.Services.Contacts
- Find timeouts in the logs to understand which customer is affected (likely an enterprise customer or one with a larger dataset)
- Using the recent update to the enquiries API consider whether a refactor of the repository is suitable/warranted to run two separate UNION'd queries which will force the database to use the right indexes which is normally the cause of these timeouts

**Comment by rlockett1121** [comment]
Hi Pete,

The issue is with our customers MNS and RYD.

Let me know if you need anything else.

Thanks



Rory Lockett  
| Web Developer
T: 0113 258 2657 
.
This E-Mail and the information contained in it and in any attachments are confidential and may be privileged. If you have received this E-Mail in error please notify us immediately. You are not authorised to, and must not disclose, copy, distribute or retain this E-Mail or any part of it. Northern Estate Agencies Group does not enter into any form of contract via this medium, nor is our staff authorised to do so on our behalf. Any opinions expressed in the E-Mail are those of the sender, and will not reflect the opinions of Northern Estate Agencies Group unless specifically stated.
Northern Estate Agencies Limited, Registered Office: Leigh House, 28-32 St Pauls Street, Leeds, LS1 2JT. Registered in England No: 2546381

**Comment by plittlewood-rpt** [comment]
Hi @rlockett1121 I've just pushed out an update to the contacts API that should hopefully resolve this as it alters how the query behaves when using the modifiedFrom filter to make better used of indexes on the database. I would recommend always coding for some kind of failure as we can't guarantee you'll _never_ get some kind of error, but this should alleviate the problem. I'll keep an eye on things at this end as you should see a general improvement in response times when using these filters.
