### ISSUE TITLE
Webhooks not firing

### ISSUE THREAD

**Issue by stebrough** [reapit/foundations#9366]
**Describe the bug**
A webhook has been set up on our app "Integrated Interest Email Marketing v2.0" for "Conveyancing Modified", and we have received no calls, even though I can see some have updated.

**Comment by AshDeeming** [comment]
Hi @stebrough 
Could you confirm if this relates to SBOX or live data please?

**Comment by stebrough** [comment]
Hi @AshDeeming it's live data

**Comment by plittlewood-rpt** [comment]
Hi @stebrough I've just had a look at this and can see that we are sending these events, however a large volume of them are being met with a 500 Internal Server Error from your endpoint. You should be able to see this in the Transaction Logs in the Developer Portal under API -> Webhooks -> Transaction Logs. Please can you have a look at your end and let us know if you need any further assistance. Incidentally it does look like we've sent a small handful of events to you successfully.

**Comment by stebrough** [comment]
Hi @plittlewood-rpt, I was using Transaction Logs to look into this earlier, but it shows no records

**Comment by stebrough** [comment]
![image](https://github.com/reapit/foundations/assets/40298446/fef1c7b2-053f-4919-8697-c4cca2863dd3)

@plittlewood-rpt

**Comment by stebrough** [comment]
Hi @plittlewood-rpt I managed to find a call when not filtering in transaction logs. 

reapit-webhook-logs-payload-2023-06-28T11_29_13.527+00_00

This payload contains no "New" object. I've set the webook to ignore _tag changes though?

**Comment by plittlewood-rpt** [comment]
When you get an event with no `new` object, that's indicative that a user has archived or deleted the entity. As part of this process, the modified date and eTag do change, so you would still receive that event. Hope this helps

**Comment by stebrough** [comment]
@plittlewood-rpt thanks for clarifying. Can you confirm why when I filter for the correct event in the transaction logs, nothing shows?

**Comment by plittlewood-rpt** [comment]
I'll need to look at that so leave it with me and I'll come back you - the filters should work, and they do seem to for other topics, so I'm not sure what's going on here

**Comment by plittlewood-rpt** [comment]
Logged #9840 to review filters
