### ISSUE TITLE
Use Previously Let Price field

### ISSUE THREAD

**Issue by Simon-Homeflow** [reapit/foundations#9370]
- We represent Paramount - Reapit customer ID PAR
- Paramount would like to use Previously Let Price field for triggering a "Gold Standard" label (field suggested by Reapit - not sure who)
- ![image](https://github.com/reapit/foundations/assets/119927358/0e18efcd-67cb-4df5-bc37-0c1d8a84f7f6)
- Use case is to supply pass through extra data to promote exceptional properties and cannot be done with current feed and key driver to move to Foundations

**Comment by plittlewood-rpt** [comment]
Hi @Simon-Homeflow this has now been enabled for you and you can request the field using the `extrasField` query string parameter. The field you should request is `pPlet` 

Examples:

`GET https://platform.reapit.cloud/properties?extrasField=pPlet`

and/or

`GET https://platform.reapit.cloud/properties/{id}?extrasField=pPlet`

Multiple extrasField parameters can be provided to request more than one field (when enabled). Please allow up to 15 minutes from receipt of this message for the changes to synchronise across our API estate. Thanks
