### ISSUE TITLE
Description field request

### ISSUE THREAD

**Issue by joejourney** [reapit/foundations#9374]
Representing Ashtons (ASH).

Require access to the _Description_ field under _Marketing Info > Extra Descriptions_:

<img width="699" alt="Screenshot 2023-06-29 at 10 06 30" src="https://github.com/reapit/foundations/assets/89912054/068df07f-37d7-4f34-b214-0fed98b2bcec">

Required to display more information when viewing a property on the Ashtons website.

Please could you advise what name this field would be when accessed through using the `extrasField` request parameter.

Thank you.

**Comment by ashindey12** [comment]
Hi @joejourney we have provided the required access and the extras descriptions filled can be accessed by "properties.pProperty, properties.pDescription, properties.pLocation, properties.pLongAd"
