### ISSUE TITLE
Reapit + Wordpress

### ISSUE THREAD

**Issue by JulianSidekick** [reapit/foundations#9375]
I need to connect a Reapit account with Wordpress so the properties listed there can be posted on Wordpress too. Can you please give me guidance as it looks I have to do the whole thing myself because you don't have any plugins or even a XML export of the properties listed.

Thanks

**Comment by joejourney** [comment]
I'm not associated with Reapit, but when we were scoping out a WordPress solution we looked at the [WP Property Hive](https://wp-property-hive.com/) plugin. They have a [Property Import](https://wp-property-hive.com/addons/property-import/) addon that can synchronise property data from the Reapit Foundations API.

To do this, you'll need to create an app in Reapit's AppMarket, even if you're just trying to retrieve data for your own company. There's more info on this here - https://foundations-documentation.reapit.cloud/troubleshooting/accessing-customer-data

**Comment by AshDeeming** [comment]
Hi @JulianSidekick 
The API can be used to pull data however there are apps in the AppMarket that offer wordpress plugin tools
