### ISSUE TITLE
Intermittent Timeouts (Again)

### ISSUE THREAD

**Issue by jaetoole** [reapit/foundations#9384]
**Describe the bug**
Server error: `GET https://platform.reapit.cloud/properties?modifiedFrom=2023-07-03T11%3A00%3A11%2B01%3A00&embed=images&marketingMode=selling&limit=50&officeId=ACR&officeId=CLI&officeId=BLA&officeId=GRH&officeId=WHA&officeId=FIN&officeId=AUC` resulted in a `504 Gateway Timeout` response:
{"message": "Endpoint request timed out"}

**Additional context**
Seems to be intermittent across foundations. We have a similar issue with #9362 

**Specification**
- Project: Reapit.Services.Properties
- As part of #8910 we made some improvements to the query performance when modified filters were used. We should look at introducing this in the properties API. The PR for the previous service is 6260

Off the back of this ticket we will also look at improving the embed performance to reduce the number of calls each embed operation needs to make. Combining these improvements should yield noticeable results

**Comment by plittlewood-rpt** [comment]
Hi @jaetoole - we'll dig into this to try and understand what's going on, however it's likely that this is down to the number of images that end up being embedded in that particular request. As you know the embed is a convenience mechanism to negate the need for you to make calls to the respective APIs yourself, however under the hood these calls still happen in an orchestration layer that sits on top of the APIs. It's worth pointing out that you won't actually be getting 50 results back as `limit` should be `pageSize` but it's unlikely that will make any difference as you'll actually be getting less than 50 results back right now. Finally, is this against MNS or RYD datasets?

**Comment by jaetoole** [comment]
Hi @plittlewood-rpt,
This is against RYD, it has also only recently started happening - it's been fine for months!

**Comment by plittlewood-rpt** [comment]
@jaetoole  the way the queries are executed when using the modified parameters has now been updated to hopefully address this. It's just gone out to production so I'll keep an eye on things this end but the latency of the responses from this service should be reduced.
