### ISSUE TITLE
Renewal negotiations checks are appearing in Agreement Section in AC

### ISSUE THREAD

**Issue by abrahamseni** [reapit/foundations#9387]
**Describe the bug**
When creating Renewal negotiations, the checks are somehow appearing in the Responsibilities card in Renewal Negotiations -> Agreement -> Responsibilities

**To Reproduce**
Steps to reproduce the behaviour in Agency Cloud, eg:
1. Go to 'Lettings'
2. Search and select Tenancy with the current status
3. Click on Financial & Extensions tab
4. In the Extensions/Alterations/Fees, click the '+' button
5. Add renewal negotiations and click Accept
6. Inside Renewal negotiations window, Renewal Letter section -> Tenant, click 'Not Sent'
7. change the value to 'Sent'
8. Inside Renewal negotiations window, Renewal Letter section -> Landlord, click 'Not Sent'
9. change the value to 'Sent'
10. Repeat steps 6 to 9 but with the value 'Reply Received'
11. In the References section -> Status, change the value to 'Received'
12. Click the save icon on the top right of the 'Renewal negotiations' window
13. Exit the Renewal negotiation window
14. Exit the Tenancy window
15. Search and select the tenancy again OR open the tenancy from Properties -> Tenancy
16. Click on Financial & Extensions tab
17. In the Extensions/Alterations/Fees, double click the renewal negotiations 
18. Click on Agreement tab
19. Responsibilities section displays renewal negotiations checks.

**Expected behaviour**
Responsiblities section should be clear and not showing any renewal negotiations checks

**Screenshots**
![Screenshot 2023-07-04 093635_1](https://github.com/reapit/foundations/assets/94949137/b83a28b3-e7a6-4ae7-b0ae-416b164f9776)

**Comment by RLAV1** [comment]
Albeit this has only recently been logged Savills have confirmed this is urgent to be completed and if we have a timeframe or eta on completion?

**Comment by plittlewood-rpt** [comment]
Hi @abrahamseni your report suggests this is a bug solely in AgencyCloud and not to do with the API as none of your steps mention any interaction with the Foundations APIs. Please can you confirm if this is the case so I can direct it to the correct team?

**Comment by abrahamseni** [comment]
Hi @plittlewood-rpt , honestly I am not sure how the API interacts with AC, but I do think this is a bug within AC.

**Comment by MatthewGoddard** [comment]
@abrahamseni Have you managed to recreate this without opening the app i.e. just using AC?

**Comment by plittlewood-rpt** [comment]
Thanks both. There is no mention of opening the app in the recreation steps hence my question.

**Comment by abrahamseni** [comment]
> @abrahamseni Have you managed to recreate this without opening the app i.e. just using AC?

Yes, I test it when not opening our app from AC, and the checks appear in the Responsibilities panel card. not sure why.

**Comment by plittlewood-rpt** [comment]
This has been confirmed as a bug in AgencyCloud and will be logged with the appropriate team. I will provide the internal bug reference shortly once I get it back from the team.

**Comment by plittlewood-rpt** [comment]
Internal bug reference ACT-412

**Comment by HollyJoyPhillips** [comment]
This has been fixed by the AgencyCloud team in version 12.167.1
