### ISSUE TITLE
searchTenancies endpoint error for customer 

### ISSUE THREAD

**Issue by andytait** [reapit/foundations#9390]
**Background context**

For a particular Reapit user we **consistently** receive the following error message, when using the `searchTenancies` endpoint.

Example cURL request:

```shell
curl --location --request GET 'https://platform.reapit.cloud/tenancies?propertyId=LET170170' \
--header 'api-version: 2020-01-31' \
--header 'reapit-customer: KEA' \
--header 'Authorization: <REDACTED>'
```

Returns:

```json
{"statusCode":500,"dateTime":"2023-07-04T08:45:26.3990797Z","description":"An unexpected error has been encountered when fulfilling this request. This incident has been logged and will be investigated. Please try again."}
```

Can you advise on what the root cause of this is?

Thanks!

**Comment by plittlewood-rpt** [comment]
Likely related to #9082 - will need to run this against a couple of datasets encountering this error

**Comment by plittlewood-rpt** [comment]
Hi @andytait I've got to the bottom of this and there'll be a patch out today
