### ISSUE TITLE
Change Tenancy Deposit Type from API

### ISSUE THREAD

**Issue by abrahamseni** [reapit/foundations#9394]
Hi,

Is it possible to read and change Tenancy Deposit Type from the API ?

Currently, there is only deposit `heldBy` and `sum` that appear in `/tenancies`

![Screenshot 2023-07-05 023832](https://github.com/reapit/foundations/assets/94949137/50a10bb5-ed45-439a-9422-c50c8ba226db)

**Specification**
- Project: Reapit.Services.Tenancies
- Update `CreateTenancyDepositModel` and `UpdateTenancyDepositModel` and associated downstream commands etc as follows:

```
"deposit": {
       "heldBy": "landlordsAgent",
	
	// The number of weeks or months rent collected as the deposit on the tenancy
	"period": 5 -> TEN.DPSTTIMES
	
	// The type of deposit
	"type": "weeksRent" | "monthsRent" | "fixedSum" | "guarantee",  -> TEN.DPSTTYPE

       "sum": 675.75
  },
  
```

- Both POST and PATCH should be supported however, once tenancy is current these values should be immutable

**Validations**
- When posting, type == weeksRents || monthsRent, period must be a >= 0
- When posting, type == fixedSum || guarantee, sum must be >= 0
 
**Behaviours**
- When posting and patching, if the period has been set AND a sum is provided, make sure that the sum matches what rent * period equates to
- When patching it should NOT be possible to update these values when the tenancy status is current (or further ie finished)

**Comment by HollyJoyPhillips** [comment]
Foundations approved. Note to consider for validation: 

There are some legal restrictions on the max deposit that we should review/include in the validation if not already considered. 

Legally deposits are capped at five weeks’ rent where the annual rent is less than £50,000 and six weeks’ rent where the annual rent is £50,000 or more
