### ISSUE TITLE
Property not being pulled from Foundations

### ISSUE THREAD

**Issue by tpjsupport** [reapit/foundations#9395]
Hi there, this is for Aspire Balham, (BID = BLM, Office ID - AEA), they have one  particular property, id BLM230202 that is not appearing on their site and we have no history in our logs to show that it's ever been made available, are you able to see if there's anything obvious that's causing this? Many thanks

**Comment by AshDeeming** [comment]
Hi @tpjsupport 
The property referenced above appears to be in an incomplete state.
Please also note marketingMode = sellingAndLetting

**Comment by tpjsupport** [comment]
Hi Ash, thanks for getting back to me, they're going to take this up with support. I have another one missing which is marked as available, RPT210051 for branch FLS. Would you mind having a look at that one too? Thanks

**Comment by AshDeeming** [comment]
Hi @tpjsupport 
Please note that the property ref RPT210051 - is currently set as Market appraisal with no price set etc.
