### ISSUE TITLE
Add EPC letter ratings to EPC model

### ISSUE THREAD

**Issue by AdamHall12** [reapit/foundations#9396]
**Request**

Rettie & Co
We need access to the extras fields below:

pHipEer 
pHipEerPot  
pHipEir
pHipEirPot
pEPCRating 
pCouncilTaxBand

**Specification**
- Expose pEPCRating for this customer
- Project: Reapit.Services.Properties
- Add properties `string eerRating` , `string eirRating`,  `string eerRatingPotential` , `string eirRatingPotential` to PropertyEpcModel. This should be set to the calculated rating inferred from the current/potential Energy Effiency and Environment Impact values respectively. Build a suitable method to calculate these (there is an example in the desktop codebase on the Property object)

```
"epc": {
    "exempt": false,
    "eer": 45,
    "eerRating": "B",
    "eerPotentialRating": "A",
    "eerPotential": 71,
    "eir": 53,
    "eirRating": "A",
    "eirPotentialRating": "A",
    "eirPotential": 81
 },
```

No changes needed to write models as these are inferred

**Behaviour**
- Build EPC calculator extension method that takes the value of one of the four ratings and returns the appropriate rating's letter
- Where the property's semi structured field contains pEPCRating, this should be used explicitly for eerRating ONLY, the other 3 values should always be calculated (this covers our Scottish customers with the scottish EPC window)

**Comment by plittlewood-rpt** [comment]
Hi @AdamHall12 most of what you need above is already available.

pHip* fields are exposed under PropertyModel.Epc:

```
 "epc": {
    "exempt": false,
    "eer": 45,
    "eerPotential": 71,
    "eir": 53,
    "eirPotential": 81
  },
```

The council tax band is exposed under `PropertyModel.councilTax`

We will discuss inclusion of the actual EPC rating more generally in our next refinement session tomorrow, however there aren't many systems that actually explicitly store this as it's inferred from the energy effiency/environment impact rating values. In the meantime I have enabled this field so you can request it using the `extrasField` query string parameter. The field you should request is as above (`pEPCRating`) and can be used alongside other existing extrasField query string parameters. Examples:

`GET https://platform.reapit.cloud/properties?extrasField=pMyField&extrasField=pEPCRating`

and/or

`GET https://platform.reapit.cloud/properties/{id}?extrasField=pMyField&extrasField=pEPCRating`

**Comment by AdamHall12** [comment]
Thanks Pete, much appreciated

**Comment by HollyJoyPhillips** [comment]
Foundation approved. This ticket will be re reviewed in our next refinement session.

**Comment by plittlewood-rpt** [comment]
Hi @AdamHall12 this change has now gone out to production. Please let me know if you have any issues with the behaviour.
