### ISSUE TITLE
Unticked Follow Up and Followed Up states between AC and Appointment Service

### ISSUE THREAD

**Issue by ss-dimasm** [reapit/foundations#9398]
**Summary**
Diary appointment in AC have possibility to untick the "Follow Up" and "Followed Up" tick boxes, how could we know the status of "follow up" and "followed up" in single appointment with unticked states in the appointment service?

In [this comment](https://github.com/reapit/foundations/issues/9012#issuecomment-1549176790) we're only able to read the appointment data between "Follow Up" or "Followed Up" states by reading the `followUp.due` value. In this case, both tick boxes are untick-so the `followUp.due` in appointment service has `null` value, and then we would mark that appointment to be "Followed Up" (actual data still not followed up yet, because both tick boxes in AC are untick)

**Detail and or supporting links and screenshots**
![image](https://github.com/reapit/foundations/assets/96416644/e2eef270-febb-496d-a36d-50624d75fac5)

**Comment by plittlewood-rpt** [comment]
Hi @ss-dimasm I've had a look at this and I think there's a weird memory related bug in AgencyCloud that might be skewing your perception of what's going on here.

The "Followed up" flag isn't stored anywhere in the database, it's just inferred from the presence of data in other fields, and you can (and should) do the same inference from the API also.

When followUp.duedate has a date, the appointment is not followed up
When followUp.duedate does NOT have a date AND there is either a value in followUp.responseId or followUp.notes, the appointment is followed up.

There is definitely some odd behaviour in Agencycloud where the Followed Up checkbox doesn't update properly unless you close the appointment and refresh the diary view. I'll get this logged with the relevant team.

Hope this helps
