### ISSUE TITLE
Contacts Consent Not Matching Reapit Categories

### ISSUE THREAD

**Issue by jaetoole** [reapit/foundations#9407]
**Describe the bug**
You only have 3 consent options in Foundations, but you have 5 in Power Reports. You're consent given mapping in foundations is actually mapping to explicitly given in Reapit with no option to fetch the correct 'given' (contacts that are explicitly consent given or assumed consent prior to 2018).

We need a way to access given and not explicitly given which is the behaviour it currently does.

---

MNS should have 80,000 contacts falling under 'Given' and not 20,000 which fall under explicitly given.

**Specification**
- Project: Reapit.Services.Contacts
- Add additional query string parameters to GET /contacts `marketingConsentFilterType` with possible values `assumed/explicit`
- `marketingConsentFilterType` must not be given without the `marketingConsent` query string parameter
- When `explicit` the existing behaviour applies, and we only return contacts that have been explicitly given the value specified in `marketingConsent`
- When `assumed` new behaviour applies as follows:
  - When `marketingConsent` query string parameter is 'given', return contacts whose consent is given OR the contact was registered before 25/05/2018 and consent is not asked
  - When `marketingConsent` query string parameter is `denied`, return contacts whose consent is explicitly denied OR the contact was registered on or after 25/05/2018 and consent is not asked
- Ensure appropriate commentary on new query string parameter to explain the behaviour
- The above approach means we can release this without it being a breaking change
- Run tests against MNS database to make sure the numbers match up with AgencyCloud
- Ensure adequate test coverage, including records registered on the threshold date of 25/05/2018

**Comment by AshDeeming** [comment]
Hi @jaetoole 

I'm aware of the 3 options, as below - could you confirm what additional ones you require? 

![image](https://github.com/reapit/foundations/assets/61687775/bacc006d-932b-4941-8668-fe5776b7df69)
![image](https://github.com/reapit/foundations/assets/61687775/f2fd156e-f900-4162-a26e-282803c5289b)

**Comment by jaetoole** [comment]
@AshDeeming 
<img width="593" alt="image" src="https://github.com/reapit/foundations/assets/61322528/28b3f6c2-9a27-48ab-ae8d-016068b4419d">

I'd ideally expect to see these columns to save me making 2 separate requests.

**Comment by jaetoole** [comment]
I'll run this as 2 separate requests to save time however, it would be good to have some concrete reflection of statuses. Given seems to mean different things
