### ISSUE TITLE
Need end point to integrate enquiry forms with ReapIT 

### ISSUE THREAD

**Issue by vandithpragallapati-cbre** [reapit/foundations#9414]
Please take a look at our FAQ's before submitting an issue, as your question may already be covered in the documentation https://foundations-documentation.reapit.cloud/faqs

**Summary**
Planning to integrate our website(https://www.cbreresidential.com/uk-resi/properties/details/GB-ReapIT-cbrrps-BSL200116/exeter-mansions-106-shaftesbury-avenue?view=isLetting) with your CRM for the purpose of form leads

**Detail and or supporting links and screenshots**

We are planning to integrate the Global Listings Enquiry forms with ReapIT. For that, I have gone through the entire documentation of ReapIT in the following link https://foundations-documentation.reapit.cloud/api/api-documentation. But I am not able to find the correct API endpoint to send the required data.

Can you please provide the supporting documentation link and API and payload for the same?

**Our website form looks like below :**
![image](https://github.com/reapit/foundations/assets/99729072/9ce17615-5c45-4a08-a169-8173fd9e05a3)

**Comment by vandithpragallapati-cbre** [comment]
I am trying to access Swagger, but it's asking for a login. Can you suggest to me where I can register?

**Comment by AshDeeming** [comment]
Hi @vandithpragallapati-cbre 
A developer account will be required, please see the link below & ensure you select the relevant option; https://developers.reapit.cloud/select-role
