### ISSUE TITLE
No way to download Desktop Developer when the developer subscription is already active

### ISSUE THREAD

**Issue by MarcinuB** [reapit/foundations#9416]
Hi Team.

I have an active desktop developer licence and I'm trying to find the way to download the setupdev.exe install file. I was trying to go through the subscribe route - but it doesn't show me a link to the file:
![image](https://github.com/reapit/foundations/assets/8589350/e79e0b56-4a24-4bbf-bed2-e71ec643ec4c)

Can you let me know where I can get a link to the install file. It would be nice if that would be available somewhere in the Developer Portal.

Thank you

**Specification** 
- If an existing subscription is present, render the modal to allow the user to download a copy of the developer edition 
- BE error: Unable to create subscription. An identical subscription is already active.
- Render the following message (we may already have code to support this): 
![image](https://github.com/reapit/foundations/assets/52408607/7f5a7ae2-7e1f-42bb-8a8d-42c27a6cd771)

- Modal Title: Active Subscription
- Text: An active subscription for your user account already exists, if you require a copy of the Developer Edition, please click ‘Download’ below.

**Comment by AshDeeming** [comment]
Hi @MarcinuB 
Once the confirm option, from the above screenshot, is selected, the download should start - Please confirm you are using a windows OS?

**Comment by MarcinuB** [comment]
Hi @AshDeeming .

Yes I'm using Windows 11. Once I click confirm - I can see the notification showing about the subscription already exists, but nothing else is happening.

**Comment by AshDeeming** [comment]
Hi @MarcinuB 
Thank you for confirming. 

With regards to the subscription, there should not be a double charge however I'll make the relevant teams aware to ensure there are no discrepancies

**Comment by MarcinuB** [comment]
Thank you @AshDeeming 
Also two suggestions on the subject: 
1. When the subscription is active - I think there should be juts a link to download somewhere (maybe even on a subscriptions list in settings). It's not the first time I have to download that install file and everytime I'm worried that I will create a double subscription. 
2. The desktop page (https://developers.reapit.cloud/desktop) is hard to find. It's not there in the sidebar and I keep forgetting where the link is in the docs.

Thanks

**Comment by HollyJoyPhillips** [comment]
This has now been released to production.
