### ISSUE TITLE
Semi-structured field request

### ISSUE THREAD

**Issue by MarcinuB** [reapit/foundations#9421]
Hi Team.

Can I ask for granting us access to the below:

    Customer: Savills
    Field required: pSorrounds, pBERRating
    Use case: to get the data from that field to populate brochure.

Thank you

**Specification**
- Enable fields above. Check spelling of pSorrounds in System Config -> Property Descriptions
- Check a few examples of properties in Ireland in the Properties API against what's AgencyCloud to ensure currency/price are coming out correctly

**Comment by MarcinuB** [comment]
Hi @AshDeeming @HollyJoyPhillips.

I have additional extras fields to add to this request: 
pBERRating, pPriceC, pCurrency. 
Let me know if you can handle it under the same ticket or do you need me to create a new one.

Thank you

**Comment by HollyJoyPhillips** [comment]
Hi @MarcinuB the same ticket should be fine. If we need any more information we'll let you know during refinement this week. Thanks.

**Comment by plittlewood-rpt** [comment]
Hi @MarcinuB can you provide a bit of detail around why you want pPriceC and pCurrency? The APIs should be taking care of this already. There is a field called Currency and the API will handle exposing of pPriceC (where it needs to). If this isn't happening and you can provide some examples we can take a look. Thanks

**Comment by MarcinuB** [comment]
Hi @plittlewood-rpt. 
We're providing FluxPro to Savills Ireland and we were informed that price and currency is stored in those fields for them. If you're saying that API handles that and exposes those values in the same fields as for UK then even better as it would be handled out of the box for us.

I don't have any propCodes to check as they didn't start using it yet.

**Comment by plittlewood-rpt** [comment]
No problem. We'l check some examples as part of this ticket

**Comment by plittlewood-rpt** [comment]
Hi @MarcinuB I can confirm the currency/prices for Ireland properties are represented correctly so you shouldn't run into any issues with that.

With regards to the other fields I can't see any properties at all with "pSorrounds" as a semi structured field. Can you confirm where the field is populated in AgencyCloud and I can probably track it down that way. I've added pBERRating and you should find you can request that for this customer after about 15 minutes once the changes sync across the network.

**Comment by MarcinuB** [comment]
Hi @plittlewood-rpt .

Still waiting for a feedback from a customer. Will let you know when it will be cleared what field they need if any.

Thanks

**Comment by MarcinuB** [comment]
Hi @plittlewood-rpt - I think we can close that now. 
Once I know from the customer what is needed I will raise another ticket. No point for this one hanging and spoiling statistics.
