### ISSUE TITLE
Expose office lat/long coordinates 

### ISSUE THREAD

**Issue by jazzlall** [reapit/foundations#9424]
Following work completed in Agency Cloud in AC-8797. Could this new field that stores the office lat/long coordinates be presented in the offices API  endpoint to allow 3rd parties to display the exact location of the office. 

**Specification**
- Project: Reapit.Services.Offices
- Add `OfficeAddressGeolocationModel` with the same structure as `PropertyAddressGeolocationModel` from the properties API
- Populate latitude and longitude with office.extra.oLatitude and office.extra.oLongitude respectively
- Add same support for the write side of the API

No rush on this item as it's only available from 12.168 which is still in beta

**Comment by plittlewood-rpt** [comment]
Spec added - no mega rush on this as it's not been released yet
