### ISSUE TITLE
Martyn Gerrard (MTG) App installation 

### ISSUE THREAD

**Issue by AnthonyKyriacou** [reapit/foundations#9429]
Martyn Gerrard (MTG) have installed our app in order for them to feed to our site. I would like to know how many branches, and if numerous, which branches they are. If there are numerous branches, we'd like to know if these can be split into individual branch feeds for account creation purposes.

**Comment by AshDeeming** [comment]
Hi @AnthonyKyriacou 
Please use GET offices to see the office (branch) breakdown

**Comment by AshDeeming** [comment]
Hi @AnthonyKyriacou 
Please see the swagger page (https://developers.reapit.cloud/swagger) where you can test the available endpoints & then utilise for the live data once clients have installed & you have access to the production data.
