### ISSUE TITLE
Expose Tenancy Agreement Clauses

### ISSUE THREAD

**Issue by abrahamseni** [reapit/foundations#9435]
Hi,

We are working on cloning the tenancy (Change of Sharer) app. Currently, we can access `tenancies/` `breakClauses`, `allowances`, and `responsibilities` endpoint. But we also required these:
1. `Option to renew` endpoint
2. ![Screenshot 2023-07-12 075231](https://github.com/reapit/foundations/assets/94949137/8a5cd13a-ef37-4bbe-8055-d82dde0fa44d)
3. in `breakClauses` we also need these additional properties: 
  - Break From (date)
  - Required Notice (date)
  - Letter Text (string)
  - ![Screenshot 2023-07-12 075654](https://github.com/reapit/foundations/assets/94949137/fcad13fd-8890-45ca-818f-38812e7d67a2)
  - We also found an error while posting new data with `appliesTo: ""` (for mutual), I will log separate ticket for this (https://github.com/reapit/foundations/issues/9436)
4. in `allowances` and `responsibilities`:
  - Letter Text (string)

Thanks

**Comment by plittlewood-rpt** [comment]
Hi @abrahamseni 

Can you confirm whether or not it's just read access you need to the letter text for break clause/allowance/responsibility text? The read side of this is fairly straightforwards however there is a lot of complexity around the write side and it will require a fair bit of work on both sides. Letter text runs explicitly off configuration and is not just a free text field. Your app would need to understand the configuration of each letter text configuration which allows users to enter their own text in certain areas of the letter text template.  We can expose this via an the configuration endpoint, but any write support would need fairly complex validation to ensure that all required parameters are provided in the payload based on each configuration.

Thanks

**Comment by abrahamseni** [comment]
Hi @plittlewood-rpt , let me consult it with the client and get back to you soon!

**Comment by plittlewood-rpt** [comment]
@abrahamseni I have split this ticket up as per links above and will close this item. Please track the individual tickets
