### ISSUE TITLE
Error when posting new tenancy break clauses when appliesTo is empty string

### ISSUE THREAD

**Issue by abrahamseni** [reapit/foundations#9436]
When posting to `tenancies/{id}/breakClauses` with this data:
```json
{
  "typeId": "RPS488",
  "active": "2023-07-27",
    "appliesTo": "",
    "agreements": {
      "landlord": true,
      "tenant": true
    }
}
```

For `Mutual`, we got the data of `appliesTo:""`, but when we try to post the same value, we got an error.
We try go give `null` to appliesTo, but the same error comes back 

![Screenshot 2023-07-12 083314](https://github.com/reapit/foundations/assets/94949137/d99b042b-8fc7-4c22-bc87-60916b24aeda)

Thanks.

**Specification**
- Project: Reapit.Services.Tenancies
- Add `mutual` as an acceptable value in the `appliesTo` property (likely an enum) when adding new break clauses to a tenancy (POST /tenancies/{id}/breakClauses) or editing an existing one (PATCH /tenancies/{id}/breakClauses/{clauseId}
- Maps to `M` in the database

**Comment by plittlewood-rpt** [comment]
Hi @abrahamseni the issue here is that we've missed adding support for the mutual appliesTo value. We'll get this corrected soon

**Comment by abrahamseni** [comment]
@ashindey12 , may I know what is the valid value for `appliesTo`? Thanks

**Comment by plittlewood-rpt** [comment]
Hi @abrahamseni the value you need is `mutual`. I will reopen this ticket as the Swagger documentation has not been updated on the POST model. @ashindey12 please can you update the documentation on the POST model "appliesTo" property to include the new value. Thanks

**Comment by abrahamseni** [comment]
@plittlewood-rpt , @ashindey12 , Thanks!
