### ISSUE TITLE
LAR222939 not syncing

### ISSUE THREAD

**Issue by charlies-fixflo** [reapit/foundations#9440]
**Describe the bug**
Property that meets Fixflo sync criteria is continually being archived due to letting field being null in API - LAR222939

**To Reproduce**
Steps to reproduce the behaviour eg:
1. Go to LAR222939 and check that all Fixflo sync criteria are met = TRUE - AgentRole is Managed tenancy, Letting status is valid and Mgmt fee is set to Managed tenancy
2. Check API for this property sync

**Expected behaviour**
The API contains the letting data that allows the property to sync into Fixflo as active

**Actual behaviour**
Letting field = null

{
    "id": "LAR222939",
    "created": "2022-07-04T00:00:00Z",
    "modified": "2023-07-07T10:30:57Z",
    "marketingMode": "Not set",
    "currency": "GBP",
    "alternateId": "Larards",
    "address": {
        "buildingName": "",
        "buildingNumber": "2",
        "line1": "Water Works Cottages",
        "line2": "Clough Road",
        "line3": "Hull",
        "line4": "East Yorkshire",
        "postcode": "HU6 7QB",
        "countryId": "GB",
        "localTimeZone": "Europe/London",
        "geolocation": {
            "latitude": 53.767927,
            "longitude": -0.334094
        }
    },
    "areaId": "HUL",
    "strapline": null,
    "description": "*Deposit free option available* A three bedroom semi detached house in a convenient location within walking distance of many local amenities and shops.",
    "longDescription": "The property comprises an entrance hall, through lounge/dining, kitchen with breakfast bar, and wet room. The the upper floor are two double bedrooms, one single bedroom, bathroom with over bath shower and separate w.c. Externally there is an enclosed rear garden. The property benefits from gas central heating and double glazing.\r\rDeposit: £801  Council Tax band: A  Energy Efficiency rating: D",
    "localAuthorityCompanyId": null,
    "localAuthorityCompanyName": null,
    "summary": "Deposit free option available\rThee Bedroom House\rSemi-Detached\rWet Room & Bathroom\r£801 Deposit\rEPC Rating D",
    "departmentId": "G",
    "negotiatorId": "SKG",
    "bedrooms": 3,
    "bedroomsMax": 0,
    "receptions": 1,
    "receptionsMax": 0,
    "bathrooms": 1,
    "bathroomsMax": 0,
    "numberOfUnits": 0,
    "parkingSpaces": 0,
    "councilTax": "A",
    "disabledPortalIds": [],
    "internetAdvertising": true,
    "isExternal": false,
    "viewingArrangements": "KEYS IN - £801 SD - PETS? - CT BAND A - EPC D - NDS AVAILABLE",
    "videoUrl": null,
    "videoCaption": null,
    "video2Url": null,
    "video2Caption": null,
    "notes": "KEYS IN - £801 SD - PETS? - CT BAND A - EPC D - NDS AVAILABLE\r\n\r\nContact Matt & Scott in all correspondance",
    "boardStatus": null,
    "boardNotes": null,
    "featuredImageUrl": "https://assets.reapit.net/loc/live/pictures/LAR/22/LAR222939_14.jpg",
    "url": null,
    "urlCaption": null,
    "groundRent": 0.0,
    "groundRentComment": null,
    "groundRentReviewDate": null,
    "groundRentIncrease": null,
    "serviceCharge": 0.0,
    "serviceChargeComment": null,
    "floorLevel": null,
    "internalFloors": null,
    "totalFloors": null,
    "boardUpdated": null,
    "valuation": null,
    "archivedOn": null,
    "fromArchive": false,
    "rural": null,
    "externalArea": null,
    "internalArea": null,
    "epc": {
        "exempt": false,
        "eer": 0,
        "eerPotential": 0,
        "eir": 0,
        "eirPotential": 0
    },
    "selling": null,
    "letting": null,
    "commercial": null,
    "regional": null,
    "type": [
        "house"
    ],
    "style": [
        "semiDetached"
    ],
    "situation": [
        "garden"
    ],
    "parking": [],
    "age": [],
    "locality": [],
    "specialFeatures": [],
    "unmappedAttributes": [],
    "rooms": [],
    "roomDetailsApproved": true,
    "officeIds": [
        "LAR"
    ],
    "lostInstructionDate": null,
    "lostInstructionNote": null,
    "keywords": [],
    "extrasField": {},
    "_eTag": "\"91CFD399568221F4955E0715EBBF3AF4\"",
    "_links": {
        "self": {
            "href": "/properties/LAR222939"
        },
        "images": {
            "href": "/propertyImages/?propertyId=LAR222939"
        },
        "documents": {
            "href": "/documents/?associatedType=property&associatedId=LAR222939"
        },
        "offers": {
            "href": "/offers/?propertyId=LAR222939"
        },
        "appointments": {
            "href": "/appointments/?propertyId=LAR222939"
        },
        "negotiator": {
            "href": "/negotiators/SKG"
        },
        "offices": {
            "href": "/offices/?id=LAR"
        },
        "department": {
            "href": "/departments/G"
        },
        "area": {
            "href": "/areas/HUL"
        }
    },
    "_embedded": null,
    "metadata": {}
}

**Comment by plittlewood-rpt** [comment]
Hi @charlies-fixflo  - this should be sorted. There was an issue with some of the data in the database record that was preventing the property type from being determined correctly. Please can you confirm if you've been able to sync the property now?

**Comment by charlies-fixflo** [comment]
Hi Pete,

Thanks very much - the property is now syncing
