### ISSUE TITLE
URGENT!!! - PATCH /appointments/<id> erroneously updates organiserId field

### ISSUE THREAD

**Issue by paganvarg** [reapit/foundations#9441]
**Describe the bug**
Every time we use Reapit API PATCH /appointments/<id> endpoint to update an appointment and we change the negotiatorIds, it also updates the organiserId field

**To Reproduce**
Steps to reproduce the behaviour eg:
1. Create an appointment e.g. (the ids are just examples)
`    "organiserId": "NEGA",
    "negotiatorIds": [
        "NEGA"
    ],`
2. Call PATCH /appointments/<id> with the following values:
`    "organiserId": "NEGA",
    "negotiatorIds": [
        "NEGB"
    ],`
3. When you get that appointment back it will return:
`    "organiserId": "NEGB",
    "negotiatorIds": [
        "NEGB"
    ],`
**Expected behaviour**
It should return:
`    "organiserId": "NEGA",
    "negotiatorIds": [
        "NEGB"
    ],`

The organiserId shouldn't change in those cases. It has a big impact on our reporting figures.

**Comment by plittlewood-rpt** [comment]
Hi @paganvarg this is happening because when not explicitly set, the organiserId field is inferred from the primary negotiator. I'll look at this behaviour as when the negotiatorIds are patched for the first time, we should be retaining the original negotiator as the organiser.

**Comment by paganvarg** [comment]
Hi @plittlewood-rpt , thanks for looking into it. I think it must have been introduced by a recent change, because we haven't noticed it before and it hasn't ever been reported to us.  Also to be clear we set the organiserId in the patch request explicitly to the value it is set to in Reapit at the time we make the change, but it's still ignored and overwritten by primary negotiator.

**Comment by plittlewood-rpt** [comment]
HI @paganvarg there haven't been any changes in this area for ages, so it's likely an undetected bug that's been lurking for some time. Nevertheless we'll get this resolved for you.

**Comment by plittlewood-rpt** [comment]
@paganvarg a fix for this is just going out to production now
