### ISSUE TITLE
Update journal API to support new jnlmatch table

### ISSUE THREAD

**Issue by plittlewood-rpt** [reapit/foundations#9461]
**Background context**
Possibility of new endpoint specifically for managing match data

**Specification**
- Project: Reapit.Services.Journal
- New jnlmatch table is being added to AgencyCloud which will house match data, which makes up a huge chunk of the journal (this is entries with entryType DS, BS, MA, NM, HM). The structure of the table is the same.
- For the existing GET endpoint: Update to use union'd result set from both tables. We may wish e smart about which tables get hit in the repository. eg Do not union when typeId is specified that doesn't contain one of the match entry types
- For POST: Make sure the entries go into the correct tables
- For AgencyCloud v < 12.183, new resources via `POST /` should be written to the jnl table, For AgencyCloud v >= 12.183, they should be written to the new table. AC are 99% sure that this is the version the change will be made in.
- There is uncertainty over when jnl data will actually get migrated to jnlmatch, so we need to be reading from both tables for the time being

**Spec Updates 09/04/2024)**
 - Data will be migrated from 12.183 onwards (due to start deployment to beta customers April 29th). We need to update the existing branch to only use the JnlMatch table from this version. The customer version is available by using `IPlatformIdentity.HasMinimumProductVersion()` (there's an example of this being used in the Documents service
   - When handling write operations from 12.183 onwards, match entry types should be written to the jnlmatch table, otherwise continue to write to jnl
   - When handling read operations from 12.183 onwards, match entry types should be read from jnlmatch, otherwise continue reading from jnl
   - Delays from other departments responsible for data migrations might mean 12.183 needs to change, but we should get the code updated

Note that we've already done analysis to see how this endpoint is being used. 99% of requests pass a typeId or another id (ie propertyId) that will filter the resultset enough to ensure that unioning two large tables won't cause too much of a performance issue

**Comment by ntiley** [comment]
@plittlewood-rpt @HollyJoyPhillips  - you should find that the new jnlmatch table is now present in all databases so this ticket can be picked up

**Comment by cduggan-reapit** [comment]
Notes from conversation w/ @plittlewood-rpt 2024-01-15

```
Journal 2020-01-31 to 2024-01-31
GET: / => This one unions

Journal 2024-01-31
GET: /api/journal/ => jnl
POST: /api/journal/
GET: /api/journal/matches/ => jnlmatch
POST: /api/journal/matches/

Journal 2024-06-01 (maybe one day)
GET: /api/journal/ => jnl
GET: /api/journal/matches/ => jnlmatch
GET: /api/journal/communications/ => jnlcmmnctn

TODO:
- Update the extant GET endpoint to union tables
- Add a new endpoint to retrieve the "stub" jnl table
- Add a new endpoint to write to the "stub" jnl table
- Add a new endpoint to retrieve the new jnlmatch table
- Add a new endpoint to write to the new jnlmatch table
```

**Comment by plittlewood-rpt** [comment]
Spec updated as we now have the release version for the data migration
