### ISSUE TITLE
searchTenancies endpoint error for customer

### ISSUE THREAD

**Issue by willburngl** [reapit/foundations#9464]
**Background context**

For a particular Reapit user we consistently receive the following error message, when using the searchTenancies endpoint.

**Example cURL request:**
```
curl --location --request GET 'https://platform.reapit.cloud/tenancies?propertyId=BLO170001' \
--header 'api-version: 2020-01-31' \
--header 'reapit-customer: twn' \
--header 'Authorization: <REDACTED>'
```

**Returns:**

```
{"statusCode":500,"dateTime":"2023-07-14T14:11:22.2388727Z","description":"An unexpected error has been encountered when fulfilling this request. This incident has been logged and will be investigated. Please try again."}
```

Can you advise on what the root cause of this is?

Thanks!

**Comment by AshDeeming** [comment]
Hi @willburngl 
Please could you confirm the app name

**Comment by willburngl** [comment]
@AshDeeming Goodlord is the app that the call is being made from.

**Comment by plittlewood-rpt** [comment]
@willburngl this should now be resolved and was due to some odd data against one the tenancies associated to this property. The data has been cleaned up and safeguards added to the API in case we encounter data in the same state again. Thanks
