### ISSUE TITLE
No data returned when no config values are set

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#9474]
**Issue:** When an organisation that has no configuration values set at all, GET /config/{organisationId} it should be returning the default values for all settings which match the product and tag query parameters, but it actually returns no data.

**Comment by plittlewood-rpt** [comment]
@ntiley are you able to supply the info that led you to discover this please (prod/dev, which org id etc)

**Comment by bashleigh** [comment]
After looking into this, this is a feature of the admin causing confusion. 

If you're an admin you can create config values for non userFriendly setting configs. Whereas a normal user will receive a 400 on that action.

After testing I found that userFriendly settings are not returned on value config requests. This is likely what happened and to my knowledge this is to be expected. 

Please confirm this is the correct requirements.


- admins can create config values for userFriendly setting values 
- when requesting config values, none userFriendly settings are not displayed

**Comment by bashleigh** [comment]
After discussion, remove the query for userFriendly on get so all data is returned regardless of userFriendly. userFriendly query value should be removed temporarily (comment out for now)

**Comment by HollyJoyPhillips** [comment]
Confirmed with NT - working as expected.
