### ISSUE TITLE
Hamburger Menu Changes

### ISSUE THREAD

**Issue by craigforrest** [reapit/foundations#9477]
**Is your feature request related to a problem? Please describe.**
After the hamburger menu has been expanded, it remains expanded until the 'x' is clicked. 
![image](https://github.com/reapit/foundations/assets/26924168/6f0ca773-7fff-487e-b5b3-94cab08cd453)

**Describe the solution you'd like**
It has been noted that it would feel more natural if the menu collapses if any part of the screen outside of the expanded menu is clicked/ pressed

**Describe alternatives you've considered**
We looked at amending this for the Diary app specifically, but it may be more sensible to change this centrally so the menu is reflected in all apps without additional development work

**Comment by willmcvay** [comment]
@craigforrest This sounds sensible. Will get it done for v4 Elements, have added to the milestone.
