### ISSUE TITLE
Update 'AgencyCloud Integration' heading 

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#9482]
**Task**: 
- Rename 'AgencyCloud Integration' heading on app listings in the AppMarket to 'AgencyCloud Launch Point' 
![image](https://github.com/reapit/foundations/assets/52408607/776972af-033e-4f00-ad69-68b3fa2c8c50)

**Comment by JohnhennessyReapit** [comment]
Thanks Holly
