### ISSUE TITLE
Savills - Opayo Payment receipt Template 

### ISSUE THREAD

**Issue by RLAV1** [reapit/foundations#9485]
**Is your feature request related to a problem? Please describe.**
as part of Savills Project to deploy UK Lettings and Client Accounts - they will be utilising our payment solution via Opayo - Savills have reported that when the payment is taking through the opayo portal and payment receipt is produced which details Reapit - this needs to say Savills instead of Reapit 

**Describe the solution you'd like**
Payment receipt template to be amended to replace the word Reapit with the work Savills 

**Describe alternatives you've considered**
No Alternatives 

**Additional context**
Any additional context required do let me know

**Comment by plittlewood-rpt** [comment]
@RLAV1  Will is on holiday so it will depend on if it can be done before he is back. @HollyJoyPhillips  and I will consider it for next sprint, depending on what's actually required. Thanks

**Comment by plittlewood-rpt** [comment]
Sorry yes I understand the requirement from your perspective I'm just not sure what the technical requirement is here (ie what we need to change at this end).

**Comment by RLAV1** [comment]
Feedback that has been gathered by Savills 

On the payment request email please can we add 

- A line about the fact we only accept UK Debit Cards
- A line about forwarding the payment confirmation to Savills once received (This one is a way to overcome the no notification email sent to the person making the email.)
- Also can we check with Opayo that the restriction to only accept UK Debit Cards is in place on the live site, as Susan only set this  for the UAT.

On the payment confirmation email the prominent logo is Reapit. 
- We need that to be Savills. Ideally with a Savills logo.

Happy to setup a call directly with Savills key contacts if any further context needs adding to this ticket

**Comment by RLAV1** [comment]
Hey @plittlewood-rpt  @HollyJoyPhillips 

Can we get this in to the next available sprint please? - this appears to be one of the last blockers on Savills go live list - but they just need to know a date as to when they can expect the template changes? 

Thank you :)

**Comment by HollyJoyPhillips** [comment]
This requires further discussion which will take place early next week. We will update the ticket if more information is required or when the ticket is allocated to a sprint. Thanks.

**Comment by HollyJoyPhillips** [comment]
Template has been updated via a separate ticket
