### ISSUE TITLE
Including 'work type' in API endpoints

### ISSUE THREAD

**Issue by katedeedman** [reapit/foundations#9488]
Hello Reapit team!

Hope all is well.

I'm one of the Product Managers at Fixflo and we have a mutual client that is requesting if we can include the 'work type' in the works order sync.

The current behaviour is: 

- If I was to create a works order from Reapit, I can select the Work Type (screenshot below)

![image](https://github.com/reapit/foundations/assets/117754771/29d26220-b93f-435a-bcd8-ba9de2e656b9)

- If I was to raise an issue in Fixflo, once that works order is in Reapit, I'm unable to select a Work Type at all (screenshot below). 

![image](https://github.com/reapit/foundations/assets/117754771/9162e5d7-170c-4149-aa41-3eabff73b72e)

As far as I can tell, 'Work Type' isn't included in your API. Please let me know if you plan to add this anytime soon? If not, please do let me know if there's a reason why it hasn't been added previously so I can report back to the client.

Thanks in advance!

-Kate

**Comment by AshDeeming** [comment]
Hi @katedeedman 
Please could you check the configuration endpoint shown below to call these, which could vary per client;
![image](https://github.com/reapit/foundations/assets/61687775/fe30af0b-bec7-403b-867e-5050c931aae9)
