### ISSUE TITLE
How to get Development details from property api response?

### ISSUE THREAD

**Issue by mrkmaulik** [reapit/foundations#9489]
Hi,

How to get development details from properties api?

Please guide, I want to link properties with development in our internal software.

**Comment by AshDeeming** [comment]
Hi @mrkmaulik 
Please see the below section with regards to the Plots and subplots, this is also within Departments however this is sub catergory, please see more details under (https://foundations-documentation.reapit.cloud/platform-glossary#interpreting-department-data)
![image](https://github.com/reapit/foundations/assets/61687775/c1b560e5-6943-495d-880b-ed0388c261e0)

**Comment by plittlewood-rpt** [comment]
Hi @mrkmaulik as an addition to what Ash has mentioned above, the way the relationship between master site records and subplots is defined in the API is detailed in ticket #3756 however to summarise, it's all done via the `_links` collection, which will include additional links if a property is a master site record or sub plot. In addition. you can fetch all sub plots associated with a site by using the `masterId` query string parameter when calling GET /properties (eg GET /properties?masterId=ABC123456 will give you all plots in the development site whose master property record has id ABC123456)

![image](https://github.com/reapit/foundations/assets/30798627/14c6dfb3-4719-4fff-8efa-02bb5156c680)


I hope this helps
