### ISSUE TITLE
Can we get Lender info on the foundations API, if so, where?

### ISSUE THREAD

**Issue by BYMIntegrations** [reapit/foundations#9500]
Please take a look at our FAQ's before submitting an issue, as your question may already be covered in the documentation https://foundations-documentation.reapit.cloud/faqs

**Summary**
Our mutual customer, Rettie, is asking if Lender information is available for us to use, however, I cannot find it on the API. (see screenshot below for example on the UI) 

Is this information available? 

**Detail and or supporting links and screenshots**
![image](https://github.com/reapit/foundations/assets/102583061/a9c3af80-52f6-449f-acf5-09a3c3b08ad1)

**Comment by AshDeeming** [comment]
Hi @BYMIntegrations 
Please see the Conveyancing endpoint/payload via swagger
