### ISSUE TITLE
Snowsight sync issue

### ISSUE THREAD

**Issue by tdstirling** [reapit/foundations#9507]
Hi,
Looks like Snowsight stopped syncing at 2023-07-24 10:39:42.128 +0000.  Is this an issue you're aware of?

Thanks,

**Comment by plittlewood-rpt** [comment]
Hi @tdstirling there was some maintenance yesterday around this time but it should only have been off for a very short period and should be back online. Are you still not receiving updates?

**Comment by tdstirling** [comment]
All sorted now, thanks Pete.

Tom Davis
[http://surveygizmolibrary.s3.amazonaws.com/library/608730/salogo01small.png]<https://www.stirlingackroyd.com/>
[http://surveygizmolibrary.s3.amazonaws.com/library/608730/saphone01small.png]01932 736 510 Ext: 1001


SALES / LETTINGS / SURVEYING / NEW HOMES / COMMERCIAL / MAINTENANCE
Sales and lettings specialists with the London connection
[https://surveygizmolibrary.s3.amazonaws.com/library/608730/Footer.png]
Stirling Ackroyd is a trading name of Stirling Ackroyd Group Ltd. Registered in England: 02653200.
Registered Office: Unit 2, Wintersells Road, Byfleet, Surrey, KT14 7LF
