### ISSUE TITLE
Enable integrations from a link

### ISSUE THREAD

**Issue by craigforrest** [reapit/foundations#9509]
**Is your feature request related to a problem? Please describe.**
As we start to roll out and market our internally developed Mobile-focused apps, we need to streamline the process of enabling an app so they can be accessed by clients.

**Describe the solution you'd like**
If we include a link/ button in an email that allows a user (with the correct permissions) to enable an app without needing to access AgencyCloud this could act as an alternative to sending instructions on how to enable the apps.

**Describe alternatives you've considered**
We are exploring the option of not having to enable internally developed apps, but this would not be without risks

**Comment by plittlewood-rpt** [comment]
@craigforrest can you let me know your ideal timescale on this? We are going to have a session with Holly next week to just hammer out what's possible here and there's a nice fit for this as part of the Reapit Connect v2 work but that will be later in the year.

**Comment by craigforrest** [comment]
Hi Pete, in an ideal world this would be ready by early next week as that'll be the first time we need to communicate instructions on how to enable the app (I'm only admitting this because I know I'm not in arms reach of a smack on the back of the head) but since we're only communicating to 6 clients it's not as important as it would be for a bigger launch which we don't have scheduled yet, and could potentially be as late as November/ December

**Comment by plittlewood-rpt** [comment]
Yep you've no chance of getting it that quick sorry! @HollyJoyPhillips  to discuss

**Comment by HollyJoyPhillips** [comment]
Agreed to use the direct Appmarket link within the email to navigate to the AppMarket and the normal process takes place for installation/using RC to validate user permissions.
