### ISSUE TITLE
Office partitioned groups should not be impacting users installed organisation wide

### ISSUE THREAD

**Issue by shawnzvinis** [reapit/foundations#9510]
**Describe the bug**
When an agency uses Office Groups and installs our app for the whole group (e.g. BRD), we are unable to access data for all office groups, if a user who logs in with Reapit Connect has a token only for their office group (e.g. BRD-GTST).

I am logging this on request of Michael Wood:
> The office partitioned groups should not be impacting users for any apps that are installed organisation wide. Given this appears to be a technical issue, you can report a bug direct on our GitHub board [here](https://github.com/reapit/foundations/issues/new?assignees=&labels=bug%2C+needs-triage&template=bug_report.md&title=).

**To Reproduce**
Steps to reproduce the behaviour eg:
1. Install an app as a whole group (with an agency that uses office groups)
2. Login with Reapit Foundations as a user that is in an office portion group
3. Make a request to access data in an office that the user is not part of

**Expected behaviour**
We expect to be able to request and receive all data if the app is installed for the whole group.

**Comment by shawnzvinis** [comment]
@AshDeeming Homeflow Lead Manager

**Comment by plittlewood-rpt** [comment]
HI @shawnzvinis if I've understood your report correctly, this is working as intended. When you use a client id/token associated to an office group, you'll only be able to retrieve data that that particular office group should have access to. To access data belonging to another office group, you'd need to call the API with a different reapit-customer header (eg BRD-GABC) or an access token belonging to a user in a different office group

**Comment by shawnzvinis** [comment]
@plittlewood-rpt Thanks for your reply. The issue is that the user in question has installed our app at the BRD group level (confirmed in https://developers.reapit.cloud/apps/*/installations) but when the same user logs in with Reapit Connect we are provided an access token for BRD-GTST rather than BRD.

**Comment by plittlewood-rpt** [comment]
Hi @shawnzvinis yes this is by design. The organisation level installation (BRD) still has the security controls applied to it because the organisation has chosen to set up office groups to segregate the data returned to apps.

**Comment by shawnzvinis** [comment]
@plittlewood-rpt We are still struggling to understand why the same user can install the app at the organisation level (BRD), but when they log in with Reapit Connect, we receive an access token scoped to BRD-GTST rather than at the organisational level. The user wants to log in at the organisational level and provide us full access. This is blocking us from being able to pull the information needed for them to go live with our app. Any further guidance would be appreciated.

**Comment by HollyJoyPhillips** [comment]
Hi @shawnzvinis, the installation at organisation level is simply for ease, rather than having to install it for the various office group, they can install is once yet it will still respect the data boundaries in place. Each user will be associated to a group which contains data they are only permitted to access. 

Please can you provide use case as to why the customer would want to bypass the office group segregation they have in place?

**Comment by HollyJoyPhillips** [comment]
Hi @shawnzvinis are you able to provide a use case please or can we close this ticket?

**Comment by shawnzvinis** [comment]
Hi @HollyJoyPhillips, we believe we've found a workaround. I will close this ticket for now. I appreciate you chasing it through to a resolution.
