### ISSUE TITLE
connect-session - session expiring after 60mins no session refresh

### ISSUE THREAD

**Issue by stuhuntington** [reapit/foundations#9511]
**Describe the bug**

We have a React application which uses  the`useReapitConnect` hook from `@reapit/connect-session` passing in an instance of `ReapitConnectBrowserSession` to authenticate. We extract the accessToken from this and send it in the Auth headers as a bearer token on all subsequent fetch/post requests. However the nature of our app requires sessions to potentially last longer than 60mins and the session does not appear to be refreshed when it expires.  

I can see in the docs here: https://foundations-documentation.reapit.cloud/app-development/connect-session

the following about refresh tokens when creating a connect session ....

```// Refresh token is provided as a convenience - in practice the module handle's refreshing and caching of your session out the box```

So I am not sure if this is a bug or if there is something I am missing as to how to refresh for a new access key once it has expired but the session does not seem to refresh out of the box as how the docs suggest.

**Expected behaviour**
The module/hook would allow for easy refresh of sessions.

**Device (please complete the following information for web issues):**
This is a React App within Agency Cloud

**Comment by willmcvay** [comment]
@stuhuntington Can you provide us with a code example of how you are referencing the connectSession object please. All our web apps use Connect Session to refresh sessions, it could be an implementation detail. It is worth pointing out that sessions timeout by default after 3 hours as a security measure. You can adjust this value with the `connectApplicationTimeout` key where you instantiate the class as per the docs.

https://foundations-documentation.reapit.cloud/app-development/connect-session#basic-browser-usage

**Comment by stuhuntington** [comment]
Sure - it's very basic....

```
import { useReapitConnect } from '@reapit/connect-session';
import { reapitConnectBrowserSession } from 'core/connect-session';

const App = () => {
  const { connectSession } = useReapitConnect(reapitConnectBrowserSession);
  
  ...
  
  const response = await axios.post(payload, { headers: { Authorization: `Bearer ${connectSession.accessToken}` } });
};
```

I am seeing the session timeout bang on the 60min mark. The object I get back from `useReapitConnect(reapitConnectBrowserSession)` contains values for `accessToken`, `idToken`, `loginIdentity` however the value for `refreshToken` is an empty string.

**Comment by stuhuntington** [comment]
Hey Will,

Definitely not getting any auth errors - the initial call that gets made to `connect.reapit.cloud/token` comes back successfully with a 200 but the refresh token string in the response obj is still empty. Have tried to implement your above solution but the same accessToken gets used so I am guessing `reapitConnectBrowserSession` caches it under the hood.

**Comment by willmcvay** [comment]
Hi @stuhuntington so yes, reapitConnectBrowserSession caches the token in memory for 55mins, it will then attempt to refresh if it has a token in the session.

When you say, the request to the /token endpojnt comes back empty, is the query `grant_type="authorization_code"` or `grant_type="refresh_token"`? If it's the latter, you don't get a refresh token back, because you send one in the request. If you aren't getting a refresh token back from an `authorization_code` request, that's more concerning

**Comment by stuhuntington** [comment]
It is the latter - `grant_type=refresh_token` - should we be using the `authorization_code` instead? I don't see anything in the docs or the types re the React hook / reapitConnectBrowserSession in order to change this - so this is being used by default.

**Comment by willmcvay** [comment]
Yes, so if you are getting an token back,  you are submitting a refresh token in the payload and therefore the library is correctly refreshing your session. Have a look in the network tab - see the example below.
<img width="559" alt="Screenshot 2023-07-25 at 09 58 43" src="https://github.com/reapit/foundations/assets/4630495/1d7fe2aa-51f4-452e-bb96-da33df257a5e">

I am guessing that one of a couple of things could be happening. You could be re-instantiating your ReapitConnectBowserSession somewhere - it should be a singleton. Please check that the constructor is only called once in your code and that the instantiated class is what is being referenced elsewhere.

Secondly, and probably more likely, check the clock time now on the device you are testing against the expiry time of the access token. To do this, just put your access token into https://jwt.io/ and look for the `exp` key.

<img width="167" alt="Screenshot 2023-07-25 at 10 04 46" src="https://github.com/reapit/foundations/assets/4630495/b29a7e01-9bb7-4fff-8fcc-33e0810d9653">

Connect session will try and refresh when the token in memory is within 5 mins of expiry however, this time is set on our AWS server and I have seen over 5 mins clock drift on some windows devices. Connect session has to use the current browser time for obvious reasons and can be significantly out of sync.

**Comment by stuhuntington** [comment]
Hmm - so to me it sounds like how I was originally using this was correct. To clarify this is actually what I am doing....

The app starts up and I create a singleton of ReapitConnectBrowserSession....

```
import { ReapitConnectBrowserSession } from '@reapit/connect-session';

export const reapitConnectBrowserSession = new ReapitConnectBrowserSession({
  connectClientId: process.env.REACT_APP_CONNECT_CLIENT_ID,
  connectOAuthUrl: process.env.REACT_APP_CONNECT_OAUTH_URL,
  connectUserPoolId: process.env.REACT_APP_CONNECT_USERPOOL_ID,
});
```

This is imported into the root level of the App and passed in to the `useReapitConnect` hook....

```
import { reapitConnectBrowserSession } from 'path/to/singleton';
import { useReapitConnect } from '@reapit/connect-session';

const App = () => {
  const { connectSession } = useReapitConnect(reapitConnectBrowserSession);

  return (
    ....
  };
};
```

That is the only time connectSession is created - we pass it into a context provider. The expiry within the JWT is - correctly - 60mins after its creation time. However I have just tried calling `reapitConnectBrowserSession.connectSession()` within the actual post after 60mins - and it redirected me to login to reauth so my app state was lost. So the refresh didn't work.

**Comment by willmcvay** [comment]
@stuhuntington So at this point I'd need to see some code to debug further am afraid. If you have something you can share, can you zip it up and forward to wmcvay@reapit.com or invite me as a viewer to the repo.

**Comment by stuhuntington** [comment]
Have emailed privately
