### ISSUE TITLE
App missing from account but Sandbox Access still available

### ISSUE THREAD

**Issue by PaulBRobinson** [reapit/foundations#9512]
**Summary:**
We can no longer see any apps in the account area but access is still working and able to retrieve data from the Sandbox.

**More Detail:**
We recently noticed that the 'apps' area in the account was completely empty, there are no created apps shown. However the application we created still has access to the Sandbox and can retrieve data without issue using it's Client ID. It is also able to retrieve new tokens without issue.

The Client ID being used is: 2hujmqts51evbgstu0kr7vh6te

The Agent is: Hooke & McDonald

Please let me know if you need any additional information.

**Comment by AshDeeming** [comment]
Hi @PaulBRobinson 
Please could you confirm the app name?

**Comment by PaulBRobinson** [comment]
Hi

I believe the app name was 'Cream Creative HMD Integration'.

**Comment by PaulBRobinson** [comment]
Hi @AshDeeming 

Sorry to ping, just checking in to see if there are any updates on this so we can move forward on development.

**Comment by AshDeeming** [comment]
Thanks @PaulBRobinson 
I can see a app with that name & is currently under the 'Cream Creative' developer account. 
There is only one user associated to this account & therefore that account will be the only one able to see the app - unless other members invited to the developer org https://developers.reapit.cloud/settings/members

**Comment by nabesakarenders** [comment]
Hi @AshDeeming ,

Yes that is currently the account we are using to try to access the app. When checking the 'apps' tab there are no longer any apps available to edit. I did find an old edit link for the app I had shared with a colleague in Slack and visiting that link allows me to edit the details of the app without issue (using the 'Cream Creative' account) but heading back to the App listing shows no app listed. 

Does that help narrow things down at all?

**Comment by PaulBRobinson** [comment]
Hi @AshDeeming,

We are currently trying to access the app using the Cream Creative account, but there are no apps shown when visiting the Apps page.

I did find an old link to the edit page of the app I shared with a colleague via slack, that link allows me to edit the details of the app (and they look correct) without issue. Navigating back to the apps listing again though shows no apps available.

Also my apologies if you got two pings for this message, I posted with the wrong account (my personal Github account).

**Comment by AshDeeming** [comment]
Thanks @PaulBRobinson 
I can only see one user associated to the developer account for Cream Creative. 
Could you confirm if you are using the user account starting ciar**?

**Comment by PaulBRobinson** [comment]
Hi @AshDeeming 

Yes I can confirm that is the account being used. 

As mentioned if I visit the app edit link I shared with a colleague on slack a while ago I can edit all the details of the app, but I cannot see the app when on the app listing page.

**Comment by AshDeeming** [comment]
Thanks @PaulBRobinson 
It appears that the above mentioned email address was invited to a clients developer org on the 14 Jul & when accepted this would have removed the previously associated developer account. 

We can arrange to re-invite you to the Cream Creative using the original email (removing access to the clients dev org) or provide an alternative email address to be used?

**Comment by PaulBRobinson** [comment]
Hi @AshDeeming 

Ah. We were unaware that the applications were not associated with the user. In this case the app is likely best located on the client's account so we have created a new app instead. If that is okay I believe this can be marked as resolved.
