### ISSUE TITLE
Feed discrepancy Martyn Gerrard (MTG)

### ISSUE THREAD

**Issue by AnthonyKyriacou** [reapit/foundations#9515]
Dear Reapit,

Can you please confirm why we krispyhouse are only reviewing 4 live adverts to let for Martyn Gerrard East Finchley whereas Righmove are displaying 26 properties for this same branch. We are using the EAN office ID for this branch.

Please see below an example link for a property being displayed on Rightmove which we are not receiving. We are however receiving a feed for a property that looks the same but the information is not comparable.

id: EAF210020
https://www.rightmove.co.uk/properties/128906168#/?channel=RES_LET

Furthermore, please see below a brief summary of Martyn Gerrard's page on krispyhouse and Rghmove wgere you can see the disparity on number of feeds. 

https://www.krispyhouse.com/adverts/posted-by/856dc56c-bb42-4b28-a4c1-123d96ccb586
https://www.rightmove.co.uk/property-to-rent/find.html?includeLetAgreed=true&locationIdentifier=BRANCH%5E13096

**Comment by AshDeeming** [comment]
Hi @AnthonyKyriacou 
From reviewing a live property (EAF210020) on both portals, it appears you are not pulling through their Long Description. 
please see the below;
https://foundations-documentation.reapit.cloud/faqs#certain-fields-are-not-exposed-by-default-in-the-platform

**Comment by AnthonyKyriacou** [comment]
Hi Ash,

Not sure what you refer to in your response makes reference to the issue I'm identifying. Please review the issue properly. Please see below data we are receiving which doesn't look correct nor up t date.

"created": "2021-02-02T17:28:30Z",
  "letting": {
    "rent": 1750,
    "term": "",
    "status": "toLetUnavailable",
    "deposit": {
      "type": "fixed",
      "amount": 0

"availableTo": null,
    "minimumTerm": 0,
    "rentIncludes": null,
    "availableFrom": "2022-07-02",
    "managementFee": null,
    "rentFrequency": "monthly",

**Comment by AshDeeming** [comment]
Hi @AnthonyKyriacou 
Please could you confirm the parameters being used to GET properties?

**Comment by AnthonyKyriacou** [comment]
Hi Ash,

Please see below request we use to GET properties.

https://platform.reapit.cloud/properties/?embed=images&lettingStatus%5B0%5D=toLet&lettingStatus%5B1%5D=toLetUnavailable&marketingMode=letting&pageNumber=1&pageSize=100&officeId=EAN

**Comment by AshDeeming** [comment]
Thanks @AnthonyKyriacou 
Can I ask why your call is for properties with the status toLetUnavailable? 
Properties which are fed to portal are usually 'available'

**Comment by AshDeeming** [comment]
Hi @AnthonyKyriacou 

Your initial question around why there was a difference in the number of properties shown on the two sites, could be down to the statuses being called. 

With regards to the fields, please could you be more specific about which you expect verse those coming through? 

your second question, i believe relates to the data surfaced from the property record however the data is correct & relates to the original letting/tenancy from 2022

**Comment by AnthonyKyriacou** [comment]
Hi Ash,

I think you misunderstand what I am asking you to look at. Can we have a call so I can simplify what I am wanting from you. There is no 'status issue causing the feed problem. 

It's simply..... Please look at the two links below. We are showing 4 adverts. Righmove are showing 26 adverts. My question to you is simply. Why the disparity in numbers.

https://www.krispyhouse.com/adverts/posted-by/856dc56c-bb42-4b28-a4c1-123d96ccb586
https://www.rightmove.co.uk/property-to-rent/find.html?includeLetAgreed=true&locationIdentifier=BRANCH%5E13096

**Comment by plittlewood-rpt** [comment]
@AnthonyKyriacou  I have had a look at the calls you are making. Firstly please note that is more than one office in their system called East Finchley, so you'll need to ensure your are amalgamating the data from the office specific calls (incidentally, I note that you are making one call per office to our API. You can make this more efficient (and reduce your API consumption) by including results for multiple offices in the same query (eg GET /properties?officeId=ABC&officeId=DEF etc)

Having looked further into the feed configuration, it looks like this customer are sending toLet and toLetUnavailable/arrangingTenancyUnavailable properties that have an availableFrom date set. 

To hit the API to get the exact results for the Rightmove listing you need to make the following request:

`GET https://platform.reapit.cloud/properties?lettingStatus=toLet&lettingStatus=arrangingTenancyUnavailable&marketingMode=letting&officeId=EAF&officeId=EAN&officeId=EAL&internetAdvertising=true&availableFrom=1970-01-01`

However, as the data states change it's likely this won't cut the bill in all situations, and it's down to you as the developer to agree with the customer what parameters need to be set to determine what gets displayed on the Krispy House portal. Simply saying it needs to match Rightmove isn't enough detail. Our Rightmove feed has it's own configuration around what statuses are/are not included, and this configuration will have been agreed with the customer at some point.

I hope this helps.

Thanks
Pete

**Comment by AnthonyKyriacou** [comment]
Dear John,

I hate to be a pain but I am annoyed that I have to spend time dealing with
technical matters that I shouldn't need too. I'm very busy and my time
extremely costly. I tried calling to speak with Pete but of course
technicians don't have phones.

Please look at the last paragraph Pete's email below. Utter nonsense. If
you won't allow us to receive the same feed as Rightmove, Zoopla etc then
at least give us the same data. It's very clear here and don't try to
disguise it any other way. What you send to Righmove/Zoopla in the way of a
BLM file should be mirrored in the API feed but it isn't.

The below property cannot be accessed by us via the API even now we have
updated the requested as instructed by Pete. If Martyn Gerrard East
Finchley have put this property on the market to let via their Reapit
dashboard then it should be accessible to us no matter what. There should
not be a need for us to agree any parameters with the customer. By default
as a property portal, you should send us the same data.

https://www.rightmove.co.uk/properties/128906168#/?channel=RES_LET

This is a simple task but your technical team are making it complicated and
I don't wish to exhaust any more of my time on expressing to you how your
logic should be configured. Just make it right.

Kind regards,


Anthony Kyriacou
*Founder & CEO*

81 Parkway
London
NW1 7PP

*T:* 0345 512 0206
*M: *07954 138663
*E: ***@***.***
*W*: www.*krispy*house.com <http://www.krispyhouse.com>

<http://www.krispyhouse.com>

      <https://www.facebook.com/Krispy-House-101108906001353>
<https://twitter.com/HouseKrispy> <https://www.instagram.com/krispyhouseuk/>
<https://www.linkedin.com/company/krispyhouse/>

This email and any files transmitted with it are confidential and intended
solely for the use of the individual or entity to whom they are addressed.
If you have received this email in error please notify the system manager.
This message contains confidential information and is intended only for the
individual named. If you are not the named addressee you should not
disseminate, distribute or copy this e-mail. Please notify the sender
immediately by e-mail if you have received this e-mail by mistake and
delete this e-mail from your system. If you are not the intended recipient
you are notified that disclosing, *copying, distributing or taking any
action in reliance on the contents of this information is strictly
prohibited.*


Krispyhouse is the trading name of Krispyhouse LTD, a company registered in
England & Wales. Registration Number 11665458

**Comment by plittlewood-rpt** [comment]
@AnthonyKyriacou I understood you did call to speak to me, but I was told you opted not to leave your contact details with our service team. The Rightmove portal is not fed using our Foundations API and is a separate feed mechanism, with it's own configuration which we agree with each customer independently. 

It strikes me that there may be a misunderstanding here as to what the Foundations APIs provide. They are not designed to power just external websites for advertising purposes, and as such return all property data where the app scopes allow. It is therefore down to individual app developers to implement their own logic to decide which properties to import and which ones to discard.

There are two issues at play here:
1) You are struggling to get the data you need from the API (which I've assisted with in my last comment on this item and also pointed out that its likely not just EAN you need to be querying)
2) You are missing pieces of information you want to display online

The information you need to deal with item one is in the paragraph you have politely described as utter nonsense. As the data provider, it's not up to Reapit to define the rules about what is and is not displayed on your property portal. As noted above, the API gives access to all properties, not just ones that would normally be included in the feed to external portals. 

Regarding the second problem, I have looked at the links you sent. I presume you are mainly referring to the description being different. The description displayed on Rightmove is indeed available in the API, please see `PropertyModel.longDescription`. The Key Features (on Rightmove) are available in the API, please see `PropertyModel.summary`. Council Tax is available in the API, please see `PropertyModel.councilTax`. If there is something specific you are challenging then please provide the details and I will help you. Every customer's Rightmove feed configuration is different. Nothing is being 'disguised' here and we are always willing to assist external parties with problems. We use Github as a way of supporting developers using Foundations APIs as other developers can then benefit from the responses as it is a public project.

Regarding the property in the link you've shared, I've had a look at this customer's Rightmove configuration and they are also sending properties with a status of Tenancy Current - Available (as well as Under Offer Available though they may not use this status in our system) to Rightmove, so you'll need to include that in your query string also. I can't stress how important it is that the decision about what to display online is between you and the customer, as each customer will have a different view on whether they advertise properties in certain states or not. We provide a means of getting the data, you are in control over how that data is filtered.

As a suggestion, an optional frontend app to serve as a companion to your server side app would allow customers to setup their own feed configuration for your system if they didn't like the default filters you apply (ie a way from selecting what property statuses to include and so on). Of course this requires upfront effort at KrispyHouse, but would put the onus back on the customer to configure your integration without you needing to get involved.

**Comment by AnthonyKyriacou** [comment]
Dear Pete,We have implemented your instruction as previously stated. Again, the property I referred too in the link is available to us but with outdated information (modified status is 2022) therefore we wouldn’t publish this because the information isn’t current. That’s the problem with this advert. Please provide a solution. Kind regards,Anthony KyriacouFounder & CEO81 ParkwayLondonNW1 7PPT: 0345 512 0206M: 07954 ***@***.***: www.krispyhouse.com        This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. If you have received this email in error please notify the system manager. This message contains confidential information and is intended only for the individual named. If you are not the named addressee you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. If you are not the intended recipient you are notified that disclosing, copying, distributing or taking any action in reliance on the contents of this information is strictly prohibited.Krispyhouse is the trading name of Krispyhouse LTD, a company registered in England & Wales. Registration Number 11665458Sent from my iPhone On 26 Jul 2023, at 15:04, Pete Littlewood ***@***.***> wrote:﻿
@AnthonyKyriacou I understood you did call to speak to me, but I was told you opted not to leave your contact details with our service team. The Rightmove portal is not fed using our Foundations API and is a separate feed mechanism, with it's own configuration which we agree with each customer independently.
It strikes me that there may be a misunderstanding here as to what the Foundations APIs provide. They are not designed to power just external websites for advertising purposes, and as such return all property data where the app scopes allow. It is therefore down to individual app developers to implement their own logic to decide which properties to import and which ones to discard.
There are two issues at play here:

You are struggling to get the data you need from the API (which I've assisted with in my last comment on this item and also pointed out that its likely not just EAN you need to be querying)
You are missing pieces of information you want to display online

The information you need to deal with item one is in the paragraph you have politely described as utter nonsense. As the data provider, it's not up to Reapit to define the rules about what is and is not displayed on your property portal. As noted above, the API gives access to all properties, not just ones that would normally be included in the feed to external portals.
Regarding the second problem, I have looked at the links you sent. I presume you are mainly referring to the description being different. The description displayed on Rightmove is indeed available in the API, please see PropertyModel.longDescription. The Key Features (on Rightmove) are available in the API, please see PropertyModel.summary. Council Tax is available in the API, please see PropertyModel.councilTax. If there is something specific you are challenging then please provide the details and I will help you. Every customer's Rightmove feed configuration is different. Nothing is being 'disguised' here and we are always willing to assist external parties with problems. We use Github as a way of supporting developers using Foundations APIs as other developers can then benefit from the responses as it is a public project.
Regarding the property in the link you've shared, I've had a look at this customer's Rightmove configuration and they are also sending properties with a status of Tenancy Current - Available (as well as Under Offer Available though they may not use this status in our system) to Rightmove, so you'll need to include that in your query string also. I can't stress how important it is that the decision about what to display online is between you and the customer, as each customer will have a different view on whether they advertise properties in certain states or not. We provide a means of getting the data, you are in control over how that data is filtered.
As a suggestion, an optional frontend app to serve as a companion to your server side app would allow customers to setup their own feed configuration for your system if they didn't like the default filters you apply (ie a way from selecting what property statuses to include and so on). Of course this requires upfront effort at KrispyHouse, but would put the onus back on the customer to configure your integration without you needing to get involved.

**Comment by plittlewood-rpt** [comment]
Hi @AnthonyKyriacou 

That property was created in 2022 but was last modified a couple of days ago. Please can you let me know what it is that makes you think it was last modified in 2022 and I can try clear up any misunderstanding.

![image](https://github.com/reapit/foundations/assets/30798627/f99f434d-0a86-4f24-8fb3-c21c84897bcc)


Thanks
Pete

**Comment by AnthonyKyriacou** [comment]
Dear Pete,

You have provided the wrong property ID. The correct id is EAF210020.

Kind regards,


Anthony Kyriacou
*Founder & CEO*

81 Parkway
London
NW1 7PP

*T:* 0345 512 0206
*M: *07954 138663
*E: ***@***.***
*W*: www.*krispy*house.com <http://www.krispyhouse.com>

<http://www.krispyhouse.com>

      <https://www.facebook.com/Krispy-House-101108906001353>
<https://twitter.com/HouseKrispy> <https://www.instagram.com/krispyhouseuk/>
<https://www.linkedin.com/company/krispyhouse/>

This email and any files transmitted with it are confidential and intended
solely for the use of the individual or entity to whom they are addressed.
If you have received this email in error please notify the system manager.
This message contains confidential information and is intended only for the
individual named. If you are not the named addressee you should not
disseminate, distribute or copy this e-mail. Please notify the sender
immediately by e-mail if you have received this e-mail by mistake and
delete this e-mail from your system. If you are not the intended recipient
you are notified that disclosing, *copying, distributing or taking any
action in reliance on the contents of this information is strictly
prohibited.*


Krispyhouse is the trading name of Krispyhouse LTD, a company registered in
England & Wales. Registration Number 11665458

**Comment by plittlewood-rpt** [comment]
Hello again @AnthonyKyriacou. The link you provided is https://www.rightmove.co.uk/properties/128906168#/?channel=RES_LET and the reference for the property is EAL220101 (you can see this at the bottom of the Rightmove listing)

![image](https://github.com/reapit/foundations/assets/30798627/dd028e07-78f3-45b5-b3b3-931df8984557)

The reference you have given in your last comment (EAF210020)  is on the same street, but has a difference house number. It also doesn't appear in the Rightmove listings for this branch.

**Comment by AnthonyKyriacou** [comment]
Dear Pete,There’s no EAL220101 in any of East Finchley office based on our updated request we make. Again, we are not being sent the same properties and we should be.Perhaps it’s easier to discuss over the phone  Please see the request:https://platform.reapit.cloud/properties/?embed=images&lettingStatus[]=toLet&lettingStatus[]=toLetUnavailable&lettingStatus[]=arrangingTenancyUnavailable&internetAdvertising=true&marketingMode=letting&availableFrom=1970-01-01&pageNumber=1&pageSize=100&officeId[]=EAF&officeId[]=EAL&officeId[]=EANKind regards,Anthony KyriacouFounder & CEO81 ParkwayLondonNW1 7PPT: 0345 512 0206M: 07954 ***@***.***: www.krispyhouse.com        This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. If you have received this email in error please notify the system manager. This message contains confidential information and is intended only for the individual named. If you are not the named addressee you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. If you are not the intended recipient you are notified that disclosing, copying, distributing or taking any action in reliance on the contents of this information is strictly prohibited.Krispyhouse is the trading name of Krispyhouse LTD, a company registered in England & Wales. Registration Number 11665458Sent from my iPhoneOn 26 Jul 2023, at 20:08, Pete Littlewood ***@***.***> wrote:﻿
Hello again @AnthonyKyriacou. The link you provided is https://www.rightmove.co.uk/properties/128906168#/?channel=RES_LET and the reference for the property is EAL220101 (you can see this at the bottom of the Rightmove listing)

The reference you have given in your last comment (EAF210020)  is on the same street, but has a difference house number. It also doesn't appear in the Rightmove listings for this branch.

**Comment by plittlewood-rpt** [comment]
Anthony,

The link you provided me above is to property EAL220101, not EAF210020. You mentioned that you weren't displaying it because of a modified date which I've clarified with you above:

"Again, the property I referred too in the link is available to us but with outdated information (modified status is 2022) therefore we wouldn’t publish this because the information isn’t current"

Now your complaint is that the property isn't being included in the results of your query.

That property has a status of tenancyCurrent, so you'll need to include this in your query of letting status options (I pointed this out in my comment at 3.03pm yesterday afternoon). Apologies that the example query I sent you the other day did not include this status.

As stated previously, the Foundations API returns _all_ properties, and how you filter these is down to you as the developer. The APIs are not simply there to power property portals and so you need to define the rules that govern whether or not you display a property on your portal. These rules should be agreed with the customer, or you should provide the customer the ability to manage their own configuration. For the avoidance of any doubt, you'll find that if you remove all your lettingStatus query string parameters you'll get all the properties back that are listed on Rightmove (plus many others that you don't care about). This confirms that the API will return the properties you want returning.

The Foundations APIs are self-service and well documented, and as such we do not offer telephone support. The information you need to resolve your problems with this feed has all been supplied above (in summary, you need to adjust your filters according to what properties you want to be displayed on your portal) and just coming back to me with the same comments is counter-productive and isn't going to change the answers you are being given. I would recommend at this point that you speak with the agent concerned and agree with them the parameters that govern the properties that should be displayed on the KrispyHouse portal and then updated your feed accordingly. We have a number of other third parties who have set up property feeds with no issues such as this, and all of these have their manage their own configuration around what statuses to include/exclude according to what they want to display online.

Many thanks
Pete

**Comment by plittlewood-rpt** [comment]
Hi Anthony

No problem - Rightmove and Zoopla aren't fed by BLM files anymore. That ceased a number of years ago and was replaced by a real-time feed mechanism which uses a completely custom feed format for each portal. 

I disagree that the Foundations API is too complicated and we do have a number of third parties using it successfully to drive web feeds and property portals. The main difference between developers using the APIs over legacy feed formats is that the onus is on the third party to filter the data as they want to as they are pulling the data, rather than having it pushed to them. It's just that responsibility that has shifted.

Pete
