### ISSUE TITLE
Please can the Dev Ed screen be updated to show free instead of £300

### ISSUE THREAD

**Issue by JohnhennessyReapit** [reapit/foundations#9517]
Hi team,

Please can the developer edition page [here](https://developers.reapit.cloud/desktop) be updated to reflect the status of the developer account. A number of partners have said that this still says £300 even though their dev account is set to Dev Ed if Free

![image](https://github.com/reapit/foundations/assets/105904391/0742c445-c21a-4ac5-be34-f4728510a727)

![image](https://github.com/reapit/foundations/assets/105904391/fcca2045-2c21-495c-9a9c-b2a098976626)

**Comment by AshDeeming** [comment]
T&C's to be updated too

**Comment by JohnhennessyReapit** [comment]
Yes we need to remove Dev Ed at £300

**Comment by HollyJoyPhillips** [comment]
Ticket already in QA to address this, closing as it's a duplicate. Will update JH.
