### ISSUE TITLE
Generate notifications when application revisions status changes

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#952]
When application revisions are approved/rejected in the marketplace, it would be useful to fire a notification to alert the developer that the status has changed

- Create SNS or similar notification when an application revision is created
- Obtain email to generate for the developer to let them know status has changed - @HollyJoyPhillips  might be able to help us here

**Comment by HollyJoyPhillips** [comment]
**Revision Approved Notification**

**Subject:** Reapit Foundations – App Revision 

Hi ‘DEVELOPER NAME',
We just wanted to let you know that our Admin Team have now ‘APPROVED’ the latest revision for your App ‘APP NAME’. 
You can now continue to make any revisions as needed. 
Best Regards,
Reapit Team

**Revision Declined Notification**

**Subject:** Reapit Foundations – App Revision 

Hi ‘DEVELOPER NAME',
We just wanted to let you know that our Admin Team have ‘DECLINED’ the latest revision for your App ‘APP NAME’. 
It is possible that the revision did not meet our Foundations Marketplace guidelines. However, one of the Admin Team will be in contact shortly to discuss further. 
Best Regards,
Reapit Team

**Comment by cbryanreapit** [comment]
Done, turned off pending templated emails
