### ISSUE TITLE
Property Manager Relationship to Property Not Available

### ISSUE THREAD

**Issue by kmacgregorPR** [reapit/foundations#9529]
We would love for the name of the **property manager** to be available in the schema. This is one of the relationships against a property record. 

**Specification**
![PM Relationship](https://github.com/reapit/foundations/assets/128388971/4ec36f86-fbce-4812-bc1d-07a65829e7b9)

**Comment by plittlewood-rpt** [comment]
Hi @kmacgregorPR this is now available. You will need to refresh your data share in the data warehouse app and then update your models in whatever BI tooling you are using (ie Power BI). The new field is `LETTINGS_PRIMARY_PROPERTY_MANAGER_NEGOTIATOR_ID` - thanks

**Comment by kmacgregorPR** [comment]
Hi Pete, 

Thank you for this, I have done as you suggested above but still are not seeing this? Which table should we see this within?

Kind regards,
Katherine MacGregor

**Comment by plittlewood-rpt** [comment]
Hi @kmacgregorPR it's in the PROPERTIES table. If you're using Power BI or similar you'll need to update the model inside the application to see it. If you login to Snowflake directly you should see the new field. Cheers
