### ISSUE TITLE
Generate notifications when a client installs a developers application

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#953]
When a customer installs an application, it would be useful to fire a notification to alert the developer that this event has occurred.

- Create SNS or similar notification when an application revision is created
- Obtain email to generate for the developer to let them know installaton has happened. -  @HollyJoyPhillips  might be able to help us here
- We should create a webhook for this purpose too - to be handled in another ticket

**Comment by HollyJoyPhillips** [comment]
**Installations Notification** 

**Subject:** Reapit Foundations – App Installation 

Hi ‘DEVELOPER NAME',
We just wanted to let you know that your App ‘APP NAME’ has just been installed by ‘CLIENT ID’. 
To view all installations for you App, you can click on the ‘Installations’ option when viewing your App in the Developers Portal. 
Best Regards,
Reapit Team

**Comment by cbryanreapit** [comment]
Done, turned off pending templated emails
