### ISSUE TITLE
Getting the documents for our client causes an error 500 on your side

### ISSUE THREAD

**Issue by andortamas** [reapit/foundations#9534]
**Background context**

Client: GHB

**Specification**
![image](https://github.com/reapit/foundations/assets/1197217/86103896-ed13-4327-98fd-0bb53244f7d5)

**Comment by plittlewood-rpt** [comment]
Hi @andortamas this should now be resolved - for some reason the configuration this customer didn't sync where it needed to sync which we'll look into separately. Thanks
