### ISSUE TITLE
Tenancy Extension Link Restrictions

### ISSUE THREAD

**Issue by rajeshwl** [reapit/foundations#9546]
One of our mutual client  has large number of tenancy records. While importing tenancy information we are supposed to import the supporting endpoints like tenancy extensions as well. But as we are making individual calls for extensions data it increase the billings and number of requests. If you can provide the extensions link in the tenancy object only for the entries which have extension data it will avoid the unnecessary calls. Which will be helpful to reduce the costs and requests. 

Client Code : LOC(Lomond Group)

Note: This changes can be done across all the sub tenants of this customer.

**Comment by plittlewood-rpt** [comment]
Hi @rajeshwl you can already use the embed mechanism on the tenancies endpoint to embed extensions. (eg `GET /tenancies?embed=extensions`). Is this not what you are after? Thanks

**Comment by rajeshwl** [comment]
@plittlewood-rpt ,
Using `embed=extensions` will it be calculated as 1 additional request for the tenancy call of page size 25 or will it be calculated as 25 requests?

**Comment by plittlewood-rpt** [comment]
Hi @rajeshwl - as you're embedding data from the same API there isn't actually an additional charge as it's all handled in the same request.

**Comment by rajeshwl** [comment]
Thanks for the details @plittlewood-rpt .
