### ISSUE TITLE
API Addition: Add support for recent fields from Negotiator requests

### ISSUE THREAD

**Issue by craigforrest** [reapit/foundations#9547]
**Request**

In order for us to grant access to Semi-structured 'extras' field data, please provide the following information in this request:

The internally built Mobile-centric Foundations apps intend to leverage a user's recent lists, stored. A user would eb able to see their recently accessed records (starting with Contact Records, Company Records and Property Records). We would also need to write to this field so the Recent list can be updated when a record is opened.

The lists are stored against a negotiator in the extra field, and contains a list of record IDs with the maximum amount being customisable.

nRecentContacts (contains both Contacts and Company records)
nRecentProperties

an example string in AgencyCloud would be `nRecentProperties='BCK130145,BCK130308,BCK110027,RPT170021,BDF110044,RPT220002,RPT220010,BCK070160,HEO154308,RPT230003,BDF140489,BCK120039,BDF140748,BDF140196,BDF110407'`

**Comment by plittlewood-rpt** [comment]
Linked to #8787

**Comment by HollyJoyPhillips** [comment]
Hi @craigforrest can you confirm if you have the information you need so we can close this ticket as it's AC work rather than platform to support this feature request?

**Comment by plittlewood-rpt** [comment]
HI @craigforrest can this now be closed? Thanks
