### ISSUE TITLE
Are we interpreting API data correctly?

### ISSUE THREAD

**Issue by steves99** [reapit/foundations#9551]
Please take a look at our FAQ's before submitting an issue, as your question may already be covered in the documentation https://foundations-documentation.reapit.cloud/faqs

**Summary**
Looking for confirmation of our understanding of the API data

**Detail and or supporting links and screenshots**
Hello, we are partnering with estate agents using the Reapit CRM in order to provide a consolidated bills package for tenants. In order to do this, we need to query their letting properties and identify new tenancies that are starting soon.
We also need to query for tenancies ending soon so that we can manage the void period bills. We will be using the /properties endpoint and including embedded tenancies and landlord data. Could you please confirm / answer the following:
1. We will be looking for tenancies matching /properties -> response: _embedded[i].tenancies[j].status = “current” with a start date + or - 7 days from the run date. How can we know that a start date is 100% confirmed before we send utility notifications?
2. We will be looking for tenancies with an end date 0 to 7 days from the run date. If /properties -> response: _embedded[i].tenancies[j].endDateConfirmed = “true”, is that sufficient to ensure the end date is 100% certain?
3. How do we filter out tenancies that are actually renewals?
4. We want to filter out commercial properties. Is this the object to use and, if so, how do we interpret it? /properties -> response: _embedded[i].commercial
Many thanks.

**Comment by AshDeeming** [comment]
Hi @steves99 

Please note that although the logic provided for points 1 & 2 make sense - it can still be down to the Agent Populating correctly. 

With regards to commercial properties - please see the below;
