### ISSUE TITLE
Getting error message on pLet field 

### ISSUE THREAD

**Issue by Simon-Homeflow** [reapit/foundations#9553]
Issue is related to https://github.com/reapit/foundations/issues/9370

- We represent Paramount
- pLet
- see 9370
-we’re getting an error message upon requesting pLet GET https://platform.reapit.cloud/properties/{id}?extrasField=pPlet
Access to one or more of the specified fields is not permitted. You must be granted access to this data beforehand

**Comment by plittlewood-rpt** [comment]
Hi @Simon-Homeflow this is working fine at this end. Are you definitely using an access token (and correct reapit-customer header for machine to machine apps) for this customer? Can you share the customer id please to make sure we're both on the same page? Note that the field is pPlet and NOT pLet (there's a difference in what you've put in your comment above and the URL itself which is correct)

**Comment by HollyJoyPhillips** [comment]
Hi @Simon-Homeflow please can you confirm you are using the correct field name?

**Comment by Simon-Homeflow** [comment]
> 

We are now. Please close
