### ISSUE TITLE
Expose contact/tenant occupy and vacate dates

### ISSUE THREAD

**Issue by iWader** [reapit/foundations#9562]
**Is your feature request related to a problem? Please describe.**

Tenancy has 2 tenants, one tenant has moved out before the tenancy ended and in RPS shows as vacated, however there is no way on the api to see their occupy and vacate dates, or vacated status.

**Describe the solution you'd like**

Expose occupy and vacate dates on the `related` attribute of a tenancy when calling `GET /tenancies/:id` and `GET /contacts/:id` endpoints

**Describe alternatives you've considered**

N/A. Currently we don't have a solution for our customer that doesn't mean ending the tenancy and creating a new one with only the remaining tenants

**Additional context**

Screenshots and ids of our scenario can be supplied, but contain customer data so cannot upload here.

**Specification**
- Add following properties to TenancyContactModel that expose the values below

| Model Property  | Property Type | Maps To | Model Comment | Notes |
| ------------- | ------------- | ------------- |------------- | ------------- |
| occupyOn | DateTime? [ShortDate]  | addstore.vars.startDate | The date the tenant moved in (or will move in) to the property | for the main tenant, this should be set to the tenancy start date |
| vacateOn  | DateTime? [ShortDate]  | addstore.vars.endDate | The date the tenant vacated (or is due to vacate) the property | for the main tenant, this should be set to the tenancy end date UNLESS ten.extra contains `tEnd` in which case this should be used instead|

**Comment by plittlewood-rpt** [comment]
Hi @iWader we'll need to just look into this in a bit more detail. Are you working on behalf of a specific customer so I can look initially at their own data?

**Comment by iWader** [comment]
Hi Pete, the customer with this request/issue is Chelton Brown. 

The additional tenant is shown as Vacated within the RPS ui, but we're unable to identify this via the api.

Property `DAV120011`
Tenancy `DAV220296`
Main Tenant `DAV22000488`
Additional Tenant `DAV21000069`

**Comment by plittlewood-rpt** [comment]
Hi @iWader thanks for this.

So as far as things stand at the moment, when a tenant is removed:

- The item will be removed from the `related` entity on the tenancy resource (if you look at this tenancy only the main tenant is now listed)
- A journal entry is written to detail that the tenant has been removed from that tenancy. For this example, you can call the journalEntries API as follows:

`GET /journalEntries/?associatedType=tenancy&associatedId=DAV220296&typeId=MN`

I'm not sure however if this is exactly what you are looking for. Can you give me your initial feedback on the above and we can take it from there? Thanks

**Comment by iWader** [comment]
Hi Pete,

It looks like the customer may have changed something now as I'm only seeing one tenant, as you've said. 

Do you have an email I can forward some screenshots to which demonstrate the customer's issue? Going to try and replicate the same scenario in our sandbox account too

**Comment by iWader** [comment]
I've replicated this on our sandbox.

Property `MKT230431`
Tenancy `MKT230234`

Fetching this on the api shows both tenants, however one is shown as vacated, but theres no data on the api to identify this.

**Comment by plittlewood-rpt** [comment]
Thanks @iWader I see what you mean. Leave this with us and we'll come back to you.
