### ISSUE TITLE
Webooks enabled for domvs.co.uk

### ISSUE THREAD

**Issue by NicolaTPJ** [reapit/foundations#9563]
Please take a look at our FAQ's before submitting an issue, as your question may already be covered in the documentation https://foundations-documentation.reapit.cloud/faqs

**Summary**
We have gone live with the DOMVS website using Foundations, but the new instruction they have tried to include since launch hasn't arrived on the site. Can you confirm if webhooks are enabled? They are enabled at our end.

**Detail and or supporting links and screenshots**
https://domvs.co.uk/
This is the missing property: https://www.rightmove.co.uk/properties/138132851#/?channel=RES_BUY

**Comment by plittlewood-rpt** [comment]
Hi @NicolaTPJ the webhooks for this customer are indeed enabled and data is being processed. I can see that a property modified event for this property for the status changing from forSaleUnavailable to forSale was successfully sent to you on 31st July 2023 at 11:21 UTC (12:21 BST). You should be able to see this event in the webhooks transaction log in the Developer Portal also for your reference. Please let me know if you need any further assistance. I'll leave this issue open to give you chance to respond. Many thanks

**Comment by NicolaTPJ** [comment]
Thanks Peter. We can close this issue.
