### ISSUE TITLE
Dev portal users no association to sbox

### ISSUE THREAD

**Issue by AshDeeming** [reapit/foundations#9565]
Issue: Developer accounts created for the developer portal appear to be created without Org or User Claims, which is preventing them for accessing the Developer Edition of AC.

See user: hollyjoyphillips+august@gmail.com created 02/08/2023

![image](https://github.com/reapit/foundations/assets/52408607/6b7db51d-121d-4c65-9597-2432dac56673)

**Steps to replicate:** 
Create a new developer 
Observe missing claims 

Manually added the user and org claims and it resolved the issue. 

Dev Ed error:
The following exception was encountered at 14:28:18 on 01/08/2023
Company: 
Office: 
User: 
AgencyCloud Version: 12.166.0
Message: An unexpected error has been encountered when fulfilling this request. This incident has been logged and will be investigated (A valid customer id must be provided (Parameter 'customerId'))
Stack Trace
   at RPS.AppSettings.TryLoginWebServiceAuthentication(Boolean reapitConnect, String& userName, String password, AppControl& appControl)
   at RPS.AppSettings.AuthenticateNegotiator(Boolean reapitConnect, String& userName, Boolean gotPassword, String password, AppControl& appControl)
   at RPS.UI.LoginPageBase.DoLogin_Background(Object sender, DoWorkEventArgs e)

Error Log Entry
01/08/2023 14:28:18    v:    o:    n:    u:SHADOW-TLS7D1QO\Shadow    m:SHADOW-TLS7D1QO    w:Windows 10 Home    trace:at RPS.AppSettings.TryLoginWebServiceAuthentication(Boolean reapitConnect, String& userName, String password, AppControl& appControl)    message:An unexpected error has been encountered when fulfilling this request. This incident has been logged and will be investigated (A valid customer id must be provided (Parameter 'customerId'))

**Comment by AshDeeming** [comment]
manually fixed for one user - adding: 
UserClaim: agencyCloudNegId: ADV
&
Org Claim: agencyCloudId: SBOX

**Comment by plittlewood-rpt** [comment]
Finally got to the bottom of what's actually happening here. Separate frontend bug logged in #9644 which was effectively being the driver for the member's profile being updated, and getting the sandbox customer id assigned
