### ISSUE TITLE
Fixflo Reapit test account 

### ISSUE THREAD

**Issue by MarceFF22** [reapit/foundations#9568]
Hello, 

I hope you are doing well. 

Our mutual client Jones Robinson is thinking of integrating Fixflo and Reapit. Before going ahead, Anna asked me to test the functionality of the Organiser panel 'Compliance'.

![image](https://github.com/reapit/foundations/assets/119598247/98174146-94f2-4ada-90c7-3e24909063a8)

![image](https://github.com/reapit/foundations/assets/119598247/ed199e45-9473-4b35-96a5-b43c12569e3b)

They use the panel to double-check that an SE event has a works order/been instructed.

I've been trying to show her the functionality with Fixflo integration using our Reapit test account. However, I cannot get to the same view as Jones Robinson, see their screenshot above.

![image](https://github.com/reapit/foundations/assets/119598247/714f9e31-9782-4eb3-ab91-5cd3526b8b26)
![image](https://github.com/reapit/foundations/assets/119598247/d919e65b-a303-443f-b654-bfccd8e3b79c)

Anna and I tried to go through it together, but we simply cannot work it out. Can you please help me with the configuration on our end, so I can demo Anna the functionality?

I hope the above makes sense, please let me know if you need any further details. 

Many thanks, 
Marcela

**Comment by AshDeeming** [comment]
Hi @MarceFF22 
The certificates can vary for each client & is therefore held within the /configuration/certificateTypes & /configuration/certificateTypes/{id}

With regards to inspections, these again may differ per client however the configuration/appointmentTypes will show which type of appointments are in each build.

**Comment by MarceFF22** [comment]
Thank you - can you please help me to configure our sandbox account so it
shows as Jones Robinson's?

**Comment by AshDeeming** [comment]
Hi @MarceFF22 
The sandbox configuration is generic/standard for all developers to us and can not be amended
