### ISSUE TITLE
As an ‘Admin’, I want to search for App Registrations by date in the Admin Portal 

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#957]
**Summary**: We should be able to produce a list of Apps registered based a date range

Given that I am an Admin, when I am on the Admin Portal Apps section, I should then have the option to filter by date to see Apps  Registered

**Location**: https://dev.marketplace.reapit.cloud/admin/apps

**Task**: To add a date filter to the ‘Apps Management’ page in the Admin Portal 
- Should include RegisteredFrom and RegisteredTo date filtering 
- Should also display ‘totalCount’

**Comment by HollyJoyPhillips** [comment]
Hi @ant066 , Thanks for the update. Unfortunately, I can't seem to search on just date range alone. It requires either an App Name, Developer or Company. 
I should be able to search on just a date range. Is this possible? 
![image](https://user-images.githubusercontent.com/52408607/79881167-cb056080-83e8-11ea-95b5-013cce4bfba9.png)

**Comment by ant066** [comment]
> Hi @ant066 , Thanks for the update. Unfortunately, I can't seem to search on just date range alone. It requires either an App Name, Developer or Company. 
> 
> I should be able to search on just a date range. Is this possible? 
> 
> ![image](https://user-images.githubusercontent.com/52408607/79881167-cb056080-83e8-11ea-95b5-013cce4bfba9.png)
> 
> 

Yes sure! I will update on next day
