### ISSUE TITLE
We seem to be showing the branch on an appointment

### ISSUE THREAD

**Issue by danielalmeidaconnellsgroup** [reapit/foundations#9573]
When we are making an appointment on the sandbox, we appear to be linking the whole branch to the appointment  - example property: MKT232641

 Are you able to advise what we're doing incorrectly?

![image](https://github.com/reapit/foundations/assets/126185395/0dc21f85-5ea1-452b-a322-cf074f326f28)

I assume we're setting a link to the branch for an appointment

**Comment by AshDeeming** [comment]
Hi @danielalmeidaconnellsgroup 
The field above would relate to the OfficeID's being associated to the Appointment when created.

**Comment by danielalmeidaconnellsgroup** [comment]
Hi Ash - thanks for the reply - so all we need to do is remove the office ids from the appointment request and we're good?

**Comment by AshDeeming** [comment]
That's correct @danielalmeidaconnellsgroup

**Comment by danielalmeidaconnellsgroup** [comment]
Thanks Ash.
