### ISSUE TITLE
Enhance tenancy break clause endpoint (POST, PATCH)

### ISSUE THREAD

**Issue by abrahamseni** [reapit/foundations#9574]
Endpoint: `tenancies/{id}/breakClauses`

We can read `breakFrom` and `noticeRequired`, could we also add these properties when POST/ PATCH a new break clause?

Payload:
```json
  "breakFrom": {
    "date": "2023-07-30",
    "minTermMonths": null
  },
  "noticeRequired": {
    "date": "2023-12-31",
    "beforeBreakMonths": null
  }
```

Link to #9495

Thanks

**Specification**
- Project: Reapit.Services.Tenancies
- Double check the break from recalculation logic that was added as part of #9495 (we may have implemented this in the inverse manner to how it should have been)
- Provide ability to write the fields above

**Validations**
- minTermMonths/beforeBreakMonths should be non-negative integers when provided

**Comment by plittlewood-rpt** [comment]
@abrahamseni  you were specifically asked whether you needed write access as part of #9435. Please can you advise why this has changed as the work was planned in to be read only because of your original response. Thanks

**Comment by abrahamseni** [comment]
@plittlewood-rpt , I think I misunderstood you, I assume read only for `letterText` but not for `breakFrom` and `noticeRequired`, or are those three dependent properties when posting?
