### ISSUE TITLE
New API Endpoint - Patch Enquires 

### ISSUE THREAD

**Issue by jazzlall** [reapit/foundations#9589]
There's a requirement for an extension to the current Enquires endpoint to provide the ability to update existing enquires in Agency Cloud to actioned/added and therefore no longer appear in Agency Cloud to be actioned. 

This is relates to the IRE integration into Agency Cloud where they'll be processing these leads through their platform. 

**Specification**
- Project: Reapit.Services.Enquiries
- New endpoint `PATCH /enquiries/{id}` protected by scope `enquiries.writes`
- Support update to the status only which should be one of the existing enumeration values

**Payload**
```
{
   "status": "added",
   "applicantId": "ABC123456"
}
```

**Behaviour**
- When status = 'added' applicantId must also be specified. This should be stored in appimp.aExtra.aCode
- When status = 'added' and there is a user in context, store the negotiator code of the user changing the status in appimp.aExtra.aCode

**Validations**
- Status must be valid enum value
- When status is _changed_ to added, applicantId must also be provided (domain validation)

**Comment by plittlewood-rpt** [comment]
Hi @jazzlall presumably it's just the ability to update the status of the enquiry they need here (ie added/spam/reject)

**Comment by jazzlall** [comment]
That's correct @plittlewood-rpt

**Comment by plittlewood-rpt** [comment]
Hi @jazzlall  we've spec'd this out above. One question that came up was removing the call to action from the user (ie they aren't clicking Add anymore) have we considered how the agents will know they have new applicants on their system (other than the obvious to call list etc)

**Comment by jazzlall** [comment]
In this particular use case, they're being checked off in Internet Registrations because they've been have a appointment created for a viewing/valuation so the branch staff we be notified by other means as part of the that process.
