### ISSUE TITLE
"Do not chase" tenancy field required

### ISSUE THREAD

**Issue by Speedway1** [reapit/foundations#9591]
**Request**

In order for us to grant access to Semi-structured 'extras' field data, please provide the following information in this request:

- The name of the customer you represent: 
     A whole lot of them. The most urgent for now are
        Folio
        Life Residential
        The development "SBOX" instance
        However a lot of others will be added to this in quick succession as we roll out the feature.

- The name of every field you need surfaced (if known)
                       "DO not chase"

- A screenshot of of the field(s) you require in the agency cloud user interface
          
![48aa31953a576eb4ddbca08f281d139441d95e56c6799538bb3dc4d6295b90d7](https://github.com/reapit/foundations/assets/100301611/aa5d9f27-81d4-46dd-819b-8b8559723d06)

- A short use case as to why you require this data
    We send automated reminders to customers who haven't paid their rent on time. Customers who have the "Do not chase" flag set must NOT be sent these reminders. At present, we cannot get to this setting through the published APIs.
    

**Specification**
- Project: Reapit.Services.Tenancies
- Add new `TenancyArrearsModel` object to `TenancyModel` called Arrears:

```
"chase": false
```

- If client accounts is disabled (check config using the configuration client package) set arrears object to null rather than presenting default chase value
- Exposes `ten.extra.tExclChaseArrs`
- Read only
- tExclChaseArrs=.T.

**Comment by plittlewood-rpt** [comment]
Hi @Speedway1 can you confirm whether you'll need write access to this field?

**Comment by Speedway1** [comment]
Hey Pete, I don't believe that we do. Just read access. Thank you, Brad

**Comment by HollyJoyPhillips** [comment]
Waiting confirmation from the Foundations team before we can continue.

**Comment by HollyJoyPhillips** [comment]
Foundations team have confirmed we can proceed. Moved to near term as a specification has already been added.

**Comment by plittlewood-rpt** [comment]
This data is now available. Please refer to updates to `TenancyModel` which now includes a new `arrears` object which will be populated when client accounts functionality is enabled in the AgencyCloud CRM (otherwise it will be null). Any issues please reach out to us. Thanks
