### ISSUE TITLE
App access - existing client, new agency

### ISSUE THREAD

**Issue by madebyparent** [reapit/foundations#9594]
We have 2 existing clients on Reapit (Curchods and Seymours) but need access to a third that has an existing app with another developer — Is it possible for us to get access to the app for Berkshire Hathaway Home Services London so that we can access data.

Or, I'm happy to have a new app, on our account, but this sig-up requires their billing details, which you must already have.

Hope you can help.

**Comment by AshDeeming** [comment]
Hi @madebyparent 
If you have an app available to the above mentioned clients, you can add the 3rd clientID to the app to allow it to be visible to their admin user(s)
Could you confirm your app name & we can review in more detail?

**Comment by madebyparent** [comment]
Hi Ash

Sorry, the app we have is for another client. 
But this client does have an existing app with another web developer.

Thanks
Chris Harman
—
Parent®

**Comment by AshDeeming** [comment]
@madebyparent 
Apologies for any confusion;

If you require access to an existing developer account, a user from that account can invite you - Please note that email addresses are unique for the Platform & therefore one email would only access one developer account.

**Comment by madebyparent** [comment]
Hi

We currently have 3 logins / accounts to manage different clients;

***@***.*** ***@***.***>
***@***.*** ***@***.***>
***@***.*** ***@***.***>

We have set-up ***@***.*** ***@***.***> as an email that could be used for this.
In the case of a fresh client like Curchods <https://curchods.com/> we created the account and the app.

In this case, Berkshire Hathaway already have an app. 
We EITHER need access to that existing app using our bhhs@ address; OR to create a new app using that email, but essentially a mirror of the existing app (used by another developer).

I think the best route forward is for us to have a separate account using ***@***.*** ***@***.***> and create a new app for Berkshire Hathaway. But part of the set-up asks for all their billing details and presumably you already have these?
How does it normally work when a client changes developer?

I hope that makes sense?

Thanks
Chris Harman
—
Parent®

**Comment by AshDeeming** [comment]
Thanks @madebyparent /Chris

Does the app that Berkshire Hathaway have, under a developer account under their control? If so they can invite you to that Developer Org as a member. 

If a new developer account is required for your app & this is under MadeByParent, you will be liable for Charges and API consumption & account information required to complete the setup.
