### ISSUE TITLE
Show Extra Fields in Reapit Properties endpoint for Easthaus

### ISSUE THREAD

**Issue by jhumeey** [reapit/foundations#9596]
**Request**

In order for us to grant access to Semi-structured 'extras' field data, please provide the following information in this request:

- The name of the customer you represent
   → Easthaus
- The name of every field you need surfaced (if known)
  → Location, Situational, Directions
- A screenshot of of the field(s) you require in the agency cloud user interface
![image](https://github.com/reapit/foundations/assets/38222819/fe6356f5-cda5-4723-8cbb-5285997f288a)

- A short use case as to why you require this data
 → The client asks to have these data displayed on the Webflow site that is using an automation to sync the data between Reapit and Webflow

**Comment by AshDeeming** [comment]
EHA

**Comment by plittlewood-rpt** [comment]
Hi @jhumeey the fields are now enabled for this customer and should be reqeusted explicitly using the `extrasField` query string parameter as below

| Field  | Query String Parameter Value |
| ------------- | ------------- |
| Situation | pSituation |
| Location  | pLocation |
| Directions  | pDirections |

eg:

`GET https://platform.reapit.cloud/properties?extrasField=pSituation&extrasField=pLocation&extrasField=pDirections`

The same can be applied to the Get By Id endpoint eg:

`GET https://platform.reapit.cloud/properties/ABC123456?extrasField=pSituation&extrasField=pLocation&extrasField=pDirections`

Please note that the long description makes part of the standard API contract. See `PropertyModel.longDescription`

The configuration changes should synchronise across the API estate within the next 15 minutes but please get in touch if you have any issues with it

Many thanks
Pete

**Comment by jhumeey** [comment]
Thanks @plittlewood-rpt , i have confirmed that this works very well.
Thank you very much
