### ISSUE TITLE
Unable to PATCH checks when renewal at renewed stage

### ISSUE THREAD

**Issue by abrahamseni** [reapit/foundations#9599]
**Describe the bug**
when we PATCH this renewal negotiations check: `https://platform.reapit.cloud/tenancies/{id}/renewalNegotiations/{renewald}/checks/{checkId}`
The API rejected it because `it is not possible to update checks when renewal is at 'renewed' stage`

**Expected behaviour**
The check status is changed

**Screenshots**
![Screenshot 2023-08-08 034843](https://github.com/reapit/foundations/assets/94949137/e47bbb09-e5ba-436b-8ee9-f29ebe89e3e5)

**Specification**
- Project: Reapit.Services.Tenancies
- We've checked with the CRM team and it's OK to allow updates to checks once a renewal completes and there is no security around this. Update `UpdateTenancyRenewalCheckComnmandHandler` to allow checks to be updated when the renewal has completed and is in the Renewed status.

**Comment by HollyJoyPhillips** [comment]
Hi @abrahamseni After looking into this further, the option to bypass the ability to ignore the current tenancy rules is part of the security configuration which we don't current expose or read via the Platform API. However, it is on our roadmap for later in the year. You can follow our milestone here https://github.com/reapit/foundations/milestone/171

**Comment by abrahamseni** [comment]
Hi @HollyJoyPhillips , am I right to assume that this can be done in AC?
I mean in AC, checks can still be amended after the status has been set to renewed.

**Comment by abrahamseni** [comment]
Hi @HollyJoyPhillips , Thanks, I will discuss it with the team.
