### ISSUE TITLE
Is it possible to query properties based on property owner id?

### ISSUE THREAD

**Issue by ss-dimasm** [reapit/foundations#9602]
**Summary**
Hi,
Is there any way to retrieve paginated properties based on property owner's (could be landlord or vendor) id? does the `masterId` query param handle this?

Thanks

**Comment by AshDeeming** [comment]
Hi @ss-dimasm 
The LandlordID is a current parameter for Get Properties & vendorID can be obtained via the propertyID.

As the Contact level is where the associated records are stored, could this be the parameter you are looking to query by?

**Comment by ss-dimasm** [comment]
Thanks @AshDeeming 

for upcoming requirements we want to query the properties based on landlord and vendor contact details, looks like is fine for landlord perspective but not for vendor. Imagine we would have 2 search fields, first it should be the vendor/landlord name and the second for choosing the marketingMode of property.
Regarding to not supported vendor case (assuming if we already select the "sales" on the marketingMode field), our planned flow is to query the paginated vendor service first based on the passed name search term, and then we will hit the paginated properties by passing the retrieved vendor Ids from vendor service. So in this case we couldn't retrieve the properties that related with the vendor Ids that we have pass previously since there aren't vendorId param in the properties service. Am I right for this scenario?

**Comment by ss-dimasm** [comment]
Hi @plittlewood-rpt it's very clear now and it's more efficient than before, thank you for the insight. Previously I don't know if we could retrieve the sales properties based on passed vendor id with `id` param on there. Once again thanks 👍

**Comment by plittlewood-rpt** [comment]
No problem! Glad to help
