### ISSUE TITLE
Strip out "Key Feature" bullets from Reapit Foundation feed

### ISSUE THREAD

**Issue by Simon-Homeflow** [reapit/foundations#9605]
**Background**
Homeflow representing Frost & Co

The Reapit BLM previously supplied did not send bullet characters in the "Key Features" and the Reapit Foundation feed does causing duplicate bullets to be displayed on client website.

**Specification**
Please remove bullet characters from Reapit Foundation feed for "Key Features" data.

Feed output:
![image](https://github.com/reapit/foundations/assets/119927358/d261f717-63c1-4cc5-a719-548bfde55050)

**Comment by AshDeeming** [comment]
Hi @Simon-Homeflow 

Please could you confirm the property ref for review. 

The way a client may use AgencyCloud may vary however the above appears to relate to Rooms within the Properties payload.

**Comment by Simon-Homeflow** [comment]
Hi @AshDeeming This is one of the properties causing an issue BFL230242. This is an extract from our log fil:
`"features":["• LILLIPUT AND BADEN POWELL SCHOOL CATCHMENT","• OUTSTANDING VIEWS OVER THE HARBOUR WITH DIRECT WATER FRONTAGE","• SLIPWAY WITH POWER WINCH FOR LAUNCH AND RECOVERY OF BOATS UP TO ABOUT 7M OR BRING YOUR SEALEGS RIB!","• SIGNIFICANT POTENTIAL TO REMODEL OR ADD ANOTHER LEVEL","• FIRST FLOOR BALCONY/ TERRACE WITH VIEWS","• DOUBLE GARAGE","• OUTDOOR HOT \u0026 COLD SHOWER","• WATER SOFTENER","• WALKING DISTANCE TO LOCAL LILLIPUT SHOPS AND CAFE'S","• GATED ENTRANCE"],"summary":"WATER FRONTAGE `

**Comment by AshDeeming** [comment]
Hi @Simon-Homeflow 
I'm unable to locate that property ref 

Could you confirm the client ID (3 digit code) for this customer please?

**Comment by AshDeeming** [comment]
Hi @Simon-Homeflow 

Please note that this data is being populated in the Accommodation summary within the Rooms section of AgencyCloud; 
![image](https://github.com/reapit/foundations/assets/61687775/42b10d62-11fa-46f2-bc38-06f584689cee)
