### ISSUE TITLE
Our public app Push.Property does not seem to have an activate/install button

### ISSUE THREAD

**Issue by ianscotland** [reapit/foundations#9612]
Our app "Push.Property" was recently made public but clients do not see an activate button
![f25aa1e3-85c5-4163-8535-d80369dbe28a](https://github.com/reapit/foundations/assets/3473797/bf8e08c9-06a6-4f5d-a5eb-968881a79688)

**Comment by HollyJoyPhillips** [comment]
Hi @ianscotland, the user on your screenshot does not have the correct permissions to install or enable integrations, please see https://foundations-documentation.reapit.cloud/faqs#why-can-i-not-see-the-option-to-install-app-or-enable-integration. Thanks.
