### ISSUE TITLE
The contacts api endpoint is timing out

### ISSUE THREAD

**Issue by philiphoy** [reapit/foundations#9613]
The contacts api endpoint is timing out for a particular agency

e.g.
`https://platform.reapit.cloud/contacts/?pageSize=1`

For app with a client id 6ulmp4obd1lrim14u8cajhvvhq and customer id LOC-GJUW

**Comment by HollyJoyPhillips** [comment]
Hi @philiphoy, please can you provide a screenshot of the exact error which includes the date and time the request was made and the method. Thanks.

**Comment by HollyJoyPhillips** [comment]
Internal note: ...contacts/?modifiedFrom=2000-01-01T00%3A00%3A00.0000000Z&pageSize=1

**Comment by philiphoy** [comment]
I am making an api call so can't really send a screenshot. I tried one at 10/08/23 9:33 am it timed out after around 60 seconds

**Comment by HollyJoyPhillips** [comment]
Hi @philiphoy Thanks, we were able to locate the error through our logs. We'll need to look into this further following our refinement session this afternoon.

**Comment by plittlewood-rpt** [comment]
@philiphoy I've made some improvements to the querying on larger datasets which are just in PR waiting for review. I'll let you know once the changes go out.

**Comment by plittlewood-rpt** [comment]
HI @philiphoy  these changes have now gone out to production. Can you run some tests and let me know the results? The API is significantly faster now so this should be the end of it.

**Comment by philiphoy** [comment]
Great I now get a response from the api. Thank you

**Comment by plittlewood-rpt** [comment]
Thanks. Latency looks good too, I can see the requests you've made. Will close this item down
