### ISSUE TITLE
Increase Address Line 1 and Area fields char limit 

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#9615]
**Related**: SI-20672 & 
**Dependent on:** AC-9336

**Summary:** AC have increased the character limit for 2 fields (see related tickets). We should update our Properties & Areas API to ensure consistency.

**Specification**
- Project: Reapit.Services.Properties
- Increase char limit for Address line 1 '`line1`' to 50
- Project: Reapit.Services.Areas
- Increase char limit for Area '`name`' to 50

**Comment by plittlewood-rpt** [comment]
@HollyJoyPhillips  do we know if this has been rolled out to all customers? From the original ticket it looks like it was applied to the customer(s) that had requested it. We can't do anything platform side unless all databases have the change

**Comment by HollyJoyPhillips** [comment]
Thanks Pete, I've reached out to that department for more information.
