### ISSUE TITLE
missing fields in reapit

### ISSUE THREAD

**Issue by themagictractor** [reapit/foundations#9616]
**Background context**
https://gherbertbanks.co.uk/property/ Residential, Agricultural and Commercial property pulled into 3 different areas on the previous Jupix feed, it seems now using Reapit that all the properties have either gone to either “to buy” or “to let” (under ‘residential’). It looks like there is no longer an agricultural or commercial property area as there was with Jupix? Is there a way to create Commercial and Agricultural as property types on Reapit alongside “to buy” and “to let” If ’yes' please share where we can find these fields? 
**Specification**
Please share where we can find these fields?

**Comment by plittlewood-rpt** [comment]
Hi @themagictractor - this is managed with departments in AgencyCloud (and therefore the APIs). I've just checked the system for this customer, and they have three departments configured:

General - used for residential stock
Commercial
Land/Agriculture

You can see the configuration of these departments at GET platform.reapit.cloud/departments (this endpoint will give you the ids you need) and then filter the property data by using the departmentId filter on the GET /properties endpoint.

Please let me know if this is unclear, but it should answer your question. Hope this helps
