### ISSUE TITLE
spike: Feasibility study for adding support for key-pair authentication to data warehouse reader accounts

### ISSUE THREAD

**Issue by plittlewood-rpt** [reapit/foundations#9625]
**Background context**
To provide a higher level of security for customers wishing to build automated server side processes that utilise data in their Snowflake reader account, we should investigate whether or not Key-Pair authentication can be supported in our warehouse offering. 

**Specification**
- Consult docs at https://docs.snowflake.com/en/user-guide/key-pair-auth and understand if this can fit into our model of provisioning reader accounts for customers.
- It's likely we would need to add the ability to setup users in the Data Warehouse app with a higher privilege than is currently possible (security admin role) so customers could manage this themselves. Alternatively, we'd need to manage the attachment of the key to the user(s) concerned through our admin backend

**Comment by roscoe2001** [comment]
This is a little off at a tangent on this one but maybe considering when deciding on the solution, one other issue we have is we can't create Temp-Tables within our SQL (because of the read only permissions). I know above references : -

>>It's likely we would need to add the ability to setup users in the Data Warehouse app with a higher 
>> privilege than is currently possible (security admin role) 

I don't know if that would get us around the temp table issue as well

**Comment by roscoe2001** [comment]
Hi
Can I just check on the status on this one please?
The reason I'm checking is this has been on the backburner for us for a while but at the end of this year Fivetran is being switched off so we're going to need a secure/MFA mechanism of connecting to the Snowflake via the DataWarehouse

**Comment by plittlewood-rpt** [comment]
Internal notes: if this is something we move on, we should look at adding ip policy management in the data warehouse app at the same time. This will need the following updates to suit all changes:

UPDATE POST /Accounts and PATCH /Accounts/{id} to accept:
 - Public key
 - Password is optional when public key provided
 - Backend behaviour is to set public key to the one provided on the new account, and disable password login when password is null

UPDATE POST /Customers and PUT /Customers/{id} to accept:
 - `string[]`IpPolicy`
 - When IpPolicy provided, setup/amend network policy on the customers reader account
 - Ensure Reapit addresses are always set on any IP policies so we don't lock ourselves out

**Comment by plittlewood-rpt** [comment]
Hi @roscoe2001 this is something that's technically possible. Unfortunately we don't have any resources that we can commit to this in the short term however we'll log an internal ticket so that when the roadmap priorities align we'll be able to look at this again and reach out to you as appropriate.
