### ISSUE TITLE
UK MAP Instances Still Missing Listing Images

### ISSUE THREAD

**Issue by Endlay** [reapit/foundations#9627]
**Background context**

We are still experiencing issues around Listing images not being all accessed via the app, depending on who it is, it is about 1-10% of images per client. Below is the latest update with instructions to consult with the platform team.

"When we open it, for those missing images, the original source of that image can’t be accessed, it cause our system can’t fetch it properly

for example:

![image](https://github.com/reapit/foundations/assets/128380605/1dd89d66-cace-457a-a4ea-516886e010ee)

the original source from API is https://assets.reapit.net/bnd/live/pictures/LDN/23/LDN230111_04.jpg

and when we try to open it from the browser manually it gives them this:

![image](https://github.com/reapit/foundations/assets/128380605/7a53feee-0aa2-4515-97a6-67c74d4bfdd3)

**What is required**

Assist with the investigation from platforms.

**Comment by plittlewood-rpt** [comment]
Hi @Endlay that image doesn't exist against the property, nor is it being returned by the API

**Comment by plittlewood-rpt** [comment]
As discussed with @Endlay I will send a summary email that can be circulated to the relevant parties

**Comment by Endlay** [comment]
thank you @plittlewood-rpt

**Comment by plittlewood-rpt** [comment]
@Endlay I'm going to drop this out of our sprint as we aren't getting any useful information back. Please let me know once there's some information to work from.

**Comment by Endlay** [comment]
Yes please @plittlewood-rpt. thank you.
