### ISSUE TITLE
Add ability to create auth code flow product apps that also generate a secret

### ISSUE THREAD

**Issue by plittlewood-rpt** [reapit/foundations#9630]
**Background context**
So that Keycloak can federate with Reapit Connect, it needs a secret to accompany the oauth client id when using an authorization code flow. This is supported in Cognito, but not my the POST products endpoint at this time. For authorization code flow apps, the secret is used when completing the token exchange

**Specification**
- Project: Internal user/organisations service
- Update create product endpoint to support new `generateSecret` boolean in oAuth properties. When true, authorization code flow apps should also have a secret generated

**Comment by plittlewood-rpt** [comment]
This shouldn't need to be done. Need to understand the requirement behind this as feels like miscommunication somewhere. PL to pick up with RM

**Comment by HollyJoyPhillips** [comment]
Not required
