### ISSUE TITLE
Cooper Adams Property Descriptions Not Pulling Through Correctly

### ISSUE THREAD

**Issue by BYMIntegrations** [reapit/foundations#9631]
Please take a look at our FAQ's before submitting an issue, as your question may already be covered in the documentation https://foundations-documentation.reapit.cloud/faqs

**Summary**
Some of the property descriptions for Cooper Adams are pulled through with "*Error*" in them by our BriefYourMarket Integration App. I have checked the API and the descriptions contain \r and \n which we believe is causing the issue.

Please can these be removed from the property descriptions on properties RUS170914 and RUS210257.

**Detail and or supporting links and screenshots**
[RUS170914.txt](https://github.com/reapit/foundations/files/12334797/RUS170914.txt)
[RUS210257.txt](https://github.com/reapit/foundations/files/12334798/RUS210257.txt)
![cooper adams 1](https://github.com/reapit/foundations/assets/102583061/6335c46a-d3e9-43d1-903a-89c28e624f26)
![cooper adams 2](https://github.com/reapit/foundations/assets/102583061/09648bf4-cdaa-43a1-9976-bd5ca64e7054)

**Comment by HollyJoyPhillips** [comment]
Hi @BYMIntegrations the text file seems to be from our Platform API but the screenshot seems to be populated by the BLM file. Both properties are using square brackets to separate paragraphs and are treated as merge codes which render in the BLM file as **error**: 

BLM: 
![image](https://github.com/reapit/foundations/assets/52408607/8dce207f-0bd2-46b8-ac29-7621663fb6f1)

Properties API: 
![image](https://github.com/reapit/foundations/assets/52408607/c70b74d4-13b4-4b3a-afb5-6b725f64980f)

Having looked at the BLM file, it seems they have over 20+ properties with errors. The BLM is a legacy feed format and is one of the limitations that makes the migration to use the Platform APIs more suitable.

**Comment by BYMIntegrations** [comment]
Hello Holly,

I hope you are well.

I have looked and there is something wrong with how we are processing. At a hunch with what you have said above, I have checked our Data Warehouse and the data is correct in there, which is populated by the Foundations API.

I believe the issue is with how we are processing the "\r \n". Could you please remove these characters from the description so I can see if this resolves the issue?

To clarify, the screenshots are populated by the data we receive and process from the properties API.

 If you have any questions, then please let me know 😊

Thanks,

Toby Hunter 
Integrations and Support Analyst

0344 800 84 24 (Ext 222) | [TobyH@briefyourmarket.co.uk](mailto:TobyH@briefyourmarket.co.uk)
[www.briefyourmarket.com](http://www.briefyourmarket.com/)

**Comment by HollyJoyPhillips** [comment]
Hi @BYMIntegrations the data returned via the API represents carriage returns (JSON format) which is set by the customer in the CRM (AgencyCloud). We wouldn't be able to edit customer data. 

However, it is possible the customer is copying and pasting text which could include background formatting such as characters which are part of extended character sets. For example: 

Formatted: 
![image](https://github.com/reapit/foundations/assets/52408607/792c83cf-1776-42e3-a759-d8cc9df8ef64)

Straight: 
![image](https://github.com/reapit/foundations/assets/52408607/0f6316d2-5079-4f75-a43b-c8fdcaeadac3)

![image](https://github.com/reapit/foundations/assets/52408607/d241d68c-0bb5-461d-9456-ae9ba442e37c)

I would suggest in the first instance, speaking to the customer and asking them to amend the special characters and debug from there.

**Comment by BYMIntegrations** [comment]
Hello Holly,

I hope you are well.

Thanks for your help and all the information.

If you have any questions, then please let me know 😊

Thanks,

Toby Hunter
Integrations and Support Analyst

0344 800 84 24 (Ext 222) | [TobyH@briefyourmarket.co.uk](mailto:TobyH@briefyourmarket.co.uk)
[www.briefyourmarket.com](http://www.briefyourmarket.com/)
