### ISSUE TITLE
Reset login password

### ISSUE THREAD

**Issue by shanelilly** [reapit/foundations#9641]
**Describe the bug**
I cannot reset my password. I get an error message asking me to contact support. 

**To Reproduce**
Steps to reproduce the behaviour 
1. Go to https://connect.reapit.cloud/login
2. Click on Forgot my password?
3. Input my account into the reset password textbox (shane.lilly@distilled.ie)
4. Click 'Reset my password' button
5. See error - "Could not reset password for the account, please contact support or try again"

**Expected behaviour**
I receive an email outlining steps to allow me to reset my password and access my account.

<img width="372" alt="Screenshot 2023-08-15 at 11 33 17" src="https://github.com/reapit/foundations/assets/49612475/e2ea3c0d-c5c8-4e7f-b92b-7458bcc6a348">

**Comment by AshDeeming** [comment]
Hi @shanelilly 
A password reset has now been issued.
