### ISSUE TITLE
Organiser panel is not updating (Fixflo integration)

### ISSUE THREAD

**Issue by MarceFF22** [reapit/foundations#9643]
Our mutual client Jones Robinson (JOR) flagged an issue with their Compliance panel in Organiser. 

**To Reproduce**
1. Go to property PRO210020 (118 Bartholomew Street, Newbury, Berkshire, RG14 5DT)
2. You can see that there's a works order under the status 'Raised' for a Gas Safety inspection. (A contractor has been instructed.)
3. If you go to the Organiser and see the Compliance panel -> Gas safety inspections due in the next 90 days. The property is listed, but the 'works order' column doesn't update with the works order date from the issue. 
![image](https://github.com/reapit/foundations/assets/119598247/e648f2e3-e8da-4828-be3a-74e3c2841f95)

**Expected behaviour**
The 'works order' field should be updated with a date according to the raised works order relating to the Gas safety inspection. 

**Specification**
Compare the worksOrder creation routine for gasInspection for AC and Platform. Ensure all relevant associated Id's are set to understand why the worksOrder is not shown on the organiser panel

**Comment by plittlewood-rpt** [comment]
HI @MarceFF22 this actually relates to something my colleague @HollyJoyPhillips emailed Lewis Bray at Fixflo about last week. In summary, the Fixflo system is passing invalid values for the `typeId` property when posting/patching the works order to the respective endpoint. As a result this means the data isn't linking up as it should do in the CRM. I've corrected the example you provided above manually, but ultimately Fixflo need to resolve the underlying issue. For Gas Safety inspections, in the JOR build you need to be passing a typeId of GS. The different type ids are accessible at GET /configuration/worksOrderTypes. We have advised Lewis that we will need to add validation in for this field which has been missed, however as this would break your existing integration we will hold off doing this until we've heard back from Fixflo. This is logged separately in issue #9697

**Comment by plittlewood-rpt** [comment]
Nothing to QA as no issue here with the API - will leave item open until third party respond

**Comment by plittlewood-rpt** [comment]
Hi @MarceFF22 for info myself and @HollyJoyPhillips  had a call with Kate at your end today and this was one of the items on the agenda. I'll leave the item open until we know it's been resolved.

**Comment by plittlewood-rpt** [comment]
Hi @MarceFF22 I'm going to close this issue. Your dev team are about to release an update that will not set the typeId at all, which will mean users need to set the type manually. This will mean until they do this, the organiser panel won't update. Kate is aware of the underlying issue but it's not a quick fix due to the UX in the Fixflo app.

**Comment by MarceFF22** [comment]
Good morning, thank you for your update. What typeId should the client set up so it updates the 'Organiser' panel? Or are you saying that unless it's done automatically, this will not work? Thank you for clarification.

**Comment by plittlewood-rpt** [comment]
Hi @MarceFF22, Kate has the details. The typeIds are configurable per customer and Fixflo need to look up the correct value for gas safety. This is _usually_ GS, but can differ between customers. All customers should have  a Gas Safety type already.
