### ISSUE TITLE
Logins are very slow when environment is cold

### ISSUE THREAD

**Issue by plittlewood-rpt** [reapit/foundations#9647]
**Background context**
Logged from #9479 

When the new Reapit Connect environment is cold (ie all Lambda containers have been disposed of) the next login is very very slow. This is very noticeable and will likely be picked up by users from time to time. We should consider whether having a keep warm event is necessary here that is triggered periodically by eventbridge or similar (we do this in Platform to try and get around cold start latency)

**Comment by joshbalfour** [comment]
Given the distributed nature of lambda@edge i don't think a keep-warmer would work, but we could minimise the number of lambdas in the login flow to minimise the cumulative cold-start time

**Comment by plittlewood-rpt** [comment]
It might not even be necessary to be honest. In production it's probably unlikely that you'll see this as the lambdas will be being hit so frequently

**Comment by joshbalfour** [comment]
It's a fair thing to look into, it's relevant with high-traffic lambdas too because if you have two parallel requests one would use the warm one and the other would spin up a new one with the cold boot time.
