### ISSUE TITLE
Automated email service

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#9655]
**Summary**: To better support partnerships and internal departments we would like to create an auto generated email containing the following information. 

**Sections**: 
**Registered Apps this month**
- **Fields**: App Name, Company Name (Developer Name), Listed, Integration, Date Created
- **Endpoint**: apps?registeredFrom=2023-07-01&registeredTo=2023-07-31

**Apps with pending approvals**
- **Fields**: App Name, Company, Summary, Date Revision Created
- **Endpoint**: /approvals 

**Apps made public this month** 
- **Fields**: App Name, Company, Summary, Date made public
- **Endpoint**: apps?publicListedDateFrom=2023-06-01&publicListedDateTo=2023-06-30&isListed=true 

**Registered Developers this month**
- **Fields**: Name, Company Name, Email Address 
- **Endpoint**: developers?pageNumber?registeredFrom=2023-06-01&registeredTo=2023-06-30

**Subscriptions this month** 
- **Fields**: Subscription Type, Company Name, User Email, Start Date, Frequency, Cost 
- **Endpoint**: /subscriptions
- **Dependent on**: https://github.com/reapit/foundations/issues/9656 

**Installations this month** 
- **Fields**: Customer Name, App Name, Customer Code, Date Installed, Installed By, Date Uninstalled, Uninstalled By
- **Endpoint**: installations?installedDateTo=2023-07-31T00:00:00&installedDateFrom=2023-06-01T00:00:00&includeOfficeGroups=true
 
**App Usage this month**
- **Fields**: App Name, Total Cost, Number of requests
- **Endpoint**: /trafficStatistics/2023-07
- **Note**: CSV to JSON conversion 
- Top 20 ordered by cost descending to limit the scope of this

**Automation** 1st and 15th monthly

**Comment by plittlewood-rpt** [comment]
@HollyJoyPhillips I'm not sure we're going down the right track with this. It feels like it should be done in the backend then there's no need for an app which feels overkill to be generating this thing

**Comment by HollyJoyPhillips** [comment]
Hello @plittlewood-rpt, as agreed this is now a backend request :)
