### ISSUE TITLE
AgencyCloud Developer Edition - no Apps menu within the property context

### ISSUE THREAD

**Issue by MarcinuB** [reapit/foundations#9667]
**Describe the bug**
I'm using Agency Cloud Developer Edition. It has updated this morning to the version 12.168.2. 
For some reason the Apps menu within the property three dot menu is gone. 
**To Reproduce**
Steps to reproduce the behaviour eg:
1. Go to Property details
2. Click on the three dot menu
3. Apps menu is missing

**Expected behaviour**
Apps menu should be there 

![image](https://github.com/reapit/foundations/assets/8589350/5663486c-fa48-4e01-ae3b-52518ed8137c)

**Comment by plittlewood-rpt** [comment]
Hi @MarcinuB - the Apps menu has been moved to be more prominent. You'll find it on the right hand side of that ribbon menu :)

**Comment by MarcinuB** [comment]
Thanks @plittlewood-rpt for info. Looks good. 

When this will be rolled out to the customers? We need to update our manuals.

**Comment by plittlewood-rpt** [comment]
Hi @MarcinuB most customers will already have this update now :)
