### ISSUE TITLE
Open the external browser from the webapp

### ISSUE THREAD

**Issue by andortamas** [reapit/foundations#9668]
Good morning,

We run a webapp which is integrated into your Reapit desktop app. We'd like to provide a link in our app to open a help page (hosting in our website) in the user's default browser. Is there a way to do this? The target="_blank" and window.open doesn't work.

Hope you make sense.

Kind regards,
Andor

**Comment by AshDeeming** [comment]
Hi @andortamas 
Please see the below link which should be of us:
https://foundations-documentation.reapit.cloud/whats-new#desktop-api-support-for-emails-and-websites

**Comment by andortamas** [comment]
Many thanks for it. I'll have a try.
