### ISSUE TITLE
Setting up the connection between Reapit and Property Hive Import Plug in 

### ISSUE THREAD

**Issue by FaridIvory** [reapit/foundations#9670]
Hi I am currently setting up the connection between Reapit and our website using Property Hive Import Plug in and while running the plug in i keep getting this error 

13:14:26 18th August 2023 - Executed manually by wpadminuser 13:14:26 18th August 2023 - Obtaining token 13:14:26 18th August 2023 - Parsing properties 13:14:26 18th August 2023 - Request failed. Response: Array ( [headers] => WpOrg\Requests\Utility\CaseInsensitiveDictionary Object ( [data:protected] => Array ( [date] => Fri, 18 Aug 2023 13:14:26 GMT [c

Any help would be greatly appreciated

Regards Farid Boulahri

**Specification**

**Comment by AshDeeming** [comment]
Hi @FaridIvory 

As the error provided relates to a 3rd party app, please could you flag this with them - Property Hive.
