### ISSUE TITLE
Fixflo adv integration / Property search timing out 

### ISSUE THREAD

**Issue by katedeedman** [reapit/foundations#9671]
**Describe the bug**
We have a mutual client (will email over the name) has added rentcollection properties to be synced from Reapit to their Fixflo account. The property search is timing out so we're unable to sync these into the system

**Expected behaviour**
Rentcollection properties should sync from RPS into Fixflo. 

**Screenshots**

Emailed over

**Comment by plittlewood-rpt** [comment]
Closing as per zendesk response
