### ISSUE TITLE
Searching for a contact results in an error response

### ISSUE THREAD

**Issue by brunosabenca** [reapit/foundations#9676]
**Describe the bug**
Searching for a contact with a specific additional tenant name (example request was made around timestamp `2023-08-21T16:23:30.5346562Z`) results in an error response.

**Screenshots**
Sent via email

**To Reproduce**
1. Call the `contacts` endpoint using parameter `name` with a certain tenant name and the client ID `LOC`
2. Response: _"An unexpected error has been encountered when fulfilling this request. This incident has been logged and will be investigated. Please try again."_

**Expected behaviour**
The API should be able to return the data.

**Device (please complete the following information for web issues):**
 - API Integration

**Additional context**
Ticket submitted by Goodlord regarding the API integration.

**Specification**
- It looks like the recent conversion was run without data integrity cleanup being done afterwards. This has resulted in a number of contacts with blank dates (instead of null) which need to be cleaned up which will resolve these errors. To be passed back to internal projects team.

**Comment by plittlewood-rpt** [comment]
Hi @brunosabenca this should now be resolved and was caused by some bad data that crept in as part of an internal project, which has now been cleaned. If you can confirm all OK your end I'd be grateful. Thanks
