### ISSUE TITLE
Error response with the details when user haven't install the app from marketplace via Browser 

### ISSUE THREAD

**Issue by ss-dimasm** [reapit/foundations#9679]
**Summary**
Hi, 
We want to get a proper error with the details (like screenshot cURL below) when the app haven't installed by user. The response is correct and we could see it via cURL, but when we try to replicate it via browser (client side) then no response body is returned (Failed to load response data: No data found for resource with given identifier). Is there way to get the returned body response with the error details via browser? or I have miss something? let me know if you need more specific data

**Steps to reproduce**
1. Create a client private app (react)
2. Access it with the credential that not included in the white list

**cURL code**
```bash
curl --location 'https://platform.reapit.cloud/appointments/' \
--header 'Authorization: <TOKEN>' \
--header 'API-Version: latest'
```

**cURL response**
![image](https://github.com/reapit/foundations/assets/96416644/4aa512c2-c964-4765-bd7a-3ad5f7aa994e)

**client side code**
```js
  const test = async () => {
    axios
      .request({
        method: 'get',
        url: 'https://platform.reapit.cloud/appointments/',
        headers: {
          Authorization: '<TOKEN>',
          'API-Version': 'latest',
        },
      })
      .catch((error) => {
        console.log(error.response) // <-- undefined
      })
  }
```
**registered browser request headers**
![image](https://github.com/reapit/foundations/assets/96416644/47d894f3-21ac-42e7-93c2-7ee29bd31716)
![image](https://github.com/reapit/foundations/assets/96416644/e78bf426-0ff6-469d-acb8-a1d9420a35d6)

**browser response headers**
![image](https://github.com/reapit/foundations/assets/96416644/05216122-51cd-48db-a04e-cd2b4446ef1a)

**browser response body**
![image](https://github.com/reapit/foundations/assets/96416644/dff9a43b-619b-49ae-8a0b-79f8db61eaf8)

**Comment by plittlewood-rpt** [comment]
Hi @ss-dimasm - this should already be possible and I'd recommend having a look at the axios documentation to understand why you're not getting the response you're expecting. Please come back if you get stuck

**Comment by plittlewood-rpt** [comment]
Hi @ss-dimasm can this be closed? Thanks

**Comment by ss-dimasm** [comment]
Hi @plittlewood-rpt  thanks for remind me. I would close this and raise a new one with more clearer explanation about the issue.
