### ISSUE TITLE
Extra Descriptions missing from API data

### ISSUE THREAD

**Issue by reech-dev** [reapit/foundations#9686]
I have been doing some API integration on behalf of Balfours and have ran into an issue where the following data fields are not available over the API.

Marketing Information -> Extra Descriptions -> Situation
Marketing Information -> Extra Descriptions -> Directions
Marketing Information -> Extra Descriptions -> Location
Marketing Information -> Extra Descriptions -> Advert

![reapit_screenshot](https://github.com/reapit/foundations/assets/119589001/df4df630-f9a4-480d-a0ee-49a7b7fcbab7)

Can these be made available for access via the API?

**Comment by AshDeeming** [comment]
Hi @reech-dev 

Please could you confirm the client name or ID & we'll convert this into a semi structured data request

**Comment by reech-dev** [comment]
Hi,
The client name is Balfours Estate Agents. Their customer ID is BLF

**Comment by plittlewood-rpt** [comment]
Hi @reech-dev these fields have now been enabled and can be accessed using the `extrasField` query string parameter.

The fields you need to request are pSituation, pDirections, pLocation and pAdvert for Situation, Direction, Location and Advert descrptions respectively. This query string parameter can be used on both the GET / and GET /{id} endpoints on the properties API eg

`GET https://platform.reapit.cloud/properties?extrasField=pSituation&extrasField=pDirectionsextrasField=pLocation&extrasField=pAdvert`

`GET https://platform.reapit.cloud/properties/ABC123456?extrasField=pSituation&extrasField=pDirectionsextrasField=pLocation&extrasField=pAdvert`

Please allow 15 minutes for this change to synchronise across all our services. If you have any issues please come back to us.

Thanks
Pete
