### ISSUE TITLE
ID checks list not appearing to the left of submission form in `Identity checks` dialog box

### ISSUE THREAD

**Issue by will92-tf** [reapit/foundations#9688]
**Describe the bug**
ID checks list not appearing to the left of submission form in `Identity checks` dialog box. Although AgencyCloud shows that an ID check has been performed on a Contact, the ID check is not visible in the list.

**To Reproduce**
This is being submitted by an integrator on behalf of an existing Reapit client. We don't know how to reproduce and we do not have access to the client's AC setup. 

**Expected behaviour**
Historic ID checks performed on a Contact should appear in a list box to the left of the check submission dialog when the `Identity checks` UI is opened. 

**Screenshots**
Will send a screenshot to sinfo@reapitfoundations.zendesk.com 

**Device (please complete the following information for web issues):**
Information not available

**Comment by AshDeeming** [comment]
Hi @will92-tf 
Please note this appears to be a system config setting for this cleint. 

I believe this is being dealt with by our Partner Success Manager - Michael
