### ISSUE TITLE
Contact API - Internal Server Error

### ISSUE THREAD

**Issue by rajeshwl** [reapit/foundations#9689]
**Describe the bug**
We are trying to import contact records for one of our mutual client and we are receiving Internal Server Error for contacts API requests. Few of the requested API URLs are given below.

https://platform.reapit.cloud/contacts/?id=JWT20002067
https://platform.reapit.cloud/contacts/?id=JWT20002426
https://platform.reapit.cloud/contacts/?pageSize=100&modifiedFrom=2022-05-01T01:00:00.031Z&modifiedTo=2022-06-01T01:00:00.031Z
https://platform.reapit.cloud/contacts/?PageNumber=46&PageSize=100&modifiedFrom=2023-07-01T01:00:00.031Z&modifiedTo=2023-08-21T01:00:00.031Z

**Customer Code: LOC-GJUW**

**Response from reapit.**
` data: {
 statusCode: 500,
dateTime: '2023-08-23T08:01:02.5777274Z',
description: 'An unexpected error has been encountered when fulfilling this request. This incident has been logged and will be investigated. Please try again.'
}`

**Expected behaviour**
- Contact data to be return for the requested URL

**Comment by rajeshwl** [comment]
@AshDeeming ,
App Name: Starberry DataXchange AWS
App ID: 36ffc6bf-8384-4f7d-a025-b1e75d0c273b

Regards,
Rajesh

**Comment by plittlewood-rpt** [comment]
Same issue as #9676 which will be picked up shortly

**Comment by plittlewood-rpt** [comment]
Hi @rajeshwl this should now be resolved and was caused by some bad data that crept in as part of an internal project, which has now been cleaned. If you can confirm all OK your end I'd be grateful. Thanks
