### ISSUE TITLE
Multiple Email Filter On Contacts Endpoint?

### ISSUE THREAD

**Issue by jaetoole** [reapit/foundations#9692]
Eyup!
/contacts on the swagger docs seems to accept an array for email (which is really useful).

In practise, when entering emails as comma separated values, I just get an invalid email address error. Didn't want to raise this as a bug if the docs are wrong.
<img width="899" alt="image" src="https://github.com/reapit/foundations/assets/61322528/fccd02c1-7a4d-4f5d-957d-7d8ad2b1c4f9">

**Comment by HollyJoyPhillips** [comment]
Hi @jaetoole can you provide an example request where it's returning the error please?

**Comment by jaetoole** [comment]
`curl "https://platform.reapit.cloud/contacts?PageSize=100&PageNumber=1&marketingConsent=grant&marketingConsentFilterType=assumedOrExplicit&email=jae%40jaetoole.me,jae.toole%40northernestateagencies.co.uk" \
     -H 'reapit-customer: SBOX' \
     -H 'api-version: 2020-01-31'
`

**Comment by HollyJoyPhillips** [comment]
Thanks @jaetoole, so the way that it will work to use multiple filters is something like this: 

https://platform.reapit.cloud/contacts/?email=hollyjoyphillips%40gmail.com&email=hollyjoyphillipsemail%40gmail.com

Comma separated values will not work with our Platform APIs, we can look at updating the documentation to reflect this.
