### ISSUE TITLE
Landlords not returning from API

### ISSUE THREAD

**Issue by j-darcy-ff** [reapit/foundations#9693]
Several instances of landlords that are linked to properties in the UI but are not returned when called through API

Steps to reproduce the behaviour eg:
1. Add landlord to property
2. Get property Id
3. Call get property by id endpoint and add ?embed=landlord to call to include landlord data
4. Landlord returned as null

You would expect that if landlord is linked to a property when viewing the UI they should be returned through the API

**Comment by AshDeeming** [comment]
Hi @j-darcy-ff 
Could you provide an example or two for further review please?

**Comment by j-darcy-ff** [comment]
- Landlord - HIC150010 - who should be linked to property - MAI170165
- Landlord - LHO150004 - who should be linked to property - GRA150128
Both of these landlords are linked to these properties in the UI but not returned through the API

**Comment by hlarkin4** [comment]
@AshDeeming Morning Ash, 

Have you managed to take a look at the examples above? Due to this bug, some of our mutual clients jobs are being instructed without landlord approval, as they are absent from the system. Would be great if this can be looked into ASAP. 

Many thanks

**Comment by plittlewood-rpt** [comment]
This is likely due to landlord ownership and the user of office groups, however we'd need to know which customer this relates to. Please can you supply the id or name of our mutual customer so this can be looked into properly? Thanks

**Comment by hlarkin4** [comment]
@plittlewood-rpt  Thanks. The customer is LSL. After an investigation with them,  we have identified it was due to landlord relationships/ office groups with some LSL franchises being set incorrectly.

**Comment by plittlewood-rpt** [comment]
Thanks @hlarkin4 do you still need any assistance with this or can it be closed?
