### ISSUE TITLE
How do we connect in a relationship the landlords to the properties?

### ISSUE THREAD

**Issue by sanjayisg** [reapit/foundations#9695]
Hi there,

We can upload the landlords as contacts and we can upload the properties but how do we connect in a relationship the landlords to the properties?

Thanks,

Sanjay Gupta

**Comment by AshDeeming** [comment]
Hi @sanjayisg 

Records can be associated - in the case of a Landlord to a property, please see the letting section of properties payload 

![image](https://github.com/reapit/foundations/assets/61687775/64e21568-4782-4acf-9f5d-ebd6d287f3fa)

**Comment by sanjayisg** [comment]
Dear Ash,

To simplify my query, we're looking to add thousands of properties, and for each property, we also need to add vendors. Currently, it appears that the only available method is manual entry in RPS since the vendor API lacks a POST option for adding vendors; it only supports GET and PATCH operations.

Could you please advise if there's an API or any alternative method that would allow us to upload these properties and vendors in bulk?

Thank you for your assistance.

Best regards,
Sanjay Gupta

**Comment by sanjayisg** [comment]
HI Ash,

Can you please respond on my last comment.

Thanks,

Sanjay Gupta

**Comment by sanjayisg** [comment]
seems like this ticket is closed?

**Comment by plittlewood-rpt** [comment]
@sanjayisg there is no option for bulk uploading properties as it's likely this would be abused. I would challenge why you are wanting to add thousands of properties all in one go, this doesn't feel like the correct use of the system. Please can you provide more detail about your use case? The advice given above is correct, and you associate a lettings property back to it's landlord using the landlordId property when calling PATCH /properties/{id}. For the sales side, the vendor shares it's id with the property, so when you create a sales property the vendor record is automatically created, from which you can then link the contacts using the POST /vendors/{id}/relationships endpoint. Please let me know if this doesn't answer your query.

**Comment by sanjayisg** [comment]
Hi Ash,

Sorry for misunderstanding we will not upload that all in one go, we will setup some crone which will execute after ever 1 min or 5 min and on each call we will add only one property not all, like for 1000 property will make 1000 call in 5 min time of interval but want to make it automatic not manual, there any issue in this approach?

**Comment by plittlewood-rpt** [comment]
Hi @sanjayisg please can you provide some clarity why you want to add this many properties? The volume is quite concerning and we need to ensure our customer's systems are protected.

**Comment by sanjayisg** [comment]
Hi @plittlewood-rpt actually we currently have properties stored in another CRM, and our goal is to transfer them to Reapit. In pursuit of this, we are exploring efficient methods to accomplish the migration. If you have any superior suggestions, we welcome your input. Otherwise, we may resort to manual migration as a fallback option.

**Comment by sanjayisg** [comment]
Hi @plittlewood-rpt I am waiting for your response on above.

**Comment by plittlewood-rpt** [comment]
@sanjayisg  please can you let me know which customer you are working on behalf of?

**Comment by plittlewood-rpt** [comment]
HI @sanjayisg - the customer has reached out to us to advise what they're trying to achieve here so hopefully I can provide enough support on this.

My understanding is that you'll be creating contact, landlord, and property records for both sales and lettings. 

In the case of both sales and lettings, you will want to create the contact first, as you need the contact id to be able to associate a vendor or landlord to the correct contacts.

Then in the case of a sales property:
- Create the property. The property id ALWAYS matches the vendor id (they are the same entity in AgencyCloud, just presented as two different resources in the APIs). When you create a property the vendor is automatically created, and will be available at the relevant endpoint (vendors/{id} where {id} is the property id, or you can use the relevant link in the _links collection of `PropertyModel`. Next attached the vendor to the contact using `POST https://platform.reapit.cloud/vendors/{id}/relationships`

In the case of a lettings property:
- Create the landlord (watch out as you should reuse an existing landlord entity if the same landlord owns multiple properties, so you should build this logic in to prevent duplicate landlord records). You can create the link back to the contact(s) as required in the POST request to platform.reapit.cloud/landlords
- Create the lettings property, specifying the landlord id in `PropertyModel.letting.landlordId`

This should be all you need based on my current understanding, but please let me know if you need any further assistance. Please let me know if the item can be closed once you've reviewed the above. Thanks

**Comment by plittlewood-rpt** [comment]
I should have added above, there is no scope for us adding bulk capabilities to these endpoints, so you will need to use the existing endpoints and make multiple calls.
