### ISSUE TITLE
Date Instructed field missing in Data Warehouse

### ISSUE THREAD

**Issue by ktanalyst** [reapit/foundations#9698]
**Describe the bug**
In the financials tab on a property card is the 'Date Instructed' field. When I run a query on the data warehouse, this field appears to be missing. I have searched through all relevant views and cannot find it. We need this field because the instruction data in PROPERTY_SALES_WON_INSTRUCTIONS is only based on a status change from Valuation to For Sale - Unavailable. It could then be a number of days until the property actually reaches market, and therefore we use the 'Date Instructed' field as a point of reference for this instead.

**Expected behaviour**
In the PROPERTIES view, there should be a field called Date Instructed.

**Screenshots**

![Screenshot 2023-08-24 095139](https://github.com/reapit/foundations/assets/143076147/bda04b65-431d-410c-89da-ff182a5b5df6)

**Device (please complete the following information for web issues):**
 - Device: PC
 - OS: Windows 11
 - Browser N/A

**Additional context**
If this field is available in another view, please let me know as it would solve the issue.

**Comment by ktanalyst** [comment]
@plittlewood-rpt I'm responding to a message pass over to us by our account manager regarding this ticket. 

I appreciate you haven't got to this ticket yet, but could you share some information about how data in the PROPERTY_SALES_WON_INSTRUCTIONS view is generated? Is it just a single status change from Market Appraisal to For Sale - Unavailable that triggers this, or would Withdrawn to For Sale - Unavailable also work? 

The point being is that withdrawn properties that re-list would need to count as an instruction too, but if that change won't generate the record then we need to make sure the status is changed back to Market Appraisal before instruction.

As I mentioned within the ticket, it doesn't make sense that a record is created when the status changes to 'For Sale - Unavailable', given the property is not on the market at this point. Hopefully that can be reflected in the data when you sort this one. Thanks

**Comment by plittlewood-rpt** [comment]
Hi @ktanalyst - we'll need to check the logic in place that generates this view and come back to you, however it's worth you having a look at the new PROPERTY_STATUS_CHANGES view which details all property status changes taken from the journal data in AgencyCloud - if you log into the data warehouse app and hit the Refresh Share button, you'll see this new view. This gives you control over how you want to present this information in your reports. One of the issues we have is that agents use the system in different ways. Some agents duplicate properties for subsequent instructions, some use the same ones. As a result it makes it difficult to build a schema that fits every different way of working.

**Comment by ktanalyst** [comment]
> Hi @ktanalyst - we'll need to check the logic in place that generates this view and come back to you, however it's worth you having a look at the new PROPERTY_STATUS_CHANGES view which details all property status changes taken from the journal data in AgencyCloud - if you log into the data warehouse app and hit the Refresh Share button, you'll see this new view. This gives you control over how you want to present this information in your reports. One of the issues we have is that agents use the system in different ways. Some agents duplicate properties for subsequent instructions, some use the same ones. As a result it makes it difficult to build a schema that fits every different way of working.

Hi @plittlewood-rpt , thank you for the info on that. Having access to all property status changes will certainly help us with most of our basic activity reporting.

Is this table still a work in progress? The reason I ask is I've just ran a query on that view to see what is available and there hasn't been a status change involving 'Under Offer - Available' or 'Under Offer - Unavailable' since 2020, and even then there are only 7 records in the entire table. Could this be because those status's don't exist on our platform?

![image](https://github.com/reapit/foundations/assets/143076147/5a40afb5-30fb-4a89-9b31-b57ab8d40819)

**Comment by plittlewood-rpt** [comment]
I will have a look at this tomorrow. There is some configurable terminology that can be turned on in AgencyCloud (eg Sale Agreed instead of Under Offer). It's likely this view just isn't taking into account this setting.

**Comment by ktanalyst** [comment]
Thanks Pete, let me know what you find

**Comment by ktanalyst** [comment]
Hi @plittlewood-rpt, did you get a chance to look at this issue?

**Comment by plittlewood-rpt** [comment]
Not as yet I'm afraid - will do my best to get to it today

**Comment by plittlewood-rpt** [comment]
The fix for the sale agreed status is just in PR so should get merged in shortly. I'll let you know once it's gone out and the schema data has refreshed.

**Comment by plittlewood-rpt** [comment]
@ktanalyst you should be able to see those rows in the PROPERTY_STATUS_CHANGES view now.

**Comment by plittlewood-rpt** [comment]
Hi @ktanalyst to answer the original point, the instructed date information comes from the journal status change entries. The reason for this is that a property might be instructed multiple times and the date on the financial screen doesn't update automatically so using journal data feels like a more foolproof solution. It also allows us to ensure we're only looking at true instructions (ie when a property goes from valuation/MA to For Sale), further protecting against errors that could be created by users accidentally updating fields etc. Given we also now have the dedicated view for status changes, I'm going to close this issue but please reach out if you wish to discuss further. Thanks

**Comment by ktanalyst** [comment]
Hi Pete, yes that makes sense now we have access to the status change table. This was originally a request for a workaround as the PROPERTY_SALES_WON_INSTRUCTIONS table provided inaccurate data. Thanks
