### ISSUE TITLE
Key Contact/Property Manager - update to property

### ISSUE THREAD

**Issue by katedeedman** [reapit/foundations#9699]
Hey Reapit team,

We have a mutual client (can share name privately) who has requested that a change in the key contact/ property manger field is picked up in an update to the property. Currently, every time one of our clients updates the field, we have to do a full data sync to pull those into Fixflo.

Is this a change that you'd consider implementing?

Let me know if you require any further information or have any questions.

Best,

Kate

(Product Manager at Fixflo)

**Comment by katedeedman** [comment]
Thanks, Pete!

**Comment by plittlewood-rpt** [comment]
Internal ref PBI-5040

**Comment by katedeedman** [comment]
Hey Reapit team,

Wondering if there was an update on this? Appreciate you said there was no commitment but please do let me know if a decision has been made. 

Our mutual client is finding it very problematic when PMs are changed in Reapit and it's not reflected in the sync into Fixflo. Issues are being assigned to ex-employees and therefore getting missed by the maintenance team.

I have also asked the client to raise the request themselves too.

Thank you!

-Kate

**Comment by plittlewood-rpt** [comment]
Hi @katedeedman I've just checked and there's no update as yet but I've chased the team responsible to see if we can get an answer. For what it's worth, it's highly likely that this will get done. There've been a few instances where we've need to handle this kind of situation which have been done reasonably quickly, so I'd be surprised if this one is any different.

**Comment by katedeedman** [comment]
Fabulous!

Thanks very much.

-Kate

**Comment by katedeedman** [comment]
Hi team,

Wondered if there was an update on timeline for this one? 

-Kate

**Comment by plittlewood-rpt** [comment]
Hi @katedeedman it's actually on my to do list for today to get back to you as I got an update from our developers just yesterday. This work is going into AgencyCloud 12.173 which is due to start beta on 6th November and start rolling out en masse to all customers from 20th November.

**Comment by katedeedman** [comment]
Ahh that's some lovely Friday news.

Thank you, Pete!

**Comment by HollyJoyPhillips** [comment]
Hi @katedeedman I can confirm the work has been completed y the Agencycloud team and the roles are getting updated and the amend date is getting updated for all the roles. Please let us know if you have any further issues. Thanks.
