### ISSUE TITLE
Invalid Marketing mode (Not set)

### ISSUE THREAD

**Issue by thashendran-perinparasa-property-logic** [reapit/foundations#9700]
Hi Team, 

We have found an odd value in the marketingMode attribute in the get properties and property endpoint. As per your documentation marketingMode should only  have these value selling, letting and sellingAndLetting but the api returned "Not set"
Customer id: PRK
office id: PEA
Property: PEA220247
Endpoint: https://platform.reapit.cloud/properties/PEA220247
![image](https://github.com/reapit/foundations/assets/53749234/851602c5-6407-4dcc-b852-08d821e8a201)
![image](https://github.com/reapit/foundations/assets/53749234/fad5ddb5-1a02-439a-abbf-eebd15aef286)

Thanks

**Comment by plittlewood-rpt** [comment]
Hi @thashendran-perinparasa-property-logic this has now been corrected and was due to an issue with the original data conversion for this customer. It was the only property affected. Many thanks

**Comment by richclicksmith** [comment]
Hi. 

I have the same issue on property REN230078 (Reapit client SWF):
![Screenshot 2023-09-14 at 11 10 13](https://github.com/reapit/foundations/assets/94179432/86b170c4-0ea3-4f9d-814e-96f390a565f6)

I can see the same on a number of other properties for this Reapit client.
