### ISSUE TITLE
Permissions error

### ISSUE THREAD

**Issue by Jhudell** [reapit/foundations#9704]
When we try and access the public key for our new web hook, we are now receiving this error message: 

The identity attached to this request does not have the required permission to access the requested data. If you think you should be able to access this data, please use the Reapit Foundations Developer Portal to contact us to discuss the problem.

**Comment by AshDeeming** [comment]
Hi @Jhudell 
Please could you confirm the app name - The above error relates to the users access rights. Admin users can amend/update these via https://developers.reapit.cloud/settings/members

**Comment by Jhudell** [comment]
Hello.

The app is Prospect Marketing API Integration. We are set up as admin users so I believe we should have the required access.

Thanks,

Jack Hudell

Digital Marketing Developer

DDI:

01344 207 427

ADDRESS:

Head Office: 24 King Street, Reading RG1 2HE

<https://www.prospect.co.uk/property-valuation?utm_campaign=staffemail&utm_medium=email&utm_source=emailfooter>

[cid:87b7fcdb-d474-4e20-972e-358c9e77b6f4]<https://www.prospect.co.uk/property-valuation?utm_campaign=Signature&utm_source=signature&utm_medium=supportstaff>

All views expressed in this message are those of the individual sender, except where the sender specifically states them to be the views of Prospect Holdings (Reading) Limited. This email may be confidential and privileged. If you are not the intended recipient please delete and notify us at ***@***.******@***.***>. Do not copy this email or use for any other purposes, nor disclose its contents to any other person. Although this email and attachments are believed to be virus free and of any defects that might affect any other computer, it is the recipient's responsibility to ensure that they are virus free. To unsubscribe from marketing emails from Prospect Estate Agency, then please click here<https://www.prospect.co.uk/marketing-preference>. Calls are recorded for training and monitoring purposes. If you would like to view our full Privacy Policy, click here<https://www.prospect.co.uk/privacy-policy>. No responsibility is accepted by Prospect Holdings (Reading) Limited for any loss or damage arising in any way from receipt or use thereof. Registered in England as Prospect Holdings (Reading) Ltd, Company No.07005392. Registered Address: 24 King Street, Reading, Berkshire RG1 2HE.

________________________________

**Comment by AshDeeming** [comment]
Thanks @Jhudell 
I can see 3 users with @prospect email addresses, all of whom are admin users

there is one user @thepmp - who is a user only, is this the user experiencing the above issue?

**Comment by Jhudell** [comment]
No, it's one of the Prospect ones.

**Comment by AshDeeming** [comment]
Thanks @Jhudell 
Please could we ask the user to log out & back in to try again please

**Comment by Jhudell** [comment]
Great thank you - that seems to have worked.
