### ISSUE TITLE
Ability to set Correspondence Address via Property API

### ISSUE THREAD

**Issue by danielalmeidaconnellsgroup** [reapit/foundations#9708]
My team and I are looking to leverage using your Property API 

**Describe the solution you'd like**
Right now, we can only set the property address, not the correspondence address 

**Describe alternatives you've considered**
No alternatives available

**Additional context**
Discussed already with Platform Team

**Specification**
- Project: Reapit.Services.Vendors
- Add new string property correspondenceAddressType to VendorModel (and also UpdateVendorModel)
- New property can have a value of property or contact right now.
- When set to contact - the box on the vendor screen is ticked and that tells you to use the contact's address.
- When set to property, the box is unticked.

**Behaviour**
- When prp.extra.vDiffAddr is true, `correspondenceAddressType` should be set to `contact`
- When prp.extra.vDiffAddr is false or not set, `correspondenceAddressType` should be set to `property`

**Comment by plittlewood-rpt** [comment]
Moved to not ready in lieu of ongoing conversations with the customer.

**Comment by danielalmeidaconnellsgroup** [comment]
Hi Pete- You've confirmed if we set the contact, then the data is there (which we have validated). The request we need therefore is simply: The ability to allow us to switch between correspondence address and property address like we can do on the UI.
