### ISSUE TITLE
Property Style, Type etc...

### ISSUE THREAD

**Issue by danielalmeidaconnellsgroup** [reapit/foundations#9709]
Hi Team

We have custom property types and styles across our estate. Looking at the API, it details set values only 

![image](https://github.com/reapit/foundations/assets/126185395/136784d6-8128-4e9f-b0bd-214333e648b7)

Some of these don't exist in our databases  and we have custom ones.

How do we determine what these values are to send on the API?

Need to know for Property Style, Property Type, Garden, Parking and Property Age

Please use CWC database as an example

**Comment by AshDeeming** [comment]
Hi @danielalmeidaconnellsgroup 
Please see the below section of our documentation which should assist;
https://foundations-documentation.reapit.cloud/platform-glossary#interpreting-department-data

**Comment by plittlewood-rpt** [comment]
HI @danielalmeidaconnellsgroup 

Anything that doesn't fall into the mapped attributes will be exposed (read-only) in the `PropertyModel.unmappedAttributes` collection.

**Comment by plittlewood-rpt** [comment]
Hi @danielalmeidaconnellsgroup can this now be closed following our email thread this week?

**Comment by danielalmeidaconnellsgroup** [comment]
Yes. , thanks for your help.
