### ISSUE TITLE
LICENSING - Updating License details requires all three dates (created, approved, expiry). Should not have this validation.

### ISSUE THREAD

**Issue by Speedway1** [reapit/foundations#9713]
In the AC licensing screen, you can input a license with only the application date. However on the API call to create/update the license information, it gives an error if you don't supply all 3. See attached screenshots. The API additional validations should match those of the licensing screen and should not have these additional restrictions. 

![36383c30d0f61cb2cbc34348c1f523d15466bb3bb36a373463b4ce91fb039272](https://github.com/reapit/foundations/assets/100301611/bdf330e7-78fc-4fb9-bf69-62c52f019020)

![2bac3a3c1d887e3ef87d7fb5bdc2d78a0e726d1e0d0d9d126005169634f721f3](https://github.com/reapit/foundations/assets/100301611/1711c4da-5f80-4885-aad4-67e3b44f175e)
![d50133aa10292084c2b57684283163e03241d52ed8fc6fe1ceb44ad1ee28e78f](https://github.com/reapit/foundations/assets/100301611/249ee158-ede5-46d8-bf19-b061ca169c65)

**Specification**
- Project: Reapit.Services.Properties
- For POST/PATCH, when the selling.licensing.application model is provided, it should be possible to pass any combination of the three date fields.

**Comment by plittlewood-rpt** [comment]
An update to resolve this is just going out to production and should be live in the next 5 minutes or so. Thanks
