### ISSUE TITLE
Bulk Property and Vendor Upload

### ISSUE THREAD

**Issue by sanjayisg** [reapit/foundations#9714]
Dear Ash,

We're looking to add thousands of properties, and for each property, we also need to add vendors. Currently, it appears that the only available method is manual entry in RPS since the vendor API lacks a POST option for adding vendors; it only supports GET and PATCH operations.

Could you please advise if there's an API or any alternative method that would allow us to upload these properties and vendors in bulk?

Thank you for your assistance.

Best regards,
Sanjay Gupta

**Comment by AshDeeming** [comment]
Hi @sanjayisg 
As per 9695 there is currently no option for bulk uploading properties
