### ISSUE TITLE
MMA Access to pSituation and pDirections

### ISSUE THREAD

**Issue by thashendran-perinparasa-property-logic** [reapit/foundations#9717]
Hi, 

Reapit customer: MMP

The client above would like to show the pSituation and pDirections data on their website please could you grant access so we can access it on the API. 

Thanks
Thashe

**Comment by plittlewood-rpt** [comment]
Hi @thashendran-perinparasa-property-logic we don't have a customer with the id MMP. Please can you confirm the agent's company name?

**Comment by thashendran-perinparasa-property-logic** [comment]
Hi @plittlewood-rpt  sorry the customer is MMA
