### ISSUE TITLE
Issues accessing Diary App following update to Production build

### ISSUE THREAD

**Issue by craigforrest** [reapit/foundations#9721]
**Describe the bug**

We recently updated the Diary app on Production to include new features which should use permissions that have already been granted.

Upon logging into the app I am presented with a custom error message that was implemented to make users aware of when the app has not yet been enabled in the AppMarket:
![image](https://github.com/reapit/foundations/assets/26924168/9689d4dc-4bb0-4aa6-b442-bec0de19ef34)

I did not receive an email advising of an update, and the AppMarket does not have an 'enable integration' option, suggesting the app is still considered installed.

Is there anything that needs to be done by Foundations/Platform to push the updated app, has something gone awry with the update or is this potentially an app specific issue?

**Comment by craigforrest** [comment]
Just to note this may be affecting our early adopter clients and is delaying our marketing email until we're confident it's not a wide spread issue/ resolved

**Comment by craigforrest** [comment]
https://diary.prod.paas.reapit.cloud/

Log into an account linked to Reapit Online Demo (ROD). I can provide details over teams

alternatively, these are the console errors that occur on login:
![image](https://github.com/reapit/foundations/assets/26924168/709f3adc-04ac-476d-b424-b3588d575a39)

**Comment by plittlewood-rpt** [comment]
Test user didn't have right privileges so app couldn't be installed. Now resolved
