### ISSUE TITLE
Add mechanism to read and write available services installed at a property

### ISSUE THREAD

**Issue by selvakumar143** [reapit/foundations#9722]
**Background Context**
The property marketing screen in AgencyCloud has an "Available Services" section that can be enabled in system configuration. When enabled, users are presented with a configurable list of options to describe services installed at a property (electricity, oil, gas, broadband etc). Third parties have requested access to this information, and have the ability to update it

![image](https://github.com/reapit/foundations/assets/31120935/b41ac186-e5fd-4220-b9a5-a276063247d3)

**Specification**
- Project: Reapit.Services.Configuration
  - Add new endpoints GET /propertyServiceTypes and GET /propertyServiceTypes/{id} that expose the uPrpServices configurable lookup list in a collection and singular format respectively
  - Ensure uPrpServices can be returned from the hidden settings endpoint as we will need to be able to access this information from the property service to validate incoming write events

- Project: Reapit.Services.Properties
  - Add new `string[]` property `availableServices` to `PropertyModel` and associated Create/Update models that expose the items selected and stored in `prp.extra.pAvServices` (convert to array)
 - Add new link to `_links` that provides respective link to `GET /configuration/propertyServiceTypes?id=ABC&id=DEF`

**Validations**
 - In Create/Update handlers, lookup customer configuration for the setting to turn this functionality on (`uShowPrpServices`) and the configurable list and validate that:
   - The functionality is enabled (if it is not, and values a provided, throw a BadRequest error)
   - Any supplied values exist in the build data is being committed to (if any values do not appear in the configured list, throw a ValidationFailedException)
 - When updating, the entire collection should be supplied. To clear select options, pass empty array. Null will be ignored as per other patch behaviour.

**Comment by AshDeeming** [comment]
Hi @selvakumar143 

Please could you confirm the app name? 
Could you also confirm the client name as unable to match MMP to a current database.

**Comment by selvakumar143** [comment]
Sorry , here is the right informations. 
Reapit customer : MMA
App name is : Property Feeder
App id :  3507d0eb-6b8f-4530-a544-1de6fcd409be

Thanks

**Comment by selvakumar143** [comment]
@AshDeeming  Could you please provide any updates regarding this matter?

**Comment by selvakumar143** [comment]
We are running out of time can you please provide an update

**Comment by AshDeeming** [comment]
Thanks @selvakumar143 
I just wanted to check how this data was stored - this would currently be a feature request. 

I'll update the ticket to go through our refinement process for further review.

**Comment by AshDeeming** [comment]
@selvakumar143 
Please note that the EPC document may be found via the documents endpoint

N.B. The configuration endpoint will be useful to help differentiae the document types - 
![image](https://github.com/reapit/foundations/assets/61687775/c8ef59ca-04c5-44ae-8908-623f29a086f5)

**Comment by plittlewood-rpt** [comment]
Ticket needs to be split into separate feature requests.

**Comment by plittlewood-rpt** [comment]
Hi @selvakumar143 I have split this ticket in two. Please see linked ticket above for updated on the request for EPC data. Thanks

**Comment by plittlewood-rpt** [comment]
Minor bug logged for AC team (ACT-536) concerning where the configurable lookup list is stored in the database.

**Comment by thashendran-perinparasa-property-logic** [comment]
Hi @plittlewood-rpt 

Do do you know if the availableServices have now been exposed in the api? 

Thanks 
Thashendran

**Comment by plittlewood-rpt** [comment]
@thashendran-perinparasa-property-logic not yet - this ticket is in our near term and will be picked up in line with our development processes. Thanks

**Comment by plittlewood-rpt** [comment]
This feature is just in the queue to go to Production (within the next 15 minutes). Please refer to the updated swagger documentation and the specification at the top of this issue for implementation details
