### ISSUE TITLE
Duplicate Apps Giving Different Permissions Responses

### ISSUE THREAD

**Issue by colearymyhome** [reapit/foundations#9725]
Hi,

We have two identical apps, we use one for testing (App ID e1a117c1-0d87-4097-acff-ac89edff0e3e), and one for production (App ID 5178f1a0-21e5-4371-a3f5-6316d788c327).

We have the same listed permissions for both apps:

Read Documents
Read Negotiators
Read offices
Read properties

![image](https://github.com/reapit/foundations/assets/68847301/117d5588-1433-41d2-8288-65b5716d8568)
![image](https://github.com/reapit/foundations/assets/68847301/d3d19de6-8764-4cdc-b688-9040ec2942c3)

After receiving a webhook, we make a get Request to get additional data to the following endpoint:

https://platform.reapit.cloud/properties/{PropertyID}?extrasField=pBERRating&extrasField=pBERNumber&extrasField=pBERExempt&extrasField=pEPI&embed=negotiator

For the production app, this works fine.

For the testing app, it doesn't. We are currently testing with Savills Cork New Homes in the testing app, they are not on the production app. This is the only difference.

The response we get is a status 400:
"Access to one or more of the specified fields is not permitted. You must be granted access to this data beforehand"

The fields in question are:
pEPI
pBERExempt
pBERNumber

If I use this endpoint, we get the expected correct response:

https://platform.reapit.cloud/properties/CKK230026?extrasField=pBERRating&embed=negotiator

![image](https://github.com/reapit/foundations/assets/68847301/7277ad21-5a5b-4fc5-bd27-3402988b4f7d)

Given that both apps have the same permissions, and it works for one and not the other - is there a configuration that we're missing, or something that is needed on the company side?

Thanks for your assistance

**Comment by AshDeeming** [comment]
Hi @colearymyhome 
The above referenced request relates to a specific cleints extrasField - this would need to be requested (via [Semi-structured 'extras' field request](https://github.com/reapit/foundations/issues/new?assignees=&labels=back-end%2C+needs-triage&projects=&template=extras_field.md&title=))for the additional client (s) as these can be custom

**Comment by colearymyhome** [comment]
Hi Ash,

Will this need to be requested for every agent moving forward? Is there a way to include that in the app permissions on install?

**Comment by AshDeeming** [comment]
Hi @colearymyhome 
This is required for each database that has custom extras fields

**Comment by colearymyhome** [comment]
Ok, we will do this for all agents moving forward
