### ISSUE TITLE
It's been several weeks since I submitted my app for review

### ISSUE THREAD

**Issue by chriscarlisle** [reapit/foundations#9727]
Please take a look at our FAQ's before submitting an issue, as your question may already be covered in the documentation https://foundations-documentation.reapit.cloud/faqs

**Summary**

It's been several weeks since I submitted my app for review and I've had no email contact whatsoever. It says it takes 1-2 days and this  is the only route I seem to be able to enquire about it.
 

**Detail and or supporting links and screenshots**

App name is jr-hopper-development, email used is chriscarlisle@jrhopper.com

**Comment by AshDeeming** [comment]
Hi @chriscarlisle 

Please note that your Developer account is currently showing as pending & therefore app is unable to be submitted for review. Once this is updated to confirmed, with our accounts and partnerships teams, you will be able to submit the app for review.

**Comment by chriscarlisle** [comment]
Thanks Ash.

Is there something I need to do, or someone else to follow up with, to to
get my developer account confirmed?
