### ISSUE TITLE
504 Gateway Timeout

### ISSUE THREAD

**Issue by rajeshwl** [reapit/foundations#9735]
**Describe the bug**
We are trying to import the transactions for past 6 months, but we are getting 504 Gateway Timeout for the requests. We tried to limit the range for one month as well. But this does not helped.

Endpoint URL: `/transactions/?pageSize=100&modifiedFrom=2023-06-01T01:00:00.031Z&modifiedTo=2023-07-01T01:00:00.031Z`
Customer Code: LOC-GTHG

Can you please check and give a solution.

**Specification**
- Project: Reapit.Services.Transactions
- ~~Review whether or not the existing COALESCE is needed to accurately filter by modified date. The new versions of AgencyCloud always set the amend date and it's likely that all historic transactions have a date set, so we may be able to query the indexed field explicitly (ignore - no modified parameter in this service)~~
- Based on the above, refactor the repository methods to improve performance

**Comment by rajeshwl** [comment]
@AshDeeming ,
Is this been fixed? Can you please prioritize this.

**Comment by plittlewood-rpt** [comment]
HI @rajeshwl we will get to this as soon as we can. Can I just enquire why you are pulling a months worth of transactions at a time, rather than coming in for smaller resultsets

**Comment by rajeshwl** [comment]
@plittlewood-rpt ,
We are storing the history of transactions and showing to the landlords in our portal. So we do this before launching a site. So we don't request on demand while a landlord log's in.

**Comment by rajeshwl** [comment]
@HollyJoyPhillips ,
Similarly we are getting timeout issues in the transactions API for other brands as well. Can you please check and resolve for all the tenants under Lomond Group(LOC).

Other Customer Code : LOC-GBRV

For this customer we tried to import only the past 3 hours data, but also we are getting timeout issues.

**Comment by plittlewood-rpt** [comment]
HI @rajeshwl I'm just looking at this - can you just confirm the query you are issuing as this API doesn't have modifiedFrom/modifiedTo query string parameters.

**Comment by plittlewood-rpt** [comment]
Ok thanks - understood.

**Comment by plittlewood-rpt** [comment]
@rajeshwl I have made some adjustments to the resources available to this API. Can you let me know if it's made any improvement? Issuing the same request at our end is working without any issues so would be useful if you could test it from your end. Thanks

**Comment by rajeshwl** [comment]
@plittlewood-rpt ,
We tried the below endpoint, but getting gateway timeout only.

`/transactions/?pageSize=100&modifiedFrom=2023-06-01T01:00:00.031Z&modifiedTo=2023-07-01T01:00:00.031Z`

Thanks

**Comment by plittlewood-rpt** [comment]
HI @rajeshwl does this happen with every request or is it intermittent? Also, please refer to my earlier note that there isn't a modifiedFrom/modifiedTo parameter pair on this endpoint, so you can omit those.

**Comment by rajeshwl** [comment]
@plittlewood-rpt ,
Do modifiedFrom / modifiedTo parameters can be used separately? Or completely unavailable?

**Comment by plittlewood-rpt** [comment]
Hi @rajeshwl please refer to the swagger documentation. You may be wanting to utilise the createdFrom/createdTo parameters in this case perhaps?

**Comment by rajeshwl** [comment]
@plittlewood-rpt ,
This will be useful only doing a full import. But for daily import of modified transactions we would need modifiedFrom filter, As the createdFrom will not help in case of any changes made to the records. If we don't have modifiedFrom then the API calls will be increased as we are don't know which records has been imported. It would be great if you can amend the modifiedFrom parameter to the API. That's a must have field for any endpoints.

**Comment by plittlewood-rpt** [comment]
@rajeshwl I have logged a new feature request for your last comment. This ticket will remain focused on the timeout problems.

**Comment by plittlewood-rpt** [comment]
Hi @rajeshwl the modified parameters have now been added which may give you a slight improvement. We've found the underlying cause of the problem and are reviewing the best approach to resolving it

**Comment by rajeshwl** [comment]
@plittlewood-rpt ,
Thanks for adding the parameters.

**Comment by plittlewood-rpt** [comment]
Hi @rajeshwl do you still experience timeouts when using the new parameters? Thanks

**Comment by rajeshwl** [comment]
Hi @plittlewood-rpt ,
Tried in the same brand and receiving timeouts. 

URL: /transactions/?pageSize=100&modifiedFrom=2023-06-01T01:00:00.031Z&modifiedTo=2023-10-01T01:00:00.031Z

**Comment by plittlewood-rpt** [comment]
Hi @rajeshwl I've been having a look further at this and whilst there's no immediate solution, you should find you see better performance, though it may still be slow. For example, I'd suggest fetching data a month at a time (or even a week at a time for even better performance)

Eg:
/transactions/?pageSize=100&modifiedFrom=2023-06-01T01:00:00.031Z&modifiedTo=2023-07-01T01:00:00.031Z
/transactions/?pageSize=100&modifiedFrom=2023-07-01T01:00:00.031Z&modifiedTo=2023-08-01T01:00:00.031Z
/transactions/?pageSize=100&modifiedFrom=2023-08-01T01:00:00.031Z&modifiedTo=2023-09-01T01:00:00.031Z
/transactions/?pageSize=100&modifiedFrom=2023-09-01T01:00:00.031Z&modifiedTo=2023-10-01T01:00:00.031Z
/transactions/?pageSize=100&modifiedFrom=2023-10-01T01:00:00.031Z

Can you give this a try and let me know how you go? Once you've done the initial import you'll be requesting much less data with each poll, so shouldn't run into the same issues.

**Comment by plittlewood-rpt** [comment]
Hi @rajeshwl have you been able to review the above?

**Comment by rajeshwl** [comment]
HI @plittlewood-rpt ,
We tried to import for one month period range, As of now, there is no timeout for these ranges. Nearly 300 to 400 pagination requests has been sent and no timeout for those requests. 

/transactions/?pageSize=100&modifiedFrom=2023-06-01T01:00:00.031Z&modifiedTo=2023-07-01T01:00:00.031Z
/transactions/?pageSize=100&modifiedFrom=2023-07-01T01:00:00.031Z&modifiedTo=2023-08-01T01:00:00.031Z

Hope, we don't get timeout issues, if the range are greater than one month also. 


Regards,
Rajesh

**Comment by plittlewood-rpt** [comment]
HI @rajeshwl you will start running into issues if you try to paginate the entire dataset. There are millions of rows to get through. Limiting your calls by date is the recommended way to proceed with this (as above). Hope this helps.

**Comment by rajeshwl** [comment]
Thanks @plittlewood-rpt. Yes, We will use the date range to limit the records.

**Comment by plittlewood-rpt** [comment]
Thanks for confirming @rajeshwl I'll close this down as the underlying issue with performance in this area is being research as part of #8339
