### ISSUE TITLE
Yomdel lead integration

### ISSUE THREAD

**Issue by LucyRead** [reapit/foundations#9740]
There is a limit on the number of characters in the name which is set to 12. When a Yomdel lead is fed into RPS, it fails if the characters in the name exceeds this limit.

1 Send lead from Yomdel system
2. Input a name that exceeds 12 characters
3. 3. Send.
4. We then receive a failed message on name

A lead should feed in, regardless of number of characters in the name

![image](https://github.com/reapit/foundations/assets/144110033/a58857cf-1c43-49e2-af85-232143f2981d)

**Comment by AshDeeming** [comment]
Hi @LucyRead 
Please see existing related ticket : #7598

**Comment by HollyJoyPhillips** [comment]
Closing as duplicate ticket.
