### ISSUE TITLE
Platform Tooling Updates

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#9741]
**Task**: 
- Rename ‘Re Enable’ check box to ‘Ignore Bulk Indexing’ 
- If no process has been ran, the status should be ‘Disabled – Never Enabled’ and button status is ‘Enable’
- Hide ‘Ignore Bulk Indexing’ checkbox on modal 
- Once enabled button status should be ‘Disable’ (as it is currently)

- If status is ‘Disabled’ button should be ‘Re Enable’
- Modal should show option to ‘Ignore Bulk Indexing’ and be deflated to true (checked). 

**Note**: Discuss with @plittlewood-rpt regarding updating previous processes

**Comment by bashleigh** [comment]
To achieve this, make a GET API call to the bulk indexing service to determine if this organisationId has had webhooks enabled previously. That way in the frontend we can specifiy if the webhooks need to have bulk indexing ran which we can do by passing the result back to the frontend on the initial call to fetch the replication task info for this organisation
