### ISSUE TITLE
MFA Device Tracking

### ISSUE THREAD

**Issue by plittlewood-rpt** [reapit/foundations#9746]
**Background context**
We should look at MFA device tracking so that users don't have to enter a second factor on trusted devices at every login. There is an option natively in Cognito for this however there are some caveats:
 - AC uses a fresh browser session every time it launches, so any cookies dropped by Cognito will get lost
 - Logins from v1.5 onwards use the SDK, so the native Cognito options won't work on their own

**Comment by plittlewood-rpt** [comment]
@HollyJoyPhillips  we need to discuss where this sits in the roadmap. There's a general agreement that not doing this will annoy a lot of users. @PaulHaynes we'll also need to discuss this from your perspective

**Comment by HollyJoyPhillips** [comment]
Duplicate of #8642
