### ISSUE TITLE
Got a internal server error response on Prod Config Service

### ISSUE THREAD

**Issue by ss-dimasm** [reapit/foundations#9747]
**Describe the bug**
Got a "Interval server error" when try to hit the production config service `/settings` endpoint with "GET" method, suddenly it's return the error message.

See the cURL request [prod-config-service.txt](https://github.com/reapit/foundations/files/12535609/prod-config-service.txt)

**To Reproduce**
Steps to reproduce the behaviour eg:
1. Go to 'https://tooling-application-config-service.prod.paas.reapit.cloud/api-docs'
2. Authorize with SBOX account access token that I got from dev portal (https://developers.reapit.cloud/apps)

**Expected behaviour**
It should return at least a proper response instead any exception.

**Additional context**
- The `access_token` that I used it's related with a SBOX account (I copy the value from prod dev portal)
- Able to access on Dev Config Service (ofc, with SBOX dev access token), but not for Prod Config Service (with same steps)

**Comment by bashleigh** [comment]
Looks like this was caused by an expired certificate. We've redistributed the certificate so if you could try again and let us know if you can use this service now and we can mark this issue as resolved.

**Comment by ss-dimasm** [comment]
hi @bashleigh , it's works for now thanks 👍

![image](https://github.com/reapit/foundations/assets/96416644/2d88dc9f-91c0-4459-b71c-0f0f457ae530)

**Comment by bashleigh** [comment]
@ss-dimasm looks like it will be broken again as that fixed broke other certs. Looking into an alternative

**Comment by bashleigh** [comment]
Ok I've made a release to the prod instance with an update to change the url for fetching the userInfo on authentication which is where the SSL issue happened. Have tested it on prod and all works now

**Comment by ss-dimasm** [comment]
Hi @bashleigh , I found another issues for today seems it's related with this changes

- **Forbidden Access - Prod Config Service**
got a new exception 'Forbidden access' when I am trying to create a new setting record on prod version, but I could create it on dev version. I am using SBOX account to do this, is there any specific role before we could create a setting on Config Service?
[forbidden-access-prod-config-service.txt](https://github.com/reapit/foundations/files/12555555/forbidden-access-prod-config-service.txt)

- **Couldn't retrieve the session, Dev Connect Session**
not able to get a session from dev.paas connect service it keeps redirecting to that page after signing in (see screenshot below)  
![image](https://github.com/reapit/foundations/assets/96416644/6c059896-687f-40cd-8a99-39dd487df5d6)
Steps to reproduce:
1. clear the stored session of that relates with `dev.paas` on the browser
2. go to the dev AppMarket (redirect to dev connect session)
3. it will redirecting to dev connect session and fill with the valid credentials, hit the sign in button
4. it's redirecting again to `connect.dev.paas.reapit.cloud/oauth2/idpresponse`, but it has 403 error and no session is stored on the browser

**Comment by bashleigh** [comment]
You're in the incorrect environment. For prod you will need to use a prod application in order to obtain a prod access_token to be authenticated with the prod app config service. 

What you should do is:
- navigate to a prod service such as https://developers.reapit.cloud 
- log in using the reapit connect flow
- once back on dev-portal, use the network tab to find the token request
- go to the preview tab and copy the access_token

> This exception is expected on dev as there's been some changes to reapit connect and we've all been encountering these on dev recently.

**Comment by ss-dimasm** [comment]
Hi @bashleigh, those are the steps that I did to reproduce the Forbidden Access Exception on Prod Config service. The additional step is to create a new `setting` on  `/settings` endpoint with POST method.

![image](https://github.com/reapit/foundations/assets/96416644/fcc49643-792c-4c64-816d-b03b66c74858)

**Comment by bashleigh** [comment]
Did this work previously on prod? If not then I would suggest you don't have the correct user group to make that request?

**Comment by ss-dimasm** [comment]
Yep, more likely I don't have the permission on prod env. But is that possible to make the 'SBOX' account create/update a records on prod Config service? because we would have a Config Service integration with ARW app in the future, or do you have a suggestions to have a better developer experience to do so?

**Comment by bashleigh** [comment]
I'm not entirely sure what you're trying to achieve here? I've messaged Nick for some clarity however, I can describe the service as far as I'm aware of it's features as of now. 

The app config service is to be used to replace an existing app config like service, reapit admins are only permitted to edit reapit settings configs for global settings or specific products. Reapit users are then permitted to override these settings with their customised configs. Users cannot make up their own config keys.

If you're trying to make product/app based configs on prod then I would suggest reaching out to someone that is able to add those for you (someone with `ReapitFoundationsAdmin`). For now there's no method for apps to manage their own configs as this would require specific methods of authentication. We could potentially use CDK to satisfy this requirement however the requirement has not been scoped yet and I don't think I'd have authority in making that decision unfortunately. 

Hopefully this info has helped in some way? Likely not unfortunately but I have message Nick so I'll do my best to ascertain the best method to resolve this.

**Comment by ss-dimasm** [comment]
Thanks for the details @bashleigh, it's more clearer now and got the point about what we have to do for next

**Comment by ss-dimasm** [comment]
I'll close this issue since it's not relevant and already fixed. Thanks once again
