### ISSUE TITLE
Remove 'Launch URI' requirement for AgencyCloud Apps

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#9766]
**Task:** 
- Remove the requirement (validation) for a launch URI on **unlisted** 'AgencyCloud' apps (client side authenticated integrations)

**To replicate:** 
- On prod, edit the app name for a client side authenticated unlisted app and 'Save Changes' can use '1cec4ab0-f7e1-41a7-bbdd-a63ce6a64d89'
![image](https://github.com/reapit/foundations/assets/52408607/b54fb9d6-c7de-4fad-ac63-4709e4be1eb0)

**Comment by plittlewood-rpt** [comment]
@HollyJoyPhillips this is just building for dev. Can you test and make sure you're happy with the new behaviour at some point please?
