### ISSUE TITLE
Referrals API return 404 when using app token

### ISSUE THREAD

**Issue by Tj3n** [reapit/foundations#9770]
Hi, I'm using [Referrals API](https://developers.reapit.cloud/swagger) for a company app project, we noticed that after deployed, we tried to create a referral in CRM, then launch the app from that referral, it results in 404 not found when trying to fetch the referral details, but its working in swagger, so we have no idea how, we already have the `agencyCloud/referrals.write` & `agencyCloud/referrals.read` permission on the app. I'll send the sample details to [sinfo@reapitfoundations.zendesk.com](mailto:sinfo@reapitfoundations.zendesk.com). Any help would be appreciated, many thanks!

**Specification**
- Project: Reapit.Services.Referrals
- Try to recreate problem locally. This could be something to do with cached customer configuration (take this with a pinch salt). Depending on outcome, fix as appropriate

**Comment by AshDeeming** [comment]
Zendesk ticket; 865

**Comment by HollyJoyPhillips** [comment]
Hi @Tj3n can you confirm which referral you used which resulted in the 404?

**Comment by HollyJoyPhillips** [comment]
Also, for which office group installation (customer ID) please?

**Comment by Tj3n** [comment]
Hi @HollyJoyPhillips , we are having issue with all of the newly created referrals (eg. HEO230049), the office group if I understand correctly then it's `SFG-GHEO`
![image](https://github.com/reapit/foundations/assets/13995715/75d60797-7d63-4a58-8cbf-1efb6deb96bd)

**Comment by HollyJoyPhillips** [comment]
Hi @Tj3n thank you. Which service (referral type) did you use to create the referral?

**Comment by HollyJoyPhillips** [comment]
**Internal note:** The app installed has access to referral type RPT02. The user associated to both contact (HEO21000008) and applicant (HEO210005) is part of the office group (HEO). 

GET 200 12/09 log ID: 37789095530887348977834034580519427134289722972587425792
GET 404 08/09 log ID: 37781160206769686581492555914113428016643560998786039808

**Comment by Tj3n** [comment]
Hi @HollyJoyPhillips , we seem to be able to fix the issue by adding the permission `Product App` in the list then do new revision, can you help elaborate what is the permission for?
For the other question then the referral type id is RPT6 (HEO230023).

**Comment by RWilcox-Reapit** [comment]
Hi @Tj3n ,

The reason the referral was not retrievable was due to `installation metadata` being setup meaning only certain `referralTypeId`s are available for retrieval. To begin with this was just `RPT08` and `RPT07` which eliminated the referral in question as it's type is `RPT02`. 
You were able to see the entity via the Marketplace API's as their is no installation in this flow.
It looks like this has since been changed to return any of the following`RPT08, RPT07, RPT6, RPT02`.
Any referral not belonging to one of these type's will return a 404.

Hope this makes sense.
Thanks
