### ISSUE TITLE
Contact Comms Preferences not Reflecting in Agency Cloud.

### ISSUE THREAD

**Issue by danielalmeidaconnellsgroup** [reapit/foundations#9778]
We believe we have an issue where by where we update a communication preference via the API, it's not reflecting in agency cloud but the API is returning to say this has been completed successfully

**To Reproduce**
Steps to reproduce the behaviour eg:
1. Go to a record (e.g. AIH22000001 on CWC)
2. Look at the Communication Preferences, they are all ticked.
3. Make an API call to set Post or Phone to be false, this returns success as expected
4. Make an API call to see the results of that in the Get Contact request - this appears to show everything as expected
5. Go to the record in Agency Cloud
6. Look at the Communication Preferences, 

Expected Behaviour

Post and Phone, if set to false, show as unticked.

Actual Results

Communication Preferences still look the same

URL:
api/v1/contact?Id=AIH22000001&PageSize=10&PageNumber=1&ReapitCustomer=CWC&ReapitApiVersion=2020-01-31

Returns:

     "communicationPreferenceLetter": false,
      "communicationPreferenceEmail": false,
      "communicationPreferencePhone": false,
      "communicationPreferenceSMS": false,

![image](https://github.com/reapit/foundations/assets/126185395/270826a1-af33-4b7b-8d1c-8e9b5bdd2cfb)

**Specification**
- Project: Reapit.Services.Contacts
- Issue very easy to replicate. It looks like there's a couple of things going on here:
  - The field name for the email flag isn't correct and should be fixed
  - Problem looks due to the default being true, rather than false, which doesn't seem to fit with our GetExtra/SetExtra logic on the domain entity. It looks like this behaviour could have been inverted since it was originally implement so we should dig into this before deciding on the best course of action.

**Comment by danielalmeidaconnellsgroup** [comment]
Detail also shared with @plittlewood-rpt via email.

**Comment by plittlewood-rpt** [comment]
@danielalmeidaconnellsgroup I've moved this into the current sprint so we'll hopefully get to it this week. Cheers
