### ISSUE TITLE
Extra field 'RERA Permit Number' required in foundation API

### ISSUE THREAD

**Issue by gokulngk** [reapit/foundations#9780]
Client: HAH
Field Required: id/permint number

Our client have an option to update the "RERA Permit Number" in the CRM dashborad. But we couldn't find the field value in foundation API. Can you please enable data field on foundation API on extra field /guide us to fetch that field. 

For your reference below I have attached CRM Screenshot which client updated in CRM.

![image001 (2)](https://github.com/reapit/foundations/assets/69853902/98155714-801d-43c8-8c97-fe76d87f2ce9)

**Comment by plittlewood-rpt** [comment]
Hi @gokulngk this field has now been enabled and can be accessed by passing `pRERA` as the `extrasField` query string parameter. If set on a property, it will be returned in the `extrasField` collection returned in the property model:

`GET https://platform.reapit.cloud/properties?extrasField=pRERA`

and/or

`GET https://platform.reapit.cloud/properties/ABC123456?extrasField=pRERA`

Please allow up to 15 minutes for the new configuration to take effect as it can take a short while to synchronise to all the APIs.

Thanks
