### ISSUE TITLE
Extra field request  - Ad budget

### ISSUE THREAD

**Issue by awogan06** [reapit/foundations#9787]
looking to access the following "extra" fields in the API 

UPDATE PRP SET extra = 'pNoUploadTo=''CH''

Field name is:    pAdBudget=500', synchRec = NOW(), amend = NOW()

**Comment by AshDeeming** [comment]
Hi @awogan06 
Could you confirm the customer/client name or ID, along with your app name please?

**Comment by awogan06** [comment]
Audrey Wogan - Sherry FitzGerald  - looking to access these fields in API

**Comment by plittlewood-rpt** [comment]
Hi Audrey

These fields have now been enabled and can be access using the extrasField query string parameter values pNoUploadTo and pAdBudget respectively, eg

GET https://platform.reapit.cloud/properties?extrasField=pNoUploadTo&extrasField=pAdBudget

and/or

GET https://platform.reapit.cloud/properties/ABC12345?extrasField=pNoUploadTo&extrasField=pAdBudget

Please note that the fields will only be returned in the property data if they are explicitly set against the property.

It may take up to 15 minutes for the changes to sync round to the API after which you should find you can access them.

Any issues let me know. Thanks

**Comment by awogan06** [comment]
thanks Pete will test today
