### ISSUE TITLE
Properties assigned to For Sale (Lost MA) are been returned with the ForSale status

### ISSUE THREAD

**Issue by TaylorMadeDigital** [reapit/foundations#9789]
Please take a look at our FAQ's before submitting an issue, as your question may already be covered in the documentation https://foundations-documentation.reapit.cloud/faqs

**Summary**

We have properties that we would like to list as For Sale (Lost MA) and differentiate them from properties that are For Sale. However within the api it returns the status as ForSale. Looking at the documentation for the property endpoint, there are no statuses for For Sale (Lost MA) which we would expect. Is there other data from the getProperty payload that we need to use to identify a property as For Sale (Lost MA)?

**Screenshots**

![Untitled design](https://github.com/reapit/foundations/assets/2045175/9ba395b3-f92d-4dac-8de2-3566a1642d7b)

**Comment by AshDeeming** [comment]
Hi @TaylorMadeDigital 

In AgencyCloud when a property is set as Lost MA, via the Platform API you'll see the property is marked as 'isExternal' - meaning its now marketed by another agent.

Calling GET /properties?isExternal=false should give you the result you are wanting here.

**Comment by TaylorMadeDigital** [comment]
Great thanks for the response

**Comment by HollyJoyPhillips** [comment]
Hi @TaylorMadeDigital in addition, you can look at the `lostInstructionDate` field as some properties can be `isExternal` true but not lost as they are being marketed with an external agent also. 

I would suggest to ensure you are looking at For Sale (Lost MA) look at both `lostInstructionDate` & `isExternal`.
