### ISSUE TITLE
Include business number in negotiator endpoint  

### ISSUE THREAD

**Issue by jazzlall** [reapit/foundations#9792]
It has been noticed that the business number is not presented in the GET/negotiators endpoint. A large majority of the client base will still populate business as well as mobile so could this be included with the other phone fields. 

![image](https://github.com/reapit/foundations/assets/36031810/ebba96db-6e11-4d7c-b6d2-17ddc95fcf25)

**Specification**
- Project: Reapit.Services.Negotiators
- Add `additionalContactDetails` mechanism as per contacts/companies APIs for both read/write. Do not add a new business field to the core model as that will then make the `NegotiatorModel` inconsistent with other services which is likely to raise questions and there is too much ambiguity between 'work' and 'business' number types
- We should handle both read and write requests here, as per other services

**Comment by plittlewood-rpt** [comment]
@jazzlall do you need write access to this data? I was going to do read and write here but I've spotted a horrible inconsistency with how we are handling the write side for additional communication details which I don't like so would prefer not to do write side here unless we actually need it right now

**Comment by jazzlall** [comment]
@plittlewood-rpt no requirement from my end as part of this request to have write access so that should be fine.
