### ISSUE TITLE
"marketingMode": "Not set" on Properties endpoint

### ISSUE THREAD

**Issue by richclicksmith** [reapit/foundations#9793]
Same issue as reported here:
https://github.com/reapit/foundations/issues/9700

Entity ID: REN230078
Reapit client: SWF

Example screenshot from API:
![Screenshot 2023-09-14 at 11 10 13](https://github.com/reapit/foundations/assets/94179432/432d19a7-5cc9-4952-a417-2a50855be96f)

**Comment by plittlewood-rpt** [comment]
Confirmed these properties are not being added via Foundations APIs

**Comment by plittlewood-rpt** [comment]
@richclicksmith I've logged a ticket with our internal service team (ref RSD-251415) and asked them to look into what's going on here. The customer should be able to correct these in the meantime, but if not please let me know.

**Comment by plittlewood-rpt** [comment]
@richclicksmith I've fixed the data against four properties that had invalid types set. For reference the ids were 

REN230069
REN230071
REN230078
REN230084

I'll close this down as this is now with our service team to investigate the underlying cause.

**Comment by plittlewood-rpt** [comment]
Hi @richclicksmith just to let you know, our service team have been able to reproduce the bug that's causing this data and it's not been reported to our AgencyCloud development team. Once it's patched and rolled out, this should stop occurring but please let me know if you encounter any more examples.

**Comment by richclicksmith** [comment]
Hi @plittlewood-rpt. This issue has come up again for property: REN230110

Thanks!

Screenshot:
![Screenshot 2023-12-19 at 10 21 31](https://github.com/reapit/foundations/assets/94179432/a2ce1250-ff77-4566-a525-c7caa91458fa)

**Comment by plittlewood-rpt** [comment]
Don't worry about logging a new ticket, I'm sorting this now

**Comment by plittlewood-rpt** [comment]
Should be sorted. Thanks
