### ISSUE TITLE
Post Tenancy Request receiving a 404 

### ISSUE THREAD

**Issue by raymond2323** [reapit/foundations#9794]
We run our API calls to Reapit in a scheduled Job so they are done asynchronously. 

From today it appears we are getting a lot of 404 errors when creating a Tenancy on Reapit for RER-GNHM and YOM-GNHM. 

We are making requests and getting some strange errors, however, because it is a job on our end it will retry and in some of the retries it will get a successful response with the same request, but we are not sure this happens will all of them as can see a lot of retries. 

An example request params are:

The request params are: 

`{"startDate":"2023-09-28","endDate":"2024-09-27","status":"offerPending","agentRole":"managed","rent":600,"rentFrequency":"monthly","isPeriodic":false,"typeId":"AS","propertyId":"GRI220366","applicantId":"GRI231547","negotiatorId":"KPZ","officeIds":["GRI"]}`

and the error is: 

error_message: {"statusCode":404,"dateTime":"2023-09-14T11:22:40.8167133Z","description":"Entity \"Tenancy\" (RPT231855) was not found."},

the error message doesn't make sense because we are doing a POST request and not GET request. 

Here is another one:

{"startDate":"2023-09-28","endDate":"2024-09-27","status":"offerPending","agentRole":"managed","rent":950,"rentFrequency":"monthly","isPeriodic":false,"typeId":"AS","propertyId":"SWT230332","applicantId":"SWT231553","negotiatorId":"YMJK","officeIds":["SWT"]}

error is: 404 Not Found

Also for example, if we ran it many times (5+) eventually we would get a success response. An example is this one that we tried manually a few times and then worked:

The request params are: {"startDate":"2023-09-28","endDate":"2024-09-27","status":"offerPending","agentRole":"managed","rent":750,"rentFrequency":"monthly","isPeriodic":false,"typeId":"AS","propertyId":"DUD220315","applicantId":"DUD233827","negotiatorId":"YCHB","officeIds":["DUD","DUL","DUE"]}

Can you please have a look?

**Comment by plittlewood-rpt** [comment]
Hi @raymond2323 it looks like this is related to the work done in #9726 which went out today. The reason this is happening is because the API needs to refetch the tenancy that has been committed to the database, but you are creating tenancy offers for an office that doesn't belong to the office group defined by the customer id you are using when issuing the POST. This is causing the NotFound exception becuase that customer id wouldn't have access to read that tenancy back again. I'll take a look at this in the morning. The tenancies are still being committed to the database, it's just the journal entries that aren't being created.

**Comment by plittlewood-rpt** [comment]
I have a PR ready to go in in the morning subject to approval. Will report back in the morning. Thanks

**Comment by plittlewood-rpt** [comment]
Hi @raymond2323 the fix for this is just going out to production - I'll monitor our logs to make sure the 404s cease

**Comment by raymond2323** [comment]
@plittlewood-rpt Thanks for pushing - I will also monitor and see if the 404s cease. 

I have been doing some more digging around, and I think our job has created multiple requests and it has created duplicates on Reapit. 

However, and probably what I am most concerned with is because we were getting 404s we don't have the ID of the Tenancy so our system can't send updates and the records aren't linked. 

Is there anyway you can support us in helping us match them? Maybe a list of the Tenancies (with their ID) that went through the 404 errors and their corresponding Customer ID and Property ID and we can write a script on our end to patch these?

**Comment by plittlewood-rpt** [comment]
Hi @raymond2323 having a look at this for you now.

**Comment by plittlewood-rpt** [comment]
HI @raymond2323 I've just reached out to you via Zendesk as needed to send you the data over. Lets continue the conversation on there but I'll leave this issue open until we've got the data cleaned up

**Comment by raymond2323** [comment]
@plittlewood-rpt I have responded. Have you seen my note?

**Comment by plittlewood-rpt** [comment]
Carried over to new sprint due to ongoing data cleanup

**Comment by plittlewood-rpt** [comment]
Cleanup completed - Zendesk discussion ongoing about a few observations made during this exercise
