### ISSUE TITLE
Ability to order the properties by recently sold or let

### ISSUE THREAD

**Issue by ss-dimasm** [reapit/foundations#9801]
**Is your feature request related to a problem? Please describe.**
Hi we have a requirement on Market Appraisals app to display the property records based on the passed address that would sort by recently sold or recently let. Looks like we couldn't retrieve the records in a efficient way or have a 1 get request to the service and get a proper result.

**Describe the solution you'd like**
Add a query params to be able sort by recently sold and let on the properties service

**Describe alternatives you've considered**
Seems we could go with fetch more than hundred properties first based on the passed address query param, and sort them on client side. But it's not precisely accurate with all of the available records in that service (esp. on diff customer client id) and the API call is not efficient enough

**Comment by plittlewood-rpt** [comment]
Hi @ss-dimasm - the easiest way to do this is to use the journalEntries endpoint using the typeId and propertyId  query string parameters in conjunction with the sortBy query string parameter to sort your results descending. This gives you the ability to fetch status change information for a collection of properties in a single query, ordered appropriately. Please let me know if this does not fit your use case.

**Comment by craigforrest** [comment]
@ss-dimasm Could you review Pete's suggestion above and let us know if it won't be suitable?

**Comment by ss-dimasm** [comment]
Hi @plittlewood-rpt and @craigforrest , yup the mentioned flow is suite as expected with the requirement esp. to know when the property status got changed from 'a' to 'b' via AC, thanks for the advice. 

Also we may need to aware if someone change the property status immediately via API (or another app) without notify the changes on journal entry service, the result might not precisely accurate between journal entry record and the newest property's status. We could refine the explained flow to get more expected output as per the requirement is.

But at the end, it's actually works when we're only focus about integrating the AC and MA app, once again thanks 👍

**Comment by plittlewood-rpt** [comment]
Great. Can this be closed down?

For your second point above, if you need real time status updates, you can just use the properties.modified webhook event. To keep the noise down and only receive status change events, consider using a webhook filter. Documentation can be [found here](https://foundations-documentation.reapit.cloud/api/webhooks#building-event-filters)

**Comment by ss-dimasm** [comment]
Thanks Pete, we could close this one
