### ISSUE TITLE
Update email templates with updated logo

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#9804]
**Payments**  
- Request 
- Confirmation
 
**Reapit Connect**
- Welcome to Reapit Connect
- Temporary Password

**Reapit Connect Landing Page**
 
**Header and logo changes:** 
Marketplace_AppCreation.json | https://reapit-email-media.s3.eu-west-2.amazonaws.com/marketplace-header.png
Marketplace_AppInstallation.json | https://reapit-email-media.s3.eu-west-2.amazonaws.com/marketplace-header.png
Marketplace_AppRevisionApproval.json | https://reapit-email-media.s3.eu-west-2.amazonaws.com/portal-revision-header.png
Marketplace_AppRevisionRejection.json | https://reapit-email-media.s3.eu-west-2.amazonaws.com/portal-revision-header.png
Marketplace_AppRevisionScopeChanges.json | https://reapit-email-media.s3.eu-west-2.amazonaws.com/marketplace-header.png
Marketplace_AppRevisionSubmission.json | https://reapit-email-media.s3.eu-west-2.amazonaws.com/portal-revision-header.png
Marketplace_AppUninstallation.json | https://reapit-email-media.s3.eu-west-2.amazonaws.com/marketplace-header.png
Marketplace_BatchAppInstallation.json | https://reapit-email-media.s3.eu-west-2.amazonaws.com/marketplace-header.png
Marketplace_BatchAppUninstallation.json | https://reapit-email-media.s3.eu-west-2.amazonaws.com/marketplace-header.png
Marketplace_DeveloperCreation.json | https://reapit-email-media.s3.eu-west-2.amazonaws.com/devportal-header.png
Marketplace_DeveloperEdition.json | https://reapit-email-media.s3.eu-west-2.amazonaws.com/devportal-header.png
Marketplace_DeveloperMemberInvite.json | https://reapit-email-media.s3.eu-west-2.amazonaws.com/devportal-header.png
Marketplace_DeveloperPending.json | https://reapit-email-media.s3.eu-west-2.amazonaws.com/devportal-header.png
Marketplace_SubscriptionCreation.json | https://reapit-email-media.s3.eu-west-2.amazonaws.com/devportal-header.png

**Comment by plittlewood-rpt** [comment]
@willmcvay can I just check the work you have been doing with Elements will take care of the Reapit Connect landing page? It references icon graphics that are part of the elements package, so I'm assuming so. Thanks
