### ISSUE TITLE
Tenancy Status Chages

### ISSUE THREAD

**Issue by elizabethhamlin** [reapit/foundations#9806]
As you have just created a property status change table, it would be great to have a tenancy status change table too so you can see when a tenancy has changed from, for example, arranging tenancy to cancelled.

**Specification**
- Project: Analytics Schema
- Add new TENANCY_STATUS_CHANGES view model and associated staging view (if required) which is essentially a duplicate of the [PROPERTY_STATUS_CHANGES](https://reapit-analytics-schema.prod.paas.reapit.cloud/#/doc/v3907/reapit-analytics/views/property-status-changes) view with the following changes:
  - PROPERTY_ID column becomes TENANCY_ID column (computed composite key)
  - Data targets data in the jnlmisc table with the following entryTypes:
    - TA (Tenancy Arranging), TC (Tenancy Current), TX (Tenancy Cancelled), TF (Tenancy Finished)
- Ensure documentation is updated to include new view model

**Comment by plittlewood-rpt** [comment]
Hi @elizabethhamlin - a new TENANCY_STATUS_CHANGES view is now available. Please use the Refresh Share mechanism in the Data Warehouse app to add it to your dataset. Thanks
