### ISSUE TITLE
Add a 'Total Users' count header on RC Service App 

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#9812]
**Task:** 
- Add a 'Total Users' header on RC Service App 

![image](https://github.com/reapit/foundations/assets/52408607/4e2a7ad9-02ae-4e0b-bfff-8b9269a18da9)

- **Field**: totalCount
- Same header as in Admin \Apps

**Comment by plittlewood-rpt** [comment]
@HollyJoyPhillips  is this OK? It feels a better use of space than having the header split over two lines

![image](https://github.com/reapit/foundations/assets/30798627/f509fbb2-b72e-46de-a85e-9471fe036321)

**Comment by HollyJoyPhillips** [comment]
Perfect @plittlewood-rpt :)
