### ISSUE TITLE
Ability to report on additional offices

### ISSUE THREAD

**Issue by ktanalyst** [reapit/foundations#9818]
There are some scenarios where we need to select an additional office in the property card on Reapit. An example would be when a property is passed over to the Sales Progression department; it still sits with the branch as the main office, but Sales Progression is selected additionally. Currently we cannot report on the additional office field within the Analytics Schema in Data Warehouse.

Please can the additional office field be added to the schema - it would presumably sit within the PROPERTIES view.

![image](https://github.com/reapit/foundations/assets/143076147/399e9ddb-24b1-40a4-be9e-e58eec4b1a99)

**Specification**
- Project: Analytics Schema
- Add ADDITIONAL_OFFICE_ID to PROPERTIES view which exposes the calculated foreign key for prp/prp_a.offCode2
- Add ADDITIONAL_OFFICE_2_ID to PROPERTIES view which exposes the calculated foreign key for prp/prp_a.offCode3
- Update documentation

**Comment by plittlewood-rpt** [comment]
New fields are now available in the PROPERTIES view model as outlined above. You will need to refresh your data share in the data warehouse app and potentially also update your view models in whatever external reporting tools you are using. Thanks
