### ISSUE TITLE
Reporting Sales Agreed in Data Warehouse

### ISSUE THREAD

**Issue by ktanalyst** [reapit/foundations#9819]
There is currently no method of reporting on Sales Agreed in the Data Warehouse Analytics Schema. The OFFERS view allows reporting on offers which have been accepted, but this is a different metric. Once an offer has been accepted, there is further investigation required, such as proof of mortgage and appointing solicitors, before the property status is then changed to 'Sale Agreed  - Unavailable'. This status change prompts the sale to move into the pipeline, so likely to be a critical stage for most estate agents when reporting sales activity.

We looked at using the 'include in pipeline' field within the OFFERS view to achieve this - the theory being that when an offer is ready for the pipeline, this field can be changed to 'Yes' and is then reportable as a sale agreed. However, when the offer falls through or completes, this field is automatically reset to 'No' and can't be amended. It would also mean the sale agreed date would still need to use the offer accepted date.

To accurately report on sales agreed, we need a view which creates a record when the property status is changed from 'Sale Agreed - Available' to 'Sale Agreed - Unavailable'.

**Comment by plittlewood-rpt** [comment]
Hi @ktanalyst - as per our discussion on #9698 we can close this one down. Let me know if there's anything unanswered on this specific topic. Thanks
