### ISSUE TITLE
How to switch AgencyCloud - Developer Edition to specific customer view

### ISSUE THREAD

**Issue by cristianmoisa** [reapit/foundations#9825]
**Summary**

We want to replicate our customer's setup in order to perform tests and verify the integration independently of them.
We are trying to use the default "AgencyCloud - Developer Edition" app but after comparing it with our customer's view of the app, we can notice quite a few differences. 
Can the config be changed on the developer edition so we can get the same view as them?
Or can you suggest an alternative?
Thank you

**Comment by AshDeeming** [comment]
Hi @cristianmoisa 
The Developer Edition is set to SBOX for all developers to test apps/integrations

Configuration for SBOX is set as a standard & we are unable to amend this on a per developer basis.

**Comment by cristianmoisa** [comment]
Thanks @AshDeeming, what would you recommend in this case?
Just throwing it out there as an idea: could we sign up as a regular paying customer with ReapIT and get a config similar to our customer in that case?

**Comment by AshDeeming** [comment]
Hi @cristianmoisa 
Although this could be possible, i believe it would be expensive & ineffective. 

Once your app/integration is setup to work using SBOX details, depending no what your apps purpose, the areas which could change would mainly come via the configuration endpoint. 

 It may be easier to list the app privately to a beta client; 
https://foundations-documentation.reapit.cloud/whats-new#private-apps
