### ISSUE TITLE
 TENANCIES complete details are not flowing into snowflake

### ISSUE THREAD

**Issue by SairamKDXFT** [reapit/foundations#9828]
**Background context**

**Specification**
Hi Team,

this is the first time I'm requesting for help. 

the TENANCIES View columns are not completely available in snowflake.

**Comment by AshDeeming** [comment]
Hi @SairamKDXFT 

Please could you confirm which Developer account & Client this is regarding?

**Comment by SairamKDXFT** [comment]
This is for the client Druce.

**Comment by SairamKDXFT** [comment]
Hi

This is for the client Druce.

Is there any way would like to speak to any Developer/support members from Reapit.

Regards



Kotta Sairam
Manager – Data Platforms
***@***.***_3cc922ce-3622-4346-93fb-154d3a9e829e.png]<http://www.dxfuturetech.com>       .       Mobile    +971555622854<tel:+971555622854>
Email     ***@***.******@***.***>
PO Box  338339
,Dubai

.


Disclaimer

The information contained in this communication from the sender is confidential. It is intended solely for use by the recipient and others authorized to receive it. If you are not the recipient, you are hereby notified that any disclosure, copying, distribution or taking action in relation of the contents of this information is strictly prohibited and may be unlawful.

**Comment by plittlewood-rpt** [comment]
@SairamKDXFT please can you provide more detail about what you are expecting to see, versus what you can see? Your report is a little vague so any additional information you can give us would be great. Thanks

**Comment by SairamKDXFT** [comment]
in the documentation (https://developers.reapit.cloud/analytics-schema-docs)  for Tenancies we have columns for Management_fee_percentage and other columns. but in the Snowflake we don't see the columns for this Views. 


also expecting the tenancy type New-let /Re-let info in the tables.

<img width="538" alt="image" src="https://github.com/reapit/foundations/assets/145762206/2ab22e13-3ac2-4364-8642-3d9f8348ae4e">

**Comment by plittlewood-rpt** [comment]
For resolve the issue with missing columns you need to click the Refresh Share button in the Data Warehouse app. These fields were added fairly recently so unless you've refreshed your share you won't have them in the views you can see.

Regarding the second point, re-let information isn't currently in those views so I'll amend this item to be a feature request on that basis next week and we can refine it in line with our development processes. Many thanks

**Comment by SairamKDXFT** [comment]
thanks for the prompt response. 

please confirm is the below option to refresh the Data to reflect in snowflake. 

<img width="826" alt="image" src="https://github.com/reapit/foundations/assets/145762206/0b8920b5-eb0b-4ba2-8790-e7ec3b6211f3">

**Comment by plittlewood-rpt** [comment]
Yep that's the one. That refreshes the schema in snowflake so will update your views with any new columns that become available. Note that if you are using power bi or other external tools you may need to force an update to the generated data models in that software also

**Comment by SairamKDXFT** [comment]
okay thanks for the information.

**Comment by SairamKDXFT** [comment]
Hi... the Managment Fee Details are empty for all the records.

**Comment by HollyJoyPhillips** [comment]
Hi @SairamKDXFT we've checked the data and it seems correct, is this still and issue? If it is, please can you provide some examples? 

Thanks

**Comment by SairamKDXFT** [comment]
@HollyJoyPhillips, this ticket can now be closed. I've raised separate tickets for the remaining issues. Thank you!
