### ISSUE TITLE
House Attribute not showing on Agency Cloud

### ISSUE THREAD

**Issue by danielalmeidaconnellsgroup** [reapit/foundations#9830]
A property we have set a property type to have house is not coming through into Reapit Agency Cloud.

To Reproduce, make an API call as below.

Expected Result:

House is shown as an attribute

Actual Result

It doesn't come through

Sandbox behaves correctly.

Seen on 
branch: COL
DB: CWE
Property Ref: COL230503

Request
    "MarketingMode": "selling",
    "DepartmentId": "G",
    "StrapLine": null,
    "Description": null,
    "Summary": null,
    "AlternateId": null,
    "Address": {
        "BuildingName": "",
        "BuildingNumber": "201",
        "Line1": "Whitchurch Road",
        "Line2": "ROMFORD",
        "Line3": "Essex",
        "Line4": null,
        "Postcode": "RM3 9AA",
        "CountryId": null,
        "Geolocation": {
            "Latitude": 0.0,
            "Longitude": 0.0
        }
    },
    "Bedrooms": 0,
    "Receptions": 0,
    "Bathrooms": 0,
    "CouncilTax": null,
    "InternetAdvertising": false,
    "ViewingArrangements": null,
    "VideoUrl": null,
    "VideoCaption": null,
    "Video2Url": null,
    "Video2Caption": null,
    "Notes": null,
    "LongDescription": null,
    "BoardStatus": null,
    "BoardNotes": null,
    "BoardUpdated": null,
    "BoardUpdatedDateTime": null,
    "Epc": null,
    "ExternalArea": null,
    "InternalArea": null,
    "Selling": {
        "Price": 0,
        "Instructed": null,
        "InstructedDateTime": null,
        "Qualifier": null,
        "Status": "valuation",
        "Disposal": null,
        "Completed": null,
        "CompletedDateTime": null,
        "Exchanged": null,
        "ExchangedDateTime": null,
        "Tenure": null,
        "RecommendedPrice": null,
        "Fee": null,
        "AccountPaid": null,
        "AccountPaiDateTime": null,
        "VendorId": null,
        "Agency": null,
        "ExchangedCompanyFee": null,
        "BrochureId": null,
        "ExchangedPrice": null,
        "ExchangedOfficeId": null,
        "Decoration": []
    },
    "Letting": null,
    "Type": [
        "house"
    ],
    "Style": [
        "detached"
    ],
    "Situation": [
        "garden"
    ],
    "Parking": [
        "garage"
    ],
    "Age": [],
    "Locality": [],
    "Rooms": [],
    "OfficeIds": [
        "COL"
    ],
    "NegotiatorId": "AGFK"

**Device (please complete the following information for web issues):**
 - Device: [e.g. iPhone6, PC, Mac]
 - Browser [e.g. Chrome, Safari]

**Additional context**

**Comment by HollyJoyPhillips** [comment]
Update the property attributes for type to include 'House/Villa' to map to 'House'

**Comment by plittlewood-rpt** [comment]
HI @danielalmeidaconnellsgroup I've just added this mapping to the three services that need to know about it (Departments, Applicants, Properties). It's going out to production now so give it 15 mins or so and this should be working for you
