### ISSUE TITLE
E500 on tenancy api

### ISSUE THREAD

**Issue by Speedway1** [reapit/foundations#9831]
This endpoint - "/tenancies/?PageNumber=343&PageSize=100&sortBy=created" keeps failing for a specific client with this response since last week: 

{"statusCode":500,"dateTime":"2023-09-22T11:03:33.3499389Z","description":"An unexpected error has been encountered when fulfilling this request. This incident has been logged and will be investigated. Please try again."}

Also it is worth mentioning that PageNumber 342 and 344 work alright.

We are not sharing the name of client to maintain confidentiality but we can share it through our email - support@sms-speedway.com

**Comment by plittlewood-rpt** [comment]
Hi @Speedway1 this should now be resolved and was caused by a tenancy being mapped to a renewal source that no longer exists. I've checked the database and this was the only one, dating back to 2012. The data has now been corrected. Thanks
