### ISSUE TITLE
is it possible if to store zero value to letting's or selling's fee ?

### ISSUE THREAD

**Issue by nurm717123** [reapit/foundations#9836]
Please take a look at our FAQ's before submitting an issue, as your question may already be covered in the documentation https://foundations-documentation.reapit.cloud/faqs

**Summary**
currently we have a form that has an input field and toggle field that handle selling fee which run the update whenever field changed. when user click the toggle to have percentage `type` fee, we immediately reset the `amount` and run the `PATCH` with value `{ selling: { fee: { amount: 0, type: 'percentage'}}}` but then after property refetched, `selling.fee` become `null`. that has same behaviour with `letting.lettingFee` and `letting.managementFee`. is it possible to store the `0` value to it ?
(since we have implement debounced `onChange` update most of them might have no problem with it when they used to), but for the first user the behaviour might not as expected when user click the toggle beforehand and wait for the update succeed before they updating the `amount` field.

**Detail and or supporting links and screenshots**
<img width="406" alt="image" src="https://github.com/reapit/foundations/assets/106480336/218d3732-8698-47eb-aa26-4424157a5544">

**Specification**
- Project: Reapit.Services.Properties
- Passing 0 as a fee amount should be handled correctly. It's likely this is getting cleared because 0 is used to clear an integer in the database. We should also check that switching between fee types (percentage to fixed and vice versa) clears the opposite database field. This should already be in place

**Comment by azkanurf-ss** [comment]
Hi @RWilcox-Reapit we tried to patch `selling.fee`, `letting.lettingFee`, and `letting.managementFee` again.
Here's what we've got. 
When we pass `{amount: 0, type: "fixed" }` the return for
 - `selling.fee` and  `letting.lettingFee` are  `{amount: 0, type: "percentage" }`
 - `letting.managementFee` is `null`
 
 When we pass `{amount: 0, type: "percentage" }` the return for
 - `selling.fee` and  `letting.lettingFee` are  `{amount: 0, type: "percentage" }`
 - `letting.managementFee` is `null`
 
 is it an intended behavior of the service?
