### ISSUE TITLE
ToggleRadio isChecked property won't listen state change

### ISSUE THREAD

**Issue by nurm717123** [reapit/foundations#9837]
**Describe the bug**
we are using `ToggleRadio` element, and we use the options property with conditional `isChecked` attribute, the conditional type is depend on the react-hook-form's `watch` fn (we have tried using React's `useState` too but still does'nt work), the expected behaviour is the `isChecked` attribute is listened by toggled item elements, but in my case it does not work. seems likely that isChecked only work on first render.

**To Reproduce**
Steps to reproduce the behaviour eg:
1. use `ToggleRadio` element (with react) https://elements.reapit.cloud/iframe.html?viewMode=docs&id=toggle--basic-usage#multi-toggle---toggleradio
2. use `options.isChecked` with external state (eg. react's `useState`)
3. trigger external state update (`setState`)
4. see unexpected result (toggle didn't switched)

**Expected behaviour**
in my case (like the screenshot), when `isUsingPercentageLettingFee` is `true`, then the first option should be checked.

**Screenshots**
<img width="300" alt="image" src="https://github.com/reapit/foundations/assets/106480336/c26012f5-936c-4488-a362-391664f7e7d8">
<img width="436" alt="image" src="https://github.com/reapit/foundations/assets/106480336/71d01c7e-431e-49c1-9341-972ac0c2cb44">

**Device (please complete the following information for web issues):**
 - Device: Windows
 - OS: Windows 11
 - Browser: Brave
 - Version: 1.8x

**Additional context**

**Comment by willmcvay** [comment]
@nurm717123 The isChecked prop sets the defaultChecked property on the radio, not the checked property. The component is intended to be controlled by the form state because hook-form passes the value to the input. 

Use the register function and will work correctly. See https://github.com/reapit/foundations/blob/master/packages/admin-portal/src/components/apps/toggle-consumption.tsx#L59 for an example.

**Comment by nurm717123** [comment]
Thanks @willmcvay the register fn work here, I thought it wouldn't work because I just changed it from checkbox to toggle (since with checkbox is easier without `register` because the field is not `boolean`) and I forgot to re-try it on toggle, and now it is good thank you.
