### ISSUE TITLE
Access to Offices oInetRM extras field

### ISSUE THREAD

**Issue by garrym** [reapit/foundations#9838]
**Request**

In order for us to grant access to Semi-structured 'extras' field data, please provide the following information in this request:

- The name of the customer you represent
Savills

- The name of every field you need surfaced (if known)
oInetRM for Office

- A screenshot of of the field(s) you require in the agency cloud user interface
I've not seen the field in the agency cloud user interface.

- A short use case as to why you require this data
This contains the Rightmove branch ID required to map a Reapit office code to a Rightmove branch. We need this to map some marketing data from Rightmove back to the relevant Savills office.

**Comment by plittlewood-rpt** [comment]
Hi @garrym this field has now been enabled for you. I think you're familiar with this mechanism by now, but in case you're not, please use the extrasField query string parameter to request this field, which will be returned only if it is explicitly set against the office resources:

`GET https://platform.reapit.cloud/offices?extrasField=oInetRM`

and/or

`GET https://platform.reapit.cloud/offices/ABC?extrasField=oInetRM`

**Comment by garrym** [comment]
Thanks Pete, does it take a while to propagate? I've just tried it and I'm still receiving a 400 response. This is on our `SAU` customer:

```
{
    "statusCode": 400,
    "dateTime": "2023-09-25T09:41:03.2152119Z",
    "description": "Access to one or more of the specified fields is not permitted. You must be granted access to this data beforehand"
}
```

CURL
```curl --location 'https://platform.reapit.cloud/offices/OXF?extrasField=oInetRM' \
--header 'Accept: application/json' \
--header 'reapit-customer: SAU' \
--header 'api-version: 2020-01-31' \
--header 'Authorization: Bearer [Removed]'```

**Comment by plittlewood-rpt** [comment]
Ah this is for your UAT build. Apologies - that's a different configuration I need to update. I've updated that now. Give it 5 mins and you should be good to go
