### ISSUE TITLE
Access to write enquiries endpoint 

### ISSUE THREAD

**Issue by AnthonyKyriacou** [reapit/foundations#9849]
Dear Reapit support,

Can you please advise on how we can access and be granted permissions to the write enquiries endpoint.

Thanks,

Anthony

**Comment by AshDeeming** [comment]
Hi @AnthonyKyriacou 
Any permissions for an app can be managed via the App details > Permissions 

Please note that any additional permissions requested, will need to be approved by all current installations before being approved.

**Comment by AnthonyKyriacou** [comment]
Dear Ash,

Thanks for the reply. I've provided instructions to our dev team. If we have any further questions, I'll be back in touch.
