### ISSUE TITLE
Help to integrate feed for Gascoines

### ISSUE THREAD

**Issue by supportagentmedium** [reapit/foundations#9852]
Hi Team,

We are looking to integrate feed for Gascoines as we have done for Wilkinson and Ideal Homes.

My Client(Gascoines) are saying they are stuck and not able to give us the permission(Screenshot Attached)

Please help us to to install Gascoines(GCS)

**Comment by supportagentmedium** [comment]
![Gas1](https://github.com/reapit/foundations/assets/130666121/10e9c845-10b6-4ada-b997-6da42eb30064)

**Comment by Steve-Clark-Reapit** [comment]
HI, I am the project manager for this. I just need to know how to help the client install the appat their end. It is important because it's a new client that went live with us this Monday so portals/web due to go live today.

**Comment by HollyJoyPhillips** [comment]
The integration has been enabled.
