### ISSUE TITLE
Create journal entry that relevant with a property ('Detail Change' and 'Price Change' types)

### ISSUE THREAD

**Issue by ss-dimasm** [reapit/foundations#9853]
**Summary**
Hi, we have a requirement on Market Appraisal app to create an entry that relevant with a property on journalEntry service with 'Detail Change' and 'Price Change' types. We've list the available types on configuration service esp. with `/configuration/journalEntryTypes` endpoint, the returned typeIds on our env (SBOX) for `Detail Change` type is `DC` and for `Price Change` type is `PC`.  Unfortunately, the service reject the passed payload (see detail below on swagger). Is there any chance to allow these typeIds?

**Detail and or supporting links and screenshots**

**Price Change**
![image](https://github.com/reapit/foundations/assets/96416644/cb13d53c-1591-4d3b-b600-27fc1de9f320)
**Detail Change**
![image](https://github.com/reapit/foundations/assets/96416644/16c4cf6a-e82d-48b9-b900-0389881814b0)

**Comment by craigforrest** [comment]
Hi @plittlewood-rpt , Currently we intend on adding the following unsupported journal types:

Price Change (PC)
Details Change (DC)
Telephone/ Contact (PH)
Left Message (LM)

**Comment by plittlewood-rpt** [comment]
Left Message and Telephone Contact make sense - we can add those very easily.

For Price Change and Detail Change though these are all system generated and so we won't be opening this up via the API which is what my question was really about. Detail Change is a big 'bucket' that field level changes get dumped into . What specifically is it you are wanting to create as a detail change, so we can prioritise adding handling for those fields. Thanks

**Comment by craigforrest** [comment]
Basically we want to ensure any change that we make in the apps create journal entries as if we made the same change via AgencyCloud, so aside from the manual entries for LM and PH we would want to ensure the following are correctly recorded in the journal:

Property price change
Contact marketing consent changes (missed from my previous list and uses codes CG and CC)
Contact name changes
Telephone/ email field changes

If these journalising tasks are handled without additional development then nothing needs to be actioned

**Comment by plittlewood-rpt** [comment]
Contact marketing consent and phone field changes are already supported, so we just need to do property price change and contact name change as a priority by the look of your list above?

**Comment by craigforrest** [comment]
Yes please, would you like me to split the ticket so we have one for DC/LM as a manual entry and another for price change and contact name?

**Comment by plittlewood-rpt** [comment]
@craigforrest I have split this ticket up into three separate items linked above. I'll close this one down, please track the 3 tickets above.
