### ISSUE TITLE
Provide API to present filterable listing of contact mailing/event subscription statuses

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#986]
## Overview
This endpoint will be responsible for presenting a paged list of subscriptions for mailing lists and events for a particular contact

### Location
`GET /contacts/{id}/subscriptions` (protected: **yes**)

### Parameters
`type` - string
`status` - string

### Success
**200 OK**
```
{
  "_embedded": [
    {
      "id": "ID123",
      "name": "Monthly newsletter",
      "status": "subscribed",  
      "type": "mailing",
      "subscribedOn": "2019-01-25T15:44:28.0000000Z",
      "unsubscribedOn": "2020-01-26T09:24:02.0000000Z",
      "_links": {
        "self": {
          "href": "/contacts/{id}/subscriptions/ID123"
        },
        "contact": {
          "href": "/contacts/{id}/"
        }
  ],
  "pageNumber": 1,
  "pageSize": 1,
  "pageCount": 1,
  "totalPageCount": 1,
  "totalCount": 25,
  "_links": {
    "self": {
      "href": "/contacts/{id}/subscriptions/?PageNumber=1&PageSize=1"
    },
    "first": {
      "href": "/contacts/{id}/subscriptions/?PageNumber=1&PageSize=1"
    },
    "next": {
      "href": "/contacts/{id}/subscriptions/?PageNumber=2&PageSize=1"
    },
    "last": {
      "href": "/contacts/{id}/subscriptions/?PageNumber=25&PageSize=1"
    }
  }
}
```
### Failure
**400 Bad Request
401 Authorised
403 Forbidden**

**Specification**
- Please confirm field locations/mappings before proceeding with ticket
- Repository method to optionally fetch subscriptions rather than doing this on every GET interaction

**Comment by plittlewood-rpt** [comment]
PR 3627 opened

**Comment by plittlewood-rpt** [comment]
Now deployed to production. Changelog updated and I have added some configured mailings in the Developer Edition Sandbox
