### ISSUE TITLE
Could not create installation: The specified app is not listed as available in the marketplace

### ISSUE THREAD

**Issue by chestertons** [reapit/foundations#9860]
Please take a look at our FAQ's before submitting an issue, as your question may already be covered in the documentation https://foundations-documentation.reapit.cloud/faqs

**Summary**
Clciking "Enable Integration" on  app fb299e6b-c0f0-4b6f-9f34-4cd0e86bb00b returns the above error

**Detail and or supporting links and screenshots**
This app should ONLY be available to the specified business, and not feature in the app store. Its sole purpose is to enable us to upload & download data
We will have a similar app for our business data once we go live.

**Comment by AshDeeming** [comment]
Hi @chestertons 

The app will need to be made private via the Edit App > Permissions & then submitted for approval. 

https://foundations-documentation.reapit.cloud/listing-your-app

Once this has been completed, an adminUser within the Agency will have the access to Enable the integration.
