### ISSUE TITLE
Unable to change Tenancy status to cancelled 

### ISSUE THREAD

**Issue by raymond2323** [reapit/foundations#9865]
API is not allowing us to change the tenancy status to cancel.

See request and we are using the following Tenancy `RPT230549` on sandbox 

```
curl --location --request PATCH 'https://platform.reapit.cloud/tenancies/RPT230549' \
--header 'Reapit-Customer: SBOX' \
--header 'If-Match: "EB0E579E549D10E23D8A9072749206D1"' \
--header 'Api-Version: 2020-01-31' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer eyJraWQiOiJFXC9TcnVuTzVCR0xBMk1yT3phY2RjWFkwVVdqRVB1cVB5N3hIb1FWbnJGdz0iLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiI2cWdoMGZvY21sczQ2ZmIxdWsxbGM2NzRmYyIsInRva2VuX3VzZSI6ImFjY2VzcyIsInNjb3BlIjoiYWdlbmN5Q2xvdWRcL2NvbXBhbmllcy5yZWFkIGFnZW5jeUNsb3VkXC9sYW5kbG9yZHMucmVhZCBhZ2VuY3lDbG91ZFwvY29udGFjdHMud3JpdGUgYWdlbmN5Q2xvdWRcL29mZmVycy5yZWFkIGFnZW5jeUNsb3VkXC9wcm9wZXJ0aWVzLndyaXRlIGFnZW5jeUNsb3VkXC9hcHBsaWNhbnRzLndyaXRlIGFnZW5jeUNsb3VkXC90YXNrcy5yZWFkIGFnZW5jeUNsb3VkXC9hcHBsaWNhbnRzLnJlYWQgYWdlbmN5Q2xvdWRcL25lZ290aWF0b3JzLnJlYWQgYWdlbmN5Q2xvdWRcL2RvY3VtZW50cy5yZWFkIGFnZW5jeUNsb3VkXC9vZmZlcnMud3JpdGUgYWdlbmN5Q2xvdWRcL2pvdXJuYWxlbnRyaWVzLnJlYWQgYWdlbmN5Q2xvdWRcL2pvdXJuYWxlbnRyaWVzLndyaXRlIGFnZW5jeUNsb3VkXC9jb21wYW5pZXMud3JpdGUgYWdlbmN5Q2xvdWRcL29mZmljZXMucmVhZCBhZ2VuY3lDbG91ZFwvcHJvcGVydGllcy5yZWFkIGFnZW5jeUNsb3VkXC9jb250YWN0cy5yZWFkIGFnZW5jeUNsb3VkXC9sYW5kbG9yZHMud3JpdGUgYWdlbmN5Q2xvdWRcL2RvY3VtZW50cy53cml0ZSBhZ2VuY3lDbG91ZFwvdGFza3Mud3JpdGUgYWdlbmN5Q2xvdWRcL3RlbmFuY2llcy5yZWFkIGFnZW5jeUNsb3VkXC90ZW5hbmNpZXMud3JpdGUiLCJhdXRoX3RpbWUiOjE2OTU3ODk2NDIsImlzcyI6Imh0dHBzOlwvXC9jb2duaXRvLWlkcC5ldS13ZXN0LTIuYW1hem9uYXdzLmNvbVwvZXUtd2VzdC0yX2VRN2RyZU56SiIsImV4cCI6MTY5NTc5MzI0MiwiaWF0IjoxNjk1Nzg5NjQyLCJ2ZXJzaW9uIjoyLCJqdGkiOiI5MDRkMWQ3Yi1hMGRiLTRlMDUtOWU5Zi01NTZmOGMxY2U5MzMiLCJjbGllbnRfaWQiOiI2cWdoMGZvY21sczQ2ZmIxdWsxbGM2NzRmYyJ9.b7Kcg5ASv-P2aSnuW8jLpirhUvD9CXKLy2urlpE1I52PV1kI1CfM0tfUVecFPzeiLb4Y3wzF4WllISWGHcRs_LxayyMgGaSUJlm2fdY5z2JCW9d5RKBDSASyJF5GSYsfuruAQJkWyauG3tJZ-2STVFcVZkjRr5hSQEq57QjkwQncKHQ7BS-shv7lo_H2u6BcsB7legOkNCOuBbH4oyCwX4vAVeGlMkgcOP-XqgeXSpxkHOajdiFyQpP1nFDb298G1UpOgp3faCKNCGIFcDfNmKhvYZ8xjzMyXXlcC_GDLd0MjvqQIOSsjbJjr239y_HSTDGDQkdvUsCFU8ghhbtXog' \
--data '{"status":"cancelled"}
'
```

```
The response is: 

{
    "errors": [
        {
            "field": "status",
            "message": "The enum value provided for TenancyStatus is incorrect"
        }
    ],
    "statusCode": 422,
    "dateTime": "2023-09-27T05:01:03.5221027Z",
    "description": "One or more validation failures have occurred. Please refer to Errors list for details"
}
```

Can you let us know how we can change the status to cancelled? 

**Specification**
- Project: Reapit.Services.Tenancies
- It should be possible to go from offerPending to another offer state (ie offerRejected/offerWithdrawn). 
- It should be possible to go from arranging to cancelled status (subject to approval from client accounts)
- Emit journal notifications for the status changes (there is already an existing mechanism in place to handle this - may need to update Reapit.Packages.Journalisation to add new entry types)
- Tweak swagger documentation to make the rules clearer - if this gets too verbose, link to Tenancy glossary page in Foundations documentation page

**Comment by raymond2323** [comment]
@AshDeeming is this a bug or something we are doing wrong?

**Comment by AshDeeming** [comment]
Hi @raymond2323 
This has been labelled for our back end team to review in more detail following refinement

**Comment by plittlewood-rpt** [comment]
@raymond2323 this is actually by design and it looks like the swagger documentation is incorrect. The API prohibits you from marking a tenancy as Finished or Cancelled because of the complex links the functionality has with the accounting functionality in AgencyCloud. It's unlikely that this will change, however we can look at supporting a change specifically from Arranging to Cancelled, but I'm not sure if that would fit the bill here.

**Comment by raymond2323** [comment]
@plittlewood-rpt

The only tenancy statuses we would need change to cancelled would be from `offerPending` and `arrangingTenancy`

Would you be able to make the API work for those?

**Comment by raymond2323** [comment]
@HollyJoyPhillips @plittlewood-rpt we are still getting error in the Sandbox:


`curl --location --request PATCH 'https://platform.reapit.cloud/tenancies/RPT230549' \
--header 'Reapit-Customer: SBOX' \
--header 'If-Match: "EB0E579E549D10E23D8A9072749206D1"' \
--header 'Api-Version: 2020-01-31' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer eyJraWQiOiJFXC9TcnVuTzVCR0xBMk1yT3phY2RjWFkwVVdqRVB1cVB5N3hIb1FWbnJGdz0iLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiI2cWdoMGZvY21sczQ2ZmIxdWsxbGM2NzRmYyIsInRva2VuX3VzZSI6ImFjY2VzcyIsInNjb3BlIjoiYWdlbmN5Q2xvdWRcL2NvbXBhbmllcy5yZWFkIGFnZW5jeUNsb3VkXC9sYW5kbG9yZHMucmVhZCBhZ2VuY3lDbG91ZFwvY29udGFjdHMud3JpdGUgYWdlbmN5Q2xvdWRcL29mZmVycy5yZWFkIGFnZW5jeUNsb3VkXC9wcm9wZXJ0aWVzLndyaXRlIGFnZW5jeUNsb3VkXC9hcHBsaWNhbnRzLndyaXRlIGFnZW5jeUNsb3VkXC90YXNrcy5yZWFkIGFnZW5jeUNsb3VkXC9hcHBsaWNhbnRzLnJlYWQgYWdlbmN5Q2xvdWRcL25lZ290aWF0b3JzLnJlYWQgYWdlbmN5Q2xvdWRcL2RvY3VtZW50cy5yZWFkIGFnZW5jeUNsb3VkXC9vZmZlcnMud3JpdGUgYWdlbmN5Q2xvdWRcL2pvdXJuYWxlbnRyaWVzLnJlYWQgYWdlbmN5Q2xvdWRcL2pvdXJuYWxlbnRyaWVzLndyaXRlIGFnZW5jeUNsb3VkXC9jb21wYW5pZXMud3JpdGUgYWdlbmN5Q2xvdWRcL29mZmljZXMucmVhZCBhZ2VuY3lDbG91ZFwvcHJvcGVydGllcy5yZWFkIGFnZW5jeUNsb3VkXC9jb250YWN0cy5yZWFkIGFnZW5jeUNsb3VkXC9sYW5kbG9yZHMud3JpdGUgYWdlbmN5Q2xvdWRcL2RvY3VtZW50cy53cml0ZSBhZ2VuY3lDbG91ZFwvdGFza3Mud3JpdGUgYWdlbmN5Q2xvdWRcL3RlbmFuY2llcy5yZWFkIGFnZW5jeUNsb3VkXC90ZW5hbmNpZXMud3JpdGUiLCJhdXRoX3RpbWUiOjE3MDUzOTYwMjAsImlzcyI6Imh0dHBzOlwvXC9jb2duaXRvLWlkcC5ldS13ZXN0LTIuYW1hem9uYXdzLmNvbVwvZXUtd2VzdC0yX2VRN2RyZU56SiIsImV4cCI6MTcwNTM5OTYyMCwiaWF0IjoxNzA1Mzk2MDIwLCJ2ZXJzaW9uIjoyLCJqdGkiOiJjZmQwNmIyNi1hMmZlLTQ5ZjItYjI4Yy1mZjMzOWNhZDllZTUiLCJjbGllbnRfaWQiOiI2cWdoMGZvY21sczQ2ZmIxdWsxbGM2NzRmYyJ9.eUX94nLcQ3lJk-Kw8gwBIVd0Aa9fepnIPoT9-qCMMJd68zNWDfzh7sQoirHW7JYmrequVLSx0cib1X_kB4Tvu9fxc9DIJXz44z1SXja8yHLAPmYZyNY2UknVxkH8w1GXPX6c-pPpR_QdJy1eNhBOOv44U3lzeWA0O--Z1Zr3m6sIdX2kKcY7wJ150kzMsa7hJJldcomo3_WoRsTTMMdvkKEZBFP34nexFyADQUzsZWxbvFh0Xc1_K892L1MehvJlihLqWdXPukZ3Yql3zf08L3zPOgCFITVpd2FZ0gi2TsgrzboQ6pk12KQZQ8aa0IsCZMYeqgSrVNSgjB8Rf0vYFA' \
--data '{
  "status": "cancelled"
}`




Response:

```
{
    "errors": [
        {
            "field": "status",
            "message": "The enum value provided for TenancyStatus is incorrect"
        }
    ],
    "statusCode": 422,
    "dateTime": "2024-01-16T09:08:26.3507822Z",
    "description": "One or more validation failures have occurred. Please refer to Errors list for details"
}
```

**Comment by plittlewood-rpt** [comment]
Hi @raymond2323 what is the current status of that tenancy? If it's current, you still won't be able to change it

**Comment by RWilcox-Reapit** [comment]
Hi @raymond2323 
This has just been released and should be working as you expect.
Any issues let us know.

Thanks
Ryan

**Comment by raymond2323** [comment]
@RWilcox-Reapit @plittlewood-rpt 

The tenancy is in arranging state and doesn't allow us to change to `cancelled` 

```
{"id"=>"RPT230549",
 "created"=>"2023-09-26T09:02:08Z",
 "modified"=>"2023-09-27T05:00:46Z",
 "startDate"=>"2023-10-10",
 "endDate"=>"2024-10-09",
 "status"=>"arranging",
 "agentRole"=>"managed",
 "rent"=>500.0,
 "rentFrequency"=>"monthly",
 "endDateConfirmed"=>false,
 "isPeriodic"=>false,
 "rentInstalmentsFrequency"=>nil,
 "rentInst
```

**Comment by RWilcox-Reapit** [comment]
Hi @raymond2323,

I've just successfully updated the status of that tenancy to 'cancelled'.
Could you provide me with your PATH request body and the response your seeing?

Thanks

**Comment by huzefa-p** [comment]
@RWilcox-Reapit - The PATH and request body are mentioned in the below CURL request and response. 

```ruby
curl --location --request PATCH 'https://platform.reapit.cloud/tenancies/RPT230549?=null' \
--header 'Reapit-Customer: SBOX' \
--header 'If-Match: "EB0E579E549D10E23D8A9072749206D1"' \
--header 'Api-Version: 2020-01-31' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer eyJraWQiOiJFXC9TcnVuTzVCR0xBMk1yT3phY2RjWFkwVVdqRVB1cVB5N3hIb1FWbnJGdz0iLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiI2cWdoMGZvY21sczQ2ZmIxdWsxbGM2NzRmYyIsInRva2VuX3VzZSI6ImFjY2VzcyIsInNjb3BlIjoiYWdlbmN5Q2xvdWRcL2NvbXBhbmllcy5yZWFkIGFnZW5jeUNsb3VkXC9sYW5kbG9yZHMucmVhZCBhZ2VuY3lDbG91ZFwvY29udGFjdHMud3JpdGUgYWdlbmN5Q2xvdWRcL29mZmVycy5yZWFkIGFnZW5jeUNsb3VkXC9wcm9wZXJ0aWVzLndyaXRlIGFnZW5jeUNsb3VkXC9hcHBsaWNhbnRzLndyaXRlIGFnZW5jeUNsb3VkXC90YXNrcy5yZWFkIGFnZW5jeUNsb3VkXC9hcHBsaWNhbnRzLnJlYWQgYWdlbmN5Q2xvdWRcL25lZ290aWF0b3JzLnJlYWQgYWdlbmN5Q2xvdWRcL2RvY3VtZW50cy5yZWFkIGFnZW5jeUNsb3VkXC9vZmZlcnMud3JpdGUgYWdlbmN5Q2xvdWRcL2pvdXJuYWxlbnRyaWVzLnJlYWQgYWdlbmN5Q2xvdWRcL2pvdXJuYWxlbnRyaWVzLndyaXRlIGFnZW5jeUNsb3VkXC9jb21wYW5pZXMud3JpdGUgYWdlbmN5Q2xvdWRcL29mZmljZXMucmVhZCBhZ2VuY3lDbG91ZFwvcHJvcGVydGllcy5yZWFkIGFnZW5jeUNsb3VkXC9jb250YWN0cy5yZWFkIGFnZW5jeUNsb3VkXC9sYW5kbG9yZHMud3JpdGUgYWdlbmN5Q2xvdWRcL2RvY3VtZW50cy53cml0ZSBhZ2VuY3lDbG91ZFwvdGFza3Mud3JpdGUgYWdlbmN5Q2xvdWRcL3RlbmFuY2llcy5yZWFkIGFnZW5jeUNsb3VkXC90ZW5hbmNpZXMud3JpdGUiLCJhdXRoX3RpbWUiOjE3MDUzOTYwMjAsImlzcyI6Imh0dHBzOlwvXC9jb2duaXRvLWlkcC5ldS13ZXN0LTIuYW1hem9uYXdzLmNvbVwvZXUtd2VzdC0yX2VRN2RyZU56SiIsImV4cCI6MTcwNTM5OTYyMCwiaWF0IjoxNzA1Mzk2MDIwLCJ2ZXJzaW9uIjoyLCJqdGkiOiJjZmQwNmIyNi1hMmZlLTQ5ZjItYjI4Yy1mZjMzOWNhZDllZTUiLCJjbGllbnRfaWQiOiI2cWdoMGZvY21sczQ2ZmIxdWsxbGM2NzRmYyJ9.eUX94nLcQ3lJk-Kw8gwBIVd0Aa9fepnIPoT9-qCMMJd68zNWDfzh7sQoirHW7JYmrequVLSx0cib1X_kB4Tvu9fxc9DIJXz44z1SXja8yHLAPmYZyNY2UknVxkH8w1GXPX6c-pPpR_QdJy1eNhBOOv44U3lzeWA0O--Z1Zr3m6sIdX2kKcY7wJ150kzMsa7hJJldcomo3_WoRsTTMMdvkKEZBFP34nexFyADQUzsZWxbvFh0Xc1_K892L1MehvJlihLqWdXPukZ3Yql3zf08L3zPOgCFITVpd2FZ0gi2TsgrzboQ6pk12KQZQ8aa0IsCZMYeqgSrVNSgjB8Rf0vYFA' \
--data '{
  "status": "cancelled"
}
'
```
Response:
```ruby
{
    "errors": [
        {
            "field": "status",
            "message": "The enum value provided for TenancyStatus is incorrect"
        }
    ],
    "statusCode": 422,
    "dateTime": "2024-01-16T09:16:40.4238465Z",
    "description": "One or more validation failures have occurred. Please refer to Errors list for details"
}
```

**Comment by huzefa-p** [comment]
@RWilcox-Reapit - I tested this tenancy `RPT220046` and it updated to canceled successfully. 

It's working now - thanks

**Comment by huzefa-p** [comment]
@plittlewood-rpt - We are again facing the same issue for tenancy ID - `RPT240018`

I have tried the below request today - so it's a fresh request. 

```ruby
curl --location --request PATCH 'https://platform.reapit.cloud/tenancies/RPT240018' \
--header 'Reapit-Customer: SBOX' \
--header 'If-Match: "D21EE9A94EBFC3C414A4999CC545F7C3"' \
--header 'Api-Version: 2020-01-31' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer eyJraWQiOiJFXC9TcnVuTzVCR0xBMk1yT3phY2RjWFkwVVdqRVB1cVB5N3hIb1FWbnJGdz0iLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiI2cWdoMGZvY21sczQ2ZmIxdWsxbGM2NzRmYyIsInRva2VuX3VzZSI6ImFjY2VzcyIsInNjb3BlIjoiYWdlbmN5Q2xvdWRcL2NvbXBhbmllcy5yZWFkIGFnZW5jeUNsb3VkXC9sYW5kbG9yZHMucmVhZCBhZ2VuY3lDbG91ZFwvY29udGFjdHMud3JpdGUgYWdlbmN5Q2xvdWRcL29mZmVycy5yZWFkIGFnZW5jeUNsb3VkXC9wcm9wZXJ0aWVzLndyaXRlIGFnZW5jeUNsb3VkXC9hcHBsaWNhbnRzLndyaXRlIGFnZW5jeUNsb3VkXC90YXNrcy5yZWFkIGFnZW5jeUNsb3VkXC9hcHBsaWNhbnRzLnJlYWQgYWdlbmN5Q2xvdWRcL25lZ290aWF0b3JzLnJlYWQgYWdlbmN5Q2xvdWRcL2RvY3VtZW50cy5yZWFkIGFnZW5jeUNsb3VkXC9vZmZlcnMud3JpdGUgYWdlbmN5Q2xvdWRcL2pvdXJuYWxlbnRyaWVzLnJlYWQgYWdlbmN5Q2xvdWRcL2pvdXJuYWxlbnRyaWVzLndyaXRlIGFnZW5jeUNsb3VkXC9jb21wYW5pZXMud3JpdGUgYWdlbmN5Q2xvdWRcL29mZmljZXMucmVhZCBhZ2VuY3lDbG91ZFwvcHJvcGVydGllcy5yZWFkIGFnZW5jeUNsb3VkXC9jb250YWN0cy5yZWFkIGFnZW5jeUNsb3VkXC9sYW5kbG9yZHMud3JpdGUgYWdlbmN5Q2xvdWRcL2RvY3VtZW50cy53cml0ZSBhZ2VuY3lDbG91ZFwvdGFza3Mud3JpdGUgYWdlbmN5Q2xvdWRcL3RlbmFuY2llcy5yZWFkIGFnZW5jeUNsb3VkXC90ZW5hbmNpZXMud3JpdGUiLCJhdXRoX3RpbWUiOjE3MDY2MTUxNTMsImlzcyI6Imh0dHBzOlwvXC9jb2duaXRvLWlkcC5ldS13ZXN0LTIuYW1hem9uYXdzLmNvbVwvZXUtd2VzdC0yX2VRN2RyZU56SiIsImV4cCI6MTcwNjYxODc1MywiaWF0IjoxNzA2NjE1MTUzLCJ2ZXJzaW9uIjoyLCJqdGkiOiI1YWI5MTkzNi1kYWRmLTQxZDMtODUwYy0yNTM5MjAzZWY0ZjEiLCJjbGllbnRfaWQiOiI2cWdoMGZvY21sczQ2ZmIxdWsxbGM2NzRmYyJ9.gejFcSScObHKmAtLZr_mhyaqzpsyfB218Gt16-lsEFoZlpxyYhAC7Wb1LZlKnCHcWx4k3wu9v3Mx2yJvVAajoJaYholsEH-A9BJxLJ5q5XmkgMpKhklzhIuCfgGX7QKE7mQXqDO79ZQDmzorHLNvlCF6bcnuFYlvzGMtOzKhHeHYHN1BiGZMi6hRZBOHMzg5tflbPUV7hHBzxAHUNaVPOTfwI563LGrGMaCy6waYTk4HCGndtWKE6oOn638jjW1zizRHhHG8oZhYQm0kvrhzlU_aLdjuamDHpBWdy-MPhsvMTTjKMf6w19RZkhCH3-CSZsSd3Gc8Yb7vJq6SxsitLw' \
--data '{
  "status": "cancelled"
}
'
```
Response:
```ruby
{
    "errors": [
        {
            "field": "Status",
            "message": "It is not permitted to change the status of the tenancy from `offerPending` to `cancelled` via this API"
        }
    ],
    "statusCode": 422,
    "dateTime": "2024-01-30T11:48:32.3342536Z",
    "description": "One or more validation failures have occurred. Please refer to Errors list for details"
}
```

@RWilcox-Reapit @plittlewood-rpt - Can you please help us here to identify what's going wrong here ?

**Comment by raymond2323** [comment]
@plittlewood-rpt can you have a look at this ?

**Comment by plittlewood-rpt** [comment]
Hi @raymond2323 @huzefa-p sorry for the delay on this - it should be resolved tomorrow I'm just waiting for a patch to get QA'd

**Comment by plittlewood-rpt** [comment]
HI @raymond2323 @huzefa-p this should be resolved. There was still a validation rule in place that specifically blocked status changed from offerPending -> cancelled which has now been dealt with
