### ISSUE TITLE
Invalid option for "yearly" value on letting.rentFrequency (property service) 

### ISSUE THREAD

**Issue by ss-dimasm** [reapit/foundations#9869]
**Describe the bug**
Hi, what is actually the available options to change the rent frequency for a property to "yearly"? the available options for rentFrequency that documented on swagger PATCH property model are "weekly", "monthly", "yearly", but when I try to change it to "yearly" it would throw an exception with 422 status

**To Reproduce**
Steps to reproduce the behaviour:
1. hit update property service with attached payload below
2. see error

**Expected behaviour**
The Swagger model documentation says the "yearly" option is considered as a valid value, so we could pass it and update the record.

**Documented options for letting.rentFrequency on Swagger update property model**
![image](https://github.com/reapit/foundations/assets/96416644/fcc521ba-8dea-4f22-8781-d688bf35353b)

**Passed Payload**
```json
{
  "letting": {
    "rent":3332,
    "rentFrequency": "yearly"
}
```

**Service Response**
![image](https://github.com/reapit/foundations/assets/96416644/9ef19daa-6d5d-48e5-97f8-f1343c44d456)

**Additional context**
Sandbox data

**Specification**
- Project: Reapit.Services.Properties
- Update documentation references to `yearly` to read `annually` where Rent Frequency is documented

**Comment by plittlewood-rpt** [comment]
Hi @ss-dimasm - the documentation here is incorrect. It should read annually. If you update your call to use annually instead of yearly it should be accepted. We'll get the documentation corrected in due course. Thanks

**Comment by ss-dimasm** [comment]
so that is the reason behind it, thanks for confirming @plittlewood-rpt , we could close this issue then👍

**Comment by plittlewood-rpt** [comment]
Please leave the issue open for now. We'll get the swagger docs corrected and then update it. Thanks
