### ISSUE TITLE
Provide API to present information for a specific contact mailing/event subscription status

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#987]
## Overview
This endpoint will be responsible for presentingthe details of a specific mailing list. A mailing list is concerned with managing subscriptions and responses for one or more contacts or companies. 

### Location
`GET /contacts/{id}/subscriptions/{subscriptionTypeID}` (protected: **yes**)

### Success
**200 OK**
```
    {
      "id": "ID123",
      "name": "Monthly newsletter",
      "status": "subscribed",  
      "type": "mailing",
      "subscribedOn": "2019-01-25T15:44:28.0000000Z",
      "unsubscribedOn": "2020-01-26T09:24:02.0000000Z",
      "_links": {
        "self": {
          "href": "/contacts/{id}/subscriptions/ID123"
        },
        "contact": {
          "href": "/contacts/{id}/"
        }

```
### Failure
**400 Bad Request
401 Authorised
403 Forbidden
404 Not Found**

**Comment by plittlewood-rpt** [comment]
PR 3627 opened

**Comment by plittlewood-rpt** [comment]
Now deployed to production. Changelog updated and I have added some configured mailings in the Developer Edition Sandbox
