### ISSUE TITLE
Feather Smailes and Scales Access to extras fields

### ISSUE THREAD

**Issue by thashendran-perinparasa-property-logic** [reapit/foundations#9878]
Hi team, 

Customer ID: FSS

Can you please give access to the client above so we can access the following extras fields pExtraServices, pBriefTerms and pLegalPackUrl?

Thanks
Thashendran

**Comment by AshDeeming** [comment]
Hi @thashendran-perinparasa-property-logic 

These fields have now been enabled and can be access using the extrasField query string parameter

GET https://platform.reapit.cloud/properties?extrasField=pExtraServices&extrasField=pBriefTerms&extrasField=pLegalPackUrl

Please note that the fields will only be returned in the property data if they are explicitly set against the property.

It may take up to 15 minutes for the changes to sync round to the API after which you should find you can access them.

**Comment by thashendran-perinparasa-property-logic** [comment]
Hi @plittlewood-rpt 
<img width="827" alt="image" src="https://github.com/reapit/foundations/assets/53749234/fe77301a-a9d8-4ded-8b43-aad6706e7c37">
<img width="944" alt="image" src="https://github.com/reapit/foundations/assets/53749234/22144f58-fef9-4d6c-9bfd-9f2d98622cf2">

It seems to be an issue with the pBriefTerms and pLegalPackUrl as on the property  "id": "HAR230082" those two attributes don't seem to be pulling but they are set in the CRM . 
full response below
`{
    "id": "HAR230082",
    "created": "2023-08-07",
    "modified": "2023-10-04T11:36:19Z",
    "lastCall": "2023-10-04",
    "nextCall": "2023-10-11",
    "marketingMode": "selling",
    "currency": "GBP",
    "alternateId": "13663",
    "address": {
        "buildingName": "",
        "buildingNumber": "1",
        "line1": "Belford Place",
        "line2": "Harrogate",
        "line3": "North Yorkshire",
        "line4": "",
        "postcode": "HG1 1HX",
        "countryId": "GB",
        "localTimeZone": "Europe/London",
        "geolocation": {
            "latitude": 53.989559,
            "longitude": -1.53792
        }
    },
    "areaId": "HAO",
    "strapline": null,
    "description": "FOR SALE IN OUR ONLINE AUCTION ON 24TH OCTOBER 2023 AT 3PM - LOT 7",
    "longDescription": "A most attractive stone fronted Georgian mid town house offering well proportioned accommodation arranged over three floors. The property has some delightful features including a breakfast kitchen with Aga and master bedroom with en-suite bathroom. There is ample parking to the front and an enclosed rear courtyard.",
    "localAuthorityCompanyId": "HAR18006521",
    "localAuthorityCompanyName": "North Yorkshire Council",
    "summary": "• FOR SALE IN OUR ONLINE AUCTION ON 24TH OCTOBER 2023 AT 3PM - LOT 7\r• Stone front Georgian house\r• Delightful features\r• Breakfast kitchen with Aga\r• Ample parking\r• Enclosed rear courtyard\r• Town centre",
    "departmentId": "G",
    "negotiatorId": "KDE",
    "bedrooms": 3,
    "bedroomsMax": 0,
    "receptions": 2,
    "receptionsMax": 0,
    "bathrooms": 2,
    "bathroomsMax": 0,
    "numberOfUnits": 0,
    "parkingSpaces": 0,
    "councilTax": "D",
    "disabledPortalIds": [],
    "internetAdvertising": true,
    "isExternal": false,
    "viewingArrangements": "Re Mosque the call to prayer, there will be no external speaker, and the call to prayer will be within the building. Please rest assured we will make every effort not to disturb any of our Neighbours.",
    "videoUrl": null,
    "videoCaption": null,
    "video2Url": null,
    "video2Caption": null,
    "notes": "Old System Code: PRP009808\r\nVendor Notes: Fax Number: Mr 07941606729",
    "boardStatus": "FS",
    "boardNotes": null,
    "featuredImageUrl": "https://assets.reapit.net/fss/live/pictures/HAR/23/HAR230082_01.jpg",
    "url": null,
    "urlCaption": null,
    "groundRent": 0.0,
    "groundRentComment": null,
    "groundRentReviewDate": null,
    "groundRentIncrease": null,
    "serviceCharge": 0.0,
    "serviceChargeComment": null,
    "floorLevel": null,
    "internalFloors": null,
    "totalFloors": null,
    "boardUpdated": null,
    "valuation": "2023-01-20",
    "archivedOn": null,
    "fromArchive": false,
    "rural": null,
    "externalArea": null,
    "internalArea": {
        "type": "squareFeet",
        "min": 1420.0,
        "max": 0.0
    },
    "epc": {
        "exempt": false,
        "eer": 53,
        "eerRating": "E",
        "eerPotential": 82,
        "eerPotentialRating": "B",
        "eir": 0,
        "eirRating": null,
        "eirPotential": 0,
        "eirPotentialRating": null,
        "fullDocumentUrl": "https://find-energy-certificate.service.gov.uk/energy-certificate/8441-6423-6300-0402-4996",
        "firstPageDocumentUrl": null
    },
    "selling": {
        "instructed": "2023-08-07",
        "price": 420000.0,
        "priceTo": null,
        "reservationFee": 0,
        "qualifier": "guidePrice",
        "status": "forSale",
        "disposal": "auction",
        "completed": null,
        "exchanged": null,
        "accountPaid": null,
        "tenure": {
            "type": "freehold",
            "expiry": null
        },
        "vendorId": "HAR230082",
        "agency": "soleAgent",
        "agencyId": "SA",
        "agreementExpiry": "2023-10-02",
        "fee": {
            "type": "percentage",
            "amount": 1.6
        },
        "exchangedCompanyFee": null,
        "recommendedPrice": 450000,
        "valuationPrice": 450000,
        "brochureId": "HAR23000161",
        "publicBrochureUrl": "https://assets.reapit.net/fss/live/pdf.php?p=HAR230082&t=S",
        "exchangedPrice": 0,
        "exchangedOfficeId": "",
        "decoration": [
            "good"
        ],
        "sharedOwnership": {
            "sharedPercentage": null,
            "rent": null,
            "rentFrequency": ""
        }
    },
    "letting": null,
    "commercial": null,
    "regional": null,
    "type": [
        "house"
    ],
    "style": [
        "terraced"
    ],
    "situation": [],
    "parking": [
        "offStreet"
    ],
    "age": [
        "period"
    ],
    "locality": [
        "townCity"
    ],
    "specialFeatures": [],
    "unmappedAttributes": [
        {
            "type": "OUTSIDE",
            "value": "Patio"
        }
    ],
    "rooms": [],
    "roomDetailsApproved": false,
    "officeIds": [
        "AUC"
    ],
    "lostInstructionDate": null,
    "lostInstructionNote": null,
    "keywords": [],
    "extrasField": {
        "pExtraServices": "All mains services are connected to the property."
    },
    "_eTag": "\"1621CF91FD037C48E518C957C602063F\"",
    "_links": {
        "self": {
            "href": "/properties/HAR230082"
        },
        "images": {
            "href": "/propertyImages/?propertyId=HAR230082"
        },
        "documents": {
            "href": "/documents/?associatedType=property&associatedId=HAR230082"
        },
        "offers": {
            "href": "/offers/?propertyId=HAR230082"
        },
        "appointments": {
            "href": "/appointments/?propertyId=HAR230082"
        },
        "negotiator": {
            "href": "/negotiators/KDE"
        },
        "offices": {
            "href": "/offices/?id=AUC"
        },
        "department": {
            "href": "/departments/G"
        },
        "vendor": {
            "href": "/vendors/HAR230082"
        },
        "area": {
            "href": "/areas/HAO"
        },
        "sellingBrochure": {
            "href": "/documents/HAR23000161"
        },
        "boardStatus": {
            "href": "/configuration/boardStatuses/FS"
        },
        "sellingAgency": {
            "href": "/configuration/agencyTypes/SA"
        },
        "localAuthority": {
            "href": "/companies/HAR18006521"
        }
    },
    "_embedded": null,
    "metadata": {}
}`

**Comment by plittlewood-rpt** [comment]
Hi @thashendran-perinparasa-property-logic I think I can see the problem. The second example appears to be OK here though, pBriefTerms is being exposed for property HAR190315. I'm just looking at the other property now

**Comment by plittlewood-rpt** [comment]
The issue with HAR230082 should now be resolved and I can confirm the legal pack URL is coming back. There was a misconfiguration in AgencyCloud which was causing some case sensitivity issues in the API.
