### ISSUE TITLE
licenceRequired field removing licence held fields

### ISSUE THREAD

**Issue by jamesgoyuno** [reapit/foundations#9887]
Currently the "licenceRequired" field on the Reapit properties endpoint will remove all the licence held data is set to false/null via API. This doesn't seem to happen is you untick the box on the front end .

Yuno is giving licence requirement information via our app and we would like to be able to save that within Reapit but when we try to save licenceRequired to null/false it will remove the properties licence held information

Would you be able to make it possible for us to set this field to false without it removing the licence held data?

**Specification**
- Project: Reapit.Services.Properties
- Update converter class to continue to expose additional property licensing information in the event license required is false (the data is already there in the db)
- Update any tests to suit

**Comment by RLAV1** [comment]
Hey @plittlewood-rpt @AshDeeming  did this one get reviewed in refinement this week? 
This is one of 3 that is a priority for Savills

**Comment by plittlewood-rpt** [comment]
Hi @RLAV1 I've moved this into the current sprint so it will be done before the end of the sprint next Friday. @RWilcox-Reapit  FYI

**Comment by RLAV1** [comment]
Legend - thank you so much @plittlewood-rpt
