### ISSUE TITLE
GET /properties/{id} endpoint is responding with incomplete list of types

### ISSUE THREAD

**Issue by au63** [reapit/foundations#9889]
RPS desktop has 11 property types in SBOX environment but in the api only 8 show up and the rest 3 are under 'unmappedAttributes'.

1. Check all 11 types under property attributes:
![image](https://github.com/reapit/foundations/assets/139497587/162696c7-b31d-4fc9-bcbb-4ca59e90a94c)

2. Go to https://developers.reapit.cloud/swagger and do a GET properties/{id}
![image](https://github.com/reapit/foundations/assets/139497587/b170efe9-6e48-4f07-bb7d-de64735b635a)
As visible in the above screenshot, only 8 show up in "type". The rest go under "unmappedAttributes".

**Comment by AshDeeming** [comment]
Hi @au63 
Those shown in unmapped are none standard & therefore shown within unmapped
