### ISSUE TITLE
Offer_Id details are populating as NULL in Snowflake Exchange and Completion tables

### ISSUE THREAD

**Issue by SairamKDXFT** [reapit/foundations#9893]
Hi Team, 

in the Snowflake tables 'property_sales_exchanges' and 'property_sales_completions' the Offer_Id Column data is coming as Null. 
Can you fix this 
<img width="448" alt="image" src="https://github.com/reapit/foundations/assets/145762206/f596f786-e591-4d8d-a8b4-78ad8161579a">

**Specification**
- Project: Analytics Schema
- Using examples from both views, work the problem backwards to ascertain why the offer id is not being set. The way this mapping is done uses journal entry data as there is no direct link between exchange/completion events and an offer, so we have to try and intelligently calculate it based on various bits of data.

**Comment by SairamKDXFT** [comment]
Hi @plittlewood-rpt  any update on this

**Comment by plittlewood-rpt** [comment]
Hi @SairamKDXFT this should now be resolved as far as we can. The offer id being populated relies on journal entries and offer entries being present against the property. I can see quite a lot of exchanged/completed properties that do not have a journal entry showing the status change to Under Offer so we can't obtain some of the information we need to infer the correct relationship back to the offer.
