### ISSUE TITLE
Back-end integration queries

### ISSUE THREAD

**Issue by steves99** [reapit/foundations#9894]
Please take a look at our FAQ's before submitting an issue, as your question may already be covered in the documentation https://foundations-documentation.reapit.cloud/faqs

**Summary**
Back-end integration queries

**Detail and or supporting links and screenshots**
Hello, we are partnering with estate agents using the Reapit CRM in order to provide a consolidated bills package for tenants. 
In order to do this, we need to query their letting properties and identify new tenancies that are starting soon. We also need to query for tenancies ending soon so that we can manage the void period bills. We will be using the /properties endpoint and including embedded tenancies and landlord data.
Can you please clarify the following:
* In order to get access to a mutual client's data in order to assist us in building our integration, do we contact them directly, or request you to do it?
* Can you let us have the set of domain values for a tenancy status, including a description of meanings?
* How can we filter out upcoming tenancies starting that are actually renewals?

**Comment by AshDeeming** [comment]
Hi @steves99 

Once an app is approved, it can be listed privately (up to 3 Clients) or Publicly - Clients can then install/enabled the integration/app

Please refer to the swagger documentation for a full breakdown of endpoints and their payloads (https://developers.reapit.cloud/swagger)

Renewal details can be found within the Tenancies endpoint.

**Comment by steves99** [comment]
Thanks Ash. In order for us to get the implementation detail right for a CRM integration, we typically engage with 2 or 3 clients to understand how they are using the CRM and see example live data. Otherwise we are guessing, for example, what a tenancy status might be when a tenant has signed the agreement for a new tenancy. 
How do we go about this?

**Comment by steves99** [comment]
Hi Ash, I'm just completing the app details prior to submitting for review, but the Description I'm adding won't save. This looks like it is a blocker to submitting for review. Can you please advise if this is a bug?

**Comment by AshDeeming** [comment]
Hi @steves99 
Could you confirm the app name & also the description (feel free to send to: sinfo@reapitfoundations.zendesk.com, if preferred)
