### ISSUE TITLE
Incorrect email template following developer invite 

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#9896]
**Issue:** Temporary password is not using the correct email template: 

**Steps to replicate:**
Invite New Developer (who doesn't have and RC account) 
Accept Invitation
Observe email content 

**On Dev:** 
![image](https://github.com/reapit/foundations/assets/52408607/b31cc2bb-6d52-4326-81b1-a4280ecdd41c)

**On Prod:** 
![image](https://github.com/reapit/foundations/assets/52408607/74d675e3-ed7b-4b0a-84bd-b4bbb54a84eb)

**Specification**
- Update Cognito stack template to include the custom mailer trigger. This occurred because we pushed out an update to the stack that introduced a new trigger (post auth) and subsequently binned the custom mailer trigger

**Comment by plittlewood-rpt** [comment]
@HollyJoyPhillips is this what I sorted out last week? I can't remember

**Comment by HollyJoyPhillips** [comment]
We did but now I'm not getting the email at all. @joshbalfour or @RWilcox-Reapit would you mind taking a look please?

**Comment by HollyJoyPhillips** [comment]
Resolved :)

**Comment by plittlewood-rpt** [comment]
@RWilcox-Reapit is there a PR up for this (I may have missed it but I'll have got it wrong in the stack somewhere)
