### ISSUE TITLE
Savills - appointment date filtering issue

### ISSUE THREAD

**Issue by BenRussell23** [reapit/foundations#9898]
**Describe the bug**
When retrieving appointments (MIF, PTC Pre Tenancy Check, PI Property Inspections) we are using the 'recurring' property and 'recurrence' objects and then filtering using the created and modified dates, however, the created and modified date filters are being ignored thus resulting in an excessive number of appointments being returned, e.g. 1700+
We are trying to retrieve appointments via the API for MIF, PTC and PI with a created date and modified date of the 1st October 2023 plus 7 days in the Savills Reapit UAT environment. Once we have approved the results with Savills in the Savills UAT environment we will then need this issue resolved in the Savills Reapit Live environment

API calls
Below are the details of the reequest and attached are the two json files:
1. created_date_reapit.json.docx
2. start_date.json.docx

------------------------------------------------------------
filter by created date september 30
Request:
curl --location 'https://platform.reapit.cloud/appointments/?typeId=PI&typeId=PT&typeId=MF&createdFrom=2023-09-30T00%3A30%3A34Z' \
--header 'Accept: application/json' \
--header 'reapit-customer: SAU-GUKL' \
--header 'api-version: 2020-01-31' \

Response: created_date_reapit.json
--------------------------------------------------------------
filter by start date september 30
Request:
curl --location 'https://platform.reapit.cloud/appointments/?start=2023-09-30T00%3A30%3A02Z&typeId=PI&typeId=PT&typeId=MF' \
--header 'Accept: application/json' \
--header 'reapit-customer: SAU-GUKL' \
--header 'api-version: 2020-01-31' \

Response: start_date.json

----------------------------------------------------------------
[start_date.json.docx](https://github.com/reapit/foundations/files/12803272/start_date.json.docx)

[created_date_reapit.json.docx](https://github.com/reapit/foundations/files/12803268/created_date_reapit.json.docx)

**Comment by RLAV1** [comment]
Hi Team, I am being chased by Savills and Kaptur for an update on this ticket - can we confirm when this will be reviewed please and the work scheduled? 
@AshDeeming FYI

**Comment by MatthewGoddard** [comment]
@RLAV1 I'll give Ben a call shortly

**Comment by plittlewood-rpt** [comment]
@MatthewGoddard  can this be closed based on the email thread thats been going on?

**Comment by RLAV1** [comment]
Hey @plittlewood-rpt given the latest comms i expect this one can be closed - i am just waiting on confirmation from the team at Savills and will update you by the end of today :)

**Comment by plittlewood-rpt** [comment]
@RLAV1 can this be closed? Thanks

**Comment by MatthewGoddard** [comment]
@plittlewood-rpt Please close this one down
