### ISSUE TITLE
As a ‘Client’, I want to use my existing email address to also register as a ‘Developer’ so that I can use the same email address

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#99]
Given that I am a ‘Client’, when I want to either login as a ‘Developer’, I need to register. Currently, we throw a 'client id does not exist in state error' and show a 404 message.

**Task**: 

- Do not throw or log the error in Sentry anymore. Instead, show a modal on the current page saying "You are not currently registered as a Reapit Developer, if you would like to register please visit [our registration page](https://dev.marketplace.reapit.com/register)".
- The footer should contain three buttons, "Register, Marketplace, and Logout" redirecting to the respective routes.

**Comment by tanphamhaiduong** [comment]
Assign to @nphivu414 because it relate to his ticket
