### ISSUE TITLE
Fee Split - Different Negotiator, Different Branches

### ISSUE THREAD

**Issue by matt-austin-andrews** [reapit/foundations#9900]
Hi there,

I notice a property doesn't reflect the fee split.

Here's the example:

**Screenshot remove due to PII**

The fee is split by different negotiators, different branches and it shows null at Snowflake.

**Screenshot remove due to PII**
When I view another property that has the same situation(different negotiators, different branches), the fee display correctly at snowflake. However, why there's duplicate row for negotiator Alex White? I join PROPERTIES and NEGOTIATORS table but it shouldn't impact the result, it should be 2 rows only.

**Screenshot remove due to PII**

**Screenshot remove due to PII**
What's the reason? or any bug needs to be fixed?

Thanks,
Jessie

**Specification**
- Reach out to customer to get examples
- Analyse analytics schema generation routine to unpick whats going on here

**Comment by matt-austin-andrews** [comment]
Hi there,

Just want to know the latest status. Do you know the reason of the bugs and will it be fixed at the next few weeks?

The reason is, our users keen on knowing the fee split for quarterly awards so it will be great to know the expected time of solving bugs.

Many thanks,
Jessie

**Comment by plittlewood-rpt** [comment]
Hi @matt-austin-andrews this will be picked up in line with our normal [Development Processes](https://foundations-documentation.reapit.cloud/dev-requests). Bugs are prioritised over requests so it shouldn't be too long before we get to it. IN addition, I have had to remove the screenshots you added to this item as they contained PII. PLease can you email them over to sinfo@reapitfoundations.zendesk.com with the ticket id (9900) in the subject line? Thanks

**Comment by matt-austin-andrews** [comment]
Thank you Pete, i just send the screenshot to the email.

**Comment by plittlewood-rpt** [comment]
@matt-austin-andrews I have sent you a response on Zendesk. Many thanks

**Comment by plittlewood-rpt** [comment]
Hi @matt-austin-andrews 
 
I think I might know what's going on here. If you check that property this morning in the PROPERTY_SALES_EARNED_FEES view you'll see the data is there and correct. This view only gets populated when a property completes. As you'll see from AgencyCloud, that's happened today (about an hour ago in fact!). The logic in the analytics schema is such that the fees aren't 'earned' until the property actually completes. 
 
Does this make sense and if so does it resolve the problem here?

**Comment by plittlewood-rpt** [comment]
Closed as per Zendesk
