### ISSUE TITLE
Expose the Property Checklist End Points 

### ISSUE THREAD

**Issue by tarasparrow** [reapit/foundations#9901]
As discussed with Holly Phillips: 

Connells Countrywide would like to start utilising our Custom Property Checklist. Please can we expose the endpoint for their API feed. Below is a link to the dev work we did: https://reapit.atlassian.net/browse/PBI-3949

Please can you let me know when this has been completed so i can confirm with client. 

Thanks

**Comment by plittlewood-rpt** [comment]
This will need splitting up into a milestone that includes deep dive, spec tickets, implementation tickets. PL to log milestone

**Comment by plittlewood-rpt** [comment]
Milestone logged. Please track the milestone items
