### ISSUE TITLE
Expected_Date filed is null in the sales_pipeline_fees table 

### ISSUE THREAD

**Issue by SairamKDXFT** [reapit/foundations#9906]
Hi Team, 

we are seeing null values for the 'Expected_Date' field in the Snowflake table 'Property_Sales_Earned_Fees'  .

can you fix this at earliest possible.

<img width="401" alt="image" src="https://github.com/reapit/foundations/assets/145762206/17227574-a3a0-45df-a2bd-91548785ab7f">

**Comment by plittlewood-rpt** [comment]
Hi @SairamKDXFT the Expected_Date is populated using the Completion Date stored against the property as that's when the fee is expected from the vendor. I've checked some of the examples and this is behaving as expected, so possibly just a misunderstanding here of how that field is populated. Thanks

**Comment by plittlewood-rpt** [comment]
Extract from the documentation, [available here](https://reapit-analytics-schema.prod.paas.reapit.cloud/#/)

![image](https://github.com/reapit/foundations/assets/30798627/5ee77189-ba9f-48a1-913e-58c10a0078e5)
