### ISSUE TITLE
Webhooks 

### ISSUE THREAD

**Issue by muuvo** [reapit/foundations#9910]
Hi, 

Can we have some help with being more efficient with Webhooks? 

We took a small amount of data consisting of 120 tenancies and 400 landlords and properties, but there were over 2400 webhook calls. What do we need to do to be more efficient with webhooks? See attachment. 

![image](https://github.com/reapit/foundations/assets/147054025/6ecc406a-e668-4200-a007-5d2758937538)

**Comment by AshDeeming** [comment]
Hi @muuvo 
Could you advise how you are using webhooks - i.e. are these via standard topics or via the event filters based on the JSON ?(https://foundations-documentation.reapit.cloud/api/webhooks#building-event-filters)

**Comment by muuvo** [comment]
Developer note -

Jamie Parks We are already define events under webhooks, that will call only when tenancy modified, please find the below attachment

[image0.jpeg]

<https://proptimisetechnology.visualstudio.com/51e29dc5-bdf7-4aa9-bf54-52a2d81db5f6/_apis/wit/attachments/38f24600-c01b-4412-aab8-a353ff40e72f?fileName=image.png>


Kind regards,
JP

Jamie Parks
Director


On 5 Oct 2023, at 13:20, Ash ***@***.***> wrote:

﻿

Hi @muuvo<https://github.com/muuvo>
Could you advise how you are using webhooks - i.e. are these via standard topics or via the event filters based on the JSON ?(https://foundations-documentation.reapit.cloud/api/webhooks#building-event-filters)

**Comment by AshDeeming** [comment]
Hi @muuvo 
Unfortunately I'm unable to see the image or request. 

Please could you send any additional details to; foundationssupport@reapit.com  subject #9910

Thanks in advance,

**Comment by muuvo** [comment]
Attachment sent.

Kind regards,
JP

Jamie Parks
Director


On 5 Oct 2023, at 13:52, Ash ***@***.***> wrote:

﻿

Hi @muuvo<https://github.com/muuvo>
Unfortunately I'm unable to see the image or request.

Please could you send any additional details to; ***@***.******@***.***> subject #9910<https://github.com/reapit/foundations/issues/9910>

Thanks in advance,

**Comment by ProptimiseSupport** [comment]
Hi 

Webook call request number is too high, below are setting we are using 

Subscription topics -> tenancy modified
Subscription customers -> Paramount
Ignore where only the etag has been modified -> true

Please check below screenshot 

<img width="635" alt="38f24600-c01b-4412-aab8-a353ff40e72f" src="https://github.com/reapit/foundations/assets/72204384/7091f621-74f2-4f35-991a-7484a24f85c2">

Could you please let us know is there any other setting needs to update.

**Comment by AshDeeming** [comment]
Thanks both,
As per the above screen shot, you appear to currently be using the standard subscription webhook topics. 

Please see the documentation below which details the schema which can be used to validate the content of an event from our customer's systems which will only be sent to your endpoint in the event that validation is successful.
https://foundations-documentation.reapit.cloud/api/webhooks#building-event-filters

**Comment by ProptimiseSupport** [comment]
Is json schema validation still in beta testing and not generally available?

Is standard subscription not enough for correct request?

**Comment by AshDeeming** [comment]
Hi @ProptimiseSupport 
Although the filtering is still technically in beta, it is available to use 

The standard webhook will provide the information required however the filtering can be used to lower the number of webhook calls where the more granular detail may fire less.

**Comment by muuvo** [comment]
@ProptimiseSupport, we need to improve the webhook count significantly. With only 120 tenancies and 3 other end points,2400 webhook calls is far too much.

**Comment by plittlewood-rpt** [comment]
Webhooks will be generated whenever anyone in branch makes a change to the records in the CRM - we have no control over what the end users do to their data. If you want to reduce the number of hooks you receive, you will need to consider using the event filters as mentioned by Ash above.

**Comment by muuvo** [comment]
Do we need to use the "modified" endpoint to only receive notifications about changes to move-in dates and modified meter readings? It appears that we are receiving many irrelevant updates that are using up our webhook usage. Perhaps we should consider using the "create" endpoint to fetch information about "arranging" and "finishing" tenancies instead and add events for move-in date and meter readings?

**Comment by HollyJoyPhillips** [comment]
Hi @muuvo, apologies for the delay in replying. Did you manage to resolve your issue or do you still need assistance?

**Comment by muuvo** [comment]
Hello,
We have not updated the integration and would still like assistance with reducing the number of webhooks that we are receiving.

**Comment by HollyJoyPhillips** [comment]
Hi @muuvo thanks for the reply. Have you looked into building specific webhook event filters? As from the comments above, you will currently receive all properties modified. If you want granular control you'll need to consider filtering on your side. Alternately, if you don't need the data in real time, you can switch to polling the data which gives you greater control on the data you require.

**Comment by muuvo** [comment]
Hello Holly,

I noticed that we are calling a single specific webhook. The webhook in question is the GET meter readings webhook. I suspect that we might be calling it every time any tenancy is updated. However, we only need to call it when there is an addition or update to the meter reading fields.

To put things in perspective, we have 122 tenancies but have made 1414 calls to the webhook. We need to make sure that we are only calling the webhook when necessary. Can you advise?

Thank you.

***@***.***

[pic]
Jamie Parks
[email]  03301229165<Tel:03301229165>   [web]   muuvo.co.uk<https://muuvo.co.uk>
[web]  Mill View House, Southampton, SO31 8BZ
Book some time with me here - Jump In My Diary<https://calendly.com/jp-muuvo/chit-chat>
[logo]<https://www.facebook.com/muuvo.uk>  [logo] <https://www.instagram.com/muuvo.uk>   [logo] <https://www.linkedin.com/company/muuvo/>

Please be advised that this electronic mail, including any accompanying attachments, is intended solely for the individual or entity named in the address field and may contain confidential and legally protected information subject to copyright. We have taken reasonable measures to mitigate the risk of computer viruses, but we cannot be held liable for any damage from its transmission. If you are not the intended recipient, please refrain from reviewing, copying, or forwarding this email. Instead, we kindly request that you promptly notify us by responding to this email and delete it from your system. I appreciate your cooperation in this matter.
[https://i.postimg.cc/KxMW86Kj/Untitled-1.png]

**Comment by plittlewood-rpt** [comment]
Hi @muuvo I would recommend having a read through [this area of the documentation](https://foundations-documentation.reapit.cloud/api/webhooks#building-event-filters) which talks about building event filters. This will allow you to target only changes to the meter readings. Many thanks

**Comment by muuvo** [comment]
Hi Pete,

My developer has come back with the below.


Reapit Integration

@Jamie Parks<file:///var/mobile/tmp/com.apple.email.maild/EMContentRepresentation/com.apple.mobilemail/073ABA37-B21E-4200-97A0-CE4DAB29976A/51A13595-184A-4F3A-B3CA-A781AC06FF0A.html#> No option found to add event filter for webhooks. I found below statement

This is an advanced feature that allows you to build on top of the default topic availability and target specific events. Please note that this is still in beta testing and not generally available

That is currently not live. Could you please confirm with the team

Kind regards,
JP

Jamie Parks
Director


On 1 Mar 2024, at 15:03, Pete Littlewood ***@***.***> wrote:

﻿

Hi @muuvo<https://github.com/muuvo> I would recommend having a read through this area of the documentation<https://foundations-documentation.reapit.cloud/api/webhooks#building-event-filters> which talks about building event filters. This will allow you to target only changes to the meter readings. Many thanks

**Comment by plittlewood-rpt** [comment]
Apologies thanks for highlighting this - would you be interested in trialling this feature? The endpoints are just hidden at the moment whilst we gather more feedback from consumers about it.

**Comment by muuvo** [comment]
Yeah sure, more than happy.

Kind regards,
JP

Jamie Parks
Director


On 1 Mar 2024, at 17:19, Pete Littlewood ***@***.***> wrote:

﻿

Apologies thanks for highlighting this - would you be interested in trialling this feature? The endpoints are just hidden at the moment whilst we gather more feedback from consumers about it.

**Comment by muuvo** [comment]
Hi @plittlewood-rpt Just seeing where we are with this one?

**Comment by plittlewood-rpt** [comment]
Hi @muuvo apologies - I will endeavour to get this information over to you via email today.

**Comment by plittlewood-rpt** [comment]
Hi @muuvo I've just sent you the info via email. Many thanks

**Comment by muuvo** [comment]
Thanks very much @plittlewood-rpt and over to you @ProptimiseSupport

**Comment by muuvo** [comment]
@plittlewood-rpt We are only using one webhook for meter readings. Am I right in thinking this is the one we need to use to trigger the webhook if a meter reading field is updated? 

  },
          {
            "in": "query",
            "name": "active",
            "description": "Only return webhook subscriptions where the `active` field matches the value provided",
            "type": "boolean"
          }
@ProptimiseSupport

**Comment by plittlewood-rpt** [comment]
Hi @muuvo you will need to create webhook event filters using the POST /{id}/filters endpoint in conjunction with the documentation linked above and in the email I've sent over. Many thanks

**Comment by plittlewood-rpt** [comment]
I will close this item down as assistance has been provided and there's been no further correspondence. Please open a new item if you need any further help. Thanks
