### ISSUE TITLE
Property status showing: "marketingMode": "Not set" when it shouldn't

### ISSUE THREAD

**Issue by tpjsupport** [reapit/foundations#9923]
Hi, property ID CTL230136 for Payne-cov/JOP is showing with no photos and the status is showing: "marketingMode": "Not set" our programmer has mentioned that this is a problem at your end. Please could somebody take a look? Thanks

**Comment by plittlewood-rpt** [comment]
HI @tpjsupport this is related to a known bug in AgencyCloud which is in the process of being resolved. I have corrected the data now so you should get the correct marketingMode value back. Thanks
