### ISSUE TITLE
Lettings Negotiator Activity Snapshot not available in data WH

### ISSUE THREAD

**Issue by holdenpip** [reapit/foundations#9926]
Lettings Negotiator Activity Snapshot Report is not available in our data warehouse - Charters Estate Agents. Can this please be added
Thanks

**Comment by plittlewood-rpt** [comment]
Hi @holdenpip please can you use the Refresh Share button in the Data Warehouse app? There was an issue quite a while back with this not being provisioned properly. Let me know if this resolves your issue. Thanks
