### ISSUE TITLE
Question on API versions

### ISSUE THREAD

**Issue by ClaireKOCHER** [reapit/foundations#9929]
Hello,

We are creating this request following Mr Reagan Taylor's suggestion, relating to request "Reapit fields to feed to Barnes London Website - Reference RSD-250375" 

We have recently reviewed the API documentation at https://connect.reapit.cloud/ and noticed that the "councilTax" field is listed as available. However, when executing the corresponding request at the URL https://webservice.reapit.net/bai/rest/properties/rps_bai-BAI230086, we noticed that no data related to this field is returned in the results.
This observation has raised questions within our development team, especially regarding the current version of the API we are presently using. It appears that the new version of the API is accessible via the URL https://plateform.reapit.cloud// , but we would appreciate confirmation from you on this matter.
Could you please provide clarification on the situation and let us know if we should transition to the new version of the API to be able to access data related to the "councilTax" field and other such fields?
 
We thank you in advance for your assistance and remain at your disposal for any further information.
Sincerely,
Claire

**Comment by AshDeeming** [comment]
Hi @ClaireKOCHER 

Please see the relevant endpoint(s) within the swagger docs: https://developers.reapit.cloud/swagger

If the required fields are custom, please see the configuration endpoint 
If the fields relate to semi-structured data, please confirm, with screenshots, which AgencyCloud fields are required?

**Comment by plittlewood-rpt** [comment]
Hi @ClaireKOCHER the URL you have provided above relates to our legacy REST API, and not the Foundations Platform which is what agents should be using (or at least planning to migrate to). Ash is correct above that the Swagger documentation at the link he has supplied is the latest version of our API tooling.
