### ISSUE TITLE
Unable to see the floor plan data for this property 

### ISSUE THREAD

**Issue by supportagentmedium** [reapit/foundations#9930]
Hi Team,

Client is using reapit software for their property feed. Unable to see the floor plan detail for this property but the client have uploaded the same over the portal.

https://staging-gascoines.propertysmash.com/for-sale/southwellnottinghamshire/manor-drive/5-bedroom-for-sale-in-manor-drive-southwellnottinghamshire/526858

![image](https://github.com/reapit/foundations/assets/130666121/8472a6bc-665d-455e-adba-dcc49938cd1e)

**Comment by Steve-Clark-Reapit** [comment]
Could someone look at this one as a priority please. The client's website go-live is held up because some items are missing, including floorplans. (Sorry, I know it has just come in but we are signing the client out of ELS and the website still isn't live)

**Comment by plittlewood-rpt** [comment]
I am unable to access that link and cannot see the Reapit property ID. Please can this be provided? Thanks

**Comment by supportagentmedium** [comment]
Please find the reapit property ID- SOU230265

**Comment by plittlewood-rpt** [comment]
Hi @supportagentmedium the floorplan is being returned by our property images service and the URL is working and serving the media asset so it doesn't look like a problem with our API. The website developers would need to investigate the missing floorplan. Thanks
