### ISSUE TITLE
Cartography tool codebase

### ISSUE THREAD

**Issue by Reapit-TanMatthews** [reapit/foundations#9943]
**Summary** 
Decommissioning of Cartography tool, 2023 Q4.

**Details**
Review of internal cartography tool codebase required. 
Potential updates to AC SetupAreas screen made leading to self-serve functionality. Alternatively code review may indicate new internal app.
(Internal email with additional information sent).

**Comment by Reapit-TanMatthews** [comment]
Hi Pete,

As the Cart tool is written in PHP, AC developers with PHP knowledge is limited. The review of the codebase to distinguish if hierarchies used are reusable is integral to approaching potential partners and AC development.
I’ve spoken with Neil and Paul. Is there another channel or process I should go through?
Thanks

**Comment by AshDeeming** [comment]
Internal discussion in progress
