### ISSUE TITLE
2x Questions around API Endpoints

### ISSUE THREAD

**Issue by adamcollison85** [reapit/foundations#9963]
Can you confirm the following.

1) Will journal entries pull in all items in the activity feed? Or will it just pull in journal entry content from the activity feed? Is the Journal and Activity feed the same thing.

2) With properties sellingStatus = Valuation and lettingStatus = Valuation is there a way to find out the date of the Market Appraisal? How do we tie the property with the actual valuation? We need to pull in the valuation date but not sure how to accurately do this? 

Thanks.

**Comment by AshDeeming** [comment]
Hi @adamcollison85 

1) Journal entries go into the associated activity feed 
2) If I've understood correctly, the valuation date within the properties endpoint will provide this;
![image](https://github.com/reapit/foundations/assets/61687775/e76c3230-3415-414f-b87c-d86f9c076fc2)
