### ISSUE TITLE
YConfDate not being set via the API

### ISSUE THREAD

**Issue by danielalmeidaconnellsgroup** [reapit/foundations#9965]
Scenario:

User goes to book an appointment via Agency Cloud and clicks All Confirmed.

This sets all Confirmed but also sets yConfDate date in the Diary extra table.

We use the API to book an appointment, All Confirmed is set but... yConfDate is not there.

Two questions:

1. What field in Reapit Database does All Confirmed on the diary map to
2. Is it possible to set yConfDate  for consistency.

**Specification**
- Project: Reapit.Services.Appointments
- Add new nullable DateTime property to handle diary.extra.yConfDate (do not expose this in the model - no real use right now)
- When handling write scenarios, update the handling to set the date if all parties are confirmed (use the AllConfirmed() method which is built to take attending parties into account). If any of the parties subsequently unconfirm their attendance, this field should be cleared

**Comment by plittlewood-rpt** [comment]
Hi @danielalmeidaconnellsgroup . All Confirmed maps to "diary.confirmed" in the database. This gets set based on the parties attached to the appointment confirming their attendance, and this happens dynamically as not all appointments have three parties attending (ie you'll only have a negotiator and property attached to a Valuation, but you'd have an additional attendee for a viewing etc).

Re the confirmation date, we'll check this out and plug that functionality gap as soon as we can
