### ISSUE TITLE
Include in Pipeline field showing 'No' for all records in Data Warehouse (Offers view)

### ISSUE THREAD

**Issue by ktanalyst** [reapit/foundations#9967]
**Describe the bug**
We recently enabled the 'Include in Pipeline' field in the offers section of AgencyCloud. The box is unticked by default, so we ticked the box on all offers which should be included in the pipeline so we can report on this using Data Warehouse. It's now been a few days since this exercise, but all records in the offers view are showing Include In Pipeline = 'No'. 

**To Reproduce**
Run Snowflake SQL query on the offers view to count records by include_in_pipeline:

`SELECT include_in_pipeline, count(id)
from offers
GROUP BY include_in_pipeline`

For us, all values sit against 'No'.

**Expected behaviour**
When the Include in Pipeline field in the offers section of AgenyCloud is ticked, the Include in Pipeline field in Data Warehouse should say 'Yes' instead of 'No'.

**Device (please complete the following information for web issues):**
 - Device: PC

**Specification**
- Review analytics schema OFFERS model to determine why this field is not being set correctly. Customer id concerned is KLR

**Comment by plittlewood-rpt** [comment]
Hi @ktanalyst this issue is now resolved. Thanks
