### ISSUE TITLE
Repeated 504 response from the Reapit API

### ISSUE THREAD

**Issue by adamcollison85** [reapit/foundations#9968]
We have noticed an increasing number of response code 504 from the API.

Have you noticed any logs your end?

We are attempting sync data and when we hit this response it's causing us issues. 

GuzzleHttp(Exception\ServerException: Server error: "GET https://platform.reapit.cloud/properties?
pageNumber=22&pageSize=100&embed=vendor resulted in a '504 Gateway Timeout' response:

**Comment by adamcollison85** [comment]
FYI literally just had another today

Server error: GET https://platform.reapit.cloud/offices?pageNumber=1&pageSize=100 resulted in a 504 Gateway Timeout response:
{"message": "Endpoint request timed out"}
Today at 3:03 PM

**Comment by adamjamesevans** [comment]
We are also getting this error with "Endpoint request timed out" with other clients.

As a side note, Is there an API status page we can use to check @Reapit support?

**Comment by MarcinuB** [comment]
I will add to it - I seem to experiencing similar issues with propertyImages endpoint on top of some issues when calling /properties/{propertyCode} endpoint

**Comment by robchett** [comment]
This has also been a problem for us too. Some endpoints have been quick (/properties, /contacts) but anything to do with /applicants and /appointments is timing out.
Requesting the same data a minute after is returning rapidly so it looks like it is going into cache eventually. https://github.com/reapit/foundations/issues/9968
Client IDs are YOM/RER

**Comment by adamcollison85** [comment]
Not sure if its related but we are also seeing some 401 responses also...

Client error: `GET https://platform.reapit.cloud/properties?pageNumber=30&pageSize=100&embed=vendor` resulted in a `401 Unauthorized` response:
{ "statusCode": 401, "dateTime": "2023-10-16T16:24:28Z", "description": "The request cannot be fulfilled because it lack (truncated...)

**Comment by plittlewood-rpt** [comment]
Good morning - please see status.reapit.com for updates on this issue - here you can also subscribe to event notifications which you may find useful in the future. 

I can confirm that Platform stability returned to normal at around 18:00UTC. Monitoring has been increased whilst we fully understand the root cause and we are working with our hosting partners to do a full investigation into the outage yesterday.

**Comment by adamcollison85** [comment]
Thanks for the update @plittlewood-rpt
