### ISSUE TITLE
Applicants Endpoint - Include marketing consent for contacts

### ISSUE THREAD

**Issue by metaljoe** [reapit/foundations#9974]
I'm currently working on an integration with applicant data. As part of the work, it's come to my attention that the marketing consent field is missing from the contact details embedded in the applicant data (via the related field). Although it can apparently be retrieved separately, via the contacts endpoint, this would involve additional calls and more complexity in the integration. Other fields are present, so not sure why this specific field has been missed out? 

Please could we add the missing marketing consent field to the contact information returned for applicant data?

Thanks in advance!

**Specification**
- Update any services that have a related entity collection to add a `marketingConsent` property that exposes the same value that is found in the contactModel returned from GET /contacts. This should also work for companies though note the behaviour is slightly different on a company record. Check the companies API for how we decide whether to display notAsked or granted.

Reapit.Services.Applicants
Reapit.Services.Offers
Reapit.Services.Vendors

Check for other services

**Comment by plittlewood-rpt** [comment]
Hi @RWilcox-Reapit I've tagged you onto this just whilst we wait for internal feedback.
