### ISSUE TITLE
MyHome.ie Foundations request for Energy Rating data for Power & Walsh (PAW)

### ISSUE THREAD

**Issue by colearymyhome** [reapit/foundations#9979]
Apps in question:
MyHomeReapitAPI Live (App ID 5178f1a0-21e5-4371-a3f5-6316d788c327)
MyHomeReapitAPI (App ID e1a117c1-0d87-4097-acff-ac89edff0e3e)

Customer information: Reapit Office Code PAW

The name of every field you need surfaced (if known)
[https://platform.reapit.cloud/properties/{PropertyID}?extrasField=pBERRating&extrasField=pBERNumber&extrasField=pBERExempt&extrasField=pEPI&embed=negotiator](https://platform.reapit.cloud/properties/%7BPropertyID%7D?extrasField=pBERRating&extrasField=pBERNumber&extrasField=pBERExempt&extrasField=pEPI&embed=negotiator)
pBERRating
pBERNumber
pBERExempt
pEPI

A short use case as to why you require this data
To get Energy Rating information which is required by law to display in Ireland

**Comment by colearymyhome** [comment]
Same query as this: https://github.com/reapit/foundations/issues/9773

**Comment by AshDeeming** [comment]
Hi @colearymyhome 

These have now been added, see below request exmaple;

GET https://platform.reapit.cloud/properties?extrasField=pBERRating

pBERRating
pBERNumber
pBERExempt
pEPI

Please note that the fields will only be returned in the property data if they are explicitly set against the property.
