### ISSUE TITLE
Adding marketin consent into the feed

### ISSUE THREAD

**Issue by EvgeniyBelchev** [reapit/foundations#9985]
Hi,

As advised by the Reapit Service Desk, we are requesting that you include the marketing consent in the feed we are receiving.

We want to receive this information in the feed to be able to add those who consent to receive marketing emails into our Email Campaign Tool.

Our app name is: rue-living-integration

Please let us know if this is possible and when this can be sorted.

Kind regards,
Evgeniy

**Comment by plittlewood-rpt** [comment]
Hi @EvgeniyBelchev - marketing consent is already available when calling https://platform.reapit.cloud/contacts. Please can you advise if there's a reason this doesn't fit your use case?
