### ISSUE TITLE
Reapit Emails sent without a link to the property

### ISSUE THREAD

**Issue by plasticboxuk** [reapit/foundations#9986]
Emails are sent from Reapit, such as the property match emails, but don't link through to the properties on the website.

Reapit have directed me here regarding this.

What's the process for getting the URL of a property to send in a Reapit email?

The website is populated with data from Reapit using a custom app we created in Foundations to provide us with the property data in XML format.

**Comment by plittlewood-rpt** [comment]
HI @plasticboxuk 
It looks like there may have been some confusion about which department you need to speak to so let me help you with that. If you are talking about emails sent from AgencyCloud itself (our CRM), this would be handled by our main service desk. If you are talking about emails generated by an app you have created, then you are responsible as the app developer to liaise with the appropriate web company to understand the structure of the property URLs that you need to add to the email templates.

Can you provide a bit more information so I can make sure you get through to the right person?

Thnaks

**Comment by plasticboxuk** [comment]
Thanks, yes the emails are sent by AgencyCloud.  Our App does not send emails.

The help desk response was from [jira@reapit.atlassian.net](mailto:jira@reapit.atlassian.net)>

They originally asked how we were populating the website - the question was:

Are you able to speak to your internal website team and ask them if they run the website via Webservice or Foundations, please?

When we confirmed Foundations, they responded with:

I hope you are well.
As the company use Foundation, you will need to ask your website support team to raise a ticket to our Foundations team via GitHub about the property link. If they can use https://github.com/reapit/foundations/issues/new/choose, they will be able to help you further.
The reason we can’t investigate this ticket further is because our desk doesn't support Foundation.

**Comment by plittlewood-rpt** [comment]
Thank you for coming back to me and I'm sorry for the mix up. Do you have the reference from our service team (or can you let me know which customer you are working on behalf of and I should be able to find it)

**Comment by plasticboxuk** [comment]
Sure, it's RSD-255318

**Comment by plittlewood-rpt** [comment]
Thanks @plasticboxuk - I've reached out to the team responsible for this who should be in touch with you shortly via that support ticket.
