### ISSUE TITLE
Unable to move position of 'Featured Apps' 

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#9989]
**Issue:** Unable to move position of featured apps in the AppMarket CMS: 

Currently the featured apps are listed as: 

![image](https://github.com/reapit/foundations/assets/52408607/34f46280-8920-460b-bf23-4d50478fab39)

However, when trying to move 'New Apps' to the top position it isn't responding. No errors are returned. 

**To replicate:** 
Access CMS
Attempt to move 'New Apps' to the top position

**Comment by bashleigh** [comment]
Unabel to replicate locally
