### ISSUE TITLE
spike: Update configuration injection for service specific/common settings to use DynamoDb

### ISSUE THREAD

**Issue by plittlewood-rpt** [reapit/foundations#9999]
**Background context**
To remove our reliance on SSM which is struggling to scale, we should refactor the methods in the identity manager package responsible for injecting common and service specific configuration options to use DynamoDb.

**Specification**
- Setup new DynamoDb table (new stack) with the following structure:
  - Service (PartitionKey)
  - Configuration - will be a single Json document containing all parameters for the service
- The idea here is that there will be a single row per service, and a single row for common items
 
- Project: Reapit.Packages.PlatformIdentityManager
- Refactor `/SSM/AddCommonConfigurationsExtension` and `/SSM/AddServiceConfigurationExtension` classes to get their data from DynamoDb. Remember there will need to be an appropriate mechanism to separate the Json document into IConfiguration
- Roll out to one or two services first (suggest doing something like contacts and documents, as the latter has service specific configuration). The mechanism should unwrap the json documents into IConfiguration because this is injected all over the place. To move to a memory cache would mean we can't just do a package update to roll this out
- There may be better ways to do this (ie Redis cache which is shared between services and a separate Lambda to periodically refresh the cache). Consider this also
- We should still aim to move to a single parameter (or row) per service to make the Platform configuration more maintainable

**Comment by RWilcox-Reapit** [comment]
This has been implemented in identityChecks.
Ticket to sweep through serverless services and apply this update raise: #10095 10095
